
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oj = {'a': ['ojang-dong',
       'ojarumaru',
       'ojacastro',
       'ojak@ran',
       'ojaqabad',
       'ojakkala',
       'ojaaarse',
       'ojancanu',
       'ojanpera',
       'ojapali',
       'ojakula',
       'ojapere',
       'ojarud',
       'ojanen',
       'ojasoo',
       'ojamaa',
       'ojalgo',
       'ojars',
       'ojala',
       'ojass',
       'ojaq',
       'ojak',
       'ojan',
       'oja'],
 'c': ['ojcowizna', 'ojcewo', 'ojcow', 'ojc'],
 'd': ['ojdanic', 'ojdula', 'ojd'],
 'e': ['ojeong-gu',
       'ojecunca',
       'ojerzyce',
       'ojeccasa',
       'ojersjo',
       'ojebyn',
       'ojeda',
       'ojeh',
       'ojen',
       'oje'],
 'h': ['ojha'],
 'i': ['ojingeo-chae-bokkeum',
       'ojiya-chijimi',
       'ojingeo-jeot',
       'oji-cree',
       'ojiambo',
       'ojinaga',
       'ojibwe',
       'ojiji',
       'ojiro',
       'ojiya',
       'ojime',
       'ojili',
       'ojima',
       'ojigi',
       'oji'],
 'j': ['ojjeh'],
 'k': ['ojkovica', 'ojkroken', 'ojkanje', 'ojk'],
 'm': ['ojm'],
 'n': ['ojnowrd'],
 'o': ['ojoraptorsaurus',
       'ojoceratops',
       'ojos-albos',
       'ojopublico',
       'ojok-tong',
       'ojoyoshu',
       'ojojona',
       'ojos',
       'ojo'],
 'r': ['ojrzanow-towarzystwo', 'ojrzanowo', 'ojrzanow'],
 's': ['ojslawice', 'ojstrica', 'ojs'],
 'u': ['ojuelegba',
       'ojukokoro',
       'ojukheon',
       'ojurahu',
       'ojuelo',
       'ojuela',
       'ojuju',
       'oju'],
 'w': ['ojw']}
