
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oh = {'_': ['oh-seong',
       'oh-lch',
       'oh-ok',
       'oh!gg',
       'oh-22',
       'oh!k',
       'oh-6',
       "oh's",
       'oh8',
       'oh4'],
 'a': ['oharaeibacter',
       'ohaji/egbema',
       'ohatchecama',
       'ohavsstien',
       'ohangaron',
       'ohara-ryu',
       'ohanavan',
       'ohaeawai',
       'ohayocon',
       'ohaozara',
       'ohakvere',
       'ohangai',
       'ohaukwu',
       'ohangla',
       'ohauiti',
       'oharice',
       'ohannes',
       'ohangam',
       'ohaldre',
       'ohakuri',
       'ohajiki',
       'ohanian',
       'ohakune',
       'ohaupo',
       'ohatsu',
       'oharae',
       'ohariu',
       'ohaton',
       'ohashi',
       'ohanet',
       'ohanes',
       'ohafia',
       'ohavec',
       'ohana',
       'ohare',
       'ohaba',
       'ohama',
       'ohayo',
       'ohaus',
       'ohada',
       'oharu',
       'ohain',
       'ohara',
       'ohata',
       'ohal',
       'ohan',
       'ohau',
       'ohai',
       'ohad',
       'ohaw',
       'oha'],
 'b': ['ohbijou'],
 'c': ['ohca', 'ohcc', 'ohc'],
 'd': ['ohd'],
 'e': ['ohessaare',
       'oherville',
       'ohekatku',
       'ohepalu',
       'ohebach',
       'oheneba',
       'ohenri',
       'ohene',
       'ohel',
       'ohey',
       'ohe'],
 'f': ['ohf'],
 'g': ['ohgr', 'ohg'],
 'h': ['ohhh...alright...', 'ohhs'],
 'i': ['ohileshwara',
       'ohiohealth',
       'ohikkoshi',
       'ohinemutu',
       'ohinemuri',
       'ohioceras',
       'ohinetahi',
       'ohilimia',
       'ohiolink',
       'ohinewai',
       'ohimini',
       'ohisama',
       'ohiya',
       'ohira',
       'ohiki',
       'ohid',
       'ohio',
       'ohis',
       'ohi'],
 'l': ['ohlendorffia',
       'ohlertidion',
       'ohlenbuttel',
       'ohleriella',
       'ohlhaussen',
       'ohlendorf',
       'ohlweiler',
       'ohlenhard',
       'ohlyuvets',
       'ohlsbach',
       'ohlsdorf',
       'ohlungen',
       'ohlstadt',
       'ohleria',
       'ohlsson',
       'ohlund',
       'ohlone',
       'ohlins',
       'ohlson',
       'ohland',
       'ohlsen',
       'ohler',
       'ohlin',
       'ohly',
       'ohl'],
 'm': ['ohmecarfentanil',
       'ohmdenosaurus',
       'ohmefentanyl',
       'ohmphrey',
       'ohmmeter',
       'ohmynews',
       'ohmdenia',
       'ohmbach',
       'ohmibod',
       'ohmstal',
       'ohmwork',
       'ohmsett',
       'ohmkar',
       'ohmden',
       'ohman',
       'ohmer',
       'ohmme',
       'ohme',
       'ohms',
       'ohm'],
 'n': ['ohnsorg-theater',
       'ohnenheim',
       'ohnistany',
       'ohnesorge',
       'ohningen',
       'ohnreith',
       'ohnisov',
       'ohnstad',
       'ohnici',
       'ohnic',
       'ohno',
       'ohne',
       'ohn'],
 'o': ['ohomairangi',
       'ohongkar',
       'ohonica',
       'oholiab',
       'ohordua',
       'oholje',
       'ohoven',
       'oholot',
       'ohori',
       'ohope',
       'ohorn',
       'ohoba',
       'ohoka',
       'oho!',
       'oho'],
 'p': ['ohpen', 'ohp'],
 'q': ['ohq'],
 'r': ['ohrtbrookgraben',
       'ohridohauffenia',
       'ohrenspitzen',
       'ohrazenice',
       'ohridiidae',
       'ohrigstad',
       'ohranjyva',
       'ohrekreis',
       'ohradzany',
       "ohrbach's",
       'ohrenbach',
       'ohrrpgce',
       'ohringen',
       'ohrobec',
       'ohrdruf',
       'ohrozim',
       'ohrdorf',
       'ohrana',
       'ohrady',
       'ohrum',
       'ohrid',
       'ohra',
       'ohre',
       'ohri',
       'ohrn',
       'ohr'],
 's': ['ohshape', 'ohs'],
 't': ['ohtakari',
       'ohtuleht',
       'ohtamis',
       'ohthere',
       'ohtis',
       'ohtla',
       'ohtja',
       'ohto',
       'ohtu',
       'ohta',
       'oht'],
 'u': ['ohukabia',
       'ohukotsu',
       'ohulepa',
       'ohunka',
       'ohuus',
       'ohuka',
       'ohura',
       'ohum',
       'ohu'],
 'v': ['ohvrilaev', 'ohvida', 'ohvira'],
 'y': ['ohyda']}
