
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_qi = {'_': ["qi'an_road_station",
       'qi_county,_kaifeng',
       'qi_county,_shanxi',
       'qi_county,_hebi',
       'qi_lin_bayin',
       'qi_shu_fang',
       'qi_of_xia'],
 'a': ['qiaodong_district,_shijiazhuang',
       'qiaodong_district,_zhangjiakou',
       'qiaoxi_district,_shijiazhuang',
       'qianjiang_wulingshan_airport',
       'qiaoxi_district,_zhangjiakou',
       'qianjin_subdistrict,_wuhan',
       'qiaotou_township,_baoding',
       'qiasabad,_razavi_khorasan',
       'qianjin_district,_jiamusi',
       'qianjiang_railway_station',
       'qianchang_railway_station',
       'qiandaohu_railway_station',
       'qianying_township,_hebei',
       'qianwei_confucius_temple',
       'qianshan_railway_station',
       'qianjia_railway_station',
       'qianyao_railway_station',
       'qiaotou,_yongjia_county',
       'qiaocheng_north_station',
       'qianjiang_century_city',
       'qiawan,_nanfeng_county',
       'qianshan_national_park',
       'qianjiang_evening_news',
       'qiaocheng_east_station',
       "qiao's_grand_courtyard",
       'qianjiang_road_station',
       'qianfeng_road_station',
       'qiantang_river_bridge',
       'qiaozhong_road_tunnel',
       'qiagen_silicon_valley',
       'qiandeng_lake_station',
       'qiandao_lake_incident',
       'qianxi_county,_hebei',
       'qiaokou_road_station',
       'qiao_family_compound',
       'qiaohe_metro_station',
       'qianwan_park_station',
       'qian_hu_corporation',
       'qiang_folk_religion',
       'qianjiang_new_city',
       'qianjin_zhidai_wan',
       'qian_julie_wang',
       'qian_fu_lun'],
 'b': ['qibao_old_street'],
 'c': ['qic-united_evangelical_church', 'qicheng_road_station'],
 'd': ['qiding_railway_station',
       'qidong_railway_station',
       'qidu_railway_station',
       'qidan_guo_zhi'],
 'e': ['qieji_township,_qinghai', 'qiemo_yudu_airport'],
 'f': ['qifeng_park_station'],
 'h': ['qihua_road_station'],
 'j': ['qijia_township,_hebei',
       'qijia,_longhua_county',
       'qiji,_yanggu_county',
       'qijian_xia_tianshan',
       'qiji,_wuji_county'],
 'k': ['qikiqtani_school_operations',
       'qikiqtaruk_territorial_park',
       'qikiqtani_general_hospital'],
 'l': ['qila_saifullah_district',
       'qilianshan_road_station',
       'qila_abdullah_district',
       'qila_mubarak,_patiala',
       'qilab_rural_district',
       'qilian_metro_station',
       'qilun_square_station',
       'qila_darshan_singh',
       'qilu_evening_news',
       'qila_gujar_singh',
       'qila_sobha_singh',
       'qila_rai_pithora',
       'qila_kallar_wala',
       'qila_sattar_shah',
       'qila_mihan_singh',
       'qila_didar_singh',
       'qilla_tek_singh',
       'qila_sura_singh',
       'qila_desa_singh',
       'qila_tara_singh',
       'qila_tek_singh',
       'qila_lal_singh'],
 'm': ['qiming_venture_partners',
       'qimei_power_plant',
       'qimron_v._shanks',
       'qimat_rai_gupta'],
 'n': ['qinhuangdao-shenyang_passenger_railway',
       'qingdao-rongcheng_intercity_railway',
       'qingyuan_subdistrict,_shijiazhuang',
       'qinglongshan_ditiexiaozhen_station',
       'qinhuangdao_shanhaiguan_airport',
       'qingdao_agricultural_university',
       'qingdao-jinan_passenger_railway',
       'qingyang_subdistrict,_jinjiang',
       'qingchengshan_railway_station',
       'qingnian_subdistrict,_bengbu',
       'qinglongqiao_railway_station',
       'qinhuangdao_beidaihe_airport',
       'qingdao_university_gymnasium',
       'qingzhoushi_railway_station',
       'qinhuangdao_railway_station',
       'qingdao-jinan_through_train',
       'qing_structural_regulations',
       'qinghe_subdistrict,_beijing',
       'qinghuayuan_railway_station',
       'qinghai_provincial_library',
       'qingshui_township,_qinghai',
       'qingzhen_township,_qinghai',
       'qingyuan_district,_baoding',
       'qingdao_symphony_orchestra',
       'qinghai_huading_industrial',
       'qingsheng_railway_station',
       'qingcheng_railway_station',
       'qingdao_binhai_university',
       'qingshan_district,_baotou',
       'qingdao_haili_helicopters',
       'qinghai_normal_university',
       'qingdao_technical_college',
       'qingyunpu_railway_station',
       'qingyuan_county,_zhejiang',
       'qinhuangdao_wildlife_park',
       "qingpu_district,_huai'an",
       'qinglong_township,_tibet',
       'qingyuan_railway_station',
       'qinglong_county,_guizhou',
       'qincheng,_nanfeng_county',
       'qingshui_railway_station',
       'qingzhou_longxing_temple',
       "qinghe_district,_huai'an",
       'qingshan_district,_wuhan',
       'qinghe_district,_tieling',
       "qingyuan_district,_ji'an",
       'qingshui_geothermal_park',
       'qingchun_square_station',
       'qingdao_tiantai_stadium',
       'qingpu_xincheng_station',
       'qinglong_railway_bridge',
       'qingdao_railway_station',
       'qingyang_xifeng_airport',
       'qingkou_railway_station',
       'qinghua_rainbow_bridge',
       'qingxisan_road_station',
       'qingdao_hailifeng_f.c.',
       'qinghe_railway_station',
       'qing_official_headwear',
       'qingjiang_road_station',
       "qin'an_railway_station",
       'qingling_road_station',
       'qingshui_river_bridge',
       'qintong_boat_festival',
       'qingnian_road_station',
       'qinling_orogenic_belt',
       'qinarjeh,_shahin_dezh',
       'qinzhou_power_station',
       'qingdao_grand_theatre',
       'qing_conquest_theory',
       'qingxu_daode_zhenjun',
       'qinghe_county,_hebei',
       'qinhuai_lantern_fair',
       'qinghu_north_station',
       'qing_dynasty_coinage',
       'qingyuan_lu_station',
       'qingdao_liming_f.c.',
       'qingnian_lu_station',
       'qinghai_senke_f.c.',
       'qin_bronze_chariot',
       'qingdao_golf_open',
       'qingfei_yihuo_wan',
       'qingdao_tv_tower',
       'qing_yan_garden',
       'qin_shi_huang',
       'qing_hui_yuan',
       'qin_er_shi'],
 'o': ['qionglai-minshan_conifer_forests',
       'qiongsha-class_cargo_ship',
       'qionghai_railway_station',
       "qionghai_bo'ao_airport",
       'qionglai_air_base'],
 'p': ['qipanjing,_inner_mongolia', 'qipan_railway_station'],
 'q': ['qiqihar_medical_university',
       'qiqihar_sanjiazi_airport',
       'qiqihar_railway_station'],
 'r': ['qirwash_ibn_al-muqallad', 'qiran,_saudi_arabia'],
 's': ['qishanyan_tunnel_explosion',
       'qishuyan_railway_station',
       'qissat_shakarwati_farmad',
       'qislaq,_asagi_amburd@r@',
       'qishan_railway_station',
       'qissa_khwani_massacre',
       'qissa_khwani_bazaar',
       'qismati_and_nasibi',
       'qissa_meherbano_ka',
       'qishla_of_jeddah',
       'qishla_of_kirkuk',
       'qismat_ka_likha',
       'qishla_of_mecca'],
 't': ['qit_madagascar_minerals', 'qitai_radio_telescope', 'qit-fer_et_titane'],
 'u': ['qiuga_east_station', 'qiubo_of_han'],
 'v': ['qivitoq_-_fjeldgaengeren'],
 'x': ['qixiaying_railway_station',
       'qixia_railway_station',
       'qixin_road_station'],
 'y': ['qiyueshan_railway_station',
       'qiyan_metro_station',
       'qiyi_street_mosque'],
 'z': ['qiziwan_railway_station',
       'qizil_qislaq,_shahbuz',
       'qizhang_metro_station',
       'qizil_qislaq,_fuzuli']}
