
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_r_ = {'_': ['r*-tree',
       'r-30490',
       'r-16661',
       'r-407c',
       'r136a1',
       'r-454b',
       'r-105d',
       'r-410a',
       'r-4066',
       'r-390a',
       'r136a2',
       'r-406a',
       'r-407a',
       'r-350m',
       'r-469a',
       'r136a3',
       'r10000',
       'r4600',
       'r136b',
       'r4000',
       'r-110',
       'r-123',
       'r1155',
       'r.511',
       'r5000',
       'r3000',
       'r2000',
       'r2-d2',
       'r6000',
       'r1200',
       'r136c',
       'r-39m',
       'r80xl',
       'r.530',
       'r-158',
       'r4200',
       'r2-45',
       'r8000',
       'r-905',
       'r2800',
       'r380',
       'r600',
       'r102',
       'r128',
       'r800',
       'r101',
       'r3.0',
       'r145',
       'r290',
       'r-4d',
       'r136',
       'r199',
       'r301',
       'r430',
       'r500',
       'r116',
       'r280',
       'r156',
       'r-77',
       'r360',
       'r-80',
       'r700',
       'r100',
       'r180',
       'r-7a',
       'r63',
       'r49',
       'r16',
       'r97',
       'r14',
       'r99',
       'r52',
       'r18',
       'r98',
       'r07',
       'r68',
       'r13',
       'r61',
       'r56',
       'r27',
       'r80',
       'r34',
       'r74',
       'r33',
       'r37',
       'r31',
       'r57',
       'r23',
       'r17',
       'r65',
       'r44',
       'r86',
       'r64',
       'r39',
       'r59',
       'r32',
       'r41',
       'r78',
       'r51',
       'r20',
       'r60',
       'r21',
       'r30',
       'r62',
       'r73',
       'r76',
       'r50',
       'r54',
       'r35',
       'r79',
       'r69',
       'r66',
       'r40',
       'r83',
       'r81',
       'r67',
       'r72',
       'r71',
       'r45',
       'r29',
       'r11',
       'r85',
       'r70',
       'r19',
       'r06',
       'r77',
       'r47',
       'r28',
       'r82',
       'r55',
       'r53',
       'r36',
       'r03',
       'r15',
       'r24',
       'r10',
       'r43',
       'r75',
       'r58',
       'r++',
       'r26',
       'r25',
       'r12',
       'r22',
       'r42',
       'r46',
       'r48'],
 'a': ['r/amitheasshole',
       'r/askhistorians',
       'r.a.m.o.n.e.s.',
       'r/askreddit',
       'r-algebroid',
       'r.a.c.l.a.',
       'r/antiwork',
       'r1a-sur51',
       'r.a.f.i.'],
 'b': ['r.b.kothuru',
       'r-banding',
       'r@b@nd',
       'r2bees',
       'r:base',
       'r&ba',
       'r&bw'],
 'c': ['r/changemyview', 'r@c@bli', 'r-clip', 'r-cast', 'r2c2', 'r8c'],
 'd': ['r/dataisbeautiful', 'r-darter', 'r2d3', 'r3d'],
 'e': ['r.e.o./t.w.o.',
       'r-expression',
       'r.e.s.o.r.t.',
       'r.e.b.e.l.s.',
       'r-evolution',
       'r.e.t.r.o.',
       'r.e.v.o.',
       'r.ecorii',
       'r-enzyme',
       'r.e.m.ix',
       'r.e.m.',
       'r.ef'],
 'f': ['r@f@dinli', 'r-factor', 'r&f'],
 'g': ['r2games', 'r/ga'],
 'h': ['r@himagali',
       'r-hadron',
       'r@himoba',
       'r@himli',
       'r-hdac',
       'r3hdml',
       'r-h-m',
       'r3hab'],
 'i': ['r.i.p.r.o',
       'r.i.p.d.',
       'r.i.d.e.',
       'r.i.f.',
       'r.i.o.',
       'r/iama',
       'r&i'],
 'k': ['r-kioski', 'r-kive', 'r9k', 'r2k'],
 'l': ['r-ladies', 'r.lum.r', 'r-loop', "r'lyeh", 'r-line', 'r&l'],
 'm': ['r-motorsport',
       'r-matrix',
       'r-mount',
       'r-mall',
       'r3mix',
       'r@m@',
       'r2ml',
       'r&m',
       'r4m'],
 'n': ['r@ncb@rl@r',
       'r.nulenuru',
       "r'nkovce",
       "r'n'besk",
       'r@ngdar',
       'r@ncb@r',
       "r'n'g",
       "r'n'r"],
 'o': ['r.o.o.t.s.',
       'r.o.t.o.r.',
       'r.o.c.k.',
       'r.o.s.e.',
       'r-o-c-k',
       'r.o.r/s',
       'r.o.b.',
       'r.o.e.',
       'r&o'],
 'p': ['r.pudupalayam',
       'r-principle',
       'r.pampalli',
       'r.pattanam',
       'r-process',
       'r-parity',
       'r-point',
       'r-phase',
       'r-pharm'],
 'r': ['r.r.d.t.', 'r&r', 'r2r'],
 's': ['r-symmetry',
       'r@sulzad@',
       'r/science',
       'r.s.a.g.',
       'r@st@c@',
       'r-swift',
       'r@sullu',
       'r-smad',
       'r1se',
       'r&s'],
 't': ['r-tools', 'r-types', 'r-truth', 'r-type', 'r-tree', 'r/t', 'r2t'],
 'u': ['r-u-dead-yet',
       'r.udayagiri',
       'r`uth-assor',
       'r.u.r.u.r.',
       'r.u.s.e.',
       'r.u.l.e.',
       'r.u.r.'],
 'v': ['r-value', 'r.v.s.'],
 'w': ['r/wallstreetbets', 'r-word', 'r\\west', 'r.wan'],
 'y': ['r2y'],
 'z': ["r'zanicino", 'r@zd@r@', 'r@z@vul', 'r@zgov', 'r-zone', 'r@zvan']}
