
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zf = {'_': ['zf_friedrichshafen', 'zf_ecolife', 'zf_ecomat', 'zf_sachs'],
 'a': ['zfat-as1', 'zfand5', 'zfa'],
 'b': ['zfb-tv', 'zfb-05'],
 'c': ['zfc_meuselwitz'],
 'd': ['zfd-fm', 'zfd'],
 'f': ['zff'],
 'g': ['zfg'],
 'h': ['zfhe-fm'],
 'k': ['zfk_fruskogorac',
       'zfk_ekonomist',
       'zfk_breznica',
       'zfk_pancevo',
       'zfk_lovcen',
       'zfk_kocani',
       'zfk_lask'],
 'm': ['zfm-fm'],
 'n': ['zfn'],
 'o': ['zfootball', 'zfourge', 'zfone'],
 'p': ['zfp91-cntf',
       'zfp36l1',
       'zfp161',
       'zfp106',
       'zfp91',
       'zfp57',
       'zfpm2',
       'zfp92',
       'zfp64',
       'zfpm1',
       'zfp36'],
 'r': ['zfr'],
 's': ['zfsp-fm', 'zfs+', 'zfs'],
 'x': ['zfx_inc.'],
 'y': ['zfyve28',
       'zfyve26',
       'zfyve27',
       'zfyve19',
       'zfyve16',
       'zfyve20',
       'zfyve1',
       'zfy'],
 'z': ['zfzz-fm']}
