
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ih = {'a': ['ihara_district,_shizuoka',
       'ihavandhoo_health_centre',
       'ihamaru_nature_reserve',
       'iharaira_te_houkamau',
       'ihab_ibrahim_hussein',
       'ihara_zeta_function',
       'ihaia_te_kirikumara',
       'ihap_hulusi_gorey',
       'iha_shell_mound',
       'ihab_ali_nawawi',
       'ihaia_te_ahu'],
 'c': ['ihc_new_zealand'],
 'e': ["ihering's_three-striped_opossum",
       'iheartradio_country_festival',
       'iheartradio_music_festival',
       'iheartradio_podcast_awards',
       'iheartradio_fiesta_latina',
       'iheartradio_music_awards'],
 'f': ['ihf_inter-continental_trophy', 'ihf_olympic_order'],
 'g': ['ihg_army_hotels'],
 'i': ['ihi_corporation_xf9',
       'ihi_corporation_xf5',
       'ihi_corporation_f7',
       'ihimba_hot_springs'],
 'l': ['ihlati_secondary_school', 'ihlia_lgbt_heritage', 'ihlas_news_agency'],
 'o': ['ihor_serhiyovych_vasylyev', 'ihor_r._lemischka'],
 'p': ['ihp_airpistol_0.177'],
 'r': ['ihr_kinderlein,_kommet', 'ihr_wolltet_spass', 'ihra_drag_racing'],
 's': ['ihsaa_conference-independent_schools',
       'ihsan_sabri_caglayangil',
       'ihsan_maulana_mustofa',
       'ihsan_yildirim_tarhan',
       'ihsan_ali_al-shehbaz',
       'ihsan_burak_ozsarac',
       'ihsan_abdel_quddous',
       'ihsan_oktay_anar',
       'ihsan_emre_vural',
       'ihsan_sabri_ozun',
       'ihsan_h._nadiem',
       'ihsan_al_jabri'],
 'u': ['ihud_bnei_habrit', 'ihu_rural_llg'],
 'w': ['ihwa_mural_village', 'ihwan_datu_adam']}
