
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_x_ = {'_': ['x-13arima-seats',
       'x46cr13',
       'x68000',
       'x11vnc',
       'x.1035',
       'x86-64',
       'x.1205',
       'x610z',
       'x.690',
       'x.400',
       'x25-m',
       'x.509',
       'x2000',
       'x.500',
       'x1000',
       'x.121',
       'x.445',
       'x.28',
       'x.25',
       'x-79',
       'x500',
       'x264',
       'x.21',
       'x-99',
       'x.32',
       'x704',
       'x386',
       'x100',
       'x-1r',
       'x.75',
       'x.64',
       'x265',
       'x300',
       'x360',
       'x-23',
       'x20',
       'x51',
       'x14',
       'x30',
       'x10',
       'x32',
       'x70',
       'x25',
       'x86',
       'x22',
       'x24',
       'x90',
       'x40',
       'x56',
       'x61',
       'x43',
       'x87',
       'x28',
       'x17',
       'x26',
       'x13',
       'x41',
       'x47',
       'x95',
       'x19',
       'x12',
       'x27',
       'x60',
       'x34',
       'x38',
       'x39',
       'x00',
       'x48',
       'x49',
       'x16',
       'x44',
       'x50',
       'x.3'],
 'a': ['x-aspirations',
       'x-amounts',
       'x-alfonso',
       'x-arcade',
       'x-agent',
       'x-acto'],
 'b': ['x-bracing', 'x-bomber', 'x-blades', 'x-babies', 'x-bow'],
 'c': ['x-communication',
       'x-corporation',
       'x-cd-roast',
       'x-coaster',
       'x-change',
       'x-corps',
       'x-cross',
       'x-crise',
       'x-chair',
       'x-cops',
       'x-cart',
       'x-can',
       'x.com',
       'x-car',
       'x2c'],
 'd': ['x.desktop', 'x-dreams', 'x-duckx', 'x-day', 'x3d'],
 'e': ['x-energy'],
 'f': ['x-forwarded-for',
       'x-flight',
       'x-fusion',
       'x-frame',
       'x-force',
       'x-fest',
       'x-face',
       'x-fab',
       'x-fen',
       'x-fly',
       'x-fi'],
 'g': ['x-gluc', 'x-gene', 'x-gal', 'x2go'],
 'h': ['x-height'],
 'i': ['x-inefficiency', 'x-inactivation', 'x-infernus'],
 'j': ['x3j13', 'x-jet'],
 'k': ['x-kid', 'x-kai'],
 'l': ['x@lf@lik@nd',
       'x@lf@honu',
       'x@l@ftala',
       'x@lilabad',
       'x@lf@kuc@',
       'x-league',
       'x@lf@l@r',
       'x@l@fs@',
       'x@lf@li',
       'x@litli',
       'x-large',
       'x@ls@',
       'x@l@c'],
 'm': ['x-mansion',
       'x-machine',
       'x-mount',
       'x-mini',
       'x-moto',
       'x-mode',
       'x-men',
       'x-m1'],
 'n': ['x-no-archive', 'x@nd@k', 'x!nk'],
 'o': ['x-originating-ip', 'x/open', 'x.org', 'x-one', 'x-out'],
 'p': ['x-parameters',
       'x-perimental',
       'x-pressions',
       'x-perience',
       'x-periment',
       'x-pulsion',
       'x-pistols',
       'x-patent',
       'x-paroni',
       'x-panda',
       'x-perts',
       'x-plor',
       'x=prem',
       'x.pc'],
 'q': ['x-quisite'],
 'r': ['x1racing',
       'x-raided',
       'x-ring',
       'x-road',
       'x-raid',
       'x-rite',
       'x-ris',
       'x-ray'],
 's': ['x@s@d@rli',
       'x-static',
       'x-statix',
       'x-sinner',
       'x-scream',
       'x-sampa',
       'x-squad',
       'x-scape',
       'x.s.e.',
       'x@sili',
       'x-seam',
       'x-sat'],
 't': ['x-terminators',
       "x'trapolis",
       'x-teens',
       'x:talk',
       'x-team',
       'x-tree',
       'x-type',
       'x-tra',
       'x@tai',
       'x-tal'],
 'u': ["x'unei"],
 'v': ['x-venture', 'x-vision'],
 'w': ['x-weighted', 'x-win32', 'x-wave', 'x-wars', 'x-wrt'],
 'x': ['x2x'],
 'y': ['x-yachts', 'x/y', 'x&y', 'x+y'],
 'z': ['x@z@rli', 'x-zone', 'x@z@r']}
