
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sd = {'_': ['sd_cinematografica',
       'sd_entertainment',
       'sd_ponferradina',
       'sd_salvatierra',
       'sd_zeljeznicar',
       'sd_association',
       'sd_amorebieta',
       'sd_formentera',
       'sd_compostela',
       'sd_bountiful',
       'sd_escoriaza',
       'sd_vojvodina',
       'sd.kfz._11/1',
       'sd_chantada',
       'sd_powerful',
       'sd_negreira',
       'sd_izakovci',
       'sd.kfz._252',
       'sd_becerrea',
       'sd.kfz._247',
       'sd_indautxu',
       'sd.kfz._234',
       'sd_tarazona',
       'sd.kfz._253',
       'sd_logrones',
       'sd.kfz._250',
       'sd_espanyol',
       'sd.kfz._254',
       'sd_victoria',
       'sd.kfz._251',
       'sd_faithful',
       'sd_oyonesa',
       'sd_blu-ray',
       'sd_bustler',
       'sd_stojnci',
       'sd_lagunak',
       'sd.kfz._10',
       'sd_ordenes',
       'sd_tenisca',
       'sd.kfz._11',
       'sd_tempest',
       'sd_lenense',
       'sd_melilla',
       'sd_almazan',
       'sd_colloto',
       'sd_beasain',
       'sd_nelson',
       'sd.kfz._2',
       'sd_reocin',
       'sd_gundam',
       'sd.kfz._9',
       'sd.kfz._7',
       'sd_huesca',
       'sd.kfz._8',
       'sd_narcea',
       'sd_brezje',
       'sd.kfz._4',
       'sd.kfz._6',
       'sd_deusto',
       'sd_torina',
       'sd_itxako',
       'sd_lemona',
       'sd_teucro',
       'sd_rogoza',
       'sd_buelna',
       'sd_nimble',
       'sd_atlas',
       'sd_times',
       'sd_borja',
       'sd_eibar',
       'sd_ceuta',
       'sd_radar',
       'sd_leioa',
       'sd_ibiza',
       'sd_laika',
       'sd_sueca',
       'sd_card',
       'sd_ejea',
       'sd_cven',
       'sd_gama',
       'sd_noja',
       'sd_1700',
       'sd_worx',
       'sd_250',
       'sd_101'],
 'a': ['sdarm_units', 'sdach_korn', 'sdas_uav'],
 'b': ['sdb_karat', 'sdb_bank'],
 'c': ['sdc_335.579-0.292', 'sdc_verifier', 'sdc_putten'],
 'd': ['sdd-age', 'sddc', 'sdd'],
 'e': ['sderot_cinematheque',
       'sdewes_centre',
       'sdei_avraham',
       'sde_warburg',
       'sdei_trumot',
       'sde_yitzhak',
       'sde_eliezer',
       'sde_eliyahu',
       "sde_ya'akov",
       'sde_nehemia',
       'sde_uziyahu',
       'sde_nitzan',
       'sde_hockey',
       'sdei_hemed',
       'sde_boker',
       'sde_moshe',
       'sde_nahum',
       'sde_david',
       'sde_ilan',
       'sde_yoav',
       'sde_tzvi',
       'sde_boaz'],
 'f': ['sdf_group'],
 'g': ['sdg_group'],
 'h': ['sdh_institute'],
 'i': ['sdi_technologies', 'sdi_presence', 'sdi_tools', 'sdi_media', 'sdi_uav'],
 'j': ['sdj'],
 'k': ['sdkj_uav'],
 'l': ['sdl_passolo', 'sdlp_youth', 'sdl_plc'],
 'm': ['sdm_domino'],
 'n': ['sdn48', 'sdn'],
 'o': ['sdot_micha', 'sdo_bussum', 'sdoos_club', 'sdot_yam'],
 'p': ['sdp-liberal_alliance'],
 'q': ['sdq'],
 'r': ['sdre', 'sdrc', 'sdr'],
 's': ['sdss_j141624.08+134826.7',
       'sdss_j001820.5-093939.2',
       'sdss_j090745.0+024507',
       'sdss_j102915+172927',
       'sdss_j0106-1000',
       'sdss_j1240+6710',
       'sdss_j0303-0019',
       'sdss_j1106+1939',
       'sdss_j1229+1122',
       'sdss_j1430+2303',
       'sdss_j1254+0846',
       'sdss_j0927+2943',
       'sdss_j0100+2802',
       'sds_protocol',
       'sds_basic',
       'sds_940',
       'sds_930'],
 't': ['sdtm', 'sdti', 'sdt'],
 'u': ['sduduzo_ka-mbili'],
 'v': ['sdv_barneveld', 'sdvs_sangh', 'sdvk_fc'],
 'w': ['sdw'],
 'x': ['sdxcentral', 'sdxf'],
 'y': ['sdyusshor-misto_kharkiv', 'sdyushor_desna'],
 'z': ['sdz_ser-082']}
