
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sf = {'_': ['sf_broadcasting',
       'sf_masterworks',
       'sf_rjukanfoss',
       'sf_sketchfest',
       'sf_camerawork',
       'sf_squeecast',
       'sf_minnesota',
       'sf_nieuwoudt',
       'sf_caspase-1',
       'sf_airlines',
       'sf_anytime',
       'sf_ammonia',
       'sf-a2_miki',
       'sf_studios',
       'sf_express',
       'sf_weekly',
       'sf_series',
       'sf_canada',
       'sf_signal',
       'sf_hydro',
       'sf_norge',
       'sf_group',
       'sf_succe',
       'sf_grei',
       'sf_site',
       'sf_film',
       'sf_line',
       'sf_net'],
 'a': ['sfalassa_viaduct',
       'sfax_governorate',
       'sfakianakis_s.a.',
       'sfa_observatory',
       'sfantu_gheorghe',
       'sfatul_tarii',
       'sfat_emet',
       'sfas_157',
       'sfan_ii',
       'sfan_11',
       'sfan_4',
       'sfan_5'],
 'b': ['sfb-oure_fa', 'sfb_games', 'sfb_874'],
 'c': ['sfc_kalinkovo',
       'sfca_taupin',
       'sfc_minerva',
       'sfc_shturmi',
       'sfc_capital',
       'sfc_russia',
       'sfc_opava',
       'sfcg_co.'],
 'd': ['sfdisk', 'sfdr', 'sfdk', 'sfd'],
 'e': ['sfera_politicii',
       'sferic_terrassa',
       'sfera_ebbasta',
       "sfeka_d'yoma",
       'sfera_award'],
 'f': ['sffilm', 'sffc', 'sff'],
 'g': ['sfgirl.com', 'sfgp', 'sfga', 'sfg'],
 'h': ['sfhk_uav'],
 'i': ['sfissifa,_bechar',
       'sfinks_festival',
       'sfiso_buthelezi',
       'sfisef_district',
       'sfia_bouarfa',
       'sfiso_ncwane'],
 'j': ['sfjazz_collective', 'sfjazz_center'],
 'k': ['sfk_vrchovina', 'sfk_united', 'sfk_trygg', 'sfk_2000', 'sfk_lyn'],
 'l': ['sfl_bremerhaven'],
 'm': ['sfm_entertainment', 'sfm_junak'],
 'n': ['sfnt', 'sfnb', 'sfn'],
 'o': ['sforzata_steelband',
       'sfo-millbrae_line',
       'sforza_compagnoni',
       'sfortia_ponzoni',
       'sforza_hours'],
 'p': ['sfpark', 'sfpq', 'sfpa', 'sfpc', 'sfp'],
 'r': ['sfr_medical'],
 's': ['sfs_group'],
 't': ['sftp', 'sfts', 'sftb', 'sft'],
 'u': ['sfurti_sahare', 'sfu_exchange'],
 'v': ['sfv'],
 'w': ['sfwa', 'sfwu', 'sfwp', 'sfw'],
 'x': ['sfx_hall'],
 'z': ['sfzero', 'sfz']}
