
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-23T11:18:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "af0cf462221752bfe3719b49a4afbbf37c8f2bf0",
 "version": "0.7.1.post.dev732"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
