
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pp = {'_': ['pp-wave_spacetime',
       'pp_motorsport',
       'pp-mi-sr_mine',
       'pp_jailbreak',
       'pp-64_wstega',
       'pp-19_vityaz',
       'pp-19_bizon',
       'pp_carinae',
       'pp-91_kedr',
       'pp_cell'],
 'a': ['ppar_agonist'],
 'b': ['ppb_group'],
 'c': ['ppc_journal', 'ppc_racing', 'ppc_ltd.'],
 'd': ['ppd,_inc.'],
 'e': ['ppep,_inc.', 'ppe_needed', 'ppe_suit'],
 'f': ['ppf_banka'],
 'g': ['ppg_industries',
       'ppg_tankette',
       'ppg_phonem',
       'ppg_place',
       'ppg_wave',
       'ppg_16'],
 'h': ['pphln1', 'pphs', 'pphi', 'pph'],
 'i': ['ppi_motorsports'],
 'j': ['ppj'],
 'k': ['ppk'],
 'l': ['ppl_corporation', 'ppl_building', 'ppl_center', 'ppl_india'],
 'm': ['ppmp-2_mine'],
 'n': ['ppn'],
 'o': ['ppojat_helsinki'],
 'p': ['ppp_canada'],
 'q': ['ppq'],
 'r': ['ppru-1', 'pprc1', 'pprc', 'ppru', 'pprm', 'ppr'],
 's': ['ppsm_magelang',
       'pps_22',
       'pps_23',
       'pps_10',
       'pps_25',
       'pps_6',
       'pps_7',
       'pps_1',
       'pps_3',
       'pps_9'],
 't': ['ppt_namenska'],
 'u': ['ppur', 'ppu'],
 'v': ['ppv'],
 'w': ['ppw'],
 'x': ['ppx'],
 'z': ['ppz']}
