
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pw = {'_': ['pw-sat2', 'pw-sat'],
 'a': ['pwani_university',
       'pwaamei_language',
       'pwapwa_language',
       'pwa_silverdome',
       'pwani_region',
       'pwa_saw'],
 'b': ['pwb_shell'],
 'c': ['pwc_plaza'],
 'd': ['pwd_bamenda'],
 'e': ['pweto_territory',
       'pweto_airport',
       'pwedeng_pwede',
       'pwera_usog',
       'pwe_kyit'],
 'g': ['pwg'],
 'h': ['pwhs', 'pwh'],
 'i': ['pwintbyu_township', 'pwilao_basumatary', 'pwint_hpoo', 'pwi_pwi'],
 'l': ['pwllyrhwyad,_llanarth',
       'pwllpriddog_oak',
       'pwllheli_south',
       'pwll,_tregare',
       'pwllheli_f.c.',
       'pwllheli_rfc',
       'pwll_lagoon',
       'pwlldu_bay',
       'pwll_dwfn',
       'pwll_du'],
 'm': ['pwm_rectifier', 'pwm_edition'],
 'n': ['pwn-9_kangaroo', 'pwnie_awards'],
 'o': ['pwo_language', 'pwoje_pyebwa'],
 'p': ['pwpaw', 'pwp2', 'pwp1'],
 'r': ['pwr_racing', 'pwr_bttm'],
 's': ['pws-102_rekin', 'pws-40_junak', 'pws-33_wyzel', 'pws-35_ogar', 'pws_3'],
 't': ['pwt'],
 'u': ['pwu'],
 'v': ['pwv'],
 'w': ['pwwp2a', 'pww'],
 'y': ['pwyll'],
 'z': ['pwz-029']}
