
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pc = {'_': ['pc12_minicomputer',
       'pc/104_consortium',
       'pc_accelerator',
       'pc-8800_series',
       'pc-8000_series',
       'pc-9800_series',
       'pc_perspective',
       'pc-6600_series',
       'pc-6000_series',
       'pc_paintbrush',
       'pc_laldinpuia',
       'pc-50x_family',
       'pc_connection',
       'pc_powerplay',
       'pc_rohlupuia',
       'pc_conectado',
       'pc_migration',
       'pc_hoofthuis',
       'pc_jeweller',
       'pc_exchange',
       'pc_siqueira',
       'pc_speaker',
       'pc_shekhar',
       'pc_answers',
       'pc1_cipher',
       'pc_optimum',
       'pc_extreme',
       'pc_express',
       'pc_leisure',
       'pc_records',
       'pc_arcade',
       'pc-7_team',
       'pc_direct',
       'pc_futbol',
       'pc_format',
       'pc_player',
       'pc_strand',
       'pc_beneke',
       'pc_mobile',
       'pc_munoz',
       'pc_gamer',
       'pc_games',
       'pc_globe',
       'pc_party',
       'pc_tools',
       'pc_chris',
       'pc_today',
       'pc_bruno',
       'pc_quest',
       'pc_mania',
       'pc_world',
       'pc_live!',
       'pc_music',
       'pc_chip',
       'pc_card',
       'pc_1715',
       'pc_plus',
       'pc_bang',
       'pc_club',
       'pc_1600',
       'pc_city',
       'pc_zone',
       'pc_1400',
       'pc_8300',
       'pc_1000',
       'pc_life',
       'pc_game',
       'pc_data',
       'pc_500',
       'pc_pro',
       'pc_ace'],
 'a': ['pcanywhere',
       'pcastl',
       'pcaas',
       'pcae',
       'pcaf',
       'pcac',
       'pcaa',
       'pcap',
       'pca3',
       'pcam',
       'pcas',
       'pcad',
       'pca'],
 'b': ['pcb_piezotronics',
       'pcb_challengers',
       'pcb_persipasi',
       'pcb_dynamites',
       'pcb_blasters',
       'pcb_strikers'],
 'c': ['pcc_streetcar', 'pccw_mobile', 'pcci_group', 'pcc_se'],
 'd': ['pcdhga11',
       'pcdhga12',
       'pcdhb15',
       'pcdhb14',
       'pcdha12',
       'pcdhb12',
       'pcdhb10',
       'pcdhb16',
       'pcdhac2',
       'pcdhb11',
       'pcdh11y',
       'pcdhgc3',
       'pcdh11x',
       'pcdhgb7',
       'pcdhb13',
       'pcdata',
       'pcdh20',
       'pcdhb9',
       'pcdhb5',
       'pcdhb7',
       'pcdh17',
       'pcdha6',
       'pcdhb4',
       'pcdha5',
       'pcdhb3',
       'pcdh18',
       'pcdha9',
       'pcdha4',
       'pcdh10',
       'pcdha3',
       'pcdh15',
       'pcdhb2',
       'pcdha2',
       'pcdh12',
       'pcdh8',
       'pcdh7',
       'pcdh1',
       'pcdi',
       'pcd'],
 'e': ['pcelic', 'pcell', 'pcea', 'pcep', 'pcem', 'pcer', 'pce'],
 'f': ['pcf_theory'],
 'g': ['pcgamingwiki',
       'pcgamerbike',
       'pcgamesn',
       'pcgem1',
       'pcgf5',
       'pcgf6',
       'pcgf1',
       'pcgf2',
       'pcgen',
       'pcgs',
       'pcgg',
       'pcgm',
       'pcg'],
 'h': ['pch_international', 'pchelnik,_russia', 'pchum_ben', 'pch_games'],
 'i': ['pcinja_district', 'pci_geomatica', 'pci_express', 'pci_hole'],
 'j': ['pcjj', 'pcj'],
 'k': ['pckeeper', 'pck2', 'pck1', 'pck'],
 'l': ['pcl_construction'],
 'm': ['pcm_adaptor', 'pcm,_inc.'],
 'n': ['pcnhs', 'pcnt', 'pcnx', 'pcns', 'pcn'],
 'o': ['pcos_challenge', 'pco_imaging'],
 'p': ['pcp_torpedo', 'pcp_theorem'],
 'r': ['pcrpi-db', 'pcrush', 'pcrl', 'pcrd', 'pcrc', 'pcra'],
 's': ['pcsb_bank'],
 't': ['pct_newsletter', 'pcti_solutions', 'pct_gazette'],
 'u': ['pcu_dolphins'],
 'v': ['pcv'],
 'w': ['pcw_ultra'],
 'x': ['pcx'],
 'y': ['pcyt1b', 'pcyox1', 'pcyt1a']}
