
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dd = {'_': ['dd_chhattisgarh',
       'dd_lakshadweep',
       'dd_microscopii',
       'dd_pondicherry',
       'dd_uttarakhand',
       'dd_coimbatore',
       'dd_arunprabha',
       'dd_north-east',
       'dd_chandigarh',
       'dd_jharkhand',
       'dd_rajasthan',
       'dd_meghalaya',
       'dd_saptagiri',
       'dd_malayalam',
       'dd_national',
       'dd_chandana',
       'dd_sahyadri',
       'dd_podhigai',
       'dd_nagaland',
       'dd_yadagiri',
       'dd_tripura',
       'dd_haryana',
       'dd_bharati',
       'dd_chennai',
       'dd_punjabi',
       'dd_manipur',
       'dd_science',
       'dd_mizoram',
       'dd_girnar',
       'dd_sikkim',
       'dd_kashir',
       'dd_bangla',
       'dd_sports',
       'dd_cream',
       'dd_smash',
       'dd_metro',
       'dd_india',
       'dd_retro',
       'dd_assam',
       'dd_bihar',
       'dd_kisan',
       'dd_tank',
       'dd_news',
       'dd_vyas',
       'dd_odia',
       'dd_urdu',
       'dd_214',
       'dd_goa',
       'dd_hd'],
 'a': ['ddakjibon_novels', 'dday_one'],
 'b': ['ddb_worldwide', 'ddb_mudra'],
 'c': ['ddc-i', 'ddc'],
 'd': ['ddd'],
 'e': ['ddef2', 'ddebo', 'ddef1', 'ddex', 'dde'],
 'f': ['ddf'],
 'g': ['ddg_hansa'],
 'h': ['ddh'],
 'i': ['ddishtv', 'ddit4l', 'ddit4', 'ddis', 'ddi1', 'ddi'],
 'j': ['ddj1'],
 'k': ['ddk'],
 'l': ['ddl_intercettazioni'],
 'm': ['ddmashen', 'ddmasar', 'ddm'],
 'n': ['ddn'],
 'o': ['ddos_mitigation', 'ddol_uchaf', 'ddo_190', 'ddo_169', 'ddo_44'],
 'p': ['ddp-24', 'ddpcr', 'ddpo', 'ddps', 'ddp'],
 'r': ['ddr_motorsport',
       'ddr5_sdram',
       'ddr_german',
       'ddr3_sdram',
       'ddr4_sdram',
       'ddr_museum',
       'ddr2_sdram',
       'ddr_sdram'],
 's': ['dds'],
 't': ['ddt_pro-wrestling', 'ddt_judgement'],
 'u': ['ddu-du_ddu-du'],
 'w': ['ddwg', 'ddw'],
 'x': ['ddx19b',
       'ddx27',
       'ddx52',
       'ddx53',
       'ddx39',
       'ddx59',
       'ddx20',
       'ddx10',
       'ddx47',
       'ddx24',
       'ddx3y',
       'ddx3x',
       'ddx21',
       'ddx46',
       'ddx23',
       'ddx56',
       'ddx41',
       'ddx17',
       'ddx43',
       'ddx50',
       'ddx42',
       'ddx11',
       'ddx31',
       'ddx5',
       'ddx6',
       'ddx1',
       'ddx'],
 'y': ['ddy'],
 'z': ['ddz']}
