
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ds = {'_': ['ds/cft_correspondence',
       'ds_automobiles',
       'ds_andromedae',
       'ds_tucanae',
       'ds_crucis',
       'ds_logon',
       'ds_smith',
       'ds_5ls',
       'ds_4s',
       'ds_3',
       'ds_5',
       'ds_9',
       'ds_4',
       'ds_6'],
 'a': ['dsa_antananarivo'],
 'b': ['dsb_congress', 'dsbn_academy', 'dsb_oresund', 'dsbv_punch', 'dsb_bank'],
 'c': ['dsc_wanne-eickel', 'dschang_airport', 'dschinghis_khan', 'dsch_motif'],
 'd': ['dsdp_367', 'dsdp_368'],
 'e': ['dser_20'],
 'f': ['dsfa_records', 'dsf_europe'],
 'g': ['dsg_international'],
 'h': ['dshamilja_kaiser', 'dshon_forbes'],
 'i': ['dsinezumi_shrew', 'dsign_music'],
 'j': ['dsj'],
 'k': ['dsk_duster', 'dsk_group', 'dsk_bank', 'dsk_hyp'],
 'l': ['dsl_filter', 'dsl_sport', 'dsl_rings', 'dsl_modem'],
 'm': ['dsm-iv_codes', 'dsm_cc'],
 'n': ['dsn_corporation', 'dsn_music'],
 'o': ['dsos', 'dso'],
 'p': ['dsp/bios_link',
       'dspnano_rtos',
       'dsp_coupling',
       'dspace_gmbh',
       'dsp_group',
       'dsp_media',
       'dsp_dev'],
 'q': ['dsq_software'],
 'r': ['dsr-precision_dsr-50',
       'dsr-precision_dsr-1',
       'dsr_proteus-eretes',
       'dsrv-1_mystic',
       'dsrv-2_avalon',
       'dsra_rna'],
 's': ['dss_haarlem', 'dssam_model', 'dss_f.c.'],
 't': ['dst_systems', 'dst_global', 'dst_group'],
 'u': ['dsungaripteroidea',
       'dsungaripteridae',
       'dsungaripterus',
       'dsup',
       'dsu'],
 'v': ['dsv_concordia',
       'dsv_shinkai',
       'dsv_leoben',
       'dsv_turtle',
       'dsv-5_nemo',
       'dsv_posen',
       'dsv_alvin',
       'dsv_saaz'],
 'w': ['dsw_entertainment'],
 'x': ['dsx'],
 'y': ['dsy'],
 'z': ['dsz']}
