# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tecton_proto/common/data_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tecton_proto/common/data_type.proto',
  package='tecton_proto.common',
  syntax='proto2',
  serialized_options=b'\n\021com.tecton.commonP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#tecton_proto/common/data_type.proto\x12\x13tecton_proto.common\"\xd5\x01\n\x08\x44\x61taType\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32!.tecton_proto.common.DataTypeEnumR\x04type\x12K\n\x12\x61rray_element_type\x18\x02 \x01(\x0b\x32\x1d.tecton_proto.common.DataTypeR\x10\x61rrayElementType\x12\x45\n\rstruct_fields\x18\x03 \x03(\x0b\x32 .tecton_proto.common.StructFieldR\x0cstructFields\"]\n\x0bStructField\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12:\n\tdata_type\x18\x02 \x01(\x0b\x32\x1d.tecton_proto.common.DataTypeR\x08\x64\x61taType*\xeb\x01\n\x0c\x44\x61taTypeEnum\x12\x15\n\x11\x44\x41TA_TYPE_UNKNOWN\x10\x00\x12\x13\n\x0f\x44\x41TA_TYPE_INT32\x10\x01\x12\x13\n\x0f\x44\x41TA_TYPE_INT64\x10\x02\x12\x15\n\x11\x44\x41TA_TYPE_FLOAT32\x10\x03\x12\x15\n\x11\x44\x41TA_TYPE_FLOAT64\x10\x04\x12\x14\n\x10\x44\x41TA_TYPE_STRING\x10\x05\x12\x12\n\x0e\x44\x41TA_TYPE_BOOL\x10\x06\x12\x17\n\x13\x44\x41TA_TYPE_TIMESTAMP\x10\x07\x12\x13\n\x0f\x44\x41TA_TYPE_ARRAY\x10\x08\x12\x14\n\x10\x44\x41TA_TYPE_STRUCT\x10\tB\x15\n\x11\x63om.tecton.commonP\x01'
)

_DATATYPEENUM = _descriptor.EnumDescriptor(
  name='DataTypeEnum',
  full_name='tecton_proto.common.DataTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_INT32', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_INT64', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_FLOAT32', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_FLOAT64', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_STRING', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_BOOL', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_TIMESTAMP', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_ARRAY', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_STRUCT', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=372,
  serialized_end=607,
)
_sym_db.RegisterEnumDescriptor(_DATATYPEENUM)

DataTypeEnum = enum_type_wrapper.EnumTypeWrapper(_DATATYPEENUM)
DATA_TYPE_UNKNOWN = 0
DATA_TYPE_INT32 = 1
DATA_TYPE_INT64 = 2
DATA_TYPE_FLOAT32 = 3
DATA_TYPE_FLOAT64 = 4
DATA_TYPE_STRING = 5
DATA_TYPE_BOOL = 6
DATA_TYPE_TIMESTAMP = 7
DATA_TYPE_ARRAY = 8
DATA_TYPE_STRUCT = 9



_DATATYPE = _descriptor.Descriptor(
  name='DataType',
  full_name='tecton_proto.common.DataType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='tecton_proto.common.DataType.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='type', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='array_element_type', full_name='tecton_proto.common.DataType.array_element_type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='arrayElementType', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='struct_fields', full_name='tecton_proto.common.DataType.struct_fields', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='structFields', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=274,
)


_STRUCTFIELD = _descriptor.Descriptor(
  name='StructField',
  full_name='tecton_proto.common.StructField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tecton_proto.common.StructField.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='tecton_proto.common.StructField.data_type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='dataType', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=369,
)

_DATATYPE.fields_by_name['type'].enum_type = _DATATYPEENUM
_DATATYPE.fields_by_name['array_element_type'].message_type = _DATATYPE
_DATATYPE.fields_by_name['struct_fields'].message_type = _STRUCTFIELD
_STRUCTFIELD.fields_by_name['data_type'].message_type = _DATATYPE
DESCRIPTOR.message_types_by_name['DataType'] = _DATATYPE
DESCRIPTOR.message_types_by_name['StructField'] = _STRUCTFIELD
DESCRIPTOR.enum_types_by_name['DataTypeEnum'] = _DATATYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataType = _reflection.GeneratedProtocolMessageType('DataType', (_message.Message,), {
  'DESCRIPTOR' : _DATATYPE,
  '__module__' : 'tecton_proto.common.data_type_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.common.DataType)
  })
_sym_db.RegisterMessage(DataType)

StructField = _reflection.GeneratedProtocolMessageType('StructField', (_message.Message,), {
  'DESCRIPTOR' : _STRUCTFIELD,
  '__module__' : 'tecton_proto.common.data_type_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.common.StructField)
  })
_sym_db.RegisterMessage(StructField)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
