
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pt = {'_': ['pt.triyugi_narayan_mahavidyalaya',
       'pt._sambhunath_university',
       'pt_gayamakmur_lestari',
       'pt._sundarlal_sharma',
       'pt_petrokimia_gresik',
       'pt_asiatic_persada',
       'pt_palindo_marine',
       'pt_mi-ba-iii_mine',
       'pt_mi-ba-ii_mine',
       'pt_prachuap_f.c.',
       'pt_pal_indonesia',
       'pt_kallista_alam',
       'pt_boat_museum',
       'pt_mi-ba_mine',
       'pt_mi-k_mine',
       'pt_mi-u_mine',
       'pt_mi-p_mine'],
 'a': ['ptakowice,_silesian_voivodeship',
       'ptakowice,_opole_voivodeship',
       'ptaki,_masovian_voivodeship',
       'ptarmigan_peak_wilderness',
       'ptaszniki,_gdansk_county',
       'ptaki,_lomza_county',
       'ptahemhat_called_ty',
       'ptaki,_kolno_county',
       'ptaa_gmb_model'],
 'c': ['ptc_creo_elements/view', 'ptc_creo_elements/pro', 'ptcl_smart_tv'],
 'e': ['pterobranchia_mitochondrial_code',
       'pteropodid_alphaherpesvirus_1',
       'pteridophyte_phylogeny_group',
       'pterygium_inversum_unguis'],
 'i': ['ptisi_and_diastima', 'ptisi_gia_dyo'],
 'l': ['ptl_satellite_network'],
 'm': ['ptm_public_gatherings'],
 'o': ['ptolemaida-florina_coal_mine',
       'ptolemaeus_of_commagene',
       'ptolemy_ii_philadelphus',
       'ptolemy_xiv_philopator',
       'ptolemais_in_phoenicia',
       'ptolemy_vi_philometor',
       'ptolemy_iv_philopator',
       'ptolemy_iii_euergetes',
       'ptolemaeus_and_lucius',
       'ptolemy_of_mauretania',
       'ptolemy_viii_physcon',
       "ptolemy's_world_map",
       'ptolemy_v_epiphanes',
       'ptolemy_xii_auletes',
       'ptolemais_of_cyrene',
       'ptolemaeus_of_lyon',
       'ptolemy_of_thebes',
       'ptolemy_of_cyprus',
       'ptolemy_of_epirus',
       'ptolemy_of_aloros',
       'ptolemy_ix_soter',
       'ptolemy_i_soter'],
 's': ["pts_lactose-n,n'-diacetylchitobiose_family",
       'pts_mannose-fructose-sorbose_family',
       'pts_fructose-mannitol_family',
       'pts_l-ascorbate_family',
       'pts_galactitol_family',
       'pts_glucitol_family'],
 't': ['ptt_global_chemical', 'ptt_istanbul_cup', 'ptt_rayong_f.c.'],
 'u': ['ptuj_city_stadium'],
 'v': ['ptv-n-2_gorgon_iv', 'ptv_news_tonight'],
 'x': ['ptx,_volume_1', 'ptx,_vol._iii', 'ptx,_vol._ii']}
