
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xu = {'a': ['xuanhuaceratops',
       'xuanhanosaurus',
       'xuanzhangtun',
       'xuansteel',
       'xuancheng',
       'xuanchuan',
       'xuanwumen',
       'xuanduan',
       'xuanzang',
       'xuanzong',
       'xuanwei',
       'xuanxue',
       'xuanhua',
       'xuankou',
       'xuasus',
       'xualae',
       'xuanhe',
       'xuanwu',
       'xuan'],
 'b': ['xubyarli', 'xubuntu', 'xubida', 'xubu'],
 'c': ['xucbala', 'xuchang', 'xucau', 'xuc'],
 'd': ['xudaverdil@r',
       'xudaverdili',
       'xudaf@rin',
       'xudayarli',
       'xudun',
       'xuda'],
 'e': ['xueyantuo',
       'xuetangx',
       'xuedytes',
       'xueshan',
       'xuefang',
       'xuefeng',
       'xueren',
       'xueshi',
       'xuereb',
       'xueta',
       'xue'],
 'f': ['xufexufe'],
 'g': ['xugezhuang'],
 'i': ['xuixo', 'xui'],
 'j': ['xujiajing',
       'xujiafang',
       'xujiadian',
       'xujiaping',
       'xujiahui',
       'xujiayao'],
 'k': ['xukuru', 'xukia'],
 'l': ['xuluquanqu',
       'xulsigiae',
       'xulrunner',
       'xuluqoba',
       'xultun',
       'xul-ha',
       'xulihu',
       'xuling',
       'xuljet',
       'xuluq',
       'xuluf',
       'xul'],
 'm': ['xumarta', 'xumarli', 'xuman', 'xumo', 'xuma'],
 'n': ['xunantunich',
       'xunmenglong',
       'xunit.net',
       'xuntian',
       'xunzhai',
       'xunyang',
       'xunlei',
       'xuncu',
       'xunpu',
       'xunyu',
       'xunit',
       'xun-1',
       'xunzi',
       'xun'],
 'p': ['xupdate', 'xupl'],
 'r': ['xurramobod',
       'xuriella',
       'xurama',
       'xursud',
       'xuray',
       'xur@l',
       'xures',
       'xuri',
       'xura',
       'xurs'],
 's': ['xusom', 'xus'],
 't': ['xuthus', 'xutuli'],
 'v': ['xuv'],
 'w': ['xuwulong'],
 'x': ['xuxcab', 'xuxuan', 'xuxa'],
 'y': ['xuyun', 'xuyen'],
 'z': ['xuzhou']}
