
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zm = {'_': ['zm_christchurch',
       'zm_wellington',
       'zm_whangarei',
       'zm_auckland',
       'zm_waikato'],
 'a': ['zmaj_defilipis',
       'zmago_sagadin',
       'zmaj_aircraft',
       'zman_switch',
       'zmaj_r-1'],
 'b': ['zmb'],
 'd': ['zmdi', 'zmd'],
 'e': ['zmeinogorsky_district', 'zmena_zdola', 'zmeevo_pass'],
 'i': ['zmijowek_wloscianski',
       'zmicier_zhylunovich',
       'zmijanje_embroidery',
       'zmitser_dashkevich',
       'zmicier_sidarovic',
       'zmijewo_koscielne',
       'zmievskaya_balka',
       'zmitrok_biadula',
       'zminec,_finiq',
       'zmija_facula',
       'zmija_group',
       'zmiev_uyezd',
       'zmiiv_raion'],
 'm': ['zmm'],
 'o': ['zmozna_wola'],
 'p': ['zmp_inc.'],
 's': ['zms'],
 't': ['zmt'],
 'u': ['zmuidzinavicius_museum', 'zmutt_glacier', 'zmulner_see'],
 'w': ['zmw_attack'],
 'y': ['zmyslona_parzynowska', 'zmyslona_ligocka', 'zmyslona_slupska'],
 'z': ['zmz_24']}
