
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ie = {'_': ['ie.merge', 'ie7pro'],
 'a': ['ieanjesus', 'ieasa', 'ieac', 'iea'],
 'b': ['iebus', 'iebc'],
 'c': ['iec-p27-1', 'iecava', 'iecee', 'iecc', 'iec'],
 'd': ['iedigital', 'iedera', 'iedea', 'ied'],
 'e': ['ieeextreme',
       'ieee-isto',
       'ieeemadc',
       'ieee-488',
       'ieeja',
       'ieet',
       'iee'],
 'f': ['iefbr14', 'ief'],
 'g': ['ieg'],
 'h': ['iehira', 'iehiro', 'iehisa', 'ieh'],
 'i': ['ieiri', 'iei'],
 'j': ['iejima', 'iej'],
 'k': ['iek'],
 'l': ['ielidassen', 'ieldraan', 'iele', 'iel'],
 'm': ['iemisch',
       'iemerii',
       'iemoto',
       'iemasa',
       'iemon',
       'iema',
       'ieml',
       'iems',
       'iem'],
 'n': ['ienaga', 'iens', 'iena', 'ien'],
 'o': ['ieo'],
 'p': ['ieperfest',
       'iepenrode',
       'iepuresti',
       'iepureni',
       'ieperlee',
       'iepe',
       'iep'],
 'r': ['ieramilimab',
       'ierapetra',
       'iervolino',
       'ierissos',
       'ier3ip1',
       'iercici',
       'ierakas',
       'iernut',
       'ierta',
       'ierna',
       'ierne',
       'iera',
       'ieri',
       'ier3',
       'ier'],
 's': ['iest-std-cc1246',
       'ies4linux',
       'iesjavri',
       'iestyn',
       'iesada',
       'iesha',
       'iesco',
       'iesa',
       'iesi',
       'ieso',
       'iesr',
       'ies'],
 't': ['ietsism', 'ietas', 'ieta', 'ietv', 'iet'],
 'u': ['ieuan', 'ieuaf', 'ieud'],
 'v': ['ieva'],
 'x': ['iexpress', 'iex'],
 'y': ['ieya'],
 'z': ['iezeru', 'iezer']}
