
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tj = {'_': ['tj-ii', 'tj-2', "tj's"],
 'a': ['tjalfiellidae',
       'tjaktjapasset',
       'tjaetsiealmaj',
       'tjapaltjarri',
       'tjalkadjara',
       'tjandamurra',
       'tjalleberd',
       'tjaernoeia',
       'tjalhuizum',
       'tjaereborg',
       'tjarnheden',
       'tjareborg',
       'tjahapimu',
       'tjakastad',
       'tjanefer',
       'tjalknol',
       'tjautjas',
       'tjamuaha',
       'tjalling',
       'tjarven',
       'tjallmo',
       'tjasker',
       'tjapko',
       'tjader',
       'tjauti',
       'tjaru',
       'tjap1',
       'tjay'],
 'c': ['tjc'],
 'd': ['tjd'],
 'e': ['tjeldbergodden',
       'tjejtrampet',
       'tjeraridjal',
       'tjesraperet',
       'tjeldsundet',
       'tjerkgaast',
       'tjernberg',
       'tjentiste',
       'tjeldsund',
       'tjensvoll',
       'tjejmilen',
       'tjejvasan',
       'tjenenyet',
       'tjerkwerd',
       'tjersland',
       'tjeldoya',
       'tjessem',
       'tjesilo',
       'tjeker',
       'tjeerd',
       'tjejer',
       'tjetju',
       'tjebu'],
 'f': ['tjf'],
 'h': ['tjh87', 'tjhs'],
 'i': ['tjilbruke',
       'tjinimin',
       'tjideng',
       'tjilpa',
       'tjibbe',
       'tjitra',
       'tjiraa',
       'tjial',
       'tji'],
 'm': ['tjm'],
 'o': ['tjonnholsoksle',
       'tjoarvekrajgge',
       'tjorneshreppur',
       'tjornholstind',
       'tjokropranolo',
       'tjongsfjorden',
       'tjornuvik',
       'tjoflaat',
       'tjolling',
       'tjornarp',
       'tjovitjo',
       'tjornes',
       'tjotter',
       'tjornin',
       'tjoflot',
       'tjorven',
       'tjodalv',
       'tjotta',
       'tjorn',
       'tjome',
       'tjore',
       'tjo'],
 'p': ['tjp3', 'tjp'],
 'r': ['tjr'],
 's': ['tjs'],
 'u': ['tjuvfjordlaguna',
       'tjuvfjorden',
       'tjuvholmen',
       'tjungundji',
       'tjurabalan',
       'tjuneroy',
       'tjuvjakt',
       'tjurunga',
       'tjuvkil',
       'tjurbo',
       'tjunti',
       'tjugum',
       'tjust',
       'tju'],
 'v': ['tjvjik'],
 'w': ['tjw'],
 'y': ['tjyllyungoo']}
