
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tv = {'_': ['tv4nyheterna',
       'tv-resistori',
       'tv-aksjonen',
       'tv-anytime',
       'tv-glotzer',
       'tv-b-gone',
       'tv-pucken',
       'tv2/nord',
       'tv5monde',
       'tv-lift',
       'tv-nytt',
       'tv-byen',
       'tv3cat',
       'tv.com',
       'tv2000',
       'tv-out',
       'tv1000',
       'tv2me',
       'tv/ep',
       'tv100',
       'tv-am',
       'tv50',
       'tv18',
       'tv80',
       'tv+',
       'tv4',
       'tv1',
       'tv6',
       'tv5'],
 'a': ['tvarbanan',
       'tvaralund',
       'tvarditsa',
       'tvangeste',
       'tvanswer',
       'tvarozna',
       'tvarskog',
       'tvardita',
       'tvashtr',
       'tvaaker',
       'tvaren',
       'tvark',
       'tvac'],
 'b': ['tvb-europe', 'tvbs-asia', 'tvbully', 'tvb8', 'tvbs', 'tvb'],
 'c': ['tvcatchup', 'tvcabo', 'tvcine', 'tvcom', 'tvcc', 'tvc'],
 'd': ['tvd'],
 'e': ['tvedestrandsposten',
       'tverradalskyrkja',
       'tverdokhlebovka',
       'tverrbytthornet',
       'tverrbottindene',
       'tverrelvdalen',
       'tverratinden',
       'tverrfjellet',
       'tverrdalsoya',
       'tveitetunet',
       'tverrvatnet',
       'tvedestrand',
       'tverrbreen',
       'tverdislav',
       'tverraksla',
       'tveteraas',
       'tveitevag',
       'tveitsund',
       'tverreggi',
       'tverecius',
       'tverraga',
       'tverskoy',
       'tvetenia',
       'tvertsa',
       'tveiten',
       'tveten',
       'tveite',
       'tverai',
       'tveide',
       'tveter',
       'tveito',
       'tveita',
       'tveit',
       'tvedt',
       'tver',
       'tvel',
       'tves',
       'tve'],
 'f': ['tvf'],
 'g': ['tvguide.co.uk', 'tvgohome', 'tvge', 'tvg2', 'tvgc', 'tvg'],
 'h': ['tvheadend', 'tvhs', 'tvh'],
 'i': ['tvillingtoppen',
       'tvillingderbyt',
       'tvindefossen',
       'tvillingen',
       'tvihofdi',
       'tvijalp',
       'tvishi',
       'tvigle',
       'tvind',
       'tvins',
       'tving',
       'tvis',
       'tvi'],
 'k': ['tvk'],
 'l': ['tvline', 'tvl'],
 'm': ['tvmnews+',
       'tvmobile',
       'tvmost',
       'tvmax',
       'tvmas',
       'tvmsl',
       'tvmt',
       'tvm3',
       'tvm'],
 'n': ['tvnolly', 'tvnorge', 'tvn24', 'tvnb', 'tvni', 'tvnz', 'tvn'],
 'o': ['tvontario',
       'tvorogovo',
       'tvorovice',
       'tvorihraz',
       'tvoroyri',
       'tvorchi',
       'tvonics',
       'tvokids',
       'tvora',
       'tvod',
       'tvos',
       'tvo'],
 'p': ['tvplayer', 'tvpad', 'tvp1', 'tvp3', 'tvpa', 'tvp2', 'tvp'],
 'q': ['tvq'],
 'r': ['tvrdomestice',
       'tvrdakovici',
       'tvrdojevac',
       'tvrtkovici',
       'tvrdosovce',
       'tvrdonice',
       'tvrdimici',
       'tvrdosin',
       'tvrzice',
       'tvrdaci',
       'tvrdkov',
       'tvrdici',
       'tvrdon',
       'tvrtko',
       'tvrda',
       'tvri',
       'tvrr',
       'tvr'],
 's': ['tvshowsondvd.com', 'tvsdesign', 'tvsn', 'tvsa', 'tvsu', 'tvss', 'tvs'],
 't': ['tvtimes', 'tvtwm', 'tvtag', 'tvtel', 'tvtv', 'tvt'],
 'u': ['tvu'],
 'w': ['tvweek', 'tvwan', 'tvw'],
 'x': ['tvxq', 'tvx'],
 'y': ['tvynovelas'],
 'z': ['tvz']}
