
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tn = {'_': ['tn-iamwarm',
       'tn10',
       "tn'g",
       'tn2',
       'tn6',
       'tn3',
       'tn5',
       'tn4',
       'tn1',
       'tn8',
       'tn7'],
 'a': ['tna'],
 'b': ['tnbc', 'tnb'],
 'c': ['tncc', 'tnca', 'tnc'],
 'd': ['tnd'],
 'e': ['tnet', 'tneb', 'tne'],
 'f': ['tnfsf12-tnfsf13',
       'tnfrsf12a',
       'tnfaip8l2',
       'tnfrsf19',
       'tnfrsf18',
       'tnfsf12',
       'tnfaip8',
       'tnfsf18',
       'tnfaip3',
       'tnfaip1',
       'tnfsf9',
       'tnfox',
       'tnftp',
       'tnfc'],
 'g': ['tngri', 'tnght', 'tng'],
 'h': ['tnh'],
 'i': ['tninvestco', 'tnihaia', 'tnip2', 'tnip1', 'tnik', 'tni'],
 'j': ['tnjri', 'tnj'],
 'k': ['tnks1bp1', 'tnk-bp', 'tnk2', 'tnk'],
 'l': ['tnla', 'tnl'],
 'm': ['tnmk', 'tnm'],
 'n': ['tnni3k', 'tnnt2', 'tnni2', 'tnnt3', 'tnnt1', 'tnni3', 'tnni1', 'tnn'],
 'o': ['tno'],
 'p': ['tnp-atp', 'tnpesa', 'tnpo2', 'tnp2', 'tnp1', 'tnpl', 'tnp'],
 'q': ['tnq'],
 'r': ['tnrc15', 'tnrc6b', 'tnrc6a', 'tnr'],
 's': ['tnsrecords', 'tnsdl', 'tns1', 'tns4', 'tnsp', 'tns'],
 't': ['tntmips', 'tntnet', 'tnt'],
 'u': ['tnuvot', 'tnuva', 'tnu'],
 'v': ['tnv'],
 'w': ['tnw'],
 'z': ['tnz']}
