
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jr = {'_': ['jr-basic', 'jr-voy'],
 'a': ['jrahovit',
       'jraberd',
       'jrashen',
       'jraifia',
       'jrarrat',
       'jrambar',
       'jradzor',
       'jraber',
       'jrarbi',
       'jraif',
       'jrapi',
       'jra'],
 'b': ['jrb'],
 'c': ['jrcls', 'jrc'],
 'd': ['jrdn'],
 'e': ['jreijes', 'jreap', 'jreif'],
 'f': ['jrf'],
 'g': ['jrg'],
 'h': ['jrhs'],
 'i': ['jri-poland', 'jripples', 'jri'],
 'j': ['jrjr'],
 'k': ['jrk'],
 'l': ['jrl'],
 'm': ['jrman', 'jrm'],
 'n': ['jrn'],
 'o': ['jrockit', 'jro'],
 'p': ['jrp-ringier', 'jrp'],
 'r': ['jrr'],
 's': ['jrs'],
 't': ['jrti', 'jrtc', 'jrt'],
 'u': ['jruby', 'jruh'],
 'v': ['jrvezh'],
 'z': ['jrz']}
