
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_aj = {'_': ['aj-60a', 'aj10', 'aj6', 'aj+'],
 'a': ['ajax--pickering',
       'ajagajantharam',
       'ajamxanthone',
       'ajatappareng',
       'ajaxjournaal',
       'ajatashatru',
       'ajaymerukot',
       'ajapsandali',
       'ajax-nieuws',
       'ajaniopsis',
       'ajaraneola',
       'ajarostaq',
       'ajayaraja',
       'ajax-mars',
       'ajay-atul',
       'ajativada',
       'ajangbadi',
       'ajayapala',
       'ajayameru',
       'ajaigarh',
       'ajax4jsf',
       'ajattara',
       'ajanbahu',
       'ajabpura',
       'ajaxview',
       'ajantrik',
       'ajaokuta',
       'ajagaibi',
       'ajaltoun',
       'ajalpan',
       'ajaccio',
       'ajanjul',
       'ajampur',
       'ajanale',
       'ajagara',
       'ajalvir',
       'ajangiz',
       'ajaipur',
       'ajaland',
       'ajacuba',
       'ajamila',
       'ajantha',
       'ajaylat',
       'ajalli',
       'ajalia',
       'ajante',
       'ajanur',
       'ajanta',
       'ajabel',
       'ajagbo',
       'ajavon',
       'ajauli',
       'ajamil',
       'ajacan',
       'ajaaib',
       'ajagae',
       'ajania',
       'ajatar',
       'ajamlu',
       'ajaran',
       'ajayan',
       'ajabaj',
       'ajaeng',
       'ajahn',
       'ajamu',
       'ajams',
       'ajang',
       'ajaka',
       'ajayi',
       'ajaqa',
       'ajayu',
       'ajara',
       'ajama',
       'ajain',
       'ajari',
       'ajand',
       'ajala',
       'ajak',
       'ajam',
       'ajay',
       'ajab',
       'ajaz',
       'ajas',
       'ajar',
       'ajah',
       'ajaw',
       'aja!',
       'ajan',
       'ajat',
       'ajac',
       'ajax',
       'aja'],
 'b': ['ajbelj', 'ajba', 'ajb'],
 'c': ['ajc'],
 'd': ['ajdinovici',
       'ajdovscina',
       'ajdabiya',
       'ajdarra',
       'ajdahak',
       'ajdna',
       'ajdar',
       'ajdir',
       'ajdal',
       'ajda'],
 'e': ['ajellomycetaceae',
       'ajeromi-ifelodun',
       'ajem-turkic',
       'ajellomyces',
       'ajeltokrok',
       'ajellidine',
       'ajeetgarh',
       'ajeetpura',
       'ajegroup',
       'ajeltake',
       'ajegunle',
       'ajemian',
       'ajesaia',
       'ajeezay',
       'ajeyudu',
       'ajethna',
       'ajents',
       'ajekar',
       'ajeti',
       'ajeeb',
       'ajeya',
       'ajesh',
       'ajeyo',
       'ajel',
       'ajez',
       'aje'],
 'g': ['ajgaibibi',
       'ajgareh',
       'ajgain',
       'ajghaz',
       'ajgaon',
       'ajgar',
       'ajga',
       'ajg'],
 'h': ['ajhuwa', 'ajhl', 'ajhs'],
 'i': ['ajisukitakahikone',
       'ajinkyatara',
       'ajilimojili',
       'ajitanatha',
       'ajiboyede',
       'ajilesoro',
       'ajitnagar',
       'ajigonomi',
       'ajinomoto',
       'ajirabad',
       'ajingare',
       'ajingara',
       'ajiniyaz',
       'ajinohur',
       'ajitwal',
       'ajibade',
       'ajivali',
       'ajibola',
       'ajintha',
       'ajisari',
       'ajinkya',
       'ajitpur',
       'ajivika',
       'ajirlu',
       'ajisai',
       'ajiaco',
       'ajijic',
       'ajingi',
       'ajiva',
       'ajima',
       'ajico',
       'ajita',
       'ajika',
       'ajila',
       'ajina',
       'ajish',
       'ajige',
       'ajil',
       'ajim',
       'ajit',
       'aji'],
 'j': ['ajjakadirenahalli',
       'ajjabasavanahalli',
       'ajjegowdanavalase',
       'ajjikyatanahalli',
       'ajjabommanahalli',
       'ajjagodanahalli',
       'ajjagondahalli',
       'ajjikamasagara',
       'ajjagonahalli',
       'ajjenahalli',
       'ajjanakatti',
       'ajjanahalli',
       'ajjihalli',
       'ajjibettu',
       'ajjampura',
       'ajjigudde',
       'ajjavara',
       'ajjipura',
       'ajjamuru',
       'ajjibal',
       'ajjowal',
       'ajjarni',
       'ajjada',
       'ajjul',
       'ajjah',
       'ajji',
       'ajju',
       'ajj'],
 'k': ['ajkaceratops', 'ajkf', 'ajka', 'ajk'],
 'l': ['ajloun', 'ajlad', 'ajla', 'ajl'],
 'm': ['ajmone-marsan',
       'ajmer-merwara',
       'ajmalicine',
       'ajmaline',
       'ajminal',
       'ajmalan',
       'ajmonia',
       'ajmera',
       'ajmer',
       'ajmal',
       'ajman',
       'ajm'],
 'n': ['ajnathavasam',
       'ajnianwala',
       'ajnabia',
       'ajnabee',
       'ajnabi',
       'ajnana',
       'ajnala',
       'ajnoha',
       'ajnale',
       'ajnuj',
       'ajnol',
       'ajna',
       'ajn'],
 'o': ['ajodhyanagar',
       'ajoneuvos',
       'ajoncourt',
       'ajoblanco',
       'ajorbast',
       'ajofrin',
       'ajoypur',
       'ajorluy',
       'ajoueir',
       'ajomojo',
       'ajooba',
       'ajorlu',
       'ajoure',
       'ajoene',
       'ajoite',
       'ajong',
       'ajoie',
       'ajose',
       'ajoba',
       'ajoux',
       'ajol',
       'ajoy',
       'ajoo',
       'ajok',
       'ajou',
       'ajo'],
 'p': ['ajph', 'ajpa', 'ajp'],
 'q': ['ajqan'],
 'r': ['ajrara', 'ajrim', 'ajrak', 'ajron', 'ajri', 'ajr'],
 's': ['ajsevica', 'ajs'],
 't': ['ajtani', 'ajtony', 'ajtte', 'ajtai', 'ajt'],
 'u': ['ajuterique',
       'ajudanabad',
       'ajugoideae',
       'ajuchitlan',
       'ajudanieh',
       'ajugoides',
       'ajuricaba',
       'ajungilak',
       'ajumako',
       'ajugeae',
       'ajuria',
       'ajumma',
       'ajudua',
       'ajuran',
       'ajubus',
       'ajusco',
       'ajuda',
       'ajuba',
       'ajuga',
       'ajuy',
       'ajur',
       'aju'],
 'v': ['ajvatovica', 'ajvatovci', 'ajvaj', 'ajvar'],
 'w': ['ajwright', 'ajwain', 'ajwa', 'ajw'],
 'y': ['ajydaar-ungkur', 'ajyguyy', 'ajyyap', 'ajyad', 'ajylu', 'ajyal'],
 'z': ['ajz']}
