
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ao = {'_': ['ao-27', 'ao-38', 'ao-44', 'ao-46', 'ao-35', 'ao3'],
 'a': ['aoandon', 'aoashi', 'aoah', 'aoa'],
 'b': ['aobadai', 'aoba-ku', 'aobiome', 'aobozu', 'aoba', 'aob'],
 'c': ['aochi', 'aocs', 'aoc3', 'aoci', 'aoc2', 'aoce', 'aocc', 'aoc'],
 'd': ['aodan', 'aodh', 'aod'],
 'e': ['aoe'],
 'f': ['aof'],
 'g': ['aoghairean', 'aogashima', 'aogram', 'aogm', 'aog'],
 'h': ['aohell', 'aohans', 'aohan', 'aoh'],
 'i': ['aois-dana', 'aoidos', 'aoikan', 'aoife', 'aoi'],
 'j': ['aojiazhen', 'aojiru', 'aojia', 'aoj'],
 'k': ['aokiichthys',
       'aokigahara',
       'aokautere',
       'aokohio',
       'aokas',
       'aokp',
       'aoki',
       'aok'],
 'l': ['aolserver', 'aolpress', 'aol'],
 'm': ['aomori', 'aomar', 'aomen', 'aomg', 'aomi', 'aoma', 'aom'],
 'n': ['aongstroemia',
       'aonchotheca',
       'aoniraptor',
       'aonidiella',
       'aonobuaka',
       'aonidiina',
       'aongatete',
       'aonodomon',
       'aontenaa',
       'aonides',
       'aonyobo',
       'aonbaw',
       'aonach',
       'aonuma',
       'aontas',
       'aonia',
       'aonla',
       'aontu',
       'aonyx',
       'aono',
       'aon'],
 'o': ['aoo'],
 'p': ['aoppana', 'aoplus', 'aopen', 'aopo', 'aop'],
 'r': ['aorta-gonad-mesonephros',
       'aortography',
       'aorabania',
       'aoriopsis',
       'aorotrema',
       'aortopexy',
       'aorangia',
       'aoranthe',
       'aortitis',
       'aoridus',
       'aorangi',
       'aoridae',
       'aornis',
       'aornum',
       'aorist',
       'aornos',
       'aoraia',
       'aoric',
       'aor-2',
       'aorta',
       'aor-1',
       'aorun',
       'aorsi',
       'aora',
       'aor'],
 's': ['aosaginohi',
       'aoshachia',
       'aoshima',
       'aosdana',
       'aoshang',
       'aosta',
       'aosa',
       'aosd',
       'aosp',
       'aoss',
       'aos'],
 't': ['aoteadrillia',
       'aoteatilia',
       'aotearapa',
       'aotearoa',
       'aotgl',
       'aotus',
       'aotea',
       'aotd',
       'aotc',
       'aotf',
       'aot'],
 'u': ['aouste-sur-sye',
       'aouleiguatt',
       'aoupinieta',
       'aoudaghost',
       'aoubellil',
       'aouderas',
       'aousserd',
       'aougrout',
       'aouguenz',
       'aoujeft',
       'aoulouz',
       'aoussou',
       'aoufous',
       'aourir',
       'aousja',
       'aourou',
       'aoulef',
       'aouste',
       'aougny',
       'aoukar',
       'aouze',
       'aouda',
       'aouf',
       'aoun',
       'aou'],
 'v': ['aovere', 'aov'],
 'w': ['aowin', 'aow'],
 'x': ['aoxomoxoa', 'aoxin', 'aox'],
 'y': ['aoyama', 'aoyagi'],
 'z': ['aozakura', 'aozora']}
