VERSION_YEAR = 2022
VERSION_MONTH = int('08')
VERSION_DAY = int('25')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('58')
MAJOR_VERSION = 0
MINOR_VERSION = 8
PATCH_VERSION = 202208251158
version_date = '2022/08/25 11:58'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
