
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dc = {'_': ['dc-international',
       'dc-sign',
       'dc/osx',
       'dc-uk',
       'dc10',
       'dc15',
       'dc1a',
       'dc++',
       'dc3',
       'dc5',
       'dc2',
       'dc4'],
 'a': ['dcappella',
       'dcap-btls',
       'dcaf17',
       'dcaf15',
       'dcache',
       'dcaf8',
       'dcaf',
       'dcas',
       'dcat',
       'dcag',
       'dca'],
 'b': ['dcbld2', 'dcbc', 'dcb'],
 'c': ['dcca', 'dcci', 'dccb', 'dccc', 'dcct', 'dccu', 'dcc1', 'dcc'],
 'd': ['dcdc2', 'dcdb', 'dcds', 'dcd'],
 'e': ['dcethreads', 'dce/rpc', 'dceased', 'dcebus', 'dce'],
 'f': ['dcf77', 'dcfc', 'dcfs', 'dcf'],
 'g': ['dcg-iv', 'dcgs', 'dcgo', 'dcg'],
 'h': ['dchs1', 'dchs2', 'dchs', 'dchp', 'dche', 'dch'],
 'i': ['dci-p3', 'dcita', 'dcide', 'dcii', 'dcim', 'dcia', 'dcis', 'dci'],
 'k': ['dckap', 'dck'],
 'l': ['dcleaks', 'dclre1a', 'dclre1b', 'dclk1', 'dcls', 'dcl1', 'dclp', 'dcl'],
 'm': ['dcmes', 'dcmu', 'dcmi', 'dcms', 'dcmp', 'dcma', 'dcml', 'dcmo', 'dcm'],
 'n': ['dcns', 'dcn'],
 'o': ['dconstructed', 'dcourseweb', 'dconf', 'dcop', 'dcos', 'dcom', 'dco'],
 'p': ['dcp1b', 'dcp1a', 'dcpg', 'dcps', 'dcpo', 'dcpl', 'dcp2', 'dcpa', 'dcp'],
 'r': ['dcrail', 'dcraw', 'dcrk', 'dcra', 'dcr'],
 's': ['dcss', 'dcsd', 'dcsc', 'dcsg', 'dcsa', 'dcs'],
 't': ['dctn6',
       'dctn5',
       'dctn2',
       'dctn3',
       'dctn1',
       'dctn4',
       'dctv',
       'dcts',
       'dct'],
 'u': ['dcun1d1', 'dcun1d4', 'dcup', 'dcu'],
 'v': ['dcvg', 'dcv'],
 'w': ['dcw234', 'dcw'],
 'x': ['dcx3', 'dcx'],
 'y': ['dcy']}
