
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ui = {'_': ['ui_greenmetric',
       'ui_ceinnselaig',
       'ui_enechglaiss',
       'ui_dunlainge',
       'ui_fiachrach',
       'ui_lochlainn',
       'ui_dunchada',
       'ui_liathain',
       'ui_diarmata',
       'ui_garrchon',
       'ui_miyazaki',
       'ui_fidgenti',
       'ui_bairrche',
       'ui_shigure',
       'ui_yah-tor',
       'ui_fergusa',
       'ui_briuin',
       'ui_maine',
       'ui_neill',
       'ui_imair',
       'ui_mail',
       'ui_lrt'],
 'a': ['uiam_station', 'uia,_estonia', 'uia_mutual', 'uiam_dam'],
 'b': ['uibujarve', 'uibaresti', 'uibopuu', 'uibai', 'uibis', 'uibo', 'uib'],
 'c': ['uic-halsted_station',
       'uichi_munakata',
       'uichiro_hatta',
       'uichiro_niwa',
       'uic_skyspace',
       'uic_building',
       'uic_flames',
       'uic_franc',
       'uic_568'],
 'd': ['uiduk_university', 'uido_truija'],
 'e': ['uie'],
 'f': ['uif_corporation'],
 'g': ['uigorlersuaq_island',
       'uig,_duirinish',
       'uige_province',
       'uige_airport',
       'uig,_snizort',
       'uig,_lewis',
       'uig_tower'],
 'h': ['uihlein'],
 'i': ['uii'],
 'j': ['uijeongbu_station',
       'uijeongbu_scandal',
       'uiju_airfield',
       'uiju_castle',
       'uiju_county'],
 'k': ['uikala'],
 'l': ['uilortussoq_island',
       'uiloq_slettemark',
       'uillian_correia',
       'uilliam_seoighe',
       'uilleann_pipes',
       'uili_kolo`ofai',
       'uilkraal_river',
       'uilika_nambahu',
       'uilke_vuurman',
       'uilian_souza',
       'uilgan_river'],
 'm': ['uimeere_river'],
 'n': ['uinseann_maceoin',
       'uinta_formation',
       'uinsky_district',
       'uinta_mountains',
       'uintah_meridian',
       'uintah_railway',
       'uinta_chipmunk',
       'uinebona_river',
       'uintah,_utah',
       'uintah_tribe',
       'uinta_basin',
       'uintah_lake',
       'uinta_river',
       'uini_atonio'],
 'p': ['uipath', 'uipi', 'uip'],
 'q': ['uiq_technology'],
 'r': ['uiryeong_county', 'uirapuru,_goias', 'uira_marques'],
 's': ['uissigheim_family',
       'uiseong_station',
       'uisgneabhal_mor',
       'uisenma_borchu',
       'uist_camanachd',
       'uiseong_county',
       'uisai_language',
       'uisce_beatha',
       'uis_mine'],
 't': ['uitangcoy-santos_house',
       'uitgeverij_prometheus',
       'uitsig,_bloemfontein',
       'uitenhage_commando',
       'uitvoerend_bewind',
       'uitkamp_wetlands',
       'uitenhage_group',
       'uitpa_formation',
       'uit_university',
       'uitsaai_projek',
       'uitm_stadium',
       'uiti_baker',
       'uit_rail',
       'uitm_fc'],
 'u': ['uiu'],
 'v': ['uiver_collection'],
 'w': ['uiwang_station'],
 'y': ['uiya']}
