
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uf = {'_': ['uf-1', 'uf3'],
 'a': ['ufabulum', 'ufahamu', 'ufana', 'ufag', 'ufa'],
 'b': ['ufboj'],
 'c': ['ufc1', 'ufcu'],
 'd': ['ufd1l', 'ufd'],
 'e': ['ufenamate',
       'ufelwy',
       'ufente',
       'ufenau',
       'ufens',
       'ufeus',
       'ufeyn',
       'ufer',
       'ufe'],
 'f': ['uffermann',
       'uffington',
       'uffenheim',
       'uffholtz',
       'uffculme',
       'uffelte',
       'uffheim',
       'ufford',
       'uffizi',
       'uffing',
       'uffie',
       'uff!',
       'uffe',
       'uffi',
       'uffa',
       'uff'],
 'g': ['ufgau', 'ufg'],
 'h': ['ufhusen', 'ufh'],
 'i': ['ufimsky', 'ufinet', 'ufita', 'ufip', 'ufi'],
 'j': ['ufj'],
 'l': ['ufl'],
 'm': ['ufmod', 'ufm1', 'ufms', 'ufm'],
 'n': ['ufn'],
 'o': ['ufo-memorial',
       'ufo/southpaw',
       'ufomammut',
       'ufotable',
       'ufology',
       'ufoetry',
       'ufo361',
       'uforia',
       'ufocom',
       'ufofu',
       'ufone'],
 'p': ['ufp'],
 'r': ['ufraw', 'ufr'],
 's': ['ufsp2', 'ufsp1', 'ufs2', 'ufs'],
 't': ['uftrungen', 'uftyuga', 'ufton', 'uftp', 'uft'],
 'u': ['ufudocyclops', 'ufufunyane', 'ufumbani', 'ufuma', 'ufuk', 'ufu'],
 'v': ['ufv'],
 'w': ['ufwa'],
 'x': ['ufx']}
