
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ue = {'_': ['ue-kedadji'],
 'a': ['uea'],
 'b': ['uebigau-wahrenbruck',
       'ueberreuter',
       'uebeschisee',
       'ueberstrass',
       'uebelmannia',
       'ueberstorf',
       'uebeschi',
       'uebel',
       'ueb'],
 'c': ['uecker-randow-tal',
       'uecker-randow',
       'ueckermunde',
       'ueckermann',
       'uechtland',
       'uechi-ryu',
       'uecker',
       'uecomm',
       'uechi',
       'uec'],
 'd': ['uedem', 'ueda', 'ued'],
 'e': ['ueekenkcoracias', 'ueekata', 'uee'],
 'f': ['uefitool', 'uefa', 'uef'],
 'g': ['uegaki', 'ueg'],
 'h': ['uehlfeld', 'uehling', 'uehrde', 'uehara', 'ueh'],
 'i': ['uei-tepui', 'uei'],
 'k': ['uekera', 'uekusa', 'ueken', 'ueki'],
 'l': ['uelversheim',
       'uelvesbull',
       'uelingara',
       'ueltschi',
       'uelliton',
       'ueland',
       'uelzen',
       'uelkal',
       'uelsen',
       'uelitz',
       'uelsby',
       'uelen',
       'uelfe',
       'uelia',
       'ueli',
       'uele',
       'uel'],
 'm': ['uematsu', 'uemura', 'uemoto', 'uemoa', 'uem'],
 'n': ['uenuku-kopako',
       'uenanthracus',
       'uenotrechus',
       'uenglingen',
       'uenohara',
       'uenoidae',
       'uentrop',
       'uenuku',
       'uendel',
       'uenoa',
       'ueno',
       'uen'],
 'p': ['uepeker', 'uepi', 'uep'],
 'r': ['uerdingen', 'uerkheim', 'uersfeld', 'uerikon', 'uer'],
 's': ['uesslingen-buch',
       'uesslingen',
       'ueshiba',
       'uesato',
       'ueslei',
       'uesugi',
       'uesac',
       'uesen',
       'uesp',
       'uess',
       'ues'],
 't': ['uetakevirus',
       'uetoayamix',
       'uetzingen',
       'uetliberg',
       'uettingen',
       'uetendorf',
       'uetersen',
       'uetze',
       'uetz',
       'ueta',
       'uet'],
 'v': ['uevld', 'uev'],
 'w': ['uew'],
 'x': ['uexkull', 'uext'],
 'y': ['ueyama'],
 'z': ['uezwil', 'uezd']}
