
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_if = {'_': ['if_finstroms_kamraterna',
       'if..._dog..._rabbit...',
       'if_tomorrow_comes...',
       'if_performance_hall',
       'if_karlstad_fotboll',
       'if_limhamn_bunkeflo',
       'if_sundsvall_hockey',
       'if_skjold_birkerod',
       'if_americans_knew',
       'if_lyseng_fodbold',
       'if_tomorrow_comes',
       'if_marriage_fails',
       'if_everyone_cared',
       'if_women_counted',
       'if_only_everyone',
       'if_memory_serves',
       'if_madonna_calls',
       'if_p&c_insurance',
       'if_vallentuna_bk',
       'if_friska_viljor',
       "if_you're_young",
       'if_anyone_falls',
       "if_we're_honest",
       'if_you_leave...',
       'if_winter_comes',
       'if_not,_winter',
       'if_you_believe',
       'if_fram_larvik',
       "if_you're_gone",
       'if_frisk_asker',
       'if_no-one_sang',
       'if_vp_uppsala',
       'if_you_please',
       "if_i'm_honest",
       "if_it's_love",
       'if_you_leave',
       'if_they_knew',
       "if_it's_cool",
       'if_you_wanna',
       'if_i_believe',
       "if_it's_over",
       'if_then_else',
       'if_lucy_fell',
       'if_it_bleeds',
       "if_i'm_lucky",
       'if_i_survive',
       'if_she_knew',
       'if_it_rains',
       'if_you_wait',
       'if_its_real',
       'if_you_must',
       'if_the_poet',
       'if_she_dies',
       'if_only_you',
       'if_i_could',
       "if_i_can't",
       'if_u_leave',
       'if_i_rise',
       'if_you_go',
       'if_i_knew',
       'if_we_may',
       'if_i_fall',
       'if_i_fell',
       'if_i_stay',
       'if_i_was',
       'if_i_say',
       'if_i_am',
       'if_i_go'],
 'a': ['ifako_international_school',
       'ifakara_health_institute',
       'ifaf_world_championship',
       'ifaistos_limnou_b.c.',
       'ifan_nanda_pratama',
       'ifanes_e_paradela',
       'ifa_horch_h3a',
       'ifa_horch_h3',
       'ifa_w_50'],
 'b': ['ifb_home_appliances'],
 'c': ['ifchina_original_studio', 'ifc_wild_bills', 'ifc_pego_cup'],
 'd': ['ifd_kapital_group'],
 'e': ['ifesinachi_comedy_nwanyanwu',
       'ifeanyi_frederick_onuigbo',
       'ifema_palacio_municipal',
       'ifeanyi_emmanuel_ojeli',
       'ifelodun,_osun_state',
       'ife_national_museum',
       'ifeanyi_chudy_momah',
       'ifeanyi_ubah_f.c.'],
 'f': ['iffley_county,_queensland',
       'iff_world_ranking',
       'iffat_miraj_awan',
       'iffhs_world_team',
       'iffat_ara_dewan',
       'iff_mark_iii',
       'iff_mark_ii',
       'iff_mark_x'],
 'g': ['ifg_farglory_square'],
 'i': ['ifigenija_zagoricnik_simonovic',
       'ifil-reghin_rg-5_pescarus',
       'ifil-reghin_rg-4_pionier',
       'ifield_community_college',
       'ifield_railway_station',
       'ifield,_west_sussex',
       'ifigenia_in_tauride',
       'ifigenia_in_aulide',
       'ifield_water_mill'],
 'k': ['ifk_uddevalla_futsal',
       'ifk_goteborg_academy',
       'ifk_lidingo_fotboll',
       'ifk_stockholm_bandy',
       'ifk_uppsala_fotboll',
       'ifk_malmo_handboll',
       'ifk_skovde_fotboll',
       'ifk_tumba_fotboll',
       'ifk_uppsala_bandy',
       'ifk_malmo_fotboll',
       'ifk_mora_fotboll',
       'ifk_tumba_hockey',
       'ifk_malmo_bandy',
       'ifk_arboga_ik',
       'ifk_ystad_hk'],
 'l': ['ifl_premier_division', 'ifl_super_league'],
 'm': ['ifm_business_school'],
 'o': ['ifor_williams_trailers',
       'iford_arts_festival',
       'iford,_east_sussex',
       'ifor_leslie_evans',
       'ifor_bowen_lloyd',
       'ifo_bromolla_if',
       'ifor_ap_glyn'],
 'r': ['ifrane_national_park'],
 't': ['iftikhar_muhammad_chaudhry',
       'iftekhar_ahmed_chowdhury',
       'iftekhar_uddin_chowdhury',
       'iftikhar_hussain_ansari',
       'iftikhar_ahmed_sirohey',
       'iftikhar_hussain_shah',
       'iftikhar_nagar_cheema',
       'iftekharul_alam_kislu',
       'iftikhar_sanayi_medal',
       'iftikhar_ali_mushwani',
       'iftikhar_khan_janjua',
       'iftikhar_khan_jhagra',
       'iftikhar_ahmed_shah',
       'iftikhar_ahmed_syed',
       'iftikhar_alam_khan',
       'iftikhar_a._ayaz',
       'iftach_ian_amit',
       'iftah_ya_simsim'],
 'u': ['ifugao_provincial_board', 'ifugao_state_university']}
