
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oy = {'_': ['oy-kayyng_botanical_reserve'],
 'a': ["oyapock's_fish-eating_rat",
       'oyama,_british_columbia',
       'oyapock_river_bridge',
       'oyak_renault_g.s.d.',
       'oyama_v._california',
       'oya_tabu_white-eye',
       'oyama_temple_ruins',
       'oya_soichi_bunko',
       'oyama_cable_car',
       'oyay_deng_ajak',
       'oyan_river_dam',
       'oya_tile_kiln'],
 'e': ['oyehut-hogans_corner,_washington',
       'oyen_municipal_airport',
       "oye!_it's_friday!",
       'oyer_and_terminer',
       'oye_stave_church',
       'oye_mi_canto',
       'oye_como_va'],
 'i': ['oyingbo_bus_terminal'],
 'l': ['oyler_high_school', 'oyler_v._boles'],
 'n': ['oyne_railway_station'],
 'o': ['oyonn_groven_myhren',
       'oyo_ollombo_airport',
       'oyo,_oyo_state',
       'oyo_boy_sotto'],
 's': ['oyster_point_marina/park',
       'oyster_creek,_queensland',
       'oystein_langholm_hansen',
       'oyster_reef_restoration',
       'oystein_gullvag_holter',
       'oyster_rock_lighthouse',
       'oyster_rocks,_karachi',
       'oyster_cove,_tasmania',
       'oystein_kvaal_osterbo',
       'oystein_lund_andersen',
       'oystein_wingaard_wolf',
       'oysters_en_brochette',
       'oystein_olsen_ravner',
       'oyster_bay,_tanzania',
       'oystein_ingar_larsen',
       'oyster_bay,_alabama',
       'oyster_bay_guardian',
       'oyster_creek,_texas',
       'oyster_point_hotel',
       'oyster_river_press',
       'oyster_bay_station',
       'oyster_bed_bridge',
       'oyster_pond_river',
       'oyslebo_og_laudal',
       'oyster_bay_branch',
       'oyster_ice_cream',
       'oyster_fly_rods',
       'oystein_b._blix'],
 'u': ['oyu_stone_circles', 'oyukiumi_no_kaina', 'oyu_tolgoi_mine'],
 'v': ['oyvind_alfred_stensrud', 'oyvind_s._bruland', 'oyvind_s._berg'],
 'y': ['oyyarathu_chandu_menon']}
