
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oi = {'_': ['oi!_mlodziez/mechaniczna_pomarancza',
       'oi_district,_fukui',
       'oi_treis_harites',
       'oi!_the_album',
       'oi_man_estate',
       'oi_kwan_hotel',
       'oi_yuen_villa',
       'oi_yoi_yoi',
       'oi_va_voi'],
 'c': ['oic_resolution_10/11'],
 'g': ['oignon_de_roscoff', 'oige_mehe_koda'],
 'j': ['oijared_ladies_open', 'oijen_en_teeffelen'],
 'k': ['oikonomos_tsaritsani_f.c.', 'oikos_university_shooting'],
 'l': ['oil-for-food_program_hearings',
       'oilers_entertainment_group',
       'oil_mines_regulations-1984',
       'oilfield_scale_inhibition',
       'oil_painting_reproduction',
       'oil_states_international',
       'oil_imperialism_theories',
       'oil_springs_reservation',
       'oilville,_west_virginia',
       'oil_depletion_allowance',
       'oil_city,_pennsylvania',
       'oil_company_residences',
       'oil_insurance_limited',
       'oil_springs,_kentucky',
       'oil_city,_mississippi',
       'oil_center,_illinois',
       'oil_city,_washington',
       'oil_trough,_arkansas',
       'oil_mist_lubrication',
       'oil_city,_california',
       'oil_springs,_ontario',
       'oilspot_and_lipstick',
       'oil_production_plant',
       'oil_cleansing_method',
       'oil_shale_economics',
       'oil_free_wellington',
       'oil_city,_wisconsin',
       'oil_city,_louisiana',
       'oil_creek_formation',
       'oil_drop_experiment',
       'oil_grove,_illinois',
       'oil_city,_kentucky',
       'oil_shale_industry',
       'oil_of_catechumens',
       'oil_city,_missouri',
       'oil_platforms_case',
       'oil_city,_maryland',
       'oil_creek_railroad',
       'oil_city,_oklahoma',
       'oil_shale_reserves',
       'oil_sands_karaoke',
       'oil_print_process',
       'oil_content_meter',
       'oil_patch_hotline',
       'oil_shale_geology',
       'oil_city_symphony',
       'oil_well_shooting',
       'oil_drying_agent',
       'oil_hill,_kansas',
       'oil_springs_fire',
       'oil_field_engine',
       'oil_retort_house',
       'oil_strike_north',
       'oil_well_control',
       'oil_city_armory',
       'oil_in_oklahoma',
       'oil_city_oilers',
       'oil_and_vinegar',
       'oil_record_book',
       "oil_can_henry's",
       'oil_city,_texas',
       'oil_by_country',
       'oil_catch_tank',
       'oil_city_park',
       'oil_of_saints',
       'oil_on_copper',
       'oil_for_drugs',
       'oil_and_water',
       'oil_well_fire',
       'oil_of_guaiac',
       'oil_on_canvas',
       'oil_shale_gas',
       'oil_of_brick',
       'oil_on_water',
       'oil_india_fc',
       'oil_and_gold',
       'oil_can_boyd',
       'oil_in_place',
       'oil_of_clove',
       'oil_blue_35',
       'oil_nut_bay',
       'oil_on_ice',
       'oil_blue_a',
       'oil_red_o'],
 'n': ['oingo_boingo_discography',
       'oinofyta_railway_station',
       'oinoi_railway_station',
       "oink's_pink_palace",
       'oinam_lukhoi_singh',
       'oinam_gautam_singh',
       'oinam_bembem_devi'],
 'o': ['oio_railway_station'],
 'p': ['oip_sensor_systems'],
 'r': ['oireachtas_na_gaeilge'],
 's': ['oishi_shinkage-ryu_kenjutsu',
       'oisterwijk_railway_station',
       "oise's_3rd_constituency",
       "oise's_7th_constituency",
       "oise's_5th_constituency",
       "oise's_6th_constituency",
       "oise's_2nd_constituency",
       "oise's_4th_constituency",
       "oise's_1st_constituency",
       'oistins_fish_festival',
       'oisin_mac_diarmada',
       'oistin_mac_amlaib',
       'oisc_of_kent'],
 't': ['oita_broadcasting_system',
       'oita_asahi_broadcasting',
       'oita_at-large_district',
       'oita_athletic_stadium',
       'oitti_railway_station',
       'oita_district,_oita',
       'oita_junior_college',
       'oita_urban_classic',
       'oit_ihuk,_arizona',
       'oita_airport_road'],
 'v': ['oivin_skappel_fjeldstad', 'oivind_storm_bjerke', 'oivind_s._jorfald'],
 'w': ['oiwayama_kofun_cluster']}
