
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_og = {'_': ['og_boo_dirty', 'og_ron_c'],
 'a': ['ogasawara_heibei_tsuneharu',
       'ogasa_district,_shizuoka',
       'oga_quasi-national_park',
       'ogasawara_national_park',
       'ogarev,_voronezh_oblast',
       'ogarita_booth_henderson',
       'ogachi_district,_akita',
       'ogasan_nature_reserve',
       'ogasawara_high_school',
       "ogaki_women's_college",
       'ogaki_asanaka_stadium',
       'oga_athletic_stadium',
       'ogallala_high_school',
       'ogae_video_contest',
       'ogan_ilir_regency',
       'oga_aquarium_gao',
       'ogawa_jihei_vii',
       'oganj_lrsvm_m18',
       'ogawa_no_hotori',
       'oga_golf_course'],
 'b': ['ogbourne_railway_station',
       'ogbonna_okechukwu_onovo',
       'ogbourne_st_andrew',
       'ogbourne_st_george',
       'ogba_kalu_nnanna'],
 'c': ['ogc_reference_model'],
 'd': ['ogdensburg-prescott_international_bridge',
       'ogdensburg-prescott_border_crossing',
       'ogden-clearfield_metropolitan_area',
       'ogdensburg_international_airport',
       'ogdensburg_correctional_facility',
       'ogden/weber_municipal_building',
       'ogden-weber_technical_college',
       'ogden_international_school',
       'ogden_township,_michigan',
       'ogden,_british_columbia',
       'ogdensburg_harbor_light',
       'ogden_elementary_school',
       'ogdensburg_free_academy',
       'ogden_military_academy',
       'ogdensburg,_new_jersey',
       'ogden,_south_carolina',
       'ogden,_north_carolina',
       'ogden,_west_yorkshire',
       'ogden_apartment_hotel',
       'ogden,_west_virginia',
       'ogdensburg,_new_york',
       'ogden_dunes,_indiana',
       'ogden_mine_railroad',
       'ogden_nature_center',
       'ogden_phipps_stakes',
       'ogden,_nova_scotia',
       'ogden_codman_house',
       'ogden_valley,_utah',
       'ogden_mills_phipps',
       'ogden_utah_temple',
       'ogden_hoffman_jr.',
       'ogden_high_school',
       'ogden_gas_scandal',
       'ogden_v._saunders',
       'ogden_mills_house',
       'ogden_codman_jr.',
       'ogden_mills_reid',
       'ogden_h._hammond',
       'ogden,_new_york',
       'ogden_l._mills',
       'ogden_city_sc',
       'ogden_j._ross'],
 'e': ['ogeechee_technical_college',
       'ogemaw_township,_michigan',
       'ogemawahj_tribal_council',
       'ogemaw_county,_michigan',
       'ogemaw_hills_pathway',
       'ogedengbe_of_ilesa',
       'oget_oktem_tanor'],
 'g': ['oggiono_railway_station', 'oggy_oggy_oggy'],
 'h': ['oghenechovwe_donald_ekpeki',
       'oghara_township_stadium',
       'oghuz_yabgu_state',
       'oghab_tehran_f.c.',
       'oghab_shiraz_f.c.'],
 'i': ['ogilvie-mackenzie_alpine_tundra',
       'ogilvie_transportation_center',
       'ogilvie,_western_australia',
       'ogirala_ramachandra_rao',
       'ogilvie_moses_farmhouse',
       'ogilvie_ridge,_edmonton',
       'ogilvie,_nova_scotia',
       'ogii_nuur,_arkhangai',
       'ogisai_kurokawa_noh',
       'ogiame_atuwatse_iii',
       'ogilvie_high_school',
       'ogi_district,_saga',
       'ogier_of_savoy',
       'ogier_the_dane',
       'ogi_no_shiori'],
 'l': ['oglebay_norton_corporation',
       'oglethorpe_county,_georgia',
       'oglala_national_grassland',
       'ogle_county_courthouse',
       'oglala_lakota_college',
       'ogle_county,_illinois',
       'oglala,_south_dakota',
       'ogle_county_airport',
       'oglesby_high_school',
       'oglaigh_na_heireann',
       'ogle_robert_gowan',
       'ogle_dvd_player'],
 'm': ['ogmundar_thattr_dytts'],
 'n': ['ognyanovo,_blagoevgrad_province',
       'ognyanovo,_pazardzhik_province',
       'ognjeslav_kostovic_stepanovic',
       'ognyanovo,_dobrich_province',
       'ogniwo,_lublin_voivodeship',
       'ognica,_stargard_county',
       'ognica,_gmina_widuchowa',
       "ognev's_long-eared_bat",
       'ognica,_gmina_chojna',
       'ogni,_altai_republic',
       'ogni,_altai_krai'],
 'o': ['ogonki,_warmian-masurian_voivodeship',
       'ogonki,_pomeranian_voivodeship',
       'ogooue-leketi_national_park',
       'ogonowice,_lodz_voivodeship',
       'ogongo_agricultural_college',
       'ogorzelec,_polkowice_county',
       'ogonow,_lublin_voivodeship',
       'ogonow,_opole_voivodeship',
       'ogoni/niger_delta_news',
       'ogof_hen_ffynhonnau',
       'ogo_bodhu_shundori',
       'ogoki_post_airport',
       'ogof_hen_formation',
       'ogof_agen_allwedd',
       'ogof_ffynnon_ddu',
       'ogof_dydd_byraf',
       'ogof_llyn_parc',
       'ogof_hesp_alyn',
       'ogon_no_hibi'],
 'r': ['ogrodzieniec,_warmian-masurian_voivodeship',
       'ogrodniki,_warmian-masurian_voivodeship',
       'ogrodek,_warmian-masurian_voivodeship',
       'ogrodzona,_silesian_voivodeship',
       'ogrodek,_masovian_voivodeship',
       'ogrodniki,_siemiatycze_county',
       'ogrodzisko,_lodz_voivodeship',
       'ograzhden,_dobrich_province',
       'ogrodniki,_bialystok_county',
       'ogrodniki,_hajnowka_county',
       'ogrodzona,_piotrkow_county',
       'ogrodniczki,_gmina_suprasl',
       'ogrodzona,_leczyca_county',
       'ogrodniki,_siedlce_county',
       'ogryzkovo,_vologda_oblast',
       'ogrodniki,_sokolka_county',
       'ogrodniki,_bielsk_county',
       'ogrodniki,_wegrow_county',
       'ogrodniki,_sejny_county',
       'ogrodniki,_gmina_tuczna',
       'ogreeta,_north_carolina',
       'ogrodniki,_monki_county',
       'ogra_fianna_fail',
       'ogre_you_asshole',
       'ogra_shinn_fein'],
 'u': ['oguzhan_presidential_palace',
       'ogunquit_memorial_library',
       'ogunquit_village_school',
       'ogunboye_iyanu_ezekiel',
       'ogun_state_television',
       'oguruwa_shell_midden',
       'ogura_hyakunin_isshu',
       'ogura_yonesuke_itoh',
       'oguz_kagan_guctekin',
       'ogushi_shell_mound',
       'oguz_han_aynaoglu',
       'ogun_prison_break',
       'ogu_na_ofo'],
 'w': ['ogwen_rural_district',
       'ogwr_borough_council',
       'ogwu_james_onoja',
       'ogwo_e._ogwo'],
 'y': ['ogyen_choeling_monastery', 'ogyen_trinley_dorje']}
