
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bm = {'_': ['bm_atletico_valladolid',
       'bm_ciudad_encantada',
       'bm_puerto_sagunto',
       'bm_aula_cultural',
       'bm_puente_genil',
       'bm_habitat_mall',
       'bm_nazrul_islam',
       'bm_ciudad_real',
       'bm_la_calzada',
       'bm_bera_bera'],
 'a': ['bmat_stem_academy'],
 'c': ['bmc_evolutionary_biology',
       'bmc_endocrine_disorders',
       'bmc_veterinary_research',
       'bmce_bank_international',
       'bmc_structural_biology',
       'bmc_development_team',
       'bmc_b-series_engine',
       'bmc_e-series_engine',
       'bmc_a-series_engine',
       'bmc_c-series_engine',
       'bmc_systems_biology',
       'bmc_racing_cup'],
 'g': ['bmg_rights_management',
       'bmg_heritage_records',
       'bmg_music_australia',
       'bmg_music_canada'],
 'j': ['bmj_best_practice'],
 'l': ['bml_munjal_university'],
 'o': ['bmo_capital_markets', 'bmo_harris_bank'],
 'p': ['bmp-1_service_history', 'bmp_file_format'],
 's': ['bms_scuderia_italia', 'bms_world_mission', 'bms_cam_rifle'],
 't': ['bmt_brooklyn_loops',
       'bmt_brighton_line',
       'bmt_canarsie_line',
       'bmt_broadway_line',
       'bmt_astoria_line',
       'bmt_jamaica_line'],
 'v': ['bmva_summer_school'],
 'w': ['bmw_vision_connecteddrive',
       'bmw_1602_elektro-antrieb',
       'bmw_ladies_championship',
       'bmw_tennis_championship',
       'bmw_international_open',
       'bmw_central_building',
       'bmw_pga_championship',
       'bmw_ladies_classic',
       'bmw_charity_pro-am',
       'bmw_/6_motorcycles',
       'bmw_guggenheim_lab',
       'bmw_cca_foundation',
       'bmw_ljubljana_open',
       'bmw_/5_motorcycles',
       'bmw_clar_platform',
       'bmw_group_classic',
       'bmw_track_trainer',
       'bmw_goldfisch_v16',
       'bmw_in_motorsport',
       'bmw_sauber_f1.09',
       'bmw_sauber_f1.08',
       'bmw_sauber_f1.06',
       'bmw_sauber_f1.07',
       'bmw_g650x_series',
       'bmw_south_africa',
       'bmw_ukl_platform',
       'bmw_c_evolution',
       'bmw_p66_series',
       'bmw_247_engine',
       'bmw_hp2_enduro',
       'bmw_cs_concept',
       'bmw_hydrogen_7',
       'bmw_asian_open',
       'bmw_02_series',
       'bmw_hp2_sport',
       'bmw_new_class',
       'bmw_nazca_c2',
       'bmw_8_series',
       'bmw_2_series',
       'bmw_hp4_race',
       'bmw_5_series',
       'bmw_6_series',
       'bmw_type_255',
       'bmw_7_series',
       'bmw_3_series',
       'bmw_1_series',
       'bmw_4_series',
       'bmw_v12_lmr',
       'bmw_m6_gtlm',
       'bmw_3200_cs',
       'bmw_new_six',
       'bmw_art_car',
       'bmw_r_ninet',
       'bmw_v12_lm',
       'bmw_320_tc',
       'bmw_m8_gte',
       'bmw_z4_gte',
       'bmw_wr_750',
       'bmw_ce_04',
       'bmw_f_76',
       'bmw_r_11']}
