
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rv = {'_': ['rv:_resurrected_victims',
       'rv_profesor_siedlecki',
       'rv_atlantic_explorer',
       'rv-1_nuclear_reactor',
       'rv_southern_surveyor',
       'rv_coastal_guardian',
       'rv_odyssey_explorer',
       'rv_kronprins_haakon',
       'rv_celtic_explorer',
       'rv_cefas_endeavour',
       'rv_tubitak_marmara',
       'rv_griffin_reserve',
       'rv_gloria_michelle',
       'rv_tauri_variable',
       'rv_david_thompson',
       'rv_pacific_escort',
       'rv_western_flyer',
       'rv_maurice_ewing',
       'rv_rachel_carson',
       'rv_martin_sheen',
       'rv_farley_mowat',
       'rv_simon_stevin',
       'rv_george_bligh',
       'rv_sir_lancelot',
       'rv_atlantis_ii',
       'rv_point_lobos',
       'rv_ernest_holt',
       'rv_mta_turkuaz',
       'rv_coriolis_ii',
       'rv_st._barbara',
       'rv_apex_solar',
       'rv_moana_wave',
       'rv_polar_duke',
       'rv_le_suroit',
       'rv_mta_selen',
       'rv_denar_2'],
 'a': ['rvacki_klub_partizan']}
