
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-22T08:18:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d192bfc7e2b1db18c3bb0ca7fd3f29aa2040b46a",
 "version": "v0.1.36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
