
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uj = {'_': ['uj_magyar_szo'],
 'a': ['ujazd,_kuyavian-pomeranian_voivodeship',
       'ujazd,_swietokrzyskie_voivodeship',
       'ujazd,_podkarpackie_voivodeship',
       'ujazdowek,_masovian_voivodeship',
       'ujazdowo,_masovian_voivodeship',
       'ujazdowek,_lodz_voivodeship',
       'ujazd,_poddebice_county',
       'ujazdow,_wlodawa_county',
       'ujazdow_avenue,_warsaw',
       'ujazd,_koszalin_county',
       'ujazdy,_rzeszow_county',
       'ujazdy,_brzozow_county',
       'ujazdow,_zamosc_county',
       'ujazd,_bochnia_county',
       'ujazd,_gniezno_county',
       'ujazd,_krakow_county',
       'ujagar_singh_sekhwan',
       'ujan_ganger_naiya',
       'ujayf_ibn_anbasa'],
 'b': ['ujbuda-kozpont_metro_station'],
 'e': ['ujezd_pod_troskami',
       'ujezd_u_boskovic',
       'ujezd_u_pruhonic',
       'ujezd_u_prelouce',
       'ujezd_u_planice',
       'ujezd_u_sezemic',
       'ujezd_u_tisnova',
       'ujezd_nade_mzi',
       'ujezd_u_chocne',
       'ujezd_u_rosic',
       'ujed_za_dusu',
       'ujezd_u_brna'],
 'h': ['ujhani_railway_station'],
 'i': ['uji_dainagon_monogatari',
       'ujina_5-chome_station',
       'ujina_4-chome_station',
       'ujina_2-chome_station',
       'ujina_3-chome_station',
       'uji_shui_monogatari',
       'uji_online_robot',
       'ujir_singh_thapa'],
 'j': ['ujjain_international_stadium',
       'ujjain_municipal_corporation',
       'ujjain_development_authority',
       'ujjain_engineering_college',
       'ujjain_polytechnic_college',
       'ujjaini_mahakali_temple',
       'ujjain_public_school',
       'ujjal_narayan_sinha',
       'ujjwal_raman_singh'],
 'k': ['ujkow_nowy_kolonia'],
 'l': ['ujlan_volcanic_complex'],
 'o': ['ujong_blang_beach'],
 'p': ['ujpest-varoskapu_metro_station',
       'ujpest-kozpont_metro_station',
       'ujpesti_torekves_se',
       'ujpest_water_tower',
       'ujpest_fc_ii'],
 's': ['ujscie,_lublin_voivodeship',
       'ujscie,_braniewo_county',
       'ujscie,_elblag_county'],
 'u': ['ujung_water_palace', 'ujue_-_uxue']}
