
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ue = {'_': ['ue_junior_warriors',
       'ue_red_warriors',
       'ue_santa_coloma',
       'ue_kara_mariko',
       'ue_sant_andreu',
       'ue_costa_brava',
       'ue_sant_julia',
       'ue_boom_2'],
 'a': ['uea_law_school'],
 'b': ['uebel_and_lechleiter'],
 'c': ['ueckermunde_stadthafen_station'],
 'd': ['ueda_high_school'],
 'f': ['uefi_platform_initialization',
       'uefa_european_championship',
       "uefa_women's_championship",
       'uefa_european_qualifiers',
       'uefa_futsal_championship',
       'uefa_stadium_categories',
       'uefa_celebration_match',
       'uefa_coaching_licences',
       "uefa_president's_award",
       'uefa-caf_meridian_cup',
       'uefa_champions_league',
       'uefa_nations_league',
       'uefa_jubilee_awards',
       'uefa_europa_league',
       'uefa_intertoto_cup',
       'uefa_youth_league',
       "uefa_regions'_cup",
       'uefa_amateur_cup',
       'uefa_euro_1988',
       'uefa_euro_2004',
       'uefa_super_cup',
       'uefa_euro_1992',
       'uefa_euro_2016',
       'uefa_euro_2022',
       'uefa_euro_1984',
       'uefa_euro_1996',
       'uefa_euro_1972',
       'uefa_euro_1968',
       'uefa_euro_2020',
       'uefa_euro_2032',
       'uefa_euro_2008',
       'uefa_euro_1980',
       'uefa_euro_2024',
       'uefa_euro_1976',
       'uefa_euro_2012',
       'uefa_euro_2000',
       'uefa_euro_2028'],
 'l': ['uell_stanley_andersen', 'uel_black_bulls', 'uel_w._lamkin'],
 'n': ['ueno_gakuen_university', 'ueno_zoo_monorail', 'ueno_temple_ruins'],
 'p': ['uep_subang_jaya'],
 'r': ['uerikon_railway_station', 'uerm_memorial_hospital'],
 't': ['uetliberg_railway_station',
       'uetendorf_railway_station',
       'uetikon_railway_station',
       'uetliberg_railway_line',
       'uet_era_ngermeuangel',
       'uet_masters_series',
       'uetsu_main_line',
       'uet_era_ongael',
       'uetikon_am_see']}
