
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mn = {'_': ['mn-111', 'mn-25', 'mn-18', 'mn103', 'mn55', 'mn+', 'mn1', 'mn8'],
 'a': ['mnatsakanyan',
       'mnasitheus',
       'mnarolitia',
       'mnasagoras',
       'mnase-seq',
       'mnasippus',
       'mnasinous',
       'mnasicles',
       'mnasalcas',
       'mnasilus',
       'mnazinia',
       'mnactec',
       'mnajdra',
       'mnarani',
       'mnadani',
       'mnaseas',
       'mnason',
       'mnasra',
       'mnais',
       'mnat1',
       'mnata',
       'mnac',
       'mnaa',
       'mna'],
 'b': ['mnba', 'mnb'],
 'c': ['mnctv', 'mnc'],
 'd': ['mndsgn', 'mndo', 'mndr', 'mnda', 'mnd'],
 'e': ['mnesarchaeidae',
       'mnemeiosaurus',
       'mnesarchella',
       'mnesilochus',
       'mnesarchaea',
       'mnesipenthe',
       'mnematidium',
       'mnesithetis',
       'mnesictena',
       'mnestiidae',
       'mnesitheus',
       'mnemiopsis',
       'mnesistega',
       'mnesampela',
       'mnesimache',
       'mnesarchus',
       'mnemonist',
       'mnesteria',
       'mnematium',
       'mnesiloba',
       'mnesileus',
       'mnemozina',
       'mnemosyne',
       'mnesarete',
       'mnemovore',
       'mnesithea',
       'mnesikles',
       'mnestheus',
       'mnemonic',
       'mnesigea',
       'mnemesis',
       'mnemoses',
       'mnester',
       'mnestia',
       'mnemata',
       'mnetes',
       'mnemic',
       'mnemea',
       'mnenia',
       'mnesia',
       'mnevis',
       'mneme',
       'mnek',
       'mnet',
       'mne'],
 'f': ['mnfpac', 'mnf'],
 'g': ['mnguni'],
 'h': ['mnhs', 'mnhm'],
 'i': ['mniszow-kolonia',
       'mnich-poludnie',
       'mnin-przymusow',
       'mnin-blagodac',
       'mnich-osrodek',
       'mniarogekko',
       'mnin-szwedy',
       'mnichovice',
       'mnichowice',
       'mnin-mokre',
       'mniopamea',
       'mniochloa',
       'mniocera',
       'mniaceae',
       'mniaecia',
       'mniotype',
       'mniowice',
       'mniszkow',
       'mnisztwo',
       'mniszew',
       'mnierea',
       'mnichov',
       'mnichus',
       'mniodes',
       'mniszki',
       'mniszek',
       'mniszow',
       'mniusa',
       'mniewo',
       'mnizus',
       'mnikow',
       'mninga',
       'mnichy',
       'mnisek',
       'mniaa',
       'mnich',
       'mnium',
       'mniow',
       'mnin',
       'mni'],
 'j': ['mnj'],
 'k': ['mnk'],
 'l': ['mnl-2', 'mnl48', 'mnla', 'mnl'],
 'm': ['mnm'],
 'n': ['mnn'],
 'o': ['mnogovershinny',
       'mnogoozyorny',
       'mnogosearch',
       'mnogotochie',
       'mnouchkine',
       'mnopedia',
       'mnong',
       'mnos'],
 'p': ['mnpp', 'mnpo', 'mnp'],
 'r': ['mnra', 'mnr'],
 's': ['mnsure', 'mnsi', 'mns'],
 't': ['mntv', 'mnt'],
 'u': ['mnuphorus', 'mnuchin', 'mnu'],
 'w': ['mnw'],
 'x': ['mnx1', 'mnx'],
 'y': ['mnyamawamtuka', 'mnyenzeni', 'mnyameni', 'mnynms'],
 'z': ['mnz']}
