
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mk = {'_': ['mk-motorsport',
       'mk-0773',
       'mk-2206',
       'mk-4409',
       'mk5000c',
       'mk-2048',
       'mk-9470',
       'mk.gee',
       'mk6-83',
       'mk-608',
       'mk-212',
       'mk-386',
       'mk-1ts',
       'mk-886',
       'mk-dos',
       'mk-434',
       'mk484',
       'mk285',
       'mk10',
       'mk14',
       'mk12',
       'mk44',
       'mk4',
       'mk1',
       'mk5',
       'mk8',
       'mk2',
       'mk7',
       'mk3'],
 'a': ['mkapuwanzee',
       'mkambini',
       'mkangawi',
       'mkalles',
       'mkalamo',
       'mkansa',
       'mkapa',
       'mkasi',
       'mkak',
       'mka'],
 'b': ['mkb-42', 'mkb'],
 'c': ['mkc'],
 'd': ['mkdir', 'mkd'],
 'e': ['mkek-4', 'mkek-1', 'mkek-6', 'mker', 'mke'],
 'f': ['mkfancy', 'mkfc', 'mkfs'],
 'g': ['mkg'],
 'h': ['mkhitarashen',
       'mkhitaryan',
       'mkhedrioni',
       'mkhchyan',
       'mkhiweni',
       'mkheidze',
       "mkh'ono",
       'mkhitar',
       'mkhare',
       'mkhize'],
 'i': ['mki67ip', 'mkilua', 'mki'],
 'j': ['mkj'],
 'k': ['mkks'],
 'l': ['mklivecd', 'mklinux', 'mkleo', 'mkl1', 'mkl2', 'mkl'],
 'm': ['mkm'],
 'n': ['mknk1', 'mknk2', 'mknk', 'mkn'],
 'o': ['mkomaniboi',
       'mkokotoni',
       'mkomongo',
       'mkongani',
       'mkokoni',
       'mkomba',
       'mkonze',
       'mkoani',
       'mkoka',
       'mko'],
 'p': ['mkpat-enin', 'mkpanghi', 'mkpani', 'mkp'],
 'q': ['mkq'],
 'r': ['mkrtchyan', 'mkrtich', 'mkrn3', 'mkr'],
 's': ['mkstemp', 'mksk', 'mks1', 'mks'],
 't': ['mktemp', 'mktv', 'mkto', 'mkt'],
 'u': ['mkunguni', 'mkunumbi', 'mkuluni', 'mkushi', 'mkuze', 'mku'],
 'v': ['mkvtoolnix', 'mkv'],
 'w': ['mkwajuni', 'mkwiro', 'mkwaja', 'mkweb', 'mkw'],
 'x': ['mkx'],
 'y': ['mky'],
 'z': ['mkz']}
