
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ms = {'_': ['ms100a7a15',
       'ms-chap',
       'ms-245',
       'ms-dos',
       'ms-net',
       'ms-200',
       'ms4a7',
       'ms-ii',
       'ms4a3',
       'ms4a2',
       'ms-74',
       'ms-13',
       'ms/8',
       'ms&t',
       'ms20',
       'ms!',
       'ms4',
       'ms3',
       'ms1',
       'ms5',
       'ms.',
       'ms2',
       'ms6'],
 'a': ['msakhurtukhutsesi',
       'msangatifu',
       'msambweni',
       'msaranga',
       'msabbaha',
       'msangaji',
       'msanzala',
       'msangano',
       'msallata',
       'msamalo',
       'msabaha',
       'msasani',
       'msalato',
       'msanga',
       'msaki',
       'msabi',
       'msas',
       'msar',
       'msav',
       'msau',
       'msat',
       'msac',
       'msaa',
       'msad',
       'msa'],
 'b': ['msbuild', 'msba', 'msb'],
 'c': ['msciszewice',
       'msciecino',
       'msciszewo',
       'msciwojow',
       'mscichow',
       'msconfig',
       'msciwuje',
       'msciszow',
       'mscramm',
       'msciwoj',
       'mscgen',
       'msciow',
       'mscdex',
       'mschif',
       'mscape',
       'mscice',
       'mscml',
       'mschf',
       'mscl',
       'msca',
       'msci',
       'msce',
       'mscp',
       'mscc',
       'msco',
       'mscw',
       'msc'],
 'd': ['msdsonline', 'msdos.sys', 'msdaipp', 'msdr', 'msde', 'msdf', 'msd'],
 'e': ['msene-lazne',
       'mselliet',
       'mseleni',
       'mseibin',
       'mseke',
       'mseno',
       'mser',
       'msea',
       'msec',
       'mse'],
 'f': ['msfa', 'msft', 'msfs', 'msfc', 'msf'],
 'g': ['msg3'],
 'h': ['mshvidobauri',
       'mshamshono',
       'msheirfeh',
       'mshengu',
       'mshindo',
       'mshewa',
       'mshana',
       'mshewe',
       'mshtml',
       'mshak',
       'mshd',
       'msh3',
       'msh2',
       'msh4',
       'mshb',
       'msh5',
       'msha',
       'msh6',
       'mshs',
       'msh'],
 'i': ['msigani',
       'msimang',
       'msisdn',
       'msingi',
       'msida',
       'msila',
       'msiri',
       'msiac',
       'msipa',
       'msied',
       'msisi',
       'msil',
       'msic',
       'msia',
       'msi'],
 'j': ['msj'],
 'k': ['msk'],
 'l': ['mslabelled', 'mslgroup', 'mslexia', 'mslr', 'mslp', 'msln', 'msl'],
 'm': ['msme-champions',
       'msm/mmm',
       'msm7000',
       'msmo1',
       'msm-1',
       'msmtp',
       'msmb',
       'msmm',
       'msma',
       'msmc',
       'msms',
       'msmu',
       'msml',
       'msm'],
 'n': ['msnbot', 'msnbc', 'msn'],
 'o': ['msongola',
       'msoura',
       'msondo',
       'msoga',
       'msoki',
       'msoro',
       'msoa',
       'msor',
       'mson',
       'msop',
       'msol',
       'msov',
       'mso'],
 'p': ['mspca-angell',
       'msp360',
       'mspot',
       'mspp',
       'mspa',
       'mspb',
       'mspe',
       'mspy',
       'mspi',
       'msp'],
 'q': ['msquic', 'msql', 'msq'],
 'r': ['msrb2', 'msrb', 'msr1', 'msri', 'msra', 'msrt', 'msr'],
 's': ['msstyles',
       'mss-1.2',
       'mssta',
       'mssa',
       'mssp',
       'mssv',
       'mssm',
       'mssr',
       'mssi',
       'mssb',
       'mss'],
 't': ['mstislavsky',
       'mstsislaw',
       'mstelcom',
       'mstibovo',
       'mstrkrft',
       'mstyczow',
       'mstislav',
       'mstitel',
       'mstyora',
       'mstivoj',
       'mstowo',
       'mstar',
       'msto1',
       'mst1r',
       'mstr',
       'msts',
       'mstp',
       'msta',
       'mst1',
       'mstc',
       'mst4',
       'mst'],
 'u': ['msumarini', 'msunduzi', 'msuakini', 'msuata', 'msun', 'msus', 'msu'],
 'v': ['msv-arena', 'msvs', 'msv'],
 'w': ['mswakini', 'mswlogo', 'msw/lfg', 'mswati', 'msw'],
 'x': ['msx-engine', 'msx-dos', 'msxml', 'msx1', 'msx'],
 'y': ['msy'],
 'z': ['mszanna-kolonia',
       'mszczyczyn',
       'mszalnica',
       'mszczonow',
       'mszczuje',
       'mszanowo',
       'mszaniec',
       'mszanka',
       'mszana',
       'mszane',
       'msz96']}
