
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mp = {'_': ['mp3directcut',
       'mp3concept',
       'mp3skull',
       'mp3gain',
       'mp3.com',
       'mp-2001',
       'mp-203',
       'mp-461',
       'mp3tag',
       'mp3pro',
       'mp-pet',
       'mp3+g',
       'mp196',
       'mp808',
       'mp3hd',
       'mp10',
       'mp35',
       'mp36',
       'mp/m',
       'mp8',
       'mp2',
       'mp3',
       'mp6',
       'mp9'],
 'a': ['mpandamatenga',
       'mpavilion',
       'mpamantwa',
       'mpalanga',
       'mpasatia',
       'mpambala',
       'mpanjaka',
       'mpatgm',
       'mpanda',
       'mpande',
       'mpanga',
       'mpacc',
       'mpack',
       'mparo',
       'mpama',
       'mpaka',
       'mpact',
       'mpala',
       'mpao',
       'mpai',
       'mpas',
       'mpac',
       'mpa'],
 'b': ['mpb4', 'mpb'],
 'c': ['mpc5xx', 'mpc&a', 'mpc-1', 'mpcc', 'mpci', 'mpcv', 'mpca', 'mpc'],
 'd': ['mpdu1', 'mpds4', 'mpdz', 'mpd'],
 'e': ['mpeketoni',
       'mpedigree',
       'mpererwe',
       'mpezeni',
       'mpeg-21',
       'mpendo',
       'mpeg-h',
       'mpeg-g',
       'mpeg-7',
       'mpeg-4',
       'mpeg-1',
       'mpeg-3',
       'mpeg-d',
       'mpeg-2',
       'mpenza',
       'mpemba',
       'mpeg-a',
       'mpec',
       'mpe'],
 'f': ['mpfs', 'mpfc', 'mpf'],
 'g': ['mpges-1', 'mpges-2', 'mpg123', 'mpg'],
 'h': ['mphenyatsatsi',
       'mphe-lebeko',
       'mpholonjeni',
       'mphorosane',
       'mphosph10',
       'mphosph8',
       'mphosph1',
       'mphosph6',
       'mphasis',
       'mphande',
       'mphaki',
       'mphl',
       'mpho',
       'mphs',
       'mph'],
 'i': ['mpintsin',
       'mpingwe',
       'mpi-cdg',
       'mpingo',
       'mpich',
       'mpigi',
       'mpisi',
       'mpika',
       'mpiri',
       'mpie',
       'mpir',
       'mpic',
       'mpio',
       'mpi'],
 'k': ['mpki', 'mpk'],
 'l': ['mplayer.com',
       'mplayer',
       'mpls-tp',
       'mpl-50',
       'mplkip',
       'mplab',
       'mplc',
       'mpls',
       'mpla',
       'mpl'],
 'm': ['mpm-10', 'mpman', 'mpmc', 'mpm'],
 'n': ['mpns', 'mpn'],
 'o': ['mpowerplayer',
       'mpophomeni',
       'mporokoso',
       'mpowerfm',
       'mpondwe',
       'mpopoma',
       'mponela',
       'mpombo',
       'mpouya',
       'mpower',
       'mpofu',
       'mpozo',
       'mpoti',
       'mpo'],
 'p': ['mpps',
       'mppc',
       'mpp1',
       'mppe',
       'mpp6',
       'mppf',
       'mpp5',
       'mppa',
       'mpp+',
       'mpp2',
       'mppl',
       'mpp'],
 'q': ['mpqc', 'mpq'],
 'r': ['mproductive',
       'mpraeso',
       'mpress',
       'mpr500',
       'mprim',
       'mpro',
       'mprp',
       'mprf',
       'mpri',
       'mpr'],
 's': ['mpsolve', 'mpstat', 'mpsa', 'mpsc', 'mps'],
 't': ['mpt-1327', 'mpt8080', 'mptc', 'mptp', 'mpta', 'mpt'],
 'u': ['mpumalanga',
       'mpulungu',
       'mpunguzi',
       'mpu-401',
       'mpuguso',
       'mpungu',
       'mpuat',
       'mpumi',
       'mpura',
       'mputu',
       'mpu'],
 'v': ['mpv17', 'mpva', 'mpv'],
 'w': ['mpwayungu', 'mpwapwa', 'mpwh', 'mpw'],
 'x': ['mpxplay', 'mpx'],
 'y': ['mpys'],
 'z': ['mpzl1']}
