
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mf = {'_': ['mf59'],
 'a': ['mfalikuivahaas',
       "mfaz'omnyama",
       'mfantseman',
       'mfarakeh',
       'mfap5',
       'mfap2',
       'mfans',
       'mfap1',
       'mfap4',
       'mfap',
       'mfac',
       'mfa'],
 'b': ['mfbty', 'mfb'],
 'c': ['mfcc', 'mfc'],
 'd': ['mfd'],
 'e': ['mfecane', 'mfezi', 'mfem', 'mfe'],
 'f': ['mffa', 'mff'],
 'g': ['mfg.com', 'mfge8', 'mfg'],
 'h': ['mfhs', 'mfh'],
 'i': ['mfilou', 'mfi'],
 'j': ['mfj'],
 'l': ['mfluids@home', 'mflow', 'mfl'],
 'm': ['mfm'],
 'n': ['mfn1', 'mfng', 'mfn2', 'mfn'],
 'o': ['mformation', 'mfo-park', 'mfoundi', 'mfone', 'mfon', 'mfou', 'mfo'],
 'p': ['mfpvp', 'mfps', 'mfp'],
 'q': ['mfq'],
 'r': ['mfrp', 'mfr'],
 's': ['mfsd14b',
       'mfsd4a',
       'mfsd11',
       'mfsd6l',
       'mfsd1',
       'mfsd7',
       'mfsd8',
       'mfsd3',
       'mfsd5',
       'mfsd2',
       'mfsb',
       'mfsa',
       'mfs'],
 't': ['mft'],
 'u': ['mfuleni', 'mfumuni', 'mfuwe', 'mfu'],
 'w': ['mfw'],
 'z': ['mfzb']}
