
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mj = {'_': ['mj/kg'],
 'a': ['mjavatnet',
       'mjamaoue',
       'mjalton',
       'mjavatn',
       'mjallby',
       'mjallom',
       'mjaft!'],
 'b': ['mjb'],
 'c': ['mjc'],
 'd': ['mjd'],
 'e': ['mjellknapp',
       'mjehovina',
       'mjellegga',
       'mjedenik',
       'mjesaji',
       'mjelde',
       'mjekic',
       'mjets',
       'mjet',
       'mje'],
 'h': ['mjhs'],
 'i': ['mjimandra', 'mjini', 'mjil'],
 'j': ['mjj'],
 'k': ['mjk'],
 'l': ['mjl'],
 'n': ['mjn'],
 'o': ['mjolkedalstinden',
       'mjolkursamsalan',
       'mjosundvatnet',
       'mjolnerparken',
       'mjogsjooksli',
       'mjorkadalur',
       'mjoifjordur',
       'mjogsjohoi',
       'mjolkudden',
       'mjostarnet',
       'mjolfjell',
       'mjondalen',
       'mjolvik',
       'mjohult',
       'mjolnir',
       'mjoback',
       'mjolhus',
       'mjolner',
       'mjoberg',
       'mjomna',
       'mjovik',
       'mjolko',
       'mjonas',
       'mjolby',
       'mjosa',
       'mjos'],
 'p': ['mjp'],
 'q': ['mjq'],
 'r': ['mjr'],
 's': ['mjs'],
 't': ['mjt'],
 'u': ['mjukkaka', 'mjuken', 'mju'],
 'w': ['mjw']}
