
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rf = {'_': ['rf&p_subdivision',
       'rf_micropower',
       'rf_modulator',
       'rf_connector',
       'rf_planning',
       'rf_engines',
       'rf_switch',
       'rf_factor',
       'rf_module',
       'rf_online',
       'rf_probe',
       'rf_chain',
       'rf_cmos'],
 'a': ['rfa_brambleleaf',
       'rfa_derwentdale',
       'rfa_freshspring',
       'rfa_orangeleaf',
       'rfa_cherryleaf',
       'rfa_tidespring',
       'rfa_resurgent',
       'rfa_tidesurge',
       'rfa_northmark',
       'rfa_appleleaf',
       'rfa_ennerdale',
       'rfa_abbeydale',
       'rfa_cedardale',
       'rfa_salvestor',
       'rfa_plumleaf',
       'rfa_tiderace',
       'rfa_darkdale',
       'rfa_dewdale',
       'rfa_bayleaf',
       'rfa_reliant',
       'rfa_oakleaf',
       'rfa_bacchus',
       'rfa_rowanol',
       'rfa_arndale',
       'rfa_turmoil',
       'rfa_scotol',
       'rfa_abadol',
       'rfa_olwen',
       'rfactor_2',
       'rfa_oakol',
       'rfa_maine',
       'rfa_olna'],
 'b': ['rfb_fantrainer', 'rfb_protocol', 'rfb_x-113', 'rfb_x-114'],
 'c': ['rfc_marjamaa', 'rfc_haarlem', 'rfc_raiders', 'rfc_liege'],
 'd': ['rfdg_insurgency'],
 'e': ['rfem', 'rfe'],
 'f': ['rffsa', 'rffe', 'rffl', 'rffc', 'rff'],
 'g': ['rfg'],
 'h': ['rfhs', 'rfh'],
 'i': ['rfid_skimming', 'rfid_journal', 'rfid_testing', 'rfi_romania'],
 'j': ['rfj'],
 'k': ['rfk_majdanpek', 'rfk_racing', 'rfk_riga'],
 'l': ['rfl_championship'],
 'm': ['rfm-swift_hotdogs', 'rfm_corporation', 'rfm_somnii'],
 'n': ['rfns_savenaca', 'rfns_volasiga', 'rfns_kacau'],
 'o': ['rfo'],
 'p': ['rfpl3-as1', 'rfpolicy', 'rfpio', 'rfpro'],
 'q': ['rfq'],
 'r': ['rfr_engineers'],
 's': ['rfs'],
 't': ['rftt', 'rft1', 'rft'],
 'u': ['rfu_championship', 'rfuea_ground'],
 'v': ['rfv'],
 'w': ['rfwd2', 'rfw'],
 'x': ['rfxank',
       'rfxap',
       'rfx2',
       'rfx6',
       'rfx1',
       'rfx4',
       'rfx5',
       'rfx3',
       'rfx']}
