
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zg = {'_': ['zg16', 'zg80'],
 'a': ['zgagowo-wies', 'zgardesti', 'zgalisce', 'zganci'],
 'b': ['zgb'],
 'c': ['zgc'],
 'e': ['zgerdhesh', 'zge-fm'],
 'f': ['zgfm', 'zgf'],
 'g': ['zgg'],
 'h': ['zghurivka', 'zgharta', 'zghira', 'zgheib', 'zgh'],
 'i': ['zgierszczanskie', 'zgierzynka', 'zgierz', 'zgi'],
 'l': ['zgliczyn-pobodzy',
       'zgliczyn-glinki',
       'zglenice-budy',
       'zglenicki',
       'zglavnica',
       'zglechow',
       'zglobice',
       'zglobien',
       'zgliniec'],
 'n': ['zgnilobloty', 'zgnilocha', 'zgnilka'],
 'o': ['zgorzynskie',
       'zgorzalowo',
       'zgorzelec',
       'zgorznica',
       'zgorzala',
       'zgorzale',
       'zgonjevo',
       'zgojewko',
       'zgojewo',
       'zgorze',
       'zgosca',
       'zgonce',
       'zgoda',
       'zgosa',
       'zgon'],
 'p': ['zgpat'],
 'r': ['zgrzebichy', 'zgrade', 'zgrf1'],
 's': ['zgs'],
 'u': ['zgurovo', 'zgurita'],
 'v': ['zgv']}
