
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rc = {'_': ['rc-o319',
       'rc-48',
       'rc3h1',
       'rc15',
       'rc44',
       'rc-1',
       'rc-5',
       'rc4',
       'rc5',
       'rc2',
       'rc3',
       'rc9',
       'rc6'],
 'a': ['rcase', 'rcan2', 'rcan3', 'rcac', 'rcar', 'rca'],
 'b': ['rcbtb2', 'rcbtb1', 'rcbc', 'rcb'],
 'c': ['rccx', 'rcca', 'rcc2', 'rcc1', 'rccs', 'rccc', 'rcc'],
 'd': ['rcdc', 'rcds', 'rcde', 'rcd'],
 'e': ['rce1', 'rcet', 'rce'],
 'f': ['rcfile', 'rcfc', 'rcf'],
 'g': ['rcgc', 'rcga', 'rcg'],
 'h': ['rcheulishvili', 'rchy1', 'rchs', 'rchm', 'rch'],
 'i': ['rcirc', 'rcis', 'rcic', 'rci'],
 'j': ['rcj'],
 'k': ['rck-2'],
 'l': ['rclone', 'rcl1', 'rcls', 'rcl'],
 'm': ['rcms', 'rcm'],
 'n': ['rcn'],
 'o': ['rcor1', 'rcoa', 'rcos', 'rco'],
 'p': ['rcp9', 'rcpd', 'rcps', 'rcpi', 'rcp'],
 'r': ['rcrc', 'rcrs', 'rcrg', 'rcrd', 'rcr'],
 's': ['rcsi-bahrain',
       'rcs-8',
       'rcs-4',
       'rcsl',
       'rcsa',
       'rcss',
       'rcsc',
       'rcsd',
       'rcs'],
 't': ['rctt', 'rctc', 'rctv', 'rcti', 'rct'],
 'u': ['rcuda', 'rcuv', 'rcu'],
 'v': ['rcv-9', 'rcvs', 'rcvr', 'rcv'],
 'w': ['rcwp', 'rcw'],
 'x': ['rcx'],
 'y': ['rcyc']}
