
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bf = {'_': ['bf_antliae', 'bf_orionis', 'bf_model'],
 'a': ['bfast', 'bfa'],
 'b': ['bfbs_lisburn'],
 'c': ['bfc_daugavpils',
       'bfc_nordstern',
       'bfc_frankfurt',
       'bfc_preussen',
       'bfc_sudring',
       'bfc_siofok'],
 'd': ['bfd'],
 'e': ['bfe'],
 'f': ['bff_girls'],
 'g': ['bfg_technologies'],
 'h': ['bfhs', 'bfh'],
 'i': ['bfi_southbank', 'bfi_flipside', 'bfi_gallery', 'bfi_imax'],
 'j': ['bfj'],
 'l': ['bflix_movies', 'bfl_group'],
 'm': ['bfm_business', 'bfm_regions', 'bfm_89.9', 'bfm_tv'],
 'n': ['bfn'],
 'o': ['bford_9'],
 'p': ['bfpp', 'bfp'],
 'q': ['bfq'],
 'r': ['bfr_algorithm'],
 's': ['bfs_group'],
 't': ['bfta', 'bft'],
 'u': ['bfu'],
 'v': ['bfv'],
 'w': ['bfw_m.26',
       'bfw_m.21',
       'bfw_m.31',
       'bfw_m.20',
       'bfw_m.29',
       'bfw_cl.i',
       'bfw_m.22',
       'bfw_m.23',
       'bfw_m.19',
       'bfw_m.35',
       'bfw_m.27',
       'bfw_n.i'],
 'x': ['bfx'],
 'y': ['bfy'],
 'z': ['bfz']}
