
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dl = {'_': ['dl_skateboards',
       'dl&w_station',
       'dl_incognito',
       'dl_holdings',
       'dl_crucis',
       'dl_series',
       'dl_class',
       'dl_boost',
       'dl_group',
       'dl_tauri',
       'dl_jones',
       'dl_hall'],
 'a': ["dlawer_ala'aldeen",
       'dlaboka_river',
       'dlagnya_rocks',
       'dlapkin_dol',
       'dla_piper'],
 'b': ['dlbd', 'dlb'],
 'c': ['dlc1', 'dlc'],
 'd': ['dld/np1', 'dld'],
 'e': ['dleskovec_plateau', 'dle_yaman'],
 'f': ['dlf'],
 'g': ['dlg2-as1',
       'dlgap2',
       'dlgap5',
       'dlgap4',
       'dlgap1',
       'dlg5',
       'dlg2',
       'dlg4',
       'dlg1',
       'dlg3',
       'dlg'],
 'h': ['dlhe_klcovo', 'dlhe_straze', 'dlhe_diely', 'dlhe_pole', 'dlha_ves'],
 'i': ['dlinnoye_lake'],
 'j': ['dljin', 'dlj'],
 'k': ['dlk1', 'dlk'],
 'l': ['dll_injection', 'dll_group', 'dll_hell'],
 'm': ['dlma_analysis', 'dlm_forum'],
 'o': ['dlouha_brtnice',
       'dlouha_trebova',
       'dlouha_loucka',
       'dlouhy_ujezd',
       'dlouha_lhota',
       'dlouha_stran',
       'dlouhy_most',
       'dlouha_ves'],
 'p': ['dlp'],
 'r': ['dlr_smartfish',
       'dlr_lexicon',
       'dlr_waves',
       'dlr_group',
       'dlr_band',
       'dlr_hy4'],
 's': ['dlshad_othman', 'dls_format'],
 't': ['dlt_solutions'],
 'u': ['dlugowola_pierwsza',
       'dlugoborz_pierwszy',
       'dlugie_grodzieckie',
       'dlugie_kamienskie',
       'dlusko_gryfinskie',
       'dluga_szlachecka',
       'dlugoleka_wielka',
       'dlugopole_gorne',
       'dlugoborz_drugi',
       'dluga_koscielna',
       'dlugopole_dolne',
       'dlugowola_druga',
       'dlugokaty_male',
       'dluga_brzezina',
       'dlugie_grzymki',
       'dluzniewo_duze',
       'dluzec_wielki',
       'dluzyna_dolna',
       'dluga_goslina',
       'dluzyna_gorna',
       'dlugie_stare',
       'dlugi_kierz',
       'dlugie_nowe',
       'dluga_gorka',
       'dluzec_maly',
       'dlugi_lasek',
       'dlugi_borek',
       'dlugie_pole',
       'dluska_wola',
       'dlugi_targ',
       'dlugi_most',
       'dlugi_lug',
       'dlugi_kat'],
 'v': ['dlvo_theory'],
 'w': ['dlw'],
 'x': ['dlx6-as1', 'dlx2', 'dlx1', 'dlx5', 'dlx4', 'dlx6', 'dlx3', 'dlx'],
 'y': ['dlya_millionov'],
 'z': ['dlzin']}
