
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dc = {'_': ['dc/wildstorm:_dreamwar',
       'dc-to-dc_converter',
       'dc_bank/probaclac',
       'dc-jam_records',
       'dc_rollergirls',
       'dc_retroactive',
       'dc_adventures',
       'dc_circulator',
       'dc9_nightclub',
       'dc_chronicles',
       'dc_presidents',
       'dc-14_phantom',
       'dc_implosion',
       'dc_streetcar',
       'dc_connector',
       'dc_defenders',
       'dc_countdown',
       'dc_challenge',
       'dc_rainmaker',
       'dc_cupcakes',
       'dc_releases',
       'dc_universe',
       'dc_trident',
       'dc_fandome',
       'dc_studios',
       'dc_cowboys',
       'dc_rebirth',
       'dc_pierson',
       'dc_circuit',
       'dc_omnibus',
       'dc_virunga',
       'dc_special',
       'dc_thomson',
       'dc_inside',
       'dc_breeze',
       'dc_heroes',
       'dc_rajesh',
       'dc_breaks',
       'dc_towers',
       'dc_minyan',
       'dc_direct',
       'dc_divest',
       'dc_comics',
       'dc_avanti',
       'dc_nation',
       'dc_daily',
       'dc_solar',
       'dc_block',
       'dc_shoes',
       'dc_drake',
       'dc_moore',
       'dc_books',
       'dc_films',
       'dc_motor',
       'dc_talk',
       'dc_mara',
       'dc_bias',
       'dc_usa',
       'dc_ep'],
 'a': ['dca_agar'],
 'b': ['dcbl_stadium', 'dcb_bank'],
 'c': ['dcc_alliance', 'dcc_racing', 'dcc_plc'],
 'd': ['dcd_publishing', 'dcd2_records', 'dcd_media', 'dcd_group'],
 'e': ['dcethreads', 'dce/rpc', 'dceased', 'dcebus', 'dce'],
 'f': ['dcf_advertising'],
 'g': ['dcg-iv', 'dcgs', 'dcgo', 'dcg'],
 'h': ['dchs1', 'dchs2', 'dchs', 'dchp', 'dche', 'dch'],
 'i': ['dciriku_language', 'dci_banks', 'dci_group'],
 'k': ['dckt_contemporary'],
 'l': ['dcleaks', 'dclre1a', 'dclre1b', 'dclk1', 'dcls', 'dcl1', 'dclp', 'dcl'],
 'm': ['dcmp_deaminase', 'dcm_ventures', 'dcmp_kinase', 'dcm_trophy'],
 'n': ['dcns', 'dcn'],
 'o': ['dconstructed', 'dcourseweb', 'dconf', 'dcop', 'dcos', 'dcom', 'dco'],
 'p': ['dcp1b', 'dcp1a', 'dcpg', 'dcps', 'dcpo', 'dcpl', 'dcp2', 'dcpa', 'dcp'],
 'r': ['dcr_workforce'],
 's': ['dcs_europe'],
 't': ['dctp_diphosphatase', 'dctp_deaminase', 'dct_gdansk'],
 'u': ['dcuc_family', 'dcu_saints', 'dcu_center', 'dcu_family', 'dcu_gaa'],
 'v': ['dcv_balder', 'dcv_aegir'],
 'w': ['dcw234', 'dcw'],
 'x': ['dcx3', 'dcx'],
 'y': ['dcypha_productions']}
