
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_db = {'_': ['db_station&service',
       'db-engines_ranking',
       'db_fernverkehr',
       'db_projektbau',
       'db_boulevard',
       'db2_database',
       'db_insurance',
       'db_breweries',
       'db_ligature',
       'db_networks',
       'db_schenker',
       'db_services',
       'db_vertrieb',
       'db_burkeman',
       'db_autozug',
       'db_records',
       'db_group',
       'db_netze',
       'db_regio',
       'db_cargo',
       'db_corp',
       'db_netz',
       'db_draw',
       'db_bahn',
       'db_601'],
 'a': ['dbar_problem', 'dbase_mac'],
 'b': ['dbb'],
 'c': ['dbc_houthalen', 'dbc_pierre', 'dbc_news', 'dbc_1012'],
 'd': ['dbdnv', 'dbdmh', 'dbdos', 'dbd'],
 'e': ['dbew_competition'],
 'f': ['dbf4', 'dbfs', 'dbfc', 'dbfx', 'dbf'],
 'g': ['dbgallery', 'dbgp', 'dbg'],
 'h': ['dbhs', 'dbh'],
 'i': ['dbix::class', 'dbit', 'dbi'],
 'j': ['dbj'],
 'k': ['dbkl_s.c.'],
 'l': ['dbl_arena'],
 'm': ['dbmaestro', 'dbmotion', 'dbm0', 'dbm'],
 'n': ['dbndd2', 'dbndns', 'dbnpa', 'dbn1', 'dbnl', 'dbna', 'dbn'],
 'o': ['dbomp', 'dbox2', 'dbox', 'dbo'],
 'p': ['dbpm_records'],
 'q': ['dbq'],
 'r': ['dbridge', 'dbr1', 'dbrs', 'dbrn', 'dbr'],
 's': ['dbs_bank'],
 't': ['dbtss', 'dbtel', 'dbtt', 'dbt'],
 'u': ['dbu_copenhagen',
       'dbu_bornholm',
       'dbu_zealand',
       'dbu_jutland',
       'dbu_bredde',
       'dbu_funen'],
 'v': ['dbv_technologies'],
 'x': ['dbx1', 'dbx2', 'dbx'],
 'y': ['dby'],
 'z': ['dbz']}
