
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nc = {'_': ["nc'nean_distillery",
       'nc_vouliagmeni',
       'nc_graphics',
       'nc10_phylum',
       'nc_machine',
       'nc-4_medal',
       'nc2_global',
       'nc_ratio',
       'nc_dinos',
       'nc_chios',
       'nc_magra',
       'nc3_dmu',
       'nc_live'],
 'a': ['ncamagoro_constituency',
       'ncaa_independents',
       'ncaa_gamebreaker',
       'ncaa_productions',
       'ncaa_volleyball',
       'ncaa_tournament',
       'ncandu_falls'],
 'b': ['ncbi_epigenomics', 'ncb_radio', 'ncb_group'],
 'c': ['ncc_education', 'ncc_group', 'ncc_open', 'ncc_bank'],
 'd': ['ncdn', 'ncda', 'ncds', 'ncdc', 'ncdr', 'ncdu', 'ncd'],
 'e': ['ncep/ncar_reanalysis',
       'ncell_football',
       'ncedile_saule',
       'nceba_hinana',
       'ncema_river',
       'ncell_cup'],
 'f': ['ncflyports',
       'ncftpd',
       'ncftp',
       'ncfta',
       'ncf1c',
       'ncfc',
       'ncfe',
       'ncf'],
 'g': ['ncgs', 'ncgr', 'ncga', 'ncg'],
 'h': ['nchelenge_district',
       'nchumbulu_language',
       'nchimunya_mweetwa',
       'ncholu_monontsi',
       'nch_corporation',
       'nchanga_stadium',
       'nchawaka_saili',
       'nchifor_valery',
       'nchwaning_mine',
       'nchanga_mines',
       'nch_software',
       'nchum_bafut',
       'nchare_yen',
       'ncha_derby',
       'nchu_uav'],
 'i': ['nci_metathesaurus', 'ncincilili_titi', 'ncis:_hawai`i', 'ncis:_sydney'],
 'k': ['ncku_imba'],
 'l': ['ncl_eclipse'],
 'm': ['ncmc', 'ncma', 'ncmi', 'ncmh', 'ncmp', 'ncmm', 'ncm'],
 'n': ['ncna', 'ncnd', 'ncnc', 'ncn'],
 'o': ['ncoza_dlova', 'ncora_dam', 'nco_group'],
 'p': ['ncp_engineering'],
 'r': ['ncr_self-service',
       'ncr_corporation',
       'ncr_voyager',
       'ncr_silver',
       'ncr_53c9x',
       'ncr_cram',
       'ncr_5380',
       'ncr_304',
       'ncr_vrx',
       'ncr_315'],
 's': ['ncsl_international',
       'ncsist_albatross',
       'ncsist_cardinal',
       'ncs:_manhunt',
       'ncsa_telnet',
       'ncsa_httpd',
       'ncs_group'],
 't': ['nct_discography',
       'nct_videography',
       'nct_dream',
       'nct_life',
       'nct_127'],
 'u': ['ncuncuni_constituency', 'ncuti_gatwa'],
 'v': ['ncvs', 'ncv'],
 'w': ['ncw_libraries']}
