
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_np = {'_': ['np-holin_family'],
 'a': ['npa_pythons'],
 'b': ['npbl'],
 'c': ['npc_international'],
 'd': ['npdgamma_experiment'],
 'e': ['npepps', 'npes', 'npe'],
 'f': ['npfl', 'npf'],
 'g': ['npg_records'],
 'h': ['nph_insulin', 'nph_usa'],
 'i': ['npiw_sindh', 'npi_media'],
 'j': ['npj'],
 'l': ['npl_network'],
 'm': ['npm,_inc.', 'npm_group'],
 'n': ['npn'],
 'o': ['npo_mashinostroyeniya',
       'npo_avtomatiki',
       'npo_tekhnomash',
       'npo_energomash',
       'npo_zappelin',
       'npo_molniya',
       'npo_novator',
       'npo_bazalt',
       'npo_nieuws',
       'npo_almaz',
       'npo_toriy',
       'npo_elsib',
       'npo_sport',
       'npo_orion',
       'npo_splav',
       'npo_zapp',
       'npo_3fm',
       'npo_doc',
       'npo_3',
       'npo_1',
       'npo_2'],
 'p': ['npp_zvezda', 'npp_istok', 'npp_start'],
 'r': ['nprotect_gameguard',
       'npr_controversies',
       'npr_playhouse',
       'npr_berlin',
       'npr_music'],
 's': ['nps_medicinewise'],
 't': ['nptc_group'],
 'u': ['npu_terminology'],
 'v': ['npv_oryx'],
 'w': ['npws', 'npw'],
 'y': ['npy'],
 'z': ['npz_model']}
