
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nr = {'_': ['nr_vulpeculae', 'nr-1_sinkhole', 'nr_brunel', 'nr_group', 'nr._10'],
 'a': ['nratv', 'nrank', 'nram', 'nras', 'nrap'],
 'b': ['nrb_touggourt', 'nrb_bearing', 'nrb_bank', 'nrb_tv'],
 'c': ['nrc_handelsblad', 'nrca_stadium', 'nrc_school', 'nrc_next'],
 'd': ['nrds_dhamdhama'],
 'e': ['nre_3gs24c-de-au',
       'nre_2gs36c-de',
       'nre_2gs16b-au',
       'nre_e-3000e3b',
       'nre_2gs12b',
       'nre_2gs14b',
       'nre_3gs21c',
       'nre_3gs21b',
       'nre_1gs7b'],
 'f': ['nrf_championship', 'nrf_foundation', 'nrf51_series'],
 'g': ['nrg_engineering',
       'nrg_networks',
       'nrg_ensemble',
       'nrg_esports',
       'nrg_station',
       'nrg_stadium',
       'nrg_center',
       'nrg_energy',
       'nrg_arena',
       'nrg_media',
       'nrg_park'],
 'h': ['nrh2o', 'nrhs', 'nrh'],
 'i': ['nripati_chattopadhyay',
       'nripen_chakraborty',
       'nripendra_narayan',
       'nripendra_misra',
       'nripesh_biswas',
       'nripen_goswami',
       'nring_circuit',
       'nrist_uav',
       'nriam_uav'],
 'j': ['nrj_russia', 'nrj_group', 'nrj_12'],
 'k': ['nrk_folkemusikk',
       'nrk_stortinget',
       'nrk_tegnsprak',
       'nrk_klassisk',
       'nrk_aktivum',
       'nrk_trojan',
       'nrk_sapmi',
       'nrk_super',
       'nrk_sport',
       'nrk_jazz',
       'nrk_news',
       'nrk_p13',
       'nrk_p1+',
       'nrk_p1',
       'nrk_p2',
       'nrk_p3'],
 'l': ['nrl_supercoach',
       'nrl_judiciary',
       'nrl_under-20s',
       'nrl_victoria',
       'nrl_tasmania',
       'nrl_nines',
       'nrl_360'],
 'm': ['nrma', 'nrm'],
 'n': ['nrnadzor', 'nrn1', 'nrn'],
 'o': ['nrounde', 'nroff', 'nron', 'nroc', 'nro'],
 'p': ['nrp_adamastor', 'nrp_espadarte', 'nrp_dao'],
 'r': ['nrrf_rna'],
 's': ['nrs_process'],
 't': ['nrt_news'],
 'u': ['nrusinghanath_temple', 'nrupatunga_award', 'nru_nsukka'],
 'v': ['nrv'],
 'w': ['nrw_holdings', 'nrw_trophy', 'nrw_forum'],
 'x': ['nrxn2', 'nrxn1', 'nrxn3', 'nrx'],
 'y': ['nry'],
 'z': ['nrz']}
