
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ns = {'_': ['ns/ep_telecommunications',
       'ns_kamporganisasjon',
       'ns_railinfratrust',
       'ns_international',
       'ns_manedshefte',
       'ns2-3_protease',
       'ns5b_inhibitor',
       'ns_motorcycle',
       'ns_solutions',
       'ns_brukkaros',
       'ns_stations',
       'ns_savannah',
       'ns_elephant',
       'ns_railway',
       'ns_concord',
       'ns_puppis',
       'ns_daures',
       'ns_basic',
       'ns_dd-ar',
       'ns0_cell',
       'ns_4000',
       'ns_3900',
       'ns_3300',
       'ns_5300',
       'ns_line',
       'ns_3700',
       'ns_6000',
       'ns_5600',
       'ns_mura',
       'ns_4300',
       'ns_7600',
       'ns_3850',
       'ns_1900',
       'ns_5000',
       'ns_8500',
       'ns_3400',
       'ns_7100',
       'ns_6100',
       'ns_3600',
       'ns_3500',
       'ns_virm',
       'ns_7700',
       'ns_93'],
 'a': ['nsambya_hospital',
       'nsa_cryptography',
       'nsaka_university',
       'nsanje_district',
       'nsama_district',
       'nsanje_airport',
       'nsang_dilong',
       'nsana_simon',
       'nsala_soup',
       'nsah_mala'],
 'b': ['nsb_biltrafikk', 'nsb_wlab-2', 'nsb_agenda', 'nsb_b5'],
 'c': ['nscad_university',
       'nsc_nijkerk',
       'nsc_united',
       'nsc_162/2',
       'nsc_68',
       'nsc_tv'],
 'd': ['nsdhl', 'nsds', 'nsd1', 'nsdg', 'nsdl', 'nsdp', 'nsd'],
 'e': ['nsenga_language',
       'nse_ekpenyong',
       'nsenga_people',
       'nse_ikpe-etim',
       'nsei_language',
       'nse_indices',
       'nse_emerge',
       'nsel_case',
       'nse_ufot'],
 'f': ['nsf_international'],
 'g': ['nsg_mouse'],
 'h': ['nshan_beshiktashlian',
       'nshan_topouzian',
       'nshan_erzrumyan',
       'nshan_munchyan'],
 'i': ['nsiika,_uganda',
       'nsimba_webster',
       'nsite_software',
       'nsikak_eduok',
       'nsi_runavik',
       'nsima_ekere',
       'nsiah_asare',
       'nsima_peter',
       'nsi_kwilu'],
 'j': ['nsjv'],
 'k': ['nsk_ltd.'],
 'l': ['nsl_cup'],
 'm': ['nsmce4a', 'nsmm', 'nsmb', 'nsma', 'nsmc', 'nsm'],
 'n': ['nsna', 'nsn'],
 'o': ['nsongo_language',
       'nsoko_airfield',
       'nsong_village',
       'nso_language',
       'nso_people',
       'nso_spirit',
       'nso_group',
       'nsong_hq'],
 'p': ['nsport+',
       'nspace',
       'nspcl',
       'nspca',
       'nspf',
       'nspw',
       'nspc',
       'nspr',
       'nspm',
       'nsps',
       'nsp'],
 'r': ['nsrdc_bqm-108', 'nsrgnts_rmxs'],
 's': ['nss_annapolis', 'nssl_doppler'],
 't': ['nstigate_games', 'nstg_aussig', 'nst_minimum', 'nstg_asch'],
 'u': ['nsungwe_formation',
       'nsu_motorenwerke',
       'nsumbu_mazuwa',
       'nsu_challenge',
       'nsukka_group',
       'nsu_sulmobil',
       'nsu_station',
       'nsu_quickly',
       'nsu_spider',
       'nsu_prinz'],
 'v': ['nsvs_14256825', 'nsv_1436'],
 'w': ['nsw_lotteries',
       'nsw_trainlink',
       'nsw/act_rams',
       'nsw_maritime',
       'nsw_marines',
       'nsw_wallaby',
       'nsw_kiama',
       'nsw_burra',
       'nsw_pride',
       'nsw_cup'],
 'x': ['nsx'],
 'y': ['nsync_discography'],
 'z': ['nsz']}
