
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nw = {'_': ['nw_elektromobil',
       'nw_rennzweier',
       'nw_natural',
       'nw_raiders',
       'nw_puppis',
       'nw_rota-1',
       'nw_e',
       'nw_s',
       'nw_b',
       'nw_c',
       'nw_j',
       'nw_f',
       'nw_d'],
 'a': ['nwakanwa_chimaobi',
       'nwanneka_okwelogu',
       'nwabueze_nwokolo',
       'nwankwo_tochukwu',
       'nwa_mid-america',
       'nwabisa_makunga',
       'nwa_powerrrtrip',
       'nwave_pictures',
       'nwagi_festival',
       'nwankwo_obiora',
       'nwanedi_river',
       'nwa_empowerrr',
       'nwa_bloodfest',
       'nwando_achebe',
       'nwa_shockwave',
       'nwa_hollywood',
       'nwa_wildside',
       'nwankwo_kanu',
       'nwafor_orizu',
       'nwanedi_dam',
       'nwa_powerrr',
       'nwa,_kale',
       'nwa_baby',
       'nwa_usa'],
 'b': ['nwbl', 'nwb'],
 'c': ['nwchem', 'nwc'],
 'd': ['nwda', 'nwd1', 'nwd'],
 'e': ['nwenaing', 'nweyon', 'nweamo', 'nwedan', 'nweke', 'nwea', 'nwe'],
 'f': ['nwfl_premiership'],
 'h': ['nwhl', 'nwhs', 'nwh'],
 'i': ['nwipe', 'nwi'],
 'l': ['nwlink', 'nwl'],
 'm': ['nwm'],
 'n': ['nwn'],
 'o': ['nwoya_district', 'nworie_river', 'nwogu,_ghana'],
 'p': ['nwpu_uav'],
 'r': ['nwra', 'nwr'],
 's': ['nwsl_expansion',
       'nwsl_playoffs',
       'nws_holdings',
       'nwsl_awards',
       'nwsl_shield',
       'nwsl_draft'],
 't': ['nwt_squash'],
 'u': ['nwu_astro'],
 'w': ['nww'],
 'x': ['nwx'],
 'y': ['nwya_devu']}
