
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nf = {'_': ['nf-kappa-b-activating_protein', 'nf_magazine'],
 'a': ['nfa_minimization', 'nfat_uavs'],
 'b': ['nfbsk', 'nfb'],
 'c': ['nfc_south', 'nfc_north', 'nfc_west', 'nfc_east'],
 'd': ['nfda', 'nfdc', 'nfd'],
 'e': ['nfernelson', 'nfe2l1', 'nfe2l2', 'nfe2l3', 'nfepp', 'nfe2', 'nfe'],
 'f': ['nfff', 'nffa', 'nff'],
 'g': ['nfg'],
 'h': ['nfhs'],
 'i': ['nfi_group', 'nfilm_hd'],
 'k': ['nfkbil1',
       'nfkbie',
       'nfkbiz',
       'nfkbid',
       'nfkbib',
       'nfkb2',
       'nfkb1',
       'nfk'],
 'l': ['nfl_scoreboard',
       'nfl_preseason',
       'nfl_primetime',
       'nfl_slimetime',
       'nfl_challenge',
       'nfl_classics',
       'nfl_showdown',
       'nfl_playoffs',
       'nfl_superpro',
       'nfl_insiders',
       'nfl_gameday',
       'nfl_country',
       'nfl_matchup',
       'nfl_network',
       'nfl_redzone',
       'nfl_lockout',
       'nfl_street',
       'nfl_xtreme',
       'nfl_europe',
       'nfl_london',
       'nfl_replay',
       'nfl_series',
       'nflpa_game',
       'nfl_honors',
       'nfl_films',
       'nfl_blitz',
       'nfl_fever',
       'nfl_tour',
       'nfl_live',
       'nfl_cup',
       "nfl_'97",
       'nfl_2k3',
       "nfl_'95",
       'nfl_2k1',
       'nfl_2k2',
       'nfl_am',
       'nfl_uk',
       'nfl_2k'],
 'n': ['nfn'],
 'o': ['nforce_600', 'nforce_700', 'nforce_500'],
 'p': ['nfp-labour_coalition',
       'nfpa_1901',
       'nfpa_1001',
       'nfpa_1670',
       'nfpa_1123',
       'nfpa_1006',
       'nfpa_1600',
       'nfpa_70e',
       'nfpa_805',
       'nfpa_704',
       'nfpa_921',
       'nfpa_70b',
       'nfpa_72'],
 'r': ['nfr-90', 'nfrkb', 'nfra', 'nfr'],
 's': ['nfs1', 'nfsr', 'nfsm', 'nfsu', 'nfs'],
 't': ['nfta_fleet'],
 'u': ['nfu_mutual'],
 'v': ['nfv'],
 'w': ['nfw_e.ii', 'nfw_e.i'],
 'x': ['nfx1'],
 'y': ['nfyb', 'nfya', 'nfyc'],
 'z': ['nfz']}
