
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yl = {'_': ['yl_ventures'],
 'a': ['ylaire_joachim', 'ylan_gomes'],
 'b': ['ylber_ramadani', 'ylbh_leader', 'ylber_sefa', 'ylber_hysa'],
 'c': ['ylc-15_radar', 'ylc-2_radar', 'ylc-6_radar', 'ylc-4_radar'],
 'd': ['yldiz_pollack-beighle'],
 'e': ['yleinen_tyottomyyskassa',
       'ylenja_lucaselli',
       'ylenia_carabott',
       'ylenia_carrisi',
       'ylena_in-albon',
       'ylenia_padilla',
       'yledigao_river',
       'ylenia_scapin',
       'yleem_poblete',
       'ylen_aamu-tv',
       'yle_uutiset',
       'yle_nyheter',
       'yle_oddasat',
       'yle_teema',
       'yle_extra',
       'yle_vega',
       'yle_tv2',
       'yle_fsr',
       'yle_x3m',
       'yle_fem',
       'yle_tv1',
       'yle_tax'],
 'g': ['ylg'],
 'i': ['ylivieska_sub-region',
       'ylivieska_airfield',
       'ylistrum_japonicum',
       'ylikiiminki_church',
       'ylistrum_balloti',
       'ylinen_kassa',
       'ylig_river'],
 'j': ['ylj'],
 'k': ['ylk_organization'],
 'l': ['ylldren_ibrahimaj',
       'yllenus_desertus',
       'yllatysten_yo',
       'ylljet_alicka',
       'yllka_berisha',
       'ylli_shameti',
       'ylli_asllani',
       'ylli_sallahi',
       'ylli_pango',
       'yll_limani',
       'yllka_kuqi',
       'yllka_mujo',
       'ylli_shehu',
       'yll_rugova',
       'yllan_okou',
       'ylli_bufi',
       'yll_hoxha',
       'ylli_lama'],
 'm': ['ylm'],
 'o': ['ylon_schwartz', 'ylona_garcia'],
 'p': ['ylpm1', 'ylppo'],
 'r': ['ylr'],
 's': ['yls'],
 't': ['ylt'],
 'v': ['ylvingen_chapel',
       'ylva_johansson',
       'ylva_eggehorn',
       'ylva_iversson',
       'ylva_lindberg',
       'ylvi_pustina',
       'ylva_persson',
       'ylva_hedlund',
       'ylva_arkvik',
       'ylva_nowen',
       'ylva_thorn',
       'ylva_loof']}
