
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ys = {'_': ['ys_megabasic', 'ys_strategy', 'ys_origin', 'ys_seven', 'ys_iv'],
 'a': ['ysaline_bonaventure',
       'ysaires_restituyo',
       'ysabel_maccloskey',
       'ysanne_churchman',
       'ysabel_birkbeck',
       'ysabella_brave',
       'ysanne_spevack',
       'ysaias_zamudio',
       'ysaye_quartet',
       'ysabel_ortega',
       'ysaora_thibus',
       'ysabel_wright',
       'ysaiah_ross',
       'ysaura_viso',
       'ysa_ferrer'],
 'b': ['ysbeidiau_heulog',
       'ysbyty_gwynedd',
       'ysbyty_alltwen',
       'ysbyty_ystwyth',
       'ysbyty_cynfyn',
       'ysbyty_eryri',
       'ysbyty_ifan'],
 'c': ['yscloskey,_louisiana', 'yscc_yokohama'],
 'e': ['yse_tardan-masquelier',
       'yser_testament',
       'yseult_island',
       'yseult_gervy',
       'yser_towers',
       'yser_front',
       'yser_medal'],
 'f': ['ysflight', 'ysf'],
 'g': ['ysgol_glanwydden',
       'ysgol_brynhyfryd',
       'ysgol_glanaethwy',
       'ysgol_treffynnon',
       'ysgol_brynrefail',
       'ysgol_aberconwy',
       'ysgol_bronyfoel',
       'ysgol_llanhari',
       'ysgol_clywedog',
       'ysgol_rhiwabon',
       'ysgol_ardudwy',
       'ysgol_tre-gib',
       'ysgyryd_fach',
       'ysgol_tryfan',
       'ysgafell_wen',
       'ysgol_eirias',
       'ysgyryd_fawr'],
 'h': ['yshmael_sali', 'yshai_oliel'],
 'i': ['ysidro_formation',
       'ysis_sonkeng',
       'ysidro_reyes',
       'ysis_barreto',
       'ysie_white'],
 'j': ['ysj'],
 'k': ['ysk'],
 'l': ['ysleta_mission', 'ysl_residences', 'ysl_records'],
 'm': ['ysmael', 'ysm'],
 'n': ['ysnp'],
 'o': ['ysopet', 'yso'],
 'p': ['yspertal', 'yspahan', 'yspi', 'ysp'],
 'r': ['ysrael_zuniga',
       'ysrael_seinuk',
       'ysr_cheyutha',
       'ysr_aasara',
       'ysr_bima'],
 's': ['yssolebias_martae', 'yssouf_kone'],
 't': ['ystradfellte_reservoir',
       'ystradgynlais_f.c.',
       'ystad_municipality',
       'ystoria_mongalorum',
       'ystradgynlais_rfc',
       'ystrad_peithyll',
       'ystrad_marchell',
       'ystalyfera_rfc',
       'ystad_djurpark',
       'ystrad_meurig',
       'ystwyth_trail',
       'ystrad_einion',
       'ystrad_mynach',
       'ystrad_fflur',
       'ystrad_aeron',
       'ystorya_adaf',
       'ystrad_tywi',
       'ystad_line',
       'ystads_if'],
 'u': ['ysu'],
 'y': ['ysyk-ata_district', 'ysyk-ata_resort', 'ysyk-kol,_tup']}
