
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_wu = {'_': ['wu-wang-zai-ju_inscribed_rock',
       'wu_chinese-speaking_people',
       'wu-chronicles,_chapter_2',
       'wu-tang_clan_videography',
       'wu-tang_clan_discography',
       'wu-tang:_shaolin_style',
       'wu-tang_clan_anthology',
       'wu-tang_chamber_music',
       "wu'ai_plaza_station",
       'wu_mian_rebellion',
       'wu_family_shrines',
       'wu_chung_library',
       'wu_xing_painting',
       'wu_qingyuan_cup',
       'wu_chung_house',
       'wu_sang_house',
       'wu_tat_cheung',
       'wu_shuang_pu',
       'wu_kwok_hung',
       'wu_guo_gushi',
       'wu_feng_park',
       'wu_chun_ming',
       'wu_shek_kok',
       'wu_xing_yao',
       'wu_lok_chun',
       'wu_kau_tang',
       'wu_lin_feng',
       'wu_siu_hong',
       'wu_ji_feng',
       'wu_teh_yao',
       'wu_kin_san',
       'wu_kai_sha',
       'wu_yu_lin',
       'wu_yun_an'],
 'b': ['wubin,_western_australia',
       "wubbzy's_big_movie!",
       'wube_haile_maryam',
       'wub_morning_vibes',
       'wubbo_de_boer'],
 'c': ['wucheng_township,_jiangxi',
       'wuchang_railway_station',
       "wucherer's_worm_lizard"],
 'd': ['wudaoliang_railway_station',
       'wudalianchi_dedu_airport',
       'wudinna,_south_australia',
       'wudinna_district_council',
       'wudang_road_subdistrict',
       'wudan,_inner_mongolia',
       'wudu_railway_station',
       'wuding_road_station',
       'wudam_al_sahil'],
 'e': ['wuest_expanded_translation'],
 'g': ['wugularr,_northern_territory',
       'wugong_railway_station',
       'wugu_cultural_village'],
 'h': ['wuhan-guangzhou_high-speed_railway',
       'wuhan-jiujiang_passenger_railway',
       'wuhan-xianning_intercity_railway',
       'wuhan-shiyan_high-speed_railway',
       'wuhan-xiaogan_intercity_railway',
       'wuhan_polytechnic_university',
       'wuhan_nationalist_government',
       'wuhan_qingchuan_university',
       'wuhandong_railway_station',
       'wuhan_jinyintan_hospital',
       'wuhuan_boulevard_station',
       'wuhan_university_library',
       'wuhan_textile_university',
       'wuhan_sports_university',
       'wuhe_township,_sichuan',
       'wuhan_botanical_garden',
       'wuhan_greenland_center',
       'wuhou_flyover_station',
       'wuhan_railway_station',
       'wuhe_township,_yunnan',
       'wuhu_xuanzhou_airport',
       'wuhan_union_hospital',
       'wuhu_olympic_stadium',
       'wuhou_avenue_station',
       'wuhu_railway_station',
       'wuhua_county_stadium',
       'wuhe_township,_henan',
       'wuhan_university_uav',
       'wuhan_street_circuit',
       'wuhan_sports_center',
       'wuhe,_wuwei,_gansu',
       'wuhu_wanli_airport',
       'wuhan_road_station',
       'wuhan_metro_museum',
       'wuhayb_ibn_al-ward',
       'wuhan_railway_hub',
       'wuhu_rail_transit',
       'wuhan_poly_plaza',
       'wuhan_art_museum',
       'wuhan_yaqi_f.c.'],
 'i': ['wuikinuxv-kitasoo-nuxalk_tribal_council'],
 'j': ['wujiang_district,_shaoguan',
       'wujek,_lublin_voivodeship',
       'wujiang_district,_suzhou',
       'wujiang_coach_station',
       'wujiang_road_station',
       'wujing_power_station',
       'wujs_arad_institute',
       'wuji_baifeng_wan',
       'wujek_coal_mine'],
 'k': ['wukuaicuo_metro_station'],
 'l': ['wulagi,_northern_territory',
       'wulkuraka_railway_station',
       'wuliangshan_horned_toad',
       'wulan_railway_station',
       'wulfsige_of_sherborne',
       'wulf_von_schimmelmann',
       'wuling_hongguang_plus',
       'wulaokeng_scenic_area',
       'wulikare,_south_sudan',
       'wulfsige_of_lichfield',
       'wulu_railway_station',
       'wuli_railway_station',
       'wulfsen_horse_burial',
       'wulfred_of_lichfield',
       'wulfhelm_of_hereford',
       'wulli_wulli_language',
       'wulfthryth_of_wessex',
       'wulfric_of_haselbury',
       'wulfgar_of_lichfield',
       'wulfthryth_of_wilton',
       'wulfhilda_of_barking',
       'wulin_square_station',
       'wulfstan_the_cantor',
       'wulfgar_of_ramsbury',
       'wulf_bernard_kunkel',
       'wulfhilde_of_saxony',
       'wulfgar_of_abingdon',
       'wulian_road_station',
       'wuling_hongguang_s3',
       'wulai_atayal_museum',
       'wuling_hongguang_s1',
       'wulfhere_of_mercia',
       'wulfhad_and_ruffin',
       'wulfstan_of_hedeby',
       'wulfhild_of_norway',
       'wulai_scenic_train',
       'wuling_hongguang_v',
       'wulfsige_of_london',
       'wulfstan_v_thomas',
       'wulf_and_eadwacer',
       'wulfhere_of_york',
       'wulai_old_street',
       'wulai_hot_spring',
       'wulfsige_of_york',
       'wulfram_of_sens',
       'wulften_am_harz',
       'wuling_san_wan',
       'wulf_h._utian'],
 'm': ['wuming_painting_collective',
       'wumatang_railway_station',
       'wum_prison_break'],
 'n': ['wundowie,_western_australia',
       'wungong,_western_australia',
       'wunaamin_miliwundi_ranges',
       'wunderkind_little_amadeus',
       'wunnewil_railway_station',
       'wunlit_peace_conference',
       'wunkar,_south_australia',
       'wunghnu_railway_station',
       'wungong_regional_park',
       'wunghnu_football_club',
       'wunna_theikdi_stadium',
       'wunnumin_lake_airport',
       'wundarr_the_aquarian',
       'wuning_road_station',
       'wunder_von_lengede',
       'wunstorf_air_base',
       'wunna_maung_lwin',
       'wun_yiu_village',
       'wuna_of_wessex',
       'wunsch_dir_was'],
 'p': ['wupperman_block/i.o.o.f._hall', 'wupatki_national_monument'],
 'q': ['wuqing_railway_station',
       'wuquan_railway_station',
       'wuqiao_railway_station',
       'wuqi_fishing_port'],
 'r': ['wurttembergische_landesbuhne_esslingen',
       'wurtsboro-sullivan_county_airport',
       'wurttemberg_football_association',
       'wurrwurrwuy_stone_arrangements',
       "wurzburg_bishops'_conference",
       'wurttembergischer_yacht_club',
       'wurttemberg_central_railway',
       'wurdong_heights,_queensland',
       'wurttemberg_western_railway',
       'wurtzite_crystal_structure',
       'wurugag_and_waramurungundi',
       'wurlitzer_electronic_piano',
       'wurttemberg_cape_regiment',
       'wurenlos_railway_station',
       'wurzburg_soviet_republic',
       'wurzburg_cultural_prize',
       'wurfgranate_patrone_326',
       'wuruma_dam,_queensland',
       'wurzen_railway_station',
       'wurzburg_witch_trials',
       'wurmberg_gondola_lift',
       'wurzburg_train_attack',
       'wurundjeri_walk_trail',
       'wurtland_union_church',
       'wuri_railway_station',
       'wurdeman_and_becket',
       'wurtsboro,_new_york',
       'wuri_metro_station',
       'wurmberg_ski_jumps',
       'wurttemberg_tss_4',
       'wurttemberg_tss_3',
       'wurttemberg_ts_4',
       'wurttemberg_t_5',
       'wurttemberg_t_3',
       'wurttemberg_t_4',
       'wurttemberg_t_6'],
 's': ['wustenrot_and_wurttembergische',
       'wushan_subdistrict,_changsha',
       'wustenfelde_railway_station',
       'wustermark_railway_station',
       'wushan_county,_chongqing',
       'wusutu_zhao_monastery',
       'wustrow,_lower_saxony',
       'wushan_square_station',
       'wusi_road_subdistrict',
       'wusheng_road_station',
       'wushan_county,_gansu',
       'wusum_sports_stadium',
       'wushu_in_singapore',
       'wushan_horned_toad',
       'wushi_oil_field'],
 't': ['wutungurra,_northern_territory',
       'wutaishan_sports_center',
       'wutaiwa_railway_station',
       'wutach_valley_railway',
       'wutong_ferry_terminal',
       'wutthakat_bts_station',
       'wuthering_high_school',
       'wuta_railway_station',
       'wutam_and_j-break'],
 'w': ['wuwei_confucius_temple',
       'wuwei_bronze_cannon',
       'wuwei_road_station',
       'wuwang_club_fire'],
 'x': ['wuxi_christian_church',
       'wuxi_railway_station',
       'wuxi_grand_theatre',
       'wuxi_sports_center',
       'wuxi_bus_accident',
       'wuxi_wugou_f.c.'],
 'y': ['wuyuan_railway_station',
       'wuyuan_county,_jiangxi',
       'wuyi_county,_zhejiang',
       'wuyuan_river_stadium',
       'wuyang,_zhang_county',
       'wuyi_square_station',
       'wuyi_county,_hebei',
       'wuyang_new_town',
       'wuyi_new_area'],
 'z': ['wuzhou_changzhoudao_airport',
       'wuzhou_film_distribution',
       'wuzhen_theatre_festival',
       'wuzhou_xijiang_airport',
       'wuzhi_railway_station',
       'wuzhou_avenue_station',
       'wuzhong_road_station',
       'wuzuolou_forest_park',
       'wuzi_yanzong_wan',
       'wuzi_of_han']}
