
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ww = {'a': ['wwa_middleweight_championship', 'wwa_trios_championship'],
 'c': ['wwc_television_championship',
       'wwc_hardcore_championship',
       "wwc_women's_championship"],
 'e': ['wwe_intercontinental_championship',
       'wwe_cruiserweight_championship',
       'wwe_universal_championship',
       'wwe_hardcore_championship',
       'wwe_european_championship',
       'wwe_superstar_spectacle',
       'wwe_elimination_chamber',
       'wwe_divas_championship',
       'wwe_performance_center',
       'wwe_capitol_punishment',
       'wwe_24/7_championship',
       'wwe_2k_battlegrounds',
       'wwe_stomping_grounds',
       'wwe_wreckless_intent',
       'wwe:_uncaged_series',
       'wwe_podcast_network',
       'wwe_bragging_rights',
       'wwe_brand_extension',
       'wwe_tagged_classics',
       'wwe_protein_domain',
       'wwe_raw_homecoming',
       'wwe_action_figures',
       'wwe_year-end_award',
       'wwe_breaking_point',
       'wwe_super_showdown',
       'wwe_workout_series',
       'wwe_worlds_collide',
       'wwe_extreme_rules',
       'wwe_super_tuesday',
       'wwe_niagara_falls',
       'wwe_tough_enough',
       'wwe_in_australia',
       'wwe_cyber_sunday',
       'wwe:_uncaged_iii',
       'wwe_judgment_day',
       'wwe_music_group',
       'wwe_crown_jewel',
       'wwe_world_title',
       'wwe_and_company',
       'wwe_bottom_line',
       'wwe:_uncaged_iv',
       'wwe_fatal_4-way',
       'wwe_diva_search',
       'wwe:_uncaged_ii',
       'wwe_home_video',
       'wwe_crush_hour',
       'wwe_main_event',
       'wwe_slam_city',
       'wwe_all_stars',
       'wwe_the_music',
       'wwe_in_canada',
       'wwe_bad_blood',
       'wwe_205_live',
       'wwe_in_india',
       'wwe_no_mercy',
       'wwe_raw_1000',
       'wwe_the_bash',
       'wwe_day_1',
       'wwe_raw_2'],
 'f': ['wwf/ajpw/njpw_wrestling_summit',
       'wwf_wrestlemania_challenge',
       'wwf_championship_wrestling',
       'wwf_canadian_championship',
       'wwf_wrestling_challenge',
       'wwf_super_wrestlemania',
       'wwfa_intermediate_cup',
       'wwf_forceable_entry',
       'wwf_capital_carnage',
       'wwf_panda_junior',
       'wwf_fully_loaded',
       'wwf_superstars_2',
       'wwf_hong_kong',
       'wwf_war_zone'],
 'i': ['wwii/korea_lvt_museum', 'wwiii_live_2003', 'wwii_in_hd'],
 'l': ['wwl_television_championship',
       'wwl_americas_championship',
       'wwl_goddess_championship',
       'wwl_extreme_championship'],
 'n': ['wwnlive_mercury_rising'],
 'o': ['wwor_emi_service'],
 'r': ['wwrd_holdings_limited', 'wwru_national_cup'],
 't': ['wwt_martin_mere']}
