
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-22T12:25:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "46d851d22d917c0c9e6a68ee20ea888082b379fe",
 "version": "0.2.26.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
