
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ws = {'_': ['ws-atomic_transaction', 'ws_audiology', 'ws_czajka', 'ws_ftp'],
 'a': ['wsaw-tv',
       'wsadmin',
       'wsaz-tv',
       'wsaj-fm',
       'wsav-tv',
       'wsau-fm',
       'wsai',
       'wsav',
       'wsaq',
       'wsar',
       'wsam',
       'wsag',
       'wsau',
       'wsan',
       'wsal',
       'wsaa',
       'wsae',
       'wsat',
       'wsak',
       'wsa'],
 'b': ['wsb_universities', 'wsb-tv_tower'],
 'c': ['wschowa_county', 'wsciekly_pies', 'wschowa_land'],
 'd': ['wsdi-ld',
       'wsdma',
       'wsdf',
       'wsdz',
       'wsds',
       'wsde',
       'wsdk',
       'wsdx',
       'wsdp',
       'wsdr',
       'wsdc',
       'wsdv',
       'wsdm',
       'wsdh',
       'wsdq',
       'wsd'],
 'e': ['wsek-fm',
       'wsev-fm',
       'wsee-tv',
       'wsel-fm',
       'wset-tv',
       'wsew',
       'wsek',
       'wsez',
       'wsei',
       'wses',
       'wsen',
       'wseo',
       'wsem',
       'wsea',
       'wsec',
       'wsel',
       'wsex',
       'wseb',
       'wseg',
       'wsey',
       'wsev',
       'wset',
       'wse'],
 'f': ['wsfa_journal', 'wsfs_bank'],
 'g': ['wsg_tirol', 'wsg_open'],
 'h': ['wshp-lp',
       'wshf-lp',
       'wshm-ld',
       'wshe-fm',
       'wshl-fm',
       'wshu-fm',
       'wshp-fm',
       'wshy',
       'wshc',
       'wsha',
       'wshj',
       'wshs',
       'wshi',
       'wshe',
       'wshh',
       'wshv',
       'wshp',
       'wshl',
       'wshu',
       'wshn',
       'wshd',
       'wsho',
       'wshw',
       'wshb',
       'wshr',
       'wsh'],
 'i': ['wsiu-tv',
       'wsil-tv',
       'wsip-fm',
       'wsix-fm',
       'wsiz-fm',
       'wsim-lp',
       'wsiq',
       'wsip',
       'wsis',
       'wsix',
       'wsib',
       'wsim',
       'wsia',
       'wsir',
       'wsic',
       'wsiv',
       'wsie',
       'wsif',
       'wsiu',
       'wsig',
       'wsil',
       'wsi'],
 'j': ['wsju-tv',
       'wsjp-ld',
       'wsjm-fm',
       'wsjg-lp',
       'wsjt-ld',
       'wsjx-lp',
       'wsjp-fm',
       'wsju-ld',
       'wsjn-cd',
       'wsjr',
       'wsju',
       'wsjy',
       'wsje',
       'wsjp',
       'wsjm',
       'wsjs',
       'wsjl',
       'wsjf',
       'wsj.',
       'wsjq',
       'wsjd',
       'wsjk',
       'wsjz',
       'wsjv',
       'wsjo',
       'wsjt',
       'wsjw',
       'wsjc'],
 'k': ['wsk_wn-3'],
 'l': ['wslm-fm',
       'wslr-lp',
       'wslc-fm',
       'wsls-tv',
       'wslx',
       'wslm',
       'wsln',
       'wsly',
       'wslp',
       'wslb',
       'wsld',
       'wslv',
       'wslw',
       'wsla',
       'wslk',
       'wslq',
       'wsl'],
 'm': ['wsmc-fm',
       'wsmv-tv',
       'wsmd-fm',
       'wsmx-fm',
       'wsmi-fm',
       'wsm-fm',
       'wsmk',
       'wsmr',
       'wsmg',
       'wsmx',
       'wsmt',
       'wsmw',
       'wsmi',
       'wsmy',
       'wsmb',
       'wsmq',
       'wsms',
       'wsmv',
       'wsme',
       'wsmn',
       'wsmh',
       'wsmo',
       'wsmj',
       'wsml',
       'wsm'],
 'n': ['wsnt-fm',
       'wsnd-fm',
       'wsnx-fm',
       'wsno-fm',
       'wsne-fm',
       'wsnn-ld',
       'wsns-tv',
       'wsnn',
       'wsnr',
       'wsnp',
       'wsnl',
       'wsni',
       'wsnc',
       'wsnq',
       'wsno',
       'wsnt',
       'wsnj',
       'wsny',
       'wsnw',
       'wsng'],
 'o': ['wso2_carbon'],
 'p': ['wsp_global', 'wsp_usa'],
 'q': ['wsqy-ld', 'wsqx-fm', 'wsqv', 'wsql', 'wsqr', 'wsq'],
 'r': ['wsradio',
       'wsrq-fm',
       'wsrw-fm',
       'wsrn-fm',
       'wsrz-fm',
       'wsr-57',
       'wsr-74',
       'wsr-1',
       'wsri',
       'wsrs',
       'wsrk',
       'wsrq',
       'wsrg',
       'wsrv',
       'wsrm',
       'wsrp',
       'wsrt',
       'wsrc',
       'wsre',
       'wsru',
       'wsrb',
       'wsrw',
       'wsra',
       'wsro',
       'wsry',
       'wsrx',
       'wsr'],
 's': ['wssus_model'],
 't': ['wsto_tv'],
 'u': ['wsu_championship', 'wsu_press'],
 'v': ['wsvv-lp',
       'wsvw-ld',
       'wsvq-lp',
       'wsvt-ld',
       'wsvl-lp',
       'wsvf-cd',
       'wsvn',
       'wsvu',
       'wsvz',
       'wsve',
       'wsvi',
       'wsvm',
       'wsvh',
       'wsva',
       'wsvo',
       'wsvs',
       'wsvg',
       'wsvx',
       'wsv'],
 'w': ['wswo-tv',
       'wswf-ld',
       'wswo-lp',
       'wswe-lp',
       'wswy-ld',
       'wswv-fm',
       'wsww-fm',
       'wswg',
       'wsww',
       'wswr',
       'wswb',
       'wswv',
       'wswd',
       'wswn',
       'wswi',
       'wswt',
       'wsw'],
 'x': ['wsx'],
 'y': ['wsyt-dt3',
       'wsyc-fm',
       'wsyr-fm',
       'wsyy-fm',
       'wsyr-tv',
       'wsym-tv',
       'wsyt',
       'wsyr',
       'wsyb',
       'wsyl',
       'wsye',
       'wsyd',
       'wsya',
       'wsyn',
       'wsyy',
       'wsyp',
       'wsyx',
       'wsyw'],
 'z': ['wszerzecz-kolonia',
       'wszechswiete',
       'wszemilowice',
       'wszemierzyce',
       'wszechswiat',
       'wszemirow',
       'wszerzecz',
       'wszeradow',
       'wszemborz',
       'wszewilki',
       'wszebory',
       'wszeliwy',
       'wszachow',
       'wszemil',
       'wszolow',
       'wsze-tv']}
