
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mb = {'_': ['mb_roland_distillery', 'mb-2_tow_tractor'],
 'a': ['mbabane_government_hospital',
       'mbabane_highlanders_f.c.',
       'mbarizunga_game_reserve',
       'mbabane_swallows_f.c.',
       'mbambe_forest_reserve',
       'mbala_mbuta_biscotte',
       'mbanza_congo_airport',
       'mbarara_high_school',
       'mba_vitus_onyekachi',
       'mbamba_bay_language',
       'mbaba_belo_selambar',
       'mbala_henri_balenga',
       'mbaba_mwana_waresa',
       "mbadi_john_ng'ongo",
       'mbanja_worm_lizard',
       'mbarara_united_fc',
       'mbaye_dieye_faye',
       'mbaye_gana_kebe',
       'mbarara_city_fc'],
 'b': ['mbb/kawasaki_bk_117', 'mbb_223_flamingo', 'mbb_bo_105', 'mbb_bo_115'],
 'c': ['mbc_entertainment_awards',
       'mbcgame_starcraft_league',
       'mbc_gayo_daejejeon',
       'mbc_dynamo_moscow',
       'mbc_drama_awards',
       'mbc_standard_fm',
       'mbc_every_1'],
 'd': ['mbda_deutschland_gmbh'],
 'e': ['mbeere_north_constituency',
       'mbeere_south_constituency',
       "mbereshi_girls'_school",
       'mbeya_rural_district',
       'mbella_sonne_dipoko',
       'mbeya_city_f.c.',
       'mbedi_a_mbongo'],
 'h': ['mbhashe_local_municipality'],
 'i': ['mbilwi_secondary_school',
       'mbissine_therese_diop',
       'mbi_sports_complex'],
 'k': ['mbk_entertainment_discography', 'mbk_fight_night', 'mbk_spu_nitra'],
 'l': ['mbl_media_school'],
 'o': ['mbombela_local_municipality',
       'mbombini_molteno_sihele',
       'mbocayaty_del_yhaguy',
       'mbour_petite-cote_fc',
       'mbombela_united_f.c.',
       'mbour_sign_language',
       'mbom_mbom_julien',
       'mbo,_akwa_ibom'],
 's': ['mbs_international_airport'],
 't': ['mbta_kickback_schemes', 'mbta_commuter_rail'],
 'u': ['mbuya_military_hospital',
       'mburucuya_national_park',
       'mbuma_mission_hospital',
       'mbuluzi_game_reserve',
       'mbuji_mayi_airport'],
 'w': ['mbwn_railway_station'],
 'y': ['mbya-guarani_cinema_collective',
       'mbya_guarani_language',
       'mbya_guarani_people']}
