
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ml = {'_': ['ml_sultan_technikon',
       'ml_4.2-inch_mortar',
       'ml_postcode_area',
       'ml_3-inch_mortar'],
 'a': ['mlawka,_warmian-masurian_voivodeship',
       'mladenovac_railway_station',
       'mladen_petrov_chervenyakov',
       'mlanje_mountain_chameleon',
       'mlada_boleslav_district',
       'mlambalasi_rock_shelter',
       'mlawula_nature_reserve',
       'mlawa_railway_station',
       'mladen_naletilic_tuta',
       'mladost_na_stopnicah',
       'mladen_vojicic_tifa',
       'mladejov_na_morave',
       'mlada_fronta_dnes',
       'mlatho_mponela_fc',
       'mlaka_pri_kocevju',
       'mladen_iii_subic',
       'mlaka_pri_kranju',
       'mlaka_nad_luso'],
 'b': ['mlb_slugfest:_loaded',
       'mlb_network_showcase',
       'mlb_slugfest_20-03',
       'mlb_advanced_media',
       'mlb_slugfest_20-04',
       'mlb_slugfest_2006',
       'mlb_dugout_heroes',
       'mlb_network_radio',
       'mlb_london_series',
       'mlb_extra_innings',
       'mlb_pennant_race',
       'mlb_draft_league',
       'mlb_china_series',
       'mlb_power_pros',
       'mlb:_the_show',
       'mlb_fan_cave',
       'mlb_in_omaha',
       'mlb_on_five'],
 'c': ['mlc_transcription_system',
       'mlcl_railway_station',
       'mlc_building,_sydney'],
 'e': ['mleczkowo,_kuyavian-pomeranian_voivodeship',
       'mleczkowo,_warmian-masurian_voivodeship',
       'mleiha_archaeological_centre'],
 'i': ['mlilwane_wildlife_sanctuary', 'mlindo_the_vocalist'],
 'l': ['mlle_le_noir'],
 'o': ['mlodow,_podkarpackie_voivodeship',
       'mlodzianowo,_makow_county',
       'mlociny_metro_station',
       'mlody_lotnik_glider',
       'mlombo_v_fourie'],
 'p': ['mlp_team_bergstrasse'],
 's': ['mls_preseason_tournaments',
       'mls_players_association',
       'mls_supplemental_draft',
       'mls_primetime_thursday',
       'mls_caribbean_combine',
       'mls_soccer_saturday',
       'mls_re-entry_draft',
       'mls_reserve_league',
       'mls_soccer_sunday',
       'mls_cup_playoffs',
       'mls_rivalry_cups',
       'mls_golden_boot',
       'mls_direct_kick',
       'mls_cup_1999',
       'mls_cup_2006',
       'mls_cup_2011',
       'mls_cup_2001',
       'mls_cup_2017',
       'mls_cup_2002',
       'mls_cup_1996',
       'mls_cup_1997',
       'mls_cup_2020',
       'mls_cup_2012',
       'mls_cup_2000',
       'mls_cup_2007',
       'mls_cup_2016',
       'mls_cup_2015',
       'mls_cup_ring',
       'mls_cup_2019',
       'mls_cup_2010',
       'mls_cup_2003',
       'mls_cup_2014',
       'mls_cup_2008',
       'mls_cup_2018',
       'mls_next_pro',
       'mls_cup_1998',
       'mls_cup_2004',
       'mls_cup_2021',
       'mls_cup_2009',
       'mls_cup_2013',
       'mls_cup_2005',
       'mls_on_espn',
       'mls_best_xi',
       'mls_on_nbc',
       'mls_on_fox',
       'mls_on_tsn'],
 'u': ['mlungu_dalitsani_malawi'],
 'w': ['mlw_azteca_underground',
       'mlw_underground_tv',
       'mlw_open_draft',
       'mlw_opera_cup',
       'mlw_fury_road',
       'mlw_one_shot'],
 'y': ['mlynik,_kuyavian-pomeranian_voivodeship',
       'mlynek,_kuyavian-pomeranian_voivodeship',
       'mlynki,_kuyavian-pomeranian_voivodeship',
       'mlyny,_kuyavian-pomeranian_voivodeship',
       'mlyniec,_warmian-masurian_voivodeship',
       'mlynik,_warmian-masurian_voivodeship',
       'mlynkowo,_czarnkow-trzcianka_county',
       'mlynki,_swietokrzyskie_voivodeship',
       'mlyny,_swietokrzyskie_voivodeship',
       'mlynisko,_pomeranian_voivodeship',
       'mlynsko,_pomeranian_voivodeship',
       'mlyny,_podkarpackie_voivodeship',
       'mlynsk,_pomeranian_voivodeship',
       'mlynisko,_masovian_voivodeship',
       'mlynik,_pomeranian_voivodeship',
       'mlynik,_podlaskie_voivodeship',
       'mlynki,_masovian_voivodeship',
       'mlynek,_silesian_voivodeship',
       'mlynkowo,_lubusz_voivodeship',
       'mlyniska,_lublin_voivodeship',
       'mlynsk,_masovian_voivodeship',
       'mlynek,_starachowice_county',
       'mlyniec,_lubusz_voivodeship',
       'mlyniec,_lublin_voivodeship',
       'mlynkowo,_szamotuly_county',
       'mlynisko,_lodz_voivodeship',
       'mlyniska,_mysliborz_county',
       'mlynki,_lublin_voivodeship',
       'mlynary,_lodz_voivodeship',
       'mlyniska,_koszalin_county',
       'mlynek,_opole_voivodeship',
       'mlynow,_lodz_voivodeship',
       'mlynki,_wejherowo_county',
       'mlynki,_starogard_county',
       'mlyny,_opole_voivodeship',
       'mlynki,_belchatow_county',
       'mlynarze,_wyszkow_county',
       'mlynowo,_ketrzyn_county',
       'mlynowo,_mragowo_county',
       'mlynki,_pajeczno_county',
       'mlynki,_chojnice_county',
       'mlynek,_radomsko_county',
       'mlynek,_chojnice_county',
       'mlynne,_limanowa_county',
       'mlynek,_opoczno_county',
       'mlynek,_pinczow_county',
       'mlynek,_kartuzy_county',
       'mlyn,_lodz_voivodeship',
       'mlynarze,_makow_county',
       'mlynek,_konin_county',
       'mlynki,_tczew_county',
       'mlynow_metro_station',
       'mlynek,_kolo_county',
       'mlynik,_kolo_county']}
