
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rn = {'_': ['rn01-ss', 'rn-9893', 'rn5s1@', 'rn-94', 'rn-21'],
 'a': ['rnaseh2c',
       'rnaseh2b',
       'rnaseh2a',
       'rna28s1',
       'rna-seq',
       'rnaset2',
       'rnaseh1',
       'rna-out',
       'rnaiii',
       'rnase6',
       'rnase1',
       'rna22',
       'rnal',
       'rnaf',
       'rnai',
       'rnag',
       'rnaa',
       'rna'],
 'b': ['rnbass', 'rnb'],
 'c': ['rnchamps', 'rncp', 'rnco', 'rnc'],
 'd': ['rndis', 'rnd2', 'rndp', 'rnd1', 'rnd3', 'rndf', 'rndm', 'rnd'],
 'e': ['rne'],
 'f': ['rnf144a',
       'rnf113a',
       'rnf19a',
       'rnf114',
       'rnf5p1',
       'rnf125',
       'rnf122',
       'rnf183',
       'rnf216',
       'rnf220',
       'rnf128',
       'rnf139',
       'rnf111',
       'rnf135',
       'rnf213',
       'rnf146',
       'rnf123',
       'rnf13',
       'rnf40',
       'rnf31',
       'rnf34',
       'rnf20',
       'rnf38',
       'rnf25',
       'rnf11',
       'rnf24',
       'rnf39',
       'rnf32',
       'rnf10',
       'rnf41',
       'rnf26',
       'rnf14',
       'rnf12',
       'rnf43',
       'rnf8',
       'rnf2',
       'rnf7',
       'rnf4',
       'rnf5',
       'rnf'],
 'g': ['rngtt', 'rng'],
 'h': ['rnh1'],
 'i': ['rnie', 'rni'],
 'k': ['rnk'],
 'l': ['rnld'],
 'm': ['rnmtl1'],
 'n': ['rnn'],
 'o': ['rno'],
 'p': ['rnps1', 'rnpep', 'rnpv', 'rnp'],
 'r': ['rnrmc', 'rnr1', 'rnr2', 'rnr4', 'rnr3', 'rnr5'],
 's': ['rnsap', 'rnsp', 'rns'],
 't': ['rntd', 'rntp', 'rnt'],
 'u': ['rnu4atac', 'rnu2-2', 'rnu12', 'rnu2'],
 'v': ['rnv']}
