
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nf = {'b': ['nfb_film_can'],
 'c': ['nfc_championship_game'],
 'f': ['nff_futsal_eliteserie'],
 'i': ['nfinity_athletic_corporation'],
 'l': ['nfl_competition_committee',
       'nfl_international_series',
       'nfl_cheerleader_playoffs',
       'nfl_coaches_association',
       'nflpa_collegiate_bowl',
       'nfl_scouting_combine',
       "nfl's_greatest_games",
       'nfl_quarterback_club',
       'nfl_central_division',
       'nfl_playoff_results',
       'nfl_network_special',
       'nfl_regular_season',
       'nfl_on_nickelodeon',
       'nfl_sunday_ticket',
       'nfl_all-time_team',
       'nfl_full_contact',
       'nfl_gameday_2001',
       'nfl_gameday_2000',
       'nfl_night_series',
       'nfl_gameday_2003',
       'nfl_dream_season',
       'nfl_golf_classic',
       'nfl_kickoff_game',
       'nfl_total_access',
       'nfl_gameday_2002',
       'nfl_gameday_2004',
       'nfl_players_inc.',
       'nfl_blitz_20-02',
       'nfl_blitz_20-03',
       'nfl_gameday_97',
       'nfl_fever_2000',
       'nfl_head_coach',
       'nfl_blitz_2001',
       'nfl_blitz_2000',
       'nfl_gameday_99',
       'nfl_color_rush',
       'nfl_gameday_98',
       'nfl_fever_2004',
       'nfl_fever_2003',
       'nfl_fever_2002',
       'nfl_on_dumont',
       'nfl_game_pass',
       'nfl_blitz_pro',
       'nfl_rush_zone',
       "nfl_blitz_'99",
       'nfl_street_3',
       'nfl_street_2',
       'nfl_xtreme_2',
       'nfl_top_100',
       'nfl_on_abc',
       'nfl_top_10',
       'nfl_on_cbs',
       'nfl_on_nbc',
       'nfl_on_tnt',
       'nfl_on_fox']}
