
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dv = {'_': ['dv8'],
 'a': ['dvakacovice',
       'dvalishvili',
       'dvarcionys',
       'dvarchive',
       'dvaravati',
       'dvadasaha',
       'dvarapala',
       'dvarsatt',
       'dvaraka',
       'dvandva',
       'dvalinn',
       'dvaleti',
       'dvabzu',
       'dvach',
       'dvals',
       'dvali',
       'dvas',
       'dvar',
       'dva'],
 'b': ['dvbviewer',
       'dvb-html',
       'dvb-cpcm',
       'dvb-rcs',
       'dvb-rct',
       'dvb-s2x',
       'dvb-ms',
       'dvb-s2',
       'dvb-sh',
       'dvb-t2',
       'dvb-t',
       'dvb-s',
       'dvb-c',
       'dvbbs',
       'dvb-h',
       'dvbs',
       'dvb'],
 'c': ['dvcreators.net', 'dvcs', 'dvc'],
 'd': ['dvdempire.com',
       'dvd+rw-tools',
       'dvd-by-mail',
       'dvdisaster',
       'dvdxpress',
       'dvd-video',
       'dvdstyler',
       'dvd-audio',
       'dvdplus',
       'dvd-ram',
       'dvd-vr',
       'dvd+vr',
       'dvd+-r',
       'dvd-d',
       'dvdrw',
       'dvd43',
       'dvd6c',
       'dvd'],
 'e': ['dvellecanus', 'dvergsdal', 'dvergsoya', 'dverberg', 'dveri', 'dve'],
 'f': ['dvfs', 'dvfr'],
 'g': ['dvga', 'dvg'],
 'h': ['dvhs', 'dvh'],
 'i': ['dvinosauroidea',
       'dvirkivshchyna',
       'dvinosaurus',
       'dvinosauria',
       'dvigatel',
       'dvied-ep',
       'dvinskoy',
       'dvinitsa',
       'dvivida',
       'dvigrad',
       'dvipng',
       'dviete',
       'dvinia',
       'dvicio',
       'dvips',
       'dvipa',
       'dvija',
       'dvina',
       'dvir',
       'dvin'],
 'k': ['dvk'],
 'l': ['dvl1', 'dvl3', 'dvlf', 'dvl2', 'dvlp', 'dvl'],
 'm': ['dvm'],
 'n': ['dvnp', 'dvno', 'dvn'],
 'o': ['dvorniky-vcelare',
       'dvoryanskoye',
       'dvokodvweni',
       'dvorishnevo',
       'dvoyezyory',
       'dvorishche',
       'dvorishchi',
       'dvoynovsky',
       'dvorianky',
       'dvorichna',
       'dvorskoye',
       'dvoretzky',
       'dvorjane',
       'dvoriste',
       'dvoracek',
       'dvoynovo',
       'dvorniky',
       'dvoranci',
       'dvoyanka',
       'dvorovoi',
       'dvorets',
       'dvorica',
       'dvorovi',
       'dvortsy',
       'dvorane',
       'dvorsky',
       'dvornik',
       'dvoriki',
       'dvorska',
       'dvorak',
       'dvorec',
       'dvorce',
       'dvojka',
       'dvori',
       'dvonn',
       'dvory',
       'dvoa',
       'dvor'],
 'p': ['dvpb-hd', 'dvp'],
 'r': ['dvrsnica', 'dvr-ms', 'dvr'],
 's': ['dvs1', 'dvsn', 'dvsr', 'dvs'],
 't': ['dvtk-eger', 'dvtk'],
 'u': ['dvulikiaspis', 'dvuluchnoye', 'dvu'],
 'v': ['dvvl'],
 'w': ['dvw'],
 'x': ['dvx']}
