
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sf = {'_': ['sf_masonic_auditorium',
       'sf_public_press',
       'sf_film_finland',
       'sf_express_uav'],
 'a': ['sfax-thyna_international_airport',
       'sfax_archaeological_museum',
       'sfantu_gheorghe,_ialomita',
       'sfantu_gheorghe,_tulcea',
       'sfax_desalination_plant',
       'sfantu_gheorghe_branch',
       'sfantu_gheorghe_ghetto',
       'sfax_railways_sports',
       'sfatul_tarii_palace',
       'sfa_softball_field',
       'sfas_emes_yeshiva',
       'sfax_war_cemetery'],
 'c': ['sfca_maillet_20',
       'sfca_lignel_161',
       'sfca_lignel_20',
       'sfca_lignel_16',
       'sfc_stern_1900',
       'sfca_lignel_31',
       'sfca_lignel_10'],
 'e': ['sfendali_railway_station',
       'sferisterio_di_macerata',
       'sfera_stin_kardia'],
 'i': ['sfintii_voievozi_monastery',
       'sfida_per_shqiperine',
       'sfida_setagaya_fc'],
 'k': ['sfk_prenaks_jablonec'],
 'm': ['sfm_holiday_network'],
 'o': ['sforza_secondo_sforza'],
 'r': ['sfra_pioneer_award'],
 'w': ['sfwa_nebula_conference'],
 'x': ['sfx_cassette_magazine']}
