
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_qo = {'_': ['qo`rg`ontepa_district',
       'qo`shko`pir_district',
       'qo`shrabot_district',
       'qo`ng`irot_district',
       'qo`shtepa_district',
       'qo_xiong'],
 'a': ['qoaling'],
 'b': ['qobustan,_absheron',
       'qobu_dilagarda',
       'qobul_berdiyev',
       'qobad_kandi',
       'qoba_mosque',
       'qobad_beygi',
       'qobad_bazn'],
 'c': ['qocaqqazma',
       'qoc@hm@dli',
       'qocb@yli',
       'qocd@r@',
       'qocali',
       'qoculu',
       'qocho',
       'qoca'],
 'd': ['qodratabad,_nehbandan',
       'qodratabad,_narmashir',
       'qodratabad,_rafsanjan',
       'qodratabad,_khuzestan',
       'qodratabad,_fahraj',
       'qodratabad,_semnan',
       'qodratabad,_rigan',
       'qods_mohajer-6',
       'qodir_zokirov',
       'qods,_semnan',
       'qods_mohajer',
       'qodrat_kandi',
       'qods_county',
       'qods_talash',
       'qods_saeghe',
       'qods,_iran',
       'qods_yasir'],
 'f': ['qofas', 'qof'],
 'h': ['qohestan_district', 'qohurd-e_sofla', 'qohurd-e_olya'],
 'i': ['qoiri', 'qoi'],
 'j': ['qojur,_kurdistan', 'qojur,_zanjan'],
 'l': ['qolamhossein_bigjekhani',
       'qoliabad,_kermanshah',
       'qolaji-ye_fatabeygi',
       'qoliabad,_kurdistan',
       'qoldarreh-ye_sofla',
       'qoliabad,_golestan',
       'qolqoleh,_dehgolan',
       'qolqoleh-ye_chatan',
       'qoldarreh-ye_olya',
       'qolyan,_kurdistan',
       'qoliabad,_hamadan',
       'qolobaa_calankeed',
       'qolqoleh,_marivan',
       'qolian,_lorestan',
       'qolqoleh,_saqqez',
       'qolqol,_hamadan',
       'qolhak-e_sofla',
       'qoliqoli_bill',
       'qoljeh_tappeh',
       'qoltuq_nagara',
       'qolhak-e_olya',
       'qolora_mouth',
       'qoli_beyglu',
       'qoli_dizaji',
       'qoli_tappeh',
       'qoli_kandi',
       'qol_quchan',
       'qolqol_rud',
       'qoli_laleh',
       'qol_rumzi',
       'qol_hasan',
       'qolleh_zu',
       'qol_ghali',
       'qol_qoleh',
       'qoli_qoli'],
 'm': ['qomchoqay,_kurdistan',
       'qomshaneh,_asadabad',
       'qomesh,_kermanshah',
       'qomshaneh,_famenin',
       'qomchoqay_castle',
       'qomish,_lorestan',
       'qomik-e_bozorg',
       'qomsheh_tappeh',
       'qomrud_castle',
       'qom_technique',
       'qomabad,_fars',
       'qom_seminary',
       'qom_province',
       'qom_qeshlaq',
       'qom_tappeh',
       'qom_county',
       'qomra_ali',
       'qomi_kola',
       'qom_river',
       'qom_rug'],
 'n': ['qonaqk@nd,_shamakhi',
       'qonggyai_county',
       'qonaqk@nd,_quba',
       'qonan_qaran'],
 'o': ['qoorlugud',
       'qoornoq',
       'qooxdoo',
       'qooder',
       'qooney',
       'qoo10',
       'qoob',
       'qoop',
       'qoo'],
 'p': ['qopiwini', 'qoppoz', 'qoph'],
 'q': ['qoqmoncaq_language'],
 'r': ['qorovulbozor_district',
       'qorbanabad,_golestan',
       'qorbanabad,_kerman',
       'qorveh,_kermanshah',
       'qorbanabad,_dargaz',
       'qoriyoley_district',
       'qorao`zak_district',
       'qorako`l_district',
       'qorveh-e_darjazin',
       'qorlortorsuaq_dam',
       'qoroq-e_qavamcheh',
       'qorqori_district',
       'qorbanabad,_fars',
       'qorqoruk-e_sofla',
       'qoroq,_golestan',
       'qormusta_tengri',
       'qoroq,_lorestan',
       'qor-peoh_mosque',
       'qorqoruk-e_olya',
       'qory_sandioriva',
       'qorqan,_shabran',
       'qorqan,_fuzuli',
       'qortin_redoubt',
       'qoriniasi_bale',
       'qorsaya_island',
       'qorqi-ye_sofla',
       'qormi_dialect',
       'qorban_peykar',
       'qorqi-ye_olya',
       "qortem_zer'a",
       'qorban_kandi',
       'qoroq,_sari',
       'qoroq,_yazd',
       'qoran_talar',
       'qoroq,_amol',
       'qorban_lak',
       'qormi_f.c.',
       'qoroq_aqa',
       'qoros_3',
       'qoros_5',
       'qoros_7'],
 's': ['qosqoccahuarina,_urubamba',
       'qosqophryne_flammiventris',
       'qosqophryne_mancoinca',
       'qosqophryne_gymnotis',
       'qosabulaq,_jabrayil',
       'qosabulaq,_gadabay',
       'qosadiz@,_ordubad',
       'qosbeh-ye_maniat',
       'qosadiz@,_babek',
       'qostin_naheyeh',
       'qoshun_castle',
       'qoscos_grid',
       'qosheh_tut',
       'qostin_lar',
       'qostin_rud'],
 't': ['qotbabad-e_kohareh', 'qotbabad,_kerman'],
 'u': ['qoussair,_lebanon'],
 'v': ['qovsi_tabrizi', 'qovaq-e_sofla', 'qovaq-e_olya'],
 'w': ['qowzlujeh,_mahabad',
       'qowsheh_degarman',
       'qowsheh-ye_sofla',
       'qowsheh-ye_olya',
       'qowzlu,_alborz',
       'qowm-e_dehqan',
       'qowl_taq'],
 'x': ['qoxmuq'],
 'y': ['qoyunbin@si', 'qoydan'],
 'z': ['qozidavlat_qoimdodov', 'qozlu,_lachin']}
