
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ys = {'a': ['ysatters-kajsa', 'ysabella', 'ysabel', 'ysane', 'ysa'],
 'b': ['ysbrechtum', 'ysbaddaden', 'ysbyty', 'ysby', 'ysb'],
 'c': ['ysceifiog', 'yscir', 'ysco', 'yscc', 'ysc'],
 'e': ['ysengrimus', 'ysengrinia', 'yseult', 'yseop', 'yset', 'yser'],
 'f': ['ysflight', 'ysf'],
 'g': ['ysgubor-y-coed', 'ysgithyrwyn', 'ysguborwen', 'ysgarth', 'ysg'],
 'h': ['ysh'],
 'i': ['ysideria', 'ysii', 'ysiv', 'ysi'],
 'j': ['ysj'],
 'k': ['ysk'],
 'l': ['ysl'],
 'm': ['ysmael', 'ysm'],
 'n': ['ysnp'],
 'o': ['ysopet', 'yso'],
 'p': ['yspertal', 'yspahan', 'yspi', 'ysp'],
 'r': ['ysr'],
 's': ['yssac-la-tourette',
       'yssel-superieur',
       'ysselsteyn',
       'yssingeaux',
       'yssandon'],
 't': ['ystradgynlais',
       'ystradyfodwg',
       'ystradfellte',
       'ystalyfera',
       'ysterplaat',
       'ystradowen',
       'ystumllyn',
       'ystumtuen',
       'ystwyth',
       'ystrad',
       'ystlyg',
       'ystad',
       'yst'],
 'u': ['ysu'],
 'y': ['ysyk-ata']}
