
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ii = {'_': ['ii-vi_semiconductor_compound',
       'ii._gimnazija,_maribor',
       'ii_gymnasium_osijek',
       'ii_gymnasium_split',
       'ii_district,_turku',
       'ii_battle_squadron',
       'ii_antigen_system',
       'ii_bomber_command',
       'ii_tone_committee',
       'ii_canadian_corps',
       'ii_cavalry_corps',
       'ii_anzac_corps',
       'ii_liga_rugby',
       'ii_liga_zapad',
       'ii_d_extreme',
       'ii_zwicky_28',
       'ii_and_iii'],
 'd': ['iidva_nature_reserve', 'iida_kofun_group'],
 'e': ['iie_iron_meteorite'],
 'h': ['iihf_continental_cup',
       'iihf_all-time_teams',
       'iihf_world_ranking',
       'iihf_european_cup',
       'iihf_super_cup'],
 'i': ['iii_reconnaissance_command',
       'iii_gymnasium_osijek',
       'iii_battle_squadron',
       'iii_fighter_command',
       'iii_smoking_barrels',
       'iii_district,_turku',
       'iii_bomber_command',
       'iii._keruleti_tve',
       'iii_steps_forward',
       'iii_cavalry_corps',
       'iii_-_tri-logy',
       'iii_the_ep',
       'iii_zw_2'],
 'j': ['iijima_bishop_pullback'],
 'n': ['iinozaka_kofun_cluster', 'iinan_district,_mie'],
 'p': ['iipumbu_ya_tshilongo'],
 's': ['iisalmi_railway_station',
       'iishi_district,_shimane',
       'iisco_steel_plant',
       'iiss_ship_files',
       'iiso_flash_shoe',
       'iisa_pa_lamang'],
 't': ['iitb-monash_research_academy',
       'iittala_railway_station',
       'iit_research_institute',
       'iit_physics_department',
       'iit_bombay_racing'],
 'z': ['iizuka_daiichi_gymnasium', 'iizaka_onsen_station']}
