
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_iw = {'a': ['iwanowo,_warmian-masurian_voivodeship',
       'iwanki,_warmian-masurian_voivodeship',
       'iwa_intercontinental_championship',
       'iwappara-skiing_ground_station',
       'iwanki,_podlaskie_voivodeship',
       'iwate_prefectural_university',
       'iwase-senzuka_kofun_cluster',
       'iwa_television_championship',
       'iwa-kakeru!_climbing_girls',
       'iwanowka,_bialystok_county',
       'iwate_broadcasting_company',
       'iwate_prefectural_assembly',
       'iwafune_district,_niigata',
       'iwase_district,_fukushima',
       'iwate_development_railway',
       'iwanai_district,_hokkaido',
       'iwa_hardcore_championship',
       'iwami-class_patrol_vessel',
       'iwate_prefectural_museum',
       'iwantja,_south_australia',
       "iwa_women's_championship",
       'iwanowice,_krakow_county',
       'iwate_medical_university',
       'iwata_district,_shizuoka',
       'iwaki_greenfield_stadium',
       'iwami_district,_tottori',
       'iwaki_general_gymnasium',
       'iwate_at-large_district',
       'iwate_menkoi_television',
       'iwakuni_junior_college',
       'iwate_asahi_television',
       'iwanowka,_sejny_county',
       'iwa_national_festival',
       'iwatayama_monkey_park',
       'iwate_morioka_stadium',
       'iwanowo_light_railway',
       'iwate_district,_iwate',
       'iwate_grulla_morioka',
       'iwa_histeria_boricua',
       'iwaki_junior_college',
       'iwan_"iwcs"_roberts',
       'iwaki_green_stadium',
       'iwakuni_art_museum',
       'iwate_3rd_district',
       'iwate_1st_district',
       'iwannis_louis_awad',
       'iwa_kawasaki_dream',
       'iwaki_yumoto_onsen',
       'iwate_4th_district',
       'iwate_2nd_district',
       'iwasaki_art_museum',
       'iwai_hanshiro_viii',
       'iwami_art_museum',
       'iwas_world_games',
       'iwai_hanshiro_i',
       'iwai_hanshiro_v',
       'iwate_big_bulls',
       'iwar_von_lucken'],
 'b': ['iwbf_champions_league', 'iwbf_challenge_cup'],
 'c': ['iwccw_heavyweight_championship',
       'iwccw_television_championship',
       "iwccw_women's_championship",
       'iwcs_a_doyle'],
 'f': ['iwf_world_cup'],
 'g': ['iwgp_intercontinental_championship',
       'iwgp_heavyweight_championship',
       'iwgb_v_cac'],
 'i': ['iwiny,_boleslawiec_county',
       'iwiny,_lodz_voivodeship',
       'iwiny,_wroclaw_county',
       'iwi_jericho_941',
       'iwi_tavor_ts12',
       'iwi_tavor_x95',
       'iwi_tavor_7'],
 'k': ['iwk_health_centre'],
 'l': ['iwla_diana_chapter'],
 'n': ['iwno,_kuyavian-pomeranian_voivodeship'],
 'o': ['iwombe_anti-aircraft_regiment',
       'iwonka_bogumila_szymanska',
       'iwo_cyprian_pogonowski',
       'iwo_eleru_skull',
       'iwo_jima_rail'],
 'r': ['iwrf_asia-oceania_championship',
       'iwrf_european_championship',
       'iwrf_americas_championship',
       'iwrg_guerra_revolucionaria',
       'iwrg_copa_revolucionaria',
       'iwrg_anniversary_shows',
       'iwrg_ejecucion_total',
       'iwrg_prision_fatal',
       'iwrg_el_protector',
       'iwrg_legado_final',
       'iwrg_la_fortaleza',
       'iwrg_la_isla'],
 'u': ['iwuchukwu_amara_tochi']}
