
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sb = {'_': ['sb19_discography',
       'sb/djk_rosenheim',
       'sb_phoenician',
       'sb_ironsides',
       'sb_repertor',
       'sb_hibernia',
       'sb_limotive',
       'sb_reminder',
       'sb_marjorie',
       'sb_creative',
       'sb_kathleen',
       'sb_xylonite',
       'sb_wyvenhoe',
       'sb_niagara',
       'sb_cambria',
       'sb_centaur',
       'sb-33_mine',
       'sb_ardwina',
       'sb-81_mine',
       'sb_203580',
       'sb_decima',
       'sb_mirosa',
       'sb_nation',
       'sb_buffer',
       'sb_kento',
       'sb_pudge',
       'sb_adieu',
       'sb_edme',
       'sb_1000',
       'sb_line',
       'sb_2500',
       'sb_ena'],
 'a': ['sba_communications',
       "sba'iyyin_madrasa",
       'sba-60k2_bulat',
       'sba_airlines'],
 'b': ['sbbl_32-pounder', 'sbb_historic', 'sbb_cargo', 'sbb_gmbh'],
 'c': ['sbc_telecom'],
 'd': ['sbds', 'sbd'],
 'e': ['sberbank_srbija', 'sberbank_city', 'sberbank_cib', 'sbe_250', 'sbe_50'],
 'f': ['sbf_120'],
 'g': ['sbgrid_consortium'],
 'h': ['sbhc', 'sbhs', 'sbh'],
 'i': ['sbiii_motorsports', 'sbi_group', 'sbi_card', 'sbi_ring'],
 'j': ['sbjd', 'sbj'],
 'k': ['sbk_records', 'sbk_skiold', 'sbk_drafn', 'sbk_live', 'sbk_2011'],
 'l': ['sbl_cup'],
 'm': ['sbmv_protocol', 'sbm_offshore'],
 'n': ['sbno2', 'sbn'],
 'o': ['sbornik_sotsial-demokrata', 'sbonginhlanhla_makhaye'],
 'p': ['sbp-tag', 'sbps', 'sbpl', 'sbp'],
 'q': ['sbq'],
 'r': ['sbri_healthcare', 'sbrosovoye_lake', 'sbr_odds'],
 's': ['sbs_invitational',
       'sbs_independent',
       'sbs_essential',
       'sbs_viceland',
       'sbs_medianet',
       'sbs_aircraft',
       'sbs_v-radio',
       'sbs_popasia',
       'sbs_transit',
       'sbs_sports',
       'sbs_sport',
       'sbs_radio',
       'sbs_fune',
       'sbs_plus',
       'sbs_food',
       'sbs_bank',
       'sbs_mtv',
       'sbs_biz',
       'sbs_cup',
       'sbs_tv',
       'sbs_4',
       'sbs_1'],
 't': ['sbtb_protein', 'sbtvd_forum'],
 'u': ['sbu_nkosi'],
 'v': ['sbv_excelsior', 'sbv_vitesse'],
 'w': ['sbwr', 'sbw'],
 'x': ['sbx'],
 'y': ['sby']}
