
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rw = {'_': ['rw3_technologies',
       'rw_aurigae',
       'rw_cephei',
       'rw_miller',
       'rw_kember',
       'rw_cygni'],
 'a': ['rwanda-tanzania_relations',
       'rwanda-turkey_relations',
       'rwanda-spain_relations',
       'rwandan_literature',
       'rwandan_revolution',
       'rwakayihura_famine',
       'rwamagana_district',
       'rwampara_district',
       'rwandan_genocide',
       'rwandan_passport',
       'rwandan_cuisine',
       'rwandan_franc',
       'rwandese_carp',
       'rwanda_rwacu',
       'rwanda_nziza',
       'rwandan_cup',
       'rwa_people',
       'rwan_seco'],
 'b': ['rwby_chibi', 'rwb_adria', 'rwb_330'],
 'd': ['rwd-14_czapla',
       'rwd_magazine',
       'rwd_11',
       'rwd_15',
       'rwd_18',
       'rwd_13',
       'rwd_16',
       'rwd_22',
       'rwd_10',
       'rwd_17',
       'rwd_23',
       'rwd_21',
       'rwd_9',
       'rwd_6',
       'rwd_2',
       'rwd_8',
       'rwd_4',
       'rwd_3',
       'rwd_1',
       'rwd_5',
       'rwd_7'],
 'e': ['rwekunye-apac-aduku-lira-kitgum-musingo_road',
       'rwenzururu_movement',
       'rwenzori_mountains',
       'rwenzori_apalis',
       'rwenzori_turaco',
       'rwegasira_oscar',
       'rwenzori_batis',
       'rweideh,_idlib',
       'rwe_tower'],
 'f': ['rwf'],
 'g': ['rwgl-3'],
 'h': ['rwh'],
 'i': ['rwitobroto_mukherjee', 'rwindi_airport', 'rwi_essen'],
 'j': ['rwjbarnabas_health', 'rwj_airpark'],
 'l': ['rwl'],
 'm': ['rwm'],
 'o': ['rwo_alzey'],
 'p': ['rwp'],
 'r': ['rwr'],
 's': ['rws_motorsport',
       'rws_bruxelles',
       'rwsfm_103.3',
       'rws_group',
       'rws_bank'],
 't': ['rwth_asr'],
 'u': ['rwu']}
