
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rm = {'_': ['rm_broadcasting',
       'rm_discography',
       'rm_turnchapel',
       'rm_education',
       "rm_sotheby's",
       'rm-81_agena',
       'rm_chivenor',
       'rm-86_exos',
       'rm_hubbert',
       'rm_johnson',
       'rm_instow',
       'rm_nimbus',
       'rm_condor',
       'rm_poole',
       'rm_tamar'],
 'a': ['rmanj_monastery'],
 'b': ['rmb_holdings', 'rmb_city'],
 'c': ['rmc_decouverte', 'rmc_story', 'rmc_group'],
 'd': ['rmd_kwikform'],
 'e': ['rmetrics', 'rmeileh', 'rmelan', 'rmeil', 'rme'],
 'f': ['rmf_fm'],
 'g': ['rmg_networks', 'rmg_connect'],
 'h': ['rmhs', 'rmh'],
 'i': ['rmi_expeditions',
       'rmi_corporation',
       'rmit_university',
       'rmit_redbacks',
       'rmit_gallery',
       'rmit_link'],
 'j': ['rmjm'],
 'k': ['rmk-brj'],
 'l': ['rml_group'],
 'm': ['rmmv', 'rmm'],
 'n': ['rmn_newsletter'],
 'o': ['rmon', 'rmo'],
 'p': ['rmp'],
 'q': ['rmq'],
 'r': ['rmrg', 'rmrp', 'rmr'],
 's': ['rms_ben-my-chree',
       'rms_strathnaver',
       'rms_lancastria',
       'rms_strathmore',
       'rms_mauretania',
       'rms_strathaird',
       'rms_magdalena',
       'rms_lusitania',
       'rms_aquitania',
       'rms_carpathia',
       'rms_rangitiki',
       'rms_franconia',
       'rms_rangitata',
       'rms_carinthia',
       'rms_britannia',
       'rms_victorian',
       'rms_carmania',
       'rms_sylvania',
       'rms_carthage',
       'rms_moldavia',
       'rms_leinster',
       'rms_slavonia',
       'rms_campania',
       'rms_teutonic',
       'rms_columba',
       'rms_etruria',
       'rms_ausonia',
       'rms_ivernia',
       'rms_aurania',
       'rms_tayleur',
       'rms_mooltan',
       'rms_andania',
       'rms_orizaba',
       'rms_lucania',
       'rms_antonia',
       'rms_locotec',
       'rms_mataroa',
       'rms_fenella',
       'rms_laconia',
       'rms_saxonia',
       'rms_niagara',
       'rms_orontes',
       'rms_alaunia',
       'rms_scythia',
       'rms_olympic',
       'rms_segwun',
       'rms_maloja',
       'rms_scotia',
       'rms_tahiti',
       'rms_umbria',
       'rms_quetta',
       'rms_amazon',
       'rms_gaelic',
       'rms_persia',
       'rms_arabia',
       'rms_cedric',
       'rms_rhone',
       'rms_ophir',
       'rms_corfu',
       'rms_douro',
       'rms_trent',
       'rms_orion',
       'rms_ebro'],
 't': ['rmt_sambandham', 'rmt_bateleur'],
 'u': ['rmu'],
 'v': ['rmvb', 'rmv'],
 'x': ['rmx'],
 'y': ['rmyn02'],
 'z': ['rmz_corp']}
