
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rs = {'_': ['rs_infotainment',
       'rs_productions',
       'rs_rocketship',
       'rs_telescopii',
       'rs_components',
       'rs_integrator',
       'rs_sjofareren',
       'rs-26_rubezh',
       'rs-28_sarmat',
       'rs_ophiuchi',
       'rs9_vampir',
       'rs4_codici',
       'rs_mistral',
       'rs-24_yars',
       'rs_venture',
       'rs_berkane',
       'rs_sailing',
       'rs_settat',
       'rs_puppis',
       'rs_mccoll',
       'rs_vision',
       'rs_persei',
       'rs_media',
       'rs_elite',
       'rs_vareo',
       'rs_group',
       'rs_feva',
       'rs_quba',
       'rs_aero',
       'rs_tera',
       'rs_500'],
 'a': ['rsa_conference',
       'rsa_security',
       'rsa_numbers',
       'rsa_securid',
       'rsa_problem',
       'rsa_rna'],
 'b': ['rsbac', 'rsbi', 'rsb'],
 'c': ['rsc_olimpiyskiy',
       'rsc_cronenberg',
       'rsc_advances',
       'rsc_brands',
       'rsc_group'],
 'd': ['rsd-10_pioneer', 'rsd_alcala', 'rsd_58'],
 'e': ['rsee', 'rse'],
 'f': ['rsf_kobol'],
 'g': ['rsg_philippines', 'rsg_radio'],
 'h': ['rshvsm_alma-ata'],
 'i': ['rsi_corporation'],
 'j': ['rsj'],
 'k': ['rsk_dizvanagi', 'rsk_group'],
 'l': ['rsl_chicken'],
 'm': ['rsm_international',
       'rsm-56_bulava',
       'rsm_classic',
       'rsm_plaza',
       'rsmw_srna',
       'rsm_tenon',
       'rsm_us',
       'rsm_uk'],
 'n': ['rsn_stadium', 'rsn_rayer', 'rsn_singh'],
 'o': ['rso_records'],
 'p': ['rspca_australia',
       'rspca_tasmania',
       'rspb_minsmere',
       'rspb_medal',
       'rspca_nsw'],
 'r': ['rsr_racing'],
 's': ['rss_invincible',
       'rss_formidable',
       'rss_courageous',
       'rss_tenacious',
       'rss_endurance',
       'rss_vengeance',
       'rss_vigilance',
       'rss_steadfast',
       'rss_enclosure',
       'rss_stalwart',
       'rss-40_buran',
       'rss_panglima',
       'rss_intrepid',
       'rss_tracking',
       'rss_supreme',
       'rss_victory',
       'rss_valiant',
       'rss_vigour',
       'rss_racing',
       'rss_editor',
       'rss_bandit',
       'rss_valour',
       'rss_cloud',
       'rss_guard',
       'rss_tv'],
 't': ['rst_model', 'rsta_fc'],
 'u': ['rsu_f.c.', 'rsu_1'],
 'v': ['rsv_lahn-dill',
       'rsvp_movies',
       'rsvp_cycles',
       'rsv_wurges',
       'rsv_nuyina',
       'rsv_koln'],
 'w': ['rswa_medal'],
 'x': ['rsx-11', 'rsx'],
 'y': ['rsyslog', 'rsync']}
