
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_qo = {'_': ['qo`rg`ontepa', 'qo`shko`pir', 'qo`ng`irot', 'qo`shrabot', 'qo`ytosh'],
 'a': ['qoaling'],
 'b': ['qobadabad',
       'qobuqiraq',
       'qobustan',
       'qobuustu',
       'qobadlu',
       'qobong',
       'qobuz',
       'qobad',
       'qobu'],
 'c': ['qocaqqazma',
       'qoc@hm@dli',
       'qocb@yli',
       'qocd@r@',
       'qocali',
       'qoculu',
       'qocho',
       'qoca'],
 'd': ['qodratabad', 'qodsian', 'qod@s@', 'qodman', 'qods'],
 'f': ['qofas', 'qof'],
 'h': ['qohestan', 'qohandiz', 'qohaito', 'qohurd', 'qohrud', 'qohab'],
 'i': ['qoiri', 'qoi'],
 'j': ['qojiabad', 'qojer', 'qojur'],
 'l': ['qolqolabad',
       'qoldarreh',
       'qoliabad',
       'qolyaqol',
       'qolqati',
       'qolasta',
       'qollmay',
       'qolundy',
       'qolq@ti',
       'qoltuq',
       'qolqol',
       'qolmas',
       'qolalu',
       'qolian'],
 'm': ['qomoqomosauropus',
       'qomoqomong',
       'qomshaneh',
       'qomdarreh',
       'qomqaleh',
       'qomchian',
       'qomiabad',
       'qomishlu',
       "qombo'ul",
       'qomeshah',
       'qombovan',
       'qomishan',
       'qomlijeh',
       'qomshan',
       'qomsheh',
       'qomrud',
       'qomish',
       'qomqan',
       'qomik',
       'qomam',
       'qom'],
 'n': ['qonaqk@nd', 'qonqurtai', 'qonaqli', 'qontis', 'qonce'],
 'o': ['qoorlugud',
       'qoornoq',
       'qooxdoo',
       'qooder',
       'qooney',
       'qoo10',
       'qoob',
       'qoop',
       'qoo'],
 'p': ['qopiwini', 'qoppoz', 'qoph'],
 'q': ['qoqfin'],
 'r': ['qorlortorsuaq',
       'qorovulbozor',
       'qorpo-santo',
       'qoreyshabad',
       'qoridheere',
       'qorbanabad',
       'qorxmazoba',
       'qoruqbagi',
       'qorao`zak',
       'qoryoley',
       'qoroqchi',
       'qorbanlu',
       'qoruqlar',
       'qorako`l',
       'qorqoruk',
       'qorahsin',
       'qorculu',
       'qorqori',
       'qorovul',
       'qorutak',
       'qorghan',
       'qoragan',
       'qoraqir',
       'qoryale',
       'qordoba',
       'qorivva',
       'qorasuv',
       'qorqan',
       'qorvis',
       'qorqor',
       'qoros',
       'qorab',
       'qorvo',
       'qorqi',
       'qormi',
       'qoriq',
       'qorcu',
       'qoroq',
       'qoruq',
       'qoro',
       'qore',
       'qor'],
 's': ['qosqophryne',
       'qosaqislaq',
       'qosmalyan',
       'qosabulaq',
       'qosaqovaq',
       'qosadiz@',
       'qossiyeh',
       'qosak@nd',
       'qoshalaq',
       'qos@l@r',
       'qosaoba',
       'qosabeh',
       'qosasu',
       'qoscaq',
       'qosbeh',
       'qosira',
       'qosur',
       'qosja',
       'qosun',
       'qosa',
       'qos'],
 't': ['qotbiyeh',
       'qoturlar',
       'qotbabad',
       'qotanlu',
       'qoturlu',
       'qottab',
       'qotlu',
       'qotan',
       'qotd'],
 'u': ['qounfuzed'],
 'v': ['qovlarsari', 'qovsudlu', 'qovurma', 'qovusuq', 'qovlar', 'qovaq'],
 'w': ['qownnotes', 'qowzlojeh', 'qowzlujeh', 'qowland', 'qowsheh'],
 'x': ['qoxmuq'],
 'y': ['qoyunbin@si', 'qoydan'],
 'z': ['qozlubulaq',
       'qozqarali',
       'qozbabali',
       'qozagaci',
       'qozlijeh',
       'qozd@r@',
       'qozloq',
       'qozlu']}
