
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rc = {'_': ['rc_epokha-polytechnic',
       'rc_obolon-university',
       'rc_riviere-pilote',
       'rc_dinamo-center',
       'rc_novokuznetsk',
       'rc2_corporation',
       "rc_l'hospitalet",
       'rc_unterfohring',
       'rc_competicoes',
       'rc_polytechnic',
       'rc_oscillator',
       'rc_succession',
       'rc_toulonnais',
       'rc_motorsport',
       'rc_algorithm',
       'rc_bafoussam',
       'rc_innsbruck',
       'rc_evko-more',
       'rc_frameries',
       'rc_boumerdes',
       'rc_soignies',
       'rc_valencia',
       'rc_suresnes',
       'rc_narbonne',
       'rc_kredo-63',
       'rc_coupling',
       'rc_posnania',
       'rc_rottweil',
       'rc_koumassi',
       'rc_relizane',
       'rc_yangiyer',
       'rc_hasselt',
       'rc_herning',
       'rc_aviator',
       'rc_abidjan',
       'rc_circuit',
       'rc_havirov',
       'rc_batyari',
       'rc_prelouc',
       'rc_revenge',
       'rc_olomouc',
       'rc_tex-a-c',
       'rc_antares',
       'rc_orleans',
       'rc_roubaix',
       'rc_leipzig',
       'rc_chalon',
       'rc_hirnyk',
       'rc_aachen',
       'rc_vyskov',
       'rc_grasse',
       'rc_dnipro',
       'rc_sitges',
       'rc_cannes',
       'rc_ricany',
       'rc_odense',
       'rc_bystrc',
       'rc_roland',
       'rc_varna',
       'rc_arbaa',
       'rc_lousa',
       'rc_kuban',
       'rc_hamme',
       'rc_olymp',
       'rc_qanot',
       'rc_rivne',
       'rc_nimes',
       'rc_pisek',
       'rc_massy',
       'rc_vichy',
       'rc_daloa',
       'rc_racer',
       'rc_donau',
       'rc_krems',
       'rc_kouba',
       'rc_mainz',
       'rc_argo',
       'rc_cola',
       'rc_lens',
       'rc_zlin',
       'rc_graz',
       'rc_cars'],
 'a': ['rca_inspiration',
       'rcaf_blackouts',
       'rca_photophone',
       'rca_connector',
       'rca_thesaurus',
       'rca_victrola',
       'rca_dimensia',
       'rca_italiana',
       'rca_tk-40/41',
       'rca_cdp1861',
       'rca_records',
       'rca_camden',
       'rca_studio',
       'rca_video',
       'rca_clean',
       'rca_dome',
       'rca_1802',
       'rca_1600',
       'rca_lyra',
       'rca_501'],
 'b': ['rcbc_plaza', 'rcb_bank'],
 'c': ['rcc_broadcasting', 'rcca_security'],
 'd': ['rcd_carabanchel',
       'rcd_mallorca',
       'rcde_stadium',
       'rcd_espanyol',
       'rcd_cordoba'],
 'e': ['rce1', 'rcet', 'rce'],
 'f': ['rcf_audio'],
 'g': ['rcgs_resolute', 'rcg_oran'],
 'h': ['rch_2000'],
 'i': ['rci_banque'],
 'j': ['rcj'],
 'k': ['rckaela_aquino'],
 'l': ['rcl_benziger', 'rcl_foods'],
 'm': ['rcm_television', 'rcm_motorsport'],
 'n': ['rcn_corporation', 'rcn_television', 'rcn_series', 'rcn_radio'],
 'o': ['rco_agde'],
 'p': ['rcp_fontainebleau', 'rcp_advisors'],
 'r': ['rcr_arquitectes', 'rcr_tomlinson', 'rcrd_lbl'],
 's': ['rcs_mediagroup',
       'rcsi_hospitals',
       'rcscc_calgary',
       'rcs2_j2327',
       'rcs_sport'],
 't': ['rctv_international', 'rctv_sangbad', 'rct_1'],
 'u': ['rcuda', 'rcuv', 'rcu'],
 'v': ['rcv-9', 'rcvs', 'rcvr', 'rcv'],
 'w': ['rcw_catalogue',
       'rcw_120',
       'rcw_103',
       'rcw_34',
       'rcw_79',
       'rcw_88',
       'rcw_38',
       'rcw_49',
       'rcw_36'],
 'x': ['rcx'],
 'y': ['rcyc']}
