
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rt = {'_': ['rt-2pm2_topol-m',
       'rt-23_molodets',
       'rt_documentary',
       'rt_andromedae',
       'rt_middleware',
       'rt-2pm_topol',
       'rt_america',
       'rt_carinae',
       'rt_aurigae',
       'rt_france',
       'rt_movies',
       'rt_normae',
       'rt_arabic',
       'rt_rail',
       'rt_pcr',
       'rt_de',
       'rt_uk'],
 'a': ['rta_insurer', 'rta_clade'],
 'b': ['rtbf_international',
       'rtb_sukmaindera',
       'rtb_perdana',
       'rtb_aneka',
       'rtbf_sat'],
 'c': ['rtc_transit', 'rtcm_sc-104'],
 'd': ['rtdna_canada', 'rtd_info'],
 'e': ['rte_television',
       'rte_ireland',
       'rte_aertel',
       'rte_choice',
       'rte_player',
       'rte_board',
       'rte_chill',
       'rte_guide',
       'rte_pulse',
       'rte_three',
       'rte_sport',
       'rte_radio',
       'rte_gold',
       'rte_2xm',
       'rte_2fm',
       'rte_one'],
 'f': ['rtfdc1', 'rtfm', 'rtf1', 'rtfc', 'rtf'],
 'g': ['rtgame', 'rtgs', 'rtg'],
 'h': ['rthk', 'rth'],
 'i': ['rtishchevsky_district',
       'rti_international',
       'rti_producciones',
       'rti_surgical',
       'rti_systems'],
 'j': ['rtj4', 'rtj'],
 'k': ['rtkl_associates', 'rtk_4', 'rtk_2', 'rtk_3', 'rtk_1'],
 'l': ['rtl_international',
       'rtl_deutschland',
       'rtl_nederland',
       'rtl_boulevard',
       'rtl_telekids',
       'rtl7_masters',
       'rtl_aktuell',
       'rtl_passion',
       'rtl_kockica',
       'rtl_travel',
       'rtl_living',
       'rtl_nieuws',
       'rtl_lounge',
       'rtl_102.5',
       'rtl_group',
       'rtl_matin',
       'rtl_crime',
       'rtl_radio',
       'rtl_zwee',
       'rtl_klub',
       'rtl_zwei',
       'rtl_24',
       'rtl_8',
       'rtl_7',
       'rtl_5',
       'rtl_4',
       'rtl_z'],
 'm': ['rtm_mostar'],
 'n': ['rtn2', 'rtn3', 'rtn1', 'rtn'],
 'o': ['rtorrent', 'rto'],
 'p': ['rtp_internacional',
       'rtp_informacao',
       'rtp_desporto',
       'rtp_madeira',
       'rtp_memoria',
       'rtp_africa',
       'rtp_acores',
       'rtp_awards',
       'rtp1_hd'],
 'q': ['rtq'],
 'r': ['rtr_moldova', 'rtr_sports', 'rtrs_plus'],
 's': ['rts_index', 'rts_svet', 'rts_info'],
 't': ['rtt_rna'],
 'u': ['rtu_rauma', 'rtu_fc'],
 'v': ['rtv_kragujevac',
       'rtv-g-4_bumper',
       'rtv-a-2_hiroc',
       'rtv-a-3_nativ',
       'rtv_jablanica',
       'rtv_zivinice',
       'rtv_rijnmond',
       'rtv_silicone',
       'rtv_panorama',
       'rtv_slobomir',
       'rtv_politika',
       'rtv_vogosca',
       'rtv_gorazde',
       'rtv_bugojno',
       'rtv_utrecht',
       'rtv_maglaj',
       'rtv_visoko',
       'rtv_zenica',
       'rtv_niksic',
       'rtv_doboj',
       'rtv_noord',
       'rtv_palma',
       'rtv_cazin',
       'rtv_sabac',
       'rtv_vikom',
       'rtve_play',
       'rtv_sana',
       'rtv_luna',
       'rtv_usk',
       'rtv_apr',
       'rtv_bn',
       'rtv_is',
       'rtv_tk'],
 'w': ['rtw'],
 'x': ['rtxc_quadros', 'rtx_toxin'],
 'z': ['rtz']}
