
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ff = {'_': ['ff_developments',
       'ff_andromedae',
       'ff_aquilae',
       'ff_phages',
       'ff_groen',
       'ff_scala',
       'ff_jaro',
       'ff_meta',
       'ff_giza',
       'ff_cup',
       'ff_din',
       'ff_dax'],
 'a': ['ffa_competitions',
       'ffa_diamant',
       'ffair_rhos',
       'ffat_motif',
       'ffa_p-16'],
 'b': ['ffb_stadium', 'ffb_open'],
 'c': ['ffc_flaesheim-hillen'],
 'd': ['ffdshow', 'ffd'],
 'e': ['ffestiniog_railway',
       'ffe_transportation',
       'ffestiniog_travel',
       'ffestiniog_flags',
       'fferam_uchaf'],
 'f': ['fff_system'],
 'g': ['ffg'],
 'h': ['ffhs', 'ffh'],
 'i': ['ffion_davies', 'ffion_morgan', 'ffion_hague', 'ffion_bowen'],
 'k': ['ffkm', 'ffk'],
 'l': ['fflewddur_fflam', 'fflur_dafydd'],
 'm': ['ffmpeg', 'ffme', 'ffm'],
 'n': ['ffn'],
 'o': ['ffolkes_baronets',
       'fforde_grene',
       'fforest_fach',
       'fforest_fawr',
       'ffos_las'],
 'p': ['ffp_standards'],
 'q': ['ffq'],
 'r': ['ffred_ffransis', 'ffrr_records', 'ffrith_beach'],
 's': ['ffsa_academy'],
 't': ['fftg_awards'],
 'u': ['ffun', 'ffu'],
 'v': ['ffv_ntc', 'ffv_890'],
 'w': ['ffwd', 'ffw'],
 'x': ['ffx'],
 'y': ['ffyona_campbell',
       'ffynone_mansion',
       'ffynnon_llugwy',
       'ffynnon_lloer',
       'ffynnon_sara'],
 'z': ['ffz']}
