
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ft = {'_': ['ft_braunschweig',
       'ft_alphaville',
       'ft_magazine',
       'ft_press',
       'ft._lake',
       'ft_pgb',
       'ft_30'],
 'a': ['fta_receiver', 'fta_show'],
 'b': ['ftb'],
 'c': ['ftc_filakovo', 'ftcs_scheme'],
 'd': ['ftdi', 'ftd'],
 'e': ['ftena_trachylia', 'fte_automotive', 'fteri,_pieria', 'ftelia,_drama'],
 'f': ['ftf_next'],
 'g': ['ftg'],
 'h': ['fth1p5', 'fth1', 'fthc', 'fths', 'fth'],
 'i': ['fti_consulting', 'fti_station'],
 'k': ['ftk'],
 'l': ['ftl_newsfeed', 'ftl_games', 'ftl_moda'],
 'm': ['ftm_international', 'ftm_magazine'],
 'n': ['ftn'],
 'o': ['fto_gene'],
 'p': ['ftp_commander',
       'ftp_explorer',
       'ftp_software',
       'ftp_voyager',
       'ftp_server'],
 'r': ['ftrmetro_swansea', 'ftr_moto'],
 's': ['ftse4good_index', 'ftse_russell', 'ftse_group', 'ftse_mib'],
 't': ['fttla', 'fttw', 'ftt'],
 'u': ['ftub', 'ftuc', 'ftu'],
 'v': ['ftv_news', 'ftv_one'],
 'w': ['ftw_championship', 'ftw_revolution'],
 'x': ['ftx_games', 'ftx_arena'],
 'y': ['ftype', 'fty']}
