
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fm = {'_': ['fm_broadcasting',
       'fm104_phoneshow',
       'fm_transmitter',
       'fm_hatsukaichi',
       'fm_tsubakidai',
       'fm_erie-built',
       'fm_toyohashi',
       'fm_h-12-44ts',
       'fm_yokohama',
       'fm_ham-star',
       'fm_fukuyama',
       'fm_h-16-66',
       'fm_h-15-44',
       'fm_h-20-44',
       'fm57_rifle',
       'fm_h-16-44',
       'fm_h-10-44',
       'fm_h-12-44',
       'fm_okinawa',
       'fm_h-24-66',
       'fm_yutopia',
       'fm_federal',
       'fm_belfast',
       'fm_p-12-42',
       'fm_h-12-46',
       'fm_circini',
       'fm_hanabi',
       'fm_nanami',
       'fm1_davao',
       'fm_global',
       'fm_conway',
       'fm_static',
       'fm_center',
       'fm_derana',
       'fm_cocolo',
       'fm_akita',
       'fm_s.h.e',
       'fm_aichi',
       'fm_haro!',
       'fm_op800',
       'fm_osaka',
       'fm_towns',
       'fm_doll',
       'fm_bats',
       'fm_rail',
       'fm_104',
       'fm_103',
       'fm_957'],
 'a': ['fma_architects',
       'fma_pulqui',
       'fma_aemb.2',
       'fma_aec.2',
       'fma_aec.1',
       'fma_aec.3',
       'fma_ia-59',
       'fma_aet.1'],
 'b': ['fmb'],
 'c': ['fmc_technologies', 'fmc_corporation', 'fmc_xr311'],
 'd': ['fmdg', 'fmd'],
 'e': ['fme_connector'],
 'f': ['fmfc', 'fmf'],
 'g': ['fmg_insurance'],
 'h': ['fmhs', 'fmh'],
 'i': ['fmi_air'],
 'j': ['fmj'],
 'k': ['fmk_firearms', 'fmk-1_mine', 'fmk-5_mine', 'fmk-3_mine', 'fmk_9c1'],
 'l': ['fmllr', 'fml'],
 'm': ['fmm'],
 'n': ['fmn_adenylyltransferase', 'fmn_riboswitch', 'fmn_reductase'],
 'o': ['fmovies', 'fmo5', 'fmod', 'fmo4', 'fmo2', 'fmo'],
 'p': ['fmp'],
 'q': ['fmqb'],
 'r': ['fmri_adaptation',
       'fmr1-as1_gene',
       'fmr_magazine',
       'fmr_records',
       'fmr_tg500'],
 's': ['fmslogo', 'fmss', 'fmsr', 'fmsx', 'fms'],
 't': ['fmt'],
 'u': ['fmu'],
 'v': ['fmv'],
 'w': ['fmw_productions'],
 'x': ['fmx'],
 'y': ['fmylife']}
