
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_z_ = {'_': ['z._terrestris',
       'z-80_softcard',
       'z189_shipyard',
       'z._flavescens',
       'z800_3dvisor',
       'z111_factory',
       'z173_factory',
       'z13_torpedo',
       'z._gracilis',
       'z._insignis',
       'z._japonica',
       'z._robustus',
       'z._maculata',
       'z213:_exit',
       'z._elegans',
       'z._grandis',
       'z._montana',
       'z._candida',
       'z8_encore!',
       'z._spinosa',
       'z*_theorem',
       'z._indica',
       'z._exigua',
       'z._marcas',
       'z1_boats',
       'z._laeta',
       'z._mason',
       'z-4_plan',
       'z_23000',
       'z._obed',
       'z:_zed',
       'z1_tv'],
 'a': ['z_andromedae', 'z.a._nizami', 'z_apodis'],
 'b': ['z_battery', 'z_brewer', 'z_bend', 'z_berg'],
 'c': ['z_camelopardalis',
       'z_communications',
       'z_chamaeleontis',
       'z_corporation',
       'z.c.b.j._hall',
       'z_carinae',
       'z_channel',
       'z_curve',
       'z_code',
       'z_cam'],
 'd': ['z-division', 'z-drive', 'z-drag', 'z-dna', 'z-dos'],
 'e': ['z_energy', 'z_event'],
 'f': ['z_filmtidsskrift',
       'z_function',
       'z-fly_uav',
       'z_force',
       'z+f_uk',
       'z_flag'],
 'g': ['z_gallerie', 'z_gorres', 'z_grill'],
 'h': ['z@hm@tabad,_jalilabad', 'z@hm@tabad,_bilasuvar', 'z_holdings'],
 'i': ['z_island'],
 'l': ['z_launcher', 'z_living', 'z_lala'],
 'm': ['z-man_records',
       'z-morh_tunnel',
       'z-man_games',
       'z_mazinger',
       'z_machine',
       'z_movie'],
 'n': ['z_notation', 'z_number', 'z_nation'],
 'o': ['z-order_curve'],
 'p': ['z-plan_castle', 'z_plan'],
 'r': ['z-ro_discography',
       'z-ro_tolerance',
       'z@rqava,_quba',
       'z@rqava,_agsu',
       'z-rock_hawaii',
       'z@rdab,_agsu',
       'z_rock',
       'z_road',
       'z_rink'],
 's': ['z-source_inverter',
       'z-scan_technique',
       'z-series_trains',
       'z_society',
       'z_series',
       'z_storm',
       'z_shell',
       'z_scale',
       'z_space'],
 't': ['z-trip_discography', 'z.tao_discography', 'z_train'],
 'u': ['z_unit'],
 'v': ['z.vex_effects'],
 'w': ['z-wave'],
 'x': ['z/x'],
 'y': ['z@ylik,_dashkasan',
       'z@ylik,_kalbajar',
       'z@y@m,_zaqatala',
       'z@y@m_cirdaxan',
       'z@y@m,_shamkir',
       'z@y@m,_qakh',
       'z.y._fu']}
