
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gc = {'_': ['gc_kompetition',
       'gc-45_howitzer',
       'gc_biaschesi',
       'gc_lucciana',
       'gc_mascara',
       'gc_rieber',
       'gc_skew',
       'gc_box'],
 'a': ['gca_corporation', 'gcaleka_kaphalo', 'gca_airlines', 'gcap_media'],
 'b': ['gcb_bioenergy', 'gcb_bank'],
 'c': ['gcc_exchange', 'gcc_summit', 'gcc_games'],
 'd': ['gcd_domain', 'gcd_test'],
 'e': ['gce_villaralbo'],
 'f': ['gcflearnfree.org', 'gcfc2', 'gcfc', 'gcf'],
 'g': ['gcg'],
 'h': ['gchq_scarborough', 'gchq_bude'],
 'i': ['gcinikhaya_mpumza',
       'gcina_mazibuko',
       'gcinile_moyane',
       'gcina_mhlophe',
       'gcina_nkosi',
       'gcirs_16sw',
       'gcirs_13e',
       'gci_coach',
       'gcirs_8*',
       'gcirs_7'],
 'j': ['gcj'],
 'k': ['gck_lions'],
 'l': ['gcl-poly', 'gclc', 'gclp', 'gclm', 'gcl'],
 'm': ['gcm_grosvenor', 'gcm_resources', 'gcm_nes'],
 'n': ['gcn1l1', 'gcnt2', 'gcnt1', 'gcn4', 'gcna', 'gcn2', 'gcn'],
 'o': ['gcobani_bobo'],
 'p': ['gcpc', 'gcp'],
 'r': ['gcrt_j1745-3009', 'gcr_audio'],
 's': ['gcse_science', 'gcs_ballpark', 'gcs_cars', 'gcs_2000'],
 't': ['gct_giles'],
 'u': ['gcube_system', 'gcu_stadium', 'gcu_london', 'gcu_arena'],
 'v': ['gcvb_rna'],
 'w': ['gcw_bloodsport', 'gcw_zero']}
