
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gs = {'_': ['gs_neuves-maisons',
       'gs50_projection',
       'gs_petroliers',
       'gs_ilioupolis',
       'gs_formalism',
       'gs&wr_0-6-4t',
       'gs&wr_sambo',
       'gs1_databar',
       'gs_2000+25',
       'gs1_canada',
       'gs_telecom',
       'gs1_sweden',
       'gs_loures',
       'gs_caltex',
       'gs_tower',
       'gs_group',
       'gs_yuasa',
       'gs_boyz',
       'gs1_edi',
       'gs1_us',
       'gs_13'],
 'a': ['gsa_advantage', 'gsa_network', 'gsafety_uav'],
 'b': ['gsba_zurich'],
 'c': ['gschwend,_baden-wurttemberg',
       'gsc_03949-00967',
       'gsc_02652-01324',
       'gsc_03549-02811',
       'gsc_03089-00929',
       'gsc_02620-00648',
       'gsc_marseille',
       'gschutt_pass',
       'gscheid_pass',
       'gsc_systems',
       'gsc_bus'],
 'd': ['gsd_microscopy'],
 'e': ['gserpa_language', 'gse_systems', 'gse_stadium'],
 'f': ['gsfc_university'],
 'g': ['gsg_aarschot', 'gsg_9'],
 'h': ['gsh-18', 'gshhg', 'gshs', 'gsh'],
 'i': ['gsis_building',
       'gsieser_bach',
       'gsi_anomaly',
       'gsi_mariner',
       'gsi_pontivy'],
 'j': ['gsj'],
 'k': ['gsk_299423'],
 'l': ['gslp-liberal_alliance', 'gslp_kudumbashree', 'gsl-class_ferry'],
 'm': ['gsm_procedures',
       'gsm_services',
       'gsm_nation',
       'gsm_london',
       'gsm_03.48',
       'gsm_03.40',
       'gsm_03.38',
       'gsm_02.07',
       'gsm_modem'],
 'n': ['gsn_radio', 'gsn_live'],
 'o': ['gso_projection', 'gso_stadium'],
 'p': ['gsp_algorithm',
       'gsp_belgrade',
       'gsp_prometeu',
       'gsp_stadium',
       'gsp_jupiter',
       'gsp_orizont',
       'gsp_saturn',
       'gsp_atlas'],
 'r': ['gsr'],
 's': ['gss_infotech'],
 't': ['gstaad_palace'],
 'u': ["gsung-'bum", 'gsur', 'gsu'],
 'v': ['gsv'],
 'w': ['gsw_immobilien'],
 'x': ['gsx'],
 'y': ['gsy'],
 'z': ['gsz_stadium']}
