
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rd = {'_': ['rd_oriamendi',
       'rd_ariffien',
       'rd_ribnica',
       'rd_mochtar',
       'rd_slovan',
       'rd_amross',
       'rd_loka',
       'rd_s.a.'],
 'a': ['rdavica', 'rdate', 'rdap', 'rdac', 'rda'],
 'b': ['rdbp', 'rdbm', 'rdb'],
 'c': ['rdcm', 'rdc'],
 'd': ['rddhi', 'rdd'],
 'e': ['rdeci_kamen'],
 'f': ['rdfz_united', 'rdf_schema', 'rdf_1985'],
 'g': ['rdgldgrn', 'rdg'],
 'h': ['rdh_architects'],
 'i': ['rdi_powerlite', 'rdi_reit'],
 'j': ['rdj'],
 'l': ['rdl'],
 'm': ['rdm_server'],
 'n': ['rdna', 'rdn'],
 'o': ['rdo_building'],
 'p': ['rdp_internacional', 'rdp_africa', 'rdp_shop'],
 'r': ['rdrand', 'rdram', 'rdr'],
 's': ['rds-2_linage', 'rds_arena', 'rds_info', 'rds_cup'],
 't': ['rdt'],
 'u': ['rdultowice', 'rdu-fm', 'rdutow', 'rdu'],
 'v': ['rdv_sportsplex'],
 'w': ['rdw'],
 'x': ['rdx_technology'],
 'z': ['rdzuchow-kolonia',
       'rdziostow',
       'rdzuchow',
       'rdzawka',
       'rdzawa',
       'rdzow']}
