
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cm = {'_': ['cm101mmxi_fundamentals',
       'cm_chondrite',
       'cm_draconis',
       'cm_airlines',
       'cm-12_tank',
       'cm_browser',
       'cm_yoko',
       'cm_almy',
       'cm_punk'],
 'a': ['cmas_europe', 'cma_sampo', 'cma_cgm', 'cmac_fc'],
 'b': ['cmb_television', 'cmb_monaco', 'cmb_thenia'],
 'c': ['cmc_international',
       'cmc_electronics',
       'cmc_magnetics',
       'cmc_aviation',
       'cmc_cruiser',
       'cmc_limited',
       'cmc_leopard',
       'cmc_markets',
       'cmc_zinger',
       'cmc_leadca',
       'cmc_veryca',
       'cmc_group',
       'cmc_cup'],
 'd': ['cmd_distribution', 'cmd_ramlink', 'cmd_group', 'cmd_file'],
 'e': ['cmereska_gorca', 'cme_group', 'cme_span'],
 'f': ['cmf_design'],
 'g': ['cmg'],
 'h': ['cmh_records'],
 'i': ['cmiljka_kalusevic',
       'cmiszew_rybnowski',
       'cmi_roadbuilding',
       'cmi_motorsports',
       'cmielow_castle'],
 'j': ['cmj_university'],
 'k': ['cmklr1'],
 'l': ['cmla', 'cml'],
 'm': ['cmm_tv'],
 'n': ['cmn_radio'],
 'o': ['cmos_amplifier', 'cmon_limited'],
 'p': ['cmp-n-acylneuraminate_phosphodiesterase',
       'cmp-n-acetylneuraminate_monooxygenase',
       'cmp_fat'],
 'q': ['cmq'],
 'r': ['cmr_university', 'cmr_convention', 'cmr_surgical'],
 's': ['cms_pipelines',
       'cms_computers',
       'cms_energy',
       'cms_oissel',
       'cms_exec'],
 't': ['cmt_association',
       'cmt_crossroads',
       'cmt_outlaws',
       'cmt_europe',
       'cmt_music'],
 'u': ['cmu_sphinx'],
 'v': ['cmv_polyradiculomyelopathy', 'cmv_group'],
 'w': ['cmw'],
 'x': ['cmx_discography', 'cmx_systems', 'cmx_600'],
 'y': ['cmy'],
 'z': ['cmz']}
