
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cp = {'_': ['cp_villarrobledo',
       'cp_sanvicenteno',
       'cp24_breakfast',
       'cp_malpartida',
       'cp_calasancio',
       'cp_violation',
       'cp_cacereno',
       'cp_olivenza',
       'cp_alcorcon',
       'cp_amanecer',
       'cp_valdivia',
       'cp_lacertae',
       'cp_football',
       'cp_tenerife',
       'cp_voltrega',
       'cp_vilanova',
       'cp_almeria',
       'cp_cerceda',
       'cp_manlleu',
       'cp_chinato',
       'cp_55,940',
       'cp_47,497',
       'cp_puppis',
       'cp_55,244',
       'cp_areces',
       'cp_merida',
       'cp_mideba',
       'cp_sarria',
       'cp_morgan',
       'cp_bootis',
       'cp_system',
       'cp_ships',
       'cp_tank',
       'cp_all',
       'cp_lim',
       'cp_lee',
       'cp_vic'],
 'a': ['cpamerica_international',
       'cpa_superfamily',
       'cpa_australia',
       'cpa_magazine',
       'cpa_canada',
       'cpa_1'],
 'b': ['cpb_bank'],
 'c': ['cpc_corporation',
       'cpc_scientific',
       'cpc_gangbangs',
       'cpc_building',
       'cpc_attack!',
       'cpc_bears'],
 'd': ['cpd-57deg2874', 'cpd-1', 'cpdl', 'cpd'],
 'e': ['cpeb1', 'cped1', 'cpeir', 'cpesc', 'cpeb', 'cpet', 'cpep', 'cpe'],
 'f': ['cpfl_energia', 'cpf_building', 'cpf_number'],
 'g': ['cpg_oligodeoxynucleotide',
       'cpg_corporation',
       'cpg_site',
       'cpg_339',
       'cpg_359'],
 'h': ['cph_deutschland', 'cph_railmotor', 'cph_pix'],
 'i': ['cpi_aerostructures', 'cpi_international', 'cpi_group'],
 'j': ['cpj'],
 'k': ['cpk_coloring', 'cpk-mb_test'],
 'l': ['cplear_experiment',
       'cpl_resources',
       'cplp_bridge',
       'cplp_games',
       'cpl_aromas',
       'cpl_gang'],
 'm': ['cpmg_architects', 'cpm_croix', 'cpm_22'],
 'n': ['cpn_radio', 'cpn_cudis', 'cpn_tools'],
 'o': ['cpo_commerce'],
 'p': ['cpp_group', 'cppc_uav'],
 'q': ['cpq'],
 'r': ['cpr_regeneration', 'cpr_bridge'],
 's': ['cps_energy', 'cps_operon', 'cps_model', 'cps_ii'],
 't': ['cpt_corporation', 'cptn_holdings', 'cpt_symmetry'],
 'u': ['cpu_multiplier',
       'cpu_shielding',
       'cpu_records',
       'cpu_socket',
       'cpu_cache',
       'cpu_modes',
       'cpu_card',
       'cpu_wars',
       'cpu_shim',
       'cpu_time',
       'cpu_sim'],
 'v': ['cpv-tv', 'cpvl', 'cpv'],
 'w': ['cpwa', 'cpw'],
 'x': ['cpxm1', 'cpx'],
 'y': ['cpython'],
 'z': ['cpz']}
