
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cw = {'_': ['cw_complex',
       'cw_skimmer',
       'cw-1_visa',
       'cw_leonis',
       'cw_mars',
       'cw_now',
       'cw_50',
       'cw_56',
       'cw_13',
       'cw_14',
       'cw_57',
       'cw_9',
       'cw_5',
       'cw_6'],
 'a': ['cwaliny_duze', 'cwaliny_male'],
 'b': ['cwbl', 'cwb'],
 'c': ['cwc_group', 'cwc_2007', 'cwc_mode'],
 'd': ['cwd'],
 'e': ['cwengile_jadezweni'],
 'f': ['cwf_mid-atlantic'],
 'g': ['cwg'],
 'h': ['cwh'],
 'i': ['cwi/wipa_awards'],
 'k': ['cwks_resovia'],
 'l': ['cwl_wz.x'],
 'm': ['cwmbach,_carmarthenshire',
       'cwm,_denbighshire',
       'cwmorthin_tramway',
       'cwmavon,_torfaen',
       'cwmystwyth_mines',
       'cwmorthin_quarry',
       'cwmllynfell_rfc',
       'cwmbran_central',
       'cwm,_llanrothal',
       'cwmbran_stadium',
       'cwmfelin_mynach',
       'cwmdu,_swansea',
       'cwmbran_centre',
       'cwmdonkin_park',
       'cwmgwrach_rfc',
       'cwm_penmachno',
       'cwmythig_hill',
       'cwmtwrch_rfc',
       'cwmdu,_powys',
       'cwmhir_abbey',
       'cwm_clydach',
       'cwmgors_rfc',
       'cwmbran_rfc',
       'cwm_nantcol',
       'cwm_cadnant',
       'cwm_rhondda',
       'cwm_silicon',
       'cwmavon_rfc',
       'cwm_cyffog',
       'cwm_cadlan',
       'cwm_hengae',
       'cwm_caseg',
       'cwm_twrch',
       'cwm_talwg',
       'cwm_gwaun',
       'cwm_idwal',
       'cwm_dyli',
       'cwm_head',
       'cwm_dewi',
       'cwm_glo',
       'cwm_fx'],
 'n': ['cwn_annwn'],
 'o': ['cwow_gallery'],
 'p': ['cwp_renewables'],
 'r': ['cwrtmawr_manuscripts', 'cwrt_herbert'],
 's': ['cws_t-1'],
 't': ['cwtch', 'cwts', 'cwt'],
 'u': ['cwu'],
 'v': ['cwv'],
 'w': ['cww'],
 'y': ['cwyllog', 'cwy']}
