
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-29T17:36:26-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e74b9826fa0ab4aa263bda36aedb6742f4c09095",
 "version": "0.9.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
