
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zr = {'_': ['zr-75-1'],
 'a': ['zrab-kolonia',
       'zrarieh',
       'zrabiec',
       'zraluo',
       'zrahia',
       'zranb2',
       'zrarda',
       'zraoua',
       'zrazim',
       'zrazy',
       'zram'],
 'c': ['zrcv', 'zrce'],
 'e': ['zrelishcha',
       'zrenjanin',
       'zreczyce',
       'zrebieta',
       'zreniye',
       'zrebice',
       'zrelovo',
       'zrekie',
       'zrecin',
       'zrebin',
       'zrece'],
 'f': ['zrf1'],
 'h': ['zrh'],
 'i': ['zrinjevac',
       'zrinscina',
       'zrinska',
       'zrinko',
       'zrizer',
       'zrilic',
       'zriba',
       'zribi',
       'zrin'],
 'k': ['zrkovci'],
 'l': ['zrl'],
 'm': ['zrmanja'],
 'n': ['zrnovnica', 'zrnovci', 'zrnovo', 'zrnova', 'zrnov', 'zrni'],
 'o': ['zrobki', 'zrodla', 'zro'],
 'p': ['zrp'],
 's': ['zrsr2', 'zrsr1', 'zrs'],
 't': ['zrtp'],
 'u': ['zrub-komarivskyi', 'zruc-senec', 'zruanduxt', "zru'a", 'zruc'],
 'y': ['zryanin', 'zrykh'],
 'z': ['zrze']}
