
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gw = {'_': ['gw-842,166x',
       'gw-405,833',
       'gw-shimano',
       'gw-803430',
       'gw170817',
       'gw190412',
       'gw190521',
       'gw-basic',
       'gw151226',
       'gw170608',
       'gw170104',
       'gw170814',
       'gw190814',
       'gw501516',
       'gw2.8tc',
       'gw0742',
       'gw-tv',
       'gw4',
       'gw2'],
 'a': ['gwaun-cae-gurwen',
       'gwangjeong-dong',
       'gwaelod-y-garth',
       'gwangjang-dong',
       'gwaith/cartref',
       'gwanmun-daero',
       'gwawinapterus',
       'gwangtonggwan',
       'gwanyang-dong',
       'gwanghui-dong',
       'gwangdeoksan',
       'gwannyongsan',
       'gwachtenhorn',
       'gwanhun-dong',
       'gwahae-dong',
       'gwaebangsan',
       'gwanghwamun',
       'gwangmyeong',
       'gwardamanga',
       'gwangajeong',
       'gwanggyosan',
       'gwaegwansan',
       'gwaranyemba',
       'gwanghuimun',
       'gwahoddiad',
       'gwass-bagi',
       'gwagwalada',
       'gwayasdums',
       'gwalichaur',
       'gwaneumsan',
       'gwaenysgor',
       "gwat'sinux",
       'gwaneumsa',
       'gwaihiria',
       'gwangyang',
       'gwadabawa',
       'gwaramari',
       'gwarighat',
       'gwagwarwa',
       'gwanaksan',
       'gwabegar',
       "gwa'sala",
       'gwandong',
       'gwapotel',
       'gwalleuk',
       'gwaltney',
       'gwapyeon',
       'gwanggyo',
       'gwanzura',
       'gwalpara',
       'gwathmey',
       'gwacheon',
       'gwaha-ju',
       'gwalary',
       'gwalior',
       'gwamegi',
       'gwallon',
       'gwaebul',
       'gwalipa',
       'gwallek',
       'gwa-jam',
       'gwanbok',
       'gwaldai',
       'gwalarn',
       'gwaelod',
       'gwangju',
       'gwarsum',
       'gwaldam',
       'gwatkin',
       'gwalan',
       'gwandi',
       'gwageo',
       'gwadar',
       'gwarzo',
       'gwayay',
       'gwanki',
       'gwamba',
       'gwalia',
       'gwanda',
       'gwagha',
       'gwaram',
       'gwavas',
       'gwantu',
       'gwandu',
       'gwasdb',
       'gwadi',
       'gwawl',
       'gwala',
       'gwaun',
       'gwami',
       'gwane',
       'gwale',
       'gwai',
       'gwas',
       'gwar',
       'gwa'],
 'b': ['gwbert', 'gwb'],
 'c': ['gwc'],
 'd': ['gwda', 'gwd'],
 'e': ['gwern-y-steeple',
       'gwedaukkaing',
       'gwernymynydd',
       'gwernaffield',
       'gwengwerere',
       'gwenhwyfach',
       'gwedaukkon',
       'gwernesney',
       'gwendolyne',
       'gwendoline',
       'gwenhwyseg',
       'gwenllwyfo',
       "gwenc'hlan",
       'gwendolyn',
       'gwendolen',
       'gwernyfed',
       'gwenfritz',
       'gwersyllt',
       'gwenllian',
       'gweesalia',
       'gwenddydd',
       'gwernogle',
       'gwenview',
       'gwenafwy',
       'gwehelog',
       'gwenpool',
       'gwenhael',
       'gwerclas',
       'gweedore',
       'gwennap',
       'gweagal',
       'gwespyr',
       'gwenter',
       'gwembe',
       'gwegyi',
       'gwedna',
       'gwereg',
       'gwebin',
       'gweilo',
       'gwent',
       'gweta',
       'gweru',
       'gweek',
       'gwerz',
       'gwern',
       'gwede',
       'gwere',
       'gwen',
       'gwe'],
 'f': ['gwfc', 'gwf'],
 'g': ['gwgon', 'gwg'],
 'h': ['gwhs'],
 'i': ['gwinear-gwithian',
       'gwittaegibong',
       'gwiazdowski',
       'gwiazdowko',
       'gwihabaite',
       'gwiin-dong',
       'gwimokbong',
       'gwizdanow',
       'gwizdalki',
       'gwizdowka',
       'gwiazdowo',
       'gwintinli',
       'gwiezdzin',
       'gwizdziny',
       "gwich'in",
       'gwizdaly',
       'gwilliam',
       'gwiazdon',
       'gwithian',
       'gwiriko',
       'gwinear',
       'gwizdaj',
       'gwinner',
       'gwillim',
       'gwi.net',
       'gwisdek',
       'gwiazda',
       'gwisin',
       'gwilym',
       'gwills',
       'gwinko',
       'gwili',
       'gwinn',
       'gwizd',
       'gwiwa',
       'gwilt',
       'gwin',
       'gwi'],
 'j': ['gwj'],
 'k': ['gwk'],
 'l': ['gwladys', 'gwlad', 'gwl'],
 'n': ['gwn7', 'gwn'],
 'o': ['gwozdzianka',
       'gwonseon-gu',
       'gwozdziany',
       'gwozdziak',
       'gwozdzice',
       'gwozdziec',
       'gwonbeop',
       'gwonbeon',
       'gwoznica',
       'gwotet',
       'gwozdz',
       'gwollu',
       'gwoza',
       'gwon',
       'gwo'],
 'p': ['gwpp', 'gwp'],
 'r': ['gwrtheyrnion',
       'gwrfoddw',
       'gwrddelw',
       'gwredog',
       'gwrthwl',
       'gwriad',
       'gwrite',
       'gwr'],
 's': ['gwsn', 'gws'],
 't': ['gwt'],
 'u': ['gwu'],
 'w': ['gww'],
 'y': ['gwyneddosaurus',
       'gwyneddichnium',
       'gwyddelwern',
       'gwynneville',
       'gwyddfarch',
       'gwytherin',
       'gwyddgrug',
       'gwynllwg',
       'gwynllyw',
       'gwynfryn',
       'gwyllion',
       'gwyllgi',
       'gwyther',
       'gwyniad',
       'gwynedd',
       'gwystyl',
       'gwydion',
       'gwyneth',
       'gwynfi',
       'gwynfe',
       'gwynia',
       'gwynne',
       'gwydir',
       'gwynno',
       'gwyer',
       'gwynt',
       'gwyn',
       'gwy']}
