
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fy = {'a': ['fyansford,_victoria', 'fyat_multirotor', 'fyat_uav'],
 'b': ['fyb'],
 'c': ['fychan', 'fyc'],
 'e': ['fyens_stiftstidende',
       'fyer_language',
       'fyer_seselwa',
       'fyell_brezi',
       'fyen_rundt'],
 'f': ['fyfield,_oxfordshire',
       'fyfield,_wiltshire',
       'fyfield,_hampshire',
       'fyfe_dangerfield',
       'fyffe_christie',
       'fyfe_robertson',
       'fyffe,_alabama',
       'fyfield,_essex',
       'fyfe_building',
       'fyfield_road',
       'fyfield_down',
       'fyffe_cobble',
       'fyffes_line',
       'fyfe_ewing',
       'fyfe_river',
       'fyfe_hills',
       'fyf_fest'],
 'g': ['fygen_lutzenkirchen'],
 'i': ['fyi_daily'],
 'j': ['fyj'],
 'k': ['fyksesund_bridge', 'fyke_farmer'],
 'l': ['fyler-hotchkiss_estate',
       'fyllingsdalen_church',
       'fyllingen_fotball',
       'fylgia_amazonica',
       'fylymon_kurchaba',
       'fylmz_festival',
       'fylde_guitars',
       'fylgia_zadig',
       'fylde_flyers'],
 'm': ['fym'],
 'n': ['fynn_hudson-prentice',
       'fynbos_buttonquail',
       'fyn-related_kinase',
       'fynn_lakenmacher',
       'fynn_arkenberg',
       'fynes_moryson',
       'fynsk_foraar',
       'fynn_gutzeit',
       'fynn_seidel',
       'fyning_hill',
       'fyning_moor',
       'fyns_hoved',
       'fyne_times',
       'fyne_court',
       'fynn_otto'],
 'o': ['fyodor_pavlov-andreevich',
       'fyodor_shcherbachenko',
       'fyodorovsky_district',
       'fyodor_shcherbatskoy',
       'fyodorovskaya_church',
       'fyodor_romodanovsky',
       'fyodor_khaskhachikh',
       'fyodorovskoye_field',
       'fyodor_kozhevnikov',
       'fyodor_chernozubov',
       'fyodor_bogdanovsky',
       'fyodor_dobronravov',
       'fyodor_lukyanovich',
       'fyodor_koriatovych',
       'fyodor_raskolnikov',
       'fyodor_gornostayev',
       'fyodor_reshetnikov',
       'fyodorovka_airport',
       'fyodor_ogorodnikov',
       'fyodorovka,_russia',
       'fyodor_stravinsky',
       'fyodor_matyushkin',
       'fyodor_shaklovity',
       'fyodor_batyushkov',
       'fyodor_fedorovsky',
       'fyodor_dostoevsky',
       'fyodor_stellovsky',
       'fyodor_sheremetev',
       'fyodor_arkhipenko',
       'fyodor_ostashenko',
       'fyodor_kudryashov',
       'fyodor_rostopchin',
       'fyodor_yurchikhin',
       'fyodor_kharitonov',
       'fyodor_bogorodsky',
       'fyodor_slavyansky',
       'fyodor_bondarchuk',
       'fyodor_lyakhovsky',
       'fyodorov_district',
       'fyodor_polishchuk',
       'fyodor_karamazov',
       'fyodor_okhlopkov',
       'fyodor_mezentsev',
       'fyodor_svarovsky',
       'fyodor_rtishchev',
       'fyodor_tolbukhin',
       'fyodor_pervushin',
       'fyodor_druzhinin',
       'fyodor_schechtel',
       'fyodor_volkonsky',
       'fyodor_konyukhov',
       'fyodor_dvornikov',
       'fyodor_terentyev',
       'fyodor_bronnikov',
       'fyodor_lukoyanov',
       'fyodor_dyachenko',
       'fyodor_arsentyev',
       'fyodor_milovanov',
       'fyodor_alekseyev',
       'fyodor_bredikhin',
       'fyodor_cherenkov',
       'fyodor_kokoshkin',
       'fyodor_kuznetsov',
       'fyokla_bezzubova',
       'fyodor_kostyayev',
       'fyodor_kuritsyn',
       'fyodor_zakharov',
       'fyodor_matveyev',
       'fyodor_simashev',
       'fyodor_korovkin',
       'fyodor_radetsky',
       'fyodor_buchholz',
       'fyodor_pirotsky',
       'fyodor_gavrilov',
       'fyodor_metelkov',
       'fyodor_sergeyev',
       'fyodor_vasilyev',
       'fyodor_palitzin',
       'fyodor_apraksin',
       'fyodor_odinokov',
       'fyodor_gagloyev',
       'fyodor_gordeyev',
       'fyodor_burdykin',
       'fyodor_vidyayev',
       'fyodor_funtikov',
       'fyodor_kamensky',
       'fyodor_lopukhov',
       'fyodor_uspensky',
       'fyodor_shebanov',
       'fyodor_kostenko',
       'fyodor_chubukov',
       'fyodor_tyutchev',
       'fyodor_shikunov',
       'fyodor_astakhov',
       'fyodor_ushakov',
       'fyodor_tolstoy',
       'fyodor_gorovoy',
       'fyodor_zabelin',
       'fyodor_kryukov',
       'fyodor_berezin',
       'fyodor_golovin',
       'fyodor_buslaev',
       'fyodor_rokotov',
       'fyodor_sologub',
       'fyodor_burtsev',
       'fyodor_kulakov',
       'fyodor_panayev',
       'fyodor_kolchuk',
       'fyodor_bakunin',
       'fyodor_kumanin',
       'fyodor_matisen',
       'fyodor_marulin',
       'fyodor_zozulya',
       'fyodor_dubasov',
       'fyodor_remezov',
       'fyodor_nikitin',
       'fyodor_shutkov',
       'fyodor_klement',
       'fyodor_abramov',
       'fyodor_polynin',
       'fyodor_borisov',
       'fyodor_khitruk',
       'fyodor_novikov',
       'fyodor_truhin',
       'fyodor_stepun',
       'fyodor_keller',
       'fyodor_rimsha',
       'fyodor_chalov',
       'fyodor_volkov',
       'fyodor_trepov',
       'fyodor_iordan',
       'fyodor_lidval',
       'fyodor_shutov',
       'fyodor_datlin',
       'fyodor_brovko',
       'fyodor_ozerov',
       'fyodor_smolov',
       'fyodor_burdin',
       'fyodor_petrov',
       'fyodor_amlong',
       'fyodor_miller',
       'fyodor_gakhov',
       'fyodor_blinov',
       'fyodor_baykov',
       'fyodor_glinka',
       'fyodor_shubin',
       'fyodor_luzhin',
       'fyodor_bursak',
       'fyodor_ertell',
       'fyodor_zubov',
       'fyodor_bruni',
       'fyodor_uglov',
       'fyodor_korol',
       'fyodor_urnov',
       'fyodor_golan',
       'fyodor_kukin',
       'fyodor_tuvin',
       'fyodor_braun',
       'fyodor_selin',
       'fyodor_minin',
       'fyodor_gogel',
       'fyodor_reut',
       'fyodor_koni',
       'fyodor_lesh',
       'fyodor_usov',
       'fyodor_dan',
       'fyodor_zak',
       'fyodor_kon'],
 'p': ['fyp'],
 'r': ['fyrish_monument',
       'fyrby_runestone',
       'fyre_festival',
       'fyr_channel',
       'fyre_fraud',
       'fyre_dept.'],
 's': ['fyssen_foundation', 'fysisk_format'],
 't': ['fytche_baronets'],
 'u': ['fyulaba', 'fyutch', 'fyuse', 'fyu'],
 'v': ['fyvush_finkel', 'fyvie_castle', 'fyve_domain'],
 'x': ['fyxation'],
 'z': ['fyzabad']}
