
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fv = {'_': ['fv4401_contentious',
       'fv104_samaritan',
       'fv438_swingfire',
       'fv_northwestern',
       'fv107_scimitar',
       'fv101_scorpion',
       'fv-e991_series',
       'fv_illertissen',
       'fv103_spartan',
       'fv_ravensburg',
       'fv102_striker',
       'fv_nyggjaberg',
       'fv106_samson',
       'fv430_series',
       'fv300_series',
       'fv105_sultan',
       'fv_shahzaib',
       'fv_margiris',
       'fv_diefflen',
       'fv_biberach',
       'fv_biebrich',
       'fv_jutland',
       'fv_antares',
       'fv_pelican',
       'fv_athena',
       'fv_speyer',
       'fv_lauda',
       'fv_gaul'],
 'a': ['fva-3_ente', 'fva-4_pipo'],
 'b': ['fvb_mouse'],
 'c': ['fvc'],
 'd': ['fvd'],
 'g': ['fvg_project'],
 'h': ['fvhs', 'fvh'],
 'l': ['fvlgvres', 'fvl'],
 'm': ['fvm'],
 'p': ['fvp'],
 'r': ['fvr'],
 's': ['fvs'],
 't': ['fvt'],
 'w': ['fvwm-crystal', 'fvwm95', 'fvwm']}
