
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fn = {'_': ['fn-kegresse_3t',
       'fn_forty-nine',
       'fn_five-seven',
       'fn_barracuda',
       'fn_browning',
       'fn_ballista',
       'fn_5.7x28mm',
       'fn_trombone',
       'fn_herstal',
       'fn_evolys',
       'fn_tricar',
       'fn_brg-15',
       'fn_minimi',
       'fn_f2000',
       'fn_m1905',
       'fn_hp-da',
       'fn_m1900',
       'fn_p-12',
       'fn_sc-1',
       'fn_fnar',
       'fn_scar',
       'fn_four',
       'fn_fal',
       'fn_m12',
       'fn_503',
       'fn_cal',
       'fn_p90',
       'fn_509',
       'fn_mag',
       'fn_tps',
       'fn_slp',
       'fn_fns',
       'fn_key',
       'fn_fnx',
       'fn_303',
       'fn_fnc',
       'fn_fnp'],
 'a': ['fnality_international', 'fna_mapping', 'fnaf_world'],
 'b': ['fnb_corporation', 'fnb_connect', 'fnb_stadium', 'fnb_field'],
 'c': ['fnc_entertainment', 'fncc_awards', 'fnc:_uncut', 'fnc_inc.'],
 'd': ['fnd_films'],
 'e': ['fneitiq', 'fneidik', 'fnet', 'fne'],
 'f': ['fnf'],
 'g': ['fng_syndrome'],
 'h': ['fnhs', 'fnh'],
 'i': ['fnideq', 'fnip1', 'fni'],
 'j': ['fnjoskadalur', 'fnj'],
 'k': ['fnk'],
 'l': ['fnl_network', 'fnl_cup'],
 'm': ['fnmtv', 'fnme', 'fnm'],
 'n': ['fnnch', 'fnn'],
 'o': ['fnord', 'fno'],
 'p': ['fnpt', 'fnp'],
 'r': ['fnr_regulon', 'fnrs_rna'],
 's': ['fnss_acv-19',
       'fnss_acv-15',
       'fnss_acv-30',
       'fnss_kunduz',
       'fnss_samur',
       'fnss_pars',
       'fnsw_ntc'],
 't': ['fnti', 'fnta', 'fntb', 'fnt'],
 'u': ['fnuf', 'fnu'],
 'v': ['fnv'],
 'w': ['fnw'],
 'x': ['fnx'],
 'y': ['fny'],
 'z': ['fnz']}
