
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sj = {'_': ['sj_loftie-eaton',
       'sj_returns',
       'sj_stovall',
       'sj_oresund',
       'sj_berwin',
       'sj_miller',
       'sj_radar',
       'sj_chiro',
       'sj_esau',
       'sj_f33',
       'sj_t43',
       'sj_wl1',
       'sj_x16',
       'sj_e10',
       'sj_x14',
       'sj_t46',
       'sj_dm3',
       'sj_t41',
       'sj_t45',
       'sj_x40',
       'sj_g11',
       'sj_t44',
       'sj_x12',
       'sj_t21',
       'sj_mg',
       'sj_rc',
       'sj_b1',
       'sj_x5',
       'sj_ra',
       'sj_x6',
       'sj_da',
       'sj_tc',
       'sj_rb',
       'sj_ma',
       'sj_b7',
       'sj_ab',
       'sj_pa',
       'sj_y3',
       'sj_tb',
       'sj_x7',
       'sj_x9',
       'sj_rm',
       'sj_tp',
       'sj_y6',
       'sj_b',
       'sj_a',
       'sj_d',
       'sj_f',
       'sj_u',
       'sj_r',
       'sj_e',
       'sj_o'],
 'a': ['sjafruddin_prawiranegara',
       'sjarifuddin_baharsjah',
       'sjaellandske_medier',
       'sjaak_brinkkemper',
       'sjarifuddin_sjah',
       'sjalvklart,_sune',
       'sjaelor_station',
       'sjaelland_rundt',
       'sjaka_septembir',
       'sjaak_roggeveen',
       'sjaellands_odde',
       'sjatte_skottet',
       'sjaron_minailo',
       'sjaak_lettinga',
       'sjaak_lucassen',
       'sjaak_pieters',
       'sjaak_alberts',
       'sjaak_troost',
       'sjaak_kohler',
       'sjalevads_ik',
       'sjaak_polak',
       'sjaak_swart'],
 'b': ['sjbp', 'sjb'],
 'c': ['sjcc', 'sjcs', 'sjc'],
 'd': ['sjd_accountancy'],
 'e': ['sjerstin_vermeulen',
       'sjenicak_lasinjski',
       'sjeverin_massacre',
       'sjernaroy_church',
       'sjenica_airport',
       'sjellebro_stone',
       'sjenina_rijeka',
       'sjeng_kerbusch',
       'sjeng_schalken',
       'sjefke_janssen',
       'sjef_hensgens',
       'sjef_janssen',
       'sjef_mertens'],
 'f': ['sjf'],
 'h': ['sjhs', 'sjh'],
 'i': ['sjinkie_knegt'],
 'j': ['sjj'],
 'k': ['sjk_akatemia', 'sjk_171'],
 'm': ['sjm'],
 'n': ['sjn'],
 'o': ['sjogren-larsson_syndrome',
       'sjoormen-class_submarine',
       'sjonstafjell_tunnel',
       'sjovar_municipality',
       "sjostedt's_greenbul",
       'sjostrand,_nesodden',
       'sjoerd_hoogendoorn',
       'sjobo_municipality',
       'sjorvoll_formation',
       'sjoerd_vollebregt',
       'sjobotnen_cirque',
       'sjoukje_dijkstra',
       'sjoerd_sjoerdsma',
       'sjostrand,_asker',
       'sjoerd_hamburger',
       'sjorring_station',
       'sjogren_syndrome',
       "sjonni's_friends",
       'sjorup_runestone',
       'sjonvarp_simans',
       'sjoberg,_sweden',
       'sjoerd_overgoor',
       'sjors_verdellen',
       'sjors_paridaans',
       'sjoerd_hoekstra',
       'sjogren_glacier',
       'sjogren_shotgun',
       'sjoerd_koppert',
       'sjock_festival',
       'sjoera_dikkers',
       'sjoerd_wartena',
       'sjoerd_joustra',
       'sjoerd_hofstra',
       'sjoerd_potters',
       'sjoerd_soeters',
       'sjoerd_marijne',
       'sjoerd_huisman',
       'sjohnna_mccray',
       'sjoerd_winkens',
       'sjonhem_church',
       'sjoneset_spur',
       'sjogren_inlet',
       'sjonsta_river',
       'sjoeke_nusken',
       'sjoerd_kuyper',
       'sjoberg_prize',
       'sjors_scheres',
       'sjouke_jonker',
       'sjoerd_wiarda',
       'sjona_church',
       'sjoert_brink',
       'sjors_kramer',
       'sjosala_vals',
       'sjoli_church',
       'sjonni_brink',
       'sjors_ultee',
       'sjostads_if',
       'sjoo_castle',
       'sjotulls_bk',
       'sjoa_chapel',
       'sjoerd_bax',
       'sjoerd_ars',
       'sjo_soons'],
 'p': ['sjpn_trust'],
 'r': ['sjraar_cuijpers'],
 's': ['sjs'],
 't': ['sjt-class_rouv', 'sjtu_uav'],
 'u': ['sjur_lindebraekke',
       'sjur_hopperstad',
       'sjur_miljeteig',
       'sjur_helgeland',
       'sjur_torgersen',
       'sjurdur_skaale',
       'sjur_braekhus',
       'sjur_johnsen',
       'sjur_refsdal',
       'sjur_olsnes',
       'sjur_rothe',
       'sjur_loen',
       'sjur_bygd'],
 'v': ['sjvn', 'sjv'],
 'w': ['sjw_entertainment', 'sjw_group']}
