
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zw = {'_': ['zw10'],
 'a': ['zwackhiomyces_parmotrematis',
       'zwaardvis-class_submarine',
       'zwartberg_airfield',
       'zwaanendael_museum',
       'zwaanendael_colony',
       'zwarte_achtegrond',
       'zwakele_mncwango',
       "zwart-wit_'28",
       'zwarte_paard',
       'zwarte_cross',
       "zwaluwen_'30",
       'zwarte_water',
       'zwagg_island',
       'zwarte_piet',
       'zwanzig_ab',
       'zwang_peak',
       'zwai_bala'],
 'e': ['zweibrucken_hauptbahnhof',
       'zweibrucken_observatory',
       'zwelisha,_mpumalanga',
       'zweibruckenstrasse_8',
       'zwei_friedenssaulen',
       'zweikofel_formation',
       'zweibrucken_airport',
       'zweibrucken_castle',
       'zwethau_formation',
       'zwelethu_mthethwa',
       'zweibel_farmstead',
       'zwelonke_sigcawu',
       'zweigen_kanazawa',
       'zwelo_ntsimbini',
       'zwelakhe_sisulu',
       'zwettl_district',
       'zwelinzima_vavi',
       'zweig_building',
       "zweifel's_frog",
       'zwenkauer_see',
       'zwettl_abbey',
       'zweites_buch',
       'zweli_mkhize',
       'zwei_mutter',
       'zwei_bruder',
       'zwe_pyae'],
 'i': ['zwickau-schwarzenberg_railway',
       'zwijndrechtse_nieuwlichters',
       'zwiesel-bodenmais_railway',
       'zwiesel-grafenau_railway',
       'zwijndrecht,_netherlands',
       'zwieselbacher_rosskogel',
       'zwierzyniec_pierwszy',
       'zwierzyniecki_bridge',
       'zwiesel_kristallglas',
       'zwickau_hauptbahnhof',
       'zwijndrecht,_belgium',
       'zwingenberg,_hesse',
       'zwierzyniec_wielki',
       'zwierzyniec_trzeci',
       'zwingenberg_castle',
       'zwischenahner_meer',
       'zwischbergen_pass',
       'zwierzyniec_drugi',
       'zwickau_formation',
       'zwierzenskie_pole',
       'zwiesel_mountain',
       "zwicky's_triplet",
       'zwickau_prophets',
       'zwierzyniec_duzy',
       'zwiefalten_abbey',
       'zwierzyniec_maly',
       'zwiefalter_aach',
       'zwickauer_mulde',
       'zwikker_reagent',
       'zwickauer_land',
       'zwittermicin_a',
       'zwickau_model',
       'zwingle,_iowa',
       'zwide_kalanga',
       'zwicker_tone',
       'zwi_migdal'],
 'l': ['zwlecza'],
 'o': ['zwolle-almelo_railway',
       'zwolle,_gelderland',
       'zwolle,_louisiana',
       'zwola_poduchowna',
       'zwolen_county'],
 'r': ['zwrocona', 'zwrot'],
 's': ['zws'],
 'y': ['zwy_milshtein', 'zwyx_yx']}
