
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gb = {'_': ['gb3_championship',
       'gb_railfreight',
       'gb_railways',
       'gb_airways',
       'gb_boxing',
       'gb_12052',
       'gb_group',
       'gb_glace',
       'gb_18030',
       'gb_news',
       'gb_rail',
       'gb_tran',
       'gb_2312',
       'gb_city',
       'gb_cave'],
 'a': ['gbadolite_agreement',
       'gba-darpa_heliplane',
       'gbangbatoke_airport',
       'gbadolite_airport',
       'gbalefa_peninsula',
       'gbanzili_language',
       'gbarzon_district',
       'gbantu_language',
       'gbandi_language',
       'gbarma_district',
       'gbar_experiment',
       'gbarpolu_county',
       'gbaya_languages',
       'gbassay_bangura',
       'gbane_chiefdom',
       'gbanu_language',
       'gbassay_sessay',
       'gbagyi_people',
       'gbagnon_badie',
       'gban_language',
       'gbado_airport',
       'gbandi_people',
       'gbaran_tribe',
       'gbari,_benin',
       'gbaya_people'],
 'b': ['gbbs', 'gbb'],
 'c': ['gbcast', 'gbcw', 'gbcs', 'gbc'],
 'd': ['gbde', 'gbd'],
 'e': ['gbenga_olawepo-hashim',
       'gbehley-geh_district',
       'gbeleban_department',
       'gbehlageh_district',
       'gbenga_elegbeleye',
       'gbenga_akinnagbe',
       'gbemiga_ogunleye',
       'gbetsu_language',
       'gbenga_ogunbote',
       'gbeapo_district',
       'gbenga_ogedegbe',
       'gbense_chiefdom',
       'gbenga_ogunniya',
       'gbenga_adeyinka',
       'gbenga_otenuga',
       'gbenga_arokoyo',
       'gbenro_ajibade',
       'gbeneme_friday',
       'gbenko_airport',
       'gberefu_island',
       'gbeya_language',
       'gbenga_oloukun',
       'gbenga_adeboye',
       'gbemisola_oke',
       'gbewaa_palace',
       'gbenga_daniel',
       'gbe_languages',
       'gberi_people',
       'gbenga_aluko',
       'gbenga_shobo',
       'gbenga_sesan',
       'gbenga_salu'],
 'f': ['gbfl', 'gbf1', 'gbfc', 'gbf'],
 'g': ['gbgt1', 'gbg'],
 'h': ['gbhs_mbengwi'],
 'i': ['gbiri-niragu_language',
       'gbidukor_festival',
       'gbii_language',
       'gbin_language'],
 'j': ['gbj'],
 'k': ['gbk_kokkola'],
 'l': ['gbledi-agbogame', 'gbld-345', 'gbliglo', 'gbla', 'gbl'],
 'm': ['gbm'],
 'n': ['gbn'],
 'o': ['gbonkolenken_chiefdom',
       'gbomblora_department',
       'gbomblora_explosion',
       'gbolahan_mudasiru',
       'gbolahan_obisesan',
       'gbolahan_salami',
       'gboyega_oyetola',
       'gboly_ariyibi',
       'gbor_district',
       'gbo_language',
       'gbo_chiefdom',
       'gboyo_river'],
 'p': ['gbp510', 'gbp2', 'gbp1', 'gbp5'],
 'q': ['gbq_partners'],
 'r': ['gbr_college', 'gbr_code'],
 's': ['gbsd', 'gbs'],
 't': ['gbtw', 'gbt'],
 'u': ['gbu-53/b_stormbreaker',
       'gbubemi_fregene',
       'gbu-43/b_moab',
       'gbudwe_state',
       'gburek_peaks'],
 'v': ['gbv'],
 'x': ['gbx2', 'gbx'],
 'y': ['gby'],
 'z': ['gbz']}
