DROP TABLE IF EXISTS products;

-- -------------- --
-- Table Creation --
-- -------------- --

-- ENUM --
-- 'BUNDLE','CREATURE','ARMOUR','AMMUNITION',
-- 'STRUCTURE','WEAPON','TOOL','CONSUMABLE',
-- 'SADDLE','ARTIFACT','RESOURCE'


CREATE TABLE IF NOT EXISTS products(
	id MEDIUMINT UNSIGNED AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
    price SMALLINT UNSIGNED DEFAULT 65535,
    type VARCHAR(100) NOT NULL,
    discount INTEGER NOT NULL DEFAULT 0,
    -- type ENUM('BUNDLE','CREATURE','ARMOUR','AMMUNITION','STRUCTURE','WEAPON','TOOL','CONSUMABLE','SADDLE','ARTIFACT','RESOURCE') NOT NULL,
    -- quality ENUM('PRIMITIVE','RAMSHACKLE','APPRENTICE','JOURNEYMAN','MASTERCRAFT', 'ASCENDANT', 'TEK') DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (name, type)
);

CREATE INDEX product_by_name ON products (name);
