
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gn = {'_': ['gn_store_nord'],
 'a': ['gnanapureeswarar_temple,_tiruvadishoolam',
       'gnatowo,_warmian-masurian_voivodeship',
       'gnaraloo_wilderness_foundation',
       'gnatowo,_podlaskie_voivodeship',
       'gna/glendale_federal_classic',
       'gnangara,_western_australia',
       'gnarabup,_western_australia',
       'gnaeus_domitius_ahenobarbus',
       'gnaeus_acerronius_proculus',
       'gnarls_barkley_discography',
       'gnaeus_manlius_cincinnatus',
       'gnaeus_cornelius_dolabella',
       'gnaeus_cornelius_lentulus',
       'gnaeus_sentius_saturninus',
       'gnaeus_fulvius_centumalus',
       'gnaeus_marcius_coriolanus',
       'gnaeus_domitius_philippus',
       'gnaeus_caecilius_simplex',
       'gnaeus_servilius_geminus',
       'gnaeus_papirius_aelianus',
       'gnagno_philibert_fagnidi',
       'gnaeus_domitius_calvinus',
       'gnaeus_pompeius_longinus',
       'gnaty,_ostroleka_county',
       'gnaeus_vergilius_capito',
       'gnaeus_domitius_corbulo',
       'gnaeus_arrius_antoninus',
       'gnaeus_claudius_severus',
       'gnat_programming_studio',
       'gnaeus_cornelius_merula',
       'gnaeus_aufidius_orestes',
       'gnaeus_pompeius_collega',
       'gnaeus_domitius_lucanus',
       'gnaeus_servilius_caepio',
       'gnaeus_suellius_flaccus',
       'gnaeus_calpurnius_piso',
       'gnaeus_afranius_dexter',
       'gnaeus_mallius_maximus',
       'gnaeus_julius_agricola',
       'gnaeus_domitius_tullus',
       'gnaeus_pompeius_strabo',
       'gnaeus_pompeius_trogus',
       'gnaeus_hosidius_geta',
       'gnaeus_manlius_vulso',
       'gnaty,_sierpc_county',
       'gnaeus_julius_verus',
       'gnas_complex_locus',
       'gnaw_their_tongues',
       'gnaw_bone,_indiana',
       'gna_and_hofvarpnir',
       'gnashing_of_teeth'],
 'c': ['gnc_grip_gauntlet'],
 'e': ['gnezdilovo,_kursk_oblast', 'gnel_of_armenia'],
 'i': ['gniazdowo,_warmian-masurian_voivodeship',
       'gniazdowo,_pomeranian_voivodeship',
       'gniewowo,_pomeranian_voivodeship',
       'gniewoszow,_masovian_voivodeship',
       'gniewkowo,_masovian_voivodeship',
       'gniazdowo,_masovian_voivodeship',
       'gniazdow,_silesian_voivodeship',
       'gnilec,_podlaskie_voivodeship',
       'gnila,_podlaskie_voivodeship',
       'gniewkowo,_bartoszyce_county',
       'gniazdowo,_goleniow_county',
       'gniazdowo,_koszalin_county',
       'gniewkowo,_mragowo_county',
       'gniewino_railway_station',
       'gniezno_railway_station',
       'gniewosz_of_dalewice',
       'gnidrolog_live_1972'],
 'k': ['gnk_dinamo_zagreb'],
 'o': ['gnojewo,_warmian-masurian_voivodeship',
       'gnojno,_warmian-masurian_voivodeship',
       'gnojno,_swietokrzyskie_voivodeship',
       'gnojewo,_pomeranian_voivodeship',
       'gnowangerup,_western_australia',
       'gnojno,_masovian_voivodeship',
       'gnojno,_lublin_voivodeship',
       'gnome-rhone_mistral_major',
       'gnojno,_inowroclaw_county',
       'gnojno,_lodz_voivodeship',
       'gnosall_railway_station',
       'gnome_core_applications',
       'gnomon_of_saint-sulpice',
       'gnosall_rural_district',
       'gnome_activity_journal',
       'gnome_fruit-eating_bat',
       'gnome_display_manager',
       'gnome_archive_manager',
       'gnojno,_lipno_county',
       'gnocchi_alla_romana',
       'gnome_character_map',
       'gnome_athletic_f.c.',
       'gnome_wave_cleaner',
       'gnoll_country_park',
       'gnomeo_and_juliet',
       'gnomes_of_zurich',
       'gnome_king_kyrie',
       'gnome_et_rhone'],
 'p': ['gnp_crescendo_records', 'gnp_sports_f.c.'],
 'r': ['gnr_stirling_4-2-2',
       'gnr_division_etna',
       'gnri_aec_class',
       'gnr_class_j13',
       'gnr_but_class',
       'gnri_class_bt',
       'gnri_class_rt',
       'gnri_class_pg',
       'gnri_class_jt',
       'gnri_class_sg',
       'gnr_521_class',
       'gnri_class_t2',
       'gnr_class_j23',
       'gnri_class_vs',
       'gnri_class_t',
       'gnr_class_h3',
       'gnr_class_c1',
       'gnri_class_q',
       'gnr_class_j9',
       'gnri_class_v',
       'gnr_class_o2',
       'gnri_class_p',
       'gnr_class_c2',
       'gnr_class_j4',
       'gnr_class_l1',
       'gnri_class_s',
       'gnr_class_n2',
       'gnr_class_h4',
       'gnri_class_u',
       'gnr_class_n1',
       'gnr_class_o1'],
 's': ['gnss_software-defined_receiver',
       'gnss_positioning_calculation',
       'gnss_road_pricing'],
 't': ['gntr-dte_rna_motif'],
 'u': ['gnu/linux_naming_controversy',
       'gnu_all-permissive_license',
       'gnu_compiler_collection',
       'gnu_scientific_library',
       'gnu_portable_threads',
       'gnu_coding_standards',
       'gnu_core_utilities',
       'gnu_privacy_guard',
       'gnu_data_language',
       'gnu_common_lisp',
       'gnu_guix_system',
       'gnu_sip_witch']}
