
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gc = {'_': ['gc_motorsports_international',
       'gc_rieber_shipping',
       'gc32_racing_tour'],
 'c': ['gcc_standardization_organization',
       'gcc_homosexuality_test',
       'gcc_u-19_championship',
       'gcc_u-23_championship',
       'gcc_u-17_championship',
       'gcc_champions_league',
       'gcc_patent_office',
       'gcc_golden_boot'],
 'e': ['gce_ordinary_level'],
 'm': ['gcm_transcription_factors'],
 'p': ['gcp_infrastructure_investments',
       'gcp_applied_technologies',
       'gcp_student_living'],
 'r': ['gcr_class_11e',
       'gcr_class_11b',
       'gcr_class_11f',
       'gcr_class_9f',
       'gcr_class_8k',
       'gcr_class_9d',
       'gcr_class_9a',
       'gcr_class_9p',
       'gcr_class_8b',
       'gcr_class_8f',
       'gcr_class_8c',
       'gcr_class_1a',
       'gcr_class_1b',
       'gcr_class_5a',
       'gcr_class_9j',
       'gcr_class_8n',
       'gcr_class_9n',
       'gcr_class_8g',
       'gcr_class_9k',
       'gcr_class_8a',
       'gcr_class_8h',
       'gcr_class_9q',
       'gcr_class_5',
       'gcr_class_8',
       'gcr_class_2',
       'gcr_class_1'],
 's': ['gcsu_sri_lanka']}
