
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rp = {'_': ['rp11-267c16.1',
       'rp-eisenbahn',
       'rp-process',
       'rp612fic',
       'rp-s512',
       'rp2040',
       'rp-570',
       'rp-3',
       'rp-1',
       'rp3',
       'rp9',
       'rp1',
       'rp2'],
 'a': ['rpain', 'rpath', 'rpap2', 'rpa4', 'rpa'],
 'b': ['rpb'],
 'c': ['rpcgen', 'rpcs3', 'rpc54', 'rpc12', 'rpca', 'rpcs', 'rpcc', 'rpc'],
 'd': ['rpd'],
 'e': ['rperf', 'rpe65', 'rpety', 'rpe2', 'rpet', 'rpe'],
 'f': ['rpfc', 'rpf'],
 'g': ['rpgrip1l',
       'rpgrip1',
       'rpg-18',
       'rpg-75',
       'rpg-29',
       'rpgnet',
       'rpg-22',
       'rpg-32',
       'rpg-28',
       'rpg-43',
       'rpg-27',
       'rpg-26',
       'rpg-40',
       'rpg-30',
       'rpg-16',
       'rpg-2',
       'rpg-7',
       'rpg-6',
       'rpg-1',
       'rpga',
       'rpg'],
 'h': ['rph3al', 'rph3a', 'rphs', 'rph'],
 'i': ['rpix86', 'rpima', 'rpix', 'rpi'],
 'k': ['rpk'],
 'l': ['rpl26l1',
       'rpl-554',
       'rpl36al',
       'rpl22l1',
       'rpl-20',
       'rpl36',
       'rplp0',
       'rpls',
       'rpl'],
 'm': ['rpmdrake', 'rpmsg', 'rpmg', 'rpmc'],
 'n': ['rpn2', 'rpn1', 'rpn'],
 'o': ['rpos', 'rpof', 'rpoe', 'rpon', 'rpob', 'rpo'],
 'p': ['rpp38', 'rpp30', 'rpp40', 'rpp14', 'rppn', 'rpps', 'rpp'],
 'r': ['rprop', 'rpr'],
 's': ['rps6ka4',
       'rps-420',
       'rps6ka2',
       'rps6ka6',
       'rps6kc1',
       'rps6ka1',
       'rps6kb2',
       'rps6ka3',
       'rps6ka5',
       'rps27a',
       'rps27l',
       'rps17',
       'rps4x',
       'rps15',
       'rps5',
       'rps'],
 't': ['rptor', 'rpts', 'rpt'],
 'u': ['rpu'],
 'v': ['rpv'],
 'w': ['rpwl', 'rpw'],
 'x': ['rpx'],
 'y': ['rpyn06', 'rpyc'],
 'z': ['rpz']}
