
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yt = {'_': ['yt//st'],
 'a': ['ytalo', 'ytay', 'yta'],
 'c': ['ytcracker', 'ytc'],
 'd': ['ytd'],
 'h': ['ythanwells',
       'ythanbank',
       'ythdc1',
       'ythdf1',
       'ythdf2',
       'ythsie',
       'ythdf3',
       'ythdc2',
       'ytht'],
 'l': ['ytl'],
 'm': ['ytmnd', 'ytm'],
 'n': ['ytn'],
 'o': ['yto'],
 'p': ['ytp'],
 'r': ['ytri-ranga',
       'ytraberget',
       'ytrebygda',
       'ytringen',
       'ytr-2320',
       'ytrac',
       'ytres',
       'ytre',
       'ytr'],
 's': ['yts'],
 't': ['ytterdalsgubben',
       'ytterdalssata',
       'ytterdalsegga',
       'yttrogummite',
       'yttermalung',
       'ytter-vikna',
       'ytterhogdal',
       'yttrocerite',
       'yttertavle',
       'yttrialite',
       'ytterdalen',
       'yttrium-90',
       'ytterhorn',
       'ytterbium',
       'ytterbyn',
       'ytteroya',
       'yttersjo',
       'yttralox',
       'ytterby',
       'ytteran',
       'yttrium',
       'ytteroy',
       'ytteren',
       'yttila'],
 'u': ['ytu'],
 'v': ['ytv'],
 'y': ['ytyk-kyuyol']}
