
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cw = {'_': ['cw11', 'cw46', 'cw27', 'cw2', 'cw4', 'cw1', 'cw3'],
 'a': ['cwarme', 'cwac', 'cwa'],
 'b': ['cwbl', 'cwb'],
 'c': ['cwc15', 'cwc'],
 'd': ['cwd'],
 'e': ['cwenthryth', 'cwenburh', 'cwen', 'cwe'],
 'f': ['cwf'],
 'g': ['cwg'],
 'h': ['cwh'],
 'i': ['cwikly-krajewo',
       'cwikly-rupie',
       'cwikielnia',
       'cwierdzin',
       'cwietalka',
       'cwiklinek',
       'cwiercie',
       'cwiklice',
       'cwichelm',
       'cwiersk',
       'cwiklin',
       'cwikow',
       'cwikla',
       'cwi-2',
       'cwis',
       'cwi'],
 'k': ['cwk'],
 'l': ['cwlp', 'cwlb', 'cwl'],
 'm': ['cwm-yr-eglwys',
       'cwmrhydyceirw',
       'cwmfelinfach',
       'cwmcarnhywel',
       'cwmcoednerth',
       'cwmllynfell',
       'cwmpengraig',
       'cwmsychbant',
       'cwmdauddwr',
       'cwmystwyth',
       'cwmtillery',
       'cwmynyscoy',
       'cwmhiraeth',
       'cwmbrwyno',
       'cwmpennar',
       'cwm-y-glo',
       'cwmsymlog',
       'cwmcarvan',
       'cwmgwili',
       'cwmerfyn',
       'cwmbwrla',
       'cwmtwrch',
       'cwm-hwnt',
       'cwmgiedd',
       'cwmfelin',
       'cwmamman',
       'cwmffrwd',
       'cwmafan',
       'cwmifor',
       'cwmavon',
       'cwmduad',
       'cwmwysg',
       'cwmbran',
       'cwmdare',
       'cwmbach',
       'cwmcarn',
       'cwmgors',
       'cwmaman',
       'cwmcych',
       'cwmparc',
       'cwmyoy',
       'cwmann',
       'cwmdu',
       'cwm'],
 'n': ['cwn'],
 'o': ['cwot', 'cwo'],
 'p': ['cwp1', 'cwp'],
 'r': ['cwrt-y-gollen', 'cwrtnewydd', 'cwrsync', 'cwrw', 'cwr'],
 's': ['cwsdpmi', 'cwsf', 'cws'],
 't': ['cwtch', 'cwts', 'cwt'],
 'u': ['cwu'],
 'v': ['cwv'],
 'w': ['cww'],
 'y': ['cwyllog', 'cwy']}
