
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cd = {'_': ['cd-73deg375',
       'cd38-in-78c',
       'cd94/nkg2',
       'cd-action',
       'cd-adapco',
       'cd-rider',
       'cd300lf',
       'cd-cops',
       'cd200r1',
       'cd-text',
       'cd3eap',
       'cd-rom',
       'cd99l2',
       'cd300c',
       'cd300a',
       'cd2bp2',
       'cd200',
       'cd3wd',
       'cd79a',
       'cd151',
       'cd302',
       'cd276',
       'cd163',
       'cd180',
       'cd248',
       'cd278',
       'cd121',
       'cd-rw',
       "cd'87",
       'cd160',
       'cd177',
       'cd-57',
       'cd244',
       'cd164',
       'cd135',
       'cd133',
       'cd120',
       'cd2ap',
       'cd320',
       'cd155',
       'cd154',
       'cd8.4',
       'cd153',
       'cd134',
       'cd146',
       'cd79b',
       'cd137',
       'cd101',
       'cd226',
       'cd:uk',
       'cd109',
       'cd47',
       'cd96',
       'cd93',
       'cd80',
       'cd64',
       'cd97',
       'cd28',
       'cd48',
       'cd32',
       'cd43',
       'cd1d',
       'cd37',
       'cd68',
       'cd81',
       'cd52',
       'cd31',
       'cd-i',
       'cd19',
       'cd23',
       'cd90',
       'cd86',
       'cd1e',
       'cd14',
       'cd5l',
       'cd99',
       'cd46',
       'cd3g',
       'cd72',
       'cd38',
       'cd1a',
       'cd3d',
       'cd58',
       'cd53',
       'cd78',
       'cd33',
       'cd34',
       'cd70',
       'cd20',
       'cd22',
       'cd44',
       'cd11',
       'cd74',
       'cd66',
       'cd+g',
       'cd8a',
       'cd-4',
       'cd36',
       'cd30',
       'cd98',
       'cd85',
       'cd24',
       'cd83',
       'cd1b',
       'cd79',
       'cd84',
       'cd63',
       'cd-r',
       'cd69',
       'cd59',
       'cd27',
       'cd16',
       'cd6',
       'cd9',
       'cd3',
       'cd1',
       'cd8',
       'cd7',
       'cd4',
       'cd5',
       'cd2'],
 'a': ['cdawgva', 'cdata', 'cdan1', 'cdax', 'cdai', 'cdaa', 'cdac', 'cda'],
 'b': ['cdburnerxp', 'cdba', 'cdb!', 'cdb'],
 'c': ['cdc42bpa',
       'cdc42ep3',
       'cdc42ep2',
       'cdc42ep4',
       'cdc42ep1',
       'cdca7l',
       'cdc25a',
       'cdc2l2',
       'cdc2l1',
       'cdc14a',
       'cdc123',
       'cdc25c',
       'cdc14b',
       'cdc25b',
       'cdc16',
       'cdcp1',
       'cdc73',
       'cdca5',
       'cdca7',
       'cdc5l',
       'cdc25',
       'cdc42',
       'cdc23',
       'cdc40',
       'cdca8',
       'cdc20',
       'cdc26',
       'cdc37',
       'cdc34',
       'cdca3',
       'cdc14',
       'cdc27',
       'cdc4',
       'cdc?',
       'cdc6',
       'cdci',
       'cdc'],
 'd': ['cddlm', 'cdda', 'cddb', 'cdd'],
 'e': ['cdemu', 'cdek', 'cdec', 'cdex', 'cde'],
 'f': ['cdfas', 'cdfs', 'cdf'],
 'g': ['cdgval', 'cdg'],
 'h': ['cdh23-as1',
       'cdh17',
       'cdh16',
       'cdh12',
       'cdh15',
       'cdh23',
       'cdh11',
       'cdh10',
       'cdh4',
       'cdh6',
       'cdh8',
       'cdhs',
       'cdh9',
       'cdh1',
       'cdh2',
       'cdh3',
       'cdh'],
 'i': ['cdiscount',
       'cdisplay',
       'cdigix',
       'cdist',
       'cdipt',
       'cdic',
       'cdis',
       'cdia',
       'cdi'],
 'j': ['cdj'],
 'k': ['cdk5rap1',
       'cdk5rap3',
       'cdkn2bas',
       'cdk5rap2',
       'cdk2ap1',
       'cdkn2b',
       'cdk5r1',
       'cdkn2d',
       'cdkn2c',
       'cdk5r2',
       'cdkal1',
       'cdkn2a',
       'cdkn1b',
       'cdkl2',
       'cdk13',
       'cdkl5',
       'cdk12',
       'cdkn3',
       'cdk'],
 'l': ['cdls', 'cdl'],
 'm': ['cdma2000', 'cdmaone', 'cdms', 'cdmt', 'cdmf', 'cdm'],
 'n': ['cdnetworks', 'cdnjs', 'cdnow', 'cdnf', 'cdnb', 'cdnc', 'cdn'],
 'o': ['cdo-squared', 'cdot', 'cdos', 'cdon', 'cdo'],
 'p': ['cdparanoia', 'cdp.pl', 'cdppb', 'cdps', 'cdp'],
 'q': ['cdq'],
 'r': ['cdrtools',
       'cdroller',
       'cdr1-as',
       'cdrwin',
       'cdrkit',
       'cdrdao',
       'cdr1',
       'cdr2',
       'cdri',
       'cdr'],
 's': ['cdss', 'cds2', 'cdsp', 'cds'],
 't': ['cdtv', 'cdt'],
 'u': ['cdu/csu', 'cduce', 'cdu'],
 'v': ['cdvu+', 'cdvd', 'cdv3', 'cdv'],
 'w': ['cdwinder', 'cdw'],
 'x': ['cdxml', 'cdxl', 'cdx1', 'cdx2', 'cdx4', 'cdx'],
 'y': ['cdyl2', 'cdy1', 'cdy'],
 'z': ['cdza', 'cdz']}
