
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ds = {'_': ['ds80c390',
       'ds-p1-yu',
       'ds4ever',
       'ds2000',
       'ds4/na',
       'ds-22',
       'ds-16',
       'ds-39',
       'ds0a',
       'ds5',
       'ds7',
       'ds3',
       'ds2',
       'ds4',
       'ds6',
       'ds1'],
 'a': ['dsatur', 'dsap', 'dsac', 'dsa'],
 'b': ['dsbfirst', 'dsba', 'dsbc', 'dsb'],
 'c': ['dsc-qx100',
       'dsc-qx10',
       'dschang',
       'dscr1',
       'dscam',
       'dsch',
       'dscn',
       'dsca',
       'dsc3',
       'dscp',
       'dsc1',
       'dsci',
       'dsc2',
       'dscr',
       'dscc',
       'dsc'],
 'd': ['dsdm', 'dsdp', 'dsda', 'dsd'],
 'e': ['dse-alpha', 'dselect', 'dsear', 'dseep', 'dsegh', 'dsei', 'dse'],
 'f': ['dsfc', 'dsfl', 'dsf'],
 'g': ['dsg'],
 'h': ['dshield', 'dshell', 'dsharp', 'dshk', 'dshs', 'dsh'],
 'i': ['dsif', 'dsip', 'dsi'],
 'j': ['dsj'],
 'k': ['dsknectd', 'dsk'],
 'l': ['dslreports', 'dslink', 'dslite'],
 'm': ['dsma-notice', 'dsm-5', 'dsml', 'dsmb', 'dsmc', 'dsm'],
 'n': ['dsniff', 'dsn-2', 'dsn1', 'dsn'],
 'o': ['dsos', 'dso'],
 'p': ['dsp-2230',
       'dsplayer',
       'dspace',
       'dsp-4',
       'dspca',
       'dsp1',
       'dspf',
       'dsps',
       'dsp'],
 'q': ['dsqi', 'dsq'],
 'r': ['dsrflow', 'dsrr', 'dsrp', 'dsr'],
 's': ['dssim', 'dssat', 'dssp', 'dsst', 'dssi', 'dssc', 'dssa', 'dss'],
 't': ['dstore', 'dstld', 'dstv', 'dsto', 'dstc'],
 'u': ['dsungaripteroidea',
       'dsungaripteridae',
       'dsungaripterus',
       'dsup',
       'dsu'],
 'v': ['dsvii', 'dsvd', 'dsv'],
 'w': ['dsw'],
 'x': ['dsx'],
 'y': ['dsy'],
 'z': ['dsz']}
