
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-08-19T12:00:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "76d551fd04719fb0ca2e0825f72fe43e9f67df38",
 "version": "1.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
