
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tl = {'_': ["tl'etinqox-t'in_government_office",
       "tl'esqox_first_nation",
       'tl_ultralight_condor'],
 'a': ['tlahuelilpan_pipeline_explosion',
       'tlaxco_municipality,_tlaxcala',
       'tlaltecatzin_of_cuauhchinanco',
       'tlalnepantla_railway_station',
       'tla-o-qui-aht_first_nations',
       'tlaxco_municipality,_puebla',
       'tlacoquemecatl_arts_garden',
       'tla_players_championship',
       'tlatelolco_metro_station',
       'tla_entertainment_group',
       'tlaltenco_metro_station',
       'tlaxcala_city_cathedral',
       'tlatelolco,_mexico_city',
       'tlahualilo_de_zaragoza',
       'tlacuilas_y_retrateras',
       'tlacolula_de_matamoros',
       "tlaloc's_leopard_frog",
       'tlahuac_metro_station',
       'tlajomulco_de_zuniga',
       'tlalixtac_de_cabrera',
       'tlalnepantla_de_baz',
       'tlacotepec_de_mejia',
       'tlapa_de_comonfort',
       'tlazala_de_fabela',
       'tlacote_el_alto',
       'tlacote_el_bajo'],
 'c': ['tlc_casino_enterprises', 'tlc_2016_tour'],
 'e': ['tlemcen_national_park'],
 'i': ['tlicho_all-season_road'],
 'o': ['tlokwe_local_municipality', 'tlomackie_street,_warsaw'],
 's': ['tls_termination_proxy'],
 'u': ['tluszcz_railway_station', 'tluszcz,_makow_county']}
