
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uv = {'_': ['uv-sensitive_syndrome',
       'uv_detectors',
       'uv_mapping',
       'uv_pinning',
       'uv_express',
       'uv_coating',
       'uv-b_lamps',
       'uv_marker',
       'uv_tattoo',
       'uv_filter',
       'uv_curing'],
 'a': ['uvariodendron_pycnophyllum',
       'uvariodendron_occidentale',
       'uvariodendron_usambarense',
       'uvariodendron_oligocarpum',
       'uvariodendron_connivens',
       'uvariodendron_giganteum',
       'uvariopsis_vanderystii',
       'uvariodendron_anisatum',
       'uvariodendron_gorgonis',
       'uvariopsis_bisexualis',
       'uvariopsis_submontana',
       'uvariopsis_korupensis',
       'uvaria_kweichowensis',
       'uvariodendron_kirkii',
       'uvariodendron_fuscum',
       'uvariopsis_tripetala',
       'uvaria_leichhardtii',
       'uvariopsis_dicaprio',
       'uvariastrum_zenkeri',
       'uvasagharam_stotra',
       'uvaria_grandiflora',
       'uvariopsis_zenkeri',
       'uvarovsky_district',
       'uvaria_macrophylla',
       'uvanilla_olivacea',
       'uvanilla_buschii',
       'uvanilla_babelis',
       'uvarus_granarius',
       'uvarus_lacustris',
       'uvatsky_district',
       'uvanilla_unguis',
       'uvarus_subtilis',
       'uvalda,_georgia',
       'uvac_monastery',
       'uvarus_texanus',
       'uvas_reservoir',
       'uvalde_lindsey',
       'uvaria_dulcis',
       'uvaldo_acosta',
       'uvalde,_texas',
       'uvaria_chamae',
       'uva,_missouri',
       'uvarus_livens',
       'uvais_karnain',
       'uva_province',
       'uvarus_falli',
       'uva,_wyoming',
       'uvaria_narum',
       'uvaldo_luna',
       'uva_letzion',
       'uva,_russia',
       'uvaria_rufa',
       'uvais_ahmad',
       'uva_method',
       'uvas_creek',
       'uvac,_rudo',
       'uvas_falls',
       'uva_river',
       'uvagut_tv',
       'uva_tosca',
       'uvais_ii',
       'uva_next',
       'uva_rara'],
 'b': ['uvb-induced_apoptosis', 'uvbie_language'],
 'c': ['uvc-based_preservation'],
 'd': ['uvdal'],
 'e': ['uveitis-glaucoma-hyphema_syndrome',
       'uvezbeli,_cumayeri',
       'uversnatten_rock',
       'uvelsky_district',
       'uvedale_lambert',
       'uvedale_corbett',
       'uveal_melanoma',
       'uvezdere,_can',
       'uvecik,_ezine',
       'uve_sabumei',
       'uveys_pasha',
       'uvero_alto',
       'uven_spur'],
 'f': ['uvf'],
 'g': ['uvg_urbanstar'],
 'i': ['uvinza-musongati-gitega_railway',
       'uvidunda_mountains',
       'uvinsky_district',
       'uvira_territory',
       'uvis_stazdins',
       'uvis_helmanis',
       'uvitonic_acid',
       'uvijek_blizu',
       'uvita_island',
       'uvis_kalnins',
       'uvision_air',
       'uvitic_acid'],
 'j': ['uvjeca'],
 'o': ['uvo_holscher'],
 'r': ['uvrabc_endonuclease'],
 's': ['uvs_province', 'uvsis_uav', 'uvs_lake'],
 't': ['uvt_aero'],
 'u': ['uvular-epiglottal_consonant',
       'uvularia_sessilifolia',
       'uvularia_grandiflora',
       'uvularia_perfoliata',
       'uvularia_floridana',
       'uvularia_puberula',
       'uvular_consonant',
       'uvula_piercing',
       'uvular_stop',
       'uvu_review'],
 'v': ['uvv_utrecht'],
 'w': ['uvw_mapping'],
 'x': ['uvx']}
