
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_u_ = {'_': ['u-101-class_submarine',
       'u-107-class_submarine',
       'u-43-class_submarine',
       'u-20-class_submarine',
       'u-50-class_submarine',
       'u-10-class_submarine',
       'u-27-class_submarine',
       'u-48-class_submarine',
       'u-52-class_submarine',
       'u-1-class_submarine',
       'u._aswathanarayana',
       'u._lakshmikandhan',
       'u._chandrasekhar',
       'u._thisaiveeran',
       'u2_discography',
       'u._nepalensis',
       'u._mathivanan',
       'u._floribunda',
       'u1_university',
       'u._orientalis',
       'u._prathibha',
       'u20_sm-sarja',
       'u._macrourus',
       'u218_singles',
       'u-9_weddigen',
       'u._australis',
       'u._africana',
       'u._mexicana',
       'u218_videos',
       'u._maculata',
       'u._japonica',
       'u._srinivas',
       'u2_clothing',
       'u1_records',
       'u,_pohnpei',
       'u._formosa',
       'u._sagayam',
       'u._elegans',
       'u._vasuki',
       'u16_girls',
       'u._nitida',
       'u._rajesh',
       'u._lutea',
       'u21_ligi',
       'u2_tower',
       'u2_3d'],
 'a': ['u_andromedae',
       'u_airlines',
       'u_antliae',
       'u_aquilae',
       'u_account',
       'u_aquarii'],
 'b': ['u-boote_westwarts!',
       'u-boat_prisoner',
       'u-boat_campaign',
       'u-bar_formation',
       'u-bahn_serfaus',
       'u-bix_classic',
       'u.b._funkeys',
       'u-boat_worx',
       'u.be_love',
       'u_brown',
       'u_bar'],
 'c': ['u-carmen_ekhayelitsha',
       'u_camelopardalis',
       'u.c._albinoleffe',
       'u.c._sampdoria',
       'u_centauri',
       'u_carinae',
       'u_class'],
 'd': ['u.d._vilafranquense',
       'u.d.o._discography',
       'u.d._oliveirense',
       'u.d._santana',
       'u.d._gandara',
       'u.d.r._alges',
       'u_dhammaloka',
       'u.d._leiria',
       'u.d._valdez',
       'u-drop_inn',
       'u.d._serra',
       'u.d._tocha'],
 'e': ['u_equulei', 'u_engine'],
 'f': ['u-fly_alliance', 'u.f.c.i._tomar', 'u_fleku'],
 'g': ['u-god_discography',
       'u_geminorum',
       'u_gambira',
       'u_gallery',
       'u_godini',
       'u_gurl'],
 'h': ['u-haul_lesbian', 'u_herculis', 'u_hydrae'],
 'i': ['u_interface'],
 'j': ['u_jeong-hwan', 'u_jung-ho'],
 'k': ['u-kiss_discography',
       'u.k._remixes',
       'u_khanapur',
       'u.k._subs',
       'u_khandi',
       'u_kadam',
       'u_kyin',
       'u_kala'],
 'l': ['u-line_corporation',
       'u-land_airlines',
       'u_language',
       'u_lacertae',
       'u_line',
       'u_live',
       'u_lwin'],
 'm': ['u_monocerotis',
       'u_microscopii',
       'u_magnovenju',
       'u_medvidku',
       'u_magazine',
       'u_mobile',
       'u_myint',
       'u_mumba',
       'u_minh',
       'u_mad'],
 'n': ['u.n._squadron',
       'u;nee_code',
       'u_narada',
       'u-no_bar',
       'u.n._me',
       'u_nyun',
       'u_nu'],
 'o': ['u2opia_mobile', 'u_ogledalu', 'u_orionis', 'u_ottama'],
 'p': ['u.p.c._tavagnacco',
       'u-prince_series',
       'u-pick_live',
       'u.p._wilson',
       'u-pass_bc',
       'u_pandita',
       'u_played',
       'u_ponnya'],
 'q': ['u-quadratic_distribution'],
 'r': ['u-rescue_villa',
       'u.r._mirense',
       'u_raskoraku',
       'u.r._cadima',
       'u-ram_choe',
       'u_raschid',
       'u_razak',
       'u_road'],
 's': ['u.s.d._fiesolecaldine',
       'u-shaped_development',
       'u.s.a._confidential',
       'u.s.-japan_alliance',
       'u-sea_saskatchewan',
       'u.s._international',
       'u.s.-japan_council',
       'u.s.d._castelsardo',
       'u.s.-japan_caucus',
       'u.s._snowboarding',
       'u.s.d._olginatese',
       'u.s.d._caravaggio',
       'u.s._customhouse',
       'u.s._mirandolese',
       'u.s._healthworks',
       'u.s.c._colognese',
       'u-shaped_valley',
       'u.s._pharmacist',
       'u.s.d._zagarolo',
       'u.s._poggibonsi',
       'u.s._renditions',
       'u.s._opitergina',
       'u.s._geothermal',
       'u.s.d._palmese',
       'u.s._christmas',
       'u.s._cremonese',
       'u.s.c._paredes',
       'u.s.d._lavello',
       'u.s._tolentino',
       'u-sea_colonsay',
       'u.s._pergolese',
       'u.s._gavorrano',
       'u.s._arzanese',
       'u.s._cellular',
       'u.s._newswire',
       'u.s._inveruno',
       'u.s.a._comics',
       'u.s._ordnance',
       'u.s._siracusa',
       'u.s._concrete',
       'u.s._ciserano',
       'u.s._woodland',
       'u.s.o._calcio',
       'u.s.d._novese',
       'u.s._pianese',
       'u.s._bancorp',
       'u.s._adriese',
       'u.s._royalty',
       'u.s._paolana',
       'u.s._fiumana',
       'u.s._country',
       'u.s._venafro',
       'u.s._classic',
       'u.s._retrace',
       'u.s._bitonto',
       'u.s._agbank',
       'u.s._squash',
       'u_sagittae',
       'u.s._mills',
       'u.s._russi',
       'u.s._crush',
       'u.s._bombs',
       'u.s._jones',
       'u.s._manga',
       'u.s._music',
       'u.s._chaos',
       'u_sung-eun',
       'u.s._lecce',
       'u.s._girls',
       'u.s._state',
       'u.s._klans',
       'u.s._acres',
       'u.s._agent',
       'u.s._steel',
       'u.s._maple',
       'u.s._games',
       'u.s._sugar',
       'u.s._open',
       'u_scorpii',
       'u.s._gold',
       'u.s._lady',
       'u.s._male',
       'u.s._seal',
       'u_skripcu',
       'u_select',
       'u.s._cup',
       'u_series',
       'u.s._500',
       'u_sports',
       'u_street',
       'u_smile',
       'u_set',
       'u_saw'],
 't': ['u.t.c.a._popekinsky',
       'u-turn_infinity',
       'u/tex_wranglers',
       'u_television',
       'u-turn_audio',
       'u-turn_gmbh',
       'u_tong-chuk',
       'u_thuzana',
       'u_taphao',
       'u_thaung',
       'u_train',
       'u_thant',
       'u_tin',
       'u_tak'],
 'u': ['u_understand'],
 'v': ['u_vulpeculae', 'u-verse_tv', 'u_vycepu', 'u_vimala', 'u_visa'],
 'w': ["u'wa_people", 'u_wisara', 'u_wave'],
 'y': ['u-ya_asaoka', 'u_yang-ja'],
 'z': ['u_zaboravu']}
