
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uh = {'_': ['uh-downtown_station',
       'uh_mamma',
       'uh_atoll',
       'uh_huh',
       'uh_oh',
       'uh_25'],
 'a': ['uhangri_formation', 'uhami_language', 'uhamu_kanzibe'],
 'b': ['uhb'],
 'c': ['uhc_zugerland', 'uhc_stockerau'],
 'd': ['uhde', 'uhd'],
 'e': ['uhehlia_nerissidioides',
       'uhersko,_ukraine',
       'uherce_mineralne',
       'uherske_hradiste',
       'uhehlia_pardalis',
       'uhelna_pribram',
       'uhersky_ostroh',
       'uheiji_uehata',
       'uhehe_fiscal',
       'uhersky_brod'],
 'f': ['uhf_connector', 'uhf-tv_inc.', 'uhf_anime', 'uhf_ii', 'uhf_cb'],
 'g': ['uhg'],
 'h': ['uhh_ahh'],
 'i': ['uhikarotid', 'uhiaguri', 'uhingen', 'uhila', 'uhid', 'uhi'],
 'k': ['uhkd', 'uhk'],
 'l': ['uhlerstown-frenchtown_bridge',
       'uhlerstown,_pennsylvania',
       'uhlorchestia_uhleri',
       'uhligia_schilskyi',
       'uhlirske_janovice',
       'uhlenhorster_hc',
       'uhlirska_lhota',
       'uhlenhuth_test',
       'uhland,_texas',
       'uhl_anomaly',
       'uhl_pottery',
       'uhl,_kansas',
       'uhl_river'],
 'm': ['uhm_hyun-kyung',
       'uhm_tae-woong',
       'uhm_bok-dong',
       'uhm_jung-hwa',
       'uhm_tae-goo',
       'uhm_ji-won'],
 'n': ['uhniv', 'uhnin', 'uhna', 'uhn'],
 'o': ['uhorska_ves', 'uhod_area', 'uhod_road'],
 'p': ['uhp'],
 'q': ['uhq'],
 'r': ['uhrichsville,_ohio',
       'uhrovske_podhradie',
       'uhrenmuseum_beyer',
       'uhreticka_lhota',
       'uhrik_truckers'],
 's': ['uhsapw', 'uhse', 'uhsn', 'uhss', 'uhs'],
 't': ["uhthoff's_phenomenon", 'uhtju_islands'],
 'u': ['uhunoma_osazuwa',
       'uhuru_movement',
       'uhuru_monument',
       'uhuru_kenyatta',
       'uhuru_hamiter',
       'uhuru_gardens',
       'uhuru_stadium',
       'uhuru_design',
       'uhuru_afrika',
       "uhura's_song",
       'uhuru_mobile',
       'uhuru_torch',
       'uhuru_times',
       'uhuru_park'],
 'v': ['uhv_jaguars'],
 'w': ['uhwudong'],
 'y': ['uhyst', 'uhy']}
