
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fs = {'_': ['fs-a1wsx', 'fs-vdsl', 'fs-1016', 'fs-fhss', 'fs1'],
 'a': ['fsarchiver', 'fsai', 'fsa'],
 'b': ['fsb'],
 'c': ['fscons',
       'fscn2',
       'fscn1',
       'fscn3',
       'fscan',
       'fscs',
       'fscc',
       'fscb',
       'fsc2',
       'fsck',
       'fsc'],
 'd': ['fsd'],
 'e': ['fsevents', 'fse'],
 'f': ['fsfo', 'fsf'],
 'g': ['fsg'],
 'h': ['fshb', 'fshs', 'fsh'],
 'i': ['fsim', 'fsia', 'fsif', 'fsi'],
 'j': ['fsj'],
 'k': ['fsk'],
 'l': ['fsl'],
 'm': ['fsma', 'fsm'],
 'n': ['fsn'],
 'o': ['fsom', 'fso'],
 'p': ['fspl', 'fsp'],
 'q': ['fsq'],
 'r': ['fsra', 'fsr'],
 's': ['fssa', 'fssp', 'fssf', 'fssc', 'fsst', 'fss'],
 't': ['fstab', 'fstl1', 'fstl3', 'fsta', 'fstv', 'fst'],
 'u': ['fsu'],
 'v': ['fsv'],
 'w': ['fsw'],
 'y': ['fsy']}
