
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fg = {'_': ['fg-8205', 'fg-7142', 'fg-02', 'fg-46', 'fg-15', 'fg-36', 'fg-47'],
 'a': ['fga'],
 'b': ['fgb'],
 'c': ['fgc-9', 'fgci', 'fgcs', 'fgc'],
 'd': ['fgd4', 'fgd2', 'fgd1', 'fgd3', 'fgd'],
 'e': ['fge'],
 'f': ['fgfr1op2',
       'fgf15/19',
       'fgfr1op',
       'fgfbp1',
       'fgf18',
       'fgf15',
       'fgf11',
       'fgf14',
       'fgf19',
       'fgf12',
       'fgf22',
       'fgf21',
       'fgf20',
       'fgf16',
       'fgf10',
       'fgf13',
       'fgf17',
       'fgf7',
       'fgf5',
       'fgf6',
       'fgf4',
       'fgf1',
       'fgf3',
       'fgf9',
       'fgf8',
       'fgf'],
 'g': ['fgg'],
 'h': ['fgh'],
 'i': ['fgin-143', 'fgin-127', 'fgi-106', 'fgi-103', 'fgi-104', 'fgi'],
 'l': ['fgl2', 'fgl1', 'fgl'],
 'n': ['fgn'],
 'o': ['fgo'],
 'p': ['fgp'],
 'r': ['fgr'],
 's': ['fgs'],
 't': ['fgt'],
 'u': ['fgura', 'fgu'],
 'v': ['fgv'],
 'w': ['fgw']}
