
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_f_ = {'_': ['f-15,599',
       'f-15063',
       'f15845',
       'f-010',
       'f1000',
       'f16x9',
       'f-125',
       'f2008',
       'f430',
       'f110',
       'f136',
       'f300',
       'f174',
       'f13b',
       'f400',
       'f100',
       'f140',
       'f750',
       'f420',
       'f500',
       'f310',
       'f103',
       'f170',
       'f650',
       'f108',
       'f130',
       'f-19',
       'f200',
       'f16c',
       'f120',
       'f700',
       'f107',
       'f101',
       'f805',
       'f50',
       'f24',
       'f61',
       'f54',
       'f55',
       'f97',
       'f27',
       'f72',
       'f48',
       'f67',
       'f58',
       'f29',
       'f39',
       'f12',
       'f18',
       'f14',
       'f64',
       'f70',
       'f56',
       'f43',
       'f90',
       'f89',
       'f36',
       'f11',
       'f99',
       'f20',
       'f69',
       'f25',
       'f19',
       'f60',
       'f31',
       'f30',
       'f63',
       'f21',
       'f91',
       'f22',
       'f84',
       'f41',
       'f75',
       'f47',
       'f32',
       'f88',
       'f82',
       'f66',
       'f85',
       'f17',
       'f40',
       'f10',
       'f81',
       'f13',
       'f42',
       'f26',
       'f49',
       'f35',
       'f59',
       'f16',
       'f44',
       'f68',
       'f15',
       'f53',
       'f28',
       'f71',
       'f37',
       'f65',
       'f80',
       'f38',
       'f57',
       'f46',
       'f51',
       'f23',
       'f62',
       'f94',
       'f33',
       'f52',
       'f34',
       'f45'],
 'a': ['f.a.t.a.l.',
       'f.a.l.t.u',
       'f-algebra',
       'f-atpase',
       'f.a.l.',
       'f8a1',
       'f2a'],
 'b': ['f-body', 'f2b', 'f5b'],
 'c': ['f-coalgebra', 'f-crystal', 'f-center', 'f-clamp', 'f.cuz', 'f2c'],
 'd': ['f-distribution', 'f-divergence', 'f-droid'],
 'e': ['f.e.e.l.i.n.g.c.a.l.l.e.d.l.i.v.e', 'f.e.a.r.'],
 'f': ['f-f-f-falling',
       'f2freestylers',
       'f-factor',
       'f-flat',
       'f-fcsr',
       'f2fs',
       'f2f',
       'f3f',
       'f&f',
       'f9f'],
 'g': ['f.godmom', 'f&g', 'f2g'],
 'h': ['f-hemoglobin'],
 'i': ['f.i.s.co.', 'f.i.s.h.', 'f-insas', 'f.i.r.', 'f.i.t.', 'f*ink', 'f-iv'],
 'l': ['f-league',
       'f-letter',
       'f.league',
       'f-liiga',
       'f-logic',
       'f.l.y.',
       'f-lock',
       'f-law',
       'f.lux'],
 'm': ['f-minus', "f'murr", 'f-man', 'f&m'],
 'n': ['f-number', 'f4n'],
 'o': ['f.o.a.d.'],
 'p': ['f-plane', 'f-plan', 'f-punk', 'f.p.1', 'f6p'],
 'r': ['f.r.i.d.a.y.',
       'f.r.u.i.t.s.',
       'f@r@cullali',
       'f.r.e.s.h.',
       'f@rz@lioba',
       'f-rating',
       'f-ratio',
       'f@r@hli',
       'f@rzili',
       'f@rzali',
       'f@rxani',
       'f0rest',
       'f@rras',
       'f@rcan',
       "f'real",
       'f2rl3',
       'f2rl2'],
 's': ['f-statistics',
       'f-statistic',
       'f-segment',
       'f.stokes',
       'f-secure',
       'f-sharp',
       'f-score',
       'f-stops',
       'f-space',
       'f-spot',
       'f-side',
       'f-star',
       'f.s.o.'],
 't': ['f@tullaqislaq',
       'f.t.f.o.m.f.',
       'f@t@lik@nd',
       'f@t@lip@y@',
       'f-tractin',
       'f.t.t.w.',
       'f-theory',
       'f.t.f.o.',
       'f@tallar',
       'f.t.a.',
       'f-test',
       'f-type',
       'f-term',
       'f&tm'],
 'u': ['f.u.e.p.', 'f.u.n.k.', 'f5u'],
 'w': ['f5wc', 'f+w'],
 'x': ['f@xrali', 'f/x2', 'f/x'],
 'y': ['f.y.p'],
 'z': ['f-zero']}
