
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fj = {'a': ['fjaerlandsfjorden',
       'fjardarheidargong',
       'fjallbackamorden',
       'fjalla-eyvindur',
       'fjardhundraland',
       'fjardvattingen',
       'fjaderholmarna',
       'fjadrargljufur',
       'fjardsjomala',
       'fjallmaraton',
       'fjallhyddan',
       'fjallsarlon',
       'fjardabyggd',
       'fjallabyggd',
       'fjardhundra',
       'fjallsatern',
       'fjaervatnet',
       'fjallbacka',
       'fjallavatn',
       'fjallraven',
       'fjardingen',
       'fjaereheia',
       'fjalkinge',
       'fjaervoll',
       'fjaerland',
       'fjalarr',
       'fjaler',
       'fjaere',
       'fjaera',
       'fjard',
       'fjall',
       'fja'],
 'b': ['fjb'],
 'c': ['fjca', 'fjc'],
 'd': ['fjd'],
 'e': ['fjernsynsteatret',
       'fjeldeventyret',
       'fjellsjokampen',
       'fjellbergella',
       'fjellvaersoya',
       'fjellheisen',
       'fjerritslev',
       'fjelbergoya',
       'fjellstrand',
       'fjerdvatnet',
       'fjellvatnet',
       'fjellfoten',
       'fjellestad',
       'fjellhamar',
       'fjell-ljom',
       'fjerdingby',
       'fjellinjen',
       'fjellsrud',
       'fjellheim',
       'fjeldsted',
       'fjermeros',
       'fjeldstad',
       'fjellstad',
       'fjelberg',
       'fjellfly',
       'fjelldal',
       'fjellner',
       'fjergen',
       'fjelso',
       'fjelde',
       'fjell'],
 'g': ['fjg'],
 'i': ['fji'],
 'm': ['fjm'],
 'o': ['fjolnisvollur',
       'fjolsvinnsmal',
       'fjordservice',
       'fjordaposten',
       'fjordabladet',
       'fjorvatnet',
       'fjordkraft',
       'fjordingen',
       'fjordland',
       'fjordgard',
       'fjortofta',
       'fjordman',
       'fjotland',
       'fjolvar',
       'fjolnir',
       'fjordia',
       'fjoloy',
       'fjord1',
       'fjolla',
       'fjord',
       'fjort',
       'fjorm'],
 'r': ['fjr'],
 's': ['fjs'],
 'u': ['fjugesta', 'fjuckby', 'fjuken'],
 'x': ['fjx1']}
