
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tl = {'_': ["tl'etinqox-t'in",
       'tl-ultralight',
       'tl-1238',
       'tl-599',
       'tl431',
       'tl.37',
       'tl-10',
       'tl-6'],
 'a': ['tlahuizcalpantecuhtli',
       'tlapalizquixochtzin',
       'tlacacuitlahuatzin',
       'tlacoachistlahuaca',
       'tlacuilolxochtzin',
       'tlalchiyahualica',
       'tlaximaltepoztli',
       'tlatlauquitepec',
       'tlalchitonatiuh',
       'tlalnelhuayocan',
       'tlacochcalcatl',
       'tlaquiltenango',
       'tlalixtaquilla',
       'tlacuilotepec',
       'tlachichilco',
       'tlaxochimaco',
       'tlalcuahuitl',
       'tlaltecuhtli',
       'tlahuelpuchi',
       'tlacateccatl',
       'tlacotzontli',
       'tlahuelilpan',
       'tlaltecatzin',
       'tlacotalpan',
       'tlalpujahua',
       'tlalmanalco',
       'tlazolteotl',
       'tlatolophus',
       'tlapitzalli',
       'tlacojalpan',
       'tlahuiltepa',
       'tlapanaloya',
       'tlaltenango',
       'tlaltizapan',
       'tlalixcoyan',
       'tlanepantla',
       'tlaquepaque',
       'tlachichila',
       'tlachichuca',
       'tlalocayotl',
       'tlalocohyla',
       'tlacotepec',
       'tlamanalco',
       'tlayacapan',
       'tlapacoyan',
       'tlaltetela',
       'tlatelolco',
       'tlaxcaltec',
       'tlatolqaca',
       'tlapehuala',
       'tlapallite',
       'tlacolulan',
       'tlaxcoapan',
       'tlazazalca',
       'tlacateotl',
       'tlanchinol',
       'tlahuicole',
       'tlaxcoaque',
       'tlanalapa',
       'tlapanala',
       'tlalocite',
       'tlapacoya',
       'tlahuapan',
       'tlacaelel',
       'tlanchana',
       'tladistad',
       'tlangmawi',
       'tlagasana',
       'tlaquilpa',
       'tlalchapa',
       'tlalixtac',
       'tlamatini',
       'tlacopan',
       'tlatoani',
       'tlayucan',
       'tlacoapa',
       'tlacenka',
       'tlaxcala',
       'tlascala',
       'tlatilco',
       'tlatlaya',
       'tlamemeh',
       'tlaxiaco',
       'tlapanec',
       'tlalocan',
       'tlachtga',
       'tlacoyo',
       'tlalpan',
       'tlahuac',
       'tlabung',
       'tlayuda',
       'tlamess',
       'tlalim',
       'tlaxco',
       'tlaola',
       'tlawng',
       'tlalli',
       'tlamim',
       'tlaloc',
       'tlass',
       'tladi',
       'tlauh',
       'tla+',
       'tla'],
 'b': ['tlbleed', 'tlb'],
 'c': ['tlcbet', 'tlc'],
 'd': ['tldp'],
 'e': ['tlepolemoides',
       'tlepolemus',
       'tlephusa',
       'tlemcen',
       'tlen.pl',
       'tleson',
       'tlepsh',
       'tleil',
       'tlell',
       'tlen',
       'tle1',
       'tle3',
       'tle4',
       'tle2',
       'tle'],
 'f': ['tlf'],
 'g': ['tlgadintsi', 'tlg'],
 'h': ['tlhareseleele', 'tlh'],
 'i': ['tlillan-tlapallan',
       'tlilpotoncatzin',
       'tliltocatl',
       'tlilapan',
       'tlibisho',
       'tlidjene',
       'tlilhua',
       'tlingit',
       'tlicho',
       'tlisi',
       'tlik',
       'tlia',
       'tli'],
 'j': ['tlj'],
 'k': ['tlk2', 'tlk1', 'tlk'],
 'l': ['tll2', 'tlli', 'tll1', 'tll'],
 'm': ['tlmace', 'tlm'],
 'n': ['tln-europa', 'tlnovelas', 'tln2', 'tln1', 'tln'],
 'o': ['tloquenahuaque',
       'tlokowisko',
       'tloczyzna',
       'tlobzoda',
       'tlokweng',
       'tloczewo',
       'tlokowo',
       'tlogob',
       'tloos',
       'tlokh',
       'tloki',
       'tlou',
       'tlos',
       'tlon',
       'tlo'],
 'p': ['tlpa', 'tlp'],
 'q': ['tlqp-62'],
 'r': ['tlr4-in-c34',
       'tlr10',
       'tlr3',
       'tlr2',
       'tlr5',
       'tlr6',
       'tlr4',
       'tlr8',
       'tlr9',
       'tlr7',
       'tlr'],
 's': ['tls-psk', 'tls-srp', 'tlsta', 'tls'],
 't': ['tltx', 'tlt'],
 'u': ['tlustomosty',
       'tlustoreby',
       'tlumaczow',
       'tluchowek',
       'tlucznice',
       'tluczewo',
       'tlungvel',
       'tlumacov',
       'tluchowo',
       'tlusciec',
       'tlucznia',
       'tlustice',
       'tlukawy',
       'tlubice',
       'tlukomy',
       'tlumach',
       'tluszcz',
       'tluczan',
       'tlumak',
       'tlucna',
       'tluste',
       'tlugwe',
       'tlumy',
       'tlu'],
 'v': ['tlvfest', 'tlv1', 'tlv'],
 'w': ['tlw'],
 'x': ['tlx1', 'tlx2', 'tlx3', 'tlx'],
 'y': ['tlyustenkhabl', 'tlyaumbetovo', 'tlyarata', 'tlyanada', 'tlya'],
 'z': ['tlz']}
