
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_td = {'_': ['td-gammon', 'td/smp', 'td2000', 'td-1a', 'td15', 'td-2', 'td-3', 'td1'],
 'a': ['tdac', 'tda'],
 'b': ['tdbzcholine', 'tdb'],
 'c': ['tdcaa', 'tdcs', 'tdc'],
 'd': ['tddb', 'tdd'],
 'e': ['tde'],
 'f': ['tdfa', 'tdf'],
 'g': ['tdg'],
 'h': ['tdhs', 'tdh'],
 'i': ['tdindustries', 'tdiq', 'tdi'],
 'k': ['tdk-micronas', 'tdkr', 'tdk'],
 'l': ['tdls', 'tdl'],
 'm': ['tdm-gcc', 'tdmoip', 'tdma', 'tdmi', 'tdm'],
 'n': ['tdna', 'tdn'],
 'o': ['tdor', 'tdo'],
 'p': ['tdp-4-oxo-6-deoxy-alpha-d-glucose-3,4-oxoisomerase', 'tdp1', 'tdp'],
 'r': ['tdrs-12',
       'tdrs-10',
       'tdrs-13',
       'tdrs-11',
       'tdrs-1',
       'tdrs-4',
       'tdrs-b',
       'tdrs-5',
       'tdrs-7',
       'tdrs-6',
       'tdrs-9',
       'tdrs-8',
       'tdrs-3',
       'tdrd3',
       'tdrd7',
       'tdrkh',
       'tdra',
       'tdri',
       'tdr'],
 's': ['tdsoft', 'tdshs', 'tdss', 'tds'],
 't': ['tdtv', 'tdt'],
 'u': ['tdu'],
 'v': ['tdvision'],
 'w': ['tdw'],
 'y': ['tdy']}
