
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tg = {'_': ['tg-4a',
       'tg-1',
       'tg24',
       'tg-5',
       'tg-4',
       'tg&y',
       'tg5',
       'tg3',
       'tg2',
       'tg1',
       'tg+',
       'tg4'],
 'a': ['tga'],
 'b': ['tgba01ad', 'tgb'],
 'c': ['tgcom24', 'tgcom', 'tgc-1', 'tgcc', 'tgc'],
 'e': ['tge'],
 'f': ['tgfb1i1', 'tgfbro', 'tgfbr3', 'tgfbi', 'tgfa', 'tgf'],
 'g': ['tgg'],
 'h': ['tghat', 'tghs', 'tgh'],
 'i': ['tgif2', 'tgif', 'tgi'],
 'k': ['tgk'],
 'l': ['tgl'],
 'm': ['tgm4', 'tgm5', 'tgm6', 'tgm3', 'tgm'],
 'n': ['tgn'],
 'o': ['tgoln2', 'tgo'],
 'p': ['tgp'],
 'r': ['tgr'],
 's': ['tgscom', 'tgs1', 'tgs'],
 't': ['tgt'],
 'u': ['tguard', 'tguma', 'tgu'],
 'v': ['tgv'],
 'w': ['tgw'],
 'y': ['tgy'],
 'z': ['tgz']}
