
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fc = {'_': ['fc-group', 'fc-75', 'fc4', 'fc6', 'fc2', 'fc3'],
 'a': ['fcak-liberia',
       'fca/mr',
       'fcaca',
       'fcaps',
       'fcab',
       'fcas',
       'fcat',
       'fcar',
       'fca'],
 'b': ['fcbb', 'fcba', 'fcbs', 'fcb'],
 'c': ['fcca', 'fccj', 'fccf', 'fcch', 'fccp'],
 'd': ['fcds', 'fcda', 'fcd'],
 'e': ['fcer1g', 'fcer1a', 'fcer1', 'fceux', 'fce'],
 'f': ['fcf1', 'fcf'],
 'g': ['fcgr3a',
       'fcgr1a',
       'fcgr3b',
       'fcgr2b',
       'fcgr2a',
       'fcgbp',
       'fcgs',
       'fcg'],
 'h': ['fchsd1', 'fchsd2', 'fcho2', 'fcho1', 'fchs', 'fch'],
 'i': ['fcitx', 'fcic', 'fcii', 'fcim', 'fci'],
 'j': ['fcj'],
 'k': ['fckh8', 'fck'],
 'l': ['fcl-web', 'fcl'],
 'm': ['fcmov', 'fcmb', 'fcmc', 'fcmm', 'fcmr', 'fcm'],
 'n': ['fcn3', 'fcn1', 'fcn2', 'fcn'],
 'o': ['fco-im', 'fcot', 'fco'],
 'p': ['fcpa', 'fcps', 'fcp'],
 'r': ['fcrl5',
       'fcrl2',
       'fcrl1',
       'fcrl3',
       'fcrla',
       'fcrl4',
       'fcron',
       'fcra',
       'fcr'],
 's': ['fcs-2',
       'fcs-1',
       'fcs-3',
       'fcsl',
       'fcsd',
       'fcss',
       'fcsb',
       'fcsc',
       'fcs'],
 't': ['fct'],
 'u': ['fcurve', 'fcu'],
 'v': ['fcv'],
 'x': ['fcx'],
 'z': ['fcz']}
