
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fm = {'_': ['fm-index',
       'fm-3000',
       'fm-2030',
       'fm-uwb',
       'fm-11',
       'fm302',
       'fm104',
       'fm802',
       'fm12',
       'fm-7',
       'fm10',
       'fm-8',
       'fm2',
       'fm1',
       'fm3',
       'fm!',
       'fm7',
       'fm4'],
 'a': ['fman', 'fma'],
 'b': ['fmb'],
 'c': ['fmcs', 'fmca', 'fmc'],
 'd': ['fmdg', 'fmd'],
 'e': ['fmextra', 'fmea', 'fmep', 'fme'],
 'f': ['fmfc', 'fmf'],
 'g': ['fmg'],
 'h': ['fmhs', 'fmh'],
 'i': ['fmiso', 'fmia', 'fmic', 'fmi'],
 'j': ['fmj'],
 'k': ['fmk-3', 'fmk'],
 'l': ['fmllr', 'fml'],
 'm': ['fmm'],
 'n': ['fmnl1', 'fmnl2', 'fmnl3', 'fmn'],
 'o': ['fmovies', 'fmo5', 'fmod', 'fmo4', 'fmo2', 'fmo'],
 'p': ['fmp'],
 'q': ['fmqb'],
 'r': ['fmrfamide', 'fmraam', 'fmr1', 'fmr'],
 's': ['fmslogo', 'fmss', 'fmsr', 'fmsx', 'fms'],
 't': ['fmt'],
 'u': ['fmu'],
 'v': ['fmv'],
 'x': ['fmx'],
 'y': ['fmylife']}
