
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jp = {'_': ['jp/politikens_hus',
       'jp_dellacamera',
       'jp_motorsports',
       'jp_triegaardt',
       'jp_pietersen',
       'jp_aerospace',
       'jp_maccallum',
       'jp_ferreira',
       'jp_jamieson',
       'jp_karliak',
       'jp1_remote',
       'jp_auclair',
       'jp_houston',
       'jp_duminy',
       'jp_rooney',
       'jp_harris',
       'jp_tokoto',
       'jp_simoes',
       'jp_cooney',
       'jp_miller',
       'jp_cooper',
       'jp_hasson',
       'jp_sears',
       'jp_tower',
       'jp_lewis',
       'jp_sauni',
       'jp_jonck',
       'jp_tobin',
       'jp_eloff',
       'jp_flynn',
       'jp_dange',
       'jp_siili',
       'jp_smith',
       'jp_saxe',
       'jp_nel'],
 'a': ['jpats', 'jpay', 'jpa'],
 'b': ['jpb'],
 'c': ['jpca', 'jpcc', 'jpc'],
 'd': ['jpd'],
 'e': ['jpegmafia_discography',
       'jpeg_2000',
       'jpeg_xl',
       'jpeg_xt',
       'jpeg_xr',
       'jpeg_xs'],
 'f': ['jpf'],
 'h': ['jph_wacheski'],
 'i': ['jpimedia', 'jpip', 'jpi'],
 'j': ['jpj'],
 'l': ['jpl_sequence'],
 'm': ['jpm_discography', 'jpmorgan_chase', 'jpmorgan_embi', 'jpm_airport'],
 'o': ['jpods', 'jpos', 'jpod', 'jpo'],
 'p': ['jpp'],
 'r': ['jprofiler', 'jpred', 'jpr'],
 's': ['jpss-2', 'jps'],
 't': ['jpts', 'jpt'],
 'u': ['jpu_records'],
 'v': ['jpv'],
 'x': ['jpx_d-320']}
