
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jc = {'_': ['jc_schoonmaker',
       'jc_kritzinger',
       'jc_oberholzer',
       'jc_pretorius',
       "jc_d'abidjan",
       'jc_gonzalez',
       'jc_vickery',
       'jc_tiuseco',
       'jc_stylles',
       'jc_studios',
       'jc_carroll',
       'jc_jacinto',
       'jc_tretter',
       "jc's_girls",
       'jc_aragone',
       'jc_stewart',
       'jc_whitney',
       'jc_chasez',
       'jc_denton',
       'jc_santos',
       'jc_lattes',
       'jc_comics',
       'jc_caylen',
       'jc_lipon',
       'jc_intal',
       'jc_astle',
       'jc_midge',
       'jc_beall',
       'jc_squad',
       'jc_road',
       'jc_roos'],
 'a': ['jcamp-dx', 'jcall', 'jcap', 'jcag', 'jca'],
 'b': ['jcb_dieselmax',
       'jcb_vibromax',
       'jcb_fastrac',
       'jcb_academy',
       'jcb_classic',
       'jcb_prize',
       'jcb_hmee'],
 'c': ['jcci', 'jccc', 'jcc'],
 'd': ['jcdecaux', 'jcd'],
 'e': ['jcet', 'jce'],
 'f': ['jcf'],
 'g': ['jcgw_uav'],
 'h': ['jchempaint', 'jchs', 'jch'],
 'i': ['jci_limited', 'jci_nepal'],
 'j': ['jcj_vanderheyden'],
 'k': ['jck'],
 'l': ['jclc', 'jcl'],
 'm': ['jcm_farming'],
 'n': ['jcnetwork'],
 'o': ['jcom_radio'],
 'p': ['jcpenney_classic'],
 'q': ['jcq'],
 'r': ['jcreator', 'jcrom', 'jcrc', 'jcr'],
 's': ['jcsat-110',
       'jcsat-11',
       'jcsat-ra',
       'jcsat-4a',
       'jcsat-2b',
       'jcsat-2a',
       'jcsat-16',
       'jcsat-3a',
       'jcsat-5a',
       'jcsat-4b',
       'jcsat-1b',
       'jcsat-15',
       'jcsat-17',
       'jcsat-2',
       'jcsat-3',
       'jcsat-1',
       'jcsat-4',
       'jcsp',
       'jcsd',
       'jcss',
       'jcs'],
 't': ['jct_fc'],
 'u': ['jcuken', 'jcube', 'jcu'],
 'v': ['jcvi'],
 'w': ['jcw']}
