
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-25T11:58:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "70adac8c12d62fa8a56a3c86bb5ac7c84117a25e",
 "version": "1.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
