
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pf = {'a': ['pfaffenthal-kirchberg_railway_station',
       'pfadfinderinnenschaft_sankt_georg',
       'pfaffenthal_panoramic_elevator',
       'pfaffstatten_railway_station',
       'pfaffenschlag_bei_waidhofen',
       'pfafftown,_north_carolina',
       'pfaffikon_railway_station',
       'pfarrkirchen_im_muhlkreis',
       'pfafstetter_coding_system',
       'pfadt_race_engineering',
       "pfa_fans'_favourites",
       "pfaff's_beer_cellar",
       'pfano_na_vhuthihi',
       'pfarr_log_house',
       'pfa_merit_award'],
 'c': ['pfc_vidima-rakovski_sevlievo',
       'pfc_shakhtar_sverdlovsk',
       'pfc_neftochimic_burgas',
       'pfc_lokomotiv_tashkent',
       'pfc_ludogorets_razgrad',
       'pfc_lokomotiv_plovdiv',
       'pfc_pirin_blagoevgrad',
       'pfc_navbahor_namangan',
       'pfc_vihar_gorublyane',
       'pfc_dynamo_stavropol',
       'pfc_septemvri_sofia',
       'pfc_spartak_nalchik',
       'pfc_spartak_plovdiv',
       'pfc_victoria_london',
       'pfc_akademik_sofia',
       'pfc_brestnik_1948',
       'pfc_naftex_burgas',
       'pfc_litex_lovech',
       'pfc_slavia_sofia',
       'pfc_levski_sofia',
       'pfc_cska_moscow',
       'pfc_cska_sofia',
       'pfc_cesky_dub'],
 'e': ['pfeiffers_corner,_maryland',
       'pfeiffer_lake,_minnesota',
       "pfeffer's_reed_snake",
       'pfeifer_broz._music',
       'pfeifer_and_langen',
       "pfeiffer's_red_bat"],
 'f': ["pff_women's_league", "pff_women's_cup"],
 'i': ["pfister's_sixteen-square_identity",
       'pfizer-biontech_covid-19_vaccine',
       'pfinzing_von_henfenfeld',
       'pfister_and_vogel'],
 'k': ['pfk_metallurg_bekabad', 'pfk_svetkavitsa_1922'],
 'l': ['pflaum-mcwilliams_mound_group',
       'pflanzengarten_bad_schandau',
       'pflugerville_high_school',
       'pfleger_family_houses',
       'pfl_challenger_series',
       'pfl_rna_motif',
       'pfl_novi_sad'],
 'o': ['pforzheim_chamber_orchestra', 'pfohl_brothers_landfill'],
 'r': ['pfriem_family_brewers'],
 'u': ['pfutsero_government_college',
       'pfungen_railway_station',
       'pfu_dna_polymerase',
       'pfunz_roman_fort']}
