
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cc = {'_': ['cc_chemokine_receptors',
       'cc_pdf_converter',
       'cc_rides_again',
       'cc_and_lee',
       'cc_48_mine'],
 'a': ['cca_trna_nucleotidyltransferase',
       'cca_global_partners',
       'ccap_rhode_island'],
 'c': ['cccf_youth_championship',
       'ccc_ranch_headquarters',
       'ccc_development_team',
       'ccc_yenching_college',
       "cccan't_you_see",
       'ccc_pro_team'],
 'g': ['ccgs_wilfred_templeman',
       'ccgs_des_groseilliers',
       'ccgs_pierre_radisson',
       'ccgs_cape_palmerston',
       'ccgs_alexander_henry',
       'ccgs_ernest_lapointe',
       'ccgs_alfred_needler',
       'ccgs_cape_discovery',
       'ccgs_cape_commodore',
       'ccgs_vincent_massey',
       'ccgs_clarks_harbour',
       'ccgs_samuel_risley',
       'ccgs_jean_goodwill',
       'ccgs_cape_cockburn',
       'ccgs_cape_caution',
       'ccgs_cape_edensaw',
       'ccgs_henry_larsen',
       'ccgs_cape_dauphin',
       'ccgs_cape_lambton',
       'ccgs_c.p._edwards',
       'ccgs_simon_fraser',
       'ccgs_provo_wallis',
       'ccgs_j.e._bernier',
       'ccgs_thunder_cape',
       'ccgs_gordon_reid',
       'ccgs_cape_norman',
       'ccgs_cape_dundas',
       'ccgs_n.b._mclean',
       'ccgs_cape_hearne',
       'ccgs_a._leblanc',
       'ccgs_cap_breton',
       'ccgs_cape_naden',
       'ccgs_cape_sutil',
       'ccgs_ann_harvey',
       'ccgs_cape_roger',
       'ccgs_cape_storm',
       'ccgs_cape_spry',
       'ccgs_cape_hurd',
       'ccgs_terry_fox',
       'ccgs_cove_isle',
       'ccgs_cap_perce',
       'ccgs_earl_grey',
       'ccgs_sipu_muin',
       'ccgs_s._dudka',
       'ccgs_cape_ann',
       'ccgs_cape_fox',
       'ccgs_cg_117',
       'ccgs_cg_119',
       'ccgs_cg_118'],
 'h': ['ccha_best_goaltender'],
 'i': ['ccir_system_g',
       'ccir_system_i',
       'ccir_system_k',
       'ccir_system_e',
       'ccir_system_n',
       'ccir_system_m',
       'ccir_system_h',
       'ccir_system_a',
       'ccir_system_c',
       'ccir_system_l',
       'ccir_system_d',
       'ccir_system_b'],
 'j': ['ccjo_rene_cassin'],
 'm': ['ccm_kirumba_stadium', 'ccmmyk_color_model'],
 'n': ['ccny_point-shaving_scandal'],
 'r': ['ccr5_receptor_antagonist', 'ccrl_refinery_complex'],
 's': ['ccsds_mission_operations', 'ccsu_baseball_field', 'ccsds_mo_services'],
 't': ['cctv_nanhai_studio', 'cct_rail_system']}
