
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cd = {'_': ['cd_internacional_intxaurrondo',
       'cd/dvd_based_immunoassay',
       'cd_orientacion_maritima',
       'cd_oroquieta_villaverde',
       'cd_paracuellos_antamira',
       'cd_colegios_diocesanos',
       'cd-class_naval_drifter',
       'cd_internacional_dili',
       'cd1-restricted_t_cell',
       'cd_barcelona_tarrafal',
       'cd_scorpion_vermelho',
       'cd_palencia_balompie',
       'cd_huelva_baloncesto',
       'cd_atletico_baleares',
       'cd_union_criptanense',
       'cd28_family_receptor',
       'cd_aurrera_ondarroa',
       'cd_bejar_industrial',
       'cd_estrela_vermelha',
       'cd_marianao_poblet',
       'cd_vijaya_adhikari',
       'cd_colonia_ofigevi',
       'cd_motril_atletico',
       'cd_once_andalucia',
       'cd_polillas_ceuta',
       'cd_domingo_salvio',
       'cd_aguiluchos_usa',
       'cd_cultural_areas',
       'cd_giner_torrero',
       'cd_ribeira_brava',
       'cd_isla_cristina',
       'cd_unidad_malabo',
       'cd_pozo_estrecho',
       'cd_santa_eugenia',
       'cd_pena_azagresa',
       'cd_puerta_bonita',
       'cd_atletico_paso',
       'cd_mostoles_urjc',
       'cd_santa_ursula',
       'cd_san_fernando',
       'cd_price_fixing',
       'cd_os_foguetoes',
       'cd_santa_amalia',
       'cd_los_boliches',
       'cd_huetor_tajar',
       'cd_de_guadalupe',
       'cd_hielo_bipolo',
       'cd_onze_unidos',
       'cd_estepona_fs',
       'cd_iruna_voley',
       'cd_diter_zafra',
       'cd_shop_awards',
       'cd_huetor_vega',
       'cd_belchite_97',
       'cd_santa_ponsa',
       'cd_castellon_b',
       'cd_calahorra_b',
       'cd_santa_marta',
       'cd_ela_nguema',
       'cd_type_thing',
       'cd_basket_mar',
       'cd_numancia_b',
       'cd_mirandes_b',
       'cd_don_benito',
       'cd_san_martin',
       'cd_lagun_onak',
       'cd_san_isidro',
       'cd_tenerife_c',
       'cd_logrones_b',
       'cd_tenerife_b',
       'cd_plus_ultra',
       'cd_no_pintcha',
       "cd_cala_d'or",
       'cd_leganes_b',
       'cd_class_700',
       'cd_bala_azul',
       'cd_class_680',
       'cd_san_roque',
       'cd_class_380',
       'cd_tedeon_ef',
       'cd_burela_fs',
       'cd_de_nacala',
       'cd_la_granja',
       'cd_huracan_z',
       'cd_class_471',
       'cd_class_814',
       'cd_river_ega',
       'cd_as_pontes',
       'cd_class_749',
       'cd_ourense_b',
       'cd_class_242',
       'cd_class_340',
       'cd_up_manica',
       'cd_la_muela',
       'cd_el_alamo',
       'cd_santa_fe',
       'cd_la_union',
       'cd_el_ejido',
       'cd_toledo_b',
       'cd_one_stop',
       'cd_vigo_fs'],
 'a': ['cda_investment_technologies', 'cdadi_v/stol_uav'],
 'c': ['cdc48_n-terminal_domain',
       'cdc_display_code',
       'cdc_6000_series',
       'cdc_3000_series',
       'cdc_broken_hill',
       'cdc_160_series'],
 'f': ['cdf_tres_cantos', 'cdfc_la_calzada'],
 'h': ['cdh_investment_bank'],
 'k': ['cdkl5_deficiency_disorder'],
 'm': ['cdma_spectral_efficiency', 'cdma_certification_forum'],
 'r': ['cdr_canal_2'],
 't': ['cdt_da_anhanguera'],
 'u': ['cdu_donations_scandal'],
 'x': ['cdx_protein_family']}
