
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lg = {'_': ['lg15:_the_resistance',
       "lg_champion's_park",
       'lg_optimus_series',
       'lg_optimus_slider',
       'lg_optimus_black',
       'lg_optimus_chat',
       'lg_optimus_chic',
       'lg_watch_urbane',
       'lg_optimus_pad',
       'lg_film_awards',
       'lg_optimus_lte',
       'lg_optimus_one',
       'lg_watch_sport',
       'lg_optimus_zip',
       'lg_optimus_l70',
       'lg15:_the_last',
       'lg_watch_style',
       'lg_optimus_l5',
       'lg_optimus_l9',
       'lg_optimus_l7',
       'lg_gd880_mini',
       'lg_optimus_2x',
       'lg_optimus_l3',
       'lg_optimus_3d',
       'lg_optimus_l2',
       'lg_optimus_vu',
       'lg_env_touch',
       'lg_v60_thinq',
       'lg_vu_series',
       'lg_g3_stylus',
       'lg_prada_3.0',
       'lg_gd510_pop',
       'lg_optimus_g',
       'lg_v50_thinq',
       'lg_optimus_7',
       'lg_optimus_q',
       'lg_v40_thinq',
       'lg_v_series',
       'lg_g7_thinq',
       'lg_g8_thinq',
       'lg_g_series',
       'lg_prada_ii',
       'lg_k_series',
       'lg_folder_2',
       'lg_g2_mini',
       'lg_rumor_2',
       'lg_g_watch',
       'lg_g_flex',
       'lg_l_fino',
       'lg_vu_3'],
 'a': ['lga_architectural_partners'],
 'b': ['lgbt-affirming_religious_groups',
       'lgbt_rights_organization',
       'lgbt_youth_vulnerability',
       'lgbtiq+_health_australia',
       'lgbt+_liberal_democrats',
       'lgbt_rights_opposition',
       'lgbt_community_centre',
       'lgbt_student_movement',
       'lgbt_liaison_officer',
       'lgbt_mormon_suicides',
       'lgbt_centre_mongolia',
       'lgbti_health_summit',
       'lgbt_youth_scotland',
       'lgbt_student_center',
       'lgbt_sex_education',
       'lgbt_in_california',
       'lgbt_history_month',
       'lgbt_aging_project',
       'lgbtq_victory_fund',
       'lgbt+_rights_ghana',
       'lgbt_humanists_uk',
       'lgbt_in_guatemala',
       'lgbt_in_argentina',
       'lgbt_in_australia',
       'lgbt_teen_fiction',
       'lgbt_in_colombia',
       'lgbt_in_israel',
       'lgbt_in_poland',
       'lgbt_in_russia',
       'lgbt_in_mexico',
       'lgbt_in_canada',
       'lgbt_in_chile',
       'lgbt_in_islam'],
 'm': ['lgm-30_minuteman_chronology', 'lgm-25c_titan_ii'],
 'o': ['lgota,_silesian_voivodeship',
       'lgota,_chrzanow_county',
       'lgota,_wadowice_county',
       'lgov,_kursk_oblast'],
 'v': ["lgv_provence-alpes-cote_d'azur", 'lgv_interconnexion_est']}
