
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pk = {'_': ['pk_machine_gun'],
 'a': ['pkah_thgall_meas', 'pkai_dos_kuntuy'],
 'i': ['pki_dan_perwakilan'],
 'k': ['pkkm_college,_mananthavady'],
 'o': ['pko_bank_polski'],
 'p': ['pkp_classification_system',
       'pkp_class_tkt48',
       'pkp_class_okl27',
       'pkp_class_okz32',
       'pkp_class_ep07',
       'pkp_class_sm42',
       'pkp_class_sm40',
       'pkp_class_ep08',
       'pkp_class_et40',
       'pkp_class_sm01',
       'pkp_class_em10',
       'pkp_class_st40',
       'pkp_class_sm30',
       'pkp_class_en57',
       'pkp_class_et22',
       'pkp_class_et41',
       'pkp_class_su42',
       'pkp_class_lyd1',
       'pkp_class_st43',
       'pkp_class_ed72',
       'pkp_class_sp45',
       'pkp_class_sm31',
       'pkp_class_pm36',
       'pkp_class_st45',
       'pkp_class_eu06',
       'pkp_class_eu07',
       'pkp_class_su46',
       'pkp_class_pu29',
       'pkp_class_et21',
       'pkp_class_ew90',
       'pkp_class_en71',
       'pkp_class_sm15',
       'pkp_class_ol49',
       'pkp_class_sm25',
       'pkp_class_sp47',
       'pkp_class_sp30',
       'pkp_class_ew51',
       'pkp_class_sp42',
       'pkp_class_ok22',
       'pkp_class_lxd2',
       'pkp_class_eu20',
       'pkp_class_ep09',
       'pkp_class_pt31',
       'pkp_class_et42',
       'pkp_class_sm48',
       'pkp_class_ed73',
       'pkp_class_sp32',
       'pkp_class_ep02',
       'pkp_class_sm04',
       'pkp_class_ep03',
       'pkp_class_lyd2',
       'pkp_class_sm03',
       'pkp_class_ep05',
       'pkp_class_pt47',
       'pkp_class_su45',
       'pkp_class_sm02',
       'pkp_class_ty2',
       'pkp_class_ok1']}
