
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mh = {'_': ['mh_equipment'],
 'a': ['mhairi-bronte_duncan',
       'mhangura_airport',
       'mhadjou_youssouf',
       "mhand_n'ifrutant",
       'mhasin_fadlalla',
       'mhar_monastery',
       'mhadere_tigabe',
       'mhasala_taluka',
       'mhairi_gilmour',
       'mhairi_grieve',
       'mhamed_arezki',
       'mhairi_spence',
       'mhamed_yazid',
       'mhairi_black',
       'mhadei_class',
       'mhairi_mckay',
       'mhaswad_dam',
       'mhaw_palin',
       'mha_puja'],
 'c': ['mhc_restriction', 'mhc_multimer', 'mhc_dmitrov'],
 'd': ['mhdys', 'mhd'],
 'e': ['mher_khachatryan',
       'mher_mesropyan',
       'mher_grigoryan',
       'mher_mkrtchyan'],
 'g': ['mhg'],
 'h': ['mhh_franssen'],
 'i': ['mhicca_carter', 'mhire_spur'],
 'k': ['mhk_zelenograd', 'mhk_kezmarok', 'mhk_humenne'],
 'l': ['mhlobo_jadezweni',
       'mhl_championship',
       'mhlume_airfield',
       'mhlathuze_river',
       'mhleli_dlamini',
       'mhlengi_gwala'],
 'm': ['mhmr', 'mhms', 'mhm'],
 'n': ['mhnp', 'mhn'],
 'o': ['mhondoro-ngezi_district', 'mhow-indore_passenger', 'mhoira_leng'],
 'p': ['mhp_communications'],
 'q': ['mhq'],
 'r': ['mhra', 'mhr'],
 's': ['mhsk_tashkent', 'mhs_aviation', 'mhsk_stadium'],
 't': ['mhtml', 'mht'],
 'u': ['mhuire', 'mhudi', 'mhu'],
 'v': ['mhv_amplitudes', 'mhv_connector'],
 'w': ['mhw-rtg'],
 'x': ['mhx'],
 'y': ['mhysa'],
 'z': ['mhz_networks', 'mhz_legacy']}
