
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mp = {'_': ['mp_motorsport',
       'mp-445_varyag',
       'mp-444_bagira',
       'mp_promotions',
       'mp-446_viking',
       'mp_materials',
       'mp3_newswire',
       'mp-443_grach',
       'mp3_surround',
       'mp-448_skyph',
       'mp3_disques',
       'mp-412_rex',
       'mp3_party',
       'mp_hostel',
       'mp4_watch',
       'mp3_blog',
       'mp_lafer',
       'mp_3008',
       'mp_bhrt',
       'mp_bank',
       'mp3_sx',
       'mp_73',
       'mp_40',
       'mp_89',
       'mp_28',
       'mp_18',
       'mp_55',
       'mp_05',
       'mp_34',
       'mp_14',
       'mp_25',
       'mp_30',
       'mp_59',
       'mp_36',
       'mp_6',
       'mp_1'],
 'a': ['mpanjaka_collenettei',
       'mpanjaka_grandidieri',
       'mpanjaka_albovirida',
       'mpalitjanh_dialect',
       'mpakwithi_dialect',
       'mpandi_formation',
       'mpanjaka_betschi',
       'mpanjaka_elegans',
       'mpanjaka_montana',
       'mpanda_district',
       'mpangi_merikani',
       'mpanda,_gihanga',
       'mpanjaka_pastor',
       'mpanda,_mpanda',
       'mpade_language',
       'mpama_language',
       'mpanda_airport',
       'mpack,_senegal',
       'mpala_lulendo',
       'mpaka_airport',
       'mparo,_rukiga',
       'mpapa_gallery',
       'mpal,_senegal',
       'mparo,_hoima',
       'mpama_people',
       'mpassa_river',
       'mpageni_pass',
       'mpact_2'],
 'b': ['mpb_mine'],
 'c': ['mpc_corporation', 'mpca_ground', 'mpc_holding', 'mpc_75'],
 'd': ['mpd_ltd'],
 'e': ['mpeketoni_attacks',
       'mpeg_multichannel',
       'mpeg_surround',
       'mpemba_effect',
       'mpemba_kasi',
       'mpe_bambou',
       'mpeg-4_sls',
       'mpeke_town',
       'mpeg-4_sl',
       'mpeg_la'],
 'f': ['mpfs', 'mpfc', 'mpf'],
 'g': ['mpg/eso_telescope'],
 'h': ['mphatlalatsane_fc',
       'mphu_ramatlapeng',
       'mphile_tsabedze',
       'mpho_tshivhase',
       'mphokuhle_dube',
       'mphiwa_dlamini',
       'mpho_phalatse',
       'mpho_kgaswane',
       'mpho_moerane',
       'mpho_mbiyozo',
       'mpho_morobe',
       'mpho_mabogo',
       'mpho_balopi',
       'mpho_makola',
       'mpho_ndumo',
       'mpho_koaho',
       'mpho_links',
       'mpho_moloi',
       'mpho_matsi',
       'mpho_mbebe',
       'mpho_madi',
       'mph_group'],
 'i': ['mpigi-kabulasoke-maddu-sembabule_road',
       'mpingo,_mozambique',
       'mpiemo_language',
       'mpinda_language',
       'mpigi_district',
       'mpinga_kasenda',
       'mpilo_hospital',
       'mpika_district',
       'mpika_central',
       'mpilo_njoloza',
       'mpilo_gumede',
       'mpitsa_marai',
       'mpi_mpxpress',
       'mpi_language',
       'mpindi_clan',
       'mpi_mp8ac-3',
       'mpi_people',
       'mpi_mp20b',
       'mpi_mp33c',
       'mpi_mp21b',
       'mpi_hsp46',
       'mpi_mp20c',
       'mpi_mp14b'],
 'k': ['mpki', 'mpk'],
 'l': ['mpl_communications',
       'mpl_philippines',
       'mplab_devices',
       'mpls_vpn',
       'mpl_75',
       'mpl_85'],
 'm': ['mpm_motors', 'mpm_erelis', 'mpm_76'],
 'n': ['mpns', 'mpn'],
 'o': ['mporokoso_district',
       'mpoeleng_mpoeleng',
       'mpondomise_people',
       'mpower_financing',
       'mpongwe_district',
       'mporokoso_group',
       'mpouya_district',
       'mpower_pictures',
       'mpoto_language',
       'mpowele_swathe',
       'mpongwe_people',
       'mpohor,_ghana',
       'mpondo_people',
       'mpoto_people',
       'mpoko_river',
       'mpoto_mpoto',
       'mpok_nori'],
 'p': ['mpp_jedinstvo'],
 'q': ['mpqc', 'mpq'],
 'r': ['mpr/dpr/dpd_building',
       'mpraeso_amanfrom',
       'mprest_systems',
       'mpra_language',
       'mpr_dam'],
 's': ['mps_finance', 'mps_records'],
 't': ['mpt-1327', 'mpt8080', 'mptc', 'mptp', 'mpta', 'mpt'],
 'u': ['mpumalanga,_kwazulu-natal',
       'mpumalanga_division',
       'mpungu_constituency',
       'mpulungu_district',
       'mpumpong_language',
       'mpumelelo_stadium',
       'mpule_kwelagobe',
       'mpuono_language',
       'mpumelelo_xulu',
       'mpumi_nyandeni',
       'mpur_language',
       'mpu_prapanca',
       'mpumi_madisa',
       'mpundi_decca',
       'mpu_gandring',
       'mpu_tantular',
       'mpumi_mpofu',
       'mpu_panuluh',
       'mpu_sindok',
       'mpu_sedah'],
 'v': ['mpv17', 'mpva', 'mpv'],
 'w': ['mpwapwa_district', 'mpwapwa_mjini'],
 'x': ['mpx_filter'],
 'y': ['mpys'],
 'z': ['mpzl1']}
