
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hp = {'_': ['hp_multi-programming_executive',
       'hp_integrated_lights-out',
       'hp_kittyhawk_microdrive',
       'hp_technology_services',
       'hp_networking_training',
       'hp_networking_products',
       'hp_mediasmart_connect',
       'hp_topshot_technology',
       'hp_time-shared_basic',
       'hp_hard_partitioning',
       'hp_converged_systems',
       'hp_essential_laptops',
       'hp_mediasmart_server',
       'hp_business_desktops',
       'hp_service_activator',
       'hp_release_control',
       'hp_photosmart_r607',
       'hp_indigo_division',
       'hp_photosmart_m407',
       'hp_virtual_connect',
       'hp_calcpad_series',
       'hp_data_protector',
       'hp_color_recovery',
       'hp_laserjet_1020',
       'hp_compaq_tc4200',
       'hp_precision_bus',
       'hp_compaq_tc1100',
       'hp_postcode_area',
       'hp_blackbird_002',
       'hp_compaq_tc4400',
       'hp_pavilion_dv2z',
       'hp1_holin_family',
       'hp_pavilion_dv7',
       'hp_39/40_series',
       'hp_pavilion_dv5',
       'hp_pavilion_dv4',
       'hp_49/50_series',
       'hp_integral_pc',
       'hp_media_vault',
       'hp_9800_series',
       'hp_laserjet_5',
       'hp_van_schoor',
       'hp_laserjet_4',
       'hp_series_80',
       'hp_48_series',
       'hp_slate_500',
       'hp_30_series',
       'hp_stream_7',
       'hp_elite_x3',
       'hp_slate_21',
       'hp_slate_7',
       'hp_pre_3'],
 'a': ['hpa_culture_collections'],
 'c': ['hpc_challenge_benchmark'],
 'e': ['hper_biomechanics_laboratory', 'hpe_integrity_servers'],
 'i': ['hpi_baja_5b/5t', 'hpi_pro_4'],
 'o': ['hponkanrazi_wildlife_sanctuary'],
 'v': ['hpv-positive_oropharyngeal_cancer']}
