
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hs = {'_': ['hs_koningin_regentes',
       'hs2_rolling_stock',
       'hs_postcode_area',
       'hs_timber_group',
       'hs_produkt_vhs',
       'hs_and_ts'],
 'a': ['hsanda_gol_formation', 'hsaung_wutyee_may'],
 'b': ['hsbc_continental_europe',
       "hsbc_women's_champions",
       'hsbc_guyerzeller_bank',
       'hsbc_canada_building',
       'hsbc_bank_australia',
       'hsbc_bank_argentina',
       'hsbc_bank_malaysia',
       'hsbc_bank_bermuda',
       'hsbc_bank_georgia',
       'hsbc_saudi_arabia',
       'hsbc_private_bank',
       'hsbc_bank_panama',
       'hsbc_bank_canada',
       'hsbc_bank_polska',
       'hsbc_bank_malta',
       'hsbc_bank_india',
       'hsbc_bank_egypt',
       'hsbc_brazil_cup',
       'hsbc_sri_lanka',
       'hsbc_bank_usa'],
 'c': ['hsc_distinction_courses',
       'hsc_benchijigua_express',
       'hsc_betancuria_express',
       'hsc_hellenic_highspeed',
       'hsc_worldchampion_jet',
       'hsc_condor_liberation',
       'hsc_atlantic_express',
       'hsc_fastcat_shanklin',
       'hsc_santorini_palace',
       'hsc_speedrunner_iii',
       'hsc_bocayna_express',
       'hsc_aeolos_kenteris',
       'hsc_condor_voyager',
       'hsc_cecilia_payne',
       'hsc_hss_discovery',
       'hsc_natchan_world',
       'hsc_caldera_vista',
       'hsc_almudaina_dos',
       'hsc_condor_rapide',
       'hsc_stena_voyager',
       'hsc_fastcat_ryde',
       'hsc_gotlandia_ii',
       'hsc_dublin_swift',
       'hsc_lake_express',
       'hsc_2000_coburg',
       'hsc_highspeed_4',
       'hsc_t&t_spirit',
       'hsc_tarifa_jet',
       'hsc_naxos_jet',
       'hsc_speed_jet',
       'hsc_express_1',
       'hsc_express_3',
       'hsc_condor_10',
       'hsc_incat_046',
       'hsc_fjord_cat',
       'hsc_express_4',
       'hsc_express_2',
       'hsc_mega_jet',
       'hsc_max_mols',
       'hsc_jaume_ii'],
 'f': ['hsf_cruise_bonaria'],
 'g': ['hsg_bad_wildungen'],
 'h': ['hsh_class_t211.0', 'hsh_class_72', 'hsh_class_31'],
 'i': ['hsinchu_international_school',
       'hsinchu_county_constituency',
       'hsinchu_chenghuang_temple',
       'hsinchu_city_constituency',
       'hsinchu_county_government',
       'hsinchu_metropolitan_area',
       'hsinchu_city_government',
       'hsinchu_industrial_park',
       'hsinchu_american_school',
       'hsinchu_railway_station',
       'hsinchu_county_stadium',
       'hsinchu_county_council',
       'hsingneng_power_plant',
       'hsiahsing_power_plant',
       'hsingyuan_power_plant',
       'hsinchu_jko_lioneers',
       'hsieh-ho_power_plant',
       'hsinchu_science_park',
       'hsinchu_city_council',
       'hsinchu_hsr_station',
       'hsintao_power_plant',
       'hsinchu_fish_harbor',
       'hsing_wu_university',
       'hsi_hseng_township',
       'hsinta_power_plant',
       'hsi-chun_mike_hua',
       'hsin_ji_building',
       'hsien_chung_wang',
       'hsi_tseng_tsiang',
       'hsiung_feng_iie',
       'hsing_yin_shean',
       'hsiung_feng_iii',
       'hsiung_feng_ii',
       'hsin_tung_yang',
       'hsi_lai_temple',
       'hsiung_feng_i'],
 'k': ['hsk_gradanski_zagreb',
       'hsk_zrinjski_mostar',
       'hsk_hajduk_zemun',
       'hsk_dunav_zemun'],
 'l': ['hsl_and_hsv'],
 'm': ['hsm-78_blue_hawks'],
 'o': ['hso_khan_pha'],
 'p': ['hsp90_cis-regulatory_element', 'hspq_protein_domain'],
 'u': ['hsuan_chuang_university',
       'hsu_chung_pi-hsia',
       'hsueh_shou_sheng',
       'hsu_yun_temple',
       'hsu_yun_tsiao',
       'hsu_eaint_san',
       'hsu_yung_chin',
       'hsu_pan_htwar',
       'hsu_and_chan',
       'hsu_ta_tung',
       'hsu_li_yang',
       'hsu_fu_chi'],
 'v': ['hsv_de_zuidvogels', 'hsv_dealer_team'],
 'w': ['hswms_drottning_victoria',
       'hswms_john_ericsson',
       'hswms_clas_fleming',
       'hswms_claes_uggla',
       'hswms_tre_kronor',
       'hswms_klas_uggla',
       'hswms_gota_lejon',
       'hswms_oscar_ii',
       'hswms_gustaf_v']}
