
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pg = {'_': ['pg_1159-035',
       'pg_1047+003',
       'pg_jaguars',
       'pg_tips',
       'pg._99',
       'pg_era'],
 'a': ['pga_championship', 'pga_express', 'pga_tour', 'pga_cup'],
 'b': ['pgb'],
 'c': ['pgc_13809',
       'pgc_10922',
       'pgc_54493',
       'pgc_44691',
       'pgc_39058',
       'pgc_6240',
       'pgc_1'],
 'd': ['pgds', 'pgde', 'pgd'],
 'e': ['pge_heliport'],
 'f': ['pgf/tikz', 'pgf'],
 'g': ['pggmb_building', 'pgg_wrightson'],
 'h': ['pghbridges.com', 'pghs', 'pgh'],
 'i': ['pgi_management'],
 'k': ['pgk1p2', 'pgk1', 'pgk'],
 'l': ['pgl_travel'],
 'm': ['pgm-39-class_gunboat',
       'pgm3_deficiency',
       'pgm-11_redstone',
       'pgm-19_jupiter',
       'pgm_precision',
       'pgm_college',
       'pgm-17_thor',
       'pgm_338',
       'pgm_500'],
 'n': ['pgnig', 'pgn'],
 'o': ['pgo_scooters', 'pgo_waves'],
 'p': ['pgp_corporation'],
 'r': ['pgreen', 'pgrmc2', 'pgrmc1', 'pgrep', 'pgrmc', 'pgrc', 'pgr'],
 's': ['pgs_entertainment', 'pgs_kissamikos'],
 't': ['pgt'],
 'u': ['pgu_tiraspol'],
 'v': ['pgv'],
 'w': ['pgw'],
 'y': ['pgy'],
 'z': ['pgz-09', 'pgz-88']}
