
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pb = {'_': ['pb&j_television',
       'pb&j_otter',
       'pb_fraser',
       'pb_djarum',
       'pb_smooth',
       'pb_devco',
       'pb_max',
       'pb_250'],
 'a': ['pba_galleries',
       'pba_partylist',
       'pbad_promoter',
       'pba_bowling',
       'pbapp_f.c.',
       'pba_rush',
       'pba_tour',
       'pba_3x3'],
 'b': ['pbb'],
 'c': ['pbc_academic', 'pbcom_tower'],
 'd': ['pbdc1', 'pbds', 'pbd'],
 'e': ['pbe'],
 'f': ['pbf_energy'],
 'g': ['pbg_sa'],
 'h': ['pbhs'],
 'i': ['pbist', 'pbil', 'pbi'],
 'j': ['pbj'],
 'k': ['pbk_architects', 'pbk-500u_drel'],
 'l': ['pbl_productions'],
 'm': ['pbm'],
 'n': ['pbnation', 'pbn'],
 'o': ['pbow', 'pbo'],
 'p': ['pbpa', 'pbp'],
 'r': ['pbr_theorem'],
 's': ['pbs_distribution',
       'pbs-1_silencer',
       'pbs_wisconsin',
       'pbs_newshour',
       'pbs_america',
       'pbs_106.7fm',
       'pbs_kids',
       'pbs_you'],
 't': ['pbt2', 'pbt'],
 'u': ['pbunavirus', 'pbu'],
 'w': ['pbworks', 'pbw'],
 'x': ['pbx_1'],
 'z': ['pbz']}
