
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_b_ = {'_': ['b4.da.$$',
       'b4-mount',
       'b98.3',
       'b-300',
       'b98.5',
       'b-2lm',
       'b-611',
       'b-67',
       'b105',
       'b612',
       'b744',
       'b13r',
       'b101',
       'b144',
       'b120',
       'b430',
       'b300',
       'b4-4',
       'b350',
       'b00t',
       'b110',
       'b420',
       'b100',
       'b717',
       'b205',
       'b330',
       'b39',
       'b86',
       'b91',
       'b96',
       'b85',
       'b65',
       'b54',
       'b36',
       'b95',
       'b43',
       'b58',
       'b80',
       'b81',
       'b23',
       'b89',
       'b62',
       'b21',
       'b94',
       'b83',
       'b17',
       'b63',
       'b93',
       'b18',
       'b66',
       'b70',
       'b78',
       'b33',
       'b53',
       'b37',
       'b51',
       'b45',
       'b42',
       'b16',
       'b49',
       'b71',
       'b77',
       'b31',
       'b98',
       'b29',
       'b97',
       'b84',
       'b90',
       'b75',
       'b72',
       'b79',
       'b27',
       'b26',
       'b28',
       'b22',
       'b13',
       'b82',
       'b15',
       'b50',
       'b57',
       'b48',
       'b11',
       'b68',
       'b61',
       'b88',
       'b67',
       'b19',
       'b59',
       'b92',
       'b30',
       'b56',
       'b44',
       'b47',
       'b46',
       'b99',
       'b69',
       'b34',
       'b55',
       'b14',
       'b60',
       'b10',
       'b24',
       'b87',
       'b20',
       'b40',
       'b73',
       'b25',
       'b32',
       'b01',
       'b74',
       'b41',
       'b64',
       'b35',
       'b76',
       'b38'],
 'a': ['b.a.t.m.a.n.',
       'b.aralikatti',
       'b-amanitin',
       'b-alanine',
       'b.a.l.l.',
       'b.a.c.k.',
       'b.a.p.s.',
       'b.a.a.s.',
       'b.a.b.e.',
       'b-a-b-y',
       'b-and-b',
       'b1a4',
       'b1a',
       'b2a'],
 'b': ['b-butyrolactone',
       'b-bungarotoxin',
       'b2blogger.com',
       'b.b.queens',
       'b-bender',
       'b-brave',
       'b4blaze',
       "b-bop's",
       'b-bomb',
       'b.b.e.',
       'b-boys',
       'b2b',
       'b&b'],
 'c': ['b-cryptoxanthin',
       'b-coloring',
       'b-carotene',
       'b@cir@van',
       'b-complex',
       'b-cell',
       'b-cas',
       'b&ce',
       'b4c'],
 'd': ['b@dirqala',
       'b@disqala',
       'b-dienst',
       'b@d@sxan',
       'b-daman',
       'b@d@lan',
       'b@d@lli',
       'b.delta',
       'b@dirli',
       'b.d.d.',
       "b'day",
       'b2d'],
 'e': ['b/e/a/t/b/o/x', 'b2evolution', 'b-edge'],
 'f': ['b-factory', 'b-flower', "b'flow", 'b-fast', 'b-flat'],
 'g': ['b-gendarmerie',
       'b.g-osborne',
       'b4galnt2',
       'b4galnt1',
       'b3galnt2',
       'b3galnt1',
       'b3galtl',
       'b4galt1',
       'b4galt5',
       'b3galt4',
       'b4galt2',
       'b.grimm',
       'b4galt7',
       'b3galt5',
       'b4galt4',
       'b4galt3',
       'b3gat1',
       'b3gnt2',
       'b3gat2',
       'b3gnt7',
       'b2gold',
       'b3gat3',
       'b3gnt1',
       'b1g1',
       'b2g',
       'b&g'],
 'h': ['b-homoleucine',
       'b@hramt@p@',
       'b@hrambag',
       'b@hliyan',
       'b@hm@nli',
       'b@hm@tli',
       'b-heap'],
 'i': ['b.i.t.c.h.'],
 'k': ['b.kanabur', 'b2krazy', 'b-kool', 'b@kl@', 'b2k'],
 'l': ['b.l.e.s.s.e.d',
       'b.l.e.v.e.',
       'b-leucine',
       'b.league',
       'b1llionz',
       'b.l.o.w.',
       'b-legit',
       'b-lgnd2',
       'b-live',
       'b&l'],
 'm': ['b-methylphenethylamine',
       'b-methyl-2c-b',
       'b-mobile',
       'b-method',
       'b-mode',
       'b-mac',
       'b2mml',
       'b2mr',
       'b&m',
       'b2m'],
 'n': ['b@novs@l@r', 'b@n@niyar', 'b-netz', 'b.net', 'b4n'],
 'o': ['b.o.l.t', 'b.o.b', 'b.o.y', 'b&o'],
 'p': ['b-project', 'b-projekt', 'b-prolog', 'b&p'],
 'q': ['b&q'],
 'r': ['b.r.a.k.e.s.',
       'b-ration',
       'b@rgusad',
       'b-room',
       'b-reel',
       'b-real',
       'b@rcan',
       'b-roll',
       'b@rgov',
       'b-red',
       'b&r'],
 's': ['b.shigigatti',
       'b@sirb@yli',
       'b-stabmine',
       'b-segment',
       'b-staging',
       'b-say-tah',
       'b.s.o.d.',
       'b-spline',
       'b@sirl@r',
       'b-stage',
       'b@sirli',
       'b-scada',
       'b-sides',
       "b'sheva",
       'b.slade',
       'b&s'],
 't': ['b-tocotrienol',
       'b-tocopherol',
       'b-television',
       'b-tagging',
       'b-theorem',
       'b2takes!',
       "b'tselem",
       'b.traits',
       'b-tight',
       'b-tribe',
       'b-thong',
       'b-tree',
       'b-town',
       "b'twin",
       'b8ta',
       'b3ta'],
 'u': ['b-unit', 'b4u', 'b-u'],
 'v': ['b.v.s.m.p.', 'b-value'],
 'w': ['b*witched', 'b-wings', 'b&w', 'b2w'],
 'x': ['b@xtiyarli', 'b4x'],
 'y': ['b@y@hm@dyurd',
       'b@ybabalar',
       'b@yimsarov',
       'b@yd@mirli',
       'b@yqislaq',
       'b@yazatli',
       'b@ydovul',
       'b@ydili',
       'b@yimli',
       'b@ylik',
       'b@yl@r',
       'b@yli',
       'b@yi'],
 'z': ['b@zirxana', "b'z"]}
