
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tt = {'_': ['tt-400tp_gunboat',
       'tt_technologies',
       'tt-line_company',
       'tt_electronics',
       'tt_grandstand',
       'tt-line_gmbh',
       'tt_language',
       'tt_aquilae',
       'tt_pistol',
       'tt_games',
       'tt_races',
       'tt_scale',
       'tt_corvi',
       'tt_cygni',
       'tt_zero',
       'tt_line'],
 'a': ['tta_airlink', 'tta_uav'],
 'b': ['ttbomk', 'ttbk1', 'ttbk2', 'ttbb', 'ttbp', 'ttb'],
 'c': ['ttc_tychy'],
 'd': ['ttdi_jaya'],
 'e': ['tteok_museum'],
 'f': ['ttf2', 'ttfa', 'ttfc', 'ttfn', 'ttff', 'ttfd', 'ttf'],
 'g': ['ttg_studios'],
 'h': ['tthebatthie_196', 'tth_holstebro'],
 'i': ['tti_telecom', 'tti,_inc.'],
 'k': ['ttk_services', 'ttk_prestige', 'ttk_group'],
 'l': ['ttll3', 'ttll1', 'ttl'],
 'm': ['ttm_f.c.'],
 'n': ['ttnet', 'ttng', 'ttn'],
 'o': ['ttongppang', 'tto'],
 'p': ['ttpost', 'ttp/a', 'ttpal', 'ttp'],
 'r': ['ttrruuces', 'ttrent', 'ttrap', 'ttr'],
 's': ['tts_brighton', 'tts_trencin', 'tts_moruga', 'tts_22'],
 't': ['ttt_riga'],
 'u': ['ttujur,_gegharkunik',
       'ttujur,_aragatsotn',
       'ttukseom_station',
       'ttu_k-12'],
 'v': ['ttv_finance', 'ttv_family', 'ttv_world'],
 'w': ['ttw'],
 'x': ['ttx_company'],
 'y': ['ttyemulator', 'ttylxox', 'ttyrec', 'ttyh3', 'ttys', 'ttyl', 'tty']}
