
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rb = {'_': ['rb12_highway',
       'rb_kolubara',
       'rb_leipzig',
       'rb_link',
       'rb_199',
       'rb_05',
       'rb_04'],
 'a': ['rba_arabia', 'rbac_f.c.'],
 'b': ['rbb_brandenburg', 'rbb_fernsehen', 'rbb_berlin'],
 'c': ['rbc_roosendaal',
       'rbc_pepinster',
       'rbc_heritage',
       'rbc_exchange',
       'rbc_stadion',
       'rbc_records',
       'rbc_centre',
       'rbc_plaza',
       'rbc_bank',
       'rbc_ext8'],
 'd': ['rbd_discography'],
 'e': ['rbe2'],
 'f': ['rbfox1', 'rbf'],
 'g': ['rbg_resources', 'rbgt_62a'],
 'h': ['rbhs', 'rbh'],
 'i': ['rbi_thiruvananthapuram'],
 'k': ['rbk_group', 'rbk_daily', 'rbk_tv'],
 'l': ['rbl_cells', 'rbl_posse', 'rbl_bank'],
 'm': ['rbmg_records'],
 'n': ['rbn'],
 'o': ['rbo'],
 'p': ['rbpms', 'rbpf', 'rbp2', 'rbpj', 'rbp1', 'rbp7', 'rbp3', 'rbp'],
 'q': ['rbq'],
 'r': ['rbr_enterprises'],
 's': ['rbs_international',
       'rbs_express',
       'rbs_tv',
       'rbs_23',
       'rbs_15',
       'rbs_70'],
 't': ['rbti', 'rbt'],
 'u': ['rbu-1200', 'rbu-6000', 'rbu-1000', 'rbu'],
 'v': ['rbv'],
 'w': ['rbw'],
 'x': ['rbx1', 'rbx'],
 'y': ['rbyc', 'rby']}
