
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rz = {'_': ['rz_pyxidis', 'rz_piscium', 'rz_normae', 'rz_gruis'],
 'a': ['rzadka_wola-parcele',
       'rzasnik_wloscianski',
       'rzasnik_szlachecki',
       'rza_discography',
       'rzanovo,_struga',
       'rzanica,_serbia',
       'rza_tahmasib',
       'rzadka_wola'],
 'd': ['rzd_arena'],
 'e': ['rzeszow-khmelnytskyi_powerline',
       'rzeczyca_ziemianska-kolonia',
       'rzeszow-jasionka_airport',
       'rzepiennik_marciszewski',
       'rzepiennik_strzyzewski',
       'rzeszotary-stara_wies',
       'rzeszow_voivodeship',
       'rzeczyca_ziemianska',
       'rzepiennik_biskupi',
       'rzechta_druzbinska',
       'rzeczyca_okragla',
       'rzepiennik_suchy',
       'rzeszotary_gorne',
       'rzechowo_wielkie',
       'rzewuski_family',
       'rzeczyca_ksieza',
       'rzepin_pierwszy',
       'rzeczyca_wielka',
       'rzeszow_castle',
       'rzeszow_county',
       'rzeczyca_dluga',
       'rzeczyca_sucha',
       'rzeczyca_mokra',
       'rzeznik_drzew',
       'rzeki_wielkie',
       'rzeczyca_mala',
       'rzepin_drugi',
       'rzeki_male'],
 'g': ['rzgow_pierwszy', 'rzgow_drugi'],
 'h': ['rzhevskoye_microdistrict',
       'rzhaksinsky_district',
       'rzhevsky_district',
       'rzhanaya_polyana',
       'rzhevka_airport',
       'rzhevsky_family',
       'rzhevsky_uyezd'],
 'i': ['rzisce,_litija'],
 'k': ['rzk_zagorje'],
 'm': ['rzm'],
 'o': ['rzodkiewnica', 'rzochow', 'rzozow'],
 'u': ['rzucewo_culture', 'rzucewo_castle', 'rzuski_las'],
 'y': ['rzymsko_bg']}
