
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zl = {'a': ['zlataritsa,_blagoevgrad_province',
       'zlatoust_machine-building_plant',
       'zlatolist,_blagoevgrad_province',
       'zlatarski_international_school',
       'zlatolist,_kardzhali_province',
       'zlatopole,_haskovo_province',
       'zlatonosovic_noble_family',
       'zlatia,_montana_province',
       'zlatia,_dobrich_province',
       'zlatan_stipisic_gibonni',
       'zlatno,_poltar_district',
       'zlate_moravce_district',
       'zlato,_srebro,_dukati',
       'zlatne_zice_slavonije',
       'zlatece_pri_sentjurju',
       'zlatni_pyasatsi_cove',
       'zlatopol,_altai_krai',
       'zlatna_na_ostrove',
       'zlata_of_maglen'],
 'i': ['zliten_truck_bombing',
       'zlin_film_festival',
       'zlin_z-37_cmelak',
       'zlin_z-25_sohaj',
       'zlin_z_526',
       'zlin_z_43',
       'zlin_z_42'],
 'o': ['zlotniczki,_kuyavian-pomeranian_voivodeship',
       'zlotopole,_kuyavian-pomeranian_voivodeship',
       'zlotniki,_kuyavian-pomeranian_voivodeship',
       'zlotoria,_kuyavian-pomeranian_voivodeship',
       'zlotnica,_warmian-masurian_voivodeship',
       'zlotowo,_warmian-masurian_voivodeship',
       'zlotniki,_swietokrzyskie_voivodeship',
       'zlotniki,_podkarpackie_voivodeship',
       'zlobek,_podkarpackie_voivodeship',
       'zlotopole,_masovian_voivodeship',
       'zlotniki,_podlaskie_voivodeship',
       'zlotowo,_masovian_voivodeship',
       'zlobin,_podlaskie_voivodeship',
       'zlota,_masovian_voivodeship',
       'zlotowo,_koscierzyna_county',
       'zlotniki,_opole_voivodeship',
       'zlotniki,_poddebice_county',
       'zlotniki,_pajeczno_county',
       'zlotoria,_gmina_choroszcz',
       'zlota,_sandomierz_county',
       'zlotowo,_chojnice_county',
       'zlotniki,_kalisz_county',
       'zlota,_lodz_voivodeship',
       'zlotowo,_malbork_county',
       'zlotniki,_poznan_county',
       'zlotniki,_kutno_county',
       'zlotki,_wegrow_county',
       'zlota,_pinczow_county',
       'zlotowo,_znin_county']}
