
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ao = {'_': ["ao-chan_can't_study!",
       'ao-35_assault_rifle',
       'ao-63_assault_rifle',
       'ao-38_assault_rifle',
       'ao_luek_district',
       'ao_sellana_f.c.',
       'ao_chania_f.c.',
       'ao_kardia_f.c.',
       'ao_poros_f.c.',
       'ao_meu_brasil',
       'ao_giao_linh',
       'ao_haru_ride',
       'ao_tennis_2',
       'ao_man_long',
       'ao_chi_hong',
       'ao_no_fuin',
       'ao_tu_than',
       'ao_ba_ba'],
 'b': ['aoba-japan_international_school',
       'aoba-dori_ichibancho_station',
       'aobagakuen_junior_college'],
 'c': ['aoc_beacon_awards'],
 'd': ['aodh_o_flaithbheartaigh',
       'aodh_ua_goirmghiallaigh',
       'aodh_mac_cathmhaoil',
       'aodan_mac_gearailt',
       'aodh_mac_aidmhire',
       'aodhan_o_riordain',
       'aodan_mac_suibhne',
       'aodh_mac_donaill',
       'aodh_o_heothaigh',
       'aodh_mac_suibhne',
       'aodh_ua_beachain',
       'aodan_mac_poilin',
       'aodh_ua_heidhin',
       'aodh_de_blacam',
       'aodh_ruadh_clg',
       'aodh_o_maille',
       'aodh_o_broin'],
 'g': ['aogan_o_rathaille', 'aogan_o_fearghail'],
 'h': ['aoharu_x_machinegun'],
 'i': ['aoibhinn_ni_shuilleabhain',
       'aoimori_railway_company',
       'aoimori_railway_line',
       'aoife_ni_fhearraigh',
       'aoife_nessa_frances',
       'aoimori_703_series',
       'aoife_ni_thuairisg',
       'aoi_mac_ollamain',
       'aoife_de_burca',
       'aoi_aso_shrine',
       'aoi_no_ue'],
 'j': ['aoji-ri_chemical_complex'],
 'l': ['aol_dejando_huellas'],
 'm': ['aomori_broadcasting_corporation',
       'aomori_prefectural_museum',
       'aomori_public_university',
       'aomori_metropolitan_area',
       'aomori_at-large_district',
       'aomori_fm_broadcasting',
       'aomori_nebuta_matsuri',
       'aomori_junior_college',
       'aomori_2nd_district',
       'aomori_3rd_district',
       'aomori_1st_district',
       'aomori_curling_club',
       'aom_french_airlines',
       'aomori_belt_highway',
       'aomori_high_school',
       'aomori_west_bypass',
       'aomori_bay_bridge',
       'aomori_city_bus'],
 'n': ['aonyx_capensis_capensis',
       'aon_hotvolleys_vienna',
       'aonla_railway_station',
       'aone_van_engelenhoven',
       'aonghus_mac_somhairle',
       'aonla,_uttar_pradesh',
       'aon_open_challenger',
       'aonghus_o_dalaigh',
       'aonach_air_chrith',
       'aonghus_mac_umhor',
       'aongus_o_giollain',
       'aon_rud_persanta'],
 'r': ['aortocaval_compression_syndrome',
       'aortopulmonary_septal_defect',
       'aortoiliac_occlusive_disease',
       'aortic_valve_replacement',
       'aorangi_railway_station',
       'aore_adventist_academy',
       'aorangi_forest_park',
       'aortic_valve_repair',
       'aortic_lymph_nodes'],
 's': ['aosta_valley_university',
       'aosta_railway_station',
       'aoshima_bunka_kyozai',
       'aosta_valley_airport',
       'aosta_valley_nation',
       'aos_and_soa'],
 't': ['aotearoa_television_network',
       'aotine_betaherpesvirus_1',
       'aotea_conservation_park',
       'aotearoa:_stand_strong',
       'aotearoa_roller_derby',
       'aotearoa_music_awards',
       'aotea_railway_station',
       'aotea,_new_zealand'],
 'u': ['aouk_national_park', 'aouinet_bel_egra'],
 'w': ['aowanda_suspension_bridge'],
 'y': ['aoyama_gakuin_university',
       'aoyagi_metals_company',
       'aoyama_kumano_shrine'],
 'z': ['aozihdi_metro_station', 'aozora_no_kakera', 'aozora_no_namida']}
