
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_aj = {'_': ['aj_tracey_discography',
       "aj's_infinite_summer",
       'aj_swanepoel_stadium',
       'aj_capital_partners',
       'aj_bell_stadium',
       "aj_yaxjal_b'aak",
       "aj's_fine_foods",
       'aj_enayet_nur',
       'aj,_aj,_aj',
       'aj_le_roux'],
 'a': ['ajaymeru_rural_municipality',
       'ajaikapada_bhairava_temple',
       'ajamaru_lakes_rainbowfish',
       'ajayi_crowther_university',
       'ajax_sportsman_combinatie',
       'ajani_anibijuwon_omisore',
       'ajana,_western_australia',
       'ajax_business_associates',
       'ajay-class_patrol_vessel',
       'ajameti_managed_reserve',
       'ajahn_thoon_khippapanno',
       'ajax_wanderers_r.u.f.c.',
       'ajay_devgn_filmography',
       'ajanti_railway_station',
       'ajax_orlando_prospects',
       'ajaysar_village,_ajmer',
       'ajami,_west_azerbaijan',
       'ajai_wildlife_reserve',
       'ajahn_chanda_thawaro',
       'ajay_prakash_sawhney',
       'ajax,_west_virginia',
       'ajaokuta_steel_mill',
       'ajay_kumar_bulganin',
       'ajahn_sao_kantasilo',
       'ajay_kumar_tripathi',
       'ajay_singh_chautala',
       'ajam_rural_district',
       'ajay_bhushan_pandey',
       'ajay_singh_jasrotia',
       'ajaip_singh_matharu',
       'ajax,_south_dakota',
       'ajaib_singh_bhatti',
       'ajax_football_club',
       'ajax_futebol_clube',
       'ajay_singh_kushwah',
       'ajaan_suwat_suvaco',
       'ajan_qarah_khvajeh',
       'ajax_youth_academy',
       'ajay_mitra_shastri',
       'ajax_america_women',
       'ajab_singh_kushwah',
       'ajay_kumar_poddar',
       'ajan_faquir_saheb',
       'ajay_pratap_singh',
       'ajay_kumar_mandal',
       'ajang_ajang_group',
       'ajay_kumar_parida',
       'ajay_kumar_bhalla',
       'ajaya_pratap_shah',
       'ajae_kumar_sharma',
       'ajay_devgn_ffilms',
       'ajay_kumar_mittal',
       'ajab_gazabb_love',
       'ajay_kumar_reddy',
       'ajay_singh_yadav',
       'ajab_khan_afridi',
       'ajay_arjun_singh',
       'ajab_shir_county',
       'ajay_kumar_saroj',
       'ajay_mishra_teni',
       'ajay_narayan_jha',
       'ajax_high_school',
       'ajay_kumar_lallu',
       'ajay_kumar_singh',
       'ajay_s._shriram',
       'ajam_of_bahrain',
       'ajax_the_lesser',
       'ajan_shir_melli',
       'ajax_go_station',
       'ajaz_ahmed_khan',
       'ajac_de_calheta',
       'ajay_veer_yadav',
       'ajai_p_mangattu',
       'ajay_raj_singh',
       'ajai_pal_singh',
       'ajay_k._pandey',
       'ajahn_maha_bua',
       'ajax_de_ouenze',
       'ajax_the_great',
       'aja_naomi_king',
       'aja_of_kosala',
       'aja_aja_tayo!',
       'ajay_dev_goud',
       'ajai_k._singh',
       'ajay_k._sood'],
 'c': ['ajc_transatlantic_institute', 'ajc_st_leger'],
 'd': ['ajdovscina_railway_station', 'ajda_pekkan_discography'],
 'e': ['ajeet_singh_kharkhari',
       'ajendra_bahadur_singh',
       'ajeya_pratap_singh',
       'ajeet_singh_yadav',
       'ajet_sopi_bllata',
       'ajen_yohl_mat',
       'aje_de_bobo'],
 'h': ['ajharail_railway_station', 'ajhai_railway_station'],
 'i': ['ajirkot_rural_municipality',
       'ajinomoto_field_nishigaoka',
       'ajith_rupasinghe_surendra',
       'ajitkheri_railway_station',
       'ajiyoshi_futagoyama_kofun',
       'ajith_kumar_filmography',
       'ajith_kumar_siriwardena',
       'ajimudaoro_aladesanmi_i',
       'ajia-do_animation_works',
       'ajit_chandra_chatterjee',
       'ajit_kumar_chakravarty',
       'ajit_kumar_chaturvedi',
       'ajira_digital_program',
       'ajita_suchitra_veera',
       'ajith_nivard_cabraal',
       'ajit_kumar_banerjee',
       'ajilon_jasper_nasiu',
       'ajit_singh_rathore',
       'ajit_singh_sarhadi',
       'ajit_narain_haksar',
       'aji_imbut_stadium',
       'ajit_singh_bhogal',
       'ajit_swaran_singh',
       'ajit_prakash_shah',
       'ajit_pratap_singh',
       'ajit_kumar_bhuyan',
       "ajija's_day_gecko",
       'ajit_kumar_panja',
       'ajit_kumar_singh',
       'ajit_kumar_mehta',
       'ajit_singh_mehta',
       'ajit_kumar_maiti',
       'ajit_singh_kohar',
       'ajit_prasad_jain',
       'ajit_iqbal_singh',
       'ajit_singh_balla',
       'ajit_pal_mangat',
       'ajit_kumar_guha',
       'ajit_kumar_saha',
       'aji_chay_bridge',
       'ajit_singh_gill',
       'ajit_kumar_basu',
       'aji_ichi_monme',
       'ajit_singh_pal',
       'ajit_pal_singh',
       'aji_de_gallina',
       'aji_chay,_iran',
       'ajit_ram_verma',
       'aji_bayu_putra',
       'ajit_das_gupta',
       'ajit_de_silva',
       'aji_sunte_ho',
       'ajit_kumar_p'],
 'j': ['ajjanahalli,_bangalore_south',
       'ajjihalli,_uttara_kannada',
       'ajjavara,_chik_ballapur',
       'ajjamada_b._devaiah',
       'ajjar_of_bulgaria',
       'ajj_de_ranjhe'],
 'l': ['ajloun_baptist_school',
       'ajloun_forest_reserve',
       'ajlan_ibn_rumaythah',
       'ajlan_and_brothers',
       'ajla_del_ponte'],
 'm': ['ajmer-rameswaram_humsafar_express',
       'ajmer-hyderabad_meenakshi_express',
       'ajmer-bandra_terminus_express',
       'ajman_international_airport',
       'ajmer_legislative_assembly',
       'ajmer_railway_division',
       'ajmalji_valaji_thakor',
       'ajmer_military_school',
       'ajmera_global_school',
       'ajmer_dargah_bombing',
       'ajmer_sharif_dargah',
       'ajmal_ali_choudhury',
       'ajmal_zaheer_ahmad',
       'ajmer_singh_aulakh',
       'ajmer_singh_chopra',
       'ajmer_jain_temple',
       'ajmal_khan_wazir',
       'ajmal_khan_park',
       'ajmer_rape_case',
       'ajman_free_zone',
       'ajmal_p._a.'],
 'n': ['ajnala_assembly_constituency',
       'ajnala_railway_station',
       'ajnod_railway_station',
       'ajni_railway_station',
       'ajnabi_lage_zindagi'],
 'o': ['ajomuzu_collette_bekaku',
       'ajou_motor_college',
       'ajob_premer_golpo',
       'ajoy_kumar_dutta',
       'ajooba_kudrat_ka',
       'ajou_law_school',
       'ajo_high_school',
       'ajo_copper_news',
       'ajos_y_zafiros',
       'ajoy_nath_ray'],
 'p': ['ajpw_junior_league'],
 's': ['ajs_silver_streak',
       'ajs_s3_v-twin',
       'ajs_model_16',
       'ajs_model_31',
       'ajs_model_20',
       'ajs_model_d'],
 't': ['ajtosi_durer_sor'],
 'u': ['ajunahi_barsaat_aahe',
       'ajudhiya_nath_khosla',
       'aju_business_daily',
       'ajuda_da_bretanha'],
 'w': ['ajw_junior_championship', 'ajwad_ibn_zamil']}
