
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ip = {'_': ['ip_multimedia_subsystem',
       'ip_fragmentation_attack',
       'ip_address_management',
       'ip_access_controller',
       'ip_address_blocking',
       'ip_address_spoofing',
       'ip_virtual_server',
       'ip_postcode_area',
       'ip_tomar_rugby',
       'ip_load_tester',
       'ip_chung_long',
       'ip_over_dvb',
       'ip_kwok_kan',
       'ip_yut_kin',
       'ip_pui_yi',
       'ip_man_3',
       'ip_in_ip',
       'ip_man_2'],
 'a': ['ipalogama_divisional_secretariat',
       'ipatovo,_stavropol_krai',
       'ipatinga_futebol_clube',
       'ipaghiganti_mo_ako...!',
       'iparty_with_victorious',
       'ipanema_atletico_clube',
       'ipanema,_minas_gerais',
       'ipag_business_school',
       'iparhi_agapi_edo',
       'ipao_pillbox_i',
       'ipar_ozay_kurt',
       'ipad_mini_4',
       'ipad_mini_3',
       'ipad_mini_2',
       'ipad_air_2'],
 'c': ['ipc_world_championships', 'ipc_shopping_centre'],
 'e': ['ipecac_recordings_discography',
       'ipe_global_limited',
       'ipek_filiz_yazici',
       'iperu,_ogun_state',
       'ipepo_lo_hlanga',
       'ipe_quero_quero',
       'ipe_06_curucaca',
       'ipe_02_nhapecan',
       'ipe_kw-2_bigua'],
 'f': ['ipfaces_mobile_framework'],
 'h': ['iphone_photography_awards',
       'iphigene_ochs_sulzberger',
       'iphigenia_efunjoke_coker',
       'iphithi_nature_reserve',
       'iphigenie_en_tauride',
       'iphitus_of_oechalia',
       'iphigenia_in_tauris',
       'iphigenie_en_aulide',
       'iphigenia_in_aulis',
       'iphone_13_pro',
       'iphone_11_pro',
       'iphone_12_pro',
       'iphone_os_2',
       'iphone_os_1',
       'iphone_os_3'],
 'i': ['ipil,_zamboanga_sibugay',
       'ipiranga_do_piaui',
       'ipiranga_do_norte',
       'ipiranga_de_goias',
       'ipiranga_do_sul',
       'ipixuna_do_para'],
 'k': ['ipk_acrylic-polyvinyl_chloride'],
 'l': ['iplik_bazar-korkut_effendi', 'iplik_pazari_mosque'],
 'm': ['ipm_multisport_pavilion'],
 'o': ['ipo_underpricing_algorithm',
       'ipoola_alani_akinrinade',
       'ipoh_railway_station',
       'ipora_esporte_clube',
       'ipomoea_x_multifida',
       'ipoh_city_council',
       'ipoh_white_coffee',
       'ipod_click_wheel',
       'ipora_do_oeste'],
 'p': ['ipperwash_provincial_park',
       'ippodromo_della_favorita',
       'ippazio_antonio_bortone',
       'ippolito_maria_beccaria',
       'ippolito_del_donzello',
       'ippolita_maria_sforza',
       "ippolito_de'_medici",
       'ippadikku_en_kadhal',
       'ippatsu_kiki_musume',
       'ippadiyum_oru_penn',
       'ippolito_ed_aricia',
       "ippolito_ii_d'este",
       "ippolito_de'_rossi",
       'ippen_shonin_eden',
       'ippon_grand_prix',
       'ippon_seoi_nage'],
 'r': ['ipr_microfinance_institution'],
 's': ['ipswich_corporation_tramways',
       'ipswich_hospital,_queensland',
       'ipsen_international_holding',
       'ipswich_motorsport_precinct',
       'ipswich_village_development',
       'ipsos_bucharest_challenger',
       'ipswich_historical_society',
       'ipswich_gymnastics_centre',
       'ipswich_road,_colchester',
       'ipstones_railway_station',
       'ipswich_transport_museum',
       'ipswich_general_cemetery',
       'ips_supported_employment',
       'ipsc_bosnia_herzegovina',
       'ipswich_female_seminary',
       'ipswich_mental_hospital',
       'ipswich_borough_council',
       'ipswich_central_mission',
       'ipswich_railway_station',
       'ipswich_community_radio',
       'ipswich_serial_murders',
       'ipswich_baptist_church',
       'ipswich_wanderers_f.c.',
       'ipsita_roy_chakraverti',
       'ipswich_road,_brisbane',
       'ipswich_grammar_school',
       'ipsc_macau_association',
       'ipswich_jazz_festival',
       'ipswich,_south_dakota',
       'ipswich_garden_suburb',
       'ipswich_built-up_area',
       'ipswitch_imail_server',
       'ipswich_town_wharves',
       'ipswich_range_lights',
       'ipswich_yellow_party',
       'ipswich_rugby_league',
       'ipswich_poetry_feast',
       'ips_business_school',
       'ipswich_gas_company',
       'ipsc_cayman_islands',
       'ipswich_hockey_club',
       'ipswich_art_society',
       'ipswich_crown_court',
       'ipswich_high_school',
       'ipswich_engine_shed',
       'ipswich_street_line',
       'ipsc_australia_inc',
       'ipswich_club_house',
       'ipswich_state_bank',
       'ipswich_model_band',
       'ipswich_knights_fc',
       'ipswich_town_hall',
       'ipswich_town_f.c.',
       'ipsc_world_shoots',
       'ipswich_cats_afc',
       'ipsc_action_air',
       'ipswich_city_fc',
       'ipsc_sri_lanka'],
 't': ['iptamenoi_pagodromoi_athinai',
       'ipt_fms-280_clairvoyance',
       'ipt_futsal_league'],
 'u': ['ipurua_municipal_stadium', 'ipur,_guntur_district'],
 'v': ['ipv6_transition_mechanism',
       'ipv4_residual_deployment',
       'ipv4_address_exhaustion',
       'ipv6_rapid_deployment',
       'ipv4_header_checksum'],
 'w': ['ipw_television_championship',
       "ipw:uk_women's_championship",
       'ipw:uk_world_championship'],
 'x': ['ipx_ultra-high-molecular-weight_polyethylene']}
