
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ub = {'_': ['ub_chartres_metropole', 'ub_postcode_area', 'ub_la_palma'],
 'a': ['ubayd-allah_ibn_abd-allah',
       'ubaydallah_ibn_al-mahdi',
       'ubaydallah_ibn_al-sari',
       'ubajara_national_park',
       'ubaldo_aguilar_flores',
       'ubaydah_ibn_al-harith',
       'ubayd-allah_ibn_jahsh',
       'ubayd_allah_al-anbari',
       'ubangi_young_workers',
       'ubayama_shell_mound',
       'ubaldo_nestor_sacco',
       'ubaldo_fillol_award',
       'ubaldo_degli_uberti',
       'ubadah_ibn_al-samit',
       'uba_protein_domain',
       'ubasi_khong_tayiji',
       'ubaidur_rahman_zia',
       'ubaldo_i_visconti',
       'ubaldo_of_gallura',
       'ubaid_ullah_mayar',
       'ubach_over_worms',
       'ubay_ibn_khalaf',
       "ubayy_ibn_ka'b"],
 'b': ['ubbo_j._albertsen'],
 'c': ['ubc_thunderbirds_football',
       'ubc_okanagan_exchange',
       'ubc_botanical_garden',
       'ubc_gussing_knights',
       'ubc_okanagan_heat',
       'ubc_media_group'],
 'd': ['ubd_ibm_centre'],
 'e': ['ubeidiya_prehistoric_site',
       'uberlandia_esporte_clube',
       'ubeshwar_mahadev_temple',
       'ube_frontier_university',
       'uber_den_tellerrand',
       'ubeidiya,_west_bank',
       'uberto_de_morpurgo',
       'uberaba_sport_club',
       'ubertino_of_casale',
       'uberall_zu_hause',
       'ube_kosan_open',
       'ube_ice_cream'],
 'i': ['ubiquitin_c-terminal_hydrolase',
       'ubiquitin-protein_ligase_e3b',
       'ubiquitous_synergy_seeker',
       'ubirajara_ribeiro_martins',
       'ubique_barracks,_widnes',
       'ubiquitinyl_hydrolase_1',
       'ubiratan_pereira_maciel',
       'ubiratan_esporte_clube',
       'ubirajara,_sao_paulo',
       'ubid_protein_domain',
       'ubi_theatre_leipzig',
       'ubisoft_blue_byte',
       'ubieranie_do_snu',
       'ubi_mrt_station',
       'ubi_de_feo'],
 'm': ['ubm_northern_classic', 'ubm_technology_group'],
 'o': ['ubon_ratchathani_university',
       'ubon_ratchathani_province',
       'ubonrak_thonburi_hospital',
       'ubon_ratchathani_airport',
       'ubombo_ranches_airfield',
       'ubon_kruanapat_f.c.',
       'uboro_isong_inyang',
       'ubodung_udung_uko',
       'ubong_moses_ekpai',
       'ubon_united_f.c.',
       'ubol_ratana_dam'],
 'u': ['ubuntu_professional_certification',
       'ubuhlebezwe_local_municipality',
       'ubuntu_local_municipality',
       'ubuntu_netbook_edition',
       'ubuntu_software_center',
       'ubuntu_connected_front',
       'ubuntu_version_history',
       'ubu_repertory_theater',
       'ubud_monkey_forest'],
 'v': ['ubv_photometric_system'],
 'x': ['ubx_protein_domain']}
