
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sd = {'_': ['sd.kfz._265_panzerbefehlswagen',
       'sd_hullera_vasco-leonesa',
       'sd_solares-medio_cudeyo',
       'sd_gimnastica_arandina',
       'sd_buducnost_podgorica',
       'sd_command_chronicles',
       'sd_atletico_albericia',
       'sd_barreda_balompie',
       'sd_atletico_camocha',
       'sd_lovcen_cetinje',
       'sd_retuerto_sport',
       'sd_northern_river',
       'sd_croatia_berlin',
       'sd_ponferradina_b',
       'sd_crvena_zvezda',
       'sd_textil_escudo',
       'sd_sporting_sada',
       'sd_alcohol_35-a',
       'sd_octavio_vigo',
       'sd_balmaseda_fc',
       'sd_erandio_club',
       'sd_nk_krizevci',
       'sd_navarro_cf',
       'sd_eibar_urko',
       'sd_san_pedro',
       'sd_huesca_b',
       'sd_eibar_b',
       'sd_o_val'],
 'a': ['sdarm_general_conference',
       'sdat_tennis_stadium',
       'sda_protein_domain',
       'sdach_domrei_sor',
       'sda_tennis_open'],
 'c': ['sdc_galicia_mugardos', 'sdc_san_antonio'],
 'e': ['sderot_railway_station',
       'sde_dov_airport',
       'sdeh_bar_farm',
       'sdelka_ili_ne',
       'sdec_r_engine',
       'sde_sea_wave'],
 'm': ['sdm_college,_ujire', 'sdm_strength_film', 'sdm_law_college'],
 'o': ['sdot_micha_airbase', 'sdok_kok_thom'],
 'p': ['sdp_youth_forum'],
 'r': ['sdruzeni_ceskoslovenskych_horniku'],
 's': ['sds_tuberculosis_sanatorium',
       'sdsu_research_foundation',
       'sdss_j1228+1040_b',
       'sds_sigma_series',
       'sds_sessions_v.1',
       'sds_9_series'],
 'u': ['sdu_research_hospital'],
 'v': ['sdv_international_logistics'],
 'y': ['sdyushor_sokil-90_kyiv', 'sdyushor_sokil-89_kyiv']}
