
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sb = {'_': ['sb_george_smeed', 'sb_lady_daphne', 'sb_lag_40'],
 'a': ['sba_504_loan'],
 'b': ['sbb_cargo_international',
       'sbb-cff-ffs_rabde_12/12',
       'sbb-cff-ffs_rabde_8/16',
       'sbb-cff-ffs_rabe_514',
       'sbb-cff-ffs_rbde_560',
       'sbb-cff-ffs_ae_8/14',
       'sbb-cff-ffs_rbe_540',
       'sbb-cff-ffs_eem_923',
       'sbb-cff-ffs_bm_4/4',
       'sbb-cff-ffs_ee_922',
       'sbb-cff-ffs_am_841',
       'sbb-cff-ffs_ae_4/7',
       'sbb-cff-ffs_ae_4/8',
       'sbb-cff-ffs_ae_3/5',
       'sbb-cff-ffs_ae_6/6',
       'sbb-cff-ffs_ae_4/6',
       'sbb-cff-ffs_be_3/5',
       'sbb-cff-ffs_ce_6/6',
       'sbb-cff-ffs_re_420',
       'sbb-cff-ffs_de_6/6',
       'sbb_vukovi_beograd',
       'sbb-cff-ffs_re_450',
       'sbb-cff-ffs_em_3/3',
       'sbb-cff-ffs_re_620',
       'sbb-cff-ffs_am_6/6',
       'sbb-cff-ffs_re_460',
       'sbb-cff-ffs_b_3/4',
       'sbb-cff-ffs_c_5/6',
       'sbb-cff-ffs_a_3/5',
       'sbb_rabe_501',
       'sbb_bem_550'],
 'c': ['sbc_long_distance',
       'sbc_senior_open',
       'sbcc_rna_motif',
       'sbcd_rna_motif'],
 'e': ["sbeitla's_spring_festival",
       'sbe_entertainment_group',
       'sberbank_europe_group'],
 'f': ['sbf_visa_group'],
 'i': ['sbi_general_insurance',
       'sbi_capital_markets',
       'sbi_graduate_school',
       'sbi_mutual_fund'],
 'k': ['sbk:_snowboard_kids'],
 'm': ['sbm_bank_india'],
 'o': ['sbor,_pazardzhik_province',
       'sbor_narodni_bezpecnosti',
       'sbor,_kardzhali_province',
       'sbornik_kgb_sssr'],
 'p': ['sbp_pambansang_tatluhan',
       'sbp_integrasi_selandar',
       'sbp_integrasi_rawang',
       'sbp_integrasi_gombak',
       'sbp_integrasi_jempol'],
 'r': ['sbrana_psychiatric_hospital', 'sbr_creative_media'],
 's': ['sbs_entertainment_awards',
       'sbs_broadcasting_group',
       'sbs_world_movies',
       'sbs_contents_hub',
       'sbs_drama_awards',
       'sbs_gayo_daejeon',
       'sbs_world_news',
       'sbs_power_fm',
       'sbs_love_fm'],
 'u': ['sbuyiselwe_angela_buthelezi']}
