
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kv = {'_': ['kv_pharmaceutical',
       'kv_tirana',
       'kv_drita',
       'kv_arena',
       'kv_top',
       'kv_1'],
 'a': ['kvadraturen_skolesenter',
       'kvaevefjellet_mountain',
       'kvarterets_olycksfagel',
       'kvachi_kvachantiradze',
       'kvanhovden_lighthouse',
       'kvam,_nord-trondelag',
       'kvassheim_lighthouse',
       'kvarnerska_rivijera',
       'kvarkensky_district',
       'kvabiskhevi_church',
       'kvaevenutane_peaks',
       'kvanxidatl_village',
       'kvamsgavlen_cliff',
       'kvaevemoen_chapel',
       'kvarnsjon,_lissma',
       'kvalsaukan_bridge',
       'kvamshesten_basin',
       'kvaloya,_finnmark',
       'kvarnsjon,_glado',
       'kvaerner_process',
       'kvarteret_skatan',
       'kvarstad_vessels',
       'kvaerner_station',
       'kvaefjord_church',
       'kvamsoy,_sogndal',
       'kvalsund_bridge',
       'kval,_trondelag',
       'kvaesthusgade_5',
       'kvalsund_church',
       'kvarnsvedens_ik',
       'kvam,_steinkjer',
       'kvalsund_tunnel',
       'kvam,_innlandet',
       'kvammen_chapel',
       'kvaefjord_cake',
       'kvaerner_govan',
       'kvamsoy_church',
       'kvarken_bridge',
       'kvalsund_ship',
       'kvaloy_church',
       'kvarner_gulf',
       'kvarven_fort',
       'kvam_station',
       'kval,_norway',
       'kvass_barrel',
       'kval_station',
       'kvas_church',
       'kvam_church',
       'kvarnby_ik',
       'kvaloya_sk',
       'kvartet_i'],
 'b': ['kvbn-lp',
       'kvbc-lp',
       'kvbc',
       'kvbh',
       'kvbv',
       'kvbl',
       'kvbt',
       'kvbr',
       'kvbe'],
 'c': ['kvcr-dt',
       'kvck-fm',
       'kvcl-fm',
       'kvcb-lp',
       'kvcx',
       'kvce',
       'kvco',
       'kvcn',
       'kvct',
       'kvcp',
       'kvcc',
       'kvcr',
       'kvcy',
       'kvci',
       'kvcv',
       'kvcl',
       'kvcb',
       'kvcw',
       'kvcu',
       'kvck',
       'kvc'],
 'd': ['kvdo-tv',
       'kvdf-cd',
       'kvdo-lp',
       'kvd-1',
       'kvdp',
       'kvdf',
       'kvdu',
       'kvdw',
       'kvdi',
       'kvda',
       'kvdg',
       'kvdo',
       'kvdm'],
 'e': ['kvernhushaug_tunnel',
       'kvervelnatten_peak',
       'kveldulf_bjalfason',
       'kvetoslav_minarik',
       'kvetoslav_svoboda',
       'kveda_nasakirali',
       'kvemo_khodasheni',
       'kveta_petrickova',
       'kverneland_group',
       'kvenvaer_church',
       'kvemo_makvaneti',
       'kvesarum_castle',
       'kvetoslav_palov',
       'kvemo_natanebi',
       'kvetera_church',
       'kvemo_barghebi',
       'kvemo_okrokana',
       'kveta_pacovska',
       'kvemo_orozmani',
       'kvernes_church',
       'kveta_hruskova',
       'kveta_legatova',
       'kveta_fialova',
       'kveta_eretova',
       'kven_language',
       'kveta_jeriova',
       'kveta_peschke',
       'kvemo_qemulta',
       'kveta_havlova',
       'kveda_dzimiti',
       'kveda_bakhvi',
       'kvemo_sarali',
       'kvemo_azhara',
       'kvemo_kartli',
       'kveda_sakara',
       'kvemo_ermani',
       'kvemo_chala',
       'kvea_valley',
       'kven_people',
       'kveim_test',
       'kven_sea'],
 'f': ['kvfs-lp',
       'kvfw-ld',
       'kvfa-lp',
       'kvfd-tv',
       'kvfc',
       'kvfx',
       'kvfe',
       'kvfd'],
 'g': ['kvgb-fm', 'kvgq', 'kvgh', 'kvgs', 'kvgc', 'kvgb', 'kvgl', 'kvg'],
 'h': ['kvhc-ld',
       'kvhd-ld',
       'kvhf-ld',
       'kvhs',
       'kvhu',
       'kvhp',
       'kvht',
       'kvhw',
       'kvhz',
       'kvh'],
 'i': ['kvindelig_fremskridtsforening',
       'kvinnliga_arbetarklubben',
       'kvindelig_laeseforening',
       'kvistaberg_observatory',
       'kvitskarvhalsen_saddle',
       'kvitholmen_lighthouse',
       'kvitbjorn_disaster',
       'kvitsoy_lighthouse',
       'kvitsvodene_valley',
       'kviabryggja_prison',
       'kvitkleven_cirque',
       'kvithamaren_cliff',
       'kvistgard_station',
       'kvinnherad_church',
       'kvinge_peninsula',
       'kvisla,_buskerud',
       'kvitkjolen_ridge',
       'kvineshei_tunnel',
       'kviteseid_church',
       'kvinesdal_church',
       'kvissel_station',
       'kvitouli_castle',
       'kvitsund_gymnas',
       'kvinneby_amulet',
       'kvitholten_hill',
       'kvithovden_peak',
       'kvirike_mosque',
       'kvinnens_plass',
       'kvissel_murder',
       'kvitsoy_church',
       'kviris_palitra',
       'kviven_tunnel',
       'kvikne_church',
       'kviknes_hotel',
       'kvichak_river',
       'kvitsoy_tower',
       'kvisr_rocks!',
       'kvitka_cisyk',
       'kvikk_lunsj',
       'kvichak_bay',
       'kvitho_peak',
       'kvidinge_if',
       'kvibille_bk',
       'kvikk_case'],
 'j': ['kvjs', 'kvjm', 'kvjy'],
 'k': ['kvki-fm', 'kvk'],
 'l': ['kvly-tv_mast'],
 'm': ['kvm_splitter', 'kvm_switch'],
 'n': ['kvna-fm',
       'kvn-49',
       'kvnu',
       'kvnc',
       'kvne',
       'kvno',
       'kvnf',
       'kvnt',
       'kvna',
       'kvnn',
       'kvng',
       'kvni',
       'kvnr',
       'kvns',
       'kvnv',
       'kvn'],
 'o': ['kvok-fm',
       'kvos-tv',
       'kvox-fm',
       'kvoe-fm',
       'kvoo-fm',
       'kvou-fm',
       'kvom-fm',
       'kvof-tv',
       'kvong',
       'kvoc',
       'kvoi',
       'kvon',
       'kvoe',
       'kvoo',
       'kvou',
       'kvox',
       'kvot',
       'kvog',
       'kvoh',
       'kvoq',
       'kvok',
       'kvod',
       'kvoz',
       'kvom',
       'kvov',
       'kvow',
       'kvol',
       'kvoa',
       'kvob',
       'kvor',
       'kvop',
       'kvo'],
 'p': ['kvpa-ld',
       'kvps-ld',
       'kvpi-fm',
       'kvpx-ld',
       'kvpm',
       'kvpp',
       'kvps',
       'kvpt',
       'kvpi',
       'kvp'],
 'q': ['kvqt-ld', 'kvq'],
 'r': ['kvrkulja_lake'],
 's': ['kvsn-dt',
       'kvst-tv',
       'kvsw-lp',
       'kvsd-ld',
       'kvsv-fm',
       'kvsh-lp',
       'kvsj-fm',
       'kvsf-fm',
       'kvsf',
       'kvsm',
       'kvsv',
       'kvsp',
       'kvsa',
       'kvsr',
       'kvsc',
       'kvso',
       'kvsi',
       'kvsh',
       'kvss',
       'kvst',
       'kvs'],
 't': ['kvtx-ld',
       'kvts-lp',
       'kvtu-ld',
       'kvte-ld',
       'kvtk',
       'kvta',
       'kvti',
       'kvty',
       'kvtt',
       'kvtr',
       'kvto',
       'kvtv'],
 'u': ['kvutzat_kinneret', 'kvutzat_shiller', 'kvutzat_yavne'],
 'v': ['kvvu-tv',
       'kvvv-tv',
       'kvvv-ld',
       'kvva-fm',
       'kvvo-lp',
       'kvvl',
       'kvvz',
       'kvvf',
       'kvvs',
       'kvvv',
       'kvvp',
       'kvvn',
       'kvvr',
       'kvv'],
 'w': ['kvwo-lp', 'kvwg-fm', 'kvwc-fm', 'kvwe', 'kvwm', 'kvwf', 'kvwg', 'kvwc'],
 'x': ['kvxo', 'kvxr', 'kvxx'],
 'y': ['kvyn', 'kvye', 'kvyl', 'kvyb'],
 'z': ['kvz_s.c.']}
