
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lg = {'_': ['lg.philips_displays',
       'lg_corporation',
       'lg15:_outbreak',
       'lg_electronics',
       'lg_intuition',
       'lg_chocolate',
       'lg_extravert',
       'lg_tab-book',
       'lg_roboking',
       'lg_tractors',
       'lg_display',
       'lg_voyager',
       'lg_philips',
       'lg_crystal',
       'lg_quantum',
       'lg_vx9400',
       'lg_fiesta',
       'lg_cloche',
       'lg_octane',
       'lg_vx5500',
       'lg_vx8350',
       'lg_incite',
       'lg_velvet',
       'lg_lancet',
       'lg_cosmos',
       'lg_vx8300',
       'lg_lf7700',
       'lg_vx8360',
       'lg_viewty',
       'lg_vx8100',
       'lg_gw525',
       'lg_gw620',
       'lg_arena',
       'lg_tromm',
       'lg_uplus',
       'lg_twins',
       'lg_prada',
       'lg_venus',
       'lg_rumor',
       'lg_versa',
       'lg_vs740',
       'lg_ks360',
       'lg_cf360',
       'lg_gd910',
       'lg_kf510',
       'lg_g1500',
       'lg_kg320',
       'lg_shine',
       'lg_thinq',
       'lg_cu500',
       'lg_lx140',
       'lg_ks20',
       'lg_cyon',
       'lg_card',
       'lg_chem',
       'lg_expo',
       'lg_u830',
       'lg_leon',
       'lg_dare',
       'lg_wing',
       'lg_t385',
       'lg_pay',
       'lg_k62',
       'lg_v10',
       'lg_cns',
       'lg_v20',
       'lg_cup',
       'lg_k10',
       'lg_v30',
       'lg_l9',
       'lg_g6',
       'lg_g5',
       'lg_g3',
       'lg_ux',
       'lg_g4',
       'lg_g2',
       'lg_gx',
       'lg_vu'],
 'a': ['lgaa_uavs',
       'lga_4094',
       'lga_4189',
       'lga_1156',
       'lga_2011',
       'lga_2066',
       'lga_1366',
       'lga_1567',
       'lga_1150',
       'lga_20xx',
       'lga_13x6',
       'lga_115x',
       'lga_13xx',
       'lga_3647',
       'lga_1356',
       'lga_1200',
       'lga_1700',
       'lga_1151',
       'lga_1155',
       'lga_1248',
       'lga_775',
       'lga_77x',
       'lga_771'],
 'b': ['lgbt+_conservatives',
       'lgbt_organizations',
       'lgbt_conservatism',
       'lgbt_billionaires',
       'lgbt_reproduction',
       'lgbt_stereotypes',
       'lgbtq_psychology',
       'lgbt_linguistics',
       'lgbt_literature',
       'lgbt_foundation',
       'lgbt_community',
       'lgbt_baltimore',
       'lgbt_marketing',
       'lgbt-free_zone',
       'lgbt_movements',
       'lgbt_parenting',
       'lgbt_migration',
       'lgbt_qaamaneq',
       'lgbt_adoption',
       'lgbt_culture',
       'lgbt_cruises',
       'lgbt_detroit',
       'lgbt_history',
       'lgbt_slogans',
       'lgbt_tourism',
       'lgbtq_nation',
       'lgbt_foroyar',
       'lgbt_erasure',
       'lgbt_danmark',
       'lgbt_symbols',
       'lgb_alliance',
       'lgbt_network',
       'lgbt+_labour',
       'lgbt_trauma',
       'lgbt_ageing',
       'lgbt_slang',
       'lgbt_music'],
 'c': ['lgc_ltd'],
 'd': ['lgd_gaming'],
 'e': ['lge.huya', 'lgeepa', 'lge'],
 'f': ['lgfc', 'lgfl', 'lgf'],
 'g': ['lggs_j004431.71+415629.1'],
 'h': ['lgharbia', 'lghs', 'lgh'],
 'i': ['lgi_homes'],
 'j': ['lgj'],
 'k': ['lgk'],
 'l': ['lgl'],
 'm': ['lgm-118_peacekeeper', 'lgm-30_minuteman'],
 'o': ['lgov_constituency',
       'lgovsky_district',
       'lgota_wolbromska',
       'lgota_gawronna',
       'lgota_murowana',
       'lgota_blotna',
       'lgoc_x-type',
       'lgov_prison',
       'lgoc_b-type',
       'lgota_gorna',
       'lgota_mala'],
 'p': ['lgp-30', 'lgp2', 'lgp'],
 'r': ['lgr_sportswear', 'lgr-1_radar'],
 's': ['lgsf_kaunas'],
 't': ['lgt_group'],
 'u': ['lguest', 'lgu'],
 'v': ['lgv_montpellier-perpignan',
       'lgv_bordeaux-toulouse',
       'lgv_poitiers-limoges',
       'lgv_mediterranee',
       'lgv_rhone-alpes',
       'lgv_rhin-rhone',
       'lgv_atlantique',
       'lgv_normandie',
       'lgv_picardie',
       'lgv_sud-est',
       'lgv_nord',
       'lgv_est'],
 'x': ['lgx']}
