
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lw = {'_': ['lw_stores'],
 'a': ['lwakhakha,_uganda',
       'lwakhakha,_kenya',
       'lwamba_chileshe',
       'lwalu_language',
       'lwajjali_river',
       'lwandiswa_zuma',
       'lwando_manase',
       'lwazi_mthembu',
       'lwandle_plate',
       'lwazi_skosana',
       'lwazi_maziya',
       'lwazi_mvovo',
       'lwazi_madi'],
 'b': ['lwb'],
 'c': ['lwc'],
 'd': ['lwd_junak', 'lwd_szpak', 'lwd_zuraw', 'lwd_zuch', 'lwd_zak'],
 'e': ['lweibdeh_shamaliyah',
       'lwemiyaga_county',
       'lweendo_chisamu',
       'lwengo_district',
       'lweibdeh_sharki',
       'lweza_fc'],
 'f': ['lwfc'],
 'h': ['lwhs', 'lwh'],
 'i': ['lwini_foundation', 'lwiza_john', 'lwin_moe', 'lwi_zar'],
 'l': ['lwl'],
 'm': ['lwma', 'lwm'],
 'n': ['lwn.net', 'lwn'],
 'o': ['lwow-warsaw_school',
       'lwow_voivodeship',
       'lwow_subdialect',
       'lwo_shih-hsiung',
       'lwowek_county',
       'lwowek_slaski',
       'lwow_uprising',
       'lwow_eaglets',
       'lwow_ghetto',
       'lwow_oath',
       'lwow_land'],
 'p': ['lwp'],
 'r': ['lwrc_international', 'lwrc_repr', 'lwrc_sabr', 'lwrc_psd', 'lwrc_m6'],
 's': ['lws-6_zubr', 'lws-3_mewa'],
 't': ['lwt_news'],
 'v': ['lwv'],
 'w': ['lww']}
