
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-22T11:00:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b07a1d44361297259aa0bd40f06f92d5d142dba",
 "version": "0.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
