
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xm = {'_': ['xm1100_scorpion',
       'xm2001_crusader',
       'xm214_microgun',
       'xm133_minigun',
       'xm_deportivo',
       'xm_classics',
       'xm-54_mine',
       'xm29_oicw',
       'xm25_cdte',
       'xm_pcr'],
 'a': ['xmap215-dis1_family',
       'xmal_deutschland',
       'xmarks_sync',
       'xmas_story',
       'xmas_tree',
       'xmas_93'],
 'c': ['xmc'],
 'd': ['xmdr', 'xmdp', 'xmdf', 'xmd'],
 'e': ['xmedia_recode', 'xmen_disease'],
 'f': ['xmf'],
 'g': ['xmg_studio'],
 'i': ['xmission', 'xmithie', 'xming', 'xmind', 'xmi'],
 'k': ['xmk'],
 'l': ['xml_validation',
       'xml_encryption',
       'xml_framework',
       'xml_retrieval',
       'xml_namespace',
       'xml_signature',
       'xml_appliance',
       'xml_resource',
       'xml_database',
       'xml_protocol',
       'xml_pipeline',
       'xml_literals',
       'xml_firewall',
       'xml_notepad',
       'xml_catalog',
       'xml_script',
       'xml_schema',
       'xml_editor',
       'xml_events',
       'xml_base',
       'xml_tree',
       'xml_log'],
 'm': ['xmmxcs_2215-1738'],
 'o': ['xmobots_apoena'],
 'p': ['xmplay', 'xmpp', 'xmp'],
 'r': ['xmr'],
 's': ['xmss', 'xms'],
 't': ['xmtc', 'xmt'],
 'u': ['xmu_uav'],
 'x': ['xmx']}
