
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_x_ = {'_': ['x99_inverness-thurso',
       'x53_stirling-kinross',
       'x86_virtualization',
       'x4:_foundations',
       'x2_transceiver',
       'x7_coastrider',
       'x._silvestrii',
       'x17_particle',
       'x._australis',
       'x2_centauri',
       'x._concinna',
       'x3:_reunion',
       'x._princeps',
       'x._maculata',
       'x1_centauri',
       'x-200_mine',
       'x._darwini',
       'x._elegans',
       'x24_engine',
       'x3_trouble',
       'x/1872_x1',
       'x57_snake',
       'x._roseum',
       'x/1106_c1',
       'x_-cross-',
       'x_100pre',
       'x32_abi',
       'x_2000'],
 'a': ['x.a.n._thessaloniki',
       'x-arg_dipeptidase',
       'x_aegilotriticum',
       'x_arctodupontia',
       'x_anniversarium',
       'x_ambassadors',
       'x_amelasorbus',
       'x_amarcrinum',
       'x_astrolista',
       'x_aliceara',
       'x_article',
       'x:a_ratio',
       'x_aranda'],
 'b': ['x_brassoepidendrum',
       'x_brassocattleya',
       'x-bar_theory',
       'x-bar_chart',
       'x-beam_f.c.',
       'x_bitmap',
       'x_brands',
       'x_boat',
       'x_band',
       'x_bar'],
 'c': ['x-com:_interceptor',
       'x-class_submarine',
       'x-com:_apocalypse',
       "x-cutioner's_song",
       'x_crataemespilus',
       'x-com:_enforcer',
       'x-com:_alliance',
       'x-com:_genesis',
       'x_cattlianthe',
       'x_cremnosedum',
       'x_cyathidaria',
       'x_chromosome',
       'x_committee',
       'x_chitalpa',
       'x_centauri',
       'x_cambria',
       'x_country',
       'x_company',
       'x_carinae',
       'x_crucis',
       'x_cancri',
       'x_clips',
       'x_corps',
       'x_caeli',
       'x_class',
       'x_clan',
       'x_club'],
 'd': ['x_development', 'x_division', 'x_disease', 'x3d_fritz'],
 'e': ['x_engine', "x'ed_out"],
 'f': ['x-factor_investigations',
       'x-file_scandal',
       'x_festulolium',
       'x_fatshedera',
       'x-files_unit',
       'x-fast_trie',
       'x_faktorius',
       'x_forgetara',
       'x_function',
       'x_faktors',
       'x_femmes',
       'x_force'],
 'g': ['x-group_culture',
       'x_galiasperula',
       'x_gasteraloe',
       'x_gonzalez',
       'x_gonimara',
       'x_games'],
 'h': ['x_hyperactivation',
       'x-his_dipeptidase',
       'x_haagespostoa',
       'x_heucherella',
       'x-hazil_sur',
       'x_howeara'],
 'i': ['x_infinity', 'x_isle'],
 'j': ['x_japan'],
 'k': ['x-kaliber_2097'],
 'l': ['x-linked_agammaglobulinemia',
       'x-linked_hypophosphatemia',
       'x-linked_hypertrichosis',
       'x-linked_ichthyosis',
       'x@lilli,_nakhchivan',
       'x@lf@li,_sabirabad',
       'x@lilli,_jalilabad',
       'x@lf@l@r,_masally',
       'x@lilli,_ismailli',
       'x@l@c,_nakhchivan',
       'x@lf@l@r,_davachi',
       'x@lilli,_davachi',
       'x@lf@li,_imishli',
       'x_laeliocattleya',
       'x@lf@li,_shusha',
       'x-level_studios',
       'x-legged_sally',
       'x@l@c,_qubadli',
       'x@l@c,_salyan',
       'x@lilli,_agsu',
       'x@l@c,_khizi',
       'x@l@c,_ujar',
       'x_league',
       'x_lovers'],
 'm': ['x-methyl-his_dipeptidase',
       'x-men:_kingbreaker',
       'x-machine_testing',
       'x-men:_apocalypse',
       'x-men:_regenesis',
       'x-men:_evolution',
       'x-men_unlimited',
       'x-mass_festival',
       'x-men:_destiny',
       'x-men_legends',
       'x-men:_schism',
       'x-mode_social',
       'x-men:_legacy',
       'x-men_misfits',
       'x_miltonidium',
       'x-men_forever',
       'x-men_reload',
       'x-men_black',
       'x-men_2099',
       'x-men_gold',
       'x_movement',
       'x_multiply',
       'x-men_blue',
       'x-men_red',
       "x-men_'92",
       'x_macro',
       'x-men_2',
       'x_moves',
       'x_mark'],
 'n': ['x@nd@k,_qubadli', 'x@nd@k,_siazan', 'x-nation_2099', 'x_nine'],
 'o': ['x.org_foundation',
       'x.o._experience',
       'x.org_server',
       'x_oncostele',
       'x-o_manowar',
       'x_offender',
       'x/open_xa'],
 'p': ['x-pro_dipeptidase',
       'x*press_x*change',
       'x-plane_airliner',
       'x_phragmipaphium',
       'x-press_feeders',
       'x_phylliopsis',
       'x-press_pearl',
       'x_pachyveria',
       'x_phyllosasa',
       'x-press_2',
       'x_plastaz',
       'x_persei',
       'x_pixmap',
       'x_party'],
 'q': ['x-quisite'],
 'r': ['x-ray_microtomography',
       'x-ray_crystallography',
       'x-ray_interferometer',
       'x-ray_nanochemistry',
       'x-ray_fluorescence',
       'x-ray_spectroscopy',
       'x-ray_reflectivity',
       'x-ray_lithography',
       'x-ray_microscope',
       'x-ray_background',
       'x-ray_transform',
       'x-ray_telescope',
       'x-ray_generator',
       'x-ray_astronomy',
       'x-ray_nanoprobe',
       'x-ray_transient',
       'x-ray_notation',
       'x-ray_detector',
       'x-rated_fusion',
       'x-ray_welding',
       'x-ray_records',
       'x-ray_machine',
       'x-ray_burster',
       'x-ray_vision',
       'x-ray_marker',
       'x-ray_filter',
       'x-ray_source',
       'x-ray_pulsar',
       'x-ring_chain',
       'x-ray_optics',
       'x-ray_binary',
       'x-ray_flash',
       'x_reyllopia',
       'x_resources',
       'x_riigikogu',
       'x-ray_specs',
       'x-ray_laser',
       'x-ray_cafe',
       'x-ray_tube',
       'x-ray_spex',
       'x-ray_star',
       'x_rebirth',
       'x_raisons',
       'x_rating',
       'x_road'],
 's': ['x_sophrolaeliocattleya',
       'x-stream_network',
       'x_sophrocattleya',
       'x_sophrolaelia',
       'x_sorbaronia',
       'x_sagittarii',
       'x-seed_4000',
       'x_security',
       'x_singles',
       'x_server',
       'x_series',
       'x_shore'],
 't': ['x-trp_aminopeptidase',
       'x-type_histiocytosis',
       'x@tai,_nakhchivan',
       'x-tinction_agenda',
       'x-treme_close-up',
       'x-treme_express',
       'x-type_asteroid',
       "x'trapolis_mega",
       "x'trapolis_100",
       'x@tai,_agstafa',
       "x'trapolis_2.0",
       'x-treme_sports',
       'x_trichocidium',
       'x-treme_x-men',
       'x-tigi_mobile',
       'x@tai,_babek',
       'x@tai_raion',
       'x-trail_jam',
       'x-tra_naked',
       'x_terminal',
       'x-t._rex',
       'x_train',
       'x_troop',
       'x_tour',
       'x_tax'],
 'u': ['x-uav_uav', 'x_unit'],
 'v': ['x_vuylstekeara'],
 'w': ['x-way_crossing', 'x-wing_fighter', 'x_woman'],
 'x': ['x2x'],
 'y': ['x-y_plotter', 'x-y_table', 'x_you'],
 'z': ['x_zone']}
