
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lh = {'_': ['lh&stl_subdivision',
       'lh2_studios',
       'lh_aviation',
       'lh_41-1042',
       'lh_54-425',
       'lh_95',
       'lh_4'],
 'a': ['lhamsuren_myagmarsuren',
       'lhasa-nyingchi_railway',
       'lhasa-xigaze_railway',
       'lhachen_palgyigon',
       'lhaimagu_faqeeraa',
       'lhalung_monastery',
       'lhakpa_tsamchoe',
       'lhaviyani_atoll',
       'lhasang_tsering',
       'lhachen_naglug',
       'lha-bzang_khan',
       'lhadji_badiane',
       'lhachen_utpala',
       'lhade_namloyak',
       'lhadon_tethong',
       'lhachen_gyalpo',
       'lhatu_wangchuk',
       'lhain_township',
       'lhachen_bhagan',
       'lhasa_tibetan',
       'lhabab_duchen',
       'lhatse_county',
       'lhasa_terrane',
       'lhakpa_sherpa',
       'lhasa_nunatak',
       'lhalu_family',
       'lhari_county',
       'lhamo_la-tso',
       'lhagba_pool',
       'lhatu_dhura',
       'lhaj_belaid',
       'lhasa_newar',
       'lhasa_river',
       'lhasa_hotel',
       'lhaki_dolma',
       'lhasa_apso',
       'lhari_town',
       'lhasa_city',
       'lhagba_la'],
 'b': ['lhb_coaches'],
 'c': ['lhcb_experiment', 'lhcf_experiment'],
 'd': ['lhd'],
 'e': ['lhermitte-duclos_disease',
       'lherm,_haute-garonne',
       'lherison_debrise',
       'lhendup_tshering',
       "lhermitte's_sign",
       'lhendup_dorji',
       'lherz_massif',
       'lherm,_lot',
       'lhen_coan'],
 'f': ['lhfpl2', 'lhfpl1', 'lhfp'],
 'h': ['lhhh', 'lhhs'],
 'i': ['lhiba_kingzoo', 'lhi_records'],
 'k': ['lhk'],
 'm': ['lhm'],
 'o': ['lhofei_shiozawa',
       'lhokpu_language',
       'lhota_rapotina',
       'lhozhag_county',
       'lhoba_language',
       'lhorong_county',
       'lhotse_middle',
       'lho_shin-yong',
       'lhorong_town',
       'lhoba_people',
       'lhotka_prize',
       'lhonak_river',
       'lhop_people',
       'lhotse_shar',
       'lhong_1919',
       'lho_la'],
 'p': ['lhp'],
 's': ['lhs_telekommunikation',
       'lhs_1815b',
       'lhs_2520',
       'lhs_1140',
       'lhs_2924',
       'lhs_6343',
       'lhs_2090',
       'lhs_288',
       'lhs_292'],
 't': ['lhtec_t800', 'lht_tower'],
 'u': ['lhunshigyia_monastery',
       'lhuntse_district',
       'lhunzhub_county',
       'lhunze_county',
       'lhuta_zarucni',
       'lhuntse_dzong',
       'lhundub_sopa',
       'lhunze_town'],
 'v': ['lhv_pank'],
 'w': ['lhw'],
 'x': ['lhx1', 'lhx4', 'lhx3', 'lhx2', 'lhx6', 'lhx']}
