
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_y_ = {'_': ['y1-class_melbourne_tram',
       'y1_adrenocortical_cell',
       'y._michel_rabbinowicz',
       'y._s._chandrashekhar',
       'y._gadilingana_goud',
       'y._ramavaram_mandal',
       'y._ravindranath_rao',
       'y._visweswara_reddy',
       'y._a._narayanaswamy',
       'y._g._parthasarathy',
       'y._b._mangunwijaya',
       'y._michal_bodemann',
       'y._g._parameshwara',
       'y._subramanya_raju',
       'y._kasi_viswanath',
       'y._v._chandrachud',
       'y._sanathoi_devi',
       'y._melvin_hodges',
       'y._n._jayarathna',
       'y._g._jayasinghe',
       'y._n._sukthankar',
       'y._frank_freeman',
       'y._lawrence_yao',
       'y._hewoto_awomi',
       'y._austin_chang',
       'y._s._vijayamma',
       'y._pierre_gobin',
       'y._eswara_reddy',
       'y._sherry_sheng',
       'y._g._mahendran',
       'y._g._padmasiri',
       'y._bhaskar_rao',
       'y._s._sharmila',
       'y._d._gundevia',
       'y._claire_wang',
       'y._c._simhadri',
       'y._n._hosakote',
       'y._s._chowdary',
       'y._p._trivedi',
       'y._s._srinath',
       'y._g._mahajan',
       'y._h._malegam',
       'y._p._varshni',
       'y._d._tiwari',
       'y._k._sohoni',
       'y._a._tittle',
       'y._k._padhye',
       'y._r._meena',
       'y._b._rowdy',
       'y._s._patil',
       'y._r._swamy',
       'y._s._tambe',
       'y._s._rajan',
       'y._v._reddy',
       'y._c._wong',
       'y._v._rao',
       'y._s._rao',
       'y._t._lee',
       'y._t._wu',
       'y._w._ma'],
 'a': ["y'all_don't_understand",
       "y'avait_un_prisonnier",
       'y.a.r.o_ka_tashan',
       "y'all_so_stupid",
       "y'a_pas_photo"],
 'b': ['y_beibl_cyssegr-lan',
       'y-bar_shrimp_goby',
       'y-bar_moray_eel',
       'y_bwthyn_bach',
       'y_bham_enuol',
       'y_b_normal?'],
 'c': ['y_chromosome_microdeletion',
       'y_chromosome_consortium',
       'y-class_melbourne_tram',
       'y-control_for_fighters',
       'y_city,_arkansas',
       'y_c_mcnease'],
 'd': ['y_drych_cristianogawl', 'y_dafarn_goch'],
 'e': ["y'en_a_marre", 'y_es_facil', 'y_eli_nie'],
 'f': ['y_felinheli_f.c.',
       'y_fenni_cheese',
       'y_fro_gymraeg',
       'y_ford_gron',
       'y_foel_goch'],
 'g': ['y_gors,_ceredigion',
       'y_genedl_gymreig',
       'y_goeden_eirin',
       'y_groes_fagl',
       'y_garn_goch'],
 'h': ['y_hubo_alguien'],
 'k': ['y2k:_the_album', 'y2k:_the_game', 'y2k_fm_90.6'],
 'l': ['y_ladi_wen', 'y_la_bamba', 'y_lle_celf'],
 'n': ['y_not_festival', 'y_no_regresas'],
 'o': ['y-o_ranch,_wyoming'],
 'p': ['y-patterned_moray_eel',
       'y_prydydd_bychan',
       'y_para_siempre',
       'y_pant_school',
       'y_p_desert'],
 'r': ['y_ro_wen'],
 's': ["y's_men_international",
       'y_stiwdio_gefn',
       'y_selar_awards',
       'y_sayeed_ahmed',
       'y_su_pueblo',
       'y_s_college',
       'y_s_bakhle',
       'y_sap_mine'],
 't': ['y_tyst_cymreig', 'y_trydydd_peth', 'y_tu_tambien'],
 'w': ['y_with_stroke', 'y_with_loop'],
 'y': ['y_yen_district', 'y_y_y']}
