
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fs = {'_': ['fs_cartagena',
       'fs_napajedla',
       'fs_martorell',
       'fs_mostoles',
       'fs_marjata',
       'fs_garcia',
       'fs_zamora',
       'fs_seoul',
       'fs_eger',
       'fs_set',
       'fs_me'],
 'a': ['fsa_corporation', 'fsa_freedom'],
 'b': ['fsbo_madison', 'fsb_academy', 'fsbi_medal'],
 'c': ['fsc_15307+3253',
       'fsc_lohfelden',
       'fsc_millport',
       'fsc_rybinsk',
       'fsc_lublin',
       'fsc_star',
       'fsc_zuk'],
 'd': ['fsd'],
 'e': ['fsevents', 'fse'],
 'f': ['fsf_trophy'],
 'g': ['fsg'],
 'h': ['fshajt_bridge', 'fshv_cup'],
 'i': ['fsi_international'],
 'j': ['fsj'],
 'k': ['fsk_klungkung'],
 'l': ['fsl'],
 'm': ['fsm_beskid'],
 'n': ['fsn_analysis'],
 'o': ['fso_warszawa',
       'fso_nabarima',
       'fso_polonez',
       'fso_syrena',
       'fso_safer'],
 'p': ['fspace_publications', 'fsp_festival', 'fsp_group'],
 'q': ['fsq'],
 'r': ['fsru_independence', 'fsr_tarpan', 'fsr_1758'],
 's': ['fss_code'],
 't': ['fstc_awka'],
 'u': ['fsue_atomflot', 'fsu_hymns'],
 'v': ['fsv_krumhermersdorf',
       'fsv_erlangen-bruck',
       'fsv_bergshausen',
       'fsv_jagersburg',
       'fsv_oggersheim',
       'fsv_hollenbach',
       'fsv_frankfurt',
       'fsv_braunfels',
       'fsv_bentwisch',
       'fsv_salmrohr',
       'fsv_bayreuth',
       'fsv_zwickau',
       'fsv_velten'],
 'w': ['fsw'],
 'y': ['fsy']}
