
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fg = {'_': ['fg_hemisphere', 'fg_syndrome', 'fg_sagittae', 'fg_1250', 'fg_42'],
 'a': ['fga'],
 'b': ['fgb'],
 'c': ['fgc_ues'],
 'd': ['fgd4', 'fgd2', 'fgd1', 'fgd3', 'fgd'],
 'e': ['fged_society'],
 'f': ['fgfr1op2',
       'fgf15/19',
       'fgfr1op',
       'fgfbp1',
       'fgf18',
       'fgf15',
       'fgf11',
       'fgf14',
       'fgf19',
       'fgf12',
       'fgf22',
       'fgf21',
       'fgf20',
       'fgf16',
       'fgf10',
       'fgf13',
       'fgf17',
       'fgf7',
       'fgf5',
       'fgf6',
       'fgf4',
       'fgf1',
       'fgf3',
       'fgf9',
       'fgf8',
       'fgf'],
 'g': ['fgg'],
 'h': ['fgh'],
 'i': ['fgin-143', 'fgin-127', 'fgi-106', 'fgi-103', 'fgi-104', 'fgi'],
 'l': ['fgl_productions', 'fglm_algorithm', 'fgl_sports'],
 'm': ['fgm-148_javelin', 'fgm-172_sraw'],
 'n': ['fgn'],
 'o': ['fgo'],
 'p': ['fgp_227'],
 'r': ['fgr-17_viper'],
 's': ['fgs'],
 't': ['fgt'],
 'u': ['fgura', 'fgu'],
 'v': ['fgv_management', 'fgv_brasilia'],
 'w': ['fgw']}
