
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bb = {'_': ['bb3b',
       'bb17',
       'bb13',
       'bb15',
       'bb06',
       'bb&t',
       'bb11',
       'bb14',
       'bb19',
       'bb84',
       'bb10',
       'bb20',
       'bb-8',
       'bb18',
       'bb12',
       'bb16',
       'bb3',
       'bb8',
       'bb7',
       'bb9',
       'bb5',
       'bb1',
       'bb6',
       'bb4'],
 'a': ['bbaale', 'bbam'],
 'b': ['bbbank', 'bbbp', 'bbbs', 'bbbb', 'bbb'],
 'c': ['bbch-scale', 'bbcode', 'bbcor', 'bbcm', 'bbci', 'bbch', 'bbcf', 'bbc'],
 'd': ['bbdo', 'bbdd', 'bbd'],
 'e': ['bbedit', 'bbeb', 'bbes', 'bbe'],
 'f': ['bbfn', 'bbf'],
 'g': ['bbga', 'bbgm', 'bbgi', 'bbg'],
 'h': ['bbhs', 'bbh'],
 'i': ['bbibbi', 'bbiab', 'bbiaw', 'bbin', 'bbi'],
 'k': ['bbk/brnk', 'bbk'],
 'l': ['bbl-pokal', 'bbl'],
 'm': ['bbmak', 'bbmg', 'bbm'],
 'n': ['bbnglive', 'bbno$', 'bbng2', 'bbn'],
 'o': ['bboongbboong-e', 'bborubong', 'bbodance', 'bbox', 'bbo'],
 'p': ['bbpr', 'bbp'],
 'q': ['bbqguys'],
 'r': ['bbrc', 'bbrg', 'bbr'],
 's': ['bbsome',
       'bbspot',
       'bbs12',
       'bbs10',
       'bbs7',
       'bbs4',
       'bbs1',
       'bbss',
       'bbs2',
       'bbs9',
       'bbs5',
       'bbs'],
 't': ['bbtm', 'bbt'],
 'u': ['bburago', 'bbu'],
 'v': ['bbv154', 'bbv'],
 'w': ['bbwc', 'bbwr', 'bbw'],
 'x': ['bbx'],
 'y': ['bbymutha', 'bbyo', 'bby']}
