
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nd = {'_': ['nd_experiment',
       'nd_stevenson',
       'nd:yag_laser',
       'nd_renkovci',
       'nd_dravinja',
       'nd_primorje',
       'nd_beltinci',
       'nd_studios',
       'nd_crnuce',
       'nd_slovan',
       'nd_gorica',
       'nd_adria',
       'nd_bilje',
       'nd_game'],
 'a': ['ndaizivei_madzikangava',
       'ndabazinhle_mdhlongwa',
       'ndande_arrondissement',
       'ndaragwa_constituency',
       'ndayishimiye_cabinet',
       'ndame_arrondissement',
       'ndaziona_chatsalira',
       'ndabaningi_sithole',
       'ndabili_bashingili',
       'ndambomo_language',
       'ndakunimba_stones',
       "nda'nda'_language",
       'ndaakoya_festival',
       'ndabenkulu_ncube',
       'ndamira_atwakire',
       'ndaweni_mahlangu',
       'ndamba_language',
       'ndaba_kamageba',
       'ndasa_language',
       'ndaka_language',
       'ndali_language',
       'ndava,_bubanza',
       'ndala_kachibo',
       'ndala_kasheba',
       'ndam_language',
       'ndala_ibrahim',
       'ndaye_mulamba',
       'ndai_language',
       'ndaba_mhlongo',
       'ndamukong_suh',
       'ndaba_mandela',
       'ndamba_people',
       'ndanda_abbey',
       'ndali_people',
       'ndarugu_farm',
       'ndau_dialect',
       'ndaka_people',
       'ndama_bapupa',
       'ndadaye_day',
       'ndanda_f.c.',
       'ndao_island',
       'ndau_people',
       'ndala_monga',
       'ndary_adopo',
       'ndaba_rock',
       'ndaba_dube',
       'ndani_tv'],
 'b': ['ndb_cluster'],
 'c': ['ndc_mediagroep'],
 'd': ['nddb', 'nddo', 'ndd'],
 'e': ['nde-nsele-nta_language',
       'ndengereko_language',
       'ndendeule_language',
       'ndengereko_people',
       'ndejje_university',
       'ndebele_language',
       'nderitu_gachagua',
       'ndendeule_people',
       'ndeutala_angolo',
       'ndemli_language',
       'nderit_pottery',
       'ndebele_people',
       'ndende_airport',
       'nderim_nexhipi',
       'ndeh_ntumazah',
       'ndebele_music',
       'nderim_saraci',
       'ndeye_ndiaye',
       'ndere_island',
       'nderitu_farm',
       'ndeye_dieng',
       'ndella_paye',
       'ndew_niang',
       'ndete_napu',
       'ndeye_sene',
       'ndeg_2'],
 'f': ['ndf_rebellion'],
 'g': ['ndga', 'ndg'],
 'h': ['ndhiwa_constituency', 'ndhq_carling'],
 'i': ['ndiedieng_arrondissement',
       'ndiaye_arrondissement',
       'ndindy_arrondissement',
       'ndioum_arrondissement',
       'ndiapo_letsholathebe',
       'ndiyona_constituency',
       'ndi_okereke-onyiuke',
       'ndidi_nnoli-edozien',
       'ndiago,_mauritania',
       'ndia_constituency',
       'ndiritu_muriithi',
       'ndileka_mandela',
       'ndiayene_bagana',
       'ndidi_winifred',
       'ndidi_onukwulu',
       'ndifuna_ukwazi',
       'nding_language',
       'ndiatte_gueye',
       'ndiaga_ndiaye',
       'ndioro_ndiaye',
       'ndiouga_dieng',
       'ndialou_paye',
       'ndidi_ekubia',
       'ndindi_nyoro',
       'ndingo_johwa',
       'ndiaga_dieng',
       'ndifreke_udo',
       'ndiole_sene',
       'ndidi_nwosu',
       'ndidi_kanu',
       'ndidi_dike',
       'ndidi_madu',
       'ndiareme_b'],
 'j': ["ndjibu_n'golomingi",
       'ndjebbana_language',
       'ndjili,_kinshasa',
       'ndjeka_mukando',
       'ndjili_river',
       'ndjim_river',
       'ndji_river'],
 'k': ['ndkt', 'ndk'],
 'l': ['ndlela_kasompisi'],
 'm': ['ndmc_supercomputer'],
 'n': ['ndn_firecracker', 'ndn_collective'],
 'o': ['ndongolera_mwangupili',
       'ndoulo_arrondissement',
       'ndoors_corporation',
       'ndorobo_language',
       'ndombe_language',
       'ndogboyosoi_war',
       'ndoda_mthethwa',
       'ndola_district',
       'ndoro_language',
       'ndogo_language',
       'ndonga_dialect',
       'ndom_language',
       'ndonde_people',
       'ndola_central',
       'ndoe_language',
       'ndombe_mubele',
       'ndok_gjeloshi',
       'ndombe_opetum',
       'ndolo_dialect',
       'ndogo_lagoon',
       'ndokoa_gorge',
       'ndo_language',
       'ndoc_martini',
       'ndogo_people',
       'ndokwa_lale',
       'ndong_awing',
       'ndoc_gjetja',
       'ndokwa_west',
       'ndokwa_east',
       'ndoc_nikaj',
       'ndon_uruan',
       'ndowa_lale',
       'ndon_utim'],
 'p': ['ndp-glucose--starch_glucosyltransferase'],
 'r': ['ndr_radiophilharmonie',
       "ndra'ngith_language",
       'ndrangith_language',
       'ndrumbea_language',
       'ndricim_shtubina',
       'ndrulo_language',
       'ndricim_babasi',
       'ndriqim_halili',
       'ndricim_ademaj',
       'ndr_fernsehen',
       'ndre_language',
       'ndricim_xhepa',
       'ndrek_luca',
       'ndre_mjeda',
       'ndr_method',
       'ndr_kinase',
       'ndr_chor'],
 's': ['ndst1',
       'ndst3',
       'ndst2',
       'ndsl',
       'ndsm',
       'ndsi',
       'ndss',
       'ndsf',
       'ndsa',
       'nds'],
 't': ['ndtv_arabia', 'ndtv_profit', 'ndtv_india', 'ndtv_prime', 'ndtv_24x7'],
 'u': ['nduduzo_makhathini',
       'ndubisi_chukunyere',
       'ndubuisi_okosieme',
       'nduduza_lembethe',
       'nduka_onwuegbute',
       'ndubuisi_ekekwe',
       'ndunda_language',
       'ndunga_language',
       'ndumiso_mvelase',
       'nduka_obaigbena',
       'ndumba_makeche',
       'ndukaku_alison',
       'ndue_perlleshi',
       'ndumiso_mabena',
       'nduga_language',
       'nduga_massacre',
       'nduduzo_sibiya',
       'ndumu_language',
       'nduku_kilonzo',
       'ndumiso_mamba',
       'ndubuisi_kanu',
       'nduga_regency',
       'ndut_language',
       'ndu,_cameroon',
       'nduduzo_mfoza',
       'nduese_essien',
       'ndubuisi_egbo',
       'ndu_languages',
       'nduka_anyanwu',
       'ndutu_cranium',
       'ndue_marashi',
       'nduka_odizor',
       'ndubuisi_eze',
       'ndumiso_capa',
       'ndu_language',
       'ndubuisi_obi',
       'nduka_ozokwo',
       'nduka_ugbade',
       'nduka_awazie',
       'ndunyu_chege',
       'ndue_mujeci',
       'ndumu_virus',
       'ndue_paluca',
       'ndumbe_eyoh',
       'nduka_usim',
       'nduo_eduo',
       'ndue_ukaj',
       'ndudi_ebi'],
 'v': ['ndvungunye', 'ndv-hxp-s', 'ndv'],
 'w': ["ndwa'ngith_language", 'ndwandwe-zulu_war', 'ndwewe_language'],
 'y': ['ndyuka-tiriyo_pidgin',
       'ndyakira_amooti',
       'ndyuka_language',
       'ndyuka_people'],
 'z': ['ndzemdzela_langwa', 'ndzalama_reserve', 'ndzerem_language']}
