
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nn = {'_': ['nn_serpentis', 'nn_group'],
 'a': ['nnaemeka_ikegwuonu',
       'nnamdi_chukwuocha',
       'nnaemeka_anyamele',
       'nnamdi_ogbonnaya',
       'nnaemeka_anyanwu',
       'nnamdi_asomugha',
       'nnamdi_innocent',
       'nnamdi_obukwelu',
       'nnamdi_oduamadi',
       'nnamdi_azikiwe',
       'nnamdi_okonkwo',
       'nnamdi_ofoborh',
       'nnaemeka_ajuru',
       'nnamdi_collins',
       'nnamdi_nwauwa',
       'nnamdi_anusim',
       'nnam_language',
       'nnamdi_moweta',
       'nnamdi_kanu',
       'nnanna_ikpo',
       'nnachi_ipia',
       'nnamdi_udoh',
       'nnanna_egwu'],
 'b': ['nnb'],
 'c': ['nnc_63-0532', 'nnc_38-1049', 'nnc_45-0095'],
 'd': ['nndb'],
 'e': ['nneka_onyeali-ikpe',
       'nnenne_iwuji-eme',
       'nneka_egbujiobi',
       'nnenna_nwakanma',
       'nneka_onyejekwe',
       'nnenna_freelon',
       'nneka_abulokwe',
       'nnedi_okorafor',
       'nneka_ogwumike',
       'nnegest_likke',
       'nneka_onuorah',
       'nneka_okpala',
       'nnenna_okore',
       'nnenna_njoku',
       'nnenna_lynch',
       'nnewi_south',
       'nnewi_north',
       'nneka_jones',
       'nneka_ukuh',
       'nnenna_oti'],
 'f': ['nnfcc', 'nnf'],
 'g': ['nngi', 'nng'],
 'h': ['nnhs'],
 'i': ['nnimmo_bassey', 'nni_news'],
 'k': ['nnk'],
 'l': ['nnls', 'nnl'],
 'm': ['nnmc', 'nnmt', 'nnm'],
 'n': ['nnn_lease'],
 'o': ['nnorom_azuonye'],
 'p': ['nnpdf', 'nnpi', 'nnp'],
 's': ['nns_okpabana', 'nns_andoni', 'nns_obuma', 'nns_aradu'],
 't': ['nnt'],
 'u': ['nnubi_dynasty'],
 'v': ['nnv'],
 'w': ['nnw'],
 'y': ['nnywane_dam']}
