
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nl = {'_': ['nl_industries'],
 'a': ["nlaka'pamux",
       'nlayers',
       'nlaman',
       'nlaiii',
       'nland',
       'nlaw',
       'nlab',
       'nla'],
 'b': ['nlb_group'],
 'c': ['nlcf', 'nlcc', 'nlc'],
 'd': ['nld'],
 'e': ['nlex_corporation', 'nle_choppa'],
 'f': ['nlf'],
 'g': ['nlgn4x', 'nlgn1', 'nlgn3', 'nlgn2', 'nlgn', 'nlg'],
 'h': ['nlhamankulu', 'nlhs', 'nlh'],
 'i': ['nlive_radio'],
 'j': ['nlj'],
 'k': ['nlk'],
 'l': ['nll_draft'],
 'm': ['nlm_cityhopper'],
 'n': ['nlnet_labs'],
 'o': ['nlogit', 'nlo'],
 'p': ['nlpqlp', 'nlpc', 'nlp'],
 'r': ['nlrp14',
       'nlrp12',
       'nlrp10',
       'nlrp13',
       'nlrp11',
       'nlrc3',
       'nlrp1',
       'nlrc4',
       'nlrp3',
       'nlrp6',
       'nlrp9',
       'nlrp7',
       'nlrc5',
       'nlrp5',
       'nlrp4',
       'nlrx1',
       'nlrp8',
       'nlrp2',
       'nlrp',
       'nlr'],
 's': ['nls_debate', 'nls_crew'],
 't': ['nlt_productions'],
 'u': ['nluug', 'nlu'],
 'v': ['nlv_pharos'],
 'w': ['nlwc', 'nlw'],
 'x': ['nlx'],
 'y': ['nly'],
 'z': ['nlz']}
