
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-09T10:49:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "73cb64ca45f361126da1a26377357f756ddd900f",
 "version": "2.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
