
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hr = {'_': ['hr_college,_amnour',
       'hr_postcode_area',
       'hr_8799_b',
       'hr_8799_d',
       'hr_top_40',
       'hr_8799_e',
       'hr_5183_b',
       'hr_2562_b',
       'hr_8799_c'],
 'a': ['hrastovac,_bjelovar-bilogora_county',
       'hrafnhildur_hanna_thrastardottir',
       'hrafnhildur_hanna_ragnarsdottir',
       'hrasnica,_gornji_vakuf-uskoplje',
       'hradiste,_partizanske_district',
       'hrabrovo,_dobrich_province',
       'hranitne,_volnovakha_raion',
       'hradec_kralove_observatory',
       'hradivka,_mykolaiv_oblast',
       'hradiste,_poltar_district',
       'hrabove,_donetsk_oblast',
       'hradec_kralove_district',
       'hrastje_pri_grosupljem',
       'hradec_kralove_airport',
       'hrabove,_odessa_oblast',
       'hrazdan_gorge_aqueduct',
       'hradec_kralove_region',
       'hrabove,_shatsk_raion',
       'hrabovec_nad_laborcom',
       'hrant_dink_foundation',
       'hradivka,_lviv_oblast',
       'hrastnik_pri_trojanah',
       'hrastje_pri_cerkljah',
       'hradiste_pod_vratnom',
       'hrase_pri_preddvoru',
       'hrastje_ob_bistrici',
       'hrastovec_pod_bocem',
       'hradec_nad_moravici',
       'hradec_nad_svitavou',
       'hradek_u_nechanic',
       'hrana_za_golubove',
       'hrana_saga_hrings',
       'hrast_pri_jugorju',
       'hradcany_air_base',
       'hrast_pri_vinici',
       'hradek_nad_nisou'],
 'c': ['hrc_culinary_academy'],
 'd': ['hrdina_jedne_noci'],
 'e': ['hrebenne,_hrubieszow_county',
       'hrefna_huld_johannesdottir',
       'hrefna_bjork_sverrisdottir',
       'hreidar_mar_sigurdsson',
       'hredric_and_hrodmund'],
 'g': ['hrg_engineering_company'],
 'i': ['hristovtsi,_gabrovo_province',
       'hristijan_todorovski_karpos',
       'hrithik_roshan_filmography',
       'hridaypur_railway_station',
       'hridayeshwar_singh_bhati',
       'hrib,_smarjeske_toplice',
       'hridayam_oru_kshethram',
       'hriday_narayan_dikshit',
       'hristo_yankov_ivanov',
       'hristo_botev_stadium',
       'hrib_pri_koprivniku',
       'hristo_borisov_hall',
       'hrizea_of_bogdanei',
       'hristo_botev_radio',
       'hridaya_ram_thani',
       'hrib_pri_cerovcu',
       'hrib_nad_ribcami',
       'hrib_pri_kamniku',
       'hristo_g._danov',
       'hrib_pri_orehku',
       'hrib_pri_hinjah',
       'hri_kumar_nair',
       'hrib_pri_fari'],
 'n': ['hrnciarovce_nad_parnou'],
 'o': ['hromundar_saga_gripssonar',
       'hrolfs_saga_gautrekssonar',
       'hronovka_and_regnerka',
       'hroa_thattr_heimska',
       'hrodgaud_of_friuli',
       'hroznata_of_uzice',
       'hrolfs_saga_kraka'],
 'p': ['hrpelje-kozina_railway_station'],
 's': ['hrs_and_hrs'],
 'u': ['hrusovany,_topolcany_district',
       'hrusica,_ilirska_bistrica',
       'hrusovany_nad_jevisovkou',
       'hrusov,_roznava_district',
       'hrustovo,_velike_lasce',
       'hrund_olof_andradottir',
       'hrustovo,_sanski_most',
       'hrusica,_novo_mesto',
       'hruzke,_kyiv_oblast',
       'hrusky_oil_field',
       'hrusovany_u_brna'],
 'v': ['hrvatska_postanska_banka',
       'hrvoje_vukcic_hrvatinic',
       'hrvatski_radio_bobovac',
       'hrvacani,_kotor_varos',
       'hrvatska_posta_mostar',
       'hrvatski_top_model',
       'hrvoje_horvat,_jr.'],
 'y': ['hrydjuverkamadur_snyr_heim',
       'hryszko_brothers_building',
       'hryniak_v_mauldin',
       'hry_o_marii',
       'hry_a_sny']}
