
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ht = {'_': ['ht_premijer_liga', 'ht_tatran_presov', 'ht_ps_uav'],
 'a': ['htamanthi_wildlife_sanctuary', 'htang_gam_shawng', 'htar_htet_htet'],
 'c': ['htc_uhlenhorst_mulheim',
       'htc_global_services',
       'htc_advantage_x7500',
       'htc_touch_diamond2',
       'htc_touch_diamond',
       'htc_desire_series',
       'htc_touch_cruise',
       'htc_sensation_xl',
       'htc_incredible_s',
       'htc_touch_family',
       'htc_desire_626s',
       'htc_butterfly_2',
       'htc_butterfly_s',
       'htc_butterfly_3',
       'htc_desire_520',
       'htc_desire_616',
       'htc_wildfire_s',
       'htc_7_surround',
       'htc_desire_820',
       'htc_desire_200',
       'htc_desire_601',
       'htc_desire_626',
       'htc_desire_510',
       'htc_desire_620',
       'htc_inspire_4g',
       'htc_one_series',
       'htc_desire_500',
       'htc_desire_eye',
       'htc_desire_610',
       'htc_touch_pro2',
       'htc_desire_600',
       'htc_blue_angel',
       'htc_desire_816',
       'htc_touch_dual',
       'htc_touch_viva',
       'htc_desire_310',
       'htc_desire_300',
       'htc_desire_826',
       'htc_desire_hd',
       'htc_desire_sv',
       'htc_raider_4g',
       'htc_re_camera',
       'htc_touch_pro',
       'htc_desire_c',
       'htc_desire_x',
       'htc_one_mini',
       'htc_desire_v',
       'htc_amaze_4g',
       'htc_desire_s',
       'htc_u_series',
       'htc_7_mozart',
       'htc_7_trophy',
       'htc_touch_hd',
       'htc_desire_z',
       'htc_titan_ii',
       'htc_touch_3g',
       'htc_one_m9+',
       'htc_evo_4g+',
       'htc_one_max',
       'htc_u_ultra',
       'htc_hd_mini',
       'htc_one_e9+',
       'htc_tytn_ii',
       'htc_one_x9',
       'htc_one_a9',
       'htc_one_m9',
       'htc_evo_4g',
       'htc_one_vx',
       'htc_evo_3d',
       'htc_u_play',
       'htc_max_4g',
       'htc_one_x',
       'htc_one_v',
       'htc_7_pro',
       'htc_one_s'],
 'e': ['hteiktin_ma_lat', 'htet_htet_htun', 'htet_phyo_wai'],
 'h': ['hth-xre_rna_motif'],
 'i': ["htin_kyaw's_cabinet",
       'htihlaing_of_prome',
       'hti_factory_fire',
       'htike_htike_aung',
       'htin_linn_aung'],
 'm': ['htms_phutthayotfa_chulalok',
       'htms_bhumibol_adulyadej',
       'htms_makut_rajakumarn',
       'htms_chakri_naruebet',
       'html_working_group',
       'htms_sri_ayudhya',
       'html5_file_api'],
 'o': ['htoo_khant_lwin', 'htoo_ein_thin'],
 's': ['hts_teologiese_studies'],
 't': ['http_persistent_connection',
       'http_parameter_pollution',
       'http/1.1_upgrade_header',
       'http_response_splitting',
       'http_request_smuggling',
       'http_header_injection',
       'http_live_streaming',
       'http/2_server_push',
       'http_message_body',
       'http_client_hints',
       'http_file_server',
       'http_post_flood'],
 'u': ['htun_naung_sint', 'htun_eaindra_bo', 'htun_htun_oo'],
 'v': ['htv_oscar_c']}
