
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_q_ = {'_': ['q+/papias_hypothesis',
       'q._palustris',
       'q101_chicago',
       'q._gracilis',
       'q3_academy',
       'q2_stadium',
       'q._serrata',
       'q-1_visa',
       'q._wang',
       'q1_mall'],
 'a': ["q'anjobalan_languages",
       "q'anjob'al_language",
       "q'anjob'al_people",
       "q'atawi_qullu",
       "q'awiri_qullu",
       "q'ara_willk'i",
       "q'ara_wayuna",
       'q&a_software',
       "q'ara_qullu",
       "q'asa_pata",
       'q_awards'],
 'b': ['q-bessel_polynomials', 'q@b@l@_muskurlu', 'q.b._cooler', 'q_band'],
 'c': ['q-charlier_polynomials',
       'q-chastic_ep',
       'q_clearance',
       'q_centauri',
       'q_carinae',
       'q_casino',
       'q_center',
       'q_cycle',
       'q_cygni',
       'q_class',
       'q_camp',
       'q_code',
       'q_car'],
 'd': ['q-difference_polynomial',
       'q@dirli,_masally',
       'q@dili,_qubadli',
       'q@dili,_samukh',
       'q@dirli,_tovuz',
       'q_division'],
 'e': ['q-exponential_distribution',
       'q-expansion_principle',
       "q'eqchi'_language",
       'q_entertainment',
       'q_eridani'],
 'f': ['q_factor', 'q_fever'],
 'g': ['q-gaussian_distribution', 'q-gaussian_process', 'q-gamma_function'],
 'h': ['q@hr@manli,_beylagan',
       'q-hahn_polynomials',
       'q@hr@manli,_barda',
       'q_hayashida'],
 'i': ["q'illu_suchusqa",
       "q'illu_apachita",
       "q'illu_pachaka",
       "q'illu_q'asa",
       "q'illu_salli",
       "q'illu_qisqa",
       "q'inqu_mayu",
       "q'illu_urqu",
       'q_is'],
 'j': ['q-jacobi_polynomials'],
 'k': ['q-krawtchouk_polynomials', 'q-konhauser_polynomials'],
 'l': ['q-laguerre_polynomials', 'q@l@bin,_mistan', 'q_lazzarus'],
 'm': ['q-meixner-pollaczek_polynomials',
       'q-meixner_polynomials',
       'q-mac_electronics',
       'q_methodology',
       'q_multiplier',
       'q_monthly',
       'q_meter'],
 'n': ['q_news'],
 'o': ["q'orianka_kilcher"],
 'p': ['q-pochhammer_symbol',
       'q-par_angus',
       'q_project',
       'q_planes',
       'q_puppis'],
 'q': ['q-q_plot'],
 'r': ['q-racah_polynomials',
       'q@ribli,_agdash',
       'q@rv@nd,_fuzuli',
       'q@rv@nd,_agdam',
       'q@ribli,_tovuz',
       'q_radio'],
 's': ['q.s._serafijn',
       'q_scorpii',
       'q_source',
       'q_school',
       'q_series',
       'q_score',
       'q_sharp',
       'q_star',
       'q_sort'],
 't': ['q-tip_discography',
       'q-theta_function',
       'q-type_asteroid',
       'q_theatre',
       'q_texture',
       'q-tee_spy',
       'q_tour',
       'q_tv'],
 'u': ["q'umir_pata", "q'uwa_qullu", "q'uwa_laki"],
 'v': ['q-vandermonde_identity', 'q_velorum', 'q_value'],
 'w': ['q-weibull_distribution', 'q_wave', 'q_who'],
 'y': ['q-york'],
 'z': ['q@zli,_sabirabad', 'q@zli,_ismailli', 'q@zyan,_qubadli']}
