
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_iq = {'_': ['iq_classification',
       'iq_imbalance',
       'iq_analytics',
       'iq_aurigae',
       'iq_sapuri',
       'iq_award',
       'iq_151'],
 'a': ['iqaluit_kangiqtunga',
       'iqaluit_airport',
       'iqaluit_centre',
       'iqaluit_east',
       'iqaluit_west'],
 'b': ['iqbal_al-gharaballi',
       'iqbal_kuttippuram',
       'iqbal_al-qazwini',
       'iqbaal_ramadhan',
       'iqbal_muhammad',
       'iqbal_geoffrey',
       'iqbal_sikander',
       'iqbal_chaudhri',
       'iqbal_sacranie',
       'iqbal_siddiqui',
       'iqbal_kashmiri',
       'iqbal_mohammed',
       'iqbal_abdulla',
       'iqbal_mehmood',
       'iqbal_hossain',
       'iqbal_bhatkal',
       'iqbal_mahmood',
       'iqbal_hussain',
       'iqbal_durrani',
       'iqbalur_rahim',
       'iqbal_assegaf',
       'iqbal_qureshi',
       'iqbal_college',
       'iqbal_stadium',
       'iqbal_qaiser',
       'iqbal_mahmud',
       'iqbal_shaikh',
       'iqbal_haider',
       'iqbal_sheikh',
       'iqbal_ashhar',
       'iqbal_manzil',
       'iqbal_arshad',
       'iqbal_narain',
       'iqbal_zuberi',
       'iqbal_akhund',
       'iqbal_review',
       'iqbal_suhimi',
       'iqbal_mirchi',
       'iqbal_baraka',
       'iqbal_naseer',
       'iqbal_quadir',
       'iqbal_wahhab',
       'iqbal_suhail',
       'iqbal_tikka',
       'iqbal_surve',
       'iqbal_kazmi',
       'iqbal_mehdi',
       'iqbal_athas',
       'iqbal_ahmed',
       'iqbal_qadri',
       'iqbal_samad',
       'iqbal_theba',
       'iqbal_singh',
       'iqbal_qasim',
       'iqbal_nagar',
       'iqbal_masih',
       'iqbal_azeem',
       'iqbal_bahu',
       'iqbal_umar',
       'iqbal_riza',
       'iqbal_town',
       'iqbal_imam',
       'iqbal_raad',
       'iqbal_khan',
       'iqbal_bano',
       'iqbal_butt',
       'iqbal_mian',
       'iqbal_azad',
       'iqbal_day'],
 'c': ['iqcb1', 'iqce', 'iqc'],
 'e': ['iqer', 'iqe'],
 'f': ['iqfoil'],
 'g': ['iqgap1', 'iqgap2'],
 'h': ['iqhiya_collective'],
 'i': ['iqinvision', 'iqiyi'],
 'l': ['iqlim_al-kharrub', 'iqlas_naha'],
 'm': ['iqmik', 'iqms', 'iqm'],
 'n': ['iqnavigator', 'iqnovate'],
 'o': ['iqon_technologies', 'iqor_getman'],
 'q': ['iqqur_ipus'],
 'r': ['iqra_university',
       'iqraam_rayners',
       'iqra_academy',
       'iqram_dinzly',
       'iqram_rifqi',
       'iqra_rasool',
       'iqra_khalid',
       'iqra_ahmed',
       'iqra_aziz'],
 's': ['iqsec2', 'iqsec1', 'iqsec3', 'iqs'],
 't': ['iqtisaduna', 'iqtell', "iqta'", 'iqt'],
 'u': ['iquezang_kor.rungthanakeat',
       'iquiracetima_brachialis',
       'iquiracetima_tuberosa',
       'iquiracetima_aspasia',
       'iquiracetima_cerari',
       'iquitos_gnatcatcher',
       'iquiracetima_rana',
       'iquitos_district',
       'iquiri_formation',
       'iquique_province',
       'iquito_language',
       'iquiara_tuiuca',
       'iquitos_varzea',
       "iquan's_party",
       'iquique_cove',
       'iqua_colson',
       'ique_player'],
 'v': ['iqvia'],
 'w': ['iqwinder_gaheer']}
