
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zg = {'_': ['zg_convoys', 'zg_mobili'],
 'a': ['zgagowo-wies', 'zgardesti', 'zgalisce', 'zganci'],
 'b': ['zgb'],
 'c': ['zgc_group'],
 'e': ['zgerdhesh', 'zge-fm'],
 'f': ['zgf_architects'],
 'g': ['zgg'],
 'h': ['zgharta_district', 'zghurivka_raion'],
 'i': ['zgierz_county'],
 'l': ['zgleczewo_szlacheckie',
       'zgleczewo_panienskie',
       'zgliczyn_witowy',
       'zglenice_duze',
       'zglenice_male',
       'zglinna_duza',
       'zglinna_mala'],
 'n': ['zgnily_gluszynek', 'zgnila_struga', 'zgnile_bloto'],
 'o': ['zgoda,_swietochlowice',
       'zgodovinski_casopis',
       'zgornja_kostrivnica',
       'zgornji_petelinjek',
       'zgornje_prebukovje',
       'zgornje_grusovlje',
       'zgornja_javorsica',
       'zgornje_gruskovje',
       'zgornja_zadobrova',
       'zgornji_kamenscak',
       'zgornje_mladetice',
       'zgornja_jablanica',
       'zgorigrad_nunatak',
       'zgornje_praprece',
       'zgornja_polskava',
       'zgornja_volicina',
       'zgornja_scavnica',
       'zgornje_dobrenje',
       'zgornja_senarska',
       'zgornji_pokstajn',
       'zgornji_gasteraj',
       'zgornje_gradisce',
       'zgornja_slivnica',
       'zgorzelec_county',
       'zgornja_pristava',
       'zgornje_jezersko',
       'zgornji_velovlek',
       'zgornji_leskovec',
       'zgornje_grusovje',
       'zgornja_bistrica',
       'zgornji_gabernik',
       'zgornje_pobrezje',
       'zgornja_breznica',
       'zgornje_poljcane',
       'zgornje_gameljne',
       'zgornji_zerjavci',
       'zgornje_partinje',
       'zgornje_konjisce',
       'zgornje_pirnice',
       'zgornja_jevnica',
       'zgornji_prhovec',
       'zgornje_stranje',
       'zgornja_pohanca',
       'zgornja_radovna',
       'zgornje_verjane',
       'zgornje_duplice',
       'zgornji_tustanj',
       'zgornje_negonje',
       'zgornja_hrusica',
       'zgornja_kungota',
       'zgornje_slemene',
       'zgornja_backova',
       'zgornja_vizinga',
       'zgornja_hajdina',
       'zgornje_jablane',
       'zgornje_palovce',
       'zgornja_selnica',
       'zgornja_loznica',
       'zgornja_lipnica',
       'zgornje_skofije',
       'zgornja_rocica',
       'zgornje_tinsko',
       'zgornje_duplje',
       'zgornja_senica',
       'zgornji_kaselj',
       'zgornja_gorica',
       'zgornje_vetrno',
       'zgornja_orlica',
       'zgornje_secovo',
       'zgornji_kocjan',
       'zgornje_vrtice',
       'zgornja_recica',
       'zgornje_koseze',
       'zgornje_vodale',
       'zgornje_bitnje',
       'zgornja_sorica',
       'zgornje_hlapje',
       'zgornji_razbor',
       'zgornji_motnik',
       'zgornji_tuhinj',
       'zgornji_prekar',
       'zgornji_porcic',
       'zgornja_korena',
       'zgornji_duplek',
       'zgornje_danje',
       'zgornji_obrez',
       'zgornja_draga',
       'zgornja_velka',
       'zgornja_sveca',
       'zgornja_kapla',
       'zgornji_brnik',
       'zgornje_gorje',
       'zgornji_okrog',
       'zgornja_siska',
       'zgornje_selce',
       'zgornji_hotic',
       'zgornji_cacic',
       'zgornje_gorce',
       'zgornje_hoce',
       'zgornje_loke',
       'zgornji_otok',
       'zgornja_lusa',
       'zgornje_roje',
       'zgornje_laze',
       'zgornja_bela',
       'zgornji_log',
       'zgornji_boc'],
 'p': ['zgpax_s5'],
 'r': ['zgrzebichy', 'zgrade', 'zgrf1'],
 's': ['zgs_communications'],
 'u': ['zgurovo', 'zgurita'],
 'v': ['zgv']}
