
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mz = {'_': ['mz_skorpion',
       'mz_pictures',
       'mz_puppis',
       'mz._hyde',
       'mz_1000s',
       'mz_kiss',
       'mz_1',
       'mz_3'],
 'a': ['mzab-wargla_languages',
       'mzayifani_buthelezi',
       'mzalendo_kibunjia',
       'mzaar_kfardebian',
       'mzamiru_yassin',
       'mzansi_account',
       'mzamo_majola',
       'mzansi_magic',
       'mzansi_tour',
       'mzab_gundi'],
 'b': ['mzbel', 'mzb1', 'mzb'],
 'd': ['mzdowiec', 'mzdowko', 'mzdowo'],
 'e': ['mzetchabuk_jaqeli', 'mzee_kaukungwa', 'mzee_chillo', 'mze_tv'],
 'f': ['mzf1-as1', 'mzf1', 'mzf'],
 'g': ['mzgee'],
 'h': ['mzhavanadze'],
 'i': ['mzikayifane_khumalo',
       'mzikayise_mashaba',
       'mzilikazi_khumalo',
       'mzimuni,_zimbabwe',
       'mzieme_language',
       'mzimba_district',
       'mzingwane_river',
       'mzimvubu_river',
       'mzimnene_river',
       'mzingwane_dam',
       'mzima_springs',
       'mzi_khumalo',
       'mzia_todua',
       'mzi_mahola'],
 'k': ['mzkt-74135', 'mzkt-79221', 'mzkt-6922', 'mzkt-7930', 'mzkt'],
 'm': ['mzm'],
 'n': ['mzn'],
 'o': ['mzoura,_morocco',
       'mzolisi_yoyo',
       'mzonke_poni',
       'mzonke_fana',
       'mzo_dyantyi'],
 'p': ['mzp'],
 't': ['mzt'],
 'u': ['mzuvukile_matomela',
       'mzumbe_university',
       'mzuzu_university',
       'mzukisi_sikali',
       'mzuzu_academy',
       'mzuzu_airport',
       'mzuvukile_tom',
       'mzungu_kichaa',
       'mzukisi_qobo'],
 'v': ['mzvee'],
 'w': ['mzwandile_ndzimandze',
       'mzwandile_makwayiba',
       'mzwandile_ngubeni',
       'mzwanele_nyhontso',
       'mzwandile_masina',
       'mzwandile_stick',
       'mzwandile_mamba',
       'mzwakhe_sibisi',
       'mzwanele_zito',
       'mzwakhe_mbuli',
       'mzwakhe_nkosi'],
 'y': ['mzymta', 'mzy']}
