
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mk = {'_': ['mk_publishers',
       'mk_nobilette',
       'mk3_grenade',
       'mk_electric',
       'mk_airlines',
       'mk_capital',
       'mk_balaji',
       'mk_metro',
       'mk_group',
       'mk_ultra',
       'mk_guth',
       'mk-v_ar',
       'mk_f.c.',
       'mk_indy',
       'mk_pop',
       'mk_one',
       'mk_20'],
 'a': ['mkalama_district',
       'mkamzee_mwatela',
       'mkabayi_kajama',
       'mkapa_bridge',
       'mkama_ndume'],
 'b': ['mkb_raduga', 'mkb_fakel', 'mkb_bank'],
 'c': ['mkc_networks'],
 'd': ['mkdir', 'mkd'],
 'e': ['mke_kirikkalespor',
       'mke_ankaragucu',
       'mke_jng-90',
       'mke_tamgec',
       'mke_mpt'],
 'f': ['mkfancy', 'mkfc', 'mkfs'],
 'g': ['mkg_group'],
 'h': ['mkhitar_mnatsakanyan',
       'mkhitar_hayrapetyan',
       'mkhanyiseli_siwahla',
       'mkhitar_djrbashian',
       'mkhitar_sebastatsi',
       'mkhuleko_hlengwa',
       'mkhuphali_masuku',
       'mkhitar_manukyan',
       'mkhitar_sparapet',
       'mkhitar_heratsi',
       'mkhululi_bhebhe',
       'mkhululi_nyathi',
       'mkhululi_calana',
       'mkhuseli_jack',
       'mkhitar_gosh'],
 'i': ['mkinga_district'],
 'j': ['mkj'],
 'k': ['mkks'],
 'l': ['mklivecd', 'mklinux', 'mkleo', 'mkl1', 'mkl2', 'mkl'],
 'm': ['mkm_aboobakar', 'mkm_stadium', 'mkm_steel'],
 'n': ['mknk1', 'mknk2', 'mknk', 'mkn'],
 'o': ['mkomazi,_tanzania'],
 'p': ['mkpat-enin', 'mkpanghi', 'mkpani', 'mkp'],
 'q': ['mkq'],
 'r': ['mkrtich_beshiktashlian',
       'mkrtich_hovhannisyan',
       'mkrtich_arzumanyan',
       'mkrtich_gardashian',
       'mkrtich_avetisian',
       'mkrtich_mazmanian',
       'mkrtich_achemian',
       'mkrtich_khrimian',
       'mkrtich_naghash',
       'mkristo_bruce',
       'mkrtich_armen'],
 's': ['mks_trzebinia-siersza',
       'mks_instruments',
       'mks_przasnysz',
       'mks_kluczbork',
       'mks_x/server',
       'mks_toolkit',
       'mks_kalisz',
       'mks_bedzin',
       'mks_lublin',
       'mks_inc.',
       'mks_vir'],
 't': ['mktbt_mine', 'mkt_trail'],
 'u': ['mkuranga_district',
       'mkunde_chachage',
       'mkulumuzi_river',
       'mkushi_district',
       'mkushi_north',
       'mkushi_south',
       'mkuzu_river'],
 'v': ['mkvtoolnix', 'mkv'],
 'w': ['mkwakwani_stadium'],
 'x': ['mkx'],
 'y': ['mky'],
 'z': ['mkz']}
