
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_np = {'_': ['np-intermediate',
       'np-completeness',
       'np300e5a-a01ub',
       'np-equivalent',
       'np-hardness',
       'np-chart',
       'np/poly',
       'np-easy',
       'np-40',
       'np-18'],
 'a': ['npapi',
       'npas2',
       'npas3',
       'npas1',
       'npas',
       'npat',
       'npap',
       'npac',
       'npa'],
 'b': ['npbl'],
 'c': ['npc1l1', 'npca', 'npc1', 'npcc', 'npc'],
 'd': ['npdpa', 'npdc1', 'npda', 'npd'],
 'e': ['npepps', 'npes', 'npe'],
 'f': ['npfl', 'npf'],
 'g': ['npg'],
 'h': ['nphp4', 'nphs2', 'nphp1', 'nphp3', 'nphs', 'nph'],
 'i': ['npin', 'npic', 'npiv', 'npis', 'npi'],
 'j': ['npj'],
 'l': ['nploc4', 'npl'],
 'm': ['npm3', 'npmd', 'npma', 'npm1', 'npm'],
 'n': ['npn'],
 'o': ['npower', 'npoess', 'npo'],
 'p': ['nppa-as1', 'nppa', 'nppd', 'nppc', 'npp'],
 'r': ['nprl3',
       'nprl2',
       'npr-1',
       'npr3',
       'nprt',
       'npr1',
       'npra',
       'npri',
       'npr2',
       'npr'],
 's': ['nps.42.ns.7524',
       'nps.42.ns.2780',
       'nps-2143',
       'npsol',
       'npsa',
       'npsg',
       'npsl',
       'npss',
       'nps'],
 't': ['nptxr', 'nptx1', 'nptx2', 'nptn', 'npta', 'nptc', 'npt'],
 'u': ['npu'],
 'v': ['npv'],
 'w': ['npws', 'npw'],
 'y': ['npy'],
 'z': ['npz']}
