
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dd = {'_': ['dd-carboxypeptidase',
       'dd-transpeptidase',
       'dd-peptidase',
       'dd.43.q.879',
       'dd.43.t.139',
       'dd/mm/yyyy',
       'dd-wrt',
       'dd172',
       'dd-15',
       'dd2',
       'dd3',
       'dd1',
       'dd7'],
 'a': ['ddareungi', 'ddamage', 'ddauto', 'ddakji', 'ddaip', 'dda'],
 'b': ['ddb2', 'ddb1', 'ddb'],
 'c': ['ddc-i', 'ddc'],
 'd': ['ddd'],
 'e': ['ddef2', 'ddebo', 'ddef1', 'ddex', 'dde'],
 'f': ['ddf'],
 'g': ['ddg'],
 'h': ['ddh'],
 'i': ['ddishtv', 'ddit4l', 'ddit4', 'ddis', 'ddi1', 'ddi'],
 'j': ['ddj1'],
 'k': ['ddk'],
 'l': ['ddl'],
 'm': ['ddmashen', 'ddmasar', 'ddm'],
 'n': ['ddn'],
 'o': ['ddos-guard', 'ddobjects', 'ddost', 'ddot', 'ddoc', 'ddo'],
 'p': ['ddp-24', 'ddpcr', 'ddpo', 'ddps', 'ddp'],
 'r': ['ddr-bestenermittlung',
       'ddr-oberliga',
       'ddrescue',
       'ddr-liga',
       'ddrum',
       'ddr2',
       'ddre',
       'ddrc',
       'ddr1',
       'ddr'],
 's': ['dds'],
 't': ['ddt-dehydrochlorinase', 'ddtv', 'ddt'],
 'u': ['dduallt', 'ddumba', 'ddub', 'ddu'],
 'w': ['ddwg', 'ddw'],
 'x': ['ddx19b',
       'ddx27',
       'ddx52',
       'ddx53',
       'ddx39',
       'ddx59',
       'ddx20',
       'ddx10',
       'ddx47',
       'ddx24',
       'ddx3y',
       'ddx3x',
       'ddx21',
       'ddx46',
       'ddx23',
       'ddx56',
       'ddx41',
       'ddx17',
       'ddx43',
       'ddx50',
       'ddx42',
       'ddx11',
       'ddx31',
       'ddx5',
       'ddx6',
       'ddx1',
       'ddx'],
 'y': ['ddy'],
 'z': ['ddz']}
