"""
    ExplainaBoard

    Backend APIs for ExplainaBoard  # noqa: E501

    The version of the OpenAPI document: 0.2.1
    Contact: explainaboard@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import explainaboard_api_client
from explainaboard_api_client.model.system_info_source_tokenizer import SystemInfoSourceTokenizer


class TestSystemInfoSourceTokenizer(unittest.TestCase):
    """SystemInfoSourceTokenizer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemInfoSourceTokenizer(self):
        """Test SystemInfoSourceTokenizer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SystemInfoSourceTokenizer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
