
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-23T10:49:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "33a97badf20f707db036dbf7f32c607e1b4db0d0",
 "version": "4.0.42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
