
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oa = {'_': ['oa-rove', 'oa-4'],
 'a': ['oaa'],
 'b': ['oabdius', 'oab'],
 'c': ['oachirakali', 'oachira', 'oac'],
 'd': ['oadby', 'oades', 'oad'],
 'e': ['oae'],
 'f': ['oafc', 'oaf'],
 'g': ['oag'],
 'h': ['oahuan', 'oahu', 'oahp', 'oahs', 'oah'],
 'i': ['oaister', 'oai'],
 'j': ['oaj'],
 'k': ['oaklandazulasylum',
       'oakville--milton',
       'oakdene/waldene',
       'oakfordbridge',
       'oakman-hertel',
       'oakerthorpe',
       'oakenclough',
       'oaklandish',
       'oakengates',
       'oakforest',
       'oaksenham',
       'oakthorpe',
       'oakeshott',
       'oakenshaw',
       'oakington',
       'oakhanger',
       'oakenholt',
       'oakhurst',
       'oakhaven',
       'oakfield',
       'oakcliff',
       'oakville',
       'oakamoor',
       'oakshela',
       'oakleigh',
       'oakworth',
       'oaklands',
       'oakbrook',
       'oakbeams',
       'oakgrove',
       'oakshott',
       'oakstar',
       'oaktown',
       'oakwell',
       'oaklana',
       'oakport',
       'oaklisp',
       'oakdene',
       'oakburn',
       'oakeley',
       'oakford',
       'oakmere',
       'oakhill',
       'oakdale',
       'oakover',
       'oakbank',
       'oakwood',
       'oakham',
       'oakwal',
       'oakton',
       'oakley',
       'oakman',
       'oaksey',
       'oakura',
       'oakes',
       'oakie',
       'oakum',
       'oak3d',
       'oakse',
       'oaken',
       'oake',
       'oaks',
       'oak'],
 'l': ['oallen', 'oal'],
 'm': ['oamishirasato', 'oamaruia', 'oamaru', 'oam'],
 'n': ['oancea', 'oannes', 'oanta', 'oantu', 'oando', 'oanes', 'oandu', 'oan'],
 'o': ['oaonui', 'oao'],
 'p': ['oaphantes', 'oapi', 'oap'],
 'q': ['oaq'],
 'r': ['oardasaurus',
       'oarotrechus',
       'oaristes',
       'oaracta',
       'oarisma',
       'oarfish',
       'oarnet',
       'oarces',
       'oarta',
       'oarba',
       'oarja',
       'oaro',
       'oare',
       'oara',
       'oar'],
 's': ['oasisamerica',
       'oasification',
       'oastler',
       'oasen',
       'oasys',
       'oasl2',
       'oasby',
       'oasix',
       'oasis',
       'oas2',
       'oass',
       'oasl',
       'oas1',
       'oasc',
       'oas3',
       'oasi',
       'oas'],
 't': ['oattathoodhuvan-1854',
       'oathbringer',
       'oathkeeper',
       'oath-bound',
       'oatfield',
       'oatgrass',
       'oatlands',
       'oatcake',
       'oathean',
       'oathlaw',
       'oatmeal',
       'oatway',
       'oatley',
       'oatman',
       'oaten',
       'oates',
       'oatly',
       'oath',
       'oats',
       'oat'],
 'u': ['oauth'],
 'v': ['oav'],
 'w': ['oaw'],
 'x': ['oaxacanthaxia',
       'oaxacania',
       'oaxtepec',
       'oaxaca',
       'oaxal',
       'oaxen',
       'oaxes'],
 'z': ['oaz1', 'oaz2', 'oaz']}
