
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uj = {'_': ['uj_stadium', 'uj_seuteni', 'uj_kelet', 'uj_elore', 'uj_musa', 'uj_szo'],
 'a': ['ujal_hagverdiyev',
       'ujaalaa_raasthaa',
       'ujangsan_station',
       'ujazd,_zgorzelec',
       'ujarma_fortress',
       'ujazdow,_warsaw',
       'ujangram_union',
       'ujazdow_castle',
       'ujar_district',
       'ujala_college',
       'ujaan_ganguly',
       'ujamaa_place',
       'ujae_airport',
       'ujazdow_park',
       'ujan_dudhpur',
       'ujagar_singh',
       'ujazd_gorny',
       'ujazd_dolny',
       'ujaku_akita',
       'uja_tirche',
       'ujan,_iran',
       'ujah_uloko',
       'ujae_atoll',
       'ujan_mas'],
 'b': ['ujbuda_fc'],
 'c': ['ujcsanalos', 'ujcov', 'ujc'],
 'd': ['ujda_chaman'],
 'e': ['ujezdziec_wielki', 'ujezdziec_maly', 'ujelang_atoll', 'ujesh_ranchod'],
 'f': ['ujfeherto', 'ujfm'],
 'h': ['ujh_river'],
 'i': ['ujidanchi-mae_station',
       'ujiyamada_station',
       'ujitoshi_konomi',
       'ujigami_shrine',
       'ujiie_yukihiro',
       'ujiie,_tochigi',
       'ujiie_naotomo',
       'ujir_language',
       'ujiie_station',
       'ujitha_eranga',
       'ujii_yashiro',
       'ujima_radio',
       'ujihiro_iga',
       'uji_station',
       'uji_shrine',
       'uji_tea'],
 'j': ['ujjain-bhopal_passenger',
       'ujjain-indore_passenger',
       'ujjain-nagda_passenger',
       'ujjain-bhopal_section',
       'ujjain-indore_road',
       'ujjain-nagda_memu',
       'ujjaini_mukherjee',
       'ujjayanta_palace',
       'ujjain_simhastha',
       'ujjwala_majumdar',
       'ujjain_division',
       'ujjain_airstrip',
       'ujjaini_express',
       'ujjain_district',
       'ujjal_howladar',
       'ujjayinee_roy',
       'ujjwal_maulik',
       'ujjwal_chopra',
       'ujjal_dosanjh',
       'ujjal_biswas',
       'ujjwal_nikam',
       'ujjwala_raut',
       'ujjal_singha',
       'ujjwal_rana',
       'ujjal_singh',
       'ujjani_dam'],
 'k': ['ujkigyos', 'ujkovice', 'ujkenez', 'ujker'],
 'l': ['ujlaki_family'],
 'm': ['ujma_mala', 'ujma_duza'],
 'n': ['ujnice', 'ujna', 'ujny'],
 'o': ['ujoni_majuli', 'ujo_noguchi'],
 'p': ['ujpest_synagogue', 'ujpesti_mte', 'ujpesti_te', 'ujpest_fc'],
 'r': ['ujrzanow', 'ujronafo'],
 's': ['ujscie_jezuickie'],
 't': ['ujtikos', 'ujtelek'],
 'u': ['ujunwa_okafor',
       'ujung_genteng',
       'uju_marshall',
       'uju_obinya',
       'uju_okeke',
       'uju_ugoka'],
 'v': ['ujvarfalva'],
 'w': ['ujwal_nirgudkar', 'ujwal_ghimire', 'ujwala_nikam', 'ujwal_thapa']}
