
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ek = {'_': ['ek_bhram...sarvagun_sampanna',
       'ek_trianguli_australis',
       'ek_zeller_eisbaren',
       'ek_villain_returns',
       'ek82_handball_club',
       'ek_aur_mahabharat',
       'ek_hazarachi_note',
       'ek_mutthi_aasmaan',
       'ek_engelmann_wien',
       'ek_pashla_bristi',
       'ek_adhuri_kahani',
       'ek_akasher_niche',
       'ek_chutki_aasman',
       'ek_daav_bhutacha',
       'ek_daav_bhatacha',
       'ek_ghar_banaunga',
       'ek_hota_vidushak',
       'ek_din_pratidin',
       'ek_aur_sikander',
       'ek_mutho_roddur',
       'ek_deewaana_tha',
       'ek_haatko_taali',
       'ek_packet_umeed',
       'ek_paheli_leela',
       'ek_thhi_naayka',
       'ek_naya_rishta',
       'ek_kali_muskai',
       'ek_mutho_chabi',
       'ek_nath_dhakal',
       'ek_phaali_rodh',
       'ek_tukro_chand',
       'ek_khondo_jomi',
       'ek_din_achanak',
       'ek_alag_mausam',
       'ek_mini_katha',
       'ek_bura_aadmi',
       'ek_tera_saath',
       'ek_thi_daayan',
       'ek_boond_ishq',
       'ek_sal_getuig',
       'ek_thi_marium',
       'ek_nai_paheli',
       'ek_hasina_thi',
       'ek_tho_chance',
       'ek_hi_raasta',
       'ek_thi_reeta',
       'ek_tha_tiger',
       'ek_hi_maqsad',
       'ek_thi_begum',
       'ek_takar_bou',
       'ek_tha_rusty',
       'ek_thi_larki',
       'ek_baar_kaho',
       'ek_baar_phir',
       'ek_tha_raja',
       'ek_cup_chya',
       'ek_aur_maut',
       'ek_tha_hero',
       'ek_hi_bhool',
       'ek_cup_cha',
       'ek_do_teen',
       'ek_love_ya',
       'ek_sam_ol',
       'ek_sam_an',
       'ek_yi_oun'],
 'a': ['ekaterina_feodorovna_baryatinskaya-dolgorukova',
       'ekambaranathar_temple,_tiruvekambathur',
       'ekambareswarar_temple,_chettikulam',
       'ekaterina_georgiewna_czerniakowska',
       'ekaterina_alekseyevna_dolgorukova',
       'ekaterina_aleksandrovna_vasilieva',
       'ekaterinoslav_bolshevik_uprising',
       'ekaterina_vladimirovna_apraksina',
       'ekambeswarar_temple,_kumbakonam',
       'ekambareswarar_temple,_chennai',
       'ekaterina_mikhailovna_lopatina',
       'ekaterina_ii-class_battleship',
       'ekaterina_sedia_bibliography',
       'ekatarina_velika_discography',
       'ekamai_international_school',
       'ekaterina_petrova_yosifova',
       'ekaterinburg_speleo_club',
       'ekalaka_national_forest',
       'eka_pada_rajakapotasana',
       'eka_pada_shirshasana',
       'ekavuri_amman_temple',
       'ekamra_manoranjan_tv',
       'eka_tjipta_widjaja',
       'ekamath_eka_rateka',
       'ekanem_ikpi_braide',
       'ekam_eco_solutions',
       'ekati_diamond_mine',
       'eka_renaka_kurullo',
       'eka_purnama_indah',
       'ekanath_k._thakur',
       'eka_supria_atmaja',
       'ekala,_sri_lanka',
       'eka_esu_williams',
       'eka_dawasaka_api',
       'eka_malaka_pethi',
       'eka_gei_sokari',
       'eka_peksha_ek'],
 'b': ['ekbalpore_triple_murder', 'ekbar_bolo_bhalobashi'],
 'c': ['ekchari_railway_station'],
 'd': ['ekdara_rural_municipality'],
 'e': ["ekeland's_variational_principle",
       'ekebergparken_sculpture_park',
       'ekebergbanen_rolling_stock',
       'eketahuna_railway_station',
       "ekensund_artists'_colony",
       'ekebergparken_tram_stop',
       'ekenas_railway_station',
       'ekeren_railway_station',
       'ekeby,_upplands_vasby',
       'ekeby_church,_uppland',
       'ekeino_to_kalokairi',
       'ekei_bole_shooting',
       'ekene_emeka_maduka',
       'ekene_dili_chukwu',
       'ekeby,_ska_socken',
       'ekenas_sport_club',
       'ekeines_kai_ego',
       'ekei_essien_oku',
       'ekeby_oak_tree'],
 'h': ['ekhtyiarabad-e_do_ziyarati',
       'ekhtiarabad_rural_district',
       'ekhane_aamar_swarga',
       'ekhane_aakash_neel'],
 'i': ['ekibastuz-kokshetau_high-voltage_line',
       'ekin_cheng_discography',
       'ekiti_state_university',
       'ekin_cheng_filmography',
       'ekitiibwa_kya_buganda',
       'ekis:_walang_tatakas',
       'ekiti_prison_break',
       'ekin_tuncay_turan',
       'ekiti_united_f.c.',
       'ekin_mert_daymaz'],
 'j': ['ekjon_shonge_chilo'],
 'k': ['ekkattuthangal_metro_station',
       'ekkadiki_pothavu_chinnavada',
       'ekkehard_von_kuenssberg',
       'ekkehard_of_huysburg',
       'ekkamai_bts_station',
       'ekkadiki_ee_parugu',
       'ekk_nayi_pehchaan',
       'ekkehard_of_aura',
       'ekk_deewana_tha',
       'ekk_thee_sanam',
       'ekka_raja_rani',
       'ekko_av_ibsen'],
 'l': ['eklakhi-balurghat_branch_line',
       'eklavya_technology_channel',
       'eklavya_sports_stadium',
       'eklipse_sports_radio',
       'eklutna_power_plant',
       'eklil_ahmad_hakimi',
       'ekla_chalo_re'],
 'm': ['ekman_current_meter', 'ekman_water_bottle'],
 'n': ['eknath_prabhakar_ghate', 'eknath_vasant_chitnis'],
 'o': ['ekostrovskoye_rural_community',
       'ekomuseum_nedre_atradalen',
       'ekos_research_associates',
       'ekoji_buddhist_temple',
       'ekolot_jk-05l_junior',
       'ekolot_kr-030_topaz',
       'eko_putro_sandjojo',
       'eko_pradana_putra',
       'ekolot_kr-010_elf',
       'ekofisk_oil_field',
       'eko_pearl_towers',
       'eko_roni_saputra',
       'eko_maulana_ali',
       'eko_yuli_irawan',
       'eko_eko_azarak'],
 'r': ['ekramul_karim_chowdhury',
       "ekrima_sa'id_sabri",
       'ekramul_haque_titu',
       'ekrem_bugra_ekinci'],
 's': ['eksali_forest_land', 'eksisu_picnic_area', 'ekstrom_ice_shelf'],
 't': ['ekti_cinemar_golpo',
       'ekta_jeev_sadashiv',
       'ekti_tarar_khonje',
       'ektu_aalor_khonje',
       'ektaar_music_ltd',
       'ekti_nadir_naam'],
 'u': ['ekukhanyeni_mission_station',
       'ekundayo_adeyinka_adeyemi',
       'ekushey_book_fair'],
 'v': ['ekv_mosfet_model'],
 'w': ['ekwueme_michael_thelwell',
       'ekwan_river_formation',
       'ekwanok_country_club']}
