
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ee = {'_': ['ee_pattanathil_bhootham',
       'ee_nagaraniki_emaindhi',
       'ee_puzhayum_kadannu',
       'ee_parakkum_thalika',
       'ee_bandha_anubandha',
       'ee_thalamura_ingane',
       'ee_varsham_sakshiga',
       'ee_manohara_theeram',
       'ee_ganam_marakkumo',
       'ee_adutha_kaalathu',
       'ee_maaya_peremito',
       'ee_jeeva_ninagagi',
       'ee_vazhi_mathram',
       'ee_kanni_koodi',
       'ee_wembley_cup',
       'ee_tiang_hong',
       'ee_peng_liang',
       'ee_aye_addio'],
 'a': ['eea_joint_committee'],
 'b': ['eeb_allay_ooo!'],
 'd': ['eedle_and_meyers', 'eedu_gold_ehe'],
 'f': ['eefje_de_visser', 'eef_van_breen', 'eef_van_riel'],
 'g': ['eeg_din_connector'],
 'k': ['eek_mountain_formation',
       'eekholt_wildlife_park',
       'eeklo_railway_station',
       'eeklo_yeti_bears',
       'eek,_a_penis!',
       'eek!_the_cat',
       'eeke_van_nes',
       'eek_and_meek'],
 'l': ['eeltsje_hiddes_halbertsma',
       'eeltsje_boates_folkertsma',
       'eelke_jelles_eelkema',
       'eel_pie_publishing',
       'eelco_van_kleffens',
       'eelco_van_asperen',
       'eel_life_history',
       'eel_brook_common',
       'eel_pie_studios',
       'eel_river_tribe',
       'eel_pie_island',
       'eelam_war_iii',
       'eelam_war_iv',
       'eelam_war_ii',
       'eelam_war_i',
       'eel_as_food',
       'eel_ulf_2',
       'eel_ulf_1'],
 'm': ['eemshaven_railway_station',
       'eemmeerdijk_wind_park',
       'eemil_nestor_setala'],
 'n': ['eendrachtsplein_metro_station',
       'een_eerlijk_zeemansgraf',
       'eenam_thettatha_kattaru',
       'eenie_meenie_records',
       'eensy_weensy_monster',
       'een_beetje_verliefd',
       'een_rondje_holland',
       'een_vreemde_liefde',
       'eena_meena_deeka',
       'een_blandt_mange',
       'een_tegen_100'],
 'o': ['eeoc_v._wyoming'],
 'r': ['eersterivier_secondary_school',
       'eerste_pastorie_winburg',
       'eerwah_vale,_queensland',
       'eera_vizhi_kaaviyangal',
       'eero_yrjo_pehkonen',
       'eerik_kumari_award',
       'eero_a._wuori'],
 's': ['eesti_kirjanike_kooperatiiv', 'eesti_otsib_superstaari'],
 'v': ['eeva_riitta_fingerroos'],
 'y': ["eeyore's_birthday_party"]}
