
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ey = {'_': ['ey_guzel_qirim'],
 'a': ['eyarkon_kalikkama_nayanar',
       'eyak_preservation_council',
       'eyarth_railway_station',
       'eyalet_of_adrianople',
       'eyad_abu_abaid',
       'eyale_le_beau',
       'eyal_ben_ami'],
 'b': ['eybakabad_industrial_estate'],
 'c': ['eycott_volcanic_group'],
 'd': ['eydie_in_love'],
 'e': ['eyemouth_transmitting_station',
       'eyebrowed_jungle_flycatcher',
       'eyemouth_lifeboat_station',
       'eyewall_replacement_cycle',
       'eyers_grove,_pennsylvania',
       'eyemouth_railway_station',
       'eyeless_golden-line_fish',
       'eyerly_aircraft_company',
       'eye_central_television',
       'eye_care_professional',
       'eyetoy:_operation_spy',
       'eye_vein_verification',
       'eyewitness_to_history',
       'eyemouth_united_f.c.',
       'eyetoy:_monkey_mania',
       'eyes_upon_separation',
       'eyedea_and_abilities',
       'eyeru_tesfoam_gebru',
       'eye_care_foundation',
       'eye_railway_station',
       'eye_contact_effect',
       'eyes_beyond_seeing',
       'eye_level_learning',
       'eye,_west_virginia',
       'eyes_of_innocence',
       'eye_on_attraction',
       'eye_of_providence',
       'eyes_open,_harry!',
       'eyes,_nose,_lips',
       'eye_spy_magazine',
       'eyes_on_tomorrow',
       'eyes_of_eternity',
       'eye_and_dunsden',
       'eyes_like_yours',
       'eyes_of_mystery',
       'eye_on_malaysia',
       'eyes_of_crystal',
       'eye_of_agamotto',
       'eyeless_in_gaza',
       'eye_against_eye',
       'eyes_for_africa',
       'eyes_open_tour',
       'eye_of_kuruman',
       'eyetoy:_play_3',
       'eye_of_jupiter',
       'eyetoy:_play_2',
       "eyes_don't_lie",
       'eye_of_harmony',
       'eyes_of_terror',
       'eye_of_fashion',
       'eye_gravel_pit',
       'eyes_wide_open',
       'eyes_and_nines',
       'eyes_closed_ep',
       'eyes_of_things',
       'eyes_wide_shut',
       'eye_on_sports',
       'eye_on_juliet',
       'eyes_of_youth',
       'eye_of_heaven',
       'eyes_of_sibiu',
       'eye_health_uk',
       'eyes_of_texas',
       'eyes_of_amber',
       'eyes_love_you',
       'eye_of_gnome',
       'eye_of_horus',
       'eye_on_crime',
       'eyes_of_love',
       'eyes_of_dawn',
       'eyes_of_fate',
       'eyes_of_fire',
       'eyes_on_this',
       'eyes_of_eden',
       'eye_for_eye',
       'eyes_on_you',
       'eye_of_pain',
       'eye_of_doom',
       'eyes_on_me',
       'eye_to_eye',
       'eye_ii_eye',
       'eye_to_ear',
       'eye_of_cat',
       'eye_and_i',
       'eye_on_it',
       'eye_2_eye',
       'eye_of_ra'],
 'g': ['eygelshoven_railway_station', 'eyglo_osk_gustafsdottir'],
 'h': ['eyholz_railway_station'],
 'i': ['eyiah_kyei_baffour'],
 'j': ['eyja-_og_miklaholtshreppur'],
 'l': ['eylul_geldi_sonra', 'eylem_elif_mavis'],
 'm': ['eymundar_thattr_hrings'],
 'n': ['eynesbury_senior_college',
       'eynsford_railway_station',
       'eynabad,_east_azerbaijan',
       'eynsham_railway_station',
       'eynesbury_rovers_f.c.',
       'eynion_de_tilston',
       'eynez_coal_mine',
       'eyn_ol_mejibel',
       'eyn_ol_zaman',
       'eyn_ol_baqar',
       'eyn_ol_rrum',
       'eyn_ol_din',
       'eyn_ol_qas'],
 'o': ['eyo_ephraim_adam',
       'eyo_ekung_inyang',
       'eyo_ating_osung',
       'eyo_esio_usung',
       'eyo_honesty_ii',
       'eyo_esio_osung',
       'eyo_edet_okon'],
 'p': ['eypak_rural_district'],
 'r': ['eyring_research_institute',
       'eyre_developmental_road',
       "eyre's_1839_expeditions",
       'eyre_telegraph_station',
       'eyre_peninsula_railway',
       'eyre_peninsula_tribune',
       'eyre_bird_observatory',
       'eyre_and_spottiswoode',
       'eyre,_south_australia',
       'eyring_science_center',
       'eyre_and_southall',
       'eyre_evans_crowe',
       'eyre_yorke_block',
       'eyre_bus_service',
       'eyre_massey_shaw',
       'eyre_and_munro',
       'eyre_de_lanux'],
 's': ['eysenck_personality_questionnaire',
       'eyshabad,_east_azerbaijan',
       'eystrup_railway_station'],
 't': ['eythor_ingi_gunnlaugsson',
       'eythorne_railway_station',
       'eythorne_baptist_church',
       'eyton_on_severn'],
 'u': ['eyup_sabri_hayirlioglu',
       'eyuboglu_high_school',
       'eyup_sultan_mosque',
       'eyup_sabri_akgol'],
 'v': ['eyvanki_industrial_estate',
       'eyvanki_rural_district',
       'eyvind_fjeld_halvorsen',
       'eyvindur_p._eiriksson',
       'eyvind_w._wang'],
 'y': ['eyyub_sultan_mosque',
       'eyyal_burial_cave',
       'eyyup_hasan_ugur',
       'eyyvah_eyvah_3',
       'eyyvah_eyvah_2']}
