
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vu = {'_': ['vu_quang_district',
       "vu_de_l'exterieur",
       'vu_western_spurs',
       'vu_ban_district',
       'vu_thu_district',
       'vu_giang_huong',
       'vu_trong_phung',
       'vu_cong_tuyen',
       'vu_hoang_diep',
       'vu_ngoc_thinh',
       'vu_thu_phuong',
       'vu_xuan_cuong',
       'vu_bich_huong',
       'vu_hong_khanh',
       "vu_d'un_chien",
       'vu_ngoc_dinh',
       'vu_minh_tuan',
       'vu_minh_hieu',
       'vu_van_thanh',
       'vu_quang_nam',
       'vu_thi_huong',
       'vu_nhu_thanh',
       'vu_the_vuong',
       'vu_thi_nhung',
       'vu_ngoc_phan',
       'vu_cat_tuong',
       'vu_thi_trang',
       'vu_hong_quan',
       'vu_dinh_long',
       'vu_duc_trung',
       'vu_van_danh',
       'vu_hoang_my',
       'vu_van_dung',
       'vu_van_giai',
       'vu_anh_tuan',
       'vu_van_nham',
       'vu_thanh_an',
       'vu_van_ninh',
       'vu_ngoc_nha',
       'vu_cao_dam',
       'vu_duc_dam',
       'vu_quoc_uy',
       'vu_thi_men',
       'vu_dan_tan',
       'vu_van_mau',
       'vu_ha_anh'],
 'a': ['vuai_abdallah_khamis'],
 'b': ['vub_night_frog'],
 'c': ['vucipolje,_zadar_county', 'vucedol_culture_museum'],
 'd': ['vudal_gazelle_f.c.'],
 'e': ['vuelta_ciclista_chiapas',
       'vuelta_a_cundinamarca',
       'vuelta_grande_airport',
       'vuelta_mexico_telmex',
       'vuelta_a_extremadura',
       'vuelta_a_chihuahua',
       'vuelta_a_andalucia',
       'vuelta_a_venezuela',
       'vuelta_del_uruguay',
       'vuelta_a_antioquia',
       'vuelta_a_guatemala',
       'vuelta_a_cantabria',
       'vuelva_el_primero',
       'vuelta_a_tenerife',
       'vuelta_a_colombia',
       'vuelta_al_ecuador',
       'vuelveme_a_querer',
       'vuelta_a_mallorca',
       'vuelta_a_paraguay',
       'vuelta_al_tachira',
       'vuelta_a_bolivia',
       'vuelta_a_navarra',
       'vuelta_a_burgos',
       'vuelta_de_jorco',
       'vuelta_a_boyaca',
       'vuelve_candy_b.',
       'vuelta_a_espana',
       'vuelta_a_aragon',
       'vue_harbor_east',
       'vuelta_a_murcia',
       'vue_at_brickell',
       'vuelvo_a_verte',
       'vuelta_a_peru',
       'vue_des_alpes',
       'vuelta_a_cuba',
       'vue_west_end',
       'vue_pa_chay',
       'vuelvo_a_ti',
       'vue_de_lac'],
 'f': ['vufflens-la-ville_railway_station'],
 'g': ['vught_railway_station'],
 'h': ['vuhlehirska_power_station'],
 'i': ['vui_clarence_nelson', 'vui_florence_saulo'],
 'k': ['vuka,_osijek-baranja_county',
       'vukovar_children_massacre',
       'vukoslavic_noble_family',
       'vukovic_printing_house',
       'vukovar_film_festival',
       'vukovar,_jedna_prica',
       'vukovar_water_tower',
       'vukasin_of_serbia',
       'vukan_r._vuchic',
       'vukan_of_serbia'],
 'l': ['vulnerability_assessment_laboratory',
       'vulvar_intraepithelial_neoplasia',
       'vulnerabilities_equities_process',
       'vulkanwerft_concentration_camp',
       'vulnerability_discovery_model',
       'vulamehlo_local_municipality',
       'vulvar_childhood_pemphigoid',
       'vulcan_capital_management',
       'vulture_street,_brisbane',
       'vulcan_materials_company',
       'vulkanland_eifel_geopark',
       "vulcana_women's_circus",
       "vulvar_crohn's_disease",
       'vulture_city,_arizona',
       'vultee_a-31_vengeance',
       'vulcan,_west_virginia',
       'vultee_xp-68_tornado',
       'vultee_p-66_vanguard',
       'vultee_bt-13_valiant',
       'vultum_dei_quaerere',
       'vulcan_street_plant',
       'vulcan_nerve_pinch',
       'vulcan_gas_company',
       'vulcanus_in_japan',
       'vulcan_iron_works',
       'vulcan_coal_mine',
       'vulture_sand_eel'],
 'n': ['vunadidir-toma_rural_llg',
       'vundela_malakonda_reddy',
       'vundavalli_aruna_kumar',
       'vunnadhi_okate_zindagi',
       'vuntut_national_park',
       'vung_tau_shipwreck',
       'vung_liem_district',
       'vung_tau_airport',
       'vung_tau_charter',
       'vunivalu_of_bau',
       'vung_tau_port',
       'vung_ro_bay'],
 'o': ['vuosaari_sports_ground',
       'vuosaari_metro_station',
       "vuong's_closeness_test",
       'vuong_trung_hieu',
       'vuong_quoc_trung',
       'vuong_thi_huyen',
       'vuong_tien_dung',
       'vuoto_a_perdere',
       'vuong_van_dong',
       'vuong_dinh_hue'],
 'p': ['vuppuluri_ganapathi_sastry'],
 'r': ["vurpillat's_opera_house",
       'vurpar_railway_station',
       'vurpar_branch_line',
       'vurgu_i_ri'],
 's': ['vusamazulu_credo_mutwa', 'vuslat_dogan_sabanci', 'vus,_crna_trava'],
 't': ['vutukuru_rami_reddy'],
 'z': ['vuzlove,_lviv_oblast']}
