
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ik = {'_': ['ik_investment_partners',
       'ik_columbia_vanersborg',
       'ik_uppsala_fotboll',
       'ik_ostria_lambohov',
       'ik_sirius_fotboll',
       'ik_tellus_bandy',
       'ik_huge_bandy',
       'ik_grand_bodo'],
 'a': ['ikazuchi-class_destroyer_escort',
       'ikatan_naturopatis_indonesia',
       'ikamvalethu_secondary_school',
       'ikarchala_railway_station',
       'ikaros_kallitheas_b.c.',
       'ika_yuliana_rochmawati',
       'ikapa_sporting_f.c.',
       'ikageng,_north_west',
       'ika_district,_shiga',
       'ikaw_ang_pag-ibig',
       'ikaw_ay_pag-ibig',
       'ikar_ai-10_ikar',
       'ika,_akwa_ibom',
       'ika_north_east',
       'ikarus_aero_2',
       'ika-6_na_utos',
       'ikaw_na_sana',
       'ikaw_ay_akin'],
 'b': ['ikb_deutsche_industriebank', 'ikbal_el_alaily', 'ikbal_ali_shah'],
 'c': ['ikco_ef_engines'],
 'e': ['ikechukwu_francis_okoronkwo',
       'ikebukuro_nishiguchi_park',
       'ikersuaq,_east_greenland',
       'ikenoura_seaside_station',
       'ikeathy_and_oughterany',
       'ike_turner_discography',
       'ikenwoli_godfrey_emiko',
       'iker_pajares_bernabeu',
       'iken_scientifica_2008',
       'ike_kligerman_barkley',
       'ikenna_stars_academy',
       'ike_franklin_andrews',
       'ikenai_luna_sensei!',
       'ike_skelton_bridge',
       'ike_reighley_house',
       'ikeja_bus_terminal',
       'ikervar_wind_farm',
       'ikere_gorge_dam',
       'ike_walton_lake',
       'ikeja_city_mall',
       'ikemen_desu_ne',
       'ikenie_no_yoru',
       'ike_van_zandt',
       "ike's_wee_wee",
       'ike_no_taiga'],
 'h': ["ikhtiyar_ma'rifat_al-rijal",
       'ikhtiyaruddin_ghazi_shah',
       'ikhtiyar_al-din_ai-taq',
       'ikhtiar_wali_khan'],
 'i': ['iki-tsushima_quasi-national_park',
       'ikinci_alib@yli,_zangilan',
       'ikiztepe_oil_field',
       'iki_no_hakatoko',
       'iki_mo_dekinai',
       'iki_genc_kiz'],
 'k': ['ikkitousen_deathmatch_survivor',
       'ikken_rakuchaku_goyoujin',
       'ikkitousen_strong_climb',
       'ikke_pe_ikka'],
 'o': ['ikorongo_game_reserve',
       'ikon_office_solutions',
       'ikogosi_warm_springs',
       'ikon_arts_foundation',
       'ikoma_district,_nara',
       'ikorodu_united_f.c.',
       'ikot_inyang,_etinan',
       'ikot_akpan_essien',
       'ikot_onwon_ediene',
       'ikot_inyang,_eket',
       'ikoma_cable_line',
       'ikot_ese,_etinan',
       'ikot_obio_inyang',
       'ikot_inyang_osom',
       'iko_the_rainman',
       'ikot_ese,_uruan',
       'ikot_ekpo_okon',
       'ikot_akpa_nkuk',
       'ikot_use_ekong',
       'ikot_akpan_ese',
       'ikot_obio_ata',
       'ikot_udo_adia',
       'ikot_udo_abia',
       'ikot_akpa_esa',
       'ikot_obio_eka',
       'ikot_esen_oku',
       'ikot_udo_oto'],
 'p': ['ikpeazu_memorial_stadium', 'ikpe_umoh_imeh'],
 'r': ['ikramullah_khan_dharejo',
       'ikram_akhtar_films',
       'ikram_ali_malik',
       'ikram_muda_f.c.'],
 's': ['iksan_jewelry_museum', 'iksan_public_stadium'],
 'u': ['ikuei_junior_college',
       'ikuta_ryokuchi_park',
       'ikuze!_kaito_shojo',
       'ikuinyi_o._ibani',
       'ikusa_no_okimi'],
 'w': ['ikwezi_local_municipality']}
