
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fs = {'_': ['fs1_flight_simulator',
       'fs_gelko_hasselt',
       'fs_baix_maestrat',
       'fs_canis_majoris',
       'fs_class_d.445',
       'fs_class_e.380',
       'fs_class_e.470',
       'fs_class_e.621',
       'fs_class_e.402',
       'fs_class_e.632',
       'fs_class_e.471',
       'fs_class_e.360',
       'fs_class_e.424',
       'fs_class_e.550',
       'fs_class_e.626',
       'fs_class_e.420',
       'fs_class_e.431',
       'fs_class_e.333',
       'fs_class_e.220',
       'fs_class_e.405',
       'fs_class_e.403',
       'fs_class_e.414',
       'fs_class_e.430',
       'fs_class_e.412',
       'fs_class_e.421',
       'fs_class_e.646',
       'fs_class_e.330',
       'fs_class_e.656',
       'fs_class_e.326',
       'fs_class_e.332',
       'fs_class_d.341',
       'fs_class_e.331',
       'fs_class_e.320',
       'fs_class_e.428',
       'fs_class_e.464',
       'fs_air_service',
       'fs_class_e.636',
       'fs_class_e.620',
       'fs_class_e.432',
       'fs_class_d.443',
       'fs_class_d.345',
       'fs_class_e.321',
       'fs_class_e.444',
       'fs_la_massana',
       'fs_line_chair',
       'fs_class_170',
       'fs_class_740',
       'fs_class_680',
       'fs_class_470',
       'fs_class_310',
       'fs_class_736',
       'fs_class_420',
       'fs_class_103',
       'fs_class_625',
       'fs_class_670',
       'fs_class_290',
       'fs_class_214',
       'fs_class_691',
       'fs_class_122',
       'fs_class_735',
       'fs_class_480',
       'fs_class_400',
       'fs_class_552',
       'fs_class_746',
       'fs_class_396',
       'fs_class_744',
       'fs_class_600',
       'fs_class_835',
       'fs_class_685',
       'fs_class_745',
       'fs_class_113',
       'fs_class_410',
       'fs_class_910',
       'fs_class_940',
       'fs_class_650',
       'fs_class_737'],
 'a': ['fsa_eligibility_list', 'fsa_debit_card'],
 'b': ['fsb_criminalistics_institute'],
 'c': ['fsc_bukovyna_chernivtsi', 'fscc_early_cash'],
 'e': ['fse_engineering_group'],
 'h': ['fshat_i_ri'],
 'm': ['fsm_national_police'],
 'o': ['fso_syrena_sport', 'fso_syrena_110'],
 'u': ['fsu_homecoming_live'],
 'v': ['fsv_gluckauf_brieske-senftenberg',
       'fsv_union_furstenwalde',
       'fsv_berolina_stralau',
       'fsv_budissa_bautzen',
       'fsv_optik_rathenow',
       'fsv_63_luckenwalde',
       'fsv_gutersloh_2009',
       'fsv_babelsberg_74',
       'fsv_1926_fernwald',
       'fsv_08_bissingen',
       'fsv_frankfurt_ii']}
