
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ef = {'_': ["ef'al",
       'ef-tu',
       'ef-24',
       'ef-ts',
       'ef-g',
       'ef-4',
       'ef50',
       'ef-5',
       'ef86',
       'ef1'],
 'a': ['efavirenz/emtricitabine/tenofovir',
       'efavirenz/lamivudine/tenofovir',
       'efaproxiral',
       'efailnewydd',
       'efalizumab',
       'efavirenz',
       'efanzines',
       'efaktura',
       'efaroxan',
       'efamro',
       'efacec',
       'efail',
       'efate',
       'efaf',
       'efab',
       'efax',
       'efas',
       'efa'],
 'b': ['efbr', 'efb'],
 'c': ['efcab6', 'efcbp2', 'efcc1', 'efcc', 'efca', 'efco', 'efc'],
 'd': ['efda', 'efd'],
 'e': ['efemcukuru',
       'efenechtyd',
       'efestivals',
       'eferding',
       'efeler',
       'efemp2',
       'efetli',
       'efemp1',
       'efecte',
       'eferi',
       'efes',
       'efet',
       'efe'],
 'f': ['effelder-rauenstein',
       'effusibacillus',
       'efferocytosis',
       'efflorescence',
       'efflatounaria',
       'effortfulness',
       'effectiveness',
       'effervescence',
       'effusimentum',
       'effractilis',
       'effenberger',
       'effincourt',
       'efficiency',
       'eff-austin',
       'effeltrich',
       'effeminacy',
       'effleurage',
       'effacement',
       'effiduase',
       'effrinagh',
       'effingham',
       'effiakuma',
       'effington',
       'effusion',
       'effected',
       'effingen',
       'efficacy',
       'effelder',
       'effenaar',
       'effluent',
       'effortel',
       'effector',
       'efferent',
       'effendi',
       'effigia',
       'efferia',
       'efforia',
       'effertz',
       'effetia',
       'effiong',
       'effurun',
       'efflamm',
       'effutu',
       'effect',
       'efflux',
       'effiat',
       'effolo',
       'effron',
       'effigy',
       'effium',
       'effasu',
       'effort',
       'efford',
       'effio',
       'effry',
       'effie',
       'effel',
       'effin',
       'effia',
       'effi',
       'effa',
       'eff'],
 'g': ['efgaming', 'efg'],
 'h': ['efhc2', 'efhc1', 'efhd2', 'efhs', 'efh'],
 'i': ['efinaconazole',
       'efilecabinet',
       'efiaimbalo',
       'efiwe.org',
       'efimenko',
       'efimeris',
       'efigenio',
       'efiewura',
       'efibula',
       'efilm',
       'efini',
       'efird',
       'efika',
       'efigs',
       'efid',
       'efic',
       'efil',
       'efik',
       'efi'],
 'j': ['efjorden'],
 'k': ['efkonindia', 'efkarpia', 'efke', 'efk'],
 'l': ['eflapegrastim',
       'eflornithine',
       'efly-hobby',
       'efloxate',
       'eflani',
       'eflow',
       'efly',
       'eflc',
       'efla',
       'efl'],
 'm': ['efm32', 'efma', 'efmi', 'efm'],
 'n': ['efnysien', 'efnmr', 'efnet'],
 'o': ['efootball.open',
       'efonidipine',
       'efon-alaaye',
       'efootball',
       'efounders',
       'efoulan',
       'efoetsy',
       'efosmo',
       'eforie',
       'efore',
       'efogi',
       'efon',
       'efo'],
 'p': ['efpalio', 'efpa', 'efp'],
 'q': ['efqm'],
 'r': ['efringen-kirchen',
       'efritin.com',
       'efremovite',
       'efrapeptin',
       'efremenkov',
       'efraasia',
       'efront',
       'efrain',
       'efrei',
       'efren',
       'efros',
       'efrat',
       'efron',
       'efrem',
       'efr'],
 's': ['efsh', 'efsi', 'efsd', 'efss', 'efs'],
 't': ['efterslaegten',
       'eftekharabad',
       'efterskole',
       'efterklang',
       'eftekasat',
       'eftekhari',
       'efterlyst',
       'efteling',
       'eftsoons',
       'eftekhar',
       'eftychia',
       'eftihos',
       'eftelot',
       'eftimiu',
       'eftpos',
       'eftud2',
       'eftel',
       'eftim',
       'efts',
       'eftp',
       'eft'],
 'u': ['efungumab', 'efulensia', 'efuse', 'efutu', 'efuru', 'efu'],
 'w': ['efw'],
 'x': ['efxeinoupoli', 'efx'],
 'y': ['efyra', 'efya'],
 'z': ['efzar', 'efze']}
