
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vj = {'_': ['vj_patterson', 'vj_hypnotica', 'vj_search', 'vj_adams', 'vj_andy'],
 'a': ['vjaceslavs_dombrovskis',
       'vjaceslavs_zevnerovics',
       'vjaceslavs_kudrjavcevs',
       'vjaceslavs_stepanenko',
       'vjatseslav_zahovaiko',
       'vjaceslavs_duhanovs',
       'vjaceslavs_giruckis',
       'vjatseslav_divonin',
       'vjaceslavs_isajevs',
       'vjaceslavs_fanduls',
       'vjatseslav_kobrin'],
 'c': ['vjc'],
 'e': ['vjekoslav_rosenberg-ruzic',
       'vjekoslav_paskovic',
       'vjekoslav_servatzy',
       'vjekoslav_vrdoljak',
       'vjekoslav_skrinjar',
       'vjekoslav_zupancic',
       'vjenceslav_richter',
       'vjekoslav_kobescak',
       'vjekoslav_spincic',
       'vjekoslav_bevanda',
       'vjekoslav_babukic',
       'vjekoslav_vrancic',
       'vjekoslav_katusin',
       'vjekoslav_heinzel',
       'vjekoslav_luburic',
       'vjenceslav_novak',
       'vjekoslav_andric',
       'vjekoslav_lokica',
       'vjekoslav_perica',
       'vjekoslav_kramer',
       'vjekoslav_huzjak',
       'vjekoslav_tomic',
       'vjekoslav_klaic',
       'vjekoslav_karas',
       'vjekoslav_bastl',
       'vjekoslav_kaleb',
       'vjekoslav_sutej',
       'vjetrenica_cave',
       'vjekoslav_curic',
       'vjerica_radeta',
       'vjeran_simunic',
       'vjera_mujovic',
       'vjeran_zuppa',
       'vjecna_vatra'],
 'i': ['vjing'],
 'o': ['vjosa_osmani'],
 's': ['vjsm_kelme'],
 'u': ['vjushkovisaurus']}
