
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vc = {'_': ['vc_epicentr-podolyany',
       'vc-10_challengers',
       'vc_barkom-kazhany',
       'vc_uralochka-ntmk',
       'vc_radiotechnik',
       'vc_zenit-kazan',
       'vc_vlissingen',
       'vc_nesselande',
       'vc_belogorie',
       'vc_maaseik',
       'vc_oudegem',
       'vc_leipzig',
       'vc_zellik',
       'vc_barre',
       'vc_baku'],
 'a': ['vca_pictures'],
 'b': ['vcbi', 'vcb'],
 'c': ['vcc-clark_station'],
 'd': ['vcdiff', 'vcdhd', 'vcds'],
 'e': ['vcelnicka', 'vcelakov', 'vcelince', 'vcenter', 'vcelna', 'vce'],
 'f': ['vcfl', 'vcfa', 'vcf'],
 'h': ['vchynice', 'vchelka', 'vchera', 'vchsr', 'vchs', 'vch'],
 'i': ['vci'],
 'l': ['vcloud_air'],
 'm': ['vcm-01', 'vcmg', 'vcm'],
 'n': ['vcn_execuvision'],
 'o': ['vconnect', 'vcon', 'vco'],
 'p': ['vcp_chinandega'],
 'r': ['vcr/blu-ray_combo', 'vcr/dvd_combo'],
 's': ['vcs'],
 't': ['vctc_intercity'],
 'u': ['vcu_brandcenter', 'vcu-vuu_station', 'vcu_rams'],
 'v': ['vcv_rack'],
 'w': ['vcw'],
 'x': ['vcx'],
 'y': ['vcy_america']}
