# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '1.0.0rc4'
git_version = '504ee18d601b88a8e413c414ffb9b7d2e94ba248'
