
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yi = {'_': ["yi'an_town,_heilongjiang",
       'yi_county,_liaoning',
       'yi_sun-sin_stadium',
       'yi_sun-sin_bridge',
       'yi_county,_hebei',
       'yi_county,_anhui',
       'yi_christy_leung',
       'yi_yuan_mansion',
       'yi_tung_shan',
       'yi_zhou_shu',
       'yi_yun_chen',
       'yi_jian_mei',
       'yi_and_imi',
       'yi_li_keng',
       'yi_jet_qi'],
 'a': ['yiannis_pathiakakis_stadium',
       'yiannis_n._moschovakis',
       "yia_yia_mary's"],
 'b': ['yibin_wuliangye_airport', 'yibin_caiba_airport'],
 'c': ['yicheng_district,_zaozhuang',
       'yicheng_district,_zhumadian',
       'yichun_mingyueshan_airport',
       'yicheng_subdistrict,_hefei',
       'yichang_railway_station',
       'yichuan_county,_shaanxi',
       'yichun_confucian_temple',
       'yichun_railway_station',
       'yichang_sanxia_airport',
       'yichuan_county,_henan',
       'yichun_lindu_airport',
       'yichun_luming_mine',
       'yick_yuen_tsuen'],
 'd': ['yiddish_theatre_district',
       'yiddish_book_center',
       'yiddish_art_theatre',
       'yiddish_black_hand',
       'yida,_south_sudan',
       'yide_lu_station'],
 'e': ['yield_strength_anomaly',
       'yield_spread_premium',
       'yield_to_maturity',
       'yie_ar_kung-fu'],
 'g': ['yigit_emre_celtik', 'yigo_guam_temple'],
 'h': ['yihuang_self-immolation_incident',
       'yihwa_international_complex',
       'yihya_yitzhak_halevi',
       'yih-ho_michael_pao'],
 'k': ["yik'in_chan_k'awiil"],
 'l': ['yilliminning,_western_australia',
       'yildiztepe_military_cemetery',
       'yildiz_assassination_attempt',
       'yildiz_technical_university',
       'yilan_county,_heilongjiang',
       'yildiz_intelligence_agency',
       'yilan_county_constituency',
       'yilan-class_patrol_vessel',
       'yilan_town,_heilongjiang',
       'yiliang_county,_zhaotong',
       'yildirim_railway_station',
       'yiliang_county,_kunming',
       'yilan_county_government',
       'yildiz_hamidiye_mosque',
       'yili_normal_university',
       'yilishen_tianxi_group',
       'yilan_creole_japanese',
       'yilan_railway_station',
       'yilan_literary_museum',
       'yilan_county_council',
       'yiliu,_ruyuan_county',
       'yildiz_cagri_atiksoy',
       'yilan_county,_taiwan',
       'yildirim_army_group',
       'yildirim_bosna_s.k.',
       'yilou,_burkina_faso',
       'yildiz_clock_tower',
       'yili_road_station',
       'yilan_county_f.c.',
       'yilan_green_expo',
       'yilan_brick_kiln'],
 'm': ['yimbun_railway_tunnel',
       'yima_railway_station',
       'yimam_of_yejju',
       'yim_tin_tsai',
       'yim_fun_fong',
       'yim_tso_ha',
       'yim_liu_ha'],
 'n': ['yinchuan-lanzhou_high-speed_railway',
       "yinchuan-xi'an_high-speed_railway",
       'yingcheng_subdistrict,_changchun',
       'yinchuan_township,_heilongjiang',
       'yingshouyingzi_mining_district',
       'yinghai_subdistrict,_jiaozhou',
       'yingcheng_subdistrict,_yingde',
       'yinchuan_xihuayuan_airport',
       'yinchuan_helanshan_airport',
       'yingda_international_trust',
       'yinzhou_district,_tieling',
       'yingtiansi_temple_station',
       'yinchuan_railway_station',
       'yinzhou_district,_ningbo',
       'yingshan_county,_sichuan',
       'yinnietharra_rock_dragon',
       'yingzhou_ecological_park',
       'yingli_college,_longleng',
       'yinchuan_township,_gansu',
       'yinmaxia_railway_station',
       'yingda_asset_management',
       'yinchuan_helanshan_f.c.',
       'yingpan,_lanping_county',
       'yingfeng_riverside_park',
       'yinshan_rock_paintings',
       'yingge_railway_station',
       'yingli,_jinzhou,_hebei',
       'yincun,_yuanshi_county',
       'yinnar_south,_victoria',
       'yinzhou_avenue_station',
       'yingbin_avenue_station',
       'yintan_railway_station',
       'yingyuehu_park_station',
       'yingshan_county,_hubei',
       'yingbin_square_station',
       'yinchuan_poetry_prize',
       'yingchun_road_station',
       'ying_chang_compestine',
       'yingfeng_road_station',
       'yingzhou,_jixi_county',
       'yingkou_lanqi_airport',
       'ying_tung_natatorium',
       'yinqueshan_han_slips',
       'yingbin_road_station',
       'yin_style_baguazhang',
       'yinghui_road_station',
       'yingiya_mark_guyula',
       'ying_on_association',
       'yinka_dene_alliance',
       'yingao_road_station',
       'yinxiang,_prince_yi',
       'yindu_road_station',
       'yinxing_de_chibang',
       'ying_yang_forever',
       'yinqiao_jiedu_wan',
       'ying_tung_estate',
       'yingjie_jay_guo',
       'ying_yang_twins',
       'ying_wa_college',
       'yin_yang_style',
       'ying_tong_song',
       'yindaw_ma_lay',
       'ying_lung_wai',
       'yin_yang_fish',
       'ying_e._zhang',
       'yin_t._hsieh',
       'yin_yang_yo!',
       'yin_and_yang',
       'ying_and_yan',
       'yin_yin_nwe',
       'yin_si_juan',
       'yin_yin_oo',
       'ying_e_chi'],
 'o': ['yio_chu_kang'],
 'p': ['yip_yip_yaphank',
       'yip_cheong_fun',
       'yip_yip_coyote',
       'yip_yip_yippy',
       'yip_cheuk_man',
       'yip_kai_foon',
       'yip_sai_wing',
       'yip_tsz_fung',
       'yip_tsz_chun',
       'yip_hon_weng',
       'yip_pin_xiu',
       'yip_ho_nung',
       'yip_kue_sum',
       'yip_hor_man',
       'yip_pui_yin',
       'yip_chi_ho',
       'yip_ka_yu'],
 'q': ['yiqun_lisa_yin'],
 'r': ['yirmisekiz_mehmed_celebi',
       'yirrkala_bark_petitions',
       'yirrkala_blind_snake',
       'yirol_west_county',
       'yirol_east_county',
       'yiram_of_magdiel'],
 's': ['yisroel_yaakov_lichtenstein',
       'yisroel_yitzchok_piekarski',
       'yishun_neighbourhood_park',
       'yissachar_shlomo_teichtal',
       'yisroel_yaakov_lubchansky',
       'yisroel_eliyahu_weintraub',
       'yishun_community_hospital',
       'yisroel_aryeh_zalmanowitz',
       'yisroel_avrohom_portugal',
       'yisrael_mordecai_safeek',
       'yisroel_moshe_dushinsky',
       'yishun_secondary_school',
       'yishun_bus_interchange',
       'yisroel_pinchos_bodner',
       'yisroel_moshe_friedman',
       'yishan,_cangnan_county',
       'yisroel_dovid_harfenes',
       'yissachar_dov_rokeach',
       'yishun_public_library',
       'yisroel_moshe_olewski',
       'yisroel_yaakov_fisher',
       'yisrael_mendel_kaplan',
       'yishun_triple_murders',
       'yisroel_ber_odesser',
       'yisroel_meir_gabbai',
       'yisroel_dovid_weiss',
       'yishan_road_station',
       'yisroel_zev_gustman',
       'yishun_mrt_station',
       'yisrael_meir_kagan',
       'yisrael_meir_lau',
       'yishun_pond_park'],
 't': ['yitzchok_isaac_krasilschikov',
       'yitzchak_dovber_schneersohn',
       'yitzchak_zelig_morgenstern',
       'yitzhak_yaakov_rabinovich',
       'yitzchak_shlomo_zilberman',
       'yitzchak_elchanan_spektor',
       'yitzchok_zev_soloveitchik',
       'yitzchak_dovid_grossman',
       'yitzhak_mizrahi_sharabi',
       'yitzchak_yaacov_reines',
       'yitzchak_eizik_epstein',
       'yitzkhok_yoel_linetzky',
       'yitzhak_halevi_herzog',
       'yitzchak_meir_helfgot',
       'yitzchok_dovid_groner',
       'yitzchok_yaakov_weiss',
       'yitzhak_yaakov_yellin',
       'yitzhak_rabin_center',
       'yitian_holiday_plaza',
       "yitha'amar_bayyin_ii",
       'yitzhak_aharon_korff',
       'yitha_yitha_language',
       'yitzchok_tuvia_weiss',
       'yitzchak_isaac_taub',
       'yitzhak_of_volozhin',
       'yitzchak_meir_alter',
       'yitzchak_isaac_sher',
       'yitzhak_sadeh_prize',
       'yitzhak_isaac_levy',
       'yityish_titi_aynaw',
       'yitong_law_firm',
       'yitzhak_ben_ner'],
 'u': ['yiu_ming_temple',
       'yiu_tung_estate',
       'yiu_on_estate',
       'yiu_kit_ching',
       'yiu_tong_chan',
       'yiu_cheuk_yin',
       'yiu_hei_man',
       'yiu_ho_ming'],
 'w': ['yiwu-madrid_railway_line',
       'yiwu-london_railway_line',
       'yiwu_railway_station',
       'yiwu,_mengla_county',
       'yiwu_high_school'],
 'x': ['yixian_railway_station',
       'yixing_railway_station',
       'yixian_elevated_road',
       'yixuan,_prince_chun',
       'yixing_clay_teapot',
       'yixin_lake_station'],
 'y': ['yiyang_county,_jiangxi',
       'yiyang_railway_station',
       'yiyang_county,_henan'],
 'z': ['yizhuang_railway_station',
       'yizheng_chemical_fibre',
       'yizhou_district,_hechi',
       'yizhou_district,_hami',
       'yizheng_high_school',
       'yizhi_jane_tao']}
