
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-19T21:42:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bfb98b17d7b6c4412c4902451961c4f3e35a7fe7",
 "version": "2022.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
