
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_db = {'_': ['db_locomotive_classification',
       'db_regio_oberfranken',
       'db_draught_classic',
       'db_museum,_koblenz',
       'db_cargo_france',
       'db_cargo_polska',
       'db_drag_racing',
       'db_class_78.10',
       'db_class_215',
       'db_class_101',
       'db_class_724',
       'db_class_218',
       'db_class_210',
       'db_class_403',
       'db_class_670',
       'db_class_610',
       'db_class_611',
       'db_class_103',
       'db_class_120',
       'db_class_151',
       'db_class_111',
       'db_class_472',
       'db_class_420',
       'db_class_628',
       'db_class_240',
       'db_class_614',
       'db_city_mall',
       'db_class_82',
       'db_class_23',
       'db_cargo_uk',
       'db_class_10',
       'db_class_65',
       'db_class_66',
       'db_le_mans',
       'db_hbr_5'],
 'a': ['dbag_class_612',
       'dbag_class_474',
       'dbag_class_422',
       'dbag_class_128',
       'dbag_class_641',
       'dbag_class_430',
       'dbag_class_481',
       'dbag_class_225',
       'dbag_class_490',
       'dbag_class_424',
       'dbag_class_088',
       'dbag_class_648',
       'dbag_class_483',
       'dbag_class_423',
       'dbag_class_425'],
 'c': ['dbcult_film_institute'],
 'k': ['dbk_historic_railway'],
 'l': ['dbl_all-defense_team',
       'dbl_all-rookie_team',
       'dbl_all-star_team',
       'dbl_all-star_gala',
       'dbl_play-offs_mvp'],
 's': ['dbs_civilian_hr'],
 't': ['dbt_online_inc.']}
