
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hc = {'_': ['hc_fribourg-gotteron',
       'hc_victoria-berestie',
       "hc_'s-hertogenbosch",
       'hc_astrakhanochka',
       'hc_bozen-bolzano',
       'hc_keski-uusimaa',
       'hc_neumarkt-egna',
       'hc_frydek-mistek',
       'hc_ambri-piotta',
       'hc_bagtyyarlyk',
       'hc_midtjylland',
       'hc_berkut-kyiv',
       'hc_oranje-rood',
       'hc_bloemendaal',
       'hc_csikszereda',
       'hc_valpellice',
       'hc_svilengrad',
       'hc_budivelnyk',
       'hc_galychanka',
       'hc_satakunta',
       'hc_topolcany',
       'hc_gherdeina',
       'hc_donbass-2',
       'hc_prievidza',
       'hc_rotterdam',
       'hc_temirtau',
       'hc_zalgiris',
       'hc_martigny',
       'hc_vrchlabi',
       'hc85_series',
       'hc_belgorod',
       'hc_vladimir',
       'hc_erlangen',
       'hc_dobrudja',
       'hc_andersen',
       'hc_litvinov',
       'hc_villars',
       'hc_tornado',
       'hc_kharkiv',
       'hc_chrudim',
       'hc_olomouc',
       'hc_everest',
       'hc_salamat',
       'hc_lipetsk',
       'hc_izhstal',
       'hc_tallinn',
       'hc_metulla',
       'hc_rybinsk',
       'hc_donbass',
       'hc_thurgau',
       'hc_bryansk',
       'hc_lipovci',
       'hc_vilnius',
       'hc_lugano',
       'hc_korosa',
       'hc_vityaz',
       'hc_chelny',
       'hc_rostov',
       'hc_varese',
       'hc_tambov',
       'hc_merano',
       'hc_ryazan',
       'hc_berkut',
       'hc_astana',
       'hc_almaty',
       'hc_kosice',
       'hc_sierre',
       'hc_dalen',
       'hc_odesa',
       'hc_davos',
       'hc_sarov',
       'hc_lutsk',
       'hc_liceo',
       'hc_yugra',
       'hc_kuban',
       'hc_monza',
       'hc_kehra',
       'hc_gilje',
       'hc_drita',
       'hc_sochi',
       'hc_braga',
       'hc_zalau',
       'hc_zubri',
       'hc_gomel',
       'hc_ajoie',
       'hc_buzau',
       'hc_tabor',
       'hc_levy',
       'hc_most',
       'hc_tps',
       'hc_mvd',
       'hc_loc',
       'hc_rys'],
 'a': ['hca_healthcare'],
 'b': ['hcb_karvina'],
 'c': ['hcc_training'],
 'd': ['hcdr', 'hcde', 'hcd'],
 'e': ['hcentive', 'hcesar', 'hce'],
 'f': ['hcf_insurance', 'hcf_catch'],
 'g': ['hcg_87'],
 'h': ['hchs', 'hch'],
 'i': ['hci_bibliography'],
 'j': ['hcjb', 'hcj'],
 'k': ['hck'],
 'l': ['hcl_technologies',
       'hcl_connections',
       'hcl_sametime',
       'hcl_commerce',
       'hcl_domino',
       'hcl_axon'],
 'm': ['hcm-6a', 'hcmos', 'hcma', 'hcm'],
 'n': ['hcng_dispenser', 'hcn_channel'],
 'o': ['hcondels', 'hco'],
 'p': ['hcp_z1'],
 'r': ['hcr_corporation', 'hcr_manorcare'],
 's': ['hcsd', 'hcst', 'hcsa', 'hcso', 'hcss', 'hcs'],
 't': ['hct116_cells', 'hct_group'],
 'u': ['hcuav', 'hcu'],
 'v': ['hcv_genotypes'],
 'w': ['hcw'],
 'y': ['hcy'],
 'z': ['hcz']}
