
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hn = {'_': ['hn_andromedae', 'hn_pegasi', 'hn_group'],
 'a': ['hnaberd,_aragatsotn',
       'hnahthial_district',
       'hnat_domenichelli',
       'hnat_honcharenko',
       'hnat_khotkevych',
       'hnaberd,_ararat',
       'hna_technology',
       'hnat_stefaniv',
       'hna_building',
       'hnanisho_ii',
       'hnanisho_i',
       'hna_group',
       'hnat_yura'],
 'b': ['hnbap', 'hnb'],
 'c': ['hncoca_experiment', 'hnca_experiment'],
 'd': ['hndrxx', 'hnd'],
 'e': ['hnevin_castle'],
 'f': ['hnf1a-as1', 'hnf1a', 'hnf1b', 'hnf'],
 'g': ['hngettwin_nikaya'],
 'h': ['hnhs', 'hnh'],
 'i': ['hnialum_lalruatfeli', 'hni_corporation', 'hnifur_abrahams', 'hnin_mya'],
 'j': ['hnj_mb'],
 'k': ['hnk_suhopolje',
       'hnk_branitelj',
       'hnk_drinovci',
       'hnk_tomislav',
       'hnk_capljina',
       'hnk_segesta',
       'hnk_brotnjo',
       'hnk_sibenik',
       'hnk_cibalia',
       'hnk_gorica',
       'hnk_rijeka',
       'hnk_orasje',
       'hnk_dinara',
       'hnk_trogir',
       'hnk_borovo',
       'hnk_grude',
       'hnk_zadar'],
 'l': ['hnlms_noord-brabant',
       'hnlms_heiligerlee',
       'hnlms_schorpioen',
       'hnlms_gelderland',
       'hnlms_groningen',
       'hnlms_friesland',
       'hnlms_rotterdam',
       'hnlms_kortenaer',
       'hnlms_amsterdam',
       'hnlms_cerberus',
       'hnlms_zeeleeuw',
       'hnlms_banckert',
       'hnlms_evertsen',
       'hnlms_zeehond',
       'hnlms_sumatra',
       'hnlms_dolfijn',
       'hnlms_zeeland',
       'hnlms_bonaire',
       'hnlms_utrecht',
       'hnlms_matador',
       'hnlms_holland',
       'hnlms_walrus',
       'hnlms_medusa',
       'hnlms_guinea',
       'hnlms_buffel',
       'hnlms_flores',
       'hnlms_soemba',
       'hnlms_borneo',
       'hnlms_draak',
       'hnlms_stier',
       'hnlms_tromp',
       'hnlms_java'],
 'n': ['hnn_extension'],
 'o': ['hnoms_tordenskjold',
       'hnoms_honningsvag',
       'hnoms_skorpionen',
       'hnoms_valkyrien',
       'hnoms_valkyrjen',
       'hnoms_stavanger',
       'hnoms_trondheim',
       'hnoms_thrudvang',
       'hnoms_nordkapp',
       'hnoms_eidsvold',
       'hnoms_sleipner',
       'hnoms_svenner',
       'hnoms_thorodd',
       'hnoms_utstein',
       'hnoms_glomma',
       'hnoms_ellida',
       'hnoms_kobben',
       'hnoms_gyller',
       'hnoms_bergen',
       'hnoms_vidar',
       'hnoms_froya',
       'hnoms_start',
       'hnoms_stegg',
       'hnoms_kjell',
       'hnoms_stord',
       'hnoms_uller',
       'hnoms_trygg',
       'hnoms_brann',
       'hnoms_hessa',
       'hnoms_ornen',
       'hnoms_nasty',
       'hnoms_rauma',
       'hnoms_vigra',
       'hnomy_norge',
       'hnoms_norge',
       'hnoms_hitra',
       'hnoms_storm',
       'hnoms_troll',
       'hnoms_snogg',
       'hnoms_tjeld',
       'hnoms_brage',
       'hnoms_draug',
       'hnoms_aeger',
       'hnoms_kvikk',
       'hnoms_rapp',
       'hnoms_snar',
       'hnoms_garm',
       'hnoms_otra',
       'hnoms_rask',
       'hnoms_sael',
       'hnoms_vale',
       'hnoms_oslo',
       'hnoms_thor',
       'hnoms_maud',
       'hnoms_odin',
       'hnoms_sel',
       'hnoms_b-5',
       'hnoms_myg',
       'hnoms_gor',
       'hnoms_ula',
       'hnoms_tyr'],
 'p': ['hnp'],
 'r': ['hnrnpa2b1',
       'hnrnpll',
       'hnrnpa0',
       'hnrpul1',
       'hnrnpa1',
       'hnrnpab',
       'hnrnpc',
       'hnrnpr',
       'hnrph3',
       'hnrpdl',
       'hnrpa3',
       'hnrph2',
       'hnrph1',
       'hnrnpk',
       'hnrnpl',
       'hnrpd',
       'hnrpf',
       'hnrpu'],
 's': ['hns_convention', 'hnsk_moslavina'],
 't': ['hnt_chicken'],
 'u': ['hnuti_brontosaurus', 'hnuti_duha'],
 'v': ['hnv'],
 'x': ['hnx'],
 'y': ['hnylyi_tikych', 'hnyla_lypa'],
 'z': ['hnz_group']}
