
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pc = {'_': ['pc/computing',
       'pc-mos/386',
       'pc-write',
       'pc-talk',
       'pc-lisp',
       'pc-lint',
       'pc-saft',
       'pc-file',
       'pc-200',
       'pc1512',
       'pc/104',
       'pc-20',
       'pc/sc',
       'pc532',
       'pc-ux',
       'pc-fx',
       'pc-1',
       'pc12',
       'pc2',
       'pc1',
       'pc3'],
 'a': ['pcanywhere',
       'pcastl',
       'pcaas',
       'pcae',
       'pcaf',
       'pcac',
       'pcaa',
       'pcap',
       'pca3',
       'pcam',
       'pcas',
       'pcad',
       'pca'],
 'b': ['pcbp1-as1',
       'pcb-rnd',
       'pcboard',
       'pcbp1',
       'pcbp2',
       'pcbp4',
       'pcbd1',
       'pcbp3',
       'pcbd2',
       'pcbc',
       'pcba',
       'pcbs',
       'pcb'],
 'c': ['pcc-stadion',
       'pccg-4',
       'pccts',
       'pcca',
       'pccw',
       'pccp',
       'pccl',
       'pccs',
       'pcci',
       'pcce',
       'pccc',
       'pcc'],
 'd': ['pcdhga11',
       'pcdhga12',
       'pcdhb15',
       'pcdhb14',
       'pcdha12',
       'pcdhb12',
       'pcdhb10',
       'pcdhb16',
       'pcdhac2',
       'pcdhb11',
       'pcdh11y',
       'pcdhgc3',
       'pcdh11x',
       'pcdhgb7',
       'pcdhb13',
       'pcdata',
       'pcdh20',
       'pcdhb9',
       'pcdhb5',
       'pcdhb7',
       'pcdh17',
       'pcdha6',
       'pcdhb4',
       'pcdha5',
       'pcdhb3',
       'pcdh18',
       'pcdha9',
       'pcdha4',
       'pcdh10',
       'pcdha3',
       'pcdh15',
       'pcdhb2',
       'pcdha2',
       'pcdh12',
       'pcdh8',
       'pcdh7',
       'pcdh1',
       'pcdi',
       'pcd'],
 'e': ['pcelic', 'pcell', 'pcea', 'pcep', 'pcem', 'pcer', 'pce'],
 'f': ['pcfc', 'pcf'],
 'g': ['pcgamingwiki',
       'pcgamerbike',
       'pcgamesn',
       'pcgem1',
       'pcgf5',
       'pcgf6',
       'pcgf1',
       'pcgf2',
       'pcgen',
       'pcgs',
       'pcgg',
       'pcgm',
       'pcg'],
 'h': ['pchelovodstvo',
       'pchegatlukay',
       'pchelinovka',
       'pchelintsev',
       'pchelarovo',
       'pchyolkino',
       'pchyovzha',
       'pchelniki',
       'pchelino',
       'pchelnik',
       'pchelari',
       'pcheda',
       'pchery',
       'pchela',
       'pchs',
       'pchp',
       'pchr',
       'pch'],
 'i': ['pci/104-express',
       'pci-sig',
       'pcinja',
       'pci-x',
       'pcid2',
       'pcip',
       'pcid',
       'pcim',
       'pcic',
       'pcia',
       'pcin',
       'pci'],
 'j': ['pcjj', 'pcj'],
 'k': ['pckeeper', 'pck2', 'pck1', 'pck'],
 'l': ['pclinuxos',
       'pclsring',
       'pcl-181',
       'pcl-171',
       'pcl-161',
       'pcloudy',
       'pcl-09',
       'pclake',
       'pclkc',
       'pclo',
       'pcl'],
 'm': ['pcmicro',
       'pcmark',
       'pcmt1',
       'pcmag',
       'pcm30',
       'pcmos',
       'pcma',
       'pcmb',
       'pcmh',
       'pcm1'],
 'n': ['pcnhs', 'pcnt', 'pcnx', 'pcns', 'pcn'],
 'o': ['pcon.planner',
       'pcoline',
       'pcolce2',
       'pcomb3h',
       'pcolce',
       'pcom',
       'pcoa',
       'pco2',
       'pcoe',
       'pco'],
 'p': ['pcpartpicker',
       'pcplayer',
       'pcpaint',
       'pcp4',
       'pcpm',
       'pcpp',
       'pcpr',
       'pcpa',
       'pcpn',
       'pcpb',
       'pcp'],
 'r': ['pcrpi-db', 'pcrush', 'pcrl', 'pcrd', 'pcrc', 'pcra'],
 's': ['pcsx-reloaded',
       'pcsat2',
       'pcsk5',
       'pcsk7',
       'pcsk9',
       'pcsx2',
       'pcsk6',
       'pcsk4',
       'pcsa',
       'pcso',
       'pcsb',
       'pcs'],
 't': ['pctct', 'pctk2', 'pctk1', 'pctk3', 'pcte', 'pctv', 'pctp', 'pct'],
 'u': ['pcun', 'pcu'],
 'v': ['pcv'],
 'w': ['pcw'],
 'x': ['pcx'],
 'y': ['pcyt1b', 'pcyox1', 'pcyt1a']}
