
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tc = {'_': ['tc_business_school',
       "tc's_trikes_coyote",
       'tc_america_series',
       'tc_energy_center',
       'tc_energy_tower',
       'tc_pista_mouras',
       'tc_works_spark',
       'tc_pick_up',
       'tc_ot_39'],
 'a': ['tca_heritage_award'],
 'c': ['tcc_batavia_towers'],
 'd': ['tcdd_suburban_fleet',
       'tcdd_subdivision_3',
       'tcdd_subdivision_1',
       'tcde_holin_family',
       'tcdd_56701_class',
       'tcdd_56301_class',
       'tcdd_45151_class',
       'tcdd_46201_class',
       'tcdd_uic-x_fleet',
       'tcdd_56501_class',
       'tcdd_45171_class',
       'tcdd_57001_class',
       'tcdd_5701_class',
       'tcdd_2201_class',
       'tcdd_hsl_700',
       'tcdd_e_52500',
       'tcdd_e_40000',
       'tcdd_e_43000',
       'tcdd_e_4000'],
 'e': ['tcec_season_21',
       'tcec_season_22',
       'tcec_season_17',
       'tcec_season_20',
       'tcec_season_16',
       'tcec_season_14',
       'tcec_season_19',
       'tcec_season_15',
       'tcec_season_18',
       'tcec_season_3',
       'tcec_season_4',
       'tcec_season_2',
       'tcec_season_1'],
 'f': ['tcf_financial_corporation'],
 'g': ['tcg_birinci_inonu',
       'tcg_ikinci_inonu',
       'tcg_osman_gazi',
       'tcg_oruc_reis'],
 'h': ['tchaikovsky_symphony_orchestra',
       'tchorzew,_masovian_voivodeship',
       'tchaikovsky_state_house-museum',
       'tchorzew,_lublin_voivodeship',
       'tcherny_railway_accident',
       'tchouk_tchouk_musik',
       "tchicaya_u_tam'si"],
 'i': ['tcifa_national_academy'],
 'l': ['tclr_st._molaga', 'tcl_10_pro', 'tcl_10_5g'],
 'o': ['tcom_blue_devil'],
 'p': ['tcp/ip_stack_fingerprinting',
       'tcp_delayed_acknowledgment',
       'tcp_global_synchronization',
       'tcp_cookie_transactions',
       'tcp_congestion_control',
       'tcp_protein_domain',
       'tcp_offload_engine',
       'tcp_gender_changer',
       'tcp_hole_punching',
       'tcp_reset_attack',
       'tcp_fast_open'],
 'r': ['tcr_international_series',
       'tcr_sakhir_round',
       'tcr_asia_series',
       'tcr_touring_car'],
 's': ['tcs_it_wiz'],
 'u': ['tcu-texas_football_rivalry', 'tcu_horned_frogs'],
 'w': ['tcw_heavyweight_championship', 'tcw_hardcore_championship'],
 'z': ['tczew_railway_station']}
