
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pz = {'_': ['pz_cassiopeiae',
       'pz_telescopii',
       'pz.sfl._ii',
       'pz_cussons',
       'pz_myers'],
 'a': ['pza_loara'],
 'c': ['pzc'],
 'f': ['pzf_44'],
 'g': ['pzg'],
 'h': ['pzh'],
 'i': ['pzinz_703', 'pzinz_130'],
 'k': ['pzk'],
 'l': ['pzl-mielec_lim-6',
       'pzl-230_skorpion',
       'pzl-105_flaming',
       'pzl.50_jastrzab',
       'pzl-126_mrowka',
       'pzl-112_junior',
       'pzl-101_gawron',
       'pzl.48_lampart',
       'pzl-104_wilga',
       'pzl.44_wicher',
       'pzl-130_orlik',
       'pzl.56_kania',
       'pzl.23_karas',
       'pzl-106_kruk',
       'pzl.45_sokol',
       'pzl-102_kos',
       'pzl.38_wilk',
       'pzl.46_sum',
       'pzl.37_los',
       'pzl_mielec',
       'pzl.49_mis',
       'pzl_kania',
       'pzl_md-12',
       'pzl_sm-2',
       'pzl_m-17',
       'pzl_p.24',
       'pzl_p.11',
       'pzl_m-2',
       'pzl_p.8',
       'pzl_l.2',
       'pzl_p.6',
       'pzl_p.1',
       'pzl_s-1',
       'pzl_p.7'],
 'm': ['pzms_poltava'],
 'o': ['pzo'],
 'p': ['pzp'],
 'y': ['pzyche']}
