
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pk = {'_': ['pk_porthcurno',
       'pk/pd_models',
       'pk-35_vantaa',
       'pk_arumugam',
       'pk_albertyn',
       'pk_carsport',
       'pk_bosna',
       'pk_dwyer',
       'pk_cards',
       'pk_park'],
 'a': ['pkaila', 'pka'],
 'b': ['pkb_corporation'],
 'c': ['pkc_group',
       'pkc_alpha',
       'pkcs_11',
       'pkcs_12',
       'pkcs_1',
       'pkcs_7',
       'pkcs_8'],
 'd': ['pkd_foundation', 'pkd_domain'],
 'e': ['pke'],
 'f': ['pkf_international'],
 'g': ['pkg-config', 'pkgsrc', 'pkg'],
 'h': ['pkharmat', 'pkhista', 'pkhyan', 'pkhali', 'pkhmat', 'pkhovi', 'pkhrut'],
 'i': ['pkioverheid',
       'pkidha',
       'pkids',
       'pkill',
       'pkig',
       'pkia',
       'pkib',
       'pki'],
 'l': ['pklr'],
 'm': ['pkmmhss_edarikode'],
 'n': ['pkn_vidhyasala', 'pkn_orlen'],
 'o': ['pko'],
 'p': ['pkp_informatyka',
       'pkp_energetyka',
       'pkp_intercity',
       'pkp_group',
       'pkp_cargo'],
 'r': ['pkr.com', 'pkr'],
 's': ['pks_2155-304',
       'pks_2000-330',
       'pks_1302-102',
       'pks_0521-365',
       'pks_2014-55'],
 't': ['pkt'],
 'u': ['pku_healthcare'],
 'w': ['pkwn_manifesto'],
 'x': ['pkx'],
 'z': ['pkzip']}
