
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pm = {'_': ['pm_entertainment',
       'pm_selfiewallie',
       'pm_magazine',
       'pm_records',
       'pm-60_mine',
       'pm-79_mine',
       'pm_press',
       'pm_m1910',
       'pm_win-t',
       'pm_live'],
 'a': ['pma-3_mine', 'pma-2_mine', 'pma_group'],
 'b': ['pmbr', 'pmb'],
 'c': ['pmc_ltd.'],
 'd': ['pmd_technologies', 'pmd_85'],
 'e': ['pmel', 'pme'],
 'f': ['pmfbp1', 'pmftc', 'pmf'],
 'g': ['pmg'],
 'h': ['pmhub', 'pmhs', 'pmh'],
 'i': ['pmi_colleges', 'pmi_group'],
 'j': ['pmji'],
 'k': ['pmk_pro-am'],
 'l': ['pml_flightlink'],
 'm': ['pmm2_deficiency', 'pmmr_62'],
 'n': ['pmn_mine'],
 'o': ['pmod_interface', 'pmos_logic'],
 'p': ['pmpv1', 'pmpcb', 'pmpca', 'pmp2', 'pmp'],
 'q': ['pmq'],
 'r': ['pmrl_stadium',
       'pmr_records',
       'pmr-3_mine',
       'pmr-u_mine',
       'pmr-4_mine',
       'pmr_ltd'],
 's': ['pms_prasad', 'pms_clan'],
 't': ['pmt_italia'],
 'u': ['pmu_interlife'],
 'v': ['pmview', 'pmve', 'pmv'],
 'w': ['pmwiki'],
 'x': ['pmx'],
 'z': ['pmz-40_mine']}
