
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pd = {'_': ['pd-4501_scenicruiser',
       'pd_subdivision',
       'pd_aerospace',
       'pd_144418',
       'pd_ports',
       'pd_draw',
       'pd_note',
       'pd_5500',
       'pd_500',
       'pd_360'],
 'a': ['pda_dimensions'],
 'b': ['pdbbind_database'],
 'c': ['pdcurses',
       'pdcd1lg2',
       'pdcd6ip',
       'pdc-109',
       'pdcd10',
       'pdcd4',
       'pdcd2',
       'pdcd7',
       'pdcd5',
       'pdcd6',
       'pdci',
       'pdca',
       'pdc'],
 'd': ['pdd-62'],
 'e': ['pde-constrained_optimization',
       'pde5_inhibitor',
       'pde3_inhibitor',
       'pde_surface',
       "pdei_la'o"],
 'f': ['pdf-xchange_viewer',
       'pdf_association',
       'pdftron_systems',
       'pdf_solutions',
       'pdf24_creator',
       'pdf_signer',
       'pdf_studio',
       'pdf_expert'],
 'g': ['pdg_s.a.'],
 'h': ['pdhs', 'pdh'],
 'i': ['pdiff', 'pdia3', 'pdia2', 'pdic', 'pdi'],
 'k': ['pdk3', 'pdk2', 'pdk4', 'pdk'],
 'l': ['pdl_biopharma'],
 'm': ['pdm_university', 'pdms_stamp', 'pdm_racing'],
 'n': ['pdnsd', 'pdns', 'pdn'],
 'o': ['pdoc_headquarters'],
 'p': ['pdp-11_architecture', 'pdp_london', 'pdp_cares'],
 'q': ['pdq_chocolate'],
 'r': ['pdr-ihumure', 'pdr1p', 'pdra', 'pdrs', 'pdrc', 'pdr'],
 's': ['pds_110', 'pds_70'],
 't': ['pdt_partners', 'pdt_standard'],
 'u': ['pdufa_date'],
 'v': ['pdval_affair'],
 'x': ['pdx_fc'],
 'z': ['pdz_domain']}
