
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kj = {'_': ['kj_choi_invitational'],
 'a': ['kjartan_atli_kjartansson',
       'kjaerlighet_og_vennskap',
       'kjaerlighet_paa_pinde',
       'kjaer_and_richter'],
 'c': ['kjc_king_dome'],
 'e': ['kjellgren_kaminsky_architecture',
       'kjersti_annesdatter_skomsvold',
       'kjell_thorbjorn_kristensen',
       'kjell_christian_ulrichsen',
       'kjetil_bragli_alstadheim',
       'kjetil_ruthford_pedersen',
       'kjerringoy_trading_post',
       "kjer's_optic_neuropathy",
       'kjerstin_woyen_funderud',
       'kjell_albin_abrahamson',
       'kjetil_traedal_thorsen',
       'kjeld_kirk_kristiansen',
       'kjersti_loken_stavrum',
       'kjell_gjostein_aabrek',
       'kjell_alrich_schumann',
       'kjeld_erik_brodsgaard',
       'kjell_egil_eimhjellen',
       'kjetil_aleksander_lie',
       'kjell_arild_pollestad',
       'kjell_sverre_johansen',
       'kjell_ingolf_ropstad',
       'kjell_ivar_lundemoen',
       'kjell_arvid_svendsen',
       'kjellman_machine_gun',
       'kjell_magne_fredheim',
       'kjell_magne_bondevik',
       'kjell_kristian_rike',
       'kjerstin_boge_solas',
       'kjell_havard_jensen',
       'kjell_bloch_sandved',
       'kjetil_korbu_nilsen',
       'kjetil_andre_aamodt',
       'kjell_a._nordstrom',
       'kjeller_f.f.9_kaje',
       'kjell_jakob_sollie',
       'kjell_mork_karlsen',
       'kjell_h._halvorsen',
       'kjell_sture_jensen',
       'kjell_terje_fevag',
       'kjell_ivar_larsen',
       'kjell_arne_bratli',
       'kjeld_abell_prize',
       'kjell_a._storeide',
       'kjeld_stub_irgens',
       'kjell_and_company',
       'kjell_rune_sellin',
       'kjell_arnljot_wig',
       'kjell_n._lindgren',
       'kjell_roar_kaasa',
       'kjell_georg_lund',
       'kjell_inge_olsen',
       'kjell_lars_berge',
       'kjell_inge_rokke',
       'kjell_g._finstad',
       'kjell_olav_kran',
       'kjell_magne_yri',
       'kjell_b._hansen',
       'kjell_ove_hauge',
       'kjell_g._nyborg',
       'kjell_otto_moe',
       'kjell_ola_dahl',
       'kjell_erik_oie'],
 'o': ['kjobenhavns_forstaeders_sporveisselskab',
       'kjofossen_power_station',
       'kjotve_the_rich']}
