
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vy = {'_': ['vy,_burkina_faso',
       'vy_vato_sakelika',
       'vy_canis_majoris',
       'vy_maria_dong'],
 'a': ['vyagrapurisvarar_temple,_thiruvengaivasal',
       'vyagrapurisvarar_temple,_thaplampuliyur',
       'vyasachala_mahadevendra_saraswati',
       'vyacheslav_kalashnikov_polishchuk',
       'vyacheslav_nikolayevich_kuznetsov',
       'vyacheslav_shishkov_bibliography',
       'vyacheslav_mikhailovich_lebedev',
       'vyacheslav_vasilievich_sazonov',
       'vyacheslav_mikhailovich_briman',
       'vyacheslav_nikolaevich_mironov',
       'vyacheslav_ivanovich_lebedev',
       'vyatskoye,_astrakhan_oblast',
       'vyatskoye,_yaroslavl_oblast',
       'vyatskoye,_khabarovsk_krai',
       'vyacheslav_ivanovich_silin',
       'vyazemsky,_khabarovsk_krai',
       'vyazovka,_voronezh_oblast',
       'vyazma_airborne_operation',
       'vyazovoye,_vologda_oblast',
       'vyazovka,_vladimir_oblast',
       'vyasnagar_railway_station',
       'vyazniki,_vladimir_oblast',
       'vyacheslav_ivanovich_zof',
       'vyacheslav_i._lebedev',
       'vyacheslav_von_plehve',
       'vyara_railway_station',
       'vyasa_vidya_peethom',
       'vyas_deo_prasad',
       'vyas_deo_sharma'],
 'b': ['vyborg_railway_station', 'vyborg_hvdc_scheme', 'vyborg_town_wall'],
 'd': ['vydubychi_railway_station',
       'vydrino,_vologda_oblast',
       'vydmantai_wind_park'],
 'h': ['vyhne_labor_camp'],
 'j': ['vyjayanti_vasanta_mogli'],
 'l': ['vyloppilli_sreedhara_menon', 'vylkovo,_altai_krai'],
 'm': ['vympel_design_bureau', 'vympel,_altai_krai'],
 'n': ['vynohrad,_cherkasy_oblast'],
 'o': ['vyoshki,_vladimir_oblast'],
 'p': ['vypolzovo,_belgorod_oblast', 'vypeen_alcohol_poisonings'],
 'r': ['vyronas_national_stadium',
       'vyroneia_railway_station',
       'vyry_railway_station'],
 's': ['vyshneve,_dnipropetrovsk_oblast',
       'vysokohirne,_yalta_municipality',
       'vysokohirne,_zaporizhzhia_raion',
       'vysokogorny,_khabarovsk_krai',
       'vyshenky,_chernihiv_oblast',
       'vysokyi_settlement_hromada',
       'vyshny_volochyok_waterway',
       'vyshka,_astrakhan_oblast',
       'vysoka,_sabinov_district',
       'vyselki,_vladimir_oblast',
       'vyselki,_krasnodar_krai',
       'vysehrad_railway_bridge',
       'vysoky,_murmansk_oblast',
       'vysoke,_kherson_oblast',
       'vysotsk,_rivne_oblast',
       'vyskytna_nad_jihlavou',
       'vyshnia,_lviv_oblast',
       'vyssi_brod_monastery',
       'vystar_credit_union',
       'vysoka_nad_kysucou',
       'vyskovce_nad_iplom',
       'vysoke_nad_jizerou',
       'vysoka_u_pribrame',
       'vysoka_pri_morave',
       'vysne_nad_hronom',
       'vysoka_nad_labem',
       'vysoka_nad_uhom',
       'vyssi_brod_pass'],
 't': ['vytautas_algimantas_buinevicius',
       'vytautas_adolfas_puplauskas',
       'vytautas_andrius_graiciunas',
       'vytautas_kazimieras_jonynas',
       'vytautas_military_district',
       'vytautas_magnus_university',
       'vytautas_petras_pleckaitis',
       'vytautas_pranas_biciunas',
       'vytautas_v._landsbergis',
       'vytis_military_district',
       'vyttila_metro_station',
       'vyttila_mobility_hub',
       'vyta_du_roc'],
 'z': ['vyzantio_kokkinochoma_f.c.']}
