
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bc = {'_': ['bc-li-0186',
       'bc-348',
       'bc-610',
       'bc-342',
       'bc-stv',
       'bc-41',
       'bc150',
       'bc548',
       'bc-3',
       'bc-1',
       'bc1',
       'bc4',
       'bc3',
       'bc2'],
 'a': ['bcachefs',
       'bcap31',
       'bcache',
       'bcap29',
       'bcas2',
       'bcas3',
       'bcar1',
       'bcar3',
       'bcas1',
       'bcaa',
       'bcas',
       'bcap',
       'bca'],
 'b': ['bcbst', 'bcbs', 'bcbg', 'bcbp', 'bcbc', 'bcb'],
 'c': ['bcc-rapid', 'bccip', 'bcciv', 'bcc6', 'bccl', 'bccm', 'bcci', 'bcc'],
 'd': ['bcdmos', 'bcdmh', 'bcds', 'bcd'],
 'e': ['bcepmuvirus', 'bcesis', 'bcet', 'bces', 'bcec'],
 'f': ['bcfg2', 'bcfp', 'bcfm', 'bcfc', 'bcf'],
 'g': ['bcgf1', 'bcg'],
 'h': ['bchernata', 'bchennine', 'bcheale', 'bcheck', 'bchs', 'bchd', 'bch'],
 'i': ['bci2000', 'bcisd', 'bciii', 'bcia', 'bcic', 'bcis', 'bcie', 'bci'],
 'j': ['bcj'],
 'k': ['bckdha', 'bckdhb', 'bckdh', 'bckdk', 'bck2', 'bck'],
 'l': ['bcl2l14',
       'bcl2l12',
       'bcl2l10',
       'bcl2l11',
       'bcl2l13',
       'bcl2l2',
       'bcl11b',
       'bclaf1',
       'bcl11a',
       'bcl-xl',
       'bcl6b',
       'bcl-2',
       'bcl10',
       'bcl9l',
       'bcl7a',
       'bcl6',
       'bcls',
       'bclp',
       'bcl3',
       'bcl9',
       'bcl'],
 'm': ['bcmp', 'bcma', 'bcms', 'bcm'],
 'n': ['bcn'],
 'o': ['bcode', 'bcor', 'bcov', 'bco'],
 'p': ['bcpnn', 'bcps', 'bcpp', 'bcpc', 'bcpl', 'bcp'],
 'q': ['bcq'],
 'r': ['bcrypt', 'bcru', 'bcrs', 'bcra', 'bcr'],
 's': ['bcs-facs',
       'bcswomen',
       'bcs1l',
       'bcsc',
       'bcsa',
       'bcss',
       'bcso',
       'bcsl',
       'bcsn',
       'bcs'],
 't': ['bctc', 'bctv', 'bct'],
 'u': ['bcube', 'bcuc', 'bcu'],
 'v': ['bcvo', 'bcv'],
 'x': ['bcx'],
 'y': ['bcycle', 'bcy'],
 'z': ['bcz']}
