
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bm = {'_': ['bm-24', 'bm-14', 'bm-1', 'bm25'],
 'a': ['bmakine', 'bmahray', 'bmapn', 'bmarc', 'bmag', 'bmas', 'bma'],
 'b': ['bmb'],
 'c': ['bmci', 'bmc'],
 'd': ['bmd-20', 'bmd-3', 'bmd-2', 'bmd-1', 'bmd-4', 'bmdp', 'bmd'],
 'e': ['bmezine', 'bme'],
 'f': ['bmfms', 'bmfc', 'bmf'],
 'g': ['bmg'],
 'h': ['bmhs', 'bmh'],
 'i': ['bmibaby', 'bmi1', 'bmic', 'bmir', 'bmi'],
 'k': ['bmkaep', 'bmktx', 'bmk'],
 'l': ['bml-190', 'bml'],
 'm': ['bmmi', 'bmm'],
 'n': ['bmnh', 'bmn'],
 'o': ['bmobile', 'bmop', 'bmon', 'bmoc', 'bmo'],
 'p': ['bmp-23',
       'bmpr1a',
       'bmpr1b',
       'bmp-2',
       'bmpr2',
       'bmp2k',
       'bmp02',
       'bmp-1',
       'bmp-3',
       'bmp1',
       'bmp2',
       'bmp3',
       'bmp'],
 'q': ['bmq'],
 'r': ['bmrst', 'bmr'],
 's': ['bms-564,929',
       'bms-470539',
       'bms-641988',
       'bms-955176',
       'bms-345541',
       'bms-906024',
       'bms-203',
       'bms-f',
       'bmss',
       'bms'],
 't': ['bmtx3', 'bmtc', 'bmt'],
 'u': ['bmu'],
 'v': ['bmvc', 'bmv'],
 'w': ['bmw'],
 'x': ['bmx'],
 'y': ['bmycharity', 'bmy-14802', 'bmy-7378'],
 'z': ['bmz']}
