
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bt = {'_': ['bt-epoxy',
       'bt.1120',
       'bt-20',
       'bt-43',
       'bt-sv',
       'bt-42',
       'bt100',
       'bt-7',
       'bt-4',
       'bt-3'],
 'a': ['btaaboura', 'btarena', 'bta-6', 'btaf1', 'btaa', 'btan', 'bta'],
 'b': ['btbd14b', 'btbd2', 'btbd1', 'btbd9', 'btbp', 'btb'],
 'c': ['btcjam', 'btc-e', 'btcl', 'btcs', 'btc'],
 'd': ['btdtgtts', 'btdigg', 'btdt'],
 'e': ['bteghrine', 'btekhnay', 'bteibat', 'btermaz', 'btec'],
 'f': ['btf3', 'btfc', 'btf'],
 'g': ['btg1', 'btg2', 'btg4', 'btg3', 'btg'],
 'h': ['bths', 'bth'],
 'i': ['bticino', 'bti'],
 'j': ['btjunkie'],
 'k': ['btk'],
 'l': ['btla', 'btlp', 'btl'],
 'm': ['btm2', 'btm'],
 'n': ['btnhresurrection', 'btn3a3', 'btnl2', 'btn'],
 'o': ['btouratige', 'btourram', 'btooom!', 'bto'],
 'p': ['btp'],
 'q': ['btq'],
 'r': ['btrx-335140',
       'btrx-246040',
       'btr-152',
       'btrieve',
       'btr-40',
       'btr-50',
       'btr-70',
       'btr-90',
       'btr-60',
       'btr-94',
       'btr-80',
       'btr-4',
       'btrfs',
       'btr-t',
       'btron',
       'btr-d',
       'btr-7',
       'btr-3',
       'btrc',
       'btr'],
 's': ['btstu', 'btsm', 'bts'],
 't': ['btt'],
 'v': ['btvi', 'btv'],
 'w': ['btw'],
 'x': ['btx'],
 'z': ['btz']}
