
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bd = {'_': ['bd-10deg3166',
       'bd+40deg4210',
       'bd+17deg3248',
       'bd+60deg2522',
       'bd-08deg2823',
       'bd+20deg307',
       'bd-1047',
       'bd1018',
       'bd1067',
       'bd1063',
       'bd1060',
       'bd1008',
       'bd1031',
       'bd1052',
       'bd-12',
       'bd-14',
       'bd-1',
       'bd20',
       'bd-j',
       'bd+',
       'bd5'],
 'a': ['bdallophytum', 'bdadoun', 'bdav', 'bda'],
 'b': ['bdbc', 'bdb'],
 'c': ['bdc'],
 'd': ['bddc', 'bdd'],
 'e': ['bdellovibrionaceae',
       'bdellovibrionales',
       'bdellomicrovirus',
       'bdellovibrionota',
       'bdellocephala',
       'bdellozonium',
       'bdellouridae',
       'bdellonyssus',
       'bdellovibrio',
       'bdelyropsis',
       'bdelloidea',
       'bdellidae',
       'bdelygmia',
       'bdellodus',
       'bdeogale',
       'bdelyrus',
       'bdeneves',
       'bdellium',
       'bdella',
       'bdebba',
       'bdes',
       'bde'],
 'f': ['bdf-3299', 'bdf-521', 'bdf'],
 'g': ['bdg'],
 'h': ['bdhs', 'bdh1', 'bdh'],
 'i': ['bdintsi', 'bdii', 'bdin', 'bdi'],
 'j': ['bdj'],
 'k': ['bdk'],
 'm': ['bdmx', 'bdm'],
 'n': ['bdnews24.com', 'bdn'],
 'o': ['bdort', 'bdood', 'bdo'],
 'p': ['bdpc', 'bdp1', 'bdp'],
 'q': ['bdq'],
 'r': ['bdr'],
 's': ['bdsni', 'bds-1', 'bdsec', 'bdsm', 'bds'],
 't': ['bdth2', 'bdt'],
 'u': ['bdu'],
 'w': ['bdwm', 'bdw'],
 'x': ['bdx'],
 'z': ['bdz']}
