
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yv = {'a': ['yvan', 'yva'],
 'e': ['yverdon-les-bains',
       'yvetot-bocage',
       'yves-gomezee',
       'yvernaumont',
       'yvecrique',
       'yvelines',
       'yversay',
       'yvetot',
       'yvesia',
       'yvette',
       'yves',
       'yven',
       'yvel',
       'yve'],
 'g': ['yvgenie'],
 'h': ['yvhs'],
 'i': ['yville-sur-seine', 'yvignac-la-tour', 'yviers', 'yvias'],
 'j': ['yvj'],
 'o': ['yvoy-le-marron',
       'yvonand',
       'yvonne',
       'yvoire',
       'yvorne',
       'yvoir',
       'yvon',
       'yvo'],
 'p': ['yvp'],
 'r': ['yvrac-et-malleyrand',
       'yvridiosuchus',
       "yvre-l'eveque",
       'yvre-le-polin',
       'yvrencheux',
       'yvrandes',
       'yvretta',
       'yvrench',
       'yvrac'],
 't': ['yvto']}
