
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nr = {'_': ['nr58-3.14.3', 'nr-413', 'nr-40', 'nr4a', 'nr4'],
 'a': ['nratv', 'nrank', 'nram', 'nras', 'nrap'],
 'b': ['nrbp1', 'nrbf2', 'nrbq', 'nrb'],
 'c': ['nrcam', 'nrca', 'nrcs', 'nrc'],
 'd': ['nrdc-gr', 'nrdc', 'nrd1', 'nrd'],
 'e': ['nrenum.net', 'nrep', 'nre'],
 'f': ['nrf1', 'nrfc', 'nrf'],
 'g': ['nrg360', 'nrg'],
 'h': ['nrh2o', 'nrhs', 'nrh'],
 'i': ['nripatindravarman',
       'nriputungavarman',
       'nrisinghapur',
       'nrithasala',
       'nrityagram',
       'nripendra',
       'nritoday',
       'nri-igbo',
       'nritya',
       'nrip1',
       'nrip2',
       'nric',
       'nri'],
 'j': ['nrj'],
 'k': ['nrk2', 'nrk1', 'nrk3', 'nrk'],
 'l': ['nrlmsise-00', 'nrla'],
 'm': ['nrma', 'nrm'],
 'n': ['nrnadzor', 'nrn1', 'nrn'],
 'o': ['nrounde', 'nroff', 'nron', 'nroc', 'nro'],
 'p': ['nrps', 'nrpc', 'nrpn', 'nrp'],
 'r': ['nrrc', 'nrrl', 'nrrd', 'nrr'],
 's': ['nrsn2', 'nrsn1', 'nrs-2', 'nrsa', 'nrsp', 'nrst', 'nrsc', 'nrs'],
 't': ['nrtl', 'nrta', 'nrt'],
 'u': ['nrusinhavatar', 'nru'],
 'v': ['nrv'],
 'w': ['nrw-express', 'nrw.invest', 'nrw-liga', 'nrw.bank'],
 'x': ['nrxn2', 'nrxn1', 'nrxn3', 'nrx'],
 'y': ['nry'],
 'z': ['nrz']}
