
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nk = {'_': ['nk-33', 'nk.pl', 'nk-92', 'nk-15', 'nk012'],
 'a': ['nkalambata',
       'nkambule',
       'nkangamo',
       'nkangala',
       'nkantolo',
       'nkabinde',
       'nkalagu',
       'nkandla',
       'nkawkaw',
       'nkain1',
       'nkaiti',
       'nkambe',
       'nkamba',
       'nkange',
       'nkawie',
       'nkara',
       'nkana',
       'nkalu',
       'nkayi',
       'nkaya',
       'nkam',
       'nkau',
       'nka'],
 'b': ['nkb'],
 'c': ['nkc'],
 'e': ['nkenglicock', 'nkenda', 'nkechi', 'nketia', 'nketa', 'nkem', 'nke'],
 'f': ['nkfc', 'nkf'],
 'g': ['nkg2d', 'nkg2', 'nkg7'],
 'h': ['nkhotakota', 'nkhaba', 'nkhoma', 'nkhs'],
 'i': ['nkilongo',
       'nkidongi',
       'nkialwa',
       'nkinora',
       'nkiras2',
       'nkinga',
       'nkinto',
       'nkisi',
       'nkima',
       'nkimi',
       'nkia',
       'nkio',
       'nki'],
 'k': ['nkk'],
 'l': ['nkl-26'],
 'm': ['nkm'],
 'n': ['nkn'],
 'o': ['nkolbissonia',
       'nkoarisambu',
       'nkokonjeru',
       'nkosinkulu',
       'nkongsamba',
       'nkolafamba',
       'nkowankowa',
       'nkoaranga',
       'nkolabona',
       'nkondjock',
       'nkong-zem',
       'nkolmetet',
       'nkoanrua',
       'nkongoro',
       'nkoltang',
       'nkoranza',
       'nkourani',
       'nkosana',
       'nkoteng',
       'nkotbsb',
       'nkomode',
       'nkoroo',
       'nkoebe',
       'nkoana',
       'nkonko',
       'nkondi',
       'nkonya',
       'nkomo',
       'nkosi',
       'nkolo',
       'nkozi',
       'nkok',
       'nkor',
       'nkom',
       'nko'],
 'p': ['nkporo', 'nkpor', 'nkpa', 'nkp'],
 'r': ['nkrankwanta', 'nkrumaism', 'nkrutkru', 'nkroful', 'nkrumah', 'nkrf'],
 's': ['nksp', 'nks'],
 't': ['nktr'],
 'u': ['nkurunziza',
       'nkurenkuru',
       'nkunumbi',
       'nkuhungu',
       'nkunga',
       'nkumba',
       'nkubu',
       'nkum',
       'nkuv'],
 'v': ['nkvd'],
 'w': ['nkwelle-ezunaka',
       'nkwidze',
       'nkwareu',
       'nkwanta',
       'nkwerre',
       'nkwifa',
       'nkwesi',
       'nkwene',
       'nkwain',
       'nkwala',
       'nkwe'],
 'x': ['nkx2-2as',
       'nkx2-3',
       'nkx6-2',
       'nkx2-2',
       'nkx3-2',
       'nkx6-1',
       'nkx3-3',
       'nkx3-1'],
 'y': ['nky']}
