
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cw = {'_': ['cw_postcode_area',
       'cw_dos_hermanas',
       'cw_chu_college',
       'cw_hood_yachts'],
 'a': ['cwaliny,_warmian-masurian_voivodeship',
       'cwa_cruiserweight_championship',
       'cwaliny,_podlaskie_voivodeship',
       'cwa_heavyweight_championship',
       'cwa_television_championship',
       'cwa_international_dagger',
       'cwa_historical_dagger',
       'cwa_rest_house'],
 'f': ['cwf_heavyweight_championship'],
 'i': ['cwi_bwamu_language', 'cwichelm_of_wessex'],
 'm': ['cwmgors_transmitting_station',
       'cwmllynfell_railway_station',
       'cwm-y-glo_railway_station',
       'cwmtawe_community_school',
       'cwmamman_urban_district',
       'cwmbran_railway_station',
       'cwmbach_railway_station',
       'cwmmawr_railway_station',
       'cwmcarn_railway_station',
       'cwmystwyth_grits_group',
       'cwmamman_united_a.f.c.',
       'cwm_clydach,_kidwelly',
       'cwmdu_railway_station',
       'cwm_wanderers_a.f.c.',
       'cwm_craig-ddu_quarry',
       'cwm_cydfin,_leckwith',
       'cwmbran_bus_station',
       'cwmbran_celtic_f.c.',
       'cwmbran_town_a.f.c.',
       'cwmcarn_high_school',
       'cwm_railway_station',
       'cwm,_blaenau_gwent',
       'cwm_welfare_a.f.c.',
       'cwm_bach,_sychpant',
       'cwm_prysor_viaduct',
       'cwm_pennant_fault',
       'cwm_du_woodlands',
       'cwm_risca_meadow',
       'cwm_albion_f.c.',
       'cwm_ebol_quarry',
       'cwm_llwyd_fault'],
 't': ['cwts_leiden_ranking', 'cwt_kaleva_travel'],
 'u': ['cwusa_television_championship']}
