
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bb = {'_': ['bb_publications',
       'bb_gandanghari',
       'bb&t_ballpark',
       'bb_microlight',
       'bb&t_classic',
       'bb_phoenicis',
       'bb_flashback',
       'bb&t_center',
       'bb&t_arena',
       'bb_airways',
       'bb_biotech',
       'bb_doradus',
       'bb_brunes',
       'bb_queen',
       'bb_steal',
       'bb_cream',
       'bb_talk',
       'bb_keet',
       'bb_good',
       'bb_gun',
       'bb_jay'],
 'a': ['bbanlam_pingyim', 'bball_cordoba', 'bbaale_county'],
 'b': ['bbb_bench'],
 'c': ['bbc_monthey-chablais',
       'bbc_northamptonshire',
       'bbc_controversies',
       'bbc_entertainment',
       'bbc_philharmonic',
       'bbc_studioworks',
       'bbc_parliament',
       'bbc_television',
       'bbc_monitoring',
       'bbc_manchester',
       'bbc_multimedia',
       'bbc_birmingham',
       'bbc2_playhouse',
       'bbc_chartering',
       'bbc_residence',
       'bbc_breakfast',
       'bbc_knowledge',
       'bbc_mindgames',
       'bbc_lifestyle',
       'bbc_magdeburg',
       'bbc_yorkshire',
       'bbc_worldwide',
       'bbc_soundcrew',
       'bbc_diekirch',
       'bbc_gujarati',
       'bbc_bitesize',
       'bbc_romanian',
       'bbc_archives',
       'bbc_wildlife',
       'bbc_learning',
       'bbc_lausanne',
       'bbc_newsline',
       'bbc_midlands',
       'bbc_scotland',
       'bbc_gaidhlig',
       'bbc_webwise',
       'bbc_persian',
       'bbc_america',
       'bbc_records',
       'bbc_schools',
       'bbc_charter',
       'bbc_singers',
       'bbc_weather',
       'bbc_academy',
       'bbc_iplayer',
       'bbc_english',
       'bbc_history',
       'bbc_studios',
       'bbc_arabic',
       'bbc_living',
       'bbc_master',
       'bbc_london',
       'bbc_canada',
       'bbc_switch',
       'bbc_nepali',
       'bbc_online',
       'bbc_sounds',
       'bbc_bangla',
       'bbc_select',
       'bbc_janala',
       'bbc_chorus',
       'bbc_brasil',
       'bbc_choice',
       'bbc_sudost',
       'bbc_player',
       'bbc_alerts',
       'bbc_pashto',
       'bbc_sussex',
       'bbc_oxford',
       'bbc_earth',
       'bbc_sport',
       'bbc_japan',
       'bbc_hausa',
       'bbc_first',
       'bbc_radio',
       'bbc_redux',
       'bbcu_f.c.',
       'bbc_micro',
       'bbc_store',
       'bbc_basic',
       'bbc_trust',
       'bbc_essex',
       'bbc_prime',
       'bbc_north',
       'bbc_south',
       'bbc_china',
       'bbc_books',
       'bbc_nitia',
       'bbc_music',
       'bbc_board',
       'bbc_hindi',
       'bbc_three',
       'bbc_mundo',
       'bbc_news',
       'bbc_alba',
       'bbc_food',
       'bbc_2002',
       'bbc_uktv',
       'bbc_kids',
       'bbc_urdu',
       'bbc_shop',
       'bbc_brit',
       'bbc_film',
       'bbc_four',
       'bbc_west',
       'bbc_east',
       'bbc_box',
       'bbc_jam',
       'bbc_two',
       'bbc_cwr',
       'bbc_one',
       'bbc_os',
       'bbc_2w',
       'bbc_hd'],
 'd': ['bbdo', 'bbdd', 'bbd'],
 'e': ['bbe-like_enzymes'],
 'f': ['bbf_tv'],
 'g': ['bbgky_hierarchy', 'bbg_academy'],
 'h': ['bbh_75'],
 'i': ['bbi_judgement', 'bbi_centar', 'bbi_films'],
 'k': ['bbk_electronics', 'bbk_bms'],
 'l': ['bbl_championship',
       'bbl_churchill',
       'bbl_pipeline',
       'bbl_trophy',
       'bbl_cup',
       'bbl_tv'],
 'm': ['bbmak', 'bbmg', 'bbm'],
 'n': ['bbn_butterfly', 'bbn_music', 'bbn_lisp'],
 'o': ['bbonhel_bala',
       'bboom_bboom',
       'bbo_114',
       'bbo_478',
       'bbo_378',
       'bbo_113',
       'bbo_214',
       'bbo_729',
       'bbo_181',
       'bbo_12',
       'bbo_81',
       'bbo_82'],
 'p': ['bbpr', 'bbp'],
 'q': ['bbq_pitmasters', 'bbq_chickens', 'bbq_brawl', 'bbq_blitz', 'bbq_champ'],
 'r': ['bbr_construction'],
 's': ['bbs_kraftfahrzeugtechnik',
       'bbs_paranoicos',
       'bbs_door',
       'bbs_tv',
       'bbs_2'],
 't': ['bbts_bielsko-biala'],
 'u': ['bburago', 'bbu'],
 'v': ['bbva_provincial',
       'bbva_argentina',
       'bbva_mexico',
       'bbva_peru',
       'bbv_hagen',
       'bbva_usa'],
 'w': ['bbwc', 'bbwr', 'bbw'],
 'x': ['bbx'],
 'y': ['bby_limited']}
