
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ue = {'_': ['ue_castelldefels',
       'ue..._paisano!',
       'ue_santboiana',
       'ue_extremenya',
       "ue_l'estartit",
       'ue_engordany',
       'ue_rapitenca',
       'ue_vilajuiga',
       'ue_figueres',
       'ue_cornella',
       'ue_tarrega',
       'ue_alcudia',
       'ue_lleida',
       'ue-li_pen',
       'ue_sants',
       'ue_valls',
       'ue_avia',
       'ue_boom',
       'ue_rubi',
       'ue_roll',
       'ue_olot',
       'ue_news',
       'ue_900',
       'ue_vic'],
 'a': ['uea_broad'],
 'b': ['uebelmannia_pectinifera',
       'uebelmannia_buiningii',
       'uebelmannia_gummifera',
       'uebayashi_station',
       'uebert_angel',
       'ueba_esou'],
 'c': ['ueckermunde_station',
       'ueckermunde_heath',
       'uecht_observatory',
       'uec-perm_engines',
       'uecker_monument',
       'uec_preston',
       'uec_saturn'],
 'd': ['uedahara_station',
       'ueda_soko-ryu',
       'uedai_station',
       'ueda_station',
       'uedo_station',
       'ueda,_nagano',
       'ueda_glacier',
       'ueda_akinari',
       'ueda_arisawa',
       'ueda_domain',
       'ueda_castle',
       'ueda_soko'],
 'e': ['ueekenkcoracias', 'ueekata', 'uee'],
 'f': ['uefa_competitions',
       'uefa_coefficient',
       'uefa_challenge',
       'uefa_congress',
       'uefa_striker',
       'uefa_league',
       'uefa_2010'],
 'g': ['uegitglanis_zammaranoi'],
 'h': ['uehling,_nebraska',
       'uehling_potential',
       'uehara,_shibuya',
       'uehara_yusaku'],
 'i': ['uei_college'],
 'j': ['uejima_onitsura'],
 'k': ['uekusa_university', 'ueki,_kumamoto', 'ueki_station', 'ueki_emori'],
 'l': ['uelzen-langwedel_railway',
       'ueli_tualaulelei',
       'ueli_scheidegger',
       'ueli_gegenschatz',
       'ueli_leuenberger',
       'uelia_sepidapex',
       'ueli_kestenholz',
       'uelzen_station',
       'ueli_bodenmann',
       'ueli_schenkel',
       'ueli_schnider',
       'ueli_schibler',
       'ueli_bachmann',
       'uele_district',
       'uele_province',
       'ueli_hofmann',
       'ueli_steiger',
       'ueleni_fono',
       'uel_eubanks',
       'ueli_maurer',
       'ueli_sutter',
       'ueli_isler',
       'uel_graham',
       'ueli_steck',
       'ueli_mulli',
       'ueli_staub',
       'ueli_wiget',
       'uele_river',
       'ueli_matti',
       'ueli_aebi',
       'uel_key'],
 'm': ['uemura_masakatsu',
       'uemoa_tournament',
       'uematsu_station',
       'uemachi_plateau',
       'uemura_masahisa',
       'uemura_station',
       'uemura_iemasa',
       'uemura_shoen',
       'uem_edgenta',
       'uemon_ikeda',
       'uem_group'],
 'n': ['ueno-okachimachi_station',
       'ueno-hirokoji_station',
       'uenoshiba_station',
       'uenohara_station',
       'ueno-tokyo_line',
       'uenoshi_station',
       'ueno_tsuruhime',
       'ueno_daibutsu',
       'ueno,_okinawa',
       'uenohara_site',
       'ueng_ming-yih',
       'ueno_tosho-gu',
       'uenae_station',
       'ueno_station',
       'ueno,_gunma',
       'ueno_hikoma',
       'uendi_vecaj',
       'ueno_route',
       'ueno_park',
       'ueno,_mie',
       'ueno_zoo',
       'ueno_dam'],
 'p': ['uep_systems'],
 'r': ['uerikon-bauma_railway',
       'uerikondjera_kasaona',
       'uerdingen_railbus',
       'uerdingen_hoard',
       'uerdingen_line',
       'uerdi_mara',
       'uere_river'],
 's': ['uesugi_tsunakatsu',
       'uesugi_kagekatsu',
       'uesugi_mochinori',
       'uesugi_norimasa',
       'uesugi_narinori',
       'uesugi_harunori',
       'uesugi_kagenobu',
       'uesugi_sadazane',
       'uesugi_kagetora',
       'uesugi_norizane',
       'uesugi_tomooki',
       'uesugi_akisada',
       'uesugi_kenshin',
       'uesugi_zenshu',
       'uesugi_clan',
       'uesu_gewog'],
 't': ['uetliberg_tv-tower',
       'uetersen_airfield',
       'ueta_solomona',
       'ueta_station',
       'uetz_pelikan'],
 'v': ['uevld', 'uev'],
 'w': ['uew'],
 'x': ['uexkull', 'uext'],
 'y': ['ueyama'],
 'z': ['uezu_house']}
