
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uy = {'_': ['uy_volantis', 'uy_scuti'],
 'a': ['uyandik,_kovancilar',
       'uyanga,_ovorkhangai',
       'uyaiedu_ikpe-etim',
       'uyanwatte_stadium',
       'uyarndha_manithan',
       'uyanik,_saraykoy',
       'uyarsky_district',
       'uyanga_language',
       'uyagawa_station',
       'uyarndha_ullam',
       'uyama_hisakane',
       'uyarthiru_420',
       'uya_language',
       'uyama_hiroto',
       'uyanga_bold',
       'uyajola_9/9',
       'uya_oron',
       'uya_oro'],
 'b': ['uybulatovo'],
 'c': ['uychi_district'],
 'd': ['uydenia', 'uydo'],
 'e': ['uyedineniya_island',
       'uyea,_northmavine',
       'uyenanao_lake',
       'uyea,_unst',
       'uyen_linh'],
 'g': ['uyghur_nationalism',
       'uyghur_literature',
       'uyghur_alphabets',
       'uyghur_phonology',
       'uyghur_americans',
       'uyghur_khaganate',
       'uyghur_tribunal',
       'uyghur_timeline',
       'uyghur_genocide',
       'uyghur_language',
       'uyghur_dialects',
       'uygur_district',
       'uyghur_grammar',
       'uyghur_cuisine',
       'uygur,_amasya',
       'uyghur_riots',
       'uygur,_kulp'],
 'i': ['uyirile_kalanthathu',
       'uyirullavarai_usha',
       'uyirukku_uyiraga',
       'uyirodu_uyiraga',
       'uyire_unakkaga',
       'uyira_maanama',
       'uyire_uyire'],
 'l': ['uylupinar,_golhisar'],
 'm': ['uymen'],
 'n': ['uynehchi', 'uynarey'],
 'o': ["uyongu_yata'uyungana",
       'uyo-gakuen_college',
       'uyoku_dantai',
       'uyo_meyo'],
 's': ['uysky_district', 'uys_krige'],
 't': ['uytash_airport'],
 'u': ['uyuk-tarlak_inscription',
       'uyucek,_kizilcahamam',
       'uyuklutatar,_edirne',
       'uyuni_municipality',
       'uyucek,_kastamonu',
       'uyurca,_kalecik',
       'uyuk,_golpazari',
       'uyunid_dynasty',
       'uyun_al-hammam',
       'uyunid_emirate',
       'uyun_al-akhbar',
       'uyui_district',
       'uyuni_airport',
       'uyun_al-wadi',
       'uyun_sahira',
       "uyu_k'uchu",
       'uyu_river',
       'uyu_uyu'],
 'v': ['uyvar_eyalet'],
 'w': ['uywa'],
 'y': ['uyyakondan_thirumalai', 'uyyala_jampala']}
