
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oj = {'_': ['oj_porteria', 'oj_mariano', 'oj_igmane', 'oj_borg', 'oj_287'],
 'a': ['ojamanga_yamada-kun',
       'ojala,_california',
       'ojai,_california',
       'ojars_grinbergs',
       'ojaotsa_springs',
       'oja-beyt,_iran',
       'ojamajo_doremi',
       'ojars_vacietis',
       'ojakgyo_family',
       'ojaq_qeshlaqi',
       'ojaswi_aroraa',
       'oja,_gotland',
       'ojars_silins',
       'ojaq_qeshlaq',
       'ojaq_alazar',
       'oja_station',
       'ojah_awake',
       'oja_church',
       "oja's_rule",
       'ojaq_kandi',
       'oja_kodar',
       'ojak_sar'],
 'b': ['ojb_jezreel'],
 'c': ['ojciec_krolowej',
       'ojciec_mateusz',
       'ojcow_castle',
       'ojc_rosmalen',
       'ojcowa_wola'],
 'd': ['ojd_morocco'],
 'e': ['ojembe_olatuga', 'ojendorfer_see', 'ojeda_beach', 'ojeby_if'],
 'h': ['ojha'],
 'i': ['ojinaga_municipality',
       'ojika-kogen_station',
       'oji-kamiya_station',
       'oji-cree_language',
       'ojibwa,_wisconsin',
       'ojibway,_missouri',
       'ojinaga_formation',
       'ojibwe_phonology',
       'oji-koen_station',
       'ojito_wilderness',
       'ojimaya_station',
       'ojiyama_stadium',
       'ojibwe_language',
       'ojibwe_dialects',
       'ojika,_nagasaki',
       'ojiya,_niigata',
       'ojibwe_grammar',
       'ojika_airport',
       'ojiya_station',
       'ojiyama_kofun',
       'ojima_station',
       'ojiako_ezenne',
       'ojie_edoburun',
       'ojin_seamount',
       'oji_umozurike',
       'ojibway_club',
       'ojima_domain',
       'ojima,_gunma',
       'ojima_lactam',
       'ojima_river',
       'ojinaga_cut',
       'oji_station',
       'oji_shrine',
       'oji,_nara',
       'oji_hiroi',
       'oji_river'],
 'j': ['ojjeh'],
 'k': ['ojkovica', 'ojkroken', 'ojkanje', 'ojk'],
 'm': ['ojm'],
 'n': ['ojnowrd'],
 'o': ['ojocaliente,_zacatecas',
       'ojokojo_torunarigha',
       'ojosan_shacho',
       'ojo_caliente',
       'ojo_maduekwe',
       'ojos_negros',
       'ojo_guarena',
       'ojos_azules',
       'ojomo_oluda',
       'ojo,_lagos',
       'ojo_taylor',
       'ojos_locos',
       'ojos_asi',
       'ojo_ade'],
 'r': ['ojrzanow-towarzystwo', 'ojrzanowo', 'ojrzanow'],
 's': ['ojstrica,_dravograd',
       'ojstro,_trbovlje',
       'ojstrica_castle',
       'ojstro,_lasko',
       'ojstriska_vas',
       'ojsc_dolomite',
       'ojstri_vrh'],
 't': ['ojt_eltoba'],
 'u': ['ojuelegba,_lagos',
       'ojuwoye,_mushin',
       'ojugbelu_arere',
       'ojus,_florida',
       'ojuela_bridge',
       'oju,_estonia',
       'oju,_nigeria',
       'oju_chosan'],
 'v': ['ojvind_moestrup', 'ojvind_larsen', 'ojvind_winge'],
 'w': ['ojw']}
