
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mg = {'_': ['mg_motors_pakistan',
       'mg_motor_india',
       'mg_rover_group',
       'mg_151_cannon',
       'mg.k_vis_vpm',
       'mg_ff_cannon',
       'mg_xpower_sv',
       'mg_car_club',
       'mg_mg_aye',
       'mg_18_tuf',
       'mg_39_rh'],
 'a': ['mga_nagbabagang_bulaklak',
       'mga_awiting_pilipino',
       'mga_ibong_mandaragit',
       'mgarr_ix-xini_tower',
       'mga_mumunting_lihim',
       'mgarr_united_f.c.',
       'mga_basang_sisiw'],
 'e': ['mgeni_jadi_kadika'],
 'i': ['mgic_investment_corporation', 'mginskoye_urban_settlement'],
 'm': ['mgm_resorts_international',
       'mgm_animation/visual_arts',
       'mgm_resorts_championship',
       'mgm/ua_premiere_network',
       "mgm_children's_matinees",
       'mgm_home_entertainment',
       'mgm_growth_properties',
       'mgm_northfield_park',
       'mgm_national_harbor',
       'mgm_grand_detroit',
       'mgm_model_school',
       'mgm_dizzee_world',
       'mgm_farm_arena',
       'mgm_grand_fire'],
 'p': ['mgp-15_submachine_gun',
       'mgp_submachine_gun',
       'mgp_nordic_2007',
       'mgp_nordic_2006',
       'mgp_nordic_2009',
       'mgp_nordic_2008',
       'mgp_nordic_2002',
       'mgp_of_indiana'],
 'r': ['mgr-3_little_john', 'mgr-1_honest_john'],
 'u': ['mguu_wa_zuberi'],
 'w': ['mgwr_class_d-bogie',
       'mgwr_class_7-12',
       'mgwr_class_12',
       'mgwr_class_1',
       'mgwr_class_e',
       'mgwr_class_a',
       'mgwr_class_p',
       'mgwr_class_9',
       'mgwr_class_w',
       'mgwr_class_6',
       'mgwr_class_b',
       'mgwr_class_l',
       'mgwr_class_k',
       'mgwr_class_d',
       'mgwr_class_h',
       'mgwr_class_7']}
