
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yp = {'a': ['ypacarai',
       'ypakoe',
       'ypaja',
       'ypato',
       'ypadu',
       'ypard',
       'ypati',
       'ypane',
       'ypa'],
 'b': ['ypbpr'],
 'c': ['ypcc'],
 'd': ['ypd'],
 'e': ['ypecolsga', 'ypehu', 'ypel3'],
 'f': ['ypfb', 'ypfl', 'ypf'],
 'h': ['yphthimoides'],
 'l': ['yplan', 'ypl'],
 'o': ['ypotagmatarchis',
       'yponomeutoidea',
       'yponomeutinae',
       'ypolochagos',
       'yponomeuta',
       'ypotryll',
       'ypops!',
       'yport',
       'ypo'],
 'p': ['yppah', 'ypp'],
 'r': ['ypreville-biville',
       'ypresiosirex',
       'ypresiomyrma',
       'ypresian',
       'yproxy',
       'ypres'],
 's': ['ypsilothuriidae',
       'ypsilonigaster',
       'ypsolophidae',
       'ypsotingini',
       'ypsilomena',
       'ypsilandra',
       'ypsigrock',
       'ypsilopus',
       'ypsolopha',
       'ypsonas',
       'ypsora',
       'yps'],
 't': ['ypthimomorpha', 'ypthima'],
 'u': ['ypupiara', 'ypu'],
 'y': ['ypypuera']}
