
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bn = {'_': ['bn_vocational_school', 'bn_postcode_area'],
 'c': ['bnc_network_hd',
       'bncr_class_a',
       'bncr_class_s',
       'bncr_class_n',
       'bncr_class_b'],
 'e': ['bnei_herzliya_basket',
       'bnei_yehuda_ground',
       'bnei_sakhnin_f.c.',
       'bnei_eilat_f.c.',
       'bnei_yehud_f.c.'],
 'f': ['bnf_francais_25516', 'bnf_francais_794', 'bnf_fr._113-116'],
 'i': ['bnin,_wloclawek_county',
       'bni_gmil_maksouline',
       'bni_ounjel_tafraout',
       'bni_ahmed_imoukzan',
       'bnin,_naklo_county',
       'bni_ahmed_gharbia',
       'bni_ahmed_cherqia',
       'bni_sidel_louta',
       'bni_sidel_jbel'],
 'o': ['bnot_netanya_f.c.', 'bnot_sakhnin_f.c.', 'bnot_eilat_f.c.'],
 'p': ['bnp_paribas_showdown', 'bnp_paribas_fortis', 'bnp_paribas_cib'],
 'r': ['bnr_class_hsg', 'bnr_class_nm', 'bnr_class_p', 'bnr_class_n'],
 's': ['bnsf_police_department',
       'bns_shaheed_moazzem',
       'bnsd_inter_college',
       'bns_shaheed_daulat',
       'bns_somudra_avijan',
       'bnsf_barstow_yard',
       'bns_sheikh_hasina',
       'bns_haji_mohshin',
       'bns_sheikh_mujib',
       'bns_abu_ubaidah',
       'bns_umar_farooq',
       'bns_somudra_joy',
       'bns_ali_haider',
       'bns_issa_khan',
       'bns_abu_bakr'],
 'y': ['bny_mellon_center']}
