
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-19T19:25:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b36285ca7fb7c4bd8a93d82343c9395c443bd039",
 "version": "0.2.25.post0.dev33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
