# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tecton_proto/dataobs/metric.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tecton_proto/dataobs/metric.proto',
  package='tecton_proto.dataobs',
  syntax='proto2',
  serialized_options=b'\n\022com.tecton.dataobsP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!tecton_proto/dataobs/metric.proto\x12\x14tecton_proto.dataobs\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n\x0bMetricValue\x12!\n\x0c\x66\x65\x61ture_name\x18\x01 \x01(\tR\x0b\x66\x65\x61tureName\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value\"\xa5\x01\n\x0fMetricDataPoint\x12J\n\x13interval_start_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x11intervalStartTime\x12\x46\n\rmetric_values\x18\x02 \x03(\x0b\x32!.tecton_proto.dataobs.MetricValueR\x0cmetricValues*\xba\x01\n\nMetricType\x12\x17\n\x13METRIC_TYPE_UNKNOWN\x10\x00\x12\x12\n\x0e\x43OUNT_DISTINCT\x10\x01\x12\x0e\n\nCOUNT_ROWS\x10\x02\x12\x0f\n\x0b\x43OUNT_NULLS\x10\x03\x12\r\n\tAVG_VALUE\x10\x04\x12\r\n\tMAX_VALUE\x10\x05\x12\r\n\tMIN_VALUE\x10\x06\x12\x0e\n\nVAR_SAMPLE\x10\x07\x12\x11\n\rSTDDEV_SAMPLE\x10\x08\x12\x0e\n\nAVG_LENGTH\x10\t*4\n\x11QueryMetricStatus\x12\x1f\n\x1bQUERY_METRIC_STATUS_UNKNOWN\x10\x00\x42\x16\n\x12\x63om.tecton.dataobsP\x01'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_METRICTYPE = _descriptor.EnumDescriptor(
  name='MetricType',
  full_name='tecton_proto.dataobs.MetricType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='METRIC_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COUNT_DISTINCT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COUNT_ROWS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COUNT_NULLS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AVG_VALUE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MAX_VALUE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MIN_VALUE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VAR_SAMPLE', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STDDEV_SAMPLE', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AVG_LENGTH', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=333,
  serialized_end=519,
)
_sym_db.RegisterEnumDescriptor(_METRICTYPE)

MetricType = enum_type_wrapper.EnumTypeWrapper(_METRICTYPE)
_QUERYMETRICSTATUS = _descriptor.EnumDescriptor(
  name='QueryMetricStatus',
  full_name='tecton_proto.dataobs.QueryMetricStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='QUERY_METRIC_STATUS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=521,
  serialized_end=573,
)
_sym_db.RegisterEnumDescriptor(_QUERYMETRICSTATUS)

QueryMetricStatus = enum_type_wrapper.EnumTypeWrapper(_QUERYMETRICSTATUS)
METRIC_TYPE_UNKNOWN = 0
COUNT_DISTINCT = 1
COUNT_ROWS = 2
COUNT_NULLS = 3
AVG_VALUE = 4
MAX_VALUE = 5
MIN_VALUE = 6
VAR_SAMPLE = 7
STDDEV_SAMPLE = 8
AVG_LENGTH = 9
QUERY_METRIC_STATUS_UNKNOWN = 0



_METRICVALUE = _descriptor.Descriptor(
  name='MetricValue',
  full_name='tecton_proto.dataobs.MetricValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_name', full_name='tecton_proto.dataobs.MetricValue.feature_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='featureName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='tecton_proto.dataobs.MetricValue.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='value', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=162,
)


_METRICDATAPOINT = _descriptor.Descriptor(
  name='MetricDataPoint',
  full_name='tecton_proto.dataobs.MetricDataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='interval_start_time', full_name='tecton_proto.dataobs.MetricDataPoint.interval_start_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='intervalStartTime', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metric_values', full_name='tecton_proto.dataobs.MetricDataPoint.metric_values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='metricValues', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=330,
)

_METRICDATAPOINT.fields_by_name['interval_start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_METRICDATAPOINT.fields_by_name['metric_values'].message_type = _METRICVALUE
DESCRIPTOR.message_types_by_name['MetricValue'] = _METRICVALUE
DESCRIPTOR.message_types_by_name['MetricDataPoint'] = _METRICDATAPOINT
DESCRIPTOR.enum_types_by_name['MetricType'] = _METRICTYPE
DESCRIPTOR.enum_types_by_name['QueryMetricStatus'] = _QUERYMETRICSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetricValue = _reflection.GeneratedProtocolMessageType('MetricValue', (_message.Message,), {
  'DESCRIPTOR' : _METRICVALUE,
  '__module__' : 'tecton_proto.dataobs.metric_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.dataobs.MetricValue)
  })
_sym_db.RegisterMessage(MetricValue)

MetricDataPoint = _reflection.GeneratedProtocolMessageType('MetricDataPoint', (_message.Message,), {
  'DESCRIPTOR' : _METRICDATAPOINT,
  '__module__' : 'tecton_proto.dataobs.metric_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.dataobs.MetricDataPoint)
  })
_sym_db.RegisterMessage(MetricDataPoint)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
