
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ss = {'_': ['ss-oberst-gruppenfuhrer',
       'ss-totenkopfverbande',
       'ss-stabsscharfuhrer',
       'ss-verfugungstruppe',
       'ss-ehrendolch',
       'ss-ehrenring',
       'ss-leitheft',
       'ss.12/as.12',
       'ss-bewerber',
       'ss-kaliert',
       'ss-general',
       'ss-n-23',
       'ss-n-22',
       'ss-103',
       'ss-101',
       'ss-100',
       'ss-102',
       'ss18l1',
       'ss220',
       'ss-77',
       'ss-11',
       'ss-50',
       'ss.11',
       'ss-42',
       'ss316',
       'ss584',
       'ss-48',
       'ss-21',
       'ss304',
       'ss-gb',
       'ss-35',
       'ss-36',
       'ss501',
       'ss-78',
       'ss235',
       'ss.10',
       'ss-45',
       'ss234',
       'ss18',
       'ss13',
       'ss-2',
       'ss12',
       'ss4',
       'ss9',
       'ss5',
       'ss6',
       'ss7',
       'ss8',
       'ss1',
       'ss3'],
 'a': ['ssangmun-dong',
       'ssanghwa-tang',
       'ssangnim-dong',
       'ssangchungsa',
       'ssangbongsa',
       'ssanggyesa',
       'ssangnyuk',
       'ssabagabo',
       'ssaurabi',
       'ssamjang',
       'ssanin',
       'ssajib',
       'ssak3',
       'ssaki',
       'ssaws',
       'ssahe',
       'ssafa',
       'ssap',
       'ssa2',
       'ssas',
       'ssam',
       'ssaa',
       'ssac',
       'ssao',
       'ssat',
       'ssab',
       'ssau',
       'ssa'],
 'b': ['ssbp2', 'ssbp4', 'ssbp1', 'ssbp3', 'ssbc', 'ssbr', 'ssb'],
 'c': ['sscac', 'ssc4d', 'sscs', 'sscp', 'ssca', 'ssci', 'ssce', 'sscc', 'ssc'],
 'd': ['ssdc', 'ssdf', 'ssdo', 'ssdt', 'ssdp', 'ssdm', 'ssdd'],
 'e': ['sseugaechima',
       'ssentamu',
       'ssense',
       'sseal',
       'ssec',
       'sse4',
       'sse2',
       'ssep',
       'ssem',
       'sse5',
       'sse3',
       'sse'],
 'f': ['ssfcu', 'ssfa2', 'ssfc', 'ssfa', 'ssfp', 'ssfl', 'ssf'],
 'g': ['ssgc', 'ssg'],
 'h': ['ssh-keygen',
       'ssh-agent',
       'sshivada',
       'ssh-68',
       'ssh-60',
       'ssh-36',
       'sshfs',
       'ssh1',
       'sshl',
       'ssh3',
       'ssh2'],
 'i': ['ssingssing',
       'ssireum',
       'ssipsis',
       'ssion',
       'ssies',
       'ssis',
       'ssit',
       'ssi'],
 'j': ['ssj'],
 'k': ['ssk'],
 'l': ['sslbridge', 'ssleay', 'ssliop', 'ssla', 'sslt', 'sslp', 'ssl'],
 'm': ['ssmem1', 'ssmis', 'ssm6a', 'ssml', 'ssm'],
 'n': ['ssn'],
 'o': ['ssop', 'ssot', 'ssoc', 'sso'],
 'p': ['sspe', 'sspf', 'ssps', 'sspc', 'sspa', 'sspl', 'sspt', 'ssp'],
 'q': ['ssq'],
 'r': ['ssr-180,711',
       'ssr-180,575',
       'ssrf',
       'ssr2',
       'ssrc',
       'ssr4',
       'ssrs',
       'ssrl',
       'ssrg',
       'ssrm',
       'ssr1',
       'ssra',
       'ssr'],
 's': ['ssss.dynazenon',
       'ssss.gridman',
       'sssnakepit',
       'sssshhh...',
       'sssh.com',
       'sssnake',
       'sssssss',
       'ssssh',
       'ssse3',
       'sssd',
       'sssm',
       'sssl',
       'ssss',
       'sssa',
       'sss*',
       'sssr',
       'sssp',
       'ssst',
       'sssc',
       'sssb',
       'sssf',
       'sssh',
       'sss'],
 't': ['sstream',
       'sstar',
       'sstb',
       'sstv',
       'sstd',
       'ssta',
       'ssth',
       'sstl',
       'sstp',
       'sstc',
       'sst'],
 'u': ['ssukcha', 'ssurgo', 'ssutr2', 'ssukh', 'ssu'],
 'v': ['ssvp', 'ssvm', 'ssv'],
 'w': ['ssw'],
 'x': ['ssx2ip', 'ssx5', 'ssx1', 'ssx6', 'ssx4', 'ssx2', 'ssx'],
 'z': ['ssz-13', 'ssz']}
