
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_iu = {'_': ['iu_videography',
       'iu_filmography',
       'iu_discography',
       'iu_aurigae',
       'iu_wai'],
 'a': ['iuani', 'iuati', 'iuaca', 'iua'],
 'b': ['iubmb_life'],
 'c': ['iucn_category'],
 'd': ['iudiciaria_torrensis'],
 'e': ['iuenka', 'iue'],
 'f': ['iufni', 'iufaa'],
 'g': ['iugani', 'iuga', 'iug'],
 'h': ['iuhetibu_fendy'],
 'i': ['iuiu'],
 'j': ['iujnoe'],
 'k': ['iuka,_mississippi',
       'iuka,_illinois',
       'iuka,_kentucky',
       'iuka,_kansas',
       'iuka,_texas'],
 'l': ['iuliana_gorea-costin',
       'iulian_liublinskii',
       'iultinsky_district',
       'iuliana_pantelimon',
       'iulia_dombrovskaia',
       'iulactis_semifusca',
       'iuliana_cantaragiu',
       'iulota_phauloptila',
       'iuliia_galimullina',
       'iullemmeden_basin',
       'iulota_ochropolia',
       'iuliana_maceseanu',
       'iulius_severianus',
       'iulactis_insignis',
       'iuliia_batenkova',
       'iulian_filipescu',
       'iulon_gagoshidze',
       'iuliia_slobodyan',
       'iulian_pacioianu',
       'iuliia_budaleeva',
       'iulian_anca-trip',
       'iuliu_naftanaila',
       'iulota_triglossa',
       'iuliana_munteanu',
       'iulota_epispila',
       'iuliu_hatieganu',
       'iulian_petrache',
       'iullus_antonius',
       'iulian_mihaescu',
       'iulota_ithyxyla',
       'iuliia_andreeva',
       'iulian_carabela',
       'iulota_bacillum',
       'iulian_teodosiu',
       'iuliia_artemeva',
       'iuliia_morozova',
       'iulian_dumitras',
       'iulian_florescu',
       'iulota_ischnora',
       'iuliana_hobincu',
       'iuliia_shishova',
       'iulian_levinski',
       'iulia_paratova',
       'iulia_traducta',
       'iulian_cristea',
       'iulia_dumanska',
       'iulian_apostol',
       'iulie_aslaksen',
       'iuliana_enescu',
       'iuliu_coroianu',
       'iuliana_colnic',
       'iuliu_hatiegan',
       'iuliu_madarasz',
       'iuliia_kaplina',
       'iulian_chirita',
       'iuliana_buhus',
       'iulian_hartig',
       'iulia_poilova',
       'iulia_olteanu',
       'iulia_petelca',
       'iulian_serban',
       'iuliu_barasch',
       'iuliu_baratky',
       'iuliu_winkler',
       'iulla_antonia',
       'iula_qilanoba',
       'iulian_bursuc',
       'iulian_andrei',
       'iuliia_mendel',
       'iulian_raicea',
       'iuliana_simon',
       'iulian_vesper',
       'iuliana_paleu',
       'iulica_ruican',
       'iulian_mamele',
       'iulian_crivac',
       'iulian_danita',
       'iulian_arhire',
       'iuliu_borbely',
       'iulia_hasdeu',
       'iulius_iancu',
       'iulian_tames',
       'iulian_balan',
       'iulia_leorda',
       'iuliu_hajnal',
       'iulia_necula',
       'iulia_helbet',
       'iuliana_popa',
       'iulian_boiko',
       'iuliu_hirtea',
       'iuliu_bodola',
       'iulian_erhan',
       'iulian_minea',
       'iulian_vladu',
       'iuliu_moisil',
       'iulica_cazan',
       'iulija_osmak',
       'iuliu_farkas',
       'iulian_chifu',
       'iuliu_darok',
       'iulian_mihu',
       'iuliu_oprea',
       'iulia_motoc',
       'iulia_bulie',
       'iulian_ilie',
       'iulius_mall',
       'iulian_popa',
       'iuliu_szocs',
       'iuliu_coste',
       'iulian_rosu',
       'iuliia_maya',
       'iuliu_hossu',
       'iuliu_maniu',
       'iulia_curea',
       'iuliu_ilyes',
       'iuliu_szabo',
       'iuliu_safar',
       'iuliu_jenei',
       'iulian_pop',
       'iuliu_falb',
       'iulian_miu',
       'iuliu_nosa',
       'iuliu_kiss'],
 'm': ['iums', 'ium'],
 'n': ['iuniarra_sipaia', 'iunmin_i'],
 'o': ['iuo'],
 'p': ['iupui_gymnasium',
       'iupui_jaguars',
       'iup_portfolio',
       'iupac_books',
       'iuput_ii',
       'iuput_i'],
 'r': ['iurie_livandovschi',
       'iurii_krakovetskii',
       'iurie_apostolachi',
       'iurik_ogannisian',
       'iurii_bozhynskyi',
       'iurie_bolboceanu',
       'iurie_chirinciuc',
       'iurie_priganiuc',
       'iuri_gabiskiria',
       'iurie_chiorescu',
       'iurii_nozdrunov',
       'iurii_semeniuk',
       'iurie_colesnic',
       'iurie_osipenco',
       'iuri_alcantara',
       'iurii_zakharov',
       'iuri_medeiros',
       "iuri_osip'ovi",
       'iurii_shestak',
       'iurie_turcanu',
       'iurie_miterev',
       'iurii_kostiuk',
       'iurie_muntean',
       'iurie_dudoglo',
       'iurii_cheban',
       'iurii_tsaruk',
       'iurie_ciocan',
       'iurie_leanca',
       'iurie_renita',
       'iuri_lomadze',
       'iurie_bulat',
       'iurie_rosca',
       'iurie_arcan',
       'iurie_darie',
       'iuri_miguel',
       'iuri_leitao',
       'iurii_utkin',
       'iuri_filosi',
       'iuri_akobia',
       'iurie_scala',
       'iurie_mirza',
       'iuri_gomes',
       'iurie_iovu',
       'iurie_tap'],
 's': ['iustin_dyadkovsky',
       'ius_indigenatus',
       'iustin_fratiman',
       'iustin_popescu',
       'ius_singulare',
       'ius_scriptum',
       'ius_naturale',
       'ius_publicum',
       'ius_italicum',
       'ius_abutendi',
       'ius_strictum',
       'ius_privatum',
       'ius_laboris',
       'ius_chasma',
       'ius_latium',
       'ius_utendi'],
 't': ['iuticosaurus', 'iuty', 'iut'],
 'v': ['iuventa_michalovce'],
 'w': ['iuwelot'],
 'z': ['iuzzolino']}
