# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tecton_proto/auth/principal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tecton_proto/auth/principal.proto',
  package='tecton_proto.auth',
  syntax='proto2',
  serialized_options=b'\n\017com.tecton.authP\001Z&github.com/tecton-ai/tecton_proto/auth',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!tecton_proto/auth/principal.proto\x12\x11tecton_proto.auth\"\xdc\x01\n\x0ePrincipalBasic\x12\x32\n\x04user\x18\x03 \x01(\x0b\x32\x1c.tecton_proto.auth.UserBasicH\x00R\x04user\x12Q\n\x0fservice_account\x18\x04 \x01(\x0b\x32&.tecton_proto.auth.ServiceAccountBasicH\x00R\x0eserviceAccount\x12\x35\n\x05group\x18\x05 \x01(\x0b\x32\x1d.tecton_proto.auth.GroupBasicH\x00R\x05groupB\x0c\n\nbasic_info\"\x81\x01\n\tUserBasic\x12\x17\n\x07okta_id\x18\x01 \x01(\tR\x06oktaId\x12\x1d\n\nfirst_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n\tlast_name\x18\x03 \x01(\tR\x08lastName\x12\x1f\n\x0blogin_email\x18\x04 \x01(\tR\nloginEmail\"9\n\x13ServiceAccountBasic\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\"0\n\nGroupBasic\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name*\x82\x01\n\rPrincipalType\x12\x1a\n\x16PRINCIPAL_TYPE_UNKNOWN\x10\x00\x12\x17\n\x13PRINCIPAL_TYPE_USER\x10\x01\x12\"\n\x1ePRINCIPAL_TYPE_SERVICE_ACCOUNT\x10\x02\x12\x18\n\x14PRINCIPAL_TYPE_GROUP\x10\x03\x42;\n\x0f\x63om.tecton.authP\x01Z&github.com/tecton-ai/tecton_proto/auth'
)

_PRINCIPALTYPE = _descriptor.EnumDescriptor(
  name='PrincipalType',
  full_name='tecton_proto.auth.PrincipalType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRINCIPAL_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRINCIPAL_TYPE_USER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRINCIPAL_TYPE_SERVICE_ACCOUNT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRINCIPAL_TYPE_GROUP', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=521,
  serialized_end=651,
)
_sym_db.RegisterEnumDescriptor(_PRINCIPALTYPE)

PrincipalType = enum_type_wrapper.EnumTypeWrapper(_PRINCIPALTYPE)
PRINCIPAL_TYPE_UNKNOWN = 0
PRINCIPAL_TYPE_USER = 1
PRINCIPAL_TYPE_SERVICE_ACCOUNT = 2
PRINCIPAL_TYPE_GROUP = 3



_PRINCIPALBASIC = _descriptor.Descriptor(
  name='PrincipalBasic',
  full_name='tecton_proto.auth.PrincipalBasic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='tecton_proto.auth.PrincipalBasic.user', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='user', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service_account', full_name='tecton_proto.auth.PrincipalBasic.service_account', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='serviceAccount', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='group', full_name='tecton_proto.auth.PrincipalBasic.group', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='group', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='basic_info', full_name='tecton_proto.auth.PrincipalBasic.basic_info',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=57,
  serialized_end=277,
)


_USERBASIC = _descriptor.Descriptor(
  name='UserBasic',
  full_name='tecton_proto.auth.UserBasic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='okta_id', full_name='tecton_proto.auth.UserBasic.okta_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='oktaId', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='tecton_proto.auth.UserBasic.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='firstName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='tecton_proto.auth.UserBasic.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='lastName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='login_email', full_name='tecton_proto.auth.UserBasic.login_email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='loginEmail', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=409,
)


_SERVICEACCOUNTBASIC = _descriptor.Descriptor(
  name='ServiceAccountBasic',
  full_name='tecton_proto.auth.ServiceAccountBasic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tecton_proto.auth.ServiceAccountBasic.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='tecton_proto.auth.ServiceAccountBasic.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=468,
)


_GROUPBASIC = _descriptor.Descriptor(
  name='GroupBasic',
  full_name='tecton_proto.auth.GroupBasic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tecton_proto.auth.GroupBasic.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='tecton_proto.auth.GroupBasic.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=518,
)

_PRINCIPALBASIC.fields_by_name['user'].message_type = _USERBASIC
_PRINCIPALBASIC.fields_by_name['service_account'].message_type = _SERVICEACCOUNTBASIC
_PRINCIPALBASIC.fields_by_name['group'].message_type = _GROUPBASIC
_PRINCIPALBASIC.oneofs_by_name['basic_info'].fields.append(
  _PRINCIPALBASIC.fields_by_name['user'])
_PRINCIPALBASIC.fields_by_name['user'].containing_oneof = _PRINCIPALBASIC.oneofs_by_name['basic_info']
_PRINCIPALBASIC.oneofs_by_name['basic_info'].fields.append(
  _PRINCIPALBASIC.fields_by_name['service_account'])
_PRINCIPALBASIC.fields_by_name['service_account'].containing_oneof = _PRINCIPALBASIC.oneofs_by_name['basic_info']
_PRINCIPALBASIC.oneofs_by_name['basic_info'].fields.append(
  _PRINCIPALBASIC.fields_by_name['group'])
_PRINCIPALBASIC.fields_by_name['group'].containing_oneof = _PRINCIPALBASIC.oneofs_by_name['basic_info']
DESCRIPTOR.message_types_by_name['PrincipalBasic'] = _PRINCIPALBASIC
DESCRIPTOR.message_types_by_name['UserBasic'] = _USERBASIC
DESCRIPTOR.message_types_by_name['ServiceAccountBasic'] = _SERVICEACCOUNTBASIC
DESCRIPTOR.message_types_by_name['GroupBasic'] = _GROUPBASIC
DESCRIPTOR.enum_types_by_name['PrincipalType'] = _PRINCIPALTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrincipalBasic = _reflection.GeneratedProtocolMessageType('PrincipalBasic', (_message.Message,), {
  'DESCRIPTOR' : _PRINCIPALBASIC,
  '__module__' : 'tecton_proto.auth.principal_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.auth.PrincipalBasic)
  })
_sym_db.RegisterMessage(PrincipalBasic)

UserBasic = _reflection.GeneratedProtocolMessageType('UserBasic', (_message.Message,), {
  'DESCRIPTOR' : _USERBASIC,
  '__module__' : 'tecton_proto.auth.principal_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.auth.UserBasic)
  })
_sym_db.RegisterMessage(UserBasic)

ServiceAccountBasic = _reflection.GeneratedProtocolMessageType('ServiceAccountBasic', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEACCOUNTBASIC,
  '__module__' : 'tecton_proto.auth.principal_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.auth.ServiceAccountBasic)
  })
_sym_db.RegisterMessage(ServiceAccountBasic)

GroupBasic = _reflection.GeneratedProtocolMessageType('GroupBasic', (_message.Message,), {
  'DESCRIPTOR' : _GROUPBASIC,
  '__module__' : 'tecton_proto.auth.principal_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.auth.GroupBasic)
  })
_sym_db.RegisterMessage(GroupBasic)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
