# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tecton_proto/metadataservice/http_over_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tecton_proto/metadataservice/http_over_grpc.proto',
  package='tecton_proto.metadataservice',
  syntax='proto2',
  serialized_options=b'\n\032com.tecton.metadataserviceB\014HttpOverGrpcP\001Z1github.com/tecton-ai/tecton_proto/metadataservice',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1tecton_proto/metadataservice/http_over_grpc.proto\x12\x1ctecton_proto.metadataservice\"\x93\x01\n\x0bHttpRequest\x12\x16\n\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n\x04\x62ody\x18\x03 \x01(\x0cR\x04\x62ody\x12 \n\x0b\x63ontentType\x18\x04 \x01(\tR\x0b\x63ontentType\x12$\n\rcontentLength\x18\x05 \x01(\x03R\rcontentLength\"u\n\x13HttpResponseHeaders\x12\x16\n\x06status\x18\x01 \x01(\x05R\x06status\x12 \n\x0b\x63ontentType\x18\x02 \x01(\tR\x0b\x63ontentType\x12$\n\rcontentLength\x18\x03 \x01(\x03R\rcontentLength\"\x93\x01\n\x11HttpResponsePiece\x12M\n\x07headers\x18\x01 \x01(\x0b\x32\x31.tecton_proto.metadataservice.HttpResponseHeadersH\x00R\x07headers\x12\x1f\n\nbody_piece\x18\x02 \x01(\x0cH\x00R\tbodyPieceB\x0e\n\x0cmessage_type2|\n\x13HttpOverGrpcService\x12\x65\n\x05Proxy\x12).tecton_proto.metadataservice.HttpRequest\x1a/.tecton_proto.metadataservice.HttpResponsePiece0\x01\x42_\n\x1a\x63om.tecton.metadataserviceB\x0cHttpOverGrpcP\x01Z1github.com/tecton-ai/tecton_proto/metadataservice'
)




_HTTPREQUEST = _descriptor.Descriptor(
  name='HttpRequest',
  full_name='tecton_proto.metadataservice.HttpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='tecton_proto.metadataservice.HttpRequest.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='method', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='tecton_proto.metadataservice.HttpRequest.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='url', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='tecton_proto.metadataservice.HttpRequest.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='body', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contentType', full_name='tecton_proto.metadataservice.HttpRequest.contentType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='contentType', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contentLength', full_name='tecton_proto.metadataservice.HttpRequest.contentLength', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='contentLength', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=231,
)


_HTTPRESPONSEHEADERS = _descriptor.Descriptor(
  name='HttpResponseHeaders',
  full_name='tecton_proto.metadataservice.HttpResponseHeaders',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='tecton_proto.metadataservice.HttpResponseHeaders.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='status', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contentType', full_name='tecton_proto.metadataservice.HttpResponseHeaders.contentType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='contentType', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contentLength', full_name='tecton_proto.metadataservice.HttpResponseHeaders.contentLength', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='contentLength', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=350,
)


_HTTPRESPONSEPIECE = _descriptor.Descriptor(
  name='HttpResponsePiece',
  full_name='tecton_proto.metadataservice.HttpResponsePiece',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='headers', full_name='tecton_proto.metadataservice.HttpResponsePiece.headers', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='headers', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body_piece', full_name='tecton_proto.metadataservice.HttpResponsePiece.body_piece', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='bodyPiece', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message_type', full_name='tecton_proto.metadataservice.HttpResponsePiece.message_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=353,
  serialized_end=500,
)

_HTTPRESPONSEPIECE.fields_by_name['headers'].message_type = _HTTPRESPONSEHEADERS
_HTTPRESPONSEPIECE.oneofs_by_name['message_type'].fields.append(
  _HTTPRESPONSEPIECE.fields_by_name['headers'])
_HTTPRESPONSEPIECE.fields_by_name['headers'].containing_oneof = _HTTPRESPONSEPIECE.oneofs_by_name['message_type']
_HTTPRESPONSEPIECE.oneofs_by_name['message_type'].fields.append(
  _HTTPRESPONSEPIECE.fields_by_name['body_piece'])
_HTTPRESPONSEPIECE.fields_by_name['body_piece'].containing_oneof = _HTTPRESPONSEPIECE.oneofs_by_name['message_type']
DESCRIPTOR.message_types_by_name['HttpRequest'] = _HTTPREQUEST
DESCRIPTOR.message_types_by_name['HttpResponseHeaders'] = _HTTPRESPONSEHEADERS
DESCRIPTOR.message_types_by_name['HttpResponsePiece'] = _HTTPRESPONSEPIECE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HttpRequest = _reflection.GeneratedProtocolMessageType('HttpRequest', (_message.Message,), {
  'DESCRIPTOR' : _HTTPREQUEST,
  '__module__' : 'tecton_proto.metadataservice.http_over_grpc_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.metadataservice.HttpRequest)
  })
_sym_db.RegisterMessage(HttpRequest)

HttpResponseHeaders = _reflection.GeneratedProtocolMessageType('HttpResponseHeaders', (_message.Message,), {
  'DESCRIPTOR' : _HTTPRESPONSEHEADERS,
  '__module__' : 'tecton_proto.metadataservice.http_over_grpc_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.metadataservice.HttpResponseHeaders)
  })
_sym_db.RegisterMessage(HttpResponseHeaders)

HttpResponsePiece = _reflection.GeneratedProtocolMessageType('HttpResponsePiece', (_message.Message,), {
  'DESCRIPTOR' : _HTTPRESPONSEPIECE,
  '__module__' : 'tecton_proto.metadataservice.http_over_grpc_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.metadataservice.HttpResponsePiece)
  })
_sym_db.RegisterMessage(HttpResponsePiece)


DESCRIPTOR._options = None

_HTTPOVERGRPCSERVICE = _descriptor.ServiceDescriptor(
  name='HttpOverGrpcService',
  full_name='tecton_proto.metadataservice.HttpOverGrpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=502,
  serialized_end=626,
  methods=[
  _descriptor.MethodDescriptor(
    name='Proxy',
    full_name='tecton_proto.metadataservice.HttpOverGrpcService.Proxy',
    index=0,
    containing_service=None,
    input_type=_HTTPREQUEST,
    output_type=_HTTPRESPONSEPIECE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HTTPOVERGRPCSERVICE)

DESCRIPTOR.services_by_name['HttpOverGrpcService'] = _HTTPOVERGRPCSERVICE

# @@protoc_insertion_point(module_scope)
