
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tm = {'_': ['tm-38837',
       'tm4sf1',
       'tm0436',
       'tm7sf2',
       'tm6sf2',
       'tm4sf5',
       'tm9sf2',
       'tm-xml',
       'tm-170',
       'tm7x',
       'tm65',
       'tm88',
       'tm2',
       'tm3'],
 'a': ['tmaxsoft',
       'tmassa',
       'tmarus',
       'tmall',
       'tma-1',
       'tma-5',
       'tma-3',
       'tma-4',
       'tma-6',
       'tma-2',
       'tmava',
       'tmas',
       'tman',
       'tmac',
       'tmax',
       'tmap',
       'tma'],
 'b': ['tmbim4', 'tmbim1', 'tmbc', 'tmb'],
 'c': ['tmc-647055',
       'tmc-310911',
       'tmco5a',
       'tmco4',
       'tmco1',
       'tmco2',
       'tmco6',
       'tmcft',
       'tmcc',
       'tmc3',
       'tmc1',
       'tmca',
       'tmc8',
       'tmc6',
       'tmc2',
       'tmcm',
       'tmc'],
 'd': ['tmdp', 'tmd'],
 'e': ['tmesisternopsis',
       'tmesisternini',
       'tmemophlebia',
       'tmesisternus',
       'tmesiphorini',
       'tmesiphantes',
       'tmesorrhina',
       'tmetomorpha',
       'tmesiphorus',
       'tmesorhhina',
       'tmeimichatt',
       'tmesipteris',
       'tmetoptera',
       'tmeticodes',
       'tmeticides',
       'tmem184b',
       'tmem126a',
       'tmem106c',
       'tmeticus',
       'tmem200a',
       'tmem126b',
       'tmem176b',
       'tmem106a',
       'tmem229b',
       'tmetuchl',
       'tmem106b',
       'tmem110',
       'tmem260',
       'tmem241',
       'tmem275',
       'tmem117',
       'tmem156',
       'tmem221',
       'tmem101',
       'tmem109',
       'tmem127',
       'tmem38a',
       'tmem158',
       'tmem230',
       'tmem143',
       'tmem267',
       'tmem239',
       'tmem138',
       'tmem249',
       'tmem128',
       'tmem125',
       'tmem63a',
       'tmem169',
       'tmem112',
       'tmem130',
       'tmem215',
       'tmem155',
       'tmem219',
       'tmem160',
       'tmem123',
       'tmem242',
       'tmem50a',
       'tmem171',
       'tmem211',
       'tmem247',
       'tmem243',
       'tmem165',
       'tmem131',
       'tmem38b',
       'tmem39b',
       'tmem150',
       'tmem196',
       'tmem216',
       'tmetric',
       'tmem212',
       'tmem72',
       'tmem51',
       'tmeff2',
       'tmem22',
       'tmed10',
       'tmem8b',
       'tmem49',
       'tmem26',
       'tmesis',
       'tmem43',
       'tmem29',
       'tmem66',
       'tmem59',
       'tmepai',
       'tmem8a',
       'tmem25',
       'tmem18',
       'tmem47',
       'tmem98',
       'tmem33',
       'tmem67',
       'tmem81',
       'tmem69',
       'tmem70',
       'tmem44',
       'tmem1',
       'tmed3',
       'tmeic',
       'tmed5',
       'tmed1',
       'tmem9',
       'tmed4',
       'tmed2',
       'tmep',
       'tme'],
 'f': ['tmf1', 'tmf'],
 'g': ['tmge', 'tmg'],
 'h': ['tmhs', 'tmh'],
 'i': ['tmigd1', 'tmigd2', 'tmi'],
 'k': ['tmk'],
 'l': ['tmlhe', 'tml'],
 'm': ['tmmk', 'tmm'],
 'n': ['tmn'],
 'o': ['tmolus', 'tmoriq', 'tmodem', 'tmogvi', 'tmotd', 'tmou', 'tmos', 'tmo'],
 'p': ['tmprss11f',
       'tmprss11d',
       'tmprss11b',
       'tmprss6',
       'tmpgenc',
       'tmprss2',
       'tmprss4',
       'tmprss3',
       'tmpdir',
       'tmpfs',
       'tmpad',
       'tmp'],
 'q': ['tmq'],
 'r': ['tmrp-6', 'tmr'],
 's': ['tms34010',
       'tmsr-lf1',
       'tmsr-500',
       'tmsb15a',
       'tms6100',
       'tmsb15b',
       'tmsb10',
       'tmsi',
       'tmsp',
       'tmsa',
       'tmss',
       'tmsc',
       'tms'],
 't': ['tmtc4', 'tmtfa', 'tmtc2', 'tmt'],
 'u': ['tmutarakan', 'tmub2', 'tmuse', 'tmuc', 'tmux', 'tmu'],
 'v': ['tmv'],
 'w': ['tmw'],
 'x': ['tmx4', 'tmx1', 'tmx3', 'tmx'],
 'y': ['tmy'],
 'z': ['tmz']}
