# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LogNode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rLogNode.proto\x12\x07LogNode\x1a\x0c\x43ommon.proto\";\n\x08log_info\x12\x1e\n\x06result\x18\x01 \x01(\x0b\x32\x0e.Common.result\x12\x0f\n\x07logging\x18\x02 \x03(\t2\x9c\x01\n\x07LogNode\x12/\n\x08StartLog\x12\x11.Common.file_path\x1a\x0e.Common.result\"\x00\x12\x30\n\nGetLogInfo\x12\r.Common.empty\x1a\x11.LogNode.log_info\"\x00\x12.\n\x07StopLog\x12\x11.Common.file_path\x1a\x0e.Common.result\"\x00\x62\x06proto3')



_LOG_INFO = DESCRIPTOR.message_types_by_name['log_info']
log_info = _reflection.GeneratedProtocolMessageType('log_info', (_message.Message,), {
  'DESCRIPTOR' : _LOG_INFO,
  '__module__' : 'LogNode_pb2'
  # @@protoc_insertion_point(class_scope:LogNode.log_info)
  })
_sym_db.RegisterMessage(log_info)

_LOGNODE = DESCRIPTOR.services_by_name['LogNode']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOG_INFO._serialized_start=40
  _LOG_INFO._serialized_end=99
  _LOGNODE._serialized_start=102
  _LOGNODE._serialized_end=258
# @@protoc_insertion_point(module_scope)
