
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_t_ = {'_': ['t4-gutachter',
       't-54/t-55',
       't-72m4cz',
       't-55agm',
       't-1000',
       't-0156',
       't-1123',
       't-3000',
       't2000',
       't790m',
       't-411',
       't1419',
       't1000',
       't.120',
       't.192',
       't-47d',
       't411',
       't-35',
       't-74',
       't-40',
       't-62',
       't-27',
       't201',
       't-72',
       't98g',
       't-84',
       't-95',
       't.37',
       't.38',
       't-34',
       't600',
       't700',
       't120',
       't100',
       't-90',
       't.25',
       't-80',
       't-70',
       't205',
       't206',
       't-19',
       't-26',
       't-46',
       't-64',
       't-28',
       't-44',
       't213',
       't800',
       't110',
       't13',
       't33',
       't26',
       't99',
       't92',
       't53',
       't35',
       't37',
       't57',
       't39',
       't40',
       't60',
       't12',
       't16',
       't36',
       't+2',
       't43',
       't32',
       't71',
       't19',
       't31',
       't14',
       't15',
       't61',
       't48',
       't34',
       't69',
       't70',
       't17',
       't80',
       't84',
       't20',
       't25',
       't10',
       't11',
       't38',
       't22',
       't45',
       't75',
       't68',
       't52',
       't21',
       't18',
       't29',
       't23',
       't59',
       't49',
       't27',
       't50',
       't66',
       't65',
       't24',
       't44',
       't51',
       't54',
       't41',
       't90',
       't42',
       't58',
       't30',
       't28'],
 'a': ['t.a.p.o.a.f.o.m.',
       't-additivity',
       't.a.h.i.t.i.',
       "t'aqachiri",
       "t'aqanawi",
       't-antenna',
       't.a.t.u.',
       't.agaram',
       't8aa-fm',
       "t'akra",
       "t'akaq",
       't-ara',
       "t'ari",
       't8aa',
       't2a'],
 'b': ['t-bucket',
       't-blades',
       't-beauty',
       't@brizli',
       't-board',
       't-bolan',
       't-beam',
       't-babe',
       't-bag',
       't-box',
       't-bar',
       't2b'],
 'c': ['t-connection',
       't-criterion',
       't-centralen',
       't-closeness',
       't-coloring',
       't-commerce',
       't-cadherin',
       't-classic',
       't-carrier',
       't-cophony',
       't-coffee',
       't.c.c.p.',
       't-center',
       't-comma',
       "t'chaka",
       't-code',
       't-cat',
       't&c'],
 'd': ['t-diaeresis', 't-duality', 't-dog', 't2d', 't.d', 't&d'],
 'e': ['t.e.v.i.n.', 't.e.l.i...', 't+e', 't&e'],
 'f': ['t-function', 't-fiber', 't-force', 't,ftfy', 't&f'],
 'g': ['t-glottalization', 't.g.i.s.', 't-groups', 't-group'],
 'h': ["t'heydinn", 't-hub', 't@hl@', 't-hca'],
 'i': ['t1international',
       't.i.a.p.f.y.h.',
       "t'ikapallana",
       "t'iyuyuq",
       "t'illu",
       "t'iwu",
       't.i.'],
 'k': ['t@kyemisan',
       't.kalathur',
       't-kontoret',
       't-kernel',
       't@k@qaya',
       't:kort',
       't@kdam',
       't@kl@',
       't@ky@'],
 'l': ['t-license', 't-league', 't.league', 't.love', 't-link', 't@la'],
 'm': ['t-mobile',
       't8m-900m',
       't8m-900',
       "t'melle",
       't-mount',
       't/maker',
       't-money',
       't-model',
       't-mpls',
       't-maze',
       't-mac',
       't-max',
       't-men',
       't-mek',
       't-mo'],
 'n': ['t@ng@alti',
       't@ng@rud',
       't-number',
       't@ngivan',
       't@ng@bin',
       "t'nalak",
       't-nutty',
       't@n@n@m',
       't-norm',
       't@ndul',
       't-nut'],
 'o': ['t,o,u,c,h,i,n,g',
       't.o.t.s.',
       't-online',
       't.o.l.d.',
       't.o.n.y.',
       't.o.k.',
       't.o.p',
       't/o'],
 'p': ['t-pistonz+kmc',
       't-platforms',
       't@p@c@nn@t',
       't@p@m@hl@',
       't.p.e.',
       't-pain',
       't-pose',
       "t'pol",
       "t'pau",
       't-pop',
       't5pc',
       't&p',
       't3p'],
 'q': ['t.q.m.'],
 'r': ['t-r-o-u-b-l-e',
       't.r.a.c.k.s.',
       't.r.u.t.h.',
       't@rxanli',
       't@rnoyut',
       't-rules',
       't-room',
       't-ride',
       't@rlan',
       "t'rung",
       't@rkes',
       "t'ruah",
       't-rac',
       't-ram',
       't-ran'],
 's': ['t.subbulapuram',
       't-statistic',
       't-structure',
       't-symmetry',
       't-spot.tb',
       't-systems',
       't-splice',
       't-street',
       't-square',
       't-schema',
       't.s.o.l.',
       't-spline',
       't-shirt',
       't-stoff',
       't/space',
       't-skirt',
       't-spoon',
       't-stage',
       't-slam',
       't@si',
       't2s'],
 't': ['t-theory',
       't-tubule',
       't-town',
       't-tree',
       't-type',
       't.t.ma',
       't-tail',
       't-trak',
       't-top',
       't/tcp',
       't.tv',
       't&t'],
 'u': ["t'urpuqucha",
       "t'uruqucha",
       't.u.s.c.a.',
       "t'uruyuq",
       "t'uquyuq",
       "t'utura",
       't-unit',
       "t'uru",
       't2u'],
 'v': ['t-vertices', 't-vice', 't-vips', 't-vis', 't-v-h'],
 'w': ['t-wayne', 't-word', 't-wave', 't.w.o'],
 'x': ['t-x'],
 'y': ['t.y.s.o.n.', "t'yngryng", 't2ya'],
 'z': ['t@z@k@nd', 't-zero']}
