
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mn = {'_': ['mn2+-dependent_adp-ribose/cdp-alcohol_diphosphatase'],
 'a': ['mnasitheus_of_sicyon',
       'mnason_of_phocis',
       'mna_na_heireann',
       'mnaga_a_zdorp'],
 'c': ['mnc_trijaya_fm', 'mnc_world_news'],
 'd': ['mndf_marine_corps'],
 'e': ['mnek_production_discography',
       "mnev's_universality_theorem",
       'mnemonics_in_trigonometry',
       'mnemonic_major_system',
       'mnesarchus_of_athens',
       'mnemonic_link_system',
       'mnemonic_peg_system',
       'mner_i_siperm'],
 'i': ['mniszek,_kuyavian-pomeranian_voivodeship',
       'mnichowo,_warmian-masurian_voivodeship',
       'mniszki,_warmian-masurian_voivodeship',
       'mnichow,_swietokrzyskie_voivodeship',
       'mniszek,_swietokrzyskie_voivodeship',
       'mniszek,_pomeranian_voivodeship',
       'mniszek,_masovian_voivodeship',
       'mnich,_silesian_voivodeship',
       'mniszek,_lublin_voivodeship',
       'mniszkow,_lodz_voivodeship',
       'mnichow,_lodz_voivodeship',
       'mniszki,_lodz_voivodeship',
       'mnisek_nad_popradom',
       'mnich,_kutno_county',
       'mnisek_nad_hnilcom',
       'mnisek_pod_brdy'],
 'j': ['mnjikaning_fish_weirs'],
 'k': ['mnk_uspinjaca_zagreb', 'mnk_seljak_livno'],
 'l': ['mnl1_data_center'],
 'q': ['mnquma_local_municipality'],
 'r': ['mnread_acuity_chart', 'mnrk_music_group'],
 's': ['mns_antigen_system']}
