
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hb = {'_': ['hb-flugtechnik_dandy',
       'hb-flugtechnik_amigo',
       'hb_construction',
       'hb-e210_series',
       'hb9xbg_antenna',
       'hb-e300_series',
       'hb_dudelange',
       'hb_chartres',
       'hb_studios',
       'hb_bassett',
       "hb_wall's",
       'hb_reavis',
       'hb_studio',
       'hb_jassin',
       'hb_colony',
       'hb_koge'],
 'a': ['hbaline', 'hbasic', 'hbap1', 'hba'],
 'b': ['hbbp1', 'hbbs'],
 'c': ['hbc_celles-sur-belle',
       'hbcu_classic',
       'hbc_wrigley',
       'hbc_nantes',
       'hbcu_band'],
 'd': ['hbds', 'hbd'],
 'e': ['hbeag', 'hbe1', 'hbes', 'hbe'],
 'f': ['hbfc', 'hbf'],
 'g': ['hbgary', 'hbg1', 'hbg2', 'hbg'],
 'h': ['hbhs', 'hbh'],
 'i': ['hbi-3000', 'hbio', 'hbic', 'hbit', 'hbi'],
 'j': ['hbj_model'],
 'k': ['hbk_investments'],
 'l': ['hbl_f.c.'],
 'm': ['hbm_iqbal'],
 'n': ['hbn_law'],
 'o': ['hbo_netherlands',
       'hbo_portugal',
       'hbo_brasil',
       'hbo_europe',
       'hbo_films',
       'hbo_hits',
       'hbo_kids',
       'hbo_asia',
       'hbo_max',
       'hbo_now',
       'hbo_go'],
 'p': ['hbp1', 'hbp'],
 'q': ['hbq1'],
 'r': ['hbr'],
 's': ['hbs_craeyenhout'],
 't': ['hbtv', 'hbtu', 'hbt'],
 'u': ['hbu'],
 'v': ['hbv'],
 'w': ['hbw_balingen-weilstetten', 'hbwat_uav'],
 'x': ['hbxip', 'hbx'],
 'y': ['hby'],
 'z': ['hbz']}
