
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dn = {'_': ['dn73a',
       'dn68a',
       'dn73',
       'dn28',
       'dn1a',
       'dn10',
       'dn21',
       'dn1b',
       'dn-1',
       'dn3',
       'dn2',
       'dn4',
       'dn6',
       'dn7',
       'dn5',
       'dn1'],
 'a': ['dnanalytics',
       'dna-scars',
       'dnase-seq',
       'dnadynamo',
       'dnase1l2',
       'dnanudge',
       'dna-pkcs',
       'dnanexus',
       'dnase1l1',
       'dnaliens',
       'dnalinux',
       'dnase1l3',
       'dnajb11',
       'dnajc28',
       'dnainfo',
       'dnajc10',
       'dnajc14',
       'dnajc11',
       'dnajc30',
       'dnastar',
       'dnajc19',
       'dnajc13',
       'dnajb4',
       'dnah11',
       'dnaja1',
       'dnajb2',
       'dnajc7',
       'dnaja3',
       'dnajc3',
       'dnajc1',
       'dnaaf2',
       'dnaja2',
       'dnajb9',
       'dnaja4',
       'dnajb6',
       'dnajb1',
       'dna-os',
       'dnajc5',
       'dnata',
       'dna2l',
       'dnah5',
       'dnah7',
       'dnah9',
       'dnal1',
       'dnai2',
       'dnal4',
       'dnah1',
       'dnai1',
       'dnae',
       'dnaa',
       'dnad',
       'dna2',
       'dnap',
       'dnah',
       'dnan',
       'dnaq',
       'dnac',
       'dnag',
       'dnai',
       'dnam',
       'dnas',
       'dnab',
       'dna'],
 'b': ['dnb'],
 'c': ['dnce', 'dnc'],
 'd': ['dnd'],
 'e': ['dneprospetsstal',
       'dneprovsky',
       'dnestrovsc',
       'dneprovka',
       'dnevniki',
       'dneprov',
       'dnevnik',
       'dnesice',
       'dnepr',
       'dneg',
       'dner',
       'dne'],
 'f': ['dnf'],
 'g': ['dngrfld', 'dng'],
 'h': ['dnhs', 'dnh'],
 'i': ['dnistryk-dubovyi',
       'dniprovahonmash',
       'dni-glutamate',
       'dnipro-arena',
       'dniproenergo',
       'dniprorudne',
       'dniprovske',
       'dniproavia',
       'dnipriany',
       'dniester',
       'dnieper',
       'dnipro',
       'dnic',
       'dnix',
       'dni'],
 'k': ['dnk'],
 'l': ['dnl'],
 'm': ['dnmt3b', 'dnmt3l', 'dnmt1', 'dnm1l', 'dnm1', 'dnm3', 'dnm2', 'dnm'],
 'n': ['dnn'],
 'o': ['dnopolje', 'dnotify', 'dnoc', 'dno'],
 'p': ['dnpep', 'dnpo', 'dnp3', 'dnp'],
 'q': ['dnqx', 'dnq'],
 'r': ['dnrc', 'dnr'],
 's': ['dnschanger',
       'dnscurve',
       'dnscrypt',
       'dnsimple',
       'dnsmasq',
       'dnsap',
       'dnswl',
       'dnsc',
       'dnsa'],
 't': ['dnttip2', 'dntv2', 'dntel', 'dnt'],
 'v': ['dnvgl-st-e271', 'dnv'],
 'w': ['dnw'],
 'y': ['dnyaneshwari',
       'dnyaprovets',
       'dnyaneshwar',
       'dnyanodaya',
       'dnyanvani',
       'dnyandeo',
       'dny'],
 'z': ['dnz']}
