
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dl = {'_': ['dl1961'],
 'a': ['dlahchevo-sablyar',
       'dlazkovice',
       'dlawarpur',
       'dlabocica',
       'dlagnevo',
       'dla0817g',
       'dlasthr',
       'dlakose',
       'dlamini',
       'dlazov',
       'dlab',
       'dla'],
 'b': ['dlbd', 'dlb'],
 'c': ['dlc1', 'dlc'],
 'd': ['dld/np1', 'dld'],
 'e': ['dlebta', 'dleu2', 'dleu1', 'dle'],
 'f': ['dlf'],
 'g': ['dlg2-as1',
       'dlgap2',
       'dlgap5',
       'dlgap4',
       'dlgap1',
       'dlg5',
       'dlg2',
       'dlg4',
       'dlg1',
       'dlg3',
       'dlg'],
 'h': ['dlhona', 'dlha', 'dlh'],
 'i': ['dlisted', 'dlife', 'dlimi', 'dlive', 'dlib', 'dli'],
 'j': ['dljin', 'dlj'],
 'k': ['dlk1', 'dlk'],
 'l': ['dll3', 'dll4', 'dll'],
 'm': ['dlm'],
 'o': ['dlouhopolsko',
       'dlouhonovice',
       'dlouhomilov',
       'dlohaiti',
       'dlogtime',
       'dlouhy',
       'dlocal',
       'dlouhe',
       'dlow',
       'dlo'],
 'p': ['dlp'],
 'r': ['dlr-tubsat', 'dlr'],
 's': ['dlst', 'dls'],
 't': ['dltbco', 'dlt'],
 'u': ['dlugoleka-swierkla',
       'dlugoszyn-kolonia',
       'dlugopole-zdroj',
       'dlugoleka-koski',
       'dlugobor-osada',
       'dluzek-kolonia',
       'dlugochorzele',
       'dlugomilowice',
       'dlusskyidris',
       'dlugosiodlo',
       'dlugoszynek',
       'dluzniewice',
       'dlugosielce',
       'dlugowizna',
       'dlugopole',
       'dlugoszyn',
       'dlugoleka',
       'dlugokaty',
       'dlutowka',
       'dlugolas',
       'dlugojow',
       'dlugobor',
       'dlutowek',
       'dlutkowo',
       'dlugosze',
       'dluzniow',
       'dlutowo',
       'dluzyna',
       'dluzyce',
       'dlugnya',
       'dlugosz',
       'dluzewo',
       'dlugie',
       'dluzki',
       'dluzew',
       'dluzec',
       'dluzka',
       'dlutow',
       'dlusk',
       'dlux',
       'dlu'],
 'v': ['dlv'],
 'w': ['dlw'],
 'x': ['dlx6-as1', 'dlx2', 'dlx1', 'dlx5', 'dlx4', 'dlx6', 'dlx3', 'dlx'],
 'y': ['dly'],
 'z': ['dlzin']}
