
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jd = {'_': ['jd_schickerling',
       'jd_motorsports',
       'jd_motorsport',
       'jd_decompiler',
       'jd_mcpherson',
       'jd_rossetti',
       'jd_davison',
       'jd_closser',
       'jd-03_pipe',
       'jd_mccrary',
       'jd_squared',
       'jd_edwards',
       'jd_gravina',
       'jd_roberto',
       'jd_natasha',
       'jd_albert',
       'jd_miller',
       'jd_eicher',
       'jd_arrate',
       'jd_sports',
       'jd_gaming',
       'jd_moller',
       'jd_cullum',
       'jd_samson',
       'jd_notae',
       'jd_allan',
       'jd_fenix',
       'jd_doyle',
       'jd_davis',
       'jd_scott',
       'jd_era'],
 'a': ['jdaydeh', 'jdaideh', 'jdate', 'jdata', 'jda'],
 'b': ['jdbc_driver', 'jdb_group'],
 'c': ['jdc_motorsports', 'jdc_records', 'jdc_west'],
 'e': ['jdeidat_al-wadi', 'jdeidat_yabous', 'jdeidat_artouz', "jde_peet's"],
 'f': ['jdfs_alberts'],
 'g': ['jdg'],
 'h': ['jdhs'],
 'i': ['jdiriya', 'jdiggz', 'jdiff', 'jdi'],
 'm': ['jdm_roitelet'],
 'n': ['jdn'],
 'o': ['jdownloader', 'jdom', 'jdoe', 'jdo'],
 'p': ['jdp'],
 'r': ['jdrf', 'jdr'],
 's': ['jds_amatsukaze',
       'jds_natsugumo',
       'jds_nagatsuki',
       'jds_takatsuki',
       'jds_shikinami',
       'jds_mochizuki',
       'jds_teruzuki',
       'jds_nadashio',
       'jds_minegumo',
       'jds_kitakami',
       'jds_yamagumo',
       'jds_yukikaze',
       'jds_makigumo',
       'jds_takanami',
       'jds_murakumo',
       'jds_makinami',
       'jds_kikuzuki',
       'jds_hayabusa',
       'jds_harukaze',
       'jds_chikugo',
       'jds_fushimi',
       'jds_oyashio',
       'jds_chihaya',
       'jds_asagumo',
       'jds_noshiro',
       'jds_akishio',
       'jds_akigumo',
       'jds_tsugaru',
       'jds_uranami',
       'jds_chitose',
       'jds_ayanami',
       'jds_yashiro',
       'jds_isonami',
       'jds_yoshino',
       'jds_tokachi',
       'jds_akizuki',
       'jds_teshio',
       'jds_mogami',
       'jds_kumano',
       'jds_niyodo',
       'jds_yugumo',
       'jds_aokumo',
       'jds_wakaba',
       'jds_mikuma',
       'jds_hayase',
       'jds_akashi',
       'jds_mirai',
       'jds_ayase',
       'jds_iwase',
       'jds_onami',
       'jds_isuzu',
       'jds_erimo',
       'jds_azuma',
       'jds_oshio',
       'jds_soya',
       'jds_oi'],
 't': ['jdtic', 'jdt'],
 'u': ['jdub_records'],
 'v': ['jdv'],
 'w': ['jdw'],
 'z': ['jdz']}
