"""Created by Lorenzo Cruz on November 24, 2021."""

MOCK_FETCH_BALANCE = {
    "info": [
        {
            "account": 348414,
            "currency": "XBt",
            "riskLimit": 1000000000000,
            "prevState": "",
            "state": "",
            "action": "",
            "amount": 225833,
            "pendingCredit": 0,
            "pendingDebit": 0,
            "confirmedDebit": 0,
            "prevRealisedPnl": -693,
            "prevUnrealisedPnl": 0,
            "grossComm": 0,
            "grossOpenCost": 0,
            "grossOpenPremium": 0,
            "grossExecCost": 0,
            "grossMarkValue": 0,
            "riskValue": 0,
            "taxableMargin": 0,
            "initMargin": 0,
            "maintMargin": 0,
            "sessionMargin": 0,
            "targetExcessMargin": 0,
            "varMargin": 0,
            "realisedPnl": 0,
            "unrealisedPnl": 0,
            "indicativeTax": 0,
            "unrealisedProfit": 0,
            "syntheticMargin": None,
            "walletBalance": 225833,
            "marginBalance": 225833,
            "marginBalancePcnt": 1,
            "marginLeverage": 0,
            "marginUsedPcnt": 0,
            "excessMargin": 225833,
            "excessMarginPcnt": 1,
            "availableMargin": 225833,
            "withdrawableMargin": 225833,
            "grossLastValue": 0,
            "commission": None,
            "makerFeeDiscount": None,
            "takerFeeDiscount": None,
            "timestamp": "2021-11-22T05:44:47.381Z",
        },
    ],
    "BTC": {"free": 0.00225833, "used": 0.0, "total": 0.00225833},
    "free": {"BTC": 0.00225833, "USDT": 100000000000.0},
    "used": {"BTC": 0.0, "USDT": 0.0},
    "total": {"BTC": 0.00225833, "USDT": 100000000000.0},
}

MOCK_FETCH_BALANCE_MULTI_WALLET = {
    "info": [
        {
            "account": 348414,
            "currency": "USDt",
            "riskLimit": 500000000000000,
            "prevState": "",
            "state": "",
            "action": "",
            "amount": 100000000000,
            "pendingCredit": 0,
            "pendingDebit": 0,
            "confirmedDebit": 0,
            "prevRealisedPnl": 0,
            "prevUnrealisedPnl": 0,
            "grossComm": 0,
            "grossOpenCost": 0,
            "grossOpenPremium": 0,
            "grossExecCost": 0,
            "grossMarkValue": 0,
            "riskValue": 0,
            "taxableMargin": 0,
            "initMargin": 0,
            "maintMargin": 0,
            "sessionMargin": 0,
            "targetExcessMargin": 0,
            "varMargin": 0,
            "realisedPnl": 0,
            "unrealisedPnl": 0,
            "indicativeTax": 0,
            "unrealisedProfit": 0,
            "syntheticMargin": None,
            "walletBalance": 100000000000,
            "marginBalance": 100000000000,
            "marginBalancePcnt": 1,
            "marginLeverage": 0,
            "marginUsedPcnt": 0,
            "excessMargin": 100000000000,
            "excessMarginPcnt": 1,
            "availableMargin": 100000000000,
            "withdrawableMargin": 100000000000,
            "grossLastValue": 0,
            "commission": None,
            "makerFeeDiscount": None,
            "takerFeeDiscount": None,
            "timestamp": "2021-11-23T00:09:02.041Z",
        },
        {
            "account": 348414,
            "currency": "XBt",
            "riskLimit": 1000000000000,
            "prevState": "",
            "state": "",
            "action": "",
            "amount": 225833,
            "pendingCredit": 0,
            "pendingDebit": 0,
            "confirmedDebit": 0,
            "prevRealisedPnl": -693,
            "prevUnrealisedPnl": 0,
            "grossComm": 0,
            "grossOpenCost": 0,
            "grossOpenPremium": 0,
            "grossExecCost": 0,
            "grossMarkValue": 0,
            "riskValue": 0,
            "taxableMargin": 0,
            "initMargin": 0,
            "maintMargin": 0,
            "sessionMargin": 0,
            "targetExcessMargin": 0,
            "varMargin": 0,
            "realisedPnl": 0,
            "unrealisedPnl": 0,
            "indicativeTax": 0,
            "unrealisedProfit": 0,
            "syntheticMargin": None,
            "walletBalance": 225833,
            "marginBalance": 225833,
            "marginBalancePcnt": 1,
            "marginLeverage": 0,
            "marginUsedPcnt": 0,
            "excessMargin": 225833,
            "excessMarginPcnt": 1,
            "availableMargin": 225833,
            "withdrawableMargin": 225833,
            "grossLastValue": 0,
            "commission": None,
            "makerFeeDiscount": None,
            "takerFeeDiscount": None,
            "timestamp": "2021-11-22T05:44:47.381Z",
        },
    ],
    "USDT": {"free": 100000000000.0, "used": 0.0, "total": 100000000000.0},
    "BTC": {"free": 0.00225833, "used": 0.0, "total": 0.00225833},
    "free": {"BTC": 0.00225833, "USDT": 100000000000.0},
    "used": {"BTC": 0.0, "USDT": 0.0},
    "total": {"BTC": 0.00225833, "USDT": 100000000000.0},
}
