
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gj = {'a': ['gjaerumiaceae',
       'gjallarhorn',
       'gjaidstein',
       'gjallarbru',
       'gjallica',
       'gjavato',
       'gjakova',
       'gjashte',
       'gjader',
       'gjain',
       'gjata',
       'gja10',
       'gjan',
       'gja8',
       'gja3',
       'gja5',
       'gja1',
       'gja4',
       'gja'],
 'b': ['gjb5', 'gjb4', 'gjb3', 'gjb7', 'gjb6', 'gjb1', 'gjb2'],
 'c': ['gjc2', 'gjc3', 'gjc1', 'gjc'],
 'd': ['gjd4', 'gjd2', 'gjd3'],
 'e': ['gjegnalundsbreen',
       'gjenfortellinger',
       'gjesvaerstappan',
       'gjerstadfjellet',
       'gjetingsdalen',
       'gjevilvatnet',
       'gjedsergaard',
       'gjengangeren',
       'gjerdinghoi',
       'gjellerasen',
       'gjermundnes',
       'gjellerupia',
       'gjendesheim',
       'gjesassjoen',
       'gjesdalbuen',
       'gjersjoelva',
       'gjec-koder',
       'gjennestad',
       'gjenganger',
       'gjensidige',
       'gjeddesdal',
       'gjestvang',
       'gjergjove',
       'gjersjoen',
       'gjeravica',
       'gjerdinga',
       'gjerdaker',
       'gjertsen',
       'gjelsvik',
       'gjessing',
       'gjendebu',
       'gjesteby',
       'gjerstad',
       'gjesling',
       'gjermund',
       'gjesvaer',
       'gjepalaj',
       'gjesasen',
       'gjergjan',
       'gjerdrum',
       'gjesdal',
       'gjelhoi',
       'gjergji',
       'gjemnes',
       'gjebrea',
       'gjegjan',
       'gjettum',
       'gjelten',
       'gjernes',
       'gjerbes',
       'gjeving',
       'gjerpen',
       'gjerset',
       'gjesso',
       'gjeroy',
       'gjende',
       'gjergj',
       'gjerde',
       'gjern',
       'gje'],
 'g': ['gjg'],
 'h': ['gjhs'],
 'i': ['gjirokaster',
       'gjinovec',
       'gjitonia',
       'gjilan',
       'gjiten',
       'gjinaj',
       'gjinoc',
       'gjinar',
       'gjin'],
 'l': ['gjl'],
 'o': ['gjommervatnet',
       'gjogvarafjall',
       'gjonavatnet',
       'gjogovice',
       'gjonbalaj',
       'gjorslev',
       'gjostein',
       'gjovdal',
       'gjorgji',
       'gjorice',
       'gjonnes',
       'gjokaj',
       'gjonaj',
       'gjocaj',
       'gjovik',
       'gjorme',
       'gjorm',
       'gjoll',
       'gjora',
       'gjogv',
       'gjone',
       'gjon',
       'gjol',
       'gjoa'],
 'r': ['gjr'],
 's': ['gjs'],
 't': ['gjt'],
 'u': ['gjuvkampen', 'gjurakoc', 'gjurmet', 'gjurov', 'gjuki', 'gju'],
 'x': ['gjxdm'],
 'y': ['gjysylkane', 'gjylekar']}
