
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gp = {'_': ['gp-100',
       'gp1bb',
       'gp-4u',
       'gp1ba',
       'gp-25',
       'gp180',
       'gp32',
       'gp-1',
       'gp2x',
       'gp14',
       'gp41',
       'gp5',
       'gp2',
       'gp4',
       'gp1',
       'gp3'],
 'a': ['gpatch11',
       'gpatch2l',
       'gpatch8',
       'gparted',
       'gpaa1',
       'gpang',
       'gpart',
       'gpa33',
       'gpat4',
       'gpac',
       'gpam',
       'gpaa'],
 'b': ['gpbp1', 'gpb'],
 'c': ['gpca', 'gpcc', 'gpc'],
 'd': ['gpd1l', 'gpdf', 'gpd'],
 'e': ['gper', 'gpes', 'gpe'],
 'f': ['gpfs', 'gpfc', 'gpf'],
 'g': ['gpg4win', 'gpgp', 'gpg'],
 'h': ['gphpedit', 'gphs-rtg', 'gphoto', 'gphb5', 'gpha2', 'gphs', 'gph'],
 'i': ['gpi-space', 'gpihbp1', 'gpisd', 'gpi'],
 'j': ['gpj'],
 'k': ['gpkism', 'gpk'],
 'l': ['gpl-violations.org', 'gplates', 'gpld1'],
 'm': ['gpm6a', 'gpm6b', 'gpm'],
 'n': ['gpnotebook', 'gpnmb', 'gpn'],
 'o': ['gpops-ii', 'gpotato', 'gpo'],
 'p': ['gpp'],
 'r': ['gpremper',
       'gprename',
       'gprasp2',
       'gpr37l1',
       'gprasp1',
       'gpr137b',
       'gpr110',
       'gpr156',
       'gpr113',
       'gprin2',
       'gpr89b',
       'gpr115',
       'gpr151',
       'gpr141',
       'gpr173',
       'gprc5b',
       'gprc5c',
       'gpr152',
       'gpr171',
       'gpr123',
       'gprc5a',
       'gpr112',
       'gpr153',
       'gpr161',
       'gpr183',
       'gpr124',
       'gpr133',
       'gpr126',
       'gpr119',
       'gpr114',
       'gpr111',
       'gpr132',
       'gpr139',
       'gpr155',
       'gpr101',
       'gpr157',
       'gpr116',
       'gpr162',
       'gpr107',
       'gpr128',
       'gprc6a',
       'gpr176',
       'gpr125',
       'gpr150',
       'gprc5d',
       'gpr158',
       'gpr149',
       'gpr135',
       'gpr148',
       'gpr174',
       'gpr143',
       'gpr146',
       'gpr120',
       'gpr144',
       'gpr179',
       'gpr142',
       'gpr177',
       'gpr182',
       'gpr160',
       'gpr22',
       'gpr37',
       'gpr65',
       'gpr62',
       'gpr15',
       'gpr42',
       'gpr31',
       'gpr63',
       'gpr32',
       'gpr25',
       'gpr52',
       'gpr33',
       'gpr50',
       'gpr20',
       'gpr75',
       'gpr68',
       'gpr45',
       'gpr84',
       'gpr34',
       'gpr97',
       'gpr39',
       'gpr12',
       'gpr56',
       'gpr21',
       'gpr98',
       'gpr83',
       'gpr27',
       'gpr78',
       'gpr35',
       'gpr85',
       'gpr17',
       'gpr55',
       'gpr77',
       'gprof',
       'gpr64',
       'gpr26',
       'gpr19',
       'gpr87',
       'gpr82',
       'gpr61',
       'gpr88',
       'gpr1',
       'gpr3',
       'gpr4',
       'gprd',
       'gpr6',
       'gpra',
       'gpr'],
 's': ['gpsoverip',
       'gpsdrive',
       'gpsbabel',
       'gps/ins',
       'gpsgate',
       'gpswox',
       'gpsone',
       'gpsm2',
       'gps*c',
       'gpsm1',
       'gpsim',
       'gpsi',
       'gpss',
       'gps1',
       'gps2',
       'gpsa',
       'gpsd'],
 't': ['gpt-3', 'gpt-2', 'gpt2', 'gpt'],
 'u': ['gpugrid.net', 'gpuopen', 'gputils', 'gpulib', 'gpu-z'],
 'v': ['gpvi'],
 'w': ['gpw'],
 'x': ['gpx3',
       'gpx4',
       'gpx7',
       'gpx6',
       'gpx8',
       'gpx2',
       'gpx5',
       'gpxe',
       'gpx1',
       'gpx'],
 'z': ['gpz']}
