
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gm = {'_': ['gm-avtovaz',
       'gm-gruppen',
       'gm-94',
       'gm2a',
       'gm-1',
       'gm3',
       'gm2',
       'gm1'],
 'a': ['gmajnica',
       'gmarket',
       'gmassa',
       'gmajna',
       'gmachl',
       'gmane',
       'gmail',
       'gmax',
       'gmac',
       'gma'],
 'b': ['gmb'],
 'c': ['gmc-4', 'gmcl1', 'gmca', 'gmc'],
 'd': ['gmds', 'gmd'],
 'e': ['gmelinoides',
       'gmelinite',
       'gmelanone',
       'gmelinka',
       'gmeinder',
       'gmelinol',
       'gmelina',
       'gmeiner',
       'gmelin',
       'gmeb1',
       'gmeb2',
       'gmer',
       'gme'],
 'f': ['gmfa', 'gmf'],
 'g': ['gmg'],
 'h': ['gmhc', 'gmhs', 'gmh'],
 'i': ['gminsidenews', 'gmiri', 'gmiss', 'gmici', 'gmina', 'gmit', 'gmi'],
 'j': ['gmj'],
 'k': ['gmk'],
 'l': ['gml10', 'gml-1', 'gmlc', 'gml'],
 'm': ['gmmtv', 'gmmr', 'gmml', 'gmm'],
 'n': ['gmn'],
 'o': ['gmosaic', 'gmogala', 'gmobile', 'gmod'],
 'p': ['gmppb', 'gmpi', 'gmp'],
 'r': ['gmr'],
 's': ['gmst', 'gmsh', 'gms'],
 't': ['gmt800', 'gmt360', 'gmt900', 'gmt400', 'gmta', 'gmtv'],
 'u': ['gmunden', 'gmurowo', 'gmund', 'gmur', 'gmul', 'gmu'],
 'v': ['gmv'],
 'w': ['gmw'],
 'x': ['gmx'],
 'y': ['gmyrdek', 'gmy'],
 'z': ['gmz']}
