
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gb = {'_': ['gb-pvr', 'gb-4', 'gb84', 'gb40', 'gb-1', 'gb3'],
 'a': ['gbangbegouine-yati',
       'gbaja-biamila',
       'gbangbegouine',
       'gbameledougo',
       'gbangbossou',
       'gbangbatoke',
       'gbatongouin',
       'gbangbadou',
       'gbarpolu-2',
       'gbagbongom',
       'gbarpolu-3',
       'gbarpolu-1',
       'gbadolite',
       'gbalamuya',
       'gbanyamli',
       'gbalekaha',
       'gbakpodji',
       'gbadamosi',
       'gbablasso',
       'gbangbale',
       'gbargolay',
       'gbakedou',
       'gbanlin',
       'gbarnga',
       'gbadjie',
       'gbabshe',
       'gbapleu',
       'gbalahi',
       'gbagbam',
       'gbabire',
       'gbaffo',
       'gbazoa',
       'gbanga',
       'gbadu',
       'gbaya',
       'gbawe',
       'gbach',
       'gbara',
       'gbako',
       'gbala',
       'gbap',
       'gba3',
       'gba2',
       'gbas'],
 'b': ['gbbs', 'gbb'],
 'c': ['gbcast', 'gbcw', 'gbcs', 'gbc'],
 'd': ['gbde', 'gbd'],
 'e': ['gberedou-baranama',
       'gberedou/hamana',
       'gbetihindjou',
       'gbegourou',
       'gbendembu',
       'gbessoba',
       'gbeleban',
       'gbekekro',
       'gbelany',
       'gbetogo',
       'gbehoue',
       'gbenga',
       'gbeogo',
       'gbegbe',
       'gbedin',
       'gbejna',
       'gbelce',
       'gberu',
       'gbelo',
       'gbeho',
       'gbefi',
       'gbedu',
       'gbely',
       'gbeko',
       'gbeke',
       'gbe'],
 'f': ['gbfl', 'gbf1', 'gbfc', 'gbf'],
 'g': ['gbgt1', 'gbg'],
 'h': ['gbhs', 'gbh'],
 'i': ['gbingue', 'gbinti', 'gbiska', 'gbiti', 'gbi'],
 'j': ['gbj'],
 'k': ['gbk'],
 'l': ['gbledi-agbogame', 'gbld-345', 'gbliglo', 'gbla', 'gbl'],
 'm': ['gbm'],
 'n': ['gbn'],
 'o': ['gbofesso-sama',
       'gbokopeteme',
       'gbolouville',
       'gbon-houye',
       'gbozounme',
       'gbolahan',
       'gbongaha',
       'gbongan',
       'gbonyin',
       'gboguhe',
       'gbogolo',
       'gbokle',
       'gbonne',
       'gbowtr',
       'gboard',
       'gboko',
       'gbon',
       'gbo'],
 'p': ['gbp510', 'gbp2', 'gbp1', 'gbp5'],
 'q': ['gbq'],
 'r': ['gbr-12935',
       'gbr-12783',
       'gbr-13069',
       'gbr-13098',
       'gbr-13119',
       'gbrimani',
       'gbrimah',
       'gbr'],
 's': ['gbsd', 'gbs'],
 't': ['gbtw', 'gbt'],
 'u': ['gbulahagu',
       'gbulung',
       'gbugli',
       'gbu-28',
       'gbudwe',
       'gbu-15',
       'gbur',
       'gbu'],
 'v': ['gbv'],
 'x': ['gbx2', 'gbx'],
 'y': ['gby'],
 'z': ['gbz']}
