
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vk = {'_': ['vk_singidunum',
       'vk_prostejov',
       'vk_vojvodina',
       'vk_primorje',
       'vk_zepperen',
       'vk_partizan',
       'vk_beograd',
       'vk_opatija',
       'vk_banjica',
       'vk_sibenik',
       'vk_solaris',
       'vk_mobile',
       'vk_kladno',
       'vk_mornar',
       'vk_osijek',
       'vk_bosna',
       'vk_becej',
       'vk_budva',
       'vk_dunav',
       'vk_sabac',
       'vk_zak',
       'vk_jug',
       'vk_20'],
 'a': ['vka_vodka'],
 'b': ['vkb'],
 'c': ['vkc_footwear'],
 'e': ['vkernel'],
 'g': ['vkg_elektrivorgud'],
 'h': ['vkhodnoy_island'],
 'l': ['vklse_gyor'],
 'm': ['vkm'],
 'o': ['vkorc1'],
 'p': ['vkp_bratislava'],
 's': ['vks737'],
 't': ['vkt-line', 'vktrace', 'vkt'],
 'v': ['vkv_dibrugarh', 'vkv_golaghat', 'vkv_shergaon', 'vkv_hurda']}
