
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dp = {'_': ['dp-64', 'dp-65', 'dp3t', 'dp1', 'dp2'],
 'a': ['dpa-713',
       'dpa-714',
       'dpagt1',
       'dpann',
       'dpath',
       'dpaa',
       'dpac',
       'dpag',
       'dpa'],
 'b': ['dpbs', 'dpb'],
 'c': ['dpcch', 'dpcp', 'dpca', 'dpc'],
 'd': ['dpdgroup', 'dpdch', 'dpdpe', 'dpd'],
 'e': ['dpephos', 'dpe'],
 'f': ['dpf1', 'dpf2', 'dpf'],
 'g': ['dpg'],
 'h': ['dphm-rs', 'dph5', 'dphs', 'dph1', 'dphp', 'dph'],
 'i': ['dpi-3290', 'dpi-287', 'dpi-221', 'dpir', 'dpie', 'dpia', 'dpi'],
 'k': ['dpkg', 'dpk'],
 'l': ['dplyr', 'dplay', 'dpll', 'dpl'],
 'm': ['dpm3', 'dpma', 'dpmi', 'dpm1', 'dpm2', 'dpms', 'dpmo', 'dpm'],
 'n': ['dpni', 'dpn'],
 'o': ['dpon-chen', 'dpo'],
 'p': ['dpp10',
       'dppa3',
       'dpp7',
       'dppc',
       'dpp8',
       'dpp9',
       'dppx',
       'dpp3',
       'dppe',
       'dpp6',
       'dpp1',
       'dpph',
       'dppa',
       'dpp'],
 'r': ['dprevank', 'dprabak', 'dprobes', 'dprc', 'dprg', 'dpr'],
 's': ['dpsir', 'dps'],
 't': ['dpt-mph', 'dpt'],
 'u': ['dpubs', 'dpu'],
 'v': ['dpvweb', 'dpvat', 'dpv'],
 'w': ['dpw'],
 'y': ['dpy19l2', 'dpysl4', 'dpysl2', 'dpysl5', 'dpysl3', 'dpys'],
 'z': ['dpz']}
