
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cb = {'_': ['cb_villarrobledo',
       "cb_l'hospitalet",
       'cb_estudiantes',
       'cb_guadalajara',
       'cb_socuellamos',
       'cb_cajabilbao',
       'cb_valladolid',
       'cb_torrevieja',
       'cb_aismalibar',
       'cb_viladecans',
       'cb_granollers',
       'cb_benicarlo',
       'cb_barcelona',
       'cb_salamanca',
       'cb_atapuerca',
       'cb_tartessos',
       'cb_cantabria',
       'cb_simulator',
       'cb_tarragona',
       'cb_martorell',
       'cb_pardinyes',
       'cb_inmobanco',
       'cb_jennings',
       'cb_axarquia',
       'cb_illescas',
       'cb_conquero',
       'cb_marbella',
       'cb_cornella',
       'cb_insights',
       'cb_zaragoza',
       'cb_alicante',
       'cb_breogan',
       'cb_clavijo',
       'cb_almansa',
       'cb_menorca',
       'cb_alcudia',
       'cb_avenida',
       'cb_granada',
       'cb_myrtia',
       'cb_alzira',
       'cb_getafe',
       'cb_tizona',
       'cb_cangas',
       'cb_zamora',
       'cb_milton',
       'cb_tijola',
       'cb_tormes',
       'cb_bears',
       'cb_elche',
       'cb_moron',
       'cb_valls',
       'cb_mass',
       'cb_bank',
       'cb_inca',
       'cb_prat',
       'cb_unix',
       'cb_vic',
       'cb_200'],
 'a': ['cba_finals', 'cba_uav'],
 'b': ['cbbc_puppets', 'cbbc_idents', 'cbb_bank', 'cbb_o2'],
 'c': ['cbc_saskatchewan',
       'cbc_television',
       'cbc_vancouver',
       'cbc_saskatoon',
       'cbc_winnipeg',
       'cbc_edmonton',
       'cbc_hamilton',
       'cbc_montreal',
       'cbc_halifax',
       'cbc_moncton',
       'cbc_windsor',
       'cbc_concert',
       'cbc_selects',
       'cbc_records',
       'cbc_calgary',
       'cbc_sudbury',
       'cbc_toronto',
       'cbc_museum',
       'cbc_regina',
       'cbc_quebec',
       'cbc_ottawa',
       'cbc_london',
       'cbc_sports',
       'cbc_tower',
       'cbc_music',
       'cbc_north',
       'cbc_radio',
       'cbc_arts',
       'cbc_news',
       'cbc_band',
       'cbc_kids',
       'cbc_sho'],
 'd': ['cbd_architects',
       'cbd_cigarette',
       'cbd_belapur',
       'cbd_media',
       'cbd_line',
       'cbd_loop'],
 'e': ['cbe_software', 'cbe_sa'],
 'f': ['cbf_ranking', 'cbf_elda'],
 'g': ['cbgb_forever'],
 'h': ['cbh_group', 'cbh_class', 'cbh_bank'],
 'i': ['cbi_laboratories'],
 'j': ['cbjx-fm', 'cbj800', 'cbj-fm', 'cbj'],
 'k': ['cbkft-dt',
       'cbka-fm',
       'cbkt-dt',
       'cbkf-fm',
       'cbk-fm',
       'cbkst',
       'cbkl',
       'cbkg',
       'cbka',
       'cbkj',
       'cbkn',
       'cbkr',
       'cbkm',
       'cbko',
       'cbk'],
 'l': ['cbl_properties', 'cbl_index'],
 'm': ['cbm_compound', 'cbm_tv'],
 'n': ['cbn_ogbogbo', 'cbn_asia'],
 'o': ['cboss_corporation'],
 'p': ['cbpp', 'cbp'],
 'q': ['cbqt-fm', 'cbqr-fm', 'cbq-fm', 'cbqi', 'cbq'],
 'r': ['cbr96-doxorubicin_immunoconjugate',
       'cbrn_defense',
       'cbr_building',
       'cbre_group',
       'cbr_brave'],
 's': ['cbs_laboratories',
       'cbs_telenoticias',
       'cbs_productions',
       'cbs_springfield',
       'cbs_corporation',
       'cbs_moneywatch',
       'cbs_storybreak',
       'cbs/fox_video',
       'cbs_roscommon',
       'cbs_paramount',
       'cbs_innertube',
       'cbs_playhouse',
       'cbs_rochester',
       'cbs_workshop',
       'cbs_kilkenny',
       'cbs_building',
       'cbs_portland',
       'cbs_catalyst',
       'cbs_mornings',
       'cbs_columbia',
       'cbs_columbus',
       'cbs_outdoor',
       'cbs_daytime',
       'cbs_kidshow',
       'cbs_station',
       'cbs_reality',
       'cbs_justice',
       'cbso_centre',
       'cbs_reports',
       'cbs_tramore',
       'cbso_chorus',
       'cbs_records',
       'cbs_studios',
       'cbs_eblana',
       'cbs_mobile',
       'cbs_domain',
       'cbs_europa',
       'cbs_austin',
       'cbs_sports',
       'cbs_albany',
       'cbs_drama',
       'cbs_cable',
       'cbs_cares',
       'cbs_radio',
       'cbs_watch',
       'cbs_films',
       'cbs_news',
       'cbs_12',
       'cbs_42',
       'cbs_47',
       'cbs_10',
       'cbs_32',
       'cbs_19',
       'cbs_11',
       'cbs_17',
       'cbs_13',
       'cbs_7',
       'cbs_9',
       'cbs_8',
       'cbs_3',
       'cbs_5',
       'cbs_6',
       'cbs_2',
       'cbs_4'],
 't': ['cbtf_technology', 'cbtis_11'],
 'u': ['cbu_capers'],
 'v': ['cbv_binnenland',
       'cbv_institute',
       'cbv_smallcap',
       'cbv_sectors',
       'cbv_midcap',
       'cbv_index',
       'cbv_total'],
 'w': ['cbwft-dt',
       'cbwt-dt',
       'cbwk-fm',
       'cbw-fm',
       'cbwd2',
       'cbwd1',
       'cbwa',
       'cbwf',
       'cbwd',
       'cbw'],
 'x': ['cbxft-dt',
       'cbxt-dt',
       'cbx-fm',
       'cbx1',
       'cbx3',
       'cbx2',
       'cbx7',
       'cbx8',
       'cbxa',
       'cbx5',
       'cbx'],
 'y': ['cbyg-fm', 'cbyk-fm', 'cbyw', 'cby1', 'cbyt', 'cby'],
 'z': ['cbz_holdings']}
