
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cg = {'_': ['cg_suppression',
       "cg'ose_ntcox'o",
       'cg_supervisor',
       'cg_puigcerda',
       'cg_railway',
       'cg_artist',
       'cg_cygni',
       'cg_4'],
 'a': ['cgac', 'cgap', 'cgal', 'cga'],
 'b': ['cgb7', 'cgb5', 'cgb1', 'cgb2', 'cgb'],
 'c': ['cgcg_049-033', 'cgcoc_group', 'cgcn_group', 'cgc_japan'],
 'd': ['cgd'],
 'e': ['cgetv', 'cger', 'cgea', 'cgel', 'cge'],
 'f': ['cgfc'],
 'g': ['cggbp1', 'cggs', 'cgg'],
 'h': ['cgh_physics', 'cghs_model'],
 'i': ['cgi_inc.'],
 'k': ['cgk733_fraud'],
 'l': ['cgl'],
 'm': ['cgm_gallagher', 'cgm_558'],
 'n': ['cgnet_swara', 'cgna_toxin'],
 'o': ['cgol', 'cgo'],
 'p': ['cgp_52608', 'cgp_grey'],
 'r': ['cgram_software', 'cgr_railmotor', 'cgr_0-6-0st', 'cgr_0-6-0t'],
 's': ['cgs_kamaruzzaman',
       'cgs_patuakhali',
       'cgs_rangamati',
       'cgs_tajuddin',
       'cgs_aberdeen',
       'cgs_vigilant',
       'cgs_kutubdia',
       'cgs_margaret',
       'cgs_noakhali',
       'cgs_aviation',
       'cgs_kestrel',
       'cgs_lambton',
       'cgs_stanley',
       'cgs_sonadia',
       'cgs_alaska',
       'cgs_petrel',
       'cgs_acadia',
       'cgs_bogra',
       'cgs_minto',
       'cgs_pabna',
       'cgs_hawk'],
 't': ['cgtn_documentary',
       'cgtn_russian',
       'cgtn_america',
       'cgtn_spanish',
       'cgtn_french',
       'cgtn_arabic',
       'cgtn_africa'],
 'u': ['cgu_insurance', 'cgu_plc'],
 'v': ['cgview', 'cgv'],
 'w': ['cgwa', 'cgw'],
 'y': ['cgy']}
