
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_wt = {'_': ['wt_small_house'],
 'a': ['wta_international_tournaments',
       'wta_doubles_championships',
       'wta_aix-en-provence_open',
       'wta_premier_tournaments',
       'wta_congoleum_classic',
       'wta_tournament_awards',
       'wta_1000_tournaments',
       'wta_500_tournaments',
       'wta_250_tournaments',
       'wta_125_tournaments',
       'wta_dusseldorf_open',
       'wta_south_carolina',
       'wta_argentine_open',
       'wta_singapore_open',
       'wta_shenzhen_open',
       'wta_auckland_open',
       'wta_slovenia_open',
       'wta_austrian_open',
       'wta_tour_records',
       'wta_elite_trophy',
       'wta_prague_open',
       'wta_indian_open',
       'wta_tour_tennis',
       'wta_poland_open',
       'wta_taiwan_open',
       'wta_qatar_open',
       'wta_swiss_open',
       'wta_new_jersey',
       'wta_san_marino',
       'wta_nice_open',
       'wta_lyon_open'],
 'c': ['wtc_cortlandt_station'],
 's': ['wts_sparta_wroclaw'],
 'v': ['wtvr_tv_tower']}
