
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_wl = {'a': ['wladyslawowo,_kuyavian-pomeranian_voivodeship',
       'wladyslawowo,_warmian-masurian_voivodeship',
       'wladyslawowo,_podlaskie_voivodeship',
       'wladyslawow,_silesian_voivodeship',
       'wladyslaw_franciszek_jablonowski',
       'wladyslawowo,_lodz_voivodeship',
       'wladyslawowo,_ciechanow_county',
       'wladyslawowo,_gmina_wierzbinek',
       'wladyslaw_aleksander_lubienski',
       'wladyslaw_mieczyslaw_kozlowski',
       'wladyslawow,_przysucha_county',
       'wladyslawow,_piaseczno_county',
       'wladyslawow,_pabianice_county',
       'wladyslawowo_railway_station',
       'wladyslawow,_zyrardow_county',
       'wladyslaw_hieronim_sanguszko',
       'wladyslawow,_piotrkow_county',
       'wladyslawow,_gmina_sochaczew',
       'wladyslawowo,_zuromin_county',
       'wladyslaw_stanislaw_zamoyski',
       'wladyslaw_grzegorz_branicki',
       'wladyslawowo,_plonsk_county',
       'wladyslawow,_gmina_zelechow',
       'wladyslaw_edward_kronenberg',
       'wladyslaw_dominik_zaslawski',
       'wladyslawowo,_gmina_kleczew',
       'wladyslawow,_gmina_garwolin',
       'wladyslaw_iii_spindleshanks',
       'wladyslawow,_parczew_county',
       'wladyslawow,_leczyca_county',
       'wladyslawow,_otwock_county',
       'wladyslawow,_zgierz_county',
       'wladyslaw_leopold_jaworski',
       'wladyslaw_marian_jakowicki',
       'wladyslawow,_losice_county',
       'wladyslawow,_zwolen_county',
       'wladyslawow,_chelm_county',
       'wladyslawow,_plock_county',
       'wladyslawow,_lukow_county',
       'wladyslaw_andrzej_serczyk',
       'wladyslawow,_kutno_county',
       'wladyslawow,_rawa_county',
       'wladyslaw_konstanty_vasa',
       'wladyslaw_the_hunchback',
       'wladyslawow,_gmina_ilow',
       'wladimir_de_schoenefeld',
       'wladimir_van_wilgenburg',
       'wladyslaw_ludwik_anczyc',
       'wladimir_von_pawlowski',
       'wladyslaw_leon_sapieha',
       'wladimir_jan_kochanski',
       'wladyslaw_ii_jagiello',
       'wladyslaw_jan_grabski',
       'wladyslaw_of_oswiecim',
       'wladyslaw_i_lokietek',
       'wladimir_a._smirnoff',
       'wladyslaw_of_legnica',
       'wladimiro_de_liguoro',
       'wladyslaw_jan_zmuda',
       'wladyslaw_of_glogow',
       'wladyslaw_the_white',
       'wladyslaw_of_bytom',
       'wladyslaw_t._benda',
       'wladyslaw_i_herman',
       'wladyslaw_of_opole',
       'wladyslaw_of_zator',
       'wladyslaw_iv_vasa'],
 'c': ['wlc_college_india'],
 'i': ['wli_falls_festival'],
 'o': ['wlosciborz,_kuyavian-pomeranian_voivodeship',
       'wlostowo,_kuyavian-pomeranian_voivodeship',
       'wloki,_kuyavian-pomeranian_voivodeship',
       'wlostow,_swietokrzyskie_voivodeship',
       'wlochow,_swietokrzyskie_voivodeship',
       'wlodzimierz_julian_korab-karpowicz',
       'wlosienica,_pomeranian_voivodeship',
       'wlodzimierzow,_gmina_aleksandrow',
       'wlodowice,_silesian_voivodeship',
       'wlostowice,_lubusz_voivodeship',
       'wlodzimierz_alfons_czartoryski',
       'wlodki,_podlaskie_voivodeship',
       'wlostowice,_lodz_voivodeship',
       'wlodzimierz,_radomsko_county',
       'wlonice,_gmina_wojciechowice',
       'wlodzimierzow,_gmina_sulejow',
       'wlodki,_masovian_voivodeship',
       'wlosty,_masovian_voivodeship',
       'wlodzislaw,_goleniow_county',
       'wloki,_masovian_voivodeship',
       'wlochow,_lubusz_voivodeship',
       'wlodzimirow,_slupca_county',
       'wloclawek_railway_station',
       'wlodzimirow,_konin_county',
       'wlodzislaw,_slawno_county',
       'wlochy,_opole_voivodeship',
       'wlodzimierz,_lask_county',
       'wloclawek_rowing_society',
       'wlostow,_gorzow_county',
       'wlochy,_pinczow_county',
       'wlodzimierz_of_cracow',
       'wlosty,_goldap_county',
       'wlonice,_gmina_ozarow',
       'wlochy,_kielce_county',
       'wlostow,_zary_county',
       'wloclawek_aero_club',
       'wlosty,_pisz_county'],
 'w': ['wlw_heavyweight_championship',
       'wlw_ladies_championship',
       'wlwt_tv_tower'],
 'y': ['wlynkowo_railway_station']}
