
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sd = {'_': ['sd-women', 'sd-wan', 'sd10', 'sd14', 'sd18', 'sd40', 'sd1'],
 'a': ['sdad1', 'sdau', 'sdaw', 'sdax', 'sdap', 'sda'],
 'b': ['sdb-005', 'sdb-006', 'sdba', 'sdb'],
 'c': ['sdccag8', 'sdch', 'sdco', 'sdcc', 'sdcv', 'sdc'],
 'd': ['sdd-age', 'sddc', 'sdd'],
 'e': ['sderot', 'sdelka', 'sdep', 'sdes', 'sdet', 'sdef', 'sde'],
 'f': ['sdf-4', 'sdf-1', 'sdf2', 'sdfc', 'sdf3', 'sdf4', 'sdf'],
 'g': ['sdge'],
 'h': ['sdhaf2', 'sdhaf1', 'sdha', 'sdhd', 'sdhs', 'sdhb', 'sdh'],
 'i': ['sdi-12', 'sdiri', 'sdic', 'sdif', 'sdib', 'sdio', 'sdia', 'sdi'],
 'j': ['sdj'],
 'k': ['sdk1', 'sdk2', 'sdk'],
 'l': ['sdlbasic', 'sdlt', 'sdla', 'sdlg', 'sdlc', 'sdl'],
 'm': ['sdma', 'sdms', 'sdmx', 'sdm'],
 'n': ['sdn48', 'sdn'],
 'o': ['sdot', 'sdo'],
 'p': ['sdps', 'sdpr', 'sdpd', 'sdp'],
 'q': ['sdq'],
 'r': ['sdre', 'sdrc', 'sdr'],
 's': ['sdssj0946+1006',
       'sds-page',
       'sds-1',
       'sds-4',
       'sdso',
       'sdsc',
       'sdss',
       'sdsl',
       'sdsd',
       'sdsf',
       'sdsr',
       'sdsi',
       'sds'],
 't': ['sdtm', 'sdti', 'sdt'],
 'u': ['sdu'],
 'v': ['sdv'],
 'w': ['sdw'],
 'x': ['sdxcentral', 'sdxf'],
 'y': ['sdy'],
 'z': ['sdz']}
