
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sg = {'_': ['sg-1000', 'sg&a'],
 'a': ['sgarabhaigh',
       'sgambelluri',
       'sgalambro',
       'sgabello',
       'sgambati',
       'sgamna',
       'sgarbi',
       'sgares',
       'sgabeo',
       'sgaa',
       'sgag',
       'sgap',
       'sgac',
       'sga'],
 'b': ['sgb'],
 'c': ['sgce', 'sgcg', 'sgcd', 'sgcb', 'sgcz', 'sgca', 'sgc'],
 'd': ['sgdc-2', 'sgdc-1', 'sgds'],
 'e': ['sgeotasaigh', 'sgem', 'sges', 'sgef', 'sge'],
 'f': ['sgf'],
 'g': ['sggs', 'sgg'],
 'h': ['sgh-d500', 'sghc', 'sghs', 'sgh'],
 'i': ['sginnovate',
       'sgian-dubh',
       'sgibeyevo',
       'sgip1',
       'sgis',
       'sgio',
       'sgic',
       'sgi'],
 'k': ['sgk3', 'sgk1', 'sgk2', 'sgk'],
 'l': ['sglr', 'sgl'],
 'm': ['sgmlguid', 'sgms1', 'sgma', 'sgm'],
 'n': ['sgnl>05', 'sgnl', 'sgn'],
 'o': ['sgoldstino',
       'sgonico',
       'sgouros',
       'sgorio',
       'sgol1',
       'sgoth',
       'sgol2',
       'sgo48',
       'sgo'],
 'p': ['sgpta', 'sgpl1', 'sgpp1', 'sgpio', 'sgps', 'sgp'],
 'r': ['sgraffito', 'sgroppino', 'sgr-a1', 'sgro', 'sgr'],
 's': ['sgsecure',
       'sgs/scn',
       'sgsm1',
       'sgsm2',
       'sgss',
       'sgsh',
       'sgs1',
       'sgsv',
       'sgsd',
       'sgs'],
 't': ['sgta', 'sgt'],
 'u': ['sgurrenergy', 'sgurgola', 'sgula', 'sguil', 'sgu'],
 'v': ['sgv'],
 'w': ['sgw'],
 'x': ['sgx']}
