
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sf = {'_': ['sf-kanalen',
       'sf-studio',
       'sf-6847',
       'sf.citi',
       'sf3b14',
       'sf-180',
       'sf3b5',
       'sf3b1',
       'sf3b4',
       'sf-36',
       'sf-12',
       'sf3a3',
       'sf3b3',
       'sf3a1',
       'sf3a2',
       'sf3b2',
       'sf21',
       'sf9',
       'sf3',
       'sf1',
       'sf5',
       'sf7',
       'sf8'],
 'a': ['sfarma-piatra',
       'sfakiotes',
       'sfasferia',
       'sfatayim',
       'sfakians',
       'sfassif',
       'sfarcea',
       'sfakera',
       'sfaray',
       'sfafaa',
       'sfakia',
       'sfaka',
       'sfaar',
       'sfard',
       'sfazu',
       'sfai',
       'sfar',
       'sfas',
       'sfax',
       'sfa'],
 'b': ['sfbc', 'sfb'],
 'c': ['sfcontario', 'sfcc', 'sfcg', 'sfcw', 'sfca', 'sfco', 'sfc'],
 'd': ['sfdisk', 'sfdr', 'sfdk', 'sfd'],
 'e': ['sfermion',
       'sferakon',
       'sfelinos',
       'sfendami',
       'sfengus',
       'sferke',
       'sfecel',
       'sfenj',
       'sfeir',
       'sfera',
       'sfena',
       'sfer',
       'sfe'],
 'f': ['sffilm', 'sffc', 'sff'],
 'g': ['sfgirl.com', 'sfgp', 'sfga', 'sfg'],
 'h': ['sfham', 'sfhea', 'sfhs', 'sfha', 'sfh'],
 'i': ['sfitakantha',
       'sfintisori',
       'sfintesti',
       'sfiaplus',
       'sfissifa',
       'sfissef',
       'sfinks',
       'sfiha',
       'sfinx',
       'sfira',
       'sfi1',
       'sfia',
       'sfi'],
 'j': ['sfj'],
 'k': ['sfk'],
 'l': ['sflow', 'sfls', 'sfl'],
 'm': ['sfmbt1', 'sfma', 'sfm'],
 'n': ['sfnt', 'sfnb', 'sfn'],
 'o': ['sfogliatella',
       'sforzando',
       'sfondrati',
       'sforzinda',
       'sfoglina',
       'sfouf',
       'sfos',
       'sfof',
       'sfog'],
 'p': ['sfpark', 'sfpq', 'sfpa', 'sfpc', 'sfp'],
 'r': ['sfrs17a',
       'sfrs2ip',
       'sfrs12',
       'sfrs16',
       'sfrs14',
       'sfrs11',
       'sfrp4',
       'sfrs4',
       'sfrp2',
       'sfrp5',
       'sfrs2',
       'sfrs6',
       'sfrs7',
       'sfrs9',
       'sfrs5',
       'sfruz',
       'sfrs3',
       'sfro',
       'sfra',
       'sfr'],
 's': ['sfscope', 'sfstory', 'sfswap', 'sfss', 'sfs'],
 't': ['sftp', 'sfts', 'sftb', 'sft'],
 'u': ['sfumatura', 'sfumato', 'sfuhen'],
 'v': ['sfv'],
 'w': ['sfwa', 'sfwu', 'sfwp', 'sfw'],
 'x': ['sfxn1', 'sfx'],
 'z': ['sfzero', 'sfz']}
