
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zr = {'_': ['zr-75-1'],
 'a': ['zrarieh_raid'],
 'c': ['zrcv', 'zrce'],
 'e': ['zrecze_chalupczanskie',
       'zrenjanin_airport',
       'zrenjanin_theatre',
       'zrecze_duze',
       'zrecze_male',
       'zrebar_lake'],
 'f': ['zrf1'],
 'h': ['zrh'],
 'i': ['zrinski_topolovac',
       'zrinski_battalion',
       'zrinka_cvitesic',
       'zrinjski_mostar',
       'zrinko_ogresta',
       'zrinski_bridge',
       'zrinski_family',
       'zrinka_ljutic',
       'zrinski_park',
       'zrinska_gora',
       'zrin_castle'],
 'k': ['zrk_danilovgrad',
       'zrk_arandelovac',
       'zrk_ajdovscina',
       'zrkadlo_rokov',
       'zrk_kumanovo',
       'zrk_metalurg',
       'zrk_pelister',
       'zrk_velenje',
       'zrk_zajecar',
       'zrk_vardar',
       'zrk_ilidza',
       'zrk_zamet',
       'zrk_naisa',
       'zrk_celje',
       'zrk_borac'],
 'l': ['zrl'],
 'm': ['zrmanja'],
 'n': ['zrnovci_municipality'],
 'o': ['zrobki', 'zrodla', 'zro'],
 'p': ['zrp'],
 's': ['zrsr2', 'zrsr1', 'zrs'],
 't': ['zrtp'],
 'u': ['zrubavel_gilad'],
 'y': ['zryanin', 'zrykh'],
 'z': ['zrze_monastery']}
