
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zn = {'_': ['zn2+-exporting_atpase'],
 'a': ['znamensky_district',
       'znamensky_theatre',
       'znamenskiy_island',
       'znamenka,_russia',
       'znamianka_raion',
       'znamenka_street',
       'znamianka_druha',
       "znam's_problem",
       'znaur_district',
       'znamenny_chant',
       'znaur_gassiev',
       'znachit,_pora',
       'znayu_ya'],
 'b': ['znbb-fm', 'znbn-fm'],
 'c': ['znc-fm', 'znc'],
 'd': ['znd'],
 'e': ['znetalici', 'znetinek', 'znen', 'zne'],
 'f': ['znfx1-as1',
       'znf277p',
       'znf385d',
       'znf133',
       'znf225',
       'znf143',
       'znf267',
       'znf471',
       'znf281',
       'znf384',
       'znf638',
       'znf548',
       'znf207',
       'znf469',
       'znf33a',
       'znf330',
       'znf182',
       'znf593',
       'znf703',
       'znf436',
       'znf193',
       'znf350',
       'znf268',
       'znf184',
       'znf366',
       'znf571',
       'znf148',
       'znf367',
       'znf146',
       'znf295',
       'znf746',
       'znf364',
       'znf346',
       'znf408',
       'znf644',
       'znf160',
       'znf649',
       'znf451',
       'znf259',
       'znf707',
       'znf331',
       'znf365',
       'znf318',
       'znf598',
       'znf219',
       'znf423',
       'znf202',
       'znf264',
       'znf239',
       'znf655',
       'znf473',
       'znf676',
       'znf238',
       'znf821',
       'znf274',
       'znf217',
       'znf452',
       'znf664',
       'znf687',
       'znf300',
       'znf224',
       'znf843',
       'znf837',
       'znf497',
       'znf830',
       'znf37a',
       'znf337',
       'znf383',
       'znf33b',
       'znf831',
       'znf83',
       'znf16',
       'znf71',
       'znf41',
       'znf24',
       'znf79',
       'znf35',
       'znf76',
       'znf22',
       'znf74',
       'znf44',
       'znf34',
       'znf19',
       'znf23',
       'znf10',
       'znf43',
       'znf3',
       'znf8',
       'znf7'],
 'g': ['zngf-fm', 'zngb-fm', 'zngr-fm', 'zng-fm'],
 'h': ['znh-fm'],
 'i': ['znicz_pruszkow', 'znicz_jaroslaw', 'zniwiarz_group', 'znin_county'],
 'j': ['znjy-fm', 'znj-fm', 'znjan'],
 'k': ['znk_dinamo-maksimir',
       'znk_radomlje',
       'znk_neretva',
       'znk_pomurje',
       'znk_osijek',
       'znk_hajduk',
       'znk_rijeka',
       'znk_donat',
       'znk_agram',
       'znk_ombla',
       'znk_split',
       'znk_krka'],
 'l': ['znl-fm'],
 'm': ['znm-fm'],
 'n': ['znnt-fm', 'znn'],
 'o': ['zno_nanostructures',
       'znojmo_catacombs',
       'znojile,_kamnik',
       'znojmo_district',
       'znojile,_tolmin',
       'znojmo_rotunda',
       'znojmo_castle'],
 'p': ['znp-fm', 'znp'],
 'r': ['znrd1-as1', 'znrd1', 'znrf1'],
 's': ['zns-3-fm', 'znst-fm', 'zns-tv', 'zns-2', 'zns-3', 'zns-1', 'zns'],
 'u': ['znucalite', 'znuabc'],
 'w': ['znw-fm'],
 'y': ['zny-fm']}
