
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kc = {'_': ['kc_sivasankaran',
       'kc_masterpiece',
       'kc_motorgroup',
       'kc_accidental',
       'kc_concepcion',
       'kc_athletics',
       'kc_streetcar',
       'kc_ohaebosim',
       'kc_lightfoot',
       'kc_mitchell',
       'kc_spinelli',
       'kc_cariappa',
       'kc_corkery',
       'kc_hilites',
       'kc_johnson',
       'kc_montero',
       'kc_eusebio',
       'kc_akshay',
       'kc_porter',
       'kc_rebell',
       'kc_lights',
       'kc_claffy',
       'kc_becker',
       'kc_groves',
       'kc_ndefo',
       'kc_adams',
       'kc_chan',
       'kc_ten',
       'kc_85'],
 'a': ['kca_university', 'kca_bangalore', 'kca_deutag'],
 'b': ['kcbs-tv/fm_tower', 'kcbx_terminals', 'kcbs_pentagram', 'kcb_group'],
 'c': ['kcc_corporation', 'kcci_tower', 'kcc_malls'],
 'd': ['kcdn-ld',
       'kcdo-tv',
       'kcdm-lp',
       'kcdh-lp',
       'kcdsa',
       'kcdr',
       'kcda',
       'kcdv',
       'kcdl',
       'kcdy',
       'kcds',
       'kcdc',
       'kcdq',
       'kcdi',
       'kcdz',
       'kcdu',
       'kcdx',
       'kcdd',
       'kcd'],
 'e': ['kce_electronics', 'kcet_studios'],
 'f': ['kcf_technologies'],
 'g': ['kcg_holdings'],
 'h': ['kchung_radio'],
 'i': ['kcipher-2',
       'kcib-ld',
       'kciz-lp',
       'kcig-lp',
       'kciw-lp',
       'kciu-lp',
       'kcix-tv',
       'kciv',
       'kcin',
       'kcif',
       'kcim',
       'kcii',
       'kcil',
       'kcid',
       'kcic',
       'kcir',
       'kciw',
       'kciu',
       'kcit',
       'kcie',
       'kcis',
       'kcix',
       'kci'],
 'j': ['kcjo-ld',
       'kcjp-lp',
       'kcjv-lp',
       'kcjm-lp',
       'kcjc',
       'kcjz',
       'kcjb',
       'kcjj',
       'kcjk'],
 'k': ['kcks-ld',
       'kckx',
       'kcko',
       'kckl',
       'kckq',
       'kckv',
       'kckn',
       'kckr',
       'kckz',
       'kckf',
       'kckc',
       'kcky',
       'kckj',
       'kckp',
       'kckb',
       'kcks',
       'kckm'],
 'l': ['kclr_96fm'],
 'm': ['kcmn-ld',
       'kcmo-fm',
       'kcmx-fm',
       'kcmc-fm',
       'kcma-lp',
       'kcmu-lp',
       'kcmj-lp',
       'kcmf1',
       'kcmg',
       'kcmn',
       'kcmh',
       'kcmc',
       'kcmq',
       'kcme',
       'kcmj',
       'kcmt',
       'kcmk',
       'kcmx',
       'kcmi',
       'kcmy',
       'kcml',
       'kcmu',
       'kcmd',
       'kcmp',
       'kcmm',
       'kcmr',
       'kcmb',
       'kcms',
       'kcm'],
 'n': ['kcnq_channels'],
 'o': ['kcom_group'],
 'p': ['kcpo-ld',
       'kcpw-fm',
       'kcpk-lp',
       'kcpn-ld',
       'kcpo',
       'kcps',
       'kcpx',
       'kcpu',
       'kcpc',
       'kcpt',
       'kcpi',
       'kcpl',
       'kcpr',
       'kcpq',
       'kcpm',
       'kcpk',
       'kcp'],
 'q': ['kcqx-lp', 'kcqq', 'kcqx', 'kcql'],
 'r': ['kcr_cro'],
 's': ['kcskehat_limestone'],
 't': ['kctb-lp',
       'kcts-tv',
       'kctx-fm',
       'kctj-lp',
       'kctq-lp',
       'kctf-lp',
       'kctp-lp',
       'kctu-ld',
       'kcti-fm',
       'kctg-lp',
       'kctt-fm',
       'kctd-lp',
       'kctr-fm',
       'kctd13',
       'kctd12',
       'kctd15',
       'kctd7',
       'kctd8',
       'kctd9',
       'kctc',
       'kcte',
       'kctj',
       'kctx',
       'kctb',
       'kctu',
       'kcty',
       'kctv',
       'kcta',
       'kctz',
       'kcti',
       'kcto',
       'kctn',
       'kct'],
 'u': ['kcug-lp',
       'kcut-lp',
       'kcun-lp',
       'kcuw-lp',
       'kcur-fm',
       'kcui',
       'kcup',
       'kcub',
       'kcuf',
       'kcuz',
       'kcul',
       'kcua',
       'kcug',
       'kcue',
       'kcuk'],
 'v': ['kcvr-fm',
       'kcvh-ld',
       'kcvb-cd',
       'kcvi',
       'kcvp',
       'kcvg',
       'kcvr',
       'kcvm',
       'kcvd',
       'kcvj',
       'kcvk',
       'kcvy',
       'kcvh',
       'kcvo',
       'kcvx',
       'kcvs',
       'kcvv',
       'kcvu',
       'kcvl',
       'kcve'],
 'w': ['kcwq-ld',
       'kcwh-ld',
       'kcwt-cd',
       'kcwi-tv',
       'kcwy-dt',
       'kcwo-tv',
       'kcwg-lp',
       'kcwc-fm',
       'kcwd',
       'kcwa',
       'kcwl',
       'kcwc',
       'kcwt',
       'kcwe',
       'kcwj',
       'kcwr',
       'kcwx',
       'kcwu',
       'kcwv',
       'kcwn',
       'kcwk',
       'kcwh',
       'kcwm',
       'kcwf',
       'kcwb'],
 'x': ['kcxp-lp', 'kcxl', 'kcxm', 'kcxr', 'kcxx', 'kcxy', 'kcx'],
 'y': ['kcyninka',
       'kcyb-lp',
       'kcyr-lp',
       'kcyu-ld',
       'kcyi-lp',
       'kcym-ld',
       'kcyc-lp',
       'kcyp-lp',
       'kcynia',
       'kcyn',
       'kcyk',
       'kcyz',
       'kcye',
       'kcys',
       'kcya',
       'kcyy',
       'kcyl'],
 'z': ['kczq', 'kczz', 'kczo', 'kcze']}
