
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kp = {'_': ['kp-sam_shingung',
       'kp_vivekananda',
       'kp_namboodiris',
       'kp_technology',
       'kp_khanal',
       'kp_snacks',
       'kp_sopot',
       'kp_media',
       'kp_duty',
       'kp_lodz'],
 'a': ['kpatcha_gnassingbe',
       'kparia_waterfalls',
       'kparblee_district',
       'kpandai_district',
       'kpassagnon_gneto',
       'kpanda_chiefdom',
       'kpasam_language',
       'kpayan_district',
       'kpalikpakpa_za',
       'kpaka_chiefdom',
       'kpando_stadium',
       'kpati_language',
       'kpan_language',
       'kpale_kpalime',
       'kpalime_duga',
       'kpah_sherman',
       'kpana_lewis'],
 'b': ['kpbx-fm',
       'kpbi-ca',
       'kpbq-fm',
       'kpbs-fm',
       'kpbt-tv',
       'kpbn-ld',
       'kpbi',
       'kpba',
       'kpbb',
       'kpbd',
       'kpbx',
       'kpbm',
       'kpbz',
       'kpbg',
       'kpbr',
       'kpbj',
       'kpbs',
       'kpbe',
       'kpbl',
       'kpb'],
 'c': ['kpcz-fm',
       'kpcg-lp',
       'kpcn-lp',
       'kpce-ld',
       'kpct-lp',
       'kpco-fm',
       'kpcr-lp',
       'kpco',
       'kpcv',
       'kpcs',
       'kpcw',
       'kpcz',
       'kpca',
       'kpcl',
       'kpch',
       'kpcp',
       'kpcr',
       'kpcc',
       'kpcq',
       'kpc'],
 'd': ['kpd_1930+2752'],
 'e': ['kpendjal_prefecture',
       'kpele_prefecture',
       'kpelle_syllabary',
       'kpelle_language',
       'kpelle_people',
       'kpee_language',
       'kperou_guera'],
 'f': ['kpfw-ld',
       'kpfs-lp',
       'kpfz-fm',
       'kpft',
       'kpfx',
       'kpfm',
       'kpfn',
       'kpfr',
       'kpfa',
       'kpfk',
       'kpfc',
       'kpf'],
 'g': ['kpga_championship'],
 'h': ['kphotoalbum',
       'kpho-tv',
       'kphe-ld',
       'kphl',
       'kphf',
       'kpht',
       'kphx',
       'kphs',
       'kphw',
       'kphi',
       'kphd',
       'kphr',
       'kphn',
       'kph'],
 'i': ['kpit_technologies', 'kpini_chugu'],
 'j': ['kpjo-ld', 'kpjn-lp', 'kpjr-tv', 'kpjk', 'kpjp', 'kpjc'],
 'k': ['kpkn-ld', 'kpkl', 'kpkk', 'kpkx', 'kpkr', 'kpke', 'kpky', 'kpk'],
 'l': ['kpledjoo_festival', 'kplang_language', 'kpl_awards'],
 'm': ['kpmb_architects',
       'kpmg_building',
       'kpmg_trophy',
       'kpmg_tower',
       'kpm_music'],
 'n': ['kpn_travels', 'kpn_tower', 'kpn_award'],
 'o': ['kpodegbe_djigla',
       'kpong_airfield',
       'kposo_language',
       'kposo_people',
       'kpong_dam',
       'kpo_plus'],
 'p': ['kpp_best'],
 'q': ['kpq-fm', 'kpqn', 'kpqx', 'kpq'],
 'r': ['kpr_kobierzyce'],
 's': ['kps_kielce', 'kpss_test', 'kps_9566'],
 't': ['kpt_f.c.'],
 'u': ['kpuere_department'],
 'v': ['kpvt-ld',
       'kpva-lp',
       'kpvi-dt',
       'kpvm-ld',
       'kpvn-lp',
       'kpvl',
       'kpvs',
       'kpvu',
       'kpvc',
       'kpvw'],
 'w': ['kpwe_language'],
 'x': ['kpxm_tower'],
 'y': ['kpyt-lp', 'kpyn', 'kpyv', 'kpym', 'kpyk'],
 'z': ['kpza-fm', 'kpze-fm', 'kpzk-fm', 'kpzk', 'kpza', 'kpz']}
