
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ui = {'_': ['ui_energy_corporation',
       'ui_fiachrach_muaidhe',
       'ui_fiachrach_aidhne',
       'ui_fiachrach_finn',
       'ui_data_binding'],
 'a': ['uia_di_ciamarella'],
 'b': ['uib_metro_station'],
 'c': ['uic_flames_baseball', 'uic_wagon_numbers', 'uic_college_prep'],
 'h': ['uihlein_soccer_park', 'uiheung_ye_clan'],
 'j': ['uijeongbu_jung-ang_station',
       'uijeongbu_sports_complex',
       'uijeongbu_cycling_team',
       'uijeongbu_high_school',
       'uijong_of_goryeo',
       'uija_of_baekje',
       'uijo_of_goryeo'],
 'l': ['uil_holdings_corporation',
       'uilliam_mag_tighearnan',
       'uilenstede_tram_stop',
       'uilliam_o_cormacain',
       'uilliam_o_fearghail',
       'uilliam_o_duinnin',
       'uiliami_leilua_vi',
       'uileacu_de_beius',
       'uilleag_de_burgh',
       'uilliam_o_dubhda'],
 'n': ['uinkaret_volcanic_field',
       'uinta_county_courthouse',
       'uinta_county,_wyoming',
       'uinta_ground_squirrel',
       'uinta_national_forest',
       'uinta_brewing_company',
       'uinta_highline_trail',
       'uintah_county,_utah',
       'uinta_basin_rail'],
 'r': ['uiryeong_nam_clan', 'uiryeong_yeo_clan', 'uiryeong_ok_clan'],
 's': ['uisko-class_landing_craft',
       'uis_business_school',
       'uist_tramping_song',
       'uis_prairie_stars',
       'uis_irish_plaza',
       'uisge_ban_falls'],
 't': ['uithuizermeeden_railway_station',
       'uitenhage_provincial_hospital',
       'uithuizen_railway_station',
       'uitgeest_railway_station',
       'uitgeverij_de_harmonie',
       'uithuizen_gas_plant',
       'uitkyk,_north_west',
       'uit_oude_grond']}
