
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ix = {'_': ['ix_equilibrium',
       'ix_riigikogu',
       'ix_monogram',
       'ix_carinae',
       'ix_corps',
       'ix_shen'],
 'a': ['ixalodectes_flectocercus',
       'ixapion_variegatum',
       'ixalotriton_parva',
       'ixalotriton_niger',
       'ixala_proutearia',
       'ixala_adventaria',
       'ixala_desperaria',
       'ixa_monodi'],
 'c': ['ixcatlan_mazatec',
       'ixcatec_language',
       'ixcoy_formation',
       'ixchaya_river',
       'ixcan_river'],
 'e': ['ixeris_stolonifera',
       'ixeridium_dentatum',
       'ixelles_cemetery',
       'ixelles_ponds'],
 'f': ['ixform'],
 'h': ['ixhuatan,_chiapas', 'ixhelt_gonzalez'],
 'i': ['ixiolirion_tataricum',
       'ixiamas_municipality',
       'ixil_municipality',
       'ixia_polystachya',
       'ixia_viridiflora',
       'ixit_corporation',
       'ixia_paniculata',
       'ixiamas_airport',
       'ixia_monadelpha',
       'ixias_marianne',
       'ixil_community',
       'ixia_maculata',
       'ixil_language',
       'ixias_pyrene',
       'ixi_software',
       'ixil_people',
       'ixi_limited',
       'ixia_dubia',
       'ixi_lang'],
 'k': ['ixkun'],
 'l': ['ixl,_oklahoma'],
 'm': ['ixmatlahuacan', 'ixmiquilpan', 'ixml', 'ixm'],
 'n': ['ixn'],
 'o': ['ixora_brevipedunculata',
       'ixonanthes_chinensis',
       'ixodia_achillaeoides',
       'ixodes_trianguliceps',
       'ixonanthes_khasiana',
       'ixora_temehaniensis',
       'ixodes_neuquenensis',
       'ixora_finlaysoniana',
       'ixodiphagus_hookeri',
       'ixodes_hoogstraali',
       'ixora_marquesensis',
       'ixora_raivavaensis',
       'ixodes_petauristae',
       'ixodes_ceylonensis',
       'ixodes_persulcatus',
       'ixora_raiateensis',
       'ixodes_holocyclus',
       'ixonia,_wisconsin',
       'ixodes_arboricola',
       'ixodes_scapularis',
       'ixodes_microgalei',
       'ixodes_siamensis',
       'ixora_ooumuensis',
       'ixodes_cornuatus',
       'ixora_malabarica',
       'ixora_setchellii',
       'ixora_mooreensis',
       'ixora_panurensis',
       'ixora_yavitensis',
       'ixodes_pacificus',
       'ixodes_hexagonus',
       'ixora_margaretae',
       'ixora_chinensis',
       'ixora_saulierei',
       'ixora_johnsonii',
       'ixodes_brunneus',
       'ixora_umbellata',
       'ixodes_angustus',
       'ixora_nigricans',
       'ixodes_canisuga',
       'ixora_peruviana',
       'ixora_st-johnii',
       'ixodes_ricinus',
       'ixora_nigerica',
       'ixora_elongata',
       'ixora_stokesii',
       'ixora_coccinea',
       'ixodes_tasmani',
       'ixodes_texanus',
       'ixora_beckleri',
       'ixora_lawsonii',
       'ixora_albersii',
       'ixora_calycina',
       'ixodes_kaiseri',
       'ixora_killipii',
       'ixodes_affinis',
       'ixora_foliosa',
       'ixodes_cookei',
       'ixodes_heathi',
       'ixora_pavetta',
       'ixora_euosmia',
       'ixora_jucunda',
       'ixodes_uriae',
       'ixora_pudica',
       'ixodes_minor',
       'ixora_ulei',
       'ixora_rufa'],
 'p': ['ixpantepec_nieves'],
 's': ['ixs_enterprise'],
 't': ['ixtlahuacan_municipality',
       'ixtaltepec_formation',
       'ixtenco_municipality',
       'ixtlan,_michoacan',
       'ixtayutla_mixtec',
       'ixtlilxochitl_ii',
       'ixtepec_airport',
       'ixtlan_district',
       'ixtlilxochitl_i',
       'ixtepec,_oaxaca',
       'ixtapa,_chiapas',
       'ixtaclum_shale',
       'ixtlan_zapotec',
       'ixtli_martinez',
       'ixtacapa_river',
       'ixtapan_region',
       'ixtenco_otomi',
       'ixtapan_river'],
 'w': ['ixworth_chicken', 'ixworth_thorpe', 'ixworth_priory'],
 'y': ['ixylasia_semivitreata',
       'ixylasia_pyroproctis',
       'ixylasia_trogonoides',
       'ixys_corporation',
       'ixylasia_schausi',
       'ixylasia_trogon']}
