
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tz = {'_': ["tz'utujil_language",
       "tz'utujil_people",
       'tz_cassiopeiae',
       'tz_database',
       'tz_limited'],
 'a': ['tzanis_stavrakopoulos',
       'tzannis_tzannetakis',
       'tzanetos_grigorakis',
       'tzavalas_karousos',
       'tzadikim_nistarim',
       'tzavaat_harivash',
       'tzamarot_ayalon',
       'tzaconeja_river',
       'tzameret_towers',
       'tzameret_fuerst',
       'tzadik_records',
       'tzachi_hanegbi',
       'tzachi_halevy',
       'tzaims_luksus',
       'tzami_tzentit',
       'tzahi_elihen',
       'tzachi_zamir',
       'tzali_reshef',
       'tzaneen_dam',
       'tzala_river',
       'tzanck_test',
       'tzahi_ilos'],
 'c': ['tzc'],
 'e': ['tzeli_hadjidimitriou',
       'tzedek_ve-shalom',
       'tzeltal_language',
       'tzeporah_berman',
       "tze'elim_stream",
       'tzeltal_people',
       'tzemach_cunin',
       'tzeni_karezi',
       'tzeni_vanou',
       'tzeo_river',
       'tze_chun',
       'tze_char'],
 'f': ['tzfat_cheese'],
 'i': ['tzintzuntzan_municipality',
       'tzintzuntzan,_michoacan',
       'tzipora_jochsberger',
       'tzihuacxochitzin_i',
       'tzippori_synagogue',
       'tzitzeica_equation',
       'tzistarakis_mosque',
       'tzippora_sharett',
       'tziporah_heller',
       'tzipora_obziler',
       'tzimis_panousis',
       'tzina_lamprousi',
       'tzipora_laskov',
       'tzipi_hotovely',
       'tzivos_hashem',
       'tzipora_rimon',
       'tziarra_king',
       'tziduk_hadin',
       'tzipi_shavit',
       'tzimon_barto',
       'tzipi_livni',
       'tzi_ma'],
 'n': ['tzn_xenna'],
 'o': ['tzotzil_language', 'tzoah_rotachat', 'tzoonie_river', 'tzomet_sfarim'],
 'r': ['tzrifin', 'tzrufa'],
 's': ['tzsp'],
 'u': ['tzucacab_municipality',
       'tzur_hadassah',
       'tzufit_grant',
       'tzur_yitzhak',
       'tzur_shezaf',
       'tzur_shalem',
       'tzuri_gueta',
       'tzu-wei_lin',
       'tzur_natan',
       'tzur_moshe',
       'tzukei_yam',
       'tzu_chi'],
 'v': ['tzvetelina_yanchulova',
       'tzvetelina_nikolova',
       'tzvetana_berkovska',
       'tzvia_greenfeld',
       'tzveta_kousseva',
       'tzvetana_maneva',
       'tzvetan_todorov',
       'tzvi_ashkenazi',
       'tzvi_berkowitz',
       'tzvika_tzemah',
       'tzvi_freeman',
       'tzvi_gluckin',
       'tzvi_avisar',
       'tzvika_brot',
       'tzv_gredelj',
       'tzvi_avni',
       'tzvi_erez',
       'tzvi_tzur'],
 'w': ['tzwetta_tzatschewa'],
 'y': ['tzy_uav']}
