
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tn = {'_': ['tn3_transposon',
       'tn_j0924-2201',
       'tn3270_plus',
       'tn_antigen',
       'tn_mobile',
       'tn_status',
       'tn_60',
       'tn_70',
       'tn_61',
       'tn_71',
       'tn_81',
       'tn_80',
       'tn_90',
       'tn_75'],
 'a': ['tna_reaction', 'tna_today', 'tna_epics', 'tna_park'],
 'b': ['tnbc', 'tnb'],
 'c': ['tnco_ceilings', 'tnc_connector', 'tnca_mtw-1'],
 'd': ['tnd'],
 'e': ['tnet', 'tneb', 'tne'],
 'f': ['tnf_inhibitor'],
 'g': ['tngri', 'tnght', 'tng'],
 'h': ['tnh'],
 'i': ['tnine_amellou', 'tnine_aglou', 'tnine_aday'],
 'j': ['tnjri', 'tnj'],
 'k': ['tnkaw_toraani', 'tnk_iii'],
 'l': ['tnl_onstage', 'tnl_tv'],
 'm': ['tnm_jawad'],
 'n': ['tnn_radio'],
 'o': ['tnoy_andrew'],
 'p': ['tnpl_pugalur'],
 'q': ['tnq'],
 'r': ['tnrc15', 'tnrc6b', 'tnrc6a', 'tnr'],
 's': ['tnsc_bank'],
 't': ['tnt_discography',
       'tnt_motorsports',
       'tnt_equivalent',
       'tnt_jackson',
       'tnt_express',
       'tnt_limited',
       'tnt_racers',
       'tnt_series',
       'tnt_africa',
       'tnt_creek',
       'tnt_post',
       'tnt_boys',
       'tnt_ii',
       'tnt_hd',
       'tnt_i'],
 'u': ['tnuvot', 'tnuva', 'tnu'],
 'v': ['tnv'],
 'w': ['tnw'],
 'z': ['tnz']}
