
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fb = {'_': ['fb_mini-beryl',
       'fb_glauberyt',
       'fb_gulbene',
       'fb_tantal',
       'fb_pm-63',
       'fb_beryl',
       'fb_onyks',
       'fb_p-64',
       'fb_mag',
       'fb_vis'],
 'a': ['fba_310',
       'fba_270',
       'fba_290',
       'fba_21',
       'fba_16',
       'fba_10',
       'fba_19',
       'fba_17',
       'fba_13'],
 'b': ['fbbank', 'fbb'],
 'c': ['fbc_kalmarsund',
       'fbc_ostrava',
       'fbc_pierola',
       'fbc_melgar',
       'fbc_aurora',
       'fbc_media',
       'fbc_bank',
       'fbc_tv'],
 'd': ['fbd_holdings'],
 'e': ['fbe'],
 'f': ['fbf'],
 'g': ['fbg'],
 'h': ['fbhs', 'fbh'],
 'i': ['fbi:_international',
       'fbi_laboratory',
       'fbi_mnemonics',
       'fbi_academy',
       'fbi_police',
       'fbi_radio',
       'fbi_index',
       'fbi_files',
       'fbi_girl'],
 'k': ['fbk_karlstad', 'fbk_kaunas', 'fbk_balkan', 'fbk_voss'],
 'l': ['fbla-pbl', 'fblim1', 'fbln5', 'fbln2', 'fbln1', 'fbl'],
 'm': ['fbma_trophy', 'fbme_bank'],
 'n': ['fbn'],
 'o': ['fbop_corporation', 'fboy_island', 'fbo_riga'],
 'p': ['fbp1', 'fbp'],
 'r': ['fbreader', 'fbr-600', 'fbrs', 'fbr'],
 's': ['fbsp_wavelet'],
 't': ['fbt'],
 'u': ['fbus_pokalturnering'],
 'w': ['fbw_80-n'],
 'x': ['fbxw10',
       'fbxo32',
       'fbxo24',
       'fbxo28',
       'fbxo11',
       'fbxo31',
       'fbxo38',
       'fbxw11',
       'fbxl3',
       'fbxo7',
       'fbxl2',
       'fbxw7',
       'fbxo9',
       'fbxo5',
       'fbxw4',
       'fbxl4',
       'fbxw5',
       'fbxw2',
       'fbxo2',
       'fbxl5',
       'fbxo6',
       'fbxo4',
       'fbxl7',
       'fbxw8',
       'fbx']}
