
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ct = {'_': ['ct_pulmonary_angiogram',
       'ct_special_forces',
       'ct_luiz_carvalho',
       'ct_postcode_area',
       'ct_united_fc',
       'ct_rei_pele'],
 'a': ['cta_holiday_train'],
 'b': ['ctbc_taichung_headquarters',
       'ctbuh_skyscraper_award',
       'ctbc_financial_holding',
       'ctbc_business_school',
       'ctbc_financial_park',
       'ctbc_flying_oyster',
       'ctb_flying_squad'],
 'f': ['ctfa_international_tournament'],
 'h': ['cthulhu_mythos_anthology',
       'cthulhu_mythos_species',
       'cthulhu_mythos_deities',
       'cthulhu_for_president',
       "cthulhu's_dark_cults",
       'cthulhu_by_gaslight'],
 'i': ['cti_electronics_corporation',
       'cti_education_group',
       'ctirad_and_sarka',
       'ctia_and_gtia'],
 'k': ['ctk_-_citylink'],
 'n': ['ctn_animation_expo'],
 'p': ['ctp-dependent_riboflavin_kinase', 'ctp_synthase_1'],
 's': ['cts_main_channel'],
 'u': ['ctu:_marine_sharpshooter'],
 'v': ['ctv_television_network',
       'ctv_northern_ontario',
       'ctv_comedy_channel',
       'ctv_sci-fi_channel',
       'ctv-n-2_gorgon_iic',
       'ctv_national_news',
       'ctv_drama_channel',
       'ctv_news_channel',
       'ctv_life_channel',
       'ctv_morning_live',
       'ctv_41_bendigo',
       'ctv_2_atlantic',
       'ctv_2_alberta']}
