
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cb = {'_': ['cb-class_midget_submarine',
       'cb_lucentum_alicante',
       'cb_marin_peixegalego',
       'cb_plasencia_ambroz',
       'cb_amadeo_tortajada',
       'cb_collado_villalba',
       'cb_atletico_guardes',
       'cb_military_symbol',
       'cb_agustinos_eras',
       'cb_islas_canarias',
       'cb_1939_canarias',
       'cb_postcode_area',
       'cb_smith_reserve',
       'cb_fisher_plate',
       'cb_santurtzi_sk',
       'cb_mar_alicante',
       'cb_penas_huesca',
       'cb_gran_canaria',
       'cb_ademar_leon',
       'cb_oar_ferrol',
       'cb_isla_unica',
       'cb_sant_josep',
       'cb_las_rozas'],
 'b': ['cbbc_summer_social'],
 'c': ['cbc_symphony_orchestra',
       'cbc_winnipeg_orchestra',
       'cbc_olympic_broadcasts',
       'cbc_summer_symphonies',
       'cbc_podcast_showcase',
       'cbc_news:_disclosure',
       'cbc_documentary_unit',
       'cbc_radio_overnight',
       'cbc_wednesday_night',
       'cbc_radio_orchestra',
       'cbc_literary_prize',
       'cbc_news:_politics',
       'cbc_news:_morning',
       'cbc_news_magazine',
       'cbc_film_festival',
       'cbc_news:_sunday',
       'cbc_concert_hour',
       'cbc_news_network',
       'cbc_thunder_bay',
       "cbc_st._john's",
       "cbc_drama_'73",
       'cbc_radio_one',
       'cbc_docs_pov',
       'cbc_radio_3',
       'cbc_tv_8'],
 'd': ['cbd_relief_line', 'cbd_rail_link'],
 'h': ['cbhs_health_fund'],
 'l': ['cbl_munchee_bangladesh', 'cbl_tkb_domain'],
 'm': ['cbm_bethel_hospital'],
 'o': ['cboe_global_markets'],
 's': ['cbs_records_international',
       'cbs_schoolbreak_special',
       'cbs_television_workshop',
       'cbs_home_entertainment',
       'cbse_expression_series',
       'cbs_olympic_broadcasts',
       'cbs_sports_spectacular',
       'cbso_youth_orchestra',
       'cbs_broadcast_center',
       'cbs_summer_playhouse',
       'cbs_theatrical_films',
       'cbs_saturday_morning',
       'cbs_studio_building',
       'cbs_television_quiz',
       'cbs_columbia_square',
       'cbs_overnight_news',
       'cbs_sports_classic',
       'cbs_sports_network',
       'cbse_gulf_sahodaya',
       'cbs_radio_workshop',
       'cbs_media_ventures',
       'cbscr_bandon_tank',
       'cbs_sexton_street',
       'cbs_studio_center',
       'cbs_morning_news',
       'cbs_this_morning',
       'cbs_sunday_movie',
       'cbs_sports_radio',
       'cbs_evening_news',
       'cbs_block_party',
       'cbs_news_radio',
       'cbs_dream_team',
       'cbs_fm_buganda',
       'cbs_sports_hq'],
 'u': ['cbu-100_cluster_bomb', 'cbu_events_center'],
 'z': ['cbz_bank_limited']}
