
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cp = {'_': ['cp_cuencas_mineras',
       'cp_urban_services',
       'cp_parla_escuela',
       'cp_san_cristobal',
       'cp_gijon_solimar',
       'cp_goya_almeria',
       'cp_music_group',
       'cp_la_felguera',
       'cp_class_2500',
       'cp_class_1320',
       'cp_system_iii',
       'cp_class_2240',
       'cp_class_1900',
       'cp_class_1200',
       'cp_class_1800',
       'cp_class_1930',
       'cp_class_2600',
       'cp_class_5600',
       'cp_class_1300',
       'cp_nel_museum',
       'cp_class_1500',
       'cp_class_1960',
       'cp_class_1150',
       'cp_granada_74',
       'cp_class_9020',
       'cp_class_2550',
       'cp_class_3150',
       'cp_class_1400',
       'cp_class_1550',
       'cp_class_4700',
       'cp_system_ii',
       'cp_la_roda'],
 'a': ['cpa_practice_advisor'],
 'b': ['cpbl-kbo_club_championship'],
 'c': ['cpcs_transcom_limited',
       'cpc_corporation_f.c.',
       'cpc_binary_barcode',
       'cpc_cine_awards'],
 'd': ['cpdrc_dancing_inmates'],
 'g': ['cpg_island_hypermethylation'],
 'h': ['cph1_holin_family'],
 'i': ['cpi_property_group'],
 'l': ['cplc_community_schools', 'cpl-u_sports_draft'],
 'm': ['cpm_s30v_steel'],
 'o': ['cpo_boss_hogg'],
 'p': ['cpp_investment_board'],
 'r': ['cpr_vaughan_intermodal',
       'cpr_aberdeen_yard',
       'cpr_parkdale_yard',
       'cpr_montrose_yard',
       'cpr_lambton_yard',
       'cpr_buffalo_yard',
       'cpr_toronto_yard',
       'cpr_kinnear_yard',
       'cpr_angus_shops',
       'cpr_alyth_yard',
       'cpr_pier_d'],
 'u': ['cpu_research_center', 'cpu_handbell_choir', 'cpu_core_voltage']}
