
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cm = {'_': ['cm-32_armoured_vehicle',
       'cm-21_armored_vehicle',
       'cm_labs_simulations',
       'cm-11_brave_tiger',
       'cm_postcode_area',
       'cm_ashok_sekhar'],
 'a': ['cma_cgm_bougainville',
       'cma_music_festival',
       'cmas**_scuba_diver',
       'cma_cgm_laperouse',
       'cmas*_scuba_diver',
       'cma_cgm_kerguelen',
       'cma_cgm_butterfly',
       'cma_cgm_thalassa',
       'cma_cgm_magellan',
       'cma_cgm_tower',
       'cma_cgm_medea',
       'cma_cgm_vela'],
 'b': ['cmbt_metro_station', 'cmb_cold_spot'],
 'c': ['cmc_connect_burson-marsteller', 'cmc_music_awards'],
 'd': ['cmd_fd_series'],
 'h': ['cmh_masjid_jhelum'],
 'i': ['cmielow_porcelain_works', 'cmic_music_awards'],
 'l': ['cmll-reina_international_championship',
       'cmll_universal_championship',
       'cmll_leyendas_mexicanas',
       'cmll_super_viernes',
       'cmll_juicio_final',
       'cmll_sin_salida'],
 'm': ['cmmg_mk47_mutant'],
 'p': ["cmp-n,n'-diacetyllegionaminic_acid_synthase",
       'cmp-sialic_acid_transporter'],
 'r': ['cmr_central,_visakhapatnam'],
 's': ['cms_yorkshire_league',
       'cms_college_kottayam',
       'cms_grammar_school',
       'cms_made_simple',
       'cms_file_system'],
 't': ["cmt's_next_superstar",
       'cmt_invitation_only',
       'cmt_cross_country',
       'cmt_comedy_stage',
       'cmt_music_awards',
       'cmt_music_fest',
       'cmt_hot_twenty',
       'cmt_front_row'],
 'u': ['cmu_pronouncing_dictionary', 'cmu_common_lisp'],
 'y': ['cmyk_color_model', 'cmy_color_model']}
