
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jr = {'_': ['jr-shuntokumichi_station',
       'jr-kawachi-eiwa_station',
       'jr-sojiji_station',
       'jr-awaji_station',
       'jr_motorsports',
       'jr-noe_station',
       'jr_esterhuizen',
       'jr_buensuceso',
       'jr_valentin',
       'jr_cawaling',
       'jr_davidson',
       'jr_chandler',
       'jr._pac-man',
       'jr_blender',
       'jr_cigars',
       'jr_hutson',
       'jr_bourne',
       'jr_castro',
       'jr_payne',
       'jr_lemon',
       'jr_shaw',
       'jr_bus',
       'jr_jr'],
 'a': ['jrashen,_armavir',
       'jrarat,_armavir',
       'jrashen,_ararat',
       'jrarat,_shirak',
       'jrarat,_kotayk',
       'jrashen,_lori',
       'jra_award',
       'jra_cup'],
 'b': ['jrb'],
 'c': ['jrcls', 'jrc'],
 'd': ['jrdn'],
 'e': ['jreijes', 'jreap', 'jreif'],
 'f': ['jrf'],
 'g': ['jrg'],
 'h': ['jrhs'],
 'i': ['jri-poland', 'jripples', 'jri'],
 'j': ['jrjr'],
 'k': ['jrk'],
 'l': ['jrl'],
 'm': ['jrman', 'jrm'],
 'n': ['jrn'],
 'o': ['jrockit', 'jro'],
 'p': ['jrp-ringier', 'jrp'],
 'r': ['jrr'],
 's': ['jrs'],
 't': ['jrti', 'jrtc', 'jrt'],
 'u': ['jruchi_monastery', "jru'_language", 'jrue_holiday'],
 'v': ['jrvezh'],
 'y': ['jry_trust'],
 'z': ['jrz']}
