
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jw = {'_': ['jw_komandosow',
       'jw_anderson',
       'jw_farquhar',
       'jw_formoza',
       'jw_jonker',
       'jw_bolton',
       'jw_player',
       'jw_jones',
       'jw_grom',
       'jw_agat'],
 'a': ['jwalamalini_temple',
       'jwaundace_candece',
       'jwacheon_station',
       'jwalshik_wilford',
       'jwaneng_airport',
       'jwaydan_moyine',
       'jwan_zhumbes',
       'jwaar_bhata',
       'jwala_gutta',
       'jwamer_aga',
       'jwala_daku',
       'jwan_yosef',
       'jwan_hesso',
       'jwala_heri',
       'jwar_bhata',
       'jwala_ji'],
 'b': ['jwb'],
 'c': ['jwcc'],
 'd': ['jwd_infologistics'],
 'e': ['jwed.com', 'jwe'],
 'h': ['jwh-424',
       'jwh-133',
       'jwh-047',
       'jwh-081',
       'jwh-250',
       'jwh-019',
       'jwh-371',
       'jwh-368',
       'jwh-366',
       'jwh-149',
       'jwh-365',
       'jwh-120',
       'jwh-373',
       'jwh-198',
       'jwh-367',
       'jwh-196',
       'jwh-015',
       'jwh-122',
       'jwh-359',
       'jwh-147',
       'jwh-210',
       'jwh-175',
       'jwh-372',
       'jwh-030',
       'jwh-018',
       'jwh-200',
       'jwh-150',
       'jwh-369',
       'jwh-116',
       'jwh-057',
       'jwh-164',
       'jwh-161',
       'jwh-302',
       'jwh-098',
       'jwh-148',
       'jwh-251',
       'jwh-176',
       'jwh-370',
       'jwh-146',
       'jwh-203',
       'jwh-363',
       'jwh-307',
       'jwh-073',
       'jwh-007',
       'jwh-309',
       'jwh-193',
       'jwh-398',
       'jwh-185',
       'jwh-167',
       'jwh-184',
       'jwh-364',
       'jwh-051',
       'jwh-249',
       'jwh-048',
       'jwh-145',
       'jwh'],
 'i': ['jwira-pepesa_language'],
 'k': ['jwk'],
 'l': ['jwl'],
 'm': ['jwm_partners'],
 'n': ['jwn'],
 'o': ['jwoww'],
 'p': ['jwpce', 'jwp'],
 'r': ['jwr'],
 's': ['jws'],
 't': ['jwt_jakarta'],
 'y': ['jwycesska_island']}
