
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-25T13:07:57-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "132fd855496f58c97218418cd27ec82ba275f4cf",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
