
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dv = {'_': ['dv8_defenders', 'dv_hasselt', 'dv_aquarii', 'dv_giochi'],
 'a': ['dvarcininkai,_kedainiai',
       'dvaraka-kamboja_route',
       'dvarcioniu_keramika',
       'dvaita_literature',
       'dvar_yerushalayim',
       'dvadasha_stotra',
       'dvaravati_sila',
       'dvaita_vedanta',
       'dvaravati_art',
       'dvaita_forest',
       'dvapara_yuga',
       'dva_ohne'],
 'b': ['dvb_dream', 'dvb_3d-tv', 'dvb_bank'],
 'c': ['dvcreators.net', 'dvcs', 'dvc'],
 'd': ['dvd+rw_alliance',
       'dvd_recordable',
       'dvd_unlimited',
       'dvd_decrypter',
       'dvd_authoring',
       'dvd_recorder',
       'dvd_magazine',
       'dvd_profiler',
       'dvd_monthly',
       'dvd_program',
       'dvd_formats',
       'dvd_verdict',
       'dvd_player',
       'dvd_shrink',
       'dvd_forum',
       'dvd_flick',
       'dvd_card',
       'dvd-r_ds',
       'dvd-r_dl',
       'dvd_talk',
       'dvd+r_dl',
       'dvd_show',
       'dvd+r_ds',
       'dvd_tv',
       'dvd_r'],
 'e': ['dverberg_church', 'dvergen_hill', 'dve_mogili', 'dve_viski'],
 'f': ['dvfs', 'dvfr'],
 'g': ['dvga', 'dvg'],
 'h': ['dvhs', 'dvh'],
 'i': ['dvipada_bhagavatamu',
       'dvir_abramovich',
       'dvinsky_forest',
       'dviete_parish',
       'dvin,_armenia',
       'dvir_benedek',
       'dvija_madhab',
       'dvira_ovadia',
       'dviant_films',
       'dvina_bay'],
 'k': ['dvk'],
 'l': ['dvl1', 'dvl3', 'dvlf', 'dvl2', 'dvlp', 'dvl'],
 'm': ['dvm'],
 'n': ['dvnp', 'dvno', 'dvn'],
 'o': ['dvoretzky-kiefer-wolfowitz_inequality',
       'dvorah_barzilay-yegar',
       "dvoretzky's_theorem",
       'dvoriste_vivodinsko',
       'dvortsovaya_sludka',
       'dvorana_velesajam',
       'dvoriste,_berovo',
       'dvorak_technique',
       'dvorana_mladosti',
       'dvor,_zuzemberk',
       'dvorje,_moravce',
       'dvorce,_brezice',
       'dvor,_ljubljana',
       'dvorichna_raion',
       'dvori,_croatia',
       'dvora,_israel',
       'dvora_bochman',
       'dvora_hacohen',
       'dvor,_croatia',
       'dvora_waysman',
       'dvorce,_saraj',
       'dvor_massacre',
       'dvori,_koper',
       'dvor,_visoko',
       'dvorska_luda',
       'dvora_netzer',
       'dvorsky_les',
       'dvora_omer'],
 'p': ['dvpb-hd', 'dvp'],
 'r': ['dvrsnica', 'dvr-ms', 'dvr'],
 's': ['dvs_records', 'dvs_mindz', 'dvs_shoes', "dvs_'33"],
 't': ['dvtk_jegesmedvek'],
 'u': ['dvuyakornaya_formation', 'dvuhyurtochnoe_lake'],
 'v': ['dvv_coburg'],
 'w': ['dvw'],
 'x': ['dvx']}
