
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dk = {'_': ['dk_lacertae', 'dk_metcalf', 'dk1_rigs', 'dk_rap'],
 'a': ['dkay.com', 'dkan'],
 'b': ['dkb_group', 'dkb_ghana'],
 'c': ['dkc'],
 'd': ['dkdc', 'dkd'],
 'e': ['dke'],
 'f': ['dkfxp'],
 'g': ['dkg'],
 'h': ['dkhissa', 'dkhar', 'dkh'],
 'i': ['dkids', 'dki'],
 'k': ['dkk-sp1', 'dkk3', 'dkk1', 'dkk4', 'dkk2', 'dkk'],
 'l': ['dkl'],
 'm': ['dkms', 'dkm'],
 'n': ['dkny'],
 'o': ['dkoi'],
 'p': ['dkp'],
 'r': ['dkr_engineering'],
 's': ['dksh', 'dks'],
 't': ['dkt_international'],
 'u': ['dku'],
 'v': ['dkv'],
 'w': ['dkw_schnellaster',
       'dkw_junior',
       'dkw_monza',
       'dkw_munga',
       'dkw_f102',
       'dkw_f89',
       'dkw_f10',
       'dkw_3=6',
       'dkw_f2',
       'dkw_f9',
       'dkw_f5',
       'dkw_f1',
       'dkw_f8',
       'dkw_f4',
       'dkw_f7']}
