
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nr = {'_': ['nr_canis_majoris', 'nr_postcode_area', 'nr_25_mine', 'nr_26_mine'],
 'a': ['nra_whittington_center', 'nra_precision_pistol', 'nra_gun_club'],
 'c': ['nrc_tailless_glider'],
 'd': ['nrdc-ita_support_brigade', 'nrdc_equity_partners', 'nrdj_rna_motif'],
 'f': ['nrfl_division_2', 'nrfl_division_1'],
 'g': ['nrg_recording_studios'],
 'h': ['nrheg_high_school'],
 'i': ['nrisimha_tapaniya_upanishad',
       'nrist_unmanned_helicopters',
       'nrisingha_prasad_bhaduri',
       'nrisingha_temple,_nadia',
       'nrist_ii-series_uav',
       'nripjit_singh_bedi',
       'nrist_s-series_uav',
       'nrist_w-series_uav',
       'nripendra_nath_roy',
       'nrist_i-series_uav',
       'nritya_gopal_das',
       'nripa_kama_ii'],
 'j': ['nrj_music_award'],
 'k': ['nrk_regional_services', 'nrk_alltid_nyheter', 'nrk_p3_pyro'],
 'l': ["nrl_women's_premiership",
       'nrl_northern_territory',
       'nrl_state_championship',
       'nrl_western_australia',
       'nrl_touch_premiership',
       'nrl_under-20s_teams',
       'nrl_south_australia',
       'nrl_match_officials',
       'nrl_regular_season',
       'nrl_finals_system',
       'nrl_schoolboy_cup',
       'nrl_mascot_mania',
       'nrl_grand_final',
       'nrl_all_stars',
       'nrl_on_fox'],
 'o': ['nro_program_a'],
 'p': ['nrpatendradevi_of_sambhupura',
       'nrp9_police_revolver',
       'nrp_goncalves_zarco',
       'nrp_bartolomeu_dias',
       'nrp_goncalo_velho',
       'nrp_corte_real',
       'nrp_rio_minho'],
 's': ['nrsp_microfinance_bank',
       'nrs_social_grade',
       'nrs_albro_lake',
       'nrsz_small_rna']}
