# Generated by Django 4.1 on 2022-08-17 07:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('simpleworker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
