
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tx = {'_': ['tx-sector',
       'tx26-427',
       'tx2-6',
       'tx-2',
       'tx-1',
       'tx-0',
       'tx1',
       'tx3',
       'tx2',
       'tx4',
       'tx5'],
 'a': ['txamantxoia', 'txalaparta', 'txarango', 'txakoli', 'txarng', 'txaa'],
 'c': ['txcn'],
 'e': ['txe'],
 'f': ['txfm', 'txf'],
 'g': ['txga'],
 'i': ['txillardegi', 'txindoki', 'txirrita', 'txistu', 'txiki', 'txii', 'txi'],
 'k': ['txk'],
 'l': ['txlnb', 'txl'],
 'n': ['txndc12',
       'txndc5',
       'txnl4a',
       'txndc9',
       'txnl4b',
       'txndc2',
       'txnrd1',
       'txnl1',
       'txnip',
       'txn2',
       'txn'],
 'o': ['txorierri', 'txoko'],
 't': ['txt2tags',
       'txt.fyi',
       'txt-tv',
       'txtmob',
       'txt402',
       'txtag',
       'txtr',
       'txt'],
 'u': ['txutxi', 'txusta', 'txu']}
