
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tc = {'_': ['tc1/mariner',
       'tc-1827',
       'tc-2216',
       'tc-1698',
       'tc-pam',
       'tc2n',
       'tc-1',
       'tc10',
       'tc-2',
       'tc3',
       'tc0',
       'tc1'],
 'a': ['tcaciuc', 'tcaci', 'tcaim', 'tcar', 'tcad', 'tcam', 'tcap', 'tca'],
 'b': ['tcb-2', 'tcbs', 'tcby', 'tcb'],
 'c': ['tcca', 'tccc', 'tccu', 'tcc'],
 'd': ['tcdd', 'tcd'],
 'e': ['tcelna', 'tceal4', 'tceal1', 'tcea1', 'tcea2', 'tcell', 'tcep', 'tce'],
 'f': ['tcf7l1',
       'tcf7l2',
       'tcf15',
       'tcf19',
       'tcf20',
       'tcf12',
       'tcf4',
       'tcf7',
       'tcf3',
       'tcfc',
       'tcfa',
       'tcf'],
 'g': ['tcga', 'tcg'],
 'h': ['tcholmanvissiidae',
       'tchernyshevioides',
       'tchianhoun-cossi',
       'tchatkalophantes',
       'tchorzew-kolonia',
       'tchiamba-nzassi',
       'tchimporo-yonde',
       'tchorzew-plewki',
       'tchoumi-tchoumi',
       'tchintabaraden',
       'tchatchaminade',
       'tchangmargarya',
       'tchoutchoubeni',
       'tchintoulous',
       'tchadailurus',
       'tchotchopola',
       'tchiquaqueia',
       'tchirozerine',
       'tchindjenje',
       'tchaenhotep',
       'tchin-tchin',
       'tchirkpambo',
       'tchorzewski',
       'tchati-bali',
       'tchitcherik',
       'tchividjian',
       'tchamutete',
       'tchai-ovna',
       'tchorovice',
       'tchapinius',
       'tcherepnin',
       'tchoukball',
       'tchicandou',
       'tchitchide',
       'tchorzanka',
       'tchalinga',
       'tchorzowa',
       'tchembere',
       'tchoubona',
       'tchimbele',
       'tchapossi',
       'tchitondi',
       'tchotchke',
       'tchaourou',
       'tchibanga',
       'tchitchoa',
       'tchatchou',
       'tchahagir',
       'tchiconco',
       'tchollire',
       'tchenguiz',
       'tchikita',
       'tchanaga',
       'tchindas',
       'tchonoro',
       'tchicaya',
       'tchologo',
       'tchoiria',
       'tchambao',
       'tcharmil',
       'tchadoua',
       'tchorzno',
       'tchokola',
       'tchaman',
       'tchello',
       'tchamba',
       'tchedio',
       'tcheoka',
       'tchukon',
       'tchphnx',
       'tchikpe',
       'tchagra',
       'tchetti',
       'tchaada',
       'tchake',
       'tchibo',
       'tchorz',
       'tcheco',
       'tchito',
       'tcheka',
       'tchort',
       'tchaka',
       'tchami',
       'tchp',
       'tcho',
       'tche',
       'tchs',
       'tch'],
 'i': ['tcirg1', 'tcim', 'tci'],
 'j': ['tcj'],
 'k': ['tck'],
 'l': ['tcl1b', 'tcl1a', 'tcl6', 'tclx', 'tcl'],
 'm': ['tcmtb', 'tcmc', 'tcm'],
 'n': ['tcnn', 'tcn'],
 'o': ['tcof-db', 'tcom', 'tcov', 'tcon', 'tco'],
 'p': ['tcp-illinois',
       'tcpaccess',
       'tcpcrypt',
       'tcptrace',
       'tcpkill',
       'tcpware',
       'tcpdump',
       'tcp-seq',
       'tcp10l',
       'tcp11',
       'tcpdf',
       'tcpy',
       'tcpa',
       'tcpo',
       'tcps',
       'tcp'],
 'q': ['tcq'],
 'r': ['tcrf', 'tcre', 'tcr'],
 's': ['tcs-ox2-29', 'tcs-1', 'tcsh', 'tcsd', 'tcs'],
 't': ['tctex1d4', 'tctn3', 'tcts', 'tctr', 'tct'],
 'u': ['tcusd', 'tcul', 'tcu'],
 'v': ['tcv'],
 'w': ['tcw'],
 'x': ['tcx'],
 'z': ['tczyca', 'tczew', 'tczow']}
