
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tz = {'_': ["tz'utujil", 'tz-45', 'tz-1'],
 'a': ['tzaganosuchus',
       'tzanichites',
       'tzantzismo',
       'tzaousios',
       'tzafririm',
       'tzaraath',
       'tzatziki',
       'tzahalon',
       'tzavaras',
       'tzangion',
       'tzafria',
       'tzaneen',
       'tzarfat',
       'tzahala',
       'tzachas',
       'tzanata',
       'tzalash',
       'tzadik',
       'tzacol',
       'tzahar',
       'tzaar',
       'tzant',
       'tzads',
       'tzazo',
       'tzav',
       'tza'],
 'c': ['tzc'],
 'e': ['tzelepides',
       'tzeltalia',
       'tzeanania',
       'tzernicus',
       'tzelafon',
       'tzedakah',
       "tze'elim",
       'tzeltal',
       'tzedek',
       'tzelem',
       'tzena',
       'tzero',
       'tzere'],
 'i': ['tzihuactlayahuallohuatzin',
       'tzitzipandaquare',
       'tzicatlacoyan',
       'tzintzuntzan',
       'tzilacatzin',
       "tzi-b'alam",
       'tzidkatcha',
       'tzitzimitl',
       'tzippori',
       'tzimtzum',
       'tzitzit',
       'tzitzis',
       'tzitzak',
       'tzii-wi',
       "tziv'on",
       'tzigane',
       'tzitzio',
       'tzimmes',
       'tzimol',
       'tzini'],
 'n': ['tzniut', 'tznic'],
 'o': ['tzotzil/mummers/tzotzil',
       'tzompantepec',
       'tzomborgha',
       'tzompantli',
       'tzoumerka',
       'tzolkinex',
       "tzolk'in",
       'tzouras',
       'tzotzil',
       'tzofit',
       'tzomet',
       'tzohar',
       'tzofar',
       'tzofim',
       'tzova',
       'tzora'],
 'r': ['tzrifin', 'tzrufa'],
 's': ['tzsp'],
 'u': ['tzurangkong',
       'tzummarum',
       'tzucacab',
       'tzuriel',
       'tzurit',
       'tzukim',
       'tzuke',
       'tzuki',
       'tzuyu',
       'tzum',
       'tzur',
       'tzu'],
 'v': ['tzvelevopyrethrum', 'tzveleviochloa'],
 'y': ['tzykanisterion']}
