
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oy = {'_': ['oy-mittelberg', 'oy-pozhum', 'oy-blikk', 'oy-tal'],
 'a': ['oyasato-yakata',
       'oyafestivalen',
       'oyak-renault',
       'oyangsvatnet',
       'oyayubihime',
       'oyano-jima',
       'oyarvatnet',
       'oyamatsumi',
       'oyarzabal',
       'oyatenna',
       'oyaku-en',
       'oyangudi',
       'oyamacho',
       'oyakjung',
       'oyakodon',
       'oyamada',
       'oyapock',
       'oyanagi',
       'oyarifa',
       'oyangen',
       'oyanish',
       'oyashio',
       'oyavis',
       'oya-ji',
       'oyapoc',
       'oyagen',
       'oyabun',
       'oyasaf',
       'oyaki',
       'oyama',
       'oyali',
       'oyato',
       'oyaca',
       'oyace',
       'oyamo',
       'oyane',
       'oyam',
       'oyak',
       'oyat',
       'oya'],
 'b': ['oybont', 'oybach', 'oybike', 'oybin'],
 'd': ['oydebreen', 'oyda', 'oyd'],
 'e': ['oye-et-pallet',
       'oyenkilen',
       'oye-plage',
       'oyebanjo',
       'oyetunde',
       'oyevitne',
       'oyewole',
       'oyedaea',
       'oyedepo',
       'oyestad',
       'oyeyemi',
       'oyenuga',
       'oyekan',
       'oyeren',
       'oyede',
       'oyene',
       'oyer',
       'oyeu',
       'oyez',
       'oyee',
       'oyem',
       'oyes',
       'oyen',
       'oye'],
 'f': ['oyfjell'],
 'g': ['oyggjatidindi', 'oygarden', 'oygard'],
 'i': ['oyin-akoko',
       'oyilattam',
       'oyiradai',
       'oyigbo',
       'oyinbo',
       'oyinda',
       'oyin',
       'oyim',
       'oyi'],
 'l': ['oyl@qulu', 'oylegate', 'oyler', 'oylum', 'oyl'],
 'm': ['oymarksjoen',
       'oymurania',
       'oymyakon',
       'oymaagac',
       'oymakli',
       'oymark',
       'oymur',
       'oyme'],
 'n': ['oyndarfjordur', 'oyne', 'oyna'],
 'o': ['oyorokoto',
       'oyon-oion',
       'oyotunji',
       'oyotung',
       'oyonnax',
       'oyoor',
       'oyodo',
       'oyoko',
       'oyola',
       'oyor',
       'oyon',
       'oyo'],
 'p': ['oyposten', 'oypa'],
 'r': ['oyrlandsodden',
       'oyrareingir',
       'oyrarbakki',
       'oyrlandet',
       'oyrieres',
       'oyrane',
       'oyr@t',
       'oyre',
       'oyri'],
 's': ['oystercatcher',
       'oystermouth',
       'oysterhaven',
       'oystershell',
       'oysterband',
       'oysonville',
       'oysterhead',
       'oystering',
       'oyskhara',
       'oysletta',
       'oystron',
       'oystein',
       'oystese',
       'oyslebo',
       'oyshee',
       'oysand',
       'oyston',
       'oystor',
       'oyster',
       'oysho'],
 't': ['oytier-saint-oblas', 'oytograk', 'oytak', 'oyten'],
 'u': ['oyun-unguokhtakh',
       'oyusardakh',
       'oyungezer',
       'oyungen',
       'oyuktas',
       'oyusut',
       'oyugis',
       'oyunaa',
       'oyubia',
       'oyuklu',
       'oyumi',
       'oyun'],
 'v': ['oyvatnet', 'oyvind']}
