
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oi = {'_': ['oi-juku', 'oi-zuki', 'oi!'],
 'a': ['oiartzualdea', 'oiartzun', 'oiapoque', "oia'i'o", 'oiasso', 'oia'],
 'b': ['oiba', 'oib'],
 'c': ['oiceoptoma',
       'oicho-kabu',
       'oichalia',
       'oiceaca',
       'oicles',
       'oicets',
       'oicata',
       'oicha',
       'oichi',
       'oici',
       'oicc'],
 'd': ['oidaematophorus',
       'oidanothrips',
       'oidemastis',
       'oidematops',
       'oidentd',
       'oidrema',
       'oidium',
       'oidor',
       'oides',
       'oido',
       'oids',
       'oid'],
 'e': ['oieren', 'oier'],
 'f': ['oif'],
 'g': ['oigny-en-valois', 'oignies', 'oigney', 'oigny', 'oiga'],
 'h': ['oihane'],
 'i': ['oii-chinese', 'oiii', 'oii'],
 'j': ['oijarvi'],
 'k': ['oikonomopoulos',
       'oikopleuridae',
       'oikobesalon',
       'oikocredit',
       'oikopleura',
       'oikophobia',
       'oiketerion',
       'oikarinen',
       'oikonomos',
       'oikeiosis',
       'oikonomou',
       'oiketicus',
       'oikistes',
       'oikeios',
       'oikango',
       'oikawa',
       'oikos',
       'oike'],
 'l': ['oilogosphere',
       'oillipheist',
       'oilinyphia',
       'oiltanking',
       'oilcloth',
       'oilstone',
       'oileides',
       'oilville',
       'oilgate',
       'oilexco',
       'oilbird',
       'oilgear',
       'oilfish',
       'oilskin',
       'oilibya',
       'oiling',
       'oilite',
       'oilton',
       'oileus',
       'oilea',
       'oille',
       'oiler',
       'oil!',
       'oil'],
 'm': ['oimachi', 'oimbra', 'oimb', 'oim'],
 'n': ['oinville-saint-liphard',
       'oinville-sur-montcient',
       'oinville-sous-auneau',
       'oinountas',
       'oinousses',
       'oinophila',
       'oinomancy',
       'oinochori',
       'oinoussa',
       'oinofyta',
       'oiniades',
       'oin-oin',
       'oinonen',
       'oinacu',
       'oinafa',
       'oinam',
       'oinia',
       'oingt',
       'oinoi',
       'oinas',
       'oina',
       'oine',
       'oink',
       'oin'],
 'o': ['oiophassus', 'oiorhinus', 'oioceros', 'oiozona', 'oioxml', 'oio'],
 'p': ['oipc', 'oip'],
 'r': ['oireachtas',
       'oireabhal',
       'oirschot',
       'oiretumu',
       'oirsbeek',
       'oirats',
       'oirase',
       'oiron',
       'oiran',
       'oiryo',
       'oirat',
       'oira',
       'oiry',
       'oir'],
 's': ['oiselay-et-grachaux',
       'oisseau-le-petit',
       'oisy-le-verger',
       'oisterwijk',
       'oiso-juku',
       'oistrakh',
       'oisemont',
       'oishinbo',
       'oisteanu',
       'oissaare',
       'oissery',
       'oistins',
       'oisseau',
       'oiseaux',
       'oisilly',
       'oishida',
       'oissel',
       'oisans',
       'oismae',
       'oiseau',
       'oisang',
       'oiseth',
       'oistat',
       'oisly',
       'oishi',
       'oison',
       'oisin',
       'oissy',
       'oism',
       'oiso',
       'oist',
       'oise',
       'oisu',
       'oisy',
       'oisc',
       'oisd',
       'ois'],
 't': ['oiticicastnia',
       'oithonidae',
       'oiticella',
       'oiticica',
       'oithona',
       'oitylo',
       'oittaa',
       'oitbi',
       'oitti',
       'oituz',
       'oitme',
       'oitc',
       'oita',
       'oitz',
       'oit'],
 'u': ['oium', 'oiu'],
 'v': ['oivind', 'oiv'],
 'w': ['oiwake-shuku'],
 'x': ['oix'],
 'y': ['oiyl'],
 'z': ['oizumigakuencho',
       'oizumimachi',
       'oizumi',
       'oizon',
       'oizys',
       'oize',
       'oiz']}
