
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ow = {'a': ['owalapolwatta',
       'owambarctia',
       'owariasahi',
       'owadaglaea',
       'owakudani',
       'owairaka',
       'owatonna',
       'owadowia',
       'owaissa',
       'owariya',
       'owariki',
       'owalini',
       'owaraha',
       'owanto',
       'owanka',
       'owando',
       'owarai',
       'owadow',
       'oware',
       'owana',
       'owasp',
       'owala',
       'owaka',
       'owari',
       'owata',
       'owada',
       'owase',
       'owain',
       'owali',
       'owan',
       'owa'],
 'b': ['owbasic', 'owbon', 'owb'],
 'c': ['owczeglowy',
       'owczarnia',
       'owchtash',
       'owchunak',
       'owczarki',
       'owchghaz',
       'owczary',
       'owchan',
       'owc'],
 'd': ['owdeh', 'owdui', 'owdlu'],
 'e': ['oweniasuchus',
       'owengallees',
       'owenahincha',
       'owenettidae',
       'owensmouth',
       'owensville',
       'owermoigne',
       'oweishiyeh',
       'oweniidae',
       'owerrinta',
       'owenstown',
       'owensite',
       'owenetta',
       'oweekeno',
       'owenodon',
       'owersby',
       'owenton',
       'owenism',
       'owencam',
       'owenbeg',
       'owenus',
       'owenia',
       'owendo',
       'owenga',
       "owen's",
       'oweina',
       'owerri',
       'owelu',
       'owela',
       'owens',
       'owego',
       'owers',
       'owen',
       'ower',
       'owez',
       'owel',
       'owe'],
 'f': ['owf'],
 'g': ['owghlan', 'owghan', 'owghal', 'owghaz', 'owg'],
 'h': ['owhelogbo', 'owhango', 'owhrode', 'owhkan', 'owhiro', 'owhata'],
 'i': ['owitigamuwa',
       'owilikanda',
       'owilfordia',
       'owidz-mlyn',
       'owitipana',
       'owieczki',
       'owieczka',
       'owington',
       'owilana',
       'owinska',
       'owiesno',
       'owingen',
       'owilla',
       'owings',
       'owino',
       'owiti',
       'owidz',
       'owink',
       'owisa',
       'owir',
       'owia',
       'owi'],
 'j': ['owjabandan',
       'owjiabad',
       'owjan',
       'owjad',
       'owjur',
       'owjak',
       'owjc',
       'owj'],
 'k': ['owkhchilar', 'owkhsar', 'owkreka', 'owkhchi', 'owksar', 'owkin', 'owk'],
 'l': ['owlet-nightjar',
       'owlknight',
       'owlsmoor',
       'owlaghan',
       'owlamchi',
       'owlcrate',
       'owlswick',
       'owlerton',
       'owlbear',
       'owletts',
       'owlman',
       'owltan',
       'owlboy',
       'owliai',
       'owlang',
       'owlpen',
       'owling',
       'owlett',
       'owl/tv',
       'owlfly',
       'owl-s',
       'owlet',
       'owlar',
       'owlom',
       'owlia',
       'owler',
       'owlya',
       'owles',
       'owlaq',
       'owlad',
       'owls',
       'owly',
       'owl2',
       'owli',
       'owl'],
 'm': ['owmby-by-spital', 'owmandan', 'owmal', 'owmby', 'owm'],
 'n': ['owner-occupancy',
       'owner-operator',
       'ownership',
       'owncloud',
       'ownlocal',
       'owneriq',
       'ownham',
       'ownice',
       'ownia',
       'owney',
       'ownby',
       'own'],
 'o': ['oworonshoki',
       'owodokpokpo',
       'owolabi',
       'owodog',
       'owosso',
       'owong',
       'owono',
       'owoh',
       'owor',
       'owox',
       'owo'],
 'p': ['owp'],
 'r': ['owrganjeh',
       'owranjaq',
       'owrachi',
       'owrtasu',
       'owriyeh',
       'owrazan',
       'owrang',
       'owryad',
       'owraki',
       'owrjak',
       'owranj',
       'owrai',
       'owrma',
       'owraq',
       'owren',
       'owrim',
       'owr'],
 's': ['owshtanian',
       'owslebury',
       'owsthorpe',
       'owsiszcze',
       'owsniczka',
       'owshendel',
       'owstonia',
       'owshiyan',
       'owstwick',
       'owsianka',
       'owschlag',
       'owsaluy',
       'owsnice',
       'owston',
       'owsley',
       'owsla',
       'owsa',
       'ows'],
 't': ['owthorne', 'owthorpe', 'owtanlu', 'owtrang', 'owtar', 'owtan'],
 'u': ['owusu-ankomah', 'owusu', 'owuo'],
 'w': ['owwa', 'oww'],
 'y': ['owyhee'],
 'z': ['owzarlu', 'owzkola', 'owzthat', 'owzaj', 'owzat']}
