
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oo = {'_': ['oo-topos', 'oo9'],
 'a': ['ooaworld', 'ooak', 'ooa'],
 'b': ['ooberman',
       'oobleck',
       'ooblets',
       'oobunus',
       'oobius',
       'oobe',
       'oobi',
       'oob'],
 'c': ['oochoristica',
       'oocystaceae',
       'oocatochus',
       'oocelyphus',
       'oocephalus',
       'oocephala',
       'oocarpais',
       'oocystis',
       'oochiton',
       'oocerina',
       'ooceraea',
       'oocorys',
       'oochya!',
       'oocyte',
       'oocss',
       'oocre',
       'oocl',
       'oocr',
       'ooc'],
 'd': ['oodinotrechus',
       'oodaigahara',
       'oodnadatta',
       'oodinkosa',
       'oodinium',
       'oodectes',
       'oodweyne',
       'oodiscus',
       'oodians',
       'oodinus',
       'oodaaq',
       'oodini',
       'oodes',
       'oodi',
       'ood'],
 'e': ['ooencyrtus', 'ooedigera', 'ooe'],
 'f': ['oofotr', 'oofem', 'oofie', 'oof'],
 'g': ['oogamochlamys',
       'oogon-talaa',
       'oogarding',
       'oogenesis',
       'oogonium',
       'oogaboo',
       'ooglies',
       'oogave',
       'oogamy',
       'oog'],
 'h': ['ooh-wakka-doo-wakka-day',
       'oohakachavadam',
       'oohkotokia',
       'ooh!media',
       'oohdm',
       'oohyo',
       'ooha',
       'ooho',
       'ooh!',
       'ooh'],
 'i': ['ooievaarsnest', 'ooidius', 'ooioo', 'ooij', 'ooia', 'ooid', 'ooi'],
 'j': ['oojah'],
 'k': ['ookteechenskaia', 'ookatku', 'ookpik', 'ookay', 'ooku', 'ooka', 'ook'],
 'l': ['ooltgensplaat',
       'oolampara',
       'oolithes',
       'oolooloo',
       'oolkatal',
       'oolitic',
       'oolong',
       'oolite',
       'oology',
       'oolu',
       'oola',
       'ool'],
 'm': ['oomorphidius',
       'oom-pah-pah',
       'oomaithurai',
       'oomasicera',
       'oomakkuyil',
       'oomorphus',
       'oomerabad',
       'oomalama',
       'oomycete',
       'oom-pah',
       'oomyces',
       'oomiste',
       'oomyzus',
       'oomancy',
       'oomine',
       'oomph!',
       'oommen',
       'oomsis',
       'oomoto',
       'oompas',
       'oomen',
       'oomba',
       'ooma',
       'oomk',
       'ooms',
       'oom'],
 'n': ['oontomyces',
       'oonopoides',
       'oonopinus',
       'oonopidae',
       'oonoceras',
       'oonooraba',
       'oonopsis',
       'oonjaal',
       'oonurme',
       'oondees',
       'oonops',
       'oonjal',
       'oonga',
       'ooni',
       'oona',
       'oon'],
 'o': ['ooooooweeee!!!', 'ooouuu', 'ooops!', 'oooh.', 'ooooo', 'ooo'],
 'p': ['ooperipatellus',
       'oopdeewopdee',
       'oophorectomy',
       'oop-pop-a-da',
       'ooperipatus',
       'oopterinus',
       'oopeltidae',
       'oophoritis',
       'oops-leon',
       'oophorini',
       'oopsidius',
       'oophytum',
       'oopterus',
       'oophagy',
       'oophana',
       'oophaga',
       'oopstad',
       'oopsla',
       'oophaa',
       'oopsis',
       'oopali',
       'oophoi',
       'oopiri',
       'oopic',
       'oops',
       'oop'],
 'r': ['oormelalagiyan',
       'ooruttambalam',
       'oorkavalan',
       'oorpally',
       'oorakkad',
       'oorderen',
       'oortiana',
       'ooredoo',
       'oorakam',
       'oorvani',
       'oorahu',
       'ooriku',
       'oorgu',
       'oorah',
       'oora',
       'oore',
       'oor'],
 's': ['oost-watergraafsmeer',
       'oosterscheldekering',
       'oostvaardersplassen',
       'oostenburgervaart',
       'oosterdokseiland',
       'oost-barendrecht',
       'oosterenkstadion',
       'ooststellingwerf',
       'oosterzee-buren',
       'oost-graftdijk',
       'oosterhesselen',
       'oosterboschite',
       'oostnieuwkerke',
       'oostknollendam',
       'oosternieland',
       'oosterwijzend',
       'oost-vlieland',
       'oostzanerwerf',
       'oosterellidae',
       'oosternijkerk',
       'oostduinkerke',
       'oost-maarland',
       'oosterbierum',
       'oost-souburg',
       'oostrozebeke',
       'oosterstreek',
       'oosterbroek',
       'oostkapelle',
       'oost-cappel',
       'oostershuis',
       'oostflakkee',
       'oosaravelli',
       'oosterwolde',
       'oosterflank',
       'oostvoorne',
       'oosterdijk',
       'oosterland',
       'oosterkerk',
       'oosterella',
       'oosterhout',
       'oosterbeek',
       'oosterweel',
       'oosterleek',
       'oosterzele',
       'oosterhuis',
       'oosthuizen',
       'oosterpark',
       'oosterhoff',
       'oosterheem',
       'oostmahorn',
       'oostpoort',
       'oosterzee',
       'oosporein',
       'oostbuurt',
       'oostegite',
       'oost-azie',
       'oostakker',
       'oosterdok',
       'oosterend',
       'oosteeklo',
       'oostkerke',
       'oostendam',
       'oosternum',
       'oostoever',
       'oostmalle',
       'oostende',
       'oostdijk',
       'ooslamaa',
       'oostkamp',
       'oostzaan',
       'oostwoud',
       'oostwold',
       'oostburg',
       'oosomini',
       'oostpunt',
       'oospore',
       'oosting',
       'oosseld',
       'oosthem',
       'oospira',
       'oostrum',
       'oospila',
       'oosaar',
       'oosoma',
       'oostum',
       'oost',
       'oosa',
       'ooso',
       'oos'],
 't': ['oottyppattanam',
       'ootischenia',
       'ootmarsum',
       'oothukadu',
       'ootpally',
       'ootheca',
       'oottara',
       'ootypus',
       'ootla',
       'ootha',
       'ootp',
       'oots',
       'ootg',
       'ootw',
       'ooty',
       'ootb'],
 'v': ['oovoo', 'oov'],
 'w': ['oowatanite', 'oowekyala', 'oow'],
 'y': ['ooyala'],
 'z': ['oozlefinch',
       'oozinator',
       'oozeball',
       'oozo.tv',
       'oozham',
       'ooze',
       'ooz']}
