
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_of = {'_': ['of-40'],
 'a': ['ofab-100-120',
       'ofaerufoss',
       'ofahengaue',
       'ofatumumab',
       'ofatulena',
       'ofatinti',
       'ofaiston',
       'ofagbe',
       'ofarim',
       'ofanto',
       'ofakim',
       'ofalu',
       'ofafa',
       'ofaye',
       'ofah',
       'ofa'],
 'b': ['ofb-frauenliga', 'ofb'],
 'c': ['ofcolaco', 'ofcom', 'ofc'],
 'd': ['ofd1', 'ofd'],
 'e': ['ofenhorn',
       'ofeherto',
       'ofermod',
       'ofeq-10',
       'ofek-16',
       'ofeq-7',
       'ofeq-9',
       'ofena',
       'ofer',
       'ofeq',
       'ofei',
       'ofe'],
 'f': ['offiziersstellvertreter',
       'offenbach-lauterborn',
       'offenbach-rosenhohe',
       'offenbach-hundheim',
       'off-balance-sheet',
       'off-off-broadway',
       'offenbach-bieber',
       'offroadfinnmark',
       'off-the-shelf',
       'office-holder',
       'offachloritis',
       'offnungsrecht',
       'off-the-grid',
       'off-broadway',
       'offertorium',
       'officesuite',
       'off-flavour',
       'offranville',
       'officeworks',
       'off-roading',
       'offroicourt',
       'off-rolling',
       'officinalis',
       'offenbuttel',
       'officearrow',
       'offenhausen',
       'officialese',
       'off-balance',
       'offsideopen',
       'offlineimap',
       'offenhauser',
       'offingawier',
       'offroad.tv',
       'off-kilter',
       'off-modern',
       'offshoring',
       'off-centre',
       'officegate',
       'offekerque',
       'offers.com',
       'offsetters',
       'offscreen',
       'offchurch',
       'offersoya',
       'offenberg',
       'offenders',
       'offertory',
       'offwiller',
       'officemax',
       'offsiders',
       'off-price',
       'offerings',
       'offenbeek',
       'officiant',
       'offleyhay',
       'offensive',
       'offsystem',
       'offrejoie',
       'offington',
       'offanengo',
       'offenheim',
       'officetel',
       'offspring',
       'offignies',
       'offlinetv',
       'off-model',
       'offenbach',
       'offendorf',
       'officinal',
       'offlanges',
       'offrethun',
       'offacolus',
       'offenburg',
       'officium',
       'offstein',
       'offering',
       'off-beat',
       'offerdal',
       'offleben',
       'offsetof',
       'offbeatr',
       'offoumpo',
       'offerman',
       'off-site',
       'offemont',
       'offprint',
       'offenham',
       'offshore',
       'offingen',
       'offcutts',
       'offensee',
       'offshoot',
       'offerton',
       'offworld',
       'official',
       'off-ramp',
       'offsider',
       'offredi',
       'offenau',
       'off-key',
       'offwell',
       'offlaga',
       'offside',
       'off-gas',
       'offrami',
       'offense',
       'offinso',
       'offagna',
       'officer',
       'offerup',
       'offgrid',
       'offbeat',
       'offuman',
       'offcell',
       'offutt',
       'offset',
       'offlow',
       'offord',
       'offers',
       'offton',
       'offham',
       'offley',
       'offner',
       'offred',
       'offida',
       'offcut',
       'office',
       'offal',
       'offer',
       'offoy',
       'offei',
       'offis',
       'offie',
       'offin',
       'offit',
       'offon',
       'offen',
       'off!',
       'offo',
       'off'],
 'g': ['ofg'],
 'i': ['oficanthon', 'oficjalow', 'ofinran', 'ofira', 'ofili', 'ofir', 'ofi'],
 'j': ['ofjord'],
 'l': ['ofloxacin', 'oflag', 'ofla', 'ofl'],
 'm': ['ofml', 'ofm'],
 'n': ['ofnerspitze', 'ofnidan', 'ofnir', 'ofner'],
 'o': ['ofoase-kokoben',
       'ofori-atta',
       'ofotfjord',
       'ofolanga',
       'ofoldeak',
       'ofoedu',
       'oforia',
       'ofoase',
       'ofoten',
       'ofosu',
       'ofono',
       'ofori',
       'ofo'],
 'p': ['ofp'],
 'q': ['ofqual'],
 'r': ['ofrynio', 'ofrenda', 'ofrekpe', 'ofriyo', 'ofra', 'ofro'],
 's': ['ofsted', 'ofspor', 'ofstad', 'ofs'],
 't': ['oftershausen',
       'ofterschwang',
       'ofterdingen',
       'oftersheim',
       'oftringen',
       'oftobruy',
       'oftering',
       'oftedal',
       'oftfor',
       'often',
       'oftia',
       'oftel',
       'oftp',
       'ofta',
       'oft'],
 'u': ['ofu-olosega',
       'ofudesaki',
       'ofushino',
       'ofunato',
       'ofunam',
       'ofuna',
       'ofuda',
       'ofu'],
 'v': ['ofvandahls', 'ofv'],
 'w': ['ofwat', 'ofw'],
 'x': ['ofx'],
 'z': ['ofz']}
