
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_o_ = {'_': ['o6-benzylguanine',
       'o*-algebra',
       'o-1269',
       'o-1602',
       'o-2545',
       'o-1918',
       'o-1812',
       'o-4210',
       'o-2172',
       'o-2390',
       'o-2113',
       'o-1871',
       'o-2372',
       'o-4310',
       'o-1125',
       'o-1238',
       'o-2050',
       'o-2694',
       'o-1057',
       'o-823',
       'o-806',
       'o-774',
       'o-18',
       'o39',
       'o07',
       'o2+',
       'o26',
       'o15',
       'o10',
       'o23',
       'o20',
       'o16',
       'o17',
       'o19',
       'o25',
       'o11',
       'o12',
       'o21',
       'o13',
       'o14',
       'o24',
       'o22'],
 'a': ['o-acylpseudotropine',
       'o-acetylbufotenine',
       'o-acetylpsilocin',
       'o-acetylserine',
       'o-automaton',
       'o-anisidine',
       'o.a.r.',
       'o-aew',
       'o&a'],
 'b': ["o'briensbridge-montpelier",
       "o'banion's",
       "o'brother",
       "o'banion",
       "o'bannon",
       "o'boylan",
       "o'beirne",
       'o.b.i.t.',
       "o'bryant",
       "o'byrne",
       "o'brien",
       "o'boyle",
       "o'bryan",
       "o'brian",
       'o-blek',
       'o2be',
       'o3b'],
 'c': ["o'connor-parkview",
       'o-cresolphthalein',
       "o'comhaltain",
       "o'charley's",
       "o'callaghan",
       "o'carroll",
       "o'collins",
       "o'connell",
       "o'conner",
       "o'cawley",
       'o-cresol',
       'o-cymene',
       "o'connor",
       "o'casey",
       "o'clery",
       'o-cedar',
       "o'conor",
       "o'ceann",
       "o'cahan",
       'o.co'],
 'd': ['o-desmethylangolensin',
       'o-dianisidine',
       "o'donoghue",
       'o-de-selle',
       "o'donohue",
       "o'doherty",
       "o'davoren",
       "o'dwyer",
       "o'death",
       "o'duffy",
       "o'dowd",
       "o'dell",
       'o.d.t.',
       'o-dog',
       "o'dea",
       "o'day",
       'o3d'],
 'f': ["o'flanagan",
       'o-faergen',
       "o'farrell",
       "o'ferrall",
       "o'farrill",
       'o.f.t.b.',
       "o'fallon",
       "o'friel"],
 'g': ["o'gorman",
       'o-glcnac',
       "o'grady",
       'o-grade',
       "o'galop",
       "o'garro",
       "o'g3ne",
       'o&g',
       'o1g'],
 'h': ["o'halloran",
       "o'higgins",
       "o'herlihy",
       "o'heerin",
       "o'hanlon",
       "o'hurley",
       'o.h.m.s.',
       "o'haran",
       "o'hearn",
       "o'hagan",
       "o'hara",
       "o'hair",
       'o-hook',
       'o-hum',
       "o'hea"],
 'j': ['o-jolle', 'o-j-i'],
 'k': ["o'kearney", "o'kennedy", "o'keeffe", "o'keefe", "o'kelly", "o'kane"],
 'l': ["o'leary-inverness",
       "o'laughlin",
       "o'loughlin",
       "o'lawlor",
       "o'learys",
       "o'leary",
       'o-logic',
       "o'lord",
       "o'loan",
       'o-lan'],
 'm': ['o-methyltransferase',
       'o-mustard',
       "o'mahony",
       "o'malley",
       'o-mikuji',
       'o-matrix',
       "o'mullod",
       "o'mega",
       'o&m'],
 'n': ['o-nitroanisole',
       'o.n.i.f.c.',
       "o'neills",
       'o`nhayot',
       "o'neil's",
       "o'neale",
       'o.n.a.'],
 'o': ['o/oreos', "o'odham", "o'o"],
 'p': ['o-phenyl-3-iodotyramine',
       'o-phenylenediamine',
       'o-pee-chee',
       "o'plerou"],
 'q': ["o'quinn"],
 'r': ["o'rahilly",
       'o`rtaovul',
       'o!rul8,2?',
       "o'riordan",
       'o-ringen',
       "o'rourke",
       "o'reilly",
       "o'regan",
       "o'rorke",
       'o-ring',
       "o'rawe",
       "o'rear",
       "o'ree"],
 's': ['o-sec-butylphenol',
       'o-saw-wah-pon',
       "o'shaughnessy",
       "o'sullivan",
       "o'sheehan",
       'o.s.c.l.',
       'o3spaces',
       'o.s.c.a.',
       'o.s.t.r.',
       "o'shane",
       "o'shea",
       'o-shen',
       'o`smat',
       'o-six'],
 't': ['o-tolylthiourea',
       'o-toluidine',
       'o.torvald',
       "o'tacos",
       'o-train',
       "o'toole",
       'o-town',
       'o.t.t.',
       'o-type',
       'o-tao',
       'o2tv'],
 'v': ['o.v.peta', 'o2v'],
 'w': ['o-we-go', 'o.w.l.', 'o&w'],
 'x': ['o-xylene', 'o:xml'],
 'y': ['o-yoroi'],
 'z': ["o'zelectroapparat-electroshield", 'o-zone']}
