
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tx = {'_': ['tx_camelopardalis',
       'tx-3000_series',
       'tx-1000_series',
       'tx-2000_series',
       'tx_network',
       'tx_piscium',
       'tx1_radio',
       'tx_group'],
 'a': ['txabi_etxebarrieta'],
 'c': ['txc_uav'],
 'e': ['txema_anibarro',
       'txemi_urtasun',
       'txema_noriega',
       'txema_salvans',
       'txema_alonso',
       'txema_garcia',
       'txetxu_rojo',
       'txe_arana'],
 'f': ['txfm', 'txf'],
 'g': ['txga'],
 'i': ['txiki_begiristain', 'txik_txak'],
 'k': ['txk'],
 'l': ['txlnb', 'txl'],
 'n': ['txndc12',
       'txndc5',
       'txnl4a',
       'txndc9',
       'txnl4b',
       'txndc2',
       'txnrd1',
       'txnl1',
       'txnip',
       'txn2',
       'txn'],
 'o': ['txomin_juaristi', 'txomin_nagore'],
 's': ['txs_0506+056'],
 't': ['txt_e-solutions', 'txt_record'],
 'u': ['txus_vidorreta', 'txus_serrano', 'txu_energy']}
