
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tk = {'_': ['tk_madhavan',
       'tk_records',
       'tk_company',
       'tk_telekom',
       'tk_samuels',
       "tk_o'ryan",
       'tk_mckamy',
       'tk_brovig',
       'tk_howden',
       'tk_solver',
       'tk_borac',
       'tk_maxx'],
 'a': ['tkalciceva_street',
       'tka_discography',
       'tkaczewska_gora',
       'tkalec_manor',
       'tkay_maidza'],
 'b': ['tkb-022pm',
       'tkb-0146',
       'tkb-506',
       'tkb-408',
       'tkb-011',
       'tkb-072',
       'tkb-010',
       'tkb-059',
       'tkb-517',
       'tkb'],
 'c': ['tkc'],
 'd': ['tkdiff', 'tkdesk'],
 'e': ['tkey_record'],
 'f': ['tkf'],
 'g': ['tkg'],
 'h': ['tkhaba-yerdy_church', 'tkh_torun'],
 'i': ['tkibuli_municipality'],
 'k': ['tkk_tallinn'],
 'l': ['tklania', 'tklapi', 'tkl'],
 'm': ['tkm-ebola', 'tkm'],
 'n': ['tkn_f.c.'],
 'o': ['tko_software', 'tko_records', 'tko_studios'],
 'p': ['tkp'],
 'r': ['tkrzw', 'tkr'],
 's': ['tks_finance', 'tks_49ers', 'tks_torun'],
 't': ['tkt_tampere'],
 'u': ['tkuma,_israel'],
 'v': ['tkvarcheli_district'],
 'w': ['tkwww', 'tkw'],
 'z': ['tkzee', 'tkz']}
