
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dn = {'_': ['dn_postcode_area', 'dn_tower_21'],
 'a': ['dna-3-methyladenine_glycosylase_ii',
       'dna/rna_non-specific_endonuclease',
       'dna-3-methyladenine_glycosylase_i',
       'dna-templated_organic_synthesis',
       'dna-functionalized_quantum_dots',
       'dna_repair-deficiency_disorder',
       'dna-directed_rna_interference',
       'dna-encoded_chemical_library',
       'dna_field-effect_transistor',
       'dna_damage-binding_protein',
       'dna_oxidative_demethylase',
       'dnase_footprinting_assay',
       'dna_nanoball_sequencing',
       'dna_polymerase_epsilon',
       'dna_replication_stress',
       'dna_sequencing_theory',
       'dnata_travel_services',
       'dna_paternity_testing',
       'dna_unwinding_element',
       'dna_adenine_methylase',
       'dna_polymerase_lambda',
       'dna_polymerase_alpha',
       'dna_polymerase_delta',
       'dna_plant_technology',
       'dna_mismatch_repair',
       'dna_polymerase_beta',
       'dna_family_secrets',
       'dna_polymerase_eta',
       'dna_polymerase_iv',
       'dna_polymerase_mu',
       'dna_polymerase_nu',
       'dna_for_beginners',
       'dna_base_flipping',
       'dna_polymerase_ii',
       'dna_end_resection',
       'dna_polymerase_v',
       'dna_binding_site',
       'dna_polymerase_i',
       'dna_pro_cycling',
       'dna_read_errors',
       'dna_doe_project',
       'dna_world_tour',
       'dna_show_vol.1',
       'dna_on_dna',
       'dna_/_doa'],
 'e': ['dneprovka,_bryansk_oblast',
       'dnevnik_hiacinte_novak',
       'dnevnik_jedne_ljubavi',
       'dnevnik_starog_momka',
       'dneper_common_shrew'],
 'i': ['dniprovsko-orilskyi_nature_reserve',
       'dniprelstan,_zaporizhzhia_raion',
       'dniester_hydroelectric_station',
       'dnieper_hydroelectric_station',
       'dnieper_metallurgical_combine',
       'dnipropetrovsk_oblast_council',
       'dnipro_international_airport',
       'dniprovskyi_district,_kyiv',
       'dnipro_railway_station',
       'dniester_news_agency',
       'dnieper_river_line'],
 's': ['dns_management_software',
       'dns_long-lived_queries',
       'dns_hosting_service',
       'dns_zone_transfer',
       'dns_over_https',
       'dns_root_zone',
       'dns_over_tls'],
 'v': ['dnv_fuel_fighter'],
 'y': ["dnyanprassarak_mandal's_college", 'dnyanmata_vidyalaya,_sangamner']}
