
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sb = {'_': ['sb-277,011-a',
       'sb-649,915',
       'sb-612,111',
       'sb-258585',
       'sb-431542',
       'sb-408124',
       'sb-258719',
       'sb-200646',
       'sb-366791',
       'sb-269970',
       'sb-228357',
       'sb-649868',
       'sb-399885',
       'sb-204741',
       'sb-243213',
       'sb-334867',
       'sb-204070',
       'sb-699551',
       'sb-205384',
       'sb-271046',
       'sb-216641',
       'sb-215505',
       'sb-236057',
       'sb-242084',
       'sb-705498',
       'sb-206553',
       'sb-357134',
       'sb1394',
       'sb-pro',
       'sb.tv',
       'sb19',
       'sb20',
       'sb1',
       'sb2'],
 'a': ['sbarcioara',
       'sbardella',
       'sbarbaro',
       'sbardun',
       'sbanken',
       'sbarro',
       'sbata',
       'sbant',
       'sbase',
       'sbach',
       'sbaa',
       'sbar',
       'sbai',
       'sbap',
       'sbac',
       'sba'],
 'b': ['sbb'],
 'c': ['sbca', 'sbcs', 'sbct', 'sbcc', 'sbc'],
 'd': ['sbds', 'sbd'],
 'e': ['sberkassa',
       'sberbank',
       'sbectel',
       'sbeitla',
       'sberna',
       'sbenu',
       'sber',
       'sbe'],
 'f': ['sbfc', 'sbf2', 'sbf1', 'sbf'],
 'g': ['sbgs', 'sbg'],
 'h': ['sbhc', 'sbhs', 'sbh'],
 'i': ['sbitenshchik',
       'sbirri',
       'sbikha',
       'sbiten',
       'sbinet',
       'sbiba',
       'sbida',
       'sbia',
       'sbid',
       'sbig',
       'sbic',
       'sbi'],
 'j': ['sbjd', 'sbj'],
 'k': ['sbk3', 'sbk'],
 'l': ['sbl'],
 'm': ['sbmt', 'sbma', 'sbml', 'sbmc', 'sbm'],
 'n': ['sbno2', 'sbn'],
 'o': ['sbordoniella',
       'sboyevskaya',
       'sborgite',
       'sborino',
       'sbobet',
       'sbouya',
       'sborz',
       'sbor',
       'sbo'],
 'p': ['sbp-tag', 'sbps', 'sbpl', 'sbp'],
 'q': ['sbq'],
 'r': ['sbracciantizzazione',
       'sbrodovo',
       'sbragia',
       'sbrinz',
       'sbrna',
       'sbrk',
       'sbri',
       'sbr'],
 's': ['sbs9',
       'sbso',
       'sbsp',
       'sbse',
       'sbsd',
       'sbst',
       'sbsa',
       'sbsi',
       'sbs6',
       'sbs'],
 't': ['sbtrkt', 'sbtk', 'sbtc', 'sbt'],
 'u': ['sburatorul', 'sbuv/2', 'sbuks', 'sbus', 'sbu'],
 'v': ['sbv'],
 'w': ['sbwr', 'sbw'],
 'x': ['sbx'],
 'y': ['sby']}
