
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uz = {'a': ['uzay-le-venon',
       'uzarzewo-huby',
       'uzair-ul-haq',
       'uzankuri',
       'uzarzewo',
       'uzarici',
       'uzakia',
       'uzana',
       'uzava',
       'uzazi',
       'uzari',
       'uzair',
       'uzalo',
       'uzak',
       'uzan',
       'uzal',
       'uzai',
       'uzay',
       'uza'],
 'b': ['uzboi-landon-morava',
       'uzbekneftegaz',
       'uzbekisation',
       'uzbekbaatar',
       'uzbekcosmos',
       'uzbekistan',
       'uzbyakovo',
       'uzbekfilm',
       'uzbuna!',
       'uzbeks',
       'uzbale',
       'uzbek',
       'uzboy',
       'uzbl',
       'uzb'],
 'c': ['uzcategui'],
 'd': ['uzdunrobita', 'uzd@noba', 'uzdowo', 'uzdin', 'uzdol', 'uzda'],
 'e': ['uzelothrips',
       'uzerliktapa',
       'uzengili',
       'uzenicky',
       'uzenice',
       'uzerche',
       'uzemain',
       'uzelac',
       'uzeyir',
       'uzelle',
       'uzebba',
       'uzeste',
       'uzein',
       'uzeir',
       'uzech',
       'uzere',
       'uzeda',
       'uzem',
       'uzee',
       'uzer',
       'uzes',
       'uzeb',
       'uzel',
       'uzen',
       'uzed'],
 'g': ['uzgavenes'],
 'h': ['uzhavarkarai',
       'uzhamalackal',
       'uzhaippali',
       'uzhiapathu',
       'uzhhorod',
       'uzhavoor',
       'uzhavan',
       'uzhanis',
       'uzhiyan',
       'uzhara',
       'uzhla',
       'uzhur',
       'uzh'],
 'i': ['uzinfocom',
       'uzinaza',
       'uziebly',
       'uzinia',
       'uzimon',
       'uzici',
       'uziel',
       'uzita',
       'uzice',
       'uzi'],
 'k': ['uzkapiai', 'uzkiano', 'uzkoye'],
 'l': ['uzlovaya', 'uzljebic', 'uzlukiai', 'uzlovoy', 'uzliany', 'uzlomac'],
 'm': ['uzmaston', 'uzmitsa', 'uzmauda', 'uzmani', 'uzmino', 'uzma'],
 'n': ['uznews.net', 'uznimakhi', 'uznezya', 'uznach'],
 'o': ['uzomathis',
       'uzovnica',
       'uzovce',
       'uzovo',
       'uzola',
       'uzoma',
       'uzor',
       'uzon',
       'uzos',
       'uzo'],
 'p': ['uzpaliai'],
 'q': ['uzquiano'],
 'r': ['uzranki', 'uzricje'],
 's': ['uzscinet', 'uzsa'],
 't': ['uztelecom', 'uzturre'],
 'u': ['uzumba-maramba-pfungwe',
       'uzunkopruspor',
       'uzunqazmalar',
       'uzuperkasis',
       'uzunbodzhak',
       'uzunlarovo',
       'uzumluk@nd',
       'uzun-mirko',
       'uzunbabali',
       'uzuncaburc',
       'uzundzhovo',
       'uzungulovo',
       'uzunboyad',
       'uzusaliai',
       'uzun-dere',
       'uzunyayla',
       'uzumcul@r',
       'uzunburun',
       'uzunkopru',
       'uzumculuk',
       'uzuntala',
       'uzunmes@',
       'uzunalan',
       'uzunkuyu',
       'uzundara',
       'uzuntash',
       'uzunt@p@',
       'uzunoluk',
       'uzu-maki',
       'uzundere',
       'uzunyurt',
       'uzulenis',
       'uzumine',
       'uzuncam',
       'uzunada',
       'uzunkas',
       'uzunlar',
       'uzumaki',
       'uzunoba',
       'uzunite',
       'uzunova',
       'uzungol',
       'uzushio',
       'uzumlu',
       'uzupis',
       'uzumcu',
       'uzucha',
       'uzuaba',
       'uzupe',
       'uzura',
       'uzury',
       'uzun',
       'uzuh',
       'uzu'],
 'v': ['uzvarciai', 'uzventis', 'uzvara', 'uzvece'],
 'w': ['uzwil'],
 'y': ['uzyanbash',
       'uzynbulaq',
       'uzynagash',
       'uzytamak',
       'uzybash',
       'uzyki',
       'uzyan',
       'uzya',
       'uzyn'],
 'z': ['uzzipari',
       'uzziah',
       'uzzano',
       'uzziel',
       'uzzell',
       'uzzah',
       'uzzal',
       'uzzi']}
