
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gv = {'_': ['gv-e400_series', 'gv_yishun', 'gv_tauri', 'gv_films'],
 'a': ['gvardeysky,_kazakhstan',
       'gvantsa_buniatishvili',
       'gvantsa_kadagishvili',
       'gvantsa_kakhaberidze',
       'gvardeysky_district',
       'gvardeysky,_russia',
       'gvardia_dushanbe',
       'gva_consultants',
       'gvantsa_dolidze'],
 'b': ['gvb'],
 'c': ['gvcs', 'gvc'],
 'd': ['gvd'],
 'e': ['gvenetadze', 'gvedysh', 'gve'],
 'f': ['gvfx', 'gvfs', 'gvf'],
 'g': ['gvg'],
 'h': ['gvhss_vellanad', 'gvhss_kadirur'],
 'i': ['gvidonas_markevicius',
       'gvidas_sabeckis',
       'gvido_birolla',
       'gvidas_juska',
       'gvido_miezis',
       'gvido_jekals'],
 'k': ['gvk_industries', 'gvk_emri', 'gvk_one'],
 'l': ['gvl'],
 'm': ['gvm'],
 'n': ['gvnml', 'gvn'],
 'o': ['gvozdarus_svetovidovi',
       'gvozdansko_castle',
       'gvozdenovic,_ub',
       'gvoko_language',
       'gvozno_lake'],
 'p': ['gvpa', 'gvp'],
 'r': ['gvr'],
 's': ['gvsu_fieldhouse'],
 't': ['gvt.bhs_kanniakulangara', 'gvt_tv'],
 'u': ['gvulot', 'gvu'],
 'v': ['gvv_unitas']}
