
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gd = {'_': ['gd_alcochetense',
       'gd_varandinha',
       'gd_amarantes',
       'gd_beira-mar',
       'gd_braganca',
       'gd_palmeira',
       'gd_greenway',
       'gd_resende',
       'gd_maputo',
       'gd_manica',
       'gd_palmar',
       'gd_space',
       'gd_sundy',
       'gd_set',
       'gd_165',
       'gd_358',
       'gd_356',
       'gd_362',
       'gd_66',
       'gd_61',
       'gd_40'],
 'a': ['gdansk_voivodeship',
       'gdansk_agreement',
       'gdansk_pomerania',
       'gdansk_tablature',
       'gdansk_refinery',
       'gdansk_shipyard',
       'gdanski_bridge',
       'gdansk_county',
       'gdansk_derby',
       'gdara_hamam',
       'gdansk_zoo',
       'gdansk_bay'],
 'b': ['gdbserver'],
 'c': ['gdc_observatory'],
 'd': ['gddr3_sdram',
       'gddr4_sdram',
       'gddr5_sdram',
       'gddr6_sdram',
       'gddr_sdram'],
 'e': ["gdecouv'r_582", 'gdelt_project', 'gde_bertoni'],
 'f': ['gdf10',
       'gdf11',
       'gdf15',
       'gdf6',
       'gdfr',
       'gdf2',
       'gdf1',
       'gdf7',
       'gdf5',
       'gdf3',
       'gdf'],
 'g': ['gdgd_fairies'],
 'h': ['gdh_559'],
 'i': ['gdiapers',
       'gdiesel',
       'gdiaper',
       'gdium',
       'gdinj',
       'gdi2',
       'gdi1',
       'gdi'],
 'j': ['gdjyb', 'gdj'],
 'k': ['gdk'],
 'l': ['gdleen', 'gdlr', 'gdl'],
 'm': ['gdm'],
 'n': ['gdn'],
 'o': ['gdovsky_district', 'gdovsky_uyezd', 'gdov_kremlin'],
 'p': ['gdp-mannose:cellobiosyl-diphosphopolyprenol_alpha-mannosyltransferase',
       'gdp-man:man2glcnac2-pp-dolichol_alpha-1,6-mannosyltransferase',
       'gdp-4-dehydro-6-deoxy-d-mannose_reductase',
       'gdp-6-deoxy-d-talose_4-dehydrogenase',
       'gdp-4-dehydro-d-rhamnose_reductase',
       'gdp-l-galactose_phosphorylase',
       'gdp-mannose_6-dehydrogenase',
       'gdp-mannose_4,6-dehydratase',
       'gdp-d-glucose_phosphorylase',
       'gdp-mannose_3,5-epimerase',
       'gdp-l-fucose_synthase',
       'gdp-linked_bond',
       'gdp_deflator',
       'gdp_density'],
 'r': ['gdr_textafrica', 'gdr_gafetense'],
 's': ['gdsii', 'gdsc', 'gds'],
 't': ['gdt_speedster'],
 'u': ['gdud_haavoda', 'gdut_uav'],
 'v': ['gdv'],
 'w': ['gdw'],
 'x': ['gdx'],
 'y': ['gdynia-kosakowo_airport',
       'gdynia_aquarium',
       'gdyel_district',
       'gdynia_arena',
       'gdynia_point',
       'gdynia_open']}
