
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gj = {'_': ['gj_1005',
       'gj_1245',
       'gj_9827',
       'gj_3991',
       'gj_3379',
       'gj_1128',
       'gj_club',
       'gj_1151'],
 'a': ['gjader_aerodrome', 'gjakova_airport', 'gjaku_im'],
 'b': ['gjb_5860-2006'],
 'c': ['gjc2', 'gjc3', 'gjc1', 'gjc'],
 'd': ['gjd4', 'gjd2', 'gjd3'],
 'e': ['gjenvick-gjonvik_archives',
       'gjertrud_schnackenberg',
       'gjeslingene_lighthouse',
       'gjert_kristoffersen',
       'gjertsen_promontory',
       'gjermund_hagesaeter',
       'gjerstad,_vestland',
       'gjemselund_stadion',
       'gjemnessund_bridge',
       'gjern_municipality',
       'gjelsvik_mountains',
       'gjert_ingebrigtsen',
       'gjerstad,_nordland',
       'gjermundbu_helmet',
       'gjellerups_forlag',
       'gjerdaker_station',
       'gjerstad_station',
       'gjermundnes_farm',
       'gjerasim_qiriazi',
       'gjert_wilhelmsen',
       'gjeble_pedersson',
       'gjergj_arianiti',
       'gjermund_larsen',
       'gjergj_cressiac',
       'gjesvaer_chapel',
       'gjerstad_church',
       'gjermund_braten',
       'gjesasen_church',
       'gjesing_church',
       'gjesdal_church',
       'gjelbrim_taipi',
       'gjest_baardsen',
       'gjerpen_church',
       'gjert_andersen',
       'gjellerasen_if',
       'gjemnes_church',
       'gjeravica_lake',
       'gjergji_muzaka',
       'gjermund_eggen',
       'gjevalin_gegaj',
       'gjelosh_gjokaj',
       'gjergj_bojaxhi',
       'gjergj_xhuvani',
       'gjergj_pekmezi',
       'gjensidige_nor',
       'gjergj_qiriazi',
       'gjergj_bardhi',
       'gjerde_church',
       'gjergj_bubani',
       'gjelstad_pass',
       'gjelsvik_peak',
       'gjergj_fishta',
       'gjeke_marinaj',
       'gjelsvik_spur',
       'gjermund_asen',
       'gjel_glacier',
       'gjergj_zheji',
       'gjert_holsen',
       'gjergji_dema',
       'gjergj_spani',
       'gjergji_papa',
       'gjerdrum_il',
       'gjergj_suli',
       'gjerpen_if'],
 'g': ['gjg'],
 'h': ['gjhs'],
 'i': ['gjirokaster_gymnasium',
       'gjirokaster_fortress',
       'gjirokaster_airfield',
       'gjirokaster_district',
       'gjirokaster_alphabet',
       'gjirokastra_stadium',
       'gjika_amplification',
       'gjirokaster_obelisk',
       'gjirokaster_county',
       'gjilan_assembly',
       'gjini_family',
       'gjin_progoni',
       'gjio_bain'],
 'l': ['gjl'],
 'm': ['gjms_operator'],
 'o': ['gjorgjija_atanasoski',
       'gjorgji_todorovski',
       'gjorgji_bojadziev',
       'gjoko_hadzievski',
       'gjorgji_talevski',
       'gjorgji_tanushev',
       'gjorgi_markovski',
       'gjorgji_cekovski',
       'gjore_jovanovski',
       'gjonaj,_prizren',
       'gjon_markagjoni',
       'gjorgi_gjorgiev',
       'gjorgji_hristov',
       'gjorgji_filipov',
       'gjonnes_station',
       'gjovalin_gjadri',
       'gjorgi_abadziev',
       'gjokaj,_albania',
       'gjorgi_stoilov',
       'gjon_kastrioti',
       'gjovik_station',
       'gjorgi_kolozov',
       'gjovdal_church',
       'gjorgji_mojsov',
       'gjogur_airport',
       'gjovik_stadion',
       'gjoran_saether',
       'gjorge_ivanov',
       'gjoko_dineski',
       'gjovik_church',
       'gjovik_hockey',
       'gjoko_taneski',
       'gjoa_oilfield',
       'gjorv_report',
       'gjorgi_kocov',
       'gjon_gazulli',
       'gjoviks_blad',
       "gjon's_tears",
       'gjorgj_kushi',
       'gjoran_tefre',
       'gjora_chapel',
       'gjon_delhusa',
       'gjoko_zajkov',
       'gjok_uldedaj',
       'gjon_simoni',
       'gjovik_line',
       'gjon_muzaka',
       'gjon_buzuku',
       'gjoa_haven',
       'gjon_ndoja',
       'gjovik_fk',
       'gjovik_ff',
       'gjon_mili'],
 'r': ['gjr'],
 's': ['gjs'],
 't': ['gjt'],
 'u': ['gjurmime_albanologjike',
       'gjuricaj_basilica',
       'gjuvara_noerieva',
       'gjuha_shqipe',
       'gjuro_szabo',
       'gjuha_jone'],
 'x': ['gjxdm'],
 'y': ['gjysylkane', 'gjylekar']}
