
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gp = {'_': ['gp_triberg-schwarzwald',
       'gp_liberazione',
       'gp_fundholding',
       'gp_investments',
       'gp_federation',
       'gp_andromedae',
       'gp_challenge',
       'gp_capodarco',
       'gp_manavgat',
       'gp2_series',
       'gp3_series',
       'gp_herning',
       'gp_pascuas',
       'gp_antalya',
       'gp_horsens',
       'gp_viborg',
       'gp_laguna',
       'gp_racing',
       'gp_wolber',
       'gp_planum',
       'gp_series',
       'gp5_chip',
       'gp_rider',
       'gp_kranj',
       'gp_belek',
       'gp2x_wiz',
       'gp_basic',
       'gp_hall',
       'gp_500',
       'gp_wu'],
 'a': ['gpa_f.c.'],
 'b': ['gpbp1', 'gpb'],
 'c': ['gpcr_oligomer', 'gpc_biotech', 'gpc_sport'],
 'd': ['gpd_win', 'gpd_xd'],
 'e': ['gper', 'gpes', 'gpe'],
 'f': ['gpfs', 'gpfc', 'gpf'],
 'g': ['gpg_mail'],
 'h': ['gph_ispat'],
 'i': ['gpi-space', 'gpihbp1', 'gpisd', 'gpi'],
 'j': ['gpj'],
 'k': ['gpkism', 'gpk'],
 'l': ['gpl-violations.org', 'gplates', 'gpld1'],
 'm': ['gpm_investments'],
 'n': ['gpnotebook', 'gpnmb', 'gpn'],
 'o': ['gpo_telephones', 'gpot_center'],
 'p': ['gpp'],
 'r': ['gpr_endopeptidase', 'gpr_index', 'gpr_120'],
 's': ['gps_hospitality',
       'gpsolo_magazine',
       'gps_meteorology',
       'gps_sonobuoy',
       'gps_signals',
       'gps_drawing',
       'gps_watch',
       'gps_rugby',
       'gps_omens',
       'gps_iir-1',
       'gps_puck',
       'gps_buoy'],
 't': ['gpt_group'],
 'u': ['gpu_virtualization', 'gpu_switching', 'gpu_cluster'],
 'v': ['gpvi'],
 'w': ['gpw'],
 'x': ['gpx3',
       'gpx4',
       'gpx7',
       'gpx6',
       'gpx8',
       'gpx2',
       'gpx5',
       'gpxe',
       'gpx1',
       'gpx'],
 'z': ['gpz']}
