
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_iz = {'_': ['iz_the_wiz', 'iz_u_down'],
 'a': ['izabela,_kuyavian-pomeranian_voivodeship',
       'izabelow,_swietokrzyskie_voivodeship',
       'izabelin,_podlaskie_voivodeship',
       'izaskun_zubizarreta_gerendiain',
       'izabella_elzbieta_czartoryska',
       'izabela,_masovian_voivodeship',
       'izabela_elzbieta_czartoryska',
       'izabelin,_lublin_voivodeship',
       'izabela_katarzyna_mrzyglocka',
       'izabelin,_legionowo_county',
       'izabelow,_lodz_voivodeship',
       'izabela_elzbieta_morsztyn',
       'izaskun_bilbao_barandica',
       'izadkhast_rural_district',
       'izabela_maria_lubomirska',
       'izabelin,_zgierz_county',
       'izard_county_courthouse',
       'izabelin,_gmina_kleczew',
       'izabelin,_gmina_kramsk',
       'izabelin,_turek_county',
       "izaak_walton's_cottage",
       'izabelin,_plock_county',
       'izard_county,_arkansas',
       'izabelin,_minsk_county',
       'izak_parviz_nazarian',
       'izaak_walton_league',
       'izaskun_oses_ayucar',
       'izaak_walton_killam',
       'izad_khvast-e_basri',
       'izak_cornelis_bergh',
       'izabella_st._james',
       'izalzu_-_itzaltzu',
       'iza_duffus_hardy',
       'izaak_walton_inn',
       'izak_van_heerden',
       'izabela_da_silva',
       'izaak_van_oosten',
       'izaz_ali_amrohi',
       'izaak_huru_doko',
       'izapa_stela_5',
       'iza_-_itza'],
 'b': ['izbiska,_podkarpackie_voivodeship',
       'izbiska,_pomeranian_voivodeship',
       'izbica,_pomeranian_voivodeship',
       'izbiska,_masovian_voivodeship',
       'izbiska,_silesian_voivodeship',
       'izbica,_masovian_voivodeship',
       'izbishchi,_vologda_oblast'],
 'd': ['izdebno,_kuyavian-pomeranian_voivodeship',
       'izdebno-kolonia,_masovian_voivodeship',
       'izdebno-kolonia,_lublin_voivodeship',
       'izdebki,_podkarpackie_voivodeship',
       'izdebnik,_masovian_voivodeship',
       'izdebno,_masovian_voivodeship',
       'izdebno,_lublin_voivodeship',
       'izdebno,_miedzychod_county',
       'izdebno,_slupca_county',
       'izdemir_power_station'],
 'e': ['izetta_roberts_cooper', 'izetta_sombo_wesley'],
 'g': ['izgrev,_blagoevgrad_province',
       'izgrev,_burgas_province',
       'izgrev,_varna_province',
       'izgubljen_u_vremenu',
       'izgrev_gas_field',
       'izgak_de_jager'],
 'h': ['izhevsk_electromechanical_plant',
       'izhevsk_mechanical_plant',
       'izhevsk_railway_station',
       'izhma,_komi_republic',
       'izhevsk_radio_plant',
       'izhar_ul_haq'],
 'i': ['iziaslav_iv_vladimirovich',
       'izi,_razavi_khorasan',
       'izi,_north_khorasan',
       'izi_castro_marques',
       'iziaslav_of_kiev'],
 'k': ['izki_natural_park', 'izki_air_base'],
 'l': ['izlaz_and_isprat'],
 'm': ['izmaylovskoye_municipal_okrug',
       'izmail_international_airport',
       'izmaylovo,_ulyanovsk_oblast',
       'izmir_archaeological_museum',
       'izmir_democracy_university',
       'izmaylovo,_vladimir_oblast',
       'izmir_bakircay_university',
       'izmalkovo,_lipetsk_oblast',
       'izmir_ethnography_museum',
       'izmirlian_medical_center',
       'izmir_commodity_exchange',
       'izmir_international_fair',
       'izmailovo_sports_palace',
       'izmir_economic_congress',
       'izmit_ismetpasa_stadium',
       'izmir_parachute_tower',
       'izmir_ataturk_stadium',
       'izmir_football_league',
       'izmit_railway_station',
       'izmir_ataturk_museum',
       'izmit_korfez_circuit',
       'izmir_coach_terminal',
       "izmir_women's_museum",
       'izmir_bomb_kurabiye',
       'izmit_clock_tower',
       'izmir_air_station',
       'izmir_clock_tower',
       'izmir_blue_train',
       'izmir_toy_museum',
       'izmedu_dva_zla'],
 'o': ['izomar_camargo_guilherme',
       'izobilny,_stavropol_krai',
       'izola_city_stadium'],
 'r': ['izrael_poznanski_palace',
       'izrael_abraham_staffel',
       'izray_iffarul_roslan',
       'izrael_chaim_wilner',
       'izrod_na_granici'],
 't': ['iztaccihuatl-popocatepetl_national_park',
       'iztapalapa_metro_station',
       'iztacalco_metro_station'],
 'u': ['izumo-class_multi-purpose_destroyer',
       'izumi_district,_kagoshima',
       'izumicho,_chiyoda,_tokyo',
       'izumo_taisha-mae_station',
       'izushi_district,_hyogo',
       'izumi_koganezuka_kofun',
       'izukyu_shimoda_station',
       'izumo_yashiro_station',
       'izumo_nankin_goldfish',
       'izuhakone_1100_series',
       'izumo_yokota_station',
       'izumo_sakane_station',
       'izumi_junior_college',
       'izumo_minari_station',
       'izumo_science_center',
       'izumo_daito_station',
       'izumizaki_cave_tomb',
       'izucar_de_matamoros',
       'izumi_garden_tower',
       'izumi_kanga_ruins',
       'izu_shaboten_zoo',
       'izumo_no_okuni',
       'izu_kyuko_line',
       'izumi_no_mori'],
 'v': ['izvorovo,_haskovo_province',
       'izvorovo,_dobrich_province',
       'izvaryne_railway_station',
       'izvor,_burgas_province',
       'izvor,_sofia_province',
       'izvestiy_tsik_islands',
       'izvoarele_solar_park',
       'izvor_metro_station',
       'izvoru_oil_field',
       'izvoru_rau_river'],
 'y': ['izyaslav_of_polotsk'],
 'z': ['izzatnagar_railway_division',
       'izzatnagar_railway_station',
       'izzy_stradlin_discography',
       'izzat_ibrahim_al-douri',
       'izzat_yousef_al-maqrif',
       'izz_al-din_manasirah',
       'izz_ad-din_al-qassam',
       'izz_al-din_al-dawla',
       'izzaq_faris_ramlan',
       'izzet_pasha_mosque',
       'izzet_mehmed_pasha',
       "izzy's_koala_world",
       'izz_al-din_husayn',
       'izzy_gold_records',
       "izz_al-din_mas'ud",
       'izzy_the_frenchie',
       'izzet_ulvi_aykurt',
       'izzy_shne_joachim',
       'izzet_ahmed_pasha',
       'izz_al-din,_syria',
       "izzie's_way_home",
       'izz_al-din_usama',
       'izz_al-din_yahya',
       'izz_al-din_shir',
       'izzat_ki_roti',
       'izzy_and_moe']}
