
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ie = {'_': ['ie_business_school',
       'ie_domain_registry',
       'ie_shima_airfield',
       'ie_29000_class',
       'ie_22000_class',
       'ie_2800_class',
       'ie_2600_class',
       'ie_8200_class',
       'ie_no_hikari',
       'ie_201_class'],
 'c': ['ieco_green_warriors', 'iec_tc_57', 'iec_tc_25'],
 'd': ['ied_countermeasure_equipment',
       'ieda_maria_vargas',
       'ied_design_awards'],
 'e': ['ieee_wireless_communications',
       'ieee_communications_magazine',
       'ieee_electromagnetics_award',
       'ieee_communications_society',
       'ieee_registration_authority',
       'ieee_nanotechnology_council',
       'ieee_communications_letters',
       'ieee_standards_association',
       'ieee_honorary_membership',
       'ieee_intelligent_systems',
       'ieee_reliability_society',
       'ieee_rebooting_computing',
       'ieee_microwave_magazine',
       'ieee_internet_computing',
       'ieee_biometrics_council',
       'ieee_photonics_society',
       'ieee_754-2008_revision',
       'ieee_magnetics_society',
       'ieee_education_society',
       'ieee_magnetics_letters',
       'ieee_centennial_medal',
       'ieee_computer_society',
       'ieee_cloud_computing',
       'ieee_photonics_award',
       'ieee_sensors_journal',
       'ieee_sensors_council',
       'ieee_internet_award',
       'ieee_std_260.1-2004',
       'ieee_computing_edge',
       'ieee_founders_medal',
       'ieee_802.11_rts/cts',
       'ieee_life_sciences',
       'ieee_edison_medal',
       'ieee_lamme_medal',
       'ieee_smart_grid'],
 'f': ['iefke_van_belkum'],
 'l': ['ielts_life_skills'],
 'p': ['ieper_railway_station'],
 'r': ['iers_reference_meridian',
       'iernut_power_station',
       'iere_village_mosque',
       'iere_high_school'],
 's': ['ieside_business_institute',
       'iese_business_school',
       'iesf_2009_challenge',
       'ies_beatriz_galindo',
       'iestyn_ap_gwrgant',
       'ies_andres_laguna',
       'ies_san_isidro',
       'ies_la_rabida',
       'ies_alfonso_x',
       'ies_la_flota'],
 't': ['iet_information_security',
       'ietje_paalman-de_miranda',
       'iet_mountbatten_medal',
       'iet_achievement_medal',
       'iet_faraday_medal',
       'ietf_language_tag',
       'iet_van_feggelen'],
 'u': ['ieuan_rhys_williams',
       'ieuan_brydydd_hir',
       'ieud_hill_church',
       'ieuan_wyn_jones']}
