
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vr = {'_': ['vr_positional_tracking',
       'vr_blue_carriages',
       'vr46_racing_team',
       'vr_baseball_2000',
       "vr_baseball_'99",
       "vr_baseball_'97",
       'vr_class_dv12',
       'vr_class_dr12',
       'vr_class_dm10',
       'vr_class_vk11',
       'vr_class_dr13',
       'vr_class_dm12',
       'vr_class_dr14',
       'vr_class_dr16',
       'vr_class_dm11',
       'vr_class_hr11',
       'vr_class_tve2',
       'vr_class_sm1',
       'vr_class_hr1',
       'vr_class_pr1',
       'vr_class_sm2',
       'vr_class_sr1',
       'vr_class_rro',
       'vr_class_sr3',
       'vr_class_sk3',
       'vr_class_pr2',
       'vr_class_sm3',
       'vr_class_sr2',
       'vr_class_dm7',
       'vr_class_tr1',
       'vr_class_vk4',
       'vr_class_sk1',
       'vr_class_sm4',
       'vr_class_vk3',
       'vr_class_eil',
       'vr_class_ds1',
       'vr_class_vr1',
       'vr_class_vr3',
       'vr_class_hv1',
       'vr_class_tk3'],
 'a': ['vrams_gunnarstorp_castle',
       'vratislav_hugo_brunner',
       'vratislavice_nad_nisou',
       'vraca_memorial_park',
       'vrazhdebna_air_base',
       'vrana,_zadar_county',
       'vranic,_kotor_varos',
       'vra_cricket_ground',
       'vratices_se_satane',
       'vranov_nad_toplou',
       'vrane_nad_vltavou',
       'vraj_hindu_temple',
       'vragel_da_silva',
       'vrabac_mini_uav',
       'vranov_nad_dyji',
       'vratice_se_rode',
       'vra_rescue_nsw'],
 'b': ['vrbica,_ilirska_bistrica',
       'vrbas,_donji_vakuf',
       'vrbno_pod_pradedem',
       'vrbova_nad_vahom',
       'vrbno_nad_lesy'],
 'c': ['vrc_sprint_classic',
       'vrc_queens_plate',
       'vrc_stakes_day',
       'vrc_st_leger'],
 'e': ['vreme_brutalnih_dobronamernika',
       'vreeland_avenue_station',
       'vrede_dairy_project',
       'vres_enan_tropo',
       'vren_of_tashir',
       'vreugd_en_rust',
       'vreed_en_hoop'],
 'h': ['vrhovo_pri_sentlovrencu',
       'vrhovec,_zagreb_county',
       'vrhpolje_pri_moravcah',
       'vrhpolje_pri_sentvidu',
       'vrhovo_pri_zuzemberku',
       'vrhpolje,_sanski_most',
       'vrhovlje_pri_kozbani',
       'vrhovlje_pri_kojskem',
       'vrhpolje_pri_kamniku',
       'vrhe,_slovenj_gradec',
       'vrh_pri_sentjerneju',
       'vrh_nad_zelimljami',
       'vrhole_pri_laporju',
       'vrh,_istria_county',
       'vrh_pri_trebelnem',
       'vrh,_bijelo_polje',
       'vrh,_velike_lasce',
       'vrh,_loska_dolina',
       'vrh_pri_bostanju',
       'vrhnika_pri_lozu',
       'vrh_pri_poljanah',
       'vrhe,_novo_mesto',
       'vrh_pri_sobracah',
       'vrh_nad_krasnjo',
       'vrh_pri_mlinsah',
       'vrh_pri_povrsju',
       'vrh_pri_dolskem',
       'vrh_nad_laskim',
       'vrh_pri_hinjah',
       'vrh_pri_ljubnu',
       'vrh_pri_krizu',
       'vrh_pri_pahi',
       'vrh_pri_fari'],
 'i': ['vriddhagiriswarar_temple,_vriddhachalam',
       'vrijzinnige_geloofsgemeenschap_npb',
       'vriessendael,_new_netherland',
       'vrije_universiteit_amsterdam',
       'vriezenveen_railway_station',
       'vrije_universiteit_brussel',
       'vrindavan_railway_station',
       'vrije_vrouwen_vereeniging',
       'vrije_groepen_amsterdam',
       'vrijhoef_en_kalverbroek',
       'vrindavana_dasa_thakura',
       'vriesendorp_and_gaade',
       'vrindavan_lal_verma',
       'vriend_v_alberta',
       'vri_fencing_club'],
 'o': ['vroom-yetton_decision_model',
       'vroomshoop_railway_station',
       'vrooman_avenue_school',
       'vrooom_vroom_vroooom',
       'vroom_and_dreesmann',
       'vrohi_ton_asterion',
       'vronsky_and_babin'],
 's': ['vrsar_crljenka_airport', 'vrsar_airport_bombing'],
 't': ['vrtoce,_bosanski_petrovac',
       'vrt_zendstation_egem',
       'vrtaca_pri_semicu'],
 'u': ['vrucina_gradskog_asfalta'],
 'y': ['vry_afrikaner_movement', 'vryburg_high_school']}
