
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mf = {'_': ['mf_liburnija',
       'mf_cardamone',
       'mf_dubrovnik',
       'mf_storegut',
       'mf_lubenice',
       'mf_prevelis',
       'mf_lastovo',
       'mf_global',
       'mf_tysnes',
       'mf_grimm',
       'mf_hrvat',
       'mf_ghost',
       'mf_doom',
       'mf_mary',
       'mf_bol',
       'mf_vis',
       'mf_77',
       'mf_19',
       'mf_01',
       'mf_ep',
       'mf_88',
       'mf_67'],
 'a': ['mfanufikile_ndzimande',
       'mfanukhona_dlamini',
       'mfantsipim_school',
       'mfa_incorporated',
       'mfanzile_dlamini',
       'mfamsibili_mnisi',
       'mfangano_island',
       'mfa_development',
       'mfa_mukachevo',
       'mfa_oil'],
 'b': ['mfbty', 'mfb'],
 'c': ['mfc_ushkyn-iskra',
       'mfc_mykolaiv-2',
       'mfc_munaishy',
       'mfc_mykolaiv',
       'mfc_tulpar',
       'mfc_ayat',
       'mfc_31',
       'mfc_19',
       'mfc_21',
       'mfc_26',
       'mfc_28',
       'mfc_18',
       'mfc_27',
       'mfc_22',
       'mfc_30',
       'mfc_25',
       'mfc_23',
       'mfc_29',
       'mfc_20',
       'mfc_17',
       'mfc_24'],
 'd': ['mfd'],
 'e': ['mfecane', 'mfezi', 'mfem', 'mfe'],
 'f': ['mff_bordtennis', 'mff_support'],
 'g': ['mfg.com', 'mfge8', 'mfg'],
 'h': ['mfhs', 'mfh'],
 'i': ['mfiondu_kabengele',
       'mfi_foundation',
       'mfinu_language',
       'mfi_program',
       'mfi_group'],
 'j': ['mfj_enterprises'],
 'k': ['mfk_ruzomberok',
       'mfk_vitkovice',
       'mfk_zarnovica',
       'mfk_karvina',
       'mfk_roznava',
       'mfk_skalica',
       'mfk_rusovce',
       'mfk_havirov',
       'mfk_chrudim',
       'mfk_treska',
       'mfk_vrbove',
       'mfk_vyskov',
       'mfk_novaky',
       'mfk_tyumen',
       'mfk_snina',
       'mfk_detva',
       'mfk_kprf'],
 'l': ['mfluids@home', 'mflow', 'mfl'],
 'm': ['mfm_radio', 'mfm_92.6', 'mfm_f.c.'],
 'n': ['mfn1', 'mfng', 'mfn2', 'mfn'],
 'o': ['mfouati_district',
       'mfoniso_udofia',
       'mfon_udoka',
       'mfon_udoh',
       'mfon_ekpo'],
 'p': ['mfpvp', 'mfps', 'mfp'],
 'q': ['mfq'],
 'r': ['mfr_souls'],
 's': ['mfsd14b',
       'mfsd4a',
       'mfsd11',
       'mfsd6l',
       'mfsd1',
       'mfsd7',
       'mfsd8',
       'mfsd3',
       'mfsd5',
       'mfsd2',
       'mfsb',
       'mfsa',
       'mfs'],
 't': ['mft'],
 'u': ['mfumte_language',
       'mfundo_ndhlovu',
       'mfundo_shumana',
       'mfuwe_airport',
       'mfuneko_ngam',
       'mfundo_nsele',
       'mfuwe_lodge'],
 'w': ['mfw'],
 'z': ['mfz_10-7']}
