
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mn = {'_': ['mn_zonation', 'mn-123_mine', 'mn-121_mine', 'mn_artists', 'mn&s_spur'],
 'a': ['mnarolitia_paulianellum',
       'mnarolitia_sylvestrella',
       'mnatsakan_iskandaryan',
       'mnarolitia_griveaudi',
       'mnarolitia_ambreella',
       'mnarolitia_nectaropa',
       'mnanzini_nothobranch',
       'mnarolitia_similans',
       'mnarani,_tanzania',
       'mnachem_risikoff',
       'mnarani_ruins',
       'mnazi_moja',
       'mna_media'],
 'b': ['mnba', 'mnb'],
 'c': ['mnc_entertainment',
       'mncedisi_shabangu',
       'mncedisi_nontsele',
       'mncedisi_filtane',
       'mnc_corporation',
       'mncedisi_malika',
       'mnc_channel',
       'mnc_vision',
       'mnc_sports'],
 'd': ['mndsgn', 'mndo', 'mndr', 'mnda', 'mnd'],
 'e': ['mnesarchella_hamadelpha',
       'mnesarchella_vulcanica',
       'mnesiloba_eupitheciata',
       'mnesictena_daiclesalis',
       'mnesarchella_fusilella',
       'mnesiloba_cauditornata',
       'mnesarchella_philpotti',
       'mnesarchaea_paracosma',
       'mnesictena_flavidalis',
       'mnesarchella_dugdalei',
       'mnesiloba_dentifascia',
       'mnesarchella_loxoscia',
       'mnesictena_pantheropa',
       'mnesistega_talantodes',
       'mnemosyne_productions',
       'mnesictena_antipodea',
       'mnesteria_pharetrata',
       'mnesarchella_ngahuru',
       'mnesictena_marmarina',
       'mnesteria_basanistis',
       'mnesarchella_stellae',
       'mnesarchella_falcata',
       'mnesteria_sideraula',
       'mnesarchaea_hudsoni',
       'mnesiloba_intentata',
       'mnesarchella_acuta',
       'mnesictena_adversa',
       'mnesampela_privata',
       'mnesistega_convexa',
       'mnesarchaea_fallax',
       'mnesampela_lenaea',
       "mnestra's_ringlet",
       'mnesarchaea_fusca',
       'mnesictena_notata',
       'mnemea_laosensis',
       'mnemea_phalerata',
       'mnek_discography',
       'mnemea_javanica',
       'mnemonic_ascent',
       'mnemonic_effect',
       'mnemic_neglect',
       'mnemba_island',
       'mnebhi_palace',
       'mnemata_site',
       'mneme_lake',
       'mnemos_ep'],
 'f': ['mnfpac', 'mnf'],
 'g': ['mng_airlines'],
 'h': ['mnh_entertainment'],
 'i': ['mniodes_plicatifolia',
       'mniodes_pickeringii',
       'mniarogekko_chahoua',
       'mniotype_aulombardi',
       'mniotype_pallescens',
       'mnikelo_ndabankulu',
       'mniotype_bathensis',
       'mniodes_piptolepis',
       'mniophila_muscorum',
       'mniodes_schultzii',
       'mnichovo_hradiste',
       'mniotype_deluccai',
       'mniotype_solieri',
       'mniarogekko_jalu',
       'mniotype_adusta',
       'mniotype_satura',
       'mniodes_radians',
       'mniszech_family',
       'mnichova_lehota',
       'mnium_stellare',
       'mnist_database',
       'mniszki_b'],
 'j': ['mnj'],
 'k': ['mnk_olmissum', 'mnk_izola'],
 'l': ['mnl48_discography'],
 'm': ['mnm_hits'],
 'n': ['mnn'],
 'o': ['mnombo_zwelendaba',
       'mnong_language',
       'mnohaya_lita',
       'mnong_people',
       'mnozil_brass'],
 'p': ['mnp_entreprise', 'mnp_tower', 'mnp_park', 'mnp_llp'],
 'r': ['mnra', 'mnr'],
 's': ['mnsi_telecom', 'mns_pebane'],
 't': ['mnt_ires'],
 'u': ['mnuphorus', 'mnuchin', 'mnu'],
 'w': ['mnw_music'],
 'x': ['mnx1', 'mnx'],
 'y': ['mnyamawamtuka', 'mnyenzeni', 'mnyameni', 'mnynms'],
 'z': ['mnz']}
