
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mg = {'_': ['mg2+-importing_atpase',
       'mg_engineering',
       'mg-lola_ex257',
       'mg_cyberster',
       'mg_magnette',
       'mg_n-type',
       'mg_j-type',
       'mg_m-type',
       'mg_f-type',
       'mg_q-type',
       'mg_l-type',
       'mg_k-type',
       'mg_p-type',
       'mg_xpower',
       'mg_t-type',
       'mg_d-type',
       'mg_r-type',
       'mg_midget',
       'mg_y-type',
       'mg_c-type',
       'mg_motor',
       'mg_14/28',
       'mg_14/40',
       'mg_18/80',
       'mg_alba',
       'mg_cars',
       'mg_ex-e',
       'mg_one',
       'mg_mgb',
       'mg_335',
       'mg_mga',
       'mg_gs',
       'mg_34',
       'mg_va',
       'mg_zs',
       'mg_sa',
       'mg_51',
       'mg_45',
       'mg_29',
       'mg_11',
       'mg_13',
       'mg_kn',
       'mg_zr',
       'mg_15',
       'mg_08',
       'mg_hs',
       'mg_tf',
       'mg_42',
       'mg_zt',
       'mg_gt',
       'mg_30',
       'mg_wa',
       'mg_5',
       'mg_7',
       'mg_6'],
 'a': ['mga_entertainment',
       'mga_anak-bukid',
       'mga_offensive',
       'mgarr_ix-xini',
       'mgarr,_gozo',
       'mgarr_phase'],
 'b': ['mgbo_language', 'mgbo_people', 'mgboko_ngwa'],
 'c': ['mgcini_tshwaku'],
 'd': ['mgd_pm-9'],
 'e': ['mger_mkrtchyan', 'mge_energy'],
 'f': ['mgf'],
 'g': ['mgga'],
 'h': ['mghvimevi_monastery'],
 'i': ['mgimwa', 'mgi'],
 'l': ['mglinsky_district', 'mglinsky_uyezd'],
 'm': ['mgm-pathe_communications',
       'mgm-british_studios',
       'mgm-134_midgetman',
       'mgm-51_shillelagh',
       'mgm_distribution',
       'mgmt_discography',
       'mgm-18_lacrosse',
       'mgm-29_sergeant',
       'mgm-31_pershing',
       'mgm_springfield',
       'mgm-140_atacms',
       'mgm_television',
       'mgm-5_corporal',
       'mgm-157_efogm',
       'mgm-1_matador',
       'mgm-166_losat',
       'mgm_holdings',
       'mgm_networks',
       'mgm-52_lance',
       'mgm_records',
       'mgm_channel',
       'mgm-13_mace',
       'mgm_parade',
       'mgm_energy',
       'mgm_grand',
       'mgm_cotai',
       'mgm_macau',
       'mgm_park',
       'mgm_hd'],
 'n': ['mgn'],
 'o': ['mgolombane_sandile'],
 'p': ['mgp-31_mine', 'mgp_nordic'],
 'r': ['mgr_kazhagam', 'mgr_memorial', 'mgr_nagaril', 'mgr_nagar', 'mgr_magan'],
 's': ['mgs-0039', 'mgscomm', 'mgs/lrs', 'mgst2', 'mgst3', 'mgsm', 'mgs'],
 't': ['mgtow', 'mgtk', 'mgtv', 'mgta', 'mgt'],
 'u': ['mgus_polyneuropathy'],
 'v': ['mgv-176', 'mgv'],
 'w': ['mgwirizano_coalition', 'mgwali_river'],
 'x': ['mgx'],
 'y': ['mgy'],
 'z': ['mgz']}
