
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-25T13:54:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8acd6a97dc49c642ec3c7cde9094b0103d67b26",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
