
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-26T09:49:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "24af0e50e4f72b9188f1ce4af9afade113947b84",
 "version": "0.1.1.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
