
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ug = {'a': ['ugandan_constitutional_conference',
       "uganda_manufacturers'_association",
       'uganda_communications_commission',
       'uganda_broadcasting_corporation',
       'uganda_relationships_commission',
       'uganda_nationalist_organization',
       'uganda_development_corporation',
       'uganda_intelligence_department',
       'uganda-united_states_relations',
       'uganda_pentecostal_university',
       'ugafode_microfinance_limited',
       'uganda_railways_corporation',
       'uganda_investment_authority',
       'uganda_athletics_federation',
       'uganda_episcopal_conference',
       'uganda_christian_university',
       'uganda_management_institute',
       'uganda_cricket_association',
       'ugatlahi_artist_collective',
       'uganda_legislative_council',
       'uganda_securities_exchange',
       'uganda_medical_association',
       'uganda_hockey_association',
       'ugandan_space_initiatives',
       'uganda_independence_medal',
       'uganda_patriotic_movement',
       'uganda_dental_association',
       'uganda_wildlife_authority',
       'uganda_martyrs_university',
       'uganda_co-operative_bank',
       'uganda_volunteer_reserve',
       'uganda_olympic_committee',
       'ugarci,_bosansko_grahovo',
       'uganda_revenue_authority',
       'uganda_national_congress',
       "uganda_people's_congress",
       'uganda_cancer_institute',
       'uganda_military_academy',
       'ugandan_nationality_law',
       'uganda_freedom_fighters',
       'uganda_woodland_warbler',
       'ugar_island,_queensland',
       'uganda_chess_federation',
       'uganda_national_police',
       'uganda_heart_institute',
       'uganda_aids_commission',
       'uganda_national_mosque',
       'uganda_salvation_front',
       "uganda_women's_network",
       'uganda_land_commission',
       'uganda_prisons_service',
       'uganda_aviation_school',
       'uganda_commercial_bank',
       'ugandan_sign_language',
       'ugandan_lowland_shrew',
       'uganda_premier_league',
       "uganda_people's_army",
       'uganda_clays_limited',
       'uganda_radio_network',
       'ugashik_bay_airport',
       "ugandan_coup_d'etat",
       'uganda_oil_refinery',
       'ugandan_red_colobus',
       'uganda_clawed_frog',
       'uganda_law_society',
       'uga_campus_transit',
       'ugandan_booby_trap',
       'uganda_rugby_union',
       'uganda_police_band',
       'uganda_green_party',
       'ugandan_musk_shrew',
       'ugandans_in_india',
       'uganda_rural_fund',
       'ugandan_civil_war',
       'uganda_road_fund',
       'ugandan_bush_war',
       'uganda_air_cargo',
       'uganda_air_force',
       'uga_costa_rica'],
 'c': ['ugc_fox_distribution'],
 'e': ['ugeskrift_for_laeger', 'ugeo_of_gojoseon'],
 'g': ['uggiano_la_chiesa'],
 'h': ['ughelli_township_stadium',
       'ughill_hall_shootings',
       'ughelli_power_plant',
       "ughaz_'elmi_warfa",
       'ughaz_nur_ii'],
 'i': ['ugie,_eastern_cape'],
 'k': ['ugk_4_life'],
 'l': ['ugly_americans:_apocalypsegeddon',
       'uglich_hydroelectric_station',
       'uglegorsk,_sakhalin_oblast',
       'uglovka,_novgorod_oblast',
       'ugly_duckling_fountain',
       "ugly_men's_association",
       'ugly_duckling_theorem',
       'ugljevik_city_stadium',
       'ugly_duckling_presse',
       'ugly_little_monsters',
       'ugly_brother_studios',
       'ugljevik_power_plant',
       'ugly_betty_thailand',
       'ugly_nephew_records',
       'ugl_rail_ph37acmai',
       'ugljare_mass_grave',
       'ugljevik_coal_mine',
       'ugly_miss_young-ae',
       'ugly_is_beautiful',
       'ugly_nasty_people',
       'ugly_man_records',
       'ugly_man_contest',
       'ugly_worm_lizard',
       'ugl_rail_c44aci',
       'ugly_dave_gray',
       'ugly_aur_pagli',
       'ugly_and_proud',
       'ugler_i_mosen',
       'ugly_kid_joe',
       'ugly_as_sin'],
 'm': ['ugm-133_trident_ii', 'ugm_campus_mosque', 'ugm-96_trident_i'],
 'n': ['ugna_mahadev,_bhawanipur'],
 'o': ['ugoszcz,_kuyavian-pomeranian_voivodeship',
       'ugoszcz,_pomeranian_voivodeship',
       'ugoszcz,_masovian_voivodeship',
       'ugolino_della_gherardesca',
       'ugory,_lublin_voivodeship',
       'ugolnoye,_sakha_republic',
       'ugolnaya_railway_station',
       'ugoszcz_railway_station',
       'ugolino_vivaldi_pasqua',
       'ugoke_railway_station',
       'ugor,_vladimir_oblast',
       'ugo_brachetti_peretti',
       'ugolnoye,_amur_oblast',
       'ugo_pasquale_mifsud',
       'ugo_mifsud_bonnici',
       'ugolino_iii_trinci',
       'ugo_pietro_spinola',
       'ugolino_di_tedice',
       'ugolino_ii_trinci',
       'ugone_della_volta',
       "ugo,_re_d'italia",
       'ugolino_of_forli',
       'ugolino_di_nerio',
       'ugo_de_carolis',
       'ugo_a._perego',
       'ugo_de_censi',
       'ugo_da_carpi',
       'ugo_la_malfa',
       'ugo_de_spina',
       'ugo_de_wilde',
       'ugo_di_nola'],
 'r': ['ugra-class_submarine_tender',
       'ugra,_smolensk_oblast',
       'ugron_de_abranfalva',
       'ugra_national_park'],
 'u': ['uguccione_della_faggiuola',
       'ugu_district_municipality',
       'ugur_group_companies',
       'ugur_rifat_karlova',
       'ugur_arslan_kuru',
       'ugur_umit_ungor',
       'uguisu_no_fun'],
 'v': ['ugv_interoperability_profile'],
 'y': ['ugyen_jigme_wangchuck', 'ugyen_academy_fc']}
