
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ud = {'_': ['ud_granadilla_tenerife',
       'ud_gijon_industrial',
       'ud_guadalajara_fs',
       'ud_san_fernando',
       'ud_los_palacios',
       'ud_gran_tarajal',
       'ud_santa_marina',
       'ud_los_barrios',
       'ud_santa_marta',
       'ud_san_claudio',
       'ud_salamanca_b',
       'ud_logrones_b',
       'ud_los_garres',
       'ud_las_palmas',
       'ud_melilla_b',
       'ud_san_pedro',
       'ud_las_zocas',
       'ud_almeria_b'],
 'a': ['udaynarayanpur_madhabilata_mahavidyalaya',
       'udarny,_karachay-cherkess_republic',
       'udaybhansinhji_natwarsinhji_jethwa',
       'udayamarthandapuram_bird_sanctuary',
       'udapalatha_divisional_secretariat',
       'udadumbara_divisional_secretariat',
       'udayapurgadhi_rural_municipality',
       'udadumbara_electoral_district',
       'udaipur_municipal_corporation',
       'udaipur_city-haridwar_express',
       'uda_talawinna_megodagammedda',
       'udav-1_anti-submarine_system',
       'udayagiri,_nellore_district',
       'udawattakele_forest_reserve',
       'udaipur_state,_chhattisgarh',
       'udachnoye,_astrakhan_oblast',
       'udayarkaddu_maha_vidyalayam',
       'udaykrishna-sibi_k._thomas',
       'udairampur_railway_station',
       'udaypur_wildlife_sanctuary',
       'udagama,_eastern_province',
       'udaipur_solar_observatory',
       'udalguri_railway_station',
       'udayapur_cement_industry',
       'udarnik,_voronezh_oblast',
       'udarnik,_sakha_republic',
       'udaipur,_madhya_pradesh',
       'udaipur_railway_station',
       'udawalawe_national_park',
       'uday_narayan_choudhary',
       'uda_pussellawa_railway',
       'udayam_kizhakku_thanne',
       'udayachal_high_school',
       'udarnoye,_amur_oblast',
       'udaras_na_gaeltachta',
       'udawatte_nanda_thero',
       'uda_matsuyama_castle',
       'udaya_shumsher_rana',
       'uda_mikumari_shrine',
       'uda_district,_nara',
       'udai_prakash_arora',
       'uday_singh_taunque',
       'uday_chand_mahtab',
       'udaya_film_awards',
       'uday_pratap_singh',
       'uday_shankar_pani',
       'udayapur_gold_cup',
       'udaya_tara_nayar',
       'udai_bhan_tewari',
       'uday_singh_mehta',
       'uday_kumar_abhay',
       'udai_singh_pawar',
       'uday_lal_maurya',
       'udai_manikya_ii',
       'udai_lal_kumhar',
       'uday_bhanu_hans',
       'uday_chand_dutt',
       'udai_lal_anjana',
       'udai_manikya_i',
       'udal_of_mahoba',
       'uda_gramenet_b',
       'udall_usd_463',
       'udai_singh_ii',
       'uday_k._mehta',
       'udai_singh_i'],
 'd': ['uddevalla_suffrage_association',
       'uddingston_railway_station',
       'uddingston_grammar_school'],
 'e': ['uderzeniowe_bataliony_kadrowe',
       'udelnaya,_moscow_oblast',
       'udesingh_kocharu_padvi',
       'udell_lookout_tower',
       'udell_h._stallings',
       'uden_war_cemetery',
       'udey_chand_dubey',
       'ude_dil_befikre',
       'ude_oko_chukwu',
       'ude_og_hjemme',
       'udet_u_8',
       'udet_u_1'],
 'h': ['udhana-palsana_industrial_corridor',
       'udhagamandalam_railway_station',
       'udhampur_railway_station',
       'udham_singh_nagoke',
       'udhaar_ki_zindagi',
       'udhar_ka_sindur'],
 'i': ['udimskaya_narrow-gauge_railway',
       'udine_railway_station',
       'udic_moisture_regime',
       "udi's_healthy_foods",
       'udi_hrant_kenkulian',
       'udine_half_marathon',
       'udi_slobodno_tour'],
 'j': ['udjiji_worm_lizard'],
 'm': ['udmurt_autonomous_oblast', 'udmurt_state_university'],
 'n': ['udny_railway_station', 'udny_parish_church', 'udny_mort_house'],
 'o': ['udoypur_union,_mollahat',
       'udolphus_aylmer_coates',
       'udom_gabriel_emmanuel',
       'udon_thani_province',
       'udon_thani_hospital',
       'udo_von_alvensleben',
       'udoji_united_f.c.',
       'udon_united_f.c.',
       'udo_max_hollrung',
       'udo_of_neustria',
       'udo_von_woyrsch',
       'udon_thani_f.c.',
       'udon_north_mine',
       'udoma_udo_udoma',
       'udoji_ki_baori',
       'udo_of_aachen',
       'udo_z._karzi',
       'udo_di_fabio'],
 'p': ['udp-galactose--udp-n-acetylglucosamine_galactose_phosphotransferase',
       'udp-2,3-diacetamido-2,3-dideoxyglucuronic_acid_2-epimerase',
       'udp-glucose--glycoprotein_glucose_phosphotransferase',
       'udp-glucuronic_acid_dehydrogenase',
       'udp_helper_address',
       'udp_hole_punching',
       'udp_flood_attack'],
 's': ['udston_mining_disaster',
       'udsali,_rouge_parish',
       'udsikter_fra_ulriken',
       'udsali,_voru_parish'],
 'u': ['udubaddawa_divisional_secretariat',
       'udunuwara_divisional_secretariat',
       'udunuwara_electoral_district',
       'ududumbara_polling_division',
       'udupiddy_electoral_district',
       'udugama_electoral_district',
       'udunuwara_polling_division',
       'udumalai_k._radhakrishnan',
       'uduvil_electoral_district',
       'udupiddy_polling_division',
       'uduc,_western_australia',
       "udupiddy_girls'_college",
       'udumala_bala_showreddy',
       'udumalai_narayana_kavi',
       "uduvil_girls'_college",
       'uduch_sengebau_senior',
       'udupi_ramachandra_rao',
       'udupi_railway_station',
       'udupi_mattu_gulla',
       'udupi_power_plant',
       'udung_ekung_ii',
       'udung_uko_town'],
 'v': ['udvada_railway_station'],
 'y': ['udyavara_madhava_acharya',
       'udyog_karmi_express',
       'udyan_pandit_award',
       'udyog_rattan_award'],
 'z': ['udzungwa_forest_partridge', 'udzungwa_red_colobus']}
