
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hk = {'_': ['hk-5000g',
       'hk-47',
       'hk119',
       'hk01',
       'hk36',
       'hk1',
       'hk2',
       'hk4',
       'hk3'],
 'a': ['hkayazahkuso',
       'hkachoyang',
       'hkahkyeng',
       'hkanlaing',
       'hkawnkaw',
       'hkahpauk',
       'hkasuhpa',
       'hkamkawn',
       'hkashang',
       'hkachang',
       'hka-u-in',
       'hkadaung',
       'hkampti',
       'hkapra',
       'hkamti',
       'hkawan',
       'hkabap',
       'hka'],
 'b': ['hkba', 'hkbh', 'hkb'],
 'c': ['hkchronicles', 'hkch', 'hkcs', 'hkcc'],
 'd': ['hkdc1', 'hkdf'],
 'e': ['hkengnang'],
 'f': ['hkfs', 'hkfa'],
 'g': ['hkgolden50', 'hkgolden', 'hkg'],
 'h': ['hkhs', 'hkh'],
 'i': ['hkinchit', 'hkia', 'hkis', 'hki'],
 'k': ['hkkf', 'hkk'],
 'l': ['hkl'],
 'm': ['hkmap.live', 'hkmo', 'hkma', 'hkmu', 'hkmm', 'hkm'],
 'n': ['hkn'],
 'o': ['hkonmaing',
       'hkonbyin',
       'hkodaung',
       'hko-nwe',
       'hkonsa',
       'hkomi',
       'hko'],
 'p': ['hkpa', 'hkpl', 'hkp'],
 'r': ['hkrangkao', 'hkringmaw', 'hkr1', 'hkr'],
 's': ['hkscan', 'hks-1', 'hkstv', 'hksm', 'hkst', 'hks'],
 't': ['hktvmall', 'hkt48', 'hkt'],
 'u': ['hkust-1'],
 'w': ['hkw']}
