
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hd = {'_': ['hd-rosetta',
       'hd-64180',
       'hd2ioa',
       'hd-plc',
       'hd-mac',
       'hd.32',
       'hd-26',
       'hd-1',
       'hd66',
       'hd-4',
       'hd2',
       'hd+',
       'hd5'],
 'a': ['hdatta',
       'hdac11',
       'hdac10',
       'hdac4',
       'hdac9',
       'hdac3',
       'hdac6',
       'hdac8',
       'hdac1',
       'hdac7',
       'hdax',
       'hdaj',
       'hda'],
 'b': ['hdbaset', 'hdb'],
 'c': ['hdcctv', 'hdcopy', 'hdcam', 'hdca', 'hdci', 'hdc'],
 'd': ['hdderase', 'hdda', 'hdd'],
 'e': ['hdep-28', 'hde'],
 'f': ['hdfc', 'hdf'],
 'g': ['hdgfrp3', 'hdgf', 'hdg'],
 'h': ['hdhomerun', 'hdhd1a', 'hdhd2', 'hdhs', 'hdh'],
 'i': ['hdil', 'hdif', 'hdiv'],
 'j': ['hdj-1000'],
 'k': ['hdk'],
 'l': ['hdlbp', 'hdl3', 'hdl'],
 'm': ['hdmp-28', 'hdmi', 'hdml', 'hdmc', 'hdmk', 'hdms', 'hdm'],
 'n': ['hdn'],
 'o': ['hdos', 'hdo'],
 'p': ['hdparm', 'hdp'],
 'r': ['hdr10+', 'hdr10', 'hdri', 'hdrm', 'hdr'],
 's': ['hdstarcraft', 'hdsb', 'hds'],
 't': ['hdtracks', 'hdt'],
 'u': ['hdu'],
 'v': ['hdvsl', 'hdv'],
 'w': ['hdwiki'],
 'x': ['hdx4', 'hdx'],
 'y': ['hdy']}
