
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_df = {'_': ['df-space',
       'df-224',
       'df-26',
       'df-zf',
       'df-3a',
       'df-21',
       'df-17',
       'df-31',
       'df-11',
       'df-15',
       'df-41',
       'df-25',
       'df-4',
       'df-1',
       'df-5',
       'df2'],
 'a': ['dfaf', 'dfa'],
 'b': ['dfb-hallenpokal', 'dfb-bundestag', 'dfb-pokal', 'dfb'],
 'c': ['dfcu', 'dfcc', 'dfco', 'dfc'],
 'd': ['dfdvd', 'dfds', 'dfdt', 'dfd'],
 'e': ['dfe'],
 'f': ['dffits', 'dffb', 'dffa', 'dff'],
 'g': ['dfg'],
 'h': ['dfh'],
 'i': ['dfinity', 'dfi'],
 'l': ['dfl-ligapokal', 'dfl-supercup'],
 'm': ['dfma', 'dfm'],
 'n': ['dfnb31', 'dfny1', 'dfna5', 'dfn'],
 'o': ['dfoa', 'dfo'],
 'p': ['dfp'],
 'r': ['dfri', 'dfrf', 'dfr'],
 's': ['dfsm', 'dfs'],
 't': ['dftb', 'dft'],
 'u': ['dfu'],
 'v': ['dfv-supercup', 'dfv'],
 'w': ['dfw'],
 'x': ['dfx2', 'dfx'],
 'z': ['dfz']}
