
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_db = {'_': ['db-soft',
       'db-2073',
       'db13w3',
       'db-alm',
       'db120',
       'db4o',
       'db-2',
       'db-1',
       'db-4',
       'db1',
       'db7',
       'db9'],
 'a': ['dbapparel', 'dbass3/5', 'dbayeh', 'dbase', 'dba'],
 'b': ['dbb'],
 'c': ['dbclifford', 'dbcrid', 'dbcc', 'dbc1', 'dbcs', 'dbc'],
 'd': ['dbdnv', 'dbdmh', 'dbdos', 'dbd'],
 'e': ['dbexpress', 'dbeaver', 'dbedit', 'dbe'],
 'f': ['dbf4', 'dbfs', 'dbfc', 'dbfx', 'dbf'],
 'g': ['dbgallery', 'dbgp', 'dbg'],
 'h': ['dbhs', 'dbh'],
 'i': ['dbix::class', 'dbit', 'dbi'],
 'j': ['dbj'],
 'k': ['dbk'],
 'l': ['dbl-583', 'dblp', 'dbl'],
 'm': ['dbmaestro', 'dbmotion', 'dbm0', 'dbm'],
 'n': ['dbndd2', 'dbndns', 'dbnpa', 'dbn1', 'dbnl', 'dbna', 'dbn'],
 'o': ['dbomp', 'dbox2', 'dbox', 'dbo'],
 'p': ['dbpedia', 'dbpc', 'dbp'],
 'q': ['dbq'],
 'r': ['dbridge', 'dbr1', 'dbrs', 'dbrn', 'dbr'],
 's': ['dbscan', 'dbsnp', 'dbss', 'dbsa', 'dbs'],
 't': ['dbtss', 'dbtel', 'dbtt', 'dbt'],
 'u': ['dbus', 'dbu'],
 'v': ['dbv'],
 'x': ['dbx1', 'dbx2', 'dbx'],
 'y': ['dby'],
 'z': ['dbz']}
