PROTECT_ONCE_CONFIG_FILE_ENV = 'PROTECT_ONCE_CONFIG_FILE'
PROTECT_ONCE_CONFIG_TOKEN_BASE_KEY = 'protectOnceToken'
PROTECT_ONCE_CONFIG_CLIENT_ID_KEY = 'clientId'
PROTECT_ONCE_CONFIG_TOKEN_KEY = 'token'
PROTECT_ONCE_CONFIG_ENDPOINT_KEY = 'endpoint'
PROTECT_ONCE_CONFIG_ENDPOINT_PORT_KEY = 'port'

BACKEND_REST_API_URL_ENV = 'PO_ENDPOINT'
BACKEND_REST_API_PORT_ENV = 'PO_ENDPOINT_PORT'
BACKEND_REST_API_CLIENT_ID_ENV = 'PO_CLIENTID'
BACKEND_REST_API_TOKEN_ENV = 'PO_TOKEN'

BACKEND_REST_API_TOKEN_KEY = 'accessToken'
BACKEND_REST_API_REFRESH_TOKEN_KEY = 'refreshToken'
BACKEND_REST_API_REFRESH_TOKEN_HEADER = 'x-protectonce-refresh-token'

APP_DELETE_STATUS_CODE = 404


#REST API Paths
REST_API_LOGIN = '/login'
REST_API_HEART_BEAT = '/heartbeat'