
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gy = {'_': ["gy's_sampling_theory", 'gy_postcode_area'],
 'a': ['gyan_educational_institution',
       'gyaneshwar_prasad_thapliyal',
       'gyanpeeth_degree_college',
       'gyanendra_bahadur_karki',
       'gyan_bahadur_yakthumba',
       'gyan_bharati_vidyalaya',
       "gyai'ra_losang_dainzin",
       'gyalwang_mipham_wangpo',
       'gyalwang_pagsam_wangpo',
       'gyanendra_pratap_singh',
       'gyanmala_bhajan_khala',
       'gyalsey_tenzin_rabgye',
       'gyan_kumari_chhantyal',
       'gyanendra_nath_pande',
       'gyan_prakash_pilania',
       'gyan_chandra_acharya',
       'gyan_chandra_mishra',
       'gyan_vigyan_academy',
       'gyan_bahadur_bohara',
       'gyan_bharati_school',
       'gyara_hazar_ladkian',
       'gyan_singh_sohanpal',
       'gyang_dalyop_datong',
       'gyarsi_bai_sahariya',
       'gyan_jyoti_college',
       'gyanendra_of_nepal',
       'gyan_jyoti_nainpur',
       'gyan_sudha_misra',
       'gyan_bagh_palace',
       'gyan_chand_jain',
       'gyan_dev_ahuja'],
 'd': ['gyda_ellefsplass_olssen',
       'gyda_westvold_hansen',
       'gyda_nature_reserve',
       'gyda_oil_field',
       'gyda_of_sweden'],
 'e': ['gyeongsangbuk-do_provincial_council',
       'gyeonggi_broadcasting_corporation',
       'gyeongju_international_marathon',
       'gyeongsang_national_university',
       'gyeongbuk_provincial_college',
       'gyeongbu_high-speed_railway',
       'gyeryongsan_national_park',
       'gyeongju_national_museum',
       'gyeonggi_gwangju_station',
       'gyeongju_historic_areas',
       'gyeongju_civic_stadium',
       'gyeongju_national_park',
       'gyeongmyeong_of_silla',
       'gyeongsin_high_school',
       'gyeongjong_of_goryeo',
       'gyeongnam_art_museum',
       'gyeongjong_of_joseon',
       'gyeongju_citizen_fc',
       'gyeongdeok_of_silla',
       'gyeongheung_eo_clan',
       'gyeonggi_gwangju_fc',
       'gyeongju_seol_clan',
       'gyeongmun_of_silla',
       'gyeongju_seop_clan',
       'gyeongju_choe_clan',
       'gyeongju_bing_clan',
       'gyeongsun_of_silla',
       'gyeongae_of_silla',
       'gyeongju_yun_clan',
       'gye_of_samhan',
       'gye_of_baekje'],
 'g': ['gygaea_of_macedon', 'gyges_of_lydia'],
 'i': ['gyirmot_fc_gyor', 'gyi_khin_pe'],
 'l': ['gylfi_thorsteinsson_gislason',
       "gyldenstolpe's_worm_skink",
       'gyldendal_norsk_forlag',
       'gyliano_van_velzen',
       'gyllene_tider_ep',
       'gyles_v_wilcox',
       'gylle_de_burgh'],
 'm': ['gymnasium_graf-anton-guenther_school',
       'gymnastics_world_championships',
       'gymnasium_"slobodan_skerovic"',
       'gymnazium_christiana_dopplera',
       'gymkhana_ground,_secunderabad',
       'gymnasium_bayreuther_strasse',
       'gymnazium_josefa_jungmanna',
       'gymnazium_kralovsky_chlmec',
       'gymkhana_ground,_bengaluru',
       'gymnasium_petrinum_dorsten',
       'gymnasium_kiril_pejcinovik',
       'gymnasium_of_dimitrovgrad',
       'gymnastics_club_ergotelis',
       'gympie_ambulance_station',
       'gymkhana_ground,_rangoon',
       'gymnazium_andreja_vrabla',
       'gymnastics_in_azerbaijan',
       'gymnadenia_x_chanousiana',
       'gymnasium_st._augustine',
       'gympie_railway_station',
       'gymnasium_munchen_nord',
       'gymnazium_jana_keplera',
       'gympie_stock_exchange',
       'gympie_road,_brisbane',
       'gymea_railway_station',
       'gymkhana_club_ground',
       'gympie_memorial_park',
       'gymnasium_jur_hronec',
       'gymnasium_am_ostring',
       'gympie_arterial_road',
       'gympie_music_muster',
       'gymnasium_at_delphi',
       'gymnastics_in_india',
       'gympie_lands_office',
       'gympie_court_house',
       'gymnoi_sto_dromo',
       'gymnasium_No._36',
       'gympie_town_hall',
       'gym_class_heroes',
       'gym_floor_cover',
       'gym_and_tonic'],
 'n': ['gynecologic_oncology_group', 'gynoid_fat_distribution'],
 'o': ['gyor-moson-sopron_county_council',
       'gyor-per_international_airport',
       'gyoko-dori_underground_gallery',
       'gyosei_international_school',
       'gyorgy_lukacs_bibliography',
       'gyorgy_cziffra_discography',
       'gyobutsuji_zen_monastery',
       'gyoten_ningen_batseelor',
       'gyokairui_yamaoka_maiko',
       'gyoda_futagoyama_kofun',
       'gyongyosi_farkasok_rk',
       'gyor_railway_station',
       'gyorgy_gyula_zagyva',
       'gyorgy_cziffra_jr.',
       'gyorgy_bp._szabo',
       'gyodong_in_clan',
       'gyoza_no_ohsho',
       'gyorgy_g._rath',
       'gyoha_no_clan',
       'gyori_eto_fc'],
 'p': ['gypsum_recycling_international',
       'gypsum_springs_formation',
       'gypsum_factory,_isfahan',
       'gypsy_solidarity_party',
       'gypsy_kumbia_orchestra',
       'gypsy,_west_virginia',
       'gypsy_hill_killings',
       'gypsum_mine,_shiraz',
       'gypsy_lore_society',
       'gypsy_caravan_tour',
       'gypsum_des_camoins',
       'gypsies_on_parade',
       'gypsy_heart_tour',
       'gypsy_folk_tales',
       'gypped_in_egypt',
       'gypsy_hill_park',
       'gypsy:_a_memoir',
       'gypsy_in_amber',
       'gypsy_rose_lee',
       'gypsy_in_jazz'],
 'r': ['gyrate_bidiminished_rhombicosidodecahedron',
       'gyroelongated_pentagonal_cupolarotunda',
       'gyrinophilus_palleucus_necturoides',
       'gyroelongated_pentagonal_birotunda',
       'gyroelongated_triangular_bicupola',
       'gyroelongated_pentagonal_bicupola',
       'gyroelongated_pentagonal_pyramid',
       'gyroelongated_pentagonal_rotunda',
       'gyroelongated_pentagonal_cupola',
       'gyroelongated_triangular_cupola',
       'gyroelongated_square_bipyramid',
       'gyroelongated_square_bicupola',
       'gyroelongated_square_pyramid',
       'gyro-kopp-ters_midnight_hawk',
       'gyroelongated_square_cupola',
       'gyro-kopp-ters_twin_eagle',
       'gyroscopic_exercise_tool',
       'gyrodyne_ron_rotorcycle',
       "gyro's_first_invention",
       'gyroflug_speed_canard',
       'gyrodyne_qh-50_dash',
       'gyro_motor_company',
       'gyrid_of_sweden',
       'gyrd_and_gnupa',
       'gyro_rate_unit',
       'gyra_rna_motif'],
 's': ['gysbert_wigand_michelbecker', 'gys_de_villiers', 'gys_van_beek'],
 't': ['gytha_of_wessex'],
 'u': ['gyurza-m-class_artillery_boat',
       'gyula_shakespeare_festival',
       'gyumri_technology_center',
       'gyumri_football_academy',
       'gyumri_railway_station',
       'gyulai_istvan_memorial',
       'gyulaj_hunting_hungary',
       'gyumri_city_stadium',
       'gyulai_varvedok_rk',
       'gyula_j._obadovics',
       'gyula_y._katona',
       'gyu_hyeong_cho']}
