
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kf = {'_': ['kf_beselidhja_prishtine',
       'kf_flamurtari_ladorisht',
       'kf_shkendija_haracine',
       'kf_djelmnia_shkodrane',
       'kf_adriatiku_mamurras',
       'kf_tekstilisti_stalin',
       'kf_flamurtari_debresh',
       'kf_vllaznia_pozheran',
       'kf_dukagjini_gjakove',
       'kf_kastrioti_ferizaj',
       'kf_shkendija_tirane',
       'kf_skenderbeu_poroj',
       'kf_bashkimi_koretin',
       'kf_defence_programs',
       'kf_skenderbeu_korce',
       'kf_behar_vitomirica',
       'kf_liria_millosheve',
       'kf_vllaznia_shkoder',
       'kf_vllaznimi_struga',
       'kf_beselidhja_lezhe',
       'kf_albpetrol_patos',
       'kf_milano_kumanove',
       'kf_perparimi_recan',
       'kf_perparimi_runik',
       'kf_korabi_peshkopi',
       'kf_bashkimi_gjilan',
       'kf_adriatiku_2012',
       'kf_vardari_forine',
       'kf_spartak_tirana',
       'kf_drita_bogovine',
       'kf_liria_zagracan',
       'kf_shemshova_1984',
       'kf_besa_doberdoll',
       'kf_vellazerimi_77',
       'kf_lirija_gercar',
       'kf_jehona_kozare',
       'kf_liria_zheline',
       'kf_liria_prizren',
       'kf_besa_sllupcan',
       'kf_ramiz_sadiku',
       'kf_fushe_kosova',
       'kf_korabi_debar',
       'kf_teuta_durres',
       'kf_tirana_women',
       'kf_fortuna_1975',
       'kf_tirana_u-21',
       'kf_tefik_canga',
       'kf_besa_kavaje',
       'kf_besa_irzniq',
       "kf_trepca_'89",
       'kf_drini_2004',
       'kf_onix_banje',
       'kf_turbina_b',
       'kf_2_korriku',
       'kf_rinia_98',
       'kf_tirana_b',
       'kf_sopoti_b',
       'kf_teuta_b'],
 'a': ['kfarjoz_municipal_stadium',
       "kfar_bar'am_synagogue",
       'kfar_etzion_massacre',
       'kfar_hanoar_hadati',
       'kfar_monash_hoard',
       'kfar_tzvi_sitrin',
       'kfar_hasidim_bet',
       'kfar_bin_nun'],
 'c': ['kfc_original_recipe',
       'kfc_uerdingen_05',
       'kfc_cycling_team',
       'kfc_yum!_center',
       'kfc_in_japan',
       'kfc_in_china'],
 'f': ['kff_vllaznia_shkoder',
       'kff_skenderbeu_korce',
       'kff_liria_prizren',
       'kff_juban_danja',
       'kff_tirana_as'],
 'u': ['kfupm_mathematics_olympiad', 'kfums_boldklub_kobenhavn'],
 'v': ['kfvs_tv_mast']}
