
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kt = {'_': ['kt_tunstall_discography',
       'kt_postcode_area',
       'kt_shooting_team',
       'kt_manu_musliar'],
 'a': ['ktav_publishing_house', 'kta_super_stores', 'ktal_tv_tower'],
 'f': ['ktff_super_lig', 'ktff_super_cup', 'ktff_1._lig'],
 'g': ['ktg_education_group'],
 'h': ['kthm_college,_nashik'],
 'i': ['ktiv_hasar_niqqud'],
 'l': ['ktla_morning_news'],
 'm': ['ktm_1190_adventure',
       'ktm_990_adventure',
       'ktm_950_adventure',
       'ktm_640_adventure',
       'ktm_duke_series',
       'ktm_390_series',
       'ktm_690_enduro',
       'ktm_450_rally',
       'ktm_class_92',
       'ktm_class_22',
       'ktm_lc4_660r',
       'ktm_class_91',
       'ktm_690_duke',
       'ktm_class_29',
       'ktm_1190_rc8',
       'ktm_class_93',
       'ktm_class_82',
       'ktm_790_duke',
       'ktm_class_61',
       'ktm_200_duke',
       'ktm_class_81',
       'ktm_class_83',
       'ktm_class_19',
       'ktm_500_exc',
       'ktm_250_frr',
       'ktm_450_exc',
       'ktm_125_frr',
       'ktm_65_sx'],
 'n': ['ktn_news_kenya'],
 's': ['ktsia-tabatskuri_managed_reserve'],
 'u': ["ktu_men's_basketball", 'ktu_radio_gaudeamus'],
 'x': ['ktx_family_card']}
