
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ks = {'_': ['ks_konfeks_legnica',
       'ks_polonia_vilnius',
       'ks_voitleja_narva',
       'ks_azs_wroclaw',
       'ks_tiga_naga',
       'ks_nowy_targ',
       'ks_ali_demi',
       'ks_x_1001',
       'ks_x_1002'],
 'a': ['ksawery,_kuyavian-pomeranian_voivodeship',
       'ksawerow,_swietokrzyskie_voivodeship',
       'ksawerynow,_masovian_voivodeship',
       'ksawerow,_lublin_voivodeship',
       'ksawerow,_pabianice_county',
       'ksawerow,_wrzesnia_county',
       'ksawerow,_pajeczno_county',
       'ksawerow,_leczyca_county',
       'ksawerow,_kalisz_county',
       'ksawerow,_konin_county',
       'ksar_chellala_district',
       'ksar_metlili_formation',
       'ksaver_sandor_gjalski',
       'ksar_hellal_congress',
       'ksar_sbahi_district',
       'ksar_ouled_soltane',
       'ksafa_super_league',
       'ksafa_major_league',
       'ksar_akil_flake',
       'ksar_el_hirane',
       'ksar_el_khali',
       'ksar_el_barka',
       'ksar_el_majaz',
       'ksar_el_abtal'],
 'c': ['ksc_headquarters_building', 'ksc_commercial_internet'],
 'd': ['ksd_shanbhag_vidyalaya'],
 'e': ['ksenia_aleksandrovna_razumova',
       'kse_targu_secuiesc',
       'kse_100_index',
       'kse_30_index'],
 'f': ['ksf_prespa_birlik'],
 'g': ['ksgm_college_nirsa'],
 'h': ['kshetresa_chandra_chattopadhyaya',
       'kshitiz_educational_foundation',
       'kshirode_prasad_vidyavinode',
       'kshitish_ranjan_chakravorty',
       'kshetrimayum_biren_singh',
       'kshetrarama_maha_vihara',
       'kshetra_pratap_adhikary',
       'kshetia_railway_station',
       'kshitish_chandra_neogy',
       'kshamichu_ennoru_vakku',
       'kshitish_mohan_lahiri',
       'kshemkari_mata_temple',
       'kshetri_irabot_singh',
       'kshitij_ye_nahi',
       'kshitij_r._vyas'],
 'i': ['ksiaz,_kuyavian-pomeranian_voivodeship',
       'ksiaznice,_swietokrzyskie_voivodeship',
       'ksiaznice,_podkarpackie_voivodeship',
       'ksiazenice,_silesian_voivodeship',
       'ksiazenice,_masovian_voivodeship',
       'ksiestwo,_masovian_voivodeship',
       'ksieginice,_trzebnica_county',
       'ksiestwo,_lodz_voivodeship',
       'ksieginice,_legnica_county',
       'ksiezno,_bartoszyce_county',
       'ksieginice,_wroclaw_county',
       'ksiega_tajemnicza._prolog',
       'ksiaz,_lublin_voivodeship',
       'ksieginki,_koscian_county',
       'ksiezno,_braniewo_county',
       'ksieginice,_lubin_county',
       'ksieginki,_srem_county',
       'ksiaz_landscape_park',
       'ksibet_el_mediouni',
       'ksiazka_i_wiedza',
       'ksi_sii_aks'],
 'k': ['ksk_energy_ventures', 'ksk_vigri_tallinn', 'ksk_luch_moscow'],
 'l': ['ksl_capital_partners'],
 'o': ['ksour_essef_cuirass'],
 'r': ['ksr_bengaluru-nagercoil_express', 'ksr_sains_f.c.'],
 's': ['kss_design_group'],
 't': ['kstovo,_vologda_oblast', "kst_live_31.08.'95"],
 'u': ['ksu_convocation_center'],
 'v': ['ksv_ankerbrot_montelaa',
       'ksv_simson_bremen',
       'ksv_hessen_kassel',
       'ksv_ice_tigers'],
 'z': ['kszo_ostrowiec_swietokrzyski']}
