
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kk = {'_': ['kk_vrijednosnice_osijek',
       'kk_zeljeznicar_sarajevo',
       'kk_hercegovac_gajdobra',
       'kk_vojvodina_srbijagas',
       'kk_vardar_osiguruvanje',
       'kk_proleter_zrenjanin',
       'kk_napredak_aleksinac',
       'kk_perlas_vilkaviskis',
       'kk_millenium_strumica',
       'kk_nemetali_ograzden',
       'kk_zeleznicar_indija',
       'kk_cedevita_olimpija',
       'kk_studentski_centar',
       'kk_napredak_krusevac',
       'kk_spartak_subotica',
       'kk_radnik_bijeljina',
       'kk_hermes_analitica',
       'kk_zeleznicar_cacak',
       'kk_radnik_surdulica',
       'kk_works_1998-2000',
       'kk_metalac_valjevo',
       'kk_cedevita_junior',
       'kk_koper_primorska',
       'kk_euronickel_2005',
       'kk_varda_visegrad',
       'kk_smederevo_1953',
       'kk_zoltasti_troti',
       'kk_zlatorog_lasko',
       'kk_dinamo_pancevo',
       'kk_student_mostar',
       'kk_knjazevac_1950',
       'kk_slavonski_brod',
       'kk_osjecki_sokol',
       'kk_karpos_sokoli',
       'kk_sloboda_uzice',
       'kk_lechia_gdansk',
       'kk_mladost_zemun',
       'kk_akademija_fmp',
       'kk_triglav_kranj',
       'kk_crvena_zvezda',
       'kk_radnicki_1950',
       'kk_zitko_basket',
       'kk_paulus_parnu',
       'kk_abs_primorje',
       'kk_balkan_steel',
       'kk_kvarner_2010',
       'kk_mega_basket',
       'kk_lovcen_1947',
       'kk_donji_vakuf',
       'kk_sveti_dorde',
       'kk_borac_zemun',
       'kk_skofja_loka',
       'kk_borac_cacak',
       'kk_bosna_royal',
       'kk_zito_vardar',
       'kk_teodo_tivat',
       'kk_mornar_bar',
       'kk_lavovi_063',
       'kk_bfc_beocin',
       'kk_mzt_skopje',
       'kk_mladost_sp',
       'kk_super_mart',
       'kk_beovuk_72',
       'kk_zeta_2011',
       'kk_jolly_jbs',
       'kk_plama_pur',
       'kk_fair_play',
       'kk_novi_sad',
       'kk_cacak_94',
       'kk_crn_drim',
       'kk_av_ohrid',
       'kk_amak_sp'],
 'k': ['kkk_mosir_krosno', 'kkkill_the_fetus'],
 'p': ['kkpk_medyk_konin'],
 's': ['kks_pro-basket_kutno', 'kks_1925_kalisz', 'kks_class_s'],
 't': ['kktm_government_college']}
