
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-25T22:08:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f91eaf9880d75bd975142915831ff47aedeb8878",
 "version": "0.2.26.post0.dev32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
