
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uu = {'_': ['uu_aurigae', 'uu_world'],
 'c': ['uucp', 'uuc'],
 'd': ['uuden_edessa'],
 'e': ['uue-saaluse',
       'uue-kariste',
       'uuemererahu',
       'uuencoding',
       'uue-antsla',
       'uuemaarahu',
       'uueveski',
       'uuevalja',
       'uuemoisa',
       'uuesalu',
       'uuearu',
       'uuemaa',
       'uue'],
 'g': ['uuganbat_batmonkh'],
 'h': ['uuhraah!', 'uuhash'],
 'i': ['uuijeong'],
 'k': ['uukwiyu_constituency', 'uukule_cluster'],
 'l': ['uulbayan,_sukhbaatar'],
 'm': ['uummannaq_heliport',
       'uummannaq_airport',
       'uummannaq_island',
       'uummannaq_fjord',
       'uum-44_subroc'],
 'n': ['uunartoq_qeqertaq',
       'uuno_epsanjassa',
       'uuno_turhapuro',
       'uunartoq_disc',
       'uuno_brander',
       'uuno_laakso',
       'uuno_kailas',
       'uuno_railo',
       'uuno_takki',
       'uuno_klami'],
 'p': ['uup'],
 'r': ['uuriintuya_dagvasambuu', 'uur_caleed', 'uureg_lake', 'uur_river'],
 's': ['uusi_tietosanakirja',
       'uusinta_ensemble',
       'uusvada_ludimagi',
       'uusimaa_province',
       'uusikyla,_lahti',
       'uusvada_tsasson',
       'uusi_nainen',
       'uusi_suomi',
       'uus_maailm',
       'uusi_lahti',
       'uusi_runo',
       'uus_eesti',
       'uus_ilm'],
 't': ['uutislehti_100'],
 'u': ['uuu'],
 'v': ['uuvudhiya_constituency'],
 'y': ['uuyoka']}
