
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ua = {'_': ['ua-columbia_cablevision',
       'ua2_experiment',
       'ua_discography',
       'ua1_experiment',
       'ua8_experiment',
       'ua5_experiment',
       'ua4_experiment',
       'ua_valettoise',
       'ua_university',
       'ua_gormgaile',
       'ua_gaillac',
       'ua_cognac',
       'ua_horta',
       'ua_8699',
       'ua_huka',
       'ua_pou'],
 'a': ['uaa_films'],
 'b': ['uaboe_district',
       'uab_hospital',
       'uab_blazers',
       'uabc_radio',
       'uab_lelija',
       'uab_icor'],
 'c': ['uac_turbotrain', 'uaco_cungo', 'uaca_river', 'uach_f.c.'],
 'd': ['uad'],
 'e': ['uaem_maastricht',
       'uae_exchange',
       'uae_royals',
       'uae_derby',
       'uae_oaks',
       'uae_five',
       'uae_tour',
       'uae_cup'],
 'f': ['uafato', 'uafa', 'uaf'],
 'g': ['uag'],
 'h': ['uahekua_herunga'],
 'i': ['uaicurapa_river', 'uailan_river', 'uai_urquiza'],
 'j': ['uaj'],
 'k': ['uakazuwaka_kazombiaze'],
 'l': ['ualikhanov_district',
       'ual_corporation',
       'uali_elamanov',
       'ualosi_kailea',
       'uali_kurzhev',
       'uale_mai'],
 'm': ['uam_azcapotzalco',
       'uam_xochimilco',
       'uams_northwest',
       'uam_iztapalapa',
       'uam_cuajimalpa',
       'uam_creoula',
       'uamh_bheag',
       'uamh_mhor'],
 'n': ['uaneen_fitzsimons',
       'uanhenga_xitu',
       'uan_muhuggiag',
       "uani_'unga",
       'uan_rasey'],
 'p': ['uapaca_heudelotii', 'uapaca_kirkiana', 'uapaca_bojeri'],
 'q': ['uaq'],
 'r': ['uaru_amphiacanthoides',
       'uaru_fernandezyepezi',
       'uarini_river',
       'uar_esgudud'],
 's': ['uas_laboratories', "uasila'a_heleta"],
 't': ['uatsamonga_order',
       'uatlok_twithu',
       'uatatas_river',
       'uatuma_river',
       'uati_maposua',
       'uati_iutana'],
 'u': ['uauaris_river'],
 'v': ['uav_fap'],
 'w': ['uaw-ford_university', 'uawa_county', 'uawa_river'],
 'x': ['uaxactun_airport'],
 'y': ['uayma_municipality'],
 'z': ['uaz_patriot', 'uaz_simbir', 'uaz_jaguar', 'uaz_simba', 'uaz_bars']}
