
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uv = {'_': ['uv-328'],
 'a': ['uvariodendron',
       'uvayatikulam',
       'uvariastrum',
       'uvariopsis',
       'uvarkkulam',
       'uvarovitsa',
       'uvarovite',
       'uvarovsky',
       'uvaricin',
       'uvarjarv',
       'uvanilla',
       'uvarovka',
       'uvalino',
       'uvavnuk',
       'uvarovo',
       'uvalno',
       'uvayuq',
       'uvarov',
       'uvarus',
       'uvalde',
       'uvalny',
       'uvaria',
       'uvanga',
       'uvala',
       'uvaly',
       'uvata',
       'uvari',
       'uvary',
       'uvalo',
       'uvas',
       'uvat',
       'uvaa',
       'uvac',
       'uva'],
 'b': ['uvb-76'],
 'c': ['uvc'],
 'd': ['uvdal'],
 'e': ['uveoparotitis',
       'uvernet-fours',
       'uversbreen',
       'uverworld',
       'uvedalia',
       'uveitis',
       'uvedale',
       'uvelsky',
       'uvelye',
       'uvero',
       'uvea',
       'uver',
       'uve'],
 'f': ['uvf'],
 'g': ['uvg'],
 'i': ['uvidicolus', 'uvilla', 'uvinul', 'uvinza', 'uvira', 'uvis', 'uvik'],
 'j': ['uvjeca'],
 'o': ['uvorici', 'uvongo', 'uvod', 'uvo'],
 'r': ['uvrag', 'uvr8', 'uvrd'],
 's': ['uvse'],
 'u': ['uvulopalatopharyngoplasty',
       'uvulopalatoplasty',
       'uvularization',
       'uvulariaceae',
       'uvuru-agada',
       'uvulotomy',
       'uvularia'],
 'v': ['uvvu', 'uvv'],
 'w': ['uvwie', 'uvw'],
 'x': ['uvx']}
