
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_md = {'_': ['md._waheduzzaman_sarkar',
       'md._mazbauddin_farhad',
       'md._shakhawat_hossain',
       'md._moniruzzaman_moni',
       'md._mokhlesur_rahman',
       'md._sharfuddin_ahmed',
       'md._muzammel_hossain',
       'md._sanowar_hossain',
       'md._reazuddin_ahmed',
       'md._mamunoor_rashid',
       'md_moshfequr_rahman',
       'md._mahbubur_rahman',
       'md._akabbar_hossain',
       'md._hasibur_rashid',
       'md._azaharul_islam',
       'md._shafiqul_islam',
       'md._ghulam_rabbani',
       'md_mahfuzur_rahman',
       'md_khaled_al-mamun',
       'md_sohorab_hossain',
       'md._touhid_hossain',
       'md._enamur_rahaman',
       'md._mokbul_hossain',
       'md_shafeenul_islam',
       'md._mozammel_haque',
       'md._tafazzul_islam',
       'md._delwar_hossain',
       'md._shahinur_islam',
       'md._habibur_rahman',
       'md._golam_mostofa',
       'md._zahirul_islam',
       'md._saifur_rahman',
       'md._shamsul_haque',
       'md._golam_mustafa',
       'md._afzal_hossain',
       'md._golam_rabbani',
       'md_ismail_hossain',
       'md._kabirul_haque',
       'md._matiur_rahman',
       'md._emdadul_haque',
       'md._salleh_yaapar',
       'md._altaf_hossain',
       'md._zahurul_islam',
       'md._habibe_millat',
       'md._motiur_rahman',
       'md._abdul_maleque',
       'md_mizanur_rahman',
       'md._golam_hossain',
       'md_hashim_hussein',
       'md._atiur_rahman',
       'md._suhrab_uddin',
       'md._shahab_uddin',
       'md._ziaur_rahman',
       'md_zakir_hossain',
       'md_saiful_abedin',
       'md._abdus_shahid',
       'md._zillul_hakim',
       'md._abdul_quddus',
       'md._tauseef_alam',
       'md._shamsul_alam',
       'md._abdus_sattar',
       'md_rafiqul_islam',
       'md_shafiqul_alam',
       'md._ruhul_quddus',
       'md._aminul_islam',
       'md._rezaul_hasan',
       'md._habibul_gani',
       'md._nurul_anwar',
       'md._kamiz_uddin',
       'md._abdul_gafur',
       'md._nazim_uddin',
       'md._tajul_islam',
       'md._abdul_hafiz',
       'md._rashed_amin',
       'md._iqbal_kabir',
       'md._abdul_haque',
       'md._abdul_kadir',
       'md_shawkat_imam',
       'md._ayeen_uddin',
       'md._umar_farooq',
       'md_abdul_mubeen',
       'md_mainul_islam',
       'md._abdul_halim',
       'md_enayet_ullah',
       'md._shawkat_ali',
       'md._keramat_ali',
       'md._rahamat_ali',
       'md._abdul_odud',
       'md._nurul_huda',
       'md._abul_kalam',
       'md._nobi_newaz',
       'md_jais_sarday',
       'md_rawi_mahmud',
       'md._yunus_khan',
       'md._ruhul_amin',
       'md_afaque_alam',
       'md._wali_ullah',
       'md_saiful_alam',
       'md._sadek_khan',
       'md._ramjan_ali',
       'md_muhsin_alam',
       'md_abul_hashem',
       'md._mahbub_ali',
       'md_saad_uddin',
       'md_korban_ali',
       'md_abdur_rouf',
       'md._abu_zahir',
       'md._ali_azgar',
       'md._a._khaleq',
       'md._abdur_rob',
       'md._abdul_hai',
       'md._abu_bakar',
       'md_sirat_abu',
       'md_isa_sabu'],
 'a': ['mdala_game_reserve'],
 'g': ['mdg_achievement_fund'],
 'i': ['mdi_biological_laboratory', 'mdina_knights_f.c.'],
 'l': ['mdl_information_systems'],
 'm': ['mdm_mdm-1_fox'],
 'n': ['mdn_web_docs'],
 'p': ['mdp_youth_wing'],
 'r': ['mdr-nudix_rna_motif'],
 'w': ['mdw_heavyweight_championship']}
