
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mk = {'_': ['mk13-class_missile_boat',
       'mk_ranjitsinh_jhala',
       'mk44_bushmaster_ii',
       'mk_preshow_shimray',
       'mk_alam_chowdhury',
       'mk_postcode_area',
       'mk_105_hotpoint',
       'mk_fintel_wind',
       'mk_214a_cannon',
       'mk_lions_arena',
       'mk_115_cannon',
       'mk_101_cannon',
       'mk_108_cannon',
       'mk_103_cannon',
       'mk_47_striker',
       'mk_iii_helmet',
       'mk_2_grenade',
       'mk_1_grenade',
       'mk_land_f.c.',
       'mk_iv_helmet',
       'mk_13_rifle',
       'mk_101_lulu',
       'mk._iii_lcu',
       'mk_7_helmet',
       'mk_f3_155mm',
       'mk_6_helmet',
       'mk._iv_lcu',
       'mk_ii_fpa',
       'mk_7_mine'],
 'a': ['mkansa,_taounate_province'],
 'f': ['mkfc_stockholm_college'],
 'h': ['mkhambathini_local_municipality',
       'mkhondo_local_municipality',
       'mkhambathi_nature_reserve',
       'mkhombo_nature_reserve',
       'mkhaya_game_reserve'],
 'm': ['mkm_educational_trust'],
 'o': ['mkombozi_commercial_bank',
       'mkoba_teachers_college',
       'mkomazi_national_park',
       'mko_abiola_stadium',
       'mko_abiola_statue',
       'mkondo_wa_simiti',
       'mko_abiola_park'],
 'p': ['mkp_pogon_siedlce'],
 's': ['mks_dabrowa_gornicza', 'mks_bedzin_squads', 'mks_180_frigate'],
 'u': ['mkulazi_holding_company', 'mkuju_river_mine', 'mkuki_na_nyota'],
 'v': ['mkvv_international_vidyalaya']}
