
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dp = {'_': ['dp_architects',
       'dp_mukerji',
       'dp_leonis',
       'dp_world',
       'dp_cell',
       'dp_code',
       'dp_7'],
 'a': ['dpa_microphones'],
 'b': ['dpbs', 'dpb'],
 'c': ['dpcch', 'dpcp', 'dpca', 'dpc'],
 'd': ['dpd_scan'],
 'e': ['dpephos', 'dpe'],
 'f': ['dpf1', 'dpf2', 'dpf'],
 'g': ['dpg_media'],
 'h': ['dphm-rs', 'dph5', 'dphs', 'dph1', 'dphp', 'dph'],
 'i': ['dpi-3290', 'dpi-287', 'dpi-221', 'dpir', 'dpie', 'dpia', 'dpi'],
 'k': ['dpkg', 'dpk'],
 'l': ['dpll_algorithm', 'dpl_inc.'],
 'm': ['dpmm_fc'],
 'n': ['dpnh-ubiquinone_reductase'],
 'o': ['dpon-chen', 'dpo'],
 'p': ['dpp10',
       'dppa3',
       'dpp7',
       'dppc',
       'dpp8',
       'dpp9',
       'dppx',
       'dpp3',
       'dppe',
       'dpp6',
       'dpp1',
       'dpph',
       'dppa',
       'dpp'],
 'r': ['dpr_construction', 'dprk_today', 'dpr_live'],
 's': ['dps_academy', 'dps_barra'],
 't': ['dpt-hib_vaccine', 'dpt_vaccine'],
 'u': ['dpubs', 'dpu'],
 'v': ['dpvweb', 'dpvat', 'dpv'],
 'w': ['dpw'],
 'y': ['dpy19l2', 'dpysl4', 'dpysl2', 'dpysl5', 'dpysl3', 'dpys'],
 'z': ['dpz_codesign']}
