
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dn = {'_': ['dn_geminorum',
       'dn160822_03',
       'dn-v_bufalo',
       'dn_capital',
       'dn_orionis',
       'dn_factor'],
 'a': ['dna-formamidopyrimidine_glycosylase',
       'dna-binding_metallo-intercalators',
       'dna-3-methyladenine_glycosylase',
       'dna_alpha-glucosyltransferase',
       'dna-deoxyinosine_glycosylase',
       'dna_beta-glucosyltransferase',
       'dna-dna_hybridization',
       'dna_methyltransferase',
       'dna-dependent_atpase',
       'dna-binding_protein',
       'dna-binding_domain',
       'dna_nanotechnology',
       'dna_re-replication',
       'dna_fragmentation',
       'dna_demethylation',
       'dna_teleportation',
       'dna_recombination',
       'dnaprint_genomics',
       'dna_condensation',
       'dna_publications',
       'dna_footprinting',
       'dna_phenotyping',
       'dna_glycosylase',
       'dna_productions',
       'dna_inscription',
       'dna_methylation',
       'dna_replication',
       'dnata_singapore',
       'dna_encryption',
       'dna_sequencing',
       'dna_bioscience',
       'dna_extraction',
       'dna_annotation',
       'dna_polymerase',
       'dna_microarray',
       'dna_photolyase',
       'dna_transposon',
       'dna_laddering',
       'dna_shuffling',
       'dna_solutions',
       'dna_supercoil',
       'dna_construct',
       'dnab_helicase',
       'dna_barcoding',
       'dna_sequencer',
       'dna_profiling',
       'dna_computing',
       'dna_disruptor',
       'dna_oxidation',
       'dna_synthesis',
       'dna_research',
       'dna_genetics',
       'dna_database',
       'dna_analyzer',
       'dna_spiking',
       'dna_marking',
       'dna_machine',
       'dna_origami',
       'dna_vaccine',
       'dna_ligase',
       'dna_gyrase',
       'dna_walker',
       'dna_motors',
       'dna_lounge',
       'dna_repair',
       'dna_adduct',
       'dna_tower',
       'dna_songs',
       'dna_films',
       'dna_virus',
       'dna_clamp',
       'dnata_uk',
       'dna_bank',
       'dna_day',
       'dna_oyj'],
 'b': ['dnb_arena', 'dnb_nord', 'dnb_asa'],
 'c': ['dnce_discography'],
 'd': ['dnd-kmp_expressway', 'dnd_flyway'],
 'e': ['dnepropetrovsk_maniacs',
       'dnepropetrovsk_sputnik',
       'dnestrovskiye_melodii',
       'dnestrovskaya_pravda',
       'dneprovsky_uyezd',
       'dnevni_telegraf',
       'dnevni_rituali',
       'dnevne_novine',
       'dnestr_radar',
       'dnevni_list',
       'dnevnik_hrt',
       'dnevni_avaz',
       'dnevnik_mrt',
       'dnepr_m-72'],
 'f': ['dnf'],
 'g': ['dngrfld', 'dng'],
 'h': ['dnhs', 'dnh'],
 'i': ['dnieper-carpathian_offensive',
       'dnieper-donets_culture',
       'dnipropetrovsk_oblast',
       'dnipropetrovsk_mafia',
       'dniprovskyi_district',
       'dnieper-donets_rift',
       'dniester_sanatorium',
       'dnieper-bug_estuary',
       'dnipro_polytechnic',
       'dnistrovskyi_raion',
       'dnipro-1_regiment',
       'dnieper_reservoir',
       'dnieper-bug_canal',
       'dnieper_flotilla',
       'dniester_estuary',
       'dniprova_chayka',
       'dnieper_ukraine',
       'dnieper_lowland',
       'dnieper_estuary',
       'dniester_canyon',
       'dnieper_rapids',
       'dnieper_upland',
       'dnieper_barbel',
       'dnipro_kherson',
       'dniester_hills',
       'dniepr_balts',
       'dnipro_metro',
       'dnipro_choir',
       'dnipro_raion',
       'dnieper_chub',
       'dni_wiatru'],
 'k': ['dnk'],
 'l': ['dnl'],
 'm': ['dnmt3b', 'dnmt3l', 'dnmt1', 'dnm1l', 'dnm1', 'dnm3', 'dnm2', 'dnm'],
 'n': ['dnn_corporation'],
 'o': ['dnovsky_district', 'dno_asa'],
 'p': ['dnpep', 'dnpo', 'dnp3', 'dnp'],
 'q': ['dnqx', 'dnq'],
 'r': ['dnrc', 'dnr'],
 's': ['dns_rebinding',
       'dns_analytics',
       'dns_hijacking',
       'dns_prevalje',
       'dns_sinkhole',
       'dns_spoofing',
       'dns_blocking',
       'dns_belgium',
       'dns.com_llc',
       'dnss_point',
       'dns_flood',
       'dns_zavrc',
       'dns_leak',
       'dns_zone'],
 't': ['dnttip2', 'dntv2', 'dntel', 'dnt'],
 'u': ['dnu_huntrakul'],
 'v': ['dnvgl-st-e271', 'dnv'],
 'w': ['dnw'],
 'x': ['dnxhr_codec'],
 'y': ['dnyaneshwar_vidyapeeth',
       'dnyanada_ramtirthkar',
       'dnyaneshwar_agashe',
       'dnyaneshwar_patil',
       'dnyanraj_chougule',
       'dnyaneshwar_mulay',
       'dnyanganga_river',
       'dnyanesh_maharao'],
 'z': ['dnz']}
