
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ii = {'_': ['ii-vi_incorporated',
       'ii-v-i_progression',
       'ii._documenta',
       'ii_riigikogu',
       'ii._ddr-liga',
       'ii_naomitsu',
       'ii_naoyoshi',
       'ii,_finland',
       'ii_naochika',
       'ii_naokatsu',
       'ii_kultepe',
       'ii_naomasa',
       'ii_naotaka',
       'ii_naonori',
       'ii_naomori',
       'ii_naosuke',
       'ii_naotora',
       'ii_naomune',
       'ii_station',
       'ii_kurashi',
       'ii_naohira',
       'ii_pegasi',
       'ii_liiga',
       'ii_trill',
       'ii_corps',
       'ii_liga',
       'ii_lupi',
       'ii_clan',
       'ii_lyga',
       'ii_taso',
       'ii_tru'],
 'a': ['iiab_meteorites', 'iia,_estonia'],
 'b': ['iibc_championships', 'iibama_station', 'iibt_vietnam'],
 'c': ['iichiro_hatoyama'],
 'd': ['iidamachi_station',
       'iidabashi_station',
       'iidaoka_station',
       'iide,_yamagata',
       'iida_yoshitake',
       'iida_vemmelpuu',
       'iide_mountains',
       'iide,_estonia',
       'iida_station',
       'iida,_nagano',
       'iida_domain',
       'iidle_elmi',
       'iida_choko',
       'iida_line'],
 'e': ['iiest,_shibpur', 'iie_sumirat'],
 'f': ['iifa_utsavam', 'iifl_wealth'],
 'g': ['iigura_station', 'iig_meteorite', 'iig_capital'],
 'h': ['iihongo', 'iihl', 'iih'],
 'i': ['iii_internatsional',
       'iii._hornspitze',
       'iiicd_meteorite',
       'iii-vs_review',
       'iii_riigikogu',
       'iii_records',
       'iii_icecrin',
       'iii_wishes',
       'iii_corps',
       'iiit_pune',
       'iii_liiga',
       'iii_liga',
       'iii_lyga',
       'iii_ep'],
 'j': ['iijima_station', 'iijima,_nagano'],
 'k': ['iikka_keranen', 'iikka_heino', 'iikka_kivi'],
 'l': ['iilm_university',
       'iilish_ross',
       'iil_is-10',
       'iil_is-12',
       'iil_is-11',
       'iil_is-9',
       'iil_is-5',
       'iil_is-4',
       'iil_is-8',
       'iil_is-7'],
 'm': ['iimoriyama_castle',
       'iimori,_nagasaki',
       'iimura_takahiko',
       'iimt_university',
       'iimori_station',
       'iimani_david',
       'iimori_hill',
       'iim_alumni'],
 'n': ['iindman_discography',
       'iinari!_aibure-shon',
       'iinuma_sadakichi',
       'iinoura_station',
       'iino_hachimangu',
       'iino,_fukushima',
       'iinuma_yokusai',
       'iina_kuustonen',
       'iinuma_station',
       'iinan,_shimane',
       'iino_domain',
       'iino_castle',
       'iina_soiri',
       'iinan,_mie',
       'iina_salmi'],
 'o': ['iio_tsuratatsu',
       'iioka_station',
       'iio_noritsura',
       'iioka,_chiba',
       'iiona_zador'],
 'p': ['iipumbu_shiimi'],
 'r': ['iiro_pakarinen',
       'iiro_seppanen',
       'iiris_suomela',
       'iiro_viinanen',
       'iiro_jarvinen',
       'iiro_sopanen',
       'iiro_rantala',
       'iiro_tarkki',
       'iiro_luoto',
       'iiro_vanha',
       'iiro_aalto',
       'iiro_jarvi',
       'iira_soni'],
 's': ['iisalmen_maalaiskunta',
       'iisalmen_peli-karhut',
       'iisalmi_airfield',
       'iisakki_nikkola',
       'iisakki_hoikka',
       'iis_university',
       'iisak_myllari',
       'iisaku_parish',
       'iisang_dagat',
       'iis_metabase',
       'iis_dahlia',
       'iis_shahin'],
 't': ['iitate,_fukushima',
       'iit_krishnamurthy',
       'iitaka_dimension',
       'iitagawa,_akita',
       'iit_gandhinagar',
       'iit_bhubaneswar',
       'iit_kharagpur',
       'iit_hyderabad',
       'iit_tirupati',
       'iit_guwahati',
       'iit_palakkad',
       'iit_roorkee',
       'iitaka,_mie',
       'iit_jodhpur',
       'iit_council',
       'iit_dharwad',
       'iit_flyover',
       'iit_bhilai',
       'iit_madras',
       'iit_kanpur',
       'iit_indore',
       'iit_bombay',
       'iit_madrid',
       'iit_jammu',
       'iit_patna',
       'iit_delhi',
       'iit_mandi',
       'iit_ropar',
       'iit_goa'],
 'u': ['iiui_schools'],
 'v': ['iivari_malmikoski',
       'iivari_kyykoski',
       'iivari_partanen',
       'iivar_vaananen',
       'iivo_hokkanen',
       'iivari_yrjola',
       'iivo_niskanen',
       'iivari_rotko',
       'iivo_ahava',
       'iivo_nei'],
 'w': ['iiwake_maybe'],
 'x': ['iix'],
 'y': ['iiyama_station',
       'iiyama,_nagano',
       'iiyama_kannon',
       'iiyama_domain',
       'iiyama_castle',
       'iiyama_line'],
 'z': ['iizaka,_fukushima',
       'iizuka_shokansai',
       'iizuka,_fukuoka',
       'iizuka_station',
       'iizume_station',
       'iizzwa_medina',
       'iizasa_ienao',
       'iizaka_onsen']}
