
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_q_ = {'_': ['q2343-bx418',
       'q0906+6930',
       'q15x25',
       'q.931',
       'q4000',
       'q112',
       'q500',
       'q111',
       'q113',
       'q106',
       'q150',
       'q100',
       'q107',
       'q102',
       'q103',
       'q101',
       'q114',
       'q110',
       'q300',
       'q104',
       'q95',
       'q87',
       'q49',
       'q50',
       'q55',
       'q47',
       'q98',
       'q45',
       'q38',
       'q68',
       'q22',
       'q72',
       'q13',
       'q30',
       'q40',
       'q17',
       'q69',
       'q94',
       'q25',
       'q10',
       'q99',
       'q31',
       'q16',
       'q32',
       'q12',
       'q60',
       'q41',
       'q35',
       'q11',
       'q70',
       'q42',
       'q53',
       'q65',
       'q96',
       'q61',
       'q92'],
 'a': ['q-analysis',
       "q'asaqucha",
       "q'anjob'al",
       "q'atawini",
       "q'aysiri",
       'q-analog',
       "q'axilu",
       "q'asiri",
       "q'ari",
       'q+a',
       'q3a',
       'q&a'],
 'b': ['q@bizd@r@', 'q-ball', 'q*bert', 'q-bus', 'q-be', 'q2b'],
 'c': ['q-construction', 'q-commerce', 'q-chem', 'q@cr@s', 'q-cert'],
 'd': ['q@dim@likqislaq',
       'q-derivative',
       'q@dimk@nd',
       'q-dance',
       'q@dirli',
       'q@dili',
       'q-d-s'],
 'e': ['q-exponential', "q'eqchi'", 'q.e.d.', "q'ero"],
 'f': ['q-function',
       'q@f@rli',
       'q-force',
       'q-flex',
       'q-feel',
       'q-free',
       'q-fish'],
 'g': ['q-guidance', 'q-games', 'q-go'],
 'h': ['q@hr@manb@yli', 'q@hr@manli'],
 'i': ["q'illuqucha",
       "q'illumayu",
       "q'isanani",
       'q-in-law',
       "q'iwiri",
       "q'ilani",
       "q'illu"],
 'k': ['q-ko-chan', 'q2k'],
 'l': ['q-learning', 'q@l@duz', 'q@l@bin', 'q@l@gah', 'q-less', 'q-lan'],
 'm': ['q-machine', 'q-matrix', 'q@m@rvan', 'q-max'],
 'n': ['q@nid@r@', 'q-notes', 'q-net'],
 'o': ['q4os'],
 'p': ['q-productions',
       'q-principle',
       'q-plate',
       'q-pace',
       'q-park',
       'q-pit',
       'q-pop'],
 'r': ['q@riblik',
       'q@ribl@r',
       'q@ribli',
       'q@rs@l@',
       'q@rv@nd',
       'q@rch@',
       'q@r@h',
       'q@r@r'],
 's': ['q-statistic',
       'q-switching',
       'q-systems',
       'q-squared',
       'q-symbio',
       'q-sensei',
       'q-slope',
       'q-ship',
       'q@s@d',
       'q@sil'],
 't': ['q-telecom', 'q.t.v.', 'q-tex', 'q-tee'],
 'u': ["q'uq'umatz",
       'q.u.e.e.n.',
       "q'ullq'uni",
       "q'umarkaj",
       "q'urawiri",
       'q.u.b.e.',
       'q-unique',
       "q'ursha"],
 'v': ['q-vectors', 'q@voy'],
 'w': ['q-workshop', 'q-warrior'],
 'y': ['q-york'],
 'z': ['q@zvinoba', 'q@zli', 'q-zar']}
