
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mw = {'a': ['mwaluganje_elephant_sanctuary',
       'mwanza_international_school',
       'mwalimu_nyerere_foundation',
       'mwadinomho_combined_school',
       'mwalimu_nyerere_university',
       'mwabvi_wildlife_reserve',
       'mwajuma_hassan_khamis',
       'mwagna_national_park',
       'mwachirunje_ya_pwani',
       'mwanedi_game_reserve',
       'mwadini_abbas_jecha',
       'mwaura_isaac_maigua',
       'mwana_bute_kasongo',
       'mwatabu_s._okantah',
       'mwana_africa_f.c.',
       'mwansa_the_great',
       'mwangi_wa_iria'],
 'b': ['mwb_group_holdings'],
 'e': ['mwenge_catholic_university',
       'mweshipandeka_high_school',
       'mwene_chitengi_chiyengele',
       'mwea_national_reserve',
       'mwela_rock_paintings',
       'mwembeshi_shear_zone',
       'mwele_ntuli_malecela',
       'mwenga_power_station',
       'mwesa_isaiah_mapoma',
       'mwe_pon_kan'],
 'f': ['mwf_heavyweight_championship'],
 'i': ['mwingi_central_constituency',
       'mwingi_south_constituency',
       'mwingi_north_constituency',
       'mwingi_west_constituency',
       'mwine_mpaka_rwamirama',
       'mwi_veterinary_supply',
       'mwingi_water_project'],
 'm': ['mwm_international_motores']}
