
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-08-19T11:32:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad8bf5fdfd7b5a0e1143da1b6893e148b5e6a2db",
 "version": "2.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
