
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gt = {'_': ['gt-power',
       'gt-76',
       'gt198',
       'gt500',
       'gt200',
       'gt300',
       'gt.m',
       'gt2',
       'gt5',
       'gt3',
       'gt1',
       'gt4'],
 'a': ['gtashen', 'gtaa', 'gtap', 'gta'],
 'b': ['gtb'],
 'c': ['gtcr', 'gtcs', 'gtc'],
 'd': ['gtd'],
 'e': ['gtexpress', 'gteter', 'gtech', 'gte'],
 'f': ['gtf2ird1',
       'gtf2a1l',
       'gtf3c4',
       'gtf2f2',
       'gtf2h2',
       'gtf3c1',
       'gtf2e1',
       'gtf2h4',
       'gtf2f1',
       'gtf3c5',
       'gtf3c2',
       'gtf2h5',
       'gtf2a1',
       'gtf2e2',
       'gtf2h1',
       'gtf3a',
       'gtf2i',
       'gtfo',
       'gtfc',
       'gtfm',
       'gtf'],
 'g': ['gtg'],
 'h': ['gthumb', 'gth'],
 'i': ['gtichavank', 'gti'],
 'k': ['gtk-gnutella',
       'gtk-server',
       'gtk2-perl',
       'gtk-qt',
       'gtkpod',
       'gtkmm',
       'gtk'],
 'l': ['gtl'],
 'm': ['gtm'],
 'n': ['gtnw', 'gtn'],
 'o': ['gtopo30', 'gtool', 'gto'],
 'p': ['gtpgammas',
       'gtpase',
       'gtpbp3',
       'gtpbp4',
       'gtpbp1',
       'gtpbp6',
       "gtp'",
       'gtp'],
 'r': ['gtranslator', 'gtrans', 'gtr'],
 's': ['gts/bkn', 'gts-21', 'gtse1', 'gtsm', 'gts'],
 't': ['gtta', 'gtt'],
 'u': ['gtunnel', 'gtube', 'gtuit', 'gtu'],
 'v': ['gtv'],
 'w': ['gtwr', 'gtw'],
 'x': ['gtx-758', 'gtx1-15', 'gtx'],
 'y': ['gty']}
