
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_g_ = {'_': ['g2-structure',
       'g292.0+01.8',
       'g350.1-0.3',
       'g1.9+0.3',
       'g.722.1',
       'g.992.2',
       'g.651.1',
       'g.723.1',
       'g.992.4',
       'g.992.5',
       'g.729.1',
       'g.992.1',
       'g.992.3',
       'g.8261',
       'g.9972',
       'g.4/31',
       'g.9963',
       'g.8201',
       'g.9970',
       'g.723',
       'g.783',
       'g.718',
       'g.722',
       'g2000',
       'g.706',
       'g.729',
       'g-616',
       'g.711',
       'g.709',
       'g.984',
       'g.728',
       'g.655',
       'g.811',
       'g-130',
       'g.703',
       'g.165',
       'g.983',
       'g.719',
       'g.652',
       'g.726',
       'g.657',
       'g.988',
       'g101',
       'g103',
       'g104',
       'g600',
       'g500',
       'g400',
       'g100',
       'g112',
       'g102',
       'g111',
       'g18p',
       'g-14',
       'g105',
       'g200',
       'g8+5',
       'g700',
       'g109',
       'g107',
       'g418',
       'g106',
       'g60',
       'g14',
       'g17',
       'g41',
       'g34',
       'g16',
       'g59',
       'g18',
       'g39',
       'g20',
       'g19',
       'g50',
       'g77',
       'g44',
       'g23',
       'g33',
       'g25',
       'g31',
       'g27',
       'g12',
       'g24',
       'g36',
       'g13',
       'g32',
       'g29',
       'g72',
       'g38',
       'g63',
       'g40',
       'g42',
       'g99',
       'g95',
       'g70',
       'g49',
       'g21',
       'g10',
       'g11',
       'g37',
       'g65',
       'g26',
       'g28',
       'g22',
       'g55',
       'g90',
       'g98',
       'g35',
       'g45'],
 'a': ['g-amanitin',
       'g`azalkent',
       'g`allaorol',
       'g-algebra',
       'g.a.m.e.',
       'g-amado',
       'g-anime',
       'g-a-y',
       'g2a',
       'g&a'],
 'b': ['g.b.o.h.', 'g-book', 'g3bp1', 'g3bp2', 'g6b'],
 'c': ['g.communication',
       'g-convergence',
       'g-carotene',
       'g-cluster',
       'g-cloud',
       'g-code',
       'g.co'],
 'd': ['g@dikqislaq',
       'g@d@zeyxur',
       'g-dragon',
       'g.d.f.r.',
       'g-darius',
       'g-devith',
       'g@d@b@y',
       'g@dik',
       'g-day',
       "g'day",
       "g&d's",
       'g&d'],
 'e': ['g-expectation', 'g-eazy', 'g.e.m.'],
 'f': ['g-fibration',
       'g-function',
       'g-force',
       'g-fest',
       'g-flat',
       "g'five",
       'g.fast',
       'g-funk'],
 'g': ['g.g.f.h.', 'g@giran', 'g@g@li', 'g&g'],
 'h': ['g.h.e.t.t.o.u.t.', 'g.ho.st', 'g-host', 'g.hn'],
 'i': ['g`ijduvon', 'g.i.r.l.', 'g-index', 'g.i.t.', 'g.i.'],
 'j': ['g-jitter'],
 'k': ['g.kothapalli', 'g.k.singh', 'g.koduru', "g'kar"],
 'l': ['g.l.o.s.s.',
       'g@linqaya',
       'g@l@b@din',
       'g-loading',
       'g-league',
       'g-lader',
       'g.l.a.d',
       'g-land',
       'g:link',
       'g-loc',
       'g@lm@'],
 'm': ['g-measure',
       "g'market",
       'g-module',
       'g-market',
       'g-mobile',
       'g-mount',
       'g-music',
       'g-mode',
       'g-man',
       'g-mik',
       "g'mic"],
 'n': ['g-network',
       'g@nc@li',
       'g@ncl@r',
       'g@ndov',
       'g.nius',
       "g'nort",
       'g-nome',
       'g.na'],
 'o': ['g-octalactone',
       'g.o.o.t.m.u.',
       'g-oryzanol',
       'g`oliblar',
       'g.o.m.d.',
       'g`ozg`on',
       'g.o.r.a.',
       "g'ole!",
       'g.o.d'],
 'p': ['g-powered',
       'g-parity',
       'g-police',
       'g-phoria',
       'g-prior',
       'g*power',
       'g-power',
       'g6pc2',
       'g6pc3',
       'g6pc',
       'g.p.',
       'g3p',
       'g-p'],
 'q': ['g-quadruplex'],
 'r': ['g@rm@seyli',
       'g@rayb@yli',
       'g@rm@cataq',
       'g@rm@xana',
       'g@rm@tuk',
       'g@rsavan',
       'g@r@kli',
       'g@rg@r',
       'g-ring',
       'g@r@n@',
       'g.r.l.',
       'g-rex',
       'g.rev',
       'g@ray',
       'g&r',
       'g2r'],
 's': ['g-spectrum',
       'g-surfers',
       'g-saviour',
       'g3school',
       'g-string',
       'g-strain',
       'g-stoned',
       'g.skill',
       'g-space',
       'g-sides',
       'g-sharp',
       'g-slimm',
       'g-shock',
       'g-star',
       'g-spot',
       'g-side',
       'g-seat',
       'g.soul',
       'g-sale',
       'g-suit',
       'g0s2',
       'g&s',
       'g4s'],
 't': ['g-tocotrienol',
       'g-technology',
       'g-tocopherol',
       'g4techtv',
       'g&t-seq',
       'g-taste',
       'g-test',
       'g&t'],
 'u': ['g`uzor', 'g.u.y.', 'g-unit'],
 'v': ['g.vattigedda', "g'ville", 'g0v'],
 'w': ['g&w'],
 'y': ['g&y', 'g0y'],
 'z': ['g-zen', 'g2zt']}
