
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gd = {'_': ['gd-rom', 'gd-42', 'gd&r', 'gd2'],
 'a': ['gdakowo',
       'gdanski',
       'gdaniec',
       'gdansk',
       'gdana',
       'gdata',
       'gdap1',
       'gdal',
       'gda'],
 'b': ['gdbserver'],
 'c': ['gdcm', 'gdci', 'gdca', 'gdc'],
 'd': ['gdd'],
 'e': ['gdeszyn-kolonia', 'gdesklets', 'gdevelop', 'gdeszyn', 'gdes', 'gde'],
 'f': ['gdf10',
       'gdf11',
       'gdf15',
       'gdf6',
       'gdfr',
       'gdf2',
       'gdf1',
       'gdf7',
       'gdf5',
       'gdf3',
       'gdf'],
 'h': ['gdhs', 'gdh'],
 'i': ['gdiapers',
       'gdiesel',
       'gdiaper',
       'gdium',
       'gdinj',
       'gdi2',
       'gdi1',
       'gdi'],
 'j': ['gdjyb', 'gdj'],
 'k': ['gdk'],
 'l': ['gdleen', 'gdlr', 'gdl'],
 'm': ['gdm'],
 'n': ['gdn'],
 'o': ['gdochia', 'gdovka', 'gdola', 'gdov', 'gdor', 'gdow', 'gdos', 'gdo'],
 'p': ['gdp-glucosidase', 'gdpase'],
 'r': ['gdraymah', 'gdrn', 'gdrt', 'gdrc'],
 's': ['gdsii', 'gdsc', 'gds'],
 't': ['gdt'],
 'u': ['gdu'],
 'v': ['gdv'],
 'w': ['gdw'],
 'x': ['gdx'],
 'y': ['gdynia', 'gdyel', 'gdynk', 'gdym']}
