
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gs = {'_': ['gs-441524',
       'gs-39783',
       'gs-6620',
       'gs1-128',
       'gs-15',
       'gs25',
       'gs4',
       'gs2',
       'gs5',
       'gs1',
       'gs9'],
 'a': ['gsallkopf',
       'gsat-5p',
       'gsat-20',
       'gsat-6a',
       'gsat-10',
       'gsat-7a',
       'gsat-30',
       'gsat-31',
       'gsat-17',
       'gsat-14',
       'gsat-18',
       'gsat-7r',
       'gsat-15',
       'gsat-12',
       'gsat-16',
       'gsat-19',
       'gsat-29',
       'gsat-11',
       'gsat-2',
       'gsat-1',
       'gsat-3',
       'gsat-8',
       'gsat-4',
       'gsat-7',
       'gsas',
       'gsab',
       'gsat',
       'gsac',
       'gsa'],
 'b': ['gsb'],
 'c': ['gschwandtkopf',
       'gschnitzbach',
       'gschwandt',
       'gschnaidt',
       'gschnitz',
       'gschwend',
       'gschaid',
       'gscp',
       'gscc',
       'gsc'],
 'd': ['gsdmc', 'gsd&m', 'gsdmd', 'gsdmb', 'gsds', 'gsd'],
 'e': ['gsengetstein', 'gsell', 'gse1', 'gse'],
 'f': ['gsf'],
 'g': ['gsg2', 'gsg'],
 'h': ['gsh-18', 'gshhg', 'gshs', 'gsh'],
 'i': ['gsieser-tal-lauf', 'gsies', 'gsi3d', 'gsis', 'gsia', 'gsif', 'gsi'],
 'j': ['gsj'],
 'k': ['gsk1360707f',
       'gsk1016790a',
       'gsk1702934a',
       'gsk417651a',
       'gsk-189254',
       'gsk2881078',
       'gsk2831781',
       'gsk2606414',
       'gsk-4336a',
       'gsk-4112',
       'gsk3b',
       'gsk3a',
       'gsk-3',
       'gsk'],
 'l': ['gslis', 'gsli', 'gsl'],
 'm': ['gsmprjctdeg', 'gsm-r', 'gsmp', 'gsmr', 'gsmd', 'gsmc', 'gsma', 'gsm'],
 'n': ['gsn'],
 'o': ['gsoap', 'gsoc', 'gson', 'gso'],
 'p': ['gspaltenhorn', 'gspt2', 'gspt1', 'gspon', 'gspd', 'gspc', 'gsp'],
 'r': ['gsr'],
 's': ['gssha', 'gsse', 'gss'],
 't': ['gstellihorn',
       'gsteigwiler',
       'gstreamer',
       'gstarcad',
       'gstrein',
       'gstanzl',
       'gstaad',
       'gstock',
       'gstt1',
       'gstm4',
       'gsta4',
       'gsto2',
       'gstz1',
       'gsta2',
       'gstm2',
       'gstm3',
       'gstk1',
       'gstp1',
       'gsto1',
       'gsta3',
       'gstat',
       'gstt2',
       'gstn',
       'gst'],
 'u': ["gsung-'bum", 'gsur', 'gsu'],
 'v': ['gsv'],
 'w': ['gswr', 'gsw'],
 'x': ['gsx'],
 'y': ['gsy'],
 'z': ['gsz']}
