
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kq = {'_': ['kq-x'],
 'a': ['kqay-fm',
       'kqav',
       'kqam',
       'kqal',
       'kqaz',
       'kqad',
       'kqac',
       'kqaq',
       'kqak',
       'kqa'],
 'b': ['kqbu-fm',
       'kqbn',
       'kqbt',
       'kqbg',
       'kqbr',
       'kqbz',
       'kqbq',
       'kqba',
       'kqbb',
       'kqbm',
       'kqbo',
       'kqbk',
       'kqbu',
       'kqbl'],
 'c': ['kqcv-fm',
       'kqcr-fm',
       'kqct-lp',
       'kqcd-tv',
       'kqcw-dt',
       'kqcr',
       'kqco',
       'kqcj',
       'kqcs',
       'kqct',
       'kqcf',
       'kqca',
       'kqck',
       'kqcv',
       'kqch',
       'kqcl'],
 'd': ['kqdf-ld',
       'kqds-tv',
       'kqds-fm',
       'kqdj-fm',
       'kqdi-fm',
       'kqdk-cd',
       'kqdi',
       'kqds',
       'kqdr',
       'kqde',
       'kqdj',
       'kqdy'],
 'e': ['kqep-lp',
       'kqeg-cd',
       'kqed-fm',
       'kqev-lp',
       'kqen',
       'kqew',
       'kqeh',
       'kqeo',
       'kqez',
       'kqel',
       'kqed',
       'kqeg',
       'kqeq'],
 'f': ['kqfx-ld', 'kqfm', 'kqfe', 'kqfn', 'kqfo', 'kqfc', 'kqfx'],
 'g': ['kqgc'],
 'h': ['kqhu-lp', 'kqhw-ld', 'kqhk', 'kqht', 'kqhn', 'kqhe'],
 'i': ['kqid-fm',
       'kqix-lp',
       'kqik-fm',
       'kqip-lp',
       'kqiz-fm',
       'kqic',
       'kqiq',
       'kqie',
       'kqib',
       'kqik',
       'kqis'],
 'j': ['kqjk'],
 'k': ['kqki-fm',
       'kqkt-ld',
       'kqkq-fm',
       'kqks',
       'kqky',
       'kqkz',
       'kqkx',
       'kqkk',
       'kqkd',
       'kqkl'],
 'l': ['kqlv/kqri',
       'kqlx-fm',
       'kqlh-lp',
       'kqlt',
       'kqlb',
       'kqlo',
       'kqlf',
       'kqlk',
       'kqlc',
       'kqlv',
       'kqlm',
       'kqll',
       'kqla',
       'kqlx',
       'kqlz',
       'kql'],
 'm': ['kqml-ld',
       'kqmm-cd',
       'kqmq-fm',
       'kqmk-ld',
       'kqms',
       'kqmv',
       'kqmo',
       'kqmg',
       'kqma',
       'kqmr',
       'kqmx',
       'kqmt',
       'kqmc',
       'kqmb',
       'kqmy'],
 'n': ['kqng-fm',
       'kqnk-fm',
       'kqnm',
       'kqny',
       'kqna',
       'kqng',
       'kqnu',
       'kqnt',
       'kqnk'],
 'o': ['kqov-lp', 'kqob', 'kqol', 'kqod', 'kqor', 'kqoh'],
 'p': ['kqpt-lp',
       'kqps-ld',
       'kqpw-lp',
       'kqpr',
       'kqpi',
       'kqpn',
       'kqpw',
       'kqps',
       'kqpt',
       'kqpz',
       'kqpm'],
 'q': ['kqql', 'kqqq', 'kqqj', 'kqqn', 'kqqf', 'kqqz', 'kqqb', 'kqqk'],
 'r': ['kqrs-fm',
       'kqrz-lp',
       'kqre-ld',
       'kqrc-fm',
       'kqry-ld',
       'kqro-ld',
       'kqrp-lp',
       'kqrk',
       'kqrs',
       'kqrx',
       'kqra',
       'kqrq',
       'kqrv',
       'kqrt',
       'kqrr',
       'kqri',
       'kqrn',
       'kqry'],
 's': ['kqsm-fm',
       'kqso-lp',
       'kqsr',
       'kqsn',
       'kqsl',
       'kqsd',
       'kqsi',
       'kqsc',
       'kqss',
       'kqsf',
       'kqsk',
       'kqse',
       'kqsp',
       'kqsw',
       'kqst'],
 't': ['kqty-fm', 'kqtv', 'kqty', 'kqtm', 'kqte', 'kqta', 'kqtz'],
 'u': ['kqus-fm', 'kque-fm', 'kqueue', 'kqur', 'kqup', 'kqul', 'kque'],
 'v': ['kqve-ld', 'kqvt', 'kqv'],
 'w': ['kqwb-fm', 'kqwc-fm', 'kqwc', 'kqwb', 'kqw'],
 'x': ['kqxy-fm', 'kqxt-fm', 'kqxx-fm', 'kqxc-fm', 'kqxl-fm', 'kqxr', 'kqxf'],
 'y': ['kqyx', 'kqyb'],
 'z': ['kqzb', 'kqzz', 'kqzr', 'kqzq']}
