
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-23T15:26:11+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c9a05e8c39bca3ef3e9794b635bc8be656a369d",
 "version": "0.16.0a1.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
