
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-23T15:50:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "200df500f754e13cb90d277b272a09f866a26522",
 "version": "1.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
