
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oo = {'a': ['ooa_hela_natten'],
 'c': ['oocyte_maturation_inhibitor', 'oocl_hong_kong'],
 'd': ['oodua_peoples_congress',
       'ood-le-uk_the_wanderer',
       'oodi_oodi_uzhaikanum'],
 'g': ['oogonial_stem_cells', 'oog_and_blik', 'oog_in_al'],
 'h': ['ooh..._diese_ferien',
       'ooh_stick_you',
       'oohs_and_aahs',
       'ooh_las_vegas',
       'ooh!_my_soul',
       'ooh_la_la',
       'ooh_ja_ja',
       'ooh_i_do'],
 'i': ['ooij_en_persingen',
       'ooi_shee_keong',
       'ooi_teik_hock',
       'ooi_tze_liang',
       'ooi_hock_lim',
       'ooi_kee_beng',
       'ooi_hoe_guan',
       'ooi_boon_ewe',
       'ooi_kah_yan',
       'ooi_tze_min'],
 'k': ['ookini_arena_maishima', 'ooklah_the_moc'],
 'l': ['oolambeyan_national_park',
       'ooldea,_south_australia',
       'oolitic_aragonite_sand',
       'ooltewah_high_school',
       'oolithe_de_trouville'],
 'm': ['oom_yung_doe'],
 'n': ['oonch_neech_beech',
       'oona_a._hathaway',
       'oon_jin_teik',
       'oon_jin_gee',
       'oon_shu_an'],
 'o': ['ooo_baby_baby', 'ooops_a_desi'],
 'p': ['oops!_wrong_planet', "oop_bop_sh'bam", 'oops,_oh_no!'],
 'r': ['oorlogskloof_nature_reserve',
       'oormakale_vida_tharu',
       'oorukku_oru_pillai',
       'oorellam_un_pattu',
       'oortsog_ovoo_mine',
       'oorja_fuel_cells',
       'oorlog_en_vrede',
       'oort_no_kumo'],
 's': ['oosterheem_randstadrail_station',
       'oosterschelde_national_park',
       'ooshima_seishoen_sanatorium',
       'oosterbeek_railway_station',
       'oosterflank_metro_station',
       'oosterland,_north_holland',
       'oostburg_school_district',
       'oostende_railway_station',
       'oostplein_metro_station',
       'oostdijk,_south_holland',
       'oost-_en_west-souburg',
       'oost-_en_middelzwake',
       'oostburg_high_school'],
 't': ['oothukkadu_venkata_kavi',
       'ooty_municipal_market',
       'ootsa_lake_formation',
       'ooty_radio_telescope',
       'ooty_golf_course',
       'ooty_varai_uravu',
       'ooty_bus_stand',
       'oot_and_aboot'],
 'y': ['ooya-san_wa_shishunki!']}
