
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gt = {'_': ['gt-gyroplanes_kruza',
       'gt_bicycles',
       'gt_capital',
       'gt_academy',
       'gt25_live!',
       'gt_legends',
       'gt_racers',
       'gt_racing',
       'gt_nexus',
       'gt_racer',
       'gt_smith',
       'gt_tour',
       'gt_cube',
       'gt_dave',
       'gt_101'],
 'a': ["gta'_language",
       'gta_grizzlies',
       'gta_teleguam',
       'gta_mycar',
       'gta_gang'],
 'b': ['gtb'],
 'c': ['gtc_wireless'],
 'd': ['gtd-5_eax'],
 'e': ['gtech_corporation',
       'gte_mainstreet',
       'gte_financial',
       'gtel_zimbabwe',
       'gte_midwest'],
 'f': ['gtf2ird1',
       'gtf2a1l',
       'gtf3c4',
       'gtf2f2',
       'gtf2h2',
       'gtf3c1',
       'gtf2e1',
       'gtf2h4',
       'gtf2f1',
       'gtf3c5',
       'gtf3c2',
       'gtf2h5',
       'gtf2a1',
       'gtf2e2',
       'gtf2h1',
       'gtf3a',
       'gtf2i',
       'gtfo',
       'gtfc',
       'gtfm',
       'gtf'],
 'g': ['gtg'],
 'h': ['gthumb', 'gth'],
 'i': ['gti_mortsel', 'gti_club'],
 'k': ['gtk_gliwice'],
 'l': ['gtl_infrastructure', 'gtl_ltd'],
 'm': ['gtm_libra', 'gtm_rossa', 'gtm_coupe', 'gtm_cars', 'gtm_k3'],
 'n': ['gtnw', 'gtn'],
 'o': ['gto_records'],
 'p': ['gtp:gtp_guanylyltransferase',
       'gtpase-activating_protein',
       'gtp_diphosphokinase',
       'gtpr_gdynia'],
 'r': ['gtr_euroseries', 'gtr_evolution'],
 's': ['gts_finnjet'],
 't': ['gtt_communications'],
 'u': ['gtunnel', 'gtube', 'gtuit', 'gtu'],
 'v': ['gtv'],
 'w': ['gtw_72'],
 'x': ['gtx_incorporated'],
 'y': ['gty']}
