
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cc = {'_': ['cc-preferring_endodeoxyribonuclease',
       'cc-class_submarine',
       'cc_subdivision',
       'cc_slaughters',
       'cc_andromedae',
       'cc_sabathia',
       'cc_ortigia',
       'cc_cowboys',
       'cc-pp_game',
       'cc_clique',
       'cc_barber',
       'cc_system',
       'cc_cream',
       'cc_uche',
       'cc_vest',
       'cc_amfi',
       'cc_sig'],
 'a': ['ccaat-enhancer-binding_proteins',
       'ccarhuayo_district',
       'ccatca_district',
       'ccapi_district'],
 'b': ['ccb_brasil'],
 'c': ['cccf_championship',
       'cccb_publications',
       'ccc_polkowice',
       'ccc_shelter',
       'ccc_film'],
 'd': ['ccd_alberite', 'ccd_cerceda'],
 'e': ['ccella_ccella', 'cce_wakefield', 'cce_mc-1000'],
 'f': ['ccfl_inverter'],
 'g': ["ccgs_d'iberville",
       'ccgs_mamilossa',
       'ccgs_waban-aki',
       'ccgs_labrador',
       'ccgs_amundsen',
       'ccgs_bradbury',
       'ccgs_bartlett',
       'ccgs_westport',
       'ccgs_parizeau',
       'ccgs_griffon',
       'ccgs_matthew',
       'ccgs_revisor',
       'ccgs_goeland',
       'ccg_profiles',
       'ccgs_teleost',
       'ccgs_moytel',
       'ccgs_tuebor',
       'ccgs_cygnus',
       'ccgs_hudson',
       'ccgs_limnos',
       'ccgs_simcoe',
       'ccgs_vector',
       'ccgs_saurel',
       'ccgs_sambro',
       'ccgs_tupper',
       'ccgs_penac',
       'ccgs_siyay',
       'ccgs_brant',
       'ccgs_shark',
       'ccgs_kelso',
       'ccgs_tracy',
       'ccgs_vakta',
       'ccgs_sora',
       'ccgs_tanu'],
 'h': ['cch_canadian', 'cch_pounder'],
 'i': ['ccie_certification',
       'ccid_consulting',
       'ccia_building',
       'cci_phantom',
       'ccir_476'],
 'j': ['ccjshs', 'ccjs', 'ccj'],
 'k': ['cck-4', 'cckm', 'cck1', 'cck'],
 'l': ['ccl_industries'],
 'm': ['ccm_communications', 'ccm_magazine', 'ccmp_capital', 'ccm_mode'],
 'n': ['ccnb-peninsule_acadienne', 'ccn_protein', 'ccni_arauco', 'ccn_tv6'],
 'o': ['ccochaccasa_district', 'ccorca_district'],
 'p': ['ccp_records', 'ccp_games'],
 'r': ['ccrd_burinhosa', 'ccr_s.a.'],
 's': ['ccso_nameserver', 'ccsds_122.0-b-1', 'ccsp_tours'],
 't': ['cctv_international',
       'cctv_headquarters',
       'cctv-storm_music',
       'cctv_channels',
       'cctv_building',
       'cctv-9_news',
       'cctv_cities',
       'cctv_tower',
       'cctv_cup'],
 'u': ['ccu_delivery'],
 'v': ['ccvs', 'ccv'],
 'w': ['ccw'],
 'x': ['ccxtv', 'ccx'],
 'z': ['ccz']}
