
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_js = {'_': ['js_saint-pierroise',
       'js_vieux-habitants',
       'js_verlorenkost',
       'js_libreville',
       'js_poto-poto',
       'js_natsushio',
       'js_shimayuki',
       'js_suzutsuki',
       'js_mochishio',
       'js_shimokita',
       'js_shirayuki',
       'js_hatsuyuki',
       'js_matsuyuki',
       'js_michishio',
       'js_kinshasa',
       'js_yamagiri',
       'js_sawayuki',
       'js_takanami',
       'js_fuyushio',
       'js_harusame',
       'js_talangai',
       'js_setogiri',
       'js_antalaha',
       'js_pictures',
       'js_sazanami',
       'js_hamayuki',
       'js_sawagiri',
       'js_teruzuki',
       'js_haruyuki',
       'js_nichinan',
       'js_hayashio',
       'js_hercules',
       'js_ishikari',
       'js_setoyuki',
       'js_kurihama',
       'js_mineyuki',
       'js_fuyuzuki',
       'js_harushio',
       'js_yamayuki',
       'js_kairouan',
       'js_kirisame',
       'js_hamagiri',
       'js_shiranui',
       'js_makishio',
       'js_narushio',
       'js_murasame',
       'js_setoshio',
       'js_ashigara',
       'js_makinami',
       'js_kunisaki',
       'js_takashio',
       'js_suzunami',
       'js_rajkumar',
       'js_wakashio',
       'js_umigiri',
       'js_isoshio',
       'js_yaeshio',
       'js_amakusa',
       'js_kabylie',
       'js_chikuma',
       'js_isoyuki',
       'js_asagiri',
       'js_massira',
       'js_noshiro',
       'js_kashima',
       'js_shirane',
       'js_chihaya',
       'js_arashio',
       'js_hakugei',
       'js_uzushio',
       'js_clayden',
       'js_akizuki',
       'js_yubetsu',
       'js_asayuki',
       'js_abukuma',
       'js_oyashio',
       'js_amagiri',
       'js_academy',
       'js_jintsu',
       'js_yugiri',
       'js_genkai',
       'js_haruna',
       'js_kurobe',
       'js_mikuma',
       'js_haguro',
       'js_kumano',
       'js_traput',
       'js_kurama',
       'js_hiuchi',
       'js_saoura',
       'js_sendai',
       'js_menzah',
       'js_mogami',
       'js_hibiki',
       'js_djijel',
       'js_harima',
       'js_wakasa',
       'js_chokai',
       'js_yubari',
       'js_shonan',
       'js_futami',
       'js_tenryu',
       'js_chiao',
       'js_onami',
       'js_bungo',
       'js_myoko',
       'js_oyodo',
       'js_osumi',
       'js_uraga',
       'js_asahi',
       'js_izumo',
       'js_kongo',
       'js_atago',
       'js_enshu',
       'js_hyuga',
       'js_asuka',
       'js_7.62',
       'js_bank',
       'js_hiei',
       'js_kaga',
       'js_maya',
       'js_baco',
       'js_tone',
       'js_aki',
       'js_suo',
       'js_ise'],
 'a': ['jsat_corporation'],
 'b': ['jsb_competition'],
 'c': ['jsc_lokomotiv',
       'jsc_kuznetsov',
       'jsc_transmash',
       'jscript_.net',
       'jsc_star'],
 'd': ['jsd_partizan', 'jsd_band'],
 'e': ['jsem_moravan', 'jse_limited'],
 'f': ['jsfiddle', 'jsfuck', 'jsf'],
 'g': ['jsgf', 'jsgi', 'jsg'],
 'h': ['jshint', 'jshell', 'jsh'],
 'i': ['jsish', 'jsi'],
 'j': ['jsj_decomposition'],
 'k': ['jsk'],
 'l': ['jsl_romanization', 'jsl_s.a.', 'jsl_cup'],
 'm': ['jsm_cheraga', 'jsm_bejaia', 'jsm_skikda', 'jsm_tiaret'],
 'n': ['jsn'],
 'o': ['json_streaming', 'json_patch', 'json_feed'],
 'p': ['jsp_records'],
 'r': ['jsr_250', 'jsr_53'],
 's': ['jssl_singapore', 'jssg_uav'],
 't': ['jst_connector'],
 'u': ['jsu_garcia'],
 'v': ['jsv'],
 'w': ['jsw_cement', 'jsw_energy', 'jsw_group'],
 'x': ['jsx'],
 'y': ['jsyu_uav']}
