
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jj = {'_': ['jj_engelbrecht',
       'jj_electronic',
       'jj_christdoss',
       'jj_mccormack',
       'jj_scheepers',
       'jj_deveraux',
       'jj_hanrahan',
       'jj_eldridge',
       'jj_chalmers',
       'jj_donnelly',
       'jj_appleton',
       'jj_metcalf',
       'jj_hickson',
       'jj_ramberg',
       'jj_project',
       'jj_gilmour',
       'jj_stewart',
       'jj_urquiza',
       'jj_gagiano',
       'jj_lawhorn',
       'jj_collins',
       'jj_alfieri',
       'jj_aldrich',
       'jj_redick',
       'jj_levine',
       'jj_jegede',
       'jj_zhuang',
       'jj_heller',
       'jj_horner',
       'jj_hooper',
       'jj_waller',
       'jj_valaya',
       'jj_bunny',
       'jj_brine',
       'jj_adams',
       'jj_kotze',
       'jj_marsh',
       'jj_feild',
       'jj_smuts',
       'jj_jones',
       'jj_wilde',
       'jj_tonks',
       'jj_lehto',
       'jj_white',
       'jj_breet',
       'jj_fong',
       'jj_bird',
       'jj_smit',
       'jj_halo',
       'jj_doom',
       'jj_bola',
       'jj_babu',
       'jj_lin',
       'jj_jia'],
 'a': ['jjamppong', 'jjapaguri', 'jja'],
 'b': ['jjb_sports'],
 'c': ['jjc_skillz'],
 'f': ['jjf'],
 'g': ['jjg'],
 'h': ['jjhoom_india'],
 'i': ['jji_brothers'],
 'k': ['jjk_jyvaskyla'],
 'l': ['jjl'],
 'n': ['jjn'],
 'o': ['jjolmyeon', 'jjokbari', 'jjonak'],
 'p': ['jjp'],
 'r': ['jjr'],
 's': ['jjs'],
 'u': ['jju_language'],
 'y': ['jjy']}
