
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_td = {'_': ['td_securities',
       'td_waterhouse',
       'td_ameritrade',
       'td_banknorth',
       'td_ballpark',
       'td_station',
       'td_garden',
       'td_synnex',
       'td_arena',
       'td_daily',
       'td_tower',
       'td_place',
       'td_cruze'],
 'a': ['tda_armements'],
 'b': ['tdbzcholine', 'tdb'],
 'c': ['tdc_games'],
 'd': ['tddb', 'tdd'],
 'e': ['tdecu_stadium'],
 'f': ['tdf_group', 'tdf_ghar', 'tdf_1', 'tdf_2'],
 'g': ['tdg_limited'],
 'h': ['tdhs', 'tdh'],
 'i': ['tdindustries', 'tdiq', 'tdi'],
 'k': ['tdk_electronics', 'tdk_macassette', 'tdk_shinwakai'],
 'l': ['tdlr_5', 'tdlr_4'],
 'm': ['tdm-to-packet_conversion', 'tdm_bus'],
 'n': ['tdna', 'tdn'],
 'o': ['tdo_connector'],
 'p': ['tdp-4-oxo-6-deoxy-alpha-d-glucose-3,4-oxoisomerase', 'tdp1', 'tdp'],
 'r': ['tdr_targets', 'tdr_capital'],
 's': ['tds_metrocom', 'tds_telecom', 'tds_racing'],
 't': ['tdtv', 'tdt'],
 'u': ['tdu-12/b_skydart'],
 'v': ['tdv_2200'],
 'w': ['tdw'],
 'x': ['tdx_group'],
 'y': ['tdy']}
