
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gs = {'_': ['gs&wr_mcdonnell_2-4-0',
       'gs1_databar_coupon',
       'gs_apollon_smyrnis',
       'gs_agia_paraskevi',
       'gs_champions_park',
       'gs_alpha_subunit',
       'gs_curtis_stores',
       'gs&wr_class_400',
       'gs&wr_class_201',
       'gs&wr_class_333',
       'gs&wr_class_500',
       'gs&wr_class_900',
       'gs&wr_class_351',
       'gs&wr_class_368',
       'gs&wr_class_101',
       'gs&wr_class_301',
       'gs&wr_class_341',
       'gs&wr_class_362',
       'gs&wr_class_52',
       'gs&wr_class_21',
       'gs&wr_class_37',
       'gs&wr_class_47',
       'gs&wr_class_90',
       'gs&wr_class_33',
       'gs&wr_class_1',
       'gs&wr_class_2',
       'gs_caltex_cup'],
 'c': ['gsc_enterprises,_inc.', 'gschaid_bei_birkfeld', 'gsc_game_world'],
 'e': ['gse_composite_index'],
 'f': ['gsfc_complex_ina'],
 'h': ['gshg-7.62_machine_gun'],
 'i': ['gsis-meralco_bribery_case', "gsi_l'equipe_open"],
 'k': ['gsk3b_interacting_protein', 'gsk_china_scandal'],
 'l': ['gsl-class_berthing_pontoon', 'gsl-class_power_barge', 'gslv_mark_iii'],
 'm': ['gsm_interworking_profile', 'gsm_frequency_bands', 'gsm_cell_id'],
 'p': ['gsp_ariosto_ferrara'],
 'r': ['gsr_class_280',
       'gsr_class_495',
       'gsr_class_850',
       'gsr_class_670',
       'gsr_class_800',
       'gsr_class_700'],
 's': ['gsss_kot_beja'],
 't': ['gstaad_international_school',
       'gst_distribution_dispute',
       'gst_computer_systems',
       'gstadt_am_chiemsee',
       'gsteig_bei_gstaad'],
 'u': ['gsu_sports_arena']}
