
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dc = {'_': ['dc-community_access_network',
       'dc_kizhakemuri_foundation',
       'dc_rivals_hypercoaster',
       'dc_universe:_legacies',
       'dc_showcase:_catwoman',
       'dc_universe_all-stars',
       'dc_universe_presents',
       'dc_extended_universe',
       'dc101_chili_cook-off',
       'dc_universe_classics',
       'dc_comics_bombshells',
       'dc_injection_braking',
       'dc_animated_universe',
       'dc_universe_infinite',
       'dc_archive_editions',
       'dc_talk_discography',
       'dc_superheroes_cafe',
       'dc_showcase:_death',
       'dc_central_kitchen',
       'dc_universe_online',
       'dc_comics_presents',
       "dc's_young_animal",
       'dc_special_series',
       'dc_touchdown_club',
       'dc_nation_shorts',
       'dc_jazz_festival',
       'dc-10_air_tanker',
       'dc_graphic_novel',
       'dc_fashion_week',
       'dc3_music_group',
       'dc_mountain_lab',
       'dc_cosmic_cards',
       'dc_brau_brewing',
       'dc_health_link',
       'dc_super_stars',
       'dc_black_label',
       'dc_one_million',
       'dc_state_fair',
       'dc_vs._marvel',
       'dc_web_women',
       'dc_to_light'],
 'f': ['dcf_interframe_space'],
 'g': ['dcg_radio-tv_network'],
 'h': ['dcheira_el_jihadia'],
 'i': ['dci_global_partnerships', 'dci_cheese_company'],
 'p': ['dcp_midstream_partners'],
 'r': ['dcrrc_track_championships'],
 's': ['dcsmat_business_school', 'dcs_copy_protection'],
 'u': ["dcu_students'_union", 'dcu_ryan_academy']}
