
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vp = {'_': ['vp_records', 'vp_awards', 'vp_bank'],
 'a': ['vpat', 'vpa'],
 'b': ['vpb-139',
       'vpb-216',
       'vpb-109',
       'vpb-118',
       'vpb-215',
       'vpb-207',
       'vpb-149',
       'vpb-209',
       'vpb-112',
       'vpb-132',
       'vpb-137',
       'vpb-145',
       'vpb-210',
       'vpb-214',
       'vpb-125',
       'vpb-127',
       'vpb-150',
       'vpb-151',
       'vpb-110',
       'vpb-113',
       'vpb-134',
       'vpb-141',
       'vpb-202',
       'vpb-103',
       'vpb-105',
       'vpb-197',
       'vpb-200',
       'vpb-206',
       'vpb-100',
       'vpb-117',
       'vpb-211',
       'vpb-213',
       'vpb-147',
       'vpb-129',
       'vpb-198',
       'vpb-212',
       'vpb-203',
       'vpb-121',
       'vpb-126',
       'vpb-199',
       'vpb-45',
       'vpb-99',
       'vpb-16',
       'vpb-23',
       'vpb-44',
       'vpb-11',
       'vpb-29',
       'vpb-84',
       'vpb-18',
       'vpb-91',
       'vpb-54',
       'vpb-13',
       'vpb-52',
       'vpb-34',
       'vpb-61',
       'vpb-15',
       'vpb-43',
       'vpb-17',
       'vpb-20',
       'vpb-98',
       'vpb-24',
       'vpb-92',
       'vpb-33',
       'vpb-63',
       'vpb-94',
       'vpb-1',
       'vpb-4'],
 'c': ['vpc'],
 'd': ['vpd'],
 'e': ['vperyod', 'vpered', 'vpec-t', 'vpe'],
 'f': ['vpf'],
 'g': ['vpg'],
 'h': ['vphs', 'vph'],
 'i': ['vpi_industries'],
 'k': ['vpk-7829_bumerang', 'vpk-3927_volk'],
 'l': ['vpl_research', 'vplp_design'],
 'm': ['vpm-fm', 'vpmi', 'vpm'],
 'n': ['vpn_blocking', 'vpn_service'],
 'o': ['vpopmail', 'vpo'],
 'p': ['vpp'],
 'r': ['vpreb3', 'vpreb1', 'vprbp', 'vpro', 'vpr'],
 's': ['vps_convenience', 'vps_healthcare'],
 't': ['vpt'],
 'u': ['vpu_protein'],
 'v': ['vpv_purmersteijn'],
 'w': ['vpw-fm'],
 'x': ['vpx'],
 'y': ['vpython']}
