
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fy = {'a': ['fyataru', 'fyans', 'fyah', 'fyan', 'fya'],
 'b': ['fyb'],
 'c': ['fychan', 'fyc'],
 'e': ['fyers', 'fye'],
 'f': ['fyfield', 'fyffes', 'fyffe', 'fyfe'],
 'i': ['fyifv', 'fyi'],
 'j': ['fyj'],
 'k': ['fyksesund', 'fyk'],
 'l': ['fyllingenbergen',
       'fyllingsdalen',
       'fylkisvollur',
       'fylingthorpe',
       'fylingdales',
       'fylkingen',
       'fyldener',
       'fyllinge',
       'fyllida',
       'fylakio',
       'fyllean',
       'fylkir',
       'fylket',
       'fylgja',
       'fylfot',
       'fyllia',
       'fyllo',
       'fylde',
       'fyles',
       'fylax',
       'fyli'],
 'm': ['fym'],
 'n': ['fynbos', 'fynbo', 'fynch', 'fynes', 'fynn', 'fyn'],
 'o': ['fyodorovsky', 'fyodorovka', 'fyodorov', 'fyodor'],
 'p': ['fyp'],
 'r': ['fyrkantserien',
       'fyrtiotalism',
       'fyrisvellir',
       'fyresvatn',
       'fyresdal',
       'fyrudden',
       'fyrsjoen',
       'fyrishov',
       'fyrish',
       'fyrkat',
       'fyrde',
       'fyris',
       'fyrk',
       'fyre',
       'fyrd',
       'fyra',
       'fyr'],
 's': ['fyska', 'fysh', 'fys'],
 't': ['fyteies', 'fytche', 'fyti', 'fyta', 'fyt'],
 'u': ['fyulaba', 'fyutch', 'fyuse', 'fyu'],
 'v': ['fyvie', 'fyve'],
 'x': ['fyxation'],
 'z': ['fyzabad']}
