
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-23T09:35:00+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "90fc43e1ac539331adf4c106f91289303a153fb1",
 "version": "0.16.0a1.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
