
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-23T09:05:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a51ed0f04c8b82d5ef3c5a4f40fa8b6c87457d3",
 "version": "v1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
