
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hk = {'_': ['hk_ozolnieki/monarhs',
       'hk_zemgale/llu',
       'hk_kremenchuk',
       'hk_dinaburga',
       'hk_vojvodina',
       'hk_medvjedi',
       'hk_olimpija',
       'hk_partizan',
       'hk_4.6x30mm',
       'hk_lovosice',
       'hk_bardejov',
       'hk_magazine',
       'hk_jahorina',
       'hk_liepaja',
       'hk_ruzinov',
       'hk_kurbads',
       'hk_slavija',
       'hk_express',
       'hk_mogilev',
       'hk_sabinov',
       'hk_beostar',
       'hk_vitebsk',
       'hk_denmark',
       'hk_aquarii',
       'hk_sampion',
       'hk_kryvbas',
       'hk_beograd',
       'hk_martin',
       'hk_brezno',
       'hk_vukovi',
       'hk_trnava',
       'hk_kosice',
       'hk_poprad',
       'hk_94-100',
       'hk_levice',
       'hk_herulf',
       'hk_drott',
       'hk_vitez',
       'hk_rapid',
       'hk_tauri',
       'hk_celje',
       'hk_malmo',
       'hk_gomel',
       'hk_first',
       'hk_nitra',
       'hk_bosna',
       'hk_brest',
       'hk_lida',
       'hk_riga',
       'hk_alfa',
       'hk_cafe',
       'hk_mogo',
       'hk_tas'],
 'a': ['hkamti,_myanmar',
       'hkamti_district',
       'hkamti_township',
       'hkakabo_razi',
       'hkamti_long',
       'hkaru_bum',
       'hka_test'],
 'b': ['hkbp_crisis', 'hkbn_bbtv', 'hkb_600'],
 'c': ['hkchronicles', 'hkch', 'hkcs', 'hkcc'],
 'd': ['hkd_napredak'],
 'e': ['hkengnang'],
 'f': ['hkfs', 'hkfa'],
 'g': ['hkgolden50', 'hkgolden', 'hkg'],
 'h': ['hkhs', 'hkh'],
 'i': ['hkinchit', 'hkia', 'hkis', 'hki'],
 'k': ['hkk_brotnjo', 'hkk_posusje', 'hkk_siroki', 'hkk_grude'],
 'l': ['hkl'],
 'm': ['hkm_zvolen', 'hkmk_bled', 'hkm_sala'],
 'n': ['hkn,_inc.'],
 'o': ['hkonmaing',
       'hkonbyin',
       'hkodaung',
       'hko-nwe',
       'hkonsa',
       'hkomi',
       'hko'],
 'p': ['hkpa', 'hkpl', 'hkp'],
 'r': ['hkr_international'],
 's': ['hks,_inc.', 'hks_700e'],
 't': ['hktvmall', 'hkt48', 'hkt'],
 'u': ['hkusam_mountain', 'hkust_library', 'hku_station', 'hkun_law'],
 'w': ['hkw_chemnitz-nord']}
