
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nb = {'_': ['nb&m_railways', 'nb_ridaz.com', 'nb_global', 'nb_ridaz', 'nb_power'],
 'a': ['nba_entertainment',
       'nba_playgrounds',
       'nba_infocenter',
       'nba_wednesday',
       'nba_countdown',
       'nba_hangtime',
       'nba_showtime',
       'nba_showdown',
       'nba_shootout',
       'nba_specials',
       'nba_playoffs',
       'nba_tonight',
       'nba_stories',
       'nba_lockout',
       'nba_ballers',
       'nba_street',
       'nba_awards',
       'nba_finals',
       'nba_action',
       'nba_friday',
       'nba_brawl',
       'nba_fines',
       'nba_hoopz',
       'nba_scout',
       'nba_today',
       'nba_draft',
       'nba_store',
       'nba_2k22',
       'nba_2k11',
       'nba_2k12',
       'nba_2k19',
       'nba_2k10',
       'nba_slam',
       'nba_2k13',
       'nba_2k14',
       'nba_2k15',
       'nba_2k17',
       'nba_2k20',
       'nba_2k21',
       'nba_2k16',
       'nba_2k18',
       'nba_live',
       'nba_2k6',
       'nba_2k2',
       'nba_2k3',
       'nba_2k9',
       'nba_jam',
       'nba_2k1',
       'nba_2k7',
       'nba_cba',
       'nba_2k8',
       'nba_tv',
       'nba_07',
       'nba_08',
       'nba_2k',
       'nba_06'],
 'b': ['nbbl', 'nbbj', 'nbbi', 'nbbc', 'nbb'],
 'c': ['nbcuniversal_archives',
       'nbc_springfield',
       'nbc_sportstalk',
       'nbc_nightside',
       'nbc_orchestra',
       'nbc_rochester',
       'nbc_presents',
       'nbc_columbia',
       'nbc_bearings',
       'nbc_portland',
       'nbc_columbus',
       'nbc_station',
       'nbc_montana',
       'nbc_studios',
       'nbc_talknet',
       'nbc_daytime',
       'nbc_chimes',
       'nbc_albany',
       'nbc_sports',
       'nbc_europe',
       'nbc_austin',
       'nbc_tower',
       'nbc_news',
       'nbc_kids',
       'nbc_logo',
       'nbc_suit',
       'nbc_page',
       'nbc_out',
       'nbc_14',
       'nbc_39',
       'nbc_26',
       'nbc_12',
       'nbc_33',
       'nbc_36',
       'nbc_15',
       'nbc_23',
       'nbc_24',
       'nbc_13',
       'nbc_17',
       'nbc_11',
       'nbc_10',
       'nbc_16',
       'nbc_18',
       'nbc_21',
       'nbc_22',
       'nbc_25',
       'nbc_7',
       'nbc_8',
       'nbc_6',
       'nbc_3',
       'nbc_4',
       'nbc_2',
       'nbc_5',
       'nbc_9'],
 'd': ['nbd_television'],
 'e': ['nbeal2', 'nbeal1', 'nbeika', 'nbench', 'nbe'],
 'f': ['nbfa', 'nbfl', 'nbf'],
 'g': ['nbg'],
 'h': ['nbhs', 'nbhd', 'nbh'],
 'i': ['nbi_knowledgebase'],
 'k': ['nbk_capital', 'nbkc_bank', 'nbk_107'],
 'l': ['nbl1_central',
       'nbl1_awards',
       'nbl1_north',
       'nbl1_south',
       'nbl_finals',
       'nbl1_east',
       'nbl1_west',
       'nbl_cup',
       'nbl_tv'],
 'm': ['nbm_publishing'],
 'n': ['nbn-3_tournament',
       'nbnk_investments',
       'nbn_television',
       'nbn_news',
       'nbn_co'],
 'o': ['nbome-mescaline', 'nbo'],
 'p': ['nbp_f.c.'],
 'q': ['nbqx'],
 'r': ['nbr1', 'nbr2', 'nbr'],
 's': ['nbs_24/7', 'nbs_bank'],
 't': ['nbt_newsletter', 'nbt_bank', 'nbt_cup'],
 'u': ['nbu_osiyo'],
 'v': ['nbv'],
 'w': ['nbw'],
 'x': ['nbx'],
 'y': ['nby']}
