
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nz = {'_': ['nz_endeavour',
       'nz_gardener',
       'nz_skeptics',
       'nz_post',
       'nz_camp',
       'nz_bus',
       'nz_85b'],
 'a': ['nzakambay_language',
       'nzakara_language',
       'nzanyi_language',
       'nzambi_district',
       'nzadi_language',
       'nzamba_airport',
       'nzamba_kitonga',
       'nzanga_mobutu',
       'nzalat_laadam',
       'nzagi_airport',
       'nzambani_rock',
       'nzambi_matee',
       'nzara_county',
       'nzaeli_kyomo',
       'nzau_namsan',
       'nzante_spee',
       'nzappa_zap'],
 'b': ['nzb'],
 'c': ['nzca_lines'],
 'd': ['nzda'],
 'e': ['nzerekore_prefecture',
       'nzerekore_airport',
       'nzerekore_region',
       'nzebi_languages',
       'nzema_district',
       'nzema_language',
       'nzega_district',
       'nzema_people'],
 'f': ['nzf'],
 'g': ['nzgss_hinemoa', 'nzg_models'],
 'h': ['nzhdeh,_armenia', 'nzhelele_river', 'nzhelele_dam'],
 'i': ['nzingha_prescod',
       'nzingha_stewart',
       'nzime_language',
       'nzinga_blake',
       'nzime_people',
       'nzioka_waita',
       'nzi_river'],
 'j': ['nzj'],
 'l': ['nzl_82', 'nzl_92', 'nzl_32'],
 'm': ['nzms', 'nzmc', 'nzma'],
 'n': ['nznog'],
 'o': ['nzovu_airport',
       'nzo_ekangaki',
       'nzoia_river',
       'nzoro_river',
       'nzoia_barb'],
 'p': ['nzpwi_invitational'],
 'r': ['nzrb', 'nzra'],
 's': ['nzs_3604'],
 'u': ['nzuzi_toko'],
 'x': ['nzxt', 'nzx'],
 'z': ['nzz_mediengruppe', 'nzz_geschichte']}
