
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_df = {'_': ['df-1_protocol', 'df_concerts'],
 'a': ['dfa_minimization', 'dfa_records'],
 'b': ['dfb-pokal_frauen'],
 'c': ['dfcu_financial',
       'dfcu_group',
       'dfcu_house',
       'dfcu_bank',
       'dfcc_bank',
       'dfc_prag'],
 'd': ['dfds_seaways', 'dfdvd_ii'],
 'e': ['dfe'],
 'f': ['dffits', 'dffb', 'dffa', 'dff'],
 'g': ['dfg'],
 'h': ['dfh_network'],
 'i': ['dfine,_inc.', 'dfi_rivers', 'dfi_roads'],
 'j': ['dfj_frontier'],
 'k': ['dfk_dainava'],
 'l': ['dfl_television', 'dfl_foundation'],
 'm': ['dfm_engineering'],
 'n': ['dfnb31', 'dfny1', 'dfna5', 'dfn'],
 'o': ['dfoa', 'dfo'],
 'p': ['dfp'],
 'r': ['dfri', 'dfrf', 'dfr'],
 's': ['dfs_kopernikus-3',
       'dfsb_kollective',
       'dfs_rhonsperber',
       'dfs_kopernikus',
       'dfs_furniture',
       'dfsk_k-series',
       'dfsk_c-series',
       'dfs_seeadler',
       'dfs_habicht',
       'dfs_records',
       'dfs_zogling',
       'dfs_kranich',
       'dfs_reiher',
       'dfsk_motor',
       'dfs_group',
       'dfs_weihe',
       'dfs_230f',
       'dfs_194',
       'dfs_193',
       'dfs_346',
       'dfs_332',
       'dfs_228',
       'dfs_230',
       'dfs_331',
       'dfs_40'],
 't': ['dftba_records', 'dft_matrix', 'dft_team'],
 'u': ['dfu'],
 'v': ['dfv-supercup', 'dfv'],
 'w': ['dfw_tornados',
       'dfw_skylink',
       'dfw_c.iii',
       'dfw_r.iii',
       'dfw_mars',
       'dfw_dr.i',
       'dfw_floh',
       'dfw_r.ii',
       'dfw_d.i',
       'dfw_b.i',
       'dfw_c.i',
       'dfw_c.v',
       'dfw_r.i'],
 'x': ['dfx2', 'dfx'],
 'z': ['dfz']}
