
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dg = {'_': ['dg_international',
       'dg_flugzeugbau',
       'dg_cement',
       'dg_arena',
       'dg_tren',
       'dg_307'],
 'a': ["dga'-ldan", 'dgamer', 'dgali', 'dgat1', 'dgac', 'dga'],
 'b': ['dgbx'],
 'c': ['dgc_records'],
 'd': ['dgdg_synthase'],
 'e': ['dgenerate_films'],
 'f': ['dgfm_flamethrower', 'dgf_flensborg'],
 'g': ['dgg'],
 'h': ['dghwede_language', 'dghe_subregion'],
 'i': ['dgi-huset', 'dgi-byen', 'dgia', 'dgi'],
 'j': ['dgje', 'dgj'],
 'k': ['dgkz', 'dgkg', 'dgkb', 'dgkq', 'dgka', 'dgkd', 'dgk'],
 'l': ['dglucy', 'dgl'],
 'm': ['dgm_racing'],
 'n': ['dgn'],
 'o': ['dgo_jet'],
 'p': ['dgp_model'],
 'q': ['dgq-20'],
 'r': ['dgroups', 'dgr'],
 's': ['dgse_companies',
       'dgs_mastodon',
       'dgs_neptune',
       'dgs_quadra',
       'dgs_naden'],
 't': ['dgtpase', 'dgt'],
 'u': ['dgusa_untouchable', 'dgusa_fearless'],
 'w': ['dgwhyperloop', 'dgw'],
 'y': ['dgy'],
 'z': ['dgz']}
