
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dt = {'_': ['dt_virginis', 'dt_eightron', 'dt_carnage', 'dt_racer', 'dt_next'],
 'a': ['dtap-ipv-hepb_vaccine',
       'dtap-ipv/hib_vaccine',
       'dtap-ipv_vaccine',
       'dtap-hib_vaccine',
       'dtack_grounded',
       'dta_evolution',
       'dta_voyageur',
       'dta_dynamic',
       'dta_feeling',
       'dta_alizes',
       'dta_magic',
       'dta_combo',
       'dta_j-ro',
       'dta_diva',
       'dta_sarl'],
 'b': ['dtbook', 'dtb'],
 'c': ['dtcc', 'dtc'],
 'd': ['dtdp-dihydrostreptose--streptidine-6-phosphate_dihydrostreptosyltransferase',
       'dtdp-3-amino-3,4,6-trideoxy-alpha-d-glucopyranose_n,n-dimethyltransferase',
       'dtdp-3-amino-3,6-dideoxy-alpha-d-galactopyranose_n,n-dimethyltransferase',
       'dtdp-3-amino-3,6-dideoxy-alpha-d-glucopyranose_n,n-dimethyltransferase',
       'dtdp-3-amino-3,6-dideoxy-alpha-d-galactopyranose_3-n-acetyltransferase',
       'dtdp-3-amino-3,6-dideoxy-alpha-d-galactopyranose_transaminase',
       'dtdp-3-amino-3,6-dideoxy-alpha-d-glucopyranose_transaminase',
       'dtdp-4-amino-4,6-dideoxy-d-galactose_acyltransferase',
       'dtdp-4-amino-4,6-dideoxy-d-glucose_acyltransferase',
       'dtdp-4-amino-4,6-dideoxy-d-glucose_transaminase',
       'dtdp-4-amino-4,6-dideoxygalactose_transaminase',
       'dtdp-4-dehydro-6-deoxyglucose_reductase',
       'dtdp-6-deoxy-l-talose_4-dehydrogenase',
       'dtdp-4-dehydrorhamnose_3,5-epimerase',
       'dtdp-4-dehydrorhamnose_reductase',
       'dtdp-galactose_6-dehydrogenase',
       'dtdp-glucose_4,6-dehydratase',
       'dtdp-l-rhamnose_4-epimerase'],
 'e': ['dtek_academy', 'dte_energy'],
 'f': ['dtfc', 'dtf'],
 'g': ['dtg'],
 'h': ['dth'],
 'i': ['dti_data'],
 'j': ['dtj'],
 'k': ['dtk_computer'],
 'l': ['dtlogin', 'dtla'],
 'm': ['dtm_trophy'],
 'n': ['dtn'],
 'o': ['dtour', 'dtot', 'dtox', 'dto'],
 'p': ['dtp_entertainment', 'dtp-hepb_vaccine', 'dtp_artist'],
 'r': ['dtrace', 'dtr'],
 's': ['dtsearch', 'dtss', 'dtsa', 'dts'],
 't': ['dttx', 'dtt'],
 'u': ['dtu_roadrunners', 'dtu_diplom', 'dtu_space'],
 'v': ['dtv_verlagsgesellschaft', 'dtv_receiver', 'dtv_america', 'dtv_radio'],
 'w': ['dtwd1', 'dtwns'],
 'x': ['dtx2', 'dtxt', 'dtx1', 'dtx'],
 'y': ['dtymk', 'dty'],
 'z': ['dtz']}
