
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_w_ = {'_': ['w8_wellingborough-bozeat',
       'w-19-class_minesweeper',
       'w-13-class_minesweeper',
       'w-1-class_minesweeper',
       'w._wickremasinghe',
       'w._selvamurthy',
       'w._lafontaine',
       'w._floribunda',
       'w._morrissey',
       'w._flitcroft',
       'w._pudupatti',
       'w._hanselman',
       'w._wilkinson',
       'w._poeppigii',
       'w._blackwell',
       'w._robertson',
       'w._patterson',
       'w350_project',
       'w2_poppodium',
       'w._tinctoria',
       'w52-fc_porto',
       'w._gigantea',
       'w._japonica',
       'w._gracilis',
       'w._maculata',
       'w._browning',
       'w._griffith',
       'w._hamilton',
       'w._downwood',
       'w._jayasiri',
       'w._mitchell',
       'w._perkins',
       'w16_engine',
       'w._nesbitt',
       'w._forster',
       'w18_engine',
       'w._grandis',
       'w._wangyuh',
       'w12_engine',
       'w._edwards',
       'w._mcadam',
       'w11_opera',
       'w8_engine',
       'w._crocea',
       'w._smith',
       'w._adams',
       'w._frahm',
       'w,_here',
       'w._epps',
       'w._park',
       'w_101',
       'w_31'],
 'a': ['w-arly-pendjari_complex',
       'w.a.s.p._discography',
       'w.a.r._bf-109',
       'w.a.r._fw-190',
       'w.a._stewart',
       'w.a._lamborn',
       'w_andromedae',
       'w.a._barrows',
       'w.a.r._p40e',
       'w_aquilae',
       'w_amman',
       'w_abc'],
 'b': ['w.b._brydon', 'w_barcelona', 'w.b._mason', 'w_bangkok', 'w_band'],
 'c': ['w-class_destroyer',
       'w.c.h._grimmer',
       'w.c.w._murdoch',
       'w.c._dodson',
       'w.c._madden',
       'w_centauri',
       'w_channel',
       'w_carinae',
       'w_cephei',
       'w_crucis',
       'w_class',
       'w_corvi',
       'w_cygni',
       'w3c_mmi'],
 'd': ['w_django!'],
 'e': ['w.e.e._greene', 'w.e._noffke', 'w.e._powell', 'w_engine'],
 'g': ['w.g._vowles',
       'w&g_records',
       'w.g._archer',
       'w.g._liston',
       'w3g_marine'],
 'h': ['w.h.r.r._giedde',
       'w&h_dentalwerk',
       'w.h.c._folsom',
       'w.h._biney',
       'w_hotels',
       'w_hydrae'],
 'i': ['w-inds_discography', 'w*ing_alliance'],
 'j': ['w_jezioranach', 'w.j._kent', 'w_juliet'],
 'k': ['w.k._border'],
 'l': ['w.l._stevens', 'w!ld_rice', 'w/l_cave', 'w_line'],
 'm': ['w.m._mensah-wood', 'w_mitchell', 'w_motors', 'w_mensae'],
 'n': ['w_network'],
 'o': ['w.o.a_records',
       'w.o._saunders',
       'w.o.w._hall',
       'w.o._smith',
       'w_orionis',
       'w/o_ram'],
 'p': ['w&p_subdivision'],
 'r': ['w.r._pickering',
       'w.r.c._hall',
       'w.r._gunn',
       'w.r._mead',
       'w_radio',
       'w_road'],
 's': ['w_sagittarii',
       'w_serpentis',
       "w's_tragedy",
       'w.s._burke',
       'w.s._hull',
       'w_series',
       'w_state',
       'w_spann'],
 't': ['w_taipei'],
 'v': ['w_virginis', 'w_vision'],
 'w': ['w.w.s.1_salamandra',
       'w&w_discography',
       'w&w_subdivision',
       'w.w.s.3_delfin',
       'w.w.s.2_zaba',
       'w.w._grave',
       'w_wish'],
 'x': ['w2xcr',
       'w2xmn',
       'w8xwj',
       'w1xay',
       'w6xah',
       'w5xa',
       'w4xa',
       'w3xk',
       'w8xh',
       'w^x'],
 'z': ['w.z._fenyang']}
