
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ys = {'a': ['ysabel_valencia_house',
       'ysaye_maria_barnwell',
       'ysabel_de_tremblay',
       'ysabeau_s._wilce',
       'ysabel_del_valle'],
 'b': ['ysbyty_penrhos_stanley',
       'ysbyty_george_thomas',
       'ysbyty_aneurin_bevan',
       'ysbyty_ystrad_fawr',
       'ysbyty_cwm_rhondda',
       "ysbyty'r_tri_chwm",
       'ysbyty_cwm_cynon'],
 'e': ['yser_metro_station', 'yseult_le_danois', 'yses_2_b'],
 'g': ['ysgol_eifionydd,_porthmadog',
       'ysgol_gymraeg_aberystwyth',
       'ysgol_uwchradd_aberteifi',
       'ysgol_uwchradd_caergybi',
       'ysgol_uwchradd_bodedern',
       'ysgol_greenhill_school',
       'ysgol_gyfun_llangefni',
       'ysgol_gyfun_aberaeron',
       'ysgol_dyffryn_nantlle',
       'ysgol_penglais_school',
       'ysgol_gyfun_rhydywaun',
       'ysgol_gyfun_gwynllyw',
       'ysgol_uwchradd_tywyn',
       'ysgol_maesteg_school',
       'ysgol_dyffryn_conwy',
       'ysgol_henry_richard',
       'ysgol_dyffryn_ogwen',
       'ysgol_dyffryn_teifi',
       'ysgol_morgan_llwyd',
       'ysgol_dyffryn_aman',
       'ysgol_david_hughes',
       'ysgol_y_gwendraeth',
       'ysgol_bro_hyddgen',
       'ysgol_gyfun_emlyn',
       'ysgol_john_bright',
       'ysgol_bro_dinefwr',
       'ysgol_calon_cymru',
       'ysgol_maes_garmon',
       'ysgol_gyfun_gwyr',
       'ysgol_garth_olwg',
       'ysgol_bryn_elian',
       'ysgol_y_creuddyn',
       'ysgol_dinas_bran',
       'ysgol_glan_clwyd',
       'ysgol_bro_gwaun',
       'ysgol_dewi_sant',
       'ysgol_yr_hendre',
       'ysgol_bryn_alyn',
       'ysgol_bro_ddyfi',
       'ysgol_y_preseli',
       'ysgol_bro_pedr',
       'ysgol_y_strade',
       'ysgol_y_berwyn',
       'ysgol_y_gader'],
 'k': ['ysk_757_karimun'],
 'l': ['ysleta-zaragoza_international_bridge', 'ysleta_high_school'],
 'm': ['ysmael_steel_admirals', 'ysmael_r._villegas'],
 'r': ['ysr_sampoorna_poshana',
       'ysr_nethanna_nestham',
       'ysr_congress_party',
       'ysr_pension_kanuka',
       'ysr_indoor_stadium',
       'ysr_rythu_bharosa',
       'ysr_vahana_mitra',
       'ysr_kapu_nestham',
       'ysr_kanti_velugu',
       'ysr_sunna_vaddi'],
 't': ['ystradgynlais_community_hospital',
       'ystalyfera_transmitting_station',
       'ystradgynlais_railway_station',
       'ystalyfera_railway_station',
       'ystradowen_railway_station',
       'ystradyfodwg_school_board',
       'ystrad_mynach_hospital',
       'ystad_railway_station',
       'ystrad_mynach_college',
       'ystrad_rhondda_rfc'],
 'u': ['ysu_academic_challenge']}
