
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ln = {'_': ['ln_postcode_area'],
 'b': ['lnb_all-star_game', 'lnb_pro_b', 'lnb_pro_a'],
 'e': ['lner_electric_units',
       'lner_class_v1/v3',
       'lner_class_b17',
       'lner_class_d49',
       'lner_class_j39',
       'lner_class_d41',
       'lner_class_j64',
       'lner_class_y10',
       'lner_class_d40',
       'lner_class_j94',
       'lner_class_y11',
       'lner_class_j38',
       'lner_class_ee1',
       'lner_class_es1',
       'lner_class_u1',
       'lner_class_p2',
       'lner_class_o1',
       'lner_class_a4',
       'lner_class_a8',
       'lner_class_y1',
       'lner_class_a1',
       'lner_class_k5',
       'lner_class_k4',
       'lner_class_v4',
       'lner_class_o4',
       'lner_class_a2',
       'lner_class_b1',
       'lner_class_p1',
       'lner_class_q1',
       'lner_class_v2',
       'lner_class_w1',
       'lner_class_y3',
       'lner_class_b2',
       'lner_class_l1',
       'lner_class_o6'],
 'g': ['lng_storage_tank'],
 'h': ['lnh_division_1', 'lnh_division_2'],
 'o': ['lnozavod,_altai_krai'],
 'p': ['lnp_media_group'],
 't': ['lnt_rna_motif'],
 'v': ['lnv_ligue_a'],
 'w': ['lnwr_dreadnought_class',
       'lnwr_experiment_class',
       'lnwr_claughton_class',
       'lnwr_precedent_class',
       'lnwr_precursor_class',
       'lnwr_electric_units',
       'lnwr_teutonic_class',
       'lnwr_waterloo_class',
       'lnwr_bloomer_class',
       'lnwr_jubilee_class',
       'lnwr_newton_class',
       'lnwr_renown_class',
       'lnwr_samson_class',
       'lnwr_special_tank',
       'lnwr_4ft_shunter',
       'lnwr_1400_class',
       'lnwr_1185_class',
       'lnwr_dock_tank',
       'lnwr_class_g2a',
       'lnwr_380_class',
       'lnwr_class_c1',
       'lnwr_class_g2',
       'lnwr_class_g1',
       'lnwr_class_b',
       'lnwr_class_c',
       'lnwr_class_g',
       'lnwr_class_a',
       'lnwr_class_e',
       'lnwr_class_f',
       'lnwr_class_d']}
