
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vy = {'_': ['vy-le-ferroux',
       'vy-les-filain',
       'vy-les-lure',
       'vy-les-rupt',
       'vy-lo-fone',
       'vy2',
       'vy1'],
 'a': ['vyakhyaprajnapti',
       'vyachakurahalli',
       'vyaznovatovka',
       'vyazutinskaya',
       'vyacheslavka',
       'vyans-le-val',
       'vyasatirtha',
       'vyarheychyk',
       'vyaghrapada',
       'vyacheslav',
       'vyalikaval',
       'vyartsilya',
       'vyadhapura',
       'vyakaranam',
       'vyasarpadi',
       'vyazovoye',
       'vyavahara',
       'vyavastha',
       'vyalkovka',
       'vyasakuta',
       'vyaamoham',
       'vyazemsky',
       'vyazmikin',
       'vyatchina',
       'vyakarana',
       'vyazovsky',
       'vyazkovka',
       'vyakhirev',
       'vyatichi',
       'vyaltsev',
       'vyazniki',
       'vyazmino',
       'vyatkino',
       'vyazovka',
       'vyachko',
       'vyappiy',
       'vyatsky',
       'vyahali',
       'vyangya',
       'vyaspur',
       'vyalovo',
       'vyanda',
       'vyapti',
       'vyazma',
       'vyatta',
       'vyansa',
       'vyazka',
       'vyatka',
       'vyara',
       'vyasa',
       'vyali',
       'vyaz'],
 'b': ['vyborgsky', 'vyborovo', 'vyborna', 'vyborny', 'vyborg', 'vybor'],
 'c': ['vycapy-opatovce',
       'vychegodsky',
       'vychegda',
       'vychodna',
       'vychodil',
       'vycpalek',
       'vycapy',
       'vycor'],
 'd': ['vydubychi',
       'vydeniai',
       'vydrikha',
       'vydrnik',
       'vydrino',
       'vydrany',
       'vydrica',
       'vydunas',
       'vydrna',
       'vydri',
       'vydra',
       'vyd'],
 'e': ['vyezdnoye', 'vyezd'],
 'g': ['vygonichi', 'vygantas', 'vyg'],
 'h': ['vyhledy', 'vyhne'],
 'j': ['vyjayanthimala'],
 'k': ['vykuntapuram',
       'vykuntapali',
       'vyklantice',
       'vykhodnoy',
       'vykintas',
       'vykleky',
       'vykhino',
       'vyking',
       'vykan',
       'vyksa'],
 'l': ['vylathur', 'vylkove', 'vylok', 'vylon'],
 'm': ['vymetnoye', 'vymazal', 'vympel', 'vymol', 'vym'],
 'n': ['vynohradar',
       'vynohradiv',
       'vynohradne',
       'vynthala',
       'vyngypur',
       'vynohrad',
       'vynnyky',
       'vyncke',
       'vyner'],
 'o': ['vyoshenskaya',
       'vyommitra',
       'vyooham',
       'vyozhki',
       'vyoksa',
       'vyoska',
       'vyond',
       'vyos'],
 'p': ['vyprachtice',
       'vypolzovo',
       'vypuchky',
       'vypasnoy',
       'vypalai',
       'vypovo',
       'vypin'],
 'r': ['vyrypayevo',
       'vyrovice',
       'vyroneia',
       'vyrytovo',
       'vyrubov',
       'vyronas',
       'vyritsa',
       'vyrnwy',
       'vyrova',
       'vyrava',
       'vyron',
       'vyrus',
       'vyrt'],
 's': ['vyshestebliyevskaya',
       'vysheslavskoye',
       'vyshe-talovka',
       'vystavochnaya',
       'vyshetalovsky',
       'vystrcenovice',
       'vysehorovice',
       'vysotinskaya',
       'vysokopillia',
       'vysokogorsk',
       'vysniauskas',
       'vyshnivchyk',
       'vyshgorodok',
       'vysehnevice',
       'vysokohirne',
       'vysokovo-2',
       'vyshnivets',
       'vyshyvanka',
       'vysokinsky',
       'vyshmanovo',
       'vyshhorod',
       'vysokovsk',
       'vysokusha',
       'vystrkov',
       'vyshkovo',
       'vysehrad',
       'vysokovo',
       'vyskytna',
       'vyshhora',
       'vyskovec',
       'vysichka',
       'vysokaje',
       'vysotsko',
       'vysovice',
       'vysochka',
       'vysocina',
       'vysehori',
       'vystavka',
       'vysocany',
       'vyskocil',
       'vysotino',
       'vyskovce',
       'vyshkov',
       'vysekal',
       'vysotsk',
       'vystrel',
       'vyselki',
       'vyshata',
       'vysokyi',
       'vysluni',
       'vysokov',
       'vysoky',
       'vysakh',
       'vysoke',
       'vysoka',
       'vyshka',
       'vysker',
       'vyskov',
       'vysun',
       'vyssa',
       'vyse',
       'vyso'],
 't': ['vyt-les-belvoir',
       'vytshegdosuchus',
       'vytauteliai',
       'vytautine',
       'vytfutia',
       'vytautas',
       'vytebet',
       'vythiri',
       'vytenis',
       'vyttila',
       'vytopna',
       'vytegra',
       'vythos',
       'vytina',
       'vytine',
       'vytas',
       'vyt'],
 'u': ['vyushitaswa', 'vyushino', 'vyuham', 'vyuha'],
 'y': ['vyyemkovo', 'vyya'],
 'z': ['vyzhnytsia',
       'vyzhenka',
       'vyznanie',
       'vyzuonos',
       'vyzlovka',
       'vyzakia',
       'vyzerky',
       'vyzice',
       'vyziki',
       'vyzas']}
