
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_v_ = {'_': ['v1-morph',
       'v0-morph',
       'v774104',
       'v2.fi',
       'v600e',
       'v1000',
       'v150',
       'v100',
       'v.92',
       'v900',
       'v300',
       'v500',
       'v2.0',
       'v-01',
       'v850',
       'v-11',
       'v-61',
       'v200',
       'v45',
       'v40',
       'v60',
       'v50',
       'v75',
       'v33',
       'v30',
       'v13',
       'v26',
       'v12',
       'v70',
       'v80',
       'v23',
       'v16',
       'v19',
       'v24',
       'v58',
       'v28',
       'v17',
       'v20',
       'v21',
       'v14',
       'v29',
       'v90',
       'v34',
       'v36',
       'v11',
       'v81',
       'v22',
       'v15',
       'v25',
       'v18',
       'v27',
       'v35'],
 'a': ['v-atpase', 'v7ab', 'v4a', 'v-a'],
 'b': ['v-business', 'v-block', 'v-boat', 'v.b.z.', 'v1bes', 'v-bor'],
 'c': ['v-cableway', 'v-chip', 'v-cord', 'v-cam'],
 'd': ['v-drive', 'v-disc'],
 'e': ['v*enna'],
 'f': ['v.f.q.p.r.d.', 'v-focus', 'v.flash', 'v2food'],
 'g': ['v3g'],
 'h': ['v/h/s/94', 'v/h/s/2', 'v-hull', 'v/h/s'],
 'i': ['v.i.p.p.', 'v.i.s.a.'],
 'k': ['v.kalathur', 'v-key', 'v2k'],
 'l': ['v@liqulub@yli',
       'v@lixanli',
       'v@l@parqo',
       'v@liusagi',
       'v@lib@yli',
       'v-league',
       'v@l@cola',
       'v@l@ver',
       'v@lv@l@',
       'v@l@mir',
       'v@l@sli',
       'v/line',
       'v-line'],
 'm': ['v-model', 'v-mount', 'v-moda', 'v-mail', 'v-man', 'v-me'],
 'n': ['v@n@sik@s',
       'v@n@dli',
       'v-nasty',
       'v-nova',
       'v@n@di',
       'v@nlik',
       'v@ndam',
       'v@ng'],
 'p': ['v-partei3', 'v-prop', 'v-pug', 'v-pop'],
 'r': ['v@rm@ziyar',
       'v@rg@duz',
       'v-rally',
       'v@r@z@t',
       'v-rock',
       'v@rdag',
       'v@rov',
       'v-ray'],
 's': ['v.s.k.valasai',
       'v8supertourer',
       'v-statistic',
       'v-ships',
       'v-strom',
       'v.smile',
       'v/stol',
       'v-sag',
       'v-sit',
       'v-src',
       'v/s'],
 't': ['v-topology', 'v-tetris', 'v@t@g@', 'v-town', 'v-tail'],
 'u': ['v.unbeatable', 'v-u-den'],
 'v': ['v.v.i.p', 'v/vm', 'v&v'],
 'w': ['v-weapons', 'v-wing'],
 'x': ['v8xtra'],
 'z': ['v@zn@s']}
