
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xt = {'_': ['xt9', 'xt6'],
 'a': ['xtabentun',
       'xtar-eur',
       'xtalsoft',
       'xtampak',
       'xtabay',
       'xtatik',
       'xtabi',
       'xtalk',
       'xtar'],
 'b': ['xtbs', 'xtb'],
 'c': ['xtcy', 'xtc'],
 'e': ['xtension', 'xtext', 'xterm', 'xtend', 'xtea', 'xtep'],
 'f': ['xtf'],
 'i': ['xti'],
 'm': ['xtm-cat', 'xtm'],
 'n': ['xtnct', 'xtnd'],
 'o': ['xtopia', 'xtort', 'xtol'],
 'p': ['xtp'],
 'r': ['xtra-vision',
       'xtr-101/102',
       'xtravaganza',
       'xtractaurs',
       'xtremeair',
       'xtracycle',
       'xtreemfs',
       'xtreamer',
       'xtraview',
       'xtrmntr',
       'xtrempc',
       'xtratum',
       'xtratuf',
       'xtralis',
       'xtripx',
       'xtradb',
       'xtrmst',
       'xtree',
       'xtro',
       'xtr'],
 's': ['xts-400', 'xtsr', 'xts'],
 'u': ['xtuple', 'xtube', 'xtul'],
 'v': ['xtv'],
 'x': ['xtx']}
