
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jy = {'_': ['jy_hitchcox',
       'jy-14_radar',
       'jy-8_radar',
       'jy-9_radar',
       'jy_simpkin',
       'jy_farrar',
       'jy_bond'],
 'a': ['jyamire,_sindhupalchok',
       'jyamire,_okhaldhunga',
       'jyamire,_khotang',
       'jyamire,_palpa',
       'jyamdi_mandan'],
 'd': ['jydegaard_formation', 'jydske_asyl', 'jyd_goolie'],
 'e': ['jyeshtharaj_joshi',
       'jye_etheridge',
       'jye_caldwell',
       'jye_edwards',
       'jye_mullane',
       'jye_mcneil',
       'jye_bolton'],
 'g': ['jygri'],
 'h': ['jyhan_artut'],
 'j': ['jyj_discography'],
 'k': ['jykine_bradley'],
 'l': ['jyldyz_mambetaliyeva',
       'jyllingevej_station',
       'jyldyz_joldosheva',
       'jyllian_gunther',
       'jyler_noviello',
       'jylian_gustlin',
       'jyles_coggins',
       'jyll_bradley',
       'jyles_tucker',
       'jylan_ware'],
 'm': ['jymie_merritt', 'jyme_bridges', 'jymn_magon', 'jymoo_zhou'],
 'n': ['jynine_james', 'jyn_erso'],
 'o': ['jyotibhushan_bhattacharya',
       'jyothirgamaya_foundation',
       'jyotirmayee_gangopadhyay',
       'jyotirvidya_parisanstha',
       'jyotirindranath_tagore',
       'jyotirmay_bhattacharya',
       'jyotirmoy_guhathakurta',
       'jyotsna_radhakrishnan',
       'jyotirindranath_nandi',
       'jyothika_filmography',
       'jyothibai_pariyadath',
       'jyotiraditya_scindia',
       'jyotsana_srivastava',
       'jyotirishwar_thakur',
       'jyotipal_mahathero',
       'jyotirmoyee_sikdar',
       'jyotipriya_mallick',
       'jyotipriyo_mullick',
       'jyotiprasad_medhi',
       'jyotirmaya_sharma',
       'jyotirmoyee_devi',
       'jyo_achyutananda',
       'jyotsna_srikanth',
       'jyotirmayee_dash',
       'jyotigram_yojana',
       'jyoti_khandelwal',
       'jyotsna_chandola',
       'jyotibacha_navas',
       'jyoti_swarupini',
       'jyoti_mhapsekar',
       'jyotsna_sonowal',
       'jyotirmoy_datta',
       'jyothi_lakshmi',
       'jyoti_randhawa',
       'jyoji_morikawa',
       'jyotica_tangri',
       'jyotiba_temple',
       'jyothi_krishna',
       'jyotindra_jain',
       'jyotsna_chanda',
       'jyotirmoy_basu',
       'jyotsna_biswas',
       'jyotsna_dhawan',
       'jyotirao_phule',
       'jyotish_mitter',
       'jyotsna_mahant',
       'jyotindra_dave',
       'jyoti_subhash',
       'jyotsna_mandi',
       'jyoti_dhawale',
       'jyoti_swaroop',
       'jyotirmoy_dey',
       'jyotsna_bhatt',
       'jyoti_ghimire',
       'jyoti_punwani',
       'jyotika_jyoti',
       'jyotsna_patel',
       'jyorapar_vala',
       'jyoti_kalani',
       'jyothi_nagar',
       'jyotii_sethi',
       'jyoti_chetty',
       'jyoti_khuria',
       'jyoti_dhurve',
       'jyoti_bansal',
       'jyotish_jani',
       'jyotsna_vaid',
       'jyoti_kalash',
       'jyoti_gondek',
       'jyoti_pandey',
       'jyoti_mirdha',
       'jyothi_meena',
       'jyoti_kumari',
       'jyoti_singh',
       'jyoti_dutta',
       'jyoti_kiran',
       'jyotish_das',
       'jyoti_hegde',
       'jyoti_sarup',
       'jyoti_bhatt',
       'jyoti_arora',
       'jyotir_math',
       'jyoti_gogte',
       'jyoti_gauba',
       'jyoti_yadav',
       'jyoti_basu',
       'jyoti_amge',
       'jyoti_puri',
       'jyoti_rout',
       'jyoti_goho',
       'jyoti_devi',
       'jyot_jale',
       'jyoti_raj'],
 'p': ['jyp_entertainment', 'jyp_jyvaskyla', 'jyp_naiset'],
 'r': ['jyrgalbek_kalmamatov',
       'jyrki_parantainen',
       'jyrki_ponsiluoma',
       'jyrki_hamalainen',
       'jyrki_heliskoski',
       'jyrki_jokipakka',
       'jyrki_kiiskinen',
       'jyri_hietaharju',
       'jyrki_valivaara',
       'jyrki_nieminen',
       'jyrki_saranpaa',
       'jyrki_niskanen',
       'jyrki_pellinen',
       'jyri_marttinen',
       'jyrki_katainen',
       'jyrki_yrttiaho',
       'jyrki_nurminen',
       'jyrki_lehtonen',
       'jyrki_kahkonen',
       'jyri_pelkonen',
       'jyrki_aimonen',
       'jyrki_tujunen',
       'jyri_jaakkola',
       'jyri_hakamies',
       'jyrki_hakala',
       'jyri_junnila',
       'jyrki_kasvi',
       'jyrki_jarvi',
       'jyrki_seppa',
       'jyrki_louhi',
       'jyrki_lumme',
       'jyrki_otila',
       'jyri_aalto',
       'jyri_niemi',
       'jyri_kjall',
       'jyrki_blom',
       'jyri_ronn',
       'jyro_xhan',
       'jyrki_aho',
       'jyrki_69'],
 's': ['jyske_bank', 'jysk_arena', 'jysk_park'],
 't': ['jytte_abildstrom',
       'jytte_guteland',
       'jytte_andersen',
       'jytte_klausen',
       'jytte_hilden',
       'jytte_hansen',
       'jytte_hoy',
       'jytte_rex'],
 'u': ['jyutei_senki'],
 'v': ['jyvaskyla-pieksamaki_railway',
       'jyvaskylan_maalaiskunta',
       'jyvaskyla_sub-region',
       'jyvaskyla_sinfonia',
       'jyvaskyla_airport',
       'jyvaskyla_tv-mast',
       'jyvaskyla_rc',
       'jyve_v'],
 'w': ['jywe_wen-yuh']}
