
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jt = {'_': ['jt_marcinkowski',
       'jt_mccormick',
       'jt_marvelous',
       'jt_mcnamara',
       'jt_thunders',
       'jt_southern',
       'jt_sundling',
       'jt_daniels',
       'jt_storage',
       'jt_jackson',
       'jt_mollner',
       'jt_hodges',
       'jt_curtis',
       'jt_playaz',
       'jt_money',
       'jt_leroy',
       'jt_roach',
       'jt_bowen',
       'jt_lewis',
       'jt_tran',
       'jt_daly',
       'jt_dunn',
       'jt_thor',
       'jt_pac'],
 'a': ['jta_supermarkets', 'jtac_hill'],
 'b': ['jtbc_golf&sports', 'jtb_corporation', 'jtbc_newsroom', 'jtbc_studios'],
 'c': ['jtc_corporation', 'jtc_plc'],
 'd': ['jtdc'],
 'e': ['jte_multimedia', 'jtekt_stings', 'jte_7-31'],
 'g': ['jtg'],
 'i': ['jtip', 'jti'],
 'k': ['jtk'],
 'l': ['jtls', 'jtl'],
 'm': ['jtm'],
 'n': ['jtnews', 'jtn'],
 'o': ['jtol'],
 'p': ['jtp'],
 'r': ['jtre_london'],
 's': ['jtsb', 'jts'],
 't': ['jtt'],
 'u': ['jtu'],
 'v': ['jtv_ethiopia'],
 'y': ['jty']}
