
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fm = {'_': ['fm_3-24_counterinsurgency',
       'fm_non-duplication_rule',
       'fm4_frequency_festival',
       'fm_consolidated_line',
       'fm12_nbc_respirator',
       'fm_broadcast_band',
       'fm/tv_mast_milki',
       'fm_100_pakistan',
       'fm_towns_marty',
       'fm99_sri_lanka',
       'fm_records_llc',
       'fm_876_network',
       'fm_radio_gods',
       'fm_santa_rosa',
       'fm_le_sieur',
       'fm_la_boca',
       'fm_and_am'],
 'a': ['fma_instruction_set',
       'fma_ia-63_pampa',
       'fma_i.ae._37',
       'fma_i.ae._48',
       'fma_saia_90',
       'fma_ia_62'],
 'b': ['fmbcapital_holdings_plc'],
 'c': ['fmc_dockyard_limited', 'fmcg_in_india'],
 'k': ['fmk-3_submachine_gun'],
 'n': ['fmn-binding_fluorescent_protein'],
 'p': ['fmp/free_music_production', 'fmp_qualt_201'],
 'r': ['fmrib_software_library', 'fmri_lie_detection'],
 'w': ['fmw/wew_hardcore_championship',
       "fmw_women's_championship",
       'fmw_summer_spectacular',
       'fmw_anniversary_show',
       'fmw_fall_spectacular',
       'fmw_deep_throat']}
