
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ff = {'_': ['ff_sport_atalaiense',
       'ff_venture_capital',
       'ff_/_vinternoll2',
       'ff_lugano_1976',
       'ff_scala_sans',
       'ff_norden_02',
       'ff_med_bert'],
 'a': ['ffar2-ffar3_receptor_heteromer',
       'ffairfach_railway_station',
       "ffas_president's_cup",
       'ffa_cup_appearances',
       'ffas_senior_league',
       'ffa_private_bank',
       'ffa_coffi_pawb'],
 'c': ['ffc_brauweiler_pulheim',
       'ffc_cambridge_process',
       'ffc_heike_rheine',
       'ffc_zuchwil_05'],
 'e': ['ffestiniog_transmitting_station',
       'ffestiniog_memorial_hospital',
       'ffestiniog_power_station',
       'ffernfael_ap_meurig',
       'ffernfael_ap_tewdwr',
       'ffernfael_ab_idwal'],
 'f': ['fff_racing_team'],
 'h': ['ffhg_division_1', 'ffhg_division_3', 'ffhg_division_2'],
 'i': ['ffilharmonious_jug_band'],
 'o': ['fforest_fawr_geopark',
       'ffordd_coed_dol-fawr',
       'ffos_las_racecourse',
       'ffordd_pen_llech'],
 'r': ['ffridd_faldwyn,_montgomery',
       'ffrith_railway_station',
       'ffrwd_fawr_waterfall'],
 's': ['ffsa_gt_championship', 'ffsa_super_league'],
 't': ['fft_eurotrainer_2000'],
 'u': ["ffu_regions'_cup"],
 'v': ['ffv_018_mine', 'ffv_016_mine', 'ffv_028_mine', 'ffvs_j_22'],
 'y': ['ffynone_house_school']}
