
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-19T15:23:42+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "27a6e5c65c40e10cb4895c56e76be39aa4c0a6ce",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
