
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xc = {'_': ['xc2000', 'xc2200', 'xc2'],
 'a': ['xcalibur', 'xcalak', 'xcaret', 'xcast', 'xcal', 'xcas', 'xcat'],
 'b': ['xcbusa', 'xcbl', 'xcb'],
 'c': ['xcc++'],
 'd': ['xcd'],
 'e': ['xcelerator',
       'xcelencia',
       'xcel-arc',
       'xceedium',
       'xcellent',
       'xcelite',
       'xceed',
       'xces'],
 'f': ['xcf'],
 'h': ['xchocobars', 'xchanging', 'xchm', 'xch'],
 'i': ['xcircuit', 'xcite', 'xcis'],
 'l': ['xcl2', 'xcl1', 'xcl'],
 'm': ['xcmg'],
 'o': ['xcodeghost',
       'xcopilot',
       'xconomy',
       'xconfig',
       'xcoff',
       'xcode',
       'xcopy',
       'xconq',
       'xcon',
       'xcom',
       'xco2'],
 'p': ['xcp'],
 'r': ['xcri', 'xcr1', 'xcr'],
 't': ['xct-790'],
 'u': ['xculoc'],
 'x': ['xcx']}
