
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xo = {'_': ['xo`jakent',
       'xo`jaobod',
       'xo`jayli',
       'xo-2nb',
       'xo-3b',
       'xo-4b',
       'xo-5b',
       'xo-1b',
       'xo-6b',
       'xo-4',
       'xo-5',
       'xo-2',
       'xo-1',
       'xo-3'],
 'a': ['xoanon', 'xoana', 'xoan', 'xoa'],
 'b': ['xobdo.org', 'xobando', 'xobotos', 'xobni', 'xobc'],
 'c': ['xochihuehuetlan',
       'xochiquetzallia',
       'xochistlahuaca',
       'xocomecatlite',
       'xochicoatlan',
       'xochiquetzal',
       'xocamusaxli',
       'xocolatlite',
       'xochiatipan',
       'xochitlicue',
       'xochiltepec',
       'xochitecatl',
       'xochiapulco',
       'xochimilco',
       'xochicalco',
       'xochitepec',
       'xochipilli',
       'xochipala',
       'xochitla',
       'xocadoy',
       'xocahan',
       'xochitl',
       'xocourt',
       'xoc@s@n',
       'xocavar',
       'xocomil',
       'xocotl',
       'xocik',
       'xoca',
       'xoco',
       'xoc'],
 'd': ['xodus', 'xod'],
 'g': ['xog'],
 'h': ['xohm'],
 'i': ['xoi'],
 'j': ['xojane', 'xojo'],
 'k': ['xokleng', 'xok'],
 'l': ['xoloitzcuintle',
       'xolt@z@k@nd',
       'xolalgidae',
       'xolocotzia',
       'xolotrema',
       'xol@z@y',
       'xolmili',
       'xolote',
       'xolani',
       'xolotl',
       'xolmis',
       'xolve',
       'xolas',
       'xolo'],
 'm': ['xombrero',
       'xomidhan',
       'xometry',
       'xombie',
       'xomgl',
       'xombi',
       'xome',
       'xom'],
 'n': ['xonrupt-longemer',
       'xonacatlan',
       'xonotlite',
       'xonville',
       'xonotla',
       'xonobod',
       'xonotic',
       'xonox',
       'xonix',
       'xonqa',
       'xonia',
       'xong'],
 'o': ['xoops', 'xootr', 'xooy', 'xoom'],
 'p': ['xop'],
 'r': ['xor-encrypt-xor',
       'xoroshiro128+',
       'xorg.conf',
       'xoridinae',
       'xorphanol',
       'xorshift',
       'xorychti',
       'xorcist',
       'xorides',
       'xoruzlu',
       'xorbit',
       'xoria',
       'xorai',
       'xorn',
       'xorp'],
 's': ['xoscobanli', 'xoskesin', 'xosbulaq', 'xosrov', 'xoser', 'xosl', 'xos'],
 't': ['xotodon', 'xotox', 'xotcl', 'xote', 'xot'],
 'u': ['xouaxange', 'xoulces', 'xousse'],
 'v': ['xover', 'xovos', 'xove', 'xov'],
 'w': ['xowa'],
 'x': ['xoxocotla', 'xoxo', 'xox'],
 'y': ['xoybun', 'xoylu', 'xoyo'],
 'z': ['xozavi']}
