
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oz = {'_': ['oz7igy'],
 'a': ['ozarki-olszanka',
       'ozarkcollenia',
       'ozarkodinida',
       'oza-cesuras',
       'ozarkodina',
       'ozanezumab',
       'ozaawindib',
       'ozarowice',
       'ozarchaea',
       'ozarovsky',
       'ozaryntsi',
       'ozaenini',
       'ozanimod',
       'ozarelix',
       'ozarenny',
       'ozankoy',
       'ozarcus',
       'ozaukee',
       'ozagrel',
       'ozarkia',
       'ozancik',
       'ozatlan',
       'ozanne',
       'ozarde',
       'ozarba',
       'ozansk',
       'ozanam',
       'ozaeta',
       'ozarks',
       'ozarka',
       'ozamia',
       'ozarow',
       'ozamiz',
       'ozana',
       'ozaki',
       'ozalp',
       'ozary',
       'ozawa',
       'ozalj',
       'ozara',
       'ozama',
       'ozal',
       'ozar',
       'ozai',
       'ozan',
       'oza'],
 'b': ['ozboynuinceli',
       'ozbilgin',
       'ozbekuy',
       'ozbilen',
       'ozbalt',
       'ozbey',
       'ozbek',
       'ozbak',
       'ozbi'],
 'c': ['ozcelik', 'ozcopa', 'ozcar', 'ozcan'],
 'd': ['ozdowski',
       'ozdfalu',
       'ozdilek',
       'ozdemir',
       'ozdere',
       'ozdany',
       'ozdin',
       'ozdil',
       'ozden',
       'ozd'],
 'e': ['ozenx-montestrucq',
       'ozero-kureyevo',
       'ozerianivka',
       'ozeryshche',
       'ozerkovici',
       'ozenoxacin',
       'ozerailles',
       'ozegahara',
       'ozerkovka',
       'ozeriany',
       'ozeaneum',
       'ozeville',
       'ozerkovo',
       'ozeryane',
       'ozernoy',
       'ozemail',
       'ozerovo',
       'ozerlag',
       'ozerko',
       'ozenay',
       'ozenna',
       'ozegna',
       'ozerne',
       'ozette',
       'ozeros',
       'ozegow',
       'ozerov',
       'ozerki',
       'ozeka',
       'ozerk',
       'ozeia',
       'ozeri',
       'ozeki',
       'ozero',
       'ozell',
       'ozen',
       'ozer',
       'ozek',
       'ozel',
       'ozem',
       'ozet',
       'oze'],
 'g': ['ozgorush',
       'ozgener',
       'ozgirl',
       'ozgon',
       'ozgur',
       'ozguc',
       'ozgen',
       'ozgul',
       'ozgu',
       'ozga',
       'ozge'],
 'h': ['ozhaguscodaywayquay',
       'ozhiginskaya',
       'ozhivukaalam',
       'ozhalapathy',
       'ozherelye',
       'ozhigovo',
       'ozhimuri',
       'ozhogina',
       'ozhur',
       'ozhan'],
 'i': ['oziotelphusa',
       'oziexplorer',
       'oziemkowka',
       'ozirhincus',
       'ozicrypta',
       'ozierskie',
       'ozichthys',
       'ozieblow',
       'ozineus',
       'oziidae',
       'ozimops',
       'ozillac',
       'ozieres',
       'oziably',
       'oziljak',
       'oziris',
       'ozinie',
       'ozieri',
       'ozinki',
       'ozinga',
       'ozimek',
       'oziroe',
       'ozius',
       'oziel',
       'ozidi',
       'ozil',
       'ozi'],
 'j': ['ozjet'],
 'k': ['ozkabaliai', 'ozkaya', 'ozkul', 'ozkan', 'ozker', 'ozkok'],
 'l': ['ozleworth', 'ozluce', 'ozland', 'ozlem', 'ozler', 'ozlu'],
 'm': ['ozmanbuk',
       'ozmana',
       'ozment',
       'ozmert',
       'ozmen',
       'ozmas',
       'ozma',
       'ozm'],
 'n': ['oznobishino', 'oznice', 'oznur', 'oznoz', 'ozna'],
 'o': ['ozouer-le-voulgis',
       'ozoir-la-ferriere',
       'ozoir-le-breuil',
       'ozoralizumab',
       'ozogamicin',
       'ozolotepec',
       'ozotroctes',
       'ozothamnus',
       'ozophorini',
       'ozonolysis',
       'ozognathus',
       'ozolinone',
       'ozotuncus',
       'ozorowice',
       'ozokerite',
       'ozothrips',
       'ozodicera',
       'ozormiste',
       'ozopactus',
       'ozolnieki',
       'ozophora',
       'ozophore',
       'ozoneweb',
       'ozomatli',
       'ozorzyce',
       'ozornovo',
       'ozodagon',
       'ozolina',
       'ozorzyn',
       'ozopore',
       'ozolles',
       'ozolins',
       'ozonide',
       'ozomdel',
       'ozodera',
       'ozovehe',
       'ozorkow',
       'ozourt',
       'ozorow',
       'ozonia',
       'ozoroa',
       'ozodes',
       'ozolin',
       'ozoguz',
       'ozolua',
       'ozoir',
       'ozona',
       'ozols',
       'ozora',
       'ozone',
       'ozola',
       'ozoro',
       'ozor',
       'ozow',
       'ozon',
       'ozol'],
 'p': ['ozploitation'],
 'r': ['ozrenovici', 'ozrakovici', 'ozraptor', 'ozrinici', 'ozrem', 'ozren'],
 's': ['ozsoy', 'ozspy'],
 't': ['ozturkmenli',
       'ozturkce',
       'oztoprak',
       'oztekin',
       'oztira',
       'ozturk',
       'oztam'],
 'u': ['ozukumi-jima',
       'ozumiech',
       'ozushima',
       'ozudogru',
       'ozurgeti',
       'ozuluama',
       'ozumchi',
       'ozubulu',
       'ozujsko',
       'ozumba',
       'ozutsu',
       'ozunca',
       'ozuna',
       'ozuma',
       'ozun',
       'ozu'],
 'v': ['ozvatan', 'ozvar'],
 'w': ['ozwathini'],
 'y': ['ozyorno-kuznetsovo',
       'ozyablitsy',
       'ozymandias',
       'ozyptila',
       'ozyorsky',
       'ozynnik',
       'ozyorny',
       'ozyorsk',
       'ozyurek',
       'ozyurt',
       'ozyory',
       'ozyora',
       'ozy'],
 'z': ['ozzmosis', 'ozzfest', 'ozzero', 'ozzano', 'ozzie']}
