INSERT INTO creature (name, name_tag, category, entity_id, blueprint)
VALUES
('Aberrant Achatina','Achatina','Invertebrates','Achatina_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Achatina/Achatina_Character_BP_Aberrant.Achatina_Character_BP_Aberrant\'"'),
('Aberrant Anglerfish','Angler','Fish','Angler_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Anglerfish/Angler_Character_BP_Aberrant.Angler_Character_BP_Aberrant\'"'),
('Aberrant Ankylosaurus','Anky','Dinosaurs','Ankylo_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Ankylo/Ankylo_Character_BP_Aberrant.Ankylo_Character_BP_Aberrant\'"'),
('Aberrant Araneo','Spider','Invertebrates','SpiderS_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Spider-Small/SpiderS_Character_BP_Aberrant.SpiderS_Character_BP_Aberrant\'"'),
('Aberrant Arthropluera','Arthro','Invertebrates','Arthro_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Arthropluera/Arthro_Character_BP_Aberrant.Arthro_Character_BP_Aberrant\'"'),
('Aberrant Baryonyx','Baryonyx','Dinosaurs','Baryonyx_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Baryonyx/Baryonyx_Character_BP_Aberrant.Baryonyx_Character_BP_Aberrant\'"'),
('Aberrant Beelzebufo','Toad','Reptiles','Toad_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Toad/Toad_Character_BP_Aberrant.Toad_Character_BP_Aberrant\'"'),
('Aberrant Carbonemys','Turtle','Reptiles','Turtle_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Turtle/Turtle_Character_BP_Aberrant.Turtle_Character_BP_Aberrant\'"'),
('Aberrant Carnotaurus','Carno','Dinosaurs','Carno_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Carno/Carno_Character_BP_Aberrant.Carno_Character_BP_Aberrant\'"'),
('Aberrant Cnidaria','Cnidaria','Invertebrates','Cnidaria_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Cnidaria/Cnidaria_Character_BP_Aberrant.Cnidaria_Character_BP_Aberrant\'"'),
('Aberrant Coelacanth','Coel','Fish','Coel_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Coelacanth/Coel_Character_BP_Aberrant.Coel_Character_BP_Aberrant\'"'),
('Aberrant Dimetrodon','Dimetro','Dinosaurs','Dimetro_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dimetrodon/Dimetro_Character_BP_Aberrant.Dimetro_Character_BP_Aberrant\'"'),
('Aberrant Dimorphodon','Dimorph','Dinosaurs','Dimorph_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dimorphodon/Dimorph_Character_BP_Aberrant.Dimorph_Character_BP_Aberrant\'"'),
('Aberrant Diplocaulus','Diplocaulus','Amphibians','Diplocaulus_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Diplocaulus/Diplocaulus_Character_BP_Aberrant.Diplocaulus_Character_BP_Aberrant\'"'),
('Aberrant Diplodocus','Diplo','Dinosaurs','Diplodocus_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Diplodocus/Diplodocus_Character_BP_Aberrant.Diplodocus_Character_BP_Aberrant\'"'),
('Aberrant Dire Bear','Direbear','Mammals','Direbear_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Direbear/Direbear_Character_BP_Aberrant.Direbear_Character_BP_Aberrant\'"'),
('Aberrant Dodo','Dodo','Birds','Dodo_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dodo/Dodo_Character_BP_Aberrant.Dodo_Character_BP_Aberrant\'"'),
('Aberrant Doedicurus','Doed','Dinosaurs','Doed_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Doedicurus/Doed_Character_BP_Aberrant.Doed_Character_BP_Aberrant\'"'),
('Aberrant Dung Beetle','Beetle','Invertebrates','DungBeetle_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/DungBeetle/DungBeetle_Character_BP_Aberrant.DungBeetle_Character_BP_Aberrant\'"'),
('Aberrant Electrophorus','Eel','Fish','Eel_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Eel/Eel_Character_BP_Aberrant.Eel_Character_BP_Aberrant\'"'),
('Aberrant Equus','Equus','Mammals','Equus_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Equus/Equus_Character_BP_Aberrant.Equus_Character_BP_Aberrant\'"'),
('Aberrant Gigantopithecus','Bigfoot','Mammals','Bigfoot_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Bigfoot/Bigfoot_Character_BP_Aberrant.Bigfoot_Character_BP_Aberrant\'"'),
('Aberrant Iguanodon','Iguanodon','Dinosaurs','Iguanodon_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Iguanodon/Iguanodon_Character_BP_Aberrant.Iguanodon_Character_BP_Aberrant\'"'),
('Aberrant Lystrosaurus','Lystro','Dinosaurs','Lystro_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Lystrosaurus/Lystro_Character_BP_Aberrant.Lystro_Character_BP_Aberrant\'"'),
('Aberrant Manta','Manta','Fish','Manta_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Manta/Manta_Character_BP_Aberrant.Manta_Character_BP_Aberrant\'"'),
('Aberrant Megalania','Megalania','Reptiles','Megalania_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Megalania/Megalania_Character_BP_Aberrant.Megalania_Character_BP_Aberrant\'"'),
('Aberrant Megalosaurus','Megalosaurus','Dinosaurs','Megalosaurus_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Megalosaurus/Megalosaurus_Character_BP_Aberrant.Megalosaurus_Character_BP_Aberrant\'"'),
('Aberrant Meganeura','Dragonfly','Invertebrates','Dragonfly_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dragonfly/Dragonfly_Character_BP_Aberrant.Dragonfly_Character_BP_Aberrant\'"'),
('Aberrant Moschops','Moschops','Synapsids','Moschops_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Moschops/Moschops_Character_BP_Aberrant.Moschops_Character_BP_Aberrant\'"'),
('Aberrant Otter','Otter','Mammals','Otter_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Otter/Otter_Character_BP_Aberrant.Otter_Character_BP_Aberrant\'"'),
('Aberrant Ovis','Sheep','Mammals','Sheep_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Sheep/Sheep_Character_BP_Aberrant.Sheep_Character_BP_Aberrant\'"'),
('Aberrant Paraceratherium','Paracer','Mammals','Paracer_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Paraceratherium/Paracer_Character_BP_Aberrant.Paracer_Character_BP_Aberrant\'"'),
('Aberrant Parasaur','Para','Dinosaurs','Para_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Para/Para_Character_BP_Aberrant.Para_Character_BP_Aberrant\'"'),
('Aberrant Piranha','Piranha','Fish','Piranha_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Piranha/Piranha_Character_BP_Aberrant.Piranha_Character_BP_Aberrant\'"'),
('Aberrant Pulmonoscorpius','Scorpion','Invertebrates','Scorpion_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Scorpion/Scorpion_Character_BP_Aberrant.Scorpion_Character_BP_Aberrant\'"'),
('Aberrant Purlovia','Purlovia','Synapsids','Purlovia_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Purlovia/Purlovia_Character_BP_Aberrant.Purlovia_Character_BP_Aberrant\'"'),
('Aberrant Raptor','Raptor','Dinosaurs','Raptor_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Raptor/Raptor_Character_BP_Aberrant.Raptor_Character_BP_Aberrant\'"'),
('Aberrant Sabertooth Salmon','Salmon','Fish','Salmon_Character_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Salmon/Salmon_Character_Aberrant.Salmon_Character_Aberrant\'"'),
('Aberrant Sarco','Sarco','Reptiles','Sarco_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Sarco/Sarco_Character_BP_Aberrant.Sarco_Character_BP_Aberrant\'"'),
('Aberrant Spino','Spino','Dinosaurs','Spino_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Spino/Spino_Character_BP_Aberrant.Spino_Character_BP_Aberrant\'"'),
('Aberrant Stegosaurus','Stego','Dinosaurs','Stego_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Stego/Stego_Character_BP_Aberrant.Stego_Character_BP_Aberrant\'"'),
('Aberrant Titanoboa','Titanboa','Reptiles','BoaFrill_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/BoaFrill/BoaFrill_Character_BP_Aberrant.BoaFrill_Character_BP_Aberrant\'"'),
('Aberrant Triceratops','Trike','Dinosaurs','Trike_Character_BP_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Trike/Trike_Character_BP_Aberrant.Trike_Character_BP_Aberrant\'"'),
('Aberrant Trilobite','Trilobite','Invertebrates','Trilobite_Character_Aberrant_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Trilobite/Trilobite_Character_Aberrant.Trilobite_Character_Aberrant\'"'),
('Alpha Basilisk','Elite Basilisk','Alpha Creatures','MegaBasilisk_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/Basilisk/MegaBasilisk_Character_BP.MegaBasilisk_Character_BP\'"'),
('Alpha Karkinos','Elite CaveCrab','Alpha Creatures','MegaCrab_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/Crab/MegaCrab_Character_BP.MegaCrab_Character_BP\'"'),
('Alpha Surface Reaper King','Elite Xenomorph','Alpha Creatures','MegaXenomorph_Character_BP_Male_Surface_C', '"Blueprint\'/Game/Aberration/Dinos/Nameless/MegaXenomorph_Character_BP_Male_Surface.MegaXenomorph_Character_BP_Male_Surface\'"'),
('Basilisk','Basilisk','Fantasy Creatures','Basilisk_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/Basilisk/Basilisk_Character_BP.Basilisk_Character_BP\'"'),
('Basilisk Ghost','Basilisk','Event Creatures','Ghost_Basilisk_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/Basilisk/Ghost_Basilisk_Character_BP.Ghost_Basilisk_Character_BP\'"'),
('Bulbdog','Pug','Fantasy Creatures','LanternPug_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/LanternPug/LanternPug_Character_BP.LanternPug_Character_BP\'"'),
('Bulbdog Ghost','Pug','Event Creatures','Ghost_LanternPug_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/LanternPug/Ghost_LanternPug_Character_BP.Ghost_LanternPug_Character_BP\'"'),
('Featherlight','Lantern Bird','Fantasy Creatures','LanternBird_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/LanternBird/LanternBird_Character_BP.LanternBird_Character_BP\'"'),
('Glowbug','Lightbug','Fantasy Creatures','Lightbug_Character_BaseBP_C', '"Blueprint\'/Game/Aberration/Dinos/Lightbug/Lightbug_Character_BaseBP.Lightbug_Character_BaseBP\'"'),
('Glowtail','Lantern Lizard','Fantasy Creatures','LanternLizard_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/LanternLizard/LanternLizard_Character_BP.LanternLizard_Character_BP\'"'),
('Karkinos','CaveCrab','Fantasy Creatures','Crab_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/Crab/Crab_Character_BP.Crab_Character_BP\'"'),
('Lamprey','Lamprey','Fish','Lamprey_Character_C', '"Blueprint\'/Game/Aberration/Dinos/Lamprey/Lamprey_Character.Lamprey_Character\'"'),
('Nameless','Chupacabra','Fantasy Creatures','ChupaCabra_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/ChupaCabra/ChupaCabra_Character_BP.ChupaCabra_Character_BP\'"'),
('Ravager','CaveWolf','Fantasy Creatures','CaveWolf_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/CaveWolf/CaveWolf_Character_BP.CaveWolf_Character_BP\'"'),
('Reaper King','Xenomorph','Fantasy Creatures','Xenomorph_Character_BP_Male_C', '"Blueprint\'/Game/Aberration/Dinos/Nameless/Xenomorph_Character_BP_Male.Xenomorph_Character_BP_Male\'"'),
('Reaper King (Tamed)','Xenomorph','Fantasy Creatures','Xenomorph_Character_BP_Male_Tamed_C', '"Blueprint\'/Game/Aberration/Dinos/Nameless/Xenomorph_Character_BP_Male_Tamed.Xenomorph_Character_BP_Male_Tamed\'"'),
('Reaper Queen','Xenomorph','Fantasy Creatures','Xenomorph_Character_BP_Female_C', '"Blueprint\'/Game/Aberration/Dinos/Nameless/Xenomorph_Character_BP_Female.Xenomorph_Character_BP_Female\'"'),
('Rock Drake','RockDrake','Fantasy Creatures','RockDrake_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/RockDrake/RockDrake_Character_BP.RockDrake_Character_BP\'"'),
('Rockwell','Rockwell','Fantasy Creatures','Rockwell_Character_BP_C', '"Blueprint\'/Game/Aberration/Boss/Rockwell/Rockwell_Character_BP.Rockwell_Character_BP\'"'),
('Rockwell (Alpha)','Rockwell','Fantasy Creatures','Rockwell_Character_BP_Hard_C', '"Blueprint\'/Game/Aberration/Boss/Rockwell/Rockwell_Character_BP_Hard.Rockwell_Character_BP_Hard\'"'),
('Rockwell (Beta)','Rockwell','Fantasy Creatures','Rockwell_Character_BP_Medium_C', '"Blueprint\'/Game/Aberration/Boss/Rockwell/Rockwell_Character_BP_Medium.Rockwell_Character_BP_Medium\'"'),
('Rockwell (Gamma)','Rockwell','Fantasy Creatures','Rockwell_Character_BP_Easy_C', '"Blueprint\'/Game/Aberration/Boss/Rockwell/Rockwell_Character_BP_Easy.Rockwell_Character_BP_Easy\'"'),
('Rockwell Tentacle','RockwellTentacle','Fantasy Creatures','RockwellTentacle_Character_BP_C', '"Blueprint\'/Game/Aberration/Boss/RockwellTentacle/RockwellTentacle_Character_BP.RockwellTentacle_Character_BP\'"'),
('Rockwell Tentacle (Alpha)','RockwellTentacle','Fantasy Creatures','RockwellTentacle_Character_BP_Alpha_C', '"Blueprint\'/Game/Aberration/Boss/RockwellTentacle/RockwellTentacle_Character_BP_Alpha.RockwellTentacle_Character_BP_Alpha\'"'),
('Rockwell Tentacle (Beta)','RockwellTentacle','Fantasy Creatures','RockwellTentacle_Character_BP_Beta_C', '"Blueprint\'/Game/Aberration/Boss/RockwellTentacle/RockwellTentacle_Character_BP_Beta.RockwellTentacle_Character_BP_Beta\'"'),
('Rockwell Tentacle (Gamma)','RockwellTentacle','Fantasy Creatures','RockwellTentacle_Character_BP_Gamma_C', '"Blueprint\'/Game/Aberration/Boss/RockwellTentacle/RockwellTentacle_Character_BP_Gamma.RockwellTentacle_Character_BP_Gamma\'"'),
('Roll Rat','MoleRat','Fantasy Creatures','MoleRat_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/MoleRat/MoleRat_Character_BP.MoleRat_Character_BP\'"'),
('Seeker','Seeker','Fantasy Creatures','Pteroteuthis_Char_BP_C', '"Blueprint\'/Game/Aberration/Dinos/Pteroteuthis/Pteroteuthis_Char_BP.Pteroteuthis_Char_BP\'"'),
('Shinehorn','Lantern Goat','Fantasy Creatures','LanternGoat_Character_BP_C', '"Blueprint\'/Game/Aberration/Dinos/LanternGoat/LanternGoat_Character_BP.LanternGoat_Character_BP\'"'),
('Surface Reaper King Ghost','Xenomorph','Event Creatures','Ghost_Xenomorph_Character_BP_Male_Surface_C', '"Blueprint\'/Game/Aberration/Dinos/Nameless/Ghost_Xenomorph_Character_BP_Male_Surface.Ghost_Xenomorph_Character_BP_Male_Surface\'"'),
('Alpha Blood Crystal Wyvern','Wyvern','Alpha Creatures','CrystalWyvern_Character_BP_Mega_C', '"Blueprint\'/Game/PrimalEarth/Dinos/CrystalWyvern/CrystalWyvern_Character_BP_Mega.CrystalWyvern_Character_BP_Mega\'"'),
('Blood Crystal Wyvern','Wyvern','Fantasy Creatures','CrystalWyvern_Character_BP_Blood_C', '"Blueprint\'/Game/PrimalEarth/Dinos/CrystalWyvern/CrystalWyvern_Character_BP_Blood.CrystalWyvern_Character_BP_Blood\'"'),
('Crystal Wyvern Queen (Gamma)','Wyvern','Bosses','CrystalWyvern_Character_BP_Boss_Easy_C', '"Blueprint\'/Game/Mods/CrystalIsles/Assets/Dinos/CIBoss/CrystalWyvern_Character_BP_Boss_Easy.CrystalWyvern_Character_BP_Boss_Easy\'"'),
('Crystal Wyvern Queen (Beta)','Wyvern','Bosses','CrystalWyvern_Character_BP_Boss_Medium_C', '"Blueprint\'/Game/Mods/CrystalIsles/Assets/Dinos/CIBoss/CrystalWyvern_Character_BP_Boss_Medium.CrystalWyvern_Character_BP_Boss_Medium\'"'),
('Crystal Wyvern Queen (Alpha)','Wyvern','Bosses','CrystalWyvern_Character_BP_Boss_Hard_C', '"Blueprint\'/Game/Mods/CrystalIsles/Assets/Dinos/CIBoss/CrystalWyvern_Character_BP_Boss_Hard.CrystalWyvern_Character_BP_Boss_Hard\'"'),
('Ember Crystal Wyvern','Wyvern','Fantasy Creatures','CrystalWyvern_Character_BP_Ember_C', '"Blueprint\'/Game/PrimalEarth/Dinos/CrystalWyvern/CrystalWyvern_Character_BP_Ember.CrystalWyvern_Character_BP_Ember\'"'),
('Giant Worker Bee','Bee','Invertebrates','HoneyBee_Character_BP_C', '"Blueprint\'/Game/Mods/CrystalIsles/Assets/Dinos/HoneyBee/HoneyBee_Character_BP.HoneyBee_Character_BP\'"'),
('Tropeognathus','Tropeognathus','Reptiles','Tropeognathus_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Tropeognathus/Tropeognathus_Character_BP.Tropeognathus_Character_BP\'"'),
('Tropical Crystal Wyvern','Wyvern','Fantasy Creatures','CrystalWyvern_Character_BP_WS_C', '"Blueprint\'/Game/PrimalEarth/Dinos/CrystalWyvern/CrystalWyvern_Character_BP_WS.CrystalWyvern_Character_BP_WS\'"'),
('Alpha King Titan','KingTitanAlpha','Fantasy Creatures','KingKaiju_Character_BP_Alpha_C', '"Blueprint\'/Game/Extinction/Dinos/KingKaiju/KingKaiju_Character_BP_Alpha.KingKaiju_Character_BP_Alpha\'"'),
('Beta King Titan','King Titan','Fantasy Creatures','KingKaiju_Character_BP_Beta_C', '"Blueprint\'/Game/Extinction/Dinos/KingKaiju/KingKaiju_Character_BP_Beta.KingKaiju_Character_BP_Beta\'"'),
('Corrupted Arthropluera','Arthro Corrupt','Invertebrates','Arthro_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Arthropluera/Arthro_Character_BP_Corrupt.Arthro_Character_BP_Corrupt\'"'),
('Corrupted Carnotaurus','Carno Corrupt','Dinosaurs','Carno_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Carno/Carno_Character_BP_Corrupt.Carno_Character_BP_Corrupt\'"'),
('Corrupted Chalicotherium','Chalico','Mammals','Chalico_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Chalicotherium/Chalico_Character_BP_Corrupt.Chalico_Character_BP_Corrupt\'"'),
('Corrupted Dilophosaur','Dilo Corrupt','Dinosaurs','Dilo_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Dilo/Dilo_Character_BP_Corrupt.Dilo_Character_BP_Corrupt\'"'),
('Corrupted Dimorphodon','Dimorph Corrupt','Dinosaurs','Dimorph_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Dimorphodon/Dimorph_Character_BP_Corrupt.Dimorph_Character_BP_Corrupt\'"'),
('Corrupted Giganotosaurus','Gigant Corrupt','Dinosaurs','Gigant_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Giganotosaurus/Gigant_Character_BP_Corrupt.Gigant_Character_BP_Corrupt\'"'),
('Corrupted Paraceratherium','Paracer','Mammals','Paracer_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Paraceratherium/Paracer_Character_BP_Corrupt.Paracer_Character_BP_Corrupt\'"'),
('Corrupted Pteranodon','Ptera Corrupt','Dinosaurs','Ptero_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Ptero/Ptero_Character_BP_Corrupt.Ptero_Character_BP_Corrupt\'"'),
('Corrupted Raptor','Raptor Corrupt','Dinosaurs','Raptor_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Raptor/Raptor_Character_BP_Corrupt.Raptor_Character_BP_Corrupt\'"'),
('Corrupted Reaper King','Xenomorph Corrupt','Fantasy Creatures','Xenomorph_Character_BP_Male_Tamed_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Nameless/Xenomorph_Character_BP_Male_Tamed_Corrupt.Xenomorph_Character_BP_Male_Tamed_Corrupt\'"'),
('Corrupted Rex','Rex Corrupt','Dinosaurs','Rex_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Rex/Rex_Character_BP_Corrupt.Rex_Character_BP_Corrupt\'"'),
('Corrupted Rock Drake','RockDrake Corrupt','Fantasy Creatures','RockDrake_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/RockDrake/RockDrake_Character_BP_Corrupt.RockDrake_Character_BP_Corrupt\'"'),
('Corrupted Spino','Spino Corrupt','Dinosaurs','Spino_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Spino/Spino_Character_BP_Corrupt.Spino_Character_BP_Corrupt\'"'),
('Corrupted Stegosaurus','Stego Corrupt','Dinosaurs','Stego_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Stego/Stego_Character_BP_Corrupt.Stego_Character_BP_Corrupt\'"'),
('Corrupted Triceratops','Trike','Dinosaurs','Trike_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Trike/Trike_Character_BP_Corrupt.Trike_Character_BP_Corrupt\'"'),
('Corrupted Wyvern','Wyvern','Fantasy Creatures','Wyvern_Character_BP_Fire_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Wyvern/Wyvern_Character_BP_Fire_Corrupt.Wyvern_Character_BP_Fire_Corrupt\'"'),
('Defense Unit','EndTank','Fantasy Creatures','Defender_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/Tank/Defender_Character_BP.Defender_Character_BP\'"'),
('Desert Titan','DesertTitan','Fantasy Creatures','DesertKaiju_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/DesertKaiju/DesertKaiju_Character_BP.DesertKaiju_Character_BP\'"'),
('Desert Titan Flock','Flock','Fantasy Creatures','DesertKaiju_FirstFlockChar_BP_C', '"Blueprint\'/Game/Extinction/Dinos/DesertKaiju/DesertKaiju_FirstFlockChar_BP.DesertKaiju_FirstFlockChar_BP\'"'),
('Enforcer','Enforcer','Fantasy Creatures','Enforcer_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/Enforcer/Enforcer_Character_BP.Enforcer_Character_BP\'"'),
('Enraged Corrupted Rex','Elite Rex Corrupt','Dinosaurs','MegaRex_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Rex/MegaRex_Character_BP_Corrupt.MegaRex_Character_BP_Corrupt\'"'),
('Enraged Triceratops','Trike','Dinosaurs','MegaTrike_Character_BP_Corrupt_C', '"Blueprint\'/Game/Extinction/Dinos/Corrupt/Trike/MegaTrike_Character_BP_Corrupt.MegaTrike_Character_BP_Corrupt\'"'),
('Forest Titan','ForestTitan','Fantasy Creatures','ForestKaiju_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/ForestKaiju/ForestKaiju_Character_BP.ForestKaiju_Character_BP\'"'),
('Forest Wyvern','Wyvern','Fantasy Creatures','Wyvern_Character_BP_Fire_Minion_C', '"Blueprint\'/Game/Extinction/Dinos/ForestKaiju/Minion/Wyvern_Character_BP_Fire_Minion.Wyvern_Character_BP_Fire_Minion\'"'),
('Gacha','Gacha','Fantasy Creatures','Gacha_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/Gacha/Gacha_Character_BP.Gacha_Character_BP\'"'),
('GachaClaus','Gacha','Fantasy Creatures','Gacha_Claus_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/Gacha/Gacha_Claus_Character_BP.Gacha_Claus_Character_BP\'"'),
('Gamma King Titan','King Titan','Fantasy Creatures','KingKaiju_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/KingKaiju/KingKaiju_Character_BP.KingKaiju_Character_BP\'"'),
('Gasbags','GasBags','Fantasy Creatures','GasBags_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/GasBag/GasBags_Character_BP.GasBags_Character_BP\'"'),
('Ice Titan','IceTitan','Fantasy Creatures','IceKaiju_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/IceKaiju/IceKaiju_Character_BP.IceKaiju_Character_BP\'"'),
('Managarmr','Managarmr','Fantasy Creatures','IceJumper_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/IceJumper/IceJumper_Character_BP.IceJumper_Character_BP\'"'),
('Mega Mek','MegaMek','Fantasy Creatures','MegaMek_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/Mek/MegaMek_Character_BP.MegaMek_Character_BP\'"'),
('Mek','Mek','Fantasy Creatures','Mek_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/Mek/Mek_Character_BP.Mek_Character_BP\'"'),
('Scout','Scout','Fantasy Creatures','Scout_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/Scout/Scout_Character_BP.Scout_Character_BP\'"'),
('Snow Owl','Owl','Birds','Owl_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/Owl/Owl_Character_BP.Owl_Character_BP\'"'),
('Snow Owl Ghost','Owl','Event Creatures','Ghost_Owl_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/Owl/Ghost_Owl_Character_BP.Ghost_Owl_Character_BP\'"'),
('Velonasaur','Velonasaur','Fantasy Creatures','Spindles_Character_BP_C', '"Blueprint\'/Game/Extinction/Dinos/Spindles/Spindles_Character_BP.Spindles_Character_BP\'"'),
('Alpha Corrupted Master Controller',NULL,'Bosses','VRMainBoss_Character_Hard_C', '"Blueprint\'/Game/Genesis/Dinos/VRMainBoss/VRMainBoss_Character_Hard.VRMainBoss_Character_Hard\'"'),
('Alpha Moeder, Master of the Ocean','EelBoss','Bosses','EelBoss_Character_BP_Hard_C', '"Blueprint\'/Game/Genesis/Dinos/EelBoss/EelBoss_Character_BP_Hard.EelBoss_Character_BP_Hard\'"'),
('Alpha X-Triceratops','Trike','Alpha Creatures','Volcano_Trike_Character_BP_Retrieve_Alpha_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Retrieve/Volcanic/Volcano_Trike_Character_BP_Retrieve_Alpha.Volcano_Trike_Character_BP_Retrieve_Alpha\'"'),
('Astrocetus','Space Whale','Fantasy Creatures','SpaceWhale_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/SpaceWhale/SpaceWhale_Character_BP.SpaceWhale_Character_BP\'"'),
('Beta Corrupted Master Controller',NULL,'Bosses','VRMainBoss_Character_Medium_C', '"Blueprint\'/Game/Genesis/Dinos/VRMainBoss/VRMainBoss_Character_Medium.VRMainBoss_Character_Medium\'"'),
('Beta Moeder, Master of the Ocean','EelBoss','Bosses','EelBoss_Character_BP_Medium_C', '"Blueprint\'/Game/Genesis/Dinos/EelBoss/EelBoss_Character_BP_Medium.EelBoss_Character_BP_Medium\'"'),
('Bloodstalker','Bloodstalker','Fantasy Creatures','BogSpider_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BogSpider/BogSpider_Character_BP.BogSpider_Character_BP\'"'),
('Brute Araneo','Spider','Brute Creatures','SpiderS_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Bog/SpiderS_Character_BP_Hunt.SpiderS_Character_BP_Hunt\'"'),
('Brute Astrocetus','Space Whale','Brute Creatures','SpaceWhale_Character_BP_Brute_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Lunar/SpaceWhale_Character_BP_Brute.SpaceWhale_Character_BP_Brute\'"'),
('Brute Basilosaurus','Basilosaurus','Brute Creatures','Basilosaurus_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Ocean/Basilosaurus_Character_BP_Hunt.Basilosaurus_Character_BP_Hunt\'"'),
('Brute Bloodstalker','Bloodstalker','Brute Creatures','BogSpider_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Bog/BogSpider_Character_BP_Hunt.BogSpider_Character_BP_Hunt\'"'),
('Brute Ferox','Bigly','Brute Creatures','Shapeshifter_Large_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Arctic/Shapeshifter_Large_Character_BP_Hunt.Shapeshifter_Large_Character_BP_Hunt\'"'),
('Brute Fire Wyvern','Wyvern','Brute Creatures','Wyvern_Character_BP_Fire_GauntletBoss_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Gauntlet/Volcanic/Wyvern_Character_BP_Fire_GauntletBoss.Wyvern_Character_BP_Fire_GauntletBoss\'"'),
('Brute Leedsichthys','Leedsichthys','Brute Creatures','Leedsichthys_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Ocean/Leedsichthys_Character_BP_Hunt.Leedsichthys_Character_BP_Hunt\'"'),
('Brute Magmasaur','LavaLizard','Brute Creatures','Cherufe_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Volcanic/Cherufe_Character_BP_Hunt.Cherufe_Character_BP_Hunt\'"'),
('Brute Malfunctioned Tek Giganotosaurus','Gigant','Brute Creatures','BionicGigant_Character_BP_Malfunctioned_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Lunar/BionicGigant_Character_BP_Malfunctioned_Hunt.BionicGigant_Character_BP_Malfunctioned_Hunt\'"'),
('Brute Malfunctioned Tek Rex','Rex','Brute Creatures','BionicRex_Character_BP_Malfunctioned_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Lunar/BionicRex_Character_BP_Malfunctioned_Hunt.BionicRex_Character_BP_Malfunctioned_Hunt\'"'),
('Brute Mammoth','Mammoth','Brute Creatures','Mammoth_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Arctic/Mammoth_Character_BP_Hunt.Mammoth_Character_BP_Hunt\'"'),
('Brute Megaloceros','Stag','Brute Creatures','Stag_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Arctic/Stag_Character_BP_Hunt.Stag_Character_BP_Hunt\'"'),
('Brute Plesiosaur','Plesiosaur','Brute Creatures','Plesiosaur_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Ocean/Plesiosaur_Character_BP_Hunt.Plesiosaur_Character_BP_Hunt\'"'),
('Brute Reaper King','Xenomorph','Brute Creatures','Xenomorph_Character_BP_Male_InitialBuryOnly_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Lunar/Xenomorph_Character_BP_Male_InitialBuryOnly_Hunt.Xenomorph_Character_BP_Male_InitialBuryOnly_Hunt\'"'),
('Brute Sarco','Sarco','Brute Creatures','Sarco_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Bog/Sarco_Character_BP_Hunt.Sarco_Character_BP_Hunt\'"'),
('Brute Seeker','Seeker','Brute Creatures','Pteroteuthis_Char_BP_HuntFollower_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Lunar/Pteroteuthis_Char_BP_HuntFollower.Pteroteuthis_Char_BP_HuntFollower\'"'),
('Brute Tusoteuthis','Tusoteuthis','Brute Creatures','Tusoteuthis_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Ocean/Tusoteuthis_Character_BP_Hunt.Tusoteuthis_Character_BP_Hunt\'"'),
('Brute X-Allosaurus','Allo','Brute Creatures','Volcano_Allo_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Volcanic/Volcano_Allo_Character_BP_Hunt.Volcano_Allo_Character_BP_Hunt\'"'),
('Brute X-Megalodon','Mega','Brute Creatures','Ocean_Megalodon_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Ocean/Ocean_Megalodon_Character_BP_Hunt.Ocean_Megalodon_Character_BP_Hunt\'"'),
('Brute X-Mosasaurus','Mosasaur','Brute Creatures','Ocean_Mosa_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Ocean/Ocean_Mosa_Character_BP_Hunt.Ocean_Mosa_Character_BP_Hunt\'"'),
('Brute X-Raptor','Raptor','Brute Creatures','Bog_Raptor_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Bog/Bog_Raptor_Character_BP_Hunt.Bog_Raptor_Character_BP_Hunt\'"'),
('Brute X-Rex','Rex','Brute Creatures','Volcano_Rex_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Volcanic/Volcano_Rex_Character_BP_Hunt.Volcano_Rex_Character_BP_Hunt\'"'),
('Brute X-Rock Elemental','RockElemental','Brute Creatures','Volcano_Golem_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Volcanic/Volcano_Golem_Character_BP_Hunt.Volcano_Golem_Character_BP_Hunt\'"'),
('Brute X-Spino','Spino','Brute Creatures','Bog_Spino_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Bog/Bog_Spino_Character_BP_Hunt.Bog_Spino_Character_BP_Hunt\'"'),
('Brute X-Yutyrannus','Yutyrannus','Brute Creatures','Snow_Yutyrannus_Character_BP_Hunt_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Hunt/Arctic/Snow_Yutyrannus_Character_BP_Hunt.Snow_Yutyrannus_Character_BP_Hunt\'"'),
('Corrupted Avatar','?','Mammals','Bot_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/Bots/Bot_Character_BP.Bot_Character_BP\'"'),
('Eel Minion',NULL,'Fantasy Creatures','EelMinion_Character_BP_Easy_C', '"Blueprint\'/Game/Genesis/Dinos/EelBoss/EelMinion_Character_BP_Easy.EelMinion_Character_BP_Easy\'"'),
('Gamma Corrupted Master Controller',NULL,'Bosses','VRMainBoss_Character_Easy_C', '"Blueprint\'/Game/Genesis/Dinos/VRMainBoss/VRMainBoss_Character_Easy.VRMainBoss_Character_Easy\'"'),
('Gamma Moeder, Master of the Ocean','EelBoss','Bosses','EelBoss_Character_BP_Easy_C', '"Blueprint\'/Game/Genesis/Dinos/EelBoss/EelBoss_Character_BP_Easy.EelBoss_Character_BP_Easy\'"'),
('Golden Striped Brute Megalodon','Mega','Brute Creatures','Ocean_Megalodon_Character_BP_Retrieve_Brute_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Retrieve/Ocean/Ocean_Megalodon_Character_BP_Retrieve_Brute.Ocean_Megalodon_Character_BP_Retrieve_Brute\'"'),
('Golden Striped Megalodon','Mega','X-Creatures','Ocean_Megalodon_Character_BP_Retrieve_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Retrieve/Ocean/Ocean_Megalodon_Character_BP_Retrieve.Ocean_Megalodon_Character_BP_Retrieve\'"'),
('Ferox (Large)','Bigly','Fantasy Creatures','Shapeshifter_Large_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/Shapeshifter/Shapeshifter_Large/Shapeshifter_Large_Character_BP.Shapeshifter_Large_Character_BP\'"'),
('Ferox','Gremlin','Fantasy Creatures','Shapeshifter_Small_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/Shapeshifter/Shapeshifter_Small/Shapeshifter_Small_Character_BP.Shapeshifter_Small_Character_BP\'"'),
('Injured Brute Reaper King','Xenomorph','Brute Creatures','Xenomorph_Character_BP_Male_InitialBuryOnly_Brute_Retrieve_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Retrieve/Lunar/Xenomorph_Character_BP_Male_InitialBuryOnly_Brute_Retrieve.Xenomorph_Character_BP_Male_InitialBuryOnly_Brute_Retrieve\'"'),
('Insect Swarm','InsectSwarm','Fantasy Creatures','InsectSwarmChar_BP_C', '"Blueprint\'/Game/Genesis/Dinos/Swarms/InsectSwarmChar_BP.InsectSwarmChar_BP\'"'),
('Magmasaur','LavaLizard','Fantasy Creatures','Cherufe_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/Cherufe/Cherufe_Character_BP.Cherufe_Character_BP\'"'),
('Malfunctioned Tek Giganotosaurus Gauntlet','Gigant','Malfunctioned Tek Creatures','BionicGigant_Character_BP_Malfunctioned_Gauntlet_C', '"Blueprint\'/Game/Genesis/Dinos/MissionVariants/Gauntlet/Lunar/BionicGigant_Character_BP_Malfunctioned_Gauntlet.BionicGigant_Character_BP_Malfunctioned_Gauntlet\'"'),
('Malfunctioned Tek Giganotosaurus','Gigant','Malfunctioned Tek Creatures','BionicGigant_Character_BP_Malfunctioned_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Giganotosaurus/BionicGigant_Character_BP_Malfunctioned.BionicGigant_Character_BP_Malfunctioned\'"'),
('Malfunctioned Tek Parasaur','Para','Malfunctioned Tek Creatures','BionicPara_Character_BP_Malfunctioned_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Para/BionicPara_Character_BP_Malfunctioned.BionicPara_Character_BP_Malfunctioned\'"'),
('Malfunctioned Tek Quetzal','Quetz','Malfunctioned Tek Creatures','BionicQuetz_Character_BP_Malfunctioned_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Quetzalcoatlus/BionicQuetz_Character_BP_Malfunctioned.BionicQuetz_Character_BP_Malfunctioned\'"'),
('Malfunctioned Tek Raptor','Raptor','Malfunctioned Tek Creatures','BionicRaptor_Character_BP_Malfunctioned_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Raptor/BionicRaptor_Character_BP_Malfunctioned.BionicRaptor_Character_BP_Malfunctioned\'"'),
('Malfunctioned Tek Rex','Rex','Malfunctioned Tek Creatures','BionicRex_Character_BP_Malfunctioned_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Rex/BionicRex_Character_BP_Malfunctioned.BionicRex_Character_BP_Malfunctioned\'"'),
('Malfunctioned Tek Stegosaurus','Stego','Malfunctioned Tek Creatures','BionicStego_Character_BP_Malfunctioned_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Stego/BionicStego_Character_BP_Malfunctioned.BionicStego_Character_BP_Malfunctioned\'"'),
('Malfunctioned Tek Triceratops','Trike','Malfunctioned Tek Creatures','BionicTrike_Character_BP_Malfunctioned_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Trike/BionicTrike_Character_BP_Malfunctioned.BionicTrike_Character_BP_Malfunctioned\'"'),
('Megachelon','GiantTurtle','Fantasy Creatures','GiantTurtle_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/GiantTurtle/GiantTurtle_Character_BP.GiantTurtle_Character_BP\'"'),
('Parakeet Fish School','Swarm','Fantasy Creatures','MicrobeSwarmChar_BP_C', '"Blueprint\'/Game/Genesis/Dinos/Swarms/MicrobeSwarmChar_BP.MicrobeSwarmChar_BP\'"'),
('Reaper Prince','Xenomorph','Fantasy Creatures','Xenomorph_Character_BP_Male_InitialBuryOnly_Adolescent_C', '"Blueprint\'/Game/Aberration/Dinos/Nameless/Xenomorph_Character_BP_Male_InitialBuryOnly_Adolescent.Xenomorph_Character_BP_Male_InitialBuryOnly_Adolescent\'"'),
('Tek Triceratops','Trike','Tek Creatures','BionicTrike_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Trike/BionicTrike_Character_BP.BionicTrike_Character_BP\'"'),
('X-Allosaurus','Allo','X-Creatures','Volcano_Allo_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Volcano_Allosaurus/Volcano_Allo_Character_BP.Volcano_Allo_Character_BP\'"'),
('X-Ankylosaurus','Anky','X-Creatures','Volcano_Ankylo_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Volcano_Ankylosaurus/Volcano_Ankylo_Character_BP.Volcano_Ankylo_Character_BP\'"'),
('X-Argentavis','Argent','X-Creatures','Snow_Argent_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Snow_Argentavis/Snow_Argent_Character_BP.Snow_Argent_Character_BP\'"'),
('X-Basilosaurus','Basilosaurus','X-Creatures','Ocean_Basilosaurus_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Ocean_Basilosaurus/Ocean_Basilosaurus_Character_BP.Ocean_Basilosaurus_Character_BP\'"'),
('X-Dunkleosteus','Dunkle','X-Creatures','Ocean_Dunkle_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Ocean_Dunkleosteus/Ocean_Dunkle_Character_BP.Ocean_Dunkle_Character_BP\'"'),
('X-Ichthyosaurus','Dolphin','X-Creatures','Ocean_Dolphin_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Ocean_Dolphin/Ocean_Dolphin_Character_BP.Ocean_Dolphin_Character_BP\'"'),
('X-Megalodon','Mega','X-Creatures','Ocean_Megalodon_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Ocean_Megalodon/Ocean_Megalodon_Character_BP.Ocean_Megalodon_Character_BP\'"'),
('X-Mosasaurus','Mosasaur','X-Creatures','Ocean_Mosa_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Ocean_Mosasaurus/Ocean_Mosa_Character_BP.Ocean_Mosa_Character_BP\'"'),
('X-Otter','Otter','X-Creatures','Snow_Otter_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Snow_Otter/Snow_Otter_Character_BP.Snow_Otter_Character_BP\'"'),
('X-Paraceratherium','Paracer','X-Creatures','Bog_Paracer_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/BogParaceratherium/Bog_Paracer_Character_BP.Bog_Paracer_Character_BP\'"'),
('X-Parasaur','Para','X-Creatures','Bog_Para_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/BogPara/Bog_Para_Character_BP.Bog_Para_Character_BP\'"'),
('X-Raptor','Raptor','X-Creatures','Bog_Raptor_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Bog_Raptor/Bog_Raptor_Character_BP.Bog_Raptor_Character_BP\'"'),
('X-Rex','Rex','X-Creatures','Volcano_Rex_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Volcano_Rex/Volcano_Rex_Character_BP.Volcano_Rex_Character_BP\'"'),
('X-Rock Elemental','RockElemental','X-Creatures','Volcano_Golem_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Lava_Golem/Volcano_Golem_Character_BP.Volcano_Golem_Character_BP\'"'),
('X-Sabertooth','Sabertooth','X-Creatures','Snow_Saber_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Snow_Saber/Snow_Saber_Character_BP.Snow_Saber_Character_BP\'"'),
('X-Sabertooth Salmon','Salmon','X-Creatures','Lunar_Salmon_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Lunar_Salmon/Lunar_Salmon_Character_BP.Lunar_Salmon_Character_BP\'"'),
('X-Spino','Spino','X-Creatures','Bog_Spino_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Bog_Spino/Bog_Spino_Character_BP.Bog_Spino_Character_BP\'"'),
('X-Tapejara','Tapejara','X-Creatures','Bog_Tapejara_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Bog_Tapejara/Bog_Tapejara_Character_BP.Bog_Tapejara_Character_BP\'"'),
('X-Triceratops','Trike','X-Creatures','Volcano_Trike_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Volcano_Trike/Volcano_Trike_Character_BP.Volcano_Trike_Character_BP\'"'),
('X-Woolly Rhino','Rhino','X-Creatures','Snow_Rhino_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Snow_WoollyRhino/Snow_Rhino_Character_BP.Snow_Rhino_Character_BP\'"'),
('X-Yutyrannus','Yutyrannus','X-Creatures','Snow_Yutyrannus_Character_BP_C', '"Blueprint\'/Game/Genesis/Dinos/BiomeVariants/Snow_Yutyrannus/Snow_Yutyrannus_Character_BP.Snow_Yutyrannus_Character_BP\'"'),
('Astrodelphis','Astrodelphis','Fantasy Creatures','SpaceDolphin_Character_BP_C', '"Blueprint\'/Game/Genesis2/Dinos/SpaceDolphin/SpaceDolphin_Character_BP.SpaceDolphin_Character_BP\'"'),
('Maewing','Maewing','Fantasy Creatures','MilkGlider_Character_BP_C', '"Blueprint\'/Game/Genesis2/Dinos/MilkGlider/MilkGlider_Character_BP.MilkGlider_Character_BP\'"'),
('Noglin','BrainSlug','Fantasy Creatures','BrainSlug_Character_BP_C', '"Blueprint\'/Game/Genesis2/Dinos/BrainSlug/BrainSlug_Character_BP.BrainSlug_Character_BP\'"'),
('Shadowmane','Lionfish Lion','Fantasy Creatures','LionfishLion_Character_BP_C', '"Blueprint\'/Game/Genesis2/Dinos/LionfishLion/LionfishLion_Character_BP.LionfishLion_Character_BP\'"'),
('Tek Stryder','TekStrider','Mechanical Creatures','TekStrider_Character_BP_C', '"Blueprint\'/Game/Genesis2/Dinos/TekStrider/TekStrider_Character_BP.TekStrider_Character_BP\'"'),
('Voidwyrm','TekWyvern','Mechanical Creatures','TekWyvern_Character_BP_C', '"Blueprint\'/Game/Genesis2/Dinos/TekWyvern/TekWyvern_Character_BP.TekWyvern_Character_BP\'"'),
('R-Allosaurus','Allo','R-Creatures','Allo_Character_BP_Rockwell_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Allo_Character_BP_Rockwell.Allo_Character_BP_Rockwell\'"'),
('R-Carnotaurus','Carno','R-Creatures','Carno_Character_BP_Rockwell_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Carno_Character_BP_Rockwell.Carno_Character_BP_Rockwell\'"'),
('R-Daeodon','Daeodon','R-Creatures','Daeodon_Character_BP_Eden_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Daeodon_Character_BP_Eden.Daeodon_Character_BP_Eden\'"'),
('R-Dilophosaur','Dilo','R-Creatures','Dilo_Character_BP_Rockwell_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Dilo_Character_BP_Rockwell.Dilo_Character_BP_Rockwell\'"'),
('R-Dire Bear','Direbear','R-Creatures','Direbear_Character_BP_Rockwell_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Direbear_Character_BP_Rockwell.Direbear_Character_BP_Rockwell\'"'),
('R-Direwolf','Direwolf','R-Creatures','Direwolf_Character_BP_Eden_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Direwolf_Character_BP_Eden.Direwolf_Character_BP_Eden\'"'),
('R-Equus','Equus','R-Creatures','Equus_Character_BP_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Equus_Character_BP_Eden.Equus_Character_BP_Eden\'"'),
('R-Gasbags','GasBags','R-Creatures','GasBags_Character_BP_Eden_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/GasBags_Character_BP_Eden.GasBags_Character_BP_Eden\'"'),
('R-Giganotosaurus','Gigant','R-Creatures','Gigant_Character_BP_Rockwell_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Gigant_Character_BP_Rockwell.Gigant_Character_BP_Rockwell\'"'),
('R-Megatherium','Megatherium','R-Creatures','Megatherium_Character_BP_Eden_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Megatherium_Character_BP_Eden.Megatherium_Character_BP_Eden\'"'),
('R-Snow Owl','Owl','R-Creatures','Owl_Character_BP_Eden_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Owl_Character_BP_Eden.Owl_Character_BP_Eden\'"'),
('R-Parasaur','Para','R-Creatures','Para_Character_BP_Eden_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Para_Character_BP_Eden.Para_Character_BP_Eden\'"'),
('R-Procoptodon','Kangaroo','R-Creatures','Procoptodon_Character_BP_Eden_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Procoptodon_Character_BP_Eden.Procoptodon_Character_BP_Eden\'"'),
('R-Quetzal','Quetz','R-Creatures','Quetz_Character_BP_Rockwell_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Quetz_Character_BP_Rockwell.Quetz_Character_BP_Rockwell\'"'),
('R-Brontosaurus','Bronto','R-Creatures','Sauropod_Character_BP_Rockwell_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Sauropod_Character_BP_Rockwell.Sauropod_Character_BP_Rockwell\'"'),
('R-Velonasaur','Velonasaur','R-Creatures','Spindles_Character_BP_Rockwell_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Spindles_Character_BP_Rockwell.Spindles_Character_BP_Rockwell\'"'),
('R-Thylacoleo','Thylacoleo','R-Creatures','Thylacoleo_Character_BP_Eden_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Thylacoleo_Character_BP_Eden.Thylacoleo_Character_BP_Eden\'"'),
('R-Carbonemys','Turtle','R-Creatures','Turtle_Character_BP_Rockwell_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Turtle_Character_BP_Rockwell.Turtle_Character_BP_Rockwell\'"'),
('R-Reaper Queen','Xenomorph','R-Creatures','Xenomorph_Character_BP_Female_Gen2_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Xenomorph_Character_BP_Female_Gen2.Xenomorph_Character_BP_Female_Gen2\'"'),
('R-Reaper King','Xenomorph','R-Creatures','Xenomorph_Character_BP_Male_Gen2_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Xenomorph_Character_BP_Male_Gen2.Xenomorph_Character_BP_Male_Gen2\'"'),
('R-Reaper King (Tamed)','Xenomorph','R-Creatures','Xenomorph_Character_BP_Male_Tamed_Gen2_C', '"Blueprint\'/Game/Genesis2/Dinos/BiomeVariants/Xenomorph_Character_BP_Male_Tamed_Gen2.Xenomorph_Character_BP_Male_Tamed_Gen2\'"'),
('Summoner','Summoner','Fantasy Creatures','Summoner_Character_BP_C', '"Blueprint\'/Game/Genesis2/Dinos/Summoner/Summoner_Character_BP.Summoner_Character_BP\'"'),
('Macrophage','Macrophage','Fantasy Creatures','Macrophage_Swarm_Character_C', '"Blueprint\'/Game/Genesis2/Dinos/Macrophage/Macrophage_Swarm_Character.Macrophage_Swarm_Character\'"'),
('Exo-Mek','Exosuit','Vehicles','Exosuit_Character_BP_C', '"Blueprint\'/Game/Genesis2/Dinos/Exosuit/Exosuit_Character_BP.Exosuit_Character_BP\'"'),
('Rockwell Prime','RockwellPrime','Bosses','RockwellNode_Character_BP_Boss_C', '"Blueprint\'/Game/Genesis2/Missions/ModularMission/FinalBattleAlt/Dinos/RockwellNode_Character_BP_Boss.RockwellNode_Character_BP_Boss\'"'),
('Rockwell Prime (Alpha)','RockwellPrime','Bosses','RockwellNode_Character_BP_Boss_Alpha_C', '"Blueprint\'/Game/Genesis2/Missions/ModularMission/FinalBattleAlt/Difficulties/Alpha/RockwellNode_Character_BP_Boss_Alpha.RockwellNode_Character_BP_Boss_Alpha\'"'),
('Rockwell Prime (Beta)','RockwellPrime','Bosses','RockwellNode_Character_BP_Boss_Beta_C', '"Blueprint\'/Game/Genesis2/Missions/ModularMission/FinalBattleAlt/Difficulties/Beta/RockwellNode_Character_BP_Boss_Beta.RockwellNode_Character_BP_Boss_Beta\'"'),
('Rockwell Prime (Gamma)','RockwellPrime','Bosses','RockwellNode_Character_BP_Boss_Gamma_C', '"Blueprint\'/Game/Genesis2/Missions/ModularMission/FinalBattleAlt/Difficulties/Gamma/RockwellNode_Character_BP_Boss_Gamma.RockwellNode_Character_BP_Boss_Gamma\'"'),
('Rockwell Node','RockwellPrime','Bosses','RockwellNode_Character_BP_FinalFight_C', '"Blueprint\'/Game/Genesis2/Missions/ModularMission/FinalBattleAlt/Dinos/RockwellNode_Character_BP_FinalFight.RockwellNode_Character_BP_FinalFight\'"'),
('Rockwell Node (Alpha)','RockwellPrime','Bosses','RockwellNode_Character_BP_FinalFight_Alpha_C', '"Blueprint\'/Game/Genesis2/Missions/ModularMission/FinalBattleAlt/Difficulties/Alpha/RockwellNode_Character_BP_FinalFight_Alpha.RockwellNode_Character_BP_FinalFight_Alpha\'"'),
('Rockwell Node (Beta)','RockwellPrime','Bosses','RockwellNode_Character_BP_FinalFight_Beta_C', '"Blueprint\'/Game/Genesis2/Missions/ModularMission/FinalBattleAlt/Difficulties/Beta/RockwellNode_Character_BP_FinalFight_Beta.RockwellNode_Character_BP_FinalFight_Beta\'"'),
('Rockwell Node (Gamma)','RockwellPrime','Bosses','RockwellNode_Character_BP_FinalFight_Gamma_C', '"Blueprint\'/Game/Genesis2/Missions/ModularMission/FinalBattleAlt/Difficulties/Gamma/RockwellNode_Character_BP_FinalFight_Gamma.RockwellNode_Character_BP_FinalFight_Gamma\'"'),
('Achatina','Achatina','Invertebrates','Achatina_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Achatina/Achatina_Character_BP.Achatina_Character_BP\'"'),
('Allosaurus','Allo','Dinosaurs','Allo_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Allosaurus/Allo_Character_BP.Allo_Character_BP\'"'),
('Alpha Carno','Elite Carno','Alpha Creatures','MegaCarno_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Carno/MegaCarno_Character_BP.MegaCarno_Character_BP\'"'),
('Alpha Leedsichthys','Leedsichthys','Alpha Creatures','Alpha_Leedsichthys_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Leedsichthys/Alpha_Leedsichthys_Character_BP.Alpha_Leedsichthys_Character_BP\'"'),
('Alpha Megalodon','Elite Mega','Alpha Creatures','MegaMegalodon_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Megalodon/MEgaMegalodon_Character_BP.MegaMegalodon_Character_BP\'"'),
('Alpha Mosasaur','Mosasaur','Alpha Creatures','Mosa_Character_BP_Mega_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Mosasaurus/Mosa_Character_BP_Mega.Mosa_Character_BP_Mega\'"'),
('Alpha Raptor','Elite Raptor','Alpha Creatures','MegaRaptor_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Raptor/MegaRaptor_Character_BP.MegaRaptor_Character_BP\'"'),
('Alpha T-Rex','Elite Rex','Alpha Creatures','MegaRex_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Rex/MegaRex_Character_BP.MegaRex_Character_BP\'"'),
('Alpha Tusoteuthis','Tusoteuthis','Alpha Creatures','Mega_Tusoteuthis_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Tusoteuthis/Mega_Tusoteuthis_Character_BP.Mega_Tusoteuthis_Character_BP\'"'),
('Ammonite','Ammonite','Invertebrates','Ammonite_Character_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Ammonite/Ammonite_Character.Ammonite_Character\'"'),
('Anglerfish','Angler','Fish','Angler_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Anglerfish/Angler_Character_BP.Angler_Character_BP\'"'),
('Ankylosaurus','Anky','Dinosaurs','Ankylo_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Ankylo/Ankylo_Character_BP.Ankylo_Character_BP\'"'),
('Araneo','Spider','Invertebrates','SpiderS_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Spider-Small/SpiderS_Character_BP.SpiderS_Character_BP\'"'),
('Archaeopteryx','Archa','Birds','Archa_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Archaeopteryx/Archa_Character_BP.Archa_Character_BP\'"'),
('Argentavis','Argent','Birds','Argent_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Argentavis/Argent_Character_BP.Argent_Character_BP\'"'),
('Arthropluera','Arthro','Invertebrates','Arthro_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Arthropluera/Arthro_Character_BP.Arthro_Character_BP\'"'),
('Baryonyx','Baryonyx','Dinosaurs','Baryonyx_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Baryonyx/Baryonyx_Character_BP.Baryonyx_Character_BP\'"'),
('Basilosaurus','Basilosaurus','Mammals','Basilosaurus_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Basilosaurus/Basilosaurus_Character_BP.Basilosaurus_Character_BP\'"'),
('Beelzebufo','Toad','Reptiles','Toad_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Toad/Toad_Character_BP.Toad_Character_BP\'"'),
('Bunny Dodo','Dodo','Event Creatures',NULL, '"Blueprint\'/Game/PrimalEarth/Dinos/Dodo/Dodo_Character_BP_Bunny.Dodo_Character_BP_Bunny\'"'),
('Bunny Oviraptor','Ovi','Event Creatures',NULL, '"Blueprint\'/Game/PrimalEarth/Dinos/Oviraptor/BunnyOviraptor_Character_BP.BunnyOviraptor_Character_BP\'"'),
('Brontosaurus','Bronto','Dinosaurs','Sauropod_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Sauropod/Sauropod_Character_BP.Sauropod_Character_BP\'"'),
('Broodmother Lysrix',NULL,'Bosses','SpiderL_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Spider-Large/SpiderL_Character_BP.SpiderL_Character_BP\'"'),
('Chalicotherium','Chalicotherium','Mammals','Chalico_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Chalicotherium/Chalico_Character_BP.Chalico_Character_BP\'"'),
('Carbonemys','Turtle','Reptiles','Turtle_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Turtle/Turtle_Character_BP.Turtle_Character_BP\'"'),
('Carnotaurus','Carno','Dinosaurs','Carno_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Carno/Carno_Character_BP.Carno_Character_BP\'"'),
('Castoroides','Beaver','Mammals','Beaver_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Beaver/Beaver_Character_BP.Beaver_Character_BP\'"'),
('Cnidaria','Cnidaria','Invertebrates','Cnidaria_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Cnidaria/Cnidaria_Character_BP.Cnidaria_Character_BP\'"'),
('Coelacanth','Coel','Fish','Coel_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Coelacanth/Coel_Character_BP.Coel_Character_BP\'"'),
('Compy','Compy','Dinosaurs','Compy_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Compy/Compy_Character_BP.Compy_Character_BP\'"'),
('Daeodon','Daeodon','Mammals','Daeodon_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Daeodon/Daeodon_Character_BP.Daeodon_Character_BP\'"'),
('Dilophosaur','Dilo','Dinosaurs','Dilo_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dilo/Dilo_Character_BP.Dilo_Character_BP\'"'),
('Dimetrodon','Dimetro','Dinosaurs','Dimetro_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dimetrodon/Dimetro_Character_BP.Dimetro_Character_BP\'"'),
('Dimorphodon','Dimorph','Dinosaurs','Dimorph_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dimorphodon/Dimorph_Character_BP.Dimorph_Character_BP\'"'),
('Diplocaulus','Diplocaulus','Amphibians','Diplocaulus_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Diplocaulus/Diplocaulus_Character_BP.Diplocaulus_Character_BP\'"'),
('Diplodocus','Diplo','Dinosaurs','Diplodocus_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Diplodocus/Diplodocus_Character_BP.Diplodocus_Character_BP\'"'),
('Dire Bear','Direbear','Mammals','Direbear_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Direbear/Direbear_Character_BP.Direbear_Character_BP\'"'),
('Direwolf','Direwolf','Mammals','Direwolf_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Direwolf/Direwolf_Character_BP.Direwolf_Character_BP\'"'),
('Direwolf Ghost','Direwolf','Event Creatures','Ghost_Direwolf_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Direwolf/Ghost_Direwolf_Character_BP.Ghost_Direwolf_Character_BP\'"'),
('Dodo','Dodo','Birds','Dodo_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dodo/Dodo_Character_BP.Dodo_Character_BP\'"'),
('DodoRex','DodoRex','Event Creatures','DodoRex_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/DodoRex/DodoRex_Character_BP.DodoRex_Character_BP\'"'),
('Doedicurus','Doed','Mammals','Doed_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Doedicurus/Doed_Character_BP.Doed_Character_BP\'"'),
('Dragon (Gamma)',NULL,'Bosses','Dragon_Character_BP_Boss_Easy_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dragon/Dragon_Character_BP_Boss_Easy.Dragon_Character_BP_Boss_Easy\'"'),
('Dragon (Beta)',NULL,'Bosses','Dragon_Character_BP_Boss_Medium_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dragon/Dragon_Character_BP_Boss_Medium.Dragon_Character_BP_Boss_Medium\'"'),
('Dragon (Alpha)',NULL,'Bosses','Dragon_Character_BP_Boss_Hard_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dragon/Dragon_Character_BP_Boss_Hard.Dragon_Character_BP_Boss_Hard\'"'),
('Dung Beetle','Bettle','Invertebrates','DungBeetle_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/DungBeetle/DungBeetle_Character_BP.DungBeetle_Character_BP\'"'),
('Dunkleosteus','Dunkle','Fish','Dunkle_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dunkleosteus/Dunkle_Character_BP.Dunkle_Character_BP\'"'),
('Electrophorus','Eel','Fish','Eel_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Eel/Eel_Character_BP.Eel_Character_BP\'"'),
('Equus','Equus','Mammals','Equus_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Equus/Equus_Character_BP.Equus_Character_BP\'"'),
('Unicorn','Equus','Mammals','Equus_Character_BP_Unicorn_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Equus/Equus_Character_BP_Unicorn.Equus_Character_BP_Unicorn\'"'),
('Eurypterid','Euryp','Invertebrates','Euryp_Character_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Eurypterid/Euryp_Character.Euryp_Character\'"'),
('Gallimimus','Galli','Dinosaurs','Galli_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Gallimimus/Galli_Character_BP.Galli_Character_BP\'"'),
('Giant Bee','Bee','Invertebrates','Bee_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Bee/Bee_Character_BP.Bee_Character_BP\'"'),
('Giganotosaurus','Gigant','Dinosaurs','Gigant_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Giganotosaurus/Gigant_Character_BP.Gigant_Character_BP\'"'),
('Gigantopithecus','Bigfoot','Mammals','Bigfoot_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Bigfoot/Bigfoot_Character_BP.Bigfoot_Character_BP\'"'),
('Hesperornis','Hesperornis','Birds','Hesperornis_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Hesperornis/Hesperornis_Character_BP.Hesperornis_Character_BP\'"'),
('Human (Male)',NULL,'Mammals',NULL, '"Blueprint\'/Game/PrimalEarth/CoreBlueprints/PlayerPawnTest_Male.PlayerPawnTest_Male\'"'),
('Human (Female)',NULL,'Mammals',NULL, '"Blueprint\'/Game/PrimalEarth/CoreBlueprints/PlayerPawnTest_Female.PlayerPawnTest_Female\'"'),
('Hyaenodon','Hyaenodon','Mammals','Hyaenodon_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Hyaenodon/Hyaenodon_Character_BP.Hyaenodon_Character_BP\'"'),
('Ichthyornis','Ichthyornis','Birds','Ichthyornis_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Ichthyornis/Ichthyornis_Character_BP.Ichthyornis_Character_BP\'"'),
('Ichthyosaurus','Dolphin','Reptiles','Dolphin_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dolphin/Dolphin_Character_BP.Dolphin_Character_BP\'"'),
('Iguanodon','Iguanodon','Dinosaurs','Iguanodon_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Iguanodon/Iguanodon_Character_BP.Iguanodon_Character_BP\'"'),
('Kairuku','Kairu','Birds','Kairuku_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Kairuku/Kairuku_Character_BP.Kairuku_Character_BP\'"'),
('Kaprosuchus','Kaprosuchus','Reptiles','Kaprosuchus_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Kaprosuchus/Kaprosuchus_Character_BP.Kaprosuchus_Character_BP\'"'),
('Kentrosaurus','Kentro','Dinosaurs','Kentro_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Kentrosaurus/Kentro_Character_BP.Kentro_Character_BP\'"'),
('Leech','Leech','Invertebrates','Leech_Character_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Leech/Leech_Character.Leech_Character\'"'),
('Diseased Leech','Leech','Invertebrates','Leech_Character_Diseased_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Leech/Leech_Character_Diseased.Leech_Character_Diseased\'"'),
('Leedsichthys','Leedsichthys','Fish','Leedsichthys_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Leedsichthys/Leedsichthys_Character_BP.Leedsichthys_Character_BP\'"'),
('Liopleurodon','Liopleurodon','Reptiles','Liopleurodon_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Liopleurodon/Liopleurodon_Character_BP.Liopleurodon_Character_BP\'"'),
('Lystrosaurus','Lystro','Dinosaurs','Lystro_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Lystrosaurus/Lystro_Character_BP.Lystro_Character_BP\'"'),
('Mammoth','Mammoth','Mammals','Mammoth_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Mammoth/Mammoth_Character_BP.Mammoth_Character_BP\'"'),
('Manta','Manta','Fish','Manta_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Manta/Manta_Character_BP.Manta_Character_BP\'"'),
('Megalania','Megalania','Reptiles','Megalania_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Megalania/Megalania_Character_BP.Megalania_Character_BP\'"'),
('Megaloceros','Stag','Mammals','Stag_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Stag/Stag_Character_BP.Stag_Character_BP\'"'),
('Megalodon','Mega','Fish','Megalodon_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Megalodon/Megalodon_Character_BP.Megalodon_Character_BP\'"'),
('Megalosaurus','Megalosaurus','Dinosaurs','Megalosaurus_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Megalosaurus/Megalosaurus_Character_BP.Megalosaurus_Character_BP\'"'),
('Meganeura','Dragonfly','Invertebrates','Dragonfly_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dragonfly/Dragonfly_Character_BP.Dragonfly_Character_BP\'"'),
('Megapithecus',NULL,'Bosses','Gorilla_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Gorilla/Gorilla_Character_BP.Gorilla_Character_BP\'"'),
('Megatherium','Megatherium','Mammals','Megatherium_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Megatherium/Megatherium_Character_BP.Megatherium_Character_BP\'"'),
('Mesopithecus','Monkey','Mammals','Monkey_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Monkey/Monkey_Character_BP.Monkey_Character_BP\'"'),
('Microraptor','Microraptor','Dinosaurs','Microraptor_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Microraptor/Microraptor_Character_BP.Microraptor_Character_BP\'"'),
('Mosasaurus','Mosasaur','Reptiles','Mosa_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Mosasaurus/Mosa_Character_BP.Mosa_Character_BP\'"'),
('Moschops','Moschops','Dinosaurs','Moschops_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Moschops/Moschops_Character_BP.Moschops_Character_BP\'"'),
('Onychonycteris','Bat','Mammals','Bat_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Bat/Bat_Character_BP.Bat_Character_BP\'"'),
('Otter','Otter','Mammals','Otter_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Otter/Otter_Character_BP.Otter_Character_BP\'"'),
('Oviraptor','Ovi','Dinosaurs','Oviraptor_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Oviraptor/Oviraptor_Character_BP.Oviraptor_Character_BP\'"'),
('Ovis','Sheep','Mammals','Sheep_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Sheep/Sheep_Character_BP.Sheep_Character_BP\'"'),
('Pachy','Pachy','Dinosaurs','Pachy_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Pachy/Pachy_Character_BP.Pachy_Character_BP\'"'),
('Pachyrhinosaurus','Pachyrhinosaurus','Dinosaurs','Pachyrhino_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Pachyrhinosaurus/Pachyrhino_Character_BP.Pachyrhino_Character_BP\'"'),
('Paraceratherium','Paracer','Mammals','Paracer_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Paraceratherium/Paracer_Character_BP.Paracer_Character_BP\'"'),
('Parasaurolophus','Para','Dinosaurs','Para_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Para/Para_Character_BP.Para_Character_BP\'"'),
('Pegomastax','Pegomastax','Dinosaurs','Pegomastax_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Pegomastax/Pegomastax_Character_BP.Pegomastax_Character_BP\'"'),
('Pelagornis','Pela','Birds','Pela_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Pelagornis/Pela_Character_BP.Pela_Character_BP\'"'),
('Phiomia','Phiomia','Mammals','Phiomia_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Phiomia/Phiomia_Character_BP.Phiomia_Character_BP\'"'),
('Piranha','Piranha','Fish','Piranha_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Piranha/Piranha_Character_BP.Piranha_Character_BP\'"'),
('Plesiosaur','Plesiosaur','Reptiles','Plesiosaur_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Plesiosaur/Plesiosaur_Character_BP.Plesiosaur_Character_BP\'"'),
('Procoptodon','Kangaroo','Mammals','Procoptodon_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Procoptodon/Procoptodon_Character_BP.Procoptodon_Character_BP\'"'),
('Pteranodon','Ptera','Dinosaurs','Ptero_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Ptero/Ptero_Character_BP.Ptero_Character_BP\'"'),
('Pulmonoscorpius','Scorpion','Invertebrates','Scorpion_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Scorpion/Scorpion_Character_BP.Scorpion_Character_BP\'"'),
('Purlovia','Purlovia','Synapsids','Purlovia_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Purlovia/Purlovia_Character_BP.Purlovia_Character_BP\'"'),
('Quetzalcoatlus','Quetz','Reptiles','Quetz_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Quetzalcoatlus/Quetz_Character_BP.Quetz_Character_BP\'"'),
('Raptor','Raptor','Dinosaurs','Raptor_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Raptor/Raptor_Character_BP.Raptor_Character_BP\'"'),
('Rex','Rex','Dinosaurs','Rex_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Rex/Rex_Character_BP.Rex_Character_BP\'"'),
('Rex Ghost','Rex','Event Creatures','Ghost_Rex_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Rex/Ghost_Rex_Character_BP.Ghost_Rex_Character_BP\'"'),
('Sabertooth','Sabertooth','Mammals','Saber_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Saber/Saber_Character_BP.Saber_Character_BP\'"'),
('Sabertooth Salmon','Salmon','Fish','Salmon_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Salmon/Salmon_Character_BP.Salmon_Character_BP\'"'),
('Sarco','Sarco','Reptiles','Sarco_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Sarco/Sarco_Character_BP.Sarco_Character_BP\'"'),
('Skeletal Bronto','Bronto','Event Creatures','Bone_Sauropod_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Sauropod/Bone_Sauropod_Character_BP.Bone_Sauropod_Character_BP\'"'),
('Skeletal Carnotaurus','Elite Carno','Event Creatures','Bone_MegaCarno_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Carno/Bone_MegaCarno_Character_BP.Bone_MegaCarno_Character_B\'"'),
('Skeletal Giganotosaurus','Gigant','Event Creatures','Bone_Gigant_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Giganotosaurus/Bone_Gigant_Character_BP.Bone_Gigant_Character_BP\'"'),
('Skeletal Quetzal','Quetz','Event Creatures','Bone_Quetz_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Quetzalcoatlus/Bone_Quetz_Character_BP.Bone_Quetz_Character_BP\'"'),
('Skeletal Raptor','Bone Raptor','Event Creatures','Bone_MegaRaptor_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Raptor/Bone_MegaRaptor_Character_BP.Bone_MegaRaptor_Character_BP\'"'),
('Skeletal Rex','Bone Rex','Event Creatures','Bone_MegaRex_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Rex/Bone_MegaRex_Character_BP.Bone_MegaRex_Character_BP\'"'),
('Skeletal Stego','Stego','Event Creatures','Bone_Stego_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Stego/Bone_Stego_Character_BP\'"'),
('Skeletal Trike','Trike','Event Creatures','Bone_Trike_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Trike/Bone_Trike_Character_BP\'"'),
('Spino','Spino','Dinosaurs','Spino_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Spino/Spino_Character_BP.Spino_Character_BP\'"'),
('Stegosaurus','Stego','Dinosaurs','Stego_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Stego/Stego_Character_BP.Stego_Character_BP\'"'),
('Tapejara','Tapejara','Reptiles','Tapejara_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Tapejara/Tapejara_Character_BP.Tapejara_Character_BP\'"'),
('Tek Parasaur','Para','Tek Creatures','BionicPara_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Para/BionicPara_Character_BP.BionicPara_Character_BP\'"'),
('Tek Quetzal','Quetz','Tek Creatures','BionicQuetz_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Quetzalcoatlus/BionicQuetz_Character_BP.BionicQuetz_Character_BP\'"'),
('Tek Raptor','Raptor','Tek Creatures','BionicRaptor_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Raptor/BionicRaptor_Character_BP.BionicRaptor_Character_BP\'"'),
('Tek Rex','Rex','Tek Creatures','BionicRex_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Rex/BionicRex_Character_BP.BionicRex_Character_BP\'"'),
('Tek Stegosaurus','Stego','Tek Creatures','BionicStego_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Stego/BionicStego_Character_BP.BionicStego_Character_BP\'"'),
('Terror Bird','TerrorBird','Birds','TerrorBird_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/TerrorBird/TerrorBird_Character_BP.TerrorBird_Character_BP\'"'),
('Therizinosaur','Therizinosaurus','Dinosaurs','Therizino_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Therizinosaurus/Therizino_Character_BP.Therizino_Character_BP\'"'),
('Thylacoleo','Thylacoleo','Mammals','Thylacoleo_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Thylacoleo/Thylacoleo_Character_BP.Thylacoleo_Character_BP\'"'),
('Titanoboa','TitanBoa','Reptiles','BoaFrill_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/BoaFrill/BoaFrill_Character_BP.BoaFrill_Character_BP\'"'),
('Titanomyrma Ground','Ant','Invertebrates','Ant_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Ant/Ant_Character_BP.Ant_Character_BP\'"'),
('Titanomyrma Air','Ant','Invertebrates','FlyingAnt_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Ant/FlyingAnt_Character_BP.FlyingAnt_Character_BP\'"'),
('Titanosaur','Titan','Dinosaurs','Titanosaur_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/titanosaur/Titanosaur_Character_BP.Titanosaur_Character_BP\'"'),
('Triceratops','Trike','Dinosaurs','Trike_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Trike/Trike_Character_BP.Trike_Character_BP\'"'),
('Trilobite','Trilobite','Invertebrates','Trilobite_Character_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Trilobite/Trilobite_Character.Trilobite_Character\'"'),
('Troodon','Troodon','Dinosaurs','Troodon_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Troodon/Troodon_Character_BP.Troodon_Character_BP\'"'),
('Turkey',NULL,'Event Creatures','TurkeyBase_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dodo/TurkeyBase_Character_BP.TurkeyBase_Character_BP\'"'),
('Super Turkey',NULL,'Event Creatures','Turkey_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dodo/Turkey_Character_BP.Turkey_Character_BP\'"'),
('Tusoteuthis','Tusoteuthis','Invertebrates','Tusoteuthis_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Tusoteuthis/Tusoteuthis_Character_BP.Tusoteuthis_Character_BP\'"'),
('Woolly Rhino','Rhino','Mammals','Rhino_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/WoollyRhino/Rhino_Character_BP.Rhino_Character_BP\'"'),
('Yeti','Bigfoot','Mammals','Yeti_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Bigfoot/Yeti_Character_BP.Yeti_Character_BP\'"'),
('Yutyrannus','Yutyrannus','Dinosaurs','Yutyrannus_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Yutyrannus/Yutyrannus_Character_BP.Yutyrannus_Character_BP\'"'),
('Zomdodo','Dodo','Event Creatures','ZombieDodo_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Dodo/ZombieDodo_Character_BP.ZombieDodo_Character_BP\'"'),
('Griffin','Griffin','Fantasy Creatures','Griffin_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Griffin/Griffin_Character_BP.Griffin_Character_BP\'"'),
('Ice Wyvern','Wyvern','Fantasy Creatures','Ragnarok_Wyvern_Override_Ice_C', '"Blueprint\'/Game/Mods/Ragnarok/Custom_Assets/Dinos/Wyvern/Ice_Wyvern/Ragnarok_Wyvern_Override_Ice.Ragnarok_Wyvern_Override_Ice\'"'),
('Alpha Fire Wyvern','Wyvern','Fantasy Creatures','MegaWyvern_Character_BP_Fire_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Wyvern/MegaWyvern_Character_BP_Fire.MegaWyvern_Character_BP_Fire\'"'),
('Alpha Deathworm','Deathworm','Invertebrates','MegaDeathworm_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Deathworm/MegaDeathworm_Character_BP.MegaDeathworm_Character_BP\'"'),
('Deathworm','Deathworm','Invertebrates','Deathworm_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/DeathWorm/DeathWorm_Character_BP.DeathWorm_Character_BP\'"'),
('Dodo Wyvern','Wyvern','Event Creatures','DodoWyvern_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/DodoWyvern/DodoWyvern_Character_BP.DodoWyvern_Character_BP\'"'),
('Jerboa','Jerboa','Mammals','Jerboa_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Jerboa/Jerboa_Character_BP.Jerboa_Character_BP\'"'),
('Skeletal Jerboa','Jerboa','Event Creatures','Bone_Jerboa_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Jerboa/Bone_Jerboa_Character_BP.Bone_Jerboa_Character_BP\'"'),
('Jug Bug','Jugbug','Invertebrates','Jugbug_Character_BaseBP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Jugbug/JugBug_Character_BaseBP.JugBug_Character_BaseBP\'"'),
('Oil Jug Bug','Jugbug','Invertebrates','Jugbug_Oil_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Jugbug/Jugbug_Oil_Character_BP.Jugbug_Oil_Character_BP\'"'),
('Water Jug Bug','Jugbug','Invertebrates','Jugbug_Water_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Jugbug/Jugbug_Water_Character_BP.Jugbug_Water_Character_BP\'"'),
('Lymantria','Moth','Invertebrates','Moth_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Moth/Moth_Character_BP.Moth_Character_BP\'"'),
('Manticore (Gamma)','Manticore','Bosses','Manticore_Character_BP_Easy_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Manticore/Manticore_Character_BP_Easy.Manticore_Character_BP_Easy\'"'),
('Manticore (Beta)','Manticore','Bosses','Manticore_Character_BP_Medium_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Manticore/Manticore_Character_BP_Medium.Manticore_Character_BP_Medium\'"'),
('Manticore (Alpha)','Manticore','Bosses','Manticore_Character_BP_Hard_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Manticore/Manticore_Character_BP_Hard.Manticore_Character_BP_Hard\'"'),
('Mantis','Mantis','Invertebrates','Mantis_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Mantis/Mantis_Character_BP.Mantis_Character_BP\'"'),
('Mantis Ghost','Mantis','Event Creatures','Ghost_Mantis_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Mantis/Ghost_Mantis_Character_BP.Ghost_Mantis_Character_BP\'"'),
('Morellatops','Camelsaurus','Dinosaurs','camelsaurus_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Camelsaurus/camelsaurus_Character_BP.camelsaurus_Character_BP\'"'),
('Rock Elemental','RockElemental','Fantasy Creatures','RockGolem_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/RockGolem/RockGolem_Character_BP.RockGolem_Character_BP\'"'),
('Rubble Golem','RockElemental','Fantasy Creatures','RubbleGolem_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/RockGolem/RubbleGolem_Character_BP.RubbleGolem_Character_BP\'"'),
('Thorny Dragon','SpineyLizard','Reptiles','SpineyLizard_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/SpineyLizard/SpineyLizard_Character_BP.SpineyLizard_Character_BP\'"'),
('Vulture','Vulture','Birds','Vulture_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Vulture/Vulture_Character_BP.Vulture_Character_BP\'"'),
('Wyvern','Wyvern','Fantasy Creatures','Wyvern_Character_BP_Base_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Base.Wyvern_Character_BP_Base\'"'),
('Phoenix','Phoenix','Fantasy Creatures','Phoenix_Character_BP_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Phoenix/Phoenix_Character_BP.Phoenix_Character_BP\'"'),
('Fire Wyvern','Wyvern','Fantasy Creatures','Wyvern_Character_BP_Fire_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Fire.Wyvern_Character_BP_Fire\'"'),
('Lightning Wyvern','Wyvern','Fantasy Creatures','Wyvern_Character_BP_Lightning_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Lightning.Wyvern_Character_BP_Lightning\'"'),
('Poison Wyvern','Wyvern','Fantasy Creatures','Wyvern_Character_BP_Poison_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Poison.Wyvern_Character_BP_Poison\'"'),
('Bone Fire Wyvern','Wyvern','Event Creatures','Bone_MegaWyvern_Character_BP_Fire_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Wyvern/Bone_MegaWyvern_Character_BP_Fire.Bone_MegaWyvern_Character_BP_Fire\'"'),
('Zombie Fire Wyvern','Wyvern','Event Creatures','Wyvern_Character_BP_ZombieFire_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_ZombieFire.Wyvern_Character_BP_ZombieFire\'"'),
('Zombie Lightning Wyvern','Wyvern','Event Creatures','Wyvern_Character_BP_ZombieLightning_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_ZombieLightning.Wyvern_Character_BP_ZombieLightning\'"'),
('Zombie Poison Wyvern','Wyvern','Event Creatures','Wyvern_Character_BP_ZombiePoison_C', '"Blueprint\'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_ZombiePoison.Wyvern_Character_BP_ZombiePoison\'"'),
('Chalk Golem','RockElemental','Fantasy Creatures','ChalkGolem_Character_BP_C', '"Blueprint\'/Game/Mods/Valguero/Assets/Dinos/RockGolem/ChalkGolem/ChalkGolem_Character_BP.ChalkGolem_Character_BP\'"'),
('Deinonychus','Deinonychus','Dinosaurs','Deinonychus_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/Raptor/Uberraptor/Deinonychus_Character_BP.Deinonychus_Character_BP\'"'),
('Ice Golem','RockElemental','Fantasy Creatures','IceGolem_Character_BP_C', '"Blueprint\'/Game/PrimalEarth/Dinos/IceGolem/IceGolem_Character_BP.IceGolem_Character_BP\'"');
