
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ln = {'a': ['lnapl_transmissivity'],
 'b': ['lnbp', 'lnb'],
 'c': ['lnct_university', 'lnct_indore'],
 'd': ['lndn_drgs'],
 'e': ['lner_pacifics', 'lner_ships'],
 'f': ['lnfa_2010',
       'lnfa_2011',
       'lnfa_2017',
       'lnfa_2014',
       'lnfa_2012',
       'lnfa_2019',
       'lnfa_2013',
       'lnfa_2008',
       'lnfa_2009',
       'lnfa_2015',
       'lnfa_1995',
       'lnfa_2018',
       'lnfa_2020',
       'lnfa_2'],
 'g': ['lng_hrvatska', 'lng_esports', 'lng_carrier', 'lng_canada', 'lng_spill'],
 'h': ['lnhs', 'lnh'],
 'i': ['lnint_uav'],
 'k': ['lnk'],
 'l': ['lnl'],
 'm': ['lnm'],
 'n': ['lnnk', 'lnn'],
 'o': ['lnozavod', 'lno'],
 'p': ['lnp'],
 'r': ['lnr'],
 's': ['lnso', 'lns'],
 't': ['lntx-1', 'lnt'],
 'u': ['lnu'],
 'w': ['lnw-80'],
 'x': ['lnx1', 'lnx'],
 'y': ['lny'],
 'z': ['lnzndrf', 'lnz']}
