
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nt = {'_': ['nt5c1a', 'nt5c3', 'nt-1', 'nt5c', 'nt5e', 'nt5m', 'nt1', 'nt4', 'nt2'],
 'a': ['ntabamhlophe',
       'ntambirweki',
       'ntabankulu',
       'ntamugenga',
       'ntarabana',
       'ntamack',
       'ntalale',
       'ntankpo',
       'ntames',
       'ntambu',
       'ntamba',
       'ntara',
       'ntap',
       'nta'],
 'b': ['ntbackup', 'ntbc', 'ntb'],
 'c': ['ntchiado', 'ntchisi', 'ntcham', 'ntcheu', 'ntcp8', 'ntcc', 'ntc'],
 'd': ['ntdetect.com', 'ntdec', 'ntds', 'ntd'],
 'e': ['ntexplorer',
       'nteichitt',
       'ntenjeru',
       'ntera-2',
       'ntelle',
       'ntelos',
       'ntezi',
       'ntete',
       'ntest',
       'ntent',
       'nteje',
       'ntem',
       'ntec',
       'nteu',
       'nte'],
 'f': ['ntfsresize',
       'ntfonjeni',
       'ntfsprogs',
       'ntfsdos',
       'ntfs-3g',
       'ntfl',
       'ntfp',
       'ntfc',
       'ntfs',
       'ntf'],
 'g': ['ntg'],
 'h': ['nthellworld', 'nthword', 'nthl1', 'nths', 'nth'],
 'i': ['ntinda', 'ntiona', 'ntime', 'ntiva', 'ntic', 'nti'],
 'j': ['ntjanini', 'ntj'],
 'k': ['ntk'],
 'l': ['ntlmssp', 'ntldr', 'ntla', 'ntl'],
 'm': ['ntm'],
 'n': ['ntn24', 'ntnui', 'ntn5', 'ntnu', 'ntn'],
 'o': ['ntoskrnl.exe',
       'ntournerakia',
       'ntombela',
       'ntobroso',
       'ntotroso',
       'ntounkwe',
       'ntondozi',
       'ntoroko',
       'ntopng',
       'ntonso',
       'ntomba',
       'ntoum',
       'ntoro',
       'ntone',
       'ntop',
       'nto'],
 'p': ['ntpdate', 'ntpa', 'ntpd', 'ntpc', 'ntp'],
 'q': ['ntq'],
 'r': ['ntruencrypt',
       'ntractive',
       'ntrusign',
       'ntrguent',
       'ntrepid',
       'ntrak',
       'ntrc',
       'ntru',
       'ntrl',
       'ntr'],
 's': ['ntsf:sd:suv::',
       'ntsoudjini',
       'ntshangase',
       'ntsaoueni',
       'ntsadjeni',
       'ntsikana',
       'ntsorale',
       'ntsc-j',
       'ntsc-c',
       'ntsele',
       'ntsh',
       'ntss',
       'ntsu',
       'ntsc',
       'ntsf',
       'nts'],
 't': ['nttr', 'nttv', 'ntt'],
 'u': ['ntuppuppakkoranendarnnu',
       'nturukpum',
       'ntungamo',
       'ntuzuma',
       'ntuusi',
       'ntuntu',
       'ntuka',
       'ntusi',
       'ntuli',
       'ntuc',
       'ntui',
       'ntu'],
 'v': ['ntv2', 'ntvg', 'ntv7', 'ntv'],
 'w': ['ntwike', 'ntwf'],
 'x': ['ntx'],
 'y': ['ntyuka'],
 'z': ['ntz']}
