
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nl = {'_': ['nl-complete', 'nl-alert', 'nl-201'],
 'a': ["nlaka'pamux",
       'nlayers',
       'nlaman',
       'nlaiii',
       'nland',
       'nlaw',
       'nlab',
       'nla'],
 'b': ['nlbeter', 'nlb'],
 'c': ['nlcf', 'nlcc', 'nlc'],
 'd': ['nld'],
 'e': ['nle1', 'nle'],
 'f': ['nlf'],
 'g': ['nlgn4x', 'nlgn1', 'nlgn3', 'nlgn2', 'nlgn', 'nlg'],
 'h': ['nlhamankulu', 'nlhs', 'nlh'],
 'i': ['nli'],
 'j': ['nlj'],
 'k': ['nlk'],
 'l': ['nll'],
 'm': ['nlm'],
 'n': ['nlnet', 'nln'],
 'o': ['nlogit', 'nlo'],
 'p': ['nlpqlp', 'nlpc', 'nlp'],
 'r': ['nlrp14',
       'nlrp12',
       'nlrp10',
       'nlrp13',
       'nlrp11',
       'nlrc3',
       'nlrp1',
       'nlrc4',
       'nlrp3',
       'nlrp6',
       'nlrp9',
       'nlrp7',
       'nlrc5',
       'nlrp5',
       'nlrp4',
       'nlrx1',
       'nlrp8',
       'nlrp2',
       'nlrp',
       'nlr'],
 's': ['nlsp', 'nlsc', 'nls'],
 't': ['nltss', 'nltc', 'nlt'],
 'u': ['nluug', 'nlu'],
 'v': ['nlv'],
 'w': ['nlwc', 'nlw'],
 'x': ['nlx'],
 'y': ['nly'],
 'z': ['nlz']}
