
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_f_ = {'_': ['f.-x.-lemieux_lake',
       'f110-class_frigate',
       'f._portoricensis',
       'f-22_interceptor',
       'f35_transmission',
       'f650_supertruck',
       'f420h2dh_family',
       'f-6,_islamabad',
       'f._californica',
       'f2_propagation',
       'f._salicifolia',
       'f._lalnunmawia',
       'f-8,_islamabad',
       'f-16_aggressor',
       'f29_retaliator',
       'f355_challenge',
       'f-1_sensation',
       'f91_dudelange',
       'f._orientalis',
       'f._nepalensis',
       'f-16_rachanon',
       'f._carbonaria',
       'f._emasculata',
       'f._ferruginea',
       'f._brunea-fox',
       'f._polymorpha',
       'f._floribunda',
       'f._pratensis',
       'f._polyclada',
       'f._colombari',
       'f1_challenge',
       'f45_training',
       'f2_logistics',
       'f11_receptor',
       'f._australis',
       'f._gardneri',
       'f._vulgaris',
       'f1_digital+',
       'f._springer',
       'f._japonica',
       'f._communis',
       'f._concinna',
       'f._moormann',
       'f._hepatica',
       'f._gracilis',
       'f._maculata',
       'f1_magazine',
       'f17_torpedo',
       'f1_manager',
       'f._andrieu',
       'f._grandis',
       'f._indicus',
       'f2_gallery',
       'f._viridis',
       'f1_grenade',
       'f._rahardi',
       'f26a_graph',
       'f._formosa',
       'f1-x_dubai',
       'f._montana',
       'f24_camera',
       'f-4_object',
       'f._elegans',
       'f1_hybrid',
       'f._maxima',
       'f1_circus',
       'f._exigua',
       'f-1_dream',
       'f._juncea',
       'f._laeisz',
       'f._crispa',
       'f3_nation',
       'f1_engine',
       'f5,_inc.',
       'f._rubra',
       'f._loree',
       'f5_tower',
       'f._lutea',
       'f._yates',
       'f1_clash',
       'f._laeta',
       'f._aurea',
       'f._hinds',
       'f3_derby',
       'f._dick',
       'f6_disk',
       'f1_race',
       'f._nana'],
 'a': ['f/a-18_interceptor',
       'f.a.c.e._school',
       'f/a-xx_program',
       'f+a_architects',
       'f.a.m.e._tour',
       'f.a._reynolds',
       'f-a-e_sonata',
       'f.a._venter',
       'f.a._dobson',
       'f.a._euro',
       'f_album'],
 'b': ['f-block_metallocene',
       'f.b.c._torinese',
       'f-beat_records',
       'f-box_protein',
       'f.b._mcfarren',
       'f.b._mulford',
       'f_band',
       'f_bar'],
 'c': ['f.c.d._altovicentino',
       'f.c.d._lottogiaveno',
       'f.c._sangiuseppese',
       'f-class_destroyer',
       'f-class_submarine',
       'f.c._chanthabouly',
       'f.c._bougainville',
       'f.c._alpendorada',
       'f.c._barreirense',
       'f_communications',
       'f.c._francavilla',
       'f.c._castiglione',
       'f.c._guadalcanal',
       'f.c._fossombrone',
       'f.c._pampilhosa',
       'f.c._richardson',
       'f.c.s._nacional',
       'f.c._copenhagen',
       'f.c._fiorentino',
       'f.c._felgueiras',
       'f.c._aboomoslem',
       'f.c._excelsior',
       'f.c._cesarense',
       'f.c._ballynure',
       'f.c._ferreiras',
       'f.c._daburiyya',
       'f.c._famalicao',
       'f.c._domagnano',
       'f.c._elmstead',
       'f.c._gullegem',
       'f.c._penafiel',
       'f.c._neapolis',
       'f.c._tirsense',
       'f.c._takoradi',
       'f.c._marinhas',
       'f.c._virginia',
       'f.c._nanumaga',
       'f-class_blimp',
       'f.c._terborgh',
       'f.c._platinum',
       'f.c._nacional',
       'f.c._canavese',
       'f.c._sudtirol',
       'f.c._lailapas',
       'f.c._bolsover',
       'f.c._johansen',
       'f.c._cabinda',
       'f.c._infesta',
       'f.c.w._keuhn',
       'f.c._talanta',
       'f.c._motagua',
       'f.c._alverca',
       'f.c._romania',
       'f.c._chitwan',
       'f.c._crotone',
       'f.c._indiana',
       'f.c._clacton',
       'f.c._netanya',
       'f.c._momase',
       'f.c._tofaga',
       'f.c._itzaes',
       'f.c._vizela',
       'f.c._fidene',
       'f.c._amares',
       'f.c._matera',
       'f.c._arouca',
       'f.c._satmos',
       'f.c._ashdod',
       'f.c._ebedei',
       'f.c._niutao',
       'f_connector',
       'f.c._carlow',
       'f.c._kallon',
       'f.c._dimona',
       'f.c._moxico',
       'f.c._kutubu',
       'f.c._luanda',
       'f_centauri',
       'f.c._marco',
       'f.c._haifa',
       'f.c._julis',
       'f.c._nania',
       'f.c._rieti',
       'f.c._vado',
       'f*ck_love',
       'f.c._cefn',
       'f.c._reno',
       'f.c._lixa',
       'f.c._tira',
       'f.c._arad',
       'f.c._maia',
       'f_collar',
       'f_crimp',
       'f_cygni',
       'f_club'],
 'd': ['f.d._crockett', 'f.d.r._jones'],
 'e': ['f.e._williams', 'f.e.l._beal', 'f.e.a.r._3', 'f_eridani'],
 'f': ['f-flat_major', 'f&f_tower'],
 'g': ['f.g.a.m._smit'],
 'h': ['f.h._steinbart', 'f.h._buckley', 'f_hydrae'],
 'i': ['f-ire_collective', 'f_international', 'f-i_curve'],
 'j': ['f.j._griffiths', 'f.j._lennon', 'f.j._fuchs', 'f_jackie'],
 'k': ["f'kirina_district", 'f_kikan'],
 'l': ['f_lalrinpuia', 'f_liner', 'f_line', 'f_lead'],
 'm': ['f.m._einheit',
       'f&m_brewery',
       'f&m_bank',
       'f_major',
       'f_meson',
       'f_minus',
       'f_minor'],
 'n': ['f-number', 'f4n'],
 'o': ['f_orionis', 'f_one'],
 'p': ['f_puppis'],
 'r': ['f@rid@_v@zirova', 'f_region', 'f_road'],
 's': ['f-series_3-wheeler',
       'f-shape_barrier',
       'f-sharp_minor',
       'f-sharp_major',
       'f-stop_music',
       'f_series',
       'f_street',
       'f_scott',
       'f_scale'],
 't': ['f-type_asteroid',
       'f-type_prisons',
       'f.t._island',
       'f@t@li_xan',
       'f_troop'],
 'u': ['f.u.e.p.', 'f.u.n.k.', 'f5u'],
 'v': ['f.v.d._stehaufchen',
       'f.v.d._doris',
       'f-ve_dolls',
       'f_velorum',
       'f_visa'],
 'w': ['f.w.p._matese',
       'f.w._anderson',
       'f.w._caulkins',
       'f+w_c-3605',
       'f_word',
       'f_wave'],
 'x': ['f-x_project', 'f.x._schmid', 'f.x._toole'],
 'y': ['f.y.p'],
 'z': ['f-zero_climax', 'f-zero_gx', 'f-zero_x']}
