
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cx = {'_': ['cx-546',
       'cx3cl1',
       'cx3cr1',
       'cx-516',
       'cx717',
       'cx614',
       'cx157',
       'cx-5',
       'cx-3',
       'cx30',
       'cx4'],
 'a': ['cxa'],
 'b': ['cxbn-2', 'cxb3s', 'cxbn'],
 'c': ['cxcl13',
       'cxcl14',
       'cxcl10',
       'cxcl15',
       'cxcl16',
       'cxcl11',
       'cxcl17',
       'cxcl5',
       'cxcl1',
       'cxcl2',
       'cxcl3',
       'cxcl7',
       'cxcr5',
       'cxcl6',
       'cxcr6',
       'cxcr4',
       'cxcl9',
       'cxcr3'],
 'e': ['cxense', 'cxema'],
 'f': ['cxfs'],
 'g': ['cxg'],
 'h': ['cxh'],
 'j': ['cxj'],
 'k': ['cxk'],
 'l': ['cxloe', 'cxl'],
 'm': ['cxml'],
 'o': ['cxorf40a', 'cxorf67', 'cxorf36', 'cxorf66', 'cxorf49', 'cxo'],
 'p': ['cxprocess', 'cxp'],
 'r': ['cxr'],
 't': ['cxt'],
 'x': ['cxxc5', 'cxxc1']}
