
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cm = {'_': ['cm-field',
       'cm-501g',
       'cm-4620',
       'cm/ecf',
       'cm-11',
       'cm156',
       'cm3',
       'cm5',
       'cm4',
       'cm2',
       'cm1'],
 'a': ['cmaptools',
       'cmachowo',
       'cmanjke',
       'cma-es',
       'cmake',
       'cmath',
       'cmaq',
       'cmaa',
       'cmap',
       'cmas',
       'cma3',
       'cma1',
       'cmax',
       'cmah',
       'cma'],
 'b': ['cmbstar-1', 'cmbfast', 'cmba', 'cmbc'],
 'c': ['cmc$', 'cmct', 'cmcs', 'cmc'],
 'd': ['cmdbuild', 'cmd.exe', 'cmd640', 'cmda', 'cmd'],
 'e': ['cmeliny', 'cmean', 'cmes', 'cmec', 'cmea', 'cme'],
 'f': ['cmft', 'cmfr', 'cmf'],
 'g': ['cmg'],
 'h': ['cmha', 'cmhi', 'cmhk', 'cmhs', 'cmhc'],
 'i': ['cmiszew-parcel',
       'cmielow',
       'cmilow',
       'cminsk',
       'cmiiw',
       'cmin',
       'cmip',
       'cmi'],
 'j': ['cmj'],
 'k': ['cmklr1'],
 'l': ['cmla', 'cml'],
 'm': ['cmml', 'cmmc', 'cmmn', 'cmm'],
 'n': ['cmn-goms', 'cmnh', 'cmn'],
 'o': ['cmolas', 'cmot', 'cmoc', 'cmoy', 'cmos', 'cmo'],
 'p': ['cmp-acetylneuraminate-lactosylceramide-sialyltransferase',
       'cmpa',
       'cmpk',
       'cmpl',
       'cmpp',
       'cmpd',
       'cmpi',
       'cmp'],
 'q': ['cmq'],
 'r': ['cmrr', 'cmri', 'cmrs', 'cmr'],
 's': ['cms-helmets',
       'cmsimple',
       'cms-02',
       'cms-01',
       'cms-2',
       'cmsc',
       'cmsa',
       'cmst',
       'cmse',
       'cmsf',
       'cms'],
 't': ['cmtx2',
       'cmtm3',
       'cmtx3',
       'cmtm2',
       'cmts',
       'cmta',
       'cmtu',
       'cmtv',
       'cmtc',
       'cmt'],
 'u': ['cmucam', 'cmune', 'cmus', 'cmu'],
 'v': ['cmv423', 'cmvc', 'cmv'],
 'w': ['cmw'],
 'x': ['cmx521', 'cmx'],
 'y': ['cmy'],
 'z': ['cmz']}
