
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cj = {'_': ['cj-033466',
       'cj-100',
       'cj-5',
       'cj-6',
       'cj-1',
       'cj7',
       'cj2',
       'cj4',
       'cj3'],
 'a': ['cjamango',
       'cjat-fm',
       'cjab-fm',
       'cjas-fm',
       'cjaq-fm',
       'cjag-fm',
       'cjai-fm',
       'cjaw-fm',
       'cjam-fm',
       'cjan-fm',
       'cjay-fm',
       'cjav-fm',
       'cjax-fm',
       'cjay',
       'cjad',
       'cjan',
       'cjar',
       'cja'],
 'b': ['cjbp-fm',
       'cjbb-fm',
       'cjbu-fm',
       'cjbi-fm',
       'cjbc-fm',
       'cjbz-fm',
       'cjbn-tv',
       'cjbx-fm',
       'cjbr-dt',
       'cjbr-fm',
       'cjbe-fm',
       'cjbq',
       'cjbk',
       'cjbc',
       'cjb'],
 'c': ['cjc-1295',
       'cjce-fm',
       'cjcb-dt',
       'cjcq-fm',
       'cjcd-fm',
       'cjcy-fm',
       'cjco-dt',
       'cjch-dt',
       'cjcs-fm',
       'cjcj-fm',
       'cjck-fm',
       'cjch-fm',
       'cjci-fm',
       'cjcn-fm',
       'cjcsg',
       'cjcs',
       'cjcj',
       'cjca',
       'cjcb',
       'cjcl',
       'cjch',
       'cjcy',
       'cjcw',
       'cjc'],
 'd': ['cjds-fm',
       'cjdm-fm',
       'cjdj-fm',
       'cjdc-tv',
       'cjdl-fm',
       'cjdv-fm',
       'cjdv',
       'cjdc',
       'cjd'],
 'e': ['cjem-fm',
       'cjeb-fm',
       'cjec-fm',
       'cjez-fm',
       'cjeg-fm',
       'cjel-fm',
       'cjeo-dt',
       'cjed-fm',
       'cjet-fm',
       'cjef'],
 'f': ['cjfw-fm',
       'cjfy-fm',
       'cjfi-fm',
       'cjfm-fm',
       'cjfh-fm',
       'cjfb-tv',
       'cjfb-fm',
       'cjfx-fm',
       'cjfl-fm',
       'cjfo-fm',
       'cjfb',
       'cjf'],
 'g': ['cjgy-fm', 'cjgo-fm', 'cjgm-fm', 'cjgb-fm', 'cjgx', 'cjg'],
 'h': ['cjhd-fm', 'cjhk-fm', 'cjhq-fm', 'cjhr-fm', 'cjhl', 'cjhs'],
 'i': ['cjic-tv',
       'cjiq-fm',
       'cjil-dt',
       'cjib-fm',
       'cjiv-fm',
       'cjij-fm',
       'cjie-fm',
       'cjit-fm',
       'cjik-fm',
       'cjic'],
 'j': ['cjjc-fm', 'cjjj-fm', 'cjjr-fm', 'cjjm-fm'],
 'k': ['cjkl-fm', 'cjkr-fm', 'cjkx-fm', 'cjks-fm', 'cjkc-fm'],
 'l': ['cjlj-fm',
       'cjly-fm',
       'cjls-fm',
       'cjla-fm',
       'cjlm-fm',
       'cjld-fm',
       'cjlf-fm',
       'cjll-fm',
       'cjlx-fm',
       'cjlu-fm',
       'cjlt-fm',
       'cjlv',
       'cjli',
       'cjlo',
       'cjls',
       'cjl'],
 'm': ['cjmo-fm',
       'cjml-fm',
       'cjmv-fm',
       'cjmu-fm',
       'cjmj-fm',
       'cjmi-fm',
       'cjmc-fm',
       'cjmp-fm',
       'cjmt-dt',
       'cjmf-fm',
       'cjmb-fm',
       'cjmq-fm',
       'cjmx-fm',
       'cjmk-fm',
       'cjmd-fm',
       'cjmg-fm',
       'cjmm-fm',
       'cjms',
       'cjmr',
       'cjme'],
 'n': ['cjni-fm',
       'cjnc-fm',
       'cjnt-dt',
       'cjnu-fm',
       'cjns-fm',
       'cjne-fm',
       'cjnr',
       'cjnb',
       'cjn'],
 'o': ['cjot-fm',
       'cjoc-fm',
       'cjos-fm',
       'cjon-dt',
       'cjoa-fm',
       'cjoe-fm',
       'cjok-fm',
       'cjoj-fm',
       'cjoh-dt',
       'cjoi-fm',
       'cjoi',
       'cjob',
       'cjon',
       'cjoy',
       'cjor'],
 'p': ['cjpt-fm',
       'cjpx-fm',
       'cjpe-fm',
       'cjpg-fm',
       'cjpc-dt',
       'cjpl-fm',
       'cjpr-fm',
       'cjpn-fm',
       'cjpm-dt',
       'cjpp',
       'cjpe',
       'cjp'],
 'q': ['cjqm-fm', 'cjqc-fm', 'cjqq-fm'],
 'r': ['cjrw-fm',
       'cjrq-fm',
       'cjrk-fm',
       'cjri-fm',
       'cjrh-fm',
       'cjro-fm',
       'cjrp-fm',
       'cjrg-fm',
       'cjrm-fm',
       'cjrt-fm',
       'cjrx-fm',
       'cjrl-fm',
       'cjrf-fm',
       'cjry-fm',
       'cjra',
       'cjrc',
       'cjrp',
       'cjrj',
       'cjrb',
       'cjru',
       'cjrn'],
 's': ['cjse-fm',
       'cjsu-fm',
       'cjss-tv',
       'cjsw-fm',
       'cjsd-fm',
       'cjsf-fm',
       'cjso-fm',
       'cjsb-fm',
       'cjsr-fm',
       'cjss-fm',
       'cjsp-fm',
       'cjsq-fm',
       'cjsa-fm',
       'cjsi-fm',
       'cjsl',
       'cjss',
       'cjsb',
       'cjsf',
       'cjsn',
       'cjs'],
 't': ['cjtr-fm',
       'cjtw-fm',
       'cjtl-fm',
       'cjtk-fm',
       'cjtb-fm',
       'cjtn-fm',
       'cjts-fm',
       'cjtt-fm'],
 'u': ['cjuc-fm',
       'cjuv-fm',
       'cjus-fm',
       'cjuj-fm',
       'cjuk-fm',
       'cjum-fm',
       'cjul'],
 'v': ['cjvd-fm',
       'cjvm-fm',
       'cjvf-fm',
       'cjvn-fm',
       'cjva-fm',
       'cjvr-fm',
       'cjvb'],
 'w': ['cjwl-fm',
       'cjwe-fm',
       'cjwf-fm',
       'cjwt-fm',
       'cjwa-fm',
       'cjwv-fm',
       'cjww',
       'cjwi'],
 'x': ['cjxk-fm', 'cjxx-fm', 'cjxl-fm', 'cjxr-fm', 'cjxy-fm'],
 'y': ['cjyc-fm', 'cjyq', 'cjym', 'cjye'],
 'z': ['cjzn-fm', 'cjz']}
