
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cv = {'_': ['cv-library',
       'cv-2000',
       'cv/gate',
       'cv-33',
       'cv-22',
       'cv-35',
       'cv-7',
       'cv-2',
       'cv4',
       'cv8',
       'cv6'],
 'a': ['cvaljina',
       'cvasnita',
       'cvarici',
       'cva-01',
       'cvarci',
       'cvax',
       'cvac',
       'cvar',
       'cva'],
 'b': ['cvb'],
 'c': ['cvcc', 'cvca', 'cvc'],
 'd': ['cvd'],
 'e': ['cvetojevac',
       'cvelferija',
       'cvetanovac',
       'cvetkovski',
       'cvetkovec',
       'cvetkovci',
       'cvetkovic',
       'cvetisce',
       'cvetovac',
       'cvetulja',
       'cvetovo',
       'cvejic',
       'cvetke',
       'cvent',
       'cveca',
       'cven',
       'cvek',
       'cve'],
 'f': ['cvf'],
 'g': ['cvg'],
 'h': ['cvhs', 'cvh'],
 'i': ['cvitanovich',
       'cvijanovic',
       'cviljevina',
       'cvislerji',
       'cviptools',
       'cvilance',
       'cvitovic',
       'cviblje',
       'cvidya',
       'cvijic',
       'cvicek',
       'cvilin',
       'cvijan',
       'cvikov',
       'cvid',
       'cvi'],
 'j': ['cvjeticanin', 'cvj'],
 'k': ['cvk'],
 'l': ['cvl-22', 'cvl'],
 'm': ['cvms', 'cvm'],
 'n': ['cvn'],
 'o': ['cvoter', 'cvo'],
 'p': ['cvps', 'cvp'],
 'q': ['cvqo'],
 'r': ['cvrtkovci',
       'cvrcovice',
       'cvrsnica',
       'cvrcici',
       'cvrcka',
       'cvrce',
       'cvrr',
       'cvrd',
       'cvra',
       'cvr'],
 's': ['cvsnt', 'cvsa', 'cvss', 'cvs'],
 't': ['cvt16', 'cvt'],
 'u': ['cvusd', 'cvu'],
 'v': ['cvvtcs', 'cvv'],
 'w': ['cvw2'],
 'x': ['cvx'],
 'z': ['cvz']}
