
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_j_ = {'_': ['j1124+4535',
       'j0815+4729',
       'j0313-1806',
       'j1000+0221',
       'j-113,397',
       'j002e3',
       'j/111',
       'j-201',
       'j/105',
       'j/92s',
       'j1922',
       'j/27',
       'j/70',
       'j-2x',
       'j/35',
       'j/28',
       'j/24',
       'j/92',
       'j/22',
       'j147',
       'j786',
       'j/80',
       'j/32',
       'j/30',
       'j32',
       'j15',
       'j30',
       'j35',
       'j52',
       'j97',
       'j25',
       'j24',
       'j36',
       'j13',
       'j19',
       'j27',
       'j12',
       'j10',
       'j26',
       'j39',
       'j11',
       'j28',
       'j00',
       'j48',
       'j20',
       'j18',
       'j85',
       'j29',
       'j14',
       'j31',
       'j42',
       'j16',
       'j38',
       'j34',
       'j33',
       'j++',
       'j17',
       'j23',
       'j21',
       'j37',
       'j22'],
 'a': ['j.a.r.v.i.s.',
       "j'accuse...!",
       "j'attendrai",
       'j-aggregate',
       "j'attendais",
       "j'arrive",
       'j.a.c.e.',
       'j.a.c.k.',
       'j/apg-1',
       'j-alert',
       "j'adore",
       'j.a.r.',
       'j.a.c.',
       'j-air',
       'j-ax'],
 'b': ['j-blogosphere',
       'j/boats',
       'j-break',
       'j-blog',
       'j-bomb',
       'j-bay',
       'j-bar',
       'j-bus',
       'j-boy',
       'j-bis'],
 'c': ['j-coupling',
       'j.c.staff',
       'j-crown',
       'j-catch',
       'j-card',
       'j-code',
       'j-core',
       'j.crew',
       'j-cart',
       'j-comi'],
 'd': ['j/direct', 'j-diggs', 'j*davey', 'j.d.s', 'j-day'],
 'e': ["j'erin", 'j.e.m'],
 'f': ['j-function',
       'j-friends',
       'j-flexx',
       'j-five',
       'j-fest',
       'j-flag',
       'j.fla'],
 'g': ['j-gate', 'j-game'],
 'h': ['j-homomorphism', 'j-hope'],
 'i': ['j-invariant', 'j-integral', "j'imagine", 'j-i'],
 'j': ['j-j-jacks', 'j.jill', 'j.john', 'j.j.!'],
 'k': ['j.krishnapuram', 'j2k-codec', "j'kyun", 'j-kwon', 'j2k'],
 'l': ['j.lindeberg',
       'j.league',
       'j.lately',
       'j-louis',
       'j-line',
       'j-list',
       'j-live'],
 'm': ['j-multiplicity',
       'j-machine',
       'j-museum',
       'j.m.k.e.',
       'j-milla',
       'j-melo',
       'j-min',
       'j-me',
       'j2m'],
 'o': ['j.oliver', "j'ouvert", "j-ok'el", 'j.o.e.', 'j-one', 'j2o'],
 'p': ['j-popcon',
       'j.period',
       'j-pilot',
       'j.prabu',
       'j.p.y.',
       'j-parc',
       'j-pop',
       'j-pas'],
 'r': ['j-rocks', 'j-roc', 'j-ro', 'j&r'],
 's': ['j*s*t*a*r*s',
       'j-structure',
       'j-setting',
       'j-stage',
       'j-swift',
       'j.sheon',
       'j-stars',
       'j2stask',
       'j-star',
       'j-shin',
       'j-sh04',
       'j-sky',
       'j-son',
       'j2s'],
 't': ['j.trill', 'j-test', 'j-turn', 'j-town', 'j-top', 'j&t'],
 'u': ['j.u.l.i.a.', 'j-u-n-k'],
 'v': ["j'voulais", 'j.views', 'j-vibe'],
 'w': ['j-wess', 'j-wear', 'j-wave', 'j-walk'],
 'x': ['j-xx'],
 'z': ['j-zone']}
