
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_js = {'_': ['js13kgames', 'js++', 'js-3', 'js41', 'js-1', 'js16', 'js2'],
 'a': ['jsad', 'jsat', 'jsa'],
 'b': ['jsbsim', 'jsbml', 'jsb'],
 'c': ['jscript.encode',
       'jscrambler',
       'jscheme',
       'jscript',
       'jschool',
       'jscc',
       'jsci',
       'jscm',
       'jsc'],
 'd': ['jsdelivr', 'jsdoc', 'jsdc', 'jsd'],
 'e': ['jse'],
 'f': ['jsfiddle', 'jsfuck', 'jsf'],
 'g': ['jsgf', 'jsgi', 'jsg'],
 'h': ['jshint', 'jshell', 'jsh'],
 'i': ['jsish', 'jsi'],
 'j': ['jsj'],
 'k': ['jsk'],
 'l': ['jslint', 'jslee', 'jsla', 'jsl'],
 'm': ['jsmooth', 'jsmath', 'jsm'],
 'n': ['jsn'],
 'o': ['json2ldap',
       'json-url',
       'json-rpc',
       'json-wsp',
       'json-ld',
       'jsoniq',
       'jsonml',
       'jsonp',
       'jsoup',
       'jsol',
       'json',
       'jso'],
 'p': ['jspx-bay', 'jsphp', 'jspx', 'jsp'],
 'r': ['jsrender/jsviews', 'jsr'],
 's': ['jssip', 'jssp', 'jssr', 'jss'],
 't': ['jstor', 'jstik', 'jstv', 'jst'],
 'u': ['jsu'],
 'v': ['jsv'],
 'w': ['jswipe', 'jswat', 'jsw'],
 'x': ['jsx'],
 'y': ['jsyn', 'jsy']}
