
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jc = {'_': ['jc3iedm', "jc's"],
 'a': ['jcamp-dx', 'jcall', 'jcap', 'jcag', 'jca'],
 'b': ['jcbc', 'jcb'],
 'c': ['jcci', 'jccc', 'jcc'],
 'd': ['jcdecaux', 'jcd'],
 'e': ['jcet', 'jce'],
 'f': ['jcf'],
 'h': ['jchempaint', 'jchs', 'jch'],
 'i': ['jci'],
 'j': ['jcj'],
 'k': ['jck'],
 'l': ['jclc', 'jcl'],
 'm': ['jcmsuite', 'jcm'],
 'n': ['jcnetwork'],
 'o': ['jconsole', 'jcorps', 'jco'],
 'p': ['jcpenney', 'jcps', 'jcpa', 'jcp'],
 'q': ['jcq'],
 'r': ['jcreator', 'jcrom', 'jcrc', 'jcr'],
 's': ['jcsat-110',
       'jcsat-11',
       'jcsat-ra',
       'jcsat-4a',
       'jcsat-2b',
       'jcsat-2a',
       'jcsat-16',
       'jcsat-3a',
       'jcsat-5a',
       'jcsat-4b',
       'jcsat-1b',
       'jcsat-15',
       'jcsat-17',
       'jcsat-2',
       'jcsat-3',
       'jcsat-1',
       'jcsat-4',
       'jcsp',
       'jcsd',
       'jcss',
       'jcs'],
 't': ['jct600', 'jct'],
 'u': ['jcuken', 'jcube', 'jcu'],
 'v': ['jcvi'],
 'w': ['jcw']}
