
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ax = {'_': ['ax:son_johnson_family',
       'ax_handle_saturday',
       'ax_3_domaines',
       'ax_the_tax'],
 'a': ['axa_investment_managers',
       'axa_equitable_center',
       'axa_training_centre',
       'axa_bank_belgium'],
 'b': ['axbridge_railway_station', 'axbridge_rural_district'],
 'e': ['axel_petersson_doderhultarn',
       'axelsberg_metro_station',
       'axel_gunerius_pettersen',
       'axess_vision_technology',
       'axel_oxenstierna_palace',
       'axedale_railway_station',
       'axel_gustav_adlercreutz',
       'axe_spectral_extraction',
       'axel_johannes_malmquist',
       'axel_fredrik_bjurstrom',
       'axelle_red_discography',
       'axel_nicolai_herlofson',
       'axel_fredrik_cronstedt',
       'axel_gustaf_gyllenkrok',
       'axe_telephone_exchange',
       'axel_leonard_melander',
       'axel_olof_freudenthal',
       'axel_gabriel_sjostrom',
       'axel_robert_schonthal',
       'axel_wilhelm_eriksson',
       'axel_ludvig_brostrom',
       'axel_de_reuterskiold',
       'axel_hampus_dalstrom',
       'axel_oskar_andresson',
       'axel_heiberg_glacier',
       'axel_fredrik_enstrom',
       'axel_andersen_byrval',
       'axel_dalberg_poulsen',
       'axel_jacob_petersson',
       'axel_fredrik_londen',
       'axel_elof_jaderholm',
       'axel_camillo_eitzen',
       'axel_springer_award',
       "axel!_will's_wissen",
       'axel_van_lamsweerde',
       'axel_heiberg_island',
       'axel_gudbrand_blytt',
       'axente_sever,_sibiu',
       "axel's_magic_hammer",
       'axel_theodor_naess',
       'axe_valley_academy',
       'axel_heiberg_stang',
       'axel_johnson_group',
       'axe_lake_aerodrome',
       'axel_johnson_ranch',
       'axel_radlach_pries',
       'axel_fabrice_konan',
       'axel_von_ambesser',
       'axel_bohman_house',
       'axel_henry_hansen',
       'axel_cedric_konan',
       'axel_von_blomberg',
       'axel_otto_normann',
       'axel_otto_morner',
       'axel_von_harnack',
       'axel_c._heitmann',
       'axel_v._tulinius',
       'axel_nixon_house',
       'axel_and_valborg',
       'axel_springer_se',
       'axel_von_fersen',
       'axel_t._brunger',
       'axel_w._persson',
       'axe_murder_boyz',
       'axel_proet_host',
       'axel_and_pixel',
       'axel_erik_roos',
       'axel_p._jensen',
       'axel_rudi_pell',
       'axel_de_vries',
       'axel_a._weber',
       'axel_d._becke',
       'axe_edge_moor',
       'axe_of_perun',
       'axel_h._reed',
       'axel_j._beck',
       'axe_to_fall'],
 'h': ['axholme_joint_railway'],
 'i': ['axillary_nerve_dysfunction',
       'axiom_of_constructibility',
       'axis_lines_international',
       'axiality_and_rhombicity',
       'axiom_of_extensionality',
       'axial_multipole_moments',
       'axiom_of_reducibility',
       'axiom_orbital_segment',
       'axiom_of_categoricity',
       'axiom_of_countability',
       'axillary_nerve_palsy',
       'axiom_of_determinacy',
       'axillary_lymph_nodes',
       'axiom_of_adjunction',
       'axidares_of_armenia',
       'axiom_of_non-choice',
       'axiom_of_regularity',
       'axioma_ethica_odini',
       'axial_stone_circle',
       'axiothea_of_phlius',
       'axis_of_resistance',
       'axixa_do_tocantins',
       'axis_dance_company',
       'axis_bird_stadium',
       'axial_piston_pump',
       'axiom_of_infinity',
       'axial_fan_design',
       'axial_flow_valve',
       'axial_flux_motor',
       'axis_mutual_fund',
       'axiom_of_pairing',
       'axiom_of_equity',
       'axis_and_allies',
       'axis_of_advance',
       'axial_pen_force',
       'axis_of_justice',
       'axiom_mission_1',
       'axiom_mission_2',
       'axiom_of_choice',
       'axiom_of_union',
       'axiom_of_maria',
       'axiom_verge_2',
       'axis_of_evil',
       'axis_of_evol',
       'axis_of_eden',
       'axis_of_time',
       'axis_of_eve'],
 'l': ['axley_brynelson,_llp'],
 'm': ['axminster_railway_station',
       'axminster_rural_district',
       'axminster_town_a.f.c.',
       'axm_futsal_manado'],
 'n': ['axn_action_awards', 'axn_sci_fi'],
 'o': ['axonic_informationssysteme_gmbh'],
 'p': ['axp_1e_1048-59'],
 's': ['axs_tv_fights'],
 't': ['axtell_high_school', 'axtla_de_terrazas', 'axtell_j._byles'],
 'u': ["axur,_re_d'ormus"],
 'w': ['axwell_and_ingrosso'],
 'x': ['axxess_technology_solutions', 'axxess_and_ace']}
