
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ez = {'_': ['ez3kiel', 'ez-link', 'ez-poly', 'ez2dj', 'ez-7'],
 'a': ['ezanville',
       'ezabad',
       'ezaart',
       'ezaki',
       'ezaro',
       'ezafe',
       'ezair',
       'ezan',
       'eza'],
 'b': ['ezbaram', 'ezboard', 'ezbaran', 'ezbob'],
 'c': ['ezcabarte', 'ezcaray', 'ezcater', 'ezcast', 'ezcorp'],
 'e': ['ezetimibe/atorvastatin',
       'ezetimibe/rosuvastatin',
       'ezetimibe/simvastatin',
       'ezergailis',
       'ezerkrasts',
       'ezeriekai',
       'ezetimibe',
       'ezetaerre',
       'ezeritai',
       'ezequias',
       'ezerelis',
       'ezequiel',
       'eze-igwe',
       'ezekiel',
       'ezerets',
       'ezeleke',
       'ezernet',
       'ezerche',
       'ezevets',
       'ezernya',
       'ezeroto',
       'ezerovo',
       'ezerani',
       'ezenwa',
       'ezeagu',
       'ezeris',
       'ezerjo',
       'ezekwe',
       'ezeiza',
       'ezeilo',
       'ezego',
       'ezell',
       'ezel',
       'ezer',
       'ezem',
       'ezeh',
       'eze'],
 'f': ['ezf'],
 'g': ['ezgenerator', 'ezgeleh', 'ezgi'],
 'h': ['ezhamkadalinakkare',
       'ezhuthiyatharadi',
       'ezhumanthuruthu',
       'ezhuthapurangal',
       'ezhuvathiruthy',
       'ezharakoottam',
       'ezhunnallathu',
       'ezhuvanthala',
       'ezhumattoor',
       'ezhamkulam',
       'ezhakadavu',
       'ezhupunna',
       'ezhudesam',
       'ezhikkara',
       'ezhumalai',
       'ezhantsy',
       'ezhukone',
       'ezhiyeh',
       'ezhumin',
       'ezhome',
       'ezhava',
       'ezhou',
       'ezhel',
       'ezhil',
       'ezh2',
       'ezha',
       'ezh1',
       'ezh'],
 'i': ['ezion-geber',
       'ezibeleni',
       'eziowelle',
       'eziobodo',
       'ezinkulu',
       'ezinachi',
       'eziorsu',
       'ezidxan',
       'eziama',
       'ezinma',
       'ezibuy',
       'ezinge',
       'eziran',
       'ezira',
       'ezio',
       'ezi'],
 'k': ['ezkio-itsaso', 'ezkerekotxa', 'ezkaton', 'ezkurra', 'ezkimo', 'ezkio'],
 'l': ['ezlopitant'],
 'm': ['ezmareh', 'ezmol', 'ezmlm', 'ezmo'],
 'n': ['eznaveleh', 'eznabad', 'eznav'],
 'o': ['ezofficeinventory',
       'ezosciadium',
       'ezorongondo',
       'ezourvedam',
       'ezoloba',
       "ezo'la",
       'ezov',
       'ezop',
       'ezo'],
 'p': ['ezprogui', 'ezproxy'],
 'r': ['ezra-nehemiah', 'ezra-nama', 'ezride', 'ezrin', 'ezri', 'ezra', 'ezr'],
 's': ['ezs'],
 't': ['eztable', 'eztv'],
 'u': ['ezutromid', 'ezumeri', 'ezubao', 'ezuz'],
 'y': ['ezy-sur-eure', 'ezycom', 'ezydvd'],
 'z': ['ezz-thetics',
       'ezzaouite',
       'ezzatabad',
       'ezzouhour',
       'ezzahabad',
       'ezzhiliga',
       'ezzolied',
       'ezzelini',
       'ezzonids',
       'ezzahra',
       'ezzell',
       'ezzoud',
       'ezzat',
       'ezzo',
       'ezz']}
