
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_eh = {'_': ["eh'hausl"],
 'a': ['ehalagastenna',
       'ehalamalpe',
       'ehatisaht',
       'ehari-ali',
       'eharmony',
       'ehavere',
       'eharius',
       'eha101',
       'ehang',
       'ehara',
       'ehaa',
       'eha'],
 'b': ['ehb'],
 'c': ['ehcache', 'ehcc', 'ehc'],
 'd': ['ehd-e-wafa', 'ehden', 'ehd4', 'ehd1', 'ehdd', 'ehd3', 'ehd2', 'ehd'],
 'e': ['ehealthinsurance',
       'ehestandshilfe',
       'ehecatotontli',
       'eheliyagoda',
       'ehekirchen',
       'ehelakanda',
       'ehenbichl',
       'ehelapola',
       'ehealthme',
       'ehelepola',
       'ehenbach',
       'ehesuma',
       'ehecatl',
       'ehelape',
       'ehengah',
       'ehealth',
       'ehenas',
       'ehenye',
       'eheke',
       'eheim',
       'ehesp',
       'ehein',
       'ehen',
       'ehe'],
 'f': ['ehf'],
 'g': ['ehg'],
 'h': ['ehhadh', 'ehhs'],
 'i': ['ehikhamenor', 'ehirava', 'ehinger', 'ehingen', 'ehis', 'ehin', 'ehi'],
 'l': ['ehlange-sur-mess',
       'ehlscheid',
       'ehlerange',
       'ehlinger',
       'ehllapi',
       'ehlbeck',
       'ehlmann',
       'ehlers',
       'ehlert',
       'ehlenz',
       'ehloec',
       'ehlen',
       'ehle',
       'ehl'],
 'm': ['ehmaniella',
       'ehmcke',
       'ehmann',
       'ehmej',
       'ehman',
       'ehmer',
       'ehmja',
       'ehmt1',
       'ehmt2',
       'ehmen',
       'ehm'],
 'n': ['ehningen', 'ehnahre', 'ehndorf', 'ehnen', 'ehna', 'ehn'],
 'o': ['ehoron.com', 'ehostela', 'eholmen', 'eholt', 'ehome', 'ehow', 'eho'],
 'p': ['ehp'],
 'r': ['ehrenfriedersdorf',
       'ehrenbreitsteiner',
       'ehrhardt-szawe',
       'ehringshausen',
       'ehrlichiaceae',
       'ehrendorferia',
       'ehrichspitze',
       'ehretioideae',
       'ehrenkirchen',
       'ehra-lessien',
       'ehrlichiosis',
       'ehrendingen',
       'ehrenfelser',
       'ehrenhausen',
       'ehrentempel',
       'ehrenfried',
       'ehrenstein',
       'ehrharteae',
       'ehrenreich',
       'ehrensvard',
       'ehrenpreis',
       'ehrenhalt',
       'ehrenfest',
       'ehrenburg',
       'ehrlichia',
       'ehrengard',
       'ehrnrooth',
       'ehrenfels',
       'ehrenfeld',
       'ehrenberg',
       'ehrenbaum',
       'ehrengrab',
       'ehrharta',
       'ehrhardt',
       'ehrgeiz',
       'ehrmann',
       'ehrling',
       'ehrlich',
       'ehretia',
       'ehrwald',
       'ehrhart',
       'ehrich',
       'ehrler',
       'ehren',
       'ehret',
       'ehrl',
       'ehrc',
       'ehr'],
 's': ['ehsanullah', 'ehsanabad', 'ehsaas', 'ehsaan', 'ehs'],
 't': ['ehtesaab', 'ehtesham', 'eht'],
 'u': ['ehursag', 'ehuasso', 'ehuns', 'ehui', 'ehud', 'ehu'],
 'v': ['ehv'],
 'w': ['ehweiler', 'ehwaz'],
 'y': ['ehyophsta', 'ehya']}
