
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ee = {'_': ['ee.ma.yau.', 'ee-mat-la', 'ee-media'],
 'a': ['eea1', 'eea'],
 'b': ['eebus', 'eeb'],
 'c': ['eeckhout', 'eecke', 'eecca', 'eecs', 'eecc', 'eeca'],
 'd': ['eeden', 'eedes', 'eedu', 'eeda', 'eede', 'eed'],
 'e': ['eee'],
 'f': ['eef1a1p43',
       'eef1b2p3',
       'eef1b2p1',
       'eef1b2p2',
       'eefting',
       'eefsele',
       'eef1e1',
       'eef1b2',
       'eefing',
       'eef1a2',
       'eef2k',
       'eefje',
       'eef1d',
       'eef1g',
       'eefde',
       'eef-1',
       'eef2',
       'eefl',
       'eef'],
 'g': ['eegonos', "eegee's", 'eegecs', 'eeglab', 'eegah', 'eega'],
 'h': ['eehongo', 'eehs'],
 'i': ['eei'],
 'j': ['eejanaika', 'eejit', 'eej'],
 'k': ['eek-a-nomics',
       'eek-a-mouse',
       'eekeemoo',
       'eekhout',
       'eekwol',
       'eekman',
       'eeklo',
       'eek'],
 'l': ['eelderwolde',
       'eelamurasu',
       'eelanatham',
       'eelgrass',
       'eelanadu',
       'eelpout',
       'eelume',
       'eelmaa',
       'eelmae',
       'eells',
       'eelco',
       'eelam',
       'eelde',
       'eeles',
       'eelv',
       'eel'],
 'm': ['eemsdelta',
       'eembrugge',
       'eemshaven',
       'eemsmond',
       'eemster',
       'eemdijk',
       'eemmeer',
       'eemnes',
       'eemian',
       'eemeli',
       'eembc',
       'eem'],
 'n': ['eendrachtsland',
       'eenoolooapik',
       'eenigenburg',
       'eenvandaag',
       'eendekuil',
       'eendracht',
       'een-west',
       'eendragt',
       'eenhoorn',
       'eenhana',
       'eenpalu',
       'eensaar',
       'eenadu',
       'eenrum',
       'eenam',
       'eense',
       'eenet',
       'een'],
 'o': ['eeoneguy', 'eeo'],
 'p': ['eepybird', 'eeprom', 'eepee', 'eep'],
 'r': ['eerieconsiliation',
       'eeriksaare',
       'eerikukivi',
       'eersterust',
       'eerstegoud',
       'eerikulaid',
       'eerstehoek',
       'eersteling',
       'eerikvere',
       'eerdeent',
       'eernegem',
       'eeriecon',
       'eerikki',
       'eerbeek',
       'eersel',
       'eerola',
       'eerma',
       'eerie',
       'eerde',
       'eeram',
       'eerik',
       'eero',
       'eerc',
       'eera',
       'eer'],
 's': ['eestilepididae',
       'eesergroen',
       'eeserveen',
       'eestirand',
       'eeswaran',
       'eesnurga',
       'eestairs',
       'eesterga',
       'eeshwar',
       'eeskula',
       'eestor',
       'eesi',
       'eesa',
       'ees'],
 't': ['eettappuli',
       'eettillam',
       'eetion',
       'eethen',
       'eetch',
       'eetti',
       'eetu',
       'eets',
       'eeta',
       'eet'],
 'u': ['eeuwfeestkliniek'],
 'v': ['eevee', 'eeves', 'eeva', 'eev'],
 'w': ['eewh'],
 'x': ['eexterveenschekanaal',
       'eexterzandvoort',
       'eexterveen',
       'eextra',
       'eexam',
       'eext',
       'eex'],
 'y': ['eeyeekalduk', 'eeyore'],
 'z': ['eez-eh']}
