
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ml = {'_': ['ml_motorsports',
       'ml_aviation',
       'ml_fairness',
       'ml_procise',
       'ml_domain',
       'ml_happy'],
 'a': ['mladen_ivankovic-lijanovic',
       'mladen_sljivancanin',
       'mladen_velimirovic',
       'mladen_veselinovic',
       'mladen_milovanovic',
       'mladen_vilotijevic',
       'mladenko_miskovic',
       'mladen_tepavcevic',
       'mladenka_malenica',
       'mlaka,_radovljica',
       'mladen_bogdanovic',
       'mlada_veselinovic',
       'mladen_krizanovic',
       'mladen_mihajlovic',
       'mladen_stilinovic',
       'mladen_bartolovic',
       'mladen_munjakovic',
       'mladen_plakalovic',
       'mladen_vladojevic',
       'mladen_milinkovic',
       'mladen_mladenovic',
       'mladen_stojanovic',
       'mladen_bartulovic',
       'mladen_brestovac',
       'mlado_nagoricane',
       'mladen_lazarevic',
       'mladen_bojinovic',
       'mladen_kujundzic',
       'mladen_zeljkovic',
       'mladen_srbinovic',
       'mladen_milicevic',
       'mladen_kovacevic',
       'mladen_micanovic',
       'mladen_sekularac',
       'mladen_dabanovic',
       'mladen_vukasovic',
       'mladen_vrankovic',
       'mladen_grujicic',
       'mladen_lorkovic',
       'mladen_khristov',
       'mladen_mladenov',
       'mladen_mitrovic',
       'mladen_karoglan',
       'mlakva,_perusic',
       'mladen_georgiev',
       'mladen_stefanov',
       'mladen_kascelan',
       'mladen_knezevic',
       'mladen_rakcevic',
       'mladen_bestvina',
       'mlandvo_shongwe',
       'mladen_matkovic',
       'mlabri_language',
       'mladen_krstajic',
       'mladost_stadium',
       'mladen_budiscak',
       'mladen_jurcevic',
       'mladen_zivkovic',
       'mlahso_language',
       'mladena_petrova',
       'mladika_complex',
       'mladen_vitkovic',
       'mladen_jankovic',
       'mladen_drazetin',
       'mladen_lambulic',
       'mladen_sarajlin',
       'mladen_sarcevic',
       'mladen_boskovic',
       'mlawianka_mlawa',
       'mladan_dordevic',
       'mlaka,_komenda',
       'mlady_smolivec',
       'mladan_silobad',
       'mla_fatakeshto',
       'mladen_popovic',
       'mladen_prskalo',
       'mladen_jeremic',
       'mladen_francic',
       'mlake,_metlika',
       'mladen_devetak',
       'mladen_pralija',
       'mladen_grdovic',
       'mladen_ivancic',
       'mladen_subaric',
       'mlawu_kararabe',
       'mlakva,_kupres',
       'mladost_trophy',
       'mlaka,_croatia',
       'mlada_boleslav',
       'mladen_bozovic',
       'mladen_erjavec',
       'mladen_bojanic',
       'mladan_janovic',
       'mladen_zujovic',
       'mladost,_sofia',
       'mladen_furtula',
       'mlaka_antinska',
       'mladen_kiselov',
       'mladen_rudonja',
       'mladen_kukrika',
       'mladen_vasilev',
       'mladen_stoicev',
       'mladen_zizovic',
       'mladen_ramljak',
       'mladen_zganjer',
       'mladen_banovic',
       'mladen_posavec',
       'mladost,_varna',
       'mlap_language',
       'mladen_stanev',
       'mladen_jutric',
       'mladen_ivanic',
       'mladen_petric',
       'mladen_koscak',
       'mladen_markac',
       'mlangeni_nawa',
       'mladen_licina',
       'mladen_ristic',
       'mladen_kuchev',
       'mladen_zrilic',
       'mladen_kranjc',
       'mladen_vranic',
       'mladen_pelaic',
       'mladen_stegic',
       'mladen_grujic',
       'mlabri_people',
       'mladan_dinkic',
       'mladen_pantic',
       'mladen_bratic',
       'mladen_kalpic',
       'mladen_dolar',
       'mlada_vozice',
       'mladen_kasic',
       'mladen_bosic',
       'mladen_palac',
       'mladen_cucic',
       'mladen_vujic',
       'mladen_romic',
       'mladen_stoev',
       'mladen_vulic',
       'mladen_kapor',
       'mladen_mitic',
       'mladec_caves',
       'mladen_galic',
       'mladen_delic',
       'mlade_briste',
       'mladen_kocic',
       'mladen_wacha',
       'mladen_bajic',
       'mladen_cukon',
       'mlada_fronta',
       'mladen_saric',
       'mladost_hall',
       'mladen_dodic',
       'mladen_ninic',
       'mladen_lukic',
       'mladen_colic',
       'mlawa_county',
       'mladen_josic',
       'mladen_brkic',
       'mladen_basic',
       'mladen_juran',
       'mla_handbook',
       'mladen_urem',
       'mlake,_muta',
       'mlandege_fc',
       'mladen_veza',
       'mladen_hren',
       'mlade_slade',
       'mlady_svet',
       'mlawa_riot',
       'mlada_hora',
       'mlade_buky',
       'mlad_borec'],
 'b': ['mlb_international',
       'mlb_superstars',
       'mlb_whiparound',
       'mlbpa_baseball',
       'mlb_stickball',
       'mlb_slugfest',
       'mlb_showdown',
       'mlb_lockout',
       'mlb_tonight',
       'mlb_network',
       'mlb_2001',
       'mlb_2000',
       'mlb_2k13',
       'mlb_2002',
       'mlb_2003',
       'mlb_2004',
       "mlb_'99",
       "mlb_'98",
       'mlb_2k'],
 'c': ['mlc_building', 'mlc_limited', 'mlc_school'],
 'd': ['mldesigner', 'mldonkey', 'mld'],
 'e': ['mlecchita_vikalpa',
       'mlechchha_dynasty',
       'mlekara_subotica',
       'mlele_district',
       'mlengana_pass'],
 'f': ['mlf1ip', 'mlf1', 'mlf'],
 'g': ['mlgb', 'mlg'],
 'h': ['mlhlnd', 'mlh1', 'mlhs', 'mlh3', 'mlh'],
 'i': ['mliniste,_croatia',
       'mlinaric_family',
       'mlib_tmetuchl',
       'mlimani_city',
       'mlibo_ngewu',
       'mlily_cup'],
 'j': ['mljet', 'mlj'],
 'k': ['mlk/fbi'],
 'l': ['mll-pll_merger',
       'mlle_raucourt',
       'mlle._modiste',
       'mlle_bocquet',
       'mlle_guerin',
       'mlle_marthe',
       'mlle_duval',
       'mll_draft'],
 'm': ['mlma', 'mlm'],
 'n': ['mln-29', 'mln'],
 'o': ['mlodziejowski_palace',
       'mloda_ekstraklasa',
       'mlodocin_mniejszy',
       'mlodocin_wiekszy',
       'mlodawin_dolny',
       'mlodawin_gorny',
       'mlomp_language',
       'mlodynie_gorne',
       'mlodynie_dolne',
       'mlondi_dlamini',
       'mlomp,_bignona',
       'mlodzawy_duze',
       'mlody_niedroz',
       'mlola_bwawani',
       'mlodzawy_male',
       'mloda_liga',
       'mlody_las'],
 'p': ['mlp_se'],
 'q': ['mlq'],
 'r': ['mlr_draft'],
 's': ['mls_superdraft', 'mls_extratime', 'mls_combine', 'mls_next', 'mls_cup'],
 't': ['mlt-3_encoding'],
 'u': ['mlungisi_mbunjana',
       'mlungisi_ngubane',
       'mluleki_nobanda',
       'mlungisi_mdluli',
       'mlungisi_mvoko',
       'mlungisi_ngece',
       'mluleki_george',
       'mluleki_nkala',
       'mlungisi_bali',
       'mluleki_ndobe'],
 'v': ['mlvm', 'mlv'],
 'w': ['mlw_superfight',
       'mlw_fightland',
       'mlw_wargames',
       'mlw_genesis',
       'mlw_rsc-24',
       'mlw_reload',
       'mlw_fusion',
       'mlw_rsc-14',
       'mlw_rsc-13',
       'mlw_rs-23',
       'mlw_m-636',
       'mlw_m-420',
       'mlw_rs-18',
       'mlw_rs-10'],
 'x': ['mlx'],
 'y': ['mlynske_struhadlo',
       'mlynek_nieswinski',
       'mlyny_piekarskie',
       'mlyniec_pierwszy',
       'mlynow,_warsaw',
       'mlynska_dolina',
       'mlyn_idzbarski',
       'mlynarska_wola',
       'mlynskie_stawy',
       'mlyniec_drugi',
       'mlyniv_raion',
       'mlyn_gorny',
       'mlyn_dolny']}
