
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mw = {'_': ['mw_polyomavirus',
       'mw_motorsport',
       'mw_propellers',
       'mw_18014',
       'mw_tops',
       'mw_tux',
       'mw_50',
       'mw_dx'],
 'a': ['mwananchi_communications',
       'mwansabombwe_district',
       'mwatate_constituency',
       'mwadingusha_airport',
       'mwanahamisi_shurua',
       'mwaghavul_language',
       'mwandawiro_mghanga',
       'mwananyanda_liwale',
       'mwala_constituency',
       'mwazulu_diyabanza',
       'mwakenya_movement',
       'mwangwego_script',
       'mwachirunge_bomu',
       'mwatebu_language',
       'mwanga,_tanzania',
       'mwanga_district',
       'mwanga_language',
       'mwanza_district',
       'mwami,_zimbabwe',
       'mwakai_language',
       'mwamba_luchembe',
       'mwandi_district',
       'mwangi_kiunjuri',
       'mwalutshe_bwadi',
       'mwampule_masule',
       'mwachema_river',
       'mwanza,_malawi',
       'mwadui_airport',
       'mwabaya_nyundo',
       'mwanza_airport',
       'mwaro_province',
       'mwanalima_adam',
       'mwani_language',
       'mwanza_mukombo',
       'mwangi_ruheni',
       'mwanga_people',
       'mwami,_zambia',
       'mwai_kumwenda',
       'mwape_musonda',
       'mwanza_region',
       'mwan_language',
       'mwanawina_ii',
       'mwanesi_mine',
       'mwadi_mabika',
       'mwana_kupona',
       'mwanza_lomba',
       'mwani_people',
       'mwape_mwelwa',
       'mwalimu_ally',
       'mwata_bowden',
       'mwana_mwinga',
       'mwape_mialo',
       'mwanda_peak',
       'mwanawina_i',
       'mwai_kibaki',
       'mwata_yamvo',
       'mwaka_moon',
       'mwape_miti',
       'mwamba_rfc',
       'mwana_fa'],
 'b': ['mwb'],
 'c': ['mwc_480', 'mwc_349'],
 'd': ['mwdwl-eithin', 'mwd'],
 'e': ['mweelrea_formation',
       'mwene-ditu_airport',
       'mwea_constituency',
       'mwesigwa_rukutana',
       'mwei_ma-gu-thauk',
       'mwenezi_district',
       'mwenga_territory',
       'mwerlap_language',
       'mweka_territory',
       'mwera,_zanzibar',
       'mwense_district',
       'mwesen_language',
       'mwera_language',
       'mwele_language',
       'mweze_ngangura',
       'mwei_ohn-naung',
       'mweya_airport',
       'mweka_airport',
       'mwetaung_mine',
       'mwenezi_river',
       'mwema_ndungo',
       'mwenda_njoka',
       'mwepu_ilunga',
       'mwera_people',
       'mwewe_river',
       'mwei_thin',
       'mwei_zeik',
       'mwei_auk',
       'mwei_kaw',
       'mwei_daw',
       'mwei_it'],
 'f': ['mwfly_b22', 'mwfly_b25'],
 'g': ['mwg'],
 'h': ['mwh_global'],
 'i': ['mwinilunga_district',
       'mwinyi_kazimoto',
       'mwingi_district',
       'mwika_kaskazini',
       'mwigulu_nchemba',
       'mwinga_mwanjala',
       'mwiza_munthali',
       'mwita_waitara',
       'mwika_kusini',
       'mwindo_epic',
       'mwila_phiri'],
 'l': ['mwl'],
 'm': ['mwm'],
 'n': ['mwng', 'mwnt', 'mwn'],
 'o': ['mwotlap_language', 'mwogo_river'],
 'p': ['mwp'],
 'r': ['mwrank', 'mwr'],
 's': ['mwsa', 'mws'],
 'u': ['mwuetsi', 'mwua', 'mwu'],
 'v': ['mwv'],
 'w': ['mww'],
 'y': ['mwyngloddfa_llechweddhelyg',
       'mwyngloddfa_cwmystwyth',
       'mwyngloddfa_cwmbrwyno',
       'mwyngloddfa_brynyrafr',
       'mwyngloddfa_nantiago',
       'mwyngloddfa_castell']}
