
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mm = {'_': ['mm2_entertainment',
       "mm'-type_filter",
       'mm-1_minimore',
       'mm_algorithm',
       'mm_shahin',
       'mm_tree',
       'mm_cohn',
       'mm_code',
       'mm_54'],
 'a': ['mmamoloko_kubayi-ngubane',
       'mmasekgoa_masire-mwamba',
       'mmabatho_mogomotsi',
       'mmabatho_ramagoshi',
       'mmabatho_stadium',
       'mmabatho_montsho',
       'mmabatho_mokause',
       'mmabana_stadium',
       'mma_fighting',
       'mma_creative',
       'mmamu_river',
       'mma_factory',
       'mma_gloves',
       'mma_raju',
       'mma_club',
       'mma_live',
       'mma_729',
       'mma_507',
       'mma_56',
       'mma_60',
       'mma_57',
       'mma_59'],
 'b': ['mmb-chmica', 'mmb-2201', 'mmb'],
 'c': ['mmc_automotriz', 'mmcx_connector', 'mmc_hospital'],
 'd': ['mmda_tv'],
 'e': ["mme._d'esperance",
       'mmen_language',
       'mme_papavoine',
       'mme_pavoshko',
       'mme_delaval',
       'mme_sicard'],
 'f': ['mmfa', 'mmff', 'mmf'],
 'g': ['mmg_limited'],
 'h': ['mmhss_thalassery', 'mmhonlumo_kikon', 'mmh-badger_mac'],
 'i': ['mmiata_anam'],
 'j': ['mmj'],
 'k': ['mmk-atakas_metallurgy'],
 'l': ['mmlp', 'mml'],
 'm': ['mmm_toamasina', 'mmm_global', 'mmm_yeah'],
 'n': ['mmn-1_mine', 'mmn-2_mine'],
 'o': ['mmoaninko_festival',
       'mmoloki_mooketsi',
       'mmoloki_chrystie',
       'mmoloki_cwaile',
       'mmoloki_nogeng'],
 'p': ['mmpl_kanpur'],
 'r': ['mmrv_vaccine', 'mmr_vaccine'],
 's': ['mms-class_minesweeper', 'mms_architecture'],
 't': ['mmt_observatory', 'mmts_kwidzyn', 'mmtc_ltd'],
 'u': ['mmuock_language', 'mmusi_maimane', 'mmuock_leteh', 'mmusa_ohilwe'],
 'v': ['mmv'],
 'w': ['mmw'],
 'x': ['mmx_mineracao'],
 'z': ['mmz']}
