
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zv = {'a': ['zvaigzdziakalnis',
       'zvarykino',
       'zvanovice',
       'zvaigznes',
       'zvartnots',
       'zvarulje',
       'zvakwana',
       'zvanarka',
       'zvabovo',
       'zvarych',
       'zvanika',
       'zvasiya',
       'zvare',
       'zvara',
       'zvala',
       'zvana',
       'zvan',
       'zvab'],
 'e': ['zverinogolovskoye',
       'zverinogolovsky',
       'zvenigorodskaya',
       'zverosovkhoz',
       'zvenyhorodka',
       'zveglevitsy',
       'zvenigorod',
       'zvenyhorod',
       'zveniachyn',
       'zveglivets',
       'zvezdelina',
       'zvestovice',
       'zvelgaitis',
       'zverkovice',
       'zvenigovo',
       'zvezdopad',
       'zvekovica',
       'zverotice',
       'zvenigora',
       'zvejnieks',
       'zventsovo',
       'zverinets',
       'zvezdets',
       'zverinac',
       'zverinek',
       'zvezdara',
       'zvenella',
       'zverotic',
       'zverynas',
       'zvernec',
       'zvestov',
       'zvezden',
       'zverina',
       'zvezdin',
       'zvezdel',
       'zverevo',
       'zvezdan',
       'zvecevo',
       'zvecan',
       'zvezda',
       'zverev',
       'zvecka',
       'zvezd',
       'zveno',
       'zveri',
       'zver',
       'zven'],
 'i': ['zvirgzdaiciai',
       'zvishavane',
       'zvijerina',
       'zvirovici',
       'zvirnjaca',
       'zviadists',
       'zvijerci',
       'zvijerka',
       'zvikovec',
       'zvingiai',
       'zvijezda',
       'zvinitsa',
       'zvirici',
       'zvijezd',
       'zvizdar',
       'zvirce',
       'zvikov',
       'zviane',
       'zvizej',
       'zviad',
       'zvika',
       'zvizd',
       'zvi'],
 'm': ['zvm'],
 'o': ['zvolenovice',
       'zvoleneves',
       'zvoristea',
       'zvonnitsa',
       'zvonimir',
       'zvoncari',
       'zvoncin',
       'zvotoky',
       'zvornik',
       'zvolen',
       'zvonko',
       'zvodno',
       'zvonik',
       'zvonce',
       'zvony',
       'zvole',
       'zvon'],
 'p': ['zvpl'],
 'u': ['zvunche', 'zvunka', 'zvue'],
 'y': ['zvyozdochka',
       'zvyagintsev',
       'zvyaglovka',
       'zvyozdnaya',
       'zvyozdny',
       'zvyagino',
       'zvyozdka',
       'zvyzhen',
       'zvyazda',
       'zvyagin']}
