
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lv = {'_': ['lv_vulpeculae', 'lv_1871', 'lv_cup'],
 'a': ['lvac', 'lvad', 'lva'],
 'c': ['lvcmos', 'lvcc', 'lvc'],
 'd': ['lvd'],
 'e': ['lvea'],
 'f': ['lvf'],
 'g': ['lvg_c.viii',
       'lvg_g.iii',
       'lvg_d.iii',
       'lvg_d.iv',
       'lvg_c.vi',
       'lvg_d.vi',
       'lvg_d.ii',
       'lvg_c.ii',
       'lvg_e.i',
       'lvg_c.v',
       'lvg_d.v',
       'lvg_g.i',
       'lvg_b.i'],
 'h': ['lvhs_pothencode', 'lvh_academy'],
 'i': ['lviv_conservatory',
       'lviv_polytechnic',
       'lviv_chronicle',
       'lviv_railways',
       'lviv_airlines',
       'lviv_stadium',
       'lviv_arsenal',
       'lvinaya_past',
       'lviv_pogrom',
       'lviv_oblast',
       'lviv_today',
       'lviv_raion',
       'lviv_metro'],
 'j': ['lvj'],
 'l': ['lvl_up', 'lvl_iv', 'lvl._1'],
 'm': ['lvmh_tower'],
 'n': ['lvn_pictures'],
 'o': ['lvov-sandomierz_offensive', 'lvov_dvor'],
 'p': ['lvp'],
 'r': ['lvrr', 'lvr'],
 's': ['lvs-97', 'lvs-86', 'lvsv', 'lvsd', 'lvs'],
 't': ['lvtp-5', 'lvt'],
 'v': ['lvvpu', 'lvv'],
 'x': ['lvx'],
 'z': ['lvzbel', 'lvz']}
