
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_wp = {'_': ['wp_motorsports',
       'wp_suspension',
       'wp_diamonds',
       'wp_theater',
       'wp_rocket',
       'wp_nel',
       'wp_35'],
 'a': ['wpa_architecture', 'wpa_supplicant', 'wpa_rustic'],
 'b': ['wpb_anders', 'wpba_tour'],
 'c': ['wpcs_international', 'wpc_56'],
 'd': ['wpds-ld',
       'wpdx-fm',
       'wpde-tv',
       'wpdf-lp',
       'wpdm',
       'wpds',
       'wpdr',
       'wpdt',
       'wpdq',
       'wpdc',
       'wpdh',
       'wpdx',
       'wpda',
       'wpd'],
 'e': ['wpeh-fm',
       'wpeo-fm',
       'wpen-lp',
       'wpel-fm',
       'wpen',
       'wpeo',
       'wpeg',
       'wpeh',
       'wpec',
       'wpet',
       'wpez',
       'wpep',
       'wpeb',
       'wpel',
       'wpek',
       'wpea',
       'wpex',
       'wpei',
       'wper',
       'wpe'],
 'f': ['wpfr-fm',
       'wpfx-fm',
       'wpfw',
       'wpfp',
       'wpfg',
       'wpfb',
       'wpfl',
       'wpff',
       'wpfm',
       'wpfo',
       'wpft',
       'wpfd',
       'wpfc',
       'wpfj',
       'wpfr',
       'wpf'],
 'g': ['wpg_resources'],
 'h': ['wphr-fm',
       'wphi-fm',
       'wpha-cd',
       'wphl-tv',
       'wphy-cd',
       'wphe',
       'wphm',
       'wphl',
       'wphr',
       'wphc',
       'wpht',
       'wphx',
       'wphb',
       'wphp',
       'wphn',
       'wphh',
       'wphd',
       'wphs',
       'wphk',
       'wphz'],
 'i': ['wpi_engineers'],
 'j': ['wpji-lp',
       'wpjn',
       'wpjw',
       'wpjk',
       'wpjy',
       'wpjc',
       'wpjm',
       'wpjp',
       'wpjs',
       'wpjl',
       'wpjf',
       'wpjx'],
 'k': ['wpko-fm',
       'wpkm-lp',
       'wpka-lp',
       'wpke-fm',
       'wpky',
       'wpkv',
       'wpkq',
       'wpkf',
       'wpkg',
       'wpke',
       'wpkr',
       'wpkz',
       'wpkn',
       'wpkl',
       'wpk'],
 'l': ['wplywologia',
       'wpls-lp',
       'wplm-fm',
       'wplp-lp',
       'wplw-fm',
       'wpln-fm',
       'wpli',
       'wplr',
       'wplm',
       'wplo',
       'wpla',
       'wpln',
       'wpll',
       'wplg',
       'wplw',
       'wplh',
       'wply',
       'wplk',
       'wplb',
       'wplt',
       'wplp',
       'wplx',
       'wplj',
       'wplv',
       'wpl'],
 'm': ['wpmi-tv',
       'wpmr-lp',
       'wpmo',
       'wpmz',
       'wpmj',
       'wpmx',
       'wpmb',
       'wpmt',
       'wpmh',
       'wpmw',
       'wpm'],
 'n': ['wpnc-fm',
       'wpny-ld',
       'wpnh-fm',
       'wpna-fm',
       'wpnv-lp',
       'wpnm-ld',
       'wpnr-fm',
       'wpng',
       'wpnh',
       'wpnn',
       'wpno',
       'wpna',
       'wpni',
       'wpne',
       'wpns',
       'wpnt',
       'wpnw'],
 'o': ['wpov-lp',
       'wpos-fm',
       'wpoi',
       'wpop',
       'wpon',
       'wpoz',
       'wpog',
       'wpoa',
       'wpoc',
       'wpol',
       'wpob',
       'wpow',
       'wpok',
       'wpot',
       'wpor',
       'wpom',
       'wpo'],
 'p': ['wpp_domain', 'wpp_aunz', 'wpp_plc'],
 'q': ['wpqp', 'wpqr'],
 'r': ['wpromote',
       'wprw-fm',
       'wprt-fm',
       'wpri-tv',
       'wprr-fm',
       'wprf-lp',
       'wpru-lp',
       'wprz-fm',
       'wprs-fm',
       'wpro-fm',
       'wprost',
       'wprime',
       'wprs',
       'wprp',
       'wpro',
       'wprf',
       'wprm',
       'wprt',
       'wprb',
       'wprx',
       'wprz',
       'wpre',
       'wprl',
       'wpry',
       'wprj',
       'wprv',
       'wprd',
       'wprk',
       'wprr',
       'wpra',
       'wpr'],
 's': ['wps_office', 'wps_racing'],
 't': ['wpts-fm',
       'wptg-cd',
       'wptv-tv',
       'wpta',
       'wptw',
       'wptc',
       'wptb',
       'wptm',
       'wpth',
       'wptj',
       'wptx',
       'wptz',
       'wptd',
       'wptp',
       'wptf',
       'wpte',
       'wptt',
       'wpti',
       'wptq',
       'wpty',
       'wptr',
       'wptn',
       'wptl',
       'wpt'],
 'u': ['wpuc-fm', 'wpub-fm', 'wput', 'wpum', 'wpul', 'wpur', 'wpup', 'wpu'],
 'v': ['wpvm-lp',
       'wpvn-cd',
       'wpvq-fm',
       'wpvi-tv',
       'wpvc-lp',
       'wpvl-fm',
       'wpvs-ld',
       'wpvq',
       'wpvd',
       'wpvh',
       'wpvm',
       'wpvr',
       'wpvl',
       'wpv'],
 'w': ['wpwr-tv', 'wpwx', 'wpwc', 'wpwt', 'wpwz', 'wpwa', 'wpwq'],
 'x': ['wpx_energy'],
 'y': ['wpyx', 'wpyr', 'wpyb', 'wpyo', 'wpya', 'wpyk', 'wpy'],
 'z': ['wpzm-lp', 'wpze', 'wpzs', 'wpza', 'wpzr', 'wpzz', 'wpz']}
