
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-25T22:43:17-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9bbf29ab372eeb291ddd4afdcd83a54ed89324c8",
 "version": "v0.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
