
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-26T11:28:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "85746b79dae549e500dc39e6312a6c029fbc279b",
 "version": "0.3.150"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
