
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_z_ = {'_': ['z80-rio',
       'z39.87',
       'z39.50',
       'z80182',
       'z1243',
       'z1210',
       'z4349',
       'z1086',
       'z88dk',
       'z103',
       'z100',
       'z800',
       'z21',
       'z14',
       'z15',
       'z23',
       'z30',
       'z33',
       'z22',
       'z26',
       'z20',
       'z11',
       'z27',
       'z17',
       'z88',
       'z28',
       'z10',
       'z12',
       'z19',
       'z18',
       'z13',
       'z25',
       'z++',
       'z16'],
 'a': ['z/architecture'],
 'b': ['z-buffering', 'z.b.u.k.u', 'z-boys'],
 'c': ['z-carotene', 'z-class', 'z-cars', 'z-card'],
 'd': ['z-division', 'z-drive', 'z-drag', 'z-dna', 'z-dos'],
 'e': ["z'ev"],
 'f': ['z-fighting', 'z-fa-fmk', 'z-factor', 'z@f@ran'],
 'g': ['z-group', 'z8games', 'z-gene', "z'goum", 'z-g'],
 'h': ['z@hm@tabad', 'z@hm@tk@nd', 'z.hera', "z'har"],
 'l': ['z-library', 'z@limxan', 'z-ligand', 'z-line'],
 'm': ['z-machine', 'z-maestro', 'z-matrix', 'z-mind', 'z-mill', 'z-man'],
 'n': ['z@ngisali', 'z@ng@ran', 'z@ng@l@', 'z@ng@n@', 'z-netz'],
 'o': ['z-order', 'z-out', 'z/os'],
 'p': ['z-polyhedron',
       'z-pinning',
       'z-plasty',
       'z-pinch',
       'z-plane',
       'z.p.g.',
       'z-push'],
 'r': ['z@rigumaco',
       'z@rd@b@r@',
       'z@rg@ran',
       'z@rg@rli',
       'z@rnava',
       'z@rn@li',
       'z@rqulu',
       'z@rb@li',
       'z@rdabi',
       'z@rqava',
       'z@rr@b',
       'z@rg@r',
       'z-ram',
       'z-rna',
       'z@rn@',
       'z-ro'],
 's': ['z-spread', 'z-squad', 'z-stoff', 'z-scars', 'z-star', 'z-san'],
 't': ['z-transform',
       'z-train',
       'z-tack',
       'z-type',
       'z-trip',
       'z-trim',
       'z-tube',
       'z-test'],
 'v': ['z-variant', 'z/vm'],
 'w': ['z-wave'],
 'x': ['z/x'],
 'y': ['z@ylik', 'z@y@m', 'z/yen']}
