
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zm = {'_': ['zm-241,385', 'zm-182345', 'zm447439', 'zm-87'],
 'a': ['zmajevic',
       'zmajevac',
       'zmaratha',
       'zmailer',
       'zmajevo',
       'zmarle',
       'zmanda',
       'zmaray',
       'zmajan',
       'zmanim',
       'zmacs',
       'zmapp',
       'zmap',
       'zman',
       'zmax',
       'zma'],
 'b': ['zmb'],
 'd': ['zmdi', 'zmd'],
 'e': ['zmeinogorsk',
       'zmeytsyno',
       'zmelkoow',
       'zmeyevka',
       'zmeoaica',
       'zmeurata',
       'zmeskal',
       'zmeitsa',
       'zmeevo',
       'zmeu'],
 'i': ['zmijewo-zagroby',
       'zmijewo-trojany',
       'zmijewo-podusie',
       'zmijewo-szawly',
       'zmijowek-mans',
       'zmijewo-ponki',
       'zmijewo-gaje',
       'zmijewo-kuce',
       'zmiennicy',
       'zmigrodek',
       'zmiennica',
       'zmijewko',
       'zmijavci',
       'zmiyovka',
       'zmitser',
       'zminjak',
       'zmiovka',
       'zmiivka',
       'zmigrod',
       'zmiarki',
       'zmijani',
       'zmijkow',
       'zmiaca',
       'zminne',
       'zminec',
       'zminac',
       'zmiz2',
       'zmiz1',
       'zminj',
       'zmiiv',
       'zmist',
       'zmila'],
 'm': ['zmm'],
 'o': ['zmodeler', 'zmojdak', 'zmodem'],
 'p': ['zmpste24', 'zmp'],
 's': ['zms'],
 't': ['zmt'],
 'u': ['zmudz-kolonia', 'zmudzinski', 'zmutt', 'zmuda', 'zmudz', 'zmud'],
 'w': ['zmw'],
 'y': ['zmyslanka',
       'zmyslowo',
       'zmynd11',
       'zmynd10',
       'zmynd8',
       'zmym2',
       'zmym3']}
