
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zs = {'a': ['zsarolyan', 'zsambok', 'zsadany', 'zsambek', 'zsana', 'zsaka', 'zsa'],
 'c': ['zschaitz-ottewig',
       'zschirnsteine',
       'zschonerbach',
       'zschornewitz',
       'zschusschen',
       'zscheiplitz',
       'zschorgula',
       'zschampert',
       'zschepplin',
       'zschadrass',
       'zschorlau',
       'zschokke',
       'zschopau',
       'zschopel',
       'zscreen',
       'zscan21',
       'zscaler'],
 'e': ['zselickisfalud',
       'zselicszentpal',
       'zselickislak',
       'zsebehaza',
       'zsedeny',
       'zsennye',
       'zseda',
       'zse'],
 'g': ['zsg'],
 'i': ['zsivoczky', 'zsigmondy', 'zsiga', 'zsira', 'zsi'],
 'l': ['zsl'],
 'm': ['zsm-5', 'zsm'],
 'n': ['zsnes'],
 'o': ['zsombor', 'zsolnai', 'zsolnay', 'zsombo', 'zsofia', 'zsolt'],
 'p': ['zspace'],
 's': ['zss-fm', 'zsss', 'zss'],
 't': ['zstd', 'zst'],
 'u': ['zsuzsanna', 'zsu-57-2', 'zsupanek', 'zsujta', 'zsu-37', 'zsurk', 'zsu'],
 'w': ['zswap'],
 'z': ['zsz']}
