
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fb = {'_': ['fb-10'],
 'a': ['fbar', 'fba'],
 'b': ['fbbank', 'fbb'],
 'c': ['fbc'],
 'd': ['fbd'],
 'e': ['fbe'],
 'f': ['fbf'],
 'g': ['fbg'],
 'h': ['fbhs', 'fbh'],
 'i': ['fbisd', 'fbis'],
 'k': ['fbk'],
 'l': ['fbla-pbl', 'fblim1', 'fbln5', 'fbln2', 'fbln1', 'fbl'],
 'm': ['fbm'],
 'n': ['fbn'],
 'o': ['fbo'],
 'p': ['fbp1', 'fbp'],
 'r': ['fbreader', 'fbr-600', 'fbrs', 'fbr'],
 's': ['fbs'],
 't': ['fbt'],
 'u': ['fbus', 'fbu'],
 'w': ['fbw'],
 'x': ['fbxw10',
       'fbxo32',
       'fbxo24',
       'fbxo28',
       'fbxo11',
       'fbxo31',
       'fbxo38',
       'fbxw11',
       'fbxl3',
       'fbxo7',
       'fbxl2',
       'fbxw7',
       'fbxo9',
       'fbxo5',
       'fbxw4',
       'fbxl4',
       'fbxw5',
       'fbxw2',
       'fbxo2',
       'fbxl5',
       'fbxo6',
       'fbxo4',
       'fbxl7',
       'fbxw8',
       'fbx']}
