from _typeshed import Incomplete

class OpenCV:
    net: Incomplete
    layer_names: Incomplete
    def __init__(self, model_config) -> None: ...
    def forward(self): ...
    def set_input(self, input) -> None: ...
    def set_backend(self, backend) -> None: ...
    def set_accelerator(self, target) -> None: ...
    def set_layer_names(self) -> None: ...
