from _typeshed import Incomplete

class TensorRT:
    net: Incomplete
    context: Incomplete
    stream: Incomplete
    def __init__(self, model_config) -> None: ...
    def set_input(self, data) -> None: ...
    def forward(self): ...

class CudaMemory:
    def __init__(self, host, device, shape, dtype) -> None: ...
    @property
    def host(self): ...
    @property
    def device(self): ...
    @property
    def shape(self): ...
    @property
    def dtype(self): ...
