
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zd = {'_': ['zd6126', 'zd30'],
 'a': ['zdaljevac',
       'zdanowice',
       'zdanowek',
       'zdarsky',
       'zdanice',
       'zdarky',
       'zdanov',
       'zdarek',
       'zdarna',
       'zdanow',
       'zdarec',
       'zdana',
       'zdany',
       'zdala',
       'zdar'],
 'b': ['zdbowo', 'zdbice', 'zdbino'],
 'c': ['zdcm-04'],
 'e': ['zdemyslice',
       'zdechovice',
       'zdeslava',
       'zdegowko',
       'zdenekia',
       'zdeglovo',
       'zdenkov',
       'zdencac',
       'zdencec',
       'zdechov',
       'zdeslav',
       'zdenci',
       'zdebel',
       'zdenac',
       'zdetin',
       'zdenko',
       'zdelov',
       'zdenka',
       'zdenek',
       'zderaz',
       'zdedy',
       'zdena'],
 'f': ['zdf-fernsehgarten',
       'zdftheaterkanal',
       'zdf-hitparade',
       'zdfdokukanal',
       'zdf-magazin',
       'zdfkultur',
       'zdfinfo',
       'zdfneo',
       'zdf'],
 'h': ['zdhhc17', 'zdhhc14', 'zdhhc2', 'zdhhc8', 'zdhhc3', 'zdhhc4', 'zdhhc9'],
 'i': ['zdislavice',
       'zdislava',
       'zdihovo',
       'zdirec',
       'zdikov',
       'zdiar',
       'zdice',
       'zdiby'],
 'm': ['zdm'],
 'n': ['zdnet'],
 'o': ['zdoroviye',
       'zdolbuniv',
       'zdobnice',
       'zdounky',
       'zdonkow',
       'zdobin',
       'zdonia',
       'zdory',
       'zdovc',
       'zdow'],
 'r': ['zdrojki-chojnowo',
       'zdrojki-piegowo',
       'zdrijelovici',
       'zdravkovets',
       'zdralovici',
       'zdravljica',
       'zdravkovic',
       'zdravchets',
       'zdrawneva',
       'zdravitsa',
       'zdravinje',
       'zdravcici',
       'zdrzychow',
       'zdrogowo',
       'zdravets',
       'zdrochec',
       'zdrebowo',
       'zdrzewno',
       'zdravkov',
       'zdralovi',
       'zdroisko',
       'zdroiska',
       'zdrojki',
       'zdrojek',
       'zdruzno',
       'zdravko',
       'zdrahal',
       'zdrimci',
       'zdrelac',
       'zdroje',
       'zdrowa',
       'zdreby',
       'zdravo',
       'zdrelo',
       'zdroj'],
 's': ['zds'],
 't': ['zdt'],
 'u': ['zduchovice',
       'zdunowice',
       'zdunowek',
       'zdunkow',
       'zdunowo',
       'zdunje',
       'zduhac',
       'zdunek',
       'zdunki',
       'zduny',
       'zdusa'],
 'v': ['zdvinsk', 'zdv'],
 'w': ['zdworz'],
 'y': ['zdyszewice', 'zdynianka', 'zdykhalno', 'zdynia'],
 'z': ['zdziechow-kolonia',
       'zdzary-kolonia',
       'zdzierczyzna',
       'zdzieslawice',
       'zdzieszowice',
       'zdzilowice',
       'zdzieszewo',
       'zdziemborz',
       'zdzislawin',
       'zdziechowa',
       'zdziar-las',
       'zdzieborz',
       'zdziarzec',
       'zdziersko',
       'zdzietawy',
       'zdziechow',
       'zdzislaw',
       'zdzenice',
       'zdzitava',
       'zdziersk',
       'zdziarka',
       'zdzarka',
       'zdzarow',
       'zdzarki',
       'zdzanne',
       'zdziary',
       'zdzary',
       'zdzar']}
