
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zf = {'_': ['zf.ger.38', 'zf2001', 'zf41'],
 'a': ['zfat-as1', 'zfand5', 'zfa'],
 'b': ['zfb-tv', 'zfb-05'],
 'c': ['zfc-fm'],
 'd': ['zfd-fm', 'zfd'],
 'f': ['zff'],
 'g': ['zfg'],
 'h': ['zfhe-fm'],
 'k': ['zfkh-fm',
       'zfkz-fm',
       'zfki-fm',
       'zfkg-fm',
       'zfkv-fm',
       'zfky-fm',
       'zfkx-fm',
       'zfks-fm',
       'zfkp-fm',
       'zfkk-fm'],
 'm': ['zfm-fm'],
 'n': ['zfn'],
 'o': ['zfootball', 'zfourge', 'zfone'],
 'p': ['zfp91-cntf',
       'zfp36l1',
       'zfp161',
       'zfp106',
       'zfp91',
       'zfp57',
       'zfpm2',
       'zfp92',
       'zfp64',
       'zfpm1',
       'zfp36'],
 'r': ['zfr'],
 's': ['zfsp-fm', 'zfs+', 'zfs'],
 'x': ['zfx'],
 'y': ['zfyve28',
       'zfyve26',
       'zfyve27',
       'zfyve19',
       'zfyve16',
       'zfyve20',
       'zfyve1',
       'zfy'],
 'z': ['zfzz-fm']}
