
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zb = {'_': ['zb-53', 'zb-50', 'zb-60', 'zb716'],
 'a': ['zbaszynek',
       'zbaraski',
       'zbarzewo',
       'zbarbar',
       'zbandaj',
       'zbarzyk',
       'zbarazh',
       'zbaszyn',
       'zbasic',
       'zbarqe',
       'zbazdi',
       'zbarz',
       'zbar'],
 'b': ['zbb'],
 'c': ['zbcomma', 'zbc'],
 'd': ['zbd-04', 'zbd-03'],
 'e': ['zbechy-pole',
       'zbeltowice',
       'zberzynek',
       'zbedowice',
       'zberoaia',
       'zbesicky',
       'zbelitov',
       'zbenice',
       'zbehnov',
       'zbeniny',
       'zberzyn',
       'zbelovo',
       'zbelava',
       'zbereze',
       'zbecnik',
       'zbechy',
       'zbeng!',
       'zberki',
       'zberoz',
       'zbevac',
       'zbecno',
       'zbehy',
       'zbed6',
       'zbed3',
       'zberg',
       'zbed1',
       'zbek',
       'zber'],
 'i': ['zbigniewice-kolonia',
       'zbiersk-cukrownia',
       'zbijewo-kolonia',
       'zbiersk-kolonia',
       'zbiki-gawronki',
       'zbiki-kierzki',
       'zbiki-starki',
       'zbiki-antosy',
       'zbigniewice',
       'zbierkowo',
       'zbikowice',
       'zbikowski',
       'zbigovci',
       'zbigniew',
       'zbilidy',
       'zbijewo',
       'zbiersk',
       'zbinohy',
       'zbietka',
       'zbijowa',
       'zbinden',
       'zbizuby',
       'zbiroza',
       'zbiczno',
       'zbiroh',
       'zbince',
       'zbilje',
       'zbica',
       'zbik'],
 'l': ['zbludowice',
       'zblutowo',
       'zblovice',
       'zbljevo',
       'zbludza',
       'zblewo',
       'zbleg',
       'zblan',
       'zbl'],
 'm': ['zbm-tv', 'zbm'],
 'o': ['zborczyce',
       'zbojstica',
       'zborowiec',
       'zborovice',
       'zborowice',
       'zborowski',
       'zborowek',
       'zbojenko',
       'zboriste',
       'zbozenna',
       'zbozicko',
       'zborovy',
       'zborowo',
       'zbontar',
       'zboiska',
       'zbozne',
       'zborov',
       'zborow',
       'zbogar',
       'zbojno',
       'zbojna',
       'zboriv',
       'zbojne',
       'zboiul',
       'zbory',
       'zboze',
       'zbots',
       'zboj'],
 'p': ['zbp1'],
 'r': ['zbraslavice',
       'zbroslawice',
       'zbraslavec',
       'zbrzeznica',
       'zbrojewsko',
       'zbrojniky',
       'zbrodzice',
       'zbrudzewo',
       'zbrachlin',
       'zbraslav',
       'zbroszki',
       'zbrojewo',
       'zbrojow',
       'zbrasin',
       'zbruch',
       'zbrush',
       'zbrui',
       'zbr'],
 's': ['zbs'],
 't': ['zbtb7a',
       'zbtb33',
       'zbtb48',
       'zbtb17',
       'zbtb20',
       'zbtb40',
       'zbtb11',
       'zbtb7b',
       'zbtb32',
       'zbtb1',
       'zbtb7',
       'zbt'],
 'u': ['zburator',
       'zbuczyn',
       'zbuzany',
       'zbudza',
       'zbure',
       'zbuch',
       'zbucz',
       'zbus'],
 'v': ['zbvi', 'zbv'],
 'y': ['zbyszewski',
       'zbyslawiec',
       'zbychowice',
       'zbyslavice',
       'zbylczyce',
       'zbylowice',
       'zbyszewo',
       'zbylutow',
       'zbytkowo',
       'zbychowo',
       'zbyszyce',
       'zbyszyno',
       'zbyczyna',
       'zbyluty',
       'zbytkow',
       'zbytowo',
       'zbyszek',
       'zbyszko',
       'zbyczyn',
       'zbytiny',
       'zbytowa',
       'zbynek',
       'zbynov',
       'zbysov',
       'zbylut',
       'zby'],
 'z': ['zbz-33']}
