from setuptools import setup, find_packages

setup(
    name="omninumeric",
    version="1.0.0",
    author="Andrei Shur",
    author_email="amshoor@gmail.com",
    description="Read and write numbers in alphabetic numeral systems",
    long_description_content_type="text/markdown",
    url="https://github.com/endrain/omninumeric",
    keywords=[
        "church slavonic",
        "conversion",
    ],
    license="MIT",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.4",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Mathematics",
        "Topic :: Software Development :: Libraries",
        "Topic :: Software Development :: Localization",
        "Intended Audience :: Developers",
        "Intended Audience :: Religion",
        "Intended Audience :: Science/Research",
    ],
    packages=find_packages(),
    python_requires=">=3.4",
)
