
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_iw = {'a': ['iwanowice-nabokow',
       'iwamurada-shuku',
       'iwakawatrochus',
       'iwantgreatcare',
       'iwaszkiewicz',
       'iwanaga-hime',
       'iwalewahaus',
       'iwaki-kuni',
       'iwamotocho',
       'iwamoto-ji',
       'iwaniszki',
       'iwamizawa',
       'iwanoffia',
       'iwabuchi',
       'iwahashi',
       'iwamatsu',
       'iwashita',
       'iwashiro',
       'iwatesan',
       'iwakisan',
       'iwanttfc',
       'iwanicki',
       'iwaniska',
       'iwasaki',
       'iwakura',
       'iwadate',
       'iwamura',
       'iwa-ait',
       'iwaraja',
       'iwatani',
       'iwataya',
       'iwanuma',
       'iwasawa',
       'iwajowa',
       'iwalewa',
       'iwakuni',
       'iwadare',
       'iwaruna',
       'iwanaga',
       'iwamoto',
       'iwanski',
       'iwazaki',
       'iwayaji',
       'iwahara',
       'iwambi',
       'iwaski',
       'iwaoka',
       'iwami',
       'iwano',
       'iwade',
       'iwaki',
       'iwama',
       'iwarp',
       'iwana',
       'iwany',
       'iwasa',
       'iwata',
       'iwaya',
       'iwaoa',
       'iwase',
       'iwate',
       'iwai',
       'iwar',
       'iwaz',
       'iwan',
       'iwao',
       'iwa'],
 'b': ['iwbank', 'iwbf', 'iwb'],
 'c': ['iwcc', 'iwc'],
 'd': ['iwd'],
 'e': ['iweek', 'iwein', 'iweb', 'iwe'],
 'f': ['iwfl', 'iwf'],
 'g': ['iwgp', 'iwgb', 'iwg'],
 'i': ['iwilsoniella',
       'iwikauikaua',
       'iwierzyce',
       'iwireless',
       'iwiecino',
       'iwitness',
       'iwickowo',
       'iwinski',
       'iwitahi',
       'iwiczno',
       'iwiczna',
       'iwindi',
       'iwindo',
       'iwiny',
       'iwiec',
       'iwiji',
       'iwie',
       'iwig',
       'iwiw',
       'iwin',
       'iwi'],
 'j': ['iwj'],
 'k': ['iwkowa', 'iwk'],
 'l': ['iwla', 'iwl'],
 'm': ['iwm'],
 'n': ['iwniki', 'iwna', 'iwno', 'iwn'],
 'o': ['iwonicz-zdroj',
       'iwontunwonsi',
       'iwoye-ketu',
       'iwogumoa',
       'iwonicz',
       'iwonie',
       'iwocl',
       'iwowe',
       'iwona',
       'iwoca',
       'iwobi',
       'iworo',
       'iwork',
       'iwoz',
       'iwon',
       'iwo'],
 'p': ['iwpr', 'iwps', 'iwp'],
 'r': ['iwrestledabearonce', 'iwr'],
 's': ['iws1', 'iws'],
 't': ['iwt'],
 'u': ['iwungilo', 'iwuy', 'iwu'],
 'x': ['iwxxm'],
 'y': ['iwye'],
 'z': ['iwz']}
