
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_if = {'_': ['if-by-whiskey',
       'if-then-else',
       'if-boat',
       'if/then',
       'if-map',
       'if....',
       'if-22',
       'if--',
       "if'n",
       'if2'],
 'a': ['ifalukellidae',
       'ifako-ijaiye',
       'ifanadiana',
       'ifarantsa',
       'ifanirea',
       'ifakara',
       'ifanboy',
       'ifacnet',
       'ifangni',
       'ifasya',
       'ifalik',
       'ifanes',
       'ifanzy',
       'ifatsy',
       'ifa-2',
       'ifans',
       'ifani',
       'ifar',
       'ifaa',
       'ifan',
       'ifat',
       'ifap',
       'ifac',
       'ifae',
       'ifas',
       'ifaw',
       'ifao',
       'ifa'],
 'b': ['ifbb', 'ifb'],
 'c': ['ifcc-ksk', 'ifconfig', 'ifca', 'ifco', 'ifc'],
 'd': ['ifda', 'ifd'],
 'e': ['iferanserin',
       'iferhounene',
       'ifenprodil',
       'ifenakaren',
       'ife-ijumu',
       'ifetroban',
       'iferouane',
       'ifelodun',
       'ifeanyi',
       'ifedayo',
       'ifedore',
       'ifenat',
       'ifeoma',
       'iferni',
       'ifeda',
       'ifest',
       'ifema',
       'ifex',
       'ife'],
 'f': ['iffland-ring',
       'iffezheim',
       'iffeldorf',
       'iffigsee',
       'iffendic',
       'iffland',
       'iffwil',
       'iffley',
       'iffou',
       'iffet',
       'iffo1',
       'iffy',
       'iff'],
 'g': ['ifg'],
 'h': ['ifht', 'ifh'],
 'i': ['ifihadahifi',
       'ifigenia',
       'ifinger',
       'ifilter',
       'ifingr',
       'ifi202',
       'ifield',
       'ifixit',
       'ifitm3',
       'ifigha',
       'ifitm1',
       'ifish',
       'ifisc',
       'ifilm',
       'ifi16',
       'ifius',
       'ifill',
       'ifi35',
       'ifi27',
       'ifit1',
       'ifit3',
       'ifi30',
       'ifito',
       'ifira',
       'ifit2',
       'ifis',
       'ifin',
       'ifit',
       'ifil',
       'ifi6',
       'ific',
       'ifi'],
 'j': ['ifjord'],
 'l': ['iflaviridae',
       'iflissen',
       'iflytek',
       'ifloga',
       'iflix',
       'iflr',
       'ifla',
       'ifl'],
 'm': ['ifmud', 'ifmad', 'ifma', 'ifmc', 'ifm'],
 'n': ['ifnotnow',
       'ifna10',
       'ifnar1',
       'ifna17',
       'ifnar2',
       'ifna14',
       'ifna13',
       'ifna21',
       'ifna16',
       'ifnb1',
       'ifna4',
       'ifna8',
       'ifna7',
       'ifna6',
       'ifn1@',
       'ifna5',
       'ifnw1',
       'ifna2',
       'ifnk',
       'ifni',
       'ifnr'],
 'o': ['ifonyintedo',
       'ifosfamide',
       'ifoxetine',
       'iforindia',
       'ifotaka',
       'ifoghas',
       'ifolder',
       'ifonly',
       'ifood',
       'ifoga',
       'iford',
       'ifold',
       'ifor',
       'ifo'],
 'p': ['ifpug', 'ifpri', 'ifpe', 'ifpa', 'ifps', 'ifpo', 'ifp'],
 'r': ['ifridytes',
       'ifriqiya',
       'ifremer',
       'ifrogz',
       'ifross',
       'ifrane',
       'iframe',
       'ifrit',
       'ifrd1',
       'ifri',
       'ifrb',
       'ifrf',
       'ifra'],
 's': ['ifsttar', 'ifsar', 'ifsm', 'ifsc', 'ifsb', 'ifsp', 'ifsa', 'ifs'],
 't': ['iftekharuzzaman',
       'iftekhar',
       'iftikhar',
       'iftikhor',
       'ift140',
       'iftran',
       'iftar',
       'ift74',
       'ifttt',
       'ifthi',
       'ift88',
       'ift57',
       'ift80',
       'ift81',
       'iftop',
       'ift20',
       'ifta',
       'ift'],
 'u': ['ifuturelist',
       'ifunda',
       'ifugao',
       'ifumbo',
       'ifunny',
       'ifucha',
       'ifund',
       'ifumi',
       'ifu'],
 'v': ['ifva'],
 'x': ['ifx'],
 'y': ['ifyoubelievein'],
 'z': ['ifz']}
