
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_iy = {'a': ['iyanla_bailey-williams',
       'iyarpagai_nayanar',
       'iyad_el-baghdadi',
       'iyaguchi_station',
       'iyabo_anisulowo',
       'iyaelima_people',
       'iya_andrushchak',
       'iyayi_atiemwen',
       'iyad_issimaila',
       'iyayu_language',
       'iyabo_obasanjo',
       'iyanla_vanzant',
       'iyad_al-khatib',
       'iyad_sughayer',
       'iyatayet_site',
       'iyabo_ismaila',
       'iyare_igiehon',
       'iya_gavrilova',
       'iyad_al-yahri',
       'iyassu_bekele',
       'iyang_station',
       'iyabo_akanmu',
       'iyad_shalabi',
       'iya_villania',
       'iya_abubakar',
       'iyad_mohamed',
       'iyad_rimawi',
       'iyad_burnat',
       'iyad_rahwan',
       'iya_arepina',
       'iya_station',
       'iyasile_naa',
       'iya_savvina',
       'iyam_friday',
       "iyasus_mo'a",
       'iyari_limon',
       'iya_hokshi',
       'iya_traore',
       'iyad_mando',
       'iya_valley',
       'iyasu_iii',
       'iyah_mina',
       'iya_terra',
       'iyami_aje',
       'iyabo_ojo',
       'iyasu_ii',
       'iyasu_iv',
       'iya_nla',
       'iyasu_i'],
 'c': ['iyceler,_kizilcahamam'],
 'd': ['iyd-i_milli'],
 'e': ['iyesha_ollivierre',
       'iye_idolorusan',
       'iyeoka_okoawo',
       'iyer_brothers',
       'iyengar_tamil',
       'iyengar_yoga',
       'iyen_island',
       'iyer_ips'],
 'h': ['iyhia_mcmichael'],
 'i': ['iyinoluwa_aboyeji',
       'iyiola_omisore',
       'iyidere,_ispir',
       'iyive_language',
       'iyiola_solanke',
       'iyiora_anam',
       'iyin_ekiti'],
 'm': ['iymen_chehade', 'iymir,_kazan', 'iyman_faris'],
 'n': ['iynefer_ii', 'iynefer_i'],
 'o': ['iyo-miyanoshita_station',
       'iyo-tachikawa_station',
       'iyo-tachibana_station',
       'iyo-shirataki_station',
       'iyo-kaminada_station',
       'iyo-nakayama_station',
       'iyo-nagahama_station',
       'iyo-matsuyama_domain',
       'iyo-kameoka_station',
       'iyo-miyoshi_station',
       'iyo-sangawa_station',
       'iyo-komatsu_station',
       'iyo-yoshida_station',
       'iyo-sakurai_station',
       'iyo-mishima_station',
       'iyo-izushi_station',
       'iyo-yokota_station',
       'iyo-tomita_station',
       'iyo-hirano_station',
       'iyobinte_pusthakam',
       'iyo-iwaki_station',
       'iyo-ohira_station',
       'iyo-saijo_station',
       "iyojwa'ja_chorote",
       'iyomishima,_ehime',
       "iyo'wujwa_chorote",
       'iyola_kingwatsiak',
       'iyo-hojo_station',
       'iyo-wake_station',
       'iyorwuese_hagher',
       'iyo-himi_station',
       'iyo-ozu_station',
       'iyo-doi_station',
       'iyopawa_island',
       'iyoshi_station',
       'iyoki_station',
       'iyothee_thass',
       'iyo_matsumoto',
       'iyozo_fujita',
       'iyorchia_ayu',
       'iyo_province',
       'iyo_bernardo',
       'iyo_language',
       'iyo_dialect',
       'iyo,_benin',
       'iyo,_ehime',
       'iyo_stone',
       'iyonix_pc',
       'iyo_araki',
       'iyoas_ii',
       'iyoas_i'],
 'p': ['iypt_2011'],
 'r': ['iyrcae', 'iyri', 'iyr'],
 's': ['iyseden_christie'],
 't': ['iytjenu', 'iyt'],
 'u': ['iyunga_mapinduzi'],
 'y': ['iyyamcode_sreedharan', 'iyyunni_chalakka']}
