
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nw = {'_': ['nw3', 'nw2', 'nw4', 'nw5', 'nw1'],
 'a': ['nwanyeruwa',
       'nwachukwu',
       'nwagboka',
       'nwakaeme',
       'nwangele',
       'nwaniba',
       'nwaneri',
       'nwankwo',
       'nwaran',
       'nwadeu',
       'nwali',
       'nwac',
       'nwa'],
 'b': ['nwbl', 'nwb'],
 'c': ['nwchem', 'nwc'],
 'd': ['nwda', 'nwd1', 'nwd'],
 'e': ['nwenaing', 'nweyon', 'nweamo', 'nwedan', 'nweke', 'nwea', 'nwe'],
 'f': ['nwfsc', 'nwfa', 'nwfp', 'nwff'],
 'h': ['nwhl', 'nwhs', 'nwh'],
 'i': ['nwipe', 'nwi'],
 'l': ['nwlink', 'nwl'],
 'm': ['nwm'],
 'n': ['nwn'],
 'o': ['nwokorie',
       'nwobodo',
       'nwokolo',
       'nwoduo',
       'nwoye',
       'nwosu',
       'nwodo',
       'nwoya',
       'nwo'],
 'p': ['nwpa', 'nwpp', 'nwp'],
 'r': ['nwra', 'nwr'],
 's': ['nwscript', 'nwsc', 'nwsa', 'nwss', 'nws'],
 't': ['nwt'],
 'u': ['nwu'],
 'w': ['nww'],
 'x': ['nwx']}
