
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ns = {'_': ['ns-dokumentationszentrum',
       'ns-ordensburgen',
       'ns-frauen-warte',
       'ns5-brane',
       'ns/stick',
       'ns-11394',
       'ns-2664',
       'ns-2710',
       'ns-2000',
       'ns-2359',
       'ns32000',
       'ns-398',
       'ns102',
       'ns19',
       'ns20',
       'ns15',
       'ns23',
       'ns13',
       'ns12',
       'ns50',
       'ns37',
       'ns17',
       'ns27',
       'ns21',
       'ns16',
       'ns11',
       'ns18',
       'ns10',
       'ns14',
       'ns34',
       'ns35',
       'ns6',
       'ns7',
       'ns5',
       'ns1',
       'ns4',
       'ns9',
       'ns2',
       'ns3',
       'ns8'],
 'a': ['nsambya',
       'nsawkaw',
       'nsalaga',
       'nsawam',
       'nsanje',
       'nsakey',
       'nsangi',
       'nsang',
       'nsaba',
       'nsapi',
       'nsasa',
       'nsad',
       'nsac',
       'nsab',
       'nsai',
       'nsaa',
       'nsar'],
 'b': ['nsbm', 'nsba', 'nsb'],
 'c': ['nsc-mycron',
       'nscor',
       'nscc',
       'nscs',
       'nsca',
       'nscr',
       'nscl',
       'nscd',
       'nsc'],
 'd': ['nsdhl', 'nsds', 'nsd1', 'nsdg', 'nsdl', 'nsdp', 'nsd'],
 'e': ['nsemensoc',
       'nsenlwa',
       'nsenene',
       'nseluka',
       'nsenga',
       'nsein',
       'nsele',
       'nsess',
       'nsep',
       'nsel',
       'nseb',
       'nsem',
       'nsec',
       'nse'],
 'f': ['nsf-grfp', 'nsfl1c', 'nsfaf', 'nsfc', 'nsf'],
 'g': ['nsg'],
 'h': ['nshimirimana',
       'nshimbodon',
       'nshkhark',
       'nshkhar',
       'nshenyi',
       'nshavan',
       'nshs',
       'nsh'],
 'i': ['nsit-ubium',
       'nsikatila',
       'nsit-ibom',
       'nsit-atai',
       'nsimeyong',
       'nsibidi',
       'nsi-189',
       'nsirimo',
       'nsi-63',
       'nsiah',
       'nsip',
       'nsis',
       'nsia',
       'nsic',
       'nsi'],
 'j': ['nsjv'],
 'k': ['nskk', 'nsk'],
 'l': ['nslookup', 'nslu2', 'nslp', 'nsl1', 'nslr', 'nsla', 'nsls', 'nsl'],
 'm': ['nsmce4a', 'nsmm', 'nsmb', 'nsma', 'nsmc', 'nsm'],
 'n': ['nsna', 'nsn'],
 'o': ['nsok-nsomo',
       'nsoatre',
       'nsodie',
       'nsoko',
       'nsoho',
       'nsoft',
       'nsolo',
       'nsou',
       'nsok',
       'nso'],
 'p': ['nsport+',
       'nspace',
       'nspcl',
       'nspca',
       'nspf',
       'nspw',
       'nspc',
       'nspr',
       'nspm',
       'nsps',
       'nsp'],
 'r': ['nsrc', 'nsrd', 'nsra', 'nsr'],
 's': ['nss-703',
       'nss-806',
       'nssc-1',
       'nss-5',
       'nss-7',
       'nss-6',
       'nss-9',
       'nss-8',
       'nssc',
       'nsse',
       'nssl',
       'nssa',
       'nsss',
       'nssf',
       'nssr',
       'nsso',
       'nssp',
       'nssb',
       'nss'],
 't': ['nstar', 'nstc', 'nstl', 'nsts', 'nstp', 'nstu', 'nst'],
 'u': ['nsuta-beposo',
       'nsupdate',
       'nsunera',
       'nsutite',
       'nsubuga',
       'nsukka',
       'nsundi',
       'nsukwa',
       'nsugbe',
       'nsumi',
       'nsuta',
       'nsun5',
       'nsun2',
       'nsut',
       'nsu'],
 'v': ['nsvl', 'nsv'],
 'w': ['nswazwi', 'nswr', 'nswc'],
 'x': ['nsx'],
 'y': ['nsync', 'nsya'],
 'z': ['nsz']}
