
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nj = {'_': ['nj_oosthuizen',
       'nj-luso_parma',
       'nj_bloodline',
       'nj_transit',
       'nj_ayuk',
       'nj_pbs'],
 'a': ['njangal_santhushtaranu',
       'njan_kathorthirikkum',
       'njabuliso_simelane',
       'njal_hostmaelingen',
       'njall_thorgeirsson',
       'njala_university',
       'njan_kodiswaran',
       'njabulo_manqana',
       'njan_gandharvan',
       'njabulo_ndebele',
       'njambi_mcgrath',
       'njan_marykutty',
       'njabulo_mabuza',
       'njala,_moyamba',
       'njan_prakashan',
       'njabulo_ngcobo',
       'njabulo_ndlovu',
       'njata,_malawi',
       'njav_language',
       'njabulo_nzuza',
       'njal_vindenes',
       'njabulo_ncube',
       'njabulo_blom',
       'njan_ekananu',
       'nja_mahdaoui',
       'njacko_backo',
       'njazi_azemi',
       'njal_sparbo',
       'njaba_river',
       'njai_dasima',
       'njan_sthree',
       'njao_island',
       'njardvik_fc',
       'njals_saga',
       'njazi_kuqi',
       'njal_olnes',
       'njal_hole'],
 'c': ['njc'],
 'd': ['njdc'],
 'e': ['njegos_janjusevic',
       'njegos_golocevac',
       'njegos_kupusovic',
       'njerep_language',
       'njesi_highlands',
       'njegos_petrovic',
       'njegos_mountain',
       'njesiti_guerril',
       'njeguski_prsut',
       'njebi_language',
       'njegos_sikiras',
       'njelele_shrine',
       'njeri_waithaka',
       'njembot_mbodj',
       'njema_frazier',
       'njenga_karume',
       'njem_language',
       'njen_language',
       'njeri_luseno',
       'njeri_karago',
       'njem_people',
       'njego_pesa'],
 'f': ['njfx', 'njf'],
 'h': ['njhl', 'njhs'],
 'i': ['njiva_rakotoharimalala',
       'njit_highlanders',
       'njivice,_croatia',
       'njisane_phillip',
       'njivice,_radece',
       'njideka_harry',
       'njihovi_dani',
       'njini_ntuta'],
 'k': ['njk'],
 'l': ['njl'],
 'm': ['njm'],
 'n': ['njn_news'],
 'o': ['njongonkulu_ndungane',
       'njoro_constituency',
       'njogu_demba-nyren',
       'njolstad_syndrome',
       'njombe_district',
       'njomgang_isaac',
       'njoroge_mungai',
       'njoki_wainaina',
       'njombe_region',
       'njombe_mjini',
       'njongo_priso',
       'njord_valley',
       'njoku_nnamdi',
       'njoro_river',
       'njoki_ngumi',
       'njoku_ji'],
 'p': ['njpw_destruction',
       'njpw_resurgence',
       'njpw_showdown',
       'njpw_dominion',
       'njpw_strong'],
 'r': ['njrat'],
 's': ['njs'],
 'u': ["njuguna_ndung'u",
       'njurunda_church',
       'njuh_venatius',
       'njurunda_sk',
       'njue_kevin',
       'njuav_ly'],
 'v': ['njvc']}
