
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hn = {'_': ['hn1l', 'hn-5', 'hn3', 'hn1'],
 'a': ['hnamadawgyi',
       'hnatkowice',
       'hnarakert',
       'hnahthial',
       'hnatyshyn',
       'hnawayaca',
       'hnatnice',
       'hnanisho',
       'hnanice',
       'hnahlan',
       'hnawgon',
       'hnaberd',
       'hnatyuk',
       'hnacov',
       'hnausa',
       'hnabi',
       'hnaef',
       'hnat',
       'hna'],
 'b': ['hnbap', 'hnb'],
 'c': ['hnc'],
 'd': ['hndrxx', 'hnd'],
 'e': ['hnevkovice',
       'hnevceves',
       'hnevosice',
       'hnevnice',
       'hnevotin',
       'hnevank',
       'hnews',
       'hne'],
 'f': ['hnf1a-as1', 'hnf1a', 'hnf1b', 'hnf'],
 'g': ['hngetpyawdaw', 'hng'],
 'h': ['hnhs', 'hnh'],
 'i': ['hnifsdalur',
       'hnizdychiv',
       'hnizdychne',
       'hnitbjorg',
       'hniezdne',
       'hniszow',
       'hnilcik',
       'hnivan',
       'hnilec'],
 'k': ['hnk'],
 'l': ['hnl'],
 'n': ['hnny', 'hnn'],
 'o': ['hnokkyo', 'hnojice', 'hnojnik', 'hnojne', 'hnonae', 'hnoss', 'hno'],
 'p': ['hnp'],
 'r': ['hnrnpa2b1',
       'hnrnpll',
       'hnrnpa0',
       'hnrpul1',
       'hnrnpa1',
       'hnrnpab',
       'hnrnpc',
       'hnrnpr',
       'hnrph3',
       'hnrpdl',
       'hnrpa3',
       'hnrph2',
       'hnrph1',
       'hnrnpk',
       'hnrnpl',
       'hnrpd',
       'hnrpf',
       'hnrpu'],
 's': ['hnsky', 'hns'],
 't': ['hntb', 'hnt'],
 'u': ['hnutove', 'hnusta', 'hnu'],
 'v': ['hnv'],
 'x': ['hnx'],
 'y': ['hnyat-phanat', 'hnyigarok', 'hnyihnu', 'hny'],
 'z': ['hnz']}
