
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hj = {'_': ['hj-story', 'hj-10', 'hj-12', 'hj-8', 'hj-9'],
 'a': ['hjarnkontoret',
       'hjaelmshoved',
       'hjartslattur',
       'hjadningavig',
       'hjalparfoss',
       'hjalmarsson',
       'hjartarson',
       'hjartdola',
       'hjallerup',
       'hjaltalin',
       'hjaltevad',
       'hjalstaby',
       'hjalteyri',
       'hjalmaren',
       'hjarnarp',
       'hjartdal',
       'hjallese',
       'hjalmar',
       'hjarsas',
       'hjartas',
       'hjartum',
       'hjarup',
       'hjarne',
       'hjarno',
       'hjarta',
       'hjalp!',
       'hjalm',
       'hja'],
 'c': ['hjck', 'hjcu'],
 'e': ['hjernerystelsesforeningen',
       'hjelmelandsvagen',
       'hjelledalstind',
       'hjeltefjorden',
       'hjertestarter',
       'hjertvatnet',
       'hjertetyven',
       'hjelmeland',
       'hjernevask',
       'hjertestop',
       'hjellestad',
       'hjelmsoya',
       'hjelmslev',
       'hjertsson',
       'hjertenes',
       'hjermann',
       'hjerkinn',
       'hjerting',
       'hjemmepc',
       'hjeltnes',
       'hjelset',
       'hjemmet',
       'hjellum',
       'hjem-is',
       'hjelme',
       'hjelde',
       'hjelm',
       'hjelt',
       'hjem'],
 'i': ['hji'],
 'k': ['hjk'],
 'l': ['hjl'],
 'm': ['hjm'],
 'n': ['hjn'],
 'o': ['hjorleifshofdi',
       'hjorundfjorden',
       'hjorundfjord',
       'hjorungavag',
       'hjortsberga',
       'hjortstamia',
       'hjortekaer',
       'hjortkvarn',
       'hjortsberg',
       'hjortshoj',
       'hjordkaer',
       'hjorring',
       'hjorvard',
       'hjollund',
       'hjorsey',
       'hjordis',
       'hjorted',
       'hjoula',
       'hjorth',
       'hjorto',
       'hjort',
       'hjo'],
 'p': ['hjp'],
 'r': ['hjr'],
 's': ['hjs'],
 't': ['hjt'],
 'u': ['hjuksevelta',
       'hjulstrom',
       'hjulsbro',
       'hjuksebo',
       'hjulsta',
       'hjulby',
       'hjuvik',
       'hjurp'],
 'v': ['hjv']}
