
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hm = {'_': ['hm-19', 'hm-14', 'hm-15', 'hm-41', 'hm13', 'hm7b', 'hm4', 'hm3'],
 'a': ['hmawngbuchhuah',
       'hmawyonmyaing',
       'hmailserver',
       'hmawbon',
       'hmangon',
       'hmanlin',
       'hmangin',
       'hmayak',
       'hmac',
       'hmav',
       'hmae',
       'hmar',
       'hma'],
 'b': ['hmb-45', 'hmbox1', 'hmbs', 'hmb'],
 'c': ['hmces', 'hmcs', 'hmc'],
 'd': ['hmda', 'hmdi', 'hmds', 'hmdb', 'hmd'],
 'e': ['hmeinsein', 'hmeljcic', 'hmeimim', 'hmeimat', 'hme'],
 'f': ['hmf'],
 'g': ['hmg-box',
       'hmg-coa',
       'hmg20b',
       'hmg20a',
       'hmgxb3',
       'hmgcs2',
       'hmgb2',
       'hmgb3',
       'hmgb4',
       'hmga1',
       'hmgn4',
       'hmgn2',
       'hmgn3',
       'hmga2',
       'hmgb1',
       'hmgnc',
       'hmgn1',
       'hmga',
       'hmgn',
       'hmg'],
 'h': ['hmht-302',
       'hmh-465',
       'hmh-461',
       'hmh-772',
       'hmh-464',
       'hmh-361',
       'hmh-466',
       'hmh-366',
       'hmh-462',
       'hmh-769',
       'hmh-463',
       'hmha1',
       'hmhb',
       'hmhs',
       'hmh'],
 'i': ['hmingthanmawia', 'hmizate', 'hmitl', 'hmiel', 'hmis', 'hmi'],
 'j': ['hmj'],
 'k': ['hmk'],
 'l': ['hmlat-303',
       'hmla-267',
       'hmla-167',
       'hmla-773',
       'hmla-269',
       'hmla-775',
       'hmla-469',
       'hmla-467',
       'hmla-169',
       'hmla-367',
       'hmla-369',
       'hml-776',
       'hmltd',
       'hml'],
 'm': ['hmmer', 'hmm1', 'hmmt', 'hmms', 'hmm'],
 'n': ['hmnj', 'hmn'],
 'o': ['hmox2', 'hmong', 'hmox1'],
 'p': ['hmpo-dapy', 'hmps', 'hmp'],
 'r': ['hmri', 'hmrs', 'hmr'],
 's': ['hmshost', 'hmsa', 'hms'],
 't': ['hmt-301', 'hmta', 'hmtv', 'hmt'],
 'u': ['hmuncheng', 'hmuifang', 'hmunlai', 'hmukhin', 'hmu'],
 'v': ['hmv'],
 'w': ['hmwk', 'hmw'],
 'x': ['hmx-1', 'hmx'],
 'y': ['hmy'],
 'z': ['hmz-t1', 'hmz']}
