
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hs = {'_': ['hs3st3a1',
       'hs3st3b1',
       'hs/link',
       'hs-333',
       'hs-121',
       'hs4air',
       'hs3st2',
       'hs2000',
       'hs1bp3',
       'hs3st1',
       'hs-127',
       'hs-376',
       'hs-393',
       'hs6st2',
       'hs2st1',
       'hs-12',
       'hs665',
       'hs9',
       'hs4',
       'hs3'],
 'a': ['hsanotherium',
       'hsandagolian',
       'hsa-pir-1082',
       'hsamonghkam',
       'hsawnghsup',
       'hsatung',
       'hsawlaw',
       'hsarpa',
       'hsarat',
       'hsaung',
       'hsad',
       'hsas',
       'hsa'],
 'b': ['hsbc', 'hsb'],
 'c': ['hsc-12',
       'hsc-84',
       'hsc-23',
       'hsc-14',
       'hsc-22',
       'hsc-21',
       'hsc-25',
       'hsc-85',
       'hsc-7',
       'hsc-3',
       'hsc-4',
       'hsc-8',
       'hsc-6',
       'hsc-9',
       'hsc-2',
       'hsc-5',
       'hsci',
       'hsct',
       'hscp',
       'hsc'],
 'd': ['hsd17b11',
       'hsd17b13',
       'hsd17b12',
       'hsd17b14',
       'hsd17b10',
       'hsd17b1',
       'hsd17b3',
       'hsd17b7',
       'hsd17b8',
       'hsd17b6',
       'hsd17b2',
       'hsd17b4',
       'hsd3b2',
       'hsd3b1',
       'hsdl',
       'hsdb',
       'hsd'],
 'e': ['hseiniyeh', 'hsenhsua', 'hsekiu', 'hseep', 'hsec', 'hsed', 'hse'],
 'f': ['hsf5', 'hsf4', 'hsfs', 'hsfc', 'hsf1', 'hsf2', 'hsf'],
 'g': ['hsgp', 'hsg'],
 'h': ['hsh2d', 'hshs', 'hsh'],
 'i': ['hsianghualite',
       'hsinbyumashin',
       'hsinbyushin',
       'hsisosuchus',
       'hsianwenia',
       'hsinbyume',
       'hsin-chu',
       'hsien-ko',
       'hsissen',
       'hsin-an',
       'hsinchu',
       'hsinbo',
       'hsipaw',
       'hsi'],
 'j': ['hsj'],
 'k': ['hsk'],
 'l': ['hsl-zuid', 'hsl-oost', 'hslvu', 'hsluv', 'hsls', 'hsla', 'hsl'],
 'm': ['hsm-72',
       'hsm-37',
       'hsm-73',
       'hsm-49',
       'hsm-51',
       'hsm-71',
       'hsm-74',
       'hsm-50',
       'hsm-46',
       'hsm-79',
       'hsm-41',
       'hsmm',
       'hsmg',
       'hsmk',
       'hsmp',
       'hsm'],
 'n': ['hsn2', 'hsn'],
 'o': ['hsohsa', 'hsoun', 'hsob', 'hso'],
 'p': ['hsp90ab1',
       'hsp90aa2',
       'hsp90b1',
       'hspc159',
       'hspa12a',
       'hspbp1',
       'hspa4l',
       'hspa14',
       'hspa1b',
       'hspa1l',
       'hsp104',
       'hspa1a',
       'hspb7',
       'hspb6',
       'hspe7',
       'hsp70',
       'hsph1',
       'hspa8',
       'hsp90',
       'hspa6',
       'hspb8',
       'hspa2',
       'hsp33',
       'hspb3',
       'hspa7',
       'hsp20',
       'hspa9',
       'hsp27',
       'hspa4',
       'hspb2',
       'hspa',
       'hsps',
       'hspc',
       'hsp'],
 'q': ['hsqldb', 'hsq'],
 'r': ['hsr-350x', 'hsromega', 'hsrn', 'hsr'],
 's': ['hsst', 'hssp', 'hsse', 'hss'],
 't': ['hstx1', 'hstcp', 'hst-2', 'hstn', 'hst'],
 'u': ['hsu-001', 'hsua', 'hsur', 'hsu'],
 'v': ['hsv-2', 'hsv'],
 'w': ['hswar', 'hswn', 'hswp', 'hsw'],
 'x': ['hsx'],
 'z': ['hsz']}
