
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hc = {'_': ['hc_neftekhimik_nizhnekamsk',
       'hc_shakhtyor_prokopyevsk',
       'hc_olimpus-85_chisinau',
       'hc_steelers_kapfenberg',
       'hc_zntu-zab_zaporozhye',
       'hc_shakhtyor_soligorsk',
       'hc_dnepryanka_kherson',
       'hc_stadion_litomerice',
       'hc_motor_zaporizhzhia',
       'hc_odorheiu_secuiesc',
       'hc_klein_zwitserland',
       'hc_berounsti_medvedi',
       'hc_la_chaux-de-fonds',
       'hc_sibir_novosibirsk',
       'hc_slovan_bratislava',
       'hc_kaustik_volgograd',
       'hc_lions_courmaosta',
       'hc_achilles_bocholt',
       'hc_dynamo_pardubice',
       'hc_ztr_zaporizhzhia',
       'hc_riviera_chisinau',
       'hc_vitkovice_ridera',
       'hc_karpaty_uzhgorod',
       'hc_steaua_bucuresti',
       'hc_kuban_krasnodar',
       'hc_sporta_hlohovec',
       'hc_presov_penguins',
       'hc_pustertal_wolfe',
       'hc_sfantu_gheorghe',
       'hc_dunarea_braila',
       'hc_vipers_tallinn',
       'hc_dinamo_yerevan',
       'hc_ramat_hasharon',
       'hc_viking_tallinn',
       'hc_ocelari_trinec',
       'hc_spartak_moscow',
       'hc_lada_togliatti',
       'hc_devils_milano',
       'hc_twk_innsbruck',
       'hc_meshkov_brest',
       'hc_dukla_jihlava',
       'hc_eppan_pirates',
       'hc_empor_rostock',
       'hc_fassa_falcons',
       'hc_zvezda_moscow',
       'hc_dinan_quevert',
       'hc_dynamo_moscow',
       'hc_dinamo_minsk',
       'hc_bosna_visoko',
       'hc_slavia_praha',
       'hc_neman_grodno',
       'hc_slezan_opava',
       'hc_milano_saima',
       'hc_levski_sofia',
       'hc_sparta_praha',
       'hc_dukla_prague',
       'hc_wikov_hronov',
       'hc_slavia_sofia',
       'hc_spartak_kyiv',
       'hc_kometa_brno',
       'hc_zubr_prerov',
       'hc_skoda_plzen',
       'hc_vita_hasten',
       'hc_sm_garliava',
       'hc_46_bardejov',
       'hc_teramo_2002',
       'hc_cska_moscow',
       'hc_19_humenne',
       'hc_lev_poprad',
       'hc_cska_sofia',
       'hc_oktan_perm',
       'hc_nove_zamky',
       'hc_agidel_ufa',
       'hc_lev_praha',
       'hc_nsa_sofia',
       'hc_21_presov',
       'hc_atk_praha',
       'hc_07_detva',
       'hc_red_ice',
       'hc_bat_yam'],
 'b': ['hcb_ticino_rockets'],
 'i': ['hci_equity_partners'],
 'l': ['hcl_color_space'],
 'm': ['hcm_baia_mare'],
 'p': ['hcpcs_level_2'],
 's': ['hcs_clustering_algorithm'],
 't': ['hct_co.,_ltd.']}
