
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lt = {'_': ['lt-10', 'lt50', 'lt24'],
 'a': ['lta-b3',
       'lta-pd',
       'lta-b2',
       'lta-b1',
       'ltava',
       'ltac',
       'ltag',
       'ltae',
       'ltan',
       'lta'],
 'b': ['ltbp2', 'ltbp3', 'ltbl', 'ltbr', 'ltba', 'ltb'],
 'c': ['ltcc', 'ltcs', 'ltci', 'ltcg', 'ltc'],
 'd': ['ltd'],
 'e': ['lte-sim', 'lte-m', 'lte'],
 'f': ['ltf'],
 'g': ['ltg'],
 'h': ['lths', 'lth'],
 'i': ['ltifr', 'ltib', 'lti'],
 'k': ['ltk'],
 'l': ['ltl'],
 'm': ['ltm'],
 'n': ['ltn1'],
 'o': ['lto'],
 'p': ['ltps', 'ltp'],
 'r': ['ltr-net', 'ltrace', 'ltra', 'ltr'],
 's': ['ltsports',
       'ltspice',
       'ltsen',
       'ltse',
       'ltsp',
       'ltss',
       'ltsa',
       'ltsr',
       'lts'],
 't': ['lttng', 'lttr', 'lttv', 'ltt'],
 'u': ['ltuc', 'ltu'],
 'v': ['ltv-n-4', 'ltv'],
 'w': ['ltwa', 'ltw'],
 'x': ['ltx'],
 'z': ['ltz1000', 'ltz']}
