
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lm = {'_': ['lm3labs',
       'lm13700',
       'lm22a-4',
       'lm-68m',
       'lm-700',
       'lm3914',
       'lm3875',
       'lm-49',
       'lm386',
       'lm-57',
       'lm-33',
       'lm317',
       'lm358',
       'lm-5',
       'lm-1'],
 'a': ['lmab-group', 'lmatx5', 'lman2l', 'lmatx3', 'lman1', 'lman2', 'lma'],
 'b': ['lmbatavank', 'lmbr1l', 'lmbrd1', 'lmbr1', 'lmbo', 'lmb'],
 'c': ['lmc195-1', 'lmctfy', 'lmcs', 'lmcc', 'lmc'],
 'd': ['lmdp', 'lmds', 'lmde', 'lmdh', 'lmd'],
 'e': ['lmechrek', 'lme'],
 'f': ['lmfao', 'lmfm', 'lmf'],
 'g': ['lmg'],
 'h': ['lmhosts', 'lmhs', 'lmh'],
 'i': ['lmia', 'lmi'],
 'k': ['lmk'],
 'l': ['lmln', 'lml'],
 'm': ['lmms', 'lmmr', 'lmm'],
 'n': ['lmnop', 'lmno', 'lmnt', 'lmn'],
 'o': ['lmod3', 'lmo4', 'lmo3', 'lmo7', 'lmo2', 'lmo1', 'lmo'],
 'p': ['lmp1', 'lmp'],
 'r': ['lmrs', 'lmr'],
 's': ['lms-9/19', 'lms-901', 'lmsr', 'lmsi', 'lmsc', 'lms'],
 't': ['lmtk2', 'lmtk3', 'lmt'],
 'u': ['lmule', 'lmu'],
 'v': ['lmv'],
 'x': ['lmx1a', 'lmx1b']}
