
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bs = {'_': ['bs2000',
       'bs-tbs',
       'bs22',
       'bs14',
       'bs12',
       'bs33',
       'bs20',
       'bs13',
       'bs15',
       'bs16',
       'bs10',
       'bs11',
       'bs28',
       'bs24',
       'bs2',
       'bs3',
       'bs9',
       'bs6',
       'bs1',
       'bs5',
       'bs8',
       'bs4',
       'bs7'],
 'a': ['bsat-2a',
       'bsat-1a',
       'bsat-4b',
       'bsanqul',
       'bsaliya',
       'bsat-1b',
       'bsat-3b',
       'bsat-4a',
       'bsat-3c',
       'bsat-2b',
       'bsat-2c',
       'bsat-3a',
       'bsalim',
       'bsarma',
       'bsames',
       'bsaira',
       'bsafe',
       'bsave',
       'bsaba',
       'bsaa',
       'bsac',
       'bsap',
       'bsat',
       'bsam',
       'bsas',
       'bsa'],
 'b': ['bsba', 'bsb'],
 'c': ['bschiesser', 'bschlabs', 'bsctx3', 'bscl2', 'bsci', 'bscs', 'bsc'],
 'd': ['bsd/os', 'bsdl'],
 'e': ['bseiso', 'bses', 'bseb', 'bsee', 'bseg', 'bse'],
 'f': ['bsfz-arena', 'bsfc', 'bsff', 'bsf'],
 'g': ['bsgs', 'bsg'],
 'h': ['bsheiriyeh', 'bsharri', 'bshuma', 'bshm', 'bshs', 'bsh'],
 'i': ['bsisa', 'bsida', 'bsic', 'bsin', 'bsim', 'bsi'],
 'j': ['bsj'],
 'k': ['bsk'],
 'l': ['bsl'],
 'm': ['bsmfc', 'bsm'],
 'n': ['bsnd', 'bsn'],
 'o': ['bsous', 'bsoft', 'bson', 'bso'],
 'p': ['bspp', 'bspr', 'bsp'],
 'q': ['bsquare'],
 'r': ['bsria', 'bsra', 'bsrm', 'bsr'],
 's': ['bssgp', 'bsse', 'bssp', 'bssm', 'bssf', 'bssc', 'bssd', 'bss'],
 't': ['bstar', 'bstfa', 'bst1', 'bsts', 'bstv', 'bst'],
 'u': ['bsu'],
 'v': ['bsv'],
 'w': ['bswm'],
 'x': ['bsx']}
