
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bj = {'_': ['bj2022', "bj's", 'bj4'],
 'a': ['bjarnfredarson',
       'bjarsjolagard',
       'bjarkalundur',
       'bjargtangar',
       'bjarkarimur',
       'bjaeverskov',
       'bjarmaland',
       'bjarnarey',
       'bjartveit',
       'bjarnason',
       'bjarkamal',
       'bjaering',
       'bjarkoya',
       'bjarnum',
       'bjarkoy',
       'bjarred',
       'bjartra',
       'bjadok',
       'bjarke',
       'bjarte',
       'bjalfi',
       'bjarni',
       'bjalbo',
       'bjasta',
       'bjarne',
       'bjarby',
       'bjaen',
       'bjarv',
       'bja'],
 'c': ['bjcc', 'bjc'],
 'd': ['bjd'],
 'e': ['bjelosavljevici',
       'bjerkestrand',
       'bjergbygaard',
       'bjelopavlici',
       'bjelkemander',
       'bjelleklang',
       'bjeloperica',
       'bjerkandera',
       'bjelasovici',
       'bjerkebanen',
       'bjelosevina',
       'bjelojevici',
       'bjerregaard',
       'bjerringbro',
       'bjelanovic',
       'bjelosevac',
       'bjelovcina',
       'bjelogrlic',
       'bjelasnica',
       'bjervamoen',
       'bjelanovac',
       'bjelogorci',
       'bjelopolje',
       'bjegovici',
       'bjelavici',
       'bjeljajci',
       'bjelasica',
       'bjerkaker',
       'bjerkreim',
       'bjelotici',
       'bjelovici',
       'bjelahova',
       'bjergsted',
       'bjelkaroy',
       'bjerkvik',
       'bjerkoya',
       'bjerreby',
       'bjekovic',
       'bjelovar',
       'bjelajce',
       'bjelovac',
       'bjelland',
       'bjelajci',
       'bjergsen',
       'bjerknes',
       'bjelusa',
       'bjesovi',
       'bjelina',
       'bjelisi',
       'bjerkas',
       'bjelice',
       'bjelica',
       'bjerrum',
       'bjerke',
       'bjerre',
       'bjelaj',
       'bjerka',
       'bjelke',
       'bjedov',
       'bjerk',
       'bjerg'],
 'f': ['bjfe'],
 'g': ['bjg'],
 'h': ['bjhs', 'bjh'],
 'm': ['bjmc'],
 'n': ['bjni', 'bjn'],
 'o': ['bjorngardsteatern',
       'bjolsegrovvatnet',
       'bjornefossvatnet',
       'bjornsonfjellet',
       'bjorndalssletta',
       'bjornstadvatnet',
       'bjornepatruljen',
       'bjorknashallen',
       'bjorlykkebreen',
       'bjornesfjorden',
       'bjornafjorden',
       'bjornbeinflya',
       'bjornbakknosi',
       'bjornfjorden',
       'bjornstjerna',
       'bjorkelangen',
       'bjornsundet',
       'bjorklunden',
       'bjorkskatan',
       'bjorkstrand',
       'bjolladalen',
       'bjorelvnes',
       'bjorgolfur',
       'bjornbreen',
       'bjornskinn',
       'bjorndalen',
       'bjorneborg',
       'bjorklinge',
       'bjorkhagen',
       'bjornestad',
       'bjornevatn',
       'bjorboholm',
       'bjollebotn',
       'bjornlunda',
       'bjorkviken',
       'bjornsjoen',
       'bjornfjell',
       'bjorkudden',
       'bjorkekarr',
       'bjorketorp',
       'bjorlanda',
       'bjorksten',
       'bjorklund',
       'bjornsund',
       'bjornahoi',
       'bjorsater',
       'bjornange',
       'bjornevag',
       'bjorkdale',
       'bjornseth',
       'bjornemyr',
       'bjorkeryd',
       'bjornebye',
       'bjornstad',
       'bjorksele',
       'bjorneboe',
       'bjorklia',
       'bjorkvik',
       'bjorgaas',
       'bjorkman',
       'bjorndal',
       'bjornson',
       'bjornoya',
       'bjoneroa',
       'bjornoen',
       'bjolstad',
       'bjorbekk',
       'bjollaga',
       'bjorvika',
       'bjorling',
       'bjorkoby',
       'bjordal',
       'bjornli',
       'bjoroya',
       'bjorlin',
       'bjoroyl',
       'bjornar',
       'bjornor',
       'bjorkum',
       'bjorgen',
       'bjoreio',
       'bjolsen',
       'bjorke',
       'bjorgo',
       'bjoroy',
       'bjorko',
       'bjorli',
       'bjorno',
       'bjorlo',
       'bjorge',
       'bjorna',
       'bjorbo',
       'bjorg',
       'bjorn',
       'bjork',
       'bjoa',
       'bjo'],
 'p': ['bjps'],
 'r': ['bjr'],
 's': ['bjsm', 'bjs'],
 'u': ['bjugnfjorden',
       'bjuroklubb',
       'bjurstrom',
       'bjuralven',
       'bjurholm',
       'bjugstad',
       'bjursas',
       'bjurra',
       'bjurum',
       'bjugn',
       'bjuv',
       'bjur',
       'bju'],
 'w': ['bjw']}
