
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cg = {'_': ['cg634', 'cg-20', 'cg-17', 'cg-2', 'cg-1'],
 'a': ['cgac', 'cgap', 'cgal', 'cga'],
 'b': ['cgb7', 'cgb5', 'cgb1', 'cgb2', 'cgb'],
 'c': ['cgcg', 'cgcc', 'cgc'],
 'd': ['cgd'],
 'e': ['cgetv', 'cger', 'cgea', 'cgel', 'cge'],
 'f': ['cgfc'],
 'g': ['cggbp1', 'cggs', 'cgg'],
 'h': ['cghene', 'cghs', 'cgh'],
 'i': ['cgiproxy', 'cgidev2', 'cgi:irc', 'cgi.pm', 'cgiar', 'cgis', 'cgi'],
 'l': ['cgl'],
 'm': ['cgmagazine', 'cgms-a', 'cgm48', 'cgmp', 'cgma', 'cgmi', 'cgmc', 'cgm'],
 'n': ['cgns', 'cgn'],
 'o': ['cgol', 'cgo'],
 'p': ['cgp-35348', 'cgp-37849', 'cgp-7930', 'cgpf', 'cgp'],
 'r': ['cgroups', 'cgr'],
 's': ['cgs-12066a',
       'cgs-21680',
       'cgs-20625',
       'cgs-15943',
       'cgs-13767',
       'cgs-8216',
       'cgs-9896',
       'cgsi',
       'cgss',
       'cgso',
       'cgsb',
       'cgsh',
       'cgst',
       'cgsm'],
 't': ['cgtrader', 'cgtp', 'cgtu', 'cgtl', 'cgt'],
 'u': ['cgu'],
 'v': ['cgview', 'cgv'],
 'w': ['cgwa', 'cgw'],
 'y': ['cgy']}
