
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cp = {'_': ['cp-154,526',
       'cp-122,288',
       'cp-226,269',
       'cp-615,003',
       'cp-532,903',
       'cp-132,484',
       'cp-39,332',
       'cp-135807',
       'cp-944629',
       'cp-809101',
       'cp-93129',
       'cp-1414s',
       'cp-823/u',
       'cp-40294',
       'cp-94253',
       'cp/m-86',
       'cp-450',
       'cp-300',
       'cp-200',
       'cp-500',
       'cp/cms',
       'cp-16',
       'cp-67',
       'cp2k',
       'cp/m',
       'cp24',
       'cp1',
       'cp5',
       'cp2',
       'cp4',
       'cp3',
       'cp6'],
 'a': ['cpachecker',
       'cpaconnect',
       'cpanel',
       'cpaf',
       'cpac',
       'cpa4',
       'cpam',
       'cpat',
       'cpas',
       'cpan',
       'cpa3',
       'cpa5',
       'cpa'],
 'b': ['cpbc', 'cpb'],
 'c': ['cpccoet', 'cpcm', 'cpce', 'cpcc', 'cpca', 'cpcp', 'cpc'],
 'd': ['cpd-57deg2874', 'cpd-1', 'cpdl', 'cpd'],
 'e': ['cpeb1', 'cped1', 'cpeir', 'cpesc', 'cpeb', 'cpet', 'cpep', 'cpe'],
 'f': ['cpff', 'cpf'],
 'g': ['cpga', 'cpg'],
 'h': ['cphpc', 'cphos', 'cphs', 'cpha', 'cphl', 'cph'],
 'i': ['cpi-0610', 'cpio', 'cpip', 'cpix', 'cpif', 'cpia', 'cpic'],
 'j': ['cpj'],
 'k': ['cpk'],
 'l': ['cplane1', 'cplink', 'cplex', 'cplx1', 'cplx2', 'cplc', 'cpl'],
 'm': ['cpmp-tools',
       'cpmulator',
       'cpm-goms',
       'cpme',
       'cpmi',
       'cpmp',
       'cpma',
       'cpml',
       'cpm'],
 'n': ['cpn-ami',
       'cpne4',
       'cpne7',
       'cpne1',
       'cpne8',
       'cpne6',
       'cpnb',
       'cpnp',
       'cpnt',
       'cpni',
       'cpn2',
       'cpn1',
       'cpn'],
 'o': ['cpo-stv', 'cpost', 'cpox', 'cpoa', 'cpo'],
 'p': ['cppdepend',
       'cppcheck',
       'cpplint',
       'cppunit',
       'cppcms',
       'cpps',
       'cppa',
       'cppc',
       'cppm',
       'cppd',
       'cpp'],
 'q': ['cpq'],
 'r': ['cpr-kontoret',
       'cpr-1000',
       'cpri',
       'cpr3',
       'cpra',
       'cprt',
       'cpr2',
       'cprs',
       'cpre'],
 's': ['cpsf7',
       'cpsf3',
       'cpsf1',
       'cpsf6',
       'cpsf2',
       'cpsf4',
       'cpsp',
       'cpsc',
       'cps1',
       'cps3',
       'cpsl',
       'cpsr',
       'cpsm',
       'cps2',
       'cpsx',
       'cpsk',
       'cpsa',
       'cps'],
 't': ['cpt2', 'cptp', 'cpt'],
 'u': ['cpu-bound', 'cpuid', 'cpu-z'],
 'v': ['cpv-tv', 'cpvl', 'cpv'],
 'w': ['cpwa', 'cpw'],
 'x': ['cpxm1', 'cpx'],
 'y': ['cpython'],
 'z': ['cpz']}
