
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yt = {'_': ['yt//st'],
 'a': ['ytai_abougzir', 'ytambey_river', 'ytalo_manzo', 'yta_tv'],
 'b': ['ytb_international'],
 'c': ['ytcracker', 'ytc'],
 'd': ['ytd'],
 'g': ['ytgt_gt-300'],
 'h': ['ythan_estuary', 'ythan_wells', 'yths_hs'],
 'l': ['ytl_communications', 'ytl_corporation', 'ytl_power'],
 'm': ['ytmnd', 'ytm'],
 'n': ['ytn_group'],
 'o': ['yto_barrada', 'yto_group'],
 'p': ['ytp'],
 'r': ['ytrehovdeholmen_island',
       'ytrebygda_church',
       'ytre_storevatnet',
       'ytre_oydnavatnet',
       'ytre_snillfjord',
       'ytre_sandsvaer',
       'ytre_oslofjord',
       'ytre_oksningan',
       'ytre_norskoya',
       'ytre_oppedal',
       'ytre_standal',
       'ytre_enebakk',
       'ytre_ostfold',
       'ytre_rendal',
       'ytri_dalur',
       'ytre_ramse',
       'ytre_tasta',
       'ytre_sula',
       'ytre_arna'],
 's': ['ytstenut_peak', 'ytste_skotet'],
 't': ['yttria-stabilized_zirconia',
       'ytterholmen_lighthouse',
       'ytteroyane_lighthouse',
       'yttrium_orthovanadate',
       'yttrium_oxyfluoride',
       'ytterbium_phosphide',
       'ytterlannas_parish',
       'ytterbium_chloride',
       'ytterbium_hydride',
       'yttrium_hydroxide',
       'yttrium_compounds',
       'yttrium_phosphide',
       'ytteborg_brewery',
       'yttergran_church',
       'yttrium_nitride',
       'yttygran_island',
       'yttrium_borides',
       'yttrium_oxalate',
       'yttrium_hydride',
       'ytterhogdals_ik',
       'yttrium_iodide',
       'ytteren_church',
       'ytteroy_church',
       'yttrium_oxide',
       'ytterby_is'],
 'u': ['ytu_hephaestus',
       'ytu_reichardti',
       'ytu_morpheus',
       'ytu_mirandus',
       'ytu_cleideae',
       'ytu_artemis',
       'ytu_cupidus',
       'ytu_demeter',
       'ytu_athena',
       'ytu_godayi',
       'ytu_yaguar',
       'ytu_cuyaba',
       'ytu_brutus',
       'ytu_ysypo',
       'ytu_phebo',
       'ytu_itati',
       'ytu_angra',
       'ytu_mirim',
       'ytu_zeus'],
 'v': ['ytv_jr.'],
 'y': ['ytyk-kyuyol']}
