
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_y_ = {'_': ['y._balaretnarajah',
       'y._ramakrishna',
       'y._karunadasa',
       'y._srilakshmi',
       'y._bhekhirst',
       'y._ramavaram',
       'y._gracilis',
       'y._nagappa',
       'y-49_cable',
       'y-50_cable',
       'y._misdaq',
       'y._vijaya',
       'y,_somme'],
 'a': ["y'anbessaw_tezeta",
       "y'alls_ballpark",
       "y'all_politics",
       "y'anna_crawley",
       'y_alloy'],
 'b': ['y_bandana', 'y_bergam', 'y_blew', 'y_byd', 'y_ban'],
 'c': ['y-chromosomal_aaron',
       'y-chromosomal_adam',
       'y-class_lifeboat',
       'y_combinator',
       'y_chromosome',
       'y_cymmrodor',
       'y_cofiadur',
       'y_centauri',
       'y_carinae',
       'y_complex',
       'y_control',
       'y_chhean',
       'y_cymro',
       'y_class',
       'y_cwmwl',
       'y_cyrff'],
 'd': ['y-d_transform',
       'y_drysorfa',
       'y_dinesydd',
       'y_drych',
       'y_dieng',
       'y_dydd'],
 'f': ['y2fly_seahawk',
       'y_felinheli',
       'y-fast_trie',
       'y_fronllwyd',
       'y_ferwig',
       'y_fflam',
       'y_force',
       'y_flyer',
       'y_fron',
       'y_ffor'],
 'g': ['y_glaslanciau',
       'y_gwyddonydd',
       'y_gwladgarwr',
       'y.g._srimati',
       'y_gwyliedydd',
       'y_gododdin',
       'y_gymraes',
       'y_gorddwr',
       'y_gamallt',
       'y_goleuad',
       'y_graig',
       'y_gors',
       'y_gaer',
       'y_gyrn',
       'y_garn',
       'y_gun'],
 'h': ['y@h@rci_qazaxlar'],
 'i': ['y_island'],
 'j': ['y_junction'],
 'k': ['y.k._kim'],
 'l': ["y'lan_noel",
       'y_linkage',
       'y_lliwedd',
       'y_lyncis',
       'y_llethr',
       'y_lolfa',
       'y_liver',
       'y_llan',
       'y_lle',
       'y_lan'],
 'm': ['y_magazine', 'y_mountain', 'y_mabinogi'],
 'n': ['y_niwl', 'y_nhi', 'y_not'],
 'o': ['y.o_concept'],
 'p': ['y_pants', 'y_punto', 'y_pris'],
 'r': ['y_rhedegydd',
       'y_records',
       'y_radio',
       'y&r_anz',
       'y_rhiw',
       'y_road',
       'y_rna'],
 's': ['y_sagittarii',
       'y_sextantis',
       'y.s._river',
       'y_service',
       'y_series',
       'y_speak',
       'y_soft'],
 't': ['y_traethodydd', 'y_traeth'],
 'u': ['y.u._mad'],
 'v': ['y_volvere'],
 'w': ['y_wladfa', 'y_werin'],
 'z': ['y.z._kami']}
