
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yr = {'_': ['yr_australydd',
       'yr_ymofynnydd',
       'yr_arloeswr',
       'yr_amserau',
       'yr_anhrefn',
       'yr_rune',
       'yr_elen',
       'yr_eifl',
       'yr_aran'],
 'a': ['yramea_cytheris'],
 'c': ['yrc'],
 'd': ['yrdyk', 'yrd'],
 'e': ['yreka,_california', 'yreina_cervantez', 'yretha_silete', 'yren_rotela'],
 'f': ['yrf_distribution', 'yrf_television'],
 'g': ['yrgyz_district', 'yrg_care'],
 'i': ['yrick_gallantes', 'yrius_carboni'],
 'j': ['yrjo_korholin-koski',
       'yrjo_saastamoinen',
       'yrjo_jaaskelainen',
       'yrjo_kilpelainen',
       'yrjo_vesterinen',
       'yrjo_lindegren',
       'yrjo_blomstedt',
       'yrjo_pulkkinen',
       'yrjo_kukkapuro',
       'yrjo_miettinen',
       'yrjo_salpakari',
       'yrjo_sinkkonen',
       'yrjo_jahnsson',
       'yrjo_raisanen',
       'yrjo_kivenoja',
       'yrjo_saarinen',
       'yrjo_tuominen',
       'yrjo_nikkanen',
       'yrjo_kallinen',
       'yrjo_parnanen',
       'yrjo_vaananen',
       'yrjo_rantanen',
       'yrjo_hietanen',
       'yrjo_kilpinen',
       'yrjo_keinonen',
       'yrjo_helander',
       'yrjo_lampila',
       'yrjo_sotiola',
       'yrjo_reenpaa',
       'yrjo_lehtila',
       'yrjo_kylmala',
       'yrjo_uimonen',
       'yrjo_sotamaa',
       'yrjo_halonen',
       'yrjo_ekqvist',
       'yrjo_vaisala',
       'yrjo_welling',
       'yrjo_hakoila',
       'yrjo_jussila',
       'yrjo_karilas',
       'yrjo_makelin',
       'yrjo_hautala',
       'yrjo_saarela',
       'yrjo_pesonen',
       'yrjo_valkama',
       'yrjo_nurmio',
       'yrjo_hakala',
       'yrjo_vartia',
       'yrjo_ollila',
       'yrjo_makela',
       'yrjo_sirola',
       'yrjo_vuolio',
       'yrjo_murto',
       'yrjo_kolho',
       'yrjo_ruutu',
       'yrjo_linko',
       'yrjo_neuvo',
       'yrjo_leiwo',
       'yrjo_norta',
       'yrjo_kokko',
       'yrjo_kiuru',
       'yrjo_leino',
       'yrjo_kesti',
       'yrjo_soini',
       'yrjo_vesa'],
 'k': ['yrke', 'yrk'],
 'l': ['yrl'],
 'm': ['yrm'],
 'o': ['yrondu_musavu-king'],
 'p': ['yrp'],
 'r': ['yrreal', 'yrrol'],
 's': ['yrsa_sigurdardottir', 'yrsa_daley-ward', 'yrsa_stenius'],
 't': ['yrttiaho', 'yrt'],
 'u': ['yru'],
 'v': ['yrvind_island'],
 'w': ['yrwall'],
 'y': ['yrybucua']}
