
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nj = {'_': ['nj/ny_gotham_fc'],
 'a': ['njangalude_veettile_athidhikal',
       'njandukalude_nattil_oridavela',
       "njardvik_women's_basketball",
       "njardvik_men's_basketball",
       'njan_samvidhanam_cheyyum',
       'njan_ninnodu_koodeyundu',
       'njan_ninne_premikkunnu',
       'njanum_ente_familiyum',
       'njaan_njaan_maathram',
       'njan_piranna_nattil',
       'njama_forest_park',
       'njan_steve_lopez',
       'njau_forest_park'],
 'c': ['njcaa_region_23', 'njcaa_region_8', 'njcaa_region_9'],
 'e': ['njegbwema,_kono_district', 'njena_reddd_foxxx', 'nje_mo_ye'],
 'i': ['njit_highlanders_baseball',
       'njideka_akunyili_crosby',
       'njit_capstone_program',
       'njivice,_herceg_novi',
       'njie_ngenevu_divine',
       'njiko_igbo_movement',
       'nji_oumarou_nchare'],
 'm': ['njm_insurance_group', 'njmp_arca_150'],
 'o': ['njonjo_land_commission',
       'njombe_urban_district',
       'njombe_rural_district',
       "njoki_susanna_ndung'u",
       'njoo_cheong_seng',
       'njoro_river_cave',
       'njord_oil_field',
       'njoo_han_siang',
       'njoo_kiem_bie'],
 'p': ['njpac/center_street_station',
       'njpw_power_struggle',
       'njpw_ultimate_crush',
       'njpw_jingu_climax',
       'njpw_royal_quest',
       'njpw_final_dome',
       'njpw_do_judge!!'],
 's': ['njsa_government_college'],
 'u': ['njube_sundowns_f.c.']}
