
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nh = {'_': ['nh_collection_open', 'nh_hotel_group', 'nh_162_ext'],
 'a': ['nha_trang_university',
       'nhaeng_nhang_commune',
       'nha_san_collective',
       'nha_trang_dolphins',
       'nha_trang_airport',
       'nha_trang_station',
       'nha_trang_stadium',
       'nhaa-ii_rna_motif',
       'nhaa-i_rna_motif',
       'nhat_tan_bridge',
       'nha_be_district',
       'nhat_le_beach',
       'nhat_le_river',
       'nhat_chi_mai',
       'nha_be_base',
       'nhac_tai_tu',
       'nha_tho_ho'],
 'e': ['nheengatu_ao_vivo', 'nhek_bun_chhay'],
 'i': ['nhif_ambulance_scandal',
       'nhill_railway_station',
       'nhi_h-3_kolibrie',
       'nhial_deng_nhial',
       'nhi_do_mai',
       'nhi_lan_le'],
 'k': ['nhk_kawaguchi_transmitter',
       'nhk_broadcasting_center',
       'nhk_symphony_orchestra',
       'nhk_spring_company',
       'nhk_educational_tv',
       'nhk_fm_broadcast',
       'nhk_nodo_jiman',
       'nhk_osaka_hall',
       'nhk_general_tv',
       'nhk_mile_cup',
       'nhk_radio_1',
       'nhk_radio_2',
       'nhk_news_7'],
 'l': ['nhlanhlayamangwe_felix_ndiweni',
       'nhl_supplemental_draft',
       'nhl_centennial_classic',
       'nhl_championship_2000',
       'nhl_conference_finals',
       'nhl_plus-minus_award',
       'nhl_heritage_classic',
       'nhl_enterprises,_lp',
       'nhl_all-rookie_team',
       'nhl_youngstars_game',
       'nhl_stadium_series',
       'nhl_winter_classic',
       'nhl_all-star_game',
       "nhl_powerplay_'96",
       'nhl_outdoor_games',
       'nhl_all-star_team',
       'nhl_powerplay_98',
       'nhl_breakaway_99',
       'nhl_breakaway_98',
       'nhl_faceoff_2001',
       'nhl_on_sportsnet',
       'nhl_faceoff_2003',
       'nhl_faceoff_2000',
       "nhlpa_hockey_'93",
       'nhl_5-on-5_2006',
       'nhl_100_classic',
       "nhl_faceoff_'97",
       'nhl_first_timer',
       'nhl_entry_draft',
       'nhl_faceoff_99',
       'nhl_salary_cap',
       'nhl_faceoff_98',
       'nhl_centre_ice',
       'nhl_center_ice',
       'nhl_hitz_2002',
       'nhl_on_global',
       'nhl_hitz_2003',
       'nhl_on_versus',
       'nhl_on_hughes',
       'nhl_hitz_pro',
       'nhl_on_hdnet',
       'nhl_on_espn',
       'nhl_on_rds',
       'nhl_on_ctv',
       'nhl_on_tnt',
       'nhl_on_nbc',
       'nhl_on_cbs',
       'nhl_on_abc',
       'nhl_on_usa',
       'nhl_on_fox'],
 'n': ['nhn_entertainment_corporation',
       'nhn_japan_corporation',
       'nhnz_moving_images'],
 'o': ['nhon_trach_district', 'nho_quan_district', 'nho_que_river'],
 'r': ['nhra_u.s._nationals'],
 's': ['nhs-wide_clearing_service',
       'nhs_information_authority',
       'nhs_volunteer_responders',
       'nhs_modernisation_agency',
       'nhs_treatments_blacklist',
       'nhs_support_federation',
       'nhs_e-referral_service',
       'nhs_charities_together',
       'nhs_ambulance_services',
       'nhs_property_services',
       'nhs_foundation_trust',
       'nhsbt_blood_donation',
       'nhs_internal_market',
       'nhs_health_scotland',
       'nhs_pension_scheme',
       'nhs_louisa_jordan',
       'nhs_west_midlands',
       'nhs_western_isles',
       'nhst_media_group',
       'nhs_apps_library',
       'nhs_forth_valley',
       'nhs_direct_wales',
       'nhs_credit_union',
       'nhs_health_check',
       'nhs_supply_chain',
       'nhs_the_musical',
       'nhs_west_essex',
       'nhs_care_trust',
       'nhs_north_west',
       'nhs_plan_2000'],
 'u': ['nhuchhe_ratna_tuladhar',
       'nhu_thanh_district',
       'nhu_xuan_district',
       'nhuan_phu_tan'],
 'v': ['nhv_eredivisie_dames']}
