
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jn = {'_': ['jn53dv', 'jn1'],
 'a': ['jnatrdharmakathah',
       'jnanaprasthana',
       'jnanasrimitra',
       'jnanagarbha',
       'jnanasudha',
       'jnanarnava',
       'jnanagupta',
       'jnanappana',
       'jnanasutra',
       'jnanayasas',
       'jnanaraja',
       'jnaerator',
       'jnanpara',
       'jnatjo',
       'jnana',
       'jna'],
 'b': ['jnbridge'],
 'c': ['jnco', 'jnc'],
 'e': ['jnes', 'jnet', 'jne'],
 'g': ['jng'],
 'j': ['jnj-28330835',
       'jnj-26990990',
       'jnj-39393406',
       'jnj-10397049',
       'jnj-18038683',
       'jnj-42165279',
       'jnj-26489112',
       'jnj-7925476',
       'jnj-5207852',
       'jnj-7777120',
       'jnj-q2'],
 'l': ['jnl'],
 'n': ['jnn'],
 'o': ['jno'],
 'p': ['jnp'],
 's': ['jns'],
 't': ['jnt'],
 'u': ['jnu']}
