
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nw = {'_': ['nw_innovation_works',
       'nw_postcode_area',
       'nw_first_truck',
       'nw_london_f.c.'],
 'a': ['nwa_heritage_championship',
       'nwa_canadian_championship',
       'nwa_hollywood_wrestling',
       'nwanedi_provincial_park',
       'nwa_all-star_wrestling',
       'nwali_sylvester_ngwuta',
       'nwa_anniversary_show',
       'nwagu_aneke_script',
       'nwa_san_francisco',
       'nwa_pop-up_event',
       'nwa_roller_derby',
       'nwam_jar_thaing',
       'nwa_hard_times',
       'nwa_all_access',
       'nway_kandar_oo'],
 'c': ['nwcfa_intermediate_cup', 'nwcfa_junior_cup'],
 'e': ['nwe_darli_tun',
       'nwet_nwet_mu',
       'nwe_nwe_aung',
       'nwe_yin_win',
       'nwe_no._21',
       'nwe_ni_oo'],
 'f': ['nwf_heavyweight_championship',
       'nwfb_route_13',
       'nwfb_route_8',
       'nwfb_route_4',
       'nwfb_route_2'],
 'l': ['nwl_cruiserweight_championship',
       'nwl_heavyweight_championship',
       'nwl_midget_championship',
       'nwl_ladies_championship'],
 'o': ['nwonyo_fishing_festival'],
 'p': ['nwpu_v/stol_uav'],
 's': ['nwsl_federation_players', "nwsl_players'_awards", 'nwsl_challenge_cup'],
 't': ['nwt_spruce_coupe']}
