
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ny = {'_': ['ny-alesund_airport,_hamnerabben',
       'ny_hasina_andriamanjato',
       'ny_avana_ramanantoanina',
       'ny_carlsberg_glyptotek',
       'ny_carlsberg_brewhouse',
       'ny_ellebjerg_station',
       'ny_kongensgade_11',
       'ny_persian_parade',
       'ny_vestergade_11',
       'ny_kongensgade_3',
       'ny_vestergade_13',
       'ny_kongensgade_5',
       'ny_carlsberg_vej',
       'ny_kongensgade_9',
       'ny_kongensgade_7',
       'ny_kongensgade_6',
       'ny_troor_tromode',
       'ny_vestergade_9',
       'ny_racing_team',
       'ny_koen_group',
       'ny_safe_act'],
 'a': ['nyakahita-kazo-kamwenge-fort_portal_road',
       'nyasaland_constitutional_party',
       'nyaribari_chache_constituency',
       'nyaribari_masaba_constituency',
       'nyasaland_government_gazette',
       'nyangabgwe_referral_hospital',
       'nyamirambo_regional_stadium',
       'nyandeni_local_municipality',
       'nyaungyan_mintaya_ayedawbon',
       'nyasaland_volunteer_reserve',
       'nyakayojo_secondary_school',
       'nyasaland_african_congress',
       'nyabing,_western_australia',
       'nyakibanda_major_seminary',
       'nyaradzo_secondary_school',
       'nyakuron_cultural_centre',
       'nyasaland_emergency_1959',
       'nyang_mangpoje_shangnang',
       'nyama_county,_queensland',
       'nyalakonda_ramkishan_rao',
       'nyang_tingngezin_sangpo',
       'nyandeng_malek_deliech',
       'nyanda_railway_station',
       'nyayo_national_stadium',
       'nyandarua_high_school',
       'nya_svenska_samskolan',
       'nyanaberi_forest_park',
       'nyayam_meere_cheppali',
       "nyandi_women's_prison",
       'nyambaria_high_school',
       "nyang'ori_high_school",
       'nyasaland_famine_1949',
       'nya_dagligt_allehanda',
       'nyassang_forest_park',
       'nyaung_waing_village',
       'nyack_public_schools',
       'nyanga,_western_cape',
       'nyanga_national_park',
       'nyanga_bus_accident',
       'nya_ludvika_tidning',
       'nyangrel_nyima_ozer',
       'nyaya_neethi_dharma',
       'nya_froken_sverige',
       'nyaay:_the_justice',
       'nyah_football_club',
       'nyaicili_boki_raja',
       'nyai_ahmad_dahlan',
       'nyala_pema_dundul',
       'nyah_kur_language',
       'nyal,_south_sudan',
       'nyai_gede_pinateh',
       'nyack_high_school',
       'nyaluk_t._gatluak',
       'nyalu_lagna_pass',
       'nyaung_u_airport',
       'nyai_roro_kidul',
       'nyah_kur_people',
       'nyack,_new_york',
       'nyah_man_chant',
       'nyaika_of_toro',
       'nyalam_tong_la',
       'nyan_tun_aung'],
 'b': ['nyborg_town_hall', 'nybrua_tram_stop'],
 'c': ['nyc_skateboard_coalition',
       'nyc_surgical_associates',
       'nycity_news_service',
       'nycasius_de_clibano',
       'nyc:_tornado_terror',
       'nyc_busker_ball',
       'nyc_arts_cypher',
       'nyc_and_company',
       'nyc_pride_march',
       'nyc_express_bus',
       'nyck_de_vries'],
 'd': ['nydala_abbey_bloodbath',
       'nydalen_metro_station',
       'nydia_quintero_turbay'],
 'e': ['nyenrode_business_university',
       'nyenchen_tanglha_mountains',
       'nyeri_town_constituency',
       'nye-holman_state_forest',
       'nyenga_mission_hospital',
       'nyeleti_brooke_mondlane',
       'nyemo_chekar_monastery',
       'nyethang_drolma_temple',
       'nyeboe_land_formation',
       'nye_county_courthouse',
       'nyerere_national_park',
       'nyero_rock_paintings',
       'nye,_west_virginia',
       'nye_county,_nevada',
       'nyeri_high_school',
       'nyenye_rovers_fc',
       'nyein_chan_aung',
       'nyein_chan_kyaw',
       'nye_jordal_amfi',
       'nyein_chan_su'],
 'g': ['nygardsfjellet_wind_farm'],
 'h': ['nyholm_central_guardhouse', 'nyhamna_gas_plant'],
 'i': ['nyirripi,_northern_territory',
       'nyiregyhaza_new_synagogue',
       'nyingchi_mainling_airport',
       'nyiregyhaza_spartacus_fc',
       'nyima_township,_baingoin',
       'nyiakeng_puachue_hmong',
       'nyika_climbing_mouse',
       'nyika_national_park',
       'nyi_ageng_serang',
       'nyika_rock_rat',
       'nyi_nyi_maung',
       'nyi_nyi_htwe',
       'nyi_nyi_lwin',
       'nyi_min_han',
       'nyi_nyi_min',
       'nyi_shu_gu'],
 'k': ['nykopings_gymnasium_gripenskolan',
       'nykobing_falster_handboldklub',
       'nykobing_falster_idraetspark',
       'nykredit_architecture_prize',
       'nykvag/nykan_nature_reserve',
       'nyke/tussen_nature_reserve',
       'nykoping_railway_bridge',
       'nyk_maritime_museum'],
 'l': ['nylsvley_nature_reserve', 'nylon_rope_trick', 'nyla_ali_khan'],
 'm': ['nymphenburg_porcelain_manufactory',
       'nymboi-binderay_national_park',
       'nymolle,_allerod_municipality',
       'nymphenburg_palace_park',
       'nympsfield_long_barrow',
       'nymph_of_fontainebleau',
       'nymboida_national_park',
       'nymphus_hinckley_house',
       'nymboida_power_station',
       'nymphidianus_of_smyrna',
       'nymphodorus_of_abdera',
       'nymphs_and_shepherds',
       'nyma_akashat_zibiri',
       'nymbai_forest_park',
       'nymphes_des_bois',
       'nymphs_and_satyr',
       'nymph_and_fawn'],
 'n': ['nynorsk_literature_prize', 'nyngan_solar_plant', 'nyngan_court_house'],
 'o': ['nyonoksa_radiation_accident',
       'nyoshul_khenpo_rinpoche',
       'nyota_radio_television',
       'nyota,_the_peacemaker',
       'nyora_railway_station',
       'nyon_railway_station',
       'nyon_rugby_club',
       'nyo_twan_awng',
       'nyo_min_lwin',
       'nyo_nyo_thin',
       'nyo_min_lu'],
 'p': ['nypd_cricket_league',
       'nypd_aviation_unit',
       'nypd_police_band',
       'nypd_x-ray_vans',
       'nypd_red_4',
       'nypd_red_3'],
 'q': ['nyquist-shannon_sampling_theorem',
       'nyquist_stability_criterion',
       'nyquist_isi_criterion'],
 'r': ['nyree_dawn_porter'],
 's': ['nystrom_guest_house',
       'nysa_of_cappadocia',
       'nyssa_high_school',
       'nysted_wind_farm'],
 't': ['nythamar_de_oliveira',
       'nytex_sports_centre',
       'nytt_pa_nytt',
       'nytt_i_uka'],
 'u': ['nyubskaya_narrow-gauge_railway',
       'nyukhcha,_arkhangelsk_oblast',
       'nyumanzi_refugee_settlement',
       'nyurpaya_kaika_burton',
       'nyu_violets_football',
       'nyu_district,_fukui',
       'nyu_liberal_studies',
       'nyutabaru_air_base',
       'nyuntam_aay_yojana',
       'nyuju_stumpy_brown',
       'nyu_langone_health',
       'nyu_tandon_online',
       'nyumba_ya_sanaa'],
 'x': ['nyxquest:_kindred_spirits', 'nyx_professional_makeup'],
 'z': ['nyzhni_sirohozy_raion', 'nyzy_railway_station']}
