
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kd = {'_': ['kd_subdivision',
       'kd_mahawangsa',
       'kd_kempamma',
       'kd_ilirija',
       'kd_slovan',
       'kd_rahmat',
       'kd_singh',
       'kd_avia',
       'kd_no:1',
       'kd_air'],
 'a': ['kdam_eurovision', 'kdanh_commune', 'kdan_mobile'],
 'b': ['kdb_darussalam',
       'kdb_darulehsan',
       'kdb_daruttaqwa',
       'kdb_darulaman',
       'kdb_syafaat',
       'kdb_ijtihad',
       'kdb_seteria',
       'kdb_mustaed',
       'kdb_pejuang',
       'kdb_waspada',
       'kdb_berkat',
       'kdb_afiat'],
 'c': ['kdc_racing', 'kdc_mine'],
 'd': ['kddx-class_destroyer', 'kddi_mobile', 'kdd_group'],
 'e': ['kde_applications',
       'kde_frameworks',
       'kde_telepathy',
       'kde_projects',
       'kde_connect',
       'kde_plasma',
       'kde_neon',
       'kde_e.v.'],
 'f': ['kdf_energy'],
 'g': ['kdgl-ld', 'kdgz-lp', 'kdge', 'kdgl', 'kdgs', 'kdgo', 'kdgw', 'kdg'],
 'h': ['kdhe-lp',
       'kdhs-lp',
       'kdhu-ld',
       'kdhw-cd',
       'kdhx',
       'kdhn',
       'kdhl',
       'kdhk',
       'kdht'],
 'i': ['kdif-lp',
       'kdis-fm',
       'kdit-cd',
       'kdice',
       'kdif',
       'kdiz',
       'kdil',
       'kdia',
       'kdic',
       'kdis',
       'kdio',
       'kdix'],
 'j': ['kdjt-cd',
       'kdjs-fm',
       'kdjs',
       'kdjf',
       'kdjj',
       'kdjw',
       'kdje',
       'kdji',
       'kdjr'],
 'k': ['kdk_factory', 'kdk_union'],
 'l': ['kdlt_tower'],
 'm': ['kdm_shipping', 'kdmm_f.c.'],
 'n': ['kdnu-ld',
       'kdnl-tv',
       'kdni',
       'kdnz',
       'kdno',
       'kdnw',
       'kdne',
       'kdnn',
       'kdnd',
       'kdnr',
       'kdns',
       'kdnk',
       'kdna',
       'kdnt',
       'kdn'],
 'o': ['kdo_transferase', 'kdol_tahen'],
 'p': ['kdpi-komala_conflict'],
 'q': ['kdqn-fm', 'kdqn'],
 'r': ['kdr_444'],
 's': ['kds_micronex', 'kds_group'],
 't': ['kdt_nacional'],
 'u': ['kdux-fm',
       'kduk-fm',
       'kdu-csl',
       'kdua-lp',
       'kdul-lp',
       'kdub-lp',
       'kduo-lp',
       'kdump',
       'kdun',
       'kdut',
       'kdus',
       'kduv',
       'kdux',
       'kduc',
       'kdub',
       'kduz',
       'kdup',
       'kdug',
       'kdur',
       'kdu'],
 'v': ['kdv_hierarchy'],
 'w': ['kdwb-fm', 'kdwr-lp', 'kdwg', 'kdwa', 'kdwd', 'kdwy', 'kdwn'],
 'x': ['kdx-iia',
       'kdxi-lp',
       'kdxe',
       'kdxt',
       'kdxu',
       'kdxy',
       'kdxl',
       'kdxx',
       'kdxn',
       'kdx'],
 'y': ['kdyn-fm',
       'kdys-ld',
       'kdyne',
       'kdyk',
       'kdya',
       'kdyw',
       'kdyl',
       'kdym',
       'kdyn',
       'kdy'],
 'z': ['kdza-tv', 'kdz1a', 'kdz1', 'kdzr', 'kdzy', 'kdzn', 'kdza', 'kdz']}
