
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_km = {'_': ['km_communications',
       'km_torhout',
       'km_produce',
       'km131_jeep',
       'km_racing',
       'km_marlin',
       'km_sobhan',
       'km-8_gran',
       'km_pekan',
       'km_asif',
       'km_arau',
       'km._0',
       'km_3'],
 'a': ['kmart_australia',
       'kmart_realism',
       'kmac_museum',
       'kma_music',
       'kmag_yoyo',
       'kma_usop'],
 'b': ['kmb09_protocol', 'kmb_jazz'],
 'c': ['kmc_controls', 'kmc_komando'],
 'd': ['kmdf-ld',
       'kmdg',
       'kmdr',
       'kmds',
       'kmdx',
       'kmdb',
       'kmdo',
       'kmdz',
       'kmdy',
       'kmdl',
       'kmd'],
 'e': ['kmehlener_berge',
       'kmele_foster',
       'kmetija_2021',
       'kmetija_2018',
       'kmetija_2019',
       'kme_group'],
 'f': ['kmfdm_discography',
       'kmfm_canterbury',
       'kmfm_maidstone',
       'kmf_policajac',
       'kmfm_ashford',
       'kmf_ekonomac',
       'kmfm_thanet',
       'kmfm_medway',
       'kmfm_extra',
       'kmf_deus',
       'kmf_sas'],
 'g': ['kmg_international', 'kmg_ethiopia', 'kmg_records', 'kmgi_group'],
 'h': ['kmh_budapest'],
 'i': ['kmita_zabierzow'],
 'j': ['kmjc-ld',
       'kmjj-fm',
       'kmj-fm',
       'kmjc',
       'kmjk',
       'kmji',
       'kmjm',
       'kmjq',
       'kmjx',
       'kmjv',
       'kmjg',
       'kmje',
       'kmj'],
 'k': ['kmkadzor,_nagorno-karabakh', 'kmkm_f.c.'],
 'l': ['kmldonkey',
       'kml-010',
       'kmlm-fm',
       'kmlm-dt',
       'kmls',
       'kmla',
       'kmlk',
       'kmle',
       'kmlo',
       'kmlu',
       'kmlb',
       'kmly',
       'kmld'],
 'm': ['kmma-cd',
       'kmms-fm',
       'kmmo-fm',
       'kmmd-cd',
       'kmmk-lp',
       'kmmy',
       'kmmo',
       'kmmm',
       'kmme',
       'kmmj',
       'kmmt',
       'kmmr',
       'kmmf',
       'kmmg',
       'kmmq',
       'kmmx',
       'kmmk',
       'kmml',
       'kmms',
       'kmmz',
       'kmm'],
 'n': ['kmn_sevnica', 'kmn_puntar'],
 'o': ['kmoz-fm',
       'kmob-lp',
       'kmon-fm',
       'kmoo-fm',
       'kmod-fm',
       'kmoh-tv',
       'kmol-ld',
       'kmos-tv',
       'kmoch',
       'kmok',
       'kmon',
       'kmot',
       'kmoc',
       'kmob',
       'kmoe',
       'kmom',
       'kmop',
       'kmoz',
       'kmog',
       'kmoa',
       'kmov',
       'kmox',
       'kmod',
       'kmoq',
       'kmor',
       'kmoj',
       'kmoy',
       'kmou',
       'kmo'],
 'p': ['kmp_holdings'],
 'q': ['kmq_viewer'],
 'r': ['kmrd-lp',
       'kmrz-fm',
       'kmre-lp',
       'kmrk-fm',
       'kmrap',
       'kmrx',
       'kmrq',
       'kmrv',
       'kmrc',
       'kmrz',
       'kmrl',
       'kmrn',
       'kmro',
       'kmrj',
       'kmrb',
       'kmrf',
       'kmrr',
       'kmri',
       'kmrs',
       'kmry',
       'kmr'],
 's': ['kmsp_tower', 'kms_fusion', 'kms_tools', 'kms_state'],
 't': ['kmtv_asia'],
 'u': ['kmum-cd',
       'kmuv-ld',
       'kmul-fm',
       'kmup-1',
       'kmud',
       'kmuw',
       'kmun',
       'kmuc',
       'kmus',
       'kmul',
       'kmue',
       'kmuz',
       'kmur',
       'kmu'],
 'v': ['kmvp-fm',
       'kmvl-fm',
       'kmvq-fm',
       'kmvu-dt',
       'kmvt',
       'kmvl',
       'kmvg',
       'kmvn',
       'kmvs',
       'kmve',
       'kmvr',
       'kmvp',
       'kmvc',
       'kmvk',
       'kmvx',
       'kmvi',
       'kmva'],
 'w': ['kmw_f2'],
 'x': ['kmxj-fm',
       'kmxa-fm',
       'kmxe-fm',
       'kmxz-fm',
       'kmxg',
       'kmxv',
       'kmxd',
       'kmxn',
       'kmxq',
       'kmxp',
       'kmxf',
       'kmxs',
       'kmxo',
       'kmxl',
       'kmxx',
       'kmxi',
       'kmxb',
       'kmxh',
       'kmxa',
       'kmxk',
       'kmxt',
       'kmxw',
       'kmxy',
       'kmxm',
       'kmxr'],
 'y': ['kmymoney',
       'kmyz-fm',
       'kmyx-fm',
       'kmyt-tv',
       'kmya-dt',
       'kmyl-ld',
       'kmyq',
       'kmys',
       'kmyc',
       'kmyo',
       'kmyn',
       'kmyi',
       'kmyt',
       'kmyu',
       'kmyy'],
 'z': ['kmzg-lp',
       'kmze',
       'kmzl',
       'kmzo',
       'kmzr',
       'kmzk',
       'kmzz',
       'kmzt',
       'kmzn',
       'kmzu',
       'kmza',
       'kmzq',
       'kmz']}
