
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kg = {'_': ['kg_canaleta', 'kg_convoys', 'kg_united'],
 'a': ['kgalebane_mohlakoana',
       'kgalagadi_language',
       'kgalagadi_district',
       'kgatleng_district',
       'kgalema_motlanthe',
       'kgakgamotso_pharo',
       'kgaogelo_sekgota',
       'kgaudisa_molefe',
       'kgari,_botswana',
       'kgagodi_crater',
       'kgale_hill'],
 'b': ['kgb_archiver', 'kgb_museum'],
 'c': ['kgce-lp',
       'kgca-lp',
       'kgcg-lp',
       'kgcs-ld',
       'kgcw',
       'kgco',
       'kgcv',
       'kgcl',
       'kgce',
       'kgcx',
       'kgcr',
       'kgcd',
       'kgcn',
       'kgcc',
       'kgc'],
 'd': ['kgdp-fm',
       'kgdm-lp',
       'kgdb',
       'kgdd',
       'kgdl',
       'kgdq',
       'kgdc',
       'kgdm',
       'kgd'],
 'e': ['kgebetli_moele'],
 'f': ['kgf_academy', 'kgf_school'],
 'g': ['kggv-lp',
       'kggf-fm',
       'kggg',
       'kggl',
       'kggs',
       'kggi',
       'kgga',
       'kggm',
       'kggn',
       'kggr',
       'kggf',
       'kggb',
       'kggo'],
 'h': ['kghb-cd',
       'kghd-lp',
       'kgho-lp',
       'kghs',
       'kght',
       'kghz',
       'kghl',
       'kghm',
       'kghp',
       'kghr',
       'kghy',
       'kgh'],
 'i': ['kgi_bank'],
 'j': ['kgjn-lp', 'kgjt-cd', 'kgjt', 'kgjx'],
 'k': ['kgkc-ld', 'kgkl-fm', 'kgks', 'kgkg', 'kgkl', 'kgky'],
 'l': ['kglr-lp',
       'kglh-lp',
       'kgla-dt',
       'kglm-fm',
       'kgld',
       'kglt',
       'kglb',
       'kglo',
       'kgla',
       'kgli',
       'kglx',
       'kglp',
       'kglk',
       'kgll',
       'kglh',
       'kglr',
       'kgls',
       'kgle',
       'kglc',
       'kgln'],
 'm': ['kgmz-fm',
       'kgmm-cd',
       'kgmz',
       'kgmx',
       'kgme',
       'kgmy',
       'kgms',
       'kgmi',
       'kgmc',
       'kgmn',
       'kgmt',
       'kgmb',
       'kgmo',
       'kgm'],
 'n': ['kgng-ld',
       'kgnc-fm',
       'kgns-tv',
       'kgnt',
       'kgnu',
       'kgnx',
       'kgnw',
       'kgno',
       'kgng',
       'kgnv',
       'kgnz',
       'kgnr',
       'kgni',
       'kgnd',
       'kgnb',
       'kgnc'],
 'o': ['kgosiemang_khumoyarano',
       'kgomotso_itlhabanyeng',
       'kgomotso_christopher',
       'kgomotso_balotthanyi',
       'kgosietsile_mampori',
       'kgothatso_montjane',
       'kgosi_galeshewe',
       'kgosi_sekonyela',
       'kgopedi_lilokoe',
       'kgomotso_moahi',
       'kgosi_gaborone',
       'kgotso_moleko',
       'kgosi_letlape',
       'kgosi_ntlhe'],
 'p': ['kgpx-tv',
       'kgpc-lp',
       'kgps-lp',
       'kgp-9',
       'kgpe',
       'kgpf',
       'kgpr',
       'kgpg',
       'kgpt',
       'kgpq',
       'kgp'],
 'q': ['kgq'],
 'r': ['kgrt-fm',
       'kgrx-ld',
       'kgra-fm',
       'kgru-lp',
       'kgre-fm',
       'kgrg-fm',
       'kgraft',
       'kgrd',
       'kgrn',
       'kgrs',
       'kgrv',
       'kgrb',
       'kgrk',
       'kgrc',
       'kgrz',
       'kgrg',
       'kgri',
       'kgrt',
       'kgrw',
       'kgrm',
       'kgro',
       'kgre',
       'kgrr',
       'kgra'],
 's': ['kgsw-tv', 'kgst', 'kgsv', 'kgsl', 'kgso', 'kgsp', 'kgsr', 'kgs'],
 't': ['kgtv_tower'],
 'u': ['kgum-fm',
       'kgus-lp',
       'kgun-tv',
       'kgu-fm',
       'kgus',
       'kgum',
       'kgud',
       'kgua',
       'kgu'],
 'v': ['kgv_oval', 'kgv_park'],
 'w': ['kgwc-tv', 'kgwn-tv', 'kgwb', 'kgwa', 'kgwy', 'kgwd', 'kgwp', 'kgw'],
 'x': ['kgxx', 'kgxy', 'kgx'],
 'y': ['kgyn', 'kgym', 'kgy']}
