
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kt = {'_': ['kt_corporation',
       'kt_rabeeullah',
       'kt_tunstall',
       'kt_sullivan',
       'kt_eridani',
       'kt_skylife',
       'kt_rolster',
       'kt_group',
       'kt_lupi',
       'kt_wiz'],
 'a': ['kta_advocates', 'ktav_ashuri', 'ktav_stam'],
 'b': ['ktb_mechatronics'],
 'c': ['ktcu-fm',
       'ktcs-fm',
       'ktcz-fm',
       'ktcj-ld',
       'ktck-fm',
       'ktch',
       'ktcs',
       'ktcv',
       'ktcc',
       'ktcy',
       'ktcn',
       'ktcm',
       'ktcx',
       'ktck',
       'ktcl',
       'ktct',
       'ktce',
       'ktco',
       'ktc'],
 'd': ['ktdu-80',
       'ktdu-35',
       'ktdt-lp',
       'ktdz',
       'ktdm',
       'ktdr',
       'ktdo',
       'ktdk',
       'ktdb',
       'ktdf',
       'ktdc',
       'ktdy',
       'ktdv',
       'ktdd',
       'ktde',
       'ktd'],
 'e': ['ktenostreptus_anderssoni',
       'ktenostreptus_specularis',
       'ktenostreptus_lankaensis',
       'ktenostreptus_costulatus',
       'ktenostreptus_centrurus',
       'ktenostreptus_rugulosus',
       'ktenostreptus_anulipes',
       'ktery_sk',
       'ktery_b',
       'ktery_a'],
 'f': ['ktfs-fm',
       'ktfw-fm',
       'ktfv-cd',
       'ktfa-lp',
       'ktfd-tv',
       'ktfo-cd',
       'ktfx-fm',
       'ktfq-tv',
       'ktfk-dt',
       'ktff-dt',
       'ktfo',
       'ktfr',
       'ktfj',
       'ktfc',
       'ktfb',
       'ktfs',
       'ktfy',
       'ktfi',
       'ktfn',
       'ktfm',
       'ktfl',
       'ktf'],
 'g': ['ktgb-lp',
       'ktgr-fm',
       'ktgm',
       'ktgg',
       'ktga',
       'ktgx',
       'ktgw',
       'ktgr',
       'ktgv',
       'ktge',
       'ktgl',
       'ktgo',
       'ktgs',
       'ktg'],
 'h': ['kthny_theory', 'ktheju_tokes', 'kth_krynica'],
 'i': ['ktiv_menuqad', 'kting_voar'],
 'j': ['ktjt-lp',
       'ktja-lp',
       'ktjo-fm',
       'ktjz',
       'ktjs',
       'ktjk',
       'ktjj',
       'ktjm',
       'ktjn',
       'ktj'],
 'k': ['ktka-tv',
       'ktkb-fm',
       'ktkb-ld',
       'ktkx',
       'ktks',
       'ktkb',
       'ktkz',
       'ktkt',
       'ktko',
       'ktkc',
       'ktke',
       'ktkr',
       'ktku',
       'ktkk',
       'ktkn',
       'ktk'],
 'l': ['ktld-cd',
       'ktlo-fm',
       'ktle-ld',
       'ktls-fm',
       'ktlk-fm',
       'ktlo-ld',
       'ktln-tv',
       'ktlb',
       'ktln',
       'ktla',
       'ktlr',
       'ktlu',
       'ktlw',
       'ktlt',
       'ktli',
       'ktlf',
       'ktlz',
       'ktlo',
       'ktlx',
       'ktlh',
       'ktlk',
       'ktlm',
       'ktlv',
       'ktlq',
       'ktl'],
 'm': ['ktm_intercity',
       'ktm_komuter',
       'ktm_rc250gp',
       'ktm_museum',
       'ktm_x-bow',
       'ktm_1190',
       'ktm_rc16',
       'ktm_300',
       'ktm_cty',
       'ktm_ets',
       'ktm_200'],
 'n': ['ktn_news'],
 'o': ['ktown_cowboys', 'kto_rosomak', 'kto_rys'],
 'p': ['ktp_basket'],
 'q': ['ktqm-fm', 'ktqx', 'ktq'],
 'r': ['ktrf-fm',
       'ktra-fm',
       'ktru-lp',
       'ktrs-fm',
       'ktrv-tv',
       'ktrk-tv',
       'ktrace',
       'ktrq',
       'ktrc',
       'ktrg',
       'ktrr',
       'ktrh',
       'ktri',
       'ktrl',
       'ktrk',
       'ktrs',
       'ktry',
       'ktrv',
       'ktru',
       'ktro',
       'ktre',
       'ktrm',
       'ktrf',
       'ktrb',
       'ktrn',
       'ktrt',
       'ktrz',
       'ktrp',
       'ktrx',
       'ktrw',
       'ktr'],
 's': ['ktse-fm',
       'ktsm-tv',
       'ktss-lp',
       'ktsc-fm',
       'ktsb-cd',
       'ktsarim',
       'ktsm-fm',
       'ktsord',
       'ktssm',
       'ktsap',
       'ktsy',
       'ktsw',
       'ktsf',
       'ktsl',
       'ktsc',
       'ktsj',
       'ktsa',
       'ktsb',
       'ktse',
       'ktsu',
       'ktsp',
       'ktsn',
       'ktsm',
       'ktso',
       'ktsd',
       'ktst',
       'ktsr',
       'kts'],
 't': ['ktts-fm',
       'kttz-fm',
       'kttu-fm',
       'kttr-fm',
       'kttn-fm',
       'kttz-tv',
       'kttf-lp',
       'kttx',
       'kttz',
       'kttg',
       'ktto',
       'kttw',
       'kttv',
       'kttl',
       'ktty',
       'kttr',
       'kttn',
       'ktth',
       'ktts',
       'kttp',
       'ktta',
       'kttc',
       'ktti',
       'kttk',
       'kttt',
       'kttf',
       'kttu',
       'ktt'],
 'u': ['ktuts_monastery', 'ktunaxa_nation'],
 'v': ['ktvo-tv_tower', 'ktv_ltd.'],
 'w': ['ktwc-ld',
       'ktwh-lp',
       'ktwo-tv',
       'ktwo',
       'ktwn',
       'ktwd',
       'ktwl',
       'ktwa',
       'ktws',
       'ktwu',
       'ktwg',
       'ktwf',
       'ktwi',
       'ktwv',
       'ktwb',
       'ktw'],
 'x': ['ktx-sancheon',
       'ktx-eum',
       'ktxc-lp',
       'ktxt-fm',
       'ktxd-tv',
       'ktxx-fm',
       'ktxj-fm',
       'ktxs-tv',
       'ktxn-fm',
       'ktxd-lp',
       'ktx-i',
       'ktxl',
       'ktxo',
       'ktxt',
       'ktxv',
       'ktxr',
       'ktxy',
       'ktxa',
       'ktxw',
       'ktxz',
       'ktxk',
       'ktxd',
       'ktxh',
       'ktxc',
       'ktxm'],
 'y': ['ktyj-lp',
       'ktyl-fm',
       'ktyn',
       'ktyr',
       'ktyd',
       'ktyv',
       'ktyk',
       'ktym',
       'ktyl',
       'ktyg'],
 'z': ["ktzi'ot_prison", 'ktzat_acheret']}
