
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xo = {'_': ['xo`jaobod_district',
       'xo`jayli_district',
       'xo_communications',
       'xo_telescope',
       'xo_project',
       'xo_stereo',
       'xo_sauce'],
 'a': ['xoanodera_amoena', 'xoan_paredes', 'xoan_singing', 'xoana_iacoi'],
 'b': ['xobdo.org', 'xobando', 'xobotos', 'xobni', 'xobc'],
 'c': ['xochicuicatl_cuecuechtli',
       'xochiquetzal_candelaria',
       'xochicalco_university',
       'xocchel_municipality',
       'xocav@nd,_aghjabadi',
       'xochitl_castaneda',
       'xochitl_gonzalez',
       'xochitl_escobedo',
       'xocali,_khojaly',
       'xocali,_salyan',
       'xochitl_hamada',
       'xochitl_ugarte',
       'xoco_language',
       "xocia's_dance",
       'xochitl_gomez',
       'xochi_birch',
       'xoc_dia'],
 'd': ['xodus', 'xod'],
 'e': ['xoes_egeria'],
 'g': ['xogoi_momo'],
 'h': ['xohana_torres'],
 'i': ['xoi'],
 'j': ['xojane', 'xojo'],
 'k': ['xokonoschtletl_gomora', 'xokleng_language'],
 'l': ['xolile_tshabalala',
       'xolelwa_nhlabatsi',
       'xolotrema_notata',
       'xoliswa_sithole',
       'xolisile_qayiso',
       'xolani_sotashe',
       'xolo_mariduena',
       'xolane_shongwe',
       'xolani_mahlaba',
       'xolani_mlambo',
       'xoliswa_mtose',
       'xolani_dlwati',
       'xolile_nqatha',
       'xol_qarabucaq',
       'xol_qaraqasli',
       'xolani_maholo',
       'xolani_ngwezi',
       'xolobeni_mine',
       'xolani_mdaki',
       'xolile_yawa',
       'xoli_zondi',
       'xola_nqola',
       'xola_petse'],
 'm': ['xom_materials'],
 'n': ['xonboury_district',
       'xongmai_township',
       'xonotla,_puebla',
       'xonqa_district',
       'xong_language',
       'xon_district',
       'xona_games',
       'xonxa_dam'],
 'o': ['xoom_corporation'],
 'p': ['xop'],
 'r': ['xorides_praecatorius',
       'xorides_corcyrensis',
       'xorides_propinquus',
       'xorides_filiformis',
       'xorides_fuligator',
       'xorides_irrigator',
       'xorides_calidus',
       'xorides_rufipes',
       'xorazm_stadium',
       'xorge_carrillo',
       'xorides_niger',
       'xorazm_region',
       'xorides_ater',
       'xor_cipher',
       'xor_ddos',
       'xor_gate'],
 's': ['xoscobanli,_masally',
       'xoscobanli,_imishli',
       'xosefa_xovellanos',
       'xosha_roquemore',
       'xosayen_yamasev',
       'xoser_astonyx',
       'xoser_exors',
       'xos_webtop'],
 't': ['xota_fs'],
 'u': ['xout_lao'],
 'v': ['xovos_district'],
 'w': ['xowa'],
 'x': ['xoxocotla,_veracruz',
       'xoxocotla,_morelos',
       'xox-theater_kleve',
       'xoxo_exo'],
 'y': ['xoybun', 'xoylu', 'xoyo'],
 'z': ['xozavi']}
