
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xp = {'_': ['xp11.2_duplication',
       'xp-class_lifeboat',
       'xp_school',
       'xp_power',
       'xp_inc.'],
 'a': ['xpat_magazine',
       'xpand_rally',
       'xpanse_cgi',
       'xpath_2.0',
       'xpand_3d',
       'xpath_3'],
 'b': ['xpb'],
 'c': ['xpcc_uav'],
 'd': ['xpdl', 'xpdf', 'xpd'],
 'e': ['xpec_entertainment',
       'xpect_discounts',
       'xperience_days',
       'xperia_play',
       'xpeng_g3',
       'xpeng_p5',
       'xpel_225',
       'xpeng_g9',
       'xpeng_p7'],
 'f': ['xpf'],
 'g': ['xpg'],
 'h': ['xphos'],
 'i': ['xpinstall', 'xpilot', 'xpidl', 'xpic'],
 'l': ['xplore_technologies',
       'xplor_international',
       'xplorer_ultraflight',
       'xploration_station',
       'xplorer_motorhomes',
       'xplorasia_airways',
       'xploding_plastix',
       'xplode_magazine',
       'xplorer_xflyer',
       'xplm_publisher',
       'xplore_dundee',
       'xpl_protocol',
       'xplore_g18',
       'xplorer_xs',
       'xplore_m98'],
 'm': ['xpm'],
 'n': ['xpnpep1', 'xpnpep2', 'xpnpep3', 'xpn'],
 'o': ['xpo_logistics'],
 'p': ['xpp'],
 'q': ['xpq-21'],
 'r': ['xpress_motorsports',
       'xpress_technology',
       'xpress_telecom',
       'xpression_fm',
       'xpress_3200',
       'xpress_air',
       'xpress_pro',
       'xpress_200'],
 's': ['xps_annotator'],
 't': ['xpt'],
 'u': ['xpu_ha'],
 'w': ['xpw_arena']}
