
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xt = {'_': ['xt_group'],
 'a': ['xtatic_truth'],
 'b': ['xtbs', 'xtb'],
 'c': ['xtc_discography'],
 'e': ['xterra_triathlon',
       'xte_j1650-500',
       'xte_j1739-285',
       'xte_j1550-564',
       'xte_j1118+480',
       'xtended_play'],
 'f': ['xtf'],
 'i': ['xtian_dela'],
 'm': ['xtm-cat', 'xtm'],
 'n': ['xtnct', 'xtnd'],
 'o': ['xto_energy'],
 'p': ['xtp'],
 'r': ['xtraordinary_people',
       'xtract_resources',
       'xtreme_triathlon',
       'xtreme_skyflyer',
       'xtra_vancouver',
       'xtra-acme_usa',
       'xtrac_limited',
       'xtreme_racing',
       'xtra_magazine',
       'xtreem_music',
       'xtreme_waste',
       'xtream_arena',
       'xtreme_swing',
       'xtra_ottawa',
       'xtreme_4x4',
       'xtra_bass',
       'xtra_heat',
       'xtra_am'],
 's': ['xts-400', 'xtsr', 'xts'],
 'u': ['xtuple', 'xtube', 'xtul'],
 'v': ['xtv'],
 'x': ['xtx_markets']}
