
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bw = {'_': ['bw-723c86', 'bw284c51', 'bw373u86', 'bw-a444'],
 'a': ['bwamiramira',
       'bwanabwana',
       'bwakira',
       'bwawani',
       'bwakaw',
       'bwalya',
       'bwaise',
       'bwatue',
       'bwari',
       'bwaa',
       'bwa'],
 'b': ['bwb'],
 'c': ['bwca', 'bwc'],
 'e': ['bweyogerere',
       'bweremana',
       'bwenieve',
       'bweeng',
       'bweiti',
       'bwejuu',
       'bwende',
       'bweni',
       'bwe'],
 'f': ['bwf'],
 'g': ['bwgcolman', 'bwg'],
 'h': ['bwhs', 'bwh'],
 'i': ['bwizibwera', 'bwisagu', 'bwindi', 'bwiam', 'bwiti', 'bwin', 'bwi'],
 'j': ['bwj'],
 'k': ['bwk'],
 'l': ['bwlch-y-ddeufaen',
       'bwlch-y-cibau',
       'bwlchygroes',
       'bwlchyfadfa',
       'bwlchgwyn',
       'bwlch',
       'bwl'],
 'n': ['bwn'],
 'o': ['bwool', 'bwog', 'bwo'],
 'p': ['bwp-2000', 'bwping', 'bwps', 'bwp'],
 'q': ['bwq'],
 'r': ['bwrx-300'],
 's': ['bws'],
 't': ['bwt'],
 'u': ['bwu'],
 'w': ['bww']}
