def ssd_post_process(results, image, confidence_level): ...
def ssd_flat_post_process(results, image, confidence_level): ...
def ssd_trt_post_process(predictions, image, confidence_level): ...
def yolo_post_process(detections, image, confidence_level, overlap_threshold): ...
def yolo_trt_post_process(results, image, confidence_level, overlap_threshold): ...
