
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-25T23:05:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "faed1a8f49d4112d24350e69f68baaac9b62ece5",
 "version": "0.2.26.post0.dev34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
