
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yn = {'_': ['yn_chruinnaght', 'yn_lhaihder', 'yn_tephra', 'yn_jay'],
 'a': ['ynares_center', 'ynav_bosseba'],
 'd': ['yndiara_asp', 'yndys_novas', 'yndi_halda'],
 'e': ['ynez_johnston', 'ynez_seabury', 'ynes_mexia'],
 'g': ['yngvar_fredriksen',
       'yngve_stiernspetz',
       'yngvar_sonnichsen',
       'yngwie_malmsteen',
       'yngve_zotterman',
       'yngve_slyngstad',
       'yngve_slettholm',
       'yngve_johansson',
       'yngvar_hakonsen',
       'yngve_liljeberg',
       'yngve_wahlander',
       'yngve_lindqvist',
       'yngve_hagensen',
       'yngvar_tornros',
       'yngvar_nielsen',
       'yngvild_ingels',
       'yngve_casslind',
       'yngve_holmberg',
       'yngve_karlsson',
       'yngve_engkvist',
       'yngve_nordwall',
       'yngvar_karlsen',
       'yngve_andersen',
       'yngve_brilioth',
       'yngve_lindgren',
       'yngvar_ustvedt',
       'yngve_ekstrand',
       'yngve_ekstrom',
       'yngsjo_murder',
       'ynglinga_saga',
       'yngve_larsson',
       'yngve_johnson',
       'yngvar_lochen',
       'yngve_karlsen',
       'yngve_wieland',
       'yngve_hackner',
       'yngvar_hauge',
       'yngvar_hagen',
       'yngve_pacius',
       'yngve_gamlin',
       'yngve_hallen',
       'yngvar_barda',
       'yngve_viebke',
       'yngwe_elstak',
       'yngvar_numme',
       'yngve_saetre',
       'yngve_skold',
       'yngve_stoor',
       'yngvar_fyhn',
       'yngve_kalin',
       'yngve_lundh',
       'yngvar_bryn',
       'yngve_brodd',
       'yngve_holm',
       'yngve_moe'],
 'h': ['ynhanfu'],
 'i': ['ynigo', 'yniol'],
 'k': ['ynk_interactive', 'ynk_korea'],
 'n': ['ynnakh_mountain', 'ynna_asistio'],
 'o': ['ynot_studios', 'ynon_kreiz'],
 'p': ['ynp'],
 'r': ['ynr_productions'],
 's': ['ynso_scholten'],
 't': ['yntymak'],
 'u': ['ynu'],
 'w': ['ynw_melly'],
 'y': ['ynyscedwyn_ironworks',
       'ynysangharad_park',
       'ynysygerwn_f.c.',
       'ynys_llanddwyn',
       'ynys_tachwedd',
       'ynysybwl_rfc',
       'ynys_castell',
       'ynys_lochtyn',
       'ynys_gifftan',
       'ynys_moelfre',
       'ynys_benlas',
       'ynysddu_rfc',
       'ynys_faelog',
       'ynys_feurig',
       'ynys_dulas',
       'ynys_gaint',
       'ynys_uchaf',
       'ynys_bery',
       'ynys_mon']}
