
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ym = {'_': ['ym_biosciences', 'ym-iii_mine'],
 'a': ['ymadawiad_arthur',
       'ymar_abdrahim',
       'ymar_daher',
       'yma_sumac',
       'ymar_sali'],
 'c': ['ymca-democrat_building',
       'ymc_entertainment',
       'ymca_philadelphia',
       'ymca_college',
       'ymca_boston',
       'ymca_press',
       'ymca_f.c.'],
 'e': ['ymer_deliallisi',
       'ymer_dishnica',
       'ymer_prizreni',
       'ymer_pampuri',
       'ymer_xhaferi',
       'ymer_island',
       'ymer_saraci',
       'ymer_shaba',
       'yme_field'],
 'f': ['ymfc'],
 'g': ['ymg'],
 'i': ['ymir_vigfusson', 'ymiysky_range', 'ymir_mountain', 'ymi_jeans'],
 'k': ['ymkje_clevering'],
 'l': ['yml'],
 'm': ['ymmo', 'ymm'],
 'o': ['ymonville', 'ymobile', 'ymodem', 'ymo'],
 'p': ['ymp_file'],
 's': ['yms-1-class_minesweeper'],
 't': ['ymt'],
 'u': ['ymusic'],
 'y': ['ymyyakhtakh_culture']}
