
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ej = {'_': ['ej,_sudbino',
       'ej_johnson',
       'ej_manuel',
       'ej_dimera',
       'ej_laure',
       'ej_hill',
       'ej_onu'],
 'a': ['ejaculatory_dysfunction',
       'ejaculation_disorders',
       'ejaculatory_prayer',
       'ejaculatory_duct',
       'ejaz_lakdawala',
       'ejaz_chaudhary',
       'ejajul_islam',
       'ejaz_durrani',
       'ejan_mackaay',
       'ejan,_ghana',
       'ejaz_yousaf',
       'ejaz,_idlib',
       'ejaz_qaiser',
       'ejay_falcon',
       'ejaz_khan',
       'ejay_day',
       'ejaz_ali'],
 'b': ['ejby_municipality', 'ejbar_kola', 'ejb_ql'],
 'c': ['ejc'],
 'd': ['ejdabrine', 'ejdus'],
 'e': ['ejective-contour_click',
       'ejective_consonant',
       'ejection_fraction',
       'ejegayehu_dibaba',
       'ejercito_grande',
       'ejection_charge',
       'ejercito_family',
       'ejegod_windmill',
       'ejective_click',
       'ejecta_blanket',
       'ejer_bavnehoj',
       'ejection_seat',
       'ejector_seat',
       'eje_comunero',
       'ejersa_goro',
       'eje_central',
       'eje_thelin',
       'ejembi_eko',
       'ejei_khan',
       'eje_oberg',
       'eje_vial',
       'eje_elgh',
       'ejen_016',
       'ejen_ali'],
 'f': ['ejf'],
 'g': ['ejgil_clemmensen', 'ejgayehu_taye'],
 'h': ['ejhl_south'],
 'i': ['ejima-ikushima_affair',
       'ejinhoro_formation',
       'ejin-hami_railway',
       'ejido,_venezuela',
       'ejikeme_ikwunze',
       'ejido_erendira',
       'ejike_ugboaja',
       'ejima_station',
       'ejike_uzoenyi',
       'ejigbo,_lagos',
       'ejiri_station',
       'ejike_asiegbu',
       'ejido_valdez',
       'ejiro_evero',
       'ejiro_kuale',
       'ejin_banner'],
 'l': ['ejler_jakobsson',
       'ejlif_krogager',
       'ejlert_bjerke',
       'ejler_allert',
       'ejler_bille'],
 'n': ['ejnar_hertzsprung',
       'ejner_federspiel',
       'ejner_johansson',
       'ejnar_mikkelsen',
       'ejner_augsburg',
       'ejnar_andersen',
       'ejnar_jacobsen',
       'ejnar_tonsager',
       'ejnar_fischer',
       'ejnar_nielsen',
       'ejnar_knudsen',
       'ejnar_levison',
       'ejnar_sylvest',
       'ejnar_hansen',
       'ejnar_emborg',
       'ejner_jensen',
       'ejnar_olsson',
       'ejner_larsen',
       'ejner_hansen',
       'ejnar_dyggve',
       'ejnar_jensen'],
 'o': ['ejovi_nuwere'],
 'p': ['ejpovice', 'ejp'],
 's': ['ejszakai_orszagut'],
 't': ['ejt'],
 'u': ['ejutla,_jalisco',
       'ejutla_district',
       'ejura_shooting',
       'ejuan_price',
       'ejup_ganic'],
 'v': ['ejvind_pedersen', 'ejvind_hansen', 'ejvind_blach'],
 'w': ['ejw'],
 'y': ['ejya_yadav']}
