
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_eh = {'_': ['eh,_cumpari!',
       'eh_phuthong',
       'eh_aalborg',
       'eh_bildu',
       'eh_joe',
       'eh_hee'],
 'a': ['eharius_marzhaniani',
       'eharius_hermonensis',
       'eharius_hymetticus',
       'eharius_kuznetzovi',
       'eharius_chergui',
       'eharius_kostini',
       'ehart,_virginia',
       'ehab_abouheif',
       'ehagay_nakoda',
       'eha_lattemae',
       'ehab_mohamed',
       'ehab_tawfik',
       'eharo_mask',
       'ehab_galal',
       'eha_tanger',
       'ehab_amin',
       'eha_runne',
       'eha_amufu',
       'eha_parn'],
 'b': ['ehb'],
 'c': ['ehc_bregenzerwald',
       'ehc_klostersee',
       'ehc_winterthur',
       'ehc_hoensbroek',
       'ehc_freiburg',
       'ehc_lustenau',
       'ehc_dortmund',
       'ehc_neuwied',
       'ehc_kloten',
       'ehc_arosa',
       'ehc_olten',
       'ehc_basel',
       'ehc_visp',
       'ehc_chur',
       'ehc_biel'],
 'd': ['ehden_massacre'],
 'e': ['ehelepola_walauwa',
       'ehealth_exchange',
       'ehelepola_nilame',
       'ehesache_lorenz',
       'ehealth_ontario',
       'ehe_chant'],
 'f': ['ehf'],
 'g': ['ehg'],
 'h': ['ehhadh', 'ehhs'],
 'i': ['ehirovipuka_conservancy',
       'ehinomen_ehikhamenor',
       'ehime_broadcasting',
       'ehingen_urspring',
       'ehime_university',
       'ehime_prefecture',
       'ehinabo_omoighe',
       'ehingen,_swabia',
       'ehire_adrianza',
       "ehi's_bitters",
       'ehime_mbano',
       'ehime_fc'],
 'l': ['ehlers-geren-sachs_theorem',
       'ehlers-danlos_syndromes',
       'ehlers-danlos_society',
       'ehl,_bas-rhin',
       'ehlers_group',
       'ehlers_knob',
       'ehler,_iowa',
       'ehlo_huang',
       'ehl_wolves'],
 'm': ['ehmetjan_qasim',
       'ehmej_festival',
       'ehmede_xasi',
       'ehmm_theory',
       'ehmede_xani',
       'ehm_welk'],
 'n': ['ehndorf_transmitter'],
 'o': ['ehoron.com', 'ehostela', 'eholmen', 'eholt', 'ehome', 'ehow', 'eho'],
 'p': ['ehp'],
 'r': ['ehrenfeucht-mycielski_sequence',
       'ehrenfeucht-mostowski_theorem',
       'ehrlichsche_gestiftskirche',
       'ehrenskold-class_destroyer',
       'ehrendorferia_chrysantha',
       'ehrenbreitstein_fortress',
       'ehrenfeucht-fraisse_game',
       'ehrendorferia_ochroleuca',
       'ehrenfest-tolman_effect',
       'ehrenfeld,_pennsylvania',
       'ehrenfried-oskar_boege',
       'ehrwalder_sonnenspitze',
       'ehrenpreis_conjecture',
       'ehrlichia_chaffeensis',
       'ehrlichia_ruminantium',
       'ehrlichsches_gestift',
       'ehresmann_connection',
       'ehrenberg,_thuringia',
       'ehringsdorf_remains',
       'ehrlich,_washington',
       'ehrenfried_pfeiffer',
       'ehrmandale,_indiana',
       'ehrenfest_equations',
       'ehrenstein_illusion',
       'ehrismann_residence',
       'ehretia_microphylla',
       'ehrenfried_rudolph',
       'ehrhart_polynomial',
       'ehrenfeld,_cologne',
       'ehrenberg,_arizona',
       'ehrengard_schramm',
       'ehrenfest_paradox',
       "ehrlich's_reagent",
       "ehresmann's_lemma",
       'ehrlichia_ewingii',
       'ehreshoven_castle',
       'ehretia_acuminata',
       'ehretia_dicksonii',
       'ehrenfest_theorem',
       'ehretia_tinifolia',
       'ehrenfried_patzel',
       'ehrharta_calycina',
       'ehrenburg_palace',
       'ehrenfels_castle',
       'ehrenberg_island',
       'ehrenberg,_hesse',
       'ehren_wassermann',
       'ehren_earleywine',
       'ehrenberg_castle',
       'ehrharta_erecta',
       'ehrick_rossiter',
       'ehrhardt_heller',
       'ehrenfest_model',
       "ehrling's_lemma",
       'ehrenfeld_group',
       'ehretia_saligna',
       'ehrlichia_canis',
       'ehrhart_neubert',
       'ehrman_mitchell',
       'ehrlichia_muris',
       'ehrhard_schmidt',
       'ehrhardt_e-v/4',
       'ehron_vonallen',
       'ehren_mcghehey',
       'ehrang_station',
       'ehretia_anacua',
       'ehretia_rigida',
       'ehretia_cymosa',
       'ehretia_laevis',
       'ehren_painter',
       'ehrhardt_post',
       'ehrhardt_koch',
       'ehren_watada',
       'ehr,_germany',
       'ehretia_alba',
       'ehren_kruger'],
 's': ['ehsan-ul-haque_chaudhry',
       'ehsan-ul-haq_piracha',
       'ehsan_naghibzadeh',
       'ehsan_peighambari',
       'ehsan_alvanzadeh',
       'ehsanullah_ehsan',
       'ehsan_rouzbahani',
       'ehsanul_sadequee',
       'ehsan_abdelmalek',
       'ehsaas_programme',
       'ehsan_khorsandi',
       'ehsanullah_reki',
       'ehsan_yarshater',
       'ehsan_alikhani',
       'ehsan_fatahian',
       'ehsan_moradian',
       'ehsan_hosseini',
       'ehsaan_noorani',
       'ehsan_pahlavan',
       'ehsan_lashgari',
       'ehsan_khandozi',
       'ehsan_naraghi',
       'ehsan_afshari',
       'ehsan_haddadi',
       'ehsan_pirhadi',
       'ehsan_hajsafi',
       'ehsanul_haque',
       'ehsan_mehrabi',
       'ehs_institute',
       'ehsan_zaffar',
       'ehsan_square',
       'ehsan_danish',
       'ehsan_tabari',
       'ehsan_masood',
       'ehsham,_fars',
       'ehsan_amini',
       'ehsan_nawaz',
       'ehsan_latif',
       'ehsan_jafri',
       'ehsan_bayat',
       'ehsan_hoque',
       'ehsan_khan',
       'ehsan_jami',
       'ehsan_adil',
       'ehsan_abdi',
       'ehsan_wyne',
       'ehsan_aman',
       'ehsan_mani',
       'ehs_today'],
 't': ['ehtiram_shahverdiyev', 'ehtuish_ehtuish'],
 'u': ['ehueun_language',
       'ehud_hrushovski',
       'ehud_goldwasser',
       'ehud_ben-tovim',
       'ehud_havazelet',
       'ehud_tenenbaum',
       'ehud_rassabi',
       'ehud_asherie',
       'ehud_shapiro',
       'ehud_avriel',
       'ehud_rogers',
       'ehud_olmert',
       'ehud_sheleg',
       'ehud_netzer',
       'ehud_banai',
       'ehud_barak',
       'ehud_gazit',
       'ehud_kalai',
       'ehud_yatom',
       'ehud_manor',
       'ehud_shani',
       'ehud_ettun',
       'ehud_yaari',
       'ehud_adiv',
       'ehud_vaks',
       'ehud_gol'],
 'v': ['ehvin_sasidharan'],
 'w': ['ehweiler', 'ehwaz'],
 'y': ['ehya_night']}
