
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tc = {'_': ['tc-class_blimp',
       'tc_television',
       'tc_electronic',
       'tc10_protein',
       'tc_pipelines',
       'tc/2.4_mine',
       'tc_clements',
       'tc_kisting',
       'tc_robati',
       'tc_energy',
       'tc_mouras',
       'tc-s_7001',
       'tc_group',
       'tc_matic',
       'tc_elima',
       'tc_pista',
       'tc_smith',
       'tc_lin',
       'tc_huo'],
 'a': ['tca_volleyball',
       'tca_raghavan',
       'tca_college',
       'tca_ground',
       'tca_awards'],
 'b': ['tcb_band'],
 'c': ['tccb_open'],
 'd': ['tcdd_tasimacilik',
       'tcdd_de18100',
       'tcdd_ht80000',
       'tcdd_de36000',
       'tcdd_dh44100',
       'tcdd_tvs2000',
       'tcdd_de22000',
       'tcdd_de20000',
       'tcdd_dh11500',
       'tcdd_dh33100',
       'tcdd_de21500',
       'tcdd_de24000',
       'tcdd_dh27000',
       'tcdd_de11000',
       'tcdd_ht65000',
       'tcdd_de18000',
       'tcdd_dm15000',
       'tcdd_de33000',
       'tcdd_mt5200',
       'tcdd_e23000',
       'tcdd_mt5700',
       'tcdd_dh6500',
       'tcdd_mt5600',
       'tcdd_dh3600',
       'tcdd_e32000',
       'tcdd_e68000',
       'tcdd_dh9500',
       'tcdd_e14000',
       'tcdd_mt5400',
       'tcdd_mt5300',
       'tcdd_dh4100',
       'tcdd_dh6000',
       'tcdd_mt5500',
       'tcdd_dh7000',
       'tcdd_e8000'],
 'e': ['tcelna', 'tceal4', 'tceal1', 'tcea1', 'tcea2', 'tcell', 'tcep', 'tce'],
 'f': ['tcf/lef_family', 'tcf_bank'],
 'g': ['tcg_degirmendere',
       'tcg_sultanhisar',
       'tcg_dumlupinar',
       'tcg_demirhisar',
       'tcg_heybeliada',
       'tcg_burgazada',
       'tcg_hizirreis',
       'tcg_kinaliada',
       'tcg_gelibolu',
       'tcg_bozcaada',
       'tcg_buyukada',
       'tcg_muavenet',
       'tcg_kocatepe',
       'tcg_alemdar',
       'tcg_anadolu',
       'tcg_atilay',
       'tcg_gayret'],
 'h': ['tchangmargarya_yangtsunghaiensis',
       'tchangmargarya_multilabiata',
       'tchintabaraden_department',
       'tchirozerine_department',
       "tchernetzov's_partisans",
       'tchorznica_wloscianska',
       'tchorznica_szlachecka',
       'tchoutacabouffa_river',
       'tchimpounga_sanctuary',
       'tchoupitoulas_street',
       'tchaoudjo_prefecture',
       'tchernichovsky_prize',
       'tchicala_tcholohanga',
       'tchongorove_airport',
       'tchikapika_district',
       'tchula,_mississippi',
       'tcheriba_department',
       'tchamba_prefecture',
       'tchumbuli_language',
       'tchepone_operation',
       'tchami_discography',
       'tchibanga_airport',
       'tchitchao_tchalim',
       'tchakala_tchanile',
       'tchavdar_georgiev',
       'tchadia_airlines',
       'tchaikazan_river',
       'tchavolo_schmitt',
       'tchiressoua_guel',
       'tchefuncte_river',
       'tchien_district',
       'tchaiko_kwayana',
       'tchitchide_tare',
       'tchefuncte_site',
       'tchale_figueira',
       'tchagen_airport',
       'tchorek_plaques',
       'tchoung_ta-chen',
       'tcheng_yu-hsiu',
       'tchien_airport',
       'tchupala_falls',
       'tchidi_chikere',
       'tchabal_nganha',
       'tchamba_river',
       'tchula_period',
       'tchiss_lopes',
       'tchan_fou-li',
       'tcheky_karyo',
       'tchaoudjo_ac',
       "tcham_n'toya",
       'tchiki_boum',
       'tchessa_abi',
       'tchad_blake',
       'tchula_lake',
       'tche_music',
       'tche_tche'],
 'i': ['tcirg1', 'tcim', 'tci'],
 'j': ['tcj'],
 'k': ['tck'],
 'l': ['tcl_electronics', 'tcl_technology', 'tclr_argadeen', 'tcl_classic'],
 'm': ['tcm_underground', 'tcm_movies'],
 'n': ['tcn_protocol', 'tcnj_lions'],
 'o': ['tco_certified', 'tco_boeny'],
 'p': ['tcp/ip_illustrated',
       'tcp_acceleration',
       'tcp_half-open',
       'tcp_westwood',
       'tcp_wrappers',
       'tcp_stealth',
       'tcp_pacing',
       'tcp_tuning',
       'tcp_fusion',
       'tcp_vegas'],
 'q': ['tcq'],
 'r': ['tcr_international'],
 's': ['tcs_china', 'tcs_bancs', 'tcs_daily'],
 't': ['tct_kids'],
 'u': ['tcu_diamond', 'tcu_place'],
 'v': ['tcv_suja'],
 'w': ['tcw_group', 'tcw_tower'],
 'x': ['tcx_technology'],
 'z': ['tczewskie_laki', 'tczew_county']}
