
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tl = {'_': ['tl-ultralight_stream',
       "tl'azt'en_nation",
       'tl_tradewinds',
       'tl_forsberg',
       'tl_9000'],
 'a': ['tlaxcala-puebla_nahuatl',
       'tlahualilo_municipality',
       'tlalnepantla_cathedral',
       'tlaxcala_municipality',
       'tlalnepantla,_morelos',
       'tlatlasikwala_nation',
       'tlacotepec_meteorite',
       'tlachichilco_tepehua',
       'tlalnepantla_region',
       'tlacolulita_zapotec',
       'tlatelolco_massacre',
       'tlahuitoltepec_mixe',
       'tlaxco_municipality',
       'tlacolula_district',
       'tlaxcala_territory',
       'tlaxiaco_district',
       'tlacotepec_plumas',
       'tlapanec_language',
       'tlatilco_culture',
       'tlake,_grosuplje',
       'tlayua_formation',
       "tla'amin_nation",
       'tlatet_eddouair',
       'tlapaneco_river',
       'tlapanec_people',
       'tlake,_rogatec',
       'tlaka,_litija',
       'tla_releasing',
       'tlachene_cove',
       'tlaxcala_city',
       'tlaxcala_f.c.',
       'tlaloc_ii-tc',
       'tlaloc_rivas',
       'tladi_bokako',
       'tlawng_dam',
       'tlair_uav'],
 'b': ['tlbleed', 'tlb'],
 'c': ['tlc_discography', 'tlc_norway', 'tlc_arabia', 'tlc_books', 'tlc_camp'],
 'd': ['tld_systems', 'tldr_pages'],
 'e': ['tlepolemus_puerulus',
       'tlepolemus_pilosus',
       'tlemcen_province',
       'tlell_river'],
 'f': ['tlf'],
 'g': ['tlgadintsi', 'tlg'],
 'h': ['tlhalosang_molapisi'],
 'i': ['tliltocatl_albopilosus',
       'tliltocatl_kahlenbergi',
       'tliltocatl_epicureanus',
       'tliltocatl_schroederi',
       'tliltocatl_aureoceps',
       'tliltocatl_sabulosus',
       'tliltocatl_alvarezi',
       'tliltocatl_verdezi',
       'tliltocatl_andrewi',
       'tlicho_government',
       'tliltocatl_vagans',
       'tlingit_language',
       'tlingit_alphabet',
       'tlikakila_river',
       'tlingit_cuisine',
       'tlingit_clans',
       'tlingit_noun'],
 'j': ['tlj'],
 'k': ['tlk2', 'tlk1', 'tlk'],
 'l': ['tll2', 'tlli', 'tll1', 'tll'],
 'm': ['tlmace', 'tlm'],
 'n': ['tln-europa', 'tlnovelas', 'tln2', 'tln1', 'tln'],
 'o': ['tlokinia_koscielna',
       'tlokoeng_airport',
       'tlowitsis_nation',
       'tlokinia_wielka',
       'tlotlo_tsamaase',
       'tlou_molekwane',
       'tlosaih_people',
       'tlokinia_mala',
       'tlou_segolela',
       'tlokwe_ruins',
       'tlokwa_tribe',
       'tlot_tlot'],
 'p': ['tlpa', 'tlp'],
 'q': ['tlqp-62'],
 'r': ['tlr_1'],
 's': ['tls_acceleration'],
 't': ['tlt_llp'],
 'u': ['tluanghup_thang', 'tlumach_raion'],
 'v': ['tlv_mirror'],
 'w': ['tlw'],
 'x': ['tlx1', 'tlx2', 'tlx3', 'tlx'],
 'y': ['tlyaratinsky_district'],
 'z': ['tlz']}
