
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tj = {'_': ['tj_maguranyanga',
       'tj_gottwaldov',
       'tj_waldburger',
       'tj_tollakson',
       'tj_neubauer',
       'tj_perenara',
       'tj_trinidad',
       'tj_schiller',
       'tj_galiardi',
       'tj_lubinsky',
       'tj_sakaluk',
       'tj_bramble',
       'tj_sanders',
       'tj_rovinka',
       'tj_ashford',
       'tj_mccloud',
       'tj_ducklo',
       'tj_friedl',
       'tj_faiane',
       'tj_fisher',
       'tj_hassan',
       'tj_moncur',
       'tj_starks',
       'tj_norris',
       'tj_morris',
       'tj_straza',
       'tj_nyman',
       'tj_liner',
       'tj_house',
       'tj_eyoma',
       'tj_cases',
       'tj_ioane',
       'tj_davis',
       'tj_klune',
       'tj_curry',
       'tj_desna',
       'tj_goree',
       'tj_imel',
       'tj_maxx',
       "tj_va'a",
       'tj_dawe',
       'tj_kirk',
       'tj_cox'],
 'a': ['tjakrabirawa_regiment',
       "tjandamurra_o'shane",
       'tjalling_halbertsma',
       'tjaereborg,_denmark',
       'tjalling_waterbolk',
       'tjakkatjakka_ston',
       'tjalling_koopmans',
       'tjabel_boonstra',
       'tjalie_robinson',
       'tjaak_pattiwael',
       'tjampuhan_hotel',
       'tjama_tjivikua',
       'tjalf_sparnaay',
       'tjasa_kysselef',
       'tjasa_jezernik',
       'tjaynera_falls',
       'tjayanka_woods',
       'tjasse_glacier',
       'tjapko_poppens',
       'tjaart_marais',
       'tjahjo_kumolo',
       'tjaronn_chery',
       'tjallie_james',
       'tjasa_srimpf',
       'tjaarke_maas',
       'tjasa_tibaut',
       'tjasa_stanko',
       'tjasa_pintar',
       'tjasa_rudman',
       'tjasa_ristic',
       'tjasa_kokalj',
       'tjasa_rutar',
       'tjark_evers',
       'tjambuk_api',
       'tjasa_vozel',
       'tjade_groot',
       'tjala_arts',
       'tjasa_iris',
       'tjasa_oder',
       'tjasa_seme'],
 'c': ['tjc'],
 'd': ['tjd'],
 'e': ['tjeertje_bergers-duif',
       'tjele_municipality',
       'tjeerd_oosterhuis',
       'tjeldsund_bridge',
       'tjerk_westerterp',
       'tjeldsund_church',
       'tjensvoll_church',
       'tjerk_vermaning',
       'tjeerd_westdijk',
       'tjeerd_borstlap',
       'tjenare_kungen',
       'tjeerd_bottema',
       'tjeerd_boersma',
       'tjerk_leegstra',
       'tjerk_bottema',
       'tjekero_tweya',
       'tjerk_smeets',
       'tjeerd_pasma',
       'tjeerd_korf',
       'tje_austin'],
 'f': ['tjf'],
 'h': ['tjhoen_tjhioe'],
 'i': ['tjipto_mangoenkoesoemo',
       'tjirrkarli_community',
       'tjipekapora_herunga',
       'tjin-a-djie_family',
       'tjitske_reidinga',
       'tjitske_siderius',
       'tjibbe_veldkamp',
       'tjitte_weistra',
       'tjioeng_wanara',
       'tjipee_murangi',
       'tjibbe_joustra',
       'tjiuee_uanivi',
       'tjimba_people',
       'tjipke_visser',
       'tjiu_mau-ying',
       'tjitze_baarda',
       'tjilik_riwut'],
 'l': ['tjl_motorsports'],
 'm': ['tjm'],
 'o': ['tjongsfjorden_church',
       'tjorn_municipality',
       'tjoloholm_castle',
       'tjostolv_moland',
       'tjong,_nordland',
       'tjotta_church',
       'tjol_lategan',
       'tjorn_bridge',
       'tjorring_if',
       'tjome_radio',
       'tjorn_sibma',
       'tjorn_runt'],
 'p': ['tjp3', 'tjp'],
 'r': ['tjr'],
 's': ['tjs'],
 'u': ['tjuntjuntjara_community',
       'tjunkiya_napaltjarri',
       'tjukayirla_roadhouse',
       'tjuvholmen,_hedmark',
       'tjurunga_paroculus',
       'tjukurla_community',
       'tjurko_bracteates',
       'tjuvholene_crags',
       'tjunkaya_tapaya',
       'tjupan_dialect',
       'tjuroro_people',
       'tjuvarnas_jul',
       'tjungkara_ken',
       'tjugum_church',
       'tjut_djalil',
       'tjupi_band',
       'tjun_tjun',
       'tjust_if',
       'tju_uav'],
 'v': ['tjvjik'],
 'w': ['tjwao_dialect'],
 'x': ['tjx_companies'],
 'y': ['tjyllyungoo']}
