
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tb = {'_': ['tb/fc_suduroy/royn',
       'tb10cs1h3_snorna',
       'tb11cs4h1_snorna',
       'tb11cs5h3_snorna',
       'tb10cs2h1_snorna',
       'tb11cs3h1_snorna',
       'tb10cs5h2_snorna',
       'tb10cs3h1_snorna',
       'tb10cs4h1_snorna',
       'tb10cs3h2_snorna',
       'tb10cs1h2_snorna',
       'tb11cs2h1_snorna',
       'tb10cs5h1_snorna',
       'tb10cs2h2_snorna',
       'tb10cs4h3_snorna',
       'tb11cs4h3_snorna',
       'tb11cs5h1_snorna',
       'tb11cs3h2_snorna',
       'tb11cs4h2_snorna',
       'tb10cs4h2_snorna',
       'tb10cs4h4_snorna',
       'tb10cs5h3_snorna',
       'tb10cs1h1_snorna',
       'tb11cs5h2_snorna',
       'tb8cs2h1_snorna',
       'tb9cs4h3_snorna',
       'tb9cs3h2_snorna',
       'tb9cs6h2_snorna',
       'tb9cs1h1_snorna',
       'tb9cs1h2_snorna',
       'tb6cs1h4_snorna',
       'tb9cs4h1_snorna',
       'tb6cs1h3_snorna',
       'tb3cs2h1_snorna',
       'tb9cs2h1_snorna',
       'tb9cs1h3_snorna',
       'tb9cs3h1_snorna',
       'tb6cs1h2_snorna',
       'tb9cs2h2_snorna',
       'tb8cs4h2_snorna',
       'tb6cs2h1_snorna',
       'tb8cs4h1_snorna',
       'tb8cs3h1_snorna',
       'tb9cs4h2_snorna',
       'tb6cs1h1_snorna',
       'tb3cs2h2_snorna',
       'tb9cs6h1_snorna',
       'tb,_maryland',
       'tb_alliance',
       'tb_alert',
       'tb_191'],
 'a': ['tba_studios'],
 'b': ['tbb_pank'],
 'c': ['tbc_corporation', 'tbc_domain', 'tbc_radio', 'tbc_bank'],
 'd': ['tbd_records'],
 'e': ['tbeli_abuserisdze', 'tbe_buffer'],
 'f': ['tbf'],
 'g': ['tbg_dragons', 'tbg_ag'],
 'h': ['tbhs', 'tbh'],
 'i': ['tbilissky_district',
       'tbilisi_caucasians',
       'tbilisis_forumi',
       'tbilisi_circus',
       'tbilisi_avenue',
       'tbi_solicitors',
       'tbilisi_metro',
       'tbilisi_sea',
       'tbilisi_zoo',
       'tbi_bank',
       'tbi_plc'],
 'j': ['tbjhome', 'tbjzl', 'tbj'],
 'k': ['tbk1', 'tbk'],
 'l': ['tblghu,_nagorno-karabakh'],
 'm': ['tbmm_tv'],
 'n': ['tbn_inspire', 'tbn_salsa'],
 'o': ['tboli_language', 'tboli_people'],
 'p': ['tbp-associated_factor'],
 'q': ['tbqh'],
 'r': ['tbr21', 'tbrg1', 'tbrg4', 'tbrb', 'tbr1', 'tbri', 'tbr'],
 's': ['tbs_education', 'tbs_radio', 'tbs_gb'],
 't': ['tbtbt', 'tbt'],
 'u': ['tbu'],
 'v': ['tbvfl_neustadt-wildenheid', 'tbv_lemgo'],
 'w': ['tbwa_worldwide'],
 'x': ['tbx18_transduction'],
 'y': ['tby'],
 'z': ['tbz']}
