
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tf = {'_': ['tf2000-class_destroyer',
       'tf_algorithm',
       'tf_carrier',
       'tf-19_wasp',
       'tf1_group',
       'tf-1_cell',
       'tf1_tower',
       'tf_sport'],
 'a': ['tfap2d',
       'tfap2b',
       'tfap2a',
       'tfap2e',
       'tfap2c',
       'tfail',
       'tfap4',
       'tfaya',
       'tfam',
       'tfae',
       'tfa'],
 'b': ['tfboys', 'tfb2m', 'tfb1m', 'tfb'],
 'c': ['tfcp2', 'tfcon', 'tfcu', 'tfcd', 'tfca', 'tfc'],
 'd': ['tfdp2', 'tfdp1', 'tfdc', 'tfd'],
 'e': ['tfeb', 'tfe3', 'tfec', 'tfe'],
 'f': ['tff_cup'],
 'g': ['tfg'],
 'h': ['tfh_publications'],
 'i': ['tfi_international', 'tfi_friday'],
 'j': ['tfj'],
 'k': ['tfk'],
 'l': ['tfl_rail'],
 'm': ['tfm-4as-1', 'tfmfly', 'tfm'],
 'n': ['tfn_group'],
 'o': ['tforce_freight'],
 'p': ['tfpi2', 'tfpt', 'tfp'],
 'r': ['tfri', 'tfr'],
 's': ['tfsd', 'tfsi', 'tfs'],
 't': ['tft_racing'],
 'u': ['tfue', 'tfu'],
 'v': ['tfvc'],
 'x': ['tfx_program']}
