
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cb = {'_': ['cb-13',
       'cb30',
       'cb-1',
       'cb-4',
       'cb25',
       'cb10',
       'cb2',
       'cb1',
       'cb5',
       'cb7',
       'cb4'],
 'a': ['cbaf-fm-15',
       'cbaf-fm-5',
       'cbaft-dt',
       'cbat-dt',
       'cbaf-fm',
       'cbam-fm',
       'cbax-fm',
       'cbal-fm',
       'cbasic',
       'cbara1',
       'cbat',
       'cbal',
       'cbax',
       'cbac',
       'cba'],
 'b': ['cbbs-fm', 'cbbx-fm', 'cbbs', 'cbbc', 'cbb'],
 'c': ['cbcx-fm',
       'cbcv-fm',
       'cbct-fm',
       'cbcl-fm',
       'cbcs-fm',
       'cbc-mac',
       'cbct-dt',
       'cbc.ca',
       'cbc-2',
       'cbc2',
       'cbcm',
       'cbca',
       'cbcu',
       'cbce',
       'cbcb',
       'cbcs',
       'cbcc',
       'cbcp',
       'cbcr',
       'cbck',
       'cbcl',
       'cbcn',
       'cbct',
       'cbc'],
 'd': ['cbdq-fm',
       'cbd-dmh',
       'cbd-fm',
       'cbdc',
       'cbdb',
       'cbdo',
       'cbdi',
       'cbdn',
       'cbd'],
 'e': ['cbe-learn',
       'cbers-2b',
       'cbeebies',
       'cbers-1',
       'cbers-3',
       'cbew-fm',
       'cbet-dt',
       'cbers-4',
       'cbers-2',
       'cbe-fm',
       'cbeft',
       'cbeff',
       'cbet',
       'cbef',
       'cbea',
       'cbec',
       'cbee'],
 'f': ['cbf-fm-10',
       'cbf-fm-8',
       'cbfa2t2',
       'cbfg-fm',
       'cbfa2t3',
       'cbft-dt',
       'cbfx-fm',
       'cbf-fm',
       'cbfc',
       'cbfb',
       'cbf'],
 'g': ['cbga-fm', 'cbgb', 'cbga', 'cbg'],
 'h': ['cbht-dt', 'cbha-fm', 'cbh-fm', 'cbhs', 'cbha', 'cbhc', 'cbh'],
 'i': ['cbipes', 'cbi-fm', 'cbid', 'cbit', 'cbia', 'cbi'],
 'j': ['cbjx-fm', 'cbj800', 'cbj-fm', 'cbj'],
 'k': ['cbkft-dt',
       'cbka-fm',
       'cbkt-dt',
       'cbkf-fm',
       'cbk-fm',
       'cbkst',
       'cbkl',
       'cbkg',
       'cbka',
       'cbkj',
       'cbkn',
       'cbkr',
       'cbkm',
       'cbko',
       'cbk'],
 'l': ['cbl-mariner',
       'cbla-fm-2',
       'cblft-dt',
       'cbla-fm',
       'cblt-dt',
       'cbl-fm',
       'cbll1',
       'cblb',
       'cbln',
       'cblc',
       'cbl'],
 'm': ['cbm-cfs3',
       'cbme-fm',
       'cbmt-dt',
       'cbm-fm',
       'cbmar',
       'cbme',
       'cbms',
       'cbm'],
 'n': ['cbnt-dt', 'cbn-fm', 'cbnlt', 'cbna', 'cbnu', 'cbnd', 'cbn'],
 'o': ['cboft-dt',
       'cbox-fm',
       'cboq-fm',
       'cbof-fm',
       'cbon-fm',
       'cboystv',
       'cbot-dt',
       'cbo-fm',
       'cbonds',
       'cbocs',
       'cbot',
       'cbom',
       'cbol',
       'cboi',
       'cboq',
       'cbor',
       'cbo'],
 'p': ['cbpp', 'cbp'],
 'q': ['cbqt-fm', 'cbqr-fm', 'cbq-fm', 'cbqi', 'cbq'],
 'r': ['cbrt-dt',
       'cbrx-fm',
       'cbr-fm',
       'cbr3',
       'cbry',
       'cbrj',
       'cbrp',
       'cbr1',
       'cbre',
       'cbrh',
       'cbrt',
       'cbrd',
       'cbrl',
       'cbrm',
       'cbr'],
 's': ['cbssports.com',
       'cbsiftbec',
       'cbs-0550',
       'cbsi-fm',
       'cbs-fm',
       'cbsi',
       'cbsl',
       'cbsc',
       'cbs7',
       'cbsp',
       'cbsa',
       'cbse',
       'cbsm',
       'cbs'],
 't': ['cbtk-fm', 'cbterm', 'cbtc', 'cbtd', 'cbta', 'cbt'],
 'u': ['cbu-98/b',
       'cbuft-dt',
       'cbuf-fm',
       'cbut-dt',
       'cbux-fm',
       'cbu-75',
       'cbu-24',
       'cbu-55',
       'cbu-fm',
       'cbu-72',
       'cbuvt',
       'cbux',
       'cbus',
       'cbu'],
 'v': ['cbvt-dt',
       'cbvx-fm',
       'cbve-fm',
       'cbv-fm',
       'cbve',
       'cbvb',
       'cbvn',
       'cbvp',
       'cbvg',
       'cbvr',
       'cbvf',
       'cbva',
       'cbv'],
 'w': ['cbwft-dt',
       'cbwt-dt',
       'cbwk-fm',
       'cbw-fm',
       'cbwd2',
       'cbwd1',
       'cbwa',
       'cbwf',
       'cbwd',
       'cbw'],
 'x': ['cbxft-dt',
       'cbxt-dt',
       'cbx-fm',
       'cbx1',
       'cbx3',
       'cbx2',
       'cbx7',
       'cbx8',
       'cbxa',
       'cbx5',
       'cbx'],
 'y': ['cbyg-fm', 'cbyk-fm', 'cbyw', 'cby1', 'cbyt', 'cby'],
 'z': ['cbzf-fm', 'cbz']}
