
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cn = {'_': ['cn120-25', 'cn120-26', 'cn-group', 'cn3d', 'cn2'],
 'a': ['cnaphalocrocis',
       'cnaemidophorus',
       'cnaphostola',
       'cnanime',
       'cnausum',
       'cna938',
       'cnapan',
       'cnaem',
       'cnavt',
       'cnac',
       'cnag',
       'cnap',
       'cnam',
       'cna2',
       'cnaf',
       'cna'],
 'b': ['cnbloggercon',
       'cnblue',
       'cnbc-e',
       'cnbp',
       'cnbm',
       'cnbl',
       'cnbc',
       'cnb'],
 'c': ['cnca', 'cncp', 'cncf', 'cnc3', 'cnco', 'cnci'],
 'd': ['cndo/2', 'cndp1', 'cnda', 'cndp', 'cndd'],
 'e': ['cnesterodontini',
       'cnephaotachina',
       'cnestrognophos',
       'cnemathraupis',
       'cnemidolophus',
       'cnemidochroma',
       'cnemidophorus',
       'cneoglossidae',
       'cnemeplatiini',
       'cnephalocotes',
       'cnecidophora',
       'cnemidocarpa',
       'cnesmocarpon',
       'cnemotettix',
       'cneoroideae',
       'cnemophilus',
       'cnemidopyge',
       'cnemacantha',
       'cnemisticta',
       'cnesterodon',
       'cnemogonini',
       'cnephalodes',
       'cneorhinini',
       'cnephasitis',
       'cnephasiini',
       'cnesteboda',
       'cnemodinus',
       'cnemidaria',
       'cnemarchus',
       'cneoraceae',
       'cnemogonus',
       'cneoridium',
       'cnestidium',
       'cnemalobus',
       'cneazevca',
       'cnemaspis',
       'cnephasia',
       'cnergyico',
       'cnephidia',
       'cnesmone',
       'cnesinus',
       'cneorane',
       'cnephora',
       'cnestrum',
       'cnemides',
       'cnemolia',
       'cnemodus',
       'cnephia',
       'cnestus',
       'cnestis',
       'cneorum',
       'cnemis',
       'cnemus',
       'cnesia',
       'cnews',
       'cneru',
       'cnep',
       'cnel',
       'cnex',
       'cnet',
       'cnes',
       'cne'],
 'f': ['cnf-sr3', 'cnf'],
 'g': ['cngrid', 'cngb1'],
 'h': ['cnhs', 'cnhi', 'cnh'],
 'i': ['cnismatocentridae',
       'cnismatocentrum',
       'cnidariologist',
       'cnidariology',
       'cnissostages',
       'cnicothamnus',
       'cnismorectis',
       'cnidoscolus',
       'cnidiocarpa',
       'cnidospora',
       'cnidocyte',
       'cnidosac',
       'cnidaria',
       'cnidium',
       'cnides',
       'cnicht',
       'cnicin',
       'cnicus',
       'cnih4',
       'cniva',
       'cnic',
       'cnih',
       'cni'],
 'j': ['cnj'],
 'k': ['cnksr2', 'cnksr3', 'cnksr1', 'cnki', 'cnk'],
 'l': ['cnl'],
 'm': ['cnma', 'cnm'],
 'n': ['cnn-news18',
       'cnn/si',
       'cnngo',
       'cnnfn',
       'cnnnn',
       'cnnm2',
       'cnna',
       'cnn3',
       'cnn+',
       'cnn'],
 'o': ['cnobheresburg',
       'cnodifrontia',
       'cnodalonini',
       'cnodontes',
       'cnodalon',
       'cnodalia',
       'cnot6l',
       'cnot10',
       'cnopus',
       'cnot11',
       'cnova',
       'cnot1',
       'cnot2',
       'cnot7',
       'cnot8',
       'cnot9',
       'cnot6',
       'cnot4',
       'cnot3',
       'cno'],
 'p': ['cnp-300', 'cnp-600', 'cnptv', 'cnpy2', 'cnpj', 'cnpa', 'cnp'],
 'q': ['cnqx'],
 'r': ['cnrt', 'cnrd', 'cnrp', 'cnrc', 'cnr'],
 's': ['cnsmp', 'cnsad', 'cnsl', 'cnso', 'cnss', 'cns'],
 't': ['cntnap4',
       'cntnap2',
       'cntrob',
       'cnt-ii',
       'cntrl',
       'cntln',
       'cntv',
       'cnts',
       'cnta',
       'cntc',
       'cnt'],
 'u': ['cnuibacter', 'cnuella', 'cnut', 'cnu'],
 'v': ['cnvi', 'cnv'],
 'x': ['cnx1', 'cnx'],
 'y': ['cnyakundi.com']}
