
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bj = {'_': ["bj's_wholesale_club"],
 'a': ['bjarne_kortgaard_ingebretsen',
       'bjarni_oskar_thorsteinsson',
       'bjarnar_saga_hitdoelakappa',
       'bjarnarflag_power_station',
       'bjarni_olafur_eiriksson',
       'bjarki_steinn_bjarkason',
       'bjarni_gunnar_sveinsson',
       'bjarne_henry_henriksen',
       'bjarne_andre_myklebust',
       'bjarni_haukur_thorsson',
       'bjarni_mark_antonsson',
       'bjarki_mar_gunnarsson',
       'bjarte_lunde_aarsheim',
       'bjarne_m._robberstad',
       'bjarne_johannes_hope',
       'bjarne_karsten_vatne',
       'bjarne_elgar_grottum',
       'bjarne_aagaard_strom',
       'bjarni_mar_magnusson',
       'bjarne_hakon_hanssen',
       'bjarne_eilif_thorvik',
       'bjarne_keyser_barth',
       'bjarne_daniel_solli',
       'bjarke_ingels_group',
       'bjarki_mar_elisson',
       'bjarkoy_fixed_link',
       'bjarne_mork_eidem',
       'bjarne_odd_weider',
       'bjarte_engen_vik'],
 'e': ['bjelland_og_grindum'],
 'k': ['bjk_inonu_stadium', 'bjk_akatlar_arena'],
 'o': ['bjorkhaga,_karlskrona_municipality',
       'bjorn_turtums_gammeldansorkester',
       'bjorgolfur_thor_bjorgolfsson',
       'bjornomalmen_och_klacknaset',
       'bjorgolfur_hideaki_takefusa',
       'bjorn_bergmann_sigurdarson',
       'bjornlandet_national_park',
       'bjorg_caritas_thorlaksson',
       'bjorn_hjortur_gudmundsson',
       'bjorn_petter_ingebretsen',
       'bjorn_steiger_foundation',
       'bjorn_atle_holter-hovind',
       'bjornar_kaldefoss_tveite',
       'bjorn_haraldsen_ironside',
       'bjorkhagen_metro_station',
       'bjorgvin_pall_gustavsson',
       'bjornar_ustad_kristensen',
       'bjorn_natthiko_lindeblad',
       'bjorn_bolstad_skjelbred',
       'bjorn_oscar_gulbrandsen',
       'bjorn_hlynur_haraldsson',
       'bjorn_daniel_sverrisson',
       'bjorgvin_franz_gislason',
       'bjorn_erling_ytterhorn',
       'bjorgvin_g._sigurdsson',
       'bjork:_biophilia_live',
       'bjorn_johan_landmark',
       'bjorgum_farm_airport',
       'bjorn_arild_levernes',
       'bjorn_odmar_andersen',
       'bjorn_morgan_enqvist',
       'bjorn_valur_gislason',
       'bjorn_otto_bragstad',
       'bjorn_th._bjornsson',
       'bjorn_rune_gjelsten',
       'bjorn_s._stefansson',
       'bjorn_ole_gleditsch',
       'bjorn_erik_sandsten',
       'bjorg_aase_sorensen',
       'bjorn_bang_andersen',
       'bjorn_skogstad_aamo',
       'bjorn_maars_johnsen',
       'bjorn_einar_romoren',
       'bjorn_the_easterner',
       'bjorn_erik_hollevik',
       'bjorn_olav_blokhus',
       'bjorn_lidin_hansen',
       'bjorn_marius_hegge',
       'bjorg_hope_galtung',
       'bjorn_t._grydeland',
       'bjorn_gunnar_olsen',
       'bjorg_krane_bostad',
       'bjorn_dirk_krapohl',
       'bjorn_g._gjerstrom',
       'bjorn_erik_melland',
       'bjorvika_tram_stop',
       'bjorn_johnny_skaar',
       'bjorn_vidar_solli',
       'bjorn_helge_riise',
       'bjorn_g._andersen',
       'bjorg_lohner_oien',
       'bjorn_tore_kvarme',
       'bjorn_e._lindblom',
       'bjorn_tore_hansen',
       'bjork_herup_olsen',
       'bjorn_j:son_lindh',
       'bjorn_johan_muri',
       'bjorn_erik_rasch',
       'bjorg_tysdal_moe',
       'bjorn_arild_gram',
       'bjorn_aage_ibsen',
       'bjorn_inge_utvik',
       'bjorg_eva_jensen',
       'bjorn_tore_godal',
       'bjorn_the_eunuch',
       'bjorn_tore_hoem',
       'bjorn_von_sydow',
       'bjorn_erik_thon',
       'bjorn_arve_lund',
       'bjorn_ole_rasch',
       'bjorn_tore_bryn',
       'bjorn_at_haugi',
       'bjorn_and_okay',
       'bjorn_m._olsen',
       'bjorn_a._ling'],
 'p': ['bjp_mahila_morcha'],
 't': ['bjt_tech_uav'],
 'w': ['bjw_heavyweight_championship', "bjw_women's_championship"]}
