
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yn = {'a': ['ynakhsyt', 'ynaija', 'ynab', 'yna'],
 'd': ['yndolaciidae', 'yndia', 'yndio'],
 'e': ['ynet', 'yne'],
 'g': ['ynglingatal',
       'yngling',
       'yngaren',
       'ynglism',
       'yngern',
       'yngwin',
       'yngsjo',
       'yng-28',
       'yngve',
       'yngvi',
       'yng'],
 'h': ['ynhanfu'],
 'i': ['ynigo', 'yniol'],
 'k': ['ynkb', 'ynk'],
 'n': ['ynn'],
 'o': ['ynolate', 'ynone', 'ynoa', 'ynol'],
 'p': ['ynp'],
 't': ['yntymak'],
 'u': ['ynu'],
 'w': ['ynw'],
 'y': ['ynysymaengwyn',
       'ynysmaerdy',
       'ynysforgan',
       'ynysboeth',
       'ynysawdre',
       'ynystawe',
       'ynysybwl',
       'ynyswen',
       'ynyshir',
       'ynyslas',
       'ynysddu',
       'ynyrga']}
