
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bn = {'_': ['bn-reactor', 'bn66'],
 'a': ['bnachii', 'bnaya', 'bna'],
 'b': ['bnb'],
 'c': ['bnc-210', 'bnc1', 'bnc'],
 'd': ['bnd'],
 'e': ['bnetweled',
       'bnehran',
       'bneyel',
       'bnetd',
       'bnext',
       'bnet',
       'bnei',
       'bne'],
 'f': ['bnf'],
 'g': ['bng'],
 'h': ['bnhs', 'bnh'],
 'i': ['bnip3l',
       'bnip2',
       'bnipl',
       'bnito',
       'bniqa',
       'bnip3',
       'bnin',
       'bnim',
       'bni'],
 'j': ['bnj'],
 'k': ['bnk48', 'bnk'],
 'l': ['bnl'],
 'm': ['bnml', 'bnm'],
 'n': ['bnnvara', 'bnn-20', 'bnn-27', 'bnny', 'bnn'],
 'o': ['bnoc', 'bno'],
 'p': ['bnpp', 'bnp'],
 'q': ['bnqt'],
 'r': ['bnrr', 'bnr'],
 's': ['bns'],
 't': ['bnta', 'bntm'],
 'u': ['bnunis', 'bnu'],
 'v': ['bnv'],
 'w': ['bnw'],
 'x': ['bnxn', 'bnx'],
 'z': ['bnz']}
