
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-22T17:42:22+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6cb13db8d8406d3e166fea36c0644c6cd65520ae",
 "version": "2.0b0.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
