
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rk = {'_': ['rk_metaloplastika',
       'rk_zeljeznicar',
       'rk_heusenstamm',
       'rk_danilovgrad',
       'rk_university',
       'rk_crikvenica',
       'rk_bagatsing',
       'rk_petrovice',
       'rk_gracanica',
       'rk_ljubljana',
       'rk_tekstilec',
       'rk_vojvodina',
       'rk_miesnieki',
       'rk_dreamwest',
       'rk_medvescak',
       'rk_kolubara',
       'rk_metkovic',
       'rk_launcher',
       'rk_partizan',
       'rk_mojkovac',
       'rk_sintelon',
       'rk_derventa',
       'rk_bjelovar',
       'rk_zalgiris',
       'rk_strumica',
       'rk_olimpija',
       'rk-3_corsar',
       'rk2_plasmid',
       'rk_tacklers',
       'rk_pljevlja',
       'rk_izvidac',
       'rk_cepelin',
       'rk_baldone',
       'rk_crvenka',
       'rk_kvarner',
       'rk_fenikss',
       'rk_jugovic',
       'rk_livonia',
       'rk_dracevo',
       'rk_zajecar',
       'rk_mladost',
       'rk_vikingi',
       'rk_vogosca',
       'rk_lovcen',
       'rk_vardar',
       'rk_herceg',
       'rk_meghen',
       'rk_zagreb',
       'rk_komovi',
       'rk_dakovo',
       'rk_ulcinj',
       'rk_bitola',
       'rk_prespa',
       'rk_berane',
       'rk_vitez',
       'rk_celik',
       'rk_borec',
       'rk_beach',
       'rk_speed',
       'rk_nagar',
       'rk_porec',
       'rk_celje',
       'rk_zamet',
       'rk_rudar',
       'rk_koper',
       'rk_vrbas',
       'rk_sisak',
       'rk_krim',
       'rk_215',
       'rk_pet',
       'rk_21',
       'rk_62',
       'rk_20',
       'rk_71',
       'rk_fm'],
 'a': ['rkav_volendam'],
 'b': ['rkb'],
 'c': ['rkc_waalwijk'],
 'd': ['rkdf_university'],
 'e': ['rke'],
 'f': ['rkf'],
 'g': ['rkg'],
 'h': ['rkhunter', 'rkhvv'],
 'i': ['rkia_damsiria', 'rkia_mazrouai', 'rkia_derham'],
 'k': ['rkky_interaction'],
 'm': ['rkm_engine', 'rkm_code'],
 'n': ['rkn'],
 'o': ['rko/unique_records', 'rko_pictures', 'rko_general', 'rko_281'],
 'p': ['rkp'],
 's': ['rksv_scherpenheuvel',
       'rksv_halsteren',
       'rksv_leonidas',
       'rks_radomsko',
       'rksv_nuenen',
       'rks_design',
       'rksv_minor',
       'rksv_dcg'],
 't': ['rkt'],
 'u': ['rku'],
 'v': ['rkvv_westlandia',
       'rkvv_brabantia',
       'rkvv_aristos',
       'rkvv_velsen',
       'rkvv_stevo',
       'rkvv_deso',
       'rkvv_evv',
       'rkvv_dem'],
 'w': ['rkw_group'],
 'y': ['rky_camp'],
 'z': ['rkzvc', 'rkz']}
