
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rp = {'_': ['rp-hapee_toothpaste',
       'rp_motorsport',
       'rp-23_sapfir',
       'rp-21_sapfir',
       'rp_mall',
       'rp_flip',
       'rp_boo',
       'rp_1'],
 'a': ['rpa_rangemaster', 'rpa_assessment', 'rpa_c12a1', 'rpa_12'],
 'b': ['rpb'],
 'c': ['rpc_group', 'rpc_fort'],
 'd': ['rpd_energy'],
 'e': ['rperf', 'rpe65', 'rpety', 'rpe2', 'rpet', 'rpe'],
 'f': ['rpfc', 'rpf'],
 'g': ['rpg_metanoia', 'rpg-76_komar', 'rpg_maker', 'rpg_group'],
 'h': ['rph3al', 'rph3a', 'rphs', 'rph'],
 'i': ['rpi_engineers'],
 'k': ['rpk-9_medvedka', 'rpk-1_vikhr', 'rpk-2_vyuga'],
 'l': ['rpl26l1',
       'rpl-554',
       'rpl36al',
       'rpl22l1',
       'rpl-20',
       'rpl36',
       'rplp0',
       'rpls',
       'rpl'],
 'm': ['rpm_international',
       'rpm-30-2-can_do',
       'rpm_orchestra',
       'rpm_challenge',
       'rpm_mortgage',
       'rpm_year-end',
       'rpm_records',
       'rpm_fusion',
       'rpm_tuning',
       'rpm_2night',
       'rpm_racing',
       'rpmi_1640'],
 'n': ['rpn_newsbreak', 'rpn_newscap', 'rpn_usa'],
 'o': ['rpo-a_shmel', 'rpo_rys', 'rpo_zr2'],
 'p': ['rpp_fm'],
 'r': ['rpra_rna', 'rpr_fom'],
 's': ['rpsg_group', 'rps_group', 'rps_leyte'],
 't': ['rpt_realty'],
 'u': ['rpu'],
 'v': ['rpv'],
 'w': ['rpwl', 'rpw'],
 'x': ['rpx_corporation'],
 'y': ['rpyn06', 'rpyc'],
 'z': ['rpz']}
