
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rn = {'_': ['rn_breakfast',
       'rn_bogliasco',
       'rn_florentia',
       'rn_arenzano',
       'rn_imperia',
       'rn_camogli',
       'rn_savona',
       'rn_bank'],
 'a': ["rna-3'-phosphate_cyclase",
       'rna_uridylyltransferase',
       'rna-dominant_disease',
       'rna-based_evolution',
       'rna-binding_protein',
       'rnas_ballyhalbert',
       'rna_interference',
       'rna_therapeutics',
       'rnas_donibristle',
       'rna_thermometer',
       'rnas_kingsnorth',
       'rnas_merryfield',
       'rna_activation',
       'rna_automation',
       'rna_polymerase',
       'rna_extraction',
       'rna_hydrolysis',
       'rna_silencing',
       'rnas_longside',
       'rna_timestamp',
       'rnad_coulport',
       'rna_splicing',
       'rna_spike-in',
       'rnas_rattray',
       'rnas_calshot',
       'rnas_caldale',
       'rnas_hatston',
       'rna_editing',
       'rna_biology',
       'rnas_tresco',
       'rnad_trecwn',
       'rna_journal',
       'rna_origami',
       'rnas_pulham',
       'rna_society',
       'rnas_howden',
       'rna_cossmos',
       'rnase_phym',
       'rnas_capel',
       'rnase_mrp',
       'rna_world',
       'rna_virus',
       'rna_motif',
       'rnase_ph',
       'rnase_r',
       'rnase_d'],
 'b': ['rnb_research'],
 'c': ['rnc_media'],
 'd': ['rndis', 'rnd2', 'rndp', 'rnd1', 'rnd3', 'rndf', 'rndm', 'rnd'],
 'e': ['rne'],
 'f': ['rnf103-chmp3_readthrough'],
 'g': ['rng_muzic'],
 'h': ['rnh_mtarfa'],
 'i': ['rnie_6', 'rnie_3', 'rnie_5', 'rnie_7', 'rnie_2', 'rnie_1', 'rnie_4'],
 'k': ['rnk_split'],
 'l': ['rnl_architecture', 'rnlb_duncan'],
 'm': ['rnmtl1'],
 'n': ['rnn'],
 'o': ['rno'],
 'p': ['rnp_world'],
 'r': ['rnrmc', 'rnr1', 'rnr2', 'rnr4', 'rnr3', 'rnr5'],
 's': ['rns_formalism'],
 't': ['rnte_shotley'],
 'u': ['rnu4atac', 'rnu2-2', 'rnu12', 'rnu2'],
 'v': ['rnv'],
 'w': ['rnw_media'],
 'z': ['rnz_national', 'rnz_pacific', 'rnz_concert']}
