
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rj = {'_': ['rj_vigneshkanth',
       'rj_shaughnessy',
       'rj_liebenberg',
       'rj_sigurdson',
       'rj_malishka',
       'rj_benjamin',
       'rj_thompson',
       'rj_nembhard',
       'rj_padilla',
       'rj_rosales',
       'rj_ophelia',
       'rj_pradeep',
       'rj_praveen',
       'rj_barrett',
       'rj_jimenez',
       'rj_rohith',
       'rj_brewer',
       'rj_hadley',
       'rj_hemant',
       'rj_harris',
       'rj_dheena',
       'rj_texted',
       'rj_balaji',
       'rj_mitte',
       'rj_cyler',
       'rj_jazul',
       'rj_duets',
       'rj_nieto',
       'rj_renu',
       'rj_king',
       'rj_may'],
 'a': ['rjana_luzica'],
 'b': ['rjb_20-22'],
 'c': ['rjc'],
 'd': ['rjdj', 'rjd2'],
 'e': ['rjecica_gornja', 'rjecica_donja'],
 'f': ['rjf'],
 'g': ['rjg_inc.'],
 'h': ['rjh'],
 'k': ['rjk'],
 'm': ['rjmetrics', 'rjm'],
 'o': ['rjoandefossen'],
 'p': ['rjp'],
 'r': ['rjr_championship', 'rjr_nabisco'],
 's': ['rjs'],
 't': ['rjtv'],
 'u': ['rjukan_arbeiderblad', 'rjukan_station', 'rjukan_falls', 'rjukan_line']}
