
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_u_ = {'_': ['u7-ctenitoxin-pn1a',
       'u2.communication',
       'u-92,016-a',
       'u-69,593',
       'u-89843a',
       'u-77891',
       'u-90042',
       'u-50488',
       'u-47700',
       'u80601',
       'u61000',
       'u46619',
       'u80701',
       'u1.11',
       'u-5ts',
       'u-434',
       'u-571',
       'u-237',
       'u0126',
       'u-232',
       'u-231',
       'u-233',
       'u-229',
       'u-239',
       'u-238',
       'u111',
       'u160',
       'u-70',
       'u125',
       'u105',
       'u218',
       'u234',
       'u-28',
       'u880',
       'u937',
       'u57',
       'u47',
       'u23',
       'u80',
       'u15',
       'u29',
       'u18',
       'u19',
       'u32',
       'u46',
       'u62',
       'u82',
       'u12',
       'u96',
       'u21',
       'u10',
       'u68',
       'u38',
       'u13',
       'u20',
       'u16',
       'u55',
       'u67',
       'u87',
       'u42',
       'u92',
       'u17',
       'u.2'],
 'a': ['u2af2', 'u/a'],
 'b': ["u'bizchutan", 'u-blox', 'u-bolt', 'u-boat', 'u-bit', 'u-bes'],
 'c': ['u-catastrophe',
       'u-control',
       'u2charist',
       'u-chart',
       'u-cont',
       'u-care',
       'u-con',
       'u-cee'],
 'd': ['u.d.a.u.f.l.',
       'u-duality',
       'u.d.o.',
       'u-dise',
       'u.d.r.',
       'u-dub',
       'u1db'],
 'f': ['u.f.o.f.', 'u-force', 'u.f.orb', 'u-form', 'u-foes'],
 'g': ['u.g.l.y.', 'u-god'],
 'h': ['u-haul', 'u-high', 'u-hid', 'u4hk'],
 'i': ['u-invariant', 'u&i'],
 'j': ['u.jimshad', 'u-j3rk5', 'u-jean', 'u-jin'],
 'k': ['u-kiss', 'u-kwon', 'u-key'],
 'l': ['u-league'],
 'm': ['u-mutation', 'u-matrix', 'u-matic', 'u-myx', 'u-man'],
 'n': ['u.n.c.o.u.p.l.e.d.',
       'u.n.c.l.e.',
       'u.n.i.t.y.',
       'u-ni-ya',
       'u-neek',
       'u-net',
       'u-niq',
       'u;nee',
       'u-n-i'],
 'o': ['u.o.e.n.o.'],
 'p': ['u-prove', 'u-piter', 'u.p.o.', 'u-pass', 'u-pop'],
 'r': ['u-report', 'u-rescue', 'u-right', 'u-rank', 'u-roy'],
 's': ['u.s.avengers',
       'u-statistic',
       'u.s.u.r.a.',
       'u-sector',
       'u.s.c.h!',
       'u.s.s.a.',
       'u-s-a!',
       'u-sing',
       'u-set'],
 't': ['u.thaniyarasu', 'u-tsang', 'u-tube', 'u-turn', 'u.tv'],
 'u': ["u'u"],
 'v': ['u-vistract', 'u-vox'],
 'w': ["u'wa"],
 'y': ['u-yal'],
 'z': ['u.z.z.u.']}
