
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ls = {'_': ['ls-115509',
       'ls-1727',
       'ls-dyna',
       'ls3/5a',
       'ls-r',
       'ls5',
       'ls3',
       'ls1',
       'ls8',
       'ls2',
       'ls7',
       'ls6'],
 'a': ['lsattr', 'lsa'],
 'b': ['lsb'],
 'c': ['lscin', 'lscm', 'lscs', 'lscb', 'lsco', 'lsc'],
 'd': ['lsdxoxo', 'lsd-pip', 'lsda'],
 'e': ['lse/os', 'lse'],
 'f': ['lsfw', 'lsfc', 'lsf'],
 'g': ['lsg-1', 'lsg1', 'lsg2', 'lsg'],
 'h': ['lshs', 'lsh'],
 'i': ['lsid', 'lsi'],
 'j': ['lsjbot'],
 'k': ['lsk-hallen', 'lsk489', 'lsk'],
 'l': ['lsla', 'lsl'],
 'm': ['lsm-775',
       'lsmem2',
       'lsmem1',
       'lsmod',
       'lsm10',
       'lsm4',
       'lsm5',
       'lsm3',
       'lsm8',
       'lsm6',
       'lsm1',
       'lsm2',
       'lsm7',
       'lsm'],
 'n': ['lsn'],
 'o': ['lsof', 'lsoh', 'lso'],
 'p': ['lspci', 'lspi', 'lsp1', 'lsp'],
 'q': ['lsq'],
 'r': ['lsrc', 'lsr'],
 's': ['lssr', 'lsso', 'lsst', 'lss'],
 't': ['lsteni', 'lst1', 'lstv', 'lst'],
 'u': ['lsu-atletas'],
 'v': ['lsv-2', 'lsvd', 'lsv'],
 'w': ['lsw'],
 'z': ['lszh']}
