
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-25T15:48:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ab4ab09fb35653d32b1d369bcc638f1829bb858",
 "version": "0.2.26.post0.dev22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
