
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-19T10:02:09-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ea68a23613f2b242579f64b9a08e3d02fb5fc6e",
 "version": "0.2.25.post0.dev28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
