
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nz = {'_': ['nz_independent_coalition',
       'nz_cycling_conference',
       'nz_transport_agency',
       'nz_performance_car',
       'nz_climate_party',
       'nz_pass_verifier',
       'nz_drift_series',
       'nz_covid_tracer',
       'nz_book_month',
       'nz_on_screen',
       'nz_rail_150',
       'nz_on_air'],
 'a': ['nzara,_south_sudan', 'nzambi_a_mpungu'],
 'e': ['nzema_kotoko_f.c.',
       'nzelo_herve_lembi',
       'nze_ukwu_nnadum',
       'nze_na_ozo'],
 'i': ['nzia_gold_medal'],
 'o': ['nzoia_sugar_f.c.'],
 'r': ['nzrfu_centenary_matches',
       'nzr_50-foot_carriage',
       'nzr_56-foot_carriage',
       'nzr_sumbersari_f.c.',
       'nzr_dsa_class',
       'nzr_wab_class',
       'nzr_dsb_class',
       'nzr_wa_class',
       'nzr_nc_class',
       'nzr_ob_class',
       'nzr_wb_class',
       'nzr_ds_class',
       'nzr_wj_class',
       'nzr_ja_class',
       'nzr_ww_class',
       'nzr_la_class',
       'nzr_bb_class',
       'nzr_wh_class',
       'nzr_fa_class',
       'nzr_wg_class',
       'nzr_kb_class',
       'nzr_ba_class',
       'nzr_uc_class',
       'nzr_wf_class',
       'nzr_rm_class',
       'nzr_df_class',
       'nzr_ua_class',
       'nzr_ub_class',
       'nzr_bc_class',
       'nzr_na_class',
       'nzr_ka_class',
       'nzr_aa_class',
       'nzr_wd_class',
       'nzr_ec_class',
       'nzr_oc_class',
       'nzr_ud_class',
       'nzr_oa_class',
       'nzr_ab_class',
       'nzr_ed_class',
       'nzr_we_class',
       'nzr_d_class',
       'nzr_v_class',
       'nzr_k_class',
       'nzr_r_class',
       'nzr_g_class',
       'nzr_h_class',
       'nzr_e_class',
       'nzr_y_class',
       'nzr_b_class',
       'nzr_m_class',
       'nzr_j_class',
       'nzr_s_class',
       'nzr_u_class',
       'nzr_c_class',
       'nzr_l_class',
       'nzr_p_class',
       'nzr_t_class',
       'nzr_a_class',
       'nzr_f_class',
       'nzr_w_class',
       'nzr_x_class',
       'nzr_o_class',
       'nzr_n_class'],
 'u': ['nzubechi_grace_nwokocha'],
 'w': ['nzwpw_heavyweight_championship']}
