
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-04T13:32:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e83bfb0233d8548f324de11968bdcee01edad13",
 "version": "v0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
