
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ls = {'_': ['ls_records',
       'ls_group',
       'ls_tower',
       'ls_mtron',
       'ls9,_inc',
       'ls_5039',
       'ls_swap',
       'ls_pgb',
       'ls_90'],
 'a': ['lsa-engines_lsa850', 'lsat_rifle'],
 'b': ['lsbl_championships', 'lsbf_group'],
 'c': ['lsc_communications'],
 'd': ['lsd_march', 'lsd_art'],
 'e': ['lse-gaddafi_affair', 'lse_cities', 'lse_ideas'],
 'f': ['lsfw', 'lsfc', 'lsf'],
 'g': ['lsg_group'],
 'h': ['lsh_hotel'],
 'i': ['lsi_corporation'],
 'j': ['lsjbot'],
 'k': ['lsk_lacarak'],
 'l': ['lsla', 'lsl'],
 'm': ['lsm_education'],
 'n': ['lsn'],
 'o': ['lsof', 'lsoh', 'lso'],
 'p': ['lsp_technologies', 'lspm_j0207+3331', 'lspu_hall'],
 'q': ['lsq'],
 'r': ['lsr_j1835+3259', 'lsr_group'],
 's': ['lssa_uavs', 'lss_4067'],
 't': ['lst_1590-4', 'lst_1590', 'lst_1564'],
 'u': ['lsu-alexandria_generals',
       'lsu-shreveport_pilots',
       'lsu_gym/armory',
       'lsu_natatorium',
       'lsu_rrna'],
 'v': ['lsv_society', 'lsv_ahlhorn', 'lsv_putnitz', 'lsv_berlin', 'lsv_danzig'],
 'w': ['lsw_if'],
 'x': ['lsxx_tour'],
 'y': ['lsy-6_microrna'],
 'z': ['lszh']}
