
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xa = {'_': ['xa_doai_orange', 'xa_loi_pagoda'],
 'a': ['xaashi_suni_fooyaan'],
 'b': ['xabier_benito_ziluaga', 'xabier_macias_virgos', 'xabier_de_lizardi'],
 'g': ['xaghra_stone_circle', 'xaghra_united_f.c.'],
 'l': ['xalqobod,_surxondaryo_region',
       'xalqobod,_namangan_region',
       'xalapa_symphony_orchestra',
       'xalnene_tuff_footprints',
       'xalil_of_kazan'],
 'm': ['xaml_browser_applications',
       "xam'd:_lost_memories",
       'xam_wilson_cartier'],
 'n': ['xanthomatous_biliary_cirrhosis',
       'xanadu_quantum_technologies',
       'xantippe,_western_australia',
       'xanthine_oxidase_inhibitor',
       'xanterra_travel_collection',
       'xanthus-class_repair_ship',
       'xanthoma_striatum_palmare',
       'xanto:_novelucha_libre',
       'xanthi_railway_station',
       'xanthippus_of_carthage',
       'xanthus_russell_smith',
       'xander_de_buisonje',
       'xand_van_tulleken',
       'xanadu_in_africa',
       'xanthi_fc_arena',
       'xan_das_bolas',
       'xan_de_waard'],
 'q': ['xaquin_lorenzo_fernandez'],
 'r': ["xarxa_vives_d'universitats",
       'xara_designer_pro+',
       'xar_moron_river',
       'xara_xtreme_lx'],
 't': ["xat'sull_first_nation", 'xato_de_museros'],
 'v': ['xavier_jayakumar_arulanandam',
       "xavier's_security_enforcers",
       'xavier_college,_madagascar',
       'xavier_musketeers_baseball',
       'xavier_musketeers_football',
       'xavier_moyssen_echeverria',
       'xavier_ehrenbert_fridelli',
       'xavier_johnsai_munyongani',
       'xavier_naidoo_discography',
       'xavier_villaurrutia_award',
       'xavier_lyceum,_guatemala',
       'xavier_technical_college',
       'xavier_chamorro_cardenal',
       'xavier_estrada_fernandez',
       'xavier_capdevila_romero',
       'xavier_desandre_navarre',
       'xavier_catholic_college',
       'xaverian_primary_school',
       'xavier:_renegade_angel',
       'xavier_lamar_truesdell',
       'xavier_college,_panama',
       'xavier_chevalier_house',
       'xavier_college,_tudela',
       'xavier_pascual_fuertes',
       'xavier_charter_school',
       'xavier_enrique_torres',
       'xavier_neira_menendez',
       'xavier_garcia_albiol',
       'xavier_maawad_robert',
       'xaverian_high_school',
       'xavier_zablah_bukele',
       'xavier_school,_manvi',
       'xavier_marcos_padros',
       'xavier_azuara_zuniga',
       'xavier_tavera_castro',
       'xavier_le_draoullec',
       'xavier_lopez_ancona',
       'xavier_cortes_rocha',
       'xavier_joseph_huber',
       'xavier_b._fernandez',
       'xaveri_south_africa',
       'xavier_abreu_sierra',
       'xavier_romero_frias',
       'xavier_de_beukelaer',
       'xavier_vila_gazquez',
       'xavier_and_ophelia',
       'xavier_prats_monne',
       'xavier_vijay_kumar',
       'xavier_lopez_house',
       'xavier_de_langlais',
       'xavier_de_montclos',
       'xavier_de_montepin',
       'xavier_de_magallon',
       'xavier_comas_guixe',
       'xavier_de_villepin',
       'xavier_de_planhol',
       'xavier_de_moulins',
       'xavier_olea_munoz',
       'xavier_de_maistre',
       'xavier_blum_pinto',
       'xavier_f._salomon',
       'xaver_paul_thoma',
       'xavier_de_merode',
       'xavier_le_pichon',
       'xavier_j._barile',
       'xaveer_de_geyter',
       'xavier_le_floch',
       'xaver_frick_jr.',
       'xavier_di_petta',
       'xavier_de_furst',
       'xavier_de_cock',
       'xavier_de_roux'],
 'x': ["xaxli'p_first_nation"],
 'y': ['xayacatlan_de_bravo']}
