
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_x_ = {'_': ['x86_instruction_listings',
       'x10_wireless_technology',
       'x86_calling_conventions',
       "x2:_wolverine's_revenge",
       'x1-class_melbourne_tram',
       'x86_memory_segmentation',
       'x23-saroni_factory_team',
       'x2-class_melbourne_tram',
       'x-10_graphite_reactor',
       'x86_assembly_language',
       'x-15_flight_3-65-97',
       'x3:_terran_conflict',
       'x12_edifact_mapping',
       'x86_debug_register',
       'x3:_albion_prelude',
       'x._henry_goodnough',
       'x8_protein_domain',
       'x._m._sellathambu',
       'x12_document_list',
       'x5_retail_group',
       'x11_color_names',
       'x-23:_target_x',
       'x2:_the_threat',
       'x._b._saintine',
       'x5_music_group',
       'x-15_flight_90',
       'x-15_flight_91',
       'x._d._selvaraj',
       'x-15_flight_87',
       'x._j._kennedy',
       'x-75_volume_1',
       'x._george_xu',
       'x_-_ten'],
 'a': ['x_ambassadors_discography',
       'x_aegilotriticum_erebunii',
       'x.a.n._thessaloniki_b.c.',
       'x_athena_widgets',
       'x_and_hell'],
 'b': ['x_beruladium_procurrens'],
 'c': ['x-class_melbourne_tram', 'x-com:_ufo_defense'],
 'd': ['x_display_manager'],
 'f': ['x_factor_indonesia',
       'x_factor_slovakia',
       'x_factor_georgia',
       'x_factor_india',
       'x_factor_malta',
       'x_factor_adria',
       'x_font_server'],
 'g': ['x_games_snocross',
       'x_games_xviii',
       'x_games_viii',
       'x_games_xiii',
       'x_games_asia',
       'x_games_xvii',
       'x_games_xiv',
       'x_games_xvi',
       'x_games_xii',
       'x_games_xv'],
 'i': ['x_image_extension', 'x_input_method', 'x_is_loaded'],
 'j': ['x_japan_discography'],
 'k': ['x_keyboard_extension', 'x-k_fm_107.9'],
 'l': ['x-linked_recessive_hypoparathyroidism',
       'x-linked_lymphoproliferative_disease',
       'x-linked_intellectual_disability',
       'x-linked_recessive_inheritance',
       'x-linked_dystonia_parkinsonism',
       'x-linked_dominant_inheritance',
       'x-linked_myotubular_myopathy',
       'x_linked_thrombocytopenia',
       'x-league_indoor_football'],
 'm': ["x-men:_gamesmaster's_legacy",
       'x-men:_endangered_species',
       'x-men_origins:_wolverine',
       'x-men:_mutant_apocalypse',
       'x-men:_manifest_destiny',
       "x-men:_wolverine's_rage",
       'x-men:_messiah_complex',
       'x-men:_next_dimension',
       'x-men:_deadly_genesis',
       'x-men:_mutant_academy',
       'x-men:_second_coming',
       'x-men_in_television',
       'x_marks_destination',
       'x-men:_first_class',
       'x-men:_mutant_wars',
       'x-men:_mojo_world',
       'x-men_fairy_tales',
       'x-men:_the_manga',
       'x_music_festival',
       'x-men:_nation_x',
       'x-men:_the_198',
       'x_motor_racing',
       'x-men:_the_end',
       'x-mas_in_hell',
       'x_minus_one',
       'x_my_heart'],
 'n': ['x_neural_switcher'],
 'o': ['x/open_transport_interface', 'x2o_badkamers_trophy', 'x_of_swords'],
 'p': ['x-polynation/book_of_flags',
       'x_papilisia_taiwaniana',
       'x_python_newsreader',
       'x_prize_foundation',
       'x_prize_cup'],
 'r': ['x-ray_photoelectron_spectroscopy',
       'x-ray_fluorescence_holography',
       'x-ray_absorption_spectroscopy',
       'x-rated_critics_organization',
       'x-ray_scattering_techniques',
       'x-ray_polarimeter_satellite',
       'x-ray_emission_spectroscopy',
       'x-ray_birefringence_imaging',
       'x-ray_astronomy_satellite',
       'x-ray_astronomy_detector',
       'x-ray_image_intensifier',
       'x-ray_raman_scattering',
       'x-ray_motion_analysis',
       'x-roads_warriors_f.c.',
       'x_rendering_extension',
       'x-ray_standing_waves',
       'x-rated_fairy_tales',
       'x-ray_mega_airport',
       'x-ray_kid_studios',
       'x-ray_style_art',
       'x-ray_ct_scan'],
 's': ['x_sorbaronia_mitschurinii',
       'x-shaped_radio_galaxy',
       'x_session_manager',
       "x's_and_o's",
       'x_ss_corps'],
 't': ['x-treme_sanctions_executive',
       'x_trianguli_australis',
       'x_toolkit_intrinsics',
       'x_the_unknown',
       'x_the_album',
       'x_to_y'],
 'v': ['x-video_bitstream_acceleration',
       'x-video_motion_compensation',
       'x_video_extension'],
 'w': ['x_window_authorization',
       'x_window_selection',
       'x_window_manager',
       'x_window_system',
       'x_with_u'],
 'x': ['x.x.x._live_tour']}
