
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xu = {'_': ["xu_chang's_rebellion",
       "xu_xiake's_travels",
       'xu_zizhi_tongjian',
       'xu_yuan_zhen',
       'xu_hong_bai',
       'xu_hong_yan'],
 'a': ['xuancheng_railway_station',
       'xuanwu_district,_beijing',
       'xuanwu_district,_nanjing',
       'xuanhua_railway_station',
       'xuancheng_high_school',
       'xuanwu_gate_incident',
       'xuan_truong_district',
       'xuanzhou_wu_chinese',
       'xuan_writing_brush',
       'xuan_loc_district',
       'xuan_la,_hanoi',
       'xuan_son_virus',
       'xuan_phu,_hue'],
 'c': ['xuchang_railway_station'],
 'e': ['xueshan_township,_qinghai',
       'xuejiawan,_jungar_banner',
       'xuelin_road_station'],
 'h': ['xuhui_high_school'],
 'j': ['xujiacao_changle_station', 'xujiang_lu_station'],
 'm': ['xumi_fushou_temple'],
 'n': ['xunqueira_de_espadanedo',
       'xunqueira_de_ambia',
       'xunta_de_galicia',
       'xun_lei_chong'],
 's': ['xustans,_ponte_caldelas', 'xushui_railway_station'],
 't': ['xutos_and_pontapes', 'xutu_gang_station'],
 'x': ['xuxa_park_fire', 'xuxa_10_anos'],
 'y': ['xuying_road_station', 'xuyen_moc_district', 'xuyi_high_school'],
 'z': ['xuzhou-yancheng_high-speed_railway',
       'xuzhou_medical_university',
       'xuzhou_railway_station',
       'xuzhou,_zitong_county']}
