
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xe = {'_': ['xe_champhone_wetlands',
       'xe_kaman_river',
       'xe_xou_river',
       'xe_do_hoang'],
 'b': ['xebio_arena_sendai'],
 'c': ['xechasmeni_railway_station'],
 'i': ['xeimonio_railway_station'],
 'k': ['xekina_mia_psaropoula'],
 'l': ['xelile_cacan_muradov', 'xellent_swiss_vodka', 'xelucha_and_others'],
 'n': ['xenomania_production_discography',
       'xenogears_original_soundtrack',
       'xenophage:_alien_bloodsport',
       'xenagoras_of_halicarnassus',
       'xenon-enhanced_ct_scanning',
       'xenocrates_of_aphrodisias',
       'xenophon_overton_pindall',
       'xenia_community_schools',
       'xenosaga:_the_animation',
       'xena:_warrior_princess',
       'xenoblade_chronicles_2',
       'xenoblade_chronicles_x',
       'xenophobia_in_malaysia',
       'xenon_fluoride_nitrate',
       'xenoblade_chronicles_3',
       'xenarchus_of_seleucia',
       'xenosaga:_pied_piper',
       'xenokrates_of_sicyon',
       'xenosaga_episode_iii',
       'xenophon_p._wilfley',
       'xenophon_of_corinth',
       'xenophon_of_robeika',
       'xenosaga_episode_ii',
       'xenophon_of_ephesus',
       'xenopus_egg_extract',
       'xenia_daily_gazette',
       "xenu's_link_sleuth",
       'xenon_2:_megablast',
       'xenia_of_yaroslavl',
       'xenia_boodberg_lee',
       'xeno_and_oaklander',
       'xenia_stad-de_jong',
       'xenion_high_school',
       'xenophon_of_aegium',
       'xenosaga_episode_i',
       'xenos_young_clark',
       'xenia_high_school',
       'xeno_nucleic_acid',
       'xenias_of_arcadia',
       'xenia_of_tarusa',
       'xenias_of_elis',
       'xeno_of_koroni',
       'xenon_arc_lamp',
       'xenia_of_rome',
       'xen_c._scott'],
 'r': ['xerox_development_environment',
       "xerxes'_pontoon_bridges",
       'xerox_operating_system',
       'xerox_network_systems',
       'xerox_escape_sequence',
       'xeros_washing_machine',
       'xerxes_de_oliveira',
       'xerez_deportivo_fc',
       'xerxes_of_sophene',
       'xerox_500_series',
       'xerdc_rna_motif',
       'xerox_sigma_9',
       'xerez_cd_b'],
 's': ['xesus_ferro_ruibal'],
 't': ['xetulul_theme_park'],
 'v': ['xevious:_fardraut_saga'],
 'w': ['xewkija_tigers_f.c.']}
