
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-19T06:40:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8451b91c4ae44cdd19a200864ca9388052e07e1f",
 "version": "1.17.0.post0.dev177"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
