
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jy = {'_': ['jy_cell_line'],
 'e': ['jyestharya_of_sambhupura'],
 'l': ['jylgyndy_forest_reserve'],
 'o': ['jyotirindra_bodhipriya_larma',
       'jyotiranjan_srichandan_ray',
       'jyothy_kendriya_vidyalaya',
       'jyoti_bhusan_chatterjea',
       'jyotirmay_singh_mahato',
       'jyoti_jyoti_mahajyoti',
       'jyothi_surekha_vennam',
       'jyoti_prasad_agarwala',
       'jyoti_bhushan_banerji',
       'jyoti_prasad_rajkhowa',
       'jyotsna_keshav_bhole',
       'jyoti_prakash_tamang',
       'jyoti_prakash_nirala',
       'jyotindra_nath_dixit',
       'jyoti_nivas_college',
       'jyotiba_rao_scindia',
       'jyoti_prakash_dutta',
       'jyoti_bhusan_chaki',
       'jyoti_sunita_kullu',
       'jyothi_high_school',
       'jyoti_kirit_parikh',
       'jyoti_ann_burrett',
       'jyoti_kumar_sinha',
       'jyoti_bane_jwala',
       'jyoti_prasad_das',
       'jyoti_kapur_das'],
 'p': ['jyp_entertainment_discography'],
 's': ['jyske_bank_boxen'],
 't': ['jytte_reichstein_nilsson'],
 'u': ['jyu_jik_chuyhn'],
 'v': ['jyvaskylan_seudun_palloseura',
       'jyvaskyla_university_library',
       'jyvaskyla_library_stabbing',
       'jyvaskyla_central_station',
       'jyvaskyla_rail_accident',
       'jyvaskyla_arts_festival',
       'jyvaskyla_city_theatre']}
