
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dm = {'_': ['dm3_density_meter', 'dm_glen_douglas'],
 'a': ['dmanisi_sioni_cathedral',
       'dmanisi_historic_site',
       'dmanisi_skull_5',
       'dmanisi_skull_3',
       'dmax_v6_engine'],
 'c': ['dmc_international_imaging',
       'dmc_surgery_hospital',
       'dmc_mining_services'],
 'g': ['dmg_mori_aktiengesellschaft', 'dmg_mori_seiki'],
 'i': ['dmitry_ivanovich_sviatopolk-mirsky',
       'dmitriy_furmanov-class_motorship',
       'dmitriy_shostakovich-class_ferry',
       'dmitry_dmitriyevich_smyshlyayev',
       'dmitri_lyudvigovich_tomashevich',
       'dmitriyevskoye,_vladimir_oblast',
       'dmitriyevskaya,_vologda_oblast',
       'dmitry_konstantinovich_zelenin',
       'dmitry_alexandrovich_medvedev',
       'dmitri_leonidovich_romanowsky',
       'dmitriyevka,_astrakhan_oblast',
       'dmitriyevsky,_voronezh_oblast',
       'dmitri_alekseyevich_gallitzin',
       'dmitri_anatolyevich_kuznetsov',
       'dmitri_aleksandrovich_kabanov',
       'dmitry_fyodorovich_selivanov',
       'dmitry_alexandrovich_smirnov',
       'dmitry_gennadyevich_medvedev',
       'dmitry_nikolayevich_filippov',
       'dmitriyevka,_vladimir_oblast',
       'dmitry_pavlovich_grigorovich',
       'dmitri_dmitriyevich_vasilyev',
       'dmitrii_ivanovich_zhuravskii',
       'dmitry_dmitrievich_maksutov',
       'dmitrovsky_district,_moscow',
       'dmitry_nikolayevich_ulyanov',
       'dmitri_anatolyevich_davydov',
       'dmitrii_ivanovich_sosnowsky',
       'dmitriyevka,_altai_republic',
       'dmitri_andreyevich_golubev',
       'dmitri_anatolyevich_kozlov',
       'dmitry_alexeyevich_davydov',
       'dmitry_matveyevich_smirnov',
       'dmitrii_nikolaevich_taliev',
       'dmitry_timofeyevich_kozlov',
       'dmitry_petrovich_dokhturov',
       'dmitri_vasilyevich_golubev',
       'dmitry_sergeyevich_kosenko',
       'dmitrikovo,_vologda_oblast',
       'dmitriy_vasilevich_polenov',
       'dmitrii_abramovich_raikov',
       'dmitry_koldun_discography',
       "dmitry_medvedev's_cabinet",
       'dmitry_petrovich_maksutov',
       'dmitry_sergeyevich_kuzmin',
       'dmitri_pokrovsky_ensemble',
       'dmitri_feodorovich_trepov',
       'dmitry_vadimovich_zelenin',
       'dmitri_petrovich_golitsyn',
       'dmitry_borisovich_volkov',
       'dmitri_ivanovich_sokolov',
       'dmitri_sergeyevich_badin',
       'dmitry_arkadjevich_bagin',
       'dmitry_pavlovich_golubev',
       'dmitry_sergeyevich_gusev',
       'dmitry_yakovlevich_popov',
       'dmitriyevka,_altai_krai',
       'dmitry_ivanovich_popov',
       'dmitri_olegovich_orlov',
       'dmitry_ilyich_ulyanov',
       'dmitri_rudolf_peacock',
       'dmitriy_g._stankevich',
       'dmitri_the_astronaut',
       'dmitry_laptev_strait',
       'dmitri_ilyich_kozlov',
       'dmitrij_f._lupishko',
       'dmitry_of_pereslavl',
       'dmitry_v._sklyarov',
       'dmitry_v._bisikalo',
       'dmitri_z._garbuzov',
       'dmitry_of_bryansk',
       'dmitri_stulov_jr.',
       'dmitry_of_suzdal',
       'dmitry_of_uglich',
       'dmitry_of_tver'],
 'j': ['dmj_pick_bridge'],
 'l': ['dml_butler_bridge'],
 'p': ['dmpg-like_communication_domain', "dmpo's_on_broadway"],
 's': ['dms_pondicherry_university'],
 'y': ['dmytriy_leonidovich_cherniavskiy',
       'dmytro_oleksandrovych_voloshyn',
       'dmytro_anatoliyovych_osadchyi',
       'dmytro_vitaliyovych_voloshyn',
       'dmytro_serhiyovych_osadchyi',
       'dmytrivka,_chernihiv_oblast',
       'dmytrivka,_shakhtarsk_raion',
       'dmytrivka,_bolhrad_raion',
       'dmytrivka,_izmail_raion']}
