
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dl = {'_': ['dl_postcode_area'],
 'a': ['dla_disposition_services', 'dlamini_king_brothers'],
 'f': ['dlf_cybercity_chennai', 'dlf_cup_2006'],
 'h': ['dlhe_nad_cirochou',
       'dlha_nad_kysucou',
       'dlha_nad_oravou',
       'dlha_nad_vahom'],
 'i': ['dlinza_forest_pinwheel'],
 's': ['dlsu_lady_booters'],
 'u': ['dlugoleka,_warmian-masurian_voivodeship',
       'dlugoleka,_swietokrzyskie_voivodeship',
       'dluzyna,_warmian-masurian_voivodeship',
       'dluzek,_warmian-masurian_voivodeship',
       'dlugie,_warmian-masurian_voivodeship',
       'dluga,_warmian-masurian_voivodeship',
       'dlugie,_strzelce-drezdenko_county',
       'dluzniewo,_podlaskie_voivodeship',
       'dlugoleka,_podlaskie_voivodeship',
       'dlugoleka,_masovian_voivodeship',
       'dluzniewo,_masovian_voivodeship',
       'dlugowola,_masovian_voivodeship',
       'dlugie,_pomeranian_voivodeship',
       'dlugie,_podlaskie_voivodeship',
       'dlugowola,_lublin_voivodeship',
       'dlugosz,_masovian_voivodeship',
       'dlugoleka,_lodz_voivodeship',
       'dluzek,_lubusz_voivodeship',
       'dlugokaty,_zyrardow_county',
       'dluthach_mac_fithcheallach',
       'dlugie,_ostroleka_county',
       'dlugie,_wloclawek_county',
       'dlugie,_przysucha_county',
       'dluzec,_wegorzewo_county',
       'dlugie,_radomsko_county',
       'dlugokaty,_mlawa_county',
       'dlubnia_landscape_park',
       'dluzec,_mragowo_county',
       'dlugie,_krosno_county',
       'dlugie,_lublin_county',
       'dlugov_assault_rifle',
       'dlugie,_rypin_county',
       'dlusko,_walcz_county',
       'dlugie,_zagan_county',
       'dlugie,_sanok_county',
       'dluga_wies_pierwsza',
       'dluga_wies_trzecia',
       'dluga_wies_druga'],
 'x': ['dlx_gene_family']}
