depends = ('ITKPyBase', 'ITKImageSources', 'ITKCommon', )
templates = (
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS2ISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS2IUC2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS2IUS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned short,2 >, itk::Image< signed short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS3ISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS3IUC3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS3IUS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned short,3 >, itk::Image< signed short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC2ISS2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC2IUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC2IUS2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC3ISS3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC3IUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC3IUS3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS2ISS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< signed short,2 >, itk::Image< unsigned short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS2IUC2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS2IUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS3ISS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< signed short,3 >, itk::Image< unsigned short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS3IUC3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS3IUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF2ISS2IF2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >, itk::Image< float,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF2IUC2IF2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF2IUS2IF2', True, 'itk::Image< float,2 >, itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF3ISS3IF3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >, itk::Image< float,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF3IUC3IF3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF3IUS3IF3', True, 'itk::Image< float,3 >, itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID2ISS2ID2', True, 'itk::Image< double,2 >, itk::Image< signed short,2 >, itk::Image< double,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID2IUC2ID2', True, 'itk::Image< double,2 >, itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID2IUS2ID2', True, 'itk::Image< double,2 >, itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID3ISS3ID3', True, 'itk::Image< double,3 >, itk::Image< signed short,3 >, itk::Image< double,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID3IUC3ID3', True, 'itk::Image< double,3 >, itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID3IUS3ID3', True, 'itk::Image< double,3 >, itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
)
