
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xp = {'_': ['xp-pen', 'xp64', 'xp8'],
 'a': ['xpander', 'xpages', 'xpath', 'xpax', 'xpak', 'xpa'],
 'b': ['xpb'],
 'c': ['xpc-binding', 'xpcom', 'xpc'],
 'd': ['xpdl', 'xpdf', 'xpd'],
 'e': ['xpert-timer',
       'xpectation',
       'xperience',
       'xpedition',
       'xpertdoc',
       'xperedon',
       'xpecial',
       'xpeng',
       'xperi',
       'xpeke',
       'xpeak',
       'xpert',
       'xped',
       'xpe'],
 'f': ['xpf'],
 'g': ['xpg'],
 'h': ['xphos'],
 'i': ['xpinstall', 'xpilot', 'xpidl', 'xpic'],
 'l': ['xplor-nih',
       'xplorair',
       'xplosion',
       'xplornet',
       'xploderz',
       'xplorer2',
       'xplorer',
       'xploder',
       'xplanet',
       'xplane',
       'xplore',
       'xplico',
       'xplora',
       'xplor',
       'xplay',
       'xpl0',
       'xplm',
       'xpl'],
 'm': ['xpm'],
 'n': ['xpnpep1', 'xpnpep2', 'xpnpep3', 'xpn'],
 'o': ['xpostfacto',
       'xpointer',
       'xposed',
       'xports',
       'xpose',
       'xpot',
       'xpo5',
       'xpo1',
       'xpo4',
       'xpo6',
       'xpo'],
 'p': ['xpp'],
 'q': ['xpq-21'],
 'r': ['xpressmusic',
       'xpressway',
       'xpressbet',
       'xpress',
       'xprint',
       'xproc',
       'xpra'],
 's': ['xps'],
 't': ['xpt'],
 'u': ['xpuhil', 'xputer', 'xpujil']}
