
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-18T21:25:25-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d78fdbee19758eb83919c6d3c202d5235ebd34bf",
 "version": "0.2.25.post0.dev20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
