
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nc = {'_': ['nc_state_wolfpack',
       'nc/nga_mice_model',
       'nc_policy_watch',
       'nc_by_train'],
 'a': ['ncar-wyoming_supercomputing_center',
       'ncaa_student-athlete_recruiting',
       'ncaa_cheerleading_competition',
       'ncaa_taekwondo_championship',
       'ncaa_basketball_tournament',
       'ncaa_fencing_championships',
       'ncaa_lacrosse_championship',
       'ncaa_skiing_championships',
       'ncaa_general_championship',
       'ncaa_bowling_championship',
       'ncaa_boxing_championship',
       'ncaa_sportsmanship_award',
       'ncaa_university_division',
       'ncaa_rifle_championship',
       'ncaa_chess_championship',
       'ncaa_inspiration_award',
       'ncaa_banned_substances',
       'ncaa_basketball_series',
       'ncaa_gamebreaker_2001',
       'ncaa_college_division',
       'ncaa_gamebreaker_2003',
       'ncaa_gamebreaker_2000',
       'ncaa_gamebreaker_2004',
       'ncaa_transfer_portal',
       'ncaa_gamebreaker_99',
       'ncaa_gamebreaker_98',
       'ncaa_basketball_10',
       'ncaa_football_2002',
       'ncaa_football_2003',
       'ncaa_football_2004',
       'ncaa_football_2000',
       'ncaa_football_2001',
       'ncaa_football_2005',
       'ncaa_basketball_09',
       'ncaa_drug_testing',
       'ncaa_division_iii',
       "ncaa_football_'98",
       'ncaa_football_14',
       'ncaa_football_13',
       'ncaa_football_12',
       'ncaa_football_09',
       'ncaa_football_11',
       'ncaa_football_06',
       'ncaa_football_08',
       'ncaa_football_07',
       'ncaa_football_10',
       'ncaa_football_99',
       'ncaa_division_ii',
       'ncaa_division_i',
       'ncaa_season_84',
       'ncaa_season_78',
       'ncaa_season_79',
       'ncaa_season_81',
       'ncaa_season_89',
       'ncaa_season_77',
       'ncaa_season_85',
       'ncaa_season_93',
       'ncaa_season_90',
       'ncaa_season_96',
       'ncaa_season_86',
       'ncaa_season_92',
       'ncaa_season_88',
       'ncaa_season_76',
       'ncaa_season_75',
       'ncaa_season_97',
       'ncaa_season_83',
       'ncaa_season_94',
       'ncaa_season_91',
       'ncaa_season_82',
       'ncaa_season_80',
       'ncaa_season_95',
       'ncaa_season_87',
       'ncaa_v._smith',
       'ncar_lsm_1.0',
       'ncaa_on_cbs'],
 'b': ['ncb_financial_group',
       'ncba_bank_tanzania',
       'ncba_bank_rwanda',
       'ncba_bank_uganda',
       'ncba_bank_kenya',
       'ncba_group_plc'],
 'c': ['nccu_international_mba',
       'ncca_knockout_trophy',
       'nccc_mall_tagum',
       'ncc_class_s2',
       'ncc_class_u2',
       'ncc_class_a1',
       'ncc_class_wt',
       'ncc_class_s1',
       'ncc_class_b3',
       'ncc_class_v',
       'ncc_class_y',
       'ncc_class_x',
       'ncc_class_w'],
 'd': ['ncdex_commodity_index'],
 'e': ['ncert_textbook_controversies'],
 'g': ['ncg_banco,_s.a.'],
 'h': ['nchc_sportsmanship_award',
       'ncheni_type_haplochromis',
       'nchingidi_worm_lizard',
       "ncha_men's_tournament",
       'nch_healthcare_system',
       'nchanga_rangers_f.c.',
       'ncha_triple_crown',
       'ncha_super_stakes',
       'nchu_v/stol_uav'],
 'i': ['nci-designated_cancer_center',
       'ncic_inmate_communications',
       'nci_building_systems',
       'ncis_backdoor_pilot',
       'nci_froward_point',
       'nci_portland_bill',
       'ncis:_new_orleans',
       'ncis:_los_angeles'],
 'l': ['ncl_division_three', 'ncl_division_one', 'ncl_division_two'],
 'o': ['nco_railway_depot', 'ncompass_labs_inc'],
 'r': ['ncr-ucl_athletic_association',
       'ncr_country_club',
       'ncr_century_100',
       'ncr_book_award'],
 's': ['ncsist_chien_hsiang', 'ncsist_teng_yun', 'ncsa_brown_dog'],
 't': ['nct_2020_resonance', 'nct_2018_empathy'],
 'u': ['ncumisa_chwayita_kondlo',
       'ncu_senior_league',
       'ncu_challenge_cup',
       'ncu_junior_cup']}
