
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oe = {'_': ['oe_district,_tokushima',
       'oe_kenzaburo_prize',
       'oe_with_diaeresis',
       'oe_no_hiromoto',
       'oe_no_masafusa',
       'oe_with_macron',
       'oe_no_chisato',
       'oe_no_otondo'],
 'b': ['oebotas_of_dyme'],
 'c': ['oecd_anti-bribery_convention', 'oecd_development_centre'],
 'd': ['oedo_sukeroku_taiko', 'oedipus_at_colonus', 'oedipe_a_colone'],
 'i': ['oeiras_international_school',
       'oeiras_ladies_open',
       'oeil_de_perdrix',
       'oeiras_do_para',
       'oei_hong_leong',
       'oeil_du_prince',
       'oei_tjie_sien',
       'oei_hok_tiang',
       'oei_tiong_ham',
       'oei_wie_gwan',
       'oei_tjoe_tat'],
 'k': ['oek_de_jong'],
 'l': ['oelrichs,_south_dakota'],
 'm': ['oemar_said_tjokroaminoto'],
 'n': ['oensingen-balsthal_railway_line',
       'oensingen_railway_station',
       'oengus_tuirmech_temrach',
       'oengus_of_tallaght',
       'oengus_mac_fergusa',
       'oenomaus_of_gadara',
       'oengus_mac_mugroin',
       'oengus_mac_colmain',
       'oengus_mac_oengusa',
       'oenanthe_of_egypt',
       'oengus_ua_gormain',
       'oengus_of_moray',
       'oen_giok_khouw'],
 'r': ['oerlikon-bulach_railway_line', 'oera_linda_book'],
 's': ['oesophagogastric_junctional_adenocarcinoma',
       'oesilo_administrative_post',
       'oesel_choeling_monastery',
       'oesman_sadik_airport',
       "oesch's_die_dritten",
       'oeste_futebol_clube',
       'oese,_parnu_county',
       'oese,_rapla_county',
       'oesman_sapta_odang'],
 't': ['oetrange_railway_station',
       'oettingen_in_bayern',
       'oethelwald_of_deira',
       'oets_kolk_bouwsma',
       'oetwil_am_see'],
 'u': ['oeufs_en_meurette'],
 'y': ['oey-diemtigen_railway_station',
       'oey_liauw_kong',
       'oey_tamba_sia',
       'oey_giok_koen',
       'oey_bian_kong',
       'oey_djie_san',
       'oey_khe_tay',
       'oey_thai_lo']}
