
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tp = {'_': ['tp_properties',
       'tp.3_reloaded',
       'tp_sudhindra',
       'tp_molunge',
       'tp_mazembe',
       'tp_formula',
       'tp_mystere',
       'tp_vision',
       'tp_icap',
       'tp_52'],
 'a': ['tpao_batman'],
 'b': ['tpb_afk'],
 'c': ['tpc_scottsdale',
       'tpc_prestancia',
       'tpc_sugarloaf',
       'tpc_stonebrae',
       'tpc_southwind',
       'tpc_michigan',
       'tpc_boston',
       'tpc_group'],
 'd': ['tpd52l1', 'tpd52l2', 'tpd52', 'tpdf', 'tpdc', 'tpd'],
 'e': ['tpen', 'tpeg', 'tpec', 'tper', 'tpe'],
 'f': ['tpf'],
 'g': ['tpg_telecom', 'tpg_inc.', 'tpg_tour'],
 'h': ['tph_partners', 'tph_club'],
 'i': ['tpi_specialties', 'tpi_theory', 'tpi_polene'],
 'j': ['tpj'],
 'k': ['tpk_algorithm'],
 'l': ['tpl_tables'],
 'm': ['tpm_domain'],
 'n': ['tpnw', 'tpn'],
 'o': ['tpok_jazz'],
 'p': ['tpp_riboswitch', 'tpp_kostolac'],
 'q': ['tpq'],
 'r': ['tpr_storytelling'],
 's': ['tps_pakistan',
       'tps_naiset',
       'tps_report',
       'tps_turku',
       'tps_group',
       'tps_star',
       'tps_foot'],
 't': ['tptp', 'tpt1', 'tpte', 'tpt'],
 'u': ['tput', 'tpu'],
 'v': ['tpv_technology'],
 'w': ['tpws', 'tpw'],
 'x': ['tpx_communications'],
 'y': ['tpy-2'],
 'z': ['tpz_fuchs']}
