
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kk = {'_': ['kk_sonik-puntamika',
       'kk_blokotehna',
       'kk_zeleznicar',
       'kk_andromedae',
       'kk_crikvenica',
       'kk_hercegovac',
       'kk_rabotnicki',
       'kk_profikolor',
       'kk_motorsport',
       'kk_superfund',
       'kk_vojvodina',
       'kk_buducnost',
       'kk_dubrovnik',
       'kk_grosuplje',
       'kk_podgorica',
       'kk_meridiana',
       'kk_zrinjevac',
       'kk_wloclawek',
       'kk_strumica',
       'kk_vinkovci',
       'kk_zlatibor',
       'kk_kumanovo',
       'kk_gostivar',
       'kk_lastovka',
       'kk_portoroz',
       'kk_hrastnik',
       'kk_radnicki',
       'kk_pelister',
       'kk_bratunac',
       'kk_crnokosa',
       'kk_partizan',
       'kk_olimpija',
       'kk_sutjeska',
       'kk_borovica',
       'kk_jagodina',
       'kk_krizevci',
       'kk_zdravlje',
       'kk_ergonom',
       'kk_belisce',
       'kk_olimpas',
       'kk_loznica',
       'kk_sentjur',
       'kk_parklji',
       'kk_radovis',
       'kk_masinac',
       'kk_baltika',
       'kk_vogosca',
       'kk_maribor',
       'kk_sentral',
       'kk_kvarner',
       'kk_elektra',
       'kk_slavija',
       'kk_rogaska',
       'kk_zarkovo',
       'kk_kastela',
       'kk_swiecie',
       'kk_dynamic',
       'kk_goswami',
       'kk_mladost',
       'kk_sibenik',
       'kk_dubrava',
       'kk_sloboda',
       'kk_dalvin',
       'kk_slodes',
       'kk_angeli',
       'kk_centar',
       'kk_thesis',
       'kk_gorica',
       'kk_sencur',
       'kk_jazine',
       'kk_leotar',
       'kk_igokea',
       'kk_trogir',
       'kk_vardar',
       'kk_kakanj',
       'kk_palace',
       'kk_vizura',
       'kk_viimsi',
       'kk_cibona',
       'kk_ulcinj',
       'kk_shkupi',
       'kk_zagreb',
       'kk_torus',
       'kk_joker',
       'kk_kalev',
       'kk_korab',
       'kk_alkar',
       'kk_bosco',
       'kk_koper',
       'kk_celik',
       'kk_celje',
       'kk_solin',
       'kk_zemun',
       'kk_opara',
       'kk_zadar',
       'kk_vrsac',
       'kk_atlas',
       'kk_kozuv',
       'kk_tamis',
       'kk_sloga',
       'kk_pirot',
       'kk_livno',
       'kk_zabok',
       'kk_rtanj',
       'kk_split',
       'kk_best',
       'kk_agha',
       'kk_krka',
       'kk_beko',
       'kk_ibar',
       'kk_null',
       'kk_fosu',
       'kk_klik',
       'kk_hito',
       'kk_star',
       'kk_heo',
       'kk_fmp',
       'kk_tft',
       'kk_bor',
       'kk_62'],
 'a': ['kkachisan_station', 'kkachiul_station', 'kkachi_durumagi'],
 'b': ['kkbj-fm',
       'kkbc-fm',
       'kkbox',
       'kkbj',
       'kkbs',
       'kkbd',
       'kkbl',
       'kkbo',
       'kkbq',
       'kkbi',
       'kkbg',
       'kkbz',
       'kkbn',
       'kkba',
       'kkbb',
       'kkbr',
       'kkbt',
       'kkb'],
 'c': ['kkcl-fm',
       'kkcq-fm',
       'kkcd',
       'kkcl',
       'kkct',
       'kkcb',
       'kkco',
       'kkcs',
       'kkca',
       'kkcr',
       'kkcw',
       'kkcm',
       'kkcq',
       'kkci',
       'kkcn',
       'kkcy',
       'kkch',
       'kkck',
       'kkc'],
 'd': ['kkds-lp',
       'kkda-fm',
       'kkdj-ld',
       'kkda',
       'kkdc',
       'kkdg',
       'kkdd',
       'kkdz',
       'kkdm',
       'kkdj',
       'kkdo',
       'kkdl',
       'kkdv',
       'kkdq',
       'kkdy',
       'kkdt'],
 'e': ['kke_architects'],
 'f': ['kkfx-cd',
       'kkfd-fm',
       'kkft',
       'kkfn',
       'kkfr',
       'kkfm',
       'kkfg',
       'kkfs',
       'kkfi'],
 'g': ['kkgq',
       'kkgr',
       'kkgu',
       'kkgk',
       'kkgo',
       'kkgb',
       'kkgl',
       'kkgx',
       'kkgm',
       'kkg'],
 'h': ['kkh_060'],
 'i': ['kkic-ld',
       'kkin-fm',
       'kkis-fm',
       'kkic',
       'kkix',
       'kkid',
       'kkin',
       'kkik',
       'kkit',
       'kkia',
       'kkiq',
       'kkim',
       'kki'],
 'j': ['kkjo-fm',
       'kkjc-lp',
       'kkjd-lp',
       'kkjl',
       'kkjy',
       'kkjz',
       'kkjb',
       'kkjg',
       'kkjd',
       'kkjq',
       'kkjk',
       'kkjm'],
 'k': ['kkk_radnicki', 'kkk_bosna'],
 'l': ['kkla-fm',
       'kkls-fm',
       'kklr-fm',
       'kklt',
       'kklj',
       'kkln',
       'kklq',
       'kklx',
       'kkls',
       'kklz',
       'kklc',
       'kklo',
       'kklb',
       'kkli',
       'kklf',
       'kklm',
       'kkld',
       'kklh',
       'kkle',
       'kkly',
       'kklv',
       'kkll',
       'kkl'],
 'm': ['kkmj-fm',
       'kkmr',
       'kkmo',
       'kkmk',
       'kkmi',
       'kkms',
       'kkmv',
       'kkma',
       'kkmp',
       'kkmc',
       'kkmy',
       'kkmg',
       'kkmt',
       'kkmx',
       'kkml',
       'kkm'],
 'n': ['kknd2:_krossfire'],
 'o': ['kkoktugakshi_nori', 'kkondae_intern'],
 'p': ['kkpm-cd',
       'kkpr-fm',
       'kkpd-ld',
       'kkpx-tv',
       'kkpk',
       'kkps',
       'kkpc',
       'kkpn',
       'kkpl',
       'kkpz',
       'kkpt',
       'kkp'],
 'q': ['kkqy', 'kkqx', 'kkqq'],
 'r': ['kkr_03', 'kkr_25'],
 's': ['kkstb_269',
       'kkstb_270',
       'kkstb_229',
       'kkstb_429',
       'kkstb_112',
       'kkstb_30',
       'kkstb_73',
       'kkstb_97',
       'kkstb_99',
       'kkstb_6',
       'kks_3'],
 't': ['kktc_telsim'],
 'u': ['kkul-tarae',
       'kkulppang',
       'kkusum',
       'kkup',
       'kkut',
       'kkus',
       'kkuu',
       'kkum',
       'kku'],
 'v': ['kkv_guitar'],
 'w': ['kkwaenggwari',
       'kkwb',
       'kkwa',
       'kkwn',
       'kkwf',
       'kkwq',
       'kkwy',
       'kkws',
       'kkwe',
       'kkwk',
       'kkwz',
       'kkwd'],
 'x': ['kkxx-fm', 'kkxl-fm', 'kkxk', 'kkxt', 'kkxa', 'kkxx', 'kkxs', 'kkxl'],
 'y': ['kkyn-fm',
       'kkyr-fm',
       'kkyk-cd',
       'kkyc',
       'kkys',
       'kkyx',
       'kkyz',
       'kkya',
       'kkyy',
       'kkyk',
       'kky'],
 'z': ['kkzn', 'kkzu', 'kkzz', 'kkzx', 'kkzi', 'kkzq', 'kkzy']}
