
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dm = {'_': ['dm-crypt',
       'dm-arena',
       'dm-cache',
       'dm-41',
       'dm2a4',
       'dm-1',
       'dm-2',
       'dm1',
       'dm2',
       'dm3'],
 'a': ['dmailer',
       'dmanisi',
       'dmalloc',
       'dmaic',
       'dmap1',
       'dmack',
       "dma's",
       'dmapi',
       'dmac1',
       'dmart',
       'dmarc',
       'dmaca',
       'dmab',
       'dmax',
       'dman',
       'dmaa',
       'dmap',
       'dmac',
       'dma'],
 'b': ['dmbmpp', 'dmbt1', 'dmba', 'dmbq', 'dmb'],
 'c': ['dmch', 'dmcm', 'dmcs', 'dmcc', 'dmc'],
 'd': ['dmdnb', 'dmdc', 'dmds', 'dmd'],
 'e': ['dmenin-wladyslawow',
       'dmenin-jozefka',
       'dmexco',
       'dmeide',
       'dmenin',
       'dmeob',
       'dmesg',
       'dmea',
       'dme'],
 'f': ['dmfas', 'dmfa', 'dmft', 'dmf'],
 'g': ['dmg'],
 'h': ['dmhc', 'dmhs', 'dmh'],
 'i': ['dmitro-pokrovskoye',
       'dmitriev-mamonov',
       'dmitryivanovite',
       'dmitryashevka',
       'dmitro-titovo',
       'dmitriyevsky',
       'dmitriyevka',
       'dmitriyevo',
       'dmitrikovo',
       'dmitrievka',
       'dmitrovsky',
       'dmitrovsk',
       'dmidecode',
       'dmitriyev',
       'dmitrieva',
       'dmitrovic',
       'dmitrovo',
       'dmitroce',
       'dmitrov',
       'dmitry',
       'dminin',
       'dmis',
       'dmi'],
 'k': ['dmk'],
 'l': ['dml'],
 'm': ['dmm.com', 'dmmda-2', 'dmmda', 'dmm'],
 'n': ['dmn'],
 'o': ['dmochy-rodzonki',
       'dmochy-wypychy',
       'dmochy-glinki',
       'dmochy-rogale',
       'dmochy-wochy',
       'dmochy-mrozy',
       'dmochy-retki',
       'dmosice',
       'dmosin',
       'dmol3',
       'dmoz',
       'dmo'],
 'p': ['dmpea',
       'dmps',
       'dmpl',
       'dmpe',
       'dmpa',
       'dmpu',
       'dmpx',
       'dmpk',
       'dmp1',
       'dmp'],
 'r': ['dmrt1', 'dmrc', 'dmr'],
 's': ['dms-1000', 'dms-100', 'dms-59', 'dmsms', 'dmss', 'dmst', 'dmsp', 'dms'],
 't': ['dmthf-tc', 'dmtmm', 'dmtf1', 'dmts', 'dmtx', 'dmtn', 'dmtv', 'dmt'],
 'u': ['dmusy', 'dmuta', 'dmu'],
 'v': ['dmv'],
 'w': ['dmwd', 'dmw'],
 'x': ['dmx512', 'dmxl2', 'dmx'],
 'y': ['dmytrenko', 'dmytrivka', 'dmytro'],
 'z': ['dmzglobal', 'dmz//38']}
