
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pn = {'a': ['pnac', 'pnar', 'pnau', 'pna'],
 'b': ['pnb'],
 'c': ['pnca', 'pnc'],
 'd': ['pnds', 'pnd'],
 'e': ['pneumonoultramicroscopicsilicovolcanoconiosis',
       'pneumoencephalography',
       'pneumoretroperitoneum',
       'pneumocystidomycetes',
       'pneumovesicoscopy',
       'pneumopericardium',
       'pneumomediastinum',
       'pneumophionyssus',
       'pneumodermatidae',
       'pneumospiruridae',
       'pneumoperitoneum',
       'pneumoparotitis',
       'pneumatoarthrus',
       'pneumonyssoides',
       'pneumoconiosis',
       'pneumatopteris',
       'pneumocephalus',
       'pneumocystosis',
       'pneumatoraptor',
       'pneumonectomy',
       'pneumoviridae',
       'pneumatherapy',
       'pneumatostega',
       'pneumotherapy',
       'pneumonolysis',
       'pneumatosophy',
       'pneumoscrotum',
       'pneumolaelaps',
       'pneumatomachi',
       'pneumatolysis',
       'pneumothorax',
       'pneumatology',
       'pneudraulics',
       'pneumodesmus',
       'pneumatocele',
       'pneumatocyst',
       'pneumograph',
       'pneumolysin',
       'pneumatosis',
       'pneumoridae',
       'pneumonitis',
       'pneumostome',
       'pneumobilia',
       'pneumaturia',
       'pneumatics',
       'pneumatode',
       'pneumonia',
       'pneumonic',
       'pnetluky',
       'pneurop',
       'pneuma',
       'pnet',
       'pnec',
       'pne'],
 'f': ['pnf'],
 'g': ['pngcrush', 'pngout', 'png'],
 'h': ['pnhs', 'pnh'],
 'i': ['pniewo-czeruchy',
       'pniewo-kolonia',
       'pnigmothrips',
       'pnigomantis',
       'pnigomenus',
       'pniewiski',
       'pnirontis',
       'pnictogen',
       'pnigodes',
       'pniewnik',
       'pniewite',
       'pnigalio',
       'pniewie',
       'pniewko',
       'pniewki',
       'pniowno',
       'pniowe',
       'pniaki',
       'pniewo',
       'pniese',
       'pniewy',
       'pnivne',
       'pniski',
       'pniel',
       'pnisr',
       'pnina',
       'pniow',
       'pnin',
       'pniv',
       'pni'],
 'k': ['pnkp', 'pnkd', 'pnk'],
 'l': ['pnld', 'pnl'],
 'm': ['pnmsoft', 'pnma8a', 'pnma2', 'pnml', 'pnm'],
 'n': ['pnn'],
 'o': ['pnov-predhradi', 'pnoepyga', 'pnovany', 'pnovice', 'pno1', 'pno'],
 'p': ['pnpsat-1', 'pnpla3', 'pnpla8', 'pnpase', 'pnp'],
 'r': ['pnrc2', 'pnrc1', 'pnra'],
 's': ['pnsc', 'pns'],
 't': ['pntm', 'pntl', 'pnt'],
 'u': ['pnu-120,596',
       'pnu-282,987',
       'pnu-142633',
       'pnu-181731',
       'pnu-99,194',
       'pnu-91356a',
       'pnu-22394',
       'pnuts',
       'pnu'],
 'v': ['pnv-ea', 'pnv'],
 'w': ['pnw'],
 'x': ['pnx'],
 'y': ['pnytagoras', 'pnyxia', 'pnyx', 'pny'],
 'z': ['pnz']}
