
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mg = {'_': ['mg-rast',
       'mg-111',
       'mg-167',
       'mg-050',
       'mg132',
       'mg14',
       'mg1',
       'mg2',
       'mg5',
       'mg4'],
 'a': ['mgaloblishvili',
       'mgambonyi',
       'mgamboni',
       'mgazini',
       'mgandu',
       'mgarjs',
       'mgat5b',
       'mgat4b',
       'mgange',
       'mgat5',
       'mgama',
       'mgat1',
       'mgat2',
       'mgarr',
       'mgat3',
       'mgac',
       'mga'],
 'b': ['mgbidi', 'mgboko', 'mgb2', 'mgb'],
 'c': ['mgc50722', 'mgc3207', 'mgcu2', 'mgcp', 'mgc1', 'mgc'],
 'd': ['mgd'],
 'e': ['mgeladze', 'mged', 'mgen', 'mge'],
 'f': ['mgf'],
 'g': ['mgga'],
 'h': ['mghayreh', 'mghart', 'mghs', 'mgh'],
 'i': ['mgimwa', 'mgi'],
 'l': ['mglinsky', 'mglin', 'mgla', 'mgl'],
 'm': ['mgm/ua', 'mgme1', 'mgmt'],
 'n': ['mgn'],
 'o': ['mgoszcz',
       'mgombom',
       'mgongo',
       'mgodi',
       'mgowo',
       'mgori',
       'mgo2',
       'mgo'],
 'p': ['mgp'],
 's': ['mgs-0039', 'mgscomm', 'mgs/lrs', 'mgst2', 'mgst3', 'mgsm', 'mgs'],
 't': ['mgtow', 'mgtk', 'mgtv', 'mgta', 'mgt'],
 'u': ['mgungira', 'mguya'],
 'v': ['mgv-176', 'mgv'],
 'w': ['mgw'],
 'x': ['mgx'],
 'y': ['mgy'],
 'z': ['mgz']}
