
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mw = {'_': ['mw-1', 'mw08', 'mw2', 'mw3'],
 'a': ['mwananyamala',
       'mwakinyungu',
       'mwadingusha',
       'mwanathumba',
       'mwambathana',
       'mwakeitari',
       'mwakirunge',
       'mwanachini',
       'mwaluvanga',
       'mwangareme',
       'mwarakaya',
       'mwathaini',
       'mwansanga',
       'mwaketutu',
       'mwasumbia',
       'mwansekwa',
       'mwangangi',
       'mwashinga',
       'mwandishi',
       'mwakibete',
       'mwamkuchi',
       'mwanzele',
       'mwangini',
       'mwangulu',
       'mwangata',
       'mwarungu',
       'mwandeti',
       'mwambiri',
       'mwakwala',
       'mwanhuzi',
       'mwandoni',
       'mwangeza',
       'mwambani',
       'mwaiseni',
       'mwanyora',
       'mwangoni',
       'mwandimu',
       'mwakunde',
       'mwankoko',
       'mwaembe',
       'mwasiti',
       'mwazare',
       'mwayaya',
       'mwalili',
       'mwabila',
       'mwatisi',
       'mwabani',
       'mwanuku',
       'mwatate',
       'mwansa',
       'mwalau',
       'mwandi',
       'mwanza',
       'mwangi',
       'mwalim',
       'mwanga',
       'mwanzo',
       'mwanda',
       'mwape',
       'mwata',
       'mwave',
       'mwaga',
       'mwari',
       'mwana',
       'mwada',
       'mwazi',
       'mwale',
       'mwaro',
       'mwami',
       'mwaya',
       'mwaru',
       'mwa'],
 'b': ['mwb'],
 'c': ['mwcd', 'mwc'],
 'd': ['mwdwl-eithin', 'mwd'],
 'e': ['mwenezi-chivi',
       'mwene-ditu',
       'mweelrea',
       'mwebantu',
       'mweileh',
       'mwenge',
       'mweiga',
       'mwe-te',
       'mwenda',
       'mwembe',
       'mweri',
       'mwesa',
       'mwewe',
       'mwera',
       'mweru',
       'mwele',
       'mweza',
       'mweka',
       'mweya',
       'mwema',
       'mweb',
       'mwe'],
 'f': ['mwfl', 'mwf'],
 'g': ['mwg'],
 'h': ['mwhs', 'mwhl', 'mwh'],
 'i': ['mwinilunga',
       'mwitikila',
       'mwimuto',
       'mwiyogo',
       'mwinda',
       'mwingi',
       'mwi'],
 'l': ['mwl'],
 'm': ['mwm'],
 'n': ['mwng', 'mwnt', 'mwn'],
 'o': ['mwogahendi', 'mwo'],
 'p': ['mwp'],
 'r': ['mwrank', 'mwr'],
 's': ['mwsa', 'mws'],
 'u': ['mwuetsi', 'mwua', 'mwu'],
 'v': ['mwv'],
 'w': ['mww']}
