
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gp = {'_': ['gp_strategies_corporation',
       'gp_betonexpressz_2000',
       'gp_express_airlines',
       'gp_slovenian_istria',
       'gp_miguel_indurain',
       'gp_comae_berenices',
       'gp_liberty_seguros',
       'gp_stad_vilvoorde',
       'gp_patient_survey',
       'gp_stad_roeselare',
       'gp_erik_breukink',
       'gp36_hol_family',
       'gp2_asia_series',
       'gp_adria_mobil',
       'gp20_rna_motif',
       'gp_sofie_goos',
       'gp-1:_part_ii',
       'gp-5_gas_mask'],
 'c': ['gpcr_neuropeptide_receptor'],
 'd': ['gpd_win_max', 'gpd_win_2', 'gpd_win_3'],
 'e': ['gpe_palmtop_environment'],
 'l': ['gpl_linking_exception', 'gpl_font_exception'],
 'n': ['gpn-loop_gtpase_3'],
 'o': ['gpo_nursing_contingent', 'gpo_film_unit'],
 'r': ['gprs_tunnelling_protocol',
       'gprs_roaming_exchange',
       'gprs_core_network'],
 's': ['gps_disciplined_oscillator',
       'gps_aircraft_tracking',
       'gps_satellite_blocks',
       'gps_portland_phoenix',
       'gps_exchange_format',
       'gps_animal_tracking',
       'gps_tracking_unit',
       'gps_block_iiif',
       'gps_block_iii',
       'gps_block_iif',
       'gpso_92_issy'],
 'y': ['gpyw_indoor_stadium']}
