
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gb = {'_': ['gb_pro-series_loughborough',
       'gb_pro-series_shrewsbury',
       'gb_pro-series_glasgow',
       'gb_theatre_company',
       'gb_virus_c',
       'gb_class_1',
       'gb_class_3',
       'gb_class_2'],
 'a': ['gbanti_kamaranka_chiefdom',
       'gbagada_general_hospital',
       'gbane_kandor_chiefdom',
       'gbagbo_junior_magbi',
       'gbahi_gwladys_sakoa'],
 'c': ['gbc_international_bank', 'gbc_asset_management'],
 'e': ['gbendembu_ngowahun_chiefdom',
       'gbehzohngar_milton_findley',
       'gbemisola_ruqayyah_saraki',
       'gbemileke_"oscar"_oyinsan',
       'gbedikpe_emmanuel_amouzou',
       'gbemi_olateru_olagbegi',
       'gbele_resource_centre',
       'gbenga_bareehu_ashafa'],
 'i': ['gbinle_dixing_chiefdom'],
 'o': ['gbolahan_olusegun_yishawu',
       'gboribiogha_john_jonah',
       'gborogboro_and_meme',
       'gbomo_gbomo_express'],
 'u': ['gbu-37_gps-aided_munition',
       'gbu-44/b_viper_strike',
       'gbu_indoor_stadium',
       'gbu-24_paveway_iii',
       'gbu-27_paveway_iii',
       'gbu-10_paveway_ii',
       'gbu-12_paveway_ii',
       'gbu-16_paveway_ii']}
