
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tk = {'_': ["tk'tk'tk", 'tk90x', 'tk-80', 'tk82c', 'tk95', 'tk-3', 'tk85'],
 'a': ['tkachenko',
       'tkaronto',
       'tkachyov',
       'tkaczyk',
       'tkachuk',
       'tkaczew',
       'tkabber',
       'tkatka',
       'tkalci',
       'tkalec',
       'tkach',
       'tkacz',
       'tkay',
       'tkac',
       'tka'],
 'b': ['tkb-022pm',
       'tkb-0146',
       'tkb-506',
       'tkb-408',
       'tkb-011',
       'tkb-072',
       'tkb-010',
       'tkb-059',
       'tkb-517',
       'tkb'],
 'c': ['tkc'],
 'd': ['tkdiff', 'tkdesk'],
 'e': ['tkeshelashvili', 'tkemali', 'tke'],
 'f': ['tkf'],
 'g': ['tkg'],
 'h': ['tkhmori', 'tkhkot', 'tkhuma', 'tkhine', 'tkhtml', 'tkhkut'],
 'i': ['tkinter', 'tkibuli', 'tkinzy', 'tkiet', 'tkip', 'tki'],
 'k': ['tkkg'],
 'l': ['tklania', 'tklapi', 'tkl'],
 'm': ['tkm-ebola', 'tkm'],
 'o': ['tkoutt', 'tkocz', 'tkon', 'tkol', 'tkoh', 'tkor', 'tko'],
 'p': ['tkp'],
 'r': ['tkrzw', 'tkr'],
 's': ['tkss', 'tks'],
 't': ['tktl1', 'tktl2', 'tkts', 'tktv', 'tkt'],
 'u': ['tkuma', 'tku'],
 'v': ['tkvarcheli'],
 'w': ['tkwww', 'tkw'],
 'z': ['tkzee', 'tkz']}
