# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hansken_extraction_plugin/framework/PrimitiveMessages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;hansken_extraction_plugin/framework/PrimitiveMessages.proto\x12\"org.hansken.extraction.plugin.grpc\x1a\x19google/protobuf/any.proto\"\t\n\x07RpcNull\"\x19\n\x08RpcBytes\x12\r\n\x05value\x18\x01 \x01(\x0c\"\x1b\n\nRpcBoolean\x12\r\n\x05value\x18\x01 \x01(\x08\"\x1b\n\nRpcInteger\x12\r\n\x05value\x18\x01 \x01(\x05\"\x18\n\x07RpcLong\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1a\n\tRpcDouble\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1a\n\tRpcString\x12\r\n\x05value\x18\x01 \x01(\t\"1\n\nRpcLatLong\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"\x1c\n\x0bRpcUnixTime\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1a\n\tRpcVector\x12\r\n\x05value\x18\x01 \x01(\x0c\"a\n\x10RpcZonedDateTime\x12\x13\n\x0b\x65pochSecond\x18\x01 \x01(\x03\x12\x14\n\x0cnanoOfSecond\x18\x02 \x01(\x05\x12\x12\n\nzoneOffset\x18\x03 \x01(\t\x12\x0e\n\x06zoneId\x18\x04 \x01(\t\"!\n\x10RpcIsoDateString\x12\r\n\x05value\x18\x01 \x01(\t\"\x0e\n\x0cRpcEmptyList\"\x1f\n\rRpcStringList\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1d\n\x0bRpcLongList\x12\x0e\n\x06values\x18\x01 \x03(\x03\"\r\n\x0bRpcEmptyMap\"\x92\x01\n\x0cRpcStringMap\x12N\n\x07\x65ntries\x18\x01 \x03(\x0b\x32=.org.hansken.extraction.plugin.grpc.RpcStringMap.EntriesEntry\x1a.\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01:\x02\x18\x01\"\x98\x01\n\x06RpcMap\x12H\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x37.org.hansken.extraction.plugin.grpc.RpcMap.EntriesEntry\x1a\x44\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x42&\n\"org.hansken.extraction.plugin.grpcP\x01\x62\x06proto3')



_RPCNULL = DESCRIPTOR.message_types_by_name['RpcNull']
_RPCBYTES = DESCRIPTOR.message_types_by_name['RpcBytes']
_RPCBOOLEAN = DESCRIPTOR.message_types_by_name['RpcBoolean']
_RPCINTEGER = DESCRIPTOR.message_types_by_name['RpcInteger']
_RPCLONG = DESCRIPTOR.message_types_by_name['RpcLong']
_RPCDOUBLE = DESCRIPTOR.message_types_by_name['RpcDouble']
_RPCSTRING = DESCRIPTOR.message_types_by_name['RpcString']
_RPCLATLONG = DESCRIPTOR.message_types_by_name['RpcLatLong']
_RPCUNIXTIME = DESCRIPTOR.message_types_by_name['RpcUnixTime']
_RPCVECTOR = DESCRIPTOR.message_types_by_name['RpcVector']
_RPCZONEDDATETIME = DESCRIPTOR.message_types_by_name['RpcZonedDateTime']
_RPCISODATESTRING = DESCRIPTOR.message_types_by_name['RpcIsoDateString']
_RPCEMPTYLIST = DESCRIPTOR.message_types_by_name['RpcEmptyList']
_RPCSTRINGLIST = DESCRIPTOR.message_types_by_name['RpcStringList']
_RPCLONGLIST = DESCRIPTOR.message_types_by_name['RpcLongList']
_RPCEMPTYMAP = DESCRIPTOR.message_types_by_name['RpcEmptyMap']
_RPCSTRINGMAP = DESCRIPTOR.message_types_by_name['RpcStringMap']
_RPCSTRINGMAP_ENTRIESENTRY = _RPCSTRINGMAP.nested_types_by_name['EntriesEntry']
_RPCMAP = DESCRIPTOR.message_types_by_name['RpcMap']
_RPCMAP_ENTRIESENTRY = _RPCMAP.nested_types_by_name['EntriesEntry']
RpcNull = _reflection.GeneratedProtocolMessageType('RpcNull', (_message.Message,), {
  'DESCRIPTOR' : _RPCNULL,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcNull)
  })
_sym_db.RegisterMessage(RpcNull)

RpcBytes = _reflection.GeneratedProtocolMessageType('RpcBytes', (_message.Message,), {
  'DESCRIPTOR' : _RPCBYTES,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcBytes)
  })
_sym_db.RegisterMessage(RpcBytes)

RpcBoolean = _reflection.GeneratedProtocolMessageType('RpcBoolean', (_message.Message,), {
  'DESCRIPTOR' : _RPCBOOLEAN,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcBoolean)
  })
_sym_db.RegisterMessage(RpcBoolean)

RpcInteger = _reflection.GeneratedProtocolMessageType('RpcInteger', (_message.Message,), {
  'DESCRIPTOR' : _RPCINTEGER,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcInteger)
  })
_sym_db.RegisterMessage(RpcInteger)

RpcLong = _reflection.GeneratedProtocolMessageType('RpcLong', (_message.Message,), {
  'DESCRIPTOR' : _RPCLONG,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcLong)
  })
_sym_db.RegisterMessage(RpcLong)

RpcDouble = _reflection.GeneratedProtocolMessageType('RpcDouble', (_message.Message,), {
  'DESCRIPTOR' : _RPCDOUBLE,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcDouble)
  })
_sym_db.RegisterMessage(RpcDouble)

RpcString = _reflection.GeneratedProtocolMessageType('RpcString', (_message.Message,), {
  'DESCRIPTOR' : _RPCSTRING,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcString)
  })
_sym_db.RegisterMessage(RpcString)

RpcLatLong = _reflection.GeneratedProtocolMessageType('RpcLatLong', (_message.Message,), {
  'DESCRIPTOR' : _RPCLATLONG,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcLatLong)
  })
_sym_db.RegisterMessage(RpcLatLong)

RpcUnixTime = _reflection.GeneratedProtocolMessageType('RpcUnixTime', (_message.Message,), {
  'DESCRIPTOR' : _RPCUNIXTIME,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcUnixTime)
  })
_sym_db.RegisterMessage(RpcUnixTime)

RpcVector = _reflection.GeneratedProtocolMessageType('RpcVector', (_message.Message,), {
  'DESCRIPTOR' : _RPCVECTOR,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcVector)
  })
_sym_db.RegisterMessage(RpcVector)

RpcZonedDateTime = _reflection.GeneratedProtocolMessageType('RpcZonedDateTime', (_message.Message,), {
  'DESCRIPTOR' : _RPCZONEDDATETIME,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcZonedDateTime)
  })
_sym_db.RegisterMessage(RpcZonedDateTime)

RpcIsoDateString = _reflection.GeneratedProtocolMessageType('RpcIsoDateString', (_message.Message,), {
  'DESCRIPTOR' : _RPCISODATESTRING,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcIsoDateString)
  })
_sym_db.RegisterMessage(RpcIsoDateString)

RpcEmptyList = _reflection.GeneratedProtocolMessageType('RpcEmptyList', (_message.Message,), {
  'DESCRIPTOR' : _RPCEMPTYLIST,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcEmptyList)
  })
_sym_db.RegisterMessage(RpcEmptyList)

RpcStringList = _reflection.GeneratedProtocolMessageType('RpcStringList', (_message.Message,), {
  'DESCRIPTOR' : _RPCSTRINGLIST,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcStringList)
  })
_sym_db.RegisterMessage(RpcStringList)

RpcLongList = _reflection.GeneratedProtocolMessageType('RpcLongList', (_message.Message,), {
  'DESCRIPTOR' : _RPCLONGLIST,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcLongList)
  })
_sym_db.RegisterMessage(RpcLongList)

RpcEmptyMap = _reflection.GeneratedProtocolMessageType('RpcEmptyMap', (_message.Message,), {
  'DESCRIPTOR' : _RPCEMPTYMAP,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcEmptyMap)
  })
_sym_db.RegisterMessage(RpcEmptyMap)

RpcStringMap = _reflection.GeneratedProtocolMessageType('RpcStringMap', (_message.Message,), {

  'EntriesEntry' : _reflection.GeneratedProtocolMessageType('EntriesEntry', (_message.Message,), {
    'DESCRIPTOR' : _RPCSTRINGMAP_ENTRIESENTRY,
    '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
    # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcStringMap.EntriesEntry)
    })
  ,
  'DESCRIPTOR' : _RPCSTRINGMAP,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcStringMap)
  })
_sym_db.RegisterMessage(RpcStringMap)
_sym_db.RegisterMessage(RpcStringMap.EntriesEntry)

RpcMap = _reflection.GeneratedProtocolMessageType('RpcMap', (_message.Message,), {

  'EntriesEntry' : _reflection.GeneratedProtocolMessageType('EntriesEntry', (_message.Message,), {
    'DESCRIPTOR' : _RPCMAP_ENTRIESENTRY,
    '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
    # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcMap.EntriesEntry)
    })
  ,
  'DESCRIPTOR' : _RPCMAP,
  '__module__' : 'hansken_extraction_plugin.framework.PrimitiveMessages_pb2'
  # @@protoc_insertion_point(class_scope:org.hansken.extraction.plugin.grpc.RpcMap)
  })
_sym_db.RegisterMessage(RpcMap)
_sym_db.RegisterMessage(RpcMap.EntriesEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"org.hansken.extraction.plugin.grpcP\001'
  _RPCSTRINGMAP_ENTRIESENTRY._options = None
  _RPCSTRINGMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _RPCSTRINGMAP._options = None
  _RPCSTRINGMAP._serialized_options = b'\030\001'
  _RPCMAP_ENTRIESENTRY._options = None
  _RPCMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _RPCNULL._serialized_start=126
  _RPCNULL._serialized_end=135
  _RPCBYTES._serialized_start=137
  _RPCBYTES._serialized_end=162
  _RPCBOOLEAN._serialized_start=164
  _RPCBOOLEAN._serialized_end=191
  _RPCINTEGER._serialized_start=193
  _RPCINTEGER._serialized_end=220
  _RPCLONG._serialized_start=222
  _RPCLONG._serialized_end=246
  _RPCDOUBLE._serialized_start=248
  _RPCDOUBLE._serialized_end=274
  _RPCSTRING._serialized_start=276
  _RPCSTRING._serialized_end=302
  _RPCLATLONG._serialized_start=304
  _RPCLATLONG._serialized_end=353
  _RPCUNIXTIME._serialized_start=355
  _RPCUNIXTIME._serialized_end=383
  _RPCVECTOR._serialized_start=385
  _RPCVECTOR._serialized_end=411
  _RPCZONEDDATETIME._serialized_start=413
  _RPCZONEDDATETIME._serialized_end=510
  _RPCISODATESTRING._serialized_start=512
  _RPCISODATESTRING._serialized_end=545
  _RPCEMPTYLIST._serialized_start=547
  _RPCEMPTYLIST._serialized_end=561
  _RPCSTRINGLIST._serialized_start=563
  _RPCSTRINGLIST._serialized_end=594
  _RPCLONGLIST._serialized_start=596
  _RPCLONGLIST._serialized_end=625
  _RPCEMPTYMAP._serialized_start=627
  _RPCEMPTYMAP._serialized_end=640
  _RPCSTRINGMAP._serialized_start=643
  _RPCSTRINGMAP._serialized_end=789
  _RPCSTRINGMAP_ENTRIESENTRY._serialized_start=739
  _RPCSTRINGMAP_ENTRIESENTRY._serialized_end=785
  _RPCMAP._serialized_start=792
  _RPCMAP._serialized_end=944
  _RPCMAP_ENTRIESENTRY._serialized_start=876
  _RPCMAP_ENTRIESENTRY._serialized_end=944
# @@protoc_insertion_point(module_scope)
