
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tb = {'_': ['tb-21007', 'tb1', 'tb3', 'tb2'],
 'a': ['tbaytel', 'tbars'],
 'b': ['tbbs', 'tbb'],
 'c': ['tbc1d10a',
       'tbc1d12',
       'tbc1d30',
       'tbc1d24',
       'tbc1d15',
       'tbc1d1',
       'tbc1d3',
       'tbc1d9',
       'tbc1d4',
       'tbcc',
       'tbcb',
       'tbca',
       'tbce',
       'tbcd'],
 'd': ['tbd.com'],
 'e': ['tbeti', 'tbea', 'tbe'],
 'f': ['tbf'],
 'g': ['tbg'],
 'h': ['tbhs', 'tbh'],
 'i': ['tbilisi-tbilisi',
       'tbilisskaya',
       'tbilissky',
       'tbilisoba',
       'tbilisi',
       'tbilat',
       'tbi'],
 'j': ['tbjhome', 'tbjzl', 'tbj'],
 'k': ['tbk1', 'tbk'],
 'l': ['tbl1xr1', 'tbl-37', 'tbl1x', 'tbl3', 'tbl'],
 'm': ['tbm'],
 'n': ['tbna', 'tbn'],
 'o': ['tboli', 'tbox', 'tbo'],
 'p': ['tbpl1', 'tbps', 'tbpo', 'tbp'],
 'q': ['tbqh'],
 'r': ['tbr21', 'tbrg1', 'tbrg4', 'tbrb', 'tbr1', 'tbri', 'tbr'],
 's': ['tbst', 'tbs'],
 't': ['tbtbt', 'tbt'],
 'u': ['tbu'],
 'v': ['tbv'],
 'w': ['tbwa\\chiat\\day', 'tbw'],
 'x': ['tbx21',
       'tbx19',
       'tbx22',
       'tbx20',
       'tbx15',
       'tbx3',
       'tbx6',
       'tbx1',
       'tbx2',
       'tbx4'],
 'y': ['tby'],
 'z': ['tbz']}
