
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tp = {'_': ['tp-seinajoki',
       'tp53inp1',
       'tp73-as1',
       'tp-2.com',
       'tp53cor1',
       'tp53i11',
       'tp53tg1',
       'tp-link',
       'tp53bp1',
       'tp53bp2',
       'tp-003',
       'tp53i3',
       'tp53rk',
       'tp-47',
       'tp-13',
       'tp-70',
       'tp63',
       'tp9'],
 'a': ['tpa-023', 'tpac', 'tpap', 'tpao', 'tpa'],
 'b': ['tpbg', 'tpb'],
 'c': ['tpc-5cn',
       'tpcn2',
       'tpcit',
       'tpc-c',
       'tpcn1',
       'tpc-w',
       'tpcc',
       'tpcp',
       'tpcs',
       'tpcd',
       'tpca',
       'tpc'],
 'd': ['tpd52l1', 'tpd52l2', 'tpd52', 'tpdf', 'tpdc', 'tpd'],
 'e': ['tpen', 'tpeg', 'tpec', 'tper', 'tpe'],
 'f': ['tpf'],
 'g': ['tpg-1', 'tpg'],
 'h': ['tph1', 'tphs', 'tph2', 'tph'],
 'i': ['tpi1', 'tpig', 'tpia', 'tpi'],
 'j': ['tpj'],
 'k': ['tpk1', 'tpk'],
 'l': ['tpl'],
 'm': ['tpmcafe', 'tpm4', 'tpms', 'tpm1', 'tpm2', 'tpm'],
 'n': ['tpnw', 'tpn'],
 'o': ['tpoint', 'tpon', 'tpo'],
 'p': ['tppts', 'tppp', 'tppd', 'tppa', 'tpp'],
 'q': ['tpq'],
 'r': ['tpr'],
 's': ['tpsab1', 'tpsd1', 'tpsb2', 'tpsg1', 'tpsc', 'tpsa', 'tps'],
 't': ['tptp', 'tpt1', 'tpte', 'tpt'],
 'u': ['tput', 'tpu'],
 'v': ['tpv'],
 'w': ['tpws', 'tpw'],
 'x': ['tpx2', 'tpx'],
 'y': ['tpy-2'],
 'z': ['tpz']}
