
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sg = {'_': ['sg_barockstadt_fulda-lehnerz',
       'sg_dynamo_hohenschonhausen',
       'sg_sonnenhof_grossaspach',
       'sg_volkspolizei_potsdam',
       'sg_gesundbrunnen_berlin',
       'sg_wannabe_discography',
       'sg_post/sud_regensburg',
       'sg_germania_wiesbaden',
       "sg_waspo'98_hannover",
       'sg_stadtmitte_berlin',
       'sg_dynamo_magdeburg',
       'sg_dynamo_zinnwald',
       'sg_wattenscheid_09',
       'sg_union_solingen',
       'sg_bbm_bietigheim',
       'sg_dynamo_erfurt',
       'sg_ss_strassburg',
       'sg_dynamo_berlin',
       'sg_postcode_area',
       'sg_quelle_furth',
       'sg_bad_breisig',
       'sg_orpo_danzig',
       'sg_01_hoechst',
       'sg_wanna_be+'],
 'a': ['sgarro_alla_camorra'],
 'b': ['sgb_championship_2021',
       'sgb_championship_2019',
       'sgb_championship_2018',
       'sgb_championship_2022',
       'sgb_championship_2017',
       'sgb_premiership_2021',
       'sgb_premiership_2019',
       'sgb_premiership_2017',
       'sgb_premiership_2022',
       'sgb_premiership_2018'],
 'f': ['sgfc_eagles_maryland'],
 'h': ["sghair_ould_m'bareck", 'sgh_war_memorial'],
 'i': ['sgi_visual_workstation',
       'sgi_origin_2000',
       'sgi_origin_200',
       'sgi_origin_350'],
 'm': ['sgmw_motor_indonesia'],
 'o': ['sgorr_na_diollaid'],
 'p': ['sgp_m-222_flamingo', 'sgpta_pu_college'],
 't': ['sgt._kabukiman_n.y.p.d.',
       "sgt._saunders'_combat!",
       'sgt._will_gardner',
       'sgt._pepper_live',
       'sgt._york_trophy'],
 'u': ["sgurr_a'_choire-bheithe",
       'sgurr_nan_ceannaichean',
       'sgurr_nan_ceathramhnan',
       'sgurr_nan_conbhairean',
       'sgurr_na_banachdaich',
       'sgurr_mhic_bharraich',
       "sgurr_a'_ghreadaidh",
       'sgurr_an_fhidhleir',
       "sgurr_a'_mhaoraich",
       "sgurr_a'_mhadaidh",
       'sgurr_na_h-ulaidh',
       'sgurr_nan_eugallt',
       "sgurr_a'_mhuilinn",
       'sgurr_nan_gillean',
       "sgurr_a'_gharaidh",
       'sgurr_na_coinnich',
       'sgurr_na_feartaig',
       'sgurr_na_lapaich',
       'sgurr_na_carnach',
       'sgurr_an_airgid',
       'sgurr_eilde_mor',
       'sgurr_na_ciche',
       'sgurr_dubh_mor',
       'sgurr_nan_each',
       'sgurr_na_sgine',
       "sgurr_a'_mhaim",
       'sgurr_nan_eag'],
 'x': ['sgx_sensortech_limited']}
