
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tv = {'_': ['tv_moldova_international',
       "tv's_naughtiest_blunders",
       'tv_mast_niort-maisonnay',
       'tv_france_international',
       'tv_brasil_internacional',
       'tv_tennis_electrotennis',
       'tv_amriswil_volleyball',
       'tv_globo_internacional',
       'tv_parental_guidelines',
       'tv_sports:_basketball',
       'tv_dos_trabalhadores',
       'tv_land_confidential',
       'tv1000_russkoe_kino',
       'tv_cidade_fortaleza',
       'tv_network_protocol',
       'tv4_science_fiction',
       'tv_sports:_football',
       "tv_reader's_digest",
       'tv1000_action_east',
       'tv_2_nyhetskanalen',
       'tv_camara_jacarei',
       'tv_1893_neuhausen',
       'tv_globo_portugal',
       'tv_guide_magazine',
       'tv5_quebec_canada',
       'tv_2_filmkanalen',
       'tv_de_mauritanie',
       'tv5_media_center',
       'tv_sao_francisco',
       'tv_today_network',
       'tv_jahn_hiesfeld',
       'tv_channel_16/12',
       'tv_detector_van',
       'tv_action_jazz!',
       "tv's_top_themes",
       'tv_out_chipsets',
       'tv5_monde_style',
       'tv_verdes_mares',
       'tv_one_pakistan',
       'tv_talent_scout',
       'tv_gospel_time',
       'tv_disc_jockey',
       'tv_aerial_plug',
       'tv_guide_award',
       'tv_travel_shop',
       'tv_star_meikan',
       'tv_en_francais',
       'tv_2_nyhetene',
       'tv_1860_furth',
       'tv_santa_cruz',
       'tv_palma_plus',
       'tv_century_21',
       'tv_slon_extra',
       'tv_tuner_card',
       'tv_now_awards',
       'tv_di_fastweb',
       'tv_2_livsstil',
       'tv_cerro_cora',
       'tv_land_award',
       'tv_tray_table',
       'tv_show_king',
       'tv_jovem_pan',
       'tv_2_charlie',
       'tv_dober_dan',
       'tv_5_dimensi',
       'tv4_fakta_xl',
       'tv_canaria_2',
       'tv_la_verdad',
       'tv3_toy_show',
       'tv_bel_kanal',
       'tv3_sport_2',
       'tv_da_gente',
       'tv_2_radio',
       'tv_2_sport',
       'tv_nova_12',
       'tv_2_group',
       'tv_2_bliss',
       'tv_2_zebra',
       'tv_2_film',
       'tv_2_play',
       'tv_tan_ep',
       'tv_2_news',
       'tv_one_hd',
       'tv_2_zulu',
       'tv_2_fri',
       'tv_to_go'],
 'a': ['tvarozna,_kezmarok_district',
       'tvarditsa,_dobrich_province',
       'tvarditsa,_burgas_province',
       'tvarditsa,_sliven_province',
       'tvare_pred_zrkadlom',
       'tvar_pod_maskou',
       'tva_morka_ogon',
       'tva_av_oss'],
 'b': ['tvbs_entertainment_channel',
       'tvb_anniversary_awards',
       'tvb_network_vision',
       'tvb_korea_channel',
       'tvb_news_channel',
       'tvb_xing_he'],
 'e': ["tvec_les_sables-d'olonne",
       'tverskaya_zastava_square',
       'tver_state_university',
       'tversity_media_server',
       'tver_railway_station',
       'tver_garment_factory',
       'tver_river_terminal',
       'tver_carriage_works',
       'tve_test_card',
       'tveir_a_bati',
       'tve_50_anos'],
 'i': ['tvin_carole_moumjoghlian'],
 'n': ['tvn_international_extra', 'tvnz_sport_extra'],
 'o': ['tvornica_autobusa_zagreb', 'tvost_og_spik'],
 'p': ['tvp3_gorzow_wielkopolski'],
 'q': ['tvq_kyushu_broadcasting'],
 'r': ['tvri_sulawesi_selatan',
       'tvr_tuscan_challenge',
       'tvri_sumatera_utara',
       'tvr_griffith_400',
       'tvrtko_of_bosnia',
       'tvr_griffith_200',
       'tvr_m_series',
       'tvr_s_series',
       'tvr_420_seac',
       'tvr_450_seac'],
 's': ['tvs_television_network',
       'tvs_motor_company',
       'tvs_ntorq_125',
       'tvs_scs_rico'],
 'x': ['tvxq_singles_discography',
       'tvxq_albums_discography',
       'tvx_broadcast_group'],
 'y': ['tvynovelas_awards_colombia']}
