
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tj = {'_': ['tj_druzstevnik_vrakun',
       'tj_druzstevnik_danova',
       'tj_partizan_domaniza',
       'tj_valasske_mezirici',
       'tj_sklotatran_poltar',
       'tj_jiskra_domazlice',
       'tj_sokol_protivanov',
       'tj_slavia_lounovice',
       'tj_tatran_bohunice',
       'tj_ryan_foundation',
       'tj_sokol_zivanice',
       'tj_jednota_banova',
       'tj_banik_kalinovo',
       'tj_slovan_vinicne',
       'tj_rozvoj_pusovce',
       'tj_sokol_tasovice',
       'tj_mladost_kalsa',
       'tj_sokol_lanzhot',
       'tj_ofc_gabcikovo',
       'tj_banik_stadium',
       'tj_dvur_kralove',
       'tj_sokol_ovcary',
       'tj_smith_stakes',
       'tj_banik_ruzina',
       'tj_high_school',
       'tj_tempo_praha'],
 'a': ['tjapartji_kanytjuri_bates',
       'tjaskers_in_overijssel',
       'tjanpi_desert_weavers',
       'tjaskers_in_friesland',
       'tjangvide_image_stone',
       'tjaskers_in_drenthe',
       'tjaskers_in_germany',
       'tjaart_du_plessis',
       'tjapko_van_bergen',
       'tjako_van_schie',
       'tjark_de_vries',
       'tjan_tjoe_som',
       'tjakko_de_vos',
       'tjay_de_barr'],
 'e': ['tjeld-class_patrol_boat',
       'tjele_helmet_fragment',
       'tjerita_njai_dasima',
       'tjejer_and_snubbar',
       'tjeerd_van_dekken',
       'tjerita_si_tjonat',
       'tjebbe_van_tijen',
       'tjerita_oeij_se'],
 'h': ['tjhit_liap_seng'],
 'i': ['tjilik_riwut_airport', 'tjintu_desert_band'],
 'o': ['tjokorda_raka_sukawati',
       'tjoeij_lin_alienilin',
       'tjock_och_lycklig',
       "tjoet_nja'_dhien",
       'tjorven_de_brul',
       'tjow_choon_boon',
       'tjong_yong_hian',
       'tjong_i_baljan!',
       'tjoe_de_paula',
       'tjoe_bou_san',
       'tjong_a_fie'],
 'u': ['tjuvholmen_sculpture_park', 'tjung_tin_jan']}
