
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-19T16:55:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "73ecddb08d64c09e0a8e6f72f4a3bfe2c69535c9",
 "version": "0.9.64"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
