
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vs = {'_': ['vs-satm1_mine',
       'vs._children',
       'vs-1.6_mine',
       'vs-hct_mine',
       'vs-mk2_mine',
       'vs-jap_mine',
       'vs_ribozyme',
       'vs-at4_mine',
       'vs._system',
       'vs-50_mine',
       'vs._time',
       'vs._tour',
       'vs_art'],
 'a': ['vsauce', 'vsan', 'vsa'],
 'b': ['vsb-30', 'vsb-tv', 'vsb'],
 'c': ['vsco_girl'],
 'd': ['vsdx_annotator'],
 'e': ['vsemirnaya_illyustratsiya',
       'vsevolozhsk_constituency',
       'vsevolod_rozhdestvensky',
       'vsevolodas_dobuzinskis',
       'vseyasvetnaya_gramota',
       'vsevolod_gussakovskiy',
       'vsevolozhsky_district',
       'vsevolod_starosselsky',
       'vsevolod_ovchinnikov',
       'vsesportovni_stadion',
       'vsevolod_murakhovsky',
       'vsevolod_mstislavich',
       'vsevolod_klechkovsky',
       'vsevolod_lebedintsev',
       'vsevolod_zhuravlyov',
       'vsevolod_vishnevsky',
       'vsevolod_tarasevich',
       'vsevolod_abramovich',
       'vsevolod_krestovsky',
       'vsevolod_yanchevski',
       'vsevolod_gantmakher',
       'vsevolod_holubovych',
       'vsevolozhsky_family',
       'vsevolod_zaderatsky',
       'vsevolod_meyerhold',
       'vsevolod_starukhin',
       'vsevolod_romanenko',
       'vsevolod_shilovsky',
       'vsevolod_perekalin',
       'vsevolod_kukushkin',
       'vsevolod_luknitsky',
       'vsevolods_zelonijs',
       'vseobecne_spiknuti',
       'vsevolod_frederiks',
       'vsevolod_zelchenko',
       'vsevolod_solovyov',
       'vsevolod_kochetov',
       'vsevolod_sadovsky',
       'vsechno_nejlepsi!',
       'vsevolod_bessonov',
       'vsevolod_kniaziev',
       'vsevolod_chentsov',
       'vsevolod_larionov',
       'vsesportovy_areal',
       'vsevolod_sharonov',
       'vsevolod_bazhenov',
       'vsevolod_pudovkin',
       'vsevolod_nestayko',
       'vsevolod_merkulov',
       'vsevolod_balitsky',
       'vsevolod_aksyonov',
       'vsevolod_chaplin',
       'vsevolod_sanayev',
       'vsevolod_safonov',
       'vsevolod_tkachuk',
       'vsevolod_garshin',
       'vsevolod_blinkov',
       'vsevolod_sorokin',
       'vsevolod_kashkin',
       'vsevolod_ivanov',
       'vsetin_district',
       'vsevolod_nihaev',
       'vsetinska_becva',
       'vsevolod_savich',
       'vse_corporation',
       'vsevolod_bobrov',
       'vsevolod_miller',
       'vsevolod_lytkin',
       'vsevolod_gakkel',
       'vsevolod_rudnev',
       'vsevolod_rauzer',
       'vsevolod_petriv',
       'vsevolod_zanko',
       'vsemirny_trud',
       'vsepr_theory',
       'vsevolod_ii'],
 'f': ['vsfighting', 'vsftpd', 'vsfs', 'vsf'],
 'g': ['vsg_altglienicke'],
 'h': ['vsh_news'],
 'i': ['vsi_pascal', 'vsi_group', 'vsi_mill'],
 'k': ['vsk_osterholz-scharmbeck', 'vsk_aarhus'],
 'l': ['vsl_international'],
 'm': ['vsm_group'],
 'n': ['vsnl_transpacific'],
 'o': ['vsoft_technologies'],
 'p': ['vspeech', 'vsp'],
 'r': ['vsrp', 'vsr'],
 's': ['vss_enterprise', 'vss_vintorez', 'vss_imagine', 'vss_unity'],
 't': ['vstric_nekonecnum',
       'vst_enterprises',
       'vst_industries',
       'vsts_profiler',
       'vst_2',
       'vst_3'],
 'u': ['vsu_futsal'],
 'v': ['vsv_tonegido'],
 'w': ['vsw'],
 'x': ['vsx2', 'vsx1', 'vsx'],
 'y': ['vsyakaya_vsyachina',
       'vsyaka_nedelya',
       'vsyo_snachala',
       'vsya_rossiya',
       'vsya_moskva']}
