
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vd = {'_': ['vd_blues', 'vd_kalra', 'vd_16', 'vd_17'],
 'a': ['vda_6.1'],
 'b': ['vdb'],
 'c': ['vdc'],
 'd': ['vdd'],
 'e': ['vde-gallo_records', 'vde_e.v.'],
 'f': ['vdf_thasana'],
 'g': ['vdgs', 'vdg'],
 'h': ['vdh'],
 'i': ['vdigam_level'],
 'j': ['vdj'],
 'k': ['vdk_bank'],
 'l': ['vdl_berkhof',
       'vdl_nedcar',
       'vdl_futura',
       'vdl_sb200',
       'vdl_sb250',
       'vdl_sb120',
       'vdl_db250',
       'vdl_groep',
       'vdl_citea',
       'vdl_bova'],
 'm': ['vdm_metals'],
 'n': ['vdnkh'],
 'o': ['vdovichenko', 'vdovolsky', 'vdovin', 'vdot', 'vdo'],
 'p': ['vdp_cloche'],
 'r': ['vdrift', 'vdre', 'vdr'],
 's': ['vdsl', 'vdso', 'vds'],
 't': ['vdt'],
 'u': ['vdub', 'vdu'],
 'v': ['vdv'],
 'w': ['vdw'],
 'x': ['vdx'],
 'z': ['vdz']}
