
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ax = {'_': ['ax-les-thermes', 'ax.25', 'ax7', 'ax1'],
 'a': ['axaxacualco',
       'axayacatl',
       'axanthism',
       'axalphorn',
       'axapusco',
       'axarquia',
       'axaxd@r@',
       'axactor',
       'axarus',
       'axalta',
       'axatse',
       'axalto',
       'axataf',
       'axaren',
       'axam@d',
       'axalp',
       'axams',
       'axact',
       'axat',
       'axa'],
 'b': ['axborough', 'axbridge', 'axb'],
 'c': ['axceler', 'axcel'],
 'e': ['axel-springer-preis',
       'axelrodichthys',
       'axenstrasse',
       'axe-monies',
       'axegrinder',
       'axestoleus',
       'axelopran',
       'axelrodia',
       'axelsberg',
       'axestemys',
       'axewitch',
       'axelborg',
       'axelsson',
       'axeltree',
       'axewound',
       'axenstar',
       'axerquia',
       'axelella',
       'axenfeld',
       'axeltorv',
       'axelrad',
       'axelson',
       'axedale',
       'axelsen',
       'axelrod',
       'axelia',
       'axenic',
       'axenus',
       'axelos',
       'axeman',
       'axelle',
       'axenos',
       'axelay',
       'axess',
       'axell',
       'axel!',
       'axel',
       'axes',
       'axen',
       'axer',
       'axe'],
 'f': ['axfood', 'axford', 'axfs'],
 'g': ['axgio'],
 'i': ['axiopoeniella',
       'axinolobidae',
       'axianassidae',
       'axiniphyllum',
       'axinotarsus',
       'axinellidae',
       'axinopalpis',
       'axinopalpus',
       'axinolobus',
       'axiologina',
       'axiocerses',
       'axiokastro',
       'axinomancy',
       'axinoptera',
       'axiothauma',
       'axinellida',
       'axiarchism',
       'axiagasta',
       'axiocrita',
       'axillarin',
       'axioupoli',
       'axiopoena',
       'axinactis',
       'axinidris',
       'axinandra',
       'axinotoma',
       'axiocteta',
       'axitectum',
       'axiophyte',
       'axiarcha',
       'axiorata',
       'axiochus',
       'axiology',
       'axitinib',
       'axiality',
       'axintele',
       'axinella',
       'axinyssa',
       'axillary',
       'axiliad',
       'axiidea',
       'axident',
       'axinite',
       'axiotta',
       'axinaea',
       'axiotis',
       'axiodes',
       'axioche',
       'axiidae',
       'axivil',
       'axilla',
       'axiata',
       'axieme',
       'axiall',
       'axisxa',
       'axicon',
       'axigen',
       'axien',
       'axios',
       'axiat',
       'axino',
       'axion',
       'axioo',
       'axial',
       'axin2',
       'axium',
       'axin1',
       'axius',
       'axixa',
       'axiom',
       'axim',
       'axia',
       'axis',
       'axie',
       'axi'],
 'k': ['axkit', 'axk'],
 'l': ['axlar-bjorn', 'axlor', 'axley', 'axler', 'axle', 'axl'],
 'm': ['axmansford',
       'axminster',
       'axmedis',
       'axmouth',
       'axmarby',
       'axmann',
       'axman',
       'axm'],
 'n': ['axn'],
 'o': ['axonolaimidae',
       'axonotmesis',
       'axonopsidae',
       'axonoceras',
       'axonophora',
       'axonometry',
       'axochiapan',
       'axoclinus',
       'axonopus',
       'axolemma',
       'axostyle',
       'axonyina',
       'axomamma',
       'axomadol',
       'axoplasm',
       'axodine',
       'axocele',
       'axotomy',
       'axoneme',
       'axolotl',
       'axosoft',
       'axonya',
       'axogen',
       'axone',
       'axona',
       'axon',
       'axoa'],
 'p': ['axp'],
 'r': ['axr'],
 's': ['axstream', 'axstedt', 'axsiz', 'axs'],
 't': ['axtaci-qarabucaq',
       'axtaxana',
       'axtbach',
       'axtaci',
       'axtell',
       'axtown',
       'axtya',
       'axton',
       'axtel',
       'axt'],
 'u': ['axunahiran',
       'axundlu',
       'axungia',
       'axullu',
       'axutla',
       'axura',
       'axus',
       'axum',
       'axu'],
 'v': ['axvall', 'axv'],
 'w': ['axworthy', 'axwarbed', 'axwijk', 'axwave', 'axwell', 'axw'],
 'x': ['axxess', 'axxis', 'axxo', 'axx'],
 'y': ['axyrostola',
       'axymyiidae',
       'axyracrus',
       'axymene',
       'axymyia',
       'axylou',
       'axyris',
       'axylia',
       'axylus']}
