
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mm = {'_': ['mm/spq-2',
       'mm-ma-ma',
       'mm..food',
       'mm-151',
       'mm10',
       'mm9',
       'mm7',
       'mm8',
       'mm3',
       'mm6',
       'mm4',
       'mm2',
       'mm5',
       'mm1',
       'mm!'],
 'a': ['mmathubudukwane',
       'mmaphashalala',
       'mmajunkie.com',
       'mmanthatisi',
       'mmadinare',
       'mmatshumo',
       'mmanxotae',
       'mmankgodi',
       'mmathethe',
       'mmamashia',
       'mmadikola',
       'mmamabula',
       'mmashoro',
       'mma-besi',
       'mmabatho',
       'mmanoko',
       'mmarena',
       'mmanwu',
       'mmadhc',
       'mmachc',
       'mmakau',
       'mmaku',
       'mmarp',
       'mmaa',
       'mmap',
       'mmac',
       'mman',
       'mmas',
       'mmai',
       'mmab'],
 'b': ['mmb-chmica', 'mmb-2201', 'mmb'],
 'c': ['mmcinemas',
       'mmcache',
       'mmc-2',
       'mmc-1',
       'mmcc',
       'mmct',
       'mmc3',
       'mmcg',
       'mmc'],
 'd': ['mmda-2', 'mmdma', 'mmdf', 'mmda', 'mmdc', 'mmd'],
 'e': ['mmegi', 'mmeya', 'mmel1', 'mmea', 'mme'],
 'f': ['mmfa', 'mmff', 'mmf'],
 'g': ['mmg'],
 'h': ['mmhmm', 'mmhi', 'mmhl', 'mmhs', 'mmh'],
 'i': ['mmix', 'mmis', 'mmi'],
 'j': ['mmj'],
 'k': ['mmk'],
 'l': ['mmlp', 'mml'],
 'm': ['mmmuffins', 'mmmbop', 'mmmmm', 'mmmm', 'mmms', 'mmmh', 'mmmc', 'mmm'],
 'n': ['mmnoungou', 'mmn80cpu', 'mmn'],
 'o': ['mmog.asia',
       'mmopane',
       'mmoths',
       'mmode',
       'mmoh',
       'mmov',
       'mmor',
       'mmo'],
 'p': ['mmp23b',
       'mmp19',
       'mmp27',
       'mmp24',
       'mmpip',
       'mmp28',
       'mmp10',
       'mmp14',
       'mmp16',
       'mmp26',
       'mmp-8',
       'mmp21',
       'mmp25',
       'mmp20',
       'mmp11',
       'mmp17',
       'mmp15',
       'mmpc',
       'mmpv',
       'mmp8',
       'mmpr',
       'mmp9',
       'mmpa',
       'mmp2',
       'mmp1',
       'mmp3',
       'mmpu',
       'mmp7',
       'mmp'],
 'r': ['mmr06', 'mmrp', 'mmr'],
 's': ['mms22l', 'mms19', 'mmsc', 'mmse', 'mmst', 'mmsa', 'mms'],
 't': ['mmtp2', 'mmts', 'mmt'],
 'u': ['mmutlane', 'mmuseumm', 'mmuock', 'mmu'],
 'v': ['mmv'],
 'w': ['mmw'],
 'x': ['mmx'],
 'z': ['mmz']}
