
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bw = {'_': ['bw_vulpeculae',
       'bw_plantation',
       'bw_offshore',
       'bw_group',
       'bw_tower',
       'bw_gas'],
 'a': ['bwamba_orthobunyavirus',
       'bwanabwana_language',
       'bwaidoka_language',
       'bwakira,_rwanda',
       'bwanga_tshimen',
       'bwa_languages',
       'bwana_mkubwa',
       'bwa_language',
       'bwaga_cheti',
       'bwana_devil',
       'bwana_mkuu',
       'bwana_tamu',
       'bwa_people',
       'bwadc_sc'],
 'b': ['bwb_holster'],
 'c': ['bwca', 'bwc'],
 'e': ['bwebwetake_areieta',
       'bwenelang_language',
       'bwenyi_language',
       'bwela_language',
       'bwe_people',
       'bwe_karen'],
 'f': ['bwf_awards'],
 'g': ['bwg_transit', 'bwg_foods'],
 'h': ['bwhs', 'bwh'],
 'i': ['bwizamani_singh',
       'bwisi_language',
       'bwile_language',
       'bwile_people',
       'bwi_gmbh'],
 'j': ['bwj'],
 'k': ['bwk'],
 'l': ['bwllfa_colliery', 'bwlch_penbarras', 'bwlch_mawr'],
 'n': ['bwn'],
 'o': ['bwool', 'bwog', 'bwo'],
 'p': ['bwp-2000', 'bwping', 'bwps', 'bwp'],
 'q': ['bwq'],
 'r': ['bwrdd_arthur'],
 's': ['bws'],
 't': ['bwt'],
 'u': ['bwu'],
 'v': ['bwv_anh.'],
 'w': ['bww'],
 'x': ['bwx_technologies'],
 'y': ['bwyd_time']}
