
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bt = {'_': ['bt_discography',
       'bt_versatility',
       'bt_monocerotis',
       'bt_ambassador',
       'bt_broadband',
       'bt_archives',
       'bt_mydonate',
       'bt-4_combat',
       'bt_research',
       'bt_consumer',
       'bt_voyager',
       'bt_ireland',
       'bt_highway',
       'bt_myplace',
       'bt_mobile',
       'bt_italia',
       'bt_fusion',
       'bt_centre',
       'bt_museum',
       'bt_cotton',
       'bt_retail',
       'bt_toews',
       'bt_tower',
       'bt_group',
       'bt/at_52',
       'bt_wi-fi',
       'bt_sport',
       'bt_21cn',
       'bt_tank',
       'bt_gunn',
       'bt_tv'],
 'a': ['bta_futsal', 'bta_bank'],
 'b': ['btb/poz_domain', 'btba_nationals', 'btb_e2e'],
 'c': ['btcc_masters', 'btc_touring', 'btc_racing', 'btc_city'],
 'd': ['btdtgtts', 'btdigg', 'btdt'],
 'e': ['btev_experiment'],
 'f': ['btf3', 'btfc', 'btf'],
 'g': ['btg_pactual'],
 'h': ['bth_bank'],
 'i': ['btissam_lakhouad', 'btissam_sadini'],
 'j': ['btjunkie'],
 'k': ['btk'],
 'l': ['btla', 'btlp', 'btl'],
 'm': ['btm_antananarivo', 'btm_consult', 'btm_layout'],
 'n': ['btnh_worldwide', 'btn_2000'],
 'o': ['btob_discography',
       'btob_videography',
       "bto's_greatest",
       'btob_blue',
       'btob_4u'],
 'p': ['btpa_protein', 'btpn_towers'],
 'q': ['btq'],
 'r': ['btr_plc'],
 's': ['bts_videography',
       'bts_skytrain',
       'bts_74,398',
       'bts_group',
       'bts_world',
       'bts_meal'],
 't': ['bttc_centre'],
 'u': ['btu_international'],
 'v': ['btv_chittagong',
       'btv247,_inc',
       'btv_action',
       'btv_cinema',
       'btv_comedy',
       'btv_radio',
       'btv_lady',
       'btv_cup'],
 'w': ['btw'],
 'x': ['btx'],
 'z': ['btz_domain']}
