
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bk = {'_': ['bk_camelopardalis',
       'bk_marienlyst',
       'bk_ventspils',
       'bk_olomoucko',
       'bk_ume-trixa',
       'bk_pardubice',
       'bk_jekabpils',
       'bk_skottfint',
       'bk_grodno-93',
       'bk_hollviken',
       'bk-3_helmet',
       'bk_saturnus',
       'bk_valmiera',
       'bk_jurmala',
       'bk_stacker',
       'bk_jelgava',
       'bk_channel',
       'bk_shivani',
       'bk_forward',
       'bk_olympic',
       'bk_amager',
       'bk_racing',
       'bk_skonto',
       'bk_saldus',
       'bk_barons',
       'bk_hacken',
       'bk_astrio',
       'bk_virus',
       'bk_derby',
       'bk_decin',
       'bk_kenty',
       'bk_opava',
       'bk_infiz',
       'bk_zeros',
       'bk_ogre',
       'bk_brno',
       'bk_xxl',
       'bk_3,7',
       'bk_das',
       'bk_tag'],
 'a': ['bka_ase'],
 'b': ['bkb'],
 'c': ['bkc'],
 'd': ['bkd,_llp'],
 'e': ['bkeftine', 'bkerke', 'bke'],
 'f': ['bkf'],
 'h': ['bkhs', 'bkh'],
 'i': ['bki'],
 'j': ['bkj'],
 'k': ['bkk_architects', 'bkk_partners', 'bkk_radnicki'],
 'l': ['bkl_architecture', 'bkl_singularity'],
 'm': ['bkm_algorithm', 'bkma_yerevan', 'bkm_lucenec', 'bkmk_press'],
 'n': ['bkn_international'],
 'o': ['bkomra', 'bkorn'],
 'p': ['bkp'],
 'q': ['bkq'],
 'r': ['bkr'],
 's': ['bks_bielsko-biala', 'bks_theory'],
 'u': ['bkulangriil', 'bkurrengel'],
 'v': ['bkv_norrtalje'],
 'w': ['bkw_energie'],
 'x': ['bkx'],
 'y': ['bkyan']}
