
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bd = {'_': ['bd_camelopardalis',
       'bd-08deg2823_c',
       'bd-08deg2823_b',
       'bd-10deg3166_b',
       'bd_phoenicis',
       'bd+60_1417b',
       'bd1_gallery',
       'bd+20_594b',
       'bd-11_4672',
       'bd-22_5866',
       'bd+20_2457',
       'bd+14_4559',
       'bd+03_2562',
       'bd+02_2056',
       'bd+43_3654',
       'bd_hotels',
       'bd+00_316',
       'bd-07_436',
       'bd_bacata',
       'bd+48_740',
       'bd-17_63',
       'bd_wong',
       'bd_cine'],
 'a': ['bdale_garbee'],
 'b': ['bdbc', 'bdb'],
 'c': ['bdc_televizija', 'bdc_building', 'bdc_marcpol', 'bdc_10'],
 'd': ['bddc', 'bdd'],
 'e': ['bdellozonium_cerviculatum'],
 'f': ['bdf_f.c.'],
 'g': ['bdg'],
 'h': ['bdhs', 'bdh1', 'bdh'],
 'i': ['bdi_bridge'],
 'j': ['bdj_team'],
 'k': ['bdk'],
 'l': ['bdl_bipolar'],
 'm': ['bdmx', 'bdm'],
 'n': ['bdnews24.com', 'bdn'],
 'o': ['bdo_global'],
 'p': ['bdp_graubunden'],
 'q': ['bdq'],
 'r': ['bdr_thermea'],
 's': ['bds_c'],
 't': ['bdth2', 'bdt'],
 'u': ['bdu'],
 'w': ['bdwm_transport', 'bdwah_dam'],
 'x': ['bdx'],
 'z': ['bdz']}
