
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bg = {'_': ['bg&cm_railroad',
       'bg_geminorum',
       'bg_gottingen',
       'bg_karlsruhe',
       'bg_express',
       'bg_stadium',
       'bg_capital',
       'bg_crucis',
       'bg_group',
       'bg_news',
       'bg_rock',
       'bg_indi',
       'bg_voz',
       'bg_uys'],
 'a': ['bga'],
 'b': ['bgb'],
 'c': ['bgc_partners', 'bgc_bus'],
 'd': ['bgd'],
 'e': ['bge'],
 'f': ['bgfibank_group'],
 'g': ['bggs', 'bgg'],
 'h': ['bgh_capital'],
 'i': ['bgi_group'],
 'k': ['bgk'],
 'l': ['bglg-cis-reg_rna', 'bgl_group'],
 'm': ['bgmea_bhaban', 'bgm-75_aicbm', 'bgm-71_tow'],
 'n': ['bgn/pcgn_romanization'],
 'o': ['bgo_records', 'bgo_gemini'],
 'p': ['bgp_hijacking'],
 'r': ['bgr_group'],
 's': ['bgsu_firelands'],
 't': ['bgtw', 'bgt'],
 'u': ['bgusat', 'bgu'],
 'v': ['bgv'],
 'w': ['bgw_systems'],
 'x': ['bgx'],
 'y': ['bgyo']}
