
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bp = {'_': ['bp_valenzuela',
       'bp_tournament',
       'bp_structure',
       'bp_shipping',
       'bp_highway',
       'bp_circini',
       'bp_fallon',
       'bp_bootis',
       'bp_canada',
       'bp_crucis',
       'bp_cooper',
       'bp_studio',
       'bp_tauri',
       'bp_solar',
       'bp_pulse'],
 'a': ['bpa_worldwide', 'bpa_trail'],
 'b': ['bpb_plc'],
 'c': ['bpcs-steganography', 'bpc-157', 'bpcp', 'bpc'],
 'd': ['bpdfamily.com', 'bpda', 'bpd'],
 'e': ['bpel_script', 'bper_banca'],
 'f': ['bpf_party', 'bpf_youth'],
 'g': ['bpg'],
 'h': ['bphs', 'bphc', 'bph'],
 'i': ['bpifrance', 'bpifb4', 'bpifb1', 'bpifa3', 'bpi'],
 'j': ['bpjs_kesehatan'],
 'k': ['bpk_penabur'],
 'l': ['bpl_group'],
 'm': ['bpm_entertainment', 'bpm_everywhere', 'bpm_37093'],
 'n': ['bpn'],
 'o': ['bpo_security'],
 'p': ['bpp_university', 'bpp_holdings'],
 'r': ['bprd', 'bprc', 'bpr'],
 's': ['bpst_instanton', 'bps_domain'],
 't': ['bptf', 'bpt'],
 'u': ['bpuji', 'bpu'],
 'v': ['bpv'],
 'w': ['bpw'],
 'x': ['bpx'],
 'y': ['bpy2', 'bpy']}
