
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pf = {'_': ['pf-03654746',
       'pf-06260414',
       'pf-00446687',
       'pf-04479745',
       'pf-04457845',
       'pf-03550096',
       'pf-05089771',
       'pf-05105679',
       'pf-04745637',
       'pf-4455242',
       'pf-592,379',
       'pf-4840154',
       'pf-4800567',
       'pf-219,061',
       'pf-610355',
       'pf-184563',
       'pf-514273',
       'pf-3845',
       'pf-98',
       'pf-89',
       'pf-9',
       'pf1',
       'pf2'],
 'a': ['pfaffen-schwabenheim',
       'pfalzgrafenweiler',
       'pfarrernotbund',
       'pfaffenweiler',
       'pfaffenhoffen',
       'pfaffschwende',
       'pfaffenhausen',
       'pfarrweisach',
       'pfannenstock',
       'pfalztheater',
       'pfaffstatten',
       'pfaffenbrief',
       'pfarrkirchen',
       'pfannenstiel',
       'pfaffenstein',
       'pfaffenhofen',
       'pfaffikersee',
       'pfaffenteich',
       'pfaffenheim',
       'pfaffhausen',
       'pfannmoller',
       'pfaffenthal',
       'pfanderbahn',
       'pfaffenberg',
       'pfaueninsel',
       'pfarrwerfen',
       'pfannkuchen',
       'pfaltzgraff',
       'pfaffstatt',
       'pfalzweyer',
       'pfammatter',
       'pfarrwiese',
       'pfandbrief',
       'pfannkuch',
       'pfaffikon',
       'pfalzfeld',
       'pfandherr',
       'pfaffroda',
       'pfaffnau',
       'pfafflar',
       'pfaffian',
       'pfakofen',
       'pfaffing',
       'pfalzbau',
       'pfastatt',
       'pfaudler',
       'pfarmers',
       'pfander',
       'pfafers',
       'pfahler',
       'pfa-100',
       'pfaffia',
       'pfanner',
       'pfalzen',
       'pfatter',
       'pfaltz',
       'pfanni',
       'pfatp6',
       'pfahnl',
       'pfahl',
       'pfalz',
       'pfarr',
       'pfann',
       'pfaff',
       'pfau',
       'pfam',
       'pfas',
       'pfaa',
       'pfa'],
 'b': ['pfb'],
 'c': ['pfcp', 'pfca', 'pfcb', 'pfc'],
 'd': ['pfdn2', 'pfdn1', 'pfdn5', 'pfdn4', 'pfd'],
 'e': ['pfefferpotthast',
       'pferdingsleben',
       'pfeiferbrunnen',
       'pfeifferinella',
       'pfefferfliess',
       'pfeffenhausen',
       'pfeddersheim',
       'pfetterhouse',
       'pfeffernusse',
       'pfeifferhorn',
       'pfeffelbach',
       'pfettisheim',
       'pfeilstorch',
       'pfenninger',
       'pferdskopf',
       'pfedelbach',
       'pfeffingen',
       'pfeiffera',
       'pfettrach',
       'pfeffikon',
       'pfeiffer',
       'pfelling',
       'pfeuffer',
       'pfeffer',
       'pfennig',
       'pfersee',
       'pfeifer',
       'pfefer',
       'pfeil',
       'pfet',
       'pfe'],
 'f': ['pffr', 'pff'],
 'g': ['pfg'],
 'h': ['pfhs'],
 'i': ['pfingstwiesengraben',
       'pfitschigogerl',
       'pfitscherjoch',
       'pfitzneriella',
       'pfitzneriana',
       'pfingstberg',
       'pfiffelbach',
       'pfitzinger',
       'pfitschtal',
       'pfiesteria',
       'pfisterer',
       'pfitzbach',
       'pfitzner',
       'pfinztal',
       'pfitzer',
       'pfinder',
       'pfitsch',
       'pfister',
       'pfieffe',
       'pfizer',
       'pfinz',
       'pfitz',
       'pfis',
       'pfiq',
       'pfic',
       'pfi'],
 'k': ['pfkfb2', 'pfkfb4', 'pfkfb3', 'pfkfb1', 'pfkl', 'pfkp', 'pfkm'],
 'l': ['pflasterspektakel',
       'pflunspitzen',
       'pfleiderer',
       'pfluckuff',
       'pflimlin',
       'pflueger',
       'pfluger',
       'pfleger',
       'pflach',
       'pflag',
       'pflug',
       'pfl'],
 'm': ['pfm-1', 'pfm'],
 'n': ['pfn2', 'pfn'],
 'o': ['pfostenschlitzmauer',
       'pfostenbach',
       'pforzheim',
       'pforring',
       'pforzen',
       'pfofeld',
       'pforth',
       'pforta',
       'pfohl',
       'pfons',
       'pfo'],
 'p': ['pfp'],
 'r': ['pfronstetten',
       'pfroslkopf',
       'pfrondorf',
       'pfrillsee',
       'pfronten',
       'pfreimd',
       'pfrimm',
       'pfra',
       'pfr'],
 's': ['pfs:write', 'pfsense', 'pfsync', 'pfsweb', 'pfs'],
 't': ['pftk1', 'pftc', 'pft'],
 'u': ['pfulgriesheim',
       'pfullendorf',
       'pfungstadt',
       'pfullingen',
       'pfuhlbach',
       'pfutsero',
       'pfungen',
       'pfunds',
       'pfunit',
       'pfuel',
       'pfund',
       'pfu'],
 'v': ['pfv'],
 'w': ['pfw'],
 'y': ['pfyffer', 'pfyffe', 'pfyn']}
