
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pp = {'_': ['pp-format',
       'pp-90m1',
       'pp-2000',
       'pp+cs',
       'pp-90',
       'pp-93',
       'pp2b',
       'pp&l',
       'pp3',
       'pp1',
       'pp7'],
 'a': ['ppapdc1a',
       'ppargc1b',
       'ppargc1a',
       'ppap2b',
       'ppap2a',
       'ppads',
       'ppap',
       'ppac',
       'ppan',
       'ppa'],
 'b': ['ppb'],
 'c': ['ppcocaine',
       'ppc64',
       'ppcs',
       'ppca',
       'ppcm',
       'ppci',
       'ppcd',
       'ppcc',
       'ppc'],
 'd': ['ppd-40', 'ppdk', 'ppds', 'ppda', 'ppd'],
 'e': ['ppef1', 'ppe'],
 'f': ['ppfibp1', 'ppfia4', 'ppfa', 'ppf'],
 'g': ['ppgi', 'ppg'],
 'h': ['pphln1', 'pphs', 'pphi', 'pph'],
 'i': ['ppip5k2',
       'ppilku',
       'ppil1',
       'ppil2',
       'ppil4',
       'ppil3',
       'ppib',
       'ppih',
       'ppid',
       'ppig',
       'ppic',
       'ppie',
       'ppif',
       'ppi'],
 'j': ['ppj'],
 'k': ['ppk'],
 'l': ['ppli', 'ppl'],
 'm': ['ppm1k',
       'ppm1g',
       'ppm1f',
       'ppm1d',
       'ppmv1',
       'ppm1b',
       'ppm1a',
       'ppmd',
       'ppml',
       'ppms',
       'ppm'],
 'n': ['ppn'],
 'o': ['pporappippam', 'ppoa', 'ppod', 'ppo'],
 'p': ['ppp1r13b',
       'ppp1r15a',
       'ppp1r14a',
       'ppp1r14c',
       'ppp1r13l',
       'ppp1r12b',
       'ppp1r14b',
       'ppp1r12a',
       'ppp2r5b',
       'ppp1r1b',
       'ppp2r5a',
       'ppp2r1b',
       'ppp1r3a',
       'ppp2r3a',
       'ppp1r27',
       'ppp1r3g',
       'ppp2r2d',
       'ppp1r9a',
       'ppp2r5c',
       'ppp2r2a',
       'ppp2r5e',
       'ppp2r2b',
       'ppp2r5d',
       'ppp2r2c',
       'ppp1r10',
       'ppp2r3c',
       'ppp2r1a',
       'ppp1r3c',
       'ppp1r17',
       'ppp2r3b',
       'ppp1r9b',
       'ppp1r11',
       'ppp1r7',
       'ppp1cb',
       'ppp1r2',
       'ppp3ca',
       'ppp2r4',
       'ppp3r1',
       'pppppp',
       'ppp1r8',
       'ppp2cb',
       'ppp1cc',
       'ppp3cb',
       'ppp6r3',
       'ppp3r2',
       'ppp3cc',
       'ppp2ca',
       'ppp4r1',
       'ppp1ca',
       'ppp4c',
       'pppox',
       'ppp5c',
       'ppp6c',
       'pppp',
       'pppd',
       'pppa',
       'ppps',
       'pppo',
       'ppp'],
 'q': ['ppq'],
 'r': ['ppru-1', 'pprc1', 'pprc', 'ppru', 'pprm', 'ppr'],
 's': ['pps-1350',
       'ppsh-41',
       'pps.tv',
       'ppsspp',
       'ppsmi',
       'ppsh',
       'ppsc',
       'ppsf',
       'pps'],
 't': ['ppt-petoletka',
       'ppt-db',
       'ppt1',
       'pptt',
       'ppts',
       'ppt2',
       'ppta',
       'pptn',
       'pptv',
       'ppt'],
 'u': ['ppur', 'ppu'],
 'v': ['ppv'],
 'w': ['ppw'],
 'x': ['ppx'],
 'z': ['ppz']}
