
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_p_ = {'_': ['p87pikap',
       'p22phox',
       'p4-t-bu',
       'p53aip1',
       'p14arf',
       'p1-185',
       'p16.d4',
       'p-047',
       'p-384',
       'p3000',
       'p4000',
       'p110d',
       'p2000',
       'p1000',
       'p8000',
       'p1101',
       'p110a',
       'p107',
       'p180',
       'p300',
       'p239',
       'p700',
       'p100',
       'p112',
       'p320',
       'p250',
       'p120',
       'p-90',
       'p572',
       'p680',
       'p108',
       'p200',
       'p600',
       'p535',
       'p900',
       'p123',
       'p11d',
       'p111',
       'p264',
       'p105',
       'p5+1',
       'p110',
       'p210',
       'p400',
       'p54',
       'p60',
       'p76',
       'p43',
       'p58',
       'p75',
       'p15',
       'p67',
       'p39',
       'p29',
       'p31',
       'p49',
       'p81',
       'p12',
       'p34',
       'p63',
       'p90',
       'p25',
       'p35',
       'p18',
       'p27',
       'p99',
       'p79',
       'p42',
       'p14',
       'p33',
       'p20',
       'p46',
       "p''",
       'p68',
       'p97',
       'p65',
       'p61',
       'p24',
       'p10',
       'p59',
       'p80',
       'p13',
       'p84',
       'p55',
       'p37',
       'p69',
       'p64',
       'p93',
       'p32',
       'p40',
       'p28',
       'p16',
       'p36',
       'p21',
       'p38',
       'p85',
       'p74',
       'p57',
       'p72',
       'p30',
       'p11',
       'p23',
       'p41',
       'p53',
       'p48',
       'p19',
       'p96',
       'p26',
       'p62',
       'p51',
       'p17',
       'p44',
       'p45',
       'p73',
       'p56',
       'p52',
       'p47',
       'p95',
       'p70',
       'p82',
       'p50',
       'p22',
       'p78'],
 'a': ['p-azobenzenearsonate',
       'p.a.m.e.l.a.',
       'p.a.th.e./p.',
       'p-anisidine',
       'p.a.r.c.e.',
       'p.a.o.n.e.',
       'p.a.i.n.',
       'p.a.o.k.',
       "p'aquchi",
       'p.a.w.s.',
       'p.a.n.',
       'p-anca',
       "p'ari",
       'p:ano',
       'p3at',
       'p4a',
       'p&a',
       'p3a'],
 'b': ['p-bodies', 'p-basis', 'p-box', 'p3b'],
 'c': ['p-chlorocresol',
       'p-curvature',
       'p-complete',
       'p-calculus',
       'p-cresol',
       'p-cymene',
       'p-course',
       'p-chart',
       'p-cube',
       'p-com',
       'p-cad',
       'p.c.t',
       'p7c3',
       'p&c'],
 'd': ['p-dimethylaminocinnamaldehyde', 'p-derivation', 'p-dioxanone'],
 'e': ["p'ent'ay"],
 'f': ['p-factor', 'p-fem', 'p0f', 'p2f'],
 'g': ['p-glycoprotein', 'p-group', 'p-grid'],
 'h': ['p-hydroxynorephedrine',
       'p.h.i.r.m.',
       'p1harmony',
       'p.h.u.q.',
       'p4htm',
       'p4ha1',
       'p4ha2',
       'p4hb',
       'p&h'],
 'i': ["p'isaqayuq",
       "p'itiqucha",
       "p'ikareum",
       "p'isaqiri",
       'p.i.m.p.',
       'p.i.p.s.',
       "p'isaqa",
       "p'iti",
       'p2i'],
 'j': ['p2j'],
 'l': ['p-laplacian', 'p@lik@s', 'p@l@kli'],
 'm': ['p-menthane-3,8-diol',
       'p:machinery',
       'p-menthane',
       'p-magazine',
       'p-matrix',
       'p-model',
       'p-money',
       'p-mode',
       'p3m3',
       'p3m'],
 'n': ['p@nahlilar', 'p-nuclei', 'p.n.03'],
 'o': ['p.o.l.o.v.i.r.u.s.',
       'p.o.y.b.l',
       'p.o.w.a.',
       'p.o.t.',
       'p.o.d.',
       'p.o.k.',
       'p.o.5',
       'p.o.p',
       'p-o-x',
       'p&o',
       'p3o',
       'p.o'],
 'p': ['p-phenylenediamine',
       'p-phenetidine',
       'p-process',
       'p-poppin',
       'p-patch',
       'p/poly',
       'p2priv',
       'p2pnet',
       'p2psp',
       'p2ptv',
       'p-pop',
       'p2pu',
       'p2p',
       'p&p',
       'p3p',
       'p4p'],
 'r': ['p@rioglular',
       'p@rizamanli',
       'p.r.o.b.e.',
       'p@rdiqiran',
       'p@rvanli',
       'p@rdili',
       'p2ry13',
       'p2ry11',
       'p-rock',
       'p2ry14',
       'p2ry10',
       'p2rx5',
       'p2ry8',
       'p2rx2',
       'p2rx1',
       'p2rx7',
       'p2ry1',
       'p2ry2',
       'p2rx6',
       'p2ry4',
       'p2rx4',
       'p2ry6',
       'p-rep',
       'p2rx3',
       'p9rc',
       'p&r'],
 's': ['p.s.i.entology',
       'p-selectin',
       'p-square',
       'p-space',
       'p-site',
       'p@sha',
       'p-sch'],
 't': ['p.t.t.e.', 'p-town', 'p-type', 'p-tefb', "p'tcha", 'p.t.o.', 'p&t'],
 'u': ["p'unquchayuq", 'p.u.n.k.s.', 'p-unit', "p'ukru"],
 'v': ['p-variation', 'p-valley', 'p-value', 'p-valve', 'p2v'],
 'w': ['p&w'],
 'x': ['p-xylene'],
 'y': ['p2y12', 'p2y'],
 'z': ['p@zm@ri']}
