
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bs = {'_': ['bs_fabrications',
       'bs_bolticgota',
       'bs-1_tishina',
       'bs_space',
       'bs_25999',
       'bs_nymph',
       'bs_5454',
       'bs_5950',
       'bs_8878',
       'bs_5993',
       'bs_7988',
       'bs_5400',
       'bs_8888',
       'bs_8110',
       'bs_8599',
       'bs_4994',
       'bs_1088',
       'bs_7671',
       'bs_7910',
       'bs_7799',
       'bs_2000',
       'bs_8414',
       'bs_5930',
       'bs_857'],
 'a': ['bsa_lifestructures',
       'bsa_manufacturing',
       'bsa_thunderbolt',
       'bsa_motorcycles',
       'bsa_lightning',
       'bsa_spitfire',
       'bsa_company',
       'bsa_bantam',
       'bsa_welgun',
       'bsa_hornet',
       'bsa_m33-10',
       'bsa_sloper',
       'bsa_w33-7',
       'bsa_ultra',
       'bsa_scout',
       'bsa_cars',
       'bsa_fury',
       'bsa_b40',
       'bsa_ten',
       'bsa_cf2',
       'bsa_c12',
       'bsa_28p',
       'bsa_b25',
       'bsa_c15',
       'bsa_b44',
       'bsa_m20',
       'bsa_c11',
       'bsa_b21',
       'bsa_b31',
       'bsa_b50',
       'bsa_a7'],
 'b': ['bsba', 'bsb'],
 'c': ['bsc_erlangen',
       'bsc_kristall',
       'bsc_preussen',
       'bsc_sendling',
       'bsc_hastedt',
       'bsc_swot'],
 'd': ['bsd_authentication',
       'bsd_disklabel',
       'bsd_licenses',
       'bsd_checksum',
       'bsd_daemon',
       'bsd_domain'],
 'e': ['bse_sensex', 'bse_tower', 'bse_pro', 'bse_dci'],
 'f': ['bsfa_award', 'bsf_uav'],
 'g': ['bsgs', 'bsg'],
 'h': ['bsharri_district', 'bsh_hausgerate'],
 'i': ['bsi_group', 'bsi_steel', 'bsi_ltd'],
 'j': ['bsj'],
 'k': ['bsk_defense', 'bsk_zmaj'],
 'l': ['bsl'],
 'm': ['bsmfc', 'bsm'],
 'n': ['bsnl_broadband', 'bsnl_mobile'],
 'o': ['bsous', 'bsoft', 'bson', 'bso'],
 'p': ['bspp', 'bspr', 'bsp'],
 'q': ['bsquare'],
 'r': ['bsr_valladolid', 'bsr_towers', 'bsrc_fc'],
 's': ['bssn_formalism', 'bss_industrial', 'bss_01'],
 't': ['bstar', 'bstfa', 'bst1', 'bsts', 'bstv', 'bst'],
 'u': ['bsu'],
 'v': ['bsv_halle-ammendorf', 'bsv_luftikus'],
 'w': ['bsww_mundialito', 'bsww_tour'],
 'x': ['bsx']}
