
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ua = {'_': ['ua_huka_airport', 'ua_pou_monarch', 'ua_pou_airport', 'ua_huka_rail'],
 'a': ['uaap_basketball_championship',
       'uaap_volleyball_championship',
       'uaap_cheerdance_competition',
       'uaap_badminton_championship',
       'uaap_taekwondo_championship',
       'uaap_swimming_championship',
       'uaap_baseball_championship',
       'uaa/apu_consortium_library',
       'uaap_football_championship',
       'uaap_softball_championship',
       'uaap_overall_championship',
       'uaap_fencing_championship',
       'uaap_tennis_championship',
       'uaap_chess_championship',
       'uaap_judo_championship',
       'uaap_varsity_channel',
       'uaap_final_four',
       'uaap_season_70',
       'uaap_season_83',
       'uaap_season_58',
       'uaap_season_57',
       'uaap_season_68',
       'uaap_season_67',
       'uaap_season_75',
       'uaap_season_66',
       'uaap_season_69',
       'uaap_season_79',
       'uaap_season_81',
       'uaap_season_62',
       'uaap_season_64',
       'uaap_season_78',
       'uaap_season_71',
       'uaap_season_73',
       'uaap_season_72',
       'uaap_season_59',
       'uaap_season_84',
       'uaap_season_82',
       'uaap_season_60',
       'uaap_season_77',
       'uaap_season_80',
       'uaap_season_56',
       'uaap_season_76',
       'uaap_season_63',
       'uaap_season_61',
       'uaap_season_65',
       'uaap_season_74'],
 'b': ['uab_blazers_baseball', 'uab_blazers_football', 'uab_meto_language'],
 'c': ['uac_power_hitters'],
 'e': ['uae_philharmonic_orchestra',
       'uae_sportbike_championship',
       'uae_chess_federation',
       "uae_president's_cup",
       'uae_german_supercup',
       'uae_awafi_festival',
       'uae_federation_cup',
       'uae_team_emirates',
       'uae_futsal_league',
       'uae_2000_guineas',
       'uae_1000_guineas',
       'uae_youth_league',
       'uae_futsal_cup',
       'uae_pro_league',
       'uae_league_cup',
       'uae_super_cup',
       'uae_team_adq',
       'uae_fa_cup'],
 'i': ['uaithne_mag_samhradhain', 'uaithne_o_cobhthaigh'],
 'l': ['uallach_ingen_muinechain'],
 'm': ['uam-azcapotzalco_metro_station',
       'uam-i_metro_station',
       'uams_medical_center',
       'uamh_an_claonaite'],
 'p': ['uapishka_biodiversity_reserve'],
 's': ['uasin_gishu_people', 'uasin_gishu_county', 'uasi_vi_kohinoa'],
 't': ['uatuma-trombetas_moist_forests',
       'uatucarbau_administrative_post',
       'uato-lari_administrative_post',
       'uatuma_biological_reserve',
       'uathmharan_mac_brocan',
       'uatu_mac_aedo'],
 'v': ['uav-systems_hardware_chart',
       'uav_outback_challenge',
       'uav_sci-tech_uav'],
 'w': ['uaw_local_5810'],
 'x': ["uaxaclajuun_ub'aah_k'awiil"]}
