
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uf = {'_': ['uf_health_jacksonville', 'uf_training_reactor'],
 'a': ['ufa-pavillon_am_nollendorfplatz',
       'ufa_international_airport',
       'ufa_maximovka_airport',
       'ufa_train_disaster',
       'ufa-palast_am_zoo',
       'ufa_lenin_museum',
       'ufa_rail_bridge'],
 'c': ['ufc_performance_institute',
       'ufcu_disch-falk_field',
       'ufc_ultimate_insider',
       'ufc_personal_trainer',
       'ufc_undisputed_2010',
       'ufc_2009_undisputed',
       'ufc:_sudden_impact',
       'ufc_undisputed_3',
       'ufcw_local_1776',
       'ufc_fight_pass',
       'ufcw_local_832',
       'ufc_all_access',
       'ufc:_tapout_2'],
 'f': ['ufford_hall,_cambridgeshire',
       'uffington_railway_station',
       'uffington_house,_chester',
       'uffington,_west_virginia',
       'uffculme_railway_station',
       'uffington_rural_district',
       'uffington_white_horse',
       'uffe_schultz_larsen',
       'uff!_yeh_mohabbat',
       'uff_yeh_mohabbat',
       'uff_meri_family'],
 'i': ['ufimsky_refinery_plant'],
 'l': ['ufl_championship_game', 'ufl_division_2', 'ufl_top_scorer'],
 'm': ['ufm_easy_riser'],
 'o': ['ufo_ultramaiden_valkyrie',
       'ufo_investigators_league',
       'ufo_conspiracy_theories',
       'ufo_interactive_games',
       'uforia_audio_network',
       'ufo_kamen_yakisoban',
       'ufo:_alien_invasion',
       'ufo_welcome_center',
       'ufo:_target_earth',
       'ufouria:_the_saga',
       'ufos_in_fiction',
       'ufo_robo_dangar',
       'ufo_2:_flying']}
