
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uc = {'_': ['uc_riverside_highlanders',
       'uc_berkeley_extension',
       'uc_baseball_stadium',
       'uc_korkusuz_arkadas',
       'uc_irvine_anteaters',
       'uc_serefeli_mosque',
       'uc_davis_aggies',
       'uc_la_estrella',
       'uc_de_lescura',
       'uc_de_pena'],
 'a': ['ucayalina_de_television',
       'ucayak_byzantine_church',
       'ucas_teacher_training',
       'ucayali_moist_forests',
       'ucam_murcia_cf',
       'ucam_murcia_cb'],
 'b': ['ucb_home_loans'],
 'c': ['uccle-calevoet_railway_station',
       'uccle-stalle_railway_station',
       'ucc-1_financing_statement',
       'ucc_philosophical_society',
       "ucc_students'_union",
       'uccs_mountain_lions'],
 'd': ['ucd_philosophy_society',
       'ucd_economics_society',
       'ucd_law_review',
       'ucd_boat_club'],
 'e': ['ucea-victoria_railway_line'],
 'f': ['ucf_knights_softball', 'ucf_knights_football', 'ucf_knights_baseball'],
 'h': ['uchucklesaht_first_nation',
       'uchitel_publishing_house',
       'uchi_technologies_berhad',
       'uchira_vaneswarar_temple',
       'uch_tappeh,_kabudarahang',
       'uchechukwu_deborah_ukeh',
       'uchee_methodist_church',
       'uchila,_udupi_district',
       'uchinoura_space_center',
       'uchtred_of_lindisfarne',
       'uchhri_railway_station',
       'uchechukwu_n._maduako',
       'uche_veronica_amazigo',
       'uchida_ryu_tanjojutsu',
       'ucha,_sultanpur_lodhi',
       "uchc_men's_tournament",
       'uchu_sentai_kyuranger',
       'uchuk_hakas_district',
       'uch_tappeh,_golestan',
       'uchu_nippon_setagaya',
       'uchu_majin_daikengo',
       'uch_tappeh,_malayer',
       'uch_tappeh-ye_qaleh',
       'uchu_enban_daisenso',
       "ucha'an_k'an_b'alam",
       "ucha'an_k'in_b'alam",
       'uch_tappeh-ye_kord',
       'uchi_mata_makikomi',
       'uchide_no_kozuchi',
       'uchi_no_sanshimai',
       'uchi_mata_sukashi',
       'uchi_mata_gaeshi',
       'uchiki_na_aitsu',
       'uchastok_No._12',
       'uchastok_No._26',
       'uche_henry_agbo',
       'uch_power_plant',
       'uchastok_No._28',
       'uche_peter_umez',
       'uchu_no_hosoku',
       'uchastok_No._4'],
 'i': ['uci_race_classifications',
       'uci_continental_circuits',
       'uci_world_championships',
       "uci_women's_team",
       'uci_golden_bike',
       'uci_world_tour',
       'uci_world_cups'],
 'k': ['uckermark_concentration_camp',
       'uckfield_railway_station',
       'uckfield_baptist_church',
       'uckfield_town_council',
       'uckfield_town_f.c.'],
 'l': ['uclouvain_brussels_woluwe',
       'ucla_meteorite_collection',
       'ucluelet_water_aerodrome',
       'ucla-nus_executive_mba',
       'ucla_loneliness_scale',
       'ucl_wolfson_institute',
       'ucluelet_first_nation',
       'ucla_bruins_softball',
       'uclouvain_fucam_mons',
       'ucla_bruins_baseball',
       'ucla_student_housing',
       'ucla_bruins_football',
       'ucl_urban_laboratory',
       'ucla_bruins_coaches',
       'ucla_taser_incident',
       'ucl_medical_school',
       'ucl_ear_institute',
       'ucla_labor_center',
       'ucl_main_building',
       'ucla_kyodo_taiko',
       'ucla_img_program',
       'ucla_spring_sing',
       'ucla_ptsd_index',
       'ucla_lab_school',
       'ucla_law_review',
       'ucl_pi_media'],
 'm': ['ucm_multipurpose_building'],
 'o': ['uconn-umass_football_rivalry',
       'uconn_huskies_basketball',
       'ucolta,_south_australia',
       'uconn_huskies_football',
       'uconn_huskies_baseball',
       'uconn_huskies_softball',
       'uco_van_wijk'],
 'p': ['ucph_bioinformatics_centre'],
 's': ['ucsf/chase_center_station',
       'ucsc_student_associations',
       'ucsb_physics_department',
       'ucsf_graduate_division',
       'ucsy_railway_station',
       'ucsc_genome_browser',
       'ucsf_medical_center'],
 't': ['uct_mathematics_competition'],
 'w': ['ucw-zero_heavyweight_championship', 'ucw-zero_ultra-x_championship']}
