
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rg = {'_': ['rg9mtd2',
       'rg7795',
       'rg-33',
       'rg146',
       'rg-19',
       'rg-41',
       'rg-12',
       'rg-34',
       'rg-58',
       'rg-35',
       'rg-42',
       'rg-59',
       'rg41',
       'rg-6',
       'rg2',
       'rg1'],
 'a': ['rgangkum', 'rgangpi', 'rga-86', 'rgaje', 'rga'],
 'b': ['rgb-60', 'rgbi', 'rgbw', 'rgbe'],
 'c': ['rgc100', 'rgc'],
 'd': ['rgd-5', 'rgd'],
 'e': ['rge'],
 'f': ['rgf'],
 'g': ['rgg'],
 'h': ['rghioua', 'rghs', 'rgh'],
 'i': ['rgielsko', 'rgielew', 'rgit', 'rgi'],
 'k': ['rgk'],
 'l': ['rgl2', 'rgl'],
 'n': ['rgn'],
 'o': ['rgotina', 'rgoste'],
 'p': ['rgpd5', 'rgp3', 'rgp'],
 'r': ['rgraph', 'rgr'],
 's': ['rgs-50m',
       'rgsh-30',
       'rgs9bp',
       'rgs12',
       'rgs16',
       'rgs17',
       'rgs14',
       'rgs10',
       'rgs11',
       'rgs18',
       'rgs19',
       'rgs13',
       'rgs20',
       'rgs9',
       'rgs3',
       'rgs4',
       'rgs5',
       'rgs8',
       'rgs7',
       'rgs1',
       'rgs2',
       'rgs6',
       'rgs'],
 't': ['rgtk2', 'rgt'],
 'v': ['rgv'],
 'w': ['rgw'],
 'x': ['rgx']}
