
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rd = {'_': ['rd-0110r',
       'rd-0233',
       'rd-0214',
       'rd-0410',
       'rd-0255',
       'rd-0237',
       'rd-0110',
       'rd-0120',
       'rd-0124',
       'rd-0236',
       'rd-0243',
       'rd-0109',
       'rd-0146',
       'rd-0210',
       'rd-0216',
       'rd-180',
       'rd-253',
       'rd-191',
       'rd-843',
       'rd-864',
       'rd-263',
       'rd-250',
       'rd-801',
       'rd-215',
       'rd-861',
       'rd-107',
       'rd-701',
       'rd-855',
       'rd-270',
       'rd-119',
       'rd-193',
       'rd-856',
       'rd-170',
       'rd-120',
       'rd-162',
       'rd-810',
       'rd-214',
       'rd-58',
       'rd-8',
       'rd1'],
 'a': ['rdavica', 'rdate', 'rdap', 'rdac', 'rda'],
 'b': ['rdbp', 'rdbm', 'rdb'],
 'c': ['rdcm', 'rdc'],
 'd': ['rddhi', 'rdd'],
 'e': ['rdesktop', 'rde-1', 'rde'],
 'f': ['rdf-powerstation', 'rdf/xml', 'rdflib', 'rdf4j', 'rdfa', 'rdf'],
 'g': ['rdgldgrn', 'rdg'],
 'h': ['rdheidhi',
       'rdh16',
       'rdh12',
       'rdh14',
       'rdh11',
       'rdh13',
       'rdh5',
       'rdh8',
       'rdhs',
       'rdh'],
 'i': ['rdiff-backup', 'rdio', 'rdi'],
 'j': ['rdj'],
 'l': ['rdl'],
 'm': ['rdma', 'rdms', 'rdm'],
 'n': ['rdna', 'rdn'],
 'o': ['rdock', 'rdovo', 'rdos', 'rdoc', 'rdo'],
 'p': ['rdpc', 'rdp'],
 'r': ['rdrand', 'rdram', 'rdr'],
 's': ['rds-127',
       'rds-37',
       'rds-2',
       'rds-9',
       'rds-5',
       'rds-1',
       'rds-4',
       'rds-3',
       'rds2',
       'rds'],
 't': ['rdt'],
 'u': ['rdultowice', 'rdu-fm', 'rdutow', 'rdu'],
 'v': ['rdv'],
 'w': ['rdw'],
 'x': ['rdx'],
 'z': ['rdzuchow-kolonia',
       'rdziostow',
       'rdzuchow',
       'rdzawka',
       'rdzawa',
       'rdzow']}
