
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_eq = {'_': ['eq-53', 'eq-5d', 'eq1', 'eq3', 'eq2'],
 'a': ['eqalugaarsuit', 'eqaluit', 'eqanie', 'eqal', 'eqah', 'eqa'],
 'b': ['eqbalabad', 'eqbaliyeh', 'eqbali', 'eqbal', 'eqb'],
 'c': ['eqcm'],
 'e': ['eqe'],
 'f': ['eqf'],
 'l': ['eqlid', 'eql'],
 'n': ['eqn'],
 'o': ['eqology'],
 'p': ['eqp'],
 'r': ['eqreqayeh'],
 's': ['eqs'],
 't': ['eqtidaar', 'eqtec', 'eqtn', 'eqt'],
 'u': ['equal-parallel/guernica-bengasi',
       'equeurdreville-hainneville',
       'equennes-eramecourt',
       'equisatisfiability',
       'equidimensionality',
       'equal-to-apostles',
       'equipotentiality',
       'equidensitometry',
       'equidimensional',
       'equipossibility',
       'equiprobability',
       'equiconsistency',
       'equensworldline',
       'equivalisation',
       'equeurdreville',
       'equidissection',
       'equianharmonic',
       'equicontinuity',
       'equinumerosity',
       'equianalgesic',
       'equipotential',
       'equalitymaine',
       'equestrianism',
       'equiveillance',
       'equihen-plage',
       'equifinality',
       'equisetaceae',
       'equitability',
       'equemauville',
       'equivocation',
       'equigranular',
       'equinovalgus',
       'equinophobia',
       'equitisation',
       'equalization',
       'equitrekking',
       'equivalents',
       'equilibrium',
       'equisetidae',
       'equinalysis',
       'equivalence',
       'equisetales',
       'equidistant',
       'equiangular',
       'equatorium',
       'equancourt',
       'equallogic',
       'equitation',
       'equestrian',
       'equilabium',
       'equaflight',
       'equal-area',
       'equevillon',
       'equilibrio',
       'equevilley',
       'equatorius',
       'equatorial',
       'equivocada',
       'equanimity',
       'equational',
       'equalitie',
       'equitable',
       'equatoria',
       'equestria',
       'equizetum',
       'equivocal',
       'equilibre',
       'equitynet',
       'equisetum',
       'equanimal',
       'equijubus',
       'equalizer',
       'equiterre',
       'equastone',
       'equaterra',
       'equityzen',
       'equipoise',
       'equator-s',
       'equitybee',
       'equipment',
       'equilenin',
       'equicizer',
       'equestris',
       'equulites',
       'equihash',
       'equitrac',
       'equuleus',
       'equation',
       'equating',
       'equinunk',
       'equilend',
       'equirria',
       'equidome',
       'equiinet',
       'equality',
       'equatair',
       'equmenia',
       'equinoxe',
       'equitius',
       'equiniti',
       'equitana',
       'equateur',
       'equalize',
       'equative',
       'equibbly',
       'equisat',
       'equals6',
       'equinae',
       'equerry',
       'equinet',
       'equinox',
       'equitel',
       'equinor',
       'equidae',
       'equirre',
       'equetus',
       'equitan',
       'equiano',
       'equilin',
       'equirex',
       'equilly',
       'equifax',
       'equator',
       'equitas',
       'equaesi',
       'equites',
       'equinix',
       'equity',
       'equair',
       'equale',
       'equant',
       'equipe',
       'equini',
       'equord',
       'equate',
       'equil2',
       'equal',
       'equol',
       'equip',
       'eques',
       'equus',
       'equix',
       'equis',
       'equi'],
 'v': ['eqv'],
 'w': ['eqworld']}
