
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lc = {'_': ['lc4mp',
       'lc-10',
       'lc-13',
       'lc80',
       'lc12',
       'lc5',
       'lc3',
       'lc9',
       'lc1',
       'lc4',
       'lc2'],
 'a': ['lca-vision', 'lcars', 'lcad', 'lcaw', 'lcat', 'lcac', 'lca5', 'lca'],
 'b': ['lcbc'],
 'c': ['lcchs', 'lccm', 'lccs', 'lcce', 'lcca', 'lccc', 'lcc'],
 'd': ['lcdp', 'lcdr'],
 'e': ['lcevc', 'lcer', 'lce'],
 'f': ['lcfr', 'lcfc', 'lcfg', 'lcf'],
 'g': ['lcg'],
 'h': ['lchkadzor',
       'lchashen',
       'lchavan',
       'lchad',
       'lchap',
       'lchc',
       'lchn',
       'lchs',
       'lchr',
       'lch'],
 'i': ['lcisd', 'lciii', 'lcia', 'lcii', 'lci'],
 'j': ['lcj'],
 'k': ['lck'],
 'l': ['lcls', 'lclc', 'lcl'],
 'm': ['lcm-1e', 'lcmt1', 'lcmt2', 'lcm-8', 'lcmc', 'lcms', 'lcm'],
 'n': ['lcn'],
 'o': ['lcovice', 'lcorl', 'lcor', 'lco'],
 'p': ['lcp1', 'lcpd', 'lcpm', 'lcps', 'lcpl', 'lcpc', 'lcpa', 'lcp'],
 'q': ['lcq'],
 'r': ['lcross', 'lcrg', 'lcrs', 'lcrb', 'lcrv', 'lcra', 'lcrl', 'lcrd', 'lcr'],
 's': ['lcs35', 'lcsc', 'lcsr', 'lcsd', 'lcs'],
 't': ['lctl', 'lct'],
 'u': ['lcu'],
 'v': ['lcvp', 'lcv'],
 'w': ['lcw'],
 'x': ['lcx']}
