
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lg = {'_': ['lg-120907',
       'lg121071',
       'lg-2527',
       'lg4',
       'lg1',
       'lg3',
       'lg6',
       'lg2',
       'lg5'],
 'a': ['lgals3bp', 'lgals13', 'lgarde', 'lga'],
 'b': ['lgbtory', 'lgbtq&a', 'lgbt', 'lgb'],
 'c': ['lgca', 'lgc'],
 'd': ['lgd-2226', 'lgd-3303', 'lgdj', 'lgdt', 'lgd'],
 'e': ['lge.huya', 'lgeepa', 'lge'],
 'f': ['lgfc', 'lgfl', 'lgf'],
 'g': ['lgg'],
 'h': ['lgharbia', 'lghs', 'lgh'],
 'i': ['lgin', 'lgi2', 'lgi1'],
 'j': ['lgj'],
 'k': ['lgk'],
 'l': ['lgl'],
 'm': ['lgmn', 'lgm'],
 'o': ['lgota-nadwarcie',
       'lgota-mokrzesz',
       'lgoczanka',
       'lgotka',
       'lgovo',
       'lgov',
       'lgow',
       'lgo'],
 'p': ['lgp-30', 'lgp2', 'lgp'],
 'r': ['lgr5', 'lgr4', 'lgr6', 'lgr'],
 's': ['lgsm', 'lgsn', 'lgs'],
 't': ['lgte', 'lgtn', 'lgt'],
 'u': ['lguest', 'lgu'],
 'v': ['lgv'],
 'x': ['lgx']}
