
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lr = {'_': ['lr-diode', 'lr-5182', 'lr-300', 'lr132', 'lr91', 'lr7', 'lr2', 'lr5'],
 'a': ['lraber', 'lrat', 'lrac'],
 'b': ['lrba', 'lrb'],
 'c': ['lrch4', 'lrcs', 'lrcc', 'lrc'],
 'd': ['lrdc', 'lrdd', 'lrd'],
 'f': ['lrfc', 'lrf'],
 'g': ['lrg1', 'lrgb', 'lrg'],
 'h': ['lrhs', 'lrh'],
 'i': ['lrit3', 'lrig1', 'lric', 'lri'],
 'j': ['lrj'],
 'k': ['lrk'],
 'm': ['lrmt', 'lrmc', 'lrm'],
 'n': ['lrn'],
 'o': ['lroc', 'lro'],
 'p': ['lrpprc',
       'lrp10',
       'lrp1b',
       'lrp11',
       'lrp2',
       'lrp3',
       'lrp4',
       'lrp5',
       'lrpu',
       'lrp1',
       'lrp6',
       'lrp'],
 'r': ['lrrfip1',
       'lrrc37a',
       'lrrc57',
       'lrrc41',
       'lrrtm1',
       'lrrc8d',
       'lrriq3',
       'lrrc17',
       'lrrc48',
       'lrrc40',
       'lrrc8c',
       'lrrc8b',
       'lrrc8a',
       'lrrc39',
       'lrrc26',
       'lrrc3b',
       'lrrc50',
       'lrrc23',
       'lrrc8e',
       'lrrc24',
       'lrrc7',
       'lrrc4',
       'lrrk2',
       'lrrn1',
       'lrrn2',
       'lrrn3',
       'lrrk1',
       'lrrr',
       'lrr'],
 's': ['lrsam1', 'lrs'],
 't': ['lrtomt', 'lrta'],
 'u': ['lru'],
 'v': ['lrv'],
 'y': ['lrytas.lt'],
 'z': ['lrz']}
