STATION_LIST_HEADER_MAPPER = {
    '지점': 'code',
    '시작일': 'begin',
    '종료일': 'until',
    '지점명': 'name',
    '지점주소': 'address',
    '관리관서': 'parent',
    '위도': 'lat',
    '경도': 'lon',
    '노장해발고도(m)': 'elevation',
    '기압계(관측장비지상높이(m))': 'barometer_height',
    '기온계(관측장비지상높이(m))': 'tempmeter_height',
    '풍속계(관측장비지상높이(m))': 'windmeter_height',
    '강우계(관측장비지상높이(m))': 'rainmeter_height',
}