
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nt = {'_': ['nt-art_gallery', 'nt_stingers', 'nt_draught', 'nt_pearls', 'nt_card'],
 'a': ['ntawere_formation',
       'ntaoleng_peacock',
       'ntazana_mayembe',
       'ntando_mahlangu',
       'ntabeni_dukisa',
       'ntando_mncube',
       'ntaba_kandoda',
       'ntala_skinner',
       'ntare_school',
       'ntando_duma',
       'ntare_mwine',
       'ntando_kebe',
       'ntak_ibesit',
       'ntare_iv'],
 'b': ['ntbackup', 'ntbc', 'ntb'],
 'c': ['ntchisi_district',
       'ntchisi_mountain',
       'ntcheu_district',
       'ntchisi_airport',
       'ntcham_language',
       'ntc_television',
       'ntca_ground',
       'ntc_poprad',
       'ntc_module',
       'ntc_senec',
       'ntc_arena',
       'ntc_tower'],
 'd': ['ntdetect.com', 'ntdec', 'ntds', 'ntd'],
 'e': ['nteboheleng_koaeana',
       'ntebogang_ratshosa',
       'ntesang_simanyana',
       'ntenyi_language',
       'ntenjeru_county',
       'ntewane_machel',
       'nteng_language',
       'ntesa_dalienst',
       'ntema_ndungidi'],
 'f': ['ntfs_links'],
 'g': ['ntg'],
 'h': ['nthabiseng_mokoena',
       'nthabeleng_likotsi',
       'ntholeng_lechesa',
       'nthabiseng_mosia',
       'nthikeng_mohlele',
       'nthomeng_majara',
       'nthokozo_tshuma',
       'nthako_matiase',
       'nthato_motlana',
       'nthati_moshesh',
       'nth_root',
       'nth_ring',
       'nth_man'],
 'i': ['ntinos_konstantakis',
       'ntinos_nikolopoulos',
       'ntinos_pontikas',
       'ntime_skhosana',
       'ntiero_effiom',
       'ntilim_ntilim',
       'ntimbale_dam',
       'ntim_gyakari',
       'nti_audio'],
 'j': ['ntjam_rosie'],
 'k': ['ntk'],
 'l': ['ntl_incorporated', 'ntlhoi_motsamai', 'ntl_ireland'],
 'm': ['ntm'],
 'n': ['ntn_corporation', 'ntn_buzztime'],
 'o': ['ntombela_kamalandela',
       'ntombiyelanga_ndlovu',
       'ntombizodwa_sibanda',
       "ntoitha_m'mithiaru",
       'ntokozo_sikhakhane',
       'ntongela_masilela',
       'ntopile_kganyago',
       'ntokozo_hlonyana',
       'ntoroko_district',
       'ntokou_district',
       'ntokozo_mahlaba',
       'ntozake_shange',
       'ntokozo_vidima',
       'ntobeko_boyce',
       'ntokozo_qwabe',
       'ntone_edjabe',
       'ntoi_rapapa'],
 'p': ['ntpc_ramagundam',
       'ntpc_limited',
       'ntpc_dadri',
       'ntpc_kawas',
       'ntp,_inc.',
       'ntp_pool'],
 'q': ['ntq'],
 'r': ['ntr:_kathanayakudu',
       'ntr:_mahanayakudu',
       'ntrapo_language',
       'ntr_district',
       'ntr_gardens',
       'ntreev_soft',
       'ntr_trust',
       'ntr_plc'],
 's': ['ntsikelelo_nyauza',
       'ntshingwayo_khoza',
       'nts_motorsports',
       'ntshingwayo_dam',
       'ntsu_mokhehle',
       'ntsiki_biyela',
       'nts_radio',
       'nts_gmbh',
       'nts_asa'],
 't': ['ntt_communications',
       'ntt_publishing',
       'ntt_facilities',
       'ntt_comware',
       'ntt_docomo',
       'ntt_plala',
       'ntt_data'],
 'u': ['ntungamo-rukungiri_road',
       'ntumbachushi_falls',
       'ntungamo_district',
       'ntumba_massanka',
       'ntuthuko_radebe',
       'ntuthuko_madela',
       'ntuthuko_mchunu',
       'ntuc_fairprice',
       'ntumba_luaba',
       'ntuc_income',
       'ntu_method'],
 'v': ['ntv_akawungeezi',
       'ntvic_kakanj',
       'ntv_kohalpur',
       'ntv_variety',
       'ntv_montena',
       'ntv_uganda',
       'ntv_patria',
       'ntv_canada',
       'ntv_jasmin',
       'ntv_tarih',
       'ntv_arena',
       'ntvu_uav',
       'ntv_news',
       'ntv_plus',
       'ntv_amna',
       'ntv_spor',
       'ntv_jata',
       'ntv_101'],
 'w': ['ntwetwe_pan'],
 'x': ['ntx_rayados'],
 'y': ['ntyam_mengue'],
 'z': ['ntz']}
