
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mj = {'_': ['mj_faoa-danielson',
       'mj_williams',
       'mj_hibbett',
       'mj_designs',
       'mj_acosta',
       'mj_pelser',
       'mj_mentz',
       'mj_hegar',
       'mj_long',
       'mj_cole',
       'mj_erb',
       'mj_lee'],
 'a': ['mjanyana_hospital', 'mjallby_aif', 'mja_insight'],
 'b': ['mjb'],
 'c': ['mjc'],
 'd': ['mjd'],
 'e': ['mjesto_primislje', 'mjell_glacier', 'mjedena_glava', 'mjeda_family'],
 'h': ['mjhs'],
 'i': ['mjimwema,_temeke', 'mji_mpya'],
 'j': ['mjj'],
 'k': ['mjk'],
 'l': ['mjl'],
 'm': ['mjm_australia'],
 'n': ['mjn'],
 'o': ['mjondalen_gummivarefabrikk',
       'mjollkvaevane_cirques',
       'mjolby_municipality',
       'mjollfoykje_bluff',
       'mjolfjell_station',
       "mjoberg's_toadlet",
       'mjondalen_station',
       'mjosa_limestone',
       'mjotvidur_maer',
       'mjosund_bridge',
       'mjolnir_crater',
       'mjomna_church',
       'mjosa_bridge',
       'mjondalen_if',
       'mjosa_cities',
       'mjolnir_llc',
       'mjolby_hc'],
 'p': ['mjp_architects'],
 'q': ['mjq'],
 'r': ['mjr'],
 's': ['mjs'],
 't': ['mjt'],
 'u': ['mjull_bathore'],
 'w': ['mjw']}
