
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_md = {'_': ['md._akram-al-hossain',
       'md._akhtaruzzaman',
       'md._emdad-ul-bari',
       'md._suzauddaulah',
       'md._khasruzzaman',
       'md._shamsuddoha',
       'md._niamatullah',
       'md._kamruzzaman',
       'md._shohrowardi',
       'md_ashikuzzaman',
       'md_helicopters',
       'md.nurul_islam',
       'md._nuruzzaman',
       'md_productions',
       'md_rahmatullah',
       'md._nematullah',
       'md_shahidullah',
       'md_nazimuddin',
       'md-ms_program',
       'md._shahjahan',
       'md._alauddin',
       'md._alamgir',
       'md_discount',
       'md&c_pavlov',
       'md-82_mine',
       'md._sohrab',
       'md._hanif',
       'md._ishak',
       'md_shoyeb',
       'md_yousuf',
       'md_kamran',
       'md._iqbal',
       'md_tokon',
       'md_geist',
       'md_data',
       'md_600',
       'md_500',
       'md_421',
       'md_88',
       'md_11',
       'md_80',
       'md_4'],
 'a': ['mda_framework'],
 'b': ['mdb_communications', 'mdb_polysequencer', 'mdb_tools'],
 'c': ['mdc_holdings', 'mdc_partners'],
 'd': ['mdd2', 'mdds', 'mddl', 'mdd'],
 'e': ['mdewakanton', 'mde-sahani', 'mdea', 'mdef', 'mde'],
 'f': ['mdfmk', 'mdfi', 'mdf'],
 'g': ['mdg_midgy-club'],
 'h': ['mdhila', 'mdhc', 'mdhs', 'mdhp', 'mdh1', 'mdh'],
 'i': ['mdina_steles', 'mdina_glass', 'mdina_gate'],
 'j': ['mdjankagnoi', 'mdjouezi', 'mdjoyezi', 'mdj'],
 'k': ['mdk-2m', 'mdk2', 'mdk'],
 'l': ['mdlr_airlines', 'mdloti_river', 'mdlaw_megbi', 'mdl_chime'],
 'm': ['mdma-assisted_psychotherapy',
       'mdm_motorsports',
       'mdm_observatory',
       'mdm_recordings',
       'mdm_bank'],
 'n': ['mdn_interactive'],
 'o': ['mdou_moctar'],
 'p': ['mdp_wethersfield', 'mdp_syndrome'],
 'q': ['mdq'],
 'r': ['mdr_rundfunkchor',
       'mdr_schlagerwelt',
       'mdr_musiksommer',
       'mdr_fernsehen',
       'mdr_klassik',
       'mdr_aktuell',
       'mdr_kultur',
       'mdr_life',
       'mdr_jump'],
 's': ['mds_gateways', 'mds_america', 'mds_matrix', 'mds_2400'],
 't': ['mdt_david'],
 'u': ['mduduzi_mdantsane',
       'mduduzi_fuzwayo',
       'mduduzi_dlamini',
       'mduduzi_manana',
       'mduduzi_mabaso',
       'mdu_resources',
       'mdu_wi-fi'],
 'v': ['mdvanii', 'mdvip', 'mdv'],
 'x': ['mdx_mouse'],
 'y': ['mdynamix', 'mdy'],
 'z': ['mdzovreti_fortress', 'mdz_shield']}
