
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_qe = {'_': ['qe4', 'qe1', 'qe3'],
 'b': ['qebehsenuef', 'qebchaq', 'qeblehi', 'qebui', 'qebh'],
 'c': ['qec'],
 'd': ['qedarites', 'qedrican', 'qed'],
 'e': ['qeerroo', 'qeelin', 'qeep', 'qee'],
 'f': ['qefm'],
 'h': ['qeha', 'qehi', 'qeh'],
 'l': ['qelichabad',
       'qelutviaq',
       'qelinjlu',
       'qelelevu',
       'qelateh',
       'qeleshe',
       'qelichi',
       'qelij',
       'qelez',
       'qello',
       'qeli'],
 'm': ['qemscan', 'qemal', 'qemah', 'qemu', 'qemm', 'qem'],
 'n': ['qenneshre',
       'qendaxan',
       'qennarit',
       'qender',
       'qenna',
       'qenet',
       'qenko',
       'qeni',
       'qena',
       'qene',
       'qen'],
 'p': ['qepchaq', 'qephom', 'qeparo', 'qep'],
 'q': ['qeqertarsuatsiaat',
       'qeqertarssdaq',
       'qeqertarsuaq',
       'qeqertalik',
       'qeqertat',
       'qeqertaq',
       'qeqqata'],
 'r': ['qernertuarssuit',
       'qernertunnguit',
       'qermezabad',
       'qermezdash',
       'qereshnik',
       'qerqereh',
       'qerkhlar',
       'qermezin',
       'qerkhlu',
       'qernaq',
       'qerret',
       'qerimi',
       'qerqiz',
       'qeran',
       'qeris',
       'qerim',
       'qerq'],
 's': ['qeshnehabad',
       'qeshquneh',
       'qeshlaqlu',
       'qestorat',
       'qeshibes',
       'qeshlaq',
       'qesarat'],
 't': ['qetesh'],
 'x': ['qex'],
 'y': ['qeyzaniyeh',
       'qeysariyeh',
       'qeytasabad',
       'qeytaniyeh',
       'qeysarabad',
       'qeynarjeh',
       'qeysvand',
       'qeysaraq',
       'qeysabad',
       'qeysnab',
       'qeytaqi',
       'qeysar',
       'qeyapa',
       'qeymas',
       'qeydar',
       'qeytas',
       'qeytak',
       'qeydu'],
 'z': ['qezkhachlu',
       'qezelqash',
       'qezmazari',
       'qezelcheh',
       'qezelabad',
       'qezeljeh',
       'qezelqan',
       'qezlijeh',
       'qezlar',
       'qezgeh',
       'qezel']}
