
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-25T22:56:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c0f83df0f0e8700ff0a8e526d34907b2aa44fba",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
