
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rt = {'_': ['rt-thread',
       'rt-m-160',
       'rt-mart',
       'rt.x100',
       'rt-841',
       'rt-20p',
       'rt-20',
       'rt-64',
       'rt-15',
       'rt-11',
       'rt-70',
       'rt-rk',
       'rt-2',
       'rt23',
       'rt-1',
       'rt!',
       'rt1'],
 'a': ['rtaudio',
       'rtaf-2',
       'rtaf-6',
       'rtaf-4',
       'rtaf-5',
       'rtari',
       'rtanj',
       'rtai',
       'rtas',
       'rta'],
 'b': ['rtbf', 'rtb'],
 'c': ['rtcc', 'rtcb', 'rtca', 'rtc'],
 'd': ['rtd'],
 'e': ['rtelnet', 'rte.ie', 'rtejr', 'rtems', 'rte2'],
 'f': ['rtfdc1', 'rtfm', 'rtf1', 'rtfc', 'rtf'],
 'g': ['rtgame', 'rtgs', 'rtg'],
 'h': ['rthk', 'rth'],
 'i': ['rtishchevsky',
       'rtishchevo',
       'rtiox-276',
       'rti-113',
       'rti-150',
       'rti-336',
       'rti-274',
       'rti-353',
       'rti-171',
       'rti-229',
       'rti-371',
       'rti-352',
       'rti-121',
       'rti-126',
       'rti-120',
       'rti-177',
       'rti-112',
       'rti-83',
       'rti-31',
       'rti-32',
       'rti-55',
       'rti-51',
       'rtice',
       'rtina',
       'rti'],
 'j': ['rtj4', 'rtj'],
 'k': ['rtkovo', 'rtkn2', 'rtkn', 'rtk'],
 'l': ['rtl8710',
       'rtlinux',
       'rtl-tvi',
       'rtl/2',
       'rtlup',
       'rtl2',
       'rtl3',
       'rtl+',
       'rtls',
       'rtl9',
       'rtl1',
       'rtl6',
       'rtl'],
 'm': ['rtmpdump', 'rtmark', 'rtma', 'rtmi', 'rtmc', 'rtmp', 'rtml', 'rtm'],
 'n': ['rtn2', 'rtn3', 'rtn1', 'rtn'],
 'o': ['rtorrent', 'rto'],
 'p': ['rtp-midi', 'rtp1', 'rtps', 'rtpc', 'rtp3', 'rtpa', 'rtp2', 'rtp'],
 'q': ['rtq'],
 'r': ['rtr-planeta', 'rtraf', 'rtrfm', 'rtr'],
 's': ['rts/cts', 'rts.fm', 'rts,s', 'rtsh', 'rts'],
 't': ['rtt-150', 'rttnews', 'rttp', 'rtts', 'rtt'],
 'u': ['rtusamhara', 'rtu'],
 'v': ['rtvideo', 'rtveli', 'rtv21', 'rtv-7', 'rtve', 'rtva', 'rtvi', 'rtv'],
 'w': ['rtw'],
 'x': ['rtx2010', 'rtx'],
 'z': ['rtz']}
