
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rr = {'_': ['rr7349'],
 'a': ['rrash-kullaj',
       'rraboshte',
       'rrashbull',
       'rrapshe',
       'rrafshi',
       'rrakala',
       'rrakull',
       'rranxe',
       'rrajce',
       'rragam',
       'rrape',
       'rragc',
       'rrase',
       'rraga',
       'rragb',
       'rras2',
       'rrad',
       'rras',
       'rra'],
 'b': ['rrbp1', 'rrb'],
 'c': ['rrcc', 'rrc'],
 'd': ['rrdtool', 'rrds', 'rrd'],
 'e': ['rreth-greth',
       'rrethinat',
       'rreshen',
       'rregula',
       'rrence',
       'rreuse',
       'rreb1'],
 'f': ['rrfc', 'rrf'],
 'g': ['rrg'],
 'h': ['rrhs', 'rrh'],
 'i': ['rriiccee', 'rrikaj', 'rripe', 'rrif', 'rrim', 'rri'],
 'k': ['rrk'],
 'l': ['rrl'],
 'm': ['rrm2b', 'rrmc', 'rrm2', 'rrm1', 'rrm3', 'rrm'],
 'n': ['rrn3', 'rrn'],
 'o': ['rrogozhine', 'rrostej', 'rromas'],
 'p': ['rrp15', 'rrp1b', 'rrp12', 'rrp1', 'rrp9', 'rrp'],
 'q': ['rrq'],
 'r': ['rrroooaaarrr', 'rrrrrrr!!!', 'rrrecords', 'rrrr', 'rrr'],
 's': ['rrs1', 'rrs'],
 't': ['rrt'],
 'u': ['rrushkull', 'rru']}
