
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rb = {'_': ['rb-3007', 'rb1cc1', 'rb-120', 'rb-101', 'rb-64', 'rb5x'],
 'a': ['rbaf', 'rba'],
 'b': ['rbbs-pc',
       'rbbp9',
       'rbbp7',
       'rbbp8',
       'rbbp4',
       'rbbp6',
       'rbbp5',
       'rbbs',
       'rbb'],
 'c': ['rbcg30', 'rbck1', 'rbcl', 'rbc'],
 'd': ['rbd'],
 'e': ['rbe2'],
 'f': ['rbfox1', 'rbf'],
 'g': ['rbg-azimuth'],
 'h': ['rbhs', 'rbh'],
 'i': ['rbi'],
 'k': ['rbk-500', 'rbk-250', 'rbk'],
 'l': ['rbl'],
 'm': ['rbmedia',
       'rbm33',
       'rbm26',
       'rbm15',
       'rbm25',
       'rbm8a',
       'rbm39',
       'rbm34',
       'rbm23',
       'rbm28',
       'rbm12',
       'rbm10',
       'rbm11',
       'rbm22',
       'rbms1',
       'rbm17',
       'rbm47',
       'rbms3',
       'rbm19',
       'rbm14',
       'rbm9',
       'rbmx',
       'rbms',
       'rbm6',
       'rbm5',
       'rbm3',
       'rbmk',
       'rbm7',
       'rbm4',
       'rbm'],
 'n': ['rbn'],
 'o': ['rbo'],
 'p': ['rbpms', 'rbpf', 'rbp2', 'rbpj', 'rbp1', 'rbp7', 'rbp3', 'rbp'],
 'q': ['rbq'],
 'r': ['rbr'],
 's': ['rbst', 'rbss', 'rbsl', 'rbsd', 'rbsp', 'rbs'],
 't': ['rbti', 'rbt'],
 'u': ['rbu-1200', 'rbu-6000', 'rbu-1000', 'rbu'],
 'v': ['rbv'],
 'w': ['rbw'],
 'x': ['rbx1', 'rbx'],
 'y': ['rbyc', 'rby']}
