
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-25T16:23:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "63fe24c1a021bf730a83b52b0e077ba72c234a36",
 "version": "7.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
