
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sg = {'_': ['sg_heidelberg-kirchheim',
       'sg_flensburg-handewitt',
       'sg_wallau-massenheim',
       'sg_aumund-vegesack',
       'sg_bergmann-borsig',
       'sg_braunschweig',
       'sg-43_goryunov',
       'sg_sacavenense',
       'sg_automotive',
       'sg_arheilgen',
       'sg_egelsbach',
       'sg_adenstedt',
       'sg_andernach',
       'sg_aulendorf',
       'sg_betzdorf',
       'sg_pontebba',
       'sg_biofuels',
       'sg_wannabe',
       'sg_mickten',
       'sg_lucense',
       'sg_holland',
       'sg_rommerz',
       'sg_cortina',
       'sg_formula',
       'sg_records',
       'sg_bornim',
       'sg_essen',
       'sg_lewis'],
 'a': ["sgarbossa's_criteria", 'sgairneach_mhor', 'sga_airlines'],
 'b': ['sgb_championship', 'sgb_premiership', 'sgb-smit_group'],
 'c': ['sgcc_uav'],
 'd': ['sgdc-2', 'sgdc-1', 'sgds'],
 'e': ['sge_group'],
 'f': ['sgf'],
 'g': ['sggs', 'sgg'],
 'h': ['sgh-d500', 'sghc', 'sghs', 'sgh'],
 'i': ['sgi_challenge',
       'sgi_algorithm',
       'sgiath_chuil',
       'sgio_theatre',
       'sgi_dogfight',
       'sgi_crimson',
       'sgi_octane',
       'sgi_1600sw',
       'sgi_europe',
       'sgi_indigo',
       'sgi_prism',
       'sgi_onyx2',
       'sgi_tezro',
       'sgi_virtu',
       'sgi_vpro',
       'sgi_iris',
       'sgi_onyx',
       'sgi_fuel',
       'sgi_indy',
       'sgi_o2'],
 'k': ['sgk3', 'sgk1', 'sgk2', 'sgk'],
 'l': ['sglt2_inhibitor', 'sgl_carbon'],
 'm': ['sgml_entity', 'sgm_light'],
 'n': ['sgnl>05', 'sgnl', 'sgn'],
 'o': ['sgouros_spata',
       'sgor_gaibhre',
       'sgorio_cymru',
       'sgor_gaoith',
       'sgorr_ruadh'],
 'p': ['sgpta', 'sgpl1', 'sgpp1', 'sgpio', 'sgps', 'sgp'],
 'r': ['sgr_j1550-5418',
       'sgr_j1745-2900',
       'sgr_0501+4516',
       'sgr_1935+2154',
       'sgript_cymru',
       'sgr_0525-66',
       'sgr_1806-20',
       'sgr_1627-41',
       'sgr_1900+14',
       'sgrs_rna'],
 's': ['sgsm_network', 'sgs_genesis', 'sgs_essen', 'sgs_s.a.'],
 't': ['sgt._mackenzie',
       'sgt._slaughter',
       'sgt._pecker',
       'sgt._bilko',
       'sgt._smith',
       'sgt._disco',
       'sgt._rock',
       'sgt._frog',
       'sgt_slick',
       'sgt_star'],
 'u': ['sgurr_mhicchoinnich',
       'sgurr_ghiubhsachain',
       'sguman_coinntich',
       'sgurr_dhomhnuill',
       'sgurr_mhurlagain',
       'sgurr_choinnich',
       'sgurr_alasdair',
       'sgurr_fhuaran',
       'sgurr_thuilm',
       'sgurr_dearg',
       'sgurr_innse',
       'sgurr_breac',
       'sgurr_dubh',
       'sgurr_mor'],
 'v': ['sgv_freiberg'],
 'w': ['sgw'],
 'x': ['sgx_centre']}
