
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kb = {'_': ['kb_mashinostroyeniya',
       'kb_prizreni-16',
       'kb_feronikeli',
       'kb_vellaznimi',
       'kb_prishtina',
       'kb_vllaznia',
       'kb_theatres',
       'kb_rahoveci',
       'kb_tochmash',
       'kb_trepca',
       'kb_indela',
       'kb_tirana',
       'kb_kosice',
       'kb_drita',
       'kb_rtv21',
       'kb_lager',
       'kb_home',
       'kb_toys',
       'kb_besa',
       'kb_test',
       'kb_ylli',
       'kb_peja',
       'kb_cup'],
 'a': ['kbal_spean'],
 'b': ['kbbx-fm',
       'kbbq-fm',
       'kbba-lp',
       'kbby-fm',
       'kbbv-cd',
       'kbbn-fm',
       'kbbo-fm',
       'kbbu',
       'kbbb',
       'kbbw',
       'kbbz',
       'kbbi',
       'kbbs',
       'kbbk',
       'kbbo',
       'kbbf',
       'kbbc',
       'kbbm',
       'kbbe',
       'kbbd',
       'kbbr',
       'kbbg',
       'kbbt',
       'kbbl',
       'kbba'],
 'c': ['kbc_duisburg', 'kbc_augusta', 'kbc_band', 'kbc_bank', 'kbc_void'],
 'd': ['kbd_algorithm'],
 'e': ['kbelnice',
       'kbew-fm',
       'kbelany',
       'kbev-fm',
       'kbel-fm',
       'kbeq-fm',
       'kbea-fm',
       'kben-fm',
       'kbem-fm',
       'kbeazy',
       'kbela',
       'kbey',
       'kbex',
       'kbef',
       'kbed',
       'kbej',
       'kbeo',
       'kbeu',
       'kbeb',
       'kbew',
       'kbel',
       'kbek',
       'kbec',
       'kben',
       'kbes',
       'kbeh',
       'kbee',
       'kber',
       'kbet',
       'kbez',
       'kbe'],
 'f': ['kbfl-fm',
       'kbfk-lp',
       'kbfe-lp',
       'kbfp-fm',
       'kbfd-dt',
       'kbfx-cd',
       'kbfx',
       'kbfb',
       'kbft',
       'kbfl',
       'kbfr',
       'kbfm',
       'kbff',
       'kbfs',
       'kbfp',
       'kbfo',
       'kbfc',
       'kbfk',
       'kbfi',
       'kbf'],
 'g': ['kbg_syndrome'],
 'h': ['kbhu-fm',
       'kbhm',
       'kbhi',
       'kbhj',
       'kbhh',
       'kbhe',
       'kbhb',
       'kbho',
       'kbhr',
       'kbhc',
       'kbhn',
       'kbht',
       'kbhs',
       'kbhl',
       'kbhp',
       'kbhw',
       'kbh'],
 'i': ['kbibtex',
       'kbim-tv',
       'kbid-lp',
       'kbim-fm',
       'kbiu',
       'kbij',
       'kbie',
       'kbic',
       'kbis',
       'kbik',
       'kbif',
       'kbia',
       'kbiz',
       'kbib',
       'kbid',
       'kbih',
       'kbix',
       'kbil',
       'kbim',
       'kbig',
       'kbiq',
       'kbit',
       'kbi'],
 'j': ['kbj_architects'],
 'k': ['kbks-fm',
       'kbkb-fm',
       'kbkf-ld',
       'kbki-ld',
       'kbkr',
       'kbkz',
       'kbkb',
       'kbky',
       'kbkv',
       'kbko',
       'kbkf',
       'kbkw',
       'kbkl',
       'kbkk',
       'kbkg',
       'kbk'],
 'l': ['kblq-fm',
       'kblk-lp',
       'kblx-fm',
       'kbln-tv',
       'kblm-lp',
       'kblu-lp',
       'kblb',
       'kblr',
       'kblm',
       'kble',
       'kbli',
       'kblp',
       'kblj',
       'kbla',
       'kblg',
       'kbld',
       'kblf',
       'kblo',
       'kbll',
       'kbls',
       'kblz',
       'kblv',
       'kblu',
       'kblt',
       'kbly',
       'kbl'],
 'm': ['kbm-7_cells'],
 'n': ['kbnt-cd',
       'kbns-cd',
       'kbna-fm',
       'kbnm-lp',
       'kbno-fm',
       'kbnf-lp',
       'kbnz-ld',
       'kbnn',
       'kbng',
       'kbnd',
       'kbnr',
       'kbnp',
       'kbnj',
       'kbnx',
       'kbnu',
       'kbnh',
       'kbna',
       'kbnl',
       'kbnw',
       'kbno',
       'kbn'],
 'o': ['kbo_league'],
 'p': ['kbpx-ld',
       'kbpt-lp',
       'kbpu',
       'kbps',
       'kbpo',
       'kbpt',
       'kbpi',
       'kbpl',
       'kbpy',
       'kbpg',
       'kbpa',
       'kbpk',
       'kbp'],
 'q': ['kbqi', 'kbql', 'kbqb', 'kbqr', 'kbqf', 'kbqq'],
 'r': ['kbr_development', 'kbr_tower'],
 's': ['kbs_america',
       'kbs_music',
       'kbs_media',
       'kbs_world',
       'kbs_tuff',
       'kbs_hall',
       'kbs_cup',
       'kbs_fm',
       'kbs_3',
       'kbs_2',
       'kbs_n',
       'kbs_1'],
 't': ['kbtu_building'],
 'u': ['kbus_pokalturnering'],
 'v': ['kbvb-hd2',
       'kbvu-fm',
       'kbvm',
       'kbvo',
       'kbvb',
       'kbvu',
       'kbvc',
       'kbva',
       'kbvr'],
 'w': ['kbwg-lp',
       'kbwv-lp',
       'kbws-fm',
       'kbwb',
       'kbwe',
       'kbwg',
       'kbww',
       'kbwc',
       'kbwf',
       'kbwd',
       'kbw'],
 'x': ['kbxr', 'kbxb', 'kbxl', 'kbxi', 'kbxn', 'kbxt', 'kbxx', 'kbxs', 'kbx'],
 'y': ['kbyu-fm',
       'kbyo-fm',
       'kbyr-fm',
       'kbyu-tv',
       'kbyb',
       'kbyn',
       'kbyh',
       'kbya',
       'kbyz',
       'kbyr',
       'kbyg',
       'kbyu',
       'kbyo',
       'kbys',
       'kbyi',
       'kby'],
 'z': ['kbzo-ld',
       'kbzc-ld',
       'kbzy',
       'kbzk',
       'kbzm',
       'kbzq',
       'kbzz',
       'kbzd',
       'kbzo',
       'kbzu',
       'kbzi',
       'kbzs',
       'kbze',
       'kbzn',
       'kbzt',
       'kbzc',
       'kbz']}
