
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_iy = {'a': ['iyang-argapura',
       'iyah-gbede',
       'iyashikei',
       'iyannough',
       "iyal'oja",
       'iyarkai',
       'iyalawo',
       'iyatiku',
       'iyakkam',
       'iyaric',
       'iyanya',
       'iyamho',
       'iyambo',
       'iyasa',
       'iyara',
       'iyasu',
       'iyai',
       'iyad',
       'iyaz',
       'iyar',
       'iya'],
 'c': ['iyc'],
 'd': ['iydmma'],
 'e': ['iyede-ame',
       'iyevlevo',
       'iyengra',
       'iyengar',
       'iyeza',
       'iyego',
       'iyela',
       'iyer',
       'iye'],
 'i': ['iyibkhentre', 'iyi-uwa', 'iyidere', 'iyiyi'],
 'm': ['iym'],
 'n': ['iynefer', 'iynx'],
 'o': ['iyotetsu',
       'iyouella',
       'iyouit',
       'iyoite',
       'iyokan',
       'iyore',
       'iyogi',
       'iyov',
       'iyo'],
 'r': ['iyrcae', 'iyri', 'iyr'],
 's': ['iysh'],
 't': ['iytjenu', 'iyt'],
 'u': ['iyulsky', 'iyunga', 'iyumbu', 'iyula'],
 'y': ['iyyapanthangal', 'iyyun']}
