
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ii = {'_': ['ii25,1', 'ii-vi'],
 'a': ['iiac', 'iiab', 'iiap', 'iias', 'iia'],
 'b': ['iib'],
 'c': ["iich'aa", 'iicons', 'iicd', 'iica', 'iict', 'iic'],
 'd': ['iidesjarvi', 'iidabashi', 'iides', 'iida', 'iide'],
 'e': ['iied', 'iies', 'iie'],
 'f': ['iifa', 'iif'],
 'g': ['iigaste'],
 'h': ['iihongo', 'iihl', 'iih'],
 'i': ['iiidrops', 'iii/iv', 'iiiee', 'iiit', 'iiis', 'iiie', 'iii'],
 'j': ['iijarvi', 'iijima', 'iijoki', 'iij'],
 'l': ['iilaste', 'iileh', 'iila', 'iil'],
 'm': ['iimura', 'iimc'],
 'n': ['iinijarvi',
       'iinoya-gu',
       'iindman',
       'iinuma',
       'iinet',
       'iino',
       'iine',
       'iina',
       'iin'],
 'o': ['iiolonioro', 'iio'],
 'p': ['iipf', 'iipa', 'iipm', 'iip'],
 'r': ['iiris', 'iirc', 'iirs', 'iira', 'iir'],
 's': ['iisvesi',
       'iisalmi',
       'iisaku',
       'iisp',
       'iisj',
       'iisu',
       'iisr',
       'iisd',
       'iism',
       'iis'],
 't': ['iittala', 'iitran', 'iitoyo', 'iitti', 'iita', 'iitt', 'iitm', 'iitr'],
 'u': ['iiuni', 'iium', 'iiuc', 'iiu'],
 'v': ['iivantiira', 'iivari', 'iiv'],
 'w': ['iiw'],
 'x': ['iix'],
 'z': ['iizaka', 'iizuna', 'iizumi']}
