
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_wz = {'_': ['wz_cassiopeiae', 'wz_andromedae', 'wz_sagittae', 'wz_cephei'],
 'a': ['wzac-fm',
       'wzaw-ld',
       'wzan',
       'wzaa',
       'wzax',
       'wzaz',
       'wzap',
       'wzam',
       'wzad',
       'wzak'],
 'b': ['wzbj-cd',
       'wzbh',
       'wzbg',
       'wzby',
       'wzba',
       'wzbr',
       'wzbb',
       'wzbl',
       'wzbq',
       'wzbc',
       'wzbf',
       'wzbz',
       'wzbo',
       'wzbk',
       'wzbn',
       'wzbt',
       'wzbd',
       'wzbj'],
 'c': ['wzcl-lp',
       'wzck-ld',
       'wzcb',
       'wzcc',
       'wzct',
       'wzch',
       'wzcp',
       'wzcr',
       'wzcy',
       'wzc'],
 'd': ['wzdol_rzadowy'],
 'e': ['wzes_uav'],
 'f': ['wzfe-lp',
       'wzfi-lp',
       'wzfj',
       'wzfm',
       'wzfr',
       'wzfx',
       'wzfl',
       'wzfc',
       'wzfn',
       'wzft',
       'wzfg'],
 'g': ['wzgorza_krzeslawickie', 'wzgorze_mickiewicza'],
 'h': ['wzhl', 'wzhd', 'wzhr', 'wzht', 'wzhf'],
 'i': ['wziachowo_wielkie', 'wziachowo_male'],
 'j': ['wzjy', 'wzjr', 'wzjo', 'wzjs', 'wzjz'],
 'k': ['wzkq-lp',
       'wzko',
       'wzkt',
       'wzky',
       'wzkr',
       'wzkd',
       'wzks',
       'wzkx',
       'wzkb'],
 'l': ['wzla-fm',
       'wzlp-lp',
       'wzlo',
       'wzlt',
       'wzlx',
       'wzlk',
       'wzlq',
       'wzly',
       'wzlr',
       'wzlb',
       'wzld',
       'wzlf'],
 'm': ['wzmh_architects'],
 'n': ['wznd-lp',
       'wznc-lp',
       'wzna-ld',
       'wzng',
       'wzne',
       'wznf',
       'wznz',
       'wznn',
       'wzno',
       'wzns',
       'wznt',
       'wzna',
       'wznx',
       'wznj',
       'wznl',
       'wzny',
       'wznp'],
 'o': ['wzonka-lad',
       'wzoo-fm',
       'wzoe-fm',
       'wzory',
       'wzoe',
       'wzot',
       'wzol',
       'wzox',
       'wzoo',
       'wzom',
       'wzor',
       'wzoc',
       'wzok',
       'wzos',
       'wzon',
       'wzoz',
       'wzob'],
 'p': ['wzpa-ld', 'wzpx-tv', 'wzph-lp', 'wzpn', 'wzpw', 'wzpl', 'wzpr'],
 'q': ['wzqk', 'wzqs', 'wzqq', 'wzqy', 'wzqz'],
 'r': ['wzrf-lp',
       'wzrx-fm',
       'wzro-lp',
       'wzra-cd',
       'wzrh',
       'wzrx',
       'wzrl',
       'wzrk',
       'wzrb',
       'wzrd',
       'wzrc',
       'wzrv',
       'wzrm',
       'wzrt',
       'wzrq',
       'wzrr'],
 's': ['wzsk', 'wzsr', 'wzsn', 'wzst', 'wzsp'],
 't': ['wzts-ld',
       'wztd-ld',
       'wzti',
       'wztu',
       'wztv',
       'wzte',
       'wztk',
       'wztq',
       'wzta',
       'wztc',
       'wztf',
       'wzth',
       'wztr',
       'wzt'],
 'u': ['wzum-fm', 'wzun-fm', 'wzun', 'wzum', 'wzup', 'wzuu', 'wzus', 'wzu'],
 'v': ['wzvn-tv', 'wzva', 'wzvk', 'wzvl', 'wzvi', 'wzvn'],
 'w': ['wzwk-lp', 'wzww', 'wzwb', 'wzwp', 'wzwz'],
 'x': ['wzxz-cd', 'wzxi', 'wzxl', 'wzxv', 'wzxr', 'wzxx'],
 'y': ['wzyk', 'wzyx', 'wzyq', 'wzyn', 'wzyz', 'wzyp'],
 'z': ['wzzk-fm',
       'wzzo',
       'wzzz',
       'wzzi',
       'wzzn',
       'wzzr',
       'wzzm',
       'wzza',
       'wzzg',
       'wzze',
       'wzzb',
       'wzzx',
       'wzzy',
       'wzzt',
       'wzzw',
       'wzzu',
       'wzzp',
       'wzzq',
       'wzzl']}
