
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jb = {'_': ["jb's_restaurants",
       'jb_catalogue',
       'jb_magsaysay',
       'jb_baretsky',
       "jb's_dudley",
       'jb-3_tiamat',
       'jb_mccuskey',
       'jb_carlson',
       'jb_meijers',
       "jb_young's",
       'jb_simmons',
       'jb_tuhure',
       'jb_derosa',
       'jb_leonor',
       'jb_nagar',
       'jb_blanc',
       'jb_shuck',
       'jb_hi-fi',
       'jb_tower',
       'jb_gill'],
 'a': ['jbala,_idlib', 'jba_motors'],
 'c': ['jbc'],
 'e': ['jbel_tamarrakoit',
       'jbel_tidirhine',
       'jbel_lakhdar',
       'jbel_kissane',
       "jbe'_kruger",
       'jbel_saghro',
       'jbel_outgui',
       'jbel_ayachi',
       'jbel_hamra',
       'jbel_aklim',
       'jbel_sirwa',
       'jbel_hebri'],
 'f': ['jbf'],
 'g': ['jbg_smith'],
 'h': ['jbhs'],
 'i': ['jbi_international', 'jbita,_hama'],
 'j': ['jbj95', 'jbj'],
 'k': ['jbk'],
 'l': ['jbl_paragon'],
 'm': ['jbm'],
 'n': ['jbn-tv', 'jbnd'],
 'o': ['jboss_messaging', 'jboss_tools', 'jboss_seam'],
 'p': ['jbpm'],
 'q': ['jbq'],
 'r': ['jbr'],
 's': ['jbs_s.a.', 'jbs_usa'],
 't': ['jbt_corporation', 'jbtz_trial'],
 'u': ['jbuilder', 'jbu'],
 'v': ['jbv'],
 'w': ['jbw'],
 'z': ['jbz']}
