
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-17T12:00:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f176da71d41635e8854fd601fd6a68102b0c6e5",
 "version": "2.7.10.dev20220820"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
