
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zy = {'_': ['zy_kher_lee'],
 'a': ['zyablikovo,_vologda_oblast'],
 'c': ['zychlin,_pomeranian_voivodeship',
       'zychlin,_piotrkow_county',
       'zychlin,_pleszew_county',
       'zyczyn_railway_station',
       'zycie_szalonym_zyciem',
       'zycie_po_smierci'],
 'd': ['zydowo,_kuyavian-pomeranian_voivodeship',
       'zydowo,_warmian-masurian_voivodeship',
       'zydy,_warmian-masurian_voivodeship',
       'zydy,_masovian_voivodeship',
       'zydowo,_lubusz_voivodeship',
       'zydowo,_mysliborz_county',
       'zydowo,_koszalin_county',
       'zydowo,_wrzesnia_county',
       'zydowo,_koscian_county',
       'zydowo,_gniezno_county',
       'zydowo,_poznan_county'],
 'g': ['zygmuntow,_swietokrzyskie_voivodeship',
       'zygomaticomaxillary_complex_fracture',
       'zygmunty,_podlaskie_voivodeship',
       'zygmunty,_masovian_voivodeship',
       'zygote_intrafallopian_transfer',
       'zygmuntow,_lublin_voivodeship',
       'zygmuntow,_szydlowiec_county',
       'zygmuntow,_przysucha_county',
       'zygmuntow,_wieruszow_county',
       'zygmuntowo,_gmina_glinojeck',
       'zygmunt_florenty_wroblewski',
       'zygmuntow,_pabianice_county',
       'zygmuntowo,_wyszkow_county',
       'zygmunt_witymir_bienkowski',
       'zygmuntowo,_koscian_county',
       'zygmuntow,_radomsko_county',
       'zygmunt_szczesny_felinski',
       'zygmuntowo,_gmina_wilczyn',
       'zygmuntowo,_rawicz_county',
       'zygomaticus_minor_muscle',
       'zygmunt_andrzej_heinrich',
       'zygmuntow,_lowicz_county',
       'zygmuntowo,_gmina_skulsk',
       'zygmunt_wilhelm_birnbaum',
       'zygomaticus_major_muscle',
       'zygmunt_karol_radziwill',
       'zygoma_reduction_plasty',
       'zygmunt_aleksander_wnek',
       'zygmunt_a._piotrowski',
       'zygos_mountain_range',
       'zygocactus_virus_x',
       'zygote_media_group'],
 'k': ['zykovka,_kursk_oblast'],
 'l': ['zyllah_inez_shannon'],
 'm': ['zymer_musiqi_house'],
 'n': ['zyndram_of_maszkowice', 'zynga_with_friends'],
 'r': ['zyryanskoye,_tomsk_oblast',
       'zyrardow_railway_station',
       'zyryanka_west_airport',
       'zyryanov_manor_house'],
 't': ['zytowo,_warmian-masurian_voivodeship', 'zytowo,_masovian_voivodeship'],
 'u': ['zyuzino,_astrakhan_oblast',
       'zyuden_sentai_kyoryuger',
       'zyuratkul_national_park',
       'zyuzino,_moscow_oblast'],
 'w': ['zywkowo,_warmian-masurian_voivodeship',
       'zywkowo,_podlaskie_voivodeship',
       'zywiec_landscape_park']}
