
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_z_ = {'_': ['z0_sex-determination_system',
       'z7_operation_rembrandt',
       'z._alexander_looby',
       'z._randall_stroope',
       'z3_theorem_prover',
       'z:_steel_soldiers',
       'z._vanessa_helder',
       'z._ritchie_house',
       'z88_fem_software',
       'z1_battle_royale',
       'z._d._mangoaela',
       'z._k._matthews',
       'z._g._muhammad',
       'z._s._strother',
       'z._mann_zilla',
       'z._j._stanley',
       'z._n._morrell',
       'z._t._johnson',
       'z._s._leymel',
       'z._f._mgcawu',
       'z._b._rawson',
       'z._a._suleri',
       'z._d._lewis',
       'z8_gnd_5296',
       'z._a._desai',
       'z._n._estes',
       'z_2n_series',
       'z._d._scott',
       'z._z._hill'],
 'c': ['z-class_melbourne_tram',
       'z.c._mindanao_aguilas',
       'z-class_torpedo_boat',
       'z.c.b.j._opera_house',
       'z_canis_majoris',
       'z_comme_zorglub'],
 'e': ['z_experimental_station', 'z_electric_vehicle'],
 'f': ['z-farnesyl_diphosphate_synthase', 'z_for_zachariah'],
 'm': ['z_music_television'],
 'n': ['z_n_model'],
 'o': ['z.o.e._dolores,_i'],
 's': ['z_sculpt_entertainment', 'z_special_unit'],
 'u': ['z_ursae_minoris', 'z_user_group'],
 'v': ['z.vex_fuzz_factory'],
 'w': ['z_with_descender', 'z_with_stroke']}
