
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-22T18:05:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ce46b3d6a7b4053cd2147d6bc72225a1c189ec3",
 "version": "0.2.26.post0.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
