
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ht = {'_': ['ht-talens',
       'ht-//dig',
       'ht-2157',
       'ht-0712',
       'ht1080',
       'ht-18',
       'ht-29',
       'ht-28',
       'ht-7',
       'ht-8',
       'ht3r'],
 'a': ['htaingmathein',
       'htaunghpau',
       'htawmshing',
       'htangprai',
       'htawng-u',
       'htamtang',
       'htawlang',
       'htangsan',
       'htandaw',
       'htatsf1',
       'htatip2',
       'htawgaw',
       'htamane',
       'htaira',
       'htab',
       'htan',
       'hta'],
 'b': ['htb'],
 'c': ['htc-highroad', 'htcondor', 'htcc', 'htc'],
 'd': ['htd'],
 'e': ['htedanshi', 'hteinson', 'hte'],
 'f': ['htf5680a1', 'htf5980', 'htfc', 'htf'],
 'g': ['htgw'],
 'h': ['hths', 'hth'],
 'i': ['htibyuhsaung',
       'htidawgaing',
       'htingrahtap',
       'htilominlo',
       'htigyaing',
       'htimahto',
       'htingra',
       'htingu',
       'htilin',
       'htisom',
       'hti'],
 'j': ['htj'],
 'k': ['htk'],
 'l': ['htlingual', 'htlv-iii', 'htl'],
 'm': ['htmlgiant',
       'html5test',
       'html+time',
       'htmlunit',
       'html-kit',
       'htmldoc',
       'html5',
       'htms',
       'html',
       'htmi',
       'htmw',
       'htm'],
 'n': ['htn'],
 'o': ['htonmalut',
       'htonwaing',
       'htonban',
       'htonbo',
       'htoo',
       'htop',
       'htol',
       'hto'],
 'p': ['htpp', 'htpa', 'htps', 'htp'],
 'r': ['htr-pm',
       'htr-10',
       'htr3b',
       'htr3c',
       'htr3d',
       'htr3a',
       'htr3e',
       'htra2',
       'htree',
       'htra1',
       'htrk',
       'htra',
       'htr'],
 's': ['htsql', 'htsc', 'hts'],
 't': ['httprange-14',
       'httpunit',
       'httrack',
       'htt-as1',
       'httperf',
       'http/2',
       'http/3',
       'httpd',
       'https',
       'httr',
       'htt'],
 'u': ['htu'],
 'v': ['htvc010p', 'htv-x1', 'htv-x', 'htv-1', 'htv-2', 'htv3', 'htv'],
 'w': ['htw'],
 'x': ['htx'],
 'y': ['hty'],
 'z': ['htz']}
