
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hp = {'_': ['hp-19c/-29c',
       'hp-interex',
       'hp-67/-97',
       'hp-19b',
       'hp-17b',
       'hp-16c',
       'hp-41c',
       'hp-32s',
       'hp-20s',
       'hp-12c',
       'hp-34c',
       'hp-fem',
       'hp-18c',
       'hp1bp3',
       'hp-10b',
       'hp-15c',
       'hp-22s',
       'hp-71b',
       'hp-27s',
       'hp-150',
       'hp-42s',
       'hp-35',
       'hp-il',
       'hp-27',
       'hp-01',
       'hp-10',
       'hp-55',
       'hp-ux',
       'hp-45',
       'hp-65',
       'hp-21',
       'hp-22',
       'hp-75',
       'hp-gl',
       'hp-25',
       'hp16',
       'hp11',
       'hp59',
       'hp8',
       'hp3',
       'hp9',
       'hp2',
       'hp1',
       'hp5',
       'hp6',
       'hp4',
       'hp7'],
 'a': ['hpalapyang',
       'hpaungzeik',
       'hpacheleik',
       'hpaungja',
       'hpayonga',
       'hpalawng',
       'hpaochan',
       'hpasawng',
       'hpanaing',
       'hpakant',
       'hpa-an',
       'hpaulu',
       'hpa-23',
       'hpare',
       'hpala',
       'hpaii',
       'hpana',
       'hpao',
       'hpac',
       'hpae',
       'hpa'],
 'b': ['hpb'],
 'c': ['hpcc', 'hpca', 'hpc5', 'hpcx', 'hpc'],
 'd': ['hpd'],
 'e': ['hpe'],
 'f': ['hpfc', 'hpfs', 'hpf'],
 'g': ['hpgv-2', 'hpg80', 'hpgd', 'hpgp', 'hpg'],
 'h': ['hphs', 'hph'],
 'i': ['hpitv', 'hping', 'hpi'],
 'j': ['hpj'],
 'k': ['hpk'],
 'l': ['hplh1', 'hpl'],
 'm': ['hpmpa', 'hpm.1', 'hpms', 'hpm'],
 'n': ['hpnotiq', 'hpn'],
 'o': ['hpongsauk', 'hposandin', 'hpo'],
 'p': ['hppd', 'hppe', 'hpp'],
 'q': ['hpq'],
 'r': ['hproduct', 'hprints', 'hpruso', 'hprcc', 'hpr'],
 's': ['hpschd',
       'hpse2',
       'hpss',
       'hpse',
       'hps6',
       'hps5',
       'hps3',
       'hps1',
       'hps4',
       'hps'],
 't': ['hpte', 'hpti', 'hpt'],
 'u': ['hpunavirus', 'hpue', 'hpu'],
 'v': ['hpv-1'],
 'w': ['hpw'],
 'x': ['hpx'],
 'y': ['hpyithpyaw', 'hpyikrang', 'hpy']}
