"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.entity.logged_data_pb2
import layerapi.api.entity.logged_model_metric_pb2
import layerapi.api.ids_pb2
import layerapi.api.value.logged_data_type_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class LogModelMetricRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    METRIC_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    @property
    def metric(self) -> api.entity.logged_model_metric_pb2.LoggedModelMetric: ...
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        metric: typing.Optional[api.entity.logged_model_metric_pb2.LoggedModelMetric] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["metric",b"metric","model_train_id",b"model_train_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["metric",b"metric","model_train_id",b"model_train_id"]) -> None: ...
global___LogModelMetricRequest = LogModelMetricRequest

class LogModelMetricResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_METRIC_ID_FIELD_NUMBER: builtins.int
    @property
    def model_metric_id(self) -> api.ids_pb2.ModelMetricId: ...
    def __init__(self,
        *,
        model_metric_id: typing.Optional[api.ids_pb2.ModelMetricId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["model_metric_id",b"model_metric_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["model_metric_id",b"model_metric_id"]) -> None: ...
global___LogModelMetricResponse = LogModelMetricResponse

class LogDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    DATASET_BUILD_ID_FIELD_NUMBER: builtins.int
    UNIQUE_TAG_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    EPOCH_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    @property
    def dataset_build_id(self) -> api.ids_pb2.DatasetBuildId: ...
    unique_tag: typing.Text
    type: api.value.logged_data_type_pb2.LoggedDataType.ValueType
    text: typing.Text
    epoch: builtins.int
    category: typing.Text
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        dataset_build_id: typing.Optional[api.ids_pb2.DatasetBuildId] = ...,
        unique_tag: typing.Text = ...,
        type: api.value.logged_data_type_pb2.LoggedDataType.ValueType = ...,
        text: typing.Text = ...,
        epoch: builtins.int = ...,
        category: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data",b"data","dataset_build_id",b"dataset_build_id","entity_id",b"entity_id","model_train_id",b"model_train_id","text",b"text"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["category",b"category","data",b"data","dataset_build_id",b"dataset_build_id","entity_id",b"entity_id","epoch",b"epoch","model_train_id",b"model_train_id","text",b"text","type",b"type","unique_tag",b"unique_tag"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data",b"data"]) -> typing.Optional[typing_extensions.Literal["text"]]: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["entity_id",b"entity_id"]) -> typing.Optional[typing_extensions.Literal["model_train_id","dataset_build_id"]]: ...
global___LogDataRequest = LogDataRequest

class LogDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LOGGED_DATA_ID_FIELD_NUMBER: builtins.int
    S3_PATH_FIELD_NUMBER: builtins.int
    @property
    def logged_data_id(self) -> api.ids_pb2.LoggedDataId: ...
    s3_path: typing.Text
    """s3_path is only returned in the case of LoggedDataTypes BLOB, IMAGE, VIDEO, FILE, DIRECTORY, this is an S3 path that we 'll write into."""

    def __init__(self,
        *,
        logged_data_id: typing.Optional[api.ids_pb2.LoggedDataId] = ...,
        s3_path: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["logged_data_id",b"logged_data_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["logged_data_id",b"logged_data_id","s3_path",b"s3_path"]) -> None: ...
global___LogDataResponse = LogDataResponse

class GetModelTrainMetricRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    UNIQUE_TAG_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    unique_tag: typing.Text
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        unique_tag: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["model_train_id",b"model_train_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["model_train_id",b"model_train_id","unique_tag",b"unique_tag"]) -> None: ...
global___GetModelTrainMetricRequest = GetModelTrainMetricRequest

class GetModelTrainMetricResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    METRIC_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    @property
    def metric(self) -> api.entity.logged_model_metric_pb2.LoggedModelMetric: ...
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        metric: typing.Optional[api.entity.logged_model_metric_pb2.LoggedModelMetric] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["metric",b"metric","model_train_id",b"model_train_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["metric",b"metric","model_train_id",b"model_train_id"]) -> None: ...
global___GetModelTrainMetricResponse = GetModelTrainMetricResponse

class GetAllModelTrainMetricsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["model_train_id",b"model_train_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["model_train_id",b"model_train_id"]) -> None: ...
global___GetAllModelTrainMetricsRequest = GetAllModelTrainMetricsRequest

class GetAllModelTrainMetricsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    METRIC_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    @property
    def metric(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[api.entity.logged_model_metric_pb2.LoggedModelMetric]: ...
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        metric: typing.Optional[typing.Iterable[api.entity.logged_model_metric_pb2.LoggedModelMetric]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["model_train_id",b"model_train_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["metric",b"metric","model_train_id",b"model_train_id"]) -> None: ...
global___GetAllModelTrainMetricsResponse = GetAllModelTrainMetricsResponse

class GetLoggedDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    DATASET_BUILD_ID_FIELD_NUMBER: builtins.int
    UNIQUE_TAG_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    @property
    def dataset_build_id(self) -> api.ids_pb2.DatasetBuildId: ...
    unique_tag: typing.Text
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        dataset_build_id: typing.Optional[api.ids_pb2.DatasetBuildId] = ...,
        unique_tag: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dataset_build_id",b"dataset_build_id","entity_id",b"entity_id","model_train_id",b"model_train_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dataset_build_id",b"dataset_build_id","entity_id",b"entity_id","model_train_id",b"model_train_id","unique_tag",b"unique_tag"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["entity_id",b"entity_id"]) -> typing.Optional[typing_extensions.Literal["model_train_id","dataset_build_id"]]: ...
global___GetLoggedDataRequest = GetLoggedDataRequest

class GetLoggedDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    DATASET_BUILD_ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    @property
    def dataset_build_id(self) -> api.ids_pb2.DatasetBuildId: ...
    @property
    def data(self) -> api.entity.logged_data_pb2.LoggedData: ...
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        dataset_build_id: typing.Optional[api.ids_pb2.DatasetBuildId] = ...,
        data: typing.Optional[api.entity.logged_data_pb2.LoggedData] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data",b"data","dataset_build_id",b"dataset_build_id","entity_id",b"entity_id","model_train_id",b"model_train_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","dataset_build_id",b"dataset_build_id","entity_id",b"entity_id","model_train_id",b"model_train_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["entity_id",b"entity_id"]) -> typing.Optional[typing_extensions.Literal["model_train_id","dataset_build_id"]]: ...
global___GetLoggedDataResponse = GetLoggedDataResponse

class GetAllLoggedDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    DATASET_BUILD_ID_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    @property
    def dataset_build_id(self) -> api.ids_pb2.DatasetBuildId: ...
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        dataset_build_id: typing.Optional[api.ids_pb2.DatasetBuildId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dataset_build_id",b"dataset_build_id","entity_id",b"entity_id","model_train_id",b"model_train_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dataset_build_id",b"dataset_build_id","entity_id",b"entity_id","model_train_id",b"model_train_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["entity_id",b"entity_id"]) -> typing.Optional[typing_extensions.Literal["model_train_id","dataset_build_id"]]: ...
global___GetAllLoggedDataRequest = GetAllLoggedDataRequest

class GetAllLoggedDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    DATASET_BUILD_ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    @property
    def dataset_build_id(self) -> api.ids_pb2.DatasetBuildId: ...
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[api.entity.logged_data_pb2.LoggedData]: ...
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        dataset_build_id: typing.Optional[api.ids_pb2.DatasetBuildId] = ...,
        data: typing.Optional[typing.Iterable[api.entity.logged_data_pb2.LoggedData]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dataset_build_id",b"dataset_build_id","entity_id",b"entity_id","model_train_id",b"model_train_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","dataset_build_id",b"dataset_build_id","entity_id",b"entity_id","model_train_id",b"model_train_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["entity_id",b"entity_id"]) -> typing.Optional[typing_extensions.Literal["model_train_id","dataset_build_id"]]: ...
global___GetAllLoggedDataResponse = GetAllLoggedDataResponse
