
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_eh = {'_': ['eh_postcode_area', 'eh,_kasi_bata', 'eh_fi_amal', 'eh,_la_bas'],
 'a': ['ehattesaht_first_nation',
       'ehab_moustafa_mansour',
       'ehab_al_shihabi',
       'ehab_el_masry'],
 'c': ['ehc_st._moritz', 'ehc_team_wien'],
 'd': ['ehd_protein_family'],
 'e': ['eheliyagoda_divisional_secretariat',
       'ehetuwewa_divisional_secretariat',
       'eheliyagoda_electoral_district',
       'eheliyagoda_polling_division',
       'ehen_vor_gericht'],
 'f': ['ehf_champions_league',
       'ehf_coefficient_rank',
       'ehf_challenge_trophy',
       'ehf_european_league',
       'ehf_european_cup',
       "ehf_nations'_cup",
       'ehf_euro_2020'],
 'i': ['ehingen,_middle_franconia',
       'ehime_at-large_district',
       'ehime_mandarin_pirates',
       'ehime_asahi_television',
       'ehigie_edobor_uzamere',
       "ehime_women's_college",
       'ehie_ogerenye_edison',
       'ehime_orange_vikings',
       'ehime_fc_ladies',
       'ehingen_am_ries'],
 'j': ['ehjeh_ascher_ehjeh'],
 'l': ['ehlanzeni_district_municipality',
       'ehlers_round_barn',
       'ehle_house_site'],
 'o': ['ehon_hyaku_monogatari',
       'ehove_career_center',
       'eho_hamara_jeevna',
       'eho_mia_angalia'],
 'p': ['ehp_spectral_sequence'],
 'r': ["ehrenpreis's_fundamental_principle",
       'ehrc-ohchr_tigray_investigation',
       'ehrlichiosis_ewingii_infection',
       'ehrlichia_wisconsin_hm543746',
       "ehrhart's_volume_conjecture",
       'ehrlich_park,_bloemfontein',
       'ehrmann_commonwealth_dairy',
       'ehrlich_ascites_carcinoma',
       'ehrhardt,_south_carolina',
       'ehrenpokal_der_luftwaffe',
       'ehrenburg,_lower_saxony',
       'ehrgott_bernhard_bendl',
       'ehrenfried_von_willich',
       'ehrich_and_graetz',
       'ehre_vater_artist',
       'ehrman_syme_nadal'],
 's': ['ehsanabad,_north_khorasan',
       'ehsan_khan_nakhichevansky',
       'ehsan_ghazizadeh_hashemi',
       'ehsanollah_khan_dustdar',
       'ehsaan_mosque,_mannheim',
       'ehsan_mohajer_shojaei',
       'ehsan_ghaem_maghami',
       'ehsaas:_the_feeling',
       'ehsan_khajeh_amiri',
       'ehsan_elahi_zaheer',
       'ehsan_riaz_fatyana',
       'ehsan_k._matoori',
       'ehsan_ullah_khan',
       'ehsaas_is_tarah',
       'ehsan_h._feroz',
       'ehsan_ali_khan',
       'ehsan_ul_haq'],
 't': ['ehtesham_ali_khan', 'ehtsham_ul_haq'],
 'u': ['ehud_r._toledano', 'ehud_de_shalit']}
