
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cn = {'_': ['cn_beachburg_subdivision',
       'cn_alderdale_subdivision',
       'cn_newmarket_subdivision',
       'cn_kingston_subdivision',
       'cn_sabadell_basketball',
       'cn_halton_subdivision',
       'cn_york_subdivision',
       'cn_bala_subdivision',
       'cn_boxcab_electric',
       'cn_times_books',
       'cn_105_f1',
       'cn_90_f4'],
 'a': ['cna_arena_akita'],
 'b': ['cnbc_on_assignment', 'cnbc_market_wrap'],
 'c': ['cncd_decision_323/2006',
       'cnc_plunge_milling',
       'cncc_charity_cup',
       'cncc_league_cup',
       'cnc_wood_router'],
 'e': ['cnemidophorus_sexlineatus_viridis', 'cnec_christian_college'],
 'g': ['cng_processing_a/s'],
 'i': ['cnicht_north_top'],
 'k': ['cnk_operating_system'],
 'l': ['cnl_financial_group'],
 'n': ['cnn/youtube_presidential_debates',
       'cnnc_international_limited',
       'cnn_philippines_newsroom',
       'cnn_business_traveller',
       'cnn_checkout_channel',
       'cnn_freedom_project',
       'cnn_sunday_morning',
       'cnn_world_sport',
       'cnn_live_today',
       'cnn_en_espanol',
       'cnn_world_news',
       'cnn_v._trump'],
 'o': ['cnoc_an_fhreiceadain',
       'cno_financial_group',
       'cnoc_an_chuillinn',
       'cnoc_na_toinne',
       'cnoc_na_peiste'],
 'r': ['cnr_spadina_roundhouse', 'cnrs_silver_medal', 'cnrs_gold_medal'],
 't': ['cntrl:_beyond_edm'],
 'u': ['cnut_of_northumbria'],
 'w': ['cnw_marketing_research']}
