
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cf = {'_': ['cf_garde_republicaine/siaf',
       'cf-18_demonstration_team',
       'cf_gendarmerie_nationale',
       'cf_gimnastico_alcazar',
       'cf_montreal_academy',
       'cf_panaderia_pulido',
       'cf_sporting_mahones',
       'cf_rayo_majadahonda',
       'cf_atletic_america',
       'cf_recambios_colon',
       'cf_atletico_ciudad',
       'cf_trival_valderas',
       'cf_lorca_deportiva',
       'cf_huracan_moncada',
       'cf_gandario_sanse',
       'cf_liberty_oradea',
       'cf_torre_levante',
       'cf_postcode_area',
       'cf_reus_deportiu',
       'cf_fuenlabrada_b',
       'cf_montreal_u23',
       'cf_canelas_2010',
       'cf_union_viera',
       'cf_os_balantas',
       'cf_sant_rafel',
       'cf_ardoi_fe',
       'cf_rapa_nui',
       'cf_la_nucia',
       'cf_cable_tv',
       'cf_la_union'],
 'a': ['cfa_redshift_survey', 'cfa2_great_wall'],
 'b': ['cfb_halifax_cashspiel',
       'cfb_currie,_calgary',
       'cfb_st._hubert',
       'cfb_moose_jaw',
       'cfb_goose_bay',
       'cfb_north_bay',
       'cfb_cold_lake'],
 'c': ['cfc_hertha_06'],
 'd': ['cfdt_finance_federation', 'cfd_mountain_view', 'cfd_in_buildings'],
 'i': ['cfi_international_race'],
 'l': ['cfl_yards_leaders',
       'cfl_cargo_denmark',
       'cfl_all-star_game',
       "cfl_football_'99",
       'cfl_class_2300',
       'cfl_class_2200',
       'cfl_class_3000',
       'cfl_class_3600',
       'cfl_class_4000',
       'cfl_class_2000',
       'cfl_line_30',
       'cfl_line_60',
       'cfl_line_10',
       'cfl_line_70',
       'cfl_line_80',
       'cfl_line_90',
       'cfl_line_50',
       'cfl_on_cbc',
       'cfl_on_nbc',
       'cfl_on_tsn',
       'cfl_on_ctv'],
 'm': ['cfm_international_cfm56',
       'cfm_international_leap',
       'cfmetr,_nanoose_bay',
       'cfm_air_dardo'],
 'p': ['cfpl_television_tower'],
 'r': ['cfr_turnu_severin',
       'cfr-class_040_dh',
       'cfr_class_tea',
       'cfr_class_47',
       'cfr_ii_cluj'],
 's': ['cfs_bisontes_castellon',
       'cfs_resolution_island',
       'cfs_frobisher_bay',
       'cfs_sioux_lookout',
       'cfs_baldy_hughes',
       'cfs_mont_apica',
       "cfs_st._john's",
       'cfs_mill_cove'],
 't': ['cftc_whistleblower_program',
       'cftr_inhibitory_factor',
       'cftri_school,_mysore'],
 'u': ['cfu_u-20_tournament', 'cfu_youth_cup']}
