
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rz = {'a': ['rza_production_discography',
       'rzasawa,_lodz_voivodeship',
       'rzadza,_gmina_stanislawow',
       'rzasnik,_wyszkow_county',
       'rzadza,_gmina_jakubow'],
 'e': ['rzeczyca,_kuyavian-pomeranian_voivodeship',
       'rzegocin,_kuyavian-pomeranian_voivodeship',
       'rzeszowek,_swietokrzyskie_voivodeship',
       'rzepki,_warmian-masurian_voivodeship',
       'rzepinek,_swietokrzyskie_voivodeship',
       'rzegocin,_swietokrzyskie_voivodeship',
       'rzeplin,_podkarpackie_voivodeship',
       'rzepnik,_podkarpackie_voivodeship',
       'rzemien,_podkarpackie_voivodeship',
       'rzepiska,_pomeranian_voivodeship',
       'rzeczyca-kolonia,_krasnik_county',
       'rzedkowice,_silesian_voivodeship',
       'rzeczyca-kolonia,_pulawy_county',
       'rzepiska,_podlaskie_voivodeship',
       'rzeczyce,_silesian_voivodeship',
       'rzeczkow,_masovian_voivodeship',
       'rzeczkow,_skierniewice_county',
       'rzezawy,_masovian_voivodeship',
       'rzeczki,_masovian_voivodeship',
       'rzedowice,_opole_voivodeship',
       'rzeczyce,_lublin_voivodeship',
       'rzedkow,_skierniewice_county',
       'rzepinek,_lubusz_voivodeship',
       'rzepki,_masovian_voivodeship',
       'rzedowice,_proszowice_county',
       'rzeplin,_lublin_voivodeship',
       'rzeczyca,_swiebodzin_county',
       'rzeszowski_family_homicides',
       'rzeczyca,_polkowice_county',
       'rzeczyca,_poddebice_county',
       'rzezawy,_lodz_voivodeship',
       'rzechta,_lodz_voivodeship',
       'rzedowice,_miechow_county',
       'rzepki,_lodz_voivodeship',
       'rzeczyca,_gmina_rzeczyca',
       'rzesnica,_drawsko_county',
       'rzedkow,_leczyca_county',
       'rzeczyca,_pulawy_county',
       'rzeczyca,_otwock_county',
       'rzeczyca,_gmina_ulhowek',
       'rzepin_railway_station',
       'rzeszow_power_station',
       'rzeczkow,_rawa_county',
       'rzepin_train_disaster'],
 'h': ['rzhavets,_voronezh_oblast',
       'rzhevsky_versus_napoleon',
       'rzhyshchiv_urban_hromada'],
 'u': ['rzuchow,_swietokrzyskie_voivodeship',
       'rzuchow,_podkarpackie_voivodeship',
       'rzuchow,_silesian_voivodeship'],
 'y': ['rzym,_kuyavian-pomeranian_voivodeship',
       'rzyszczewko,_szczecinek_county',
       'rzyszczewko,_koszalin_county',
       'rzyszczewo,_bialogard_county',
       'rzymiec,_skierniewice_county',
       'rzyszczewko,_slawno_county',
       'rzyszczewo,_slawno_county',
       'rzym,_kartuzy_county',
       'rzymiec,_rawa_county']}
