
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rn = {'_': ['rn_shetty_stadium', 'rn_pudur,_erode'],
 'a': ['rna-induced_transcriptional_silencing',
       'rna-induced_silencing_complex',
       'rna_immunoprecipitation_chip',
       'rna-dependent_rna_polymerase',
       'rna-binding_protein_database',
       'rna-directed_dna_methylation',
       'rna_modification_database',
       'rna-binding_protein_fus',
       'rna-binding_protein_ews',
       'rnai_global_initiative',
       'rna_recognition_motif',
       'rna_helicase_database',
       'rnase_h-dependent_pcr',
       'rna_integrity_number',
       'rnad_broughton_moor',
       'rna,_18s_ribosomal',
       'rna_polymerase_iii',
       'rna_polymerase_ii',
       'rnas_hornsea_mere',
       'rnas_prawle_point',
       'rna_polymerase_iv',
       'rna_polymerase_i',
       'rna_polymerase_v',
       'rna_helicase_a',
       'rna_tie_club'],
 'b': ['rnb_global_university', 'rnb_fridays_live'],
 'e': ['rne-ii_rna_motif'],
 'f': ['rnf_motogp_racing'],
 'i': ['rnib_college,_loughborough', 'rnib_connect_radio'],
 'l': ['rnlb_queen_victoria', 'rnlb_mary_stanford'],
 'm': ['rnmd_milford_haven'],
 'o': ['rnov_shabab_oman'],
 'z': ['rnzaf_station_waipapakauri',
       'rnzaf_station_weraroa',
       'rnzaf_base_woodbourne',
       'rnzaf_security_forces',
       'rnzaf_base_auckland',
       'rnzaf_base_ohakea',
       'rnzaf_dip_flat']}
