
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rw = {'_': ['rw_ursae_minoris', 'rw_racing_gp', 'rw_kit_cars'],
 'a': ['rwanda-united_states_relations',
       'rwanda-south_africa_relations',
       'rwanda_basketball_federation',
       'rwamwanja_refugee_settlement',
       'rwandan_reproductive_health',
       'rwanda_investigation_bureau',
       'rwanda_football_federation',
       'rwamwanja_secondary_school',
       'rwanda_cricket_association',
       'rwanda_development_gateway',
       'rwanda_scouts_association',
       'rwanda_cycling_federation',
       'rwanda_revenue_authority',
       'rwanda_national_congress',
       'rwanda_development_board',
       'rwandan_second_division',
       'rwandese_national_union',
       'rwanda_african_mole-rat',
       'rwanda_development_bank',
       'rwandan_patriotic_front',
       'rwandan_socialist_party',
       'rwandan_genocide_denial',
       'rwandan_nationality_law',
       'rwanda_rugby_federation',
       'rwanda_national_police',
       'rwanda_cricket_stadium',
       'rwanda_education_board',
       'rwandan_sign_language',
       'rwanda_premier_league',
       'rwanda_stock_exchange',
       'rwanda_film_festival',
       'rwanda_defence_force',
       'rwanda_cancer_centre',
       'rwandan_plane_crash',
       'rwanda_energy_group',
       'rwanda_pour_memoire',
       'rwandair_flight_205',
       'rwandan_shaggy_rat',
       'rwandan_heroes_cup',
       'rwandan_air_force',
       'rwang_pam_stadium',
       'rwandan_civil_war',
       'rwandan_red_cross'],
 'b': ['rwby:_grimm_eclipse', 'rwb_ladies_cup'],
 'e': ['rwenzori-virunga_montane_moorlands',
       'rwenzori_double-collared_sunbird',
       'rwenzori_hill_babbler',
       'rwesero_art_museum'],
 'j': ['rwjbarnabas_health_arena'],
 't': ['rwth_international_academy',
       'rwth_aachen_university',
       'rwth_fsa_toolkit']}
