
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rm = {'_': ['rm_films_international',
       'rm_postcode_area',
       'rm_williams_way',
       'rm_w/a_vu'],
 'a': ['rma_tube_designation', 'rma_gold_airways'],
 'd': ['rmd_engineering_college'],
 'f': ['rmf_rna_motif'],
 'i': ['rmi_harmonic_synthesizer',
       'rmit_university_library',
       'rmit_university_vietnam',
       'rmit_building_220',
       'rmit_building_11',
       'rmit_building_8',
       'rmit_design_hub'],
 'k': ['rmk_engineering_college', 'rmk_residential_school'],
 'l': ['rml_6.6-inch_howitzer',
       'rml_6.3-inch_howitzer',
       'rml_short_wheelbase',
       'rml_8-inch_howitzer',
       'rml_64-pounder_gun',
       'rml_40-pounder_gun',
       'rmli_gosport_f.c.',
       'rml_7-inch_gun'],
 'm': ['rmmv_capetown_castle',
       'rmmv_stirling_castle',
       'rmmv_athlone_castle',
       'rmmv_survivor_r'],
 'r': ['rmrs_pg_college'],
 's': ['rms_pendennis_castle',
       'rms_transvaal_castle',
       'rms_queen_elizabeth',
       'rms_dunottar_castle',
       'rms_arundel_castle',
       'rms_durham_castle',
       'rms_fort_victoria',
       'rms_lady_hawkins',
       "rms_mona's_isle",
       'rms_lady_nelson',
       'rms_wray_castle',
       'rms_queen_mary',
       'rms_manx_maid',
       'rms_st_helena'],
 'v': ['rmv_scillonian_iii']}
