
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ns = {'_': ['ns_intercity_materieel',
       'ns_sprinter_lighttrain',
       'ns1_influenza_protein',
       'ns_brendan_simbwaye',
       'ns_timetable_2010',
       'ns1_antigen_test',
       'ns_class_airship',
       'ns_betaria_f.c.',
       'ns_wanderers_rc',
       'ns_class_1300',
       'ns_class_1100',
       'ns_class_2400',
       'ns_class_1500',
       'ns_class_6400',
       'ns_class_1200',
       'ns_class_8800',
       'ns_class_1000',
       'ns_class_1700',
       'ns_class_1600',
       'ns_class_186',
       'ns_class_600',
       'ns_class_400',
       'ns_class_200',
       "ns_mat_'54",
       "ns_mat_'64",
       'ns_dm_90'],
 'a': ['nsaid_hypersensitivity_reactions',
       'nsa_encryption_systems',
       'nsa_product_types',
       'nsambya_home_care',
       'nsa_ant_catalog'],
 'b': ['nsb_intercity_express',
       'nsb_class_xxii',
       'nsb_class_xxi',
       'nsb_class_83',
       'nsb_class_70',
       'nsb_class_73',
       'nsb_class_88',
       'nsb_class_64',
       'nsb_class_72',
       'nsb_class_22',
       'nsb_class_30',
       'nsb_class_21',
       'nsb_class_69',
       'nsb_class_67',
       'nsb_class_68',
       'nsb_class_66',
       'nsb_class_65',
       'nsb_class_87',
       'nsb_class_49',
       'nsb_class_62',
       'nsb_class_86',
       'nsb_class_iv',
       'nsb_el_11',
       'nsb_el_16',
       'nsb_el_13',
       'nsb_el_15',
       'nsb_el_12',
       'nsb_el_14',
       'nsb_el_18',
       'nsb_el_17',
       'nsb_di_6',
       'nsb_el_7',
       'nsb_el_8',
       'nsb_el_5',
       'nsb_di_2',
       'nsb_di_8',
       'nsb_di_3',
       'nsb_di_4',
       'nsb_el_2',
       'nsb_el_3',
       'nsb_di_1',
       'nsb_el_1',
       'nsb_el_4',
       'nsb_el_9',
       'nsb_el_6'],
 'c': ['nscro_national_championships',
       'nscad_lithography_workshop',
       'nscad_conceptual_art',
       'nscro_champions_cup',
       'nsc_marathon_02'],
 'e': ['nse_co-location_scam', 'nsez_metro_station'],
 'h': ['nshm_knowledge_campus'],
 'i': ['nsir4_small_rna'],
 'k': ['nsk_trade_city'],
 'l': ['nsl_second_division'],
 'o': ['nsofwa_petronella_sampa'],
 'r': ['nsr_h1_class', 'nsr_m_class', 'nsr_h_class', 'nsr_g_class'],
 's': ['nss_college_rajakumari',
       'nss_college,_ottapalam',
       'nssf_mbarara_complex',
       'nss_college,_nenmara',
       'nss_law_college'],
 't': ['nst_niigata_open', 'nst_bs_650'],
 'u': ['nsu/fiat_weinsberg_500',
       'nsu_university_school',
       'nsumbu_national_park',
       'nsu-pipe_25/40_ps',
       'nsu-pipe_15/24_ps',
       'nsu_delphin_iii',
       'nsu_quick_50',
       'nsu_typ_110',
       'nsu_ro_80'],
 'v': ['nsv_machine_gun'],
 'w': ["nswrl_women's_premiership",
       'nsw_schoolhouse_museum',
       'nsw_bookstall_company',
       'nsw_business_chamber',
       'nsw_minerals_council',
       'nsw_koori_knockout',
       'nsw_challenge_cup',
       'nsw_police_legacy',
       'nsw_fair_trading',
       'nsw_kiama_fowler',
       'nsw_league_three',
       'nsw_public_works',
       'nsw_rail_museum',
       'nsw_law_reports',
       'nsw_photo_card',
       'nsw_league_two',
       'nsw_league_one'],
 'y': ['nsync_in_concert']}
