
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nd = {'_': ['nd_slovenj_gradec', 'nd_ilirija_1911', 'nd_mura_05'],
 'a': ['ndamira_catherine_atwikiire',
       'ndabezinhle_sibanda_sigogo',
       'ndakom_valerie_ndeidoum',
       'ndahiro_ii_cyamatare',
       'ndawula_of_buganda',
       'ndave_david_njoku',
       'ndate_yalla_mbodj'],
 'e': ['ndebele_house_painting',
       'ndejje_university_fc',
       'ndeye_binta_diongue',
       'ndeye_fatou_ndiaye',
       'ndeye_fatou_soumah',
       'ndey_tapha_sosseh',
       'ndeye_fatou_kane',
       'ndeg5_on_tour'],
 'g': ['ndg_auckland_centre'],
 'i': ['ndidi_okonkwo_nwuneli', 'ndiss_kaba_badji', 'ndi_oji_abam'],
 'j': ['ndjole_ville_airport'],
 'k': ['ndk_metro_station'],
 'l': ['ndlambe_local_municipality', 'ndlovu_v_ngcobo'],
 'o': ['ndonga_linena_constituency',
       'ndongo_serge_philippe',
       'ndola_city_council',
       'ndoua_lydie_yamkou',
       'ndop_prison_break',
       'ndoto_za_elibidi',
       'ndoc_mark_gega'],
 'r': ['ndr_elbphilharmonie_orchestra',
       'ndr_kultur_sachbuchpreis',
       'ndri_elise_kangah'],
 'u': ['ndungu_land_commission',
       'nduom_sports_stadium',
       'ndut_initiation_rite',
       'ndumo_game_reserve',
       'ndubuisi_kanu_park',
       'ndumbe_lobe_bell'],
 'w': ['ndwedwe_local_municipality']}
