
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pf = {'_': ['pf_umbertide', 'pf_flyers', 'pf_magic', 'pf_schio', 'pf_fire'],
 'a': ['pfaffenthal-kirchberg_funicular',
       'pfaffenhofen,_baden-wurttemberg',
       'pfaffikon-arth-goldau_railway',
       'pfahlbaumuseum_unteruhldingen',
       'pfadfinderbund_weltenbummler',
       'pfalzgrafenstein_castle',
       'pfannenstiel_incision',
       'pfau-crichton_cottage',
       'pfaffian_orientation',
       'pfaffenhofen,_tyrol',
       'pfalz_flugzeugwerke',
       'pfaffian_constraint',
       'pfaffendorf_bridge',
       'pfaffikon_district',
       'pfaueninsel_palace',
       'pfaffikon,_zurich',
       'pfaffian_function',
       'pfaffing,_austria',
       'pfaffikon,_schwyz',
       'pfaffia_glomerata',
       'pfadi_winterthur',
       'pfaffikon_castle',
       'pfaffen_saddle',
       'pfaffia_jubata',
       'pfarrer_braun',
       'pfafers_abbey',
       'pfaff_island',
       'pfa_scotland',
       'pfalz_d.viii',
       'pfalz_d.vii',
       'pfalz_dr.ii',
       'pfalz_d.xii',
       'pfalz_d.iii',
       'pfalz_d.xv',
       'pfalz_dr.i',
       'pfalz_d.vi'],
 'b': ['pfb'],
 'c': ['pfc_energy', 'pfc_burgas', 'pfc_bansko', 'pfc_sochi', 'pfc_sumy'],
 'd': ['pfd_allowance'],
 'e': ['pfeiffer-redwood_creek',
       'pferderennplatz_meran',
       'pfeiffera_monacantha',
       'pfeiffer_university',
       'pfeiffer,_arkansas',
       'pfeiffer_syndrome',
       'pfeffingen_castle',
       'pfeffer_integral',
       'pfeiffer_falcons',
       'pfeiffer_vacuum',
       'pfeiffer_effect',
       'pfeifer,_kansas',
       'pfeiffer_georgi',
       'pfeiffer_house',
       'pfeiffer,_ohio',
       'pfeiffer_beach',
       'pfeffel_family',
       'pfelderer_tal'],
 'f': ['pff_league'],
 'g': ['pfg'],
 'h': ['pfhs'],
 'i': ['pfitzner-moffatt_oxidation',
       'pfitzneriana_olivescens',
       'pfitzneriella_monticola',
       'pfitzneriella_lucicola',
       'pfitzneriella_similis',
       'pfitzneriana_prosopus',
       'pfingsten,_minnesota',
       'pfiesteria_shumwayae',
       'pfiesteria_piscicida',
       'pfitzneriella_remota',
       'pfitzinger_reaction',
       'pfitzneriana_allura',
       'pfitzneriana_vogli',
       'pfinzing_castle',
       'pfisterer_group',
       'pfi_convention',
       'pfitscher_bach',
       'pfitzner_flyer',
       'pfisters_muhle',
       'pfister_form',
       'pfizer_award',
       'pfizer_uk'],
 'k': ['pfk_nurafshon', 'pfk_sementchi', 'pfk_piestany'],
 'l': ['pflugerville_formation',
       'pflugerville,_texas',
       'pflerscher_bach',
       'pflag_canada',
       'pflag_china',
       'pfl_everett',
       'pfl_daytona',
       'pfl_10',
       'pfl_8',
       'pfl_4',
       'pfl_6',
       'pfl_1',
       'pfl_2',
       'pfl_3',
       'pfl_5',
       'pfl_7',
       'pfl_9'],
 'm': ['pfm_group'],
 'n': ['pfn2', 'pfn'],
 'o': ['pforzheim_hauptbahnhof',
       'pforzheimer_zeitung',
       'pforzheimer_house',
       'pforta_monastery',
       'pforzen_buckle'],
 'p': ['pfp'],
 'r': ['pfrang_association',
       "pfrimer's_parakeet",
       'pfrimm_viaduct',
       'pfrogner_point'],
 's': ['pfspz_vaccine'],
 't': ['pft_commenter', 'pfts_index'],
 'u': ['pfungstadt_railway',
       'pfungstadt_station',
       'pfund_telescope',
       'pfungwa_dziike',
       'pfunderer_bach',
       'pfungwa_mahefu',
       'pfu_bluecats',
       'pfu_limited'],
 'v': ['pfv'],
 'w': ['pfw'],
 'y': ['pfyn_culture']}
