
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hw = {'_': ['hw.sensors', 'hw2'],
 'a': ['hwangseong-dong',
       'hwangbyeongsan',
       'hwamyeong-dong',
       'hwangcheolbong',
       'hwangnam-ppang',
       'hwanggeum-dong',
       'hwajeong-myeon',
       'hwangjeongsan',
       'hwanghaeicola',
       'hwanghak-dong',
       'hwangnam-dong',
       'hwanbyeokdang',
       'hwangseoksan',
       'hwangjangsan',
       'hwayang-dong',
       'hwa-om-kyung',
       'hwangnyongsa',
       'hwagok-dong',
       'hwango-dong',
       'hwandudaedo',
       'hwanghaksan',
       'hwangmaesan',
       'hwanseongsa',
       'hwasong-15',
       'hwasong-14',
       'hwawangsan',
       'hwaetberht',
       'hwamongjip',
       'hwasong-10',
       'hwangaksan',
       'hwasong-13',
       'hwahyejang',
       'hwawon-eup',
       'hwajangsan',
       'hwasong-17',
       'hwasong-12',
       'hwasong-6',
       'hwasong-5',
       'hwasong-7',
       'hwabyeong',
       'hwa-young',
       'hwamaesan',
       'hwangudan',
       'hwasong-8',
       'hwaaksan',
       'hwanjile',
       'hwayasan',
       'hwa-dong',
       'hwaeomsa',
       'hwajeong',
       'hwan-guk',
       'hwaseong',
       'hwanhee',
       'hwangbo',
       'hwayang',
       'hwangto',
       'hwachae',
       'hwasser',
       'hwabaek',
       'hwayobi',
       'hwagwan',
       'hwajeon',
       'hwarang',
       'hwangap',
       'hwanung',
       'hwacha',
       'hwaeom',
       'hwando',
       'hwawon',
       'hwages',
       'hwange',
       'hwarot',
       'hwamei',
       'hwali',
       'hwasa',
       'hwama',
       'hwair',
       'hwal',
       'hwan',
       'hwaa',
       'hwa'],
 'b': ['hwb'],
 'c': ['hwc'],
 'd': ['hwd'],
 'e': ['hwemaukkan',
       'hwesokchi',
       'hwepanan',
       'hwebalan',
       'hwekyin',
       'hwemate',
       'hwekum',
       'hwein',
       'hwena',
       'hwem',
       'hwe'],
 'f': ['hwf'],
 'g': ['hwga', 'hwg'],
 'h': ['hwh'],
 'i': ['hwigyeong-dong', 'hwidiem', 'hwicce', 'hwin', 'hwi'],
 'l': ['hwlitsum', 'hwl'],
 'm': ['hwm'],
 'n': ['hwn'],
 'o': ['hwoarang', 'hwo'],
 'p': ['hwp1', 'hwp'],
 'r': ['hwr'],
 's': ['hws'],
 't': ['hwt'],
 'u': ['hwu'],
 'w': ['hww'],
 'y': ['hwy'],
 'z': ['hwz']}
