
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_h_ = {'_': ['h418ov21.c',
       'h2356-309',
       'h1821+643',
       'h323plus',
       'h1504+65',
       'h2-cbd',
       'h4-cbd',
       'h.263',
       'h.450',
       'h.245',
       'h.460',
       'h.234',
       'h.261',
       'h.235',
       'h.870',
       'h.320',
       'h1299',
       'h37rv',
       'h.331',
       'h.120',
       'h.241',
       'h.239',
       'h-1nf',
       'h295r',
       'h.323',
       'h.248',
       'h.324',
       'h100',
       'h120',
       'h-58',
       'h101',
       'h300',
       'h-89',
       'h320',
       'h30',
       'h16',
       'h11',
       'h31',
       'h47',
       'h40',
       'h19',
       'h80',
       'h45',
       'h23',
       'h50',
       'h18',
       'h42',
       'h44',
       'h17',
       'h34',
       'h99',
       'h29',
       'h53',
       'h13',
       'h39',
       'h24',
       'h37',
       'h32',
       'h25',
       'h35',
       'h27',
       'h92',
       'h26',
       'h33',
       'h21',
       'h63',
       'h28',
       'h43',
       'h20',
       'h48',
       'h14',
       'h12',
       'h49',
       'h57',
       'h59',
       'h64',
       'h10',
       'h41',
       'h54',
       'h15',
       'h52',
       'h38',
       'h22',
       'h36'],
 'a': ['h.a.m.m.e.r.',
       'h.a.a.r.p.',
       'h.a.t.e.u.',
       'h.a.n.d.',
       'h.a.q.q.',
       "h'angus",
       'h-alpha',
       'h2afb2',
       'h2afy2',
       'h2afb3',
       'h2afb1',
       'h*a*m',
       'h2afj',
       'h2afv',
       'h2afy',
       'h2afx',
       'h2a'],
 'b': ['h@bibk@nd',
       'h-blockx',
       'h-bridge',
       'h2bk5ac',
       'h-block',
       'h2bfwt',
       'h-bahn',
       'h-boat',
       'h-back',
       'h-bio',
       'h2bfm',
       'h2bfs',
       'h-bar',
       'h2biz',
       'h2b'],
 'c': ['h-cobordism', 'h*commerce'],
 'd': ['h-derivative',
       'h-dropping',
       'h-dagurinn',
       'h1droid',
       'h-drive',
       'h-dhami',
       'h.d.',
       'h&d'],
 'e': ['h.e.r.b.i.e.',
       'h.e.a.r.',
       'h.e.d.z.',
       'h-eugene',
       'h.e.l.p.',
       'h2ewsos',
       'h.e.r.',
       'h-e-b'],
 'f': ['h@ft@sov', 'h-factor', 'h1foo', 'h1fnt', 'h3f3a', 'h1fx', 'h1f0'],
 'g': ['h1ghlander', 'h-gun', 'h2g2'],
 'h': ['h3h3productions', 'h4h', 'h&h'],
 'i': ['h-invitational',
       'h.i.t.s.',
       'h.i.v.e.',
       'h-index',
       'h-iia',
       'h-iib',
       'h-ii',
       'h&i',
       'h-i'],
 'j': ['h@jo'],
 'k': ['h2k-gaming',
       'h3k79me2',
       'h3k36me2',
       'h3k27me3',
       'h3k36me3',
       'h4k20me',
       'h3k23ac',
       'h4k91ac',
       'h3k27ac',
       'h4k16ac',
       'h3k14ac',
       'h3k56ac',
       'h3k36ac',
       'h3k4me1',
       'h3k4me3',
       'h3k36me',
       'h3k9me3',
       'h4k12ac',
       'h-kayne',
       'h3k9me2',
       'h4k5ac',
       'h4k8ac',
       'h3k9ac',
       'h@k@ri',
       'h3k27',
       'h3k4',
       'h&k'],
 'l': ['h3llb3nt', 'h-logic', 'h2lo', 'h2l2'],
 'm': ['h-matrix', 'h@my@li', 'h@m@nli', 'h@mz@li', 'h@my@', 'h-m-d', 'h&m'],
 'n': ['h@nif@', 'h2n2o2', 'h-net', 'h2no', 'h2n'],
 'o': ['h.o.m.e.-studios',
       'h2overdrive',
       'h.o.r.d.e.',
       'h2olympia',
       'h.o.s.t.',
       'h-object',
       'h.o.l.y.',
       'h.o.t.s.',
       'h2onews',
       'h.o.t.'],
 'p': ['h-prize', 'h-point', 'h-pem', 'h2pro', 'h2ptm', 'h6pd', 'h5p', 'h&p'],
 'r': ['h-reflex',
       'h3r26me2',
       'h3r17me2',
       'h4r3me2',
       "h'raoua",
       'h3r2me2',
       'h3r42me',
       'h3r8me2',
       'h@rtiz',
       'h-r-m',
       'h8rz',
       'h.r.',
       'h&r',
       'h8r',
       'h2r'],
 's': ['h@s@ncobanli',
       'h@s@nqulular',
       'h@s@nqaydi',
       'h@s@nxanli',
       'h-soz-kult',
       'h@s@nqala',
       'h@s@nbin@',
       'h@s@nqaya',
       'h@s@nqoca',
       'h@s@nabad',
       'h-street',
       'h@s@nl@r',
       'h-sphere',
       'h@s@nli',
       'h@s@nsu',
       'h.stern',
       'h-store',
       'h-space',
       'h-s-n',
       'h@sin',
       'h2s',
       'h&s'],
 't': ['h-theorem', 'h@t@ml@r', 'h-town', 'h-tcp'],
 'u': ['h.u.m.a.n.w.i.n.e.', 'h.u.r.l.', 'h.u.n.e.'],
 'v': ['h-vector'],
 'w': ['h-wonder', 'h-wing', 'h&w'],
 'x': ['h2x'],
 'y': ['h.y.c.y.bh'],
 'z': ['h@zr@oba', 'h@ziabad', 'h@zr@', 'h/zkj']}
