
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sj = {'_': ['sj-sound'],
 'a': ['sjalagardsgatan',
       'sjaellandsgade',
       'sjaerdemaslot',
       'sjamsuridjal',
       'sjaastad',
       'sjastad',
       'sjaelso',
       'sjambok',
       'sjalo',
       'sjava',
       'sjaak',
       'sjab',
       'sjac',
       'sjam',
       'sja'],
 'b': ['sjbp', 'sjb'],
 'c': ['sjcc', 'sjcs', 'sjc'],
 'd': ['sjdanceco', 'sjd'],
 'e': ['sjernaroyane',
       'sjeverovici',
       'sjettebreen',
       'sjeverovci',
       'sjernaroy',
       'sjecevac',
       'sjetlina',
       'sjenokos',
       'sjeverin',
       'sjenina',
       'sjekose',
       'sjenica',
       'sjeng',
       'sje'],
 'f': ['sjf'],
 'h': ['sjhs', 'sjh'],
 'i': ['sjisjka', 'sjis', 'sji'],
 'j': ['sjj'],
 'k': ['sjk'],
 'm': ['sjm'],
 'n': ['sjn'],
 'o': ['sjorovar-fabbe',
       'sjogrenfjellet',
       'sjoestedtius',
       'sjosmyrsjon',
       'sjongshoi',
       'sjostrand',
       'sjogestad',
       'sjolunden',
       'sjosanden',
       'sjomarken',
       'sjoholmen',
       'sjolisand',
       'sjofloyte',
       'sjolander',
       'sjoqvist',
       'sjotofta',
       'sjodiken',
       'sjocrona',
       'sjovegan',
       'sjodalen',
       'sjostrom',
       'sjostedt',
       'sjogata',
       'sjoasen',
       'sjoberg',
       'sjogren',
       'sjorrod',
       'sjotorp',
       'sjoholm',
       'sjonsta',
       'sjoholt',
       'sjolund',
       'sjoblom',
       'sjolie',
       'sjolin',
       'sjoerd',
       'sjodin',
       'sjovik',
       'sjona',
       'sjokz',
       'sjors',
       'sjora',
       'sjoli',
       'sjosa',
       'sjobo',
       'sjofn',
       'sjoa',
       'sjon'],
 'p': ['sjp'],
 'r': ['sjriak', 'sjr'],
 's': ['sjs'],
 't': ['sjt'],
 'u': ['sjuhollendarbukta',
       'sjumansholmen',
       'sjumilakliv',
       'sjumandjaja',
       'sjulsmark',
       'sjuhalla',
       'sjursnes',
       'sjursoya',
       'sjuntorp',
       'sjusjoen',
       'sjuoyane',
       'sjursen',
       'sjunnen',
       'sjurdur',
       'sjukdom',
       'sjung',
       'sjuan',
       'sjusd',
       'sjur',
       'sju'],
 'v': ['sjvn', 'sjv']}
