
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_aw = {'_': ['aw*-algebra', 'aw-ka-tha', 'aw.dtv'],
 'a': ['awakebutstillinbed',
       'awala-yalimapo',
       'awaouichthys',
       'awakening!!',
       'awasthiella',
       'awarewaunau',
       'awardwallet',
       'awashimaura',
       'awa-kwaiker',
       'awakenings',
       'awalaching',
       'awantipora',
       'awadelphis',
       'awatrechus',
       'awainggale',
       'awashonks',
       'awareness',
       'awakening',
       'awaragira',
       'awayland',
       'awadhani',
       'awalgaon',
       'awatinas',
       'awabakal',
       'awandiya',
       'awadhiya',
       'awastara',
       'awarpada',
       'awallani',
       'awaydays',
       'awateria',
       'awaruite',
       'awazapur',
       'awaludin',
       'awaiting',
       'awakatek',
       'awakkule',
       'awarapan',
       'awashima',
       'awargol',
       'awakeve',
       'awatoto',
       'awapuni',
       'awaasif',
       'awalmir',
       'awaradi',
       'awaargi',
       'awaswas',
       'awakeri',
       'awagarh',
       'awakino',
       'awasthi',
       'awamaki',
       'awamori',
       'awajki',
       'away3d',
       'awaing',
       'awamir',
       'awaara',
       'awaroa',
       'awaken',
       'awagat',
       'awarai',
       'awaous',
       'awassi',
       'awabel',
       'awashi',
       'awarta',
       'awayan',
       'awaiti',
       'awaran',
       'awanyu',
       'awanui',
       'awatea',
       'awarua',
       'awake!',
       'awadam',
       'awadir',
       'awaya',
       'awalt',
       'awate',
       'awaji',
       'awaru',
       'awaza',
       'awano',
       'awaga',
       'awash',
       'awati',
       'awasi',
       'awais',
       'awase',
       'awaka',
       'awami',
       'award',
       'awaaz',
       'awaso',
       'awana',
       'awara',
       'awasu',
       'awaba',
       'awans',
       'awang',
       'awadh',
       'awada',
       'awake',
       'awali',
       'awaj',
       'awaz',
       'awak',
       'awac',
       'awae',
       'away',
       'awai',
       'awar',
       'awam',
       'awal',
       'awah',
       'awad',
       'awan',
       'awa'],
 'b': ['awbridge', 'awbare', 'awbery', 'awbube', 'awbz', 'awb'],
 'c': ['awc'],
 'd': ['awdheegle', 'awdiinle', 'awdry', 'awdal', 'awdl', 'awdf', 'awd'],
 'e': ['awesomenauts',
       'awesometown',
       'awes-kon-wa',
       'awesomer',
       'awesom-o',
       'awesome',
       'awedony',
       'aweiden',
       'aweyden',
       'awelye',
       'aweida',
       'awendo',
       'awedis',
       'aweday',
       'aweres',
       'aweti',
       'aweto',
       'awelo',
       'awena',
       'aweer',
       'aweke',
       'awen',
       'awem',
       'aweb',
       'awei',
       'awe'],
 'f': ['awf8f35', 'awford', 'awfis', 'awful', 'awfc', 'awf'],
 'g': ['awgatha', 'awgbu', 'awgu'],
 'h': ['awheaturris', 'awhs', 'awhf', 'awh'],
 'i': ['awithlaknakwe',
       'awinmul',
       'awilda',
       'awilix',
       'awino',
       'awich',
       'awirs',
       'awit',
       'awie',
       'awi'],
 'j': ['awjilah', 'awjila', 'awj'],
 'k': ['awka-etiti',
       'awkwafina',
       'awkward',
       'awkuzu',
       'awkley',
       'awkin',
       'awka',
       'awk'],
 'l': ['awliscombe', 'awlam', 'awlu', 'awl'],
 'm': ['awmsawi', 'awm'],
 'n': ['awngchit', 'awning', 'awngsa', 'awnaw', 'awn'],
 'o': ['awonawilona',
       'awo-omamma',
       'awolnation',
       'awoulaba',
       'awosika',
       'aworowa',
       'awoingt',
       'awojobi',
       'awoshie',
       'awoniyi',
       'awodey',
       'awonou',
       'awoda',
       'awori',
       'aworo',
       'awomo',
       'awon',
       'awoo',
       'awok',
       'awo'],
 'p': ['awpp', 'awp'],
 'r': ['awrtable', 'awrajja', 'awrey', 'awre', 'awry', 'awr'],
 's': ['awsworth', 'awstats', 'awsumb', 'aws-1', 'awst', 'awss'],
 't': ['awthaw', 'awtaad', 'awtano', 'awtas', 'awtel', 'awt'],
 'u': ['awulbodale', 'awukugua', 'awujale', 'awunz', 'awuah', 'awutu', 'awu'],
 'v': ['awv'],
 'w': ['awwwards', 'awwad', 'awwa', 'aww'],
 'y': ['awy'],
 'z': ["awza'i", 'awzaan']}
