# coding: utf-8

"""
    eHelply SDK - 1.1.103

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.103
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import ehelply_python_experimental_sdk
from ehelply_python_experimental_sdk.model.heartbeat_response import HeartbeatResponse
from ehelply_python_experimental_sdk import configuration


class TestHeartbeatResponse(unittest.TestCase):
    """HeartbeatResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
