
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rr = {'_': ['rr_telescopii',
       'rr_donnelley',
       'rr_enriquez',
       'rr_pictoris',
       'rr_centauri',
       'rr_auction',
       'rr_herrera',
       'rr_garcia',
       'rr_media',
       'rr_caeli',
       'rr_lyrae'],
 'a': ['rrahman_hallaci',
       'rragam,_shkoder',
       'rranxe,_shkoder',
       'rrat_j1819-1458',
       'rrahman_morina',
       'rrahul_sudhir',
       'rrapush_papoj',
       'rrapo_hekali',
       'rrahman_rama',
       'rrahim_cota',
       'rrapo_taho'],
 'b': ['rrb_energy'],
 'c': ['rrcc', 'rrc'],
 'd': ['rrd_editor'],
 'e': ['rreze_abdullahu', 'rrezart_cungu', 'rre_ventures'],
 'f': ['rrfc', 'rrf'],
 'g': ['rrg_professor', 'rrg_prufling', 'rrg_fafnir', 'rrg_falke'],
 'h': ['rrh_portreath', 'rrh_benbecula', 'rrh_buchan'],
 'i': ['rri_2', 'rri_1'],
 'j': ['rrj_capital'],
 'k': ['rrkm_theory'],
 'l': ['rrl'],
 'm': ['rrm2b', 'rrmc', 'rrm2', 'rrm1', 'rrm3', 'rrm'],
 'n': ['rrna_n-glycosylase', 'rrna_endonuclease'],
 'o': ['rrogozhine_stadium',
       'rrok_gjonlleshaj',
       'rron_statovci',
       'rrok_mirdita',
       'rrose_rrome',
       'rron_broja'],
 'p': ['rrp15', 'rrp1b', 'rrp12', 'rrp1', 'rrp9', 'rrp'],
 'q': ['rrqr_factorization'],
 'r': ['rrroooaaarrr', 'rrrrrrr!!!', 'rrrecords', 'rrrr', 'rrr'],
 's': ['rrs_shackleton', 'rrs_bransfield', 'rrs_discovery'],
 't': ['rrt_global'],
 'u': ['rrushkull,_shkoder', 'rrustem_berisha']}
