
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ej = {'a': ['ejaculation',
       'ejabberd',
       'ejaji',
       'ejari',
       'ejaz',
       'ejan',
       'ejay',
       'eja'],
 'b': ['ejbca', 'ejbeh', 'ejby'],
 'c': ['ejc'],
 'd': ['ejdabrine', 'ejdus'],
 'e': ['ejectosome',
       'ejemekwuru',
       'ejectment',
       'ejection',
       'ejercito',
       'ejecta',
       'ejerie',
       'ejeme',
       'ejeda',
       'ejer',
       'ejep',
       'eje'],
 'f': ['ejf'],
 'h': ['ejh'],
 'i': ['ejiri-juku',
       'ejinaspis',
       'ejinhoro',
       'ejipura',
       'ejiofor',
       'ejigbo',
       'ejiogu',
       'ejisu',
       'ejido',
       'ejima',
       'ejiri',
       'ejigu',
       'ejin',
       'eji'],
 'l': ['ejlstrup', 'ejlinge', 'ejler', 'ejl'],
 'n': ['ejnyc', 'ejner', 'ejnar', 'ejn'],
 'o': ['ejogo', 'ejot', 'ejo'],
 'p': ['ejpovice', 'ejp'],
 's': ['ejszeryszki', 'ejstrup'],
 't': ['ejt'],
 'u': ['ejulve', 'ejutla', 'ejule', 'ejupi', 'ejura', 'eju'],
 'w': ['ejw']}
