
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ew = {'_': ['ew!'],
 'a': ['ewartiothamnus',
       'ewanje-epee',
       'ewaldsgade',
       'ewanrigg',
       'ewartia',
       'ewandro',
       'ewarton',
       'ewater',
       'ewald',
       'ewart',
       'eway',
       'ewan',
       'ewa'],
 'b': ['ewbank', 'ewb'],
 'c': ['ewcin', 'ewc'],
 'd': ['ewd'],
 'e': ['ewecross',
       'ewerthon',
       'ewesdale',
       'ewekoro',
       'ewerton',
       'ewenton',
       'ewelme',
       'ewelin',
       'ewenny',
       'ewerby',
       'ewell',
       'ewery',
       'ewert',
       'ewers',
       'ewens',
       'eweek',
       'ewen',
       'ewe'],
 'f': ['ewf'],
 'g': ['ewg'],
 'h': ['ewhurst', 'ewhs'],
 'i': ['ewigschneehorn',
       'ewighausen',
       'ewigkeit',
       'ewington',
       'ewingite',
       'ewingia',
       'ewinow',
       'ewina',
       'ewins',
       'ewing',
       'ewijk',
       'ewip',
       'ewin',
       'ewi'],
 'j': ['ewj'],
 'k': ['ewk'],
 'l': ['ewloe', 'ewl'],
 'm': ['ewm'],
 'n': ['ewn'],
 'o': ['eworkexperience',
       'ewostatewos',
       'eworthy',
       'ewopole',
       'ewondo',
       'eworld',
       'ewose',
       'ewout',
       'ewok',
       'ewos',
       'ewom',
       'ewo'],
 'p': ['ewp'],
 'r': ['ewrc-results.com'],
 's': ['ews/fli', 'ews-ux', 'ewshot', 'ewsd'],
 't': ['ewtn', 'ewt'],
 'u': ['ewunia', 'ewuare', 'ewunin', 'ewu'],
 'w': ['eww'],
 'y': ['ewyas', 'ewy']}
