
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ey = {'_': ['ey-parthenon'],
 'a': ['eyarkot',
       'eyalet',
       'eyaht',
       'eyara',
       'eyach',
       'eyal',
       'eyam',
       'eyak',
       'eya1',
       'eya2',
       'eya4',
       'eya'],
 'b': ['eybakabad', 'eybouleuf', 'eyburie', 'eybens', 'eyb'],
 'c': ['eycheil', 'eyck', 'eyc'],
 'd': ['eydelstedt',
       'eydhafushi',
       'eydarshan',
       'eydehavn',
       'eydison',
       'eydabad',
       'eydanak',
       'eydoche',
       'eydap',
       'eydlu',
       'eydie',
       'eydon',
       'eyde'],
 'e': ['eyedollartree',
       'eyebuydirect',
       'eyesteelfilm',
       'eyecatchers',
       'eye-rolling',
       'eye-gouging',
       'eyeluminati',
       'eyecatcher',
       'eyebroughy',
       'eyewitness',
       'eyehategod',
       'eyecarepro',
       'eyerusalem',
       'eyeverify',
       'eyeopener',
       'eyeshield',
       'eyewriter',
       'eyegroove',
       'eyendorf',
       'eyesburn',
       'eyephone',
       'eyepiece',
       'eyepatch',
       'eyemouth',
       'eyestalk',
       'eyeworth',
       'eye-ring',
       'eyeborgs',
       'eyerlekh',
       'eyeshade',
       'eyesat-1',
       'eyeguide',
       'eyedress',
       'eyenine',
       'eyesafe',
       'eyelash',
       'eyespot',
       'eyeland',
       'eye-cup',
       'eyeries',
       'eyewire',
       'eyebeam',
       'eyesore',
       'eyeborg',
       'eyetong',
       'eyewash',
       'eye-sys',
       'eyetech',
       'eyewear',
       'eyedrum',
       'eyeharp',
       'eyebrow',
       'eyebar',
       'eyelid',
       'eyetap',
       'eyetoy',
       'eye-fi',
       'eyejot',
       'eyerly',
       'eyesaw',
       'eyelis',
       'eyepet',
       'eyedea',
       'eyekit',
       'eyeish',
       'eye-d',
       'eyeka',
       'eyemo',
       'eyeos',
       'eyeem',
       'eyetv',
       'eyedi',
       'eyez',
       'eyeq',
       'eye'],
 'f': ['eyfura', 'eyfi', 'eyf'],
 'g': ['eygurande-et-gardedeuil',
       'eygluy-escoulin',
       'eygelshoven',
       'eyguebelle',
       'eygalieres',
       'eygurande',
       'eygalayes',
       'eyguieres',
       'eygaliers',
       'eyguians',
       'eygliers'],
 'i': ['eyimofe', 'eyikyar', 'eyiaba', 'eyiba', 'eyik'],
 'j': ['eyjafjardarsveit',
       'eyjafjallajokull',
       'eyjarskeggjar',
       'eyjafjordur',
       'eyjolfsson',
       'eyjeaux'],
 'k': ['eyke', 'eyk'],
 'l': ['eylembilim',
       'eylaidae',
       'eyliac',
       'eylaki',
       'eylove',
       'eylais',
       'eylau',
       'eylar',
       'eyler',
       'eyles',
       'eylem',
       'eylo',
       'eyl'],
 'm': ['eymouthiers',
       'eymoutiers',
       'eymundsson',
       'eymeux',
       'eymet',
       'eymur',
       'eyman',
       'eymir'],
 'n': ['eyndhovenia',
       'eynhallow',
       'eynesbury',
       'eynibulaq',
       'eynsford',
       'eynatten',
       'eynalli',
       'eynesse',
       'eynesil',
       'eynatan',
       'eynsham',
       'eynelli',
       'eynabad',
       'eynort',
       'eynali',
       'eynar',
       'eynaa',
       'eynon',
       'eyne',
       'eyn'],
 'o': ['eyo-orukra-usuyak',
       'eyo-esang-obisung',
       'eyo-esio-uwak',
       'eyo-otong-uwe',
       'eyo-okpo-oyo',
       'eyosio-osung',
       'eyo-odiong',
       'eyokponung',
       'eyobiasang',
       'eyokpifie',
       'eyo-oyete',
       'eyobisung',
       'eyobiosio',
       'eyo-ifang',
       'eyo-ating',
       'eyo-okpo',
       'eyo-atta',
       'eyotong',
       'eyo-esu',
       'eyo-uya',
       'eyotai',
       'eyokpu',
       'eyofin',
       'eyota',
       'eyoko',
       'eyo!',
       'eyoh',
       'eyob',
       'eyo'],
 'p': ['eyprepocnemidinae', 'eyprepocnemis', 'eypio', 'eypak', 'eype', 'eyp'],
 'r': ['eyraud-crempse-maurens',
       'eyres-moncube',
       'eyravallen',
       'eyrarbakki',
       'eyralpenus',
       'eyrosuchus',
       'eyrecourt',
       'eyriesia',
       'eyragues',
       'eyreton',
       'eyroles',
       'eyrieux',
       'eyring',
       'eyrich',
       'eyrgun',
       'eyrein',
       'eyrans',
       'eyres',
       'eyrie',
       'eyre'],
 's': ['eysturoyartunnilin',
       'eysyslopterus',
       'eysenhardtia',
       'eysturtindur',
       'eyserbosweg',
       'eysteinsson',
       'eyserheide',
       'eysarcoris',
       'eyserbeek',
       'eysteinn',
       'eyshabad',
       'eysseric',
       'eysturoy',
       'eysenck',
       'eystein',
       'eysines',
       'eyshgeh',
       'eystrup',
       'eyshum',
       'eyshan',
       'eyster',
       'eysson',
       'eysink',
       'eysins',
       'eyston',
       'eysus',
       'eys'],
 't': ['eythorne', 'eythrope', 'eytinge', 'eyton'],
 'u': ['eyumodjock',
       'eyupspor',
       'eyuphuro',
       'eyuboglu',
       'eyupoglu',
       'eyulor',
       'eyup'],
 'v': ['eyvazxanb@yli',
       'eyvazalilar',
       'eyvazallar',
       'eyvazlilar',
       'eyvanabad',
       'eyvallah',
       'eyvandar',
       'eyvanki',
       'eyvazli',
       'eyvirat',
       'eyvaraq',
       'eyvanak',
       'eyvand',
       'eyvani',
       'eyvind',
       'eyvan',
       'eyvaq'],
 'w': ['eywiller'],
 'y': ['eyyubiye', 'eyyal'],
 'z': ['eyzin-pinet', 'eyzaguirre', 'eyzadiyeh', 'eyzerac', 'eyzahut', 'eyza']}
