
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_y_ = {'_': ['y.156sam',
       'y-23684',
       'y-27632',
       'y.3172',
       'y.3173',
       'y.3176',
       'y.1731',
       'y.1564',
       'y.3800',
       'y106.5',
       'y-320',
       'y102',
       'y101',
       'y187',
       'y100',
       'y108',
       'y721',
       'y14',
       'y94',
       'y15',
       'y10',
       'y11',
       'y16',
       'y12',
       'y98'],
 'a': ['y.a.l.a.', 'y.a.g.i', 'y.a.s.', "y'all"],
 'c': ['y-cable', 'y:cube'],
 'f': ['y-factor', 'y-films'],
 'h': ['y-homeomorphism'],
 'i': ['y-intercept'],
 'j': ['y2j'],
 'l': ['y-love'],
 'm': ['y-matrix', 'y-mag'],
 'n': ['y?n-vee'],
 'o': ['y.o.u.n.g', 'y-o-u'],
 'r': ['y&r'],
 's': ['y-str', 'y-snp', 'y3s'],
 't': ['y-traxx', 'y&t'],
 'w': ['y-wing'],
 'z': ['y-zet']}
