
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ih = {'a': ['iharkutosuchus',
       'ihalagammedda',
       'ihaladiggala',
       'iharosbereny',
       'ihadilanana',
       'ihaddadene',
       'ihamuotila',
       'ihalainen',
       'ihazoara',
       'ihasalu',
       'ihagama',
       'ihamaru',
       'ihanga',
       'ihagee',
       'ihaste',
       'ihango',
       'ihanja',
       'iharos',
       'ihanda',
       'ihatsi',
       'ihara',
       'iham',
       'ihan',
       'ihab',
       'iha'],
 'b': ['ihbc', 'ihba', 'ihb'],
 'c': ['ihch-7113', 'ihcc', 'ihc'],
 'd': ["ihda'", 'ihd'],
 'e': ['iheringichthys',
       'iheartradio',
       'iheartmedia',
       'iheyaspira',
       'iheanacho',
       'iheringia',
       'ihembosi',
       'ihenacho',
       'ihemeje',
       'ihering',
       'ihenga',
       'iherir',
       'iheme',
       'ihec',
       'ihep',
       'ihe'],
 'f': ['ihf'],
 'g': ['ihg'],
 'h': ['ihh'],
 'i': ['ihitte/uboma',
       'ihigaini',
       'ihiagwa',
       'ihievbe',
       'ihiala',
       'ihinga',
       'ihite',
       'ihi'],
 'k': ['ihk'],
 'l': ['ihlienworth',
       'ihlegramma',
       'ihlebaek',
       'ihlewitz',
       'ihlany',
       'ihlara',
       'ihlea',
       'ihlen',
       'ihlow',
       'ihler',
       'ihle',
       'ihl'],
 'm': ['ihmissokkelo', 'ihme-zentrum', 'ihme', 'ihms', 'ihm'],
 'n': ['ihnen', 'ihne'],
 'o': ['ihorombe', 'iholdy', 'ihosy', 'ihova', 'ihop'],
 'p': ['ihpk1', 'ihpk2', 'ihpa', 'ihp'],
 'q': ['ihq'],
 'r': ['ihrlerstein',
       'ihringen',
       'ihram',
       'ihrim',
       'ihrig',
       'ihrac',
       'ihrc',
       'ihre',
       'ihra',
       'ihrd',
       'ihr'],
 's': ['ihsanullah',
       'ihsangazi',
       'ihsaniye',
       'ihsaas',
       'ihsahn',
       'ihsim',
       'ihsan',
       'ihsaa',
       'ihss',
       'ihsa',
       'ihs'],
 't': ['ihtaimlat', 'ihtiman', 'ihtisab', 'ihtc', 'iht'],
 'u': ['ihumatao',
       'ihuatzio',
       'ihuririo',
       'ihururu',
       'ihuman',
       'ihunch',
       'ihumwa',
       'ihud',
       'ihub',
       'ihuo',
       'ihua',
       'ihug',
       'ihu'],
 'v': ['ihv'],
 'w': ['ihwa-dong', 'ihwagi'],
 'y': ['ihy']}
