
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ix = {'_': ['ix.br'],
 'a': ['ixalotriton',
       'ixabepilone',
       'ixalerpeton',
       'ixalodectes',
       'ixazomib',
       'ixanthus',
       'ixamatus',
       'ixalan',
       'ixala',
       'ixa'],
 'c': ['ixcuinquitlapilco',
       'ixcapuzalco',
       'ixcaquixtla',
       'ixcatepec',
       'ixchiguan',
       'ixcatecos',
       'ixcatlan',
       'ixchela',
       'ixcatec',
       'ixcanul',
       'ixchel',
       'ixcan',
       'ixc'],
 'e': ['ixekizumab', 'ixeridium', 'ixelles', 'ixeris', 'ixe-13', 'ixerba'],
 'f': ['ixform'],
 'h': ['ixhuatlancillo', 'ixhuatlan', 'ixhuatan', 'ixhuacan'],
 'i': ['ixiochlamys',
       'ixiolirion',
       'ixinandria',
       'ixiolaena',
       'ixianthes',
       'ixiquarks',
       'ixiolite',
       'iximche',
       'ixiamas',
       'ixigo',
       'ixico',
       'ixion',
       'ixias',
       'ixia',
       'ixil',
       'ixi'],
 'k': ['ixkun'],
 'l': ['ixleeds', 'ixlu', 'ixl'],
 'm': ['ixmatlahuacan', 'ixmiquilpan', 'ixml', 'ixm'],
 'n': ['ixn'],
 'o': ['ixodorhynchidae',
       'ixonanthaceae',
       'ixorheorida',
       'ixothraupis',
       'ixodonerium',
       'ixodiphagus',
       'ixobrychus',
       'ixonanthes',
       'ixoroideae',
       'ixophorus',
       'ixonympha',
       'ixorheis',
       'ixodidae',
       'ixorhea',
       'ixodia',
       'ixodes',
       'ixora',
       'ixopo',
       'ixos'],
 'p': ['ixpiyacoc', 'ixp1200', 'ixpe'],
 's': ['ixsystems', 'ixsir', 'ixs'],
 't': ['ixtacamaxtitlan',
       'ixtaczoquitlan',
       'ixtapangajoya',
       'ixtlilxochitl',
       'ixtlahuacan',
       'ixtacomitan',
       'ixtapaluca',
       'ixtoc-alfa',
       'ixtlilton',
       'ixtepeque',
       'ixtonton',
       'ixtepec',
       'ixtenco',
       'ixtutz',
       'ixtapa',
       'ixtlan',
       'ixtab',
       'ixtle'],
 'w': ['ixworth'],
 'y': ['ixyophora', 'ixylasia', 'ixy']}
