
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_i_ = {'_': ['i...vampire',
       'i105-107fm',
       'i102-104fm',
       'i24news',
       'i81b4u',
       'i-180',
       'i98fm',
       'i-351',
       'i-500',
       'i-175',
       'i.431',
       'i-174',
       'i-370',
       'i-394',
       'i-361',
       'i.430',
       'i-502',
       'i-201',
       'i-166',
       'i-177',
       'i486',
       'i-2k',
       'i860',
       'i485',
       'i140',
       'i100',
       'i270',
       'i185',
       'i176',
       'i129',
       'i-4k',
       'i386',
       'i-54',
       'i-1k',
       'i165',
       'i786',
       'i124',
       'i-6k',
       'i-3k',
       'i72',
       'i14',
       'i28',
       'i27',
       'i19',
       'i15',
       'i26',
       'i49',
       'i21',
       'i11',
       'i10',
       'i18',
       'i23',
       'i13',
       'i20',
       'i22',
       'i16',
       'i40',
       'i37',
       'i29',
       'i31',
       'i94',
       'i25',
       'i52',
       'i54',
       'i17',
       'i24',
       'i12',
       'i30'],
 'a': ['i.a.recordings', 'i.am.gia', 'i.am.me', "i'anson", 'i.am+'],
 'b': ['i-braintech', 'i-bundle', "i'billin", 'i-balita', 'i-beam', 'i-bot'],
 'c': ['i-caught',
       'i-cubex',
       'i-cybie',
       'i-cell',
       'i.c.p.',
       'i:cube',
       'i-city',
       'i-crei',
       'i-con',
       'i-chu',
       'i.cx',
       'i&c',
       'i2c',
       'i3c'],
 'd': ['i-divisioona', 'i-doser', 'i-drive', 'i-deas', 'i-d'],
 'e': ['i-empire'],
 'f': ["i-feel-like-i'm-fixin'-to-die",
       'i/flancy',
       'i.f.l.y.',
       'i-free',
       'i-fly',
       'i-f'],
 'g': ['i-gami', 'i-go'],
 'h': ['i-house', 'i2hub'],
 'i': ['i.i.m.u.n.', 'i-iv-v-i', "i'itoi", 'i4i', 'i2i'],
 'j': ['i-juca-pirama', 'i-joist', "i'jaz"],
 'k': ['i.k.u.'],
 'l': ['i-league', 'i-level', 'i-lived', 'i-logix', 'i-land', "i'll"],
 'm': ['i-mutation',
       "i'mperfect",
       'i-message',
       'i-mobile',
       'i-me-we',
       'i-mate',
       'i-mscp',
       'i-mode',
       'i-m-r',
       'i.m.p',
       'i.mx'],
 'n': ['i-n-azaoua',
       'i.n.f.o.',
       'i-number',
       'i-novel',
       'i-ninja',
       'i-news',
       'i-name',
       'i.n.g',
       'i-no'],
 'o': ['i.o.u.s.a.',
       'i.o.i.o.',
       'i-octane',
       'i-opener',
       'i.o.r.',
       'i.o.i',
       'i2o'],
 'p': ['i.play', 'i-pass', 'i-pin', 'i3p', 'i2p'],
 'r': ['i-radio', 'i-roy', 'i-ram', 'i&r'],
 's': ['i-see-you.com',
       'i:scintilla',
       'i.s.r.o.',
       'i-spread',
       'i-spline',
       'i-shakti',
       'i-space',
       'i-see-o',
       'i-shift',
       'i-smad',
       'i-sala',
       'i-suit',
       "i'sot",
       'i.sat',
       'i2s',
       'i"s'],
 't': ["i'tisam-ud-din",
       'i-television',
       'i-testament',
       'i.t.a.l.y.',
       'i-taliani',
       'i-techie',
       'i-tasser',
       "i'tikaf",
       'i-tree',
       'i-team',
       'i.tv',
       'i.t'],
 'w': ['i-wireless', 'i-witness', 'i-weilian', 'i-war', "i'wai"],
 'y': ["i'yad"],
 'z': ['i-zoom']}
