
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_iu = {'_': ['iu-kiao-li', 'iu-miteru', 'iu...im'],
 'a': ['iuani', 'iuati', 'iuaca', 'iua'],
 'b': ['iubaltiana', 'iubdan', 'iub'],
 'c': ['iucundiana', 'iuclid', 'iuchi', 'iucab', 'iucf', 'iucc', 'iucv', 'iuc'],
 'd': ['iudila'],
 'e': ['iuenka', 'iue'],
 'f': ['iufni', 'iufaa'],
 'g': ['iugani', 'iuga', 'iug'],
 'h': ['iuhod', 'iuh'],
 'i': ['iuiu'],
 'j': ['iujnoe'],
 'k': ['iuka'],
 'l': ['iulomorphidae',
       'iulotrichia',
       'iulactis',
       'iuliano',
       'iuliana',
       'iulian',
       'iulops',
       'iultin',
       'iulota',
       'iuliu',
       'iulia'],
 'm': ['iums', 'ium'],
 'n': ['iuniverse', 'iunknown', 'iunctim', 'iunits', 'iunit', 'iunre', 'iuna'],
 'o': ['iuo'],
 'p': ['iupshara', 'iupati', 'iuput', 'iup'],
 'r': ['iurubanga',
       'iurceni',
       'iuridae',
       'iurreta',
       'iurus',
       'iurie',
       'iury',
       'iura',
       'iur'],
 's': ['iusnaturalism',
       'iushenshen',
       'iusaaset',
       'iustin',
       'iusask',
       'iusd',
       'iuss',
       'iust',
       'ius'],
 't': ['iuticosaurus', 'iuty', 'iut'],
 'v': ['iuventum'],
 'w': ['iuwelot'],
 'z': ['iuzzolino']}
