
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ij = {'a': ['ijaz-ur-rehman',
       'ijaz-ul-haq',
       'ijamsville',
       'ijara-isin',
       'ijanikin',
       'ijaazat',
       'ijangui',
       'ijagiri',
       'ijazah',
       'ijagbe',
       'ijaiye',
       'ijames',
       'ijarah',
       'ijara',
       'ijare',
       'ijani',
       'ijaci',
       'ijams',
       'ijang',
       'ijas',
       'ijaw',
       'ija'],
 'b': ['ijburg', 'ijb'],
 'c': ['ijc'],
 'd': ['ijdileni', 'ijdanak', 'ijdan', 'ijdb'],
 'e': ['ijebu-jesa',
       'ijermaouas',
       'ijesha',
       'ijegun',
       'ijevan',
       'ijeri',
       'ijegu',
       'ijede',
       'ijebu',
       'ijen',
       'ijet',
       'ije'],
 'f': ['ijf'],
 'g': ['ijgeul', 'ijg'],
 'h': ['ijhorst', 'ijhl'],
 'i': ['ijinasi', 'ijimaia', 'ijiraq', 'ijichi', 'iji'],
 'j': ['ijjuriktuq', 'ijjodu', 'ijji'],
 'k': ['ijkdijk', 'ijk'],
 'l': ['ijlst', 'ijl'],
 'm': ['ijmuiden', 'ijmeer', 'ijms', 'ijm'],
 'n': ['ijnisinya', 'ijn'],
 'o': ['ijolite', 'ijoukak', 'ijombe', 'ijoko', 'ijok', 'ijo'],
 'p': ['ijpl'],
 'r': ['ijrahwa', 'ijrud'],
 's': ['ijsselmeervogels',
       'ijsselmuiden',
       'ijsselhallen',
       'ijsselmonde',
       'ijsselstein',
       'ijsselderby',
       'ijsselmeer',
       'ijsseloog',
       'ijsselham',
       'ijsbrand',
       'ijscolf',
       'ijssel',
       'ijs'],
 't': ['ijtunnel', 'ijtram', 'ijtema', 'ijt'],
 'u': ['ijustwanttobecool',
       'ijustine',
       'ijuander',
       'ijuhya',
       'ijumu',
       'ijuh',
       'ijui',
       'ijuw',
       'ijun',
       'iju'],
 'v': ['ijvm', 'ijv'],
 'z': ['ijzerbedevaart',
       'ijzerkoekje',
       'ijzevoorde',
       'ijzendoorn',
       'ijzendijke',
       'ijzerwake',
       'ijzerlo',
       'ijzim']}
