
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lt = {'_': ['lt_headtrip',
       'lt_cortesia',
       'lt._kernal',
       'lt_united',
       'lt_group',
       'lt_moe',
       'lt_pgb'],
 'a': ['lta-b3',
       'lta-pd',
       'lta-b2',
       'lta-b1',
       'ltava',
       'ltac',
       'ltag',
       'ltae',
       'ltan',
       'lta'],
 'b': ['ltbp2', 'ltbp3', 'ltbl', 'ltbr', 'ltba', 'ltb'],
 'c': ['ltcl_diptesol', 'ltc_praha', 'ltc_tv'],
 'd': ['ltd_lo-120s'],
 'e': ['lte-wlan_aggregation', 'lte_advanced'],
 'f': ['ltf'],
 'g': ['ltg'],
 'h': ['lths', 'lth'],
 'i': ['ltifr', 'ltib', 'lti'],
 'j': ['ltj_bukem'],
 'k': ['ltk_commune'],
 'l': ['ltl_architects', 'ltl_production'],
 'm': ['ltm_recordings', 'ltm_51-52', 'ltm_53', 'ltm_51'],
 'n': ['ltn_family'],
 'o': ['lto'],
 'p': ['ltp_induction'],
 'r': ['ltr_retrotransposon', 'ltr_standard', 'ltr_multinet'],
 's': ['ltsports',
       'ltspice',
       'ltsen',
       'ltse',
       'ltsp',
       'ltss',
       'ltsa',
       'ltsr',
       'lts'],
 't': ['ltt_1445ab', 'ltt_3780', 'ltt_1445'],
 'u': ['ltu_international', 'ltu_technologies', 'ltu_austria'],
 'v': ['ltv_ethiopia', 'ltv_xc-142', 'ltv_xqm-93', 'ltv_l450f'],
 'w': ['ltwa', 'ltw'],
 'x': ['ltx'],
 'z': ['ltz1000', 'ltz']}
