
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lp = {'_': ['lp-type_problem',
       'lp_andromedae',
       'lp_recharge',
       'lp_aquarii',
       'lp_145-141',
       'lp_40-365',
       'lp_record',
       'lp_944-20',
       'lp_816-60',
       'lp_658-2',
       'lp_71-82',
       'lp_space',
       'lp_iii',
       'lp_duo',
       'lp_sum',
       'lp_ii'],
 'a': ['lpa512',
       'lpar5',
       'lpar3',
       'lpar6',
       'lpar4',
       'lpar1',
       'lpar2',
       'lpac',
       'lpa'],
 'b': ['lpboost', 'lpb'],
 'c': ['lpcat1', 'lpcc', 'lpc'],
 'd': ['lpd-824', 'lpd433', 'lpddr', 'lpd'],
 'e': ['lpec', 'lpe'],
 'f': ['lpfp_awards'],
 'g': ['lpga_international', 'lpgc_ayame'],
 'h': ['lphant', 'lphs', 'lph'],
 'i': ['lpi_media'],
 'k': ['lpk-26', 'lpk'],
 'l': ['lpl_financial'],
 'm': ['lpm_comunicacao'],
 'n': ['lpny'],
 'o': ['lpo-50', 'lpod', 'lpo'],
 'p': ['lpp'],
 'q': ['lpq'],
 'r': ['lprc_oilers'],
 's': ['lps_tozeur'],
 'u': ['lpu'],
 'v': ['lpv'],
 'w': ['lpw_glider'],
 'x': ['lpxtgase', 'lpxn', 'lpx'],
 'y': ['lpy'],
 'z': ['lpz_mine']}
