# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '1.0.0rc4'
git_version = '4233f4379733742230d74973dd8ab051e0387d9b'
