
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nc = {'_': ['nc-cam', 'nc*sa', 'nc-si', 'nc186', 'nc.a', 'nc10', 'nc3o', 'nc4'],
 'a': ['ncapd3',
       'ncache',
       'ncaang',
       'ncapd2',
       'ncaph2',
       'ncapai',
       'ncapg2',
       'ncats',
       'ncapg',
       'ncase',
       'ncafc',
       'ncaph',
       'ncac',
       'ncas',
       'ncat',
       'nca'],
 'b': ['ncbioimpact', 'ncba', 'ncbc', 'ncbs', 'ncb'],
 'c': ['nccr-mageuzi',
       'nccert',
       'nccu',
       'ncca',
       'nccs',
       'nccr',
       'nccn',
       'nccc',
       'nccf',
       'ncci',
       'nccp',
       'ncct',
       'ncc'],
 'd': ['ncdn', 'ncda', 'ncds', 'ncdc', 'ncdr', 'ncdu', 'ncd'],
 'e': ['nced8',
       'ncell',
       'ncec',
       'nced',
       'ncem',
       'ncer',
       'ncep',
       'ncel',
       'ncef',
       'ncew',
       'ncea',
       'nces',
       'nce'],
 'f': ['ncflyports',
       'ncftpd',
       'ncftp',
       'ncfta',
       'ncf1c',
       'ncfc',
       'ncfe',
       'ncf'],
 'g': ['ncgs', 'ncgr', 'ncga', 'ncg'],
 'h': ['nchelenge',
       'nchangram',
       'nchimwani',
       'nchpad',
       'nchan',
       'nchc',
       'nchd',
       'ncha',
       'nchs',
       'nch'],
 'i': ['nci-60', 'ncino', 'ncid', 'ncip', 'ncit', 'ncia', 'ncis', 'nci'],
 'k': ['nckipsd', 'nckap1', 'nck2', 'nck1', 'nck'],
 'l': ['nclass', 'ncls', 'ncln', 'nclc', 'ncl'],
 'm': ['ncmc', 'ncma', 'ncmi', 'ncmh', 'ncmp', 'ncmm', 'ncm'],
 'n': ['ncna', 'ncnd', 'ncnc', 'ncn'],
 'o': ['ncomputing',
       'ncotshane',
       'ncojane',
       'ncover',
       'ncoa5',
       'ncoa7',
       'nconf',
       'ncora',
       'ncole',
       'ncoa6',
       'ncoa4',
       'ncoic',
       'ncose',
       'ncomm',
       'ncoc',
       'ncoa',
       'ncow',
       'ncos',
       'ncod',
       'nco'],
 'p': ['ncphs', 'ncpc', 'ncpa', 'ncp'],
 'r': ['ncryptoki',
       'ncrupar',
       'ncr-340',
       'ncree',
       'ncrc',
       'ncr3',
       'ncrq',
       'ncra',
       'ncri',
       'ncr1',
       'ncre',
       'ncrp',
       'ncr2',
       'ncr'],
 's': ['ncsimul',
       'ncs-382',
       'ncsoft',
       'ncstl',
       'ncsim',
       'ncsi',
       'ncsa',
       'ncso',
       'ncst',
       'ncsy',
       'ncss',
       'ncsc',
       'ncse',
       'ncsb',
       'ncsl',
       'ncs1',
       'ncs'],
 't': ['nctv', 'ncte', 'nctc', 'ncta', 'nctl', 'nctr', 'ncti', 'ncts', 'nct'],
 'u': ['ncurses', 'ncube', 'ncue', 'ncuk', 'ncu'],
 'v': ['ncvs', 'ncv'],
 'w': ['ncwadi', 'ncwc', 'ncw']}
