
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nh = {'_': ['nh41', 'nh1', 'nh2', 'nh7', 'nh6', 'nh4'],
 'a': ['nhandiroboideae',
       'nhatranglive',
       'nhaawuparlku',
       'nhandumirim',
       'nhamini-wi',
       'nhamatanda',
       'nhandeara',
       'nhavigad',
       'nhamunda',
       'nhacra',
       'nhandu',
       'nhanha',
       'nhamo',
       'nhavi',
       'nha'],
 'b': ['nhb'],
 'c': ['nhct', 'nhcs', 'nhcc', 'nhc'],
 'd': ['nhd'],
 'e': ['nheengatu', 'nhecu'],
 'f': ['nhfa', 'nhf'],
 'g': ['nhg'],
 'h': ['nhhs'],
 'i': ['nhindustries',
       'nhibernate',
       'nhialdiu',
       'nhialic',
       'nhill',
       'nhis',
       'nhi'],
 'j': ['nhj'],
 'k': ['nhk'],
 'l': ['nhlangano',
       'nhlambeni',
       'nhlanhla',
       'nhlapo',
       'nhlrc2',
       'nhlrc1',
       'nhlpa',
       'nhlh1',
       'nhla'],
 'm': ['nhms', 'nhmc', 'nhm'],
 'n': ['nhnz', 'nhnn', 'nhn'],
 'o': ['nhoabe', 'nhoah'],
 'p': ['nhp2l1', 'nhps', 'nhp'],
 'r': ['nhrc', 'nhrs', 'nhrp', 'nhr'],
 's': ['nhs.net', 'nhsx', 'nhst'],
 't': ['nhttpd', 'nht'],
 'u': ['nhulunbuy', 'nhuwala', 'nhu'],
 'v': ['nhv'],
 'y': ['nhydrate', 'nhy'],
 'z': ['nhz']}
