
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bs = {'_': ['bs_college,_danapur',
       'bs_national_beehive',
       'bs_postcode_area',
       'bs_el_ideologo',
       'bs_en_13121-3'],
 'a': ['bsa/triumph_racing_triples',
       'bsa_lightning_clubman',
       'bsa_lightning_rocket',
       'bsac_london_branch',
       'bsa_super_rocket',
       'bsa_golden_flash',
       'bsa_road_rocket',
       'bsa_empire_star',
       'bsa_a65_rocket',
       'bsa_a10_series',
       'bsa_unit_twins',
       'bsa_blue_star',
       'bsa_light_six',
       'bsa_gold_star',
       'bsa_a65_star',
       'bsa_model_e',
       'bsa_model_l'],
 'c': ['bsc_furstenfeld_panthers',
       'bscs_science_learning',
       'bsc_lokomotiv_moscow',
       'bsc_rehberge_berlin',
       'bsc_spartak_moscow',
       'bsc_kickers_1900',
       'bsc_marine_group',
       'bsc_saturn_koln',
       'bsc_artur_music',
       'bsc_young_boys',
       'bsc_yb_frauen',
       'bsc_old_boys'],
 'g': ['bsg_chemie_leipzig', 'bsg_stahl_riesa', 'bsg_wismut_gera'],
 'h': ['bshendlaya_-_rashadiya'],
 'i': ['bsi_challenger_lugano', 'bsi_pas_2060', 'bsi_pas_100'],
 'k': ['bsk_olympia_neugablonz', 'bsk_saint_petersburg'],
 'l': ['bsl_500_v3'],
 'n': ['bsnl_sports_quiz', 'bsn_season_2009'],
 'o': ['bsous_silk_museum'],
 'p': ['bsp_for_bulgaria'],
 's': ['bss_sporting_club'],
 'u': ['bsubi/psti_restriction_endonuclease'],
 'v': ['bsv_schwarz-weiss_rehden',
       'bsv_07_schwenningen',
       'bsv_bad_bleiberg',
       'bsv_olper_2000'],
 'w': ['bsww_world_ranking']}
