
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bc = {'_': ['bc_transmission_corporation',
       'bc_paraplegic_association',
       'bc_gladiator_cluj-napoca',
       'bc_assessment_authority',
       'bc_pension_corporation',
       'bc_kraft_moobel/kohila',
       'bc_transplant_society',
       'bc_ural_yekaterinburg',
       "bc_premier's_handicap",
       'bc_geographical_names',
       'bc_refederation_party',
       'bc_hospitality_group',
       'bc_legislature_raids',
       'bc_flamurtari_vlore',
       'bc_virtus_werkendam',
       'bc_partizani_tirana',
       'bc_balkan_botevgrad',
       'bc_wildfire_service',
       'bc_spartak_primorye',
       'bc_hydrogen_highway',
       'bc_cannabis_stores',
       'bc_nizhny_novgorod',
       'bc_ferry_authority',
       'bc_pieno_zvaigzdes',
       'bc_timba_timisoara',
       'bc_tsmoki-minsk_ii',
       'bc_rilski_sportist',
       'bc_lokomotiv_sofia',
       'bc_spartak_pleven',
       'bc_clark_jewelers',
       'bc_krasny_oktyabr',
       'bc_krasnye_krylia',
       'bc_rakvere_tarvas',
       'bc_castors_braine',
       'bc_tallinna_kalev',
       'bc_dinamo_tbilisi',
       'bc_highland_games',
       'bc_triple_threat',
       'bc_liquor_stores',
       'bc_espoir_fukash',
       'bc_golden_gloves',
       'bc_cancer_agency',
       'bc_canis_minoris',
       'bc_dinamo_tirana',
       'bc_irkut_irkutsk',
       'bc_apolonia_fier',
       'bc_games_society',
       'bc_online_school',
       'bc_school_sports',
       'bc_scm_timisoara',
       'bc_kutaisi_2010',
       'bc_arsenal_tula',
       'bc_sparta_praha',
       'bc_ska_alma-ata',
       'bc_kamza_basket',
       'bc_barsy_atyrau',
       'bc_teuta_durres',
       'bc_caspiy_aktau',
       'bc_winter_games',
       'bc_levski_sofia',
       'bc_summer_games',
       'bc_mia_academy',
       'bc_cherno_more',
       'bc_tsu_tbilisi',
       'bc_dynamo_kyiv',
       'bc_grand_sport',
       'bc_novy_jicin',
       'bc_cska_sofia',
       'bc_cska_kyiv',
       'bc_icim_arad',
       'bc_bike_race',
       'bc_bus_north',
       'bc_card_cup'],
 'c': ['bcci_corporate_trophy', 'bcci_domestic_teams', 'bcc_lions_f.c.'],
 'h': ['bchira_ben_mrad'],
 'i': ['bcim_economic_corridor'],
 'l': ['bcl-2-associated_death_promoter',
       'bcl-2-associated_x_protein',
       'bcl-x_interacting_domain',
       'bcl2-related_protein_a1',
       'bcl_bay_09'],
 'm': ['bcm_u_pitesti'],
 'n': ['bcn_main_line'],
 'p': ['bcpa_flight_304'],
 'r': ['bcr-abl_tyrosine-kinase_inhibitor',
       'bcr_open_romania',
       'bcr_tower_sibiu'],
 's': ['bcs_professional_certification',
       'bcs_financial_group',
       'bcs_lovelace_medal',
       'bcs:_50_years'],
 't': ['bct_common_controller'],
 'u': ['bcuz_of_u']}
