
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hl = {'_': ['hl_tauri', 'hl7_aecg'],
 'a': ['hlaingthaya_township',
       'hlaing-myat-paw_gcba',
       'hlanganani,_limpopo',
       'hlaingbwe_township',
       'hladgudr_svanhvit',
       'hla_a1-b8-dr3-dq2',
       'hlatikhulu_forest',
       'hlaudi_motsoeneng',
       'hlanganani_gumbi',
       'hla_b7-dr15-dq6',
       'hlaing_township',
       'hladke_zivotice',
       'hlaskover_rock',
       'hlava_kasandry',
       'hlai_languages',
       'hlasna_treban',
       'hlavce_njive',
       'hla_thamein',
       'hlaing_minn',
       'hladno_pivo',
       'hlai_people',
       'hla_dr3-dq2',
       'hlawga_park',
       'hla_thaung',
       'hlas_lesa',
       'hla_thein',
       'hla_myint',
       'hla_nyunt',
       'hla_htwe',
       'hlae_sar',
       'hla_swe',
       'hla_moe',
       'hla_tun',
       'hla_min',
       'hla_oo',
       'hla_pe'],
 'b': ['hlb_international'],
 'c': ['hlcm', 'hlc'],
 'd': ['hlde', 'hlds', 'hld'],
 'e': ['hlengiwe_mavimbela',
       'hlengiwe_mkhaliphi',
       'hlengiwe_mkhize',
       'hlersu_language',
       'hleb_saladukha',
       'hlegu_township',
       'hleb_dudarau',
       'hleb_harbuz',
       'hlevni_vrh'],
 'f': ['hlfs_ursprung'],
 'g': ['hlg'],
 'h': ['hlh_orion'],
 'i': ['hlin_eiriksdottir',
       'hlincea_monastery',
       'hlinaia,_edinet',
       'hlib_lonchyna',
       'hlib_piskunov',
       'hlincova_hora',
       'hlib_hrachov',
       'hlinka_guard',
       'hlib_savchuk',
       'hlib_bukhal',
       'hliappui_s'],
 'j': ['hljomalind', 'hljod'],
 'k': ['hlkx_clairvoyance', "hlk'yah_gawga", 'hlkx_dragon', 'hlkx_uav'],
 'l': ['hll_lifecare'],
 'm': ['hlm'],
 'n': ['hln'],
 'o': ['hlodvir_thorfinnsson',
       'hlompo_modimokwane',
       'hlohovec_district',
       'hlonipha_mokoena',
       'hlompho_kekana',
       'hlompho_kalake',
       'hlomla_dandala',
       'hlobyne_raion',
       'hlomela_bucwa'],
 'p': ['hlp'],
 'r': ['hlr'],
 's': ['hlsl2glsl', 'hlss', 'hlsw', 'hls'],
 't': ['hltf', 'hltv', 'hlt'],
 'u': ['hluhluwe-imfolozi_park',
       'hluhluwe_airport',
       'hluboke_masuvky',
       'hlubeck_glacier',
       'hlukhiv_okruha',
       'hluboka_castle',
       'hluhluwe_river',
       'hlubi_language',
       'hlusk_district',
       'hlucin_region',
       'hlukhiv_raion',
       'hluboke_dvory',
       'hlumelo_biko',
       'hlubi_people',
       'hlubi_kings',
       'hlubi_mboya'],
 'v': ['hlv'],
 'w': ['hlw_international', 'hlwan_paing', 'hlwan_moe'],
 'x': ['hlx-1', 'hlx'],
 'y': ['hlynur_baeringsson',
       'hlybokaye_district',
       'hlynur_birgisson',
       'hlynur_andresson',
       'hlynur_atlason',
       'hlyniany_gate',
       'hlyboka_raion'],
 'z': ['hlz']}
