
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hp = {'_': ['hp_storageworks',
       'hp_serviceguard',
       'hp_x-terminals',
       'hp_calculators',
       'hp_cloudsystem',
       'hp_photosmart',
       'hp_touchsmart',
       'hp-28_series',
       'hp_winrunner',
       'hp_elitebook',
       'hp_superdome',
       'hp_openmail',
       'hp_newquist',
       'hp_diatreme',
       'hp_autonomy',
       'hp_omnibook',
       'hp_openview',
       'hp_products',
       'hp_pavilion',
       'hp_opencall',
       'hp_laserjet',
       'hp_touchpad',
       'hp/de_tijd',
       'hp_neoview',
       'hp_deskjet',
       'hp_xpander',
       'hp_probook',
       'hp_tinker',
       'hp_saturn',
       'hp_garage',
       'hp_filter',
       'hp_eprint',
       'hp_xb3000',
       'hp_vectra',
       'hp_sauce',
       'hp_620lx',
       'hp_9845c',
       'hp_prime',
       'hp_lyrae',
       'hp_200lx',
       'hp_300lx',
       'hp_dc100',
       'hp_slate',
       'hp_64000',
       'hp_warta',
       'hp_swart',
       'hp_cloud',
       'hp_focus',
       'hp_roman',
       'hp_zbook',
       'hp_basic',
       'hp_foods',
       'hp_660lx',
       'hp_spam',
       'hp_200a',
       'hp_inc.',
       'hp_labs',
       'hp_2100',
       'hp_2640',
       'hp_7935',
       'hp_3000',
       'hp_mini',
       'hp_9000',
       'hp_7470',
       'hp_envy',
       'hp_omen',
       'hp_boyz',
       'hp_hood',
       'hp_brio',
       'hp_95lx',
       'hp_ac++',
       'hp_veer',
       'hp_33s',
       'hp_cas',
       'hp_rtr',
       'hp_110',
       'hp_300',
       'hp_20b',
       'hp_35s',
       'hp_10s',
       'hp_250',
       'hp_38g',
       'hp_30b',
       'hp_9g',
       'hp_z'],
 'a': ['hpasawng_township',
       'hpawlam_jinghkyen',
       'hpakant_township',
       'hpa-an_township',
       'hpapun_district',
       'hpa-an_district',
       'hpapun_township',
       'hpa-an_airport',
       'hpala,_hsawlaw',
       'hpa-an_stadium',
       'hpala,_chipwi',
       'hpa_toucan'],
 'b': ['hpb'],
 'c': ['hpcg_benchmark', 'hpc_europa'],
 'd': ['hpd_arx-04b', 'hpd_arx-03'],
 'e': ['hpe_bladesystem',
       'hpe_discover',
       'hper_complex',
       'hpe_helion',
       'hpe_coxa',
       'hpe_3par',
       'hpe_xp'],
 'f': ['hpfc', 'hpfs', 'hpf'],
 'g': ['hpgv-2', 'hpg80', 'hpgd', 'hpgp', 'hpg'],
 'h': ['hph_304'],
 'i': ['hpi_savage', 'hpi_groupe', 'hpi,_llc', 'hpi_ltd'],
 'j': ['hpj'],
 'k': ['hpk_kiekkonaiset', 'hpk_sp-1'],
 'l': ['hplh1', 'hpl'],
 'm': ['hpmpa', 'hpm.1', 'hpms', 'hpm'],
 'n': ['hpnotiq', 'hpn'],
 'o': ['hpon_language', 'hpo_formalism'],
 'p': ['hpp_model'],
 'q': ['hpq'],
 'r': ['hpruso_township'],
 's': ['hps_stain'],
 't': ['hptn_052', 'hptn_083'],
 'u': ['hpunavirus', 'hpue', 'hpu'],
 'v': ['hpv_vaccine'],
 'w': ['hpw'],
 'x': ['hpx'],
 'y': ['hpyithpyaw', 'hpyikrang', 'hpy']}
