
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hj = {'_': ['hj_bunko', 'hj_luus', 'hj_lu'],
 'a': ['hjalmar_christoffersen',
       'hjalmar_riiser-larsen',
       'hjalmared,_kungsbacka',
       'hjalmar_thorarinsson',
       'hjalmar_hammarskjold',
       'hjalmar_munsterhjelm',
       'hjalmared,_alingsas',
       'hjalmar_christensen',
       'hjalmar_johannessen',
       'hjalmar_cedercrona',
       'hjalmar_hjalmarson',
       'hjalmar_steenstrup',
       'hjalti_gudmundsson',
       'hjalmar_pettersson',
       'hjalmar_stefansson',
       'hjalmart_andersen',
       'hjalmar_bergstrom',
       'hjalmar_pettersen',
       'hjalmar_kiaerskou',
       'hjalmar_siilasvuo',
       'hjalmar_mellander',
       'hjalti_skeggiason',
       'hjalmar_andersson',
       'hjalmar_soderberg',
       'hjalmar_borgstrom',
       'hjalte_norregaard',
       'hjalmar_cornilsen',
       'hjalmar_johansson',
       'hjalmar_welhaven',
       'hjalte_rasmussen',
       'hjalmar_andersen',
       'hjalmar_gullberg',
       'hjalmar_petersen',
       'hjalmar_lonnroth',
       'hjallerup_market',
       'hjalti_einarsson',
       'hjalmar_saxtorph',
       'hjalmar_andresen',
       'hjalmar_karlsson',
       'hjalmar_zambrano',
       'hjalmar_johansen',
       'hjalmar_granfelt',
       'hjalmar_lundbohm',
       'hjartats_hjaltar',
       'hjalmar_selander',
       'hjalmar_peterson',
       'hjalmar_branting',
       'hjalmar_dahlberg',
       'hjalmar_nygaard',
       'hjalmar_kumlien',
       'hjalmar_schacht',
       'hjalmar_heiberg',
       'hjalmar_thomsen',
       'hjalmar_kinberg',
       'hjalmar_frisell',
       'hjallis_harkimo',
       'hjalmar_bergman',
       'hjalmar_stromme',
       'hjalmar_jonsson',
       'hjalgrim_elttor',
       'hjalmar_nystrom',
       'hjalmar_ohlsson',
       'hjalte_froholdt',
       'hjalmar_holand',
       'hjalmar_haalke',
       'hjalmar_ohagen',
       'hjarsas_church',
       'hjalti_arnason',
       'hjalmare_kanal',
       'hjartats_trakt',
       'hjalmar_sunden',
       'hjalmar_lundin',
       'hjalmar_mellin',
       'hjalmar_stolpe',
       'hjalmar_astrom',
       'hjalpum_theim',
       'hjarnarps_gif',
       'hjalmar_frisk',
       'hjalmar_ekdal',
       'hjalmar_kjaer',
       'hjalmar_uggla',
       'hjalmar_kelin',
       'hjalmar_waage',
       'hjalmar_fries',
       'hjarter_knekt',
       'hjalmar_loken',
       'hjalmar_levin',
       'hjartat_fullt',
       'hjalmar_broch',
       'hjalmar_krag',
       'hjalmar_falk',
       'hjalmar_mehr',
       'hjalmar_hvam',
       'hjart_island',
       'hjalmar_vare',
       'hjalmar_mae'],
 'c': ['hjck', 'hjcu'],
 'e': ['hjelmslev_transformation',
       "hjelmslev's_theorem",
       'hjelmeland_church',
       'hjerkinn_station',
       'hjemkomst_center',
       'hjerpe_grocery',
       'hjelme_church',
       'hjemmenes_vel',
       'hjerm_station',
       'hjelmsgate_3',
       'hjelm_waage',
       'hjelm_range'],
 'i': ['hji'],
 'k': ['hjk'],
 'l': ['hjl'],
 'm': ['hjm'],
 'n': ['hjn'],
 'o': ['hjorleifur_guttormsson',
       'hjordis_lind-campbell',
       'hjorleifr_hrodmarsson',
       'hjorring_municipality',
       'hjorundfjord_church',
       'hjortur_hermannsson',
       'hjordis_schymberg',
       'hjorthagen_church',
       'hjordis_petterson',
       'hjortshoj_station',
       'hjorth_parameters',
       'hjordkaer_parish',
       'hjo_municipality',
       'hjortspring_boat',
       'hjorring_station',
       'hjorring_stadium',
       'hjordis_hosoien',
       'hjordis_genberg',
       'hjordis_nerheim',
       'hjorring_county',
       'hjordis_nordin',
       'hjorthagens_ip',
       'hjordis_levin',
       'hjordis_topel',
       'hjort_trench',
       'hjort_massif',
       'hjorth_hill',
       'hjo_church'],
 'p': ['hjp'],
 'r': ['hjr'],
 's': ['hjs_akatemia'],
 't': ['hjt'],
 'u': ['hjuksebo_station',
       'hjulstrom_curve',
       'hjula_vaeverier',
       'hjularod_castle',
       'hjulsbro_ik'],
 'v': ['hjv']}
