
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vf = {'_': ['vf_corporation',
       'vf-1_valkyrie',
       'vf_bandwidth',
       'vf_venture',
       'vf_venieri'],
 'a': ['vfa-204',
       'vfa-136',
       'vfa-192',
       'vfa-146',
       'vfa-132',
       'vfa-303',
       'vfa-137',
       'vfa-147',
       'vfa-101',
       'vfa-305',
       'vfa-161',
       'vfa-201',
       'vfa-115',
       'vfa-213',
       'vfa-127',
       'vfa-151',
       'vfa-113',
       'vfa-154',
       'vfa-103',
       'vfa-105',
       'vfa-143',
       'vfa-131',
       'vfa-102',
       'vfa-106',
       'vfa-125',
       'vfa-122',
       'vfa-203',
       'vfa-22',
       'vfa-11',
       'vfa-32',
       'vfa-31',
       'vfa-41',
       'vfa-86',
       'vfa-82',
       'vfa-83',
       'vfaw-3',
       'vfa-37',
       'vfa-81',
       'vfa-94',
       'vfa-97',
       'vfa-27',
       'vfa-34',
       'vfa-15',
       'vfa-25',
       'vfa-87',
       'vfa-2',
       'vfax',
       'vfa'],
 'b': ['vfb_friedrichshafen',
       'vfb_sangerhausen',
       'vfb_helmbrechts',
       'vfb_konigsberg',
       'vfb_oldenburg',
       'vfb_eichstatt',
       'vfb_stuttgart',
       'vfb_friedberg',
       'vfb_hermsdorf',
       'vfb_possneck',
       'vfb_speldorf',
       'vfb_gaggenau',
       'vfb_eppingen',
       'vfb_auerbach',
       'vfb_marburg',
       'vfb_giessen',
       'vfb_homberg',
       'vfb_lubeck',
       'vfb_altena',
       'vfb_wissen',
       'vfb_asslar',
       'vfb_theley',
       'vfb_aachen',
       'vfb_huls'],
 'c': ['vfc_anklam', 'vfc_plauen'],
 'd': ['vfdb', 'vfd'],
 'f': ['vff_cup'],
 'i': ['vfinity', 'vfi'],
 'l': ['vfl_lubeck-schwartau',
       'vfl_kirchheim/teck',
       'vfl_engelskirchen',
       'vfl_sindelfingen',
       'vfl_gummersbach',
       'vfl_leverkusen',
       'vfl_pinneberg',
       'vfl_hamm/sieg',
       'vfl_frohnlach',
       'vfl_osnabruck',
       'vfl_oldenburg',
       'vfl_lohbrugge',
       'vfl_wolfsburg',
       'vfl_neckarau',
       'vfl_herzlake',
       "vfl_women's",
       'vfl_marburg',
       'vfl_stettin',
       'vfl_bochum',
       'vfl_bergen',
       'vfl_nagold'],
 'm': ['vfm'],
 'n': ['vfn'],
 'p': ['vfp-206', 'vfp-306', 'vfp-63', 'vfp-62', 'vfp'],
 'r': ['vfr_over-the-top',
       'vfr_neumunster',
       'vfr_baumholder',
       'vfr_pforzheim',
       'vfr_burstadt',
       'vfr_garching',
       'vfr_mannheim',
       'vfr_neuburg',
       'vfr_achern',
       'vfr_dohren',
       'vfr_aalen'],
 's': ['vfs_global'],
 't': ['vfts_352', 'vfts_682', 'vfts_102'],
 'u': ['vfu'],
 'w': ['vfw-fokker_fk-3', 'vfw-fokker_614', 'vfw_club'],
 'x': ['vfx1_headgear', 'vfx_festival']}
