
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-19T05:33:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8dcaf11d85405322fc9e5dcd04ea7564d64b21b",
 "version": "1.17.0.post0.dev168"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
