
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bc = {'_': ['bc_politekhnika-halychyna',
       'bc_mgzavrebi-armia',
       'bc_namur-capitale',
       'bc_ecosocialists',
       'bc_lietkabelis-2',
       'bc_chernomorets',
       'bc_tsmoki-minsk',
       'bc_politekhnik',
       'bc_novosibirsk',
       'bc_lietkabelis',
       'bc_dnipro-azot',
       'bc_radviliskis',
       'bc_delikatesas',
       'bc_valga-valka',
       'bc_gargzdai-sc',
       'bc_budivelnyk',
       'bc_kibirkstis',
       'bc_zaporizhya',
       'bc_zalgiris-2',
       'bc_winterthur',
       'bc200_lncrna',
       'bc_mazeikiai',
       'bc_chernihiv',
       'bc_eindhoven',
       'bc108_family',
       'bc_prievidza',
       'bc_savanoris',
       'bc_magazine',
       'bc_research',
       'bc_partners',
       'bc_boncourt',
       'bc_zalgiris',
       'bc_augsburg',
       'bc_fourteen',
       'bc_siauliai',
       'bc_kretinga',
       'bc_ternopil',
       'bc_juventus',
       'bc_ezerunas',
       'bc_neptunas',
       'bc_borisfen',
       'bc_prometey',
       'bc_terreur',
       'bc_transit',
       'bc_taurage',
       'bc_prienai',
       'bc_sakalai',
       'bc_orchies',
       'bc_nevezis',
       'bc_ferries',
       'bc_sukhumi',
       'bc_goverla',
       'bc_rustavi',
       'bc_andorra',
       'bc_avtodor',
       'bc_aichach',
       'bc_statyba',
       'bc_telsiai',
       'bc_donetsk',
       'bc_dzukija',
       'bc_studies',
       'bc_palanga',
       'bc_kormend',
       'bc_kursiai',
       'bc_odessa',
       'bc_shumen',
       'bc_angels',
       'bc_silute',
       'bc_lavera',
       'bc_powder',
       'bc_sliven',
       'bc_report',
       'bc_enisey',
       'bc_titebi',
       'bc_samara',
       'bc_trakai',
       'bc_khimik',
       'bc_vision',
       'bc_titans',
       'bc_almaty',
       'bc_kosher',
       'bc_yambol',
       'bc_hartha',
       'bc_vienna',
       'bc_khimki',
       'bc_astana',
       'bc_alytus',
       'bc_racers',
       'bc_jonava',
       'bc_dnipro',
       'bc_rasai',
       'bc_lions',
       'bc_beroe',
       'bc_vytis',
       'bc_lulea',
       'bc_kalev',
       'bc_nokia',
       'bc_cygni',
       'bc_place',
       'bc_euras',
       'bc_rytas',
       'bc_parma',
       'bc_mures',
       'bc_lusis',
       'bc_parks',
       'bc_unics',
       'bc_alita',
       'bc_kolin',
       'bc_hydro',
       'bc_bears',
       'bc_rail',
       'bc_jean',
       'bc_kyiv',
       'bc_card',
       'bc_brno',
       'bc_tel'],
 'a': ['bca_marketplace', 'bca_research', 'bca_tower'],
 'b': ['bcb_106.6fm', 'bcbs_239'],
 'c': ['bcci_awards'],
 'd': ['bcdr_4-6-4t', 'bcd_group', 'bcdr_28', 'bcdr_2'],
 'e': ['bce_inc.'],
 'f': ['bcf_wolfratshausen', 'bcfw_recursion', 'bcf_arena'],
 'g': ['bcg_vaccine'],
 'h': ['bch_lions', 'bch_code'],
 'i': ['bci_citirider', 'bcic_college', 'bcia_inc.', 'bci_bus'],
 'j': ['bcjr_algorithm'],
 'k': ['bck_algebra'],
 'l': ['bcl-2-interacting_killer',
       'bcl-6_corepressor',
       'bcl_molecular',
       'bcl-2_family',
       'bcl2-like_1',
       'bcl_springs',
       'bcl_limited',
       'bcl_102'],
 'm': ['bcm_gravelines-dunkerque',
       'bcm_classification',
       'bcmp_network',
       'bcm_theory',
       'bcms_uav'],
 'n': ['bcn_nanotube', 'bcn_week', 'bcn_mes'],
 'o': ['bcore_disc'],
 'p': ['bcp-1_cells'],
 'q': ['bcq'],
 'r': ['bcr_chisinau'],
 's': ['bcs_examination',
       'bcs_statistics',
       'bcs_countdown',
       'bcs_league',
       'bcs_theory',
       'bcs_clash'],
 't': ['bct_modernization', 'bct_commander', 'bct_network'],
 'u': ['bcube', 'bcuc', 'bcu'],
 'v': ['bcv_building'],
 'w': ['bcwest_air'],
 'x': ['bcx'],
 'y': ['bcycle', 'bcy'],
 'z': ['bcz']}
