
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bn = {'_': ['bn_camelopardalis',
       'bn-1200_reactor',
       'bn-600_reactor',
       'bn-800_reactor',
       'bn-350_reactor',
       'bn_televizija',
       'bn_dockyard',
       'bn_destem',
       'bn_radio'],
 'a': ['bna_records'],
 'b': ['bnb_vib'],
 'c': ['bnc_connector', 'bncr_mount', 'bnc_bank'],
 'd': ['bnd'],
 'e': ['bne_intellinews',
       'bnei_netzarim',
       'bnei_menashe',
       'bnei_bathyra',
       'bneid_al-gar',
       'bnei_dekalim',
       'bnei_atzmon',
       'bnei_atarot',
       'bnei_yehuda',
       'bnei_baruch',
       'bnei_darom',
       'bnei_ayish',
       'bnei_akiva',
       "bnei_re'em",
       'bnei_brak',
       'bnei_dror',
       'bnei_yoel',
       'bnei_zion'],
 'f': ['bnf'],
 'g': ['bng'],
 'h': ['bnh_hospital'],
 'i': ['bni_bouifrour',
       'bni_bouchibet',
       'bni_marghnine',
       'bni_abdallah',
       'bni_bouayach',
       'bnin,_kornik',
       'bni_chegdale',
       'bni_faghloum',
       'bni_hassane',
       'bni_tsiriss',
       'bni_darkoul',
       'bni_mansour',
       'bni_boufrah',
       'bni_yagrine',
       'bni_tadjite',
       'bni_bounsar',
       'bni_garfett',
       'bni_frassen',
       'bni_selmane',
       'bni_arouss',
       'bni_hadifa',
       'bni_ammart',
       'bni_makada',
       'bni_khloug',
       'bni_chiker',
       'bni_bouzra',
       'bni_quolla',
       'bni_snous',
       'bni_bchir',
       'bni_oulid',
       'bni_salah',
       'bni_rzine',
       'bni_oukil',
       'bni_hilal',
       'bni_smih',
       'bni_gmil',
       'bni_zoli',
       'bni_drar',
       'bni_ayat',
       'bni_ftah',
       'bni_lent',
       'bni_oual'],
 'j': ['bnj'],
 'k': ['bnk48_discography', 'bnkc_architects', 'bnk_petroleum'],
 'l': ['bnl'],
 'm': ['bnml', 'bnm'],
 'n': ['bnn_bloomberg'],
 'o': ['bnot_hazahav', 'bnois_king', 'bno_news'],
 'p': ['bnp_paribas', 'bnp_youth'],
 'q': ['bnqt'],
 'r': ['bnr/asp-box_repeat', 'bnr_newsradio', 'bnr_prolog'],
 's': ['bns_sher-e-bangla',
       'bns_bangabandhu',
       'bns_anushandhan',
       'bns_dhaleshwari',
       'bns_kapatakhaya',
       'bns_shadhinota',
       'bns_durdharsha',
       'bns_karnafuli',
       'bns_bishkhali',
       'bns_prottasha',
       'bns_madhumati',
       'bns_nabajatra',
       'bns_aparajeya',
       'bns_tallashi',
       'bns_durdanta',
       'bns_joyjatra',
       'bns_durvedya',
       'bns_dordanda',
       'bns_bhatiary',
       'bnsf_railway',
       'bns_atandra',
       'bns_shaikat',
       'bns_sangram',
       'bns_anirban',
       'bns_duranta',
       'bns_shaibal',
       'bns_sahayak',
       'bns_prottoy',
       'bns_titumir',
       'bns_karotoa',
       'bns_darshak',
       'bns_nirbhoy',
       'bns_adamya',
       'bns_durdam',
       'bns_jamuna',
       'bns_nishan',
       'bns_nirmul',
       'bns_durbar',
       'bns_durgam',
       'bns_surovi',
       'bns_gomati',
       'bns_durjoy',
       'bns_shapla',
       'bns_meghna',
       'bns_barkat',
       'bns_surma',
       'bns_tista',
       'bns_bijoy',
       'bns_turag',
       'bnsf_line',
       'bns_sagar',
       'bns_osman',
       'bns_sangu',
       'bns_padma',
       'bns_salam',
       'bns_uttal',
       'bns_ulka'],
 't': ['bnt_shibsha',
       'bnt_rupsha',
       'bntu_minsk',
       'bnt_2',
       'bnt_3',
       'bnt_4',
       'bnt_1'],
 'u': ['bnunis', 'bnu'],
 'v': ['bnv'],
 'w': ['bnw'],
 'x': ['bnxt_supercup', 'bnxt_league'],
 'y': ['bny_mellon'],
 'z': ['bnz']}
