
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zw = {'_': ['zw_sex-determination_system', 'zw_ii_96'],
 'a': ['zwartowo,_pomeranian_voivodeship',
       'zwartowo,_szczecinek_county',
       'zwanzig_projection_operator',
       'zwartowo,_bialogard_county',
       'zwartowko_railway_station',
       'zwartowo_railway_station',
       'zwanowice,_brzeg_county',
       'zwanowice,_nysa_county'],
 'e': ['zweilutschinen_railway_station',
       'zwelifile_christopher_ntuli',
       'zwei_himmlische_dickschadel',
       'zweisimmen_railway_station',
       'zweidlen_railway_station',
       'zwei_himmlische_tochter',
       "zweifel's_helmet_skink",
       'zwekapin_united_f.c.',
       'zweder_van_culemborg',
       'zweibrucken_air_base',
       'zwe_tun_village',
       'zwe_thet_paing',
       'zwe_ohn_chein'],
 'i': ['zwierzyniec,_kuyavian-pomeranian_voivodeship',
       'zwierzyniec,_swietokrzyskie_voivodeship',
       'zwierzyniec,_podlaskie_voivodeship',
       'zwierzyn,_podkarpackie_voivodeship',
       'zwierzynek,_pomeranian_voivodeship',
       'zwierzyniec,_lubusz_voivodeship',
       'zwierzyniecki_salon_artystyczny',
       'zwickau_reichstag_constituency',
       'zwierzyniec,_krasnystaw_county',
       'zwiazek_organizacji_wojskowej',
       'zwierzyniec,_lodz_voivodeship',
       'zwierzyniec,_kozienice_county',
       'zwierzyniec,_lidzbark_county',
       'zwierzynek,_choszczno_county',
       'zwierzyn,_lubusz_voivodeship',
       'zwierzyniec,_wolomin_county',
       'zwierzyniec,_ostroda_county',
       'zwijndrecht_railway_station',
       'zwierzyniec,_makow_county',
       'zwicky_transient_facility',
       'zwischenfall_in_benderath',
       'zwijnaarde_science_park',
       'zwingen_railway_station',
       'zwiesel_forest_museum',
       'zwischen_2_welten',
       'zwick_roell_group',
       'zwi_perez_chajes',
       'zwing_uri_castle'],
 'o': ['zwola,_swietokrzyskie_voivodeship',
       'zwola,_kozienice_county',
       'zwolen,_gostynin_county',
       'zwolle_railway_station',
       'zwola,_garwolin_county',
       'zwolle_half_marathon',
       'zwolnieni_z_teorii']}
