
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zd = {'a': ['zdanow,_swietokrzyskie_voivodeship',
       'zdanow,_lublin_voivodeship',
       'zdar_nad_sazavou',
       'zdar_nad_orlici',
       'zdar_nad_metuji'],
 'e': ['zdenka_predna_discography',
       'zdenek_of_sternberk',
       'zdenko_hans_skraup',
       'zdeslav_of_croatia',
       'zdenek_p._bazant'],
 'i': ['zdihovo,_zagreb_county', 'zdirec_nad_doubravou'],
 'o': ['zdob_si_zdub'],
 'r': ['zdroje,_warmian-masurian_voivodeship',
       'zdroj,_warmian-masurian_voivodeship',
       'zdrojno,_pomeranian_voivodeship',
       'zdrojki,_podlaskie_voivodeship',
       'zdrada,_pomeranian_voivodeship',
       'zdroje,_masovian_voivodeship',
       'zdravets,_haskovo_province',
       'zdrojek,_dzialdowo_county',
       'zdrojki,_starogard_county',
       'zdrojki,_czluchow_county',
       'zdroje,_szamotuly_county',
       'zdravets,_varna_province',
       'zdrojek,_nidzica_county',
       'zdroje,_brodnica_county',
       'zdrojek,_olsztyn_county',
       'zdrapy,_krasnik_county',
       'zdroje,_tuchola_county',
       'zdroje,_swidwin_county',
       'zdroje,_gmina_suprasl',
       'zdrapy,_lublin_county',
       'zdroje,_pila_county'],
 't': ["zdt's_amusement_park"],
 'u': ['zdunowo,_warmian-masurian_voivodeship',
       'zduny,_warmian-masurian_voivodeship',
       'zdunowo,_masovian_voivodeship',
       'zduny,_pomeranian_voivodeship',
       'zduny,_aleksandrow_county',
       'zduny,_brodnica_county',
       'zdunska_wola_karsznice',
       'zduny,_leczyca_county',
       'zduny,_lowicz_county',
       'zduny,_kalisz_county',
       'zdunska_wola_county'],
 'z': ['zdzary,_podkarpackie_voivodeship',
       'zdzislawice,_lublin_voivodeship',
       'zdziechowice,_opole_voivodeship',
       'zdziechow,_szydlowiec_county',
       'zdzislaw,_lubusz_voivodeship',
       'zdzar,_masovian_voivodeship',
       'zdziechow,_lodz_voivodeship',
       'zdzary,_lublin_voivodeship',
       'zdzislaw_jozef_porosinski',
       'zdzary,_wieruszow_county',
       'zdzar,_szczecinek_county',
       'zdzary,_wrzesnia_county',
       'zdziechow,_radom_county',
       'zdzary,_opoczno_county',
       'zdzar,_koszalin_county',
       'zdzary,_grojec_county',
       'zdzislaw_jan_zamoyski',
       'zdzary,_lowicz_county',
       'zdzary,_konin_county',
       'zdzary,_radom_county',
       'zdzary,_turek_county',
       'zdzislaw_jan_ryn']}
