
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lh = {'a': ['lhamoyzingkhar',
       'lhanbryde',
       'lhaviyani',
       'lhakhang',
       "lha'gyai",
       'lhamana',
       'lhanice',
       'lhammas',
       'lhakar',
       'lhardy',
       'lhaze',
       'lhatu',
       'lhamo',
       'lhari',
       'lhasa',
       'lhau',
       'lha'],
 'b': ['lhb'],
 'c': ['lhc@home'],
 'd': ['lhd'],
 'e': ['lheedharifulhu',
       'lherzolite',
       'lheritier',
       'lhermitte',
       'lheebroek',
       'lheraule',
       'lhenice',
       'lhedang',
       'lhery',
       'lherm',
       'lhec',
       'lhez',
       'lhee'],
 'f': ['lhfpl2', 'lhfpl1', 'lhfp'],
 'h': ['lhhh', 'lhhs'],
 'i': ['lhi'],
 'k': ['lhk'],
 'm': ['lhm'],
 'o': ['lhota-vlasenice',
       'lhotzkyella',
       'lhokseumawe',
       'lhospitalet',
       'lhotshampa',
       'lhommaize',
       'lhoksukon',
       'lhopital',
       'lhoumois',
       'lhommeia',
       'lhorong',
       'lhotsko',
       'lhoknga',
       'lhotky',
       'lhotse',
       'lhomme',
       'lhotka',
       'lhote',
       'lhota',
       'lhohi',
       'lhor',
       'lho'],
 'p': ['lhp'],
 's': ['lhsa', 'lhs'],
 't': ['lhtako', 'lhtec', 'lht'],
 'u': ['lhuillier',
       'lhuitre',
       'lhuntse',
       'lhunze',
       'lhuys',
       'lhuna',
       'lhuis',
       'lhuta',
       'lhu'],
 'v': ['lhv'],
 'w': ['lhw'],
 'x': ['lhx1', 'lhx4', 'lhx3', 'lhx2', 'lhx6', 'lhx']}
