
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-19T19:27:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b10138dc32d35d7af2b43b354984559eff355dab",
 "version": "1.5.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
