
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zl = {'a': ['zlatniky-hodkovice',
       'zlatar-bistrica',
       'zlatoustovsky',
       'zlatoustovka',
       'zlatoustovo',
       'zlatoutovsk',
       'zlatopramen',
       'zlataritsa',
       'zlatolicje',
       'zlatanovic',
       'zlatevtsi',
       'zlatolist',
       'zlaticevo',
       'zlatograd',
       'zlatkovic',
       'zlatenka',
       'zladovce',
       'zlatanov',
       'zlatnica',
       'zlatinov',
       'zlatosel',
       'zladovac',
       'zlatenek',
       'zlamanec',
       'zlatitsa',
       'zlatance',
       'zlatokop',
       'zlatopil',
       'zlataric',
       'zlatniky',
       'zlatibor',
       'zlatoust',
       'zlakova',
       'zlakusa',
       'zlatari',
       'zlatkov',
       'zlatica',
       'zlatovo',
       'zlakowo',
       'zlatnik',
       'zlatare',
       'zlavast',
       'zlatan',
       'zlasti',
       'zlatar',
       'zlatev',
       'zlatno',
       'zlabor',
       'zlatna',
       'zlarin',
       'zlagna',
       'zlazne',
       'zlatko',
       'zlatia',
       'zlate',
       'zlast',
       'zlata',
       'zlan'],
 'e': ['zlepsovak',
       'zletece',
       'zlechov',
       'zletovo',
       'zleszyn',
       'zlesti',
       'zleovo',
       'zlebe',
       'zleby'],
 'i': ['zliechov',
       'zlijebac',
       'zlicans',
       'zlinice',
       'zlib-fm',
       'zliten',
       'zlicin',
       'zlijeb',
       'zliv',
       'zlib',
       'zlin'],
 'j': ['zljebovi', 'zljeb'],
 'k': ['zlkovce'],
 'l': ['zllash'],
 'n': ['zlne'],
 'o': ['zlotoria-podlesie',
       'zlotoria-kolonia',
       'zlotki-starowies',
       'zlotki-przeczki',
       'zlotki-pulapki',
       'zlotoglowice',
       'zlotoryjsko',
       'zlotopolice',
       'zlocieniec',
       'zlotowizna',
       'zlochowice',
       'zlokukane',
       'zlokukani',
       'zlotoklos',
       'zlokucane',
       'zlotoryja',
       'zlobayevo',
       'zlopoljac',
       'zlozeniec',
       'zlocudovo',
       'zlotkowy',
       'zlotniki',
       'zloncice',
       'zloganje',
       'zlobizna',
       'zlotoria',
       'zlotkowo',
       'zlotowka',
       'zlotshev',
       'zlobnica',
       'zlokarje',
       'zlobice',
       'zlowody',
       'zlombol',
       'zlogosh',
       'zlotowo',
       'zloczew',
       'zlotege',
       'zlonice',
       'zlokuce',
       'zlockie',
       'zlotkow',
       'zlosela',
       'zlobino',
       'zlotnik',
       'zlosyn',
       'zlobin',
       'zlotna',
       'zlojec',
       'zlonin',
       'zlotne',
       'zlotow',
       'zlocha',
       'zlotki',
       'zlodol',
       'zlotno',
       'zloch',
       'zlota',
       'zlot'],
 't': ['zlt'],
 'u': ['zlunice', 'zlutice', 'zlutava', 'zlukov'],
 'w': ['zlw'],
 'y': ['zlynkovsky', 'zlydzens', 'zlynka', 'zly']}
