
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nk = {'_': ['nk_jadran_hrpelje-kozina',
       'nk1_receptor_antagonist',
       'nk_hrvatski_dragovoljac',
       'nk_jedinstvo_omladinac',
       'nk_bratstvo_gracanica',
       'nk_kamen_ivanbegovina',
       'nk_slavija_pleternica',
       'nk_graficar_ljubljana',
       'nk_olimpija_ljubljana',
       'nk_krivaja_zavidovici',
       'nk_zeleznicar_maribor',
       'nk_omladinac_vranjic',
       'nk_svoboda_ljubljana',
       'nk_neretvanac_opuzen',
       'nk_omladinac_mionica',
       'nk_zvijezda_gradacac',
       'nk_lokomotiva_zagreb',
       'nk_korotan_prevalje',
       'nk_brinje_grosuplje',
       'nk_granicar_zupanja',
       'nk_croatia_zmijavci',
       'nk_ilirska_bistrica',
       'nk_slavonija_pozega',
       'nk_mladost_prolozac',
       'nk_mladost_zdralovi',
       'nk_croatia_sesvete',
       'nk_svoboda_kisovec',
       'nk_papuk_orahovica',
       'nk_kovinar_maribor',
       'nk_slaven_zivinice',
       'nk_zagorec_krapina',
       'nk_jedinstvo_bihac',
       'nk_posavina_zagreb',
       'nk_olimpija_osijek',
       'nk_slatina_radenci',
       'nk_vihor_jelisavac',
       'nk_metalac_osijek',
       'nk_mladost_cernik',
       'nk_branik_maribor',
       'nk_bedem_ivankovo',
       'nk_mladost_prelog',
       'nk_jezero_medvode',
       'nk_portoroz_piran',
       'nk_croatia_dakovo',
       'nk_inter_zapresic',
       'nk_ivancna_gorica',
       'nk_alam_chowdhury',
       'nk_rudar_trbovlje',
       'nk_elkroj_mozirje',
       'nk_gosk_dubrovnik',
       'nk_triglav_kranj',
       'nk_branik_solkan',
       'nk_nafta_lendava',
       'nk_iskra_bugojno',
       'nk_siroki_brijeg',
       'nk_sask_napredak',
       'nk_branik_smarje',
       'nk_slaven_belupo',
       'nk_primorac_1929',
       'nk_marsonia_1909',
       'nk_tsk_topolovac',
       'nk_kovinar_store',
       'nk_rudar_velenje',
       'nk_zagora_unesic',
       'nk_mons_claudius',
       'nk_vodice_sempas',
       'nk_plama_podgrad',
       'nk_slavija_vevce',
       'nk_pomorac_1921',
       'nk_jadran_porec',
       'nk_vis_simm-bau',
       'nk_kamen_ingrad',
       'nk_medulin_1921',
       'nk_novi_travnik',
       'nk_jarun_zagreb',
       'nk_papuk_velika',
       'nk_bosna_visoko',
       'nk_brezice_1919',
       'nk_celik_zenica',
       'nk_bela_krajina',
       'nk_tabor_sezana',
       'nk_smartno_1928',
       'nk_olimp_celje',
       'nk_stol_virtus',
       'nk2_homeobox_1',
       'nk_veres_rivne',
       'nk_rudar_labin',
       'nk_vir_posusje',
       'nk_slavonac_co',
       'nk_gosk_gabela',
       'nk_tosk_tesanj',
       'nk_istra_1961',
       'nk_nafta_1903',
       'nk_junak_sinj',
       'nk_kras_repen',
       'nk_sava_kranj',
       'nk_maribor_b',
       'nk_dugo_selo',
       'nk_rudar_47'],
 'a': ['nkangala_district_municipality', 'nkandla_local_municipality'],
 'e': ['nketoana_local_municipality',
       'nkechi_blessing_sunday',
       'nkechi_justina_nwaogu',
       'nkechi_okoro_carroll'],
 'f': ['nkf_burbage_f.c.'],
 'h': ['nkhotakota_wildlife_reserve', 'nkhata_bay_district'],
 'i': ['nkiruka_florence_nwakwe', 'nki_national_park'],
 'k': ['nkk_sea_hawks'],
 'm': ['nkm_wz.38_fk'],
 'o': ['nkonya-alavanyo_conflict,_ghana',
       'nkonkobe_local_municipality',
       'nkomazi_local_municipality',
       'nkosi_ntsikayezwe_sigcau',
       'nkoranza_north_district',
       "nkosi_sikelel'_iafrika",
       'nko,_cross_river'],
 'q': ['nkqubela_chest_hospital'],
 'r': ['nkrabeah_effah_dartey', 'nkrumah_james_eric'],
 't': ['nkt_arena_karlskrona'],
 'u': ['nkululeko_mkastos_sibanda', 'nkulu_mitumba_kilombo'],
 'v': ['nkvd_prisoner_massacres',
       'nkvd_filtration_camp',
       'nkvd_special_groups',
       'nkvd_labor_columns'],
 'w': ['nkwanta_north_district',
       'nkwe_ya_selefera',
       'nkwe_ya_boronse',
       'nkwe_ya_gauta']}
