
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pj = {'_': ["pj's_smoothies",
       'pj_hirabayashi',
       'pj1_trackbite',
       'pj_vermeulen',
       'pj_steenkamp',
       'pj_banville',
       "pj's_coffee",
       'pj_trailers',
       'pj_loughran',
       'pj_torokvei',
       'pj_crossan',
       'pj_haarsma',
       'pj_liguori',
       'pj_library',
       'pj_bianco',
       'pj_harvey',
       'pj_dozier',
       'pj_morton',
       'pj_phelan',
       'pj_manney',
       'pj_powers',
       'pj_deboy',
       'pj_masks',
       'pj_meyer',
       'pj_botha',
       'pj_raval',
       'pj_perez',
       'pj_bevis',
       'pj_marsh',
       'pj_black',
       'pj_media',
       'pj_bond',
       'pj_ladd',
       'pj_ward'],
 'a': ['pjanici', 'pjanoo', 'pja2', 'pja1', 'pja'],
 'c': ['pjc'],
 'd': ['pjd'],
 'e': ['pjesma_mediterana',
       'pjeter_zakaria',
       'pjer_simunovic',
       'pjeter_bogdani',
       'pjescana_uvala',
       'pjeter_arbnori',
       'pjeter_zarishi',
       'pjeter_malota',
       'pjeter_gjoka',
       'pjeter_spani',
       'pjeter_dungu',
       'pjer_zalica',
       'pjeter_budi',
       'pjerin_noga'],
 'f': ['pjf'],
 'h': ['pjhl'],
 'i': ['pjirc'],
 'm': ['pjm_interconnection'],
 'o': ['pjotr_degtjarjov', 'pjotr_sunin'],
 'p': ['pjp_landfill'],
 's': ['pjsc_vimpelcom'],
 't': ['pjt_partners'],
 'w': ['pjw']}
