
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pn = {'_': ['pn_saxena'],
 'a': ['pnar_language', 'pnar_people', 'pnai_plus'],
 'b': ['pnb_banka', 'pnb_rock'],
 'c': ['pnc_stadium',
       'pnc_center',
       'pnc_field',
       'pnc_tower',
       'pnc_plaza',
       'pnc_arena',
       'pnc_park'],
 'd': ['pnds', 'pnd'],
 'e': ['pneumocystis_wakefieldiae',
       'pneumatopteris_pennigera',
       'pneumatosis_intestinalis',
       'pneumatopteris_truncata',
       'pneumocytic_hyperplasia',
       'pneumococcal_infection',
       'pneumococcal_pneumonia',
       'pneumocystis_pneumonia',
       'pneumocystis_jirovecii',
       'pneumatic_institution',
       'pneumatics_automation',
       'pneumatic_fracturing',
       'pneumococcal_vaccine',
       'pneumosinus_dilatans',
       'pneumatic_lubricator',
       'pneumocystis_murina',
       'pneumatic_chemistry',
       'pneumatic_otoscopy',
       'pneumatic_actuator',
       'pneumatic_cylinder',
       'pneumatic_vehicle',
       'pneumatic_barrier',
       'pneumatic_bladder',
       'pneumatic_circuit',
       'pneumatic_gripper',
       'pneuma_recordings',
       'pneumatic_trough',
       'pneumatic_filter',
       'pneumonic_device',
       'pneumatic_school',
       'pneumatic_cannon',
       'pneumonic_plague',
       'pneumonia_jacket',
       'pneumatic_hammer',
       'pneumatic_weapon',
       'pneumatic_motor',
       'pneumocandin_b0',
       'pneumatic_trail',
       'pneumatic_drill',
       'pneumonia_front',
       'pneumatic_tube',
       'pneumatic_tool',
       'pneumonia_alba',
       'pne_agrodome',
       'pnei_kedem',
       'pne_ag'],
 'f': ['pnf'],
 'g': ['png_power', 'pngase_f', 'png_air', 'png_gas'],
 'h': ['pnh_fc'],
 'i': ['pnictes_asphyxiatus',
       'pnirontis_languida',
       'pnina_tamano-shata',
       'pnictogen_hydride',
       'pnirontis_infirma',
       'pnirontis_modesta',
       'pniaki_mokrzeskie',
       'pnina_rosenblum',
       'pniewo_wielkie',
       'pniewska_gorka',
       'pnina_granirer',
       'pnina_werbner',
       'pnina_salzman',
       'pnina_tornai',
       'pnina_herzog',
       'pnina_gary',
       'pnina_bor'],
 'k': ['pnkp', 'pnkd', 'pnk'],
 'l': ['pnl_discography', 'pnl_explained'],
 'm': ['pnm_resources'],
 'n': ['pnn'],
 'o': ['pnov-predhradi', 'pnoepyga', 'pnovany', 'pnovice', 'pno1', 'pno'],
 'p': ['pnp_agar'],
 'r': ['pnrc2', 'pnrc1', 'pnra'],
 's': ['pns_shamsheer',
       'pns_himalaya',
       'pns_zulfiqar',
       'pns_jalalat',
       'pns_tughril',
       'pns_hashmat',
       'pns_alamgir',
       'pns_muhafiz',
       'pns_khaibar',
       'pns_shujaat',
       'pns_hameed',
       'pns_khalid',
       'pns_hurmat',
       'pns_makran',
       'pns_moawin',
       'pns_karsaz',
       'pns_mehran',
       'pns_taimur',
       'pns_akram',
       'pns_ghazi',
       'pns_zafar',
       'pns_azmat',
       'pns_qasim',
       'pns_tariq',
       'pns_dacca',
       'pns_ahsan',
       'pns_babur',
       'pns_iqbal',
       'pns_hamza',
       'pns_aslat',
       'pns_saad',
       'pns_badr',
       'pns_nasr',
       'pns_saif'],
 't': ['pntc_colleges'],
 'u': ['pnuma_trio'],
 'v': ['pnv-ea', 'pnv'],
 'w': ['pnw'],
 'x': ['pnx'],
 'y': ['pny_technologies', 'pnyxia_scabiei'],
 'z': ['pnz']}
