
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mf = {'_': ['mf_grimm_discography',
       'mf_doom_discography',
       'mf_vladimir_nazor',
       'mf_milano_finanza',
       'mf_bartol_kasic',
       'mf_mate_balota',
       'mf_tycho_brahe',
       'mf_via_mare',
       'mf_bunko_j'],
 'a': ['mfantsiman_municipal_district',
       'mfana_futhi_bhembe',
       'mfa_elite_division',
       'mfa_super_division'],
 'c': ['mfc_lokomotyv_kharkiv',
       'mfc_shakhtar_donetsk',
       'mfc_prodexim_kherson',
       'mfc_lokomotyv_odesa',
       'mfc_stalitsa_minsk',
       'mfc_spartak_varna',
       'mfc_interkas_kyiv',
       'mfc_08_lindenhof',
       'mfc_hit_kyiv'],
 'f': ['mff_football_centre', 'mff_charity_cup', 'mff_super_cup'],
 'g': ['mfg_in_minnesota'],
 'i': ['mfi_world_matchplay', 'mfi_ba-12_slandan'],
 'k': ['mfk_sinara_yekaterinburg',
       'mfk_zemplin_michalovce',
       'mfk_slovan_giraltovce',
       'mfk_lokomotiva_zvolen',
       'mfk_topvar_topolcany',
       'mfk_norilsk_nickel',
       'mfk_slovan_sabinov',
       'mfk_stara_lubovna',
       'mfk_zarya_yakutsk',
       'mfk_dinamo_moskva',
       'mfk_nova_dubnica',
       'mfk_cska_moscow',
       'mfk_dolny_kubin',
       'mfk_dina_moskva',
       'mfk_nova_bana'],
 'o': ['mfo_civilian_medal'],
 's': ['mfs_investment_management', 'mfs_2000_inc'],
 'u': ['mfulupinga_nlando_victor', 'mfundo_cecil_mathonsi'],
 'v': ['mfv_elinor_viking']}
