
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mp = {'_': ['mp_creek,_queensland',
       'mp-apvl_83-f4_mine',
       'mp4_holin_family',
       'mp_anil_kumar',
       'mp_and_silva',
       'mp_muar_f.c.',
       'mp_united_fc'],
 'a': ['mpanga-kipengere_game_reserve', 'mpatu_a_ponta'],
 'b': ['mpbl_finals_mvp'],
 'e': ['mpelembe_secondary_school',
       'mpeg-2_transport_stream',
       'mpeg-4_structured_audio',
       'mpenjati_nature_reserve',
       'mpeg_common_encryption',
       'mpeg_elementary_stream',
       'mpeg_transport_stream',
       'mpeg_media_transport',
       'mpeg_program_stream',
       'mpeg_industry_forum',
       'mpesela_ntlot_soeu',
       'mpeg_audio_decoder',
       'mpeg-h_3d_audio',
       'mpeg-4_part_14',
       'mpeg-4_part_11',
       'mpeg-4_part_20',
       'mpeg_user_data',
       'mpeg-4_part_17',
       'mpeg-4_part_3',
       'mpeg-4_part_2',
       'mpeg-2_part_3'],
 'f': ['mpf_industry_group'],
 'h': ['mphj_technology_investments',
       'mph_entertainment,_inc.',
       'mphanda_nkuwa_dam',
       'mpho_osei_tutu'],
 'i': ['mpisekhaya_ngangomhlaba_sigcawu',
       'mpigi_general_hospital',
       'mpika_railway_station',
       'mpire_music_group',
       'mpi_media_group'],
 'l': ['mpls_local_protection'],
 'o': ['mpofana_local_municipality',
       'mpohor/wassa_east_district',
       'mpower_tobacco_control',
       'mpofu_nature_reserve',
       'mpopoma_high_school',
       'mponeng_gold_mine'],
 'p': ['mppj_selangor_f.c.', 'mpp-b_wierzba_mine'],
 's': ['mps_records_discography', 'mps_capital_services'],
 'u': ['mpumalanga_provincial_legislature', 'mpu_tantular_museum'],
 'w': ['mpwapwa_worm_lizard']}
