
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mt = {'_': ['mt._lebanon,_pennsylvania',
       'mt._rushmore_broadcasting',
       'mt._meridian_schoolhouse',
       'mt._vernon_register-news',
       'mt._angel_glockenspiel',
       'mt._elgon_constituency',
       'mt-50_multitouch_table',
       'mt_explosive_motorboat',
       'mt._memorial_cemetery',
       'mt._shavano_hatchery',
       'mt._rich_petroglyphs',
       'mt._zion_schoolhouse',
       'mt._mercy_apartments',
       'mt_zafirah_hijacking',
       'mt_pratibha_cauvery',
       'mt._sinai_synagogue',
       'mt_timofey_guzhenko',
       'mt._lebanon_station',
       'mt._sterling_essex',
       'mt._union_cemetery',
       'mt._juliet_station',
       'mt._woods_cemetery',
       'mt._rush,_virginia',
       'mt._nebo,_valencia',
       'mt._lebanon_tunnel',
       'mt._eden_formation',
       'mt._angel,_oregon',
       'mt_ommaney_centre',
       'mt._prospect_open',
       'mt._eden_cemetery',
       'mt_sierra_college',
       'mt._sidney_school',
       'mt._zion_cemetery',
       'mt._angel_maypole',
       'mt_wellington_rfc',
       'mt._torry_furnace',
       'mt_sidsel_knutsen',
       'mt._hope_airport',
       'mt_orkim_harmony',
       'mt_yuriy_kuchiev',
       'mt_tasman_spirit',
       'mt._fuji_station',
       'mt_maria_college',
       'mt._mcsauba_site',
       'mt._fuji_records',
       'mt._baldy_league',
       'mt._cuba_center',
       'mt_hagen_eagles',
       'mt_lindsay_mine',
       'mt_cattlin_mine',
       'mt_webber_mine',
       'mt_stolt_valor',
       'mt._scott_park',
       'mt._data_hotel',
       'mt_frans_suell',
       'mt4_ecn_bridge',
       'mt_new_diamond',
       'mt._sac_relays',
       'mt._echo_park'],
 'a': ['mta_bus_time'],
 'c': ['mtc_mq-17_spyhawk'],
 'd': ['mtdna_control_region'],
 'g': ["mtg_hawke's_bay"],
 'h': ['mthonjaneni_local_municipality',
       'mthethomusha_game_reserve',
       'mthwakazi_republic_party',
       'mthatha_general_hospital',
       'mth_electric_trains',
       'mth_racing_engines',
       'mthatha_bucks_f.c.',
       'mthembu_v_letsela',
       'mthuli_ka_shezi',
       'mth_r_422-cg'],
 'i': ['mtirala_national_park',
       'mtito_andei_airport',
       'mtibwa_sugar_f.c.',
       'mti_home_video'],
 'k': ['mtk_budapest_fc'],
 'n': ['mtn_south_sudan'],
 'o': ['mto_wa_mbu'],
 'r': ['mtr_professional_audio',
       'mtr_adtranz-caf_emu',
       'mtr_gaming_group',
       'mtr_in-train_tv',
       'mtr_rotem_emu'],
 's': ['mts_system_architecture', 'mts_systems_corporation'],
 't': ['mtt-s_geographic_activities', 'mtt_turbine_superbike'],
 'u': ['mtubatuba_local_municipality',
       'mtu_turbomeca_rolls-royce',
       'mtutura_a._mtutura',
       'mtu_aero_engines'],
 'v': ['mtv_entertainment_studios',
       'mtv_sports:_snowboarding',
       'mtv_millennial_awards',
       'mtv2_headbangers_ball',
       'mtv_news:_unfiltered',
       'mtv_australia_awards',
       'mtv_artists_platform',
       'mtv_satellite_radio',
       "mtv's_greatest_hits",
       'mtv_campus_diaries',
       'mtv:_trl_christmas',
       'mtv_reality_stars',
       'mtv_school_attack',
       'mtv_staying_alive',
       'mtv_sound_trippin',
       "mtv's_most_wanted",
       'mtv_fandom_awards',
       'mtv_unplugged_2.0',
       'mtv_wonder_girls',
       'mtv_spring_break',
       'mtv_asia_hitlist',
       'mtv_base_player',
       'mtv_asia_awards',
       'mtv_love_school',
       'mtv_beach_house',
       "mtv's_the_lair",
       'mtv_full_tank',
       'mtv_brand_new',
       'mtv_music_24',
       'mtv_fakta_xl',
       'mtv2_hip_hop',
       'mtv_ao_vivo',
       'mtv_vj_hunt',
       'mtv_rock_on',
       'mtv_grind_1',
       "mtv's_amp_2",
       'mtv_big_f'],
 'w': ['mtwara_development_corridor', 'mtwara-mbamba_bay_road'],
 'x': ['mtx_tatra_v8'],
 'y': ['mty_food_group'],
 'z': ['mtz_black_hole']}
