
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_qo = {'a': ['qoaling_highlanders_fc'],
 'd': ['qods_azad_cooperative', 'qods_brick_factory', 'qods_raad_85'],
 'h': ['qohestan_rural_district', 'qohrud_rural_district'],
 'j': ['qojur,_west_azerbaijan'],
 'l': ['qolqoleh,_salas-e_babajani',
       'qolkhanchek-e_shah_tutiya',
       'qolqoleh,_west_azerbaijan',
       'qoltuq_rural_district',
       'qoli_kandi,_charuymaq',
       'qolla_l-bajda_battery',
       'qoli_beyglu,_ardabil',
       'qoli_kandi,_malekan',
       'qoli_kandi,_hamadan',
       'qoli_laleh-ye_sofla',
       'qolqol_rud_district',
       'qoloub_tahta_ramad',
       'qoli_kandi,_zanjan',
       'qoli_laleh-ye_olya',
       'qol_qoleh,_dalahu'],
 'm': ['qomeshlu,_east_azerbaijan',
       'qom_international_airport',
       'qomolangma_national_park',
       'qomsheh-ye_lor_zanganeh',
       'qomsheh-ye_seyyed_yaqub',
       'qomsheh-ye_seyyed_qasem',
       'qombovan_rural_district',
       'qomsheh-ye_seyyed_amin',
       'qom_tappeh,_shabestar',
       'qomrud_rural_district',
       'qom,_razavi_khorasan',
       'qom_tappeh,_maragheh',
       'qom_railway_station',
       'qoman_khoda_nazer',
       'qom_urban_railway',
       'qom_yek-e_kuchak'],
 'o': ['qoornuup_qeqertarsua_island'],
 'r': ['qorveh_industrial_estate',
       'qorveh-e_darjazin_county',
       'qornet_shehwan_gathering',
       'qorban_kandi,_hashtrud',
       'qoroq,_razavi_khorasan',
       'qorqori_rural_district',
       'qorban_kandi,_malekan',
       'qoroq_rural_district',
       'qorban_qelich_molla',
       'qortimet_e_vjeshtes',
       'qori_kalis_glacier',
       'qormi_hockey_club',
       'qorban_ali_mirza'],
 's': ['qos_class_identifier'],
 't': ['qotbabad_rural_district'],
 'v': ['qovaq-e_sofla,_zanjan', 'qovaq-e_olya,_zanjan']}
