
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rt = {'_': ['rt_trianguli_australis',
       'rt_aerostats_systems',
       'rt-21_temp_2s',
       'rt_en_espanol',
       'rt_rna_motifs'],
 'a': ['rta_kapur_chishti', 'rta_rapid_transit'],
 'c': ['rtc_x_roads'],
 'e': ['rte_programme_classifications',
       'rte_commercial_enterprises',
       'rte_philharmonic_choir',
       'rte_television_centre',
       'rte_concert_orchestra',
       'rte_performing_groups',
       'rte_vanbrugh_quartet',
       'rte_executive_board',
       'rte_studio_bombing',
       'rte_radio_centre',
       'rte_radio_cork',
       'rte_jr_radio',
       'rte_lyric_fm',
       'rte_radio_1'],
 'h': ['rthc_bayer_leverkusen',
       'rthk_2020_awards',
       'rthk_radio_3',
       'rthk_tv_31'],
 'i': ['rti_international_metals'],
 'k': ['rtk_class_iii'],
 'l': ['rtl_tele_letzebuerg',
       'rtl_samstag_nacht',
       'rtl_croatia_world',
       'rtl_late_night',
       'rtl_102.5_tv',
       'rtl_ii_you'],
 'm': ['rtmc_reconnaissance_battalion', 'rtmc_astronomy_expo'],
 'n': ['rtnc_congo_building'],
 'p': ['rtp_control_protocol', 'rtp_payload_formats', 'rtp_unia_raciborz'],
 's': ['rts-monton_racing_team'],
 'v': ['rtve_symphony_orchestra',
       'rtv_kozarska_dubica',
       'rtv_novi_pazar',
       'rtv_belle_amie',
       'rtv_bk_telecom',
       'rtv_1879_basel',
       'rtv_studio_b',
       'rtv_euro_agd',
       'rtv_7_tuzla'],
 'x': ['rtx_red_rock'],
 'y': ['rtyne_v_podkrkonosi', 'rtyne_nad_bilinou']}
