
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xm = {'_': ['xm1128',
       'xm70e2',
       'xm2go',
       'xm806',
       'xm104',
       'xm301',
       'xm312',
       'xm25',
       'xm22'],
 'a': ['xmark93', 'xmass', 'xman', 'xmap', 'xmas', 'xma'],
 'c': ['xmc'],
 'd': ['xmdr', 'xmdp', 'xmdf', 'xmd'],
 'e': ['xmetal'],
 'f': ['xmf'],
 'g': ['xmg'],
 'i': ['xmission', 'xmithie', 'xming', 'xmind', 'xmi'],
 'k': ['xmk'],
 'l': ['xmlhttprequest',
       'xml/edifact',
       'xmlstarlet',
       'xmlbeansxx',
       'xmlvend',
       'xmlnuke',
       'xmlmind',
       'xml-rpc',
       'xml:tm',
       'xmlspy',
       'xmlgui',
       'xmltv',
       'xml'],
 'm': ['xmm-newton', 'xmms2', 'xmmer', 'xmms', 'xmm'],
 'o': ['xmobots',
       'xmortis',
       'xmouse',
       'xmonad',
       'xmodem',
       'xmods',
       'xmove',
       'xmos',
       'xmo'],
 'p': ['xmplay', 'xmpp', 'xmp'],
 'r': ['xmr'],
 's': ['xmss', 'xms'],
 't': ['xmtc', 'xmt'],
 'u': ['xmultiplies', 'xmulzencab', 'xmule', 'xmu'],
 'x': ['xmx']}
