
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ht = {'_': ['ht_motorsports',
       'ht_eronet',
       'ht_media',
       'ht_omega',
       'ht_hayko',
       'ht_bandy',
       'ht_tran'],
 'a': ['htantabin_township',
       'htanthi_mont',
       'htay_myint',
       'htamin_jin',
       'htahte_pam',
       'htay_saung',
       'htay_kywe',
       'htay_aung',
       'htay_ngwe',
       'htaw_lay',
       'htay_oo'],
 'b': ['htblva_graz-ortweinschule', 'htb_network'],
 'c': ['htc_thunderbolt',
       'htc_jetstream',
       'htc_excalibur',
       'htc_universal',
       'htc_butterfly',
       'htc_sensation',
       'htc_cavalier',
       'htc_magician',
       'htc_explorer',
       'htc_wildfire',
       'htc_startrek',
       'htc_rezound',
       'htc_phoebus',
       'htc_tornado',
       'htc_artemis',
       'htc_prophet',
       'htc_typhoon',
       'htc_tattoo',
       'htc_desire',
       'htc_apache',
       'htc_touch2',
       'htc_canary',
       'htc_sonata',
       'htc_chacha',
       'htc_legend',
       'htc_gratia',
       'htc_exodus',
       'htc_center',
       'htc_wizard',
       'htc_first',
       'htc_smart',
       'htc_rhyme',
       'htc_magic',
       'htc_radar',
       'htc_salsa',
       'htc_sense',
       'htc_p3600',
       'htc_atlas',
       'htc_touch',
       'htc_dream',
       'htc_p4350',
       'htc_flyer',
       'htc_shift',
       'htc_titan',
       'htc_merge',
       'htc_hero',
       'htc_s730',
       'htc_s710',
       'htc_gene',
       'htc_u12+',
       'htc_tytn',
       'htc_vive',
       'htc_iris',
       'htc_aria',
       'htc_evo',
       'htc_hd2',
       'htc_one',
       'htc_hd7',
       'htc_u11',
       'htc_re',
       'htc_10'],
 'd': ['htd'],
 'e': ['hteinbin_cemetery', 'htein_lin', 'htec_uav', 'htet_yan'],
 'f': ['htf5680a1', 'htf5980', 'htfc', 'htf'],
 'g': ['htgw'],
 'h': ['hth,_hand'],
 'i': ['htigyaing_township',
       'htibyuhsaung_medaw',
       'htilominlo_temple',
       'htilin_monastery',
       'htilin_township',
       'htike_zaw',
       'htin_aung',
       'hti_group',
       'htin_kyaw',
       'htin_gyi',
       'hti_tan'],
 'j': ['htj'],
 'k': ['htk_ltd'],
 'l': ['htl1_lastenstrasse'],
 'm': ['htm_personenvervoer',
       'html5_boilerplate',
       'html_sanitization',
       'html_application',
       'html_components',
       'htms_bangpakong',
       'htms_sukhothai',
       'htmf_mahajanga',
       'html_attribute',
       'htms_thonburi',
       'htms_angthong',
       'htms_maeklong',
       'htms_naresuan',
       'htms_pattani',
       'html_element',
       'html5_audio',
       'html_editor',
       'htm_skytrac',
       'html5_video',
       'htms_taksin',
       'htms_prasae',
       'htms_krabi',
       'html_email',
       'html_tidy'],
 'n': ['htna_uav'],
 'o': ['htoo_foundation', 'htoma_myauk', 'htoe_mont', 'htoot_may', 'hto_park'],
 'p': ['htp_motorsport', 'htp_2'],
 'r': ['htra2_peptidase'],
 's': ['hts_kimberley', 'hts_tentiq'],
 't': ['http_authentication',
       'http_speed+mobility',
       'https_everywhere',
       'http_compression',
       'http_switchboard',
       'http_pipelining',
       'http_location',
       'httu_stadium',
       'http_referer',
       'htt_plethore',
       'http_handler',
       'http_server',
       'http_cookie',
       'http_tunnel',
       'http_flood',
       'http_etag',
       'http_403',
       'http_404',
       'http_301',
       'http_302',
       'http_303',
       'http_451'],
 'u': ['htukkanthein_temple', 'htupayon_pagoda', 'htun_htun', 'htun_wai'],
 'v': ['htv_basket', 'htv_mostar', 'htv_news'],
 'w': ['htw_berlin'],
 'x': ['htx'],
 'y': ['hty_mav'],
 'z': ['htzc_uavs']}
