
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rk = {'_': ['rk_gladijatori_derventa',
       'rk_buducnost_podgorica',
       'rk_podravka_koprivnica',
       'rk_radnicki_kragujevac',
       'rk_budvanska_rivijera',
       'rk_proleter_zrenjanin',
       'rk_lokomotiva_zagreb',
       'rk_eurofarm_pelister',
       'rk_tutunski_kombinat',
       'rk_sutjeska_niksic',
       'rk_warriors_nemila',
       'rk_jeruzalem_ormoz',
       'rk_gorenje_velenje',
       'rk_zeleznicar_1949',
       'rk_metalurg_skopje',
       'rk_rudar_pljevlja',
       'rk_partizan_tivat',
       'rk_bosna_sarajevo',
       'rk_maribor_branik',
       'rk_zeleznicar_nis',
       'rk_sloboda_tuzla',
       'rk_trimo_trebnje',
       'rk_tineks_prolet',
       'rk_crvena_zvezda',
       'rk_sloga_pozega',
       'rk_prilep_2010',
       'rk_nexe_nasice',
       'rk_zito_prilep',
       'rk_sloga_doboj',
       'rk_nada_split',
       'rk_mornar_bar',
       'rk_03_berlin',
       'rk_ovce_pole',
       'rk_95_tp'],
 'a': ['rka_petroleum_companies'],
 'b': ['rkb_mainichi_broadcasting'],
 'g': ['rkg-3_anti-tank_grenade'],
 'i': ['rkia_el_moukim'],
 'k': ['rkk_energiya_museum'],
 'o': ["rko_keith's_theater",
       'rko_boston_theatre',
       'rko_radio_network',
       'rko_forty_acres'],
 's': ['rksv_centro_dominguito',
       'rksv_groene_ster',
       'rks_liblice_1',
       'rks_liblice_2'],
 'v': ['rkv_fc_sithoc']}
