
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rf = {'_': ['rf_resistance_architecture',
       'rf_distribution_amplifier',
       'rf_monitor_software',
       'rf_power_amplifier',
       'rf_micro_devices',
       'rf_switch_matrix',
       'rf_power_margin',
       'rf_front_end'],
 'a': ['rfamide_peptide_family',
       'rfa_lady_cory-wright',
       'rfa_surf_pioneer',
       'rfa_fort_rosalie',
       'rfa_ocean_salvor',
       'rfa_wave_knight',
       'rfa_gray_ranger',
       'rfa_surf_patrol',
       'rfa_wave_ruler',
       'rfa_wave_laird',
       'rfa_wave_chief'],
 'b': ['rfb/grumman_american_fanliner'],
 'c': ['rfc_bad_reichenhall', 'rfc_liegeois_rugby', 'rfc_arsenal_tivat'],
 'e': ['rfe_phonetic_alphabet'],
 'i': ['rfid_on_metal'],
 'k': ['rfk_must_die'],
 'l': ['rfl_reserve_championship',
       'rfl_community_shield',
       'rfl_match_officials',
       "rfl_president's_cup",
       'rfl_yorkshire_cup',
       'rfl_1895_cup',
       'rfl_league_1'],
 'q': ['rfq_beam_cooler'],
 'u': ['rfu_intermediate_cup',
       'rfu_championship_cup',
       'rfu_championship_xv',
       'rfu_senior_vase',
       'rfu_junior_vase']}
