
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rc = {'_': ['rc_lescure-arthes_xiii',
       'rc_locomotive_tbilisi',
       'rc_cola-army_troopers',
       'rc_slovan_bratislava',
       'rc_epernay_champagne',
       'rc_strasbourg_alsace',
       'rc_lokomotiv_moscow',
       'rc_flight_simulator',
       'rc_academy_tbilisi',
       'rc_rustavi_kharebi',
       'rc_armazi_marneuli',
       'rc_kochebi_bolnisi',
       'rc_carpentras_xiii',
       'rc_optical_systems',
       "rc_murphy's_lommel",
       'rc_tashkent_lions',
       'rc_spartak_trnava',
       'rc_spartan_oradea',
       'rc_bobo_dioulasso',
       'rc_yantra_gabrovo',
       'rc_lechia_gdansk',
       'rc_tatra_smichov',
       'rc_time_constant',
       'rc_slavia_prague',
       'rc_sparta_prague',
       'rc_aubenas_vals',
       'rc_army_tbilisi',
       'rc_arka_gdynia',
       'rc_dragon_brno',
       'rc_begles_xiii',
       'rc_roanne_xiii',
       'rc_aia_kutaisi',
       'rc_hotel_open',
       'rc_salon_xiii',
       'rc_baho_xiii',
       'rc_jiki_gori',
       "rc_'t_gooi",
       'rc_de_go!'],
 'a': ['rca_open-source_application',
       'rcaf_station_charlottetown',
       'rcaf_overseas_headquarters',
       'rca_communication_systems',
       'rcaf_detachment_gananoque',
       'rcaf_station_grostenquin',
       'rcaf_detachment_alliston',
       'rcaf_station_assiniboia',
       'rcaf_station_beaverbank',
       'rcaf_station_whitehorse',
       'rcaf_station_claresholm',
       'rca_camden_discography',
       'rcaf_station_saskatoon',
       'rcaf_station_centralia',
       'rcaf_station_macdonald',
       'rcaf_station_dunnville',
       'rca_italiana_orchestra',
       'rcaf_station_marville',
       'rcaf_station_kingston',
       'rca_records_nashville',
       'rcaf_station_davidson',
       'rcaf_station_carberry',
       'rcaf_station_mossbank',
       'rcaf_station_hamilton',
       'rcaf_station_yorkton',
       'rcaf_station_paulson',
       'rca/jive_label_group',
       'rcaf_station_penhold',
       'rcaf_station_weyburn',
       'rcaf_station_moncton',
       'rcaf_station_lachine',
       'rcaf_station_neepawa',
       'rcaf_station_estevan',
       'rcaf_station_dauphin',
       'rcaf_station_brandon',
       'rca_service_company',
       'rca_country_legends',
       'rcaf_station_guelph',
       'rcaf_station_winisk',
       'rcaf_station_virden',
       'rcaf_station_bowden',
       'rcaf_station_parent',
       'rcaf_station_aylmer',
       'rcaf_station_fingal',
       'rcaf_station_tofino',
       'rcaf_station_jarvis',
       'rcaf_station_vulcan',
       'rcaf_station_pearce',
       'rcaf_station_oshawa',
       'rcaf_station_souris',
       'rca_tape_cartridge',
       'rcaf_station_edgar',
       'rcaf_station_dafoe',
       'rca_an/fps-4_radar',
       'rcaf_station_gimli',
       'rcaf_station_caron',
       'rcaf_old_stadium',
       'rca_music_group',
       'rca_spectra_70',
       'rca_studio_ii',
       'rca_studio_b',
       'rca_studio_a',
       'rca_vp_3000'],
 'b': ['rcb_oued_rhiou'],
 'c': ['rcc_marching_tigers'],
 'd': ['rcd_espanyol_femenino',
       'rcd_espanyol_voleibol',
       'rcd_espanyol_basquet',
       'rcd_espanyol_cantera',
       'rcd_espanyol_hoquei',
       'rcd_espanyol_b',
       'rcd_mallorca_b'],
 'i': ['rci_hospitality_holdings'],
 'j': ['rcj_farul_constanta'],
 'm': ['rcmp_harassment_policy',
       'rcmp_security_service',
       'rcmp_heritage_centre',
       'rcmp_vessel_nadon',
       'rcmp_"e"_division'],
 'p': ['rcp_design_global'],
 'r': ['rcr_wireless_news'],
 's': ['rcs_la_chapelle', 'rcsr1_small_rna', 'rcs_motor_club']}
