
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hw = {'_': ['hw_virginis'],
 'a': ['hwangseong-dong,_gyeongju',
       'hwanggeum-dong,_gimcheon',
       'hwanggeum-dong,_gwangju',
       'hwajeong-myeon,_yeosu',
       'hwanggeum-dong,_daegu',
       'hwayang-myeon,_yeosu',
       'hwanggumpyong_island',
       'hwanggumbol_station',
       'hwangnyong_fortress',
       'hwaseong,_gyeonggi',
       'hwarangdae_station',
       'hwangsuwon_airport',
       'hwang_woo-seul-hye',
       'hwaseong_fortress',
       'hwanggeum_station',
       'hwang_young-cheul',
       'hwang_wang-hsiang',
       'hwangseong_sinmun',
       'hwang_byeong-geun',
       'hwamyeong_station',
       'hwanghae_province',
       'hwang_byeong-gwan',
       'hwangbo_seung-hee',
       'hwang_seong-beom',
       'hwang_jung-chiou',
       'hwang_kyeong-tae',
       'hwang_hong-cheol',
       'hwang_chang-shik',
       'hwanghae_dialect',
       'hwa&dam_pictures',
       'hwang_kyun-young',
       'hwanggan_station',
       'hwang_kyung-seon',
       'hwang_myong-chol',
       'hwang_young-shik',
       'hwang_seok-jeong',
       'hwajeong_station',
       'hwang_min-kyoung',
       'hwang_seok-keun',
       'hwang_hyun-chul',
       'hwang_byung-dae',
       'hwang_dong-hyuk',
       'hwange_colliery',
       'hwajeong_museum',
       'hwang_hyeon-jun',
       'hwang_seong-eun',
       'hwang_yeon-seok',
       'hwang_ui-gyeong',
       'hwang_young-hee',
       'hwang_inn-choon',
       'hwang_wei-chung',
       'hwang_young-cho',
       'hwange_district',
       'hwang_tae-hyeon',
       'hwajeon_station',
       'hwangseong_park',
       'hwang_ryong-hak',
       'hwang_kwang-hee',
       'hwacheon_county',
       'hwang_hye-seong',
       'hwang_seung-eon',
       'hwang_jeong-dae',
       'hwang_chul-soon',
       'hwapyong_county',
       'hwang_yea-baang',
       'hwang_jong-hyun',
       'hwang_chan-sung',
       'hwang_ho-lyeong',
       'hwang_keum-sook',
       'hwangbo_je-gong',
       'hwangju_airport',
       'hwang_chung-gum',
       'hwang_kyo-chung',
       'hwangju_station',
       'hwang_jung-woon',
       'hwang_hye-young',
       'hwang_sok-yong',
       'hwang_chi-yeul',
       'hwang_shin-duk',
       'hwang_jin-hyok',
       'hwagok_station',
       'hwang_hyun-hee',
       'hwang_gyu-dong',
       'hwaseo_station',
       'hwang_gyu-beom',
       'hwang_ji-woong',
       'hwang_soo-jung',
       'hwang_jung-eun',
       'hwang_ah-hyeon',
       'hwang_jung-gon',
       'hwang_jung-min',
       'hwang_jun-seok',
       'hwang_hee-chan',
       'hwang_tong-gyu',
       'hwang_sung-min',
       'hwang_min-hyun',
       'hwang_nam-sook',
       'hwawon_station',
       'hwang_hyun-soo',
       'hwang_jang-yop',
       'hwang_pyong-so',
       'hwabon_station',
       'hwang_gi-cheon',
       'hwang_dae-heon',
       'hwang_seong-gu',
       'hwagye_station',
       'hwang_hyun-sun',
       'hwang_hui-yeol',
       'hwang_in-young',
       'hwang_chi-fang',
       'hwangju_county',
       'hwang_youn-joo',
       'hwana_language',
       'hwang_shin-hye',
       'hwang_jin-sung',
       'hwang_sang-hoi',
       'hwang_geum-hee',
       'hwang_hye-youn',
       'hwang_jung-eum',
       'hwang_sun-hong',
       'hwang_byungsng',
       'hwang_byung-ju',
       'hwang_taek-eui',
       'hwang_soon-min',
       'hwang_jang-lee',
       'hwasun_station',
       'hwang_kyo-ahn',
       'hwang_seok-ho',
       'hwang_te-song',
       'hwang_jung-oh',
       'hwang_i-hsuan',
       'hwang_woo-yea',
       'hwang_jae-won',
       'hwang_woo-jin',
       'hwang_hye-suk',
       'hwanggang_dam',
       'hwang_hyeon-a',
       'hwasun_county',
       'hwanseon_cave',
       'hwang_dong-il',
       'hwang_jae-hun',
       'hwang_sun-hui',
       'hwang_hun-hee',
       'hwang_in-sung',
       'hwang_min-woo',
       'hwang_in-youp',
       'hwang_sun-woo',
       'hwang_sang-ho',
       'hwang_do-yeon',
       'hwang_in-shik',
       'hwang_byungki',
       'hwang_yun-gil',
       'hwang_yau-tai',
       'hwang_ho-dong',
       'hwang_jin-woo',
       'hwado_station',
       'hwang_ki-wook',
       'hwang_woo-suk',
       'hwang_yool-ja',
       'hwang_sun-hee',
       'hwang_ji-yoon',
       'hwang_song-su',
       'hwang_san-ung',
       'hwang_jin-san',
       'hwanghae_line',
       'hwang_eun-suk',
       'hwang_shinwei',
       'hwang_yun-suk',
       'hwang_ik-hwan',
       'hwang_hee-tae',
       'hwang_yao-han',
       'hwang_ki-chul',
       'hwadae_county',
       'hwang_sun-won',
       'hwang_in-beom',
       'hwang_in-dong',
       'hwang_sun-pil',
       'hwang_hak-sun',
       'hwata_dynasty',
       'hwang_ye-sul',
       'hwang_ok-sil',
       'hwang_mun-ki',
       'hwang_in-jae',
       'hwang_jun-ho',
       'hwang_in-sun',
       'hwarang_segi',
       'hwang_bo-ram',
       'hwang_in-suk',
       'hwang_bo-sil',
       'hwang_gyu-ok',
       'hwang_ji-soo',
       'hwang_mu-kyu',
       'hwang_sun-ho',
       'hwang_jin-su',
       'hwang_eul-su',
       'hwang_he-suk',
       'hwangbo_kwan',
       'hwandan_gogi',
       'hwang_sun-mi',
       'hwacheon_dam',
       'hwang_ji-man',
       'hwang_seon-a',
       'hwang_eun-ju',
       'hwang_sun-ai',
       'hwang_yak-na',
       'hwang_sun-il',
       'hwang_il-su',
       'hwang_yu-mi',
       'hwaebul_cup',
       'hwang_river',
       'hwang_bo-ra',
       'hwang_in-ho',
       'hwawon_park',
       'hwang_myung',
       'hwang_u-won',
       'hwa-bi_hong',
       'hwang_ui-jo',
       'hwaseong_fc',
       'hwang_jini',
       'hwad_abdel',
       'hwangbo_in',
       'hwang_ji-u',
       'hwang_kee',
       'hwang_sin',
       'hwang_jin',
       'hwang_hui',
       'hwang_hee',
       'hwawei_ko',
       'hwa_chong',
       'hwa_team'],
 'b': ['hwb'],
 'c': ['hwcg_llc'],
 'd': ['hwd'],
 'e': ['hwerow_hweg'],
 'f': ['hwfa_williams'],
 'g': ['hwga', 'hwg'],
 'h': ['hwh'],
 'i': ['hwigyeong-dong', 'hwidiem', 'hwicce', 'hwin', 'hwi'],
 'l': ['hwl_ebsworth', 'hwl_pegaz'],
 'm': ['hwm'],
 'n': ['hwn'],
 'o': ['hwoarang', 'hwo'],
 'p': ['hwp1', 'hwp'],
 'r': ['hwr_group'],
 's': ['hws'],
 't': ['hwt'],
 'u': ['hwung_hwung-hweng', 'hwu_transmitter'],
 'w': ['hww_limited'],
 'y': ['hwyl_nofio', 'hwy_62'],
 'z': ['hwz']}
