
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hv = {'_': ['hv_sittardia',
       'hv_aalsmeer',
       'hv_hurry-up',
       'hv_quintus',
       'hv_11423',
       'hv71_dam',
       'hv_11417',
       'hv_2112',
       'hv_888'],
 'a': ['hval_sjokoladefabrikk',
       'hvalfjordur_tunnel',
       'hvaler_fjordcruise',
       'hvalstad_station',
       'hvar_observatory',
       'hvar_rebellion',
       'hvalsey_church',
       'hvar_cathedral',
       'hvarchil_point',
       'hvam,_skedsmo',
       'hvaler_tunnel',
       'hvar_culture',
       'hvar_channel',
       "hval's_codex",
       'hval_station',
       'hvar_arsenal',
       'hvala,_ne!',
       'hvam,_nes'],
 'b': ['hvb'],
 'c': ['hvc_127-41-330'],
 'd': ['hvdc_mechanicville-schenectady',
       'hvdc_italy-corsica-sardinia',
       'hvdc_hellsjon-grangesberg',
       'hvdc_volgograd-donbass',
       'hvdc_gezhouba-shanghai',
       'hvdc_thailand-malaysia',
       'hvdc_ekibastuz-centre',
       'hvdc_hokkaido-honshu',
       'hvdc_sileru-barsoor',
       'hvdc_lehrte-misburg',
       'hvdc_russia-finland',
       'hvdc_norway-germany',
       'hvdc_cross-channel',
       'hvdc_inter-island',
       'hvdc_haenam-cheju',
       'hvdc_italy-greece',
       'hvdc_rihand-delhi',
       'hvdc_leyte-luzon',
       'hvdc_tian-guang',
       'hvdc_kingsnorth',
       'hvdc_tjaereborg',
       'hvdc_visby-nas',
       'hvdc_converter',
       'hvdc_zhoushan',
       'hvdc_dolwin2',
       'hvdc_dolwin3',
       'hvdc_helwin1',
       'hvdc_dolwin1',
       'hvdc_helwin2',
       'hvdc_borwin1',
       'hvdc_gotland',
       'hvdc_borwin3',
       'hvdc_borwin2',
       'hvdc_sylwin1',
       'hvdc_itaipu',
       'hvdc_troll',
       'hvdc_moyle'],
 'e': ['hvedholm_castle', 'hvert_minut'],
 'f': ['hvf'],
 'g': ['hvgc-1', 'hvg'],
 'h': ['hvhs'],
 'i': ['hviezdoslavovo_namestie',
       'hvitfeldtska_gymnasiet',
       'hvidovre_municipality',
       'hvidovre_hospital',
       'hvidbjerg_station',
       'hvitfeldt_hansen',
       'hvidovre_station',
       'hvidkilde_castle',
       'hvidovre_stadium',
       'hvidovre_church',
       'hvidsten_group',
       'hvidsten_inn',
       'hvita_bridge',
       'hvite_gutter',
       'hvidovre_if',
       'hvide_sande'],
 'j': ['hvj_associates'],
 'k': ['hvk_gusar'],
 'l': ['hvlan', 'hvl'],
 'm': ['hvm_racing'],
 'n': ['hvnnibvl', 'hvn'],
 'o': ['hvorslev_municipality',
       'hvoyna_dialect',
       'hvot_blonduos',
       'hvoyna_cove'],
 'p': ['hvp'],
 'r': ['hvr'],
 's': ['hvs_7'],
 't': ['hvtn_505', 'hvtn_702'],
 'v': ['hvv_hollandia'],
 'x': ['hvx'],
 'y': ['hvy1', 'hvy']}
