
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hh = {'_': ['hh_electronics',
       'hh_equation',
       'hh_tunnel',
       'hh_46/47',
       'hh_24-26',
       'hh_elite',
       'hh_azur',
       'hh_1/2',
       'hh_111',
       'hh_34'],
 'a': ['hhadydia_minte', 'hha_services'],
 'b': ['hhb'],
 'c': ['hhc_hardenberg'],
 'd': ['hhd'],
 'e': ['hhelehhele', 'hhead', 'hhex', 'hhe'],
 'f': ['hhf_architects'],
 'g': ['hhg'],
 'h': ['hhhr_tower'],
 'i': ['hhipl1', 'hhip', 'hhi'],
 'j': ['hhj'],
 'k': ['hhk'],
 'l': ['hhla', 'hhl'],
 'm': ['hhman1', 'hhms', 'hhm'],
 'n': ['hhn'],
 'o': ['hho_multimedia', 'hhohho_region'],
 'p': ['hhpc', 'hhpa', 'hhp'],
 'r': ['hhr'],
 's': ['hhs_glasgow'],
 't': ['hhtdd', 'hht'],
 'u': ['hhukwini', 'hhus', 'hhu'],
 'v': ['hhv-8-associated_mcd'],
 'w': ['hhw'],
 'y': ['hhy'],
 'z': ['hhz']}
