
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yl = {'a': ['yla-enonvesi',
       'yla-rieveli',
       'ylay-talaa',
       'yla-malmi',
       'ylander',
       'ylakiai',
       'ylamaa',
       'ylands',
       'ylane',
       'yla'],
 'c': ['ylc'],
 'd': ['yldefonso', 'yld'],
 'e': ['ylenia', 'yle24', 'ylem', 'ylex', 'yle'],
 'g': ['ylg'],
 'i': ['ylioppilaslehti',
       'yli-suolijarvi',
       'ylikersantti',
       'ylikiiminki',
       'yli-maaria',
       'ylivaapeli',
       'yli-kitka',
       'ylivieska',
       'ylitornio',
       'ylipulli',
       'yliaster',
       'yliharma',
       'ylistaro',
       'ylilauta',
       'yliskyla',
       'ylistrum',
       'yli-ii',
       'ylide',
       'ylipe',
       'ylike',
       'yli'],
 'j': ['ylj'],
 'k': ['ylk'],
 'l': ['yllymakh', 'yllenus', 'yllana', 'yllka', 'yllas', 'ylla', 'yll'],
 'm': ['ylm'],
 'o': ['ylojarvi', 'ylonen', 'ylodes', 'ylo'],
 'p': ['ylpm1', 'ylppo'],
 'r': ['ylr'],
 's': ['yls'],
 't': ['ylt'],
 'v': ['ylvingen', 'ylvis', 'ylva']}
