
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ef = {'_': ['ef_johnson_technologies',
       "ef'al_regional_council",
       'ef_reims_sainte-anne',
       'ef_education_first'],
 'a': ['efaf_challenge_cup',
       'efao_zografou_b.c.',
       'efar_system_model',
       'efasi_rna_motif'],
 'c': ['efc_frejus_saint-raphael', 'efc_uganda_limited'],
 'd': ['efda_nations_cup'],
 'e': ['efeo_chinese_transcription',
       'efeler_railway_station',
       'efetobor_wesley_apochi',
       'efes_beverage_group',
       'efendi_abdul_malek',
       'efek_rumah_kaca',
       'efe_jerry_obode',
       'efe_paul_azino'],
 'f': ['efficiency-thoroughness_trade-off_principle',
       'effingham-teutopolis_christmas_classic',
       'effia-kwesimintsim_municipal_district',
       'effective_group_decision-making',
       'effluent_decontamination_system',
       'effective_diffusion_coefficient',
       'effective_medium_approximations',
       'effretikon-hinwil_railway_line',
       'effective_one-body_formalism',
       'efficient_envy-free_division',
       'effective_circulating_volume',
       'effective_refractory_period',
       'effie_newbigging_richardson',
       'effective_transmission_rate',
       'efficient_consumer_response',
       'effingham_county_courthouse',
       'effective_evolutionary_time',
       'effective_unemployment_rate',
       'efficient_coding_hypothesis',
       'effective_perl_programming',
       'effective_public_relations',
       'efficient_power_conversion',
       'effingham_county,_illinois',
       'effretikon_railway_station',
       'effective_safety_training',
       'effective_altruism_global',
       'effutu_municipal_district',
       'effingham,_south_carolina',
       'efficient_contract_theory',
       'effingham_county,_georgia',
       'effective_population_size',
       'efficient_xml_interchange',
       'effort_sharing_regulation',
       'effingham,_new_hampshire',
       'effective_radiated_power',
       'effective_nuclear_charge',
       'efficiency_new_brunswick',
       'effective_exchange_rate',
       'effective_selfing_model',
       'effective_atomic_number',
       'effective_interest_rate',
       'effie_adelaide_rowlands',
       'effective_gross_income',
       'effects_of_pornography',
       'effective_field_theory',
       'effective_polish_space',
       'effective_sample_size',
       'effiegene_locke_wingo',
       'effler,_west_virginia',
       'effective_mode_volume',
       'effects_of_meditation',
       'effie_mccollum_jones',
       'efferent_nerve_fiber',
       'efficient_voter_rule',
       'efficient_energy_use',
       'effingham_daily_news',
       'effie_anderson_smith',
       'effie,_west_virginia',
       'effie_a._southworth',
       'effects_of_marriage',
       'effa_ellis_perfield',
       'effie:_just_quietly',
       'effects_of_cannabis',
       'effects_of_overtime',
       'effiong_dickson_bob',
       'effie_waller_smith',
       'effects_of_madness',
       'effacer_le_tableau',
       'effects_of_divorce',
       'effie_louise_power',
       'efficacy_of_prayer',
       'effie_alberta_read',
       'effie_m._morrissey',
       'effie_lee_newsome',
       'eff_pioneer_award',
       'effiom_otu_bassey',
       'effect_of_reality',
       'effie_lee_morris',
       'effect_model_law',
       'effect_and_cause',
       'effiong_okon_eyo',
       'effie_neal_jones',
       'effie_i._canning',
       'effie_f._kamman',
       'effort_and_love',
       'effie_mona_mack',
       'effie_t._battle',
       'eff_des_cracker',
       'effie_j._taylor',
       'effects_of_war',
       'effets_de_soir',
       'effie_t._brown'],
 'i': ['efigenia_vasquez_astudillo',
       "efird's_department_store",
       'efimerida_ton_syntakton',
       'efimeris_ton_athinon',
       'efi_system_partition',
       'efigie_da_republica',
       'efi_technology_inc',
       'efini_hiroshima_sc',
       'efisio_kon_uguak'],
 'l': ['efl_championship_play-offs',
       'efland,_north_carolina',
       'efl_golden_glove',
       'efl_league_two',
       'efl_league_one',
       'efl_on_quest'],
 'm': ['efm_health_clubs'],
 'o': ['eforia_spitalelor_civile',
       'eforie_sud,_constanta',
       'efootball_pes_2020',
       'efort_open_reviews',
       'efo_kodjo_mawugbe',
       'efogi_tree_frog'],
 'q': ['efqm_excellence_award'],
 'r': ['efremov_atamans_palace',
       'efrain_sanchez_hidalgo',
       'efrain_morales_sanchez',
       'efrain_aguilar_gongora',
       'efrain_arizmendi_uribe',
       'efraim_basilio_krevey',
       'efrain_teodoro_torres',
       'efrain_forero_trivino',
       'efrain_andrade_viteri',
       'efrain_esquivias_jr.',
       'efrain_pena_damacio',
       'efrain_gonzalez_jr.',
       'efrem_zimbalist_jr.',
       'efren_cerezo_torres',
       'efraim_medina_reyes',
       'efrain_rivera_perez',
       'efrain_jara_idrovo',
       'efren_perez_rivera',
       'efrain_morote_best',
       'efrain_lopez_neris',
       'efrain_rios_montt',
       'efren_nunez_mata',
       'efren_reyes_sr.',
       'efrain_bu_giron',
       'efrain_de_jesus',
       'efren_reyes_jr.',
       'efren_c._pinon'],
 's': ['efstratios_n._pistikopoulos', 'efstratiou_v_glantschnig'],
 't': ['efterarsmorgen_ved_sortedamssoen',
       'eftimie_murgu,_caras-severin',
       'efter_nattens_brander'],
 'z': ['efzar_rural_district']}
