
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ew = {'a': ['ewald-heinrich_von_kleist-schmenzin',
       'ewald-oseen_extinction_theorem',
       'ewa_heavyweight_championship',
       'ewald_von_kleist-schmenzin',
       'ewan_mcgregor_filmography',
       'ewald_heinrich_rubsaamen',
       'ewansville,_new_jersey',
       'ewart_agnew_boddington',
       'ewald_gerhard_seeliger',
       'ewald_auguste_esselen',
       'ewaldus_martinus_sedu',
       'ewa_hedkvist_petersen',
       'ewart_alan_mackintosh',
       'ewald_von_demandowsky',
       'ewa_district,_hawaii',
       'ewald_stefan_pollok',
       'ewa_district,_nauru',
       'ewald_j._schmeichel',
       'ewan_stafford_page',
       'ewa_larysa_krause',
       'ewart_c._atkinson',
       'ewaso_nyiro_labeo',
       'ewart_park_phase',
       'ewald_von_lochow',
       'ewa_thalen_finne',
       'ewan,_new_jersey',
       'ewa_skoog_haslum',
       'ewan_david_alman',
       'ewals_cargo_care',
       'ewald_von_kleist',
       'ewaso_nyiro_barb',
       'ewald_o._stiehm',
       'ewa_monika_mes',
       'ewald_w._busse',
       'ewart_g._plank',
       'ewale_a_mbedi',
       'ewa_ad_amorem',
       'ewa_da_cruz'],
 'b': ['ewbank_da_camara'],
 'e': ['ewelinow,_swietokrzyskie_voivodeship',
       'ewelinow,_lodz_voivodeship',
       "ewens's_sampling_formula",
       'ewenki_autonomous_banner',
       'ewe_unification_movement',
       'ewesley_railway_station',
       'ewelme_watercress_beds',
       'ewen_wallace_cameron',
       'ewell_ross_mccright',
       'ewell_castle_school',
       'ewenny_priory_house',
       'ewe_baskets_juniors',
       'ewen_cameron_bruce',
       'ewerby_and_evedon',
       'ewen_neil_mcqueen',
       'ewen_hugh_cameron',
       'ewen_paul_cameron',
       'ewen_maddock_dam',
       'ewe_cote,_whitby'],
 'f': ['ewf_cruiserweight_championship', 'ewf_heavyweight_championship'],
 'h': ['ewha_womans_university',
       'ewhurst,_east_sussex',
       'ewha_law_school',
       'ewhl_super_cup'],
 'i': ['ewing_township,_michigan',
       'ewing_christian_college',
       'ewingville,_new_jersey',
       'ewingar_state_forest',
       'ewing_public_schools',
       'ewing_v._california',
       'ewing_v._goldstein',
       'ewine_van_dishoeck',
       'ewing_high_school',
       'ewing_thomas_kerr',
       'ewing_miles_brown',
       'ewing_werlein_jr.',
       'ewing_y._freeland',
       'ewing_e._booth',
       'ewing_t._boles',
       'ewin_l._davis',
       'ewig_mit_dir'],
 'l': ['ewl_management_limited'],
 'o': ['ewout_w._steyerberg',
       'ewout_van_asbeck',
       'ewo_brewery_ltd.',
       'ewonde_a_kwane'],
 'r': ['ewr_vj_101'],
 'u': ['ewu-um_governors_cup'],
 'y': ['ewy_rosqvist-von_korff', 'ewyas_harold_meadows', 'ewyas_harold_castle']}
