
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_eo = {'_': ['eo_personal_communicator', 'eo_sidi_bouzid', 'eo_media_group'],
 'c': ['eocene-oligocene_extinction_event',
       'eochaid_mac_domangairt',
       'eochaid_ua_flannacain',
       'eochaid_mac_domnaill',
       'eochaid_mac_fiachnai',
       'eochaid_mac_oengusa',
       'eochaidh_o_heoghusa',
       'eochaid_mac_echdach',
       'eochaid_mac_condlai',
       'eochaid_faebar_glas',
       'eochaidh_ua_floinn',
       'eochu_mac_ailella',
       'eochocan_mac_aedo',
       'eochaid_mac_eirc'],
 'd': ['eodicynodon_assemblage_zone',
       'eodisha_summit_2013',
       'eodisha_summit_2014'],
 'g': ['eoganacht_airthir_cliach',
       'eoghan_mag_samhradhain',
       'eogan_of_strathclyde',
       'eoganacht_locha_lein',
       'eoghan_ban_gallagher',
       'eogan_mac_durthacht',
       'eoghan_o_donnghaile',
       'eogan_mac_muiredaig',
       'eoganan_mac_oengusa',
       'eoghan_o_neachtain',
       'eogan_of_ardstraw',
       'eoghan_o_madadhan',
       'eoghan_o_tuairisc',
       'eoghan_ua_cathain',
       'eoghain_o_cianain',
       'eoghan_o_heidhin',
       'eoghan_of_argyll',
       'eogan_mac_neill'],
 'i': ['eoi_business_school',
       'eoin_o_cuileannain',
       'eoin_mac_suibhne',
       'eoin_ryan_snr',
       'eoin_ryan_jnr',
       'eoin_g._harty',
       'eoin_o_murchu',
       'eoin_o_broin',
       'eoin_o_gnimh'],
 'l': ['eolais_mac_biobhsach',
       'eola-amity_hills_ava',
       'eolyne_y._nichols',
       'eolus_von_rettig',
       'eolyn_klugh_guy'],
 'm': ['eomst_unmanned_blimps'],
 'n': ['eon_digital_entertainment', "eon_de_l'etoile", 'eon_of_axum'],
 'o': ['eoornis_pterovelox_gobiensis', 'eoon_qi_xuan'],
 'r': ['eordaikos_2007_f.c.',
       'eorcenberht_of_kent',
       'eormenred_of_kent',
       'eormenric_of_kent'],
 's': ['eosinophil_cationic_protein', 'eosin_methylene_blue'],
 't': ['eotvos_lorand_university'],
 'w': ['eowils_and_halfdan', 'eowa_of_mercia'],
 'y': ['eoy_cosplay_festival']}
