
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ez = {'_': ['ez_canis_majoris', 'ez_do_dance'],
 'a': ['ezana_of_axum'],
 'b': ['ezbet_el_haggana', 'ezbet_el_nakhl', 'ezbet_el_borg'],
 'c': ['ezcaroz_-_ezkaroze'],
 'd': ['ezdan_holding_group'],
 'e': ['ezekiel_of_seleucia-ctesiphon',
       'ezerets,_blagoevgrad_province',
       'ezequiel_montes_municipality',
       'ezequiel_zamora_municipality',
       'ezequiel_gutierrez_iglesias',
       'ezequiel_montes,_queretaro',
       'ezenzeleni_blind_institute',
       'ezerets,_dobrich_province',
       'ezequiel_fernandez_langan',
       'ezequiel_martinez_estrada',
       'ezerovo,_plovdiv_province',
       'ezequiel_padilla_penaloza',
       'ezequiel_ataucusi_gamonal',
       'ezerovo,_varna_province',
       'ezekiel_abraham_ezekiel',
       'ezerini,_penkule_parish',
       'ezequiel_oscar_scarione',
       'ezekiel_saleh_manasseh',
       'ezekiel_woodruff_house',
       'ezekiel_"easy"_rawlins',
       'eze_castle_integration',
       'ezekiel_cheever_school',
       'ezequiel_perez_companc',
       'ezequiel_gonzalez_mas',
       'ezemvelo_kzn_wildlife',
       'ezekiel_isaac_malekar',
       'ezekiel_stone_wiggins',
       'ezell,_south_carolina',
       'ezekial_gardner_house',
       'ezekiel_kiptoo_chebii',
       'ezekiel_the_tragedian',
       'ezekiel_emerson_farm',
       'ezekiel_lol_gatkuoth',
       'ezekiel_phelps_house',
       'ezekiel_kelsey_house',
       'ezeiza,_buenos_aires',
       'ezekiel_j._ingersoll',
       'ezekiel_ayo_awosoga',
       'ezekiel_f._chambers',
       'ezekiel_c._gathings',
       'ezekiel_sawin_house',
       'eze_vincent_okeuhie',
       'ezequiel_pedro_paz',
       'ezekiel_s._sampson',
       'ezenwo_nyesom_wike',
       'eze_nri_omalonyeso',
       'ezekiel_ezra_smith',
       'ezechiel_de_decker',
       'ezekiel_b._turner',
       'ezequiel_di_paolo',
       'eze_nri_ifikuanim',
       'eze_nri_anyamata',
       'eze_chika_philip',
       'ezekiel_a._straw',
       'eze_nri_obalike',
       'ezekiel_f._clay',
       'eze_nri_ezimilo',
       'ezell_blair_jr.',
       'eze_nri_fenenu',
       'eze_nri_omalo',
       'eze_nri_buife',
       'eze_nri_agu'],
 'h': ['ezhumesvaramudayar_temple,_koyirkkulam',
       'ezhukone_railway_station',
       'ezhimala_railway_station',
       'ezhumattoor_devi_temple',
       'ezhu_sundara_rathrikal',
       'ezhou_railway_station',
       'ezhou_huahu_airport',
       'ezhai_padum_padu'],
 'i': ['ezinqoleni_local_municipality',
       'ezidxan_protection_force',
       "ezidxan_women's_units",
       'ezikial_perry_house',
       'ezio_della_savia',
       'ezio_maria_gray',
       'ezio_di_matteo'],
 'm': ['ezmel_de_ablitas'],
 'n': ['eznik_of_kolb'],
 'o': ['ezo,_south_sudan', 'ezo_red_fox'],
 'r': ['ezra_churchill_henniger',
       'ezra_yaghoub_synagogue',
       'ezras_israel_synagogue',
       'ezra_townsend_cresson',
       'ezra_carll_homestead',
       'ezra_carpenter_house',
       'ezra_allred_bungalow',
       'ezra_meeker_mansion',
       'ezra_stiles_college',
       'ezra_stiles_gannett',
       'ezra_greenleaf_weld',
       'ezra_allred_cottage',
       'ezra_squier_tipple',
       'ezra_ripley_thayer',
       'ezra_palmer_gould',
       'ezra_stiles_house',
       'ezra_otis_kendall',
       'ezra_hall_gillett',
       'ezra_abbott_house',
       'ezra_danolds_cole',
       'ezra_white,_ll.b.',
       'ezra_w._wilkinson',
       'ezra_zion_melamed',
       'ezra_baya_lawiri',
       'ezra_t._champlin',
       'ezra_clark_house',
       'ezra_p._prentice',
       'ezra_taft_benson',
       'ezras_torah_fund',
       'ezra_c._carleton',
       'ezra_butler_eddy',
       'ezra_jacob_kraus',
       'ezra_j._william',
       'ezra_jack_keats',
       'ezra_stiles_ely',
       'ezra_a._burrell',
       'ezra_rice_house',
       'ezra_b._taylor',
       'ezra_weston_ii',
       'ezra_c._stiles',
       'ezra_uzi_yemin',
       'ezra_t._newman',
       'ezra_a._carman',
       'ezra_t._benson',
       'ezra_p._savage',
       'ezra_clark_jr.',
       'ezra_h._ripple',
       'ezra_b._french',
       'ezra_a._bowen',
       'ezra_f._kysor',
       'ezra_g._levin',
       'ezra_c._dalby',
       'ezra_w._mudge',
       'ezra_c._gross',
       'ezra_p._ewers',
       'ezra_s._carr',
       'ezra_w._taft'],
 'u': ['ezulwini_handicrafts_centre', 'ezuriko_kofun_cluster'],
 'z': ['ezzatabad,_razavi_khorasan',
       'ezzedine_salim_subdistrict',
       'ezzeldin_muktar_abdurahman',
       'ezzedine_choukri_fishere',
       'ezzatabad-e_sharm_dasht',
       'ezz_el-dine_zulficar',
       'ezzedin_yacoub_hamed',
       'ezzeddine_hadj_sassi',
       'ezz_el-din_esmail',
       'ezz_el-din_nasir',
       'ezzat_el_kamhawi',
       'ezza_agha_malak',
       'ezz_eddin_hosni',
       'ezzat_abou_aouf',
       'ezzat_el_alaili',
       'ezzat_ol_din',
       'ezz_od_din']}
