
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oj = {'_': ['oj_da_juiceman'],
 'a': ['ojai_playwrights_conference',
       'ojamajo_doremi_discography',
       'ojakula,_laane-viru_county',
       'ojamajo_doremi_na-i-sho',
       'ojaq_qeshlaq-e_khoruslu',
       'ojars_arvids_feldbergs',
       'ojala_pudiera_borrarte',
       'ojai_tennis_tournament',
       'ojamajo_doremi_dokkan!',
       'ojakula,_jarva_county',
       'ojaq_kandi,_hashtrud',
       'ojakula,_hiiu_county',
       'ojamajo_doremi_sharp',
       'ojaq_kandi,_minjavan',
       'ojars_eriks_kalnins',
       'ojai_music_festival',
       'ojai_valley_school',
       'ojai_valley_news',
       'ojaq_qoli_kandi',
       'ojai_valley_inn'],
 'c': ['ojcow_national_park'],
 'e': ['ojetta_rogeriee_thompson', 'ojeda,_la_pampa'],
 'g': ['ojg_klal_israel'],
 'h': ['ojhri_camp_disaster'],
 'i': ['oji_chukwuemeka_ifeanyichukwu',
       'ojibway_correctional_facility',
       'ojika-class_patrol_vessel',
       'ojibway_provincial_park',
       'ojibway_prairie_complex',
       'ojibwe_writing_systems',
       'ojima_komatsugawa_park',
       'ojisan_and_marshmallow',
       'ojima_neputa_festival',
       'ojibway_fire_tower',
       'oji_paper_company',
       'ojibwe_in_montana'],
 'o': ['ojos_negros,_teruel',
       'ojo_alamo_formation',
       'ojo_caliente_spring',
       'ojos_del_caburgua',
       'ojos_de_maricunga',
       'ojos_del_salado',
       'ojo_del_muerto',
       'ojo_the_lucky',
       'ojos_de_brujo',
       'ojo_de_liebre',
       'ojos_de_fuego',
       'ojos_de_agua',
       'ojo_de_buey',
       'ojos_de_mar',
       'ojo_del_sol',
       'ojo_de_agua',
       'ojo_in_oz'],
 'r': ['ojrzanow,_masovian_voivodeship',
       'ojrzen,_masovian_voivodeship',
       'ojrzanow,_lodz_voivodeship',
       'ojrzen,_lodz_voivodeship'],
 's': ['ojsjomyrarna_nature_reserve'],
 'u': ['oju_senior_championships', 'ojuelos_de_jalisco', 'ojude_oba_festival']}
