
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pk = {'_': ['pk-banken',
       'pk.com.cn',
       'pk-huset',
       'pk-11195',
       'pk-35',
       'pk-17',
       'pk3'],
 'a': ['pkaila', 'pka'],
 'b': ['pkb'],
 'c': ['pkcs', 'pkc'],
 'd': ['pkd1l1', 'pkd2l1', 'pkd'],
 'e': ['pke'],
 'f': ['pkfix', 'pkf'],
 'g': ['pkg-config', 'pkgsrc', 'pkg'],
 'h': ['pkharmat', 'pkhista', 'pkhyan', 'pkhali', 'pkhmat', 'pkhovi', 'pkhrut'],
 'i': ['pkioverheid',
       'pkidha',
       'pkids',
       'pkill',
       'pkig',
       'pkia',
       'pkib',
       'pki'],
 'l': ['pklr'],
 'm': ['pkmyt1', 'pkm2', 'pkms', 'pkm'],
 'n': ['pknox1', 'pknox2', 'pknic', 'pkna', 'pkn2', 'pkn'],
 'o': ['pko'],
 'p': ['pkpass', 'pkp'],
 'r': ['pkr.com', 'pkr'],
 's': ['pks1353-341', 'pks'],
 't': ['pkt'],
 'u': ['pkunity', 'pku'],
 'w': ['pkware'],
 'x': ['pkx'],
 'z': ['pkzip']}
