
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pd = {'_': ['pd-217,014',
       'pd-102,807',
       'pd-168,077',
       'pd-0298029',
       'pd-128,907',
       'pd-137889',
       'pd-atrics',
       'pd-50',
       'pd-l1',
       'pd1'],
 'a': ['pdap1', 'pdac', 'pdaf', 'pdag', 'pda'],
 'b': ['pdbreport', 'pdbwiki', 'pdbe-kb', 'pdbsum', 'pdb'],
 'c': ['pdcurses',
       'pdcd1lg2',
       'pdcd6ip',
       'pdc-109',
       'pdcd10',
       'pdcd4',
       'pdcd2',
       'pdcd7',
       'pdcd5',
       'pdcd6',
       'pdci',
       'pdca',
       'pdc'],
 'd': ['pdd-62'],
 'e': ['pde11a',
       'pde10a',
       'pde6d',
       'pde4d',
       'pde1a',
       'pde10',
       'pde11',
       'pde1b',
       'pde4a',
       'pde7a',
       'pde6c',
       'pdeng',
       'pde8a',
       'pde4c',
       'pde4b',
       'pde6b',
       'pde2a',
       'pde8b',
       'pde9a',
       'pde1c',
       'pde6a',
       'pde7b',
       'pde6g',
       'pde1',
       'pdea',
       'pde6',
       'pdes',
       'pde9',
       'pde'],
 'f': ['pdfcreator',
       'pdf-parser',
       'pdfescape',
       'pdftotext',
       'pdfimages',
       'pdfsharp',
       'pdfedit',
       'pdfvue',
       'pdf/vt',
       'pdf.js',
       'pdf417',
       'pdf/ua',
       'pdftex',
       'pdf/x',
       'pdftk',
       'pdf/a',
       'pdf/e',
       'pdfa',
       'pdf'],
 'g': ['pdgfra', 'pdgfrb', 'pdgfd', 'pdgfc', 'pdgfb', 'pdgfa', 'pdg'],
 'h': ['pdhs', 'pdh'],
 'i': ['pdiff', 'pdia3', 'pdia2', 'pdic', 'pdi'],
 'k': ['pdk3', 'pdk2', 'pdk4', 'pdk'],
 'l': ['pdlim7',
       'pdlim4',
       'pdlim1',
       'pdlim3',
       'pdlim5',
       'pdlim2',
       'pdlct',
       'pdlc',
       'pdl'],
 'm': ['pdm-35', 'pdmu', 'pdms', 'pdmi', 'pdma', 'pdm'],
 'n': ['pdnsd', 'pdns', 'pdn'],
 'o': ['pdogg', 'pdoto', 'pdoc', 'pdos', 'pdo'],
 'p': ['pdp-laban',
       'pdp-11/73',
       'pdp-8/e',
       'pdp-14',
       'pdp-11',
       'pdp-15',
       'pdp-16',
       'pdp-12',
       'pdp-10',
       'pdp-6',
       'pdp-9',
       'pdp-1',
       'pdp-8',
       'pdp-5',
       'pdp-7',
       'pdp-4',
       'pdpr',
       'pdpn',
       'pdp'],
 'q': ['pdq'],
 'r': ['pdr-ihumure', 'pdr1p', 'pdra', 'pdrs', 'pdrc', 'pdr'],
 's': ['pdss2', 'pdshp', 'pds5a', 'pdss1', 'pds5b', 'pdsd', 'pdsa', 'pds'],
 't': ['pdtv', 'pdtc', 'pdt'],
 'u': ['pdu'],
 'v': ['pdvsa', 'pdvvp', 'pdval', 'pdv'],
 'x': ['pdxlan', 'pdx1', 'pdxs', 'pdxk', 'pdx'],
 'z': ['pdzk1ip1', 'pdzrn3', 'pdzd11', 'pdzd2', 'pdzk1', 'pdzd4', 'pdz']}
