
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pm = {'_': ['pm-international', 'pm2fgd', 'pm20d1', 'pm2fgr', 'pm3', 'pm2'],
 'a': ['pmat', 'pmac', 'pmag', 'pmaa', 'pma'],
 'b': ['pmbr', 'pmb'],
 'c': ['pmc-sierra', 'pmcs', 'pmcl', 'pmcd', 'pmc'],
 'd': ['pmdta', 'pmdtt', 'pmdf', 'pmdc', 'pmda', 'pmd'],
 'e': ['pmel', 'pme'],
 'f': ['pmfbp1', 'pmftc', 'pmf'],
 'g': ['pmg'],
 'h': ['pmhub', 'pmhs', 'pmh'],
 'i': ['pmirkb', 'pmi-80', 'pmip', 'pmi'],
 'j': ['pmji'],
 'k': ['pmk'],
 'l': ['pmlf', 'pmla', 'pmln', 'pmle', 'pmlq', 'pml'],
 'm': ['pmm2', 'pmm1', 'pmma', 'pmmp', 'pmm'],
 'n': ['pmnh', 'pmn'],
 'o': ['pmode', 'pmos', 'pmof', 'pmo'],
 'p': ['pmpv1', 'pmpcb', 'pmpca', 'pmp2', 'pmp'],
 'q': ['pmq'],
 'r': ['pmr446', 'pmrs', 'pmrt', 'pmr'],
 's': ['pmseic',
       'pmset',
       'pmsf',
       'pmsl',
       'pms1',
       'pmsa',
       'pmsg',
       'pmse',
       'pms2'],
 't': ['pmtoday', 'pmtair', 'pmts', 'pmt'],
 'u': ['pmut', 'pmu'],
 'v': ['pmview', 'pmve', 'pmv'],
 'w': ['pmwiki'],
 'x': ['pmx'],
 'z': ['pmz-a-750']}
