
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ij = {'_': ['ij,_zanjan', 'ij,_iran'],
 'a': ['ijamsville,_maryland',
       'ijamsville,_indiana',
       'ijara_constituency',
       'ijahnya_christian',
       'ijaharul_hussain',
       'ijaw_languages',
       'ijara_district',
       'ijah_anderson',
       'ijazul_ahsan',
       'ijahman_levi',
       'ijad_madisch',
       'ijaz_hussain',
       'ijah_halley',
       'ijaw_people',
       'ijaz_faqih',
       'ijaz_masih',
       'ijaz_mirza',
       'ijaz_ahmed',
       'ijaz_butt'],
 'b': ['ijburg', 'ijb'],
 'c': ['ijc'],
 'd': ['ijdileni', 'ijdanak', 'ijdan', 'ijdb'],
 'e': ['ijeoma_ndukwe-egwuronu',
       'ijevan_dendropark',
       'ijeoma_nwaogwugwu',
       'ijem_onwuamaegbu',
       'ijele_masquerade',
       'ijeoma_umebinyuo',
       'ijeoma_egbunine',
       'ijeoma_uchegbu',
       'ijebu_kingdom',
       'ijebu_people',
       'ijebu_north',
       'ijeoma_john',
       'ijero_ekiti',
       'ijeoma_oluo',
       'ijeoma_obi',
       'ijebu_east',
       'ijebu,_owo',
       'ijebu_igbo',
       'ijebu_ode'],
 'f': ['ijf_blokker'],
 'g': ['ijgeul', 'ijg'],
 'h': ['ijhorst', 'ijhl'],
 'i': ['ijimaia_plicatellus',
       'ijivitari_district',
       'ijiri_station',
       'ijichi_kosuke',
       'ijiel_protti',
       'ijiri_okada',
       'ijira_river',
       'iji_castle'],
 'j': ['ijjuriktuq', 'ijjodu', 'ijji'],
 'k': ['ijke_buisma'],
 'l': ['ijlil_al-shamaliyya', 'ijlil_al-qibliyya'],
 'm': ['ijmuiden_heliport', 'ijmuider_courant', 'ijm_corporation'],
 'n': ['ijnisinya', 'ijn'],
 'o': ['ijoid_languages', 'ijora,_lagos', 'ijo_temple', 'ijon_tichy'],
 'p': ['ijpl'],
 'r': ['ijrud_county'],
 's': ['ijsselmonde,_rotterdam',
       'ijsbrand_chardon',
       'ijsbrand_godske',
       'ijssel_line'],
 't': ['ijtihadi_family', 'ijteba_nadwi'],
 'u': ['ijuin,_kagoshima',
       'ijuizinho_river',
       'ijuin_hikokichi',
       'ijumaa_mosque',
       'ijuin_station',
       'ijuw_district',
       'ijuin_tadaaki',
       'ijui_airport',
       'ijuin_goro',
       'ijui_river',
       'iju,_ogun'],
 'v': ['ijvm', 'ijv'],
 'y': ['ijyaraj_singh'],
 'z': ['ijzerbedevaart',
       'ijzerkoekje',
       'ijzevoorde',
       'ijzendoorn',
       'ijzendijke',
       'ijzerwake',
       'ijzerlo',
       'ijzim']}
