
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-21T09:27:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1efb15518ac8c0f14dbfb7e9c8ccf436d363cc15",
 "version": "1.0.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
