
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vv = {'_': ['vv_nieuw-lekkerland',
       'vv_noordscheschut',
       'vv_scherpenzeel',
       'vv_monnickendam',
       'vv_rigtersbleek',
       'vv_spijkenisse',
       'vv_heerjansdam',
       'vv_papendrecht',
       'vv_sliedrecht',
       'vv_buitenpost',
       'vv_heerenveen',
       'vv_chevremont',
       'vv_haaglandia',
       'vv_staphorst',
       'vv_noordwijk',
       'vv_kloetinge',
       'vv_smitshoek',
       'vv_hoogeveen',
       'vv_rijsoord',
       'vv_hoogland',
       'vv_zwaluwen',
       'vv_martinus',
       'vv_bennekom',
       'vv_nunspeet',
       'vv_baronie',
       'vv_alkmaar',
       'vv_katwijk',
       'vv_almkerk',
       'vv_capelle',
       'vv_eemdijk',
       'vv_geldrop',
       'vv_orionis',
       'vv_alverna',
       'vv_gestel',
       'vv_gemert',
       'vv_cephei',
       'vv_dongen',
       'vv_pernis',
       'vv_berkum',
       'vv_corvi',
       'vv_emmen',
       'vv_dovo',
       'vv_desk',
       'vv_goes',
       'vv_duno',
       'vv_zob',
       'vv_sjc',
       'vv_sho',
       'vv_una'],
 'a': ['vva_podmoskovye'],
 'b': ['vvb'],
 'c': ['vvcap', 'vvc'],
 'e': ['vvedenskoye_cemetery', 'vvedenskaya_gotnya'],
 'g': ['vvg'],
 'h': ['vvhs'],
 'i': ['vvi'],
 'l': ['vvl'],
 'm': ['vvm'],
 'o': ['vvo2max', 'vvog', 'vvob', 'vvo'],
 'p': ['vvpb', 'vvp'],
 'r': ['vvrssnn', 'vvr'],
 's': ['vvs_laxman', 'vvs_moscow'],
 't': ['vvt-i', 'vvt'],
 'v': ['vvv_survey'],
 'z': ['vvz']}
