
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nj = {'_': ['nj2045/2046', 'nj.com', 'nj9842', 'nj2'],
 'a': ['njardtaksvollurinn',
       'njavalppazhangal',
       'njananikshepam',
       'njardhallen',
       'njakinjaki',
       'njarackal',
       'njattadi',
       'njardvik',
       'njalila',
       'njabini',
       'njarka',
       'njaba',
       'njall',
       'njala',
       'njars',
       'njaan',
       'njac',
       'njai',
       'nja'],
 'c': ['njc'],
 'd': ['njdc'],
 'e': ['njeliyanparambu',
       'njeganovici',
       'njegosevo',
       'njemanica',
       'njeezhoor',
       'njegnjevo',
       'njegovuda',
       'njesuthi',
       'njection',
       'njegusi',
       'njerve',
       'njenga',
       'njegas',
       'njeim',
       'njega',
       'njeri',
       'njege',
       'njele',
       'njeru',
       'nje'],
 'f': ['njfx', 'njf'],
 'h': ['njhl', 'njhs'],
 'i': ['njinikom',
       'njiverce',
       'njikoka',
       'njivice',
       'njigari',
       'njirana',
       'njivica',
       'njikwa',
       'njivak',
       'njimom',
       'njimi',
       'njiku',
       'njie'],
 'k': ['njk'],
 'l': ['njl'],
 'm': ['njm'],
 'n': ['njn'],
 'o': ['njomza',
       'njombe',
       'njorun',
       'njordr',
       'njoro',
       'njora',
       'njoya',
       'njoko',
       'njoge',
       'njoto',
       'njoku',
       'njoy',
       'njos',
       'njo'],
 'p': ['njps', 'njp'],
 'r': ['njrat'],
 's': ['njs'],
 'u': ['njurundabommen',
       'njuri-ncheke',
       'njutanger',
       'njupeskar',
       'njuskalo',
       'njurunda',
       'njunis',
       'njunga',
       'njuup',
       'njuga',
       'njuhe'],
 'v': ['njvc']}
