
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gv = {'a': ['gvav-rapiditas',
       'gvardeysky',
       'gvardeysk',
       'gvaladze',
       "gvar'am",
       'gvazava',
       'gvazda',
       'gvarv',
       'gvat',
       'gvax',
       'gva'],
 'b': ['gvb'],
 'c': ['gvcs', 'gvc'],
 'd': ['gvd'],
 'e': ['gvenetadze', 'gvedysh', 'gve'],
 'f': ['gvfx', 'gvfs', 'gvf'],
 'g': ['gvg'],
 'h': ['gvhs', 'gvh'],
 'i': ['gvisor', 'gvidas', 'gvido', 'gviet', 'gvir', 'gvi'],
 'k': ['gvk'],
 'l': ['gvl'],
 'm': ['gvm'],
 'n': ['gvnml', 'gvn'],
 'o': ['gvozdanovic',
       'gvozdenovic',
       'gvozdyovka',
       'gvozdansko',
       'gvozdovka',
       'gvozdarus',
       'gvozdevo',
       'gvozdev',
       'gvozdic',
       'gvozdac',
       'gvozno',
       'gvozd'],
 'p': ['gvpa', 'gvp'],
 'r': ['gvr'],
 's': ['gvsig', 'gvsd', 'gvs'],
 't': ['gvt'],
 'u': ['gvulot', 'gvu'],
 'v': ['gvvv']}
