VERSION_YEAR = 2022
VERSION_MONTH = int('08')
VERSION_DAY = int('24')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('34')
MAJOR_VERSION = 0
MINOR_VERSION = 7
PATCH_VERSION = 202208240934
version_date = '2022/08/24 09:34'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
