
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jy = {'_': ['jy1-sat', 'jy15'],
 'a': ['jyamirgadhi', 'jyamrukot', 'jyamaruk', 'jyamire', 'jyani'],
 'd': ['jydskevestkysten', 'jyderup', 'jydge'],
 'e': ['jyeshthoputro', 'jyesthadeva', 'jyellowl'],
 'g': ['jygri'],
 'j': ['jyj'],
 'l': ['jyllands-posten',
       'jyllands-ringen',
       'jyluu-bulak',
       'jyly-suu',
       'jyllinge',
       'jylandy',
       'jyl-kol',
       'jylha'],
 'm': ['jymmy'],
 'n': ['jynge', 'jynx'],
 'o': ['jyotirmimamsa',
       'jyotihsastra',
       'jyothirmayi',
       'jyotirlinga',
       'jyotipuram',
       'jyotikuchi',
       'jyotisar',
       'jyothika',
       'jyotipur',
       'jyongri',
       'jyotsna',
       'jyoshna',
       'jyoti'],
 'p': ['jyp-akatemia', 'jypsi', 'jyp'],
 'r': ['jyrgalang', 'jyrobike', 'jyrki', 'jyr'],
 's': ['jystrup', 'jysk'],
 't': ['jython', 'jytte'],
 'u': ['jyu-oh-sei', 'jyutping'],
 'v': ['jyvasjarvi', 'jyvaskyla']}
