
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cs = {'_': ['cs_universitatea_cluj-napoca',
       'cs_universitatea_alexandria',
       'cs_gloria_bistrita-nasaud',
       'cs_tiligul-tiras_tiraspol',
       'cs_femina-sport_chisinau',
       'cs_universitatea_craiova',
       'cs_petrolistul_boldesti',
       'cs_universitatea_resita',
       'cs_crisul_chisineu-cris',
       'cs_mont-royal_outremont',
       'cs_metalurgistul_cugir',
       'cs_minerul_mehedinti',
       'cs_luceafarul_oradea',
       'cs_concordia_chiajna',
       'cs_progym_gheorgheni',
       'cs_plebiscito_padova',
       'cs_muncitorul_resita',
       'cs_unirea_tarlungeni',
       'cs_stiinta_miroslava',
       'cs_phoenix_constanta',
       'cs_politehnica_iasi',
       'cs_sporting_rosiori',
       'cs_dinamo_bucuresti',
       'cs_vedita_colonesti',
       'cs_portul_constanta',
       'cs_rapid_bucuresti',
       'cs_viitorul_daesti',
       'cs_conpet_ploiesti',
       'cs_sporting_liesti',
       'cs_sporting_vaslui',
       'cs_sportul_snagov',
       'cs_aerostar_bacau',
       'cs_minerul_lupeni',
       'cs_national_sebis',
       'cs_viitorul_ianca',
       'cs_sedan_ardennes',
       'cs_motorul_oradea',
       'cs_soimii_pancota',
       'cs/mpq-90_bee_eye',
       'cs_arcada_galati',
       'cs_salamis_glory',
       'cs_coltea_brasov',
       'cs_stiinta_bacau',
       'cs_bihorul_beius',
       'cs_turnu_severin',
       'cs_gloria_resita',
       'cs_soimii_lipova',
       'cs_minerul_motru',
       'cs_triumf_barca',
       'cs_unirea_jucu',
       'cs_gloria_arad',
       'cs_cfr_simeria',
       'cs_ocean_layer',
       'cs_targu_mures',
       'cs_bayou_city',
       'cs_rugby_1863',
       'cs_42/3_mine',
       'cs_don_bosco',
       'cs_42/2_mine',
       'cs_la_mancha',
       'cs_36_merlin',
       'cs_fola_esch',
       'cs_acu_arad',
       'cs_sao_joao'],
 'a': ['csa_orthocarolina_sportsplex',
       'csa_provincial_competitions',
       'csa_axiopolis_cernavoda',
       'csaba_ferenc_asztalos',
       'csa_steaua_bucuresti',
       'csaba_nagy_lakatos',
       'csain_snia_milano',
       'csar_rack_4-6-4rt',
       'csa_t20_challenge',
       'csaba_p._kovesdy',
       'csa_ps-38_tourer',
       'csa_flight_001',
       'csa_flight_511',
       'csa_flight_540',
       'csa_flight_523',
       'csa_aurul_brad',
       'csak_ii_hahot',
       'csak_i_hahot'],
 'b': ['csbc_corporation,_taiwan'],
 'c': ['csc_aircraft_company',
       'csc_maiden_saginaw',
       'csc_1599_selimbar',
       'cscl_arctic_ocean',
       'cscl_indian_ocean',
       "csc_team_o'grady",
       'csc_nika_stadium',
       'csc_media_group',
       'csc_champa_f.c.',
       'cscl_long_beach',
       'csc_de_cayenne'],
 'd': ['csd_class_t478.3', 'csd_class_387.0', 'csd_class_477.0'],
 'e': ['csepel_automobile_factory', 'cse_insurance_group'],
 'f': ['csf/serum_glucose_ratio',
       'csf/serum_albumin_ratio',
       'csf_spartanii_selemet',
       'csf_sparta_chisinau',
       'csf_cfr_timisoara',
       'csf_tap_test'],
 'i': ['csi:_fatal_conspiracy',
       'csilla_von_boeselager',
       'csi_immanuel_church',
       'csi:_the_experience',
       'csi:_deadly_intent',
       'csi:_hard_evidence',
       'csi:_dark_motives',
       'csi:_crime_city',
       'csi_300_index',
       'csi_100_index',
       'csir_sara_ii'],
 'k': ['cska_pamir_dushanbe',
       'cska_sports_complex',
       'csk_uhersky_brod',
       'csk_zsu_stadium',
       'cska_ice_palace',
       'csk_vmf_moscow'],
 'l': ['csl_golden_boot', 'csl_group_ltd'],
 'm': ['csm_sighetu_marmatiei',
       'csm_bucovina_radauti',
       'csm_olimpia_salonta',
       'csm_jiul_petrosani',
       'csmd_diables_noirs',
       'csm_dunarea_galati',
       'csm_avantul_reghin',
       'csm_flacara_moreni',
       'csm_miercurea_ciuc',
       'csm_dacia_orastie',
       'csm_ramnicu_sarat',
       'csm_corona_brasov',
       'csm_campia_turzii',
       'csm_digi_oradea',
       'csm_targu_mures',
       'csm_satu_mare',
       'csm_u_oradea'],
 'n': ['csn_international_translators'],
 'o': ['csongrad-csanad_county_assembly',
       "csorba's_mouse-eared_bat",
       'cso_tricolorul_breaza',
       'csoa_forte_prenestino',
       'csongor_istvan_nagy',
       'cso_concert_hall',
       'csongor_es_tunde'],
 'p': ['csp_um_timisoara', 'csp_music_group'],
 'r': ['csr_refinery,_yarraville',
       'csr_corporation_limited',
       'csra_football_classic',
       'csrb/rsmb_rna_family',
       'csr_qishuyan_sda2',
       'csr_ziyang_sda1',
       'csrc_rna_family'],
 's': ['css_general_beauregard',
       'css_image_replacement',
       'css_stonewall_jackson',
       'css_palmetto_state',
       'css_north_carolina',
       'css_colonel_lovell',
       'css_general_lovell',
       'css_html_validator',
       'css_working_group',
       'css_black_warrior',
       'css_patrick_henry',
       'css_general_polk',
       'css_colonel_lamb',
       'css_indian_chief',
       'css_cotton_plant',
       'css_virginia_ii',
       'css_george_page',
       'css_grid_layout',
       'css_new_orleans',
       'css_grand_duke',
       'css_lady_davis',
       'css_zen_garden',
       'css_box_model',
       'css_sea_bird',
       'css_rob_roy'],
 't': ['cst-panvel_fast_corridor', 'cstc_hmcs_acadia'],
 'u': ['csu_pueblo_thunderwolves',
       'csu_neptun_constanta',
       'csu_danubius_galati',
       'csu_vointa_sibiu',
       'csu_alba_iulia'],
 'v': ['csv_olympia_1897'],
 'w': ['cswf_hardcore_championship'],
 'x': ['csx_transportation_building',
       'csx_northern_region',
       'csx_southern_region',
       'csx_8888_incident',
       'csx_a-line_bridge'],
 'y': ['csyd_tristan_suarez']}
