
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nm = {'_': ['nm-2-ai', 'nm-2201', 'nm142', 'nm135'],
 'a': ['nmai_dzorn'],
 'b': ['nmb48', 'nmb'],
 'c': ['nmc_recordings', 'nmc_health', 'nmc_music', 'nmc_jhapa'],
 'd': ['nmda_receptor'],
 'e': ['nme_originals',
       'nmea_onenet',
       'nme_awards',
       'nme_radio',
       'nmea_0183',
       'nmea_2000',
       'nme_tv'],
 'f': ['nmfp', 'nmf'],
 'g': ['nmgc', 'nmg'],
 'h': ['nmhc_nijmegen'],
 'i': ['nmixx', 'nmic', 'nmit', 'nmi'],
 'k': ['nmky_helsinki'],
 'l': ['nml_cygni'],
 'm': ['nmmu_f.c.'],
 'n': ['nmn_nucleosidase'],
 'o': ['nmos_logic', 'nmon_ford'],
 'p': ['nmperign', 'nmp22', 'nmp-7', 'nmpa', 'nmpi', 'nmp'],
 'r': ['nmr_database', 'nmr_tube'],
 's': ['nms_marasesti',
       'nms_randunica',
       'nms_elisabeta',
       'nms_marsuinul',
       'nms_constanta',
       'nms_trotusul',
       'nms_viscolul',
       'nms_fulgerul',
       'nms_rechinul',
       'nms_delfinul',
       'nms_grivita',
       'nms_vedenia',
       'nms_marasti',
       'nms_aurora',
       'nms_naluca',
       'nms_sborul',
       'nms_smeul'],
 't': ['nmtb', 'nmtc', 'nmtv', 'nmt'],
 'u': ['nmu_stadium'],
 'v': ['nmvac4-a/c/y/w-135', 'nmv'],
 'w': ['nmwa', 'nmw']}
