
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nv = {'_': ['nv-41_mine', 'nv_network', 'nv_puppis', 'nv_energy', 'nv_arena'],
 'a': ['nvax', 'nva'],
 'b': ['nvb'],
 'c': ['nvc'],
 'd': ['nvdimm', 'nvdla', 'nvdes', 'nvda', 'nvd'],
 'e': ['nve'],
 'f': ['nvfc'],
 'g': ['nvg'],
 'h': ['nvhs', 'nvh'],
 'i': ['nvidia_gameworks',
       'nvidia_purevideo',
       'nvidia_optimus',
       'nvidia_jetson',
       'nvidia_g-sync',
       'nvidia_share',
       'nvidia_tesla',
       'nvidia_titan',
       'nvidia_nvdec',
       'nvidia_nvenc',
       'nvidia_drive',
       'nvidia_br02',
       'nvidia_grid',
       'nvidia_ion',
       'nvi_f.k.33',
       'nvidia_gtc',
       'nvidia_dgx',
       'nvi_f.k.34',
       'nvi_f.k.31',
       'nvi_f.k.29',
       'nvi_f.k.32',
       'nvidia_rtx',
       'nvi_f.k.35'],
 'k': ['nvk_sakha'],
 'l': ['nvlink'],
 'm': ['nvm_express'],
 'p': ['nvpi'],
 'r': ['nvr,_inc.'],
 's': ['nvss_2146+82'],
 't': ['nvtc', 'nvtv', 'nvt'],
 'v': ['nvv'],
 'x': ['nvx'],
 'z': ['nvz']}
