
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mt = {'_': ['mt-propeller',
       'mt-energie',
       'mt-rnr2',
       'mt-atp8',
       'mt-nd4l',
       'mt-rnr1',
       'mt-atp6',
       'mt-snp',
       'mt6235',
       'mt-usa',
       'mt-nd1',
       'mt-nd5',
       'mt-nd2',
       'mt-nd6',
       'mt-nd4',
       'mt-tl2',
       'mt-cyb',
       'mt-ts1',
       'mt-nd3',
       'mt-tl1',
       'mt-lbu',
       'mt-ts2',
       'mt-tn',
       'mt-tp',
       'mt103',
       'mt-tv',
       'mt-lb',
       'mt-ty',
       'mt-te',
       'mt-ta',
       'mt-tw',
       'mt940',
       'mt-45',
       'mt-tk',
       'mt-55',
       'mt-ti',
       'mt-03',
       'mt-tq',
       'mt-th',
       'mt-tr',
       'mt-tf',
       'mt-tg',
       'mt-tt',
       'mt-tm',
       'mt-td',
       'mt-tc',
       'mt1e',
       'mt3d',
       'mt81',
       'mt1x',
       'mt1b',
       'mt1f',
       'mt1h',
       'mt63',
       'mt1m',
       'mt3',
       'mt2',
       'mt9',
       'mt1'],
 'a': ['mtarnagha',
       'mtakoudja',
       'mtawarira',
       'mtaileb',
       'mtanana',
       'mtavari',
       'mtanila',
       'mtamaa',
       'mtarfa',
       'mtama',
       'mtasc',
       'mta3',
       'mtac',
       'mtas',
       'mta1',
       'mtaa',
       'mtap',
       'mta2',
       'mtab',
       'mta'],
 'b': ['mtbs', 'mtbo', 'mtb'],
 'c': ['mtconnect', 'mtcp1', 'mtch1', 'mtch2', 'mtcc', 'mtc'],
 'd': ['mtdh', 'mtd'],
 'e': ['mtevandidi',
       'mtekente',
       'mtendere',
       'mtembur',
       'mtenje',
       'mterf1',
       'mtepe',
       'mteza',
       'mtel',
       'mtep',
       'mte'],
 'f': ['mtfongwaneni', 'mtfr1l', 'mtfmt', 'mtfc', 'mtff', 'mtf1', 'mtf'],
 'g': ['mtgf', 'mtg1', 'mtg'],
 'h': ['mthwalume',
       'mthwakazi',
       'mthethwa',
       'mthatha',
       'mthfd1l',
       'mthembu',
       'mthfd2l',
       'mthfd2',
       'mthfd1',
       'mths',
       'mth'],
 'i': ['mtispiri',
       'mtiuleti',
       'mtitaa',
       'mtiebi',
       'mtinko',
       'mtif2',
       'mtime',
       'mtipa',
       'mti'],
 'j': ['mtj'],
 'k': ['mtk'],
 'l': ['mtld', 'mtl'],
 'm': ['mtmr12',
       'mtmr14',
       'mtmtmk',
       'mtmr1',
       'mtmr6',
       'mtmr2',
       'mtmr9',
       'mtmr3',
       'mtm'],
 'n': ['mtnx', 'mtn'],
 'o': ['mtorrent',
       'mtongwe',
       'mtools',
       'mtonya',
       'mtonia',
       'mtower',
       'mtorc2',
       'mtorc1',
       'mtoni',
       'mtori',
       'mtosi',
       'mtoto',
       'mtor',
       'mto1',
       'mtom',
       'mtoe',
       'mtoa',
       'mto'],
 'p': ['mtpaint', 'mtp18', 'mtpas', 'mtpa', 'mtpn', 'mtpd', 'mtp'],
 'r': ['mtropolis',
       'mtrnr2l6',
       'mtrnr2l8',
       'mtrf1l',
       'mtrace',
       'mtron',
       'mtrr',
       'mtrx',
       'mtr'],
 's': ['mtsignobartukhutsesi',
       'mtskheta-mtianeti',
       'mtsangamboua',
       'mtsangadjou',
       'mtsangadoua',
       'mtsamboro',
       'mtskhetos',
       'mtsambama',
       'mts-116m',
       'mtsapere',
       'mtsahara',
       'mtsamdou',
       'mtskheta',
       'mtsensk',
       'mtsvane',
       'mtshazo',
       'mtsghun',
       'mts255',
       'mtss1',
       'mtso',
       'mtsl',
       'mtss',
       'mtsa',
       'mts'],
 't': ['mttfd', 'mttr', 'mttd', 'mtt'],
 'u': ['mtubatuba',
       'mtunzini',
       'mtungi',
       'mtumba',
       'mtus1',
       'mtusa',
       'mtume',
       'mtuc',
       'mtu'],
 'v': ['mtv1987',
       'mtv-82',
       'mtvph',
       'mtv-1',
       'mtv3',
       'mtvu',
       'mtvx',
       'mtv2',
       'mtv'],
 'w': ['mtwivila', 'mtwapa', 'mtwara', 'mtw'],
 'x': ['mtx1', 'mtx'],
 'z': ['mtz']}
