
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mh = {'_': ['mh-1a', 'mh4'],
 'a': ['mhainamtsi',
       'mhaimbhat',
       'mhasawad',
       'mhallami',
       'mhachkay',
       'mhaydseh',
       'mhangura',
       'mhaismal',
       'mhadalem',
       'mhasurne',
       'mhaireth',
       'mhadjeb',
       'mhaikam',
       'mhaswad',
       'mhasoba',
       'mhakave',
       'mhasane',
       'mhande',
       'mhasla',
       'mhapan',
       'mhango',
       'mhasad',
       'mhairi',
       'mhacks',
       'mhalsa',
       'mhac',
       'mhai',
       'mha'],
 'c': ['mhc'],
 'd': ['mhdys', 'mhd'],
 'e': ['mhendhan',
       'mheibes',
       'mhealth',
       'mhetase',
       'mheg-5',
       'mheer',
       'mhere',
       'mhezi',
       'mher',
       'mhe'],
 'g': ['mhg'],
 'h': ['mhhs', 'mhh'],
 'i': ['mhi'],
 'k': ['mhk'],
 'l': ['mhlambanyatsi',
       'mhlangatane',
       'mhlangeni',
       'mhlangana',
       'mhlosheni',
       'mhlumeni',
       'mhlongo',
       'mhluzi',
       'mhlume',
       'mhl'],
 'm': ['mhmr', 'mhms', 'mhm'],
 'n': ['mhnp', 'mhn'],
 'o': ['mhowgaon', 'mhorkya', 'mhow', 'mho'],
 'p': ['mhp'],
 'q': ['mhq'],
 'r': ['mhra', 'mhr'],
 's': ['mhsnet', 'mhsaa', 'mhsc', 'mhsi', 'mhsa', 'mhs'],
 't': ['mhtml', 'mht'],
 'u': ['mhuire', 'mhudi', 'mhu'],
 'v': ['mhv'],
 'w': ['mhw-rtg'],
 'x': ['mhx'],
 'y': ['mhysa']}
