
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_md = {'_': ['md5deep',
       'md-phd',
       'md5sum',
       'md5crk',
       'md.45',
       'md&di',
       'md-4',
       'md-5',
       'md-6',
       'md6',
       'md4',
       'md3',
       'md7',
       'md5',
       'md2'],
 'a': ['mda-mb-453',
       'mda-mb-468',
       'mdantsane',
       'mdaemon',
       'mda-19',
       'mdandu',
       'mdadm',
       'mdat',
       'mdai',
       'mdax',
       'mda5',
       'mda'],
 'b': ['mdb'],
 'c': ['mdcc-arena',
       'mdc-1200',
       'mdcalc',
       'mdc08',
       'mdc-2',
       'mdch',
       'mdc1',
       'mdca',
       'mdcc',
       'mdc'],
 'd': ['mdd2', 'mdds', 'mddl', 'mdd'],
 'e': ['mdewakanton', 'mde-sahani', 'mdea', 'mdef', 'mde'],
 'f': ['mdfmk', 'mdfi', 'mdf'],
 'g': ['mdgrape-4', 'mdga2'],
 'h': ['mdhila', 'mdhc', 'mdhs', 'mdhp', 'mdh1', 'mdh'],
 'i': ['mdivani',
       'mdimba',
       'mdina',
       'mditv',
       'mdia1',
       'mdisc',
       'mdis',
       'mdia',
       'mdi'],
 'j': ['mdjankagnoi', 'mdjouezi', 'mdjoyezi', 'mdj'],
 'k': ['mdk-2m', 'mdk2', 'mdk'],
 'l': ['mdluli', 'mdlinx', 'mdlp', 'mdl'],
 'm': ['mdmb-4en-pinaca',
       'mdmb-fubinaca',
       'mdmb-chminaca',
       'mdmb-chmica',
       'mdmb-fubica',
       'mdmat',
       'mdmai',
       'mdmar',
       'mdma',
       'mdmf',
       'mdm2',
       'mdm4',
       'mdmp',
       'mdmx',
       'mdm'],
 'n': ['mdn1', 'mdna', 'mdnx', 'mdn'],
 'o': ['mdoukha', 'mdos', 'mdot', 'mdoc', 'mdop', 'mdo'],
 'p': ['mdphp', 'mdpi', 'mdp'],
 'q': ['mdq'],
 'r': ['mdr-literaturpreis', 'mdrc', 'mdra', 'mdr3', 'mdr'],
 's': ['mdsave', 'mds-1', 'mdsp', 'mdsc', 'mdsd', 'mds'],
 't': ['mdta', 'mdt'],
 'u': ['mdundonyi', 'mdundiko', 'mdu'],
 'v': ['mdvanii', 'mdvip', 'mdv'],
 'x': ['mdx-1097', 'mdx'],
 'y': ['mdynamix', 'mdy'],
 'z': ['mdzimure', 'mdzewko', 'mdzewo', 'mdz']}
