
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ml = {'_': ['ml2-sa1', 'ml-si3', 'ml-sa1', 'ml-154', 'ml.net', 'ml-1', 'ml/i'],
 'a': ['mladeskovici',
       'mladejovice',
       'mladosevica',
       'mladosovice',
       'mladonovice',
       'mladeskovci',
       'mladenovic',
       'mlaschagna',
       'mladenovac',
       'mlangarini',
       'mladorossi',
       'mlamolovo',
       'mlae-2011',
       'mladinovo',
       'mladenovo',
       'mlajtinci',
       'mlatisuma',
       'mladezhko',
       'mlae-2009',
       'mladotice',
       'mlazovice',
       'mladejov',
       'mladecko',
       'mladenov',
       'mlandege',
       'mladzovo',
       'mlangali',
       'mlappara',
       'mlangeni',
       'mlaciste',
       'mladovo',
       'mladkov',
       'mladica',
       'mladost',
       'mladina',
       'mladek',
       'mladje',
       'mladec',
       'mlambo',
       'mlakva',
       'mlanca',
       'mladen',
       'mlakar',
       'mlabri',
       'mlava',
       'mlake',
       'mladz',
       'mlaka',
       'mlada',
       'mlali',
       'mlace',
       'mlawa',
       'mlana',
       'mlan',
       'mlah',
       'mlat',
       'mlab',
       'mla'],
 'b': ['mlb.com'],
 'c': ['mlcommons', 'mlcc', 'mlc1', 'mlc'],
 'd': ['mldesigner', 'mldonkey', 'mld'],
 'e': ['mlekominci',
       'mlekovita',
       'mlekojedy',
       'mleczowka',
       'mlekosrby',
       'mlechevo',
       'mlechino',
       'mleczkow',
       'mlescevo',
       'mleczewo',
       'mleczna',
       'mleczko',
       'mlecice',
       'mleccha',
       'mlewiec',
       'mleczno',
       'mlegwa',
       'mleiha',
       'mlesna',
       'mlecze',
       'mlecva',
       'mlecin',
       'mlewo',
       "mle'a",
       'mlete',
       'mleh',
       'mle'],
 'f': ['mlf1ip', 'mlf1', 'mlf'],
 'g': ['mlgb', 'mlg'],
 'h': ['mlhlnd', 'mlh1', 'mlhs', 'mlh3', 'mlh'],
 'i': ['mlice-kostery',
       'mliniste',
       'mlinaric',
       'mlinsko',
       'mlibizi',
       'mlimani',
       'mlilot',
       'mlimba',
       'mlinci',
       'mlinse',
       'mli-84',
       'mlinar',
       'mlini',
       'mliba',
       'mlikh',
       'mlisp',
       'mliha',
       'mlia',
       'mlis',
       'mlip',
       'mlik',
       'mli'],
 'j': ['mljet', 'mlj'],
 'k': ['mlk/fbi'],
 'l': ['mllt10', 'mllt1', 'mllt6', 'mllt3', 'mll4', 'mll'],
 'm': ['mlma', 'mlm'],
 'n': ['mln-29', 'mln'],
 'o': ['mlodojewo-parcele',
       'mlotkowo-kolonia',
       'mlodzieszynek',
       'mlotkowo-wies',
       'mlodziejewice',
       'mlock-kopacze',
       'mlodziejowice',
       'mlokhim-bukh',
       'mlodzikowice',
       'mlodoszowice',
       'mlodzieszyn',
       'mlodzikowko',
       'mlodzianow',
       'mlodzinava',
       'mlotkowice',
       'mlodzikowo',
       'mlodziejow',
       'mloteczno',
       'mlodojewo',
       'mlodowice',
       'mlodochow',
       'mlogoszyn',
       'mlodolino',
       'mlotkowko',
       'mlodnice',
       'mlolongo',
       'mlodasko',
       'mlokicie',
       'mlotkowo',
       'mlodocin',
       'mloszowa',
       'mlodynin',
       'mlosina',
       'mloszow',
       'mlochow',
       'mlodnik',
       'mlonda',
       'mlodat',
       'mlomp',
       'mlops',
       'mlock',
       'mlowo',
       'mloty',
       'mlowa',
       'mlo'],
 'p': ['mlpack', 'mlp-3', 'mlpy', 'mlpa', 'mlps', 'mlpc', 'mlp'],
 'q': ['mlq'],
 'r': ['mlr'],
 's': ['mlstd2', 'mlst8', 'mlse', 'mlsa'],
 't': ['mlton', 'mltr', 'mlt'],
 'u': ['mlunduzi', 'mlungisi', 'mludzyn', 'mlusa', 'mlu'],
 'v': ['mlvm', 'mlv'],
 'w': ['mlwin', 'mlw'],
 'x': ['mlx'],
 'y': ['mlyny-wybudowanie',
       'mlynczysko',
       'mlynkowiec',
       'mlynarczyk',
       'mlynarovce',
       'mlynczyska',
       'mlynowiec',
       'mlynarski',
       'mlynceky',
       'mlynisko',
       'mlynarki',
       'mlynkowo',
       'mlyniska',
       'mlynica',
       'mlynice',
       'mlynisk',
       'mlyniec',
       'mlynary',
       'mlynsko',
       'mlynowo',
       'mlynow',
       'mlynky',
       'mlynek',
       'mlyniv',
       'mlynka',
       'mlynar',
       'mlynik',
       'mlynki',
       'mlyny',
       'mly']}
