
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_wq = {'a': ['wqaz-lp',
       'wqaw-ld',
       'wqad-tv',
       'wqah-fm',
       'wqal',
       'wqab',
       'wqac',
       'wqak',
       'wqar',
       'wqaq',
       'wqam'],
 'b': ['wqbe-fm',
       'wqbk-fm',
       'wqbh-lp',
       'wqbs-fm',
       'wqbr',
       'wqbq',
       'wqbn',
       'wqbt',
       'wqbz',
       'wqbc',
       'wqbk',
       'wqba',
       'wqbg',
       'wqbs',
       'wqbx',
       'wqb'],
 'c': ['wqcn-lp',
       'wqcc',
       'wqcw',
       'wqcb',
       'wqcp',
       'wqch',
       'wqct',
       'wqcy',
       'wqcm',
       'wqcr',
       'wqck',
       'wqcs',
       'wqcd'],
 'd': ['wqdh-ld',
       'wqdy-fm',
       'wqdd-lp',
       'wqdi-ld',
       'wqdr-fm',
       'wqde-ld',
       'wqdt-ld',
       'wqdc',
       'wqdk',
       'wqdr'],
 'e': ['wqed_multimedia'],
 'f': ['wqfl-ca',
       'wqfx-fm',
       'wqfr-lp',
       'wqfb-lp',
       'wqfs',
       'wqfx',
       'wqfm',
       'wqfl'],
 'g': ['wqgn-fm', 'wqga', 'wqgr'],
 'h': ['wqhs_radio'],
 'i': ['wqik-fm', 'wqid-lp', 'wqiz', 'wqix', 'wqil', 'wqii', 'wqio'],
 'j': ['wqjj-lp', 'wqjc-lp', 'wqjq', 'wqjs', 'wqjz'],
 'k': ['wqks-fm',
       'wqka-lp',
       'wqki-fm',
       'wqkq',
       'wqkx',
       'wqky',
       'wqkz',
       'wqkr',
       'wqkc',
       'wqke',
       'wqkl',
       'wqkt'],
 'l': ['wqln-fm',
       'wqlt-fm',
       'wqlf',
       'wqlj',
       'wqlz',
       'wqle',
       'wqlk',
       'wqli',
       'wqlq',
       'wqln',
       'wqla',
       'wqlv',
       'wqll',
       'wqlb',
       'wqlx',
       'wqlc',
       'wqlh',
       'wqlr',
       'wqlu',
       'wqls',
       'wql'],
 'm': ['wqmc-ld',
       'wqmr-lp',
       'wqmt',
       'wqmu',
       'wqmz',
       'wqma',
       'wqms',
       'wqmp',
       'wqme',
       'wqmr',
       'wqml',
       'wqmj',
       'wqmf',
       'wqmg',
       'wqmx',
       'wqmv',
       'wqmy'],
 'n': ['wqnh-lp',
       'wqny',
       'wqns',
       'wqnx',
       'wqnt',
       'wqnq',
       'wqnu',
       'wqno',
       'wqnz',
       'wqnr'],
 'o': ['wqos-lp',
       'wqom',
       'wqos',
       'wqox',
       'wqor',
       'wqoh',
       'wqol',
       'wqon',
       'wqok',
       'wqof',
       'wqop',
       'wqow'],
 'p': ['wqpt-tv', 'wqpx-tv', 'wqpo', 'wqpm', 'wqpw', 'wqph', 'wqpc', 'wqpd'],
 'q': ['wqqo', 'wqqq', 'wqqb', 'wqql', 'wqqp', 'wqqk', 'wqqw'],
 'r': ['wqrz-lp',
       'wqrf-tv',
       'wqrp',
       'wqrl',
       'wqrt',
       'wqrc',
       'wqrv',
       'wqrr',
       'wqrm',
       'wqri',
       'wqrb',
       'wqrw',
       'wqrs',
       'wqrk'],
 's': ['wqsv-lp',
       'wqsb',
       'wqsl',
       'wqsn',
       'wqsi',
       'wqsc',
       'wqst',
       'wqss',
       'wqsr',
       'wqso',
       'wqsm',
       'wqsh',
       'wqsv',
       'wqsu'],
 't': ['wqtc-fm',
       'wqtr-lp',
       'wqtz-lp',
       'wqtx',
       'wqty',
       'wqtm',
       'wqtl',
       'wqte',
       'wqtq',
       'wqts',
       'wqtu',
       'wqtk'],
 'u': ['wque-fm', 'wqud', 'wqua', 'wqul', 'wqus', 'wqut', 'wqub'],
 'v': ['wqvc-cd', 'wqvn', 'wqve'],
 'w': ['wqwq-ld', 'wqwk', 'wqwv'],
 'x': ['wqxc-fm',
       'wqxd-lp',
       'wqxt-cd',
       'wqxa-fm',
       'wqxr-fm',
       'wqxb',
       'wqxk',
       'wqxe',
       'wqxl',
       'wqxz',
       'wqxo',
       'wqxr',
       'wqxy',
       'wqxm',
       'wqxw',
       'wqxi'],
 'y': ['wqyk-fm', 'wqyq', 'wqyz', 'wqyk'],
 'z': ['wqzk-fm', 'wqzs', 'wqzq', 'wqzl', 'wqzz', 'wqzx', 'wqzy']}
