
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rv = {'_': ['rv_investigator',
       'rv_coefficient',
       'rv_andromedae',
       'rv_polarstern',
       'rv_mirabilis',
       'rv_sprightly',
       'rv_tangaroa',
       'rv_cirolana',
       'rv_atlantis',
       'rv_bernicia',
       'rv_corystes',
       'rv_platessa',
       'rv_franklin',
       'rv_sikuliaq',
       'rv_zeeleeuw',
       'rv_callista',
       'rv_endeavor',
       'rv_corella',
       'rv_belgica',
       'rv_calypso',
       'rv_tellina',
       'rv_bilim-2',
       'rv_vantuna',
       'rv_horizon',
       'rv_derinsu',
       'rv_pelican',
       'rv_oceanus',
       'rv_oceania',
       'rv_pelagia',
       'rv_onnuri',
       'rv_falkor',
       'rv_huxley',
       'rv_onaway',
       'rv_zephyr',
       'rv_wecoma',
       'rv_petrel',
       'rv_clione',
       'rv_triton',
       'rv_caeli',
       'rv_sonne',
       'rv_tauri',
       'rv_mirai',
       'rv_araon',
       'rv_tioga',
       'rv_corvi',
       'rv_atair',
       'rv_knorr',
       'rv_hero',
       'rv_argo',
       'rv_park',
       'rv_144'],
 'a': ['rvachev_function', 'rva_magazine'],
 'b': ['rvb'],
 'c': ['rvca', 'rvc'],
 'd': ['rvd-hpa'],
 'e': ['rveeh', 'rve'],
 'f': ['rvf'],
 'g': ['rvg'],
 'h': ['rvhs', 'rvh'],
 'i': ['rvivr', 'rvi'],
 'k': ['rvk_studios'],
 'l': ['rvl_aviation'],
 'm': ['rvmagnetics', 'rvm'],
 'n': ['rvng_intl.'],
 'o': ['rvo'],
 'p': ['rvp'],
 'r': ['rvr'],
 's': ['rvsv-zebov_vaccine', 'rvs_eyewear', 'rvs_tukoro', 'rvs_iii'],
 't': ['rvt-802', 'rvt'],
 'u': ['rvu_protocol', 'rvu_alliance'],
 'v': ['rvvh', 'rvv'],
 'w': ['rvw'],
 'x': ['rvxp_motif'],
 'y': ['rvy']}
