
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ui = {'_': ['ui-te-rangiora', 'ui-dong'],
 'a': ['uiallalla', 'uiagm', 'uia'],
 'b': ['uibujarve', 'uibaresti', 'uibopuu', 'uibai', 'uibis', 'uibo', 'uib'],
 'c': ['uichang-gu', 'uichteritz', 'uicheon', 'uicc', 'uic'],
 'd': ['uidemar', 'uid'],
 'e': ['uie'],
 'f': ['uif'],
 'g': ['uigshader', 'uigeumbu', 'uigwe', 'uige', 'uig'],
 'h': ['uihlein'],
 'i': ['uii'],
 'j': ['uijeongbu', 'uijuro', 'uijin'],
 'k': ['uikala'],
 'l': ['uilenburgergracht',
       'uilenkraalsmond',
       'uilliams',
       'uilleam',
       'uileacu',
       'uilson',
       'uila',
       'uil'],
 'm': ['uimc1', 'uimid', 'uimx', 'uims', 'uima', 'uiml', 'uim'],
 'n': ['uintatheriidae',
       'uintascorpio',
       'uintatherium',
       'uintacrinus',
       'uintaceras',
       'uintasorex',
       'uintacyon',
       'uinskoye',
       'uintan',
       'uinyeo',
       'uinsky',
       'uinta',
       'uin'],
 'p': ['uipath', 'uipi', 'uip'],
 'q': ['uiq'],
 'r': ['uiramuta',
       'uirapuru',
       'uirauna',
       'uirassu',
       'uirne',
       'uirr',
       'uiro',
       'uir'],
 's': ['uiseong-eup',
       'uissigheim',
       'uiscedwr',
       'uisdean',
       'uisang',
       'uisken',
       'uisun',
       'uise',
       'uist',
       'uisd',
       'uis'],
 't': ['uittamo-skanssi',
       'uithuizermeeden',
       'uitwellingerga',
       'uittenbogaard',
       'uitwierde',
       'uitlander',
       'uithuizen',
       'uitmsat-1',
       'uitenhage',
       'uittienia',
       'uitgeest',
       'uithoorn',
       'uitmarkt',
       'uitvlugt',
       'uitkerke',
       'uitikon',
       'uitumen',
       'uittamo',
       'uitwijk',
       'uitkijk',
       'uitkoms',
       'uitdam',
       'uitweg',
       'uits',
       'uit'],
 'u': ['uiu'],
 'v': ['uivar'],
 'w': ['uiwang'],
 'y': ['uiya']}
