
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uh = {'_': ['uh-uh-uh', 'uh-ohhh!', 'uh-huh', 'uh-232', 'uh-301', 'uh-ee', 'uh88'],
 'a': ['uharte-arakil',
       'uhart-mixe',
       'uhart-cize',
       'uhaitxa',
       'uhabia',
       'uhaitz',
       'uhana',
       'uha'],
 'b': ['uhb'],
 'c': ['uhc2030', 'uhcc', 'uhc'],
 'd': ['uhde', 'uhd'],
 'e': ['uhercice', 'uhersko', 'uhehlia', 'uherce', 'uhelna', 'uher', 'uhe'],
 'g': ['uhg'],
 'h': ['uhha-ziti', 'uhh'],
 'i': ['uhikarotid', 'uhiaguri', 'uhingen', 'uhila', 'uhid', 'uhi'],
 'k': ['uhkd', 'uhk'],
 'l': ['uhlingen-birkendorf',
       'uhldingen-muhlhofen',
       'uhlstadt-kirchhasel',
       'uhlenkrugstadion',
       'uhlorchestia',
       'uhlakanyana',
       'uhlandshohe',
       'uhlenhorst',
       'uhleriola',
       'uhlenbach',
       'uhligella',
       'uhligites',
       'uhlovitsa',
       'uhlwiller',
       'uhlenburg',
       'uhlenbeck',
       'uhlemann',
       'uhlsport',
       'uhliska',
       'uhlmann',
       'uhligia',
       'uhlanga',
       'uhlejov',
       'uhlirov',
       'uhlberg',
       'uhlich',
       'uhlava',
       'uhland',
       'uhler',
       'uhlen',
       'uhlig',
       'uhlan',
       'uhle',
       'uhl'],
 'm': ['uhmardu', 'uhmk1', 'uhm'],
 'n': ['uhniv', 'uhnin', 'uhna', 'uhn'],
 'o': ['uholicky',
       'uhorilka',
       'uhornyky',
       'uhonice',
       'uhotici',
       'uhorske',
       'uhogua',
       'uhorna',
       'uhost',
       'uhowo',
       'uho'],
 'p': ['uhp'],
 'q': ['uhq'],
 'r': ['uhrturmchen',
       'uhrynkivtsi',
       'uhrsleben',
       'uhrwiller',
       'uhrenkopf',
       'uhritulet',
       'uhrencup',
       'uhretice',
       'uhricice',
       'uhryniv',
       'uhroidy',
       'uhrovec',
       'uhrinov',
       'uhrich',
       'uhrusk',
       'uhrice',
       'uhrf1',
       'uhryn',
       'uhrf2',
       'uhryb',
       'uhrig',
       'uhre',
       'uhry'],
 's': ['uhsapw', 'uhse', 'uhsn', 'uhss', 'uhs'],
 't': ['uhtjarve',
       'uhtjarv',
       'uhthoff',
       'uhtred',
       'uhtrex',
       'uhtna',
       'uhtri',
       'uhti'],
 'u': ['uhunmwonde', 'uhudler', 'uhuru', 'uhub', 'uhu'],
 'v': ['uhv'],
 'w': ['uhwudong'],
 'y': ['uhyst', 'uhy']}
