
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uk = {'_': ['uk-432,097', 'uk-414,495', 'uk-dmc'],
 'a': ['ukabazumorezu',
       'ukanomitama',
       'ukaliqtuuq',
       'ukay-ukay',
       'ukanafun',
       'ukarumpa',
       'ukamenia',
       'ukactive',
       'ukaidam',
       'ukagaka',
       'ukasan',
       'ukamau',
       'ukanje',
       'ukams',
       'ukays',
       'ukanc',
       'ukash',
       'ukase',
       'ukala',
       'ukai',
       'ukan',
       'ukaf',
       'ukal',
       'ukah',
       'uka'],
 'b': ['ukbara', 'ukba', 'ukb'],
 'c': ['ukchartsplus', 'ukcloud', 'ukccsg', 'ukcc', 'ukc'],
 'd': ['ukdomains', 'ukdungle'],
 'e': ['ukerevyen',
       'ukemochi',
       'uke-hunt',
       'ukelayat',
       'ukerewe',
       'ukelin',
       'ukehi',
       'ukeep',
       'ukek',
       'ukee',
       'uken',
       'ukeu',
       'uke'],
 'f': ['ukfast', 'ukf'],
 'g': ['ukgameshows.com', 'ukg'],
 'h': ['ukhaatherium',
       'ukhtoceras',
       'ukhtomsky',
       'ukholovo',
       'ukhimath',
       'ukhtanga',
       'ukhalad',
       'ukhunda',
       'ukhtoma',
       'ukhot40',
       'ukhrul',
       'ukhtym',
       'ukhati',
       'ukhrid',
       'ukhov',
       'ukhta',
       'ukhra',
       'ukhul',
       'ukha'],
 'i': ['ukiyo-zoshi',
       'ukiyoburo',
       'ukininkas',
       'ukiernica',
       'ukishima',
       'ukiyotei',
       'ukiyo-e',
       'ukifune',
       'ukigumo',
       'ukiyaz',
       'ukilla',
       'ukina',
       'ukiyo',
       'uki-e',
       'ukita',
       'ukiah',
       'ukiam',
       'uki'],
 'k': ['ukkirasinghan',
       'ukkulankulam',
       'ukkusissat',
       'ukkadam',
       'ukkadai',
       'ukkonen',
       'ukkali',
       'ukkola',
       'ukkin',
       'ukko',
       'ukka',
       'ukk'],
 'l': ['uklonskovite',
       'uklejnica',
       'ukleisee',
       'uklejka',
       'uklejki',
       'ukleja',
       'ukla',
       'ukl'],
 'm': ['ukm-2000', 'ukmerge', 'ukman', 'ukma'],
 'n': ['uknowhowwedu', 'uknof', 'uknc', 'ukn'],
 'o': ['ukonvasara',
       'ukozyash',
       'ukonkivi',
       'ukonline',
       'ukonvesi',
       'ukonga',
       'ukojas',
       'ukoln',
       'ukobu',
       'ukodo',
       'ukon'],
 'p': ['ukpe-okhue',
       'ukpong',
       'ukpass',
       'ukpsf',
       'ukpor',
       'ukpa',
       'ukps',
       'ukp'],
 'r': ['ukrgasvydobuvannya',
       'ukrpovitroshliakh',
       'ukrhydroenergo',
       'ukrspetsexport',
       'ukrinterenergo',
       'ukroboronprom',
       'ukrainization',
       'ukrainophilia',
       'ukraineinvest',
       'ukrecoresursy',
       'ukrtransnafta',
       'ukrainskoye',
       'ukrautoprom',
       'ukrsotsbank',
       'ukranenland',
       'ukrtatnafta',
       'ukrtelecom',
       'ukrainskiy',
       'ukrahrokom',
       'ukrainurus',
       'ukrainians',
       'ukrkosmos',
       'ukrayiner',
       'ukrposhta',
       'ukrainian',
       'ukrinform',
       'ukrainsky',
       'ukrainka',
       'ukrupata',
       'ukrferry',
       'ukrnafta',
       'ukrainsk',
       'ukrinai',
       'ukraine',
       'ukrain',
       'ukrina',
       'ukrani',
       'ukrop',
       'ukrah',
       'ukrid',
       'ukrc',
       'ukra'],
 's': ['uksnurme',
       'ukscblog',
       'uksichan',
       'uksunay',
       'uksunny',
       'uksici',
       'uksg',
       'uksc',
       'uksw',
       'uksa'],
 't': ['uktenadactylus', 'uktaspis', 'ukteyevo', 'uktzim', 'uktv', 'ukta'],
 'u': ['ukulan-tojon',
       'ukuthwalwa',
       'ukungenwa',
       'ukupanipo',
       'ukupseni',
       'ukumari',
       'ukuwela',
       'ukuroba',
       'ukulele',
       'ukulhas',
       'ukusoma',
       'ukujima',
       'ukutule',
       'ukuwala',
       'ukunda',
       'ukuma',
       'ukush',
       'ukuda',
       'ukula',
       'ukuug',
       'ukuz',
       'ukur',
       'ukum',
       'uku'],
 'v': ['ukvisas'],
 'w': ['ukwulu', 'ukwa', 'ukwi'],
 'y': ['ukyo', 'ukyr'],
 'z': ['ukz']}
