
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ua = {'_': ['ua-football', 'ua:kultura', 'ua:first', 'ua-ildak', 'ua120'],
 'a': ['uaa'],
 'b': ['uabc', 'uaba'],
 'c': ['uachdar', 'uacaba', 'uaces', 'uach', 'uaca', 'uacv', 'uac'],
 'd': ['uad'],
 'f': ['uafato', 'uafa', 'uaf'],
 'g': ['uag'],
 'h': ['uahuka', 'uahs', 'uah'],
 'i': ['uaipan-tepui',
       'uaitemuri',
       'uaithne',
       'uaithni',
       'uaiuara',
       'uaioe',
       'uaica',
       'uair',
       'uai'],
 'j': ['uaj'],
 'k': ['uakitite', 'uakari', 'uakit', 'uakti', 'uak'],
 'l': ['ualalapi', 'uallach', 'ualefi', 'uala', 'ual'],
 'm': ['uamsan', 'uamsho', 'uamba', 'uamc', 'uams', 'uam'],
 'n': ['uanda', 'uan'],
 'p': ['uapsat-1', 'uaprof', 'uapaca', 'uapila', 'uapou', 'uap1', 'uap'],
 'q': ['uaq'],
 'r': ['uarbryichthys', 'uarini', 'uardry', 'uaroo', 'uars', 'uaru'],
 's': ['uastyrdzhi',
       'uashat',
       'uasal',
       'uasd',
       'uas7',
       'uasp',
       'uasc',
       'uasa',
       'uas'],
 't': ['uatchitodon', 'uathach', 'uath', 'uatv', 'uatu', 'uat'],
 'u': ['uaua', 'uau'],
 'v': ['uavision', 'uavcan'],
 'x': ['uaxactun'],
 'y': ['uaymil', 'uayma', 'uay'],
 'z': ['uaz-452', 'uaz-469', 'uaz']}
