
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-19T14:31:13+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "779e62f3f677de5cebc9b8646f6356865054a8c6",
 "version": "0.29.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
