
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pb = {'_': ['pb.db_the_mixtape', 'pb-32_quetta_ix', 'pb_swiss_tools'],
 'a': ['pba_reinforced_conference',
       'pba_players_championship',
       'pba_developmental_league',
       'pba_all-defensive_team',
       'pba_world_championship',
       "pba_commissioner's_cup",
       'pba_fiesta_conference',
       'pba_third_conference',
       'pba_open_conference',
       'pba_all-rookie_team',
       'pba_philippine_cup',
       "pba_women's_series",
       "pba_governors'_cup",
       'pba_tour_playoffs',
       'pba_regional_tour',
       'pba_mythical_team',
       "pba_women's_3x3",
       'pbao_chouk_sao',
       'pba_on_nbn/ibc',
       'pba_on_espn',
       'pba_on_mbs',
       'pba_on_usa',
       'pba_on_kbs',
       'pba_on_bbc',
       'pba_on_fox',
       'pba_on_abc'],
 'c': ['pbc_lokomotiv_kuban', 'pbc_cska_moscow', 'pbc_cska_junior'],
 'g': ['pbg_basket_poznan'],
 'n': ['pbn_broadcasting_network'],
 'r': ['pbr_global_cup', 'pbr_world_cup'],
 's': ['pbs_satellite_service',
       'pbsc_urban_solutions',
       'pbs_digital_studios',
       'pbs_north_carolina',
       'pbs_velka_bites',
       'pbs_kids_go!']}
