
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pc = {'_': ['pc-461-class_submarine_chaser',
       'pc-flight_pretty_flight',
       'pc_building_simulator',
       'pc_music_discography',
       'pc/tcp_packet_driver',
       'pc&y_railroad_bridge',
       'pc_engine_supergrafx',
       'pc_david_copperfield',
       'pc_transport_systems',
       'pc-aero_elektra_one',
       'pc_power_management',
       'pc_jabin_college',
       'pc_weasel_2000',
       'pc_screen_font',
       'pc_load_letter',
       'pc_master_race',
       'pc12_cell_line',
       'pc_engine_fan',
       'pc_futbol_5.0'],
 'b': ['pcb_reverse_engineering',
       'pcb_congener_list',
       'pcb_nc_formats',
       'pcb_drill_file'],
 'c': ['pcc_community_markets', 'pcc_rail_tabor'],
 'd': ['pcd_world_tour'],
 'e': ['pce-842-class_patrol_craft'],
 'h': ['pchelarovo,_kardzhali_province',
       'pchelarovo,_dobrich_province',
       'pchelnik,_dobrich_province',
       'pchelin,_burgas_province'],
 'i': ['pci_configuration_space', 'pci_mezzanine_card'],
 'm': ['pcmc_hockey_stadium', 'pcman_file_manager'],
 'o': ['pco_judges_case'],
 'p': ['pcp_site_2'],
 'r': ['pcr_food_testing'],
 's': ['pcso_lottery_draw'],
 'v': ['pcvc_speech_dataset']}
