
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pn = {'b': ['pnb_rock_discography'],
 'c': ['pnc_financial_services', 'pnc_music_pavilion', 'pnc_bank_building'],
 'e': ['pneumococcal_polysaccharide_vaccine',
       'pneumococcal_conjugate_vaccine',
       'pneumatic_stabilized_platform',
       'pneumatic_exercise_equipment',
       'pneumatic_artificial_muscles',
       'pneumatic_non-return_valve',
       'pneumonia_severity_index',
       'pneumatic_valve_springs',
       'pneumatic_line_thrower',
       'pneumothorax_ex_vacuo',
       'pneumatic_web_guides'],
 'g': ['png_conservative_party',
       'png_football_stadium',
       'png_country_party',
       'png_labour_party',
       'png_eng_huat'],
 'i': ['pniewy,_kuyavian-pomeranian_voivodeship',
       'pniewo,_warmian-masurian_voivodeship',
       'pniaki,_swietokrzyskie_voivodeship',
       'pniow,_podkarpackie_voivodeship',
       'pniowek,_silesian_voivodeship',
       'pniewo,_podlaskie_voivodeship',
       'pniewy,_masovian_voivodeship',
       'pnie,_pomeranian_voivodeship',
       'pniow,_silesian_voivodeship',
       'pniowek,_lublin_voivodeship',
       'pnie,_masovian_voivodeship',
       'pniewko,_lodz_voivodeship',
       'pniow,_lubusz_voivodeship',
       'pniewo,_gmina_miedzyrzecz',
       'pniewo,_lodz_voivodeship',
       'pniewko,_gryfino_county',
       'pniewko,_gryfice_county',
       'pniewo,_gryfino_county',
       'pniewo,_gryfice_county',
       'pniewo,_pultusk_county',
       'pniewo,_gmina_bledzew',
       'pniewo,_zlotow_county',
       'pniel,_northern_cape',
       'pniewo,_kolo_county',
       'pniel,_south_africa',
       'pni_digital_media',
       'pniowek_coal_mine',
       'pnina_moed_kass'],
 'p': ['pnp_lady_patrollers'],
 'r': ['pnr_em10000_class',
       'pnr_5000_class',
       'pnr_8000_class',
       'pnr_2500_class',
       'pnr_8300_class',
       'pnr_8100_class',
       'pnr_900_class'],
 's': ['pns_rahat_hospital',
       'pns_shifa_hospital',
       'pns_mehran_attack',
       'pns_tippu_sultan',
       'pns_rah_naward',
       'pns_behr_paima',
       'pns_shah_jahan'],
 'v': ['pnvf_champions_league'],
 'w': ['pnw_wrestling_extravaganza']}
