
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uy = {'_': ['uy-salgan'],
 'a': ['uyarndhavargal',
       'uyazybashevo',
       'uyarangalil',
       'uyazytamak',
       'uyarapulam',
       'uyandykovo',
       'uyadybash',
       'uyandina',
       'uyarani',
       'uyankul',
       'uyalovo',
       'uyarra',
       'uyanik',
       'uyandi',
       'uyaquq',
       'uyare',
       'uyady',
       'uyar',
       'uyai',
       'uyas',
       'uya'],
 'b': ['uybulatovo'],
 'c': ['uychi'],
 'd': ['uydenia', 'uydo'],
 'e': ['uyeasound', 'uyemsky', 'uyench', 'uyea'],
 'g': ['uyghuristan', 'uyghurlar', 'uyg`ursoy', 'uyghurs', 'uyghur', 'uygun'],
 'i': ['uyirthezhunnelppu',
       'uyilankulam',
       'uyirmei',
       'uyil',
       'uyir',
       'uyin',
       'uyi'],
 'l': ['uylenburgh', 'uylak'],
 'm': ['uymen'],
 'n': ['uynehchi', 'uynarey'],
 'o': ['uyole', 'uyo'],
 's': ['uyskoye', 'uysal', 'uyshu', 'uysky', 'uys'],
 't': ['uytenbogaardtite', 'uyttersprot', 'uyts', 'uyta'],
 'u': ['uyunqimg', 'uyugan', 'uyuni', 'uyuk', 'uyu'],
 'v': ['uyvayka'],
 'w': ['uywa'],
 'y': ['uyyakondaravi', 'uyyalawada', 'uyyale']}
