
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uu = {'_': ['uu-a-thluk'],
 'c': ['uucp', 'uuc'],
 'd': ['uudekula', 'uudibe', 'uudam'],
 'e': ['uue-saaluse',
       'uue-kariste',
       'uuemererahu',
       'uuencoding',
       'uue-antsla',
       'uuemaarahu',
       'uueveski',
       'uuevalja',
       'uuemoisa',
       'uuesalu',
       'uuearu',
       'uuemaa',
       'uue'],
 'g': ['uugla', 'uug'],
 'h': ['uuhraah!', 'uuhash'],
 'i': ['uuijeong'],
 'k': ['uukwaluudhi', 'uukwangali', 'uukuniemi', 'uukwambi', 'uukkivi'],
 'l': ['uulutilaid', 'uulu'],
 'm': ['uummannaarsuk',
       'uummarmiutun',
       'uummarmiut',
       'uummannaq',
       'uumaa',
       'uum'],
 'n': ['uunijuusto', 'uunarteq', 'uunet', 'uunsi', 'uuno'],
 'p': ['uup'],
 'r': ['uurainen', 'uurad', 'uuri'],
 's': ['uus-nootamaa',
       'uusikaupunki',
       'uusitaloia',
       'uusivirta',
       'uuskula',
       'uusvada',
       'uusimaa',
       'uuslinn',
       'uusna',
       'uusi'],
 't': ['uutaalnganu',
       'uutisvuoto',
       'uutiset',
       'uutool',
       'uutoni',
       'uutela',
       'uuta'],
 'u': ['uuu'],
 'v': ['uuvudhiya', 'uuvere'],
 'y': ['uuyoka']}
