
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uw = {'a': ['uwantme2killhim?',
       'uwajimaya',
       'uwa-obi',
       'uwanari',
       'uwabaki',
       'uwa-001',
       'uwa-101',
       'uwakai',
       'uwaisi',
       'uways',
       'uwain',
       'uwagi',
       'uwan'],
 'b': ['uwb'],
 'c': ['uwchlan', 'uwc'],
 'e': ['uwemba', 'uwe-2', 'uwe-1', 'uwec', 'uwe'],
 'f': ['uwf'],
 'g': ['uwg'],
 'h': ['uwharrie', 'uwh'],
 'i': ['uwilingiyimana',
       'uwiedziona',
       'uwielinek',
       'uwieliny',
       'uwingu',
       'uwini',
       'uwink',
       'uwire',
       'uwin'],
 'l': ['uwl'],
 'm': ['uwm'],
 'n': ['uwn'],
 'p': ['uwp'],
 'r': ['uwr'],
 's': ['uwsgi', 'uwsp', 'uwsa', 'uws'],
 'u': ['uwu'],
 'w': ['uww']}
