
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ug = {'_': ['ug99'],
 'a': ['ugao-miraballes',
       'ugashik-peulik',
       'ugandapithecus',
       'ugandolaelaps',
       'ugayafukiaezu',
       'ugandaltica',
       'ugandinella',
       'ugartsthal',
       'ugartechea',
       'ugardanti',
       'ugabhoga',
       'ugaritic',
       'ugatusat',
       'ugallery',
       'ugarkhod',
       'ugarchin',
       'ugaragol',
       'ugamedi',
       'ugandax',
       'uga-uga',
       'ugatame',
       'ugashik',
       'ugabhad',
       'ugarit',
       'ugalde',
       'uganik',
       'ugallu',
       'ugalla',
       'ugarci',
       'uganda',
       'ugajin',
       'ugamia',
       'ugarov',
       'ugarte',
       'ugala',
       'ugadi',
       'ugali',
       'ugada',
       'ugaki',
       'ugao',
       'ugal',
       'ugam',
       'uga'],
 'b': ['ugborough', 'ugbokhare', 'ugbrooke', 'ugboba', 'ugbo', 'ugb'],
 'c': ['ugchelen', 'ugcc', 'ugcg', 'ugc'],
 'd': ['ugdh-as1'],
 'e': ['ugetme',
       'ugento',
       'ugeoji',
       'ugetsu',
       'ugena',
       'ugene',
       'ugen',
       'ugep',
       'uge'],
 'f': ['ugf'],
 'g': ['uggleviksreservoaren',
       'uggiate-trevano',
       'uggahakumbura',
       'uggs-n-rugs',
       'ugginakeri',
       'uggleviken',
       'uggerslev',
       'uggletorp',
       'uggeshall',
       'uggdal',
       'uggie',
       'uggla',
       'uggt',
       'uggi',
       'ugg'],
 'h': ['ughedzor',
       'ughaiti',
       'ughoton',
       'ughelli',
       'ughandi',
       'ughill',
       'ughli',
       'ugh!',
       'ughi',
       'ugh'],
 'i': ['ugimeigenia',
       'ugiertowo',
       'ugiodes',
       'ugijar',
       'ugine',
       'ugia',
       'ugis',
       'ugi'],
 'k': ['ugk'],
 'l': ['uglychristmassweater.com',
       'uglerodovsky',
       'ugleuralsky',
       'uglenskaya',
       'uglitskaya',
       'uglentsevo',
       'uglegorsky',
       'uglovskoye',
       'ugljarevac',
       'uglyanets',
       'ugljarevo',
       'ugljesici',
       'uglegorsk',
       'uglydolls',
       'uglichsky',
       'uglydoll',
       'uglovoye',
       'uglovsky',
       'ugljevik',
       'ugljare',
       'ugljara',
       'uglione',
       'ugljesa',
       'uglovka',
       'ugljan',
       'ugljes',
       'uglovo',
       'uglara',
       'uglies',
       'uglich',
       'uglov',
       'uglow',
       'uglem',
       'uglas',
       'ugley',
       'ugly',
       'ugl'],
 'm': ['ugmicrosatdb', 'ugm'],
 'n': ["ugny-l'equipee",
       'ugny-sur-meuse',
       'ugny-le-gay',
       'ugnouas',
       'ugnasay',
       'ugniewo',
       'ugnele',
       'ugnazi',
       'ugny',
       'ugni',
       'ugne',
       'ugna',
       'ugn'],
 'o': ['ugoy-ugoy',
       'ugorelets',
       'ugochukwu',
       'ugolskoye',
       'ugotowani',
       'ugolskaya',
       'ugoszcz',
       'ugorsko',
       'ugogoni',
       'ugolini',
       'ugolsky',
       'ugolino',
       'ugovec',
       'ugolny',
       'ugolki',
       'ugoyan',
       'ugosce',
       'ugory',
       'ugong',
       'ugoff',
       'ugola',
       'ugoki',
       'ugod',
       'ugol',
       'ugo'],
 'p': ['ugp'],
 'r': ['ugryumovskaya',
       'ugrashravas',
       'ugra-karma',
       'ugryumikha',
       'ugryumovo',
       'ugrenovic',
       'ugrinovci',
       'ugrewala',
       'ugrasena',
       'ugryumov',
       'ugrzele',
       'ugrians',
       'ugrupur',
       'ugroza',
       'ugreen',
       'ugress',
       'ugramm',
       'ugrai',
       'ugrak',
       'ugrim',
       'ugrin',
       'ugros',
       'ugric',
       'ugra',
       'ugr'],
 's': ['ugs'],
 't': ['ugtan-unitaire',
       'ugthorpe',
       'ugt2b17',
       'ugt2b10',
       'ugt2b15',
       'ugt1a10',
       'ugt1a4',
       'ugt1a9',
       'ugt1a6',
       'ugt2b4',
       'ugt1a3',
       'ugtaal',
       'ugt2a1',
       'ugt2b7',
       'ugt1a8',
       'ugt1a5',
       'ugt2a2',
       'ugt1a',
       'ugt8',
       'ugt'],
 'u': ['uguressapitiya',
       'uguresapitiya',
       'ugunskrusts',
       'ugunsgreks',
       'ugurb@yli',
       'ugurludag',
       'ugurkoy',
       'uguzevo',
       'ugurlu',
       'uguana',
       'ugunja',
       'ugun',
       'ugur',
       'ugu'],
 'w': ['ugwunagbo', 'ugwuoba', 'ugwueke', 'ugwuele', 'ugweno', 'ugwa', 'ugwu'],
 'y': ['ugyuligmiut', 'ugyek']}
