
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uj = {'a': ['ujaleshwar',
       'ujazd-huby',
       'ujanowice',
       'ujariyaon',
       'ujarulvar',
       'ujalhati',
       'ujazdow',
       'ujalpur',
       'ujarras',
       'ujazdek',
       'ujanik',
       'ujados',
       'ujamaa',
       'ujazd',
       'ujari',
       'ujah',
       'ujan'],
 'b': ['ujbarok', 'ujbuda'],
 'c': ['ujcsanalos', 'ujcov', 'ujc'],
 'd': ['ujdombrad'],
 'e': ['ujescisko-lostowice',
       'ujezdziec',
       'ujezdecek',
       'ujejsce',
       'ujezdec',
       'ujezna',
       'ujedia',
       'ujevic',
       'ujeon',
       'ujezd'],
 'f': ['ujfeherto', 'ujfm'],
 'h': ['ujhartyan', 'ujhani', 'ujhari', 'ujhana'],
 'i': ['ujitawara',
       'ujihara',
       'ujimqin',
       'ujikaji',
       'ujiogba',
       'ujigami',
       'ujilica',
       'ujiraz',
       'ujireg',
       'ujiji',
       'ujina',
       'ujire',
       'ujia',
       'ujir',
       'uji'],
 'j': ['ujjinakoppa',
       'ujjainiya',
       'ujjanatti',
       'ujjelli',
       'ujjain',
       'ujjayi',
       'ujjini'],
 'k': ['ujkigyos', 'ujkovice', 'ujkenez', 'ujker'],
 'l': ['ujlorincfalva',
       'ujlipotvaros',
       'ujlengyel',
       'ujleta',
       'ujlam',
       'ujlak'],
 'm': ['ujmajuridze', 'ujmisht', 'ujme'],
 'n': ['ujnice', 'ujna', 'ujny'],
 'o': ['ujow'],
 'p': ['ujpalota', 'ujpetre', 'ujpest'],
 'r': ['ujrzanow', 'ujronafo'],
 's': ['ujszentmargita',
       'ujszentivan',
       'ujscie-leg',
       'ujszalonta',
       'ujszilvas',
       'ujszasz',
       'ujsolt',
       'ujsoly',
       'ujscie'],
 't': ['ujtikos', 'ujtelek'],
 'u': ['ujunglero', 'ujudvar', 'ujukata', 'ujuxte', 'ujung'],
 'v': ['ujvarfalva'],
 'w': ["ujwang'a", 'ujwadu']}
