
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hv = {'_': ['hv-016', 'hv71'],
 'a': ['hvalfjardarstrandarhreppur',
       'hvassaleitisskoli',
       'hvannadalshnjukur',
       'hvalfjardarsveit',
       'hvalbiartunnilin',
       'hvare-khshaeta',
       'hvalbiareidi',
       'hvammstangi',
       'hvalfjordur',
       'hvassaleiti',
       'hvardiiske',
       'hvarf/heim',
       'hvaletinci',
       'hvannasund',
       'hvaltorvet',
       'hvalsmoen',
       'hvalbakur',
       'hvanneyri',
       'hvalpsund',
       'hvaldimir',
       'hvalvatn',
       'hvalimir',
       'hvalstad',
       'hvalsey',
       'hvasser',
       'hvalvik',
       'hvalso',
       'hvaler',
       'hvalba',
       'hvar',
       'hvam',
       'hvat',
       'hva'],
 'b': ['hvb'],
 'c': ['hvcn1', 'hvcc', 'hvc'],
 'd': ['hvd'],
 'e': ['hvezdonovice',
       'hvervenbukta',
       'hveravellir',
       'hvezdonice',
       'hveragerdi',
       'hvergelmir',
       'hvezdlice',
       'hverfjall',
       'hvedekorn',
       'hvelreki',
       'hvepsen',
       'hveding',
       'hvezda'],
 'f': ['hvf'],
 'g': ['hvgc-1', 'hvg'],
 'h': ['hvhs'],
 'i': ['hviezdoslavov',
       'hvittingfoss',
       'hvistendahl',
       'hviezdoslav',
       'hvitserkur',
       'hvitebjorn',
       'hvitarholt',
       'hvitarvatn',
       'hvissinge',
       'hvitavatn',
       'hvilsager',
       'hvittrask',
       'hvidebaek',
       'hvitanes',
       'hvidsten',
       'hvidovre',
       'hvizdets',
       'hvitsten',
       'hvitserk',
       'hvidore',
       'hvide',
       'hviid',
       'hvita',
       'hvizd'],
 'j': ['hvj'],
 'k': ['hvk'],
 'l': ['hvlan', 'hvl'],
 'm': ['hvmn', 'hvm'],
 'n': ['hvnnibvl', 'hvn'],
 'o': ['hvolsvollur',
       'hvostyane',
       'hvozdnica',
       'hvozdnice',
       'hvozdany',
       'hvorvarp',
       'hvorslev',
       'hvoslef',
       'hvozdec',
       'hvozdna',
       'hvosno',
       'hvozd',
       'hvob',
       'hvo'],
 'p': ['hvp'],
 'r': ['hvr'],
 's': ['hvsc', 'hvs'],
 't': ['hvtr', 'hvt'],
 'x': ['hvx'],
 'y': ['hvy1', 'hvy']}
