
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fj = {'_': ['fj_management', 'fj_abm'],
 'a': ['fjalar_thorgeirsson',
       'fjaerland_tunnel',
       'fjardsjomala_aif',
       'fjalkinge_church',
       'fjaerland_church',
       'fjallnas_castle',
       'fjalar_finnas',
       'fjaera_chapel',
       'fjare_hundred',
       'fjaere_church',
       'fjaera_tunnel',
       'fjaras_kyrkby'],
 'b': ['fjb'],
 'c': ['fjca', 'fjc'],
 'd': ['fjd'],
 'e': ['fjerritslev_municipality',
       'fjellbergella_tuxeni',
       'fjellimellom_valley',
       'fjellstrand,_norway',
       'fjends_municipality',
       'fjellgardane_church',
       'fjellhamar_station',
       'fjelberg_church',
       'fjelldal_chapel',
       'fjell_fortress',
       'fjellhamar_fk',
       'fjelie_church',
       'fjell_church',
       'fjell_skole',
       'fjep_bonson'],
 'g': ['fjg_ram'],
 'i': ['fji'],
 'm': ['fjm'],
 'o': ['fjord1_fylkesbaatane',
       'fjortende_julibreen',
       'fjordia_chriskaugei',
       'fjordenes_tidende',
       'fjoloy_lighthouse',
       'fjordia_capensis',
       'fjodor_ljubovski',
       'fjordia_insolita',
       'fjordgard_chapel',
       'fjortoft_church',
       'fjordia_lineata',
       'fjodor_lishajko',
       'fjotland_church',
       'fjorden_cowboys',
       'fjolla_kelmendi',
       'fjodor_koltsin',
       'fjorda_shabani',
       'fjordia_browni',
       'fjoralb_deliaj',
       'fjodor_elesin',
       'fjoart_jonuzi',
       'fjord,_norway',
       'fjorton_suger',
       'fjodor_xhafa',
       'fjolla_shala',
       'fjogur_piano',
       'fjord_horse',
       'fjord_city',
       'fjord1_mrf',
       'fjord_line'],
 'r': ['fjr'],
 's': ['fjs'],
 'u': ['fjut_uav'],
 'x': ['fjx1']}
