
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vs = {'_': ['vs-plus',
       'vs-1d7',
       'vs-931',
       'vs-22',
       'vs-15',
       'vs-37',
       'vs-41',
       'vs-24',
       'vs-38',
       'vs-33',
       'vs-35',
       'vs-30',
       'vs-32',
       'vs-40',
       'vs-29',
       'vs-23',
       'vs-25',
       'vs-31',
       'vs/9',
       'vs1'],
 'a': ['vsauce', 'vsan', 'vsa'],
 'b': ['vsb-30', 'vsb-tv', 'vsb'],
 'c': ['vscii', 'vsco', 'vscf', 'vsc'],
 'd': ['vsdocman', 'vsd'],
 'e': ['vsekhsvyatskoye',
       'vsevolodo-vilva',
       'vsevolozhsky',
       'vsemirskaya',
       'vsevolozhsk',
       'vsechovice',
       'vsemyslice',
       'vsechlapy',
       'vseradice',
       'vsevobuch',
       'vselibice',
       'vsestary',
       'vsestudy',
       'vsesulov',
       'vseti.by',
       'vsepadly',
       'vseradov',
       'vsevolod',
       'vsetaty',
       'vseruby',
       'vselyub',
       'vsevily',
       'vsenory',
       'vsekary',
       'vsehrdy',
       'vsenice',
       'vsejany',
       'vsesvit',
       'vsemina',
       'vsetin',
       'vsen',
       'vsel',
       'vsee',
       'vse'],
 'f': ['vsfighting', 'vsftpd', 'vsfs', 'vsf'],
 'g': ['vsg'],
 'h': ['vshchizh', 'vshojo', 'vsh'],
 'i': ['vsig2', 'vsig8', 'vsig1', 'vside', 'vsim', 'vsip', 'vsi'],
 'k': ['vskhson', 'vsk-94', 'vsk'],
 'l': ['vsl'],
 'm': ['vsmpo-avisma', 'vsmu', 'vsm'],
 'n': ['vsn'],
 'o': ['vsop', 'vsoe', 'vso'],
 'p': ['vspeech', 'vsp'],
 'r': ['vsrp', 'vsr'],
 's': ['vss-unes-usu', 'vsse', 'vss'],
 't': ['vstrechny', 'vstis', 'vsta', 'vst'],
 'u': ['vsun', 'vsu'],
 'v': ['vsv'],
 'w': ['vsw'],
 'x': ['vsx2', 'vsx1', 'vsx']}
