
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vt = {'_': ['vt-patrol',
       'vt-line',
       'vt1000',
       'vt-158',
       'vt-10',
       'vt-86',
       'vt320',
       'vt180',
       'vt1.5',
       'vt420',
       'vt-22',
       'vt-21',
       'vt520',
       'vt-27',
       'vt100',
       'vt-28',
       'vt220',
       'vt-8',
       'vt-6',
       'vt05',
       'vt58',
       'vt-4',
       'vt52',
       'vt11',
       'vt-9'],
 'a': ['vtackovce', 'vtape', 'vtap', 'vtac', 'vta1', 'vta'],
 'c': ['vtcn1', 'vtcc', 'vtc'],
 'd': ['vtdigger', 'vtd-xml', 'vtdk'],
 'e': ['vtelno', 'vtech', 'vten', 'vtec', 'vte'],
 'g': ['vtg'],
 'i': ['vti1a', 'vti1b', 'vti'],
 'k': ['vtk'],
 'l': ['vtls', 'vtl'],
 'm': ['vtml', 'vtm'],
 'n': ['vtnz'],
 'o': ['vtoryye', 'vtorovo', 'vtorov', 'vtol', 'vto'],
 'p': ['vtpr'],
 's': ['vts1', 'vts'],
 't': ['vttest'],
 'u': ['vtuber', 'vtune', 'vtun'],
 'v': ['vtv-gujarati',
       'vtv7',
       'vtvl',
       'vtv3',
       'vtv2',
       'vtv6',
       'vtv1',
       'vtv5',
       'vtv4',
       'vtv'],
 'w': ['vtwm'],
 'x': ['vtx'],
 'y': ['vty'],
 'z': ['vtz']}
