
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nf = {'_': ['nf-kb', 'nf3', 'nf2', 'nf1'],
 'a': ['nfatc1',
       'nfatc4',
       'nfatc3',
       'nfatc2',
       'nfasc',
       'nfat5',
       'nfam1',
       'nfat',
       'nfas',
       'nfaa',
       'nfa'],
 'b': ['nfbsk', 'nfb'],
 'c': ['nfc-wi', 'nfcu', 'nfct', 'nfc'],
 'd': ['nfda', 'nfdc', 'nfd'],
 'e': ['nfernelson', 'nfe2l1', 'nfe2l2', 'nfe2l3', 'nfepp', 'nfe2', 'nfe'],
 'f': ['nfff', 'nffa', 'nff'],
 'g': ['nfg'],
 'h': ['nfhs'],
 'i': ['nfisseh',
       'nfifa',
       'nfil3',
       'nfix',
       'nfia',
       'nfib',
       'nfiw',
       'nfic',
       'nfi'],
 'k': ['nfkbil1',
       'nfkbie',
       'nfkbiz',
       'nfkbid',
       'nfkbib',
       'nfkb2',
       'nfkb1',
       'nfk'],
 'l': ['nflvr.com', 'nfls'],
 'n': ['nfn'],
 'o': ['nforce2', 'nforce4', 'nforce3', 'nforce', 'nfon', 'nfo'],
 'p': ['nfpa', 'nfpw', 'nfps', 'nfp'],
 'r': ['nfr-90', 'nfrkb', 'nfra', 'nfr'],
 's': ['nfs1', 'nfsr', 'nfsm', 'nfsu', 'nfs'],
 't': ['nftables', 'nftbooks', 'nfty', 'nftc', 'nfta'],
 'u': ['nfu'],
 'v': ['nfv'],
 'x': ['nfx1'],
 'y': ['nfyb', 'nfya', 'nfyc'],
 'z': ['nfz']}
