
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nb = {'_': ['nb.bbvci', 'nb-fi'],
 'a': ['nbac', 'nbaf', 'nbar', 'nbat', 'nbas', 'nbaa'],
 'b': ['nbbl', 'nbbj', 'nbbi', 'nbbc', 'nbb'],
 'c': ['nbcuniversal', 'nbcnews.com', 'nbcsn', 'nbca', 'nbcc', 'nbci', 'nbc'],
 'd': ['nbd-tma', 'nbd'],
 'e': ['nbeal2', 'nbeal1', 'nbeika', 'nbench', 'nbe'],
 'f': ['nbfa', 'nbfl', 'nbf'],
 'g': ['nbg'],
 'h': ['nbhs', 'nbhd', 'nbh'],
 'i': ['nbia', 'nbic', 'nbi'],
 'k': ['nbk'],
 'l': ['nblxnba', 'nbl1', 'nbl'],
 'm': ['nbmr-1', 'nbmr-3', 'nbm'],
 'n': ['nbname', 'nbn'],
 'o': ['nbome-mescaline', 'nbo'],
 'p': ['nbpf15',
       'nbpf19',
       'nbpf10',
       'nbpf1',
       'nbpf3',
       'nbpp',
       'nbpa',
       'nbpf',
       'nbpo',
       'nbps',
       'nbp'],
 'q': ['nbqx'],
 'r': ['nbr1', 'nbr2', 'nbr'],
 's': ['nbscett', 'nbs'],
 't': ['nbtel', 'nbti', 'nbtc', 'nbt'],
 'u': ['nbu-prisen', 'nbump', 'nbuf', 'nbu'],
 'v': ['nbv'],
 'w': ['nbw'],
 'x': ['nbx'],
 'y': ['nby']}
