
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cv = {'_': ['cv_torrelavega',
       'cv_ciutadella',
       'cv_alcobendas',
       'cv4_technique',
       'cv_barcelona',
       'cv_tenerife',
       'cv_stephen',
       'cv_logrono',
       'cv_almeria',
       'cv_aguere',
       'cv_villas',
       'cv_xativa',
       'cv_teruel',
       'cv_portol',
       'cv_haro'],
 'a': ['cvaljina',
       'cvasnita',
       'cvarici',
       'cva-01',
       'cvarci',
       'cvax',
       'cvac',
       'cvar',
       'cva'],
 'b': ['cvb'],
 'c': ['cvcc', 'cvca', 'cvc'],
 'd': ['cvd'],
 'e': ['cvetkovic-macek_agreement',
       'cvetkovic,_jastrebarsko',
       'cvetan_grozdanov',
       'cvetan_churlinov',
       'cveta_majtanovic',
       'cvetanka_petrova',
       'cvetak_zanovetak',
       'cvetana_dekleva',
       'cvetkova_pijaca',
       'cvetkovic_brdo',
       'cvetko_rajovic',
       'cven,_ljutomer',
       'cveto_pretnar',
       'cvetka_ahlin',
       'cvetka_lipus',
       'cveto_pavcic',
       'cvetnic_brdo',
       'cvetka_bevc',
       'cvetni_trg'],
 'f': ['cvf'],
 'g': ['cvg'],
 'h': ['cvhs', 'cvh'],
 'i': ['cvijetin_blagojevic',
       'cvijetin_mijatovic',
       'cvitovic,_croatia',
       'cvijan_milosevic',
       'cvijanovic_brdo',
       'cvijeta_zuzoric',
       'cvitan_spuzevic',
       'cvijan_saric',
       'cvitan_galic',
       'cvitko_bilic'],
 'j': ['cvjetkovic_ca-65', 'cvjetkovic_ca-61', 'cvjetko_popovic'],
 'k': ['cvk'],
 'l': ['cvlt_nation'],
 'm': ['cvm_television'],
 'n': ['cvnh_domain'],
 'o': ['cvoter', 'cvo'],
 'p': ['cvps', 'cvp'],
 'q': ['cvqo'],
 'r': ['cvr_partners'],
 's': ['cvs_pharmacy', 'cvs_caremark', 'cvs_ferrari', 'cvs_health', 'cvso_30'],
 't': ['cvt2_veltro', 'cvt4_strale', 'cvt1_zigolo', 'cvt_m-200', 'cvt_m-300'],
 'u': ['cvusd', 'cvu'],
 'v': ['cvv-4_pellicano', 'cvv-6_canguro'],
 'w': ['cvw2'],
 'x': ['cvx'],
 'z': ['cvz']}
