
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lj = {'_': ['lj-001'],
 'a': ['ljajkovici',
       'ljanselva',
       'ljania',
       'ljanik',
       'ljabru',
       'ljajic',
       'ljan'],
 'e': ['ljepojevici',
       'ljestansko',
       'ljesovina',
       'ljepovici',
       'ljeljenca',
       'ljepunice',
       'ljesljani',
       'ljeskovik',
       'ljesevici',
       'ljeskovac',
       'ljetinic',
       'ljetovik',
       'ljesnica',
       'ljenobud',
       'ljekova',
       'ljevaja',
       'ljesevo',
       'ljes',
       'ljeb',
       'lje'],
 'f': ['ljf'],
 'i': ['ljiljance', 'ljiljani', 'ljiljana', 'ljiljan', 'ljig'],
 'j': ['ljj'],
 'm': ['ljm'],
 'n': ['ljn'],
 'o': ['ljotebotnberget',
       'ljosabelgen',
       'ljosufjoll',
       'ljosland',
       'ljoljici',
       'ljotolfr',
       'ljosa'],
 'p': ['ljp'],
 's': ['ljs'],
 'u': ['ljubljana-zagreb-beograd',
       'ljubina-poturovici',
       'ljusfallshammar',
       'ljubijankici',
       'ljubljanica',
       'ljungbyholm',
       'ljubostinja',
       'ljubomislje',
       'ljubinkovic',
       'ljubatovici',
       'ljubatovica',
       'ljubezen.si',
       'ljubibratic',
       'ljunghusen',
       'ljubescica',
       'ljudmilena',
       'ljungkvist',
       'ljutovnica',
       'ljungskile',
       'ljubicevac',
       'ljubanista',
       'ljungstrom',
       'ljubojevic',
       'ljungqvist',
       'ljungbyhed',
       'ljungaverk',
       'ljubovcici',
       'ljungsarp',
       'ljuskrona',
       'ljubetovo',
       'ljubovija',
       'ljubisnja',
       'ljutenica',
       'ljudemisl',
       'ljungdahl',
       'ljubuncic',
       'ljuberada',
       'ljubacevo',
       'ljunggren',
       'ljusnedal',
       'ljungberg',
       'ljubotici',
       'ljubljana',
       'ljungsbro',
       'ljubgojna',
       'ljubstava',
       'ljubnica',
       'ljubisav',
       'ljubicno',
       'ljubnici',
       'ljubicic',
       'ljustero',
       'ljubinci',
       'ljubovic',
       'ljubinic',
       'ljutomer',
       'ljubanje',
       'ljutomir',
       'ljudevit',
       'ljubunci',
       'ljubojno',
       'ljubanci',
       'ljubuski',
       'ljubinje',
       'ljubecna',
       'ljunghia',
       'ljuljaci',
       'ljuboten',
       'ljubija',
       'ljukovo',
       'ljupten',
       'ljubine',
       'ljupina',
       'ljubusa',
       'ljusdal',
       'ljubica',
       'ljutaje',
       'ljusnan',
       'ljubace',
       'ljungan',
       'ljutice',
       'ljusina',
       'ljugarn',
       'ljubisa',
       'ljungby',
       'ljubnic',
       'ljusici',
       'ljubina',
       'ljubovo',
       'ljubuca',
       'ljubavi',
       'ljubinj',
       'ljubava',
       'ljutici',
       'ljutovo',
       'ljubin',
       'ljutic',
       'ljusne',
       'ljubac',
       'ljubav',
       'ljunga',
       'ljupka',
       'ljubic',
       'ljubis',
       'ljutez',
       'ljubi',
       'ljusa',
       'ljuba',
       'ljuce',
       'ljubo',
       'ljung'],
 'y': ['ljy-netzer']}
